### ISSUE TITLE
Trouble excluding/matching hidden files in Linux

### ISSUE THREAD

**Issue by QantumEntangled** [restic/restic#1001]
#### OS
Zorin (Ubuntu 16.04.4)
>`Linux version 4.8.0-53-generic (buildd@lgw01-56) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017`
#### Restic Version
>restic 0.6.1
>compiled with go1.8.3 on linux/amd64
#### How did you start restic exactly?
>[Unzip .bz2 file]
>`mv restic_0.6.1_linux_amd64 restic`
>`chmod 755 ./restic`
>`sudo cp ./restic /bin/restic`

run with `restic`
Saved to `/home/user/Backup`

note: I was unable to find anywhere in the documentation that talked about installing restic on Ubuntu/Debian systems, but the binary runs fine afaik so I dropped it in my bin so I could run it from bash. It's not elegant or best practice but it works for now.

## Problem
I'm trying to backup my home directory, but I don't care about the extra 10+ GB worth of hidden files that are also in there, I just want my visible directories (but I'll add more in the future so don't want to explicitly specify).

So I tried running this:
`restic -r /home/user/Backup/ backup ~/ --tag HomeDir --exclude=Backup --exclude=.* --exclude-file=.* --exclude=env --exclude=Arduino --exclude=vmware --exclude=Steam`

But I keep getting this error:
>`error reading exclude patterns: open .*: no such file or directory`

I've tried a `.?*`, `~/.*`, and `~/.?*` but they throw the same error. What am I missing here? Is there a way to match anything that starts with a `.` followed by any sequence of non-Separator characters? Reading through https://golang.org/pkg/path/filepath/#Match it didn't look like I need to escape out the `.` character.

**Comment by fd0** [comment]
Hm, interesting. The option `--exclude-file=.*` is definitely wrong: it instructs restic to read the names of things to exclude from a file called `.*` (a dot and an asterisk), which does not exist. This is what restic complains about.

Apart from that your command-line looks good, it should do what you want:
```
$ restic -r /home/user/Backup/ backup ~/ --tag HomeDir --exclude=Backup --exclude=.* --exclude=env --exclude=Arduino --exclude=vmware --exclude=Steam
```

You can also create a [debug logfile](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs) and grep for `excluded by a filter`. Please be aware that it may contain sensitive data such as file and directory names.

**Comment by fd0** [comment]
I'm going to close this issue for now, please report back if it doesn't work as described. Thanks!

**Comment by giordy** [comment]
from my tests it seems that the proper way to exclude hidden files and directories should be this one 

> --exclude /home/user/\..+

and adapting it to the example of this issue

> $ restic -r /home/user/Backup/ backup ~/ --tag HomeDir --exclude=Backup --exclude=\..+ --exclude=env --exclude=Arduino --exclude=vmware --exclude=Steam

you can [test this here](https://regex101.com/r/qMj88l/1)

**Comment by fd0** [comment]
I'm sorry, but this is not correct: restic does not use regular expressions for backup, but uses globbing instead. Using `--exclude /home/user/\..+` will exclude the literal file `\..+` in your home directory.

If you want to exclude all files starting with a dot, use `--exclude '.*'`, if you want to exclude all files starting with a dot in your home directory (and include them in other directories), use `--exclude '/home/user/.*'`.

**Comment by giordy** [comment]
@fd0 you're right, I was having wrong results because I was missing the quotes '
I made more thorough tests and I confirm what you're stating, my solution was wrong.
Thanks for the help!

**Comment by QantumEntangled** [comment]
I am unable to find documentation on globbing. Is there somewhere I can reference to find out how globbing works?

Sorry if this is off topic. I was unaware that there were other standards than regex.

**Comment by fd0** [comment]
There's a short paragraph in the manual, here: https://restic.readthedocs.io/en/latest/040_backup.html#backing-up

It references the documentation of the library we're using: https://golang.org/pkg/path/filepath/#Match
