### ISSUE TITLE
Cannot find docs for the exclude file syntax

### ISSUE THREAD

**Issue by LaszloHont** [restic/restic#1005]
I can't seem to find any docs on how the exclude file syntax is parsed.

i.e. does it support wildcards? regex? how does it differentiate between files and directories? are path prefixes needed? where from (cwd/or root?)?

Some examples:
```
.qiv-trash (directory that could be anywhere on the filesystem)
.DS_Store
lost+found/
._*
desktop.ini
Thumbs.db (file that could be anywhere on the filesystem)
.Trash-* (the asterisk could be any number, is it needed?)
.tmp$ (file ending in .tmp)
~$ (file ending in a tilde)
~/.cache/ (cache directory in user home dir, using tilde syntax)
/full/path/to/directory/.syncthing/index*
```

**Comment by fwilhe** [comment]
Hi, have you seen

> Patterns use filepath.Glob internally, see filepath.Match for syntax. Additionally ** excludes arbitrary subdirectories. Environment-variables in exclude-files are expanded with os.ExpandEnv.

in https://github.com/restic/restic/blob/master/doc/manual.rst?

I think this should answer your questions.

**Comment by LaszloHont** [comment]
I went to the documentation at https://restic.readthedocs.io/en/latest/manual.html and searched for exclude, where it unfortunately doesn't include any common examples (or a reference to the other documentation at manual.rst) :/

**Comment by LaszloHont** [comment]
I read the golang doc and I think the end-user (me!) isn't going to know what restic is comparing an exclude to internally - is it the full path (e.g. /home/me/blah) or a path from the repository root (/blah or blah), or relative to the cwd (me/blah when I am at /home)?

**Comment by fd0** [comment]
Thanks for raising this issue, I think you have a valid point. The manual should explain the exclude filters without referencing godoc.org, and more examples are necessary.

**Comment by fd0** [comment]
To answer a few of your questions already:
 * The patterns are evaluated relative to the current working directory
 * Relative paths/patterns will match anywhere below the path to be saved
 * At the moment there's no way to distinguish between a file and a directory, so `--exclude foo` will exclude any files and directories named `foo`. The same goes for `--exclude foo/`.

**Comment by LaszloHont** [comment]
Thanks @fd0 

So with "current directory", you don't mean the directory I was in when I launched the backup, but the directory that restic is currently in examining the files (apart from excludes that begin with a slash). Got it.

The behaviour for files and directories is slightly unexpected, I would have expected --exclude foo/ to backup the directory but not the contents, whereas --exclude foo to backup neither. Not sure why, from rsync I guess.

My examples missed an important one: spaces! I guess I need to escape those and shell metacharacters with a backslash.

I ended up copying lots of these ones: https://gist.github.com/jult/e2eaedad6b9e29d95977fea0ddffae7d

Are comments allowed in the excludes file?

**Comment by fd0** [comment]
Ah, I'm afraid that's still not completely correct. I'll describe how restic evaluates the exclude patterns. Let's suppose that restic is run by a user in his home directory (`/home/user`) like this:
```
$ restic backup --exclude='*.bak' --exclude='/home/user/secret' --exclude='extra' ~
```

Then restic will see the following command line arguments (after expansion by the shell):
```
["restic", "backup", "--exclude='*.bak'", "--exclude='/home/user/secret'", "--exclude='extra'", "/home/user"]
```

Then, it starts traversing `/home/user`. The following list describes what happens when the named file/dir is seen. restic always tests the complete path against the patterns:
 * file `/home/user/foo.bak`: The pattern `*.bak` matches and the file is not saved. The pattern is not absolute so it matches everywhere for all files ending in `.bak`.
 * dir `/home/user/secret`: The absolute pattern `/home/user/secret` matches, so the dir is not saved and not traversed
 * dir `/home/user/work/extra`: The pattern `extra` matches, the dir is not saved.

I hope that this is a bit clearer now, I'll add a section to the manual describing the process. The key take-away point is that the patterns are evaluated against the full path of the files during backup. So if you want to match a single directory, use the complete path, otherwise it may match several times somewhere.

Any further questions? :)

**Comment by LaszloHont** [comment]
I have further questions, and I very much appreciate the time you are taking to answer them. It's really one question about automagic anchoring of patterns. I think I can guess the answer (we rely on the absolute path being fairly unique and giving us the behaviour we want), but it's best to ask and be sure.

Would the absolute pattern `/home/user/secret` match `/home/user/secret2`? (What if you don't want it to?)
Would the absolute pattern `/home/user/secret` match `/home/user/somemount/home/user/secret`?

**Comment by fd0** [comment]
In both cases: No, the pattern won't match.

**Comment by LaszloHont** [comment]
Why is that?

**Comment by fd0** [comment]
The matching code there is modeled after what a shell would do: If you'd ask yourself, if the file `/home/user/secret2` exists, what would `ls /home/user/secret` print (provided the file `secret` does not exist)?

In more formal terms: If the pattern starts with a `/` it is absolute and the pattern must match at the beginning of the string under test, so pattern `/home/user/secret` does not match `/home/user/somemount[...]`: The pattern is not a prefix of the string.

**Comment by fd0** [comment]
All these examples should be document in the manual I think.

**Comment by LaszloHont** [comment]
Gotcha. Thanks.

**Comment by pkpowell** [comment]
Are negative excludes possible ala .gitignore?
say I want to exclude all content in directories named .meteor except for the nested dir .meteor/local/db, could I do this?

/etc/restic/excludes:
````
.meteor/
!.meteor/local/db
````
`restic backup exclude-file=/etc/restic/excludes`

**Comment by fd0** [comment]
No, that is not implemented yet.

**Comment by fd0** [comment]
Documenting include/exclude examples is tracked in #396, I'm closing this issue here.

**Comment by tomwaldnz** [comment]
There's a lot of examples above, but it's still not clear how to exclude folders specified as full path names.

For example, say I'm backing up c:\documents\financials and I want to exclude all files in c:\documents\financials\temporary, how do I do that?

I've tried the following and a few more variations, but the contents of temporary are still included in the backup.

```
restic_0.9.1_windows_amd64.exe --exclude='temporary' -r C:\repo backup c:\documents\financials
restic_0.9.1_windows_amd64.exe --excludefile='temporary' -r C:\repo backup c:\documents\financials
restic_0.9.1_windows_amd64.exe --exclude='c:\documents\financials\temporary' -r C:\repo backup 
restic_0.9.1_windows_amd64.exe --exclude='c:\documents\financials\temporary\*' -r C:\repo backup c:\documents\financials
```

**Comment by karthikpaidi** [comment]
@fd0 i was trying exclude paths like below jobs/**/jobs/**/builds/**/archive to exclude archive dir from all directories would that work

**Comment by OvaisTariq95** [comment]
how can i exclude multiple files with with one flage?
i.e 
--exclude=foo/bar/t.txt foor/bar2/1.txt

**Comment by MichaelEischer** [comment]
You have to specify the excludes as `--exclude foo/bar/t.txt --exclude foor/bar2/1.txt` Unless `foo/bar/t.txt foor/bar2/1.txt` is a single filename. Or use an exclude file as described in https://restic.readthedocs.io/en/stable/040_backup.html#excluding-files
