### ISSUE TITLE
Cannot find docs for b2 backend

### ISSUE THREAD

**Issue by LaszloHont** [restic/restic#1006]
I came to restic because of the amazing feature set and the support for b2, but I'm having trouble finding the docs for b2 - I found s3 under the latest documentation at https://restic.readthedocs.io/en/latest/tutorials.html

**Comment by LaszloHont** [comment]
Aha I found https://github.com/restic/restic/pull/978/commits/122462b9b1c339419fa3e279f9716f0af1fd7df2

**Comment by LaszloHont** [comment]
Your docs talk about an account id and an account key, but b2 has an account id and an *application* key.

**Comment by fd0** [comment]
We have a section in the manual that describes the setup process for the different backends, did you discover that yet? https://restic.readthedocs.io/en/latest/manual.html#backblaze-b2

**Comment by LaszloHont** [comment]
I found that section, but was confused by it not being in the tutorial section. Thanks.
