### ISSUE TITLE
panic: trying to decrypt invalid data: ciphertext too small

### ISSUE THREAD

**Issue by skirmish** [restic/restic#1009]
## Output of `restic version`

restic 0.6.1
compiled with go1.8.3 on windows/amd64

## How did you start restic exactly? (Include the complete command line)

`d:\restic\restic.exe -r d:\restic\backup rebuild-index`

## What backend/server/service did you use?

None

## Expected behavior

Be able to rebuild the index.

## Actual behavior

```
C:\>d:\restic\restic.exe -r d:\restic\backup rebuild-index
enter password for repository:
counting files in repo
panic: trying to decrypt invalid data: ciphertext too small

goroutine 40 [running]:
restic/crypto.Decrypt(0xc0420e20f0, 0xb78100, 0x0, 0x0, 0xb78100, 0x0, 0x0, 0x0, 0xc0441b50e0, 0xc042027000)
        src/restic/crypto/crypto.go:280 +0x662
restic/pack.List(0xc0420e20f0, 0xb26fe0, 0xc044185e00, 0x400000, 0x40, 0x400000, 0x0, 0x0, 0xc0421ea140)
        src/restic/pack/pack.go:228 +0xbf
restic/repository.(*Repository).ListPack(0xc042038de0, 0x3c7228555392a300, 0x63c3ac493f7c55c, 0xf66e7ddb526bc869, 0xe6fd42ae9401139e, 0x2, 0x2, 0xc0422dffb0, 0x2, 0x2, ...)
        src/restic/repository/repository.go:473 +0x17c
restic/list.AllPacks.func1(0x8cca20, 0xc0422d30c0, 0x0, 0x0, 0x0, 0x0, 0xc042230060, 0x8e2440, 0xc0421ea140, 0x0, ...)
        src/restic/list/list.go:42 +0xe7
restic/worker.(*Pool).runWorker(0xc0421ebe00, 0x7)
        src/restic/worker/pool.go:86 +0x206
created by restic/worker.New
        src/restic/worker/pool.go:40 +0x181
```

## Steps to reproduce the behavior

Ran a backup operation (in windows) to an external USB plugged drive, part way through, the USB cable 'apparently' became unplugged. Upon reconnecting the drive, running a 'restic check' prompted to run rebuild-index. This didn't go well.

## Do you have any idea what may have caused this?

See steps to reproduce.

**Comment by fd0** [comment]
I'll have a look, thanks for the report!

**Comment by fd0** [comment]
I'll have a look, thanks for reporting it. Could you please create a [debug logfile](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)? Please be aware that it may contain sensitive data such as file and directory names.

**Comment by skirmish** [comment]
Sure, here you go;
[debug.txt](https://github.com/restic/restic/files/1061943/debug.txt)

Turns out there is a zero byte length file in the data folder. There might be more, would deleting it be an option?

thanks

**Comment by fd0** [comment]
Thank you very much, I'll have a look. I think you can safely delete all empty files, restic never leaves empty files behind. That will likely also fix your problem. Please report back!

**Comment by skirmish** [comment]
Ah, cool, but unfortunately it didn't fix it, attached is the latest debug.
[debug.txt](https://github.com/restic/restic/files/1061985/debug.txt)

**Comment by fd0** [comment]
Could you paste the stacktrace that matches the debug

**Comment by fd0** [comment]
Ah, don't bother, I can reproduce it. There's a truncated file somewhere in your repo.

**Comment by skirmish** [comment]
d:\restic\restic -r d:\restic\backup rebuild-index
debug log file debug.log
debug enabled
enter password for repository:
counting files in repo
panic: trying to decrypt invalid data: ciphertext too small

goroutine 51 [running]:
restic/crypto.Decrypt(0xc0420de320, 0xd071d8, 0x0, 0x0, 0xd071d8, 0x0, 0x0, 0x0, 0xc04202e800, 0x5d)
        src/restic/crypto/crypto.go:280 +0x662
restic/pack.List(0xc0420de320, 0xcaec60, 0xc0441ecf30, 0x400000, 0x4, 0xc0441f65c0, 0x40, 0x400000, 0x0)
        src/restic/pack/pack.go:228 +0xbf
restic/repository.(*Repository).ListPack(0xc0420d09c0, 0xcb3a20, 0xc04203e300, 0x3c7228555392a300, 0x63c3ac493f7c55c, 0xf66e7ddb526bc869, 0xe6fd42ae9401139e, 0xc042280420, 0x6, 0x6, ...)
        src/restic/repository/repository.go:474 +0x199
restic/list.AllPacks.func1(0xcb3a20, 0xc04203e300, 0x9cb280, 0xc042342900, 0x0, 0x0, 0x0, 0x0, 0x9e7080, 0xc04200c7c0, ...)
        src/restic/list/list.go:43 +0x10a
restic/worker.(*Pool).runWorker(0xc042110000, 0xcb3a20, 0xc04203e300, 0x9)
        src/restic/worker/pool.go:86 +0x253
created by restic/worker.New
        src/restic/worker/pool.go:40 +0x15d

**Comment by fd0** [comment]
Could you please give the code in the branch `fix-1009` (PR #1011)

**Comment by skirmish** [comment]
Ergh, still no good;

>restic version
debug log file debug.txt
debug enabled
restic 0.6.1 (v0.6.1-32-g1aab123-dirty)
compiled with go1.8 on windows/amd64

>restic -r d:\restic\backup rebuild-index
debug log file debug.txt
debug enabled
enter password for repository:
counting files in repo
panic: trying to decrypt invalid data: ciphertext too small

goroutine 47 [running]:
restic/crypto.Decrypt(0xc0420e0370, 0xd07220, 0x0, 0x0, 0xd07220, 0x0, 0x0, 0x0, 0xc04216a800, 0x5d)
        src/restic/crypto/crypto.go:280 +0x662
restic/pack.List(0xc0420e0370, 0xcaec60, 0xc0442e4090, 0x400000, 0x4, 0xc04203fd40, 0x40, 0x400000, 0x0)
        src/restic/pack/pack.go:254 +0xbf
restic/repository.(*Repository).ListPack(0xc0420d69c0, 0xcb3a60, 0xc04203e8c0, 0x3c7228555392a300, 0x63c3ac493f7c55c, 0xf66e7ddb526bc869, 0xe6fd42ae9401139e, 0xc0442b0160, 0x6, 0x6, ...)
        src/restic/repository/repository.go:474 +0x199
restic/list.AllPacks.func1(0xcb3a60, 0xc04203e8c0, 0x9cb660, 0xc044273120, 0x0, 0x0, 0x0, 0x0, 0x9e7460, 0xc0420d9680, ...)
        src/restic/list/list.go:43 +0x10a
restic/worker.(*Pool).runWorker(0xc042110060, 0xcb3a60, 0xc04203e8c0, 0x9)
        src/restic/worker/pool.go:86 +0x253
created by restic/worker.New
        src/restic/worker/pool.go:40 +0x15d

[debug.txt](https://github.com/restic/restic/files/1062065/debug.txt)

**Comment by fd0** [comment]
Huh, nice! At least two bugs already :)

**Comment by skirmish** [comment]
Lol, at some point I'm going to do a 'restic purge', I'm guessing that might find another ;)

**Comment by fd0** [comment]
Let's tackle this first. I've pushed another commit in the branch `fix-1009`, please retry!

**Comment by skirmish** [comment]
Looking good, been running 10 mins and no panics yet, I'll update when it's done, it'll be a while

**Comment by fd0** [comment]
Ok, at the moment the faulty files aren't deleted, but reported each time you run `rebuild-index`, `check` or `prune`, so you'll need to delete them manually. I'll build something to automatically delete them later.

**Comment by skirmish** [comment]
Yeah, it got to the end finally without panics:

>restic -r d:\restic\backup rebuild-index
debug log file debug.txt
debug enabled
enter password for repository:
counting files in repo
unable to list pack 00a39253: readHeader: header length is zero
unable to list pack 09fb8b79: readHeader: header length is zero
unable to list pack 0c618392: readHeader: header length is zero
unable to list pack 100c3798: readHeader: header length is zero
unable to list pack 270ae21a: readHeader: header length is zero
unable to list pack 2fd79209: readHeader: header length is zero
unable to list pack 4b2df316: readHeader: header length is zero
unable to list pack 4dd0ea7c: readHeader: header length is zero
unable to list pack 508c6b8b: readHeader: header length is zero
unable to list pack 5c2555ba: readHeader: header length is zero
unable to list pack 614fde51: readHeader: header length is zero
unable to list pack 71bb41f6: readHeader: header length is zero
unable to list pack 84e78729: readHeader: header length is zero
unable to list pack 861c02a6: readHeader: header length is zero
unable to list pack 99e186fc: readHeader: header length is zero
unable to list pack 9ae278bd: readHeader: header length is invalid
unable to list pack bd0f0f65: readHeader: header length is zero
unable to list pack bf5aafcb: readHeader: header length is zero
unable to list pack ca3af343: readHeader: header length is zero
unable to list pack d35663a7: readHeader: header length is zero
unable to list pack f298fb2c: readHeader: header length is invalid
[1:27:56] 100.00%  60608 / 60608 packs
finding old index files
saved new index as 8eb509bd
remove 114 old index files

Thanks, nice work.

**Comment by fd0** [comment]
Cool, thanks for the report!
