### ISSUE TITLE
too many open files with restic cache

### ISSUE THREAD

**Issue by Gordin** [restic/restic#101]
I ran `restic -r REPO cache` and after so time the output switched from 

    tree 4012a865 stored
    tree 51b731e0 stored
    tree 2cb44bf2 stored
    tree 5d58cbe6 stored
    tree 222c739a stored
    tree 4aaa5840 stored
    tree 403ccf4e stored
    tree 27f0012d stored
    tree 26678210 stored
    tree 22cce287 stored
    tree 577534ed stored
    tree 438c26ad stored
    tree 62d005af stored
    tree 52c6e0dd stored
    tree 2aa8c1d8 stored
    tree 4b2e3f15 stored
    tree 3b1ec46a stored
    tree 3ee3edca stored
    tree 64e9f611 stored
    tree 4e753b99 stored
    tree 3f68b4c8 stored
to

    tree 65a8538b cache error: open /home/gordin/.cache/restic/trees/65a8538ba96f1c1ddda73598220b21d867bc7f19efea6f1a511ca11d17c8f419: too many open files
      load error: open /run/media/gordin/backup/elchstation.restic/trees/65/658b133e8ac99832c12d233e6e8ac6fe19ddb10e56fdcaf24e7d0171b01a5d63: too many open files
    tree 65b5e3af cache error: open /home/gordin/.cache/restic/trees/65b5e3af2a29b252931a856eb4847d42a7a2a2900cc2d677ddb2a97114d651b8: too many open files
    tree 6591b4ba cache error: open /home/gordin/.cache/restic/trees/6591b4bacdc47c4ff44de7724793d5a63bac6d3429ef7c9988e563e08fd5fe41: too many open files
    tree 65af2414 cache error: open /home/gordin/.cache/restic/trees/65af2414a91d7757c8a35bd85941fc8aa4af788d0cf833d1db8e4e80e35579fd: too many open files
    tree 65adc69f cache error: open /home/gordin/.cache/restic/trees/65adc69f66815a78f394a9ea00b8c9c342234341a70e411e3712c773a338c552: too many open files
    tree 65591aa3 cache error: open /home/gordin/.cache/restic/trees/65591aa3ec492331d7f0524b22d06316a20a71ccfd5381f2abae1d98dbf5c63c: too many open files
    tree 65bf323a cache error: open /home/gordin/.cache/restic/trees/65bf323a676020bf3936329e2929b9eea222ed9b56b1609e10c1bdb3d1de1eb1: too many open files
    tree 65ccd1d9 cache error: open /home/gordin/.cache/restic/trees/65ccd1d992bd37d0113149f42bc53e9c88b666b365e02d314bd10825571e8819: too many open files
    tree 655923a4 cache error: open /home/gordin/.cache/restic/trees/655923a42cbc3e540a13943faca54321a0f036351107f83ed8de2c9affc8dab4: too many open files
    tree 6572fae5 cache error: open /home/gordin/.cache/restic/trees/6572fae565bbba595a206911227a67604e6f4f42fbf8d1e80ded0cdfa6aeb212: too many open files
    tree 6569d0a6 cache error: open /home/gordin/.cache/restic/trees/6569d0a642c50243590a9fdab29eaa2c59b2162e8c19865457d3c36f221ebc31: too many open files
    tree 65c414ef cache error: open /home/gordin/.cache/restic/trees/65c414eff641e4e6b406d72b9d26ddf1d15d38fe39c663a4b515306027d06f72: too many open files
    ...
    tree 745853ec cache error: open /home/gordin/.cache/restic/trees/745853ecad86cf64e7c3e785995001d4b8532ffa4b904964e40b386275e30bb9: too many open files
    tree 745b9d6f cache error: open /home/gordin/.cache/restic/trees/745b9d6f8c5ceeb12e13b7519b159146caed5efa3fc5acb236efa433719ab670: too many open files
    tree 74621c9e cache error: open /home/gordin/.cache/restic/trees/74621c9e02235c8f79eb4ee2cb9657acc363cceb93a6fb32cd95cb36a3f35603: too many open files
    tree 74604a97 cache error: open /home/gordin/.cache/restic/trees/74604a97b1104267ef029a1bb51d65679d676ca4d985228a0c8edeff222e3933: too many open files
    tree 74787003 cache error: open /home/gordin/.cache/restic/trees/74787003e58f43eace677f06ca67bfae1a757a356025e057da4e53c471af0340: too many open files
    tree 7482217f cache error: open /home/gordin/.cache/restic/trees/7482217f46e1f6a07d85285ee8fa5d274d676e1fd2c42834caafb99e61a948e0: too many open files
    tree 7481c21d cache error: open /home/gordin/.cache/restic/trees/7481c21d6539390b44710458a66e25c5194f4ad19398e626e8c2edc78d897a36: too many open files
    tree 7480c07a cache error: open /home/gordin/.cache/restic/trees/7480c07a9492718c06065ec43cedb6222cfbbf13ee6d9c991f8323ee2e89cd8e: too many open files
    tree 74827a6f cache error: open /home/gordin/.cache/restic/trees/74827a6fce87366c5e7e087ef3b6a38a160da22a33ca72086bacf9ce8330ce34: too many open files
    tree 7485be19 cache error: open /home/gordin/.cache/restic/trees/7485be199d2ac69f30b9583b8b881ffc4ed37cad2224b9ea673b391ded23ed2f: too many open files
      store error: open /home/gordin/.cache/restic/trees/2171d7b6ed3ed8eac4c7872f3e0e2e21baf73955f9c26c62ceac85adf53d700e: too many open files
    tree 7485b5da cache error: open /home/gordin/.cache/restic/trees/7485b5da6c2c1163a55fea5471b71a862672cddb1925b25a46d638709f4feb98: too many open files
    tree 74864cf9 cache error: open /home/gordin/.cache/restic/trees/74864cf9f7d11c331563c2fa06307405cd2be842e79ca4d11f9b7c73a00cc4d1: too many open files
      store error: open /home/gordin/.cache/restic/trees/2880bdce522c0bad17bea21e9a0e927739a3a08998ae2f4527b6636236b78135: too many open files
    tree 748cf0ff cache error: open /home/gordin/.cache/restic/trees/748cf0ff2d98c418a4090c3f894f7dad7aaf3e0e2e37e174cc70558ba15410f7: too many open files
    tree 748f0bdf cache error: open /home/gordin/.cache/restic/trees/748f0bdf776da65954fb264a9a9144a6ea6fbd358b869859388fcaad4c673901: too many open files
    tree 7495ca9c cache error: open /home/gordin/.cache/restic/trees/7495ca9c713ca28eb184ca8e0b21780d75641ebc25cd29596e755d8d153dc9bf: too many open files
    tree 74954c52 cache error: open /home/gordin/.cache/restic/trees/74954c52bd42ffdd5f2cdafb7c1bc3761c77221de7668ada3514dd891f322e2c: too many open files
    tree 74a57262 cache error: open /home/gordin/.cache/restic/trees/74a572621916e388c4b30c01aa396d07325d8852880bf1a6f95bb9c0c8de274f: too many open files
    tree 74a395ef cache error: open /home/gordin/.cache/restic/trees/74a395ef17637bc3322c53db89faf983249937230e1811ff9f7cd09369caed32: too many open files

**Comment by fd0** [comment]
Wow, interesting. i'll investigate that.

**Comment by fd0** [comment]
This is fixen in b17840c6ee9d1d3c80d1cbd2dacf5c26fb53ca51, I refactored the cache command.
