### ISSUE TITLE
restic ls shows MISSING files

### ISSUE THREAD

**Issue by LaszloHont** [restic/restic#1017]
## Output of `restic version`
restic 0.6.1
compiled with go1.8.3 on linux/amd64

## How did you start restic exactly? (Include the complete command line)
restic -r /mnt/media/restictest ls latest | grep MISSING

## What backend/server/service did you use?
local

## Expected behavior
the output from ls should match what is on the filesystem, excluding excludes

## Actual behavior
weirdly named files e.g. `./.config/gconf/desktop/gnome/interface/%!g(MISSING)conf.xml`

## Steps to reproduce the behavior
```
$ restic -r /mnt/media/restictest ls latest | grep MISSING
./.config/gconf/apps/%!g(MISSING)conf.xml
./.config/gconf/apps/GnomeBaker/%!g(MISSING)conf.xml
./.config/gconf/apps/GnomeBaker/Devices/%!g(MISSING)conf.xml
```
So `./.config/gconf/apps/GnomeBaker/%gconf.xml` becomes `./.config/gconf/apps/GnomeBaker/%!g(MISSING)conf.xml`

## Do you have any idea what may have caused this?
Maybe restic is mishandling the `%` character.

**Comment by fd0** [comment]
Huh, that's indeed a bug. Thanks for taking the time to report this!
