### ISSUE TITLE
Die on unsupported repo type?

### ISSUE THREAD

**Issue by LaszloHont** [restic/restic#1021]
Could restic fail if I try to backup to an unsupported repo type? I spent five minutes working out that b2:thing:thang is backing up to my current directory at b2:thing:thang all because I am using the release version of restic, and not the git built version. 😊

## Output of `restic version`
$ restic version
restic 0.6.1
compiled with go1.8.3 on linux/amd64

**Comment by fd0** [comment]
Yeah, I also ran into that. I'll add code so that restic fails if the repo location contains a : with an unsupported schemes. If someone really wants to backup into `/foo/bar:repo`, then they need to specify that as `local:/foo/bar:repo`.
