### ISSUE TITLE
sftp backend not usable on FreeBSD

### ISSUE THREAD

**Issue by simulot** [restic/restic#1037]
The documentation page about SFTP (http://restic.readthedocs.io/en/latest/manual.html?highlight=sftp#sftp) mention a wrong format for SFTP repo string:
restic -r sftp:user@host:/tmp/backup init

A look to source code (thanks to open source) shows the expected format:
restic -r "sftp://user@host/path" init

++ 
great job!

**Comment by fd0** [comment]
Hey, thanks for leaving an issue. The format you discovered is actually the old, deprecated format, which isn't mentioned in the docs any more because it shouldn't be used. I'm going to close this issue, feel free to add further comments. Thanks!

**Comment by simulot** [comment]
Fine, anyway I'm not able to use the new format sftp:user@host:path on freebsd.

**Comment by fd0** [comment]
Hu, that's interesting! Could you please paste a few details on how (exactly) you call restic? What do you specify for the repository?

**Comment by simulot** [comment]
Certainly,

on my Freenas box, running FreeBsd, following command line fails:
```
#./restic -r sftp:admin@restic:/share/Public/Restic init
create backend at sftp:admin@restic:/share/Public/Restic failed: cmd.StderrPipe: pipe: function not implemented

#./restic -r sftp//admin@restic/share/Public/Restic init
enter password for new backend:
enter password again:
created restic backend 97e733e56c at sftp//admin@restic/share/Public/Restic
```

**Comment by fd0** [comment]
That's almost certainly a bug, thanks for reporting! Could you please create a [debug logfile](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)? Please be aware that it may contain sensitive data such as file and directory names. A log of the `init` command is sufficient.


Thanks!

**Comment by fd0** [comment]
Oh, are you aware that the second call to restic initializes a repo in the **local path** `sftp//admin@restic/share/Public/Restic` in a subdir of the current directory? There's a colon (:) missing in the repository location...

**Comment by simulot** [comment]
oops, thanks... that explains why the remote doesn't contain the repo!

**Comment by fd0** [comment]
Ok, no need for the debug log any more, it may just be this issue: https://github.com/golang/go/issues/18854

**Comment by fd0** [comment]
The issue mentions that compiling the kernel with `COMPAT_FREEBSD10` works.

**Comment by simulot** [comment]
I'm not going to compile a kernel for the Freenas! It's out of my knowledge.

# freebsd-version -u
11.0-STABLE

With corrected path, i get an error:
```
# ./restic -r sftp://admin@restic:/share/Public/Restic init
create backend at sftp://admin@restic:/share/Public/Restic failed: cmd.StderrPipe: pipe: function not implemented
```

**Comment by simulot** [comment]
I'll attach a disk to the nas for doing a local backup. 
Thanks for you quick support!

**Comment by fd0** [comment]
Okay. Would you be willing to try restic compiled with Go 1.9beta1?

**Comment by simulot** [comment]
Sure, I'll give it a try later this week.

**Comment by fd0** [comment]
Nice, I've attached the binaries for freebsd here: [restic_freebsd_go19.zip](https://github.com/restic/restic/files/1077990/restic_freebsd_go19.zip)

**Comment by simulot** [comment]
I should wait the end of the current backup... ETA 46:12:55  
After that, I'll either using cross compilation either directly on the nas.
I'll keep you posted with results.

**Comment by simulot** [comment]
Thanks for providing binaries! 
Once password less connection correctly set, i have ran restic with success. 

Thanks for your efficient support.

**Comment by fd0** [comment]
Nice, thanks for the feedback!

**Comment by winks** [comment]
Hi,
I have exactly this issue.

```
./bin/restic version
restic 0.9.0 compiled with go1.10.2 on freebsd/amd64

# this doesn't work
[root@xxx /mnt/main/root]# export DEBUG_LOG=/mnt/main/root/debug.log
[root@xxx /mnt/main/root]# ./bin/restic -r sftp://backup@REMOTE:/.../restic init
Fatal: create repository at sftp://backup@REMOTE:/.../restic failed: cmd.StderrPipe: pipe: function not implement
[root@xxx /mnt/main/root]# ls debug.log
ls: debug.log: No such file or directory

# this works:
/bin/restic -r /mnt/main/root/restic init
created restic repository 70e1199055 at /mnt/main/root/restic
```

```
[root@paramount /mnt/main/root]# echo $BASH_VERSION
4.2.45(1)-release
[root@paramount /mnt/main/root]# uname -a
FreeBSD XXX 9.2-RELEASE-p3 FreeBSD 9.2-RELEASE-p3 #0 r262572+38751c8: Thu Mar 20 21:13:02 PDT 2014     root@build.ixsystems.com:/tank/home/jkh/9.2.1-BRANCH/freenas/os-base/amd64/tank/home/jkh/9.2.1-BRANCH/freenas/FreeBSD/src/sys/FREENAS.amd64  amd64
```

Maybe 9.x is not support anymore?

Also,
> The format you discovered is actually the old, deprecated format, which isn't mentioned in the docs any more because it shouldn't be used

If you meant https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp - nope, still `sftp:`

**Comment by fd0** [comment]
I'm sorry, it seems that sftp is not supported on FreeBSD 9. I don't know what we can do about that.

The sftp format is `sftp:user@host:/path`, the deprecated format was `sftp://user@host//path`.

**Comment by winks** [comment]
Yeah, I reread the original bug report and I think the wording is just a bit ambiguous. Sorry for the noise.
