### ISSUE TITLE
Information command

### ISSUE THREAD

**Issue by jannickfahlbusch** [restic/restic#1047]
It would be nice, to have a `restic info` command.

Currently there is no way to see the number of snapshots and the size of the repo (and much more info) with one command.

I would open a PR implementing this, if somebody could guide me in the right direction.

**Comment by fd0** [comment]
Hm, good suggestion. I'd wait until the metadata cache is in place (see #1040), but then we can discuss what such a command (I have more of a `status` command in mind) can display. I'm happy to guide you then.

**Comment by middelink** [comment]
Dup of #874 ?

**Comment by fd0** [comment]
Partial, yes. But slightly different IMHO.

**Comment by middelink** [comment]
Yeah, this is higher level information

So what can we do / do we want? To kick off the list:

- \# keys (+total size)
- \# indexes (+total size)
- \# snapshots (+total size)
- \# packs (+total size)
- \# blobs (and if possible \# data blobs vs \# tree blobs), likely also total sizes here, although they will mostly be the pack total size minus the headers...
- total size of the repo

**Comment by jannickfahlbusch** [comment]
I think, that the number of hosts and tags should be shown also.

**Comment by darkdragon-001** [comment]
Any news on this?

**Comment by aawsome** [comment]
Just saw this issue. I think #2543 already implements this.
