### ISSUE TITLE
Cannot execute the 0.7.0 binary on linux_arm64

### ISSUE THREAD

**Issue by heikojansen** [restic/restic#1072]
Just downloaded restic_0.7.0_linux_arm64.bz2 from the releases section; bunzip worked fine but executing the binary does not:
```bash: ./restic_0.7.0_linux_arm64: Kann die Binärdatei nicht ausführen: Fehler im Format der Programmdatei```
Downloading with wget instead of browser makes no difference.

Followed the exact same steps with the restic_0.6.1_linux_amd64.bz2 release and everything just works.

**Comment by fd0** [comment]
Uhm, are you sure you have the right binary? It looks like you're trying to execute an **arm64** binary on **amd64**, is that what you want?

**Comment by fd0** [comment]
I don't have a Linux/arm64 ready, but the extracted binaries look fine to me:
```
$ file restic*

restic_0.6.1_linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
restic_0.6.1_linux_arm64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
restic_0.7.0_linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
restic_0.7.0_linux_arm64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
```

**Comment by heikojansen** [comment]
Arrrghhh. Yes. Sorry...

**Comment by fd0** [comment]
Don't worry, I'm glad we could find the issue so quickly.
