### ISSUE TITLE
S3 migrate command interrupted, how to continue?

### ISSUE THREAD

**Issue by nztim** [restic/restic#1073]
## Output of `restic version`
restic 0.7.0
compiled with go1.8.3 on windows/amd64

## How did you start restic exactly? (Include the complete command line)
restic.exe --repo s3:s3.amazonaws.com/bucket-name -p repo-pass.txt migrate s3_layout

## What backend/server/service did you use?
Amazon S3

## Expected behavior
Migrate backend to new layout

## Actual behavior
1st run: the process began running and I could see the data files being renamed in the bucket. After some time the process stopped with a connection error. I lost the message because I then ran check and it was longer than the console scrollback, but it was related to network connection - I've had lots of connection errors so this wasn't surprising.

2nd run: migration s3_layout cannot be applied: check failed

## Steps to reproduce the behavior
I expect that disconnecting the network during the migration process would probably replicate this.

## Do you have any idea what may have caused this?
The migration was interrupted, so it looks to me like the repo is in an inconsistent state. 

Is there a way to continue the migration?

**Comment by fd0** [comment]
Thanks for raising this issue, I'll have a look now.

**Comment by fd0** [comment]
Please check out the branch `migrate-s3-continue`, build restic with `go run build.go` and re-run the migration with `./restic migrate s3_legacy --force`. It now can be re-run with then new `--force` option and automatically retries on error. Please report back!

**Comment by nztim** [comment]
I ran `migrate s3_legacy --force`, it continued the migration and I think it completed successfully. The files were renamed and as below the results of `check` look OK. Given how long it took to complete I expected a connection error but it didn't stop.

Output:
```
check for migration s3_layout failed, continuing anyway
applying migration s3_layout...
renaming file returned error: Put https://bucket-name.s3-ap-southeast-2.amazonaws.com/restic/data/fb/fb60...ddc273: dial tcp 52.95.132.6:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
migration s3_layout: success
```

After completion I tried to run `check` but I had to unlock it first.

After unlocking the results of `check` were tons of `pack xyz: not referenced in any index` followed by 
```
Check snapshots, trees and blobs
Fatal: repository contains errors
```
I understand from the docs that this isn't a problem but I can clean it up with `purge`.

Running a backup now and it looks all good. Thanks very much Alexander!

**Comment by fd0** [comment]
Hm, interesting. I find the message about unreferenced packs unexpected, I'll have a second look. Can you check that the number of snapshots matches? And that the path `snapshot` has been successfully renamed to `snapshots` (including all files in it)?

**Comment by nztim** [comment]
Yes `snapshot` was renamed to `snapshots` with all files. The list of snapshots and number of snapshots appears to be correct - I don't have anything to compare it with. 

There were a lot of unreferenced packs were there before the migration so I wasn't surprised to see this. I began a `prune` afterwards and there was a similar amount of duplicate data. 

Thanks again :)

**Comment by fd0** [comment]
Thanks fro the feedback, I'm much calmer now :)
