### ISSUE TITLE
Symlinks to a directory are not detected in Windows

### ISSUE THREAD

**Issue by martinml** [restic/restic#1078]
## Output of `restic version`
    restic 0.7.0
    compiled with go1.8.3 on windows/amd64

## How did you start restic exactly? (Include the complete command line)
    restic backup --repo R:\test_backup R:\test

## What backend/server/service did you use?
Local.

## Expected behavior
The symlink to a directory should be detected just like symlinks to files are.

## Actual behavior
    warning for test\symlinkdir: invalid node type ""

## Steps to reproduce the behavior
    restic init --repo R:\test_backup
    restic backup --repo R:\test_backup R:\test

`R:\test` contains a directory called `realdir` and a symlink to it called `symlinkdir` created with `mklink /D symlinkdir realdir` (you'll need an elevated prompt in order to do that). A junction to the directory (`mklink /J`) behaves the same way (what's the difference? [see end of page 431](https://books.google.com/books?id=3rdCAwAAQBAJ&pg=PA431&lpg=PA431&dq=there+are+no+windows+function+for+creating+reparse+points&source=bl&ots=d7zxxodyqG&sig=D9qYu2h69YJwSkkSpU6GffoWxO4&hl=es&sa=X&redir_esc=y#v=onepage&q=there%20are%20no%20windows%20function%20for%20creating%20reparse%20points&f=false)).

## Do you have any idea what may have caused this?
Somehow `nodeTypeFromFileInfo()` is returning `""` for a symlink to a directory. It might be a bug in the `os` package and this is more like an upstream thing?

**Comment by cfcs** [comment]
Slightly off-topic, but question for @fd0 related to Windows links -- how do we handle "directory junctions"?
(Had to look up `mklink`, found this article: http://windows7themes.net/en-us/windows-7-mklink-command-use-to-create-symbolic-links/ )

**Comment by fd0** [comment]
Hm, not sure what goes wrong here. We need to handle directory symlinks on Windows as a special case, so somebody needs to find out how to do that.

**Comment by martinml** [comment]
I barely know Go but I tried to delve into the problem a bit more. So I created the following structure:

    ├───test
       ├───dir
       ├───junction-to-dir (made with mklink /J junction-to-dir dir)
       ├───symlink-to-dir (made with mklink /D symlink-to-dir dir)
       ├───file.txt
       └───symlink-to-file.txt (made with mklink symlink-to-file.txt file.txt)

Then ran the following go program inside the `test` directory (sorry for any un-golanginess):
	package main

	import (
		"fmt"
		"os"
	)

	func main() {
		files := []string{"dir", "junction-to-dir", "symlink-to-dir", "file.txt", "symlink-to-file.txt"}
		
		for i := 0; i < len(files); i++ { 
			fi, _ := os.Stat(files[i])
			mode := fi.Mode();

			if(mode&os.ModeSymlink != 0) {
				fmt.Println("symlink")
			} else {
				fmt.Println("something else")
			}
		}
	}

And I got 5 `something else` 🤔

That really sounds like a bug in Go and not in restic, doesn't it? Can anybody confirm?

**Comment by fd0** [comment]
I think it's helpful to open an issue in the Go project here: https://github.com/golang/go, sounds like a bug. I'm willing to help fix this (e.g. writing the code and doing the Gerrit dance to get it in), but I don't have the time to do a lot of debug this, especially not on Windows (which I don't normally use). So, any help is appreciated.

For restic, I'd like to propose we handle this the same way as a symlink.

**Comment by martinml** [comment]
Hmm, my bad. My example should be using `os.Lstat` and not `os.Stat`. That does return the expected result indeed:

```
something else
symlink
symlink
something else
symlink
```

How this difference would apply to restic?

**Comment by fd0** [comment]
Hm, then restic should be able to detect the symlinks then. Strange. What's the difference between a "junction" and "symlink"?

**Comment by martinml** [comment]
I think none unless they are in a remote server:

> [junctions are processed at the server and directory symbolic links are processed at the client](https://superuser.com/questions/343074/directory-junction-vs-directory-symbolic-link)

**Comment by cfcs** [comment]
@martinml: Good catch. Backing up a shared drive doesn't seem like an unreasonable use case.

I'm trying to wrap my head around potential problems storing it as a symlink (downgrading from a "junction" which is not easily expressible in Linux), but I'm not sure what we'd want to do when restic is configured to *not* follow symlinks (following it is easy) :-)

**Comment by torado1984** [comment]
Hi, guys. Got the same problem with symlinks for folders and files with restic 0.9.6 on windows 7, sp1. Symlinks(hardlinks and junction) don't appear in recovery folder after snapshot is extracted, they are missed or skipped by restic. May be, is there a solution for that problem? Thanks in advance.

**Comment by mmnweb** [comment]
Hi
Still around in restic 0.11.0 compiled with go1.15.3 running on windows 10 20H2 build 19042.746.

**Comment by jzebedee** [comment]
Directory junctions are still not working, and will result in operations on valid repositories failing as contents are not detected through junction paths

```
<data/f0a27b4e> <data/95196307> <data/75f0fcbf> <data/1a1ed809> <data/390f7504> <data/5f983305> <data/5fd4548a> 
<data/dd936104> <data/3f42c65d> <data/c3ebd58c> <data/76a14005> <data/95e8372d> <data/081e8337> <data/040e6329> 
<data/f43cf506> <data/c02c8834> <data/cd87bbf3> <tree/ae375fd3> <data/f4cc7f7b> <data/470895e4> <data/098a8909> 
<data/e1937a18> <data/726dc7aa> <data/2ac68d52> <data/75c3d8ff> <tree/53370880> <data/f8712b78> <data/fc14aa86> 
<data/39f749d7> <data/6e6de62c> <data/560675bb> <tree/ae4e2da5> <data/038a5a34> <data/3a994b15> <data/a0467386> 
<data/529468b2> <data/68908ff7> <data/ec134522> <data/b962bff9> <data/2e6a4e80> <data/86ce4750> <data/d4070d1f> 
<data/e9049a4d> <data/cd83cbf0> <data/9fa41497> <data/3e27914e> <data/292950a1> <data/9a5561ee> <data/04d2f7c9> 
<data/cbd93aef> <data/ea7e1e5a> <data/c292f18b> <data/2c264351> <data/9be2feb5> <data/98d67ee3> <data/e0dd12d1> 
<data/690eb390> <data/d3e916b3> <data/22f2547b> <data/c3e04c99> <tree/776eda9d> <data/37d9b6c0> <data/0b0413cd> 
<data/037a1bcd> <data/d7a0b436> <data/2e0fa3e3> <data/ab48e7c8> <data/e05cb265> <data/46ebb89d> <tree/391865fb> 
<data/b5065e75> <data/b6cc118b> <data/6d679bbc> <data/6677cc92> <data/34e2729c> <data/a844db17> <data/c9b035e0> 
...snip... (continues for several hundred thousand lines)

<data/71f5cef6> <data/dccbd376>] not found in the new index


Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
restic.exe : pack 7dbe9340: does not exist
 
pack 257b1228: does not exist
pack 21b7dace: does not exist
pack c77d9337: does not exist
pack 50e36e3d: does not exist
pack a8ab914f: does not exist
pack 52a119da: does not exist
pack ccb0a266: does not exist
pack cacc5768: does not exist
pack 915fd217: does not exist
pack 8544cdf9: does not exist
pack 8940cd85: does not exist
pack db9d239f: does not exist
...snip... (continues for several hundred thousand lines)
```

**Comment by MichaelEischer** [comment]
@jzebedee That error message is completely different from the initial problem in this issue, please open a new issue.

Where are directory junctions involved? That error message shows no indication that directory junctions are involved. Please update to at least restic 0.12.0, run `restic check` and open a new issue.

**Comment by cowwoc** [comment]
I just ran across this issue in version 0.12.1 with a junction to a local drive. I lost an important file, tried restoring it only to discover that it was never backed up in the first place 😠 I spent hours debugging why only to figure out that no junctions are backed up.

So... Can we please have a workaround for this issue *and* increase its priority?

PS: I cannot simply convert the junction to a normal directory because the directory in question is very large and resides on a completely different drive.

**Comment by jzebedee** [comment]
Yeah, restic on windows completely ignores junctions. The only workaround I found is to run restic in WSL (which already follows Windows links) or run restic server in WSL/Docker and have the Windows restic connect to it.

**Comment by jzebedee** [comment]
> @jzebedee That error message is completely different from the initial problem in this issue, please open a new issue.
> 
> Where are directory junctions involved? That error message shows no indication that directory junctions are involved. Please update to at least restic 0.12.0, run `restic check` and open a new issue.

It's the same issue, that restic on Windows doesn't follow links or junctions. My issue was just the output of running restic against a repository that contains junctions inside of it, where the initial issue was for restic backups not picking up files through junctions. It's the same issue in two different scenarios, completely reproducible, and has never been fixed.

Just make some of the data folders (`00`, `0a`, etc) in a repository junctions and run Windows restic against them, you'll get the same output of data failures.

**Comment by MichaelEischer** [comment]
@cowwoc @jzebedee The problems you've described sound completely different from the one in this issue. My guess would be that you're seeing #3594 or #2708. What is unclear to me is whether restic issues a warning in your case.

**Comment by MichaelEischer** [comment]
@cowwoc Please open a separate issue, I agree that restic should never silently skip files during backup. The problem in this issue is that the symlink is not restored by the `restore` command although it exists in the snapshot. Your  problem on the other hand sounds like the data was never backed up.

**Comment by cowwoc** [comment]
@MichaelEischer Done: https://github.com/restic/restic/issues/3674
