### ISSUE TITLE
forget --keep-tag is ambigous

### ISSUE THREAD

**Issue by fd0** [restic/restic#1081]
A user reported that `forget --keep-tag` is not clearly defined. The manual says:

> `--keep-tag` keep all snapshots which have all tags specified by this option (can be specified multiple times).

 The help text is:
```
--keep-tag tag        keep snapshots with this tag (can be specified multiple times)
```

At the moment it's implemented this way: When just one tag to keep is specified (`--keep-tag foo`) restic won't touch any snapshots that have tag `foo`. For multiple tags to keep (e.g. `--keep-tag foo --keep-tag bar`) restic won't remove snapshots which have **both** tag `foo` and tag `bar`, but can forget snapshots which just have tag `foo`.

The manual states this (more or less clearly), but the help text is not clear.

I'd like to propose the following change: `--keep-tag foo` will work as is. `--keep-tag foo,bar` instructs restic to keep all snapshots that have both `foo` and `bar`. `--keep-tag foo --keep-tag bar` will not touch any snapshots that have either `foo` or `bar` set.

@middelink What do you think?

**Comment by rawtaz** [comment]
I think this is a very good suggestion/solution. It's practical and dynamic, while still not becoming spaghetti. I'd say go for it.

**Comment by fd0** [comment]
The same is with `--tag`, we should align that as well.

**Comment by tamalsaha** [comment]
As a user of restic, this sounds like a good idea to me. The new description text makes it also clear to me that I did not understand how it works thus far.

**Comment by middelink** [comment]
Wait, how do you want to do that, AFAIK the flag library will treat --tags A,B the same as --tags A followed by --tags B. So we cannot make that distinction.

**Comment by middelink** [comment]
It seems that --path is handled in a similar way, E.g. --path A,B equals --path A followed by --path B... Do you want to make the same change here? --path A,B matches snapshots with A **and** B, but --path A --path B matches snapshots with either A **or** B?

**Comment by fd0** [comment]
Huh, I stumbled upon this yesterday also. I think we should make it consistent, implement a type similar to `StringArray` so that `--foo a --foo b` is different than `--foo a,b`. This particular rabbit hole is deep...

**Comment by middelink** [comment]
Ah, ok, I can stop working on a fix then ^^

**Comment by middelink** [comment]
... sometimes github is too smart. It concluded that my #1081 reference in MY fork pointed to this bug. Oh well. Gives you something to look at ^^

**Comment by fd0** [comment]
Ah, you've already finished an implementation? Awesome, I got interrupted halfway through and didn't finished it. How should we proceed?

**Comment by middelink** [comment]
Oh, if you're ok with it, I can make a PR of it.
...
Hmm. I need to update the docs and likely some help, or do you think the later is generic enough to encompass the new way of things?

**Comment by fd0** [comment]
Yeah, I think the docs need a few more examples. When you fix the code then I'll fix the docs :)

**Comment by middelink** [comment]
Not 100% sure where the code needed fixing (tests pass), but the restic PR has arrived on your doorstep!

**Comment by fd0** [comment]
Nice, I'll have a look.
