### ISSUE TITLE
Snapshots number limitation

### ISSUE THREAD

**Issue by bmagnier** [restic/restic#1083]
This is not a bug, just a question : is there a maximum number of snapshots for a restic repository ?
More specifically, have you encoutered or designed such a limit for a swift backend ?

I have searched and found some pointers on the swift side of the question (https://answers.launchpad.net/swift/+question/181977), but wanted your input on the subject.

Context : we are currently evaluating new solutions for our infrastructure backup, and so we have to manage several snapshots per host, while regrouping our hosts in separate repositories (per client, per network zone, ...)

Thanks in advance for any help you can provide

**Comment by fd0** [comment]
There's no maximum number of snapshots. The [design document](https://github.com/restic/restic/blob/master/doc/design.rst) describes how snapshots are handled: At the moment a snapshot corresponds to a file in the repo, in the subdir `snapshots`. So I can imagine that this does not scale if you have 100k snapshots, as for each new backup all snapshots are loaded. We have plans to handle that (see e.g. #523).

So, I'm going to close this issue as your question is answered. Please feel free to add further comments, thanks!
