### ISSUE TITLE
Restic thinks that swift backend does not support byte range (but backend has Accept-Range header support)

### ISSUE THREAD

**Issue by mastergenius** [restic/restic#1084]
## Output of `restic version`
restic 0.7.0
compiled with go1.8.3 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)
restic -r swift:name:/ init

## What backend/server/service did you use?
swift backend

## Expected behavior
Restic repository inited

## Actual behavior
Error message
create backend at swift:name:/ failed: backend does not support byte range

## Steps to reproduce the behavior
Register account at https://selectel.com/services/cloud/storage/

Create user, use following swift config:

```
export ST_AUTH="https://auth.selcdn.ru/v1.0"
export ST_USER="<user name>"
export ST_KEY="<secret>"
export RESTIC_PASSWORD="<secret>"
```
Try to create new restic repo using
```
restic -r swift:name:/ init
```

## Do you have any idea what may have caused this?
There is problem at https://github.com/restic/restic/blob/master/src/restic/backend/swift/swift.go#L99
Storage api do not return Accept-Range header for account request:
```
curl -I https://redacted.selcdn.ru/ -H "X-Auth-Token: token_here"

HTTP/1.1 204 No Content
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Backend-Timestamp, Etag, Last-Modified, X-Object-Manifest, X-Timestamp
Content-Type: text/plain; charset=utf-8
Date: Tue, 04 Jul 2017 11:06:25 GMT
X-Account-Bytes-Used: 1234567890
X-Account-Container-Count: 11
X-Account-Object-Count: 12341656
X-Account-Storage-Policy-Policy-0-Bytes-Used: 1234567890
X-Account-Storage-Policy-Policy-0-Container-Count: 11
X-Account-Storage-Policy-Policy-0-Object-Count: 12341656
X-Put-Timestamp: 1493079499.65206
X-Timestamp: 1341238785.63341

```
Selectel storage supports range requests.
Possible solution will be add option to ignore this error.

**Comment by fd0** [comment]
Hey, thanks for reporting this issue. I'd thought that all Swift servers return what they support in the response of that request. Hm.

@ncw What's your experience with Swift services, is this a good test? https://github.com/restic/restic/blob/master/src/restic/backend/swift/swift.go#L99

Or should we just try a byte range and return an error if that doesn't work?

How many different implementations of Swift are there?

**Comment by ncw** [comment]
According to the RFC : Origin servers that accept byte-range requests MAY send

          Accept-Ranges: bytes

but are not required to do so.

So I'd dispense with this check.

As far as I know all swift servers support range requests. Certainly all the ones I have access to do as rclone tests it works in its integration tests.

**Comment by ncw** [comment]
Sorry didn't answer the last part of your question...

There are two main implementations of swift. The Openstack one, and one by Ceph as part of RadosGW. The openstack one has been around quite a few years now so has quite a few versions. The Ceph one is gaining rapidly in popularity as the Ceph object store does a lot more that the swift object store.

Both of these systems can be behind a variety of load balancers and proxies some of which can break http features like chunked encoding or expect continue.

**Comment by fd0** [comment]
Ok, I'll remove the check and add a check for the correct length in the response to `GET`. Thanks for the feedback!
