### ISSUE TITLE
selfproduced error, how to solve

### ISSUE THREAD

**Issue by novski** [restic/restic#1091]
## Output of `restic version`
restic 0.7.0
compiled with go1.8.3 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)
restic -r /Volumes/Backup/restic-backups backup /Users/<user>/Documents

## What backend/server/service did you use?
?
Its a USB3.1 HDD Storage

## Expected behavior
to complete

## Actual behavior
warning for /Users/<user>/Documents/Parallels/Win 10 64 D EDU.pvm/Win 10 64 D EDU-0.hdd/Win 10 64 D EDU-0.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds: expected 7739539456 bytes, saved 7819231232 bytes
panic: OpenFile: open /Volumes/Backup/restic-backups/data/65/65b8a2ed843fdb0e79d1b98ced919c99120badc22843e7e7fde549ca94aedc14: device not configured

goroutine 180274 [running]:
restic/archiver.(*Archiver).saveChunk(0xc433091310, 0x181f6a0, 0xc420070348, 0x4a88bee26, 0x879c0, 0xab2ffacd00000, 0xc42b47c000, 0x879c0, 0xa0000, 0xc432b638c0, ...)
	src/restic/archiver/archiver.go:165 +0x395
created by restic/archiver.(*Archiver).SaveFile
	src/restic/archiver/archiver.go:239 +0x3a4

## Steps to reproduce the behavior
Make a Backup and pull out the USB Cable. 

## Do you have any idea what may have caused this?
Yes myself.

## what did you try so far?
MacBook:~ novski$ restic -r /Volumes/Backup/restic-backups **check**
enter password for repository: 
Create exclusive lock for repository
repository is already locked by PID 1726 on MacBook.local by novski (UID 501, GID 20)
lock was created at 2017-07-07 14:22:14 (43h51m33.390966612s ago)
storage ID 24f2953a
the `unlock` command can be used to remove stale locks
MacBook:~ novski$ restic -r /Volumes/Backup/restic-backups **unlock**
enter password for repository: 
successfully removed locks
MacBook:~ novski$ restic -r /Volumes/Backup/restic-backups **check**
enter password for repository: 
Create exclusive lock for repository
Load indexes
error: error loading index 39feebfd: load <index/39feebfd49>: invalid data returned
Fatal: LoadIndex returned errors

MacBook:~ novski$ restic -r /Volumes/Backup/restic-backups **prune**
enter password for repository: 
load <index/39feebfd49>: invalid data returned
restic/repository.(*Repository).LoadAndDecrypt
	src/restic/repository/repository.go:65
restic/repository.LoadIndexWithDecoder
	src/restic/repository/index.go:526
restic/repository.LoadIndex
	src/restic/repository/repository.go:353
restic/repository.(*Repository).LoadIndex.func1
	src/restic/repository/repository.go:321
restic/repository.ParallelWorkFuncParseID.func1
	src/restic/repository/parallel.go:74
restic/repository.FilesInParallel.func1
	src/restic/repository/parallel.go:39
runtime.goexit
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197

## note
I didn't find a Forum or more helpful Helpsection in http://restic.readthedocs.io/en/latest/faq.html
How can i solfe the damaged backup?
Thanks, Novski

**Comment by ibib** [comment]
Did you try to rebuild the index?

**Comment by fd0** [comment]
Run `restic rebuild-index`, then run the backup again. Should be good as new :)

**Comment by novski** [comment]
I had to do that rebuild and prune two times before check run through without errors, but now its solved. Thanks for that. Can the FAQ be updated with a note where to get help? I wasn't shure if this is the right place for user-help...
