### ISSUE TITLE
500 Internal Server Error 

### ISSUE THREAD

**Issue by michbsd** [restic/restic#1092]
## Output of `restic version`
restic 0.7.0 (v0.7.0-0-g27ea0623)
compiled with go1.8.3 on freebsd/amd64

## How did you start restic exactly? (Include the complete command line)
/root/work/restic/restic -r rest:https://my_host.com:8989 backup my_directory_to_backup

## What backend/server/service did you use?
rest-server (with tls) - launch command:
rest-server --listen ":8989"  --tls --path /tank/core_backup

 /tank/core_backup is my repo

## Expected behavior

The directory should be added as snapshot

## Actual behavior

enter password for repository:
scan [my_directory_to_backup]
scanned 507 directories, 3590 files in 0:00
panic: server response unexpected: 500 Internal Server Error (500) errors  ETA 0:00

goroutine 3600 [running]:
restic/archiver.(*Archiver).saveChunk(0xc420344fa0, 0xc1a6c0, 0xc420076358, 0xaeb2ac, 0x2076d0, 0xdb767ce400000, 0xc422210000, 0x2076d0, 0x268000, 0xc420d138c0, ...)
	src/restic/archiver/archiver.go:165 +0x395
created by restic/archiver.(*Archiver).SaveFile
	src/restic/archiver/archiver.go:239 +0x3a4

## Steps to reproduce the behavior

Every time I run the above command.

## Do you have any idea what may have caused this?

Nope.

**Comment by michbsd** [comment]
Local backups / operations are working fine.

snapshot listing, key creation etc etc is working through the rest-server as well

**Comment by zcalusic** [comment]
Please check the ownership of the folder /tank/core_backup and everything below it. The user you're running rest server under must be able to read/write repo folder.

If the ownership is OK, then please enable debug log for rest server and see which exact command/request returned 500. It should be near the end of the log after unsuccessful backup run. Then we'll try to determine what happened from the log.

**Comment by michbsd** [comment]
rest-server is running as root (at least while testing) - so it is not a permission problem.
Will provide the rest-server debug in a few

**Comment by michbsd** [comment]
rest-server:
GET /data/c68d5896a412451d31c6425db80989dec500223e9c8238fd51981926bf420895
GetBlob()
GET /data/1cf0f0e070f97135b79a1adb4a33a20142e1cb4f0a5d5b2ed0c279168a4e3526
GetBlob()
POST /data/50b7a40e95c6fd992778ee7a4cd52e02ff6d6d063e342160dbe0e0469adfc832
SaveBlob()
POST /data/cbc752dd81b17701abb71868179ad77d13888ca22bd50a2e6ca9e5b93752cff7
SaveBlob()
open /tank/core_backup/data/cb/cbc752dd81b17701abb71868179ad77d13888ca22bd50a2e6ca9e5b93752cff7: no such file or directory
DELETE /locks/8f461c3f0f5c5e678e4dafe4044bd2b5c4037e5b8bd3350b7f4a283cbe6b096f
DeleteBlob()
^C


restic client:
 ❯ /root/work/restic/restic -r rest:https://my_host.com:8989 backup www. my_directory_to_backup.com                                                                                                                           
enter password for repository:
using parent snapshot 64baa3bf
scan [/www/www.my_directory_to_backup.com]
scanned 507 directories, 3590 files in 0:00
[0:00] 100.00%  0B/s  58.498 MiB / 58.498 MiB  4097 / 4097 items  0 errors  ETA 0:00
duration: 0:00, 217.51MiB/s
server response unexpected: 500 Internal Server Error (500)
restic/backend/rest.(*restBackend).Save
	src/restic/backend/rest/rest.go:134
restic/repository.(*Repository).savePacker
	src/restic/repository/packer_manager.go:122
restic/repository.(*Repository).Flush
	src/restic/repository/repository.go:248
restic/archiver.(*Archiver).Snapshot
	src/restic/archiver/archiver.go:733
main.runBackup
	src/cmds/restic/cmd_backup.go:493
main.glob..func2
	src/cmds/restic/cmd_backup.go:39
github.com/spf13/cobra.(*Command).execute
	src/github.com/spf13/cobra/command.go:631
github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/spf13/cobra/command.go:710
github.com/spf13/cobra.(*Command).Execute
	src/github.com/spf13/cobra/command.go:669
main.main
	src/cmds/restic/main.go:63
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197


It seems like it is very sporadic. Running the backup command several times will yield different results. Even a few successful backups (1 out of 10 or so)

**Comment by zcalusic** [comment]
Oh, I see. This seems to be a repo created locally, then later served with rest-server. Unfortunately we found a bug, or better yet impedance mismatch between client and server. Restic didn't create all hash directories up front, where rest-server expects them all to be pre-created for performance reasons.

Please check https://github.com/restic/rest-server/issues/17 there's a workaround in the last comment which can help you fix the repo with oneliner, and then everything should work normally after that.

And please report back if it fixes the issue, thanks!

**Comment by michbsd** [comment]
It is working! Thanks
