### ISSUE TITLE
Question :  backup / restore only keys

### ISSUE THREAD

**Issue by michbsd** [restic/restic#1094]
Hi, 

First off, thanks for creating restic. It really looks promising. 

I will do backup for 3 main reasons:

1. Hardware malfunctioning 
2. Accidentally deletion of data by a staff member / developer
3. Compromised system

Point #1 and #2 are well covered by restic. 
However #3 is a bit more tricky. I run a rest-server on a remote system (with a non-privileged user). From my main "prod" system I do restic snapshots to the rest-server. Great. Everything works.

Since the restic backup cmd is running periodically from cron - the repo password is read from a pwd file on disk. 

However, should me "prod" system ever get compromised, and the attacker should would get root access - there is nothing to stop him/her from deleting all my snapshots on the remote server. 

That's why, I would like to create keys that can only backup and restore. They should not be able to forget/prune the repo. 

Or perhaps there's another way around this? 

Many thanks!

**Comment by fd0** [comment]
Hey, this use case is not supported yet, we've started collecting ideas in #187. I'm going to close this issue as a duplicate, please subscribe to the other issue to be notified of any progress.

**Comment by michbsd** [comment]
Will do thanks!
