### ISSUE TITLE
build.go: absolute path for --output is treated as relative to cwd

### ISSUE THREAD

**Issue by fawick** [restic/restic#1099]
## Output of ~~`restic version`~~`git describe`
`v0.7.0-22-g1d2045cb`

## How did you start ~~restic~~ the build exactly? (Include the complete command line)
`go run build.go -v -o /home/user/bin/restic`

## What backend/server/service did you use?
Not applicable.

## Expected behavior
Resulting binary would be in `/home/user/bin/restic`.

## Actual behavior
Resulting binary would be in `/home/user/src/restic/home/user/bin/restic`.

## Steps to reproduce the behavior
1. `git checkout v0.7.0-22-g1d2045cb`
2. `go run build.go -v -o $HOME/bin/restic`

## Do you have any idea what may have caused this?
The parameter value for `--output` is always joined with the current working directory in 
https://github.com/restic/restic/blob/master/build.go#L404

_(hmm, __line 404__... so maybe the "not found" for the binary was intentional... :grin: )_

**Comment by fd0** [comment]
Merged, thanks!
