### ISSUE TITLE
Write documentation for reporting bugs

### ISSUE THREAD

**Issue by fd0** [restic/restic#110]
This should at least contain:
 * bulding restic with debug
 * writing a debug log file
 * notice: debug log file contains sensitive information (file and dir names)
 * restic version (git commit id)

**Comment by fw42** [comment]
If critical (or when in doubt), should bugs be reported confidentially, not on GitHub? Documentation should mention that and provide an email address (and a GPG key)?

**Comment by fd0** [comment]
True, thanks for pointing it out. I'm also planning to add gpg signatures to at least the releases, maybe even for all commits.

**Comment by fd0** [comment]
The document `CONTRIBUTING.md` contains all the required steps, and the `README` has a section on reporting confidential bugs, closing.
