### ISSUE TITLE
open locks: operation not permitted

### ISSUE THREAD

**Issue by LaszloHont** [restic/restic#1104]
## Output of `restic version`
restic 0.7.0
compiled with go1.8.3 on linux/amd64

## How did you start restic exactly? (Include the complete command line)
restic -r /mnt/media/restic-backups/box/ --quiet --exclude-file /home/user/etc/restic.excludes backup /home/user

## What backend/server/service did you use?
local mount

## Expected behavior
backup. it worked in 0.6.1

## Actual behavior
```
open /mnt/media/restic-backups/box/locks/2c1b721129e9edb0e69cc813a404aa2de1e4abbd6f858e5e6fb3c34c8ccfc9f1: operation not permitted
OpenFile
restic/backend/local.(*Local).Save
	src/restic/backend/local/local.go:113
restic/repository.(*Repository).SaveUnpacked
	src/restic/repository/repository.go:230
restic/repository.(*Repository).SaveJSONUnpacked
	src/restic/repository/repository.go:215
restic.(*Lock).createLock
	src/restic/lock.go:173
restic.newLock
	src/restic/lock.go:102
restic.NewLock
	src/restic/lock.go:63
main.lockRepository
	src/cmds/restic/lock.go:36
main.lockRepo
	src/cmds/restic/lock.go:23
main.runBackup
	src/cmds/restic/cmd_backup.go:370
main.glob..func2
	src/cmds/restic/cmd_backup.go:39
github.com/spf13/cobra.(*Command).execute
	src/github.com/spf13/cobra/command.go:631
github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/spf13/cobra/command.go:710
github.com/spf13/cobra.(*Command).Execute
	src/github.com/spf13/cobra/command.go:669
main.main
	src/cmds/restic/main.go:63
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197
```
That disk is mounted and I can write there. It isn't full.

## Do you have any idea what may have caused this?
No but it started after I upgraded to 0.7.0

**Comment by LaszloHont** [comment]
Trying with 0.6.1 gives the same error now.

**Comment by LaszloHont** [comment]
The backup to b2 still works.

**Comment by LaszloHont** [comment]
DEBUG_LOG does not work, I guess the official binary is not built with support for that.

**Comment by fd0** [comment]
Hi, thanks for raising this issue. I have a rough idea what may have happened here, but I'd like you to create a debug log for it. You need to recompile restic, instructions are here: https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by fd0** [comment]
Which file system do you use?

**Comment by LaszloHont** [comment]
ext4

**Comment by LaszloHont** [comment]
I think I know what is happening. I am hitting another issue, I cannot chown any files on this nfs share. Not your bug.

**Comment by LaszloHont** [comment]
I fixed the problem with the nfs share and now restic is working again. Sorry for the not-a-bug.

**Comment by fd0** [comment]
Thanks for leaving feedback, it's always good to know what's the underlying issue is.

In this case I think it's not chmod since that's done later in the code. I suspect it's the `open` call with `O_EXCL`. That wasn't present in earlier versions of restic.
