### ISSUE TITLE
Meeting at FrOSCon, August 19/20 in Sankt Augustin (near Cologne), Germany

### ISSUE THREAD

**Issue by fd0** [restic/restic#1110]
Hi,

I'd like to meet at [FrOSCon in Sankt Augustin (near Cologne), Germany on August 19/20](https://www.froscon.de/en/). The conference is cozy and has no entry fee. Is anybody else planning to attend?

We can discuss the future of the project, how to improve working together, short and long term goals and so on. And I'd like to meet you :)

**Time and date**: Saturday, 19 August, 15:00 o'clock, **Room A129**

Agenda:
 * Meet people
 * Share and discuss experience reports, feature requests
 * Collect ideas on how to improve contributions in the project

**Comment by davidak** [comment]
I will attend and would like to talk about restic.

Will you announce a meeting time here?

**Comment by fd0** [comment]
Probably, yes. And also on [Twitter](https://twitter.com/resticbackup).

**Comment by fawick** [comment]
I am going to attend FrOSCon at one of the two days. I would chose that day so that I could meet with you.

**Comment by fd0** [comment]
I'll try to get us a room.

**Comment by chaquotay** [comment]
+1

**Comment by middelink** [comment]
As per email, sadly I will be in the USA at the time, so unable to make it. Love to have come!

**Comment by fd0** [comment]
@middelink Huh, email? I haven't gotten one from you apparently...

**Comment by middelink** [comment]
@fd0 Hmm. Brilliant, just discovered my Android phone has 2 pending msgs in the outgoing queue and no way to kick them free it looks like. Well, one of them is for you ^^ (content was the same as my prev posting)

**Comment by fd0** [comment]
Then have fun in the US, and we'll meet another time ;)

**Comment by davidak** [comment]
I noticed that i have planned to attend a music festival that weekend. So i will sadly not be able to attend FrOSCon this year.

**Comment by fd0** [comment]
So, the time and date is now fixed: Saturday, 19 August, 15:00 o'clock. I'll announce the room as soon as I have it.

**Comment by fd0** [comment]
Coordinates: Time and date: Saturday, 19 August, 15:00 o'clock, Room A129

**Comment by chaquotay** [comment]
Was really looking forward to attend, but I won't be able to come, 'family stuff'  :-(

**Comment by fawick** [comment]
That was a good meeting, at least from my point-of-view. In the end, there were five of us, including @fd0, who collected our user stories and recommendations for improvement. 

I think this issue can be closed. :-)

**Comment by fd0** [comment]
Don't worry, next time. It was great fun! thanks for all who attended!
