### ISSUE TITLE
Restic doesn't accept self-signed certificates

### ISSUE THREAD

**Issue by pztrn** [restic/restic#1114]
## Output of `restic version`

restic 0.7.0
compiled with go1.8.3 on linux/amd64

## How did you start restic exactly? (Include the complete command line)

restic init --repo "rest:https://backup:backup@192.168.1.250:8888/repo_name"

## What backend/server/service did you use?

Caddy's plugin

## Expected behavior

Repo inited and I can do backups over HTTPS

## Actual behavior

create backend at rest:https://backup:backup@192.168.1.250:8888/repo_name failed: Post https://backup:backup@192.168.1.250:8888/repo_name?create=true: x509: certificate signed by unknown authority

There is no option to accept self-signed certificates. I can't easily issue LE certificate because this VM isolated from WAN.

## Steps to reproduce the behavior

Create Caddyfile with HTTP and HTTPS (or just HTTP) enabled, specify restic's plugin options, start Caddy. Issue this command on client:

restic init --repo "rest:https://backup:backup@192.168.1.250:8888/repo_name"

**Comment by fd0** [comment]
Hey, this is indeed the case, restic does not accept certificates which are not signed by a trusted CA. What do you expect in terms of options? Do you have an internal CA for this?

**Comment by tamalsaha** [comment]
@fd0, From my experience, generally there is a way to pass a CA cert. If no CA cert is provided, the ca-certificates from the OS is used. This is pattern I see used in Kubernetes.

**Comment by pztrn** [comment]
Actually I expect that restic have a flag to accept self-signed certificate by given fingerprint, like reading password from file (``-p``), or accept self-signed certificate without fingerprint. I know it is possible in Go :).

Use case - Caddy with ``tls self_signed`` parameter on internal LAN.

**Comment by mbiebl** [comment]
I'd like to backup some remote servers via https. I can generate a certificate using a local CA, but then I'd need a way to tell restic to trust that CA root certificate.

Is there a way to do that? On one of the remote servers I don't have root access. Thankfully I can just scp the static restic binary over to backup my /home directory. But that also means I can't install any CA certs in system paths.

**Comment by fd0** [comment]
I've thought about this for a bit and I think we should add an option to pass in a CA certificate to verify against. That's not hard to do, it just needs to be done :)

**Comment by LinusT** [comment]
That would be much appreciated fd0. I'm currently running one of my backup servers in China. In China you cannot use Let's Encrypt current version to issue certificates, since it requires access on port 80/443, both of which are blocked by default according to government regulation. So self signing and identifying from client with fingerprint would be ideal.
