### ISSUE TITLE
Remove repository

### ISSUE THREAD

**Issue by mnesrine** [restic/restic#1118]
I'd like to remove my backup repository in the server,  
and i not found a command witch remove it, or a reverse of init command.

Is there a option to remove a backup repository with `restic command` ?

Thanks.

**Comment by davidak** [comment]
You can just `rm -rf /path/to/repository`.

I'm not sure if a restic command that does just that is helpful.

**Comment by novski** [comment]
in v 0.7.0 i see a new command called "dump" in the help `restic -h` its descripted as "dump data structures". The manual doesn't yet list it and i don't know what it does, but you cold try it and let us know... :-)

**Comment by davidak** [comment]
@novski i assume it's like mysqldump and you get a readable copy of the data structure. So it would not delete anything.

**Comment by novski** [comment]
good point. also possible. but `migrate` cold do same...
Doc's need to be updated...

**Comment by fd0** [comment]
Hey!

There's no method to remove a repository, you need to do this by hand.

The `dump` command is only available when restic is built with `debug` support.

**Comment by DillFrescott** [comment]
I believe this would be a useful command for clients using `rest-server` as they cannot ssh into the server to run a `rm -f` command

**Comment by colans** [comment]
@fd0 Kindly reopen this given all of the :+1: s  for REST server use?
