### ISSUE TITLE
nit: please remove dot imports

### ISSUE THREAD

**Issue by stapelberg** [restic/restic#1119]
Many (all?) restic tests use dot imports such as `import . "restic/test"`. This makes it harder than necessary to find the definition of identifiers, for example while debugging test failures for #1085.

The Go wiki gives similar advice: https://github.com/golang/go/wiki/CodeReviewComments#import-dot

Please get rid of dot imports.

**Comment by fd0** [comment]
Yeah, I know. It's tedious work ;)

**Comment by hgfischer** [comment]
Hello, I've just made this PR to solve this: #1312
