### ISSUE TITLE
Repo on encrypted USB NTFS drive became faulty

### ISSUE THREAD

**Issue by MatthiasKauer** [restic/restic#1125]
## Output of `restic version`
restic 0.7.0
compiled with go1.8.3 on windows/amd64

## How did you start restic exactly? (Include the complete command line)
It's hard to describe what I did to cause the behavior. My situation is certainly quite challenging for restic and there is a decent probability that what I am seeing is caused by hard drive failure. I will diagnose that next and report back.
Here's what I can reproduce from memory and the limited scrollback I have.

- Win7 64bit. Trying to write to a local USB drive that I encrypted with Truecrypt a while ago. 
- I'm executing restic via a `restic.cmd` file. All executables are on the USB drive as well.
```
@echo off
bin\restic_0.7.0_windows_amd64.exe -r repo --password-file "password" %*
```
- I followed the tutorial video. 
  - Created a repo with `restic init`.
  - `restic backup` about 250GB into the repo. 
  - Connection to the drive was lost (unclear whether this was a hardware issue; I may have touched the drive) and I cleaned the repo by  `purge` and `rebuild-index`.
  - `check` succeeded at this point.
  - `restic backup` 250 GB again. Successfully this time.
  - `restic backup` another 50 GB. Did not finish for some reason.
  - Now `restic check` reports 
```
 Z:\restic>restic check
Create exclusive lock for repository
Load indexes
Check all packs
pack 05c77c579e745ed3c695f52a3a1aef8822439f95f8a9c67860ee1ec6d36590bf: not referenced in any index
.....
Check snapshots, trees and blobs
error for tree bad59072:
  tree bad59072, blob ec2d58fe: not found in index
error for tree 0d828e60:
  tree 0d828e60, blob 89caadf9: not found in index
  tree 0d828e60, blob a154926e: not found in index
  tree 0d828e60, blob 5e312a43: not found in index
  tree 0d828e60, blob e043f48d: not found in index
error for tree 15cfea07:
  tree 15cfea07, blob d7e29ce9: not found in index
error for tree 248798c5:
  tree 248798c5, blob faa8046f: not found in index
  tree 248798c5, blob c768ce49: not found in index
  tree 248798c5, blob 7ee13cd2: not found in index
  tree 248798c5, blob d7b2a2e9: not found in index
....
error for tree fd590f21:
  tree fd590f21, blob f87ded3f: not found in index
  tree fd590f21, blob 3743b4c2: not found in index
Fatal: repository contains errors
```

I tried a combination of `purge`, `rebuild-index` and also deleted the newer snapshot but `check` still reports that the repo is faulty.

## What backend/server/service did you use?
Local USB drive.

## Expected behavior
I would've liked to see the 250GB + 50GB on my hard drive and `restic check` reporting success.

## Actual behavior
`restic check` warns me about corruption.

## Steps to reproduce the behavior
See description above. I doubt that this is reliably reproducible.

## Do you have any idea what may have caused this?
Some guesses:

- NTFS issues
- Double encryption (restic and target drive which is also where restic is executing from)
- Faulty hardware: To be confirmed.

## Summary
Like I said, I am not sure if this is restic's fault at all. Let me clear this up.
In the meantime:
- Can I try anything else to salvage this repo?
- Should I produce a more detailed log of further `check`, `rebuild-index`, `purge` operations?

Best regards,
Matthias

**Comment by fd0** [comment]
Hey, thanks for the report. We had a similar report not so long ago, and I'd like to find out what's going on here. Could you please for each tree ID that `restic check` prints:
 * Find the complete tree ID by running (please translate that to Windows commands): `restic list blobs | grep <treeID>`
 * Print the tree: `restic cat blob <treeIDComplete>`
 * Upload the trees somewhere (after sanitizing file/dirnames) please?

I have a hunch that I'd like to confirm or falsify before we debug this further.

Thanks!

**Comment by MatthiasKauer** [comment]
I hope I got that right. I ran `check` then took 3 trees that were marked erroneous there.
After running `list blobs` and storing the output to a file, I used the editor to find the full ID of the tree in that file. Next, I used `cat blob` to produce the following.

[03_restic_cat_569007.txt](https://github.com/restic/restic/files/1167944/03_restic_cat_569007.txt)
[03_restic_cat_cb37e90.txt](https://github.com/restic/restic/files/1167945/03_restic_cat_cb37e90.txt)
[03_restic_cat_708f.txt](https://github.com/restic/restic/files/1167946/03_restic_cat_708f.txt)

On the hardware check: The drive performs normal from Windows otherwise and it turns out to be harder than I thought to run diagnostic software on external drives.
What are your suspicions?

**Comment by fd0** [comment]
Thank you so far. Can you tell me for each of the trees that you dumped which blobs are reported as missing?

**Comment by MatthiasKauer** [comment]
How would I find that? By grepping the output from check for the tree id?

**Comment by zcalusic** [comment]
Just paste a section of restic check command error output, but for those trees you dumped. It shows which blob is missing in that tree.

**Comment by fd0** [comment]
Turns out, this was a bug in restic 0.7.0, it is corrected in restic 0.7.1. The background story is here: https://restic.github.io/blog/2017-07-25/please-upgrade-to-0.7.1

**Comment by MatthiasKauer** [comment]
Wow, this was fast.
My investigations during the week are usually a bit slow, I'm afraid.

I'm glad you could figure this out! Thank you.

**Comment by fd0** [comment]
I had a very personal motivation to find this bug ;)

It seems you ran into the bug and had a bad drive simultaneously. Thanks a lot for taking the time to report this issue and debug it with us!
