### ISSUE TITLE
Merging 2 repositories

### ISSUE THREAD

**Issue by gvangool** [restic/restic#1127]
Due to the bug with pruning in restic 0.7.0, I corrupted my backup repository.
I created a new repository which I wasn't pruning, but I'd like to merge the "old" and new repository again.

Is this possible?

**Comment by fd0** [comment]
Hi, there's no way to merge two repositories. Which "bug with pruning" do you mean? What exactly is the curruption you see? What does `restic check` report exactly?

**Comment by gvangool** [comment]
I thought it was related to #1115.

I'll try to reproduce it with 0.7.0, because a rebuild-index with 0.7.1 fixed it.
In my test I was using:
```bash
restic forget --keep-last 1 --keep-hourly 24 --keep-daily 14 --keep-weekly 12 --keep-monthly 12 --keep-yearly 10 --keep-tag save
restic prune
```

**Comment by fd0** [comment]
Yeah, part of that particular bug was that restic detects an error on the next backup run, and either `prune` or `rebuild-index` fixes that. There was no corrupt data (phew), just a slightly wrong index that could easily be fixed. I'm going to close this for now, please let me know anything else you find :)
