### ISSUE TITLE
Slow network throughput to REST server with HTTPS, but fast via HTTP

### ISSUE THREAD

**Issue by codesmaker** [restic/restic#1128]
## Output of `restic version`
restic 0.7.0
compiled with go1.8.3 on linux/amd64

## How did you start restic exactly? (Include the complete command line)
```
restic -p /tmp/pass -r rest:https://restic:password@server1:8000/user backup /home/user/Downloads/
```

## What backend/server/service did you use?
rest-server 0.9.3

## Expected behavior
The backup speed should be as fast as my Internet connection (or close) but not as slow as what I'm currently getting.

## Actual behavior
The speed is very fast when it starts then it settles down to as slow as  900KiB/s
`scanned 300 directories, 898 files in 0:00
[12:39] 2.66%  859.446 KiB/s  637.031 MiB / 23.376 GiB  52 / 1198 items  0 errors  ETA 7:42:41`

## Do you have any idea what may have caused this?
Actually, I'm very new to Restic. I recently find it and I was testing it to make sure that it can handle daily laptop backups (about 100GB). I've started to write a script wrapper (BASH) to run everything automatically but the speed is just a bummer. Could you please help me optimize it?

**Comment by fd0** [comment]
Hey, welcome to the restic issue tracker! I think there are two different things at play:
 * Was this a subsequent (=non-initial) backup? We don't have a local metadata cache yet, so all metadata is loaded on demand from the repo. This is sometimes slow, depending on the latency of the remote. You can force re-reading all files locally so that no metadata is read from the repo, use `restic backup --force`. This is not a permanent thing, we're working on the metadata cache (see #1040).
 * The throughput that is printed during backup is not the throughput of data written to the repo, but data processed in the backup stage. So first restic starts reading files, bundles them together and writes the data to temp files. That's really fast. Then it starts uploading to the repo and slows down. That'll be fixed after the cache is done.

**Comment by codesmaker** [comment]
Hi
Thanks a lot for the quick reply, for the welcome, and for the explanation :)!
Actually, it was a new backup. So it's an initial backup. I guess "-f" option won't matter right? Anyways, I've run the backup with "--force" as you suggested:
`restic -p /tmp/pass -f -r rest:https://restic:password@server1:8000/user backup /home/user/Downloads/`

Unfortunately, I got the same speed :(.
Laptop connection speed: 100/100 Mbps download/upload (tested)
Backup server connection speed: 4/1 Gbps download/upload (tested)

**Comment by fd0** [comment]
For an initial backup `--force` has no effect, that's correct. I'm a bit at loss what's the cause of the slow speed here is. What do you get when you use a local directory for a repo? or running the REST server locally?

**Comment by codesmaker** [comment]
I've run the rest-server on my internal network to test. The speed was much better (around 15MiB) compared to the remote backup server but it still is slow considering that it's a 1Gbps network. Are there any parameters to fine-tune the throughput? What's causing the bottleneck here? I've also checked if the /tmp was full but it wasn't because I read that Restic uses it during the backup process.

**Comment by zcalusic** [comment]
@codesmaker, please append a dozen lines or so of `vmstat 1` output from source and destination servers during the time when you observe slow speed. I suspect source CPU or destination disk overload.

There aren't any tunables, everything should be as fast as possible out of the box.

**Comment by codesmaker** [comment]
Please find attached.
[vmstat.txt](https://github.com/restic/restic/files/1172849/vmstat.txt)

**Comment by zcalusic** [comment]
Huh, that is really weird, both sides are completely underutilized in all aspects. There must be some explanation for this behaviour, though it will be quite hard to find it without access to the servers.

You might try with http transport (no SSL) to try to see if https brings any slowdown.

Are there any firewalls between the machines, that could somehow introduce any slowdown?

**Comment by codesmaker** [comment]
Bingo! The problem was with SSL! It's strange though no? Do you know why?

**Comment by zcalusic** [comment]
I have only one thing in mind. If for some reason http keepalive connections are not working, then you constantly fire up new connections for every new request. And when you add SSL handshake on top of that, the latency goes up the roof.

Still, we weeded out all such bugs before 0.7.0, so I don't see how it could happen.

**Comment by fd0** [comment]
Is there anything in between you and the server? Any load-balancer, proxy, or anything?

**Comment by codesmaker** [comment]
Actually no. The laptop is behind a router (with firewall). The rest-server is installed on the backup server which has a firewall too but port 8000 is open. Do I need to open another port?

**Comment by fd0** [comment]
No, you don't need another port. We've had reports of middle boxes (proxys, load balancers) interfering with restic traffic, so I thought that this may be the case for you. Do you see high CPU load on one of the machines when you do a backup over HTTPS?

**Comment by codesmaker** [comment]
Not really. On the server side, all the CPU's cores are at ease. On the laptop, it's in the range of 4-30% max which I find normal no? Does it have something to do with the SSL certificate itself? I use letsencrypt. Maybe a bug in the rest-server? Have you guys experienced such issues?

**Comment by zcalusic** [comment]
Certificate really shouldn't matter, and BTW I'm also using letsencrypt and observe no performance issues.

Somehow, judged by the vmstat output, I feel like the slowdown comes from the client side, but I can't guess what could be wrong. Maybe turn on debugging on the client and try to see if there's anything fishy in the log output? @fd0, you have any other ideas?

**Comment by middelink** [comment]
Maybe a regression to what we observed earlier, many many open http sessions? (like per file ones).
@codesmaker, can you check on the laptop side (with netstat -nt) if it has many sockets open to the rest box?

**Comment by codesmaker** [comment]
Actually just one to the rest-server box:
`tcp        0  65783 192.168.0.243:55632     IP:8000       ESTABLISHED`

**Comment by middelink** [comment]
That's what it is suppose to be, if you use a certificate, yes.

**Comment by fd0** [comment]
Very mysterious, indeed. Hm.

**Comment by fd0** [comment]
Btw: Please upgrade to 0.7.1, see https://restic.github.io/blog/2017-07-25/please-upgrade-to-0.7.1 for details about a serious bug we discovered recently.

**Comment by codesmaker** [comment]
Thanks for the heads up! I'll upgrade right away. Do you guys think it would impose a serious security risk if I use the rest-server with authentication but without SSL? I understand that Restic encrypts the data by its own and the SSL only needed to encrypt the authentication process. I think the risk would be minimized if I only accept connections to the rest server from one IP. I've also tried the SFTP but unfortunately it isn't as fast as the rest server backend solution.

**Comment by fd0** [comment]
I don't recommend using the REST server without ssl: The password can be read by everybody who is able to observe your traffic. This doesn't allow decrypting data (as restic encrypts the data before transmission) but allows removing all your data from the REST server. You probably don't want that.

I'd rather like to find out what's going on here. Can you try with TLS again, but disable HTTP2 with the following command?
```
$ GODEBUG=h2client=0 ./restic backup [...]
```

How is the speed then?

**Comment by codesmaker** [comment]
So I've run:
`GODEBUG=h2client=0 restic -p /tmp/pass -r rest:https://restic:password@server1:8000/user backup /home/user/Downloads/`

No joy.

**Comment by codesmaker** [comment]
Here is some of what I get when I enable "--debug" on the rest-server box:
`rest-server 0.9.3 compiled with go1.8.3 on linux/amd64
Data directory: /mnt/laptop/restic
Authentication enabled
TLS enabled
Private key: /mnt/laptop/restic/private_key
Public key: /mnt/laptop/restic/public_key
Starting server on :8000
HEAD /user/config
CheckConfig()
GET /user/keys/
ListBlobs()
GET /user/keys/031909cbc19b8f278ccedaf3c5207e4d3e21e027114c4cfa31f315fe734ceb20
GetBlob()
GET /user/config
GetConfig()
GET /user/locks/
ListBlobs()
POST /user/locks/ab18d82fa487d68f886c03d2e237e7dc7f629ab1afde601030252db98eb6a5fd
SaveBlob()
GET /user/locks/
ListBlobs()
GET /user/locks/ab18d82fa487d68f886c03d2e237e7dc7f629ab1afde601030252db98eb6a5fd
GetBlob()
GET /user/index/
ListBlobs()
GET /user/snapshots/
ListBlobs()
POST /user/data/3b36091f32dcaa17242d11a2ab0cb1f70c24b7db11e1481e31a568cc03d8ce44
SaveBlob()
POST /user/data/8adc2b61e397eca6c9acbe14f46e9cf374289b0f499ac8987f6614c9b51454f8
SaveBlob()
POST /user/data/1966f058d564b79391377d72c1a9945a4fc5cdd498af9402adc5dde42e1dc030
SaveBlob()
POST /user/data/c703a58c59189b2856c981a43ec3b6b68e8da7685485a0dcd749bf133bf9b62c
SaveBlob()
POST /user/data/fd2b3e096dc581f20b83e62b5a7056f168e55147eff6b98c79df36bc3d970682
SaveBlob()
POST /user/data/6a67208c75827dd068494477904f20b6984b9087b3a34f58eb1ff17a98243ea0
SaveBlob()
POST /user/data/92b71459e470fac4b0f4c79734c8e09a46704ef856ab260348001226ba007dba
SaveBlob()
POST /user/data/de24eb40c57f5cb6ea18b00c45c622a2ebfd27e159ae7ca908acb8df3daed251
SaveBlob()
POST /user/data/bf3f93f6d8d13950c0c4e00d4398eedc00e0554e36e9221019e0c6b094b293de
SaveBlob()
POST /user/data/8cd8ab22fb2bac633e6be0a52b387a241df89f2ad0221b230fa9ebe8a99f67ac
SaveBlob()
POST /user/data/339f39ee28f652cb9de6fe4dbfcb5bb33f5b65c421092b37982dd8568f2744cc
SaveBlob()
POST /user/data/4980502da949cc54bfde44a45a08449f790098bd07586a81a44808dd2ab05a2f
SaveBlob()
POST /user/data/f2144658b5ac63829042470744edceeb89415194071e206879d136481e4062ce
SaveBlob()
POST /user/data/84a2892233e4500571794682dc36b8fd433cea20d2226a8607b2d4d9d7dae275
SaveBlob()
POST /user/data/15fe080a639743917af9ca58c5ac33858f682dafb27e09d773cf2a8aeb54c0b5
SaveBlob()
POST /user/data/1e4e77d425a584bbfb78b4db45605e469be79a1d471c7baa76b402f3e1a0f6c9
SaveBlob()
POST /user/data/76119f24fe00efac1f5a813a7418a4d44e2e168615cd971a3ea488ad24b1de38
SaveBlob()
POST /user/data/a5b589c4cf8e626b3e096ef2746388f60ebd0d23cc28a57932c272ecbd6e183e
SaveBlob()
POST /user/data/65d1a732b0177360c4a375b9104d7aa17ba389e08955f3d724061c25226e1ec7
SaveBlob()
POST /user/data/568ac4d6c8d61d272d80c1715a1f14133ee3a6189e7d4f18f3cd6d86896118c5
SaveBlob()
POST /user/data/f5d5c95b2854fe5692f57e79ec74c50531442617c04b3cdc29ed382e73b7bf2a
SaveBlob()
POST /user/data/7a5ba72ae98ab907c5bb0da44a6a0c71e73dd74e98d97dcec18d012be88d7520
SaveBlob()
POST /user/data/f385548dd30b5313c8951c53af9badc8140f7e7f3d4576b6ba731574295f2123
SaveBlob()
POST /user/data/c83a4a8160578d536d96a1bca091411876f678e22c5b62d5ad8b64bb7e1a4714
SaveBlob()
POST /user/data/4a4f23ac6c03ec3438007ce7ee67d19d27534a70d7bc28ab320c35f37664172b
SaveBlob()`

Can't see anything suspicious.

**Comment by fd0** [comment]
Can you check with wireshark if the data traffic looks suspicious? Many retransmits, very small or large packets?

**Comment by codesmaker** [comment]
Can't see anything wrong neither but I'm not 100% sure. Please find attached.
[wireshark.txt](https://github.com/restic/restic/files/1179516/wireshark.txt)

**Comment by chromium58** [comment]
@codesmaker  I think it could be the problem with MTU discovery. Do you use some vpn like OpenVPN, L2TP or other? Or may be your internet connection is based on vpn technology, e.g. pptp ?

**Comment by codesmaker** [comment]
@chromium58 Not at all but even it was the case, I would have the same issue with the HTTP no?

**Comment by chromium58** [comment]
@codesmaker 
No, https uses DF "Do Not Fragment IP flag" and http not.

> HTTPS servers set the DF or Do Not Fragment IP flag on packets and regular HTTP servers do not.
> 
> This matters because HTTP and HTTPS usually transfer a lot of data. That means that the packets are usually quite large and are often the maximum allowed size.
> 
> So if a server sends out a very big HTTP packet and it goes through a route on the network that does not allow packets that size, then the router in question simply breaks the packet up.
> 
> But if a server sends out a big HTTPS packet and it hits a route that doesn’t allow packets that size, the routers on that route can’t break the packet up. So they drop the packet and send back an ICMP message telling the machine that sent the big packet to adjust it’s MTU (maximum transfer unit) size and resend the packet. This is called Path MTU Discovery.

> This can create some interesting problems that don’t exist with plain HTTP. For example, if your ops 
 team has gotten a little overzealous with security and decided to filter out all ICMP traffic, your web server won’t receive any of those ICMP messages I’ve described above telling it to break up it’s packets and resend them. So large secure packets that usually are sent halfway through a secure HTTPS connection will just be dropped. So visitors to your website who are across network paths that need to have their packets broken up into smaller pieces will see half-loaded pages from the secure part of your site.

Quote source - http://markmaunder.com/2009/10/20/routers-treat-https-and-http-traffic-differently/

**Comment by fd0** [comment]
This is very interesting information!

@codesmaker could you try setting a lower MTU manually (`ifconfig eth0 mtu 1400`) on client and server and try again?

@chromium58 wouldn't MTU problems (which are oftentimes voodoo) show up in wireshark, either as ICMP packets from hops on the path or as retransmits?

**Comment by chromium58** [comment]
@fd0 If MTU size is a problem - in wireshark we should see icmp packets, but they can be filtered on any hop between client and server, that's why PMTU discovery can fail. TCP retransmits - i suppose we should see them too and i don't have explanation about why we don't :) 

But commonly MTU problems seem to appear if overlay or encapsulation technologies are used like VPN. That's why i asked about it first.

**Comment by codesmaker** [comment]
Very interesting stuff indeed! Decreasing the MTU on the client and server to 1400 didn't help :(.

**Comment by stv0g** [comment]
Hi also have problems with the rest-server.

My 2017 Macbook (i7 16GB RAM) is connected via Gigabit Ethernet to my server.

I get around 55 MiB/s throughput for an incremental backup. I would expect around twice that 
Apparently, CPU is the bottleneck here. Both machines have multiple threads of rest-server / rustic running consuming 100%.

Thats disappointing. Restic's slogan tells something different.
But every rsync or scp is faster in comparison.

Whats the problem here? Both machines have plenty of RAM for leveraging the page caches.
Both are multicore machines with HW encryption support...

:(

**Comment by fd0** [comment]
Interesting, I have several ideas what might be the cause here:
 * Could you paste the output of an incremental backup run? Is there a line saying `found parent snapshot`?
 * It may also be the latency between the laptop and the server (although it is in the LAN), this will be resolved when #1040 lands.
 * You can also try running `restic backup --force` (which will not use metadata from a previous snapshot, but re-hash everything locally)

Please report back.

**Comment by stv0g** [comment]
Hi @fd0,

 - I don't see `found parent snapshot` in my debug log
 - I am already using #1040 
 - I will try the `--force` tonight.

But I guess that latency isn't the problem in my case. I have a wired gigabit connection with just a single switch in between.

Also the fact that both systems use 100% CPU makes me think that the problem is somewhere else?

**Comment by fd0** [comment]
Hm. If you don't see the `using parent backup` line for a new backup, then restic fails to find a previous backup and will re-hash all data locally. That uses a lot of CPU and is basically the same as running `backup --force`.

Does something differ in between the snapshots? Do the names of the directories vary? Is the hostname different (check the `Host` column in `restic snapshots`)?

**Comment by fd0** [comment]
Since there hasn't been any activity here recently and I cannot reproduce the issue I'm going to close it for now. Please feel free to add further comments. Thanks.
