### ISSUE TITLE
prune: There is not enough space on the disk.

### ISSUE THREAD

**Issue by stuertz** [restic/restic#1140]
## Output of `restic version`
restic 0.7.1
compiled with go1.8.3 on windows/amd64

## How did you start restic exactly? (Include the complete command line)
d:\restic\restic -r d:\restic\ prune

## What backend/server/service did you use?
Filesystem (local usb windows, ntfs partition)

## Expected behavior
reduce disk usage

## Actual behavior
```
λ d:\restic\restic -r d:\restic\ prune
counting files in repo
building new index for repo
[44:35] 100.00%  99865 / 99865 packs
incomplete pack file (will be removed): 7de8bd2c65eacc121bb689d748caa95139b1ad84e6a661bbe9704b86774949d9
repository contains 99864 packs (7063132 blobs) with 459.184 GiB bytes
processed 7063132 blobs: 203673 duplicate blobs, 14.243 GiB duplicate
load all snapshots
find data that is still in use for 30 snapshots
[33:27] 100.00%  30 / 30 snapshots
found 3338752 of 7063132 data blobs still in use, removing 3724380 blobs
will remove 1 invalid files
will delete 15626 packs and rewrite 12427 packs, this frees 106.755 GiB
write \\?\d:\restic\data\9c\9c620cef19836b6f78fb9cbcc99353756f94e13d277e3a5981f3c871b9700be5: There is not enough space on the disk.
Write
restic/backend/local.(*Local).Save
        src/restic/backend/local/local.go:110
restic/repository.(*Repository).savePacker
        src/restic/repository/packer_manager.go:122
restic/repository.(*Repository).SaveAndEncrypt
        src/restic/repository/repository.go:203
restic/repository.(*Repository).SaveBlob
        src/restic/repository/repository.go:529
restic/repository.Repack
        src/restic/repository/repack.go:103
main.pruneRepository
        src/cmds/restic/cmd_prune.go:242
main.runPrune
        src/cmds/restic/cmd_prune.go:83
main.glob..func14
        src/cmds/restic/cmd_prune.go:23
github.com/spf13/cobra.(*Command).execute
        src/github.com/spf13/cobra/command.go:647
github.com/spf13/cobra.(*Command).ExecuteC
        src/github.com/spf13/cobra/command.go:726
github.com/spf13/cobra.(*Command).Execute
        src/github.com/spf13/cobra/command.go:685
main.main
        src/cmds/restic/main.go:63
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2197

```
## Steps to reproduce the behavior
Having a small partition while pruning a lot of files.

What I did was exactly:

- had some space on the partition
- run forget, which  marked several backups.
- tried to prune
- got above error 
- removed other files on the partition
- retried to prune
- got above error again.
- Again the device is completely filled.

Now I'm stuck, is there anything that can be savely removed?

## Do you have any idea what may have caused this?
as mentioned in #725 previous files are backuped but not removed in case of an error.

**Comment by middelink** [comment]
set TMPDIR to a mountpoint with some room. restic generates pack files locally when compacting them.
You can also run the prune from a different machine if need be.

**Comment by fd0** [comment]
The problem here is that restic is very conservative: It will only remove files from the repo once it has moved all still used data to other files. So the step where it removes files is the last step. If the file system where the repo is located fills up before, restic returns the error.

**Comment by stuertz** [comment]
@middelink: Setting TMPDIR to another location didn't help.

**Comment by mbiebl** [comment]
I've run into this issue as well (my backup location is a local disk). Tried to clean up a few older snapshots, then ran prune, which aborted with the above error as the disk was full.
check shows a lot of dangling pack files:

```
$ restic check
Create exclusive lock for repository
Load indexes
Check all packs
pack 0011a3706907383d629e94094a793267a8e2d1bda3b71daca760957b737f8052: not referenced in any index
[1750 lines snipped]
pack ffc304866b692599c2b8b7a51209e96a26009bd85efce2a497633527a485e0c3: not referenced in any index
Check snapshots, trees and blobs
Fatal: repository contains errors
```
How can I recover from this situation or is my backup repository hosed? 
Could restic be more resilient in this case and pre-calculate the amount of disk space it needs for a prune operation and warn/abort if the available (disk) space is not sufficient?
It looks like prune required dozens of GBs for repack, could this operation of forgetting old snapshots and reclaiming that space be made more efficient?

**Comment by fd0** [comment]
I think we can improve the situation, I'll think about it. It seems users regularly run into this (thanks for the reports!).

**Comment by mbiebl** [comment]
To give some background: I've created a backup of my /home directory to a local disk. It's about 30GB of data.  I had about 15GB of free space left on the backup location (external hard drive) when I tried to run prune+forget.

**Comment by McKael** [comment]
FWIW, I've been hit by this as well.
I've increased the backup partition size several times, but not enough...  And each time it fails, the repository gets bigger.

The repository is now 5 times its usual size :/

I wish there was at least a proper way to clean up failed prunes (or redundant data).

**Comment by fd0** [comment]
I'm aware of the limitation of `prune`. As a workaround, you could remove all files from the repo that were added since the run of `prune` started. Since `prune` will only ever remove data at the very end of the run, that shouldn't remove any data that isn't saved in another file which was present before. If in doubt, don't remove the files, but move them to a different directory outside of the repo and run `restic check` first.

**Comment by stefan-as** [comment]
Any news on this issue? We run into it on a 10TB Hetzner Storage Box. There is no way to increase the disk size :-(

**Comment by fd0** [comment]
You can try the code in the `prune-aggressive` branch, which removes files that are completely unneeded before starting the repack process.

**Comment by stefan-as** [comment]
Thanks for your quick reply! I built the `prune-aggressive` branch, but it does not seem to solve the situation:

```
Remove(<data/78348004bc>) returned error, retrying after 524.954656ms: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
Remove(<data/78348004bc>) returned error, retrying after 565.788962ms: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
Remove(<data/78348004bc>) returned error, retrying after 843.003712ms: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
Remove(<data/78348004bc>) returned error, retrying after 1.538368257s: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
Remove(<data/78348004bc>) returned error, retrying after 2.141937077s: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
Remove(<data/78348004bc>) returned error, retrying after 2.495749063s: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
Save(<lock/028fdb788e>) returned error, retrying after 12.885220654s: OpenFile: open /mnt/backup/kb_restic/locks/028fdb788ea2622df15c230c42370fc5a850696a03827f2c36f7577669e845c0: no space left on device
Remove(<data/78348004bc>) returned error, retrying after 8.041276629s: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
Remove(<data/78348004bc>) returned error, retrying after 8.552941091s: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
Save(<lock/028fdb788e>) returned error, retrying after 14.277652003s: OpenFile: open /mnt/backup/kb_restic/locks/028fdb788ea2622df15c230c42370fc5a850696a03827f2c36f7577669e845c0: no space left on device
Remove(<data/78348004bc>) returned error, retrying after 8.742477617s: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
Remove(<data/78348004bc>) returned error, retrying after 10.005156128s: Chmod: chmod /mnt/backup/kb_restic/data/78/78348004bc72698753b0f0991b432d2dd1cfa6868362b422d10e8ccb5f91413e: no space left on device
unable to refresh lock: OpenFile: open /mnt/backup/kb_restic/locks/028fdb788ea2622df15c230c42370fc5a850696a03827f2c36f7577669e845c0: no space left on device
unable to remove file 78348004 from the repository
[...]
[11:44:32] 0.25%  749 / 304270 packs deleted
```

**Comment by fd0** [comment]
Hm, does it remove any files at all? I would've thought so...

**Comment by stefan-as** [comment]
Reading the bottom line of the output there is some clue of removed files, but I assume it will take some more hours until we'll have a final statement...

**Comment by jo-so** [comment]
Is there a way to find the ids of the unused indexes to delete them manually?

**Comment by stefan-as** [comment]
@fd0 some updates about the prune run based on the `prune-aggressive` branch: even if there is any effect on disk usage in the long run, this approach does not seems to be usable because of the runtime it requires to complete.

```
Remove(<data/2222cd9bac>) returned error, retrying after 16.70137233s: Chmod: chmod /mnt/backup/kb_restic/data/22/2222cd9bac8304a6d080b3f969e26f1bae8648966cdb7435a6ffd59a95ac5487: no space left on device
Remove(<data/2222cd9bac>) returned error, retrying after 14.017690407s: Chmod: chmod /mnt/backup/kb_restic/data/22/2222cd9bac8304a6d080b3f969e26f1bae8648966cdb7435a6ffd59a95ac5487: no space left on device
[155:30:25] 5.80%  17263 / 297794 packs deleted
```

This is going to finish in spring 2019 ;-)

**Comment by Kjwon15** [comment]
I found a temporary solution: use overlayfs and rsync them back
```sh
mkdir /tmp/{upper,overlay,workdir}
mount -t overlayfs -o upperdir=/tmp/upper,lowerdir=/mnt/backup,workdir=/tmp/workdir /tmp/overlay
restic -r /tmp/overlay prune
rsync --delete -rulHtv /tmp/overlay/ /mnt/backup/
umount /tmp/overlay
rm -r /tmp/{upper,overlay,workdir}
```

**Comment by aawsome** [comment]
In #2718 there is a new flag `--max-repack-count` which allows to limit the number of files that are repacked (hence the number of newly generated files). The new implementation also first deletes completely unreferenced files trying to free space as early as possible, while still applying "safety first".

**Comment by WhyNotHugo** [comment]
I've tried setting `TMPDIR=/mnt` (which has 0.3TB free, my repo is about 1TB), and it still failed.

I also tried:

    # restic prune --repo /run/media/hugo/backups/restic --max-repack-size 1M

But that also failed:

    Fatal: write /run/media/hugo/backups/restic/index/88e8e85694d3f421aab50f18480a13a994d0b75fa9bf1499cb5a60da83fc1b6e: no space left on device

Any tips here?

**Comment by rawtaz** [comment]
@WhyNotHugo This issue is closed, you should open another one or even better post on the forum ;)

That said, you can try this PR: https://github.com/restic/restic/pull/3481 - Simply clone that repo/branch and `go run build.go` in it to get yourself a nice restic binary that you can then run. Be sure to read the text in the beginning of that PR though!

**Comment by jo-so** [comment]
> But that also failed:
> 
>     Fatal: write /run/media/hugo/backups/restic/index/88e8e85694d3f421aab50f18480a13a994d0b75fa9bf1499cb5a60da83fc1b6e: no space left on device
> 
> Any tips here?

@Hugo: My old solution was to move a few directories underneath *data* to
another filesystem and bring them back via bind-mounts. Symlinks doesn't
work. Thereafter, I've removed the bind-mount and moved the files back.

**Comment by matthijskooijman** [comment]
For anyone coming here and wondering how to use the `--max-repack-size` option mentioned above: This tells restic to limit the total size of new packs to this size, so if you pass a small number to it, restic will not write as much new packs as it would without this option. Note that pass 0 does not work, but you can pass `1B` to effectively disable repacking:

    restic prune --max-repack-size 1B

AFAIU this prevents all repacking, so it will only delete pack files that contain only unused blobs, but that might be enough to free up some diskspace so you can do some repacking in a second pass.

Note that this will not prevent *all* writes to the disk before deleting files, I've seen that restic rebuilds (thus writes) index files before actually deleting unused packs and the old index files, so you will still need *some* free space for prune to work.

**Comment by MichaelEischer** [comment]
> . Note that pass 0 does not work, but you can pass `1B` to effectively disable repacking:

Since restic 0.13.0 `--max-repack-size 0B` works as expected.

> Note that this will not prevent _all_ writes to the disk before deleting files, I've seen that restic rebuilds (thus writes) index files before actually deleting unused packs and the old index files, so you will still need _some_ free space for prune to work.

Please have a look at [--unsafe-recover-no-free-space](https://github.com/restic/restic/blob/master/changelog/0.14.0_2022-08-25/issue-1153) introduced by restic 0.14.0.

restic has to update or remove the index before deleting pack files. Otherwise later backups might loose data if prune is interrupted.

**Comment by matthijskooijman** [comment]
Ah, was orignally working with 0.12 and did not recheck the available options after upgrading. Thanks for the additionall info, I've updated my comment accordingly.
