### ISSUE TITLE
using tags slows down backup process

### ISSUE THREAD

**Issue by gwqggodf** [restic/restic#1143]
## Output of `restic version`

restic 0.7.1
compiled with go1.8.3 on linux/386

## How did you start restic exactly? (Include the complete command line)

time restic -r /dev/shm/test backup --tag **$RANDOM** /usr/share/

## What backend/server/service did you use?

a local tmpfs at /dev/shm/

## Expected behavior

restic should finish as fast as without using tags

## Actual behavior

restic is much slower when using a tag name **that wasn't used before**

## Steps to reproduce the behavior

time restic -r /dev/shm/test backup /usr/share/  \#fast: ~5s
time restic -r /dev/shm/test backup --tag new1 /usr/share/  \#slow: ~30s
time restic -r /dev/shm/test backup --tag new1 /usr/share/  \#fast: ~5s
time restic -r /dev/shm/test backup --tag new1 /usr/share/  \#fast: ~5s
time restic -r /dev/shm/test backup --tag new2 /usr/share/  \#slow: ~30s
time restic -r /dev/shm/test backup --tag new2 /usr/share/  \#fast: ~5s
time restic -r /dev/shm/test backup --tag new2 /usr/share/  \#fast: ~5s

## Do you have any idea what may have caused this?

unfortunately not

**Comment by fd0** [comment]
Thanks for the report. I think I know what's going on here, but can you please confirm: For a slow backup you see lots of CPU usage by restic, and for a fast backup not so much. Is that correct?

**Comment by gwqggodf** [comment]
I run 'time restic ...' on two different machines. Twice without using tags, then twice using a former unused tag. NB: The machines were not completely idle so times vary a bit.

machine1, an old Intel(R) Core(TM)2 Duo:
```
real    1m59.455s
user    1m54.037s
sys     1m17.557s

real    1m34.558s
user    1m50.387s
sys     1m5.002s
```
```
real    32m31.183s
user    13m31.179s
sys     11m51.606s

real    55m6.722s
user    14m12.955s
sys     16m7.045s
```
machine2, Intel(R) Core(TM) i5-4570S:
```
real    0m20.229s
user    0m41.232s
sys     0m11.123s

real    0m20.430s
user    0m40.850s
sys     0m11.569s
```
```
real    1m52.699s
user    4m54.658s
sys     1m1.855s

real    1m51.048s
user    4m52.791s
sys     1m1.528s
```

**Comment by gwqggodf** [comment]
machine3, another old two core AMD:
```
real    0m28.516s
user    0m43.451s
sys     0m1.600s

real    0m30.528s
user    0m46.127s
sys     0m2.072s
```
```
real    1m35.162s                                                              
user    2m38.178s                                                              
sys     0m7.188s                                                               

real    1m38.761s                                                              
user    2m38.706s                                                              
sys     0m8.133s                                                               
```

**Comment by fd0** [comment]
So, what I had in mind was that at the start of a new backup run, restic looks for older snapshots on the same machine with the same set of directories, so that it can check if the files to be saved have been modified since and it can skip re-reading all data. If you add tags that have not been used before, restic apparently does not find a previous snapshot, and re-reads all files. That's what you observe. On a subsequent backup with the same tags it will find the previous snapshot and can be fast.

You can check by looking for the `found parent snapshot` line at the start of the backup. If that's there, restic found a previous snapshot and should be fast, if it isn't it starts from scratch (at least concerning reading and hashing all files locally).

Does that match your observations?

**Comment by gwqggodf** [comment]
I can confirm that the `found parent snapshot` line is missing when using a new tag name.

1. Running `restic backup ...` without `--tag` seems to select the last backup of the given directory, tagged or not, as its parent. (That's what I expected restic to do.)
2. When using a formerly used tag name, restic seems to choose the last snapshot with this tag, even if it is quite old, ignoring any newer snapshots of the given directory.
3. When using a new tag name, restic fails to identify a parent.

As `restic help backup` says `parent snapshot (default: last snapshot in the repo that has the same target files/directories)` I consider 2) and 3) a bug.

**Comment by fd0** [comment]
Thanks for the feedback, I think this may be a bug.
