### ISSUE TITLE
Index look up multiple time

### ISSUE THREAD

**Issue by gluthgao** [restic/restic#1146]
## Output of `restic version`
$ ./restic version
debug enabled
restic 0.7.0 (v0.7.0-19-g38e5640-dirty)
compiled with go1.8.1 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)
restic -r

## What backend/server/service did you use?
S3 backend
## Expected behavior
BlockId just needs to lookup once, looks like we do multiple times of lookup.
## Actual behavior
2017/07/24 14:38:53 repository/index.go:141     repository.(*Index).Lookup      1       id 84b214ea not found
2017/07/24 14:38:53 repository/index.go:141     repository.(*Index).Lookup      1       id 84b214ea not found
2017/07/24 14:38:53 repository/index.go:123     repository.(*Index).Lookup      1       id 84b214ea found in pack afd7f99e at 57, length 10276
2017/07/24 14:38:53 repository/index.go:123     repository.(*Index).Lookup      1       id 84b214ea found in pack afd7f99e at 57, length 10276
2017/07/24 14:38:53 repository/repository.go:501        repository.(*Repository).LoadBlob       1       load blob 84b214ea into buf (len 10244, cap 10276)
2017/07/24 14:38:53 repository/index.go:141     repository.(*Index).Lookup      1       id 84b214ea not found
2017/07/24 14:38:53 repository/index.go:141     repository.(*Index).Lookup      1       id 84b214ea not found
2017/07/24 14:38:53 repository/index.go:123     repository.(*Index).Lookup      1       id 84b214ea found in pack afd7f99e at 57, length 10276
2017/07/24 14:38:53 repository/index.go:123     repository.(*Index).Lookup      1       id 84b214ea found in pack afd7f99e at 57, length 10276
2017/07/24 14:38:53 repository/repository.go:81 repository.(*Repository).loadBlob       1       load data with id 84b214ea (buf len 10244, cap 10276)
2017/07/24 14:38:53 repository/master_index.go:29       repository.(*MasterIndex).Lookup        1       looking up id 84b214ea, tpe data
2017/07/24 14:38:53 repository/index.go:141     repository.(*Index).Lookup      1       id 84b214ea not found
2017/07/24 14:38:53 repository/index.go:141     repository.(*Index).Lookup      1       id 84b214ea not found

## Steps to reproduce the behavior
just run the restore

## Do you have any idea what may have caused this?
Normally we should not lookup one block multiple times, i am not sure why we have that?

**Comment by fd0** [comment]
Hi, thanks for raising an issue. I'm not sure what exactly this issue is about. The debug log contains information what restic does internally, this includes the index lookup. It is just an internal function call during the runtime of restic when it tries to determine where a block of data is located. Why should it be a problem that the lookup is execute more than once? After all, the in-memory data structure that serves the lookup is there precisely so that restic can look up blobs.

Would you mind elaborating a bit on why you think this is an issue?

**Comment by gluthgao** [comment]
yea, thanks, that's internal control,  but from performance point of view, we can just query one time after got that we keep in memory no need to query again and again, from the log i can see we query more than 6 times. that's strange. 
The good logical like using hash, if no information in hash then query and add to hash,  if hash hit should not query. 
thanks

**Comment by fd0** [comment]
I'm sorry, but I think this is not an issue. We will later rework the whole index handling, I'll keep this in mind for then. I'm going to close this issue for now, feel free to add further comments.
