### ISSUE TITLE
tree not find in any index

### ISSUE THREAD

**Issue by gluthgao** [restic/restic#1152]
## Output of `restic version`
./restic version
debug log file /Users/gluth/Desktop/test2/restic/gao1.txt
debug enabled
restic 0.7.0 (v0.7.0-19-g38e5640-dirty)
compiled with go1.8.1 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)
Run the ./restic -r mydir prune
then run ./resitc -r mydir check

## What backend/server/service did you use?
my local dir

## Expected behavior
should not report any error

## Actual behavior
it report the error

## Steps to reproduce the behavior
stop in the prune step when it was running in progress, then run prune again.
prune finished successfully, then run check it report the error.

## Do you have any idea what may have caused this?
code problem? we should make sure the all the tree&data will be indexed, when do the prune we probably don't make the consistency between the index and tree&data?  like when failed in some internal steps we missed something, then do second time we can't find the remain steps to make it consistency.

debug enabled
enter password for repository:
{
  "time": "2017-07-24T10:08:44.642229605+08:00",
  "parent": "6ce59c09d5220fc0bfee648237e45e91f75768fd8535e021bbe375abc0e411fd",
  "tree": "689f08a5d497b0d12f92f46a15d55f2e0c0ff4727b98191f7a38287693748644",
  "paths": [
    "/Users/gluth/Desktop/test3"
  ],
  "hostname": "gluthdeMacBook-Pro.local",
  "username": "gluth",
  "uid": 501,
  "gid": 20
}

error for tree 41093a10:
  id 41093a10c73845319ff46d942b7af4a0ea7e2d184d8f48a2cdc2db03cd7c5ee5 not found in any index
error for tree b8847623:
  id b884762357dec215bc066a705fc2a4a7ac67428a02a4bbc1298b273036cbae4c not found in any index
error for tree 29104789:
  id 291047891a2d20fdd4a9f779151e63356197f34ec4d49e112ce7ad13cfc16562 not found in any index
error for tree 8c7ae44b:
  id 8c7ae44b051a8cbfdb4184909401a7334da0bf12e1e613b1f0c92ce584b522ee not found in any index
error for tree 689f08a5:
  id 689f08a5d497b0d12f92f46a15d55f2e0c0ff4727b98191f7a38287693748644 not found in any index
error for tree 812c8a35:
  id 812c8a35e5e5086f72a4206da357d579124b645e2ee2653b7b1fd0889f42c593 not found in any index
Fatal: repository contains errors

you can see the 689f08a5d497b0d12f92f46a15d55f2e0c0ff4727b98191f7a38287693748644 is not in any index but from the snapshot cat command the tree list there.

**Comment by dimejo** [comment]
I think this bug has been fixed with v.0.7.1. You should try again with the latest release.

**Comment by fd0** [comment]
Indeed, this is a serious bug that has been corrected in 0.7.1, I'm therefore closing this issue. You can find a bit of background information [in the blog](https://restic.github.io/blog/2017-07-25/please-upgrade-to-0.7.1).

When you use restic for backup it is a good idea to follow at least one of the update channels: [Twitter: resticbackup](https://twitter.com/resticbackup), the [blog](https://restic.github.io/blog) or [the Atom releases feed](https://github.com/restic/restic/releases.atom).

**Comment by fd0** [comment]
Please be aware that just using 0.7.1 may not bring back the tree blobs that are missing: Those may be lost completely. That's why the bug is so serious (more details in the blog post).
