### ISSUE TITLE
Reference the forum in restic help

### ISSUE THREAD

**Issue by rawtaz** [restic/restic#1155]
Now that there's a forum on the restic site, I suggest that there be some text referencing that in the help text of restic.

The help snippet could list what it does now in terms of commands/arguments, but it could also say something like "If you have any questions, please feel free to visit the restic forum at [URL]".

The intention would be to encourage people to use the forum and making them feel welcome to do so.

**Comment by fd0** [comment]
Nice, great idea!

**Comment by rawtaz** [comment]
For some reason GitHub is completely not functioning for me right now, so I can't edit the post I made, but I meant for there to be a URL at the end of that sentence, of course. And perhaps a "please" in there as well. But anything goes.

**Comment by rawtaz** [comment]
I'm closing this, it doesn't feel very relevant, seems like the forum is gaining visitors anyway :)

**Comment by fd0** [comment]
I've also added it to the "new issue" dialog yesterday, thanks for all the issue gardening!
