### ISSUE TITLE
Data format transparency

### ISSUE THREAD

**Issue by rubenv** [restic/restic#116]
I was thinking about the data format the other day and we might have a problem when it comes to the management side.

Let me explain: one of the things I really like about [BackupPC](http://backuppc.sourceforge.net/) is that it can monitor backups: the server knows when each host has backed up and the server is capable of doing smart backup rotation (deleting the ones that are no longer needed).

Now, BackupPC is capable of doing that because there's no encryption whatsoever, so that's only usable in a situation where you fully trust your sysadmin.

Restic swings the pendulum completely the other way: encrypt all, server knows nothing. This is great for untrusted storage, but it also means you lose a lot of good things in situations where there is slightly more trust: we can't have a smart server implementation that does monitoring, automated replication, disconnected cleanup and e.g. archival of old backups to Amazon Glacier.

I don't think both goals (strong encryption/privacy + smart servers) are incompatible. You can go a long way by exposing just enough data (name of the machine, timestamp, tree structure).

This would complicate things quite a bit (I guess), so it's a matter of deciding whether or not this is a goal for restic.

**Comment by fd0** [comment]
This is easy to do: If the server is trusted, add a password for the server to the repository. Now the server can run fsck and even remove old backups...

For the future, I'm planning to add more crypto similar to what [tarsnap](http://www.tarsnap.com/crypto.html) does. When this is planned, I think we can have a look at this use case again.

**Comment by fw42** [comment]
> add a password for the server to the repository

if the server is trusted and has the decryption key, what's the point of encrypted backups in the first place?

**Comment by tsenart** [comment]
Transport encryption? Prevents MITM attacks.

On Friday, March 27, 2015, Florian Weingarten <notifications@github.com>
wrote:

> add a password for the server to the repository
>
> if the server is trusted and has the decryption key, what's the point of
> encrypted backups in the first place?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restic/restic/issues/116#issuecomment-86973260>.
>


-- 
Sent from Gmail Mobile

**Comment by fd0** [comment]
For the first version, restic will only supports encrypted backups. There may be a non-crypto mode added later on, but for now I'll focus on the scenario where the storage location is untrusted (as that's my main use case).

**Comment by fw42** [comment]
> I'll focus on the scenario where the storage location is untrusted

:+1:

**Comment by rubenv** [comment]
> add a password for the server to the repository

That's "encryption 0", as other backup systems do it. What I'm describing is exposing just enough structure for the server to do maintenance and monitor whether backups are taken, but sufficiently encrypt things so that the server can't read what's in there and can't tamper with things.

Might be hard to do though.

**Comment by fd0** [comment]
I think this is possible but requires asymmetric cryptography. Let's wait until the symmetric case works, then we can tackle this use case.

**Comment by fd0** [comment]
@henryk found a severe attack against attic that allows attackers who can modify the repository to disable encryption. When the backup is atomated, the victim is unable to recognize the attack.

@henryk: great catch!

**Comment by fd0** [comment]
I'll close this issue for now, we can revisit it when we (eventually) add asymmetric encryption. Thanks!
