### ISSUE TITLE
Support XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by mathstuf** [restic/restic#1161]
In addition to `TMPDIR`, it would be nice if restic would use the `XDG_RUNTIME_DIR` as a hint for where to store its temporary files. As per the spec at least, it is per-user rather than global.

**Comment by fd0** [comment]
Good idea, I'd be willing to merge a PR which adds this. Be aware though: We're not handling `TMPDIR` explicitly  but rather use the Go standard library which does this for us. So we need to find all calls to `ioutil.TempFile` and `ioutil.TempDir` and replace it with a custom function e.g. in our `internal/fs` package.

**Comment by middelink** [comment]
Or we just override TMPDIR with the XDG_RUNTIME_DIR at the top of the code if it is set.

**Comment by MichaelEischer** [comment]
Closing this as according to https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html `XDG_RUNTIME_DIR` is not suitable for large files, especially pack files could get quite large.

> Applications should use this directory for communication and synchronization purposes and should not place larger files in it, since it might reside in runtime memory and cannot necessarily be swapped out to disk.
