### ISSUE TITLE
No command besides "init" should create a repository

### ISSUE THREAD

**Issue by mbiebl** [restic/restic#1167]
## Output of `restic version`

restic 0.7.1
compiled with go1.8.3 on linux/amd64

Today, restic scared my good.
I ran ```restic  -r /mnt/bacup/restic snaphosts``` and got

```
unable to open config file: Stat: stat /mnt/bacup/restic/config: no such file or directory
Is there a repository at the following location?
/mnt/bacup/restic
```

I quickly checked /mnt/bacup/restic/ and indeed, the config file was missing. I was already worried that my repository was hosed. Then it dawned on me, that I simply had typoed the repository path (which should have been /mnt/backup/restic).
restic unhelpfully had created a /mnt/bacup/restic directory/repository.

Imho, restic should never auto-create a repository. The only time this should happen is on ```restic init```.
It should simply return an error in such a case.
To reproduce the error, run
``` restic -r /tmp/typo snapshots``` and see that restic has created something at /tmp/typo which looks like a (incomplete) repository.

**Comment by fd0** [comment]
Oh, interesting! That's indeed a bug and I agree with you that only `restic init` should create a repo. Thanks for the report!

**Comment by mbiebl** [comment]
Thanks for the super fast response!
Fwiw, snapshots is  not the only command which currently triggers this behaviour, others like backup or check do so as well.

**Comment by fd0** [comment]
Yeah, I've already triaged the problem ;)

**Comment by mbiebl** [comment]
> Yeah, I've already triaged the problem ;)

You're awesome :-)
