### ISSUE TITLE
Restic process being killed by OOM

### ISSUE THREAD

**Issue by jamesjwarren** [restic/restic#1171]
## Output of `restic version`
restic 0.7.1
compiled with go1.8.3 on linux/amd64

## How did you run restic exactly?
```
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export RESTIC_REPOSITORY=
export RESTIC_PASSWORD=
export TMPDIR='/var/tmp'

restic backup --tag store --files-from "./files-store.conf"
```

## What backend/server/service did you use?
Google Cloud Storage in S3 compatibility mode

## Expected behaviour
Backup to process complete successfully.

## Actual behaviour
Restic process killed ~50% through creating the backup.

## Steps to reproduce the behaviour
Backup a large repo ~1.2TB

## Do you have any idea what may have caused this?
Restic using a large amount of memory ~3GB and being killed by the oom killer, output of dmesg:
```
Out of memory: Kill process 17889 (restic) score 332 or sacrifice child
Killed process 17889 (restic) total-vm:2792044kB, anon-rss:2777972kB, file-rss:0kB
```

**Comment by jamesjwarren** [comment]
Turns out swap was disabled on the machine, I've added some swap space and will try again.

**Comment by jamesjwarren** [comment]
Yeh that fixed it for me, I guess this could still be an issue on machines with limited memory.

**Comment by fd0** [comment]
Hey, thanks for raising this issue. I was busy with real life things for a few days so please excuse the late response. We're aware that restic may use too much memory, we'll work that out eventually. Thanks!
