### ISSUE TITLE
Restic not working with Azure

### ISSUE THREAD

**Issue by CurtWarfield** [restic/restic#1172]
## Output of `restic version`
./restic_0.7.1_linux_amd64 version
restic 0.7.1
compiled with go1.8.3 on linux/amd64

## How did you run restic exactly?

./restic_0.7.1_linux_amd64 -r azure:/backup:/ init

Exported secret key and account name too

## What backend/server/service did you use?
Azure

## Expected behavior

Initialize Azure container/repo

## Actual behavior

$ ./restic_0.7.1_linux_amd64 -r azure:/vmbackup:/ init
create backend at azure:/vmbackup:/ failed: invalid backend
If the repo is in a local directory, you need to add a `local:` prefix

## Steps to reproduce the behavior
See above

## Do you have any idea what may have caused this?
It doesn't appear that restic works with Azure yet.

**Comment by tamalsaha** [comment]
@CurtWarfield , azure support was added to master and not available in 0.7.1 . You can build from source and try the Azure backend. https://github.com/restic/restic/blob/master/CONTRIBUTING.md#development-environment

**Comment by fd0** [comment]
Hey, I was busy with real life issues for a few days. @tamalsaha is right: The Azure support has not been released yet, but you can build the latest master branch which includes it. Since this issue is resolved I'm closing it. Please feel free to add further comments. Thanks!
