### ISSUE TITLE
Backup panics with invalid AccessTime year

### ISSUE THREAD

**Issue by metalmatze** [restic/restic#1173]
## Output of `restic version`

restic 0.7.1
compiled with go1.8.3 on linux/amd64

## How did you run restic exactly?

```bash
restic -r foo-backup/ backup foo
```

## What backend/server/service did you use?

Local Directory

## Expected behavior

Not panic. Maybe it should print a warning. For me this is not a file I really care about, just looks like a random thumbnail.

## Actual behavior

```
restic -r foo-backup/ backup foo
enter password for repository: 
scan [/var/services/homes/metalmatze/foo]
scanned 1168 directories, 18455 files in 0:00
panic: Marshal: json: error calling MarshalJSON for type *restic.Node: node /var/services/homes/metalmatze/foo/Bilder/@eaDir/581086_389180967791572_100000990158327_1099470_849915346_n.jpg/SYNOFILE_THUMB_S.jpg has invalid AccessTime year 4443304: 4443304-04-19 23:12:32 +0100 CET

goroutine 69 [running]:
restic/archiver.(*Archiver).dirWorker(0xc4201946e0, 0xc213e0, 0xc4200123b8, 0xc42011b7d0, 0xc4200824d0, 0xc4203d9260)
	src/restic/archiver/archiver.go:405 +0xcbf
created by restic/archiver.(*Archiver).Snapshot
	src/restic/archiver/archiver.go:713 +0x68b
```

## Steps to reproduce the behavior

Not really sure what the problem with that file is.

`ls` prints:
```
-rwxrwxrwx 1 root root 12318 May 20  2012 /var/services/homes/metalmatze/foo/Bilder/@eaDir/581086_389180967791572_100000990158327_1099470_849915346_n.jpg/SYNOFILE_THUMB_S.jpg

```

## Do you have an idea how to solve the issue?

Not sure if this should really panic.

**Comment by metalmatze** [comment]
These `@eaDir` folders are created by Synology's NAS. 
I'm going to disable their creation as I don't need them.
Might be interesting for debugging purposes nevertheless.

https://www.flynsarmy.com/2013/09/how-to-find-and-remove-eadir-directories-on-synology-nas/

**Comment by fd0** [comment]
Huh, very strange indeed! Restic complains that the access date is invalid, the year is 4443304. Could you please run `stat` on the file and report back?

**Comment by fd0** [comment]
Since we haven't heard anything back I'm closing this issue, if you want to follow along for a similar issue with `mtime`, head over to #2174.
