### ISSUE TITLE
how to list files in a snapshot 

### ISSUE THREAD

**Issue by rupat** [restic/restic#1177]
sorry for asking this simple question but did not find a way in doc or help of restic itself ;)

**Comment by dimejo** [comment]
Use `restic find` to search for a specific file in the repository.

https://restic.readthedocs.io/en/latest/manual.html#under-the-hood-browse-repository-objects

**Comment by fd0** [comment]
You can list a snapshot with the `ls` command, e.g. to list the latest snapshot use:
`restic ls latest`.

The `list` command is indeed for inspecting low-level objects in a repository.

I'm closing this issue for now, please feel free to add further comments.
