### ISSUE TITLE
restic not comparing mtime

### ISSUE THREAD

**Issue by rakoo** [restic/restic#118]
Hello,

First off, thank you for restic, it really is fast and will make for a perfect backup solution !

I made some tests locally, and it looks like the `mtime` of files is not checked and files are always re-read, even if they didn't change; did I miss something or is it expected ?

[Here is the log](https://ghostbin.com/paste/hwfwx) of the first addition of the `restic` binary (i.e the binary is not already in the repo). [Here is the log](https://ghostbin.com/paste/txy5z) of saving the same file in the repo. As you can see the file is re-read (and blobs are correctly re-used, of course) even though I didn't touch it.

`restic` is compiled with debugs from git, commit is 094ca7e635286b289bef72d49db3bec630fb71ba

**Comment by fd0** [comment]
Hey, thanks for giving restic a try!

It seems you did call restic with two completely different directories to backup, is that what you wanted?

At the moment when you want restic to backup the same directory again, you need to specify an old snapshot ID in the paramente `--parent`, like this:

    $ restic -r /tmp/backup backup ~/shared/work/web 
    Enter Password for Repository: 
    scan [/home/fd0/shared/work/web]
    scanned 764 directories, 1816 files in 0:00
    loading blobs
    [0:25] 100.00%  63.492 MiB/s  1.582 GiB / 1.582 GiB  2581 / 2580 items  ETA 0:00 
    duration: 0:25, 64.80MiB/s
    snapshot abdf487d saved

    $ restic -r /tmp/backup backup --parent abdf487d ~/shared/work/web
    Enter Password for Repository: 
    found parent snapshot abdf487dab5b4d2761437cb1a62150c8a0a2025145e55e31582ba20cb08d321f
    scan [/home/fd0/shared/work/web]
    scanned 764 directories, 1816 files in 0:00
    loading blobs
    [0:00] 100.00%  0B/s  1.582 GiB / 1.582 GiB  2581 / 2580 items  ETA 0:00 
    duration: 0:00, +InfMiB/s
    snapshot 8d56c854 saved

Once #105 is implemented, restic will find the parent snapshot automatically.

**Comment by rakoo** [comment]
Ah true, I pasted the wrong log for the addition of the binary.

Alright, so this one's a duplicate of #105 then :)
