### ISSUE TITLE
Deleting passwords.

### ISSUE THREAD

**Issue by yerrysherry** [restic/restic#1180]
Hallo,

Once you have a password from a repository, you can do a lot of things, even deleting passwords from other users like root. I hope this is a know issue. As a sysadmin, I start backup's from the cron but when other people can delete my password key this will break my backup's and my restore. 

Regards,
Gerrit

**Comment by fd0** [comment]
Hi, thanks for the question. I'm not sure that I understood you correctly (and unfortunately you did not fill out the issue template), could you elaborate a bit on your setup? What backend do you use?

As far as I understood, you have a machine that uses restic to regularly create backups via cron. Then we assume an attacker gets access to the machine and can access the files created by restic. What I don't understand is this: An attackers with access to the restic repository files can just delete all passwords by removing the files in the `keys/` directory, without knowing a single password.

In restic, a password is used to decrypt the repository master keys (from one of the files in the `keys/` directory). It is **not** used for restricting access to the encrypted files in the repository. When attackers manage to delete files in the repository, that cannot be prevented with restic.

Was that what you meant? Did I understood you correctly?

**Comment by yerrysherry** [comment]
Hallo,

Sorry, here some more info:

I made 2 serves with virtualbox. 
 - restic (192.168.59.103/24) 
 - minio (latest version, 192.168.59.104/24) 

Following commands I execute on restic.

root@restic:~# restic version
restic 0.7.1
compiled with go1.8.3 on linux/amd64
root@restic:~# cat restic.sh (some environment variables)
export AWS_ACCESS_KEY_ID=4X45BUL0ZWSDPWAL6YMD
export AWS_SECRET_ACCESS_KEY=aXlTlyc0Da53rVhSwKJaPvMA8gLC2DmfEEcrpuGJ

export RESTIC_REPOSITORY=s3:http://192.168.59.104:9000/restic
#export RESTIC_PASSWORD=serege

root@restic:~# restic init
enter password for new backend:
enter password again:
created restic backend 1020a38d3a at s3:http://192.168.59.104:9000/restic

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

Now, I create a new user, bob. He is a developer and want doing some backups.

root@restic:~# adduser bob (password = bob)
root@restic:~# su - bob
bob@restic:~$ source restic.sh

bob@restic:~$ restic key list
enter password for repository: serege
 ID          User        Host        Created
----------------------------------------------------------------------
*8b168184    root        restic      2017-08-27 07:11:49

bob@restic:~$ restic key add
enter password for repository: serege
enter password for new key: bob
enter password again: bob
saved new key as <Key of bob@restic, created on 2017-08-27 07:18:16.74422432 +0200 CEST>

Now, I tell bob that he can backup with restic. He log into the server and 

bob@restic:~$ restic key list
enter password for repository: bob
 ID          User        Host        Created
----------------------------------------------------------------------
*23896154    bob         restic      2017-08-27 07:18:16
 8b168184    root        restic      2017-08-27 07:11:49

and deleted the key of root.

bob@restic:~$ restic key rm 8b168184
enter password for repository: bob
removed key 8b168184e0fb0a2460999b3eca6d594b3753571a5b2841e4df2c0d0bee00b768

bob@restic:~$ restic key list
enter password for repository: bob
 ID          User        Host        Created
----------------------------------------------------------------------
*23896154    bob         restic      2017-08-27 07:18:16

Bob deleted the password of root. I think this is a problem because when root have some cron jobs for backup they fail and root has no more control over the backup. He can not execute restic forget and prune commands.

Regards,
Gerrit

**Comment by fd0** [comment]
So, the user `bob` has regular access to the credentials for the Minio server. In this case, he can just use an s3 client program to delete all data in the backup. There's nothing restic can do about that, this is not an issue in restic.

If you want `bob` not to have write access to the backup location, then don't give him access. You could for example use two different Minio servers with different credentials for the two different users, and make sure that the user `bob` is unable to read the shell script containing the access credentials for the other user.

I'm going to close this issue for now, feel free to add further comments. Thanks!

**Comment by yerrysherry** [comment]
It is clear now. Thank you very much for your time and explanation.
