### ISSUE TITLE
restic hangs when b2.connections is set to 1

### ISSUE THREAD

**Issue by armhold** [restic/restic#1188]
Setting b2.connections >= 2 overloads my internet connection. Setting it = 1 causes restic to hang.

## Output of `restic version`
```
restic compiled manually
compiled with go1.8.3 on darwin/amd64
```

(was built from restic/restic master on Aug 10).

## How did you run restic exactly?

I have set RESTIC_PASSWORD,  B2_ACCOUNT_ID and  B2_ACCOUNT_KEY appropriately. 

Then I use the following bash alias: 

`alias restic-b2='caffeinate restic -r b2:MY-BUCKET:restic backup ~ /Volumes/data1 --hostname george-iMac --exclude-file ~/restic-excludes --exclude-file ~/s3-excludes -o b2.connections=1'`

NB: `caffeinate` is a standard macOS program that prevents the computer from going to sleep while running another shell command.

## What backend/server/service did you use?

B2

## Expected behavior

restic should not hang when using only a single b2.connection. 

## Actual behavior

Restic seems to hang, does not even get to the "scan" phase (as far as I can tell) and does not produce a single line of output after several hours.

## Steps to reproduce the behavior

Set vars as above to real credential values, then run `restic-b2` as a non-root user in bash.

## Do you have any idea what may have caused this?

Wondering if perhaps there is a deadlock situation regarding worker threads.

## Do you have an idea how to solve the issue?

I can run a debug build if you think that would be helpful.

**Comment by armhold** [comment]
Just to remove ambiguities, I reproduced the problem with latest master:

```
debug enabled
restic 0.7.1 (v0.7.1-89-g4e60156b)
compiled with go1.9 on darwin/amd64
```

I have captured a debug log, but would ask for some help in redacting info... is it enough to `grep -v` out my b2 credentials? I suspect the `Authorization` headers, etc are also sensitive. What about restic index file names? Presumably these are just hashes, and not sensitive? 

I am not concerned about filenames, paths, etc of my own data (it's just dummy data which I created for testing). Thanks.

**Comment by armhold** [comment]
I also find that the proc is not killable via ^c when it gets stuck. restic responds with "Interrupt received, cleaning up", but I can't get it to exit. I *can* kill it if I suspend it first (^z followed by ^c again).

**Comment by fd0** [comment]
The restic file names are not sensitive, it's the SHA256 hash of the encrypted files. That's of no use for anybody ;)

**Comment by armhold** [comment]
The bug is fairly reproducible using the following steps:

1. init a new b2 repo
2. do an initial backup of at least a few hundred MB.
3. keep doing incrementals of the existing data (no need to add new files) using "-o b2.connections=1" until you get a hang.

The attached debug log is from the hang (3rd incremental) below.

Annotated example follows.

```
[armhold@george-iMac]$ restic-debug version
debug log file /Volumes/data1/restic-debug.log
debug enabled
restic 0.7.1 (v0.7.1-89-g4e60156b)
compiled with go1.9 on darwin/amd64


directory we will backup:
```
[armhold@george-iMac]$ ls -l fodder1
total 583576
-rw-r--r--  1 armhold  staff         35 Aug 30 08:10 dummy.txt
-rw-r--r--  1 armhold  staff  298784000 Aug 29 09:14 random1.dat
```

initial (full) backup:
```
[armhold@george-iMac]$ restic-debug -r b2:beta-restic:restic backup ~/fodder1  -o b2.connections=1
debug log file /Volumes/data1/restic-debug.log
debug enabled
body not drained, 1 bytes not read, body: "."
scan [/Users/armhold/fodder1]
scanned 1 directories, 2 files in 0:00
body not drained, 1 bytes not read, body: "\x82".943 MiB  3 / 3 items  0 errors  ETA 0:00 
[8:41] 100.00%  560.040 KiB/s  284.943 MiB / 284.943 MiB  3 / 3 items  0 errors  ETA 0:00 
duration: 8:41, 0.55MiB/s
snapshot e88afae9 saved
body not drained, 1 bytes not read, body: "\x99"
```

1st incremental (no file changes), succeeds:
```
[armhold@george-iMac]$ restic-debug -r b2:beta-restic:restic backup ~/fodder1  -o b2.connections=1
debug log file /Volumes/data1/restic-debug.log
debug enabled
body not drained, 1 bytes not read, body: "."
using parent snapshot e88afae9
scan [/Users/armhold/fodder1]
scanned 1 directories, 2 files in 0:00
[0:05] 100.00%  56.989 MiB/s  284.943 MiB / 284.943 MiB  3 / 3 items  0 errors  ETA 0:00 
duration: 0:05, 50.48MiB/s
snapshot 92d171d1 saved
body not drained, 1 bytes not read, body: "\xcd"
```

2nd incremental (no file changes), succeeds:
```
[armhold@george-iMac]$ restic-debug -r b2:beta-restic:restic backup ~/fodder1  -o b2.connections=1
debug log file /Volumes/data1/restic-debug.log
debug enabled
body not drained, 1 bytes not read, body: "."
using parent snapshot 92d171d1
scan [/Users/armhold/fodder1]
scanned 1 directories, 2 files in 0:00
[0:03] 100.00%  94.981 MiB/s  284.943 MiB / 284.943 MiB  3 / 3 items  0 errors  ETA 0:00 
duration: 0:03, 91.45MiB/s
snapshot 3ff314fc saved
body not drained, 1 bytes not read, body: "\xca"
```

3rd incremental (no file changes), but HANGS. The attached restic-debug.log is from this (hung) session):
```
[armhold@george-iMac]$ restic-debug -r b2:beta-restic:restic backup ~/fodder1  -o b2.connections=1
debug log file /Volumes/data1/restic-debug.log
debug enabled
body not drained, 1 bytes not read, body: "."
```
[restic-debug.log.gz](https://github.com/restic/restic/files/1263793/restic-debug.log.gz)

**Comment by armhold** [comment]
I think I see what's going on here. 

`(r *Repository) LoadIndex(ctx context.Context)` will start up 20 worker threads, each of which will
call `LoadIndex() -> LoadIndexWithDecoder() -> repo.LoadAndDecrypt() -> be.Load()`.

In each of these 20 workers, the b2 implementation of `be.Load()` will block on `be.sem.GetToken()`, since b2.connections=1. Normally that's fine, they'll just run sequentially.  

But meanwhile back in `(r *Repository) LoadIndex(ctx context.Context)()`,
`FilesInParallel()` is called to run the workers. Preceding the loop that processes the workers is a call to `repo.List()`. And 
`(be *b2Backend) List()` tries to grab another token on line 299:
```
	be.sem.GetToken()
```

So simplified, if one of the workers manages to start while `List()` is still holding a token, you get
deadlock. I'm not sure what a proper the solution is, but I hope I described the problem clearly.

**Comment by fd0** [comment]
Thanks for the analysis!
