### ISSUE TITLE
internal/crypto: Decrypt overlap rules are a bit off

### ISSUE THREAD

**Issue by FiloSottile** [restic/restic#1190]
There seems to be a problem with the `Decrypt` overlap rules:

> plaintext and ciphertext may point to (exactly) the same slice.

The `cipher.Stream` interface implemented by CTR mode says this at the method `XORKeyStream`:

> Dst and src may point to the same memory.

Which isn't that helpful. There is already a discussion about it at golang/go#21279 but I think it means that `dst` and `src` may overlap entirely (without misalignment) or not at all.

However, calling `Decrypt` with the same buffer for plaintext and ciphertext (as done throughout the code and allowed by the docs) means that `buf[16:]` is decrypted into `buf[:]` because of the IV. That's theoretically(?) not ok.

I don't think it's a problem right now, but it might become one as the CTR implementation [is optimized](https://github.com/golang/go/issues/20967).

Also, I'm not sure what this is supposed to mean in the `Encrypt` docs, but overlapping buffers are never used in the codebase anyway.

> ciphertext and plaintext may not point to (exactly) the same slice or non-intersecting slices.

**Comment by FiloSottile** [comment]
Looks like Decrypt will panic when golang/go#21624 happens.

**Comment by FiloSottile** [comment]
A nice standard API to consider might be to make `Key` implement `cipher.AEAD` with AES256-Poly1305-AES, and move IV splitting to the callers.

**Comment by fd0** [comment]
Ah, that's indeed a thing we should resolve, good catch!

**Comment by FiloSottile** [comment]
I'd definitely return an error 👍

**Comment by cstockton** [comment]
@FiloSottile Happened to read on r/golang about restic and saw this issue. It's not immediately clear to me right now if the [buffer reuse](https://github.com/restic/restic/pull/731#issuecomment-274297676) which I try to avoid in general is being FORBIDDEN or ALLOWED here? When I interpreted the doc comments in https://github.com/restic/restic/pull/731#issuecomment-274315898 the language seemed to be granting specific permission to ALLOW buffer reuse, was it meant to be interpreted as a implementation detail of the interface which would imply such use is unsafe?

**Comment by FiloSottile** [comment]
Buffer reuse is allowed, if and only if the two slices overlap entirely. This is globally defined by the interface. golang/go#21279 is about to make the wording clearer.

**Comment by fd0** [comment]
Meh, closed prematurely ;)

**Comment by fd0** [comment]
@FiloSottile I've added changes in #1397 which makes `*crypto.Key` implement `cipher.AEAD`. I like the code! Would you mind reviewing the changes if you have time?
