### ISSUE TITLE
Panic during backup

### ISSUE THREAD

**Issue by yerrysherry** [restic/restic#1192]
## Output of `restic version`

```
 ./restic version
restic 0.7.1
compiled with go1.8.3 on linux/amd64
```

## How did you run restic exactly?

```
 crontab -l
6 0 * * * /opt/admin/scripts/restic.sh > /var/tmp/restic.log 2> /var/tmp/restic.err

 cat /opt/admin/scripts/restic.sh
export AWS_ACCESS_KEY_ID=XXX
export AWS_SECRET_ACCESS_KEY=XXX

export RESTIC_REPOSITORY=s3:http://minio-s3-restic-pr-1
[sar.output.gz](https://github.com/restic/restic/files/1259189/sar.output.gz)

:9000/backup
export RESTIC_PASSWORD=restic

/opt/admin/scripts/restic backup /opt/tomcat/data
```

## What backend/server/service did you use?

Minio S3

## Expected behavior

That everything went fine

## Actual behavior
Backup started around 00:00

```
 ls -l /var/tmp/
total 12
-rw-r--r-- 1 root root  371 Aug 29 03:16 restic.err
-rw-r--r-- 1 root root  128 Aug 29 00:27 restic.log

 cat /var/tmp/restic.log
scan [/opt/tomcat/data]
[20:59] 389087 directories, 6437037 files, 3.990 TiB
scanned 389087 directories, 6437037 files in 20:59
```

## Steps to reproduce the behavior

Execute crontab command again. 

## Do you have any idea what may have caused this?

```
 cat /var/tmp/restic.err
panic: client.PutObject: The specified key does not exist.

goroutine 1910874 [running]:
restic/archiver.(*Archiver).saveChunk(0xc420151c70, 0xc213e0, 0xc420074338, 0x0, 0x6d800, 0x1, 0xc430c02000, 0x6d800, 0x80000, 0xc4201bc000, ...)
	src/restic/archiver/archiver.go:165 +0x395
created by restic/archiver.(*Archiver).SaveFile
	src/restic/archiver/archiver.go:239 +0x3a4
```

## Do you have an idea how to solve the issue?

No, maybe file disappeared during backup? (ex. log file, ...)

## More info

This filesystem is nearly 4 TB. The minio backend is at an other datacenter. Between them there is a 10Gb connection. In the syslog at the minio server I see:

```
#cat /var/log/syslog
Aug 29 00:55:07 localhost minio[7321]: time="2017-08-29T02:55:07+02:00" level=error msg="Unable to peek into incoming protocol" cause="read tcp 10.34.31.187:9000->10.34.32.161:60230: i/o timeout" source="[server-mux.go:262:newListenerMux.func1.1()]"
Aug 29 00:55:07 localhost minio[7321]: time="2017-08-29T02:55:07+02:00" level=error msg="Unable to peek into incoming protocol" cause="read tcp 10.34.31.187:9000->10.34.32.161:60228: i/o timeout" source="[server-mux.go:262:newListenerMux.func1.1()]"
Aug 29 00:55:31 localhost minio[7321]: time="2017-08-29T02:55:31+02:00" level=error msg="Unable to peek into incoming protocol" cause="read tcp 10.34.31.187:9000->10.34.32.161:60240: i/o timeout" source="[server-mux.go:262:newListenerMux.func1.1()]"
```

A check does not work.
```
./restic check
Create exclusive lock for repository
repository is already locked by PID 20498 on dms-pr-1 by  (UID 0, GID 0)
lock was created at 2017-08-29 00:06:02 (7h15m33.475192963s ago)
storage ID 52bb6c10
the `unlock` command can be used to remove stale locks
```
I can unlock it but how do  I cleanup the backup data because I do not see them in the snapshot list.

Regards,
Gerrit

**Comment by fd0** [comment]
Hm, interesting. What's the Minio version?

@harshavardhana can you please take a quick look?

**Comment by harshavardhana** [comment]
@yerrysherry https://github.com/minio/minio/issues/4727 we fixed a similar issue in this regard here. Can you try the latest release?

**Comment by yerrysherry** [comment]
root@minio-s3-restic-pr-1:~# /opt/minio/minio version
Version: 2017-06-13T19:01:01Z
Release-Tag: RELEASE.2017-06-13T19-01-01Z
Commit-ID: 353f2d3a6e30f595a721abcd9cf1b108b041ee21

root@minio-s3-restic-pr-1:~# df -h
Filesystem                             Size  Used Avail Use% Mounted on
....
/dev/mapper/opt_minio_data_vg-data_lv  9.7T  609G  8.7T   7% /opt/minio/data

As you see 609 GB backup that is allocated from a previous restic backup (2x) and is probably useless.

root@dms-pr-1:/opt/admin/scripts# ./restic check
Create exclusive lock for repository
repository is already locked by PID 20498 on dms-pr-1 by  (UID 0, GID 0)
lock was created at 2017-08-29 00:06:02 (8h58m9.937296669s ago)
storage ID 52bb6c10
the `unlock` command can be used to remove stale locks
root@dms-pr-1:/opt/admin/scripts# ./restic unlock
successfully removed locks
root@dms-pr-1:/opt/admin/scripts# ./restic check
Create exclusive lock for repository
Load indexes
pack 13457663 contained in several indexes: {02286b93 b9481227}
pack 9650c374 contained in several indexes: {4ea910ed 68ed2e3a}
pack 7b4f0a8b contained in several indexes: {355a6d9f 81a75f35}
pack 4244fdeb contained in several indexes: {8918c1c9 ddb510d2}
....
pack d7257b9e contained in several indexes: {0e34c60e a0ef3e59}
pack b6cf26a4 contained in several indexes: {0c7aedfb ddde8a58}

run `restic rebuild-index' to correct this
Check all packs

pack 000e9a94e614485ecaa400293ce1c492dbb2b049c8a91ba6888b153ca2c7ee87: not referenced in any index
pack 008d6dbca9b0e939c7abb72908b39e8d836e0c34bc96be2cc6cb12a52be270ba: not referenced in any index
...
pack ff6acc7b81aac9e2d3ae72dd8ef4c1fa5120c08b66e58dc3090c9ffa28b3f18d: not referenced in any index
pack ffeb002aafac8bf3f1e59c9c48c4e104ff87cb1d2741b130e053084287654aab: not referenced in any index
Check snapshots, trees and blobs
Fatal: repository contains errors
root@dms-pr-1:/opt/admin/scripts#
root@dms-pr-1:/opt/admin/scripts# ./restic snapshots
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
5ddd2bfc  2017-08-28 16:06:25  dms-pr-1                /etc
c1a80ca4  2017-08-28 16:10:02  dms-pr-1                /etc

root@dms-pr-1:/opt/admin/scripts# ./restic check
Create exclusive lock for repository
Load indexes
pack 7c5e1357 contained in several indexes: {a15191ab c07c5b71}
pack c5b2695f contained in several indexes: {b4c7d04f ddde8a58}
....
pack 598099f7 contained in several indexes: {818dad4c aff6fe5b}
pack 7b4f0a8b contained in several indexes: {355a6d9f 81a75f35}

run `restic rebuild-index' to correct this
Check all packs
pack 000e9a94e614485ecaa400293ce1c492dbb2b049c8a91ba6888b153ca2c7ee87: not referenced in any index
pack 008d6dbca9b0e939c7abb72908b39e8d836e0c34bc96be2cc6cb12a52be270ba: not referenced in any index
pack 008e506db2075115489ac9b331e8a69b05555313ddfa1f513b03d5d266d63547: not referenced in any index
....
pack ff6acc7b81aac9e2d3ae72dd8ef4c1fa5120c08b66e58dc3090c9ffa28b3f18d: not referenced in any index
pack ffeb002aafac8bf3f1e59c9c48c4e104ff87cb1d2741b130e053084287654aab: not referenced in any index
Check snapshots, trees and blobs
Fatal: repository contains errors
root@dms-pr-1:/opt/admin/scripts# ./restic rebuild-index
counting files in repo
[11:20] 100.00%  129197 / 129197 packs
finding old index files
saved new index as 98ac5e20
remove 139 old index files

root@dms-pr-1:/opt/admin/scripts# ./restic rebuild-index
counting files in repo
[5:31] 100.00%  129197 / 129197 packs
finding old index files
saved new index as dbe30d92
remove 1 old index files

I start the backup by cron:
15 22 * * * /opt/admin/scripts/restic.sh > /var/tmp/restic.log 2> /var/tmp/restic.err

The 2 Ubuntu servers are kvm, running on OpenNebula. The storage backend is both on Ceph.

root@dms-pr-1:/opt/admin/scripts# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

root@minio-s3-restic-pr-1:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

I started back the backup:

root       651     1  0 Aug03 ?        Ss     0:11 /usr/sbin/cron -f
root     18002   651  0 22:15 ?        S      0:00  \_ /usr/sbin/CRON -f
root     18003 18002  0 22:15 ?        Ss     0:00      \_ /bin/sh -c /opt/admin/scripts/restic.sh > /var/tmp/restic.log 2> /var/tmp/restic.err
root     18004 18003  0 22:15 ?        S      0:00          \_ /bin/sh /opt/admin/scripts/restic.sh
root     18005 18004 21 22:15 ?        Sl     0:48              \_ /opt/admin/scripts/restic backup /opt/tomcat/data

root@dms-pr-1:/opt/admin/scripts# prlimit -p 18005
RESOURCE   DESCRIPTION                             SOFT      HARD UNITS
AS         address space limit                unlimited unlimited bytes
CORE       max core file size                         0 unlimited blocks
CPU        CPU time                           unlimited unlimited seconds
DATA       max data size                      unlimited unlimited bytes
FSIZE      max file size                      unlimited unlimited blocks
LOCKS      max number of file locks held      unlimited unlimited
MEMLOCK    max locked-in-memory address space     65536     65536 bytes
MSGQUEUE   max bytes in POSIX mqueues            819200    819200 bytes
NICE       max nice prio allowed to raise             0         0
NOFILE     max number of open files              131072    131072
NPROC      max number of processes                39956     39956
RSS        max resident set size              unlimited unlimited pages
RTPRIO     max real-time priority                     0         0
RTTIME     timeout for real-time tasks        unlimited unlimited microsecs
SIGPENDING max number of pending signals          39956     39956
STACK      max stack size                       8388608 unlimited bytes

Gerrit

**Comment by harshavardhana** [comment]
> root@minio-s3-restic-pr-1:~# /opt/minio/minio version
> Version: 2017-06-13T19:01:01Z
> Release-Tag: RELEASE.2017-06-13T19-01-01Z
> Commit-ID: 353f2d3a6e30f595a721abcd9cf1b108b041ee21

You would have to updated @yerrysherry to latest for this issue to be fixed `RELEASE.2017-08-05T00-00-53Z`

**Comment by yerrysherry** [comment]
This morning (Belgium time), restic was still running. But around 9:30 AM in oom killer killed my minio kvm. 3 GB memory is not enough. Now, the minio kvm 8 GB RAM and the latest minio version.

Later the restic client (dms-pr-1) was also killed by the oom service. So, when the backend store is losed. restic do not see it and keep running. 

root@minio-s3-restic-pr-1:/opt/minio/data/backup# free -mt
              total        used        free      shared  buff/cache   available
Mem:           5967          74        5587          10         305        5636
Swap:          2047           0        2047
Total:         8015          74        7635
root@minio-s3-restic-pr-1:/opt/minio/data/backup# /opt/minio/minio version
Version: 2017-08-05T00:00:53Z
Release-Tag: RELEASE.2017-08-05T00-00-53Z
Commit-ID: aeafe668d8b6d25caac671d59e2b0f0473ce35d0

Thx, harshavardhana for the info!!

**Comment by harshavardhana** [comment]
> This morning (Belgium time), restic was still running. But around 9:30 AM in oom killer killed my minio kvm. 3 GB memory is not enough. Now, the minio kvm 8 GB RAM and the latest minio version.

Do you have a OOM kernel trace when this occurred?  would be interesting to look at. Was this trace also with the latest or old version?

**Comment by yerrysherry** [comment]
Yes, this was with the older version of minio. Meanwhile, everything is working. The backup is now running for 20 hours.

Because of the oom killing, I created 3 GB of swap space. 

You see that restic take a lot of RSZ memory, that's probably the restic process was killed.

root@dms-pr-1:~# ps  -u root -o pid,user,vsz,rss,comm,args |egrep '(PID|restic)'
  PID USER        VSZ   RSS COMMAND         COMMAND
 9403 root      11288   964 grep            grep -E --color=auto (PID|restic)
13974 root       4508   640 sh              /bin/sh -c /opt/admin/scripts/restic.sh > /var/tmp/restic.log 2> /var/tmp/restic.err
13975 root       4508   588 sh              /bin/sh /opt/admin/scripts/restic.sh
13976 root     3332800 3022640 restic       /opt/admin/scripts/restic backup /opt/tomcat/datash

df -h
/dev/mapper/opt_tomcat_data_vg-data_lv  6.0T  4.1T  1.7T  71% /opt/tomcat/data

On the minio server:

root@minio-s3-restic-pr-1:~# free -mt
              total        used        free      shared  buff/cache   available
Mem:           5967         653         139          10        5173        4992
Swap:          2047           0        2047
Total:         8015         653        218
root@minio-s3-restic-pr-1:~# ps  -u minio -o pid,user,vsz,rss,comm,args |egrep '(PID|minio)'
  PID USER        VSZ   RSS COMMAND         COMMAND
  793 minio    617280 600764 minio          /opt/minio/minio server --address :9000 /opt/minio/data

df -h

/dev/mapper/opt_minio_data_vg-data_lv  9.7T  2.2T  7.2T  23% /opt/minio/data

Gerrit

**Comment by fd0** [comment]
So, can we close this issue? It looks like it is resolved

**Comment by yerrysherry** [comment]
Yes, but the only problem is that we need 3 GB extra RAM or swap space for backing up 4 TB, otherwise the oom killer gets active. Is  deduplication taking a lot of ram?

**Comment by fd0** [comment]
I'm not sure yet what makes restic use so much RAM. You can try running it with `GOGC=20` (default is `100`) in order to instruct the garbage collector to release memory earlier.
