### ISSUE TITLE
Implementing Jottacloud

### ISSUE THREAD

**Issue by jkaberg** [restic/restic#1193]
Continuing the chat we had on IRC the other day: my goal is to implement [Jottacloud](https://jottacloud.com/en/about.html) as a backend for Restic to store data on. Jottacloud offers a free tier with 5GB of storage, while the main offering is an unlimited plan for £7.5/month.

Jottacloud is hosted and operating out of Norway, and they have an [warrant canary](https://www.jottacloud.com/canary/).

**Comment by fd0** [comment]
Hm, a couple of questions:
 * What's the status of their API? Is there documentation?
 * Do they allow range queries? Is there a way to run integration tests against the live service?
 * Is there a stable client implementation for Go?

To be honest I'm skeptical that this is the right service to implement for restic. After all, once we'll add the backend we're stuck with it and forced to maintain it. So it's only valueable to do that if someone steps up and debugs issues that come up, and there should be enough users regularly using it.

**Comment by fawick** [comment]
Maybe a server for the REST-API that works on Jottacloud but is maintained as a third-party-project would be the best way to proceed here.

**Comment by jkaberg** [comment]
@fawick I was actully thinking the same. @fd0 has some valid points.

Will let you know how I proceed.

**Comment by phunni** [comment]
I know this is only a couple of weeks old, but I was wondering if there was any news?

**Comment by ailox** [comment]
For anyone reading this: Jottacloud can be used with the rclone backend. For this to work, you have to set your account up in rclone first, then use restic with a repository like `rclone:jotta:backup/path`.

I think this old issue can therefor be closed.

**Comment by jkaberg** [comment]
@ailox yeah your right 😄 closeing

**Comment by guysoft** [comment]
Hey, there is an issue with rclone when doing this, because the local drive cache gets full and eventually runs out of space. I had an issue when doing that using rclone and borgbackup.
So I am not sure this would work
