### ISSUE TITLE
Directory nodes only have the permission bits set

### ISSUE THREAD

**Issue by rakoo** [restic/restic#120]
`node.go` has this in [`NodeFromFileInfo`](https://github.com/restic/restic/blob/f02865a205d1f883a7e2692fdb0e459cf30b7ed8/node.go#L60):

```go
node := &Node{
    [...]
    Mode: fi.Mode() & os.ModePerm,
    [...]
}
```

Because of this, all the `os.ModeType` bits aren't set.

I saw this while building the fuse command: you can't `switch` on the node's mode, you have to manually check if it's a `"dir"` or a `"file"`. It's ok for the moment but it may be an issue later.

Is there a reason why `Mode` only has the perm bits ?

**Comment by fd0** [comment]
Thanks for reporting this, it's a bug and I'll fix it. I think it's a bit redundant to have the mode bits and the `type` json key, but that's okay.
