### ISSUE TITLE
Complimentary projects page?

### ISSUE THREAD

**Issue by LaszloHont** [restic/restic#1208]
I'd like to give restic to my windows-loving family members, with a gui if possible. Is it too early for a page for complimentary projects/wrappers for restic?

**Comment by mholt** [comment]
Not sure if you saw this already, but we've been talking about this on the forum: https://forum.restic.net/t/anyone-working-on-a-user-friendly-frontend-to-restic/116?u=matt

**Comment by fd0** [comment]
I'm not sure how well restic can be wrapped at the moment, since that's not our primary objective (at least not for now). :)

Let's move the discussion to the forum, and close this issue here. Thanks!
