### ISSUE TITLE
Compact snapshots view

### ISSUE THREAD

**Issue by mrzv** [restic/restic#1218]
It would be nice if the `snapshots` command had an option to give a compact view of the snapshots. Currently, it lists all the directories passed to the `backup` command when the snapshot was made. When there is a dozen of these in each snapshot, the screen real estate is very quickly wasted. If there was a `--compact` option that listed just the first line, without the directory list, it would be much easier to scan what's available in the repository.

**Comment by fd0** [comment]
Good idea, I've just merged your PR.
