### ISSUE TITLE
Changing the hostname results in expensive rescan

### ISSUE THREAD

**Issue by mbiebl** [restic/restic#1221]
## Output of `restic version`

restic 0.7.1
compiled with go1.8.3 on linux/amd64

I have a restic setup where I use a local rest-server [1] storing the files on a locally attached disk. I then run restic on a remote host via SSH using the rest transport (```RESTIC_REPOSITORY=rest:https://...```)

Typically a backup of that remote system is rather fast (a few minutes).
Today I decided that the hostname I had chosen for the remote system was not ideal, so I changed it via ```restic --hostname=```.
The result was that restic took a really long time to complete. I didn't use a stopwatch, but it was around an hour or so. During that time, almost no data was transmitted.
I'm not entirely sure what was going on and why.
If this behaviour is expected, could this please be documented in the man page for the --hostname flag.

[1] https://github.com/restic/rest-server

**Comment by mbiebl** [comment]
I need to add that subsequent runs with the new hostname are fast again. It was only the first run after the hostname change which is slow.

**Comment by fd0** [comment]
Your observation can be easily explained, although I agree that from the outside it isn't obvious why restic reacts this way.

When a backup is started, restic tries to find a previous snapshot for the same directories on the same host to use as a template (so it can detect if files have been modified, and use the data from the previous snapshot if that's not the case). It uses the list of directories and the host name to find this previous snapshot. When you set the host name to something new manually (via `restic backup --hostname`), it cannot find a previous snapshot.

Then restic behaves as if `restic backup --force` was used: It doesn't know if files have been modified, so it reads all files and hashes the contents. It then detects that all data for the files to be saved is already in the repo, so it just makes a note of the metadata of the file and continues to the next file. That's what happened during the time almost no data was transmitted. It took some time to read and hash the data again.

I agree that we can add a note somewhere, do you have a good idea where? In the help text of the `--hostname` option?

**Comment by mbiebl** [comment]
Thanks for the quick answer. I was already expecting that this somehow was a forced rescan, but didn't know why. Your explanation was very helpful. Adding that information (in a shorter form) to the help text (and man page) for the ```--hostname``` option would be useful. Especially with the hint about ```--parent```. I wasn't aware that I could have avoided that costly rescan by using that option.
