### ISSUE TITLE
"Invalid data returned" when loading index

### ISSUE THREAD

**Issue by rawtaz** [restic/restic#1229]
## Output of `restic version`
~~~
restic 0.7.1 (v0.7.1-62-g03e39b2)
compiled with go1.8 on darwin/amd64
~~~

This is the add-cache branch, by the way 👍 

## How did you run restic exactly?
`date && sudo ./restic -r sftp://HOSTNAME/restic backup ~/Library/Mail/`

## What backend/server/service did you use?
SFTP on a machine of my own.

## Expected behavior
Not seeing the below stack trace.

## Actual behavior
~~~
enter password for repository:
load <index/4fc62d740f>: invalid data returned
github.com/restic/restic/internal/repository.(*Repository).LoadAndDecrypt
	src/github.com/restic/restic/internal/repository/repository.go:78
github.com/restic/restic/internal/repository.LoadIndexWithDecoder
	src/github.com/restic/restic/internal/repository/index.go:558
github.com/restic/restic/internal/repository.LoadIndex
	src/github.com/restic/restic/internal/repository/repository.go:436
github.com/restic/restic/internal/repository.(*Repository).LoadIndex.func1
	src/github.com/restic/restic/internal/repository/repository.go:378
github.com/restic/restic/internal/repository.ParallelWorkFuncParseID.func1
	src/github.com/restic/restic/internal/repository/parallel.go:74
github.com/restic/restic/internal/repository.FilesInParallel.func1
	src/github.com/restic/restic/internal/repository/parallel.go:39
runtime.goexit
	/usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:2197
~~~

## Steps to reproduce the behavior
Probably to cut off the network connection to the backend at the very end of the backup (approximately at 99.95%) while the index is being uploaded. This is what happened to the backup run just before this one (the computer was put to sleep and then moved from the network), and is likely what caused the issue.

## Do you have any idea what may have caused this?
Yes, the above? Are you not reading what I'm trying to tell you? I thought we already had this conversation, I thought we worked it through.. 😞 💔 

## Do you have an idea how to solve the issue?
Prod @fd0 with a slimy stick until he's annoyed enough to look into it.

It was however suggested by him that I delete the index file (or rather, the index file starting with that hash in the error message) manually, and doing so made it work again.

**Comment by fd0** [comment]
Run `rebuild-index`, it'll be cleaned up afterwards.

**Comment by sheerun** [comment]
I get the same error  (Fatal: load <index/c9b29647e7>: invalid data returned) but rebuild-index is not helping... it returns the same error

**Comment by maxkratz** [comment]
> I get the same error (Fatal: load <index/c9b29647e7>: invalid data returned) but rebuild-index is not helping... it returns the same error

I had the same error some minutes ago and `rebuild-index` did not work either. Clearing the restic cache in `~/.cache/restic` and then running `rebuild-index` did the trick for me.

**Comment by sheerun** [comment]
FYI cache dir in MacOS is in `/Users/sheerun/Library/Caches/restic`
