### ISSUE TITLE
Implement repository configuration file

### ISSUE THREAD

**Issue by fd0** [restic/restic#123]
At the moment, the files `version` and `id` are not signed. Before the first
release it should be decided whether a signature is needed for those files too.

Maybe it's a good idea to combine these two into a `config` file that is signed
and encrypted with the master keys and also includes the polynomial used for
the chunker.

**Comment by fw42** [comment]
What's the disadvantage of signing them? (Other than having to write and maintain the code for that :-))

**Comment by fd0** [comment]
It's a change that needs to be done before the alpha release, after that I'd like to have backwards-compatible repositories. It's basically a change in the repository structure and some added code.

**Comment by fd0** [comment]
I propose to add a file named 'config' to the repository containing an encrypted (and authenticated) json structure with the following fields:
 * chunker polynomial
 * repository id
 * repository version

After opening a key with a password, this file is read, the config JSON structure is parsed and the next thing the code does is chenking the version number. This way we can extend the config structure later with additional fields and increment the version field, so that restic can decide if it can handle this version repository or not. Comments?

**Comment by fw42** [comment]
Hmm.. Why encrypt the version number? Seems like that could make it potentially more annoying to make versioned changes to the encryption code (like, version 1 means AES, but now version 2 uses something much better than AES, but you can't know that because you already removed the AES code from that code path).

**Comment by fw42** [comment]
> chunker polynomial (contained redundantly in the key files at the moment, **that's not ideal**)

What's wrong with embedding the polynomial with the keys?

**Comment by fd0** [comment]
There may be more than one key (more than one password), so each one contains the chunker polynomial again. That's redundant. In addition, if an attacker has access to several different repos where the same password is used (but  a different chunker polynomial), she can swap the key-files and restic would (probably) use the other chunker polynomial... I'm not sure how relevant this attack is, though.

**Comment by fd0** [comment]
So, maybe leave the version out? This would make it easy for an attacker to downgrade the repository version...

**Comment by fw42** [comment]
I would MAC the version number, but not encrypt it...

**Comment by fd0** [comment]
I think we should include the repository version number in the encrypted config file.

Suppose we exchange AES for something else (e.g. Chacha20), keeping the MAC (Poly1305).

The relevant scenarios are:

 * Users with a new version of restic accessing an older repository: restic
   tries to authenticate the config file (that works), but decryption fails.
   Afterwards it can try to decrypt with AES, that works again. Display a
   message to the user that the repository uses an older format, with the option
   to upgrade it.

 * Users with an old version of restic accessing a newer repository:
   Authenticating the config file works, but decryption fails. We can display an
   error that the repository is too new for the version of restic.

If we exchange the MAC, it's the same thing:

 * Users with a new version of restic accessing an older repository: restic
   tries to authenticate the config file, which fails. This would also be the
   case if the config file was authenticated but unencrypted. Then try with the
   old method, this works and the config file can be decrypted, so display a
   warning that this repository uses an older structure, with option to upgrade
   it.

 * Users with an old version of restic accessing a newer repository:
   Authenticating the config file fails, so display a warning that the
   repository has either been tampered with, or uses a newer structure. Urge the
   user to upgrade restic.

The only difference is that when the version number is present in plain text
(with a MAC attach) we can show this version number to the user. That's it. Am I
missing something?

**Comment by fw42** [comment]
How do you feel about not only including a "repository version" but also including the exact same version of restic that was used last time the repository was written? Just for "debugging purposes". That way, you always know which version of restic will definitely work to restore your data if everything else fails.

**Comment by fd0** [comment]
You're talking about uploading the binary that was used to create the repository?

**Comment by fw42** [comment]
no I mean just add an identifier that tells you which build of the binary was used.. like the git sha.

**Comment by fw42** [comment]
Although uploading the actual binary is an interesting idea too

**Comment by fd0** [comment]
So, let's keep this idea for later, once we have the means to include this version number or git ID.

What do you think about the config file? I'd go ahead and encrypt and authenticate it, including the repository version number.

**Comment by fw42** [comment]
> I'd go ahead and encrypt and authenticate it, including the repository version number.

sure :+1:

**Comment by fd0** [comment]
I added the necessary code in #166, please have a look.

**Comment by fd0** [comment]
#166 is merged, so I'll close this.
