### ISSUE TITLE
bash autocompletion improvements

### ISSUE THREAD

**Issue by mbiebl** [restic/restic#1237]
This is related to this downstream bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872174

I'd like to see the bash completion file added to the restic package so it works ootb. 

Atm this can only be done during runtime having root privileges. It would be nice if ```restic autocomplete``` would respect a environment variable which would allow to override the installation target. This way, one could use the binary that is generated as part of the package build process to also generate the completion file, like
```
DESTDIR=/foo/bar/baz/ ./restic autocomplete
```
This would result in the completion file to be installed at /foo/bar/baz/etc/bash_completion.d/restic.sh

That said, nowadays, bash completions should be installed into /usr/share/bash-completion/completions/ and have the name of the binary (i.e. the .sh suffix should be dropped). This way the completions can be loaded on demand by bash.
See https://github.com/systemd/systemd/commit/d611dadc for example.

**Comment by mbiebl** [comment]
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776954

**Comment by mbiebl** [comment]
An alternative to the DESTDIR idea would be, to ship the generated file in the git repo as was done for the man pages in db389058fab763fbe4e2c5bf76a4879154beb4af

**Comment by fd0** [comment]
Thanks for raising this issue. The bash auto completion file can be written to an arbitrary file with the `--completionfile` flag (which is not intuitive and we should change that someday). I'm not sure what to do with the generated man page files, if it's a good idea to keep them in the repo (for non-release tags).

**Comment by mbiebl** [comment]
A perfect, I didn't know about the ```--completionfile``` argument. That makes my request for the DESTDIR env var obsolete
