### ISSUE TITLE
Restic always reads contents of unchanged files when system timezone has changed

### ISSUE THREAD

**Issue by ctberthiaume** [restic/restic#1238]
## Output of `restic version`
restic 0.7.2
compiled with go1.9 on linux/amd64

## How did you run restic exactly?
```
export RESTIC_PASSWORD=password
restic -r repo init
restic -r repo backup datafile
restic -r repo backup datafile
```

## What backend/server/service did you use?
Local repository on root EBS volume, ext4 filesystem of an AWS EC2 t2.micro, Ubuntu 16.04.2 LTS instance.

## Expected behavior
The second snapshot of the data file should not trigger a full read of file contents since the file has not changed.

## Actual behavior
The file being backed up is read again. Snapshot creation takes significantly longer than is necessary.

## Steps to reproduce the behavior
Perform a backup then immediately perform another backup on the same file on a Linux system with timezone set to UTC. This doesn't affect systems with non-UTC timezones.

Below is a Bash script to reproduce this behavior. I ran this with a custom debugging binary that added some logging print statements to make the cause clearer, but the script should work with the latest 0.7.2 Linux amd64 binary just fine. The debugging binary was based on v0.7.2 with these lines added in `internal/restic/node.go`,  `IsNewer()` right before the ModTime equality check, around line 516. They show why modtime and changetime are failing equality checks.

```golang
debug.Log("modtime1=%s, modtime1-Location=%s", node.ModTime, node.ModTime.Location())
debug.Log("modtime2=%s, modtime2-Location=%s", fi.ModTime(), fi.ModTime().Location())
debug.Log("changetime1=%s, changetime1-Location=%s", node.ChangeTime, node.ChangeTime.Location())
debug.Log("changetime2=%s, changetime2-Location=%s", changeTime(extendedStat), changeTime(extendedStat).Location())
```

then build debugging binary with `go run build.go --goos linux --goarch amd64 -tags debug` and place the binary in the `/usr/local/bin` or somewhere in the PATH.

```sh
#!/bin/bash

restic version

# Make 300MiB datafile
echo ""
echo "Creating 300MB datafile"
head -c 300M </dev/urandom >datafile

export RESTIC_PASSWORD=password

##########################################################
# With UTC timezone
##########################################################
echo ""
sudo timedatectl set-timezone Etc/UTC
date +"%Z %z"

restic -r repo-UTC init

# Create first snapshot
restic -r repo-UTC backup datafile

# Create second snapshot
# Notice it rescans the file
DEBUG_LOG=restic-debug-UTC.log restic -r repo-UTC backup datafile

# Confirm identical timestamps but different Locations and file is flagged as
# newer than one in repo
grep "IsNewer" restic-debug-UTC.log 2>/dev/null

##########################################################
# non-UTC timezone
##########################################################
echo ""
sudo timedatectl set-timezone America/Los_Angeles
date +"%Z %z"

restic -r repo-Local init

# Create first snapshot
restic -r repo-Local backup datafile

# Create second snapshot
# Does not rescan the file
DEBUG_LOG=restic-debug-Local.log restic -r repo-Local backup datafile

# Confirm identical timestamps and identical Locations and file NOT flagged
# as newer than one in repo
grep "IsNewer" restic-debug-Local.log 2>/dev/null
```

Here's the output of my debugging run

```
$ bash bug.sh 
debug enabled
restic 0.7.2 (v0.7.2-0-g5b1e4df1-dirty)
compiled with go1.9 on linux/amd64

Creating 300MB datafile

UTC +0000
debug enabled
created restic backend c832910cb8 at repo-UTC

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
debug enabled
scan [/home/ubuntu/datafile]
scanned 0 directories, 1 files in 0:00
[0:05] 100.00%  50.219 MiB/s  300.000 MiB / 300.000 MiB  1 / 1 items  0 errors  ETA 0:00 
duration: 0:05, 50.16MiB/s
snapshot 922f8dac saved
debug log file restic-debug-UTC.log
debug enabled
using parent snapshot 922f8dac
scan [/home/ubuntu/datafile]
scanned 0 directories, 1 files in 0:00
[0:02] 100.00%  124.335 MiB/s  300.000 MiB / 300.000 MiB  1 / 1 items  0 errors  ETA 0:00 
duration: 0:02, 125.72MiB/s
snapshot c1298c30 saved
2017/09/14 19:35:35 restic/node.go:516	restic.(*Node).IsNewer	47	modtime1=2017-09-14 19:35:26.202751237 +0000 UTC, modtime1-Location=UTC
2017/09/14 19:35:35 restic/node.go:517	restic.(*Node).IsNewer	47	modtime2=2017-09-14 19:35:26.202751237 +0000 UTC, modtime2-Location=Local
2017/09/14 19:35:35 restic/node.go:518	restic.(*Node).IsNewer	47	changetime1=2017-09-14 19:35:26.202751237 +0000 UTC, changetime1-Location=UTC
2017/09/14 19:35:35 restic/node.go:519	restic.(*Node).IsNewer	47	changetime2=2017-09-14 19:35:26.202751237 +0000 UTC, changetime2-Location=Local
2017/09/14 19:35:35 restic/node.go:524	restic.(*Node).IsNewer	47	node /home/ubuntu/datafile is newer: timestamp, size or inode changed

PDT -0700
debug enabled
created restic backend b0e7dfd8f9 at repo-Local

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
debug enabled
scan [/home/ubuntu/datafile]
scanned 0 directories, 1 files in 0:00
[0:05] 100.00%  51.371 MiB/s  300.000 MiB / 300.000 MiB  1 / 1 items  0 errors  ETA 0:00 
duration: 0:05, 50.22MiB/s
snapshot 2cb637de saved
debug log file restic-debug-Local.log
debug enabled
using parent snapshot 2cb637de
scan [/home/ubuntu/datafile]
scanned 0 directories, 1 files in 0:00
[0:00] 100.00%  0B/s  300.000 MiB / 300.000 MiB  1 / 1 items  0 errors  ETA 0:00 
duration: 0:00, 20311.28MiB/s
snapshot 21699923 saved
2017/09/14 12:35:46 restic/node.go:516	restic.(*Node).IsNewer	47	modtime1=2017-09-14 12:35:26.202751237 -0700 PDT, modtime1-Location=Local
2017/09/14 12:35:46 restic/node.go:517	restic.(*Node).IsNewer	47	modtime2=2017-09-14 12:35:26.202751237 -0700 PDT, modtime2-Location=Local
2017/09/14 12:35:46 restic/node.go:518	restic.(*Node).IsNewer	47	changetime1=2017-09-14 12:35:26.202751237 -0700 PDT, changetime1-Location=Local
2017/09/14 12:35:46 restic/node.go:519	restic.(*Node).IsNewer	47	changetime2=2017-09-14 12:35:26.202751237 -0700 PDT, changetime2-Location=Local
2017/09/14 12:35:46 restic/node.go:528	restic.(*Node).IsNewer	47	node /home/ubuntu/datafile is not newer
```

## Do you have any idea what may have caused this?
The Linux system timezone was set to UTC, which broke the `time.Time` modtime and changetime equality checks in `internal/restic/node.go:IsNewer()` because the Location component of the `time.Time` values differed. See debugging log output above. This is because using `==` to compare `time.Time` types checks the timestamp and the Location. From [golang docs](https://golang.org/pkg/time/#Time) for `time.Time` type:

> Note that the Go == operator compares not just the time instant but also the Location and the monotonic clock reading. Therefore, Time values should not be used as map or database keys without first guaranteeing that the identical Location has been set for all values, which can be achieved through use of the UTC or Local method, and that the monotonic clock reading has been stripped by setting t = t.Round(0). In general, prefer t.Equal(u) to t == u, since t.Equal uses the most accurate comparison available and correctly handles the case when only one of its arguments has a monotonic clock reading.

## Do you have an idea how to solve the issue?
In `IsNewer()` use `! t.Equal()` to compare times rather than `!=`.

i.e.

`if node.ModTime != fi.ModTime() || node.ChangeTime != changeTime(extendedStat)`
becomes
`if !node.ModTime.Equal(fi.ModTime()) || !node.ChangeTime.Equal(changeTime(extendedStat))`

Without knowing much about the internals of restic, I would suggest this change should be made throughout the code base since in most cases the intention is probably not to check the Location and monotonic clock, just the time since epoch.

**Comment by jrothlis** [comment]
I'm having this issue on Windows 2012 R2. I'm in the UK, but it is British summer time (daylight savings) right now, so not strictly UTC.

**Comment by fd0** [comment]
Thank you very much for the detailed error report and the time you spent debugging it! It sound like you're right: We shouldn't compare `time.Time` with `==`. I'll prepare a PR.
