### ISSUE TITLE
[SUGGESTION] Adding an "agent" command

### ISSUE THREAD

**Issue by MelkorLord** [restic/restic#1239]
Hi,

I've tested Restic and I'm mostly satisfied with the results except for one thing, the lack of an "agent" mode.

Restic, as well as Borg for that matter, is geared at "backup-and-push-to-repository" which is nice but not desired in my environment. I need a "repository-pulls-backup-from-agent" design. There could be an additional "agent" command that would :
  * Use ssh transport by default to contact an host and the ssh keys benefits (authorized keys, etc.)
  * Spawn a Restic instance to make the backup on the remote host (like a normal Restic call) but feed the result back to the calling Restic instance, which holds the repository

Of course, it would be of the administrator responsibility to setup everything accordingly to use either one repository for every remote host or script something a bit smarter to use a repository per host or group of hosts, whatever suits the needs.

Why such a setup?

Because, in my case at least, the backup server is of critical importance and network isolated from the other hosts. I really don't want the "all-hosts-can-contact-the-backup-server" style but the "only-backup-server-can-contact-hosts" kind of behavior.

This also helps to limit the strain on the backup server. Having all the hosts, with no predictable backup size, hammering the backup server at the same time (cronjob) is not desirable, especially on sites with storage on budget :-)

Would you consider such a request? Thanks.

**Comment by dionorgua** [comment]
Take a look to [this post](https://forum.restic.net/t/make-restic-more-attractive-for-obnam-users/61/16) (and a few posts after it).

**Comment by fd0** [comment]
This is not new, we're tracking this feature in #299, therefore I'm closing this issue as a duplicate.

The matter itself is not so complicated: I can see the use case and I think we will eventually implement such a mode, but there's no timeline for it.

Please subscribe over at #299 in order to be notified of any progress. Thanks!
