### ISSUE TITLE
flaky swift backend CI tests

### ISSUE THREAD

**Issue by fd0** [restic/restic#1252]
At the moment, the swift backend tests execute by Travis are run against a server provided by OVH. I noticed that the test is very flaky.

Among others, it creates files in the backend, then removes them again and tests that they are indeed removed. This often fails: The file is still present (at least a `HEAD` request still returns information for it). Or the file is saved, and then cannot be removed.

I have even added a check for delayed removal so the code will try for 5 minutes to remove the file, but that does not resolve the issue.

Is there some caching involved that I'm not aware of? Does the Swift protocol have some defined time after which files are available (or removed)?

@ncw @rledisez @byo @jayme-github Do you have any idea what this is about, or how to debug this further?

The CI test being flaky is very annoying, usually I just restart the tests that fail manually in the Travis web UI, but then it takes time to run the test again.

Here's a sample of a failed swift test: https://travis-ci.org/restic/restic/jobs/276786075

**Comment by ncw** [comment]
This almost certainly eventual consistency at work.  Swift listings are often out of date with respect to the actual objects stored.  I have the same problem in the rclone tests - I work around by retrying the listing operations until I get the result I expect.

It also depends on how busy the swift server is.  You could try signing up for a [free 5GB Memstore account](https://www.memset.com/cloud/storage/) - that may be more reliable.  If you want more than 5GB let me know (I work for Memset).

5 minutes sounds like a long time to wait though - a few 10s of seconds is the most I've seen.  Amazon Cloud drive eventual consistency is much worse than swift in my experience!

**Comment by fd0** [comment]
Hm, that's a good idea, I'll try that. Let's see how far we get with 5GB ;)

**Comment by fd0** [comment]
Bummer, I created an account but it won't let me proceed without entering credit card details.

**Comment by ncw** [comment]
@fd0 I put a 50GB free Memstore in your account

**Comment by fd0** [comment]
Thank you! I'll try that :)

**Comment by fd0** [comment]
Ok, that is much faster and seems to also converge faster. We'll the Memset service for the CI tests for now. Thank you very much!

I'm closing this issue for now.

**Comment by fd0** [comment]
The backend tests against the Memset Swift service haven't errored a single time, so that's much better. Thank you @ncw!

**Comment by byo** [comment]
@ncw I'm wondering now... since swift is an eventually consistent system, is there a possibility that it will cause issues with locks? Maybe those flaky tests actually proven there's something wrong with this backend?
