### ISSUE TITLE
Feature request: CLI option to retry upon failed network requests

### ISSUE THREAD

**Issue by mholt** [restic/restic#1255]
I schedule regular backups using launchd on my Mac. Something that happens quite regularly is I get to work, open my computer, and restic is immediately executed, before it connects to the Internet. Sometimes I have wifi off, so it takes several minutes before I turn it on, other times it just takes a few seconds to connect to wifi anyway. Thus my backup fails with:

```
unable to open config file: client.Head: Head https://<redacted>: dial tcp: lookup <redacted> on <redacted>: write udp 192.168.254.53:64373-><redacted>: write: network is down
Is there a repository at the following location?
rest:https://<redacted>
```

I would love a little CLI option like `--robust-start` or `--retry-connection` or something, that would tell restic to keep retrying on network errors when initially starting the backup, up till about 1 hour? Upon first connection failure, restic could just log "Waiting for network..." and then when it succeeds, start logging as normal.

Not a high priority, but would make my regular backups more robust without awful bash hacks. (I don't use a bash script to run restic.) Thanks for reading!

(If there's consensus on this, it MIGHT be something I can contribute, if it doesn't turn out to be too tricky.)

**Comment by fd0** [comment]
Thanks for the suggestion! To be honest I'm reluctant to add this to restic, it feels like a very special case.

**Comment by mholt** [comment]
Yeah it is pretty niche. No worries. I'll try to hack some network wait loops into a bash script and update my launchd service.

**Comment by maxstoyanov** [comment]
This is also relevant to automatic server backups where manual intervention is key. There may be network separations at night during backups and I would like to specify in a config file how restic should react.

**Comment by mholt** [comment]
Yeah, that's true. In the meantime I've worked around this in the script that invokes restic, so I'm satisfied closing this issue. It seems reasonable to let a script or process supervise restic and decide how to handle it.
