### ISSUE TITLE
Exclude documentation from codecov

### ISSUE THREAD

**Issue by jniggemann** [restic/restic#1268]
Adding to the documentation currently decreases coverage as reported by codecov.
Excluding the documentation would give a more accurate coverage report.

**Comment by fd0** [comment]
Adding documentation is not the cause for the declining coverage: We run a bunch of integration tests for various backend implementations against live services. For security reasons, the credentials used for those tests are not exposed when integration tests are run for third-party (not a branch in the restic repo) pull requests, so the backend tests are skipped and therefore the code for them is not covered.

For example, have a look at where in the code (the documentation files are not even tracked by codecov.io) the coverage fell for PR #1254: https://codecov.io/gh/restic/restic/pull/1254/changes
