### ISSUE TITLE
--exclude-if-present leads to lots of lstat-operations for each directory

### ISSUE THREAD

**Issue by phillipp** [restic/restic#1271]
## Output of `restic version`

restic 0.7.3 (v0.7.3-28-g2080afd-dirty)
compiled with go1.9 on linux/amd64

## How did you run restic exactly?

export RESTIC_REPOSITORY=/srv/storage/restic
export RESTIC_PASSWORD_FILE=$HOME/.config/restic-password

ionice -c 3 ./restic backup --exclude-caches --exclude /mnt/backup-snapshot/_backup --force /mnt/backup-snapshot

## What backend/server/service did you use?
local mount of ZFS via CIFS

## Expected behavior
lstat each CACHEDIR.TAG once per directory

## Actual behavior
CACHEDIR.TAG is lstat'ed once per file 

```
futex(0xc4204cf610, FUTEX_WAKE, 1)      = 1 <0.000007>
lstat("/mnt/backup-snapshot/[..sensitive pathname..]/cache/81/7969-tiny-816f5f5ad4039bdb6eb0bdeebe3fe69ed4f83c3a", {st_mode=S_IFREG|0600, st_size=7425, ...}) = 0 <0.000024>
lstat("/mnt/backup-snapshot/[..sensitive pathname..]/cache/81/CACHEDIR.TAG", 0xc545816518) = -1 ENOENT (No such file or directory) <0.000008>
lstat("/mnt/backup-snapshot/[..sensitive pathname..]/cache/81/7969-tiny-816f5f5ad4039bdb6eb0bdeebe3fe69ed4f83c3a", {st_mode=S_IFREG|0600, st_size=7425, ...}) = 0 <0.000010>
lstat("/mnt/backup-snapshot/[..sensitive pathname..]/cache/81/CACHEDIR.TAG", 0xc5458166b8) = -1 ENOENT (No such file or directory) <0.000007>
epoll_wait(4, {}, 128, 0)               = 0 <0.000006>
futex(0xe3feb0, FUTEX_WAIT, 0, NULL)    = 0 <0.008781>
epoll_wait(4, {}, 128, 0)               = 0 <0.000010>
pselect6(0, NULL, NULL, NULL, {0, 3000}, 0) = 0 (Timeout) <0.000064>
futex(0xc420108490, FUTEX_WAKE, 1)      = 1 <0.000013>
futex(0xc420108490, FUTEX_WAKE, 1)      = 1 <0.000008>
lstat("/mnt/backup-snapshot/[..sensitive pathname..]/cache/81/8236-81177c7d3b2c70e6a9a60bc53bdbc29b5a857be8", {st_mode=S_IFREG|0600, st_size=587571, ...}) = 0 <0.000068>
lstat("/mnt/backup-snapshot/[..sensitive pathname..]/cache/81/CACHEDIR.TAG", 0xc5fbc7f628) = -1 ENOENT (No such file or directory) <0.000009>
lstat("/mnt/backup-snapshot/[..sensitive pathname..]/cache/81/8236-81177c7d3b2c70e6a9a60bc53bdbc29b5a857be8", {st_mode=S_IFREG|0600, st_size=587571, ...}) = 0 <0.000007>
lstat("/mnt/backup-snapshot/[..sensitive pathname..]/cache/81/CACHEDIR.TAG", 0xc5fbc7f7c8) = -1 ENOENT (No such file or directory) <0.000008>
```

## Steps to reproduce the behavior

run restic with --exclude-caches or own --exclude-if-present

## Do you have any idea what may have caused this?
From looking at the code I'd judge that the problem is, that the exclude filter is only applied to entries of each path that is walked in Pipe.Walk. If it would be applied to the path itself, too, and skip walking the entries if the path itself is excluded, this should not happen. Otherwise this seems not the complete solution, as if it were true, the problem should only happen in the first level of path traversal and not in "deeper" levels. So I'd say my analysis is flawed somehow.

## Do you have an idea how to solve the issue?

I see multiple possible solutions:

1. split exclude filters for paths and entries. This seems to be the most effective solution: if the exclude filters are split (--exclude-if-present goes only with path and not with entry filters) then there is no need to check the presence of these files for each entry, but rather for each path
2. implement a temporary cache for the files presence(s)

**Comment by fd0** [comment]
You are right, the test for the `CACHEDIR.TAG` is "stateless", it is executed once per item (file or dir) and does not remember results from previous items.

Can you please describe why this is a problem in your use case?

**Comment by rawtaz** [comment]
I don't get it. Naturally only when the current item is a directory, should restic look for the exclude file in that directory. If the current item is a file it shouldn't perform the check for an exclude file (in the current file's directory). Seems like a no-brainer?

**Comment by fd0** [comment]
That's not the way the code is structured right now, that'd mean changing things around. And I'd like to know if the current behavior is impacting something in some way. I agree that it's an issue and that we should resolve it, so it's just a matter of prioritizing.

**Comment by phillipp** [comment]
I havent measured the exact performance impact yet, but syscalls are not free. Looking at the strace summary the lstat's for CACHEDIR.TAG is the top syscall of restic, so this must be a performance hit. I agree that this depends on the directory/entry ratio of the backup set.

**Comment by fawick** [comment]
I planned to add a internal "cache" (mutex and a map[string]bool) for storing the exclusion result of each directory in the first visit. I just have not got around to do that, yet.
