### ISSUE TITLE
How to deal with auto generated files (manpages, bash completion file)

### ISSUE THREAD

**Issue by fd0** [restic/restic#1274]
I'd like to bounce ideas around what to do with the auto generated files, which (at the moment) are mainly the man pages (in `doc/man`) and the bash auto-completion file (not automatically generated). For both we have dedicated commands (`restic manpage` and `restic autocomplete`, which need to be reworked anyway to maybe `restic generate`?).

The manpages are required to be up to date, which is checked by the CI tests running on Travis (mainly so that I don't forget to update them). The bash auto-completion file is not generated automatically.

I think we need to find a common solution for both items. I can see that contributors (including myself) regularly forget to update the manpages, so that at least one additional push/test cycle is needed. The upside is that the repo always contains the latest set of manpages.

So, what should we do? Force the auto-completion file to be generated and present in the repo? Or remove the manpages from that and only generate the files for releases?

Comments/ideas?

**Comment by rumpelsepp** [comment]
Anything against some Makefile with the required targets? The needed commands to generate the said failes could be listed in the installation manual. Packagers could adopt this in the packaging process, installations from source need to issue one or two more commands, and finally the travis script could be updated to generate those files.

**Comment by fd0** [comment]
So, you're saying to not keep the generated files in the repo, but make it easier to generate them during compiling/installation?

When the files were generated by Travis, how would they end up in the repo?

**Comment by rumpelsepp** [comment]
> So, you're saying to not keep the generated files in the repo, but make it easier to generate them during compiling/installation?

Exactly. Or this there any reason I have missed to keep them in the rendered version within the repository?

> When the files were generated by Travis, how would they end up in the repo?

They don't. But you were talking about tests. If it is needed to generate them for tests, travis can do this.

**Comment by rumpelsepp** [comment]
> When we remove the generated manpages from the repo, the test isn't needed any more.]

That's another benefit of dropping generated files from the repo... :)

> When cross-compiling, the binary cannot be used to generate the manpages any more. 

Is this really an issue? Go compiles so fast that i personally wouldn't care about this.

**Comment by fd0** [comment]
Ok, I'm inclined to do this: Remove the autogenerated man pages from the repo, and add documentation on how to generate the man pages and the autocompletion files. I'll also add a target to the `Makefile` to do that (it's there mainly for convenience). Then we can remove the test and make it easier for contributors. :)

**Comment by mbiebl** [comment]
Related to that https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872174 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872173
For the bash-completion file I proposed this patch: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=872174;filename=restic-bash-completion.diff;msg=10

As you can see, the resulting package would differ from a native package if it was cross-compiled.
Shipping pre-generated files would indeed avoid this and make it a bit simpler for a package maintainer.

**Comment by fd0** [comment]
Ah, but that is just the distribution packager's perspective. We've been talking about the git repository. For released versions (as in: the .tar.gz files) I'd like to include pre-generated autocomplete files and manual pages. That's not hard to do during the release process.
