### ISSUE TITLE
Snapshot is created even if backup source path doesn't exist

### ISSUE THREAD

**Issue by fw42** [restic/restic#128]
Trying to backup a directory ("foobar") that does not exist: 

```
$ cmd/restic/restic -r /tmp/restic backup foobar
Enter Password for Repository:
scan [/Users/flo/go/src/github.com/restic/restic/foobar]
error for /Users/flo/go/src/github.com/restic/restic/foobar: lstat /Users/flo/go/src/github.com/restic/restic/foobar: no such file or directory
scanned 0 directories, 0 files in 0:00
loading blobs
[0:00] NaN%  0B/s  0B / 0B  1 / 0 items  ETA 0:00
duration: 0:00, NaNMiB/s
snapshot b319c02e saved
```
gives an error, but still creates an empty snapshot.

Is that on purpose or a bug?

**Comment by fd0** [comment]
That's a bug on a corner case. Usually, restic tries to continue in spite of errors (see #112), but in this case all items that are to be saved return an error. This case should be handled explicitely.
