### ISSUE TITLE
Feature request: Verify

### ISSUE THREAD

**Issue by jniggemann** [restic/restic#1280]
As a user, I'd like to make sure that the data in the repo and the data on the disk are actually the same, i.e. I'd like to have the possibility to verify that the backed up data is accurate and complete. The feature could be called `verify` or `compare`. Running it right after a backup has finished should report “OK”, if the on-disk data hasn’t changed in between…

An idea how to implement this was discussed in the restic forums:
For each file both present in the repo and in the local file system, read the file and see whether the it contains the same blobs as recorded in the snapshot.

**Comment by mbiebl** [comment]
I did something with simple shell script: 
- Mounted the restic repo via fuse
- Get all files via find and generate the md5sums using md5sum
- Run the md5sum check again on the real system

**Comment by mbiebl** [comment]
Using fuse is not the fastest method, but this way I didn't need twice the storage capacity

**Comment by zcalusic** [comment]
@mbiebl, that is indeed a cool idea. 👍

**Comment by fd0** [comment]
As mentioned in the forum, the workflow can be improved a lot by using the data restic has already available: The list of blobs the file consists of. With the new metadata cache that'd mean loading almost nothing from the remote repo, and doing all the work locally: Split a file, read the blobs, compare with the list of blobs in the repo.

**Comment by fd0** [comment]
The `restore` command has `--verify`, this should do for now, closing. Please feel free to add further comments. Thanks!
