### ISSUE TITLE
Add "backup --verbose/--files-to" logging

### ISSUE THREAD

**Issue by lathspell** [restic/restic#1284]
As of restic 0.7.3 the backup command is very silent and DEBUG_LOG much too verbose.
I'd like to have a --verbose switch that makes restic print one line for every file it processes.

Example:

     item 234: -rwx-rx-rx- /bin/bash             13 MB  found
     item 235: -rwx-rx-rx- /bin/bconsole         20 MB  added (50% compressed)
     item 236: -rw--r--r-- /bin/foobar.iso     8000 MB  added (0% compressed)

That way, when my USB drive keeps hitting "no space left on device" without me knowing what could possible have gone wrong, I could browse through the logfile and maybe notice that there's a big file that was accidently moved into the wrong directory. Or that I mounted an NFS share which I'm now
accidently backing up.

The format of course was just an example, it would be nice if it were processable with the usual Unix tools like sed/awk/cut.

**Comment by fd0** [comment]
That's a good idea, and I have plans to refactor the UI for the backup command, but that includes heavy modifications to the internal processing pipeline (which we need to touch anyway). So I leave this open as a reminder to do this once we get around to refactoring the archiver code.

**Comment by paul-t-t** [comment]
If I could add an elaboration to this feature request: I think it would be useful if it were possible to have a line of output only for each file that is new or modified since the last snapshot.

**Comment by lathspell** [comment]
@paul-t-t maybe this should rather be done using "r | grep" to keep it simple.

BTW, is showing "modified" possible all? Restic probably only looks if the hash value exists, not if the current file name is part of the last or any other snapshot as this would be a different database lookup.

**Comment by whereisaaron** [comment]
Boo, unfortunately `-v v` log every file including unchanged files, not just added/modified/deleted files. And just `-v` does not mention files at all.

For me just 0.12% of log entries are the interesting ones I am after with `-v -v`. As @paul-t-t mentioned, grepping them away is possible but ideally there would be some middle ground between the current `-v` and `-v -v`.

```
$ kubectl logs foo | wc -l -c
  43241 7018311

$ kubectl | grep -v unchanged | wc -l -c
     51    6908
```

**Comment by fd0** [comment]
Thanks for giving the new feature a test drive! I had to decide a solution on how to expose different things to users and decided to use a coarse setting for now. We can tune this when I've collected several more use cases :)

> I assume for a modified entries the data size if just the modified chunks?

Exactly, the archiver tracks the sum of all data blobs newly added, so chunks already in the repo are not counted.

> Could the stats include the full size as well as the size added to the snapshot, or is that info not available at that point in the code?

It's pretty much all available in the code, but I'd like to now completely overwhelm users with irrelevant data. I'm open to discussion on what  amount of data shown (with different `--verbose` settings), though.

> With the new archiver driving this, is there an option for JSON log entries? 

Not yet, we don't have a clear strategy for logging things when run non-interactively (yet).

I'm going to close this issue, as the basic feature is implemented. @whereisaaron would you mind creating a new issue so we can collect use cases and discuss improvements? Thanks!
