### ISSUE TITLE
Use full paths in mounted snapshots

### ISSUE THREAD

**Issue by mrzv** [restic/restic#1286]
If I backup a set of directories: `restic backup ~/A ~/B ~/C ~/D/E/F ~/G/H`, and then `mount` the snapshot, I get a directory structure with top level directories: A, B, C, F, H. I.e., only the last directory is used. When I list the `snapshots`, I can see the full paths, so the information is clearly preserved. I think it would be beneficial, if mounted snapshots used the full path structure, so in the example above, I'd see only one directory: /Users (on a Mac) or /home (on Linux).

This problem, by the way, becomes an actual bug, if there are overlapping names (e.g., ~/A/X and ~/B/X). Only one of them is available in the mounted snapshot.

**Comment by mbiebl** [comment]
looks like a duplicate of https://github.com/restic/restic/issues/549

**Comment by mrzv** [comment]
Indeed, it's another manifestation of that problem. This one being in the `mount` command. Should I close this issue?

**Comment by fd0** [comment]
Yes, please close the issue, this is a duplicate of #549. Since 0.7.3, restic will rename the directories during backup if such a conflict occurs.

I'll work on resolving #549 next.
