### ISSUE TITLE
backup to sftp fails

### ISSUE THREAD

**Issue by sebastianbeyer** [restic/restic#1288]
## Output of `restic version`
```
debug enabled
restic 0.7.3 (v0.7.3-72-g1ee15595)
compiled with go1.8.3 on linux/amd64
```

## How did you run restic exactly?
`export DEBUG_LOG=./restic-debug.log`
`./restic -r sftp:sebirestic@resticserver:~/backup backup CHANGELOG.md`

## What backend/server/service did you use?
sftp on 
- `OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016`
- `Ubuntu 16.04.3 LTS`
- odroid xu-4

## Expected behavior
restic making the backup

## Actual behavior
```
debug log file ./restic-debug.log
debug enabled
enter password for repository: 
sftp: "Failure" (SSH_FX_FAILURE)
Write
github.com/restic/restic/internal/backend/sftp.(*SFTP).Save
	src/github.com/restic/restic/internal/backend/sftp/sftp.go:350
github.com/restic/restic/internal/cache.(*Backend).Save
	src/github.com/restic/restic/internal/cache/backend.go:69
github.com/restic/restic/internal/repository.(*Repository).SaveUnpacked
	src/github.com/restic/restic/internal/repository/repository.go:277
github.com/restic/restic/internal/repository.(*Repository).SaveJSONUnpacked
	src/github.com/restic/restic/internal/repository/repository.go:262
github.com/restic/restic/internal/restic.(*Lock).createLock
	src/github.com/restic/restic/internal/restic/lock.go:173
github.com/restic/restic/internal/restic.newLock
	src/github.com/restic/restic/internal/restic/lock.go:102
github.com/restic/restic/internal/restic.NewLock
	src/github.com/restic/restic/internal/restic/lock.go:63
main.lockRepository
	src/github.com/restic/restic/cmd/restic/lock.go:36
main.lockRepo
	src/github.com/restic/restic/cmd/restic/lock.go:23
main.runBackup
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:384
main.glob..func2
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:49
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:650
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:729
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:688
main.main
	src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
	/usr/lib/go/src/runtime/proc.go:185
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:2197
```

[restic-debug.log](https://github.com/restic/restic/files/1340093/restic-debug.log)

## Steps to reproduce the behavior
It happens every time I try to backup. Init works as expected.
On another server it does work
(same ubuntu version, `OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013`)

## Do you have any idea what may have caused this?
I think it has to do something with the sftp backend...
Already looked at  #983, but that was with `proftpd` and not openssh.

## Do you have an idea how to solve the issue?
no

**Comment by fd0** [comment]
Hey, thanks for the report. I think this is caused by the `~` character in the path, which is not expanded by restic (nor the sftp server). If you want to reference a directory relative to the start dir of the user on the server (mostly the home dir), use a relative directory.

Could you retry with `sftp:sebirestic@resticserver:backup backup CHANGELOG.md` and report back? Thanks!

**Comment by sebastianbeyer** [comment]
Yeah! that worked! Thank you!
Still strange that it works with the `~` on the other sftp server... So it depends on the server if it is expanded? Maybe we should somehow add this to the documentation /FAQ? Something like "please be aware that paths are not expanded"?

**Comment by fd0** [comment]
Would you like to do a PR? :)

**Comment by sebastianbeyer** [comment]
Yeah sure! but I would like to understand a bit more about this first. Does it depend on the servers sftp implementation if the path is expanded? I have not really found anything about this so far... Maybe we should not allow `~` in the repo path at all?

**Comment by fd0** [comment]
I think so. Even the OpenSSH server and the `sftp` client program do not expand `~`:
```
$ sftp server:~fd0
Connected to server.
File "/home/fd0/~fd0" not found.
```

So I think it's fair to print a warning when the path given to the sftp backend starts with `~`.

**Comment by fd0** [comment]
So, I've just gone ahead and added code and documentation about this behavior. I'm sorry that I've taken this away from you.

**Comment by sebastianbeyer** [comment]
No problem, even better for me ;-)

**Comment by jniggemann** [comment]
@fd0: Can we close this issue?

**Comment by fd0** [comment]
Yes, it should've been closed automatically anyway.

**Comment by Cantello** [comment]
Just as a possible addendum: I had the same non-descript error (SSH_FX_FAILURE) while backing up from a debian computer to a Hetzner storagebox and the culprit here was the leading slash in the path. `sftp user.storagebox.de:/restic` did not work, whereas `sftp user.storagebox.de:restic` did indeed work.

**Comment by LucaRed** [comment]
Thanks @Cantello ! After spending one hour not understanding why I couldn't setup my configuration with an SFTP connection to a Hetzner Box, I found your solution.

All I had to do was removing the leading slash from the address!

For future reference, I added the whole server definition to my `.ssh/config` file like this:

```
Host hetzner-storage-box
    HostName u123456.your-storagebox.de
    User u123456
    IdentityFile /home/username/.ssh/id_ed25519
    Port 23
```

...so I can just reference the name `hetzner-storage-box` in the SFTP address, as in:

```
sftp:hetzner-storage-box:my-backup-folder
```

May your pillow always be cold on both sides, I wish you the best 🙏
