### ISSUE TITLE
Check reports Missing Pack files backing up to B2

### ISSUE THREAD

**Issue by deanroker123** [restic/restic#1289]
## Output of `restic version`

restic 0.7.2
compiled with go1.9 on linux/amd64

## How did you run restic exactly?
usr/bin/restic -r b2:personal-restic-backup:/restic-repo check

## What backend/server/service did you use?
B2

## Expected behavior
No Errors 

## Actual behavior
pack ad6651849f222e209464bed14edfdb6a69b8f13abcd55a7b6697ee21560031d0: does not exist
pack c83030497cdf9db321cee7244555226dd82d04ba6fa4b147a694511bd9e4b580: does not exist
pack 8601d322c5af3e58f88b9f2b95a32385a86be35d1182b4f5b0b4a5cdcacac50a: does not exist

## Do you have any idea what may have caused this?
I stopped a backup half way through, because I changed some options, then restarted it. 

## Do you have an idea how to solve the issue?
How can I get those pack files back? how can I tell what files they affect?

**Comment by fd0** [comment]
Hu, hm. That's unexpected. Can you please use restic 0.7.3, run `restic rebuild-index` and then run `restic check` again? Please report back with the complete output of `restic check`.

**Comment by deanroker123** [comment]
I got this doing rebuild-index, I guess my internet dropped out or B2 had a problem. I am running it again and will post the output if check tomorrow
counting files in repo
pack file cannot be listed 20f9dade: Stat: unexpected end of JSON input
pack file cannot be listed 21c3758f: Stat: unexpected end of JSON input
pack file cannot be listed 985bfb02: Stat: net/http: TLS handshake timeout
pack file cannot be listed 985d6331: Stat: net/http: TLS handshake timeout
pack file cannot be listed 99ba126c: ReadAt: net/http: TLS handshake timeout
pack file cannot be listed 99c3ced2: Stat: net/http: TLS handshake timeout
pack file cannot be listed 99bb981a: ReadAt: net/http: TLS handshake timeout
pack file cannot be listed 99e89266: ReadAt: net/http: TLS handshake timeout
pack file cannot be listed 99e9641d: ReadAt: net/http: TLS handshake timeout
pack file cannot be listed 9a988b11: Stat: net/http: TLS handshake timeout
[9:44:17] 100.00%  60341 / 60341 packs

**Comment by deanroker123** [comment]
Ok now running rebuild index got this output
counting files in repo
pack file cannot be listed 230c9a59: Stat: unexpected end of JSON input
pack file cannot be listed 36d68821: Stat: unexpected end of JSON input
[12:50:54] 100.00%  60341 / 60341 packs
finding old index files
saved new index as a14128ae
remove 1 old index files
 about to start restic check

**Comment by fd0** [comment]
We've just now discovered a bug within the library we're using to access B2, that's tracked in #1291

**Comment by fd0** [comment]
The fix has been merged into the master branch, I'm therefore closing this issue. Can you please try again and report back? Thanks!

**Comment by deanroker123** [comment]
Will do, for the record I got his output from check
Create exclusive lock for repository
Load indexes
Check all packs
pack 1e67b38eb0fedebfaaf5b1a19417ba8c71e05298ce46c4e0fcbc44503bf4e905: does not exist
pack 797db6e56c03966810a6d03af5fa6abcab6d0cd67e97329c6b6da951fc26faa0: does not exist
pack 849683f5ee462c0bbb7df2e8adc76edb6b84aa01828281f21263d6c0753a2a03: does not exist
pack 230c9a5980da4b52cfc1045b9f0c6dbba89d1f788b5120cecd447ff4c186eea9: not referenced in any index
pack 36d6882159e23baa4576c8c6beee1d3a77694c89eb43be29104f39bc90115fe0: not referenced in any index
Check snapshots, trees and blobs
error for tree 22006a21:
  tree 22006a21, blob 96ca534d: not found in index
  tree 22006a21, blob 6e6fc51d: not found in index
  tree 22006a21, blob 378a4837: not found in index
error for tree 83230643:
  tree 83230643, blob afd1e996: not found in index
  tree 83230643, blob 06cf5f80: not found in index
  tree 83230643, blob 6176ed7f: not found in index
  tree 83230643, blob 2d99315c: not found in index
Fatal: repository contains errors
