### ISSUE TITLE
Undocumented /restic prefix requirement of S3 top-level repositories

### ISSUE THREAD

**Issue by ctberthiaume** [restic/restic#1292]
## Output of `restic version`
```
debug enabled
restic 0.7.3 (v0.7.3-72-g1ee15595)
compiled with go1.9 on linux/amd64
```

## How did you run restic exactly?
Create local repo and snapshot with 

```
restic init -r myrepo
restic backup -r myrepo folder
```

Then copy to an existing bucket in S3 and check for snapshots.

```
restic -r s3:s3-us-west-2.amazonaws.com/mybucket snapshots
```

## What backend/server/service did you use?
S3

## Expected behavior
Restic lists the snapshots from the S3 repo.

## Actual behavior
Restic can't find the config file and exits with an error.

```
unable to open config file: Stat: The specified key does not exist.
Is there a repository at the following location?
s3:s3-us-west-2.amazonaws.com/mybucket/
```

## Steps to reproduce the behavior
See commands above.

## Do you have any idea what may have caused this?
Looking at debug logs, when the S3 repo URL is simply the bucket, restic looks for the repo under `bucket/restic`. I don't think this is documented anywhere in the manual. If restic is used to init the repo in S3 it will create the required `restic` folder, and if an existing repo is copied to any other subfolder in the bucket and this subfolder is included in the URL it works OK.

## Do you have an idea how to solve the issue?
When copying a non-S3 backend repo to S3, make sure to copy into a top-level empty `restic` folder and us `bucket` as the URL, or copy into a subfolder and use `bucket/path/to/subfolder` as URL.

Would it be possible to document this layout requirement for S3 repos with some text in either the "Initialize a repository" section on S3 or in the "References/Design/Repository Format" section? Or could restic look for a valid repo at the top-level of the bucket before checking in `/restic`? Any way  to simplify the process of copying an existing repo into an S3 bucket would be helpful.

**Comment by fd0** [comment]
Hey, thanks for raising this issue. It is indeed not really documented (apart from the code). I'd like to drop the automatic "/restic" prefix at some point because that's unexpected.

**Comment by jniggemann** [comment]
Should we document this in the manual, or rather lease the docs as-is and concentrate on dropping the automatic "/restic" prefix?

**Comment by fd0** [comment]
I think we should do both: Drop the prefix in 0.8.0, and document (in the manual and the changelog) that it was there once, and how to specify the s3 backend with the prefix.

**Comment by fd0** [comment]
The code is merged now, and I've also written a blog post about it: https://restic.github.io/blog/2017-11-25/upcoming-changes-to-s3
