### ISSUE TITLE
Unable to prune

### ISSUE THREAD

**Issue by Mebus** [restic/restic#1302]
Hallo,

currently I am trying to prune a repository, but I get this error:

```
found 1771555 of 3990366 data blobs still in use, removing 2218811 blobs
will remove 4 invalid files
will delete 2141 packs and rewrite 20779 packs, this frees 66.188 GiB
read blob <data/7818f887> from /tmp/restic-temp-repack-779824068: wrong data returned, hash is 31c07063e8e2e2b322962d74a9e200bf20dcea2ef824a0c6a9f7bc25b0cac083
github.com/restic/restic/internal/repository.Repack
        src/github.com/restic/restic/internal/repository/repack.go:100
main.pruneRepository
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:274
main.runPrune
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:85
main.glob..func15
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:25
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:650
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:729
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:688
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/lib/golang/src/runtime/proc.go:185
runtime.goexit
        /usr/lib/golang/src/runtime/asm_amd64.s:2337
```

Also it is using about 60 GB more after starting the prune process on disk than before. The repo size on disk is now about 180 GB.

The output of "restic version" is:

restic 0.7.3 (v0.5.0-800-gba23d24)
compiled with go1.9 on linux/amd64

Mebus

**Comment by fd0** [comment]
Please run `restic prune` again from the branch `prune-wrong-data`, I have a hunch what's going on.

How old is that repo?

**Comment by fd0** [comment]
So, @mebus reported that the prune using branch `prune-wrong-data` succeeded over night, that's great to hear. I think what happened is this (unconfirmed guesswork):

With a previous, rather old version of restic that still has the "read-twice approach" it was possible to get a blob into the repo that has a wrong ID: e.g. it was saved with the ID `7818f887`, but the SHA2 hash of the data is `31c07063` (shortened, of course). If this blob is still referenced, during repacking the error mentioned above is printed and restic aborts (`wrong data returned`).

What I did in the branch `prune-wrong-data` was to make this a non-fatal error. The repo will still work, accessing the file in fuse works, and restore works, just the ID of the blob is wrong.

I'll merge this into master later.

@mebus if you have the debug.log ready somewhere I'd like to take a look.
