### ISSUE TITLE
The check command should output "No errors found."

### ISSUE THREAD

**Issue by Mebus** [restic/restic#1303]
Hallo,

the check command is not explicit about whether it found errors.

Please output something like "No errors were found." in addition to

```
Create exclusive lock for repository
Load indexes
Check all packs
Check snapshots, trees and blobs
```
when it did not find an error, so that I know whats going on.

Mebus

**Comment by fd0** [comment]
Sounds like a good proposal.

**Comment by antonlindstrom** [comment]
I can take a stab at this.
