### ISSUE TITLE
XDG_CACHE_HOME is ignored on macOS

### ISSUE THREAD

**Issue by armhold** [restic/restic#1309]
## Output of `restic version`

restic 0.7.3 (v0.7.3-87-g3afd974d)
compiled with go1.9 on darwin/amd64

## How did you run restic exactly?

`restic -r ~/restic-cache-debug backup ~/backup-fodder` 

## What backend/server/service did you use?

Local & B2.

## Expected behavior

If `XDG_CACHE_HOME` is defined, and `--cache-dir` is not specified, then restic should use `$XDG_CACHE_HOME ` for cache.

## Actual behavior

On macOS, restic is ignoring `XDG_CACHE_HOME`, in favor of either or `--cache-dir` flag or `darwinCacheDir()`. From a quick read of the code, Windows has this problem as well.

## Steps to reproduce the behavior

Set XDG_CACHE_HOME to a valid dirname, and run a backup as above.

## Do you have any idea what may have caused this?

I think it was 21338691276a138f6e0bb2ead9068683c38ddf9f.

## Do you have an idea how to solve the issue?

If `XDG_CACHE_HOME` is only meant to be supported on Linux (perhaps reasonable to do so?) then the documentation should reflect that. Else, maybe [something like this](https://github.com/armhold/restic/commit/8968fd7fdfd3625d77bca05903e15e004b12a9b0) (I have not tested that code.)

**Comment by armhold** [comment]
PS: how can I run a specific unit test file? I am not sure what is tripping up the package resolution here. Also tried running the test from the package dir. 

```
go test ./internal/cache/file_test.go 
# command-line-arguments
internal/cache/file_test.go:16:64: undefined: Cache
internal/cache/file_test.go:44:28: undefined: Cache
internal/cache/file_test.go:66:33: undefined: Cache
internal/cache/file_test.go:75:34: undefined: Cache
internal/cache/file_test.go:86:16: undefined: TestNewCache
internal/cache/file_test.go:139:16: undefined: TestNewCache
internal/cache/file_test.go:197:16: undefined: TestNewCache
FAIL	command-line-arguments [build failed]
```

**Comment by prattmic** [comment]
I just changed this in https://github.com/restic/restic/pull/1287. Previously restic always followed XDG regardless of the OS.

Neither Windows nor Darwin officially follow the XDG directory specification. Certainly neither sets the XDG environment variables by default.

That said, I don't often develop for either. Is it common for applications to respect the XDG environment variables even on non-standard platforms like Windows and Darwin? I'm not opposed to a top-level "use XDG_CACHE_DIR" check above all else, I just don't know if such behavior would be expected on these platforms.

**Comment by armhold** [comment]
Hi @prattmic,

I had never even heard of XDG_CACHE_HOME until this was implemented for restic. But I started using it, and then after #1287 I was surprised to find it being ignored, in favor of a new 4GB cache in ~/Library/Caches/restic. 

All of that is fine (since the default on macOS seems correct, and there is a command line option to override it), but the docs should reflect the intended behavior.

In particular the CHANGELOG is currently misleading for mac/win:

```
The cache location is ~/.cache/restic by default, which can be overridden
with --cache-dir or the environment variable XDG_CACHE_HOME.
```

What do you think?

**Comment by prattmic** [comment]
You're right, the docs should be clear on the behavior. I'll send a PR.

**Comment by fd0** [comment]
thanks @prattmic for stepping in and for the fix!

@armhold for the reference, the `go test` tool can be used to run a single test, you need to specify `go test -run TestFooBar pkgdir`, but that only works if the restic repo is checked out in a valid `GOPATH`. Do you know how to do that?

Apart from that, `go run build.go --test` will also execute the tests for you (all of them, though).

**Comment by armhold** [comment]
Thank you both for humoring me on this fix. :-) 

Yes, I have restic checked out at `$GOPATH/restic/restic`. This seems to be a common golang stumbling block- if you want to run a specific test file under a package, apparently you must also name all other files that are required to build the test file:

https://stackoverflow.com/a/16936314/93995

So while this works just fine: 

```
 go test -run FilesTest ./internal/cache
```

... if I want to run all tests in file `./internal/cache/file_test.go`, I need to specify all its dependencies, like:

```
   go test ./internal/cache/file_test.go ./internal/cache/file.go ./internal/cache/cache.go ./internal/cache/dir.go ./internal/cache/backend.go ./internal/cache/testing.go
```
A little suboptimal IMHO, but not a restic problem. Thanks for the handholding!
