### ISSUE TITLE
Remove old cache directories

### ISSUE THREAD

**Issue by fd0** [restic/restic#1318]
As described in https://forum.restic.net/t/local-metadata-cache-available-in-master/159/20?u=fd0 by @wscott, at the moment there's no code in restic which removes old cache directories for other repos. The proposed solution was to remove directories for other repos in the cache directory if they haven't been updated in a month. I like that proposal, but we need to specify this in a bit more depth.

My idea would be to do the following:
 * When restic starts after it knows the current repo ID, it looks at the other directories in the cache dir
 * When the base dir's (`~/.cache/restic/010203[...]`) modification timestamp is older than a month, remove that entire directory
 * This goes for all the cache dirs other than the current repo cache dir.
 * For the current repo cache dir, update the basedir modification timestamp to the current time

I thought about descending into the cache dir to check modification timestamps of all files there, and check if there's a newer file in it, but since we haven't released the cache code yet we can still just add code which updates the timestamp of the base dir.

Thoughts?

**Comment by zcalusic** [comment]
I feel like this functionality could belong to some cache management command, which would then be run manually as a separate step (not unlike the forget/prune commands, which are run independently of the backup command). I'm afraid too much heuristics could hurt us in the long run.

Also, you don't specify above, during which command this cache cleanup would execute ("When restic starts", but which command?). I'd prefer that if I backup/prune/forget/check/whatever one repo, then restic doesn't spend time deciding what to do with the cache of the other repo? Feels like layering violation?

Even then, with some special `cache --clean` command implemented, I'd rather that command be conservative and compare cache and remote repo on a file by file basis and thus decide which local files can be safely removed, and finally do it (again, not making decisions based on heuristics, but educated guess). That makes sense to me. 

BTW, that's why I was complaining that cache layout is different from repo layout. Cache cleanup logic described above is unbelievable easy if layouts match, heck, I could do it with a small shell script. 😃 But, of course, still doable with currently differing layouts, with a bit of translation in both directions.

What do you think?

**Comment by fd0** [comment]
@zcalusic Hm, I feel that we're talking about different things here: I was talking about removing cache directories for repositories, you're talking about managing the files stored in the cache directory for the "current" repository (for which restic is started).

I can imagine running the cachedir expiry code for most commands automatically.

**Comment by zcalusic** [comment]
"Removing cache directories for repositories" still falls under "managing the files stored in the cache directory" IMHO.

**Comment by fd0** [comment]
There's another problem: When you start restic, usually there's only the repository available which should be used during that run, so we don't have any information (nor access credentials) to the other repos. So we can't check whether the files in the cache dirs are still needed...

**Comment by zcalusic** [comment]
Huh, that really is the problem. Dunno then, this seems to be a hard problem to solve. Either, at each run for a single repo, restic will mess with cache belonging to completely different repos (I still think that's not a good idea), or there will be leftover cache files in time...

Maybe a way out is to just document somewhere that rm -rf ~/.cache/restic is non-fatal (but can impact performance in such and such way), and leave that operation as an exercise to the user. 😉 

Do whatever you please, after all...

**Comment by wscott** [comment]
The problem is that these cache files are really not normally visible by users and can contain a non-trivial amount of data. My biggest issue is for backups run by the 'root' user. Often root's home directory is on a relatively small install partition for a machine that might have really large arrays of data to be saved.

And if it takes a couple tries to get backups working right you might have a couple different copies of a 3Gig cache directory where only one is needed.

The cache is written in the user's home directory so, in theory, you should have access rights to other caches in the same directory.

The risk of this cleanup is a race where you notice a cache has not been updated in over a month so it gets deleted, but a backup process happens to start in that exact period when the data is being erased. This seems very unlikely especially if you rename the directory before deleting.

@zcalusic suggests a separate garbage collecting command, or just telling the user they can delete things.  But that doesn't address the idea that the user doesn't know about the wasted space.

**Comment by dionorgua** [comment]
What about just warning (to stderr) at the end of `prune`/`check` operation if there is cache dir for repo that is not used for a long time. And some `--disable-cache-checking` to mute it.

But please don't remove any files outside of backed up repo (or it's cache) by default.

**Comment by fd0** [comment]
Hm, then it'd need to warn after `backup` then, because there will be many hosts which just run backup, not `prune` or `check. Any thoughts on that?

**Comment by dionorgua** [comment]
Well. As far as I remember there was an idea to warn if repo is not checked for a long time (probably around 'please upgrade ASAP' 0.7.1 release). 

At the same time I agree that `check`/`prune` may be called only on one host while other machines just call `backup`. So probably yes, such cache checking should be added to `backup`.

**Comment by fd0** [comment]
I'll come up with some code so we can discuss the specifics then.

**Comment by underhillian** [comment]
A somewhat contrarian suggestion:  implement a "delete" command to delete a repo which also deletes any associated cache.

If this is documented as the "recommended" way to delete an unwanted or experimental repo, it seems to me that it will address **@wscott**s concerns about the unsophisticated user who is unaware of the cache.  It will force the user to provide the correct credentials for the specific repo/cache in question.  It will also prevent the unwanted automatic deletion of a cache that a user might actually want to retain indefinitely (say for a repo that is updated very infrequently). Finally, it would eliminate the (admittedly minor) annoyance of having to log onto a repo host and manually delete a repo when no longer needed...it could all be done with one restic command.

**Comment by fd0** [comment]
Code is in #1436. When a cache dir is used, its modification timestamp is updated. At the start, restic scans for cache dirs with a modification timestamp of older than 30 days, and warns if it finds some. Users can then call `restic cache --cleanup` to remove them.

Opinions?

**Comment by legrostdg** [comment]
I usually run restic with a cronjob which runs "backup" and then "prune". As I understand it, with #1436 I may get warnings during the backup step, which does not seem ideal for a cronjob. I would be nice to have a "--no-cache-warning" flag, to be able to run "backup", "prune" and then "cache --cleanup".

**Comment by underhillian** [comment]
Since @fd0 asks for opinions, I (with some trepidation) will insert a somewhat off-topic comment.

I'm a little concerned about "feature creep" in restic.  It seems to me that the developer(s) are, to their credit, very helpful and enthusiastic about adding features like this one which (with apologies in advance to the OP and others who may be offended by my opinion)  adds a new command, and possibly multiple additional flags, to provide a function that will not be useful to very many people and which is fairly easily scripted to meet individual needs outside of restic for those who do need the functionality.

I make this comment because I came to restic after first trying duplicati.  Duplicati is a solid program and I'm sure very useful to many people.  But, as a complete newbie, I spent almost a week getting it to meet my needs, mostly because of the dozens and dozens of features, options, and interfaces (many of which are poorly documented) that I struggled through on the way to finding what I needed.  I would hate to see restic end up in the same place.

To be clear, I don't mean to criticize this (or any other) particular enhancement.  I don't expect restic to stand still, but I do want to keep restic accessible and easy to use for as many new and potential users as possible.

**Comment by fd0** [comment]
> I usually run restic with a cronjob which runs "backup" and then "prune". As I understand it, with #1436 I may get warnings during the backup step, which does not seem ideal for a cronjob. I would be nice to have a "--no-cache-warning" flag, to be able to run "backup", "prune" and then "cache --cleanup".

Thanks for the feedback. I don't think this warrants a flag to disable the warning: At the moment it's a one-line message printed to stderr (but that's up for debate, we could also use stdout). It is only printed when there are old cache dirs for a different repo. For most servers I guess that there will be just one repo, so no warning will be printed at all. When you run `cache --cleanup` as the last command in the cron job, there will just be a single warning, then the old cache dirs are removed.

**Comment by fd0** [comment]
@underhillian  Thank you for your comment. I can understand where you're coming from. Posting a possibly controversial opinion isn't easy. I'd like to set the tone for all the forums that people feel safe posting such opinions, I hope that I'm successful so far ;)

> I'm a little concerned about "feature creep" in restic. It seems to me that the developer(s) are, to their credit, very helpful and enthusiastic about adding features like this one which (with apologies in advance to the OP and others who may be offended by my opinion) adds a new command, and possibly multiple additional flags, to provide a function that will not be useful to very many people and which is fairly easily scripted to meet individual needs outside of restic for those who do need the functionality.

It's always a fine line between "not enough functionality" and "feature creep". I'm trying to find the right balance, and there are plenty of features suggested in GitHub issues that probably won't get implemented for that reason.

In this case I think it's important that restic manages the data it leaves in the user's cache directory. I think programs using the cache directory should also include functions to cleanup that data. I don't like it when programs leave large amounts of data in the cache directory without a plan when and how this data is removed eventually (several image viewers come to my mind, I once collected around 20GiB of preview images). We cannot do anything about data in the cache directory when restic isn't run, but when it is, it should detect stale data stored in the cache dir and act accordingly.

I'm open for suggestions/opinions whether or not restic automatically removes stale cached data (that was my initial idea), I'm also open to not removing it by default and letting the user decide what to do. In this case we need to print at least a warning so that the users are aware that there is stale data.

We can discuss the actual implementation, I don't mind having a `cleanup-cache` command instead of a `cache` command with a `--cleanup` flag. Or even a global flag `--cleanup-cache` or so.

**Comment by legrostdg** [comment]
If a cronjob ran successfully, it does not seem very convenient to report a warning to the user... I would prefer to be able to clean the cache automatically (by default or with a global flag).

**Comment by pvgoran** [comment]
> If a cronjob ran successfully, it does not seem very convenient to report a warning to the user...

I second this. If each successful (!) cronjob generates an unimportant warning like this, the user can easily be overwhelmed by the stream of emails from cron, and then start missing really important emails from cronjobs.

So maybe instead of the flag specific for this particular warning, it could be a generic flag like "--no-transient-warnings" (probably not the best name), that would silence all "unimportant" warnings (those that don't indicate that anything went wrong).

**Comment by fd0** [comment]
I've amended the code and incorporated your feedback, thanks! The message about old cache dirs is now a notice that isn't printed when `--quiet` is passed. I've also removed the `cache` command in favor of a global `--cleanup-cache` (default is off) option that allows restic to automatically remove old cache dirs (if there are some).

Thanks again for the feedback.

**Comment by pvgoran** [comment]
Will `restic --cleanup-cache` (without any command) just clean up the cache, then?

**Comment by fd0** [comment]
Yes

**Comment by fd0** [comment]
Ah, I'm wrong: `restic --clenaup-cache` without any command won't cleanup the cache, it needs at least a command.

**Comment by pvgoran** [comment]
It's a small interface problem, then. :) I believe users shouldn't be forced to issue a fake/unrelated command, if all they want is to perform cache cleanup.

**Comment by rawtaz** [comment]
`restic prune --cache` FTW (to have `prune` only clean the cache and not the repo).

**Comment by fd0** [comment]
I've decided to leave this for now. We'll see how it goes. Thanks again for the feedback!

**Comment by meisterluk** [comment]
Sadly the situation on this issue did not improve for me:

```
meisterluk@lagrange ~ % time restic-0.8.3 -r "sftp:somesshconfig:." unlock
user@secret-sftp-account's password: 
enter password for repository: 
password is correct
found 1 old cache directories in /home/meisterluk/.cache/restic, pass --cleanup-cache to remove them
successfully removed locks
restic-0.8.3 -r "sftp:somesshconfig:." unlock  0.50s user 0.06s system 4% cpu 12.360 total
meisterluk@lagrange ~ % time restic-0.8.3 -r "sftp:somesshconfig:." check --cleanup-cache
user@secret-sftp-account's password: 
enter password for repository: 
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
restic-0.8.3 -r "sftp:somesshconfig:." check --cleanup-cache  528.58s user 126.37s system 18% cpu 59:54.93 total
meisterluk@lagrange ~ % time restic-0.8.3 -r "sftp:somesshconfig:." backup ~ --tag home
user@secret-sftp-account's password: 
enter password for repository: 
password is correct
found 1 old cache directories in /home/meisterluk/.cache/restic, pass --cleanup-cache to remove them
using parent snapshot 0ab59a3b
scan [/home/meisterluk]
[...]
```

Expected behavior:
1. Call `check --cleanup-cache`
2. No warning

Actual behavior:
1. Call `check --cleanup-cache`
2. warning `found 1 old cache directories [...], pass --cleanup-cache to remove them` triggered

Just for reference: I created the repository with `restic-0.8.1` after its release and backed up data regularly since. The issue does not seem to create any problems though.

**Comment by fd0** [comment]
Hu? That's odd. Can you please paste a listing? `ls -al /home/meisterluk/.cache/restic`

**Comment by meisterluk** [comment]
```
meisterluk@lagrange ~ % ls -la /home/meisterluk/.cache/restic
total 12
drwx------ 1 meisterluk meisterluk 1176 Mar 23 19:15 .
drwx------ 1 meisterluk meisterluk 5864 Apr 15 15:21 ..
drwx------ 1 meisterluk meisterluk  672 Apr 14 23:53 7c64943ddf5a6ba88acb40d5e0f839900ab5d4d4fdccf2b030e6d2b4c559851b
drwx------ 1 meisterluk meisterluk  672 Jan 11 02:45 9bcce072293ea9a3c24718bb49d8827727161465ad901da474002f0c75909e4a
drwx------ 1 meisterluk meisterluk  672 Apr 15 15:24 9bf34f15a7b6784e018f488f562133ee611daf7c5612af75eb43018925c18c77
-rw-r--r-- 1 meisterluk meisterluk   44 Jan 11 02:45 CACHEDIR.TAG
meisterluk@lagrange ~ % find /home/meisterluk/.cache/restic | wc -l
435
meisterluk@lagrange ~ % cat /home/meisterluk/.cache/restic/CACHEDIR.TAG 
Signature: 8a477f597d28d172789f06886806bc55
meisterluk@lagrange ~ % time restic-0.8.3 -r "sftp:somesshconfig:." backup ~ --tag home
user@secret-sftp-account's password: 
enter password for repository: 
password is correct
found 1 old cache directories in /home/meisterluk/.cache/restic, pass --cleanup-cache to remove them
using parent snapshot 8700b986
scan [/home/meisterluk]
error for /home/meisterluk/.dbus: open /home/meisterluk/.dbus: permission denied
error for /home/meisterluk/.gvfs: open /home/meisterluk/.gvfs: permission denied
scanned 37206 directories, 209775 files in 1:09
error walking dir meisterluk/.dbus: Open: open /home/meisterluk/.dbus: permission denied
error walking dir meisterluk/.gvfs: Open: open /home/meisterluk/.gvfs: permission denied
[2:31] 100.00%  39.286 GiB / 39.286 GiB  247002 / 246981 items  2 ... ETA 0:00 
duration: 2:31
snapshot f712c161 saved
52.74user 30.31system 4:05.09elapsed 33%CPU (0avgtext+0avgdata 843592maxresident)k
8551200inputs+257720outputs (1315major+220488minor)pagefaults 0swaps
restic-0.8.3 -r "sftp:somesshconfig:." check --cleanup-cache  52.74s user 30.32s system 33% cpu 4:05.10 total
meisterluk@lagrange ~ % time restic-0.8.3 -r "sftp:somesshconfig:." check --cleanup-cache
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
subprocess ssh: packet_write_wait: Connection to [secret IPv4-address] port 22: Broken pipe
Load(<data/2cd5f2b08a>, 1551, 3192173) returned error, retrying after 257.896163ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 1175, 3189830) returned error, retrying after 327.614316ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 416, 3496970) returned error, retrying after 484.28068ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 424, 2331072) returned error, retrying after 685.774907ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 1183, 3187043) returned error, retrying after 434.066558ms: failed to send packet header: write |1: file already closed
unable to refresh lock: OpenFile: EOF
Load(<data/2cd5f2b08a>, 416, 2495775) returned error, retrying after 386.14653ms: failed to send packet header: write |1: file already closed
Load(<data/cc7bb04294>, 415, 952125) returned error, retrying after 296.323404ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 418, 2494941) returned error, retrying after 432.333568ms: failed to send packet header: write |1: file already closed
Load(<data/cc7bb04294>, 415, 967379) returned error, retrying after 376.321979ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 3035, 3423243) returned error, retrying after 691.388842ms: failed to send packet header: write |1: file already closed
Load(<data/cc7bb04294>, 414, 969780) returned error, retrying after 622.904068ms: failed to send packet header: write |1: file already closed
Load(<data/cc7bb04294>, 418, 948884) returned error, retrying after 534.024959ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 418, 3496136) returned error, retrying after 731.009626ms: failed to send packet header: write |1: file already closed
Load(<data/cc7bb04294>, 417, 966547) returned error, retrying after 251.140502ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 1178, 3178480) returned error, retrying after 398.999774ms: failed to send packet header: write |1: file already closed
Save(<lock/bd3e294ae5>) returned error, retrying after 500.518966ms: OpenFile: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 415, 3547927) returned error, retrying after 513.798916ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 419, 2516965) returned error, retrying after 564.770568ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 416, 2521884) returned error, retrying after 438.60325ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 416, 2580161) returned error, retrying after 609.732489ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 418, 3647274) returned error, retrying after 370.869202ms: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 416, 3648108) returned error, retrying after 251.832626ms: failed to send packet header: write |1: file already closed
[...]
Load(<data/2cd5f2b08a>, 416, 3496970) returned error, retrying after 3.104918847s: failed to send packet header: write |1: file already closed
Load(<data/2cd5f2b08a>, 414, 3749745) returned error, retrying after 2.603952225s: failed to send packet header: write |1: file already closed
  signal interrupt received, cleaning up
no errors were found
Save(<lock/bd3e294ae5>) returned error, retrying after 2.324790676s: OpenFile: failed to send packet header: write |1: file already closed
^C^C^C^CSave(<lock/bd3e294ae5>) returned error, retrying after 6.358799522s: OpenFile: failed to send packet header: write |1: file already closed
^C^C


^C^CSave(<lock/bd3e294ae5>) returned error, retrying after 9.603101074s: OpenFile: failed to send packet header: write |1: file already closed
Save(<lock/bd3e294ae5>) returned error, retrying after 10.932434401s: OpenFile: failed to send packet header: write |1: file already closed
^C^C^C^C^C^C^CSave(<lock/bd3e294ae5>) returned error, retrying after 13.95390271s: OpenFile: failed to send packet header: write |1: file already closed
[2]    4184 killed     restic-0.8.3 -r $RESTIC_SYS010 check --cleanup-cache
restic-0.8.3 -r $RESTIC_SYS010 check --cleanup-cache  466.56s user 112.24s system 8% cpu 1:52:22.61 total
137 meisterluk@lagrange ~ % md5sum =restic-0.8.3 
4b02c7b1ae4eb18e5ff54f3cc2eeca01  /home/meisterluk/bin/restic-0.8.3
meisterluk@lagrange ~ % ls -la /home/meisterluk/.cache/restic
total 12
drwx------ 1 meisterluk meisterluk 1176 Mar 23 19:15 .
drwx------ 1 meisterluk meisterluk 5864 Apr 15 17:42 ..
drwx------ 1 meisterluk meisterluk  672 Apr 14 23:53 7c64943ddf5a6ba88acb40d5e0f839900ab5d4d4fdccf2b030e6d2b4c559851b
drwx------ 1 meisterluk meisterluk  672 Jan 11 02:45 9bcce072293ea9a3c24718bb49d8827727161465ad901da474002f0c75909e4a
drwx------ 1 meisterluk meisterluk  672 Apr 15 17:20 9bf34f15a7b6784e018f488f562133ee611daf7c5612af75eb43018925c18c77
-rw-r--r-- 1 meisterluk meisterluk   44 Jan 11 02:45 CACHEDIR.TAG
meisterluk@lagrange ~ % find /home/meisterluk/.cache/restic | wc -l
440
meisterluk@lagrange ~ % cat /home/meisterluk/.cache/restic/CACHEDIR.TAG
Signature: 8a477f597d28d172789f06886806bc55
```

Hm, seems like I run into a bunch of problems. Not aware of anything I did wrong from my side, though. I guess, I will have to trash my backup repository and create a new one.

Is it normal, that cache files only have the read-bit set?
```
meisterluk@lagrange ~ % ls -la /home/meisterluk/.cache/restic/9bf34f15a7b6784e018f488f562133ee611daf7c5612af75eb43018925c18c77/snapshots/f7/f*                                                               
-r-------- 1 meisterluk meisterluk 341 Apr 15 15:28 /home/meisterluk/.cache/restic/9bf34f15a7b6784e018f488f562133ee611daf7c5612af75eb43018925c18c77/snapshots/f7/f712c161193c51b205e5c67ce368a7b7b8e6937b6754db89c8a1217003ead1f3
```
