### ISSUE TITLE
Very little progress output on prune

### ISSUE THREAD

**Issue by darkskiez** [restic/restic#1322]
## Output of `restic version`

restic 0.7.2 (v0.7.2-0-g5b1e4df1)

## How did you run restic exactly?
 
restic prune

## What backend/server/service did you use?

sftp

## Expected behavior

pruned repo

## Actual behavior

12h so far of:

counting files in repo

## Steps to reproduce the behavior

Have a large remote repo

## Do you have an idea how to solve the issue?

Some progress on the prune would be nice (if it cant be made faster.)

**Comment by fd0** [comment]
Huh, that's really odd. Between the line "counting files in repo" and the start of the progress output it really only lists the files in the backend. Is maybe the terminal output blocked? Can you try pressing ^Q (ctrl+Q)?

Or has the sftp connection stalled?

It really shouldn't take so much time.

**Comment by darkskiez** [comment]
So, I sadly think its a problem with restic over slow links.. I tried running prune locally but the RPI3 OOMed pretty quickly..

I've sadly had to give up on restic for now, trying borgbackup instead as it seems robust to over-the-internet backups.

**Comment by fd0** [comment]
But that's a different problem. We already know that restic needs a lot of memory right now (and we need to work on that), but what about the slow sftp connection?

I can understand if you don't have any interested to investigate further (and I'm happy you've found a backup solution that works for you), so feel free to close this issue.
