### ISSUE TITLE
SFTP Permission denied do not say what path failed, and sometimes error silently

### ISSUE THREAD

**Issue by darkskiez** [restic/restic#1323]
## Output of `restic version`

restic version
restic 0.7.2 (v0.7.2-0-g5b1e4df1)
compiled with go1.8.3 on linux/amd64

## How did you run restic exactly?

restic backup -x /

## What backend/server/service did you use?

sftp

## Expected behavior

SSH Permission denied "/path/to/repo/file"

## Actual behavior

SSH Permission denied [unknown file]

## Steps to reproduce the behavior

I had mounted a disk with my repo on it remotely but with the wrong user ids..

I chowned a bunch of files to the right id when I found out my mistake, but some
got missed after it had been cancelled

## Do you have any idea what may have caused this?

I was a bit silly.

## Do you have an idea how to solve the issue?

Add the path to the file that caused the error message.

If the key files are unreadable it silently fails with no error at all (this was a little scary)

**Comment by fd0** [comment]
Good point, thanks for raising this issue! It somehow fell off and I haven't read it, but @armhold fixed it in #1398. :)

**Comment by armhold** [comment]
I should add that I was not able to repro the "if key files are unreadable it silently fails" bit... I always got an error msg from the sftp client code; it just did not include the path.

If you can give more detail on how to reproduce that problem I can revisit.
