### ISSUE TITLE
Add option to create new snapshots only if there are changes

### ISSUE THREAD

**Issue by maxhq** [restic/restic#1329]
One might want to run `restic backup` quite often (e.g. hourly). It would then be nice to have an option to keep the snapshot list as small as possible by only adding new snapshots if there are actually any changed files.
I guess the snapshot creation is the first step Restic does. So maybe the actual implementation could just delete the newly created snapshot if the backup process did not pick up any changed files.

**Comment by ignus2** [comment]
Hi, didn't notice there is a new issue, this was already requested by someone before in #662 I added my comments there.
I second this request!

**Comment by fd0** [comment]
Since there's already an issue (#662) with a discussion I'm closing this one as a duplicate.
