### ISSUE TITLE
fuse mount: parallel execution of mount and backup

### ISSUE THREAD

**Issue by mungomat** [restic/restic#1330]
Currently after being mounted the directory does not recognize new snapshots. So the user has to remount the repository after every backup.

I made some promising tests where the mounted directory could show newly generated snapshots. No need to unmount for every backup. Unfortunately this requires a reloading of the index every time the user does a "ls /mnt/snapshots" which takes time.

Questions:
- Would it be a useful feature?
- What about other operations parallel to a mount (forget, prune)?
- Is there a faster way to recognize a repository-change despite reloading the index?

**Comment by fd0** [comment]
That'd be useful indeed, but will require significant changes to the fuse code. It'd need to create a non-exclusive lock in the repo, so that `backup` works fine, but `forget` and `prune` won't.

The best way to find out if there is new data is to reload the list of snapshots.

**Comment by benschumacher** [comment]
This appears to be closed with #1337.

**Comment by fd0** [comment]
Indeed, thanks for the hint! I'm closing this issue.
