### ISSUE TITLE
fuse mount: mounting without user interaction

### ISSUE THREAD

**Issue by mungomat** [restic/restic#1331]
Currently mounting a restic repository is started via 'restic mount' and after mounting restic waits for the user to hit control-c.
You can however unmount it on a different terminal with 'fusermount -u'. In this case restic stops with 'unable to umount (maybe already umounted?): exit status 1: fusermount: entry for /mnt/restic not found in /etc/mtab'

This is in contrast to other mounting mechanisms where you have one program for mounting and another for unmounting.

Wouldn't it be better to have 'restic mount' and 'restic unmount'?

**Comment by fd0** [comment]
Yes, good idea, at least for `mount` that's rather easy: Start restic in a subprocess and exit the main process.

**Comment by darioseidl** [comment]
Hi,
I'm new to restic and currently evaluating it. It looks really promising!
I was quite confused by the mount command, I assumed there was a bug and it was hanging/sleeping here:

```
sudo restic -r /mnt/backup/restic-local/ mount /mnt/restic/
enter password for repository: 
Now serving the repository at /mnt/restic/
Don't forget to umount after quitting!
```

Just to confirm, this is expected behavior, i.e. it is done mounting at this point and it is save to stop the process with Ctrl+C?

**Comment by fd0** [comment]
Yes, that's the expected behavior (at least for now).

**Comment by darioseidl** [comment]
Okay, thanks for confirming. All good.

As you can guess, I agree that an `unmount` command would be nicer.

**Comment by darioseidl** [comment]
I'm back at using restic and remembered this (and saw that it was still open).

I think the easiest way to avoid confusion would be to add an example to the documentation showing how to safely mount and unmount in one shell:

Run restic mount in the background (with `&`):
```
$ restic -r /tmp/backup mount /mnt/restic &
enter password for repository:
Now serving /tmp/backup at /tmp/restic
Don't forget to umount after quitting!
```
Do some work with the mounted backup:
```
$ ls /mnt/restic/snapshots/latest/
...
```
Send SIGINT to restic to unmount:
```
$ pkill -2 restic
```

That's the way I do it at least.

**Comment by mholt** [comment]
FWIW, I've been automating `restic mount` for a while now with no problems. Simply signal it when you're done to unmount it (as you suggested above).
