### ISSUE TITLE
Fails to connect to Minio server

### ISSUE THREAD

**Issue by jeffdupont** [restic/restic#1341]
## Output of `restic version`
restic 0.7.3
compiled with go1.9.1 on darwin/amd64

## How did you run restic exactly?
restic -r s3:http://192.168.1.153:9000/backups snapshots

## What backend/server/service did you use?
minio

## Expected behavior
I expected restic to prompt me for the password and then list my snapshots

## Actual behavior
unable to open config file: Stat: Get http://169.254.169.254/latest/meta-data/iam/security-credentials: dial tcp 169.254.169.254:80: i/o timeout
Is there a repository at the following location?
s3:http://192.168.1.153:9000/backups

I recently had to restore my system and reinstall everything. I loaded restic according to the documentation using brew. I tested out the minio server and confirmed that I can A. get to it from the browser and B. i can telnet to the IP and port to trigger a non-HTTP message in the minio logs. The restic attempt does not log any sort of attempt to the minio server so I'm not sure that it is even making a connection attempt to minio.

**Comment by fd0** [comment]
Thanks for the report. Could you please build restic with debug support and create a [debug logfile](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)? It will contain all HTTP requests/responses, so please redact the authentication information from the log.

I have a hunch that Minio redirects the restic client to this strange looking link-local IP address (169.254.169.254), so we may need to involve the Minio people :)

Please report back.

**Comment by jeffdupont** [comment]
I will report back on the debug info, but I have another system that also
back ups to the same minio server and that one has no issues.

**Comment by fd0** [comment]
That makes this issue even more interesting. What's different between the two systems? Same version of restic?

**Comment by jeffdupont** [comment]
Second system is running 0.7.1 built on go1.8.3.  Maybe there's something
in the code changes between those versions.

**Comment by jeffdupont** [comment]
Thanks to the debug log I was able to notice that it was not setting the
KeyID from the environment variables. Took a look at the env for the KEY_ID
and i had a misspelling in the variable name. Fixed the spelling error and
tested again successfully. Thanks!!!

**Comment by fd0** [comment]
Hm, thanks for the feedback, can you please have a look what the Minio server does when the key ID is empty? Did it redirect to the link-local IP address? Which environment variable was it that had the typo? What's the version of the Minio server that you used?

**Comment by jeffdupont** [comment]
When the key is not set, that is when restic attempts to pull IAM
credentials using the AWS 169.254.169.254 IP address. This end up trying to
hit that IP from my local machine and since minio is not running locally
that request never hits my remote minio and just times out.

**Comment by fd0** [comment]
@harshavardhana Would you mind taking a look? Is that a bug, in either minio or minio-go?

**Comment by jeffdupont** [comment]
I would think that this is an issue more with Restic and how it attempts to
pull IAM credentials if the KEY ID and/or SECRET is not provided in the
env. My minio server logs were never hit during this issue because it did
not have all the necessary configurations to make a valid request.

**Comment by harshavardhana** [comment]
> @harshavardhana Would you mind taking a look? Is that a bug, in either minio or minio-go?

This minio-go IAM support support @fd0 not sure why it is being enabled unless explicitly asked in the NewWithCredentials() initialization.

**Comment by harshavardhana** [comment]
Looks like perhaps due to this recent fix? - https://github.com/restic/restic/issues/1067 @jeffdupont are you sure your access and secret keys are set properly?

**Comment by harshavardhana** [comment]
Here you go refactored the credentials management https://github.com/restic/restic/pull/1345 @fd0

**Comment by jeffdupont** [comment]
I did have a spelling error on the access key which was why the value was
missing when I looked at the debug log. Problem I see is that A, restic was
attempting to access the IAM credentials from the local machine assuming
that the S3 was there by calling the 169.254.169.254 address despite
providing a remote path to the server. And B, the error could more clearly
specify that the access key was not provided. Until I had looked at the
logs I had no idea of the spelling error. Could've saved me a lot of
frustration.

**Comment by fd0** [comment]
@jeffdupont can you retry with the latest master that includes #1345? That'd be great!

**Comment by jeffdupont** [comment]
Well I was able to rebuild the binary and connect with only having to provide the -r url to the minio server. I did not have any env variables set at the time (used a new terminal instance to make sure that the profile was clean). I would think that I should still need to provide those security variables to connect properly. Aside from that, everything worked.

**Comment by harshavardhana** [comment]
> Well I was able to rebuild the binary and connect with only having to provide the -r url to the minio server. I did not have any env variables set at the time (used a new terminal instance to make sure that the profile was clean). I would think that I should still need to provide those security variables to connect properly. Aside from that, everything worked.

did you have any envs set?

**Comment by jeffdupont** [comment]
Nothing related to restic, minio, or aws.

**Comment by rawtaz** [comment]
Is this still an issue or can it be closed?

**Comment by fd0** [comment]
I'll close it, please report back and add a comment if it's still an issue. Thanks!
