### ISSUE TITLE
Option to store files with absolute path name

### ISSUE THREAD

**Issue by LordGaav** [restic/restic#1344]
## Output of `restic version`
```
# restic version
restic 0.7.3
compiled with go1.9 on linux/amd64
```

## How did you run restic exactly?

```
# cat /etc/restic/files.include 
/etc/letsencrypt
/etc/nginx
/etc/ssh
/var/www/nextcloud
/var/data/nextcloud
# cat /etc/restic/files.exclude
# restic backup --files-from /etc/restic/files.include --exclude-file /etc/restic/files.exclude
```

## What backend/server/service did you use?

swift on openstack, also tried with b2.

## Expected behavior

Paths are named using an absolute path name, I excepted the full paths to be present in the backup.

## Actual behavior

Paths are actually stored using the last part of the path. This causes duplication is my case, for instance:

```
# restic mount tmp/
Now serving the repository at tmp/
Don't forget to umount after quitting!

# ls -1 tmp/snapshots/2017-10-09T16\:25\:42Z/                                                                                    
letsencrypt
nextcloud
nextcloud-1
nginx
ssh
```

## Do you have an idea how to solve the issue?

I would like an option to store found files under paths with only the leading `/` removed, mimicking for instance the way that `tar` handles paths. This makes it easier to find files.

**Comment by fd0** [comment]
I'm sorry to just close the issue so quickly, but we're already aware of the current limitation, and this is tracked in #549. Please subscribe over there, thanks! :)

**Comment by LordGaav** [comment]
Ah, that's ok. I tried to find an existing issue, but couldn't find one.

Great response time though ;)

**Comment by fd0** [comment]
Heh, yeah, I was just browsing the issues when you submitted it ;)
