### ISSUE TITLE
go panic during S3 backup

### ISSUE THREAD

**Issue by ctberthiaume** [restic/restic#1349]
## Output of `restic version`

restic 0.7.3 (v0.7.3-87-g3afd974d)
compiled with go1.9 on linux/amd64

## How did you run restic exactly?

```
restic -r s3:s3.amazonaws.com/mybucket/home init
restic -r s3:s3.amazonaws.com/mybucket/home backup home/
```

## What backend/server/service did you use?
S3

## Expected behavior
Successful backup with no error or stack trace. It looks like restic caught the error based on "error while saving data to the repo", but then I'm not really sure how to interpret the panic and stack trace. Either restic should do more retries when encountering this error or if the retry limit has been reached at least exit more cleanly.

## Actual behavior
Error with stack trace
```
$ restic -r s3:s3.amazonaws.com/mybucket/home init
enter password for new backend: 
enter password again: 
created restic backend f82b336ee6 at s3:s3.amazonaws.com/mybucket/home

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

$ restic -r s3:s3.amazonaws.com/mybucket/home backup home/
enter password for repository: 
scan [/media/data/backup/home]
scanned 223870 directories, 2309793 files in 3:41
[1:15:27] 5.03%  57.200 MiB/s  252.874 GiB / 4.913 TiB  95872 / 2533663 items  0 errors  ETA 23:45:44 
error while saving data to the repo: Put https://s3-us-west-2.amazonaws.com/mybucket/home/data/d3/d369f4e67aaad876b05537c16c66b5784437cc4fbbdcdcd42ebbc345ea384baf: net/http: HTTP/1.x transport connection broken: write tcp 192.168.5.3:45742->54.231.184.216:443: write: connection reset by peer
client.PutObject
github.com/restic/restic/internal/backend/s3.(*Backend).Save
	src/github.com/restic/restic/internal/backend/s3/s3.go:283
github.com/restic/restic/internal/cache.(*Backend).Save
	src/github.com/restic/restic/internal/cache/backend.go:69
github.com/restic/restic/internal/repository.(*Repository).savePacker
	src/github.com/restic/restic/internal/repository/packer_manager.go:107
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
	src/github.com/restic/restic/internal/repository/repository.go:250
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
	src/github.com/restic/restic/internal/repository/repository.go:637
github.com/restic/restic/internal/archiver.(*Archiver).Save
	src/github.com/restic/restic/internal/archiver/archiver.go:104
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
	src/github.com/restic/restic/internal/archiver/archiver.go:161
runtime.goexit
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:2337
panic: client.PutObject: Put https://s3-us-west-2.amazonaws.com/mybucket/home/data/d3/d369f4e67aaad876b05537c16c66b5784437cc4fbbdcdcd42ebbc345ea384baf: net/http: HTTP/1.x transport connection broken: write tcp 192.168.5.3:45742->54.231.184.216:443: write: connection reset by peer

goroutine 322890 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc420562320, 0xe273a0, 0xc4200120a0, 0xc30911fd, 0x359d23, 0x1397335b00000, 0xc46ddf4000, 0x359d23, 0x928000, 0xc420090370, ...)
	src/github.com/restic/restic/internal/archiver/archiver.go:166 +0x41b
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
	src/github.com/restic/restic/internal/archiver/archiver.go:240 +0x3d0
```

## Steps to reproduce the behavior
Since it looks like this was caused by some transient network error it'll be hard to reproduce.

## Do you have any idea what may have caused this?
Not really. Looks like an unhandled network error but beyond that I'm not sure.

## Do you have an idea how to solve the issue?
No

**Comment by Tomdarkness** [comment]
Same problem, some kind of transient network issue causes the client to panic:

```
error while saving data to the repo: Post xxx: dial tcp: lookup xxx.s3-eu-wes
t-1.amazonaws.com: no such host
client.PutObject
github.com/restic/restic/internal/backend/s3.(*Backend).Save
        src/github.com/restic/restic/internal/backend/s3/s3.go:228
github.com/restic/restic/internal/repository.(*Repository).savePacker
        src/github.com/restic/restic/internal/repository/packer_manager.go:122
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:203
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:529
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:104
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:161
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
panic: client.PutObject: Post https://xxx.s3-eu-west-1.amazonaws.com/xxx: dial tcp: lookup xxx.s3-eu-west-1.amazonaw
s.com: no such host

goroutine 255985 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc0421fa4b0, 0xdb82c0, 0xc042010128, 0x535d21, 0x22951
7, 0x1b60968fd00000, 0xc1213b6000, 0x229517, 0x266000, 0xc042228420, ...)
        src/github.com/restic/restic/internal/archiver/archiver.go:166 +0x422
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
        src/github.com/restic/restic/internal/archiver/archiver.go:240 +0x3d7
```

Would expect it to re-try with exponential backoff rather than just panicing

**Comment by Tomdarkness** [comment]
This is making is basically impossible for me to complete my initial backup since every time it fails it takes hours to scan everything again before actually continuing with the upload and then it fails with something like:

error while saving data to the repo: Post https://xxx.s3-eu-west-1.amazonaws.com/xxx: http: server closed idle connection
client.PutObject
github.com/restic/restic/internal/backend/s3.(*Backend).Save
        src/github.com/restic/restic/internal/backend/s3/s3.go:228
github.com/restic/restic/internal/repository.(*Repository).savePacker
        src/github.com/restic/restic/internal/repository/packer_manager.go:122
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:203
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:529
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:104
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:161
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
panic: client.PutObject: Post https://xxx.s3-eu-west-1.amazonaws.com/xxx: http: server closed idle connection

goroutine 253251 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc042144460, 0xdb82c0, 0xc042010150, 0x8fb26f, 0x2780f
3, 0xc18d8f1200000, 0xc049b6c000, 0x2780f3, 0x3c0000, 0xc0423524d0, ...)
        src/github.com/restic/restic/internal/archiver/archiver.go:166 +0x422
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
        src/github.com/restic/restic/internal/archiver/archiver.go:240 +0x3d7

**Comment by fd0** [comment]
Thanks for taking the time to report this issue. It's a common problem with AWS S3, and the library we're using for accessing S3 will retry a few times before giving up. You can try to use `-o s3.retries=5` or even higher to set the number of retries.

I also agree that restic should return a meaningful error message and not just dump a stack trace.

**Comment by ctberthiaume** [comment]
restic errored out in the same fashion on a subsequent backup last night. I'm trying again with a higher retry setting. I understand that different retry limits make sense for different cases and it's hard to find the right number that satisfies all cases, so I'm not suggesting that the default retry limit should be increased. But since this will probably be a fairly common error it might be nice to include the suggestion to increase the retry limit with `-o s3.retries=n` in the error message itself (minus stack trace). And a note on why this error occurs and how to increase the retry limit for various network backends would be helpful somewhere in the docs.

**Comment by fd0** [comment]
FYI, you can also try to lower the number of parallel connections to the server via `-o s3.connections=2` (default is 5).

**Comment by Tomdarkness** [comment]
Thanks. I've tried `-o s3.retries=1000` but it still fails with a panic. Not sure how high this should be but 1000 seems very high already. At the moment it literally fails pretty much as soon as it gets to the point where it failed last time. So it spends about 2hrs reading the files it's already uploaded then literally as soon as it gets to the point where it failed last time it panics.

**Comment by ctberthiaume** [comment]
My initial backup succeeded using `-o s3.retries=10`. I didn't change `s3.connections`. Now I'm rebuilding the index and pruning to clean up the incomplete attempts. Thanks for pointing me to the retry option.

**Comment by Phaeilo** [comment]
I'm also seeing this issue with 0.7.1 every few nights. I'll give `-o s3.retries=10` a shot.

**Comment by fd0** [comment]
In the meantime I've added code in the master branch that retries saving data in the backend on a higher level, maybe give that a try?

**Comment by Phaeilo** [comment]
Tried 0.7.3 which resulted in a out-of-memory condition somewhere in the minio code. Afterwards I deployed v0.7.3-180-g7507a658 which seems to work fine.

**Comment by fd0** [comment]
Thanks for the feedback!

**Comment by lian** [comment]
`v0.7.3-195-g8d37b723` (current master) finally makes s3 backend usable again. 💯 ❤️

**Comment by ishworgurung** [comment]
Thanks. The `master` branch with `-o s3.retries=<large N>` and `--limit-upload N` did the trick for me on a relatively unstable, volatile and poorly managed network provider.

**Comment by lloeki** [comment]
@fd0 indeed the 0.7.3 release seems to leak like a sieve, causing crashes of the backup processes. Thanks @Phaeilo, I'll be trying master after v0.7.3-180-g7507a658.

**Comment by fd0** [comment]
I'm going to close this issue, it is resolved in master. A new release is not far away, in the meantime people can find beta releases here: https://beta.restic.net/?sort=time&order=desc
