### ISSUE TITLE
CI tests on darwin

### ISSUE THREAD

**Issue by fd0** [restic/restic#135]
Travis has support for CI tests on darwin, however this is in beta and must be enabled manually, see http://docs.travis-ci.com/user/multi-os/

Figure out how to do this and enable integration tests on darwin.

**Comment by fw42** [comment]
I sent an email to support@travis-ci.com, asking to enable the feature.

**Comment by fd0** [comment]
I'll leave this open until the travis people respond. Thanks for your contribution!

**Comment by fd0** [comment]
I've added cross-compilation tests with gox in 94ecdc6e84829bd5a1ca26d7cc945d2b4db355d3 so we can spot things like #136 early.

**Comment by fw42** [comment]
> Hey Florian,
> 
> Thanks for your email.
> 
> Unfortunately, at the moment we don't accept any further projects into our multi-os feature, as we're 
> currently revamping our Mac cloud and increasing its capacity too.
> 
> We should be ready for more projects in a couple of weeks' time.
> 
> Cheers, Mathias

**Comment by fd0** [comment]
Bummer, but thanks for trying. We can reapply in a few weeks. ;)

**Comment by fw42** [comment]
I sent another email...

> Hey folks,
> 
> already asked about this about two months ago and I was told it will
> take a few more weeks, so I thought I'd just check again now.
> 
> Can we get the Darwin test beta feature for the restic/restic repository?
> 
> For reference: https://github.com/restic/restic/issues/135
> 
> Thanks
> 
> Flo

**Comment by fw42** [comment]
> Hey Flo,
> 
> Thanks for getting in touch again. Our OS X capacity is getting better, so I've just enabled multi OS
> support for restic/restic.
> 
> Here's what to add in your `.travis.yml`: http://docs.travis-ci.com/user/multi-os/#Setting-.travis.yml
> 
> Please note that it's currently on beta so please let us know anything you feel can be improved or
> anything you miss.
> 
> If you got any other questions - just let us know!
> 
> Have a great day!
> 
> María

**Comment by fw42** [comment]
Since we already have the `- osx` line in our Travis config (https://github.com/restic/restic/pull/138), I think this issue can be closed now.

**Comment by fw42** [comment]
<img width="690" alt="screen shot 2015-07-08 at 9 04 32 am" src="https://cloud.githubusercontent.com/assets/2072686/8570722/5d66a724-2550-11e5-8ec6-10800d758710.png">

Seems to work. Even though the tests are failing on OS X right now because of some ModTime shit.

**Comment by fd0** [comment]
Awesome! Thanks for following up with the folks from Travis!
