### ISSUE TITLE
Restored from a remote location folder (via zip-file) doesn't pass check

### ISSUE THREAD

**Issue by thumbline** [restic/restic#1357]
## Output of `restic version`
restic 0.7.3
compiled with go1.9 on windows/amd64

## How did you run restic exactly?
D:\Temp\gopath\bin\restic -r ./archive check

## What backend/server/service did you use?
Mega.nz

## Expected behavior
Restore folder should allow check

## Actual behavior
```
D:\Temp\gopath\bin\restic -r ./archive check
enter password for repository:
Create exclusive lock for repository
open \\?\D:\Users\User\Desktop\_restic_ar_remote\archive\locks\f2df6a34d1051d8ba5f2b6bc7f27cc9c86743ca123a738ac38f9e0ac6eb09b0e: The system cannot find the path specified.
OpenFile
github.com/restic/restic/internal/backend/local.(*Local).Save
        src/github.com/restic/restic/internal/backend/local/local.go:132
github.com/restic/restic/internal/repository.(*Repository).SaveUnpacked
        src/github.com/restic/restic/internal/repository/repository.go:230
github.com/restic/restic/internal/repository.(*Repository).SaveJSONUnpacked
        src/github.com/restic/restic/internal/repository/repository.go:215
github.com/restic/restic/internal/restic.(*Lock).createLock
        src/github.com/restic/restic/internal/restic/lock.go:173
github.com/restic/restic/internal/restic.newLock
        src/github.com/restic/restic/internal/restic/lock.go:102
github.com/restic/restic/internal/restic.NewExclusiveLock
        src/github.com/restic/restic/internal/restic/lock.go:70
main.lockRepository
        src/github.com/restic/restic/cmd/restic/lock.go:36
main.lockRepoExclusive
        src/github.com/restic/restic/cmd/restic/lock.go:27
main.runCheck
        src/github.com/restic/restic/cmd/restic/cmd_check.go:87
main.glob..func5
        src/github.com/restic/restic/cmd/restic/cmd_check.go:25
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:650
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:729
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:688
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
```

## Steps to reproduce the behavior
Just backup a restic backup folder to mega.nz. Then try to download it from remote as a *.zip file.

## Do you have any idea what may have caused this?
By simple comparison between local and remote archive it could be seen that empty folders under data (like "00", "0a", etc.) don't exist after unpacking zip-file (they actually exist remotely, but due to the way zip-file is created, they disappear).

## Do you have an idea how to solve the issue?
I think empty non-existing folders under "data" should be either dismissed or auto-restored. If there is already a step that might help to fix the problem manually, it should be mentioned in the error output.

**Comment by fd0** [comment]
Thanks for the report. This is already resolved in the master branch, which will just create the directory `locks` if it does not exist.

Second, you can also check the repository without locking, by using `restic check --no-lock`. Can you try that and report back? Thanks!

I'm going to close this issue for now (since it is already resolved in master). Please feel free to add further comments, thanks!

**Comment by thumbline** [comment]
Correct --no-lock passes. I'll try master branch! Thank you @fd0
