### ISSUE TITLE
Retry sftp if ssh connection dies

### ISSUE THREAD

**Issue by jgfrm** [restic/restic#1364]
With sftp, sometimes the connection dies.

Error:
error while saving data to the repo: failed to send packet header: write |1: file already closed
github.com/restic/restic/vendor/github.com/pkg/sftp.sendPacket
        src/github.com/restic/restic/vendor/github.com/pkg/sftp/packet.go:132
github.com/restic/restic/vendor/github.com/pkg/sftp.(*conn).sendPacket
        src/github.com/restic/restic/vendor/github.com/pkg/sftp/conn.go:31
github.com/restic/restic/vendor/github.com/pkg/sftp.(*clientConn).dispatchRequest
        src/github.com/restic/restic/vendor/github.com/pkg/sftp/conn.go:106
github.com/restic/restic/vendor/github.com/pkg/sftp.(*clientConn).sendPacket
        src/github.com/restic/restic/vendor/github.com/pkg/sftp/conn.go:97
github.com/restic/restic/vendor/github.com/pkg/sftp.(*Client).open
        src/github.com/restic/restic/vendor/github.com/pkg/sftp/client.go:401
github.com/restic/restic/vendor/github.com/pkg/sftp.(*Client).OpenFile
        src/github.com/restic/restic/vendor/github.com/pkg/sftp/client.go:396
github.com/restic/restic/internal/backend/sftp.(*SFTP).Save
        src/github.com/restic/restic/internal/backend/sftp/sftp.go:324
github.com/restic/restic/internal/repository.(*Repository).savePacker
        src/github.com/restic/restic/internal/repository/packer_manager.go:122
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:203
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:529
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:104
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:161
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337

It would be nice if restic retries the connection.

**Comment by fd0** [comment]
You're right, but we already have an issue for that (#353), so I'm going to close this issue as a duplicate. Please subscribe over there, thanks!
