### ISSUE TITLE
Prune error: number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by jkahrs** [restic/restic#1366]
## Output of `restic version`
restic 0.7.3 (v0.7.3-154-g9ce2a73f)
compiled with go1.9.1 on linux/amd64

## How did you run restic exactly?
restic -r sftp://{{ my_backup_server }}//home/backups prune
enter password for repository: 
password is correct
counting files in repo
building new index for repo
[0:12] 100.00%  24987 / 24987 packs
repository contains 24987 packs (3691414 blobs) with 111.785 GiB
processed 3691414 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 41 snapshots
[4:22] 100.00%  41 / 41 snapshots
number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

## What backend/server/service did you use?
sftp

## Expected behavior
prune completes without errors

## Actual behavior
prune quit at 100% with the following message:

[4:22] 100.00%  41 / 41 snapshots
number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

## Steps to reproduce the behavior
re-running prune against my repo

**Comment by fd0** [comment]
Thanks for the report! Can you please run `restic check --read-data` on that repo and report back?

**Comment by jkahrs** [comment]
enter password for repository: 
password is correct
Create exclusive lock for repository
Load indexes
Check all packs
Check snapshots, trees and blobs
Read all data
[59:19] 100.00%  24987 / 24987 items
duration: 59:19
No errors were found

**Comment by fd0** [comment]
Hm, that's very odd, we need to debug this together.

**Comment by fd0** [comment]
We've identified the issue: The repository contained several tree blobs that were also used as contents of files. This isn't detected by the checker, but prune fails for that.

**Comment by fd0** [comment]
I'm going to close this issue for now, the repo was in an unusual state.

Please leave a commit if you experience this issue so we can reopen it!
