### ISSUE TITLE
Allow comments in --file-from file, in the same way as --exclude-file

### ISSUE THREAD

**Issue by TobyLL** [restic/restic#1367]
## Output of `restic version`
restic 0.7.3
compiled with go1.9 on linux/amd64

## How did you run restic exactly?
$ echo '# Backup group 1' > /tmp/files-from
$ echo /tmp/backup.txt >> /tmp/files-from
$ echo Back me up > /tmp/backup.txt
$ restic -r /tmp/restic init
enter password for new backend:
enter password again:
created restic backend dd3bad435d at /tmp/restic

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
$ restic -r /tmp/restic backup --files-from=/tmp/files-from
**/tmp/# Backup group 1 does not exist, skipping**
enter password for repository:
scan [/tmp/backup.txt]
scanned 0 directories, 1 files in 0:00
[0:00] 100.00%  0B/s  11B / 11B  1 / 1 items  0 errors  ETA 0:00
duration: 0:00, 0.00MiB/s
snapshot 69829fe5 saved

## What backend/server/service did you use?
Any

## Expected behavior
Lines in the --from-file file that start with # are simply ignored

## Actual behavior
Lines in the --from-file file that start with # are treated as filenames, and processing is attempted

## Steps to reproduce the behavior
See above

## Do you have an idea how to solve the issue?
Will raise a pull request

**Comment by fd0** [comment]
Good idea, thanks for the report and the PR!
