### ISSUE TITLE
Concurrent restorer

### ISSUE THREAD

**Issue by is** [restic/restic#1370]
## Output of `restic version`

```
debug enabled
restic 0.7.3 (v0.7.3-172-ga8dc7934-dirty)
compiled with go1.9.1 on linux/amd64
```

## How did you run restic exactly?

```
restic restore -c 40 --target _ 18a2cde
```

## What backend/server/service did you use?
Any

## Actual behavior
Unlike backup, restore is a very slow process, especially when a lot of small files there.

## Steps to reproduce the behavior
restore a big snapshot (10G+, 40000+ dirs and files) to local filesystem.

## Do you have any idea what may have caused this?
The default restorer is worked in single thread.

## Do you have an idea how to solve the issue?
I try to rewrite a restorer, with worked in multiple goroutines pool.

background: I run restic on a stronger server, with 128G ram and 10G NIC.
I hope to finish backup/restore as soon as possible, without thinking to
much about CPU/memory consumption.

**Comment by creckx** [comment]
:+1: 

I would like to say this is the only thing which keeps us from using restic in production. Backup is superfast into our own minio cluster or SFTP connection, but restore is annoyingly slow. It's fine if you are not in hurry like with photos, but usually we are, because if we need the backup it means the service is down.

**Comment by fd0** [comment]
@is thanks for tackling this issue! I'll try to find time to review your PR the next couple of days and give you feedback.

**Comment by dionorgua** [comment]
I've found that `restic mount` is currently much faster than restore for me (at least when I need to restore just one particular directory that is less than ~10% of snapshot)

**Comment by fd0** [comment]
This has been resolved, the restorer is concurrent now. I'm closing this issue.
