### ISSUE TITLE
restic access repository without password

### ISSUE THREAD

**Issue by scialo** [restic/restic#1382]
## Output of `restic version`
restic 0.7.3
compiled with go1.9 on linux/amd64

## How did you run restic exactly?
restic -r b2:bucket:path snapshots

## What backend/server/service did you use?
b2

## Expected behavior
i have init b2 on host "A" but when i connect from host "B" and i run snapshots command restic don't ask me password.

**Comment by fd0** [comment]
Unfortunately you haven't included any output or error messages printed by restic and also not how you configure the B2 access, so I can only guess that on host "B" you've set the environment variable `RESTIC_PASSWORD` or `RESTIC_PASSWORD_FILE`. When that's the case, restic won't ask for the password. Try `unset RESTIC_PASSWORD; unset RESTIC_PASSWORD_FILE` on host "B" and try again.

I'm going to close this issue for now, please feel free to add further comments.

**Comment by scialo** [comment]
thanks,
on host "B" not set environment variable and no file password.
i will try before unset

**Comment by fd0** [comment]
Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it.

And please take the time to describe on how to reproduce this problem, ideally by filling out the [issue template](https://raw.githubusercontent.com/restic/restic/master/.github/ISSUE_TEMPLATE.md).

How do you configure B2 access for restic on each host? Please paste the commands and variables you use (after replacing sensitive values).
