### ISSUE TITLE
small cleanup, "lint" issues

### ISSUE THREAD

**Issue by armhold** [restic/restic#1385]
I'd like to contribute a few minor code cleanups. Mostly cosmetic, but with the goal of shining light on potential bugs, ignored errors, etc. Sample commit [here](https://github.com/armhold/restic/commit/bcdebfb84e249738d6573fd678f8ff480f09e610).

If this kind of thing is useful, I propose to discuss & track such changes here. Thanks!

**Comment by fd0** [comment]
Please do so, thanks!

**Comment by armhold** [comment]
How do you feel about this ignored error from f.Close() [in a defer](https://github.com/restic/restic/blob/master/internal/restic/node.go#L256)? 

My feeling is that since there's a write, errors from that close are significant, and should probably be returned to the caller. (Feel free to talk me out of that... am I wrong?)

I know the resulting error handling in this situation is kind of ugly. We could:

1) Change the func signature to have a named error, and have the defer check if that named err is nil, and if so, return the result of the close.

2) Remove the defer, put `f.Close()` in front of every return statement in the for loop.

3) Remove the defer, refactor that for loop into its own func (maybe even inline anonymous), and move the `f.Close()` after the error check from the call to *that* func.

**Comment by fd0** [comment]
Oh, good catch, I feel the ignored error here is bug! :)

I'd go for option 3, with a named function, which should improve readability.

**Comment by armhold** [comment]
OK this one might be significant for B2 users. [defaultListMaxItems](https://github.com/restic/restic/blob/master/internal/backend/b2/b2.go#L28) is currently unused in the codebase. Shouldn't this be used like so?

```
	be := &b2Backend{
		client: client,
		bucket: bucket,
		cfg:    cfg,
		Layout: &backend.DefaultLayout{
			Join: path.Join,
			Path: cfg.Prefix,
		},
		listMaxItems: defaultListMaxItems,  // added this line
		sem: sem,
	}
```

Otherwise it defaults to zero, which has the effect of using the [B2 default of 100](https://www.backblaze.com/b2/docs/b2_list_file_names.html) for listing files, rather than the "restic" default of 1000.

If it really is intentional to default to 0/100 (maybe it was perf-tested to work well?) then I would make that explicit in the const, and pass in the setting as above.

**Comment by armhold** [comment]
Is there a good reason for the receivers on [Node](https://github.com/restic/restic/blob/master/internal/restic/node.go) to not all be pointer receivers? 

I haven't looked deeply at all of the usages of these funcs, so there may be a perfectly good reason to have a mix of value & pointer receivers here. But my initial impression is that this might be an oversight.

The [Go guidelines](https://golang.org/doc/faq#methods_on_values_or_pointers) recommend "If some of the methods of the type must have pointer receivers, the rest should too, so the method set is consistent regardless of how the type is used."

I did some quick experimentation, and the structs seem small (< 300 bytes), but I'm not sure how many might be kept in RAM at the same time. Even if there are not many kept simultaneously, I imagine the constant copying creates a lot of GC turnover.

**Comment by fd0** [comment]
Both are very good points, would you mind just creating PRs for each of them? It also makes discussion easier :)

**Comment by armhold** [comment]
Sorry, didn't realize that a PR was a better place for discussion (despite years on Github I'm still a bit of a PR newb).

The above PR contains the more-or-less cosmetic changes. Will add the "close error not returned" in `createFileAt` to that PR as well, as it seems related. And I'll create separate PRs for the other items discussed above.

Does it matter how I stage my commits? I.e., can they depend on the previous commits/PRs, or do you want them from a fresh branch, not dependent on the prev code? (There is some overlap in the changed files.)

**Comment by fd0** [comment]
Ideally, each PR contains a set of commits that's independent of all other PRs, so it's easier to review.

**Comment by armhold** [comment]
Coming back to this cleanup after a break, I find that "go vet" is reporting a few issues:

```
go vet ./...
# github.com/restic/restic/internal/migrations
internal/migrations/s3_layout.go:71: unreachable code
# github.com/restic/restic/internal/backend/test
internal/backend/test/tests.go:421: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak
# github.com/restic/restic/internal/backend/b2
internal/backend/b2/b2.go:324: unreachable code
# github.com/restic/restic/internal/archiver
internal/archiver/tree.go:235: unreachable code
internal/archiver/archiver_test.go:140: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:221: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:361: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:394: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:474: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:755: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:845: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:1005: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:1294: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:1458: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:1562: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:1735: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/archiver_test.go:1870: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/scanner_test.go:99: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/scanner_test.go:240: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
internal/archiver/scanner_test.go:310: github.com/restic/restic/internal/fs.Track composite literal uses unkeyed fields
# github.com/restic/restic/internal/index
internal/index/index_test.go:254: the cancel function is not used on all paths (possible context leak)
internal/index/index_test.go:268: this return statement may be reached without using the cancel var defined on line 254
```

**Comment by rawtaz** [comment]
Closing this as there's been a lot of PRs merged (no outstanding ones referencing this issue from what I can tell) and it's been stale for a while now. Thanks @armhold!
