### ISSUE TITLE
Fuse mount not working on macOS High Sierra

### ISSUE THREAD

**Issue by wojas** [restic/restic#1388]
## Output of `restic version`

```
restic 0.7.3 (v0.7.3-198-g5b96885c)
compiled with go1.8.3 on darwin/amd64
```

Running on: macOS 10.13 (High Sierra) with an APFS filesystem.

## How did you run restic exactly?

I tried all of these:

```
restic -r rest:http://test:test@localhost:8333/test -p tmp/passwd mount ~/tmp/mnt
restic -r tmp/test -p tmp/passwd mount ~/tmp/mnt
sudo restic -r tmp/test -p tmp/passwd mount ~/tmp/mnt
```

## What backend/server/service did you use?

I tried with both the local backend and the rest-server.

## Expected behavior

Working mount.

## Actual behavior

```
password is correct
exit status 6
unable to umount (maybe already umounted?): unmount /Users/wojas/tmp/mnt: invalid argument
```

The `~/tmp/mnt` directory exists and has no filesystem mounted on it.

## Steps to reproduce the behavior

Try to mount any repo under macOS High Sierra.

The corresponding tests also fail:
```
could not read signature from exclusion tagfile "/var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-717445343/CACHEDIR.TAG": unexpected EOF
integration_fuse_test.go:59: unexpected error: exit status 6

--- FAIL: TestMount (4.32s)
	testing.go:30: using low-security KDF parameters for test
	testing.go:30: using low-security KDF parameters for test
	lock.go:77: setting lock timeout to 0s
	integration_test.go:50: repository initialized at /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-020374147/repo
	integration_fuse_test.go:86: checking for 0 snapshots: []
	integration_fuse_test.go:54: subdir "snapshots" of dir /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-020374147/mount never appeared
	integration_fuse_test.go:93: virtual directory "snapshots" doesn't exist
	integration_fuse_test.go:73: unable to umount dir /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-020374147/mount, last error was: unmount /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-020374147/mount: invalid argument
integration_fuse_test.go:59: unexpected error: exit status 6

--- FAIL: TestMountSameTimestamps (4.27s)
	testing.go:30: using low-security KDF parameters for test
	integration_fuse_test.go:86: checking for 3 snapshots: [28030368 75ad6cdc 5fd0d8b2]
	integration_fuse_test.go:54: subdir "snapshots" of dir /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-229170182/mount never appeared
	integration_fuse_test.go:93: virtual directory "snapshots" doesn't exist
	integration_fuse_test.go:73: unable to umount dir /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-229170182/mount, last error was: unmount /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-229170182/mount: invalid argument
error for testdata/0/0/9/37: Lstat: lstat /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-248856444/testdata/0/0/9/37: no such file or directory
error walking dir testdata/0/0/9/37: Lstat: lstat /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-217322721/testdata/0/0/9/37: no such file or directory
error walking dir 0/9: Open: open /var/folders/cr/nj9c04_x215dl0wm3z3cdyp00000gs/T/restic-test-608697015/testdata/0/0/9: no such file or directory
```

Can anyone else reproduce this?

## Do you have any idea what may have caused this?

Not sure. [The OSXFuse release notes](https://github.com/osxfuse/osxfuse/releases) show that they added support for macOS 10.13 beta 3 in 3.6.2, but restic uses a different implementation (https://github.com/bazil/fuse), which has not been updated for a while. I don't see any related issue for bazil/fuse.

## Do you have an idea how to solve the issue?

If other can confirm this also happens on their machines, we might need to dig through the OSXFuse changes and see if they can be applied to bazil/fuse.

**Comment by fd0** [comment]
Thanks for the report, it'd be  good to know if that happens to somebody else.

Fuse is bit confusing:
 * There's the fuse protocol, originally implemented on Linux, that's also what OSXFuse implements (the "server" so to speak)
 * And then there's the fuse clients, that's usually a C library (the "client"), and there are also native Go implementations. bazi/fuse is one of them.

restic sets up the connection to the kernel by calling `fusermount`, it looks like that has failed for you.

**Comment by wojas** [comment]
^ I referenced the wrong issue in the commit above. I pushed a new one, but the link to the old one remains.

**Comment by jkahrs** [comment]
Hi, it seems there is something more to this.
When I'm trying to reproduce the issue the mount works as intended.
This is on MacOS 10.13 with APFS and restic 0.7.3

**Comment by wojas** [comment]
After upgrading to the latest [OSXFuse](https://osxfuse.github.io/), I can confirm it works! Closing this issue.
