### ISSUE TITLE
Restic Backup fails during backup with exit code 137

### ISSUE THREAD

**Issue by virtualmarc** [restic/restic#1396]
## Output of `restic version`

restic 0.7.3
compiled with go1.9 on linux/amd64

## How did you run restic exactly?

```
export B2_ACCOUNT_ID="<B2 Account ID>"
export B2_ACCOUNT_KEY="<B2 Account Key>"
export RESTIC_PASSWORD="<Password>"
/backup/restic -r b2:<B2BucketName>:<Directory> backup / --exclude-file=/backup/exclude.conf
```

## What backend/server/service did you use?

Backblaze B2

## Expected behavior

Like on other servers I backed up the backup should finish after all files backed up and a snapshot should be available.

## Actual behavior

Backup Stops before finishing and exits with Exit Code 137.

> scan [/]
> scanned 17284 directories, 106674 files in 0:14
> Killed 86.85%  4.056 MiB/s  1.936 GiB / 2.229 GiB  120100 / 123958 items  0 errors  ETA 1:15

## Steps to reproduce the behavior

I tried to backup a DigitalOcean Droplet to Backblaze B2.

I initialized the Repo and than do a backup (which I've done successfully on other Servers not on DigitalOcean).

The Droplet is still running Ubuntu 15.04 (GNU/Linux 3.19.0-22-generic x86_64)

## Do you have any idea what may have caused this?

No. Maybe a file it can't backup, is not available anymore, etc. No error message is displayed.

## Do you have an idea how to solve the issue?

No. Debug Output would be helpful.

**Comment by fd0** [comment]
Most likely the kernel's Out-Of-Memory detector killed restic, you don't seem to have enough memory. Can you check `dmesg` and report back?

**Comment by virtualmarc** [comment]
Ahh yes this seems to be the problem:

> [27256989.445455] Out of memory: Kill process 31743 (restic) score 598 or sacrifice child
> [27256989.445534] Killed process 31743 (restic) total-vm:320512kB, anon-rss:308224kB, file-rss:0kB

This is a droplet with 512MB RAM, 168MB used. Backed up with Duplicity just fine.

**Comment by rawtaz** [comment]
@virtualmarc Try adding `GOGC=20` before your restic command, e.g. `$ GOGC=20 /backup/restic -r b2:<B2BucketName>:<Directory> backup / --exclude-file=/backup/exclude.conf`. Might help. And turn off that pesky OOM killer ;)

**Comment by fd0** [comment]
Hm, I'm aware that restic needs a lot of RAM (and we need to fix that). One of the reasons is that we use `scrypt()` to derive encryption keys from a password, which (intentionally) uses ~120MB RAM for that to make it harder to find the password by brute-force.

You could try to make the Go runtime garbage collector more aggressive with `GOGC=20 restic backup [...]`.

**Comment by virtualmarc** [comment]
Thanks. That worked. Took way longer to complete but was successfully.

> scan [/]
> scanned 17284 directories, 106674 files in 0:18
> [7:19:52] 100.00%  88.544 KiB/s  2.229 GiB / 2.229 GiB  123957 / 123958 items  0 errors  ETA 0:00
> duration: 7:19:52, 0.09MiB/s
> snapshot 20ac6f34 saved

**Comment by rawtaz** [comment]
You can try higher values well to see where the sweet spot between it working and it performing is. E.g. 30 or 40. Glad it works now though!
