### ISSUE TITLE
pack NNN: does not exist

### ISSUE THREAD

**Issue by ctberthiaume** [restic/restic#1404]
## Output of `restic version`
restic 0.7.3 (v0.7.3-201-ge44ac55f)
compiled with go1.9.1 on linux/amd64

## How did you run restic exactly?
```
restic -r s3:s3.amazonaws.com/mybucket/home init
restic -r s3:s3.amazonaws.com/mybucket/home backup home/
# ... s3 errors and panic
restic -r s3:s3.amazonaws.com/mybucket/home backup home/
restic -r s3:s3.amazonaws.com/mybucket/home check
# ... check fails with pack does not exist
restic -r s3:s3.amazonaws.com/mybucket/home rebuild-index
restic -r s3:s3.amazonaws.com/mybucket/home backup home/
restic -r s3:s3.amazonaws.com/mybucket/home forget --keep-last 1
restic -r s3:s3.amazonaws.com/mybucket/home prune
restic -r s3:s3.amazonaws.com/mybucket/home check
... check fails with pack does not exist
```

## What backend/server/service did you use?
S3

## Expected behavior
Repository check passes with no errors.

## Actual behavior
This repository was the same one I created and reported on in issue #1349. In that issue restic crashed during initial backup due to unhandled network errors when connecting to S3. I eventually managed to complete a backup by increasing s3 retries. Later I upgraded restic to track the latest changes in master, specifically the new backend retry functionality.

So far I can't get the repository to pass checks. I first tried a `rebuild-index` with no success. Next I tried to do a fresh backup, then forget all previous snapshots, and prune. Check still fails with the same error.

```
restic -r s3:s3.amazonaws.com/mybucket/home rebuild-index
password is correct
counting files in repo
[7:53:20] 100.00%  807191 / 807191 packs
finding old index files
saved new index as 985db3d0
remove 1 old index files
```

```
restic -r s3:s3.amazonaws.com/mybucket/home check
password is correct
Create exclusive lock for repository
Load indexes
Check all packs
pack b2be4de3174e711250db91cca6e858129ca80e6a49c8c8be5a121b91906ea013: does not exist
pack b425bd52c10c41a12d0c4bc6a69af3e859f31974b41c76f6bfdfe78d1f3b1e26: does not exist
pack 1aa051ed78dd70566fa733774cadf1254b61f8fe05ec88aa5f43f951fa9d64e9: does not exist
...
Interrupt received, cleaning up  # <- sent SIGINT here
```
```
restic -r s3:s3.amazonaws.com/mybucket/home backup /home
password is correct
using parent snapshot fd4e017b
scan [/home]
scanned 223899 directories, 2313070 files in 5:59
[16:24] 100.00%  5.125 GiB/s  4.925 TiB / 4.925 TiB  2536969 / 2536969 items  0 errors  ETA 0:00 
duration: 16:24, 5247.74MiB/s
snapshot 5a9f2714 saved
```

```
restic -r s3:s3.amazonaws.com/mybucket/home forget --keep-last 1
```

```
restic -r s3:s3.amazonaws.com/mybucket/home prune
password is correct
counting files in repo
building new index for repo
Load(<data/39a2501c50>, 4, 5452382) returned error, retrying after 637.13132ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/39/39a2501c502dedd496addb5ff85528c892bcbadb0a9beccbfe5d3aebbb1cc9ae: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35457->192.168.5.24:53: i/o timeout
Load(<data/39a1cfce2d>, 69, 5784262) returned error, retrying after 437.815109ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/39/39a1cfce2dc2026b98c4e03c6a38003569608834aa0dae61b699391457e37e3a: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35457->192.168.5.24:53: i/o timeout
Load(<data/39a2464b37>, 4, 4849621) returned error, retrying after 488.246823ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/39/39a2464b3761d9a480a03a848bb4a7458a607b0a9ea44af3750dd11ea8360819: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35457->192.168.5.24:53: i/o timeout
Load(<data/39a23c9931>, 4, 5663361) returned error, retrying after 628.480688ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/39/39a23c99311d1ad45e6670f408cd9be3a2a7296f6e180d94e73ccdd6c9c830bd: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35457->192.168.5.24:53: i/o timeout
Stat(<data/39a25d9d3c>) returned error, retrying after 317.583797ms: Stat: Head https://s3-us-west-2.amazonaws.com/mybucket/home/data/39/39a25d9d3c3d36537f441e8aabe8b4d22a678b936f2e396e02f83d5dffe2e3e1: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35457->192.168.5.24:53: i/o timeout
Load(<data/39a1d063b8>, 143, 4239316) returned error, retrying after 265.387844ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/39/39a1d063b84268f67a693fc107c58d78064dbbe6f1b10d364f77f506a40f4cc1: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35457->192.168.5.24:53: i/o timeout
Stat(<data/39a27ce44b>) returned error, retrying after 564.326979ms: Stat: Head https://s3-us-west-2.amazonaws.com/mybucket/home/data/39/39a27ce44bd04b4ba27e8288efeacdc6dc88a1d6605e53470b85d92a95492942: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35457->192.168.5.24:53: i/o timeout
Stat(<data/39a2782aca>) returned error, retrying after 537.602848ms: Stat: Head https://s3-us-west-2.amazonaws.com/mybucket/home/data/39/39a2782acac7118dba02f20606ad830416719d1700a7c3170cc614f952dc7594: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35457->192.168.5.24:53: i/o timeout
Load(<data/8a0374e868>, 4, 8791794) returned error, retrying after 660.016801ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/8a/8a0374e868573078fa744d3aaa2c84b68ce43e0b1b224cb4b21886a2e6931c93: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35257->192.168.5.24:53: i/o timeout
Stat(<data/8a03993363>) returned error, retrying after 307.920285ms: Stat: Head https://s3-us-west-2.amazonaws.com/mybucket/home/data/8a/8a039933632278c04b192a5345f902e12b740c5da65206ebd9319bdb1a5b2cf8: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35257->192.168.5.24:53: i/o timeout
Stat(<data/8a03b6c14a>) returned error, retrying after 543.086722ms: Stat: Head https://s3-us-west-2.amazonaws.com/mybucket/home/data/8a/8a03b6c14ace75f4e6589894e64229598956301e1da4450a5c3e7223a407bfb9: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35257->192.168.5.24:53: i/o timeout
Load(<data/8a033346ca>, 180, 4490575) returned error, retrying after 669.036606ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/8a/8a033346cac7819e5dc86d12e0a075e055e2400a10395a0a5994f4c9e9d28488: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35257->192.168.5.24:53: i/o timeout
Load(<data/8a031c0631>, 180, 7540803) returned error, retrying after 642.815071ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/8a/8a031c063117ca531618a2adcf6fd707ba95ca6f91b70bc98280d0e8209d5218: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35257->192.168.5.24:53: i/o timeout
Load(<data/8a036a1c0f>, 4, 4338603) returned error, retrying after 675.528059ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/8a/8a036a1c0fff2b79e38eeb66cd07f668523528386b12b7fb5893488e140eb9c1: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35257->192.168.5.24:53: i/o timeout
Load(<data/8a0369cb91>, 4, 5027150) returned error, retrying after 571.205033ms: Get https://s3-us-west-2.amazonaws.com/mybucket/home/data/8a/8a0369cb91e42e592b24590657d5634c3bec92a73fbbd1464d9962dfe038a326: dial tcp: lookup s3-us-west-2.amazonaws.com on 192.168.5.24:53: read udp 192.168.5.50:35257->192.168.5.24:53: i/o timeout
[10:16:35] 100.00%  809955 / 809955 packs
repository contains 809955 packs (4555127 blobs) with 4.056 TiB
processed 4555127 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 1 snapshots
[2:46] 100.00%  1 / 1 snapshots
found 4133510 of 4555127 data blobs still in use, removing 421617 blobs
will remove 0 invalid files
will delete 510 packs and rewrite 3393 packs, this frees 7.879 GiB
[56:22] 100.00%  3393 / 3393 packs rewritten
counting files in repo
[10:35:36] 100.00%  808342 / 808342 packs
finding old index files
saved new index as 6422fe96
remove 8 old index files
[2:31] 100.00%  3903 / 3903 packs deleted
done
```

```
restic -r s3:s3.amazonaws.com/mybucket/home check
password is correct
Create exclusive lock for repository
Load indexes
Check all packs
pack 58302352ee0498907f19d939fe22d10c082aa49be9f0c3815d1f86632cf564d5: does not exist
pack 07d6a80a1146e0040bec163d362ae304e1a4091ac3af1bdb21d8ef311dda9377: does not exist
pack 3538befaa153e9842c79e03eb20fa3d34b7f6904deaebb99d7f8b5bf26c33053: does not exist
...
Check snapshots, trees and blobs
Fatal: repository contains errors
```

## Do you have any idea what may have caused this?
No.

## Do you have an idea how to solve the issue?
No.

**Comment by fd0** [comment]
Hey, thanks for the report. I'd like to dig down what the problem here is. Can you please confirm (or correct me):

 * You've made a backup to s3 of about ~5TiB
 * `restic check` complains of missing pack files 
 * `restic rebuild-index` doesn't help
 * `restic prune` throws errors about UDP and port 53

Is that correct so far?

**Comment by ctberthiaume** [comment]
Yep that's all correct.

**Comment by fd0** [comment]
Hm. Anything else out of the ordinary? Any special configuration for the s3 credentials or so?

I'm a bit at loss what's going on here. The UDP errors point into the direction of too many connections during prune, you could verify that by running it again and periodically looking at `netstat -n`, but I thought we found all the problems with excessive connection usage.

Use a browser or something like `rclone` to list the `index/` subdir (there only should be one file in it), then run `rebuild-index`, then list it again. The should still be one file, now a different one. Does that work?

Afterwards, does `check` still complain?

**Comment by ctberthiaume** [comment]
I'll take a look and report back tomorrow. The rebuild process takes about 8 hours.

**Comment by ctberthiaume** [comment]
The index file in S3 is different after last night's `rebuild-index` and a `check` this morning passed without errors. One other note, I erased the local restic cache folder before doing the `rebuild-index`. I'm not sure if that affected anything or if I just needed to do the final `rebuild-index` after the `forget --keep-last 1` and `prune`. Anyway, thanks for your help. If nothing else this issue might be useful if someone else encounters a similar situation.

**Comment by fd0** [comment]
Okay, hm. I still like to find out what's wrong...

**Comment by snc** [comment]
I also had problems regarding DNS resolution (using REST server backend)... I simply added the repository domain to /etc/hosts as it was a static IP, of cause this won't really work with s3. Maybe caching the DNS response could help?

**Comment by ctberthiaume** [comment]
The error during `check` has reappeared after a new backup, but not all the time. A `check` from an EC2 instance passed ok. I'm going to run some tests this weekend to try to isolate the combination of hosts and possibly other variables that produce the error.

**Comment by fd0** [comment]
Great, the more we know about the error the better.

You can also try creating a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue for us to have a look at it. Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it.

**Comment by ctberthiaume** [comment]
After running a bunch of `backup`s and `check`s for the same NFS share from a different host I can't recreate the error. The only warning I get is `pack ... contained in several indexes: {... ...}` which I gather is not critical. I'm leaning towards faulty hardware on the original host, probably from the disk since the server has ECC RAM. Maybe the local cache of the index or `restic` temp files were getting corrupted.

In the case of a suspect client disk (not the disk holding data to be backed up) do you think a `check --read-data` would be sufficient to ensure integrity? I could do a test full restore as well. Or just recreate the repository from scratch.

**Comment by fd0** [comment]
You can run `rebuild-index` to create a new index which will correct the error, that's not a big deal.

A run of `restic check --read-data` will show you internal (=data structure) and external (=corrupted/modified file on disk) errors, that should be sufficient in this case. It will not show you if the suspect host saved modified/garbled data to the repo (e.g. a file with content `foo` is saved as `Xoo`, that you won't detect).

I'm proposing closing this issue for now. Thoughts?

**Comment by ctberthiaume** [comment]
Sounds good to me. Thanks for your help.
