### ISSUE TITLE
Exception during prune

### ISSUE THREAD

**Issue by stuertz** [restic/restic#1407]
## Output of `restic version`
restic 0.7.1
compiled with go1.8.3 on windows/amd64

## How did you run restic exactly?

> X:\restic
> λ x:\restic\restic -r x:\restic prune
> counting files in repo
> building new index for repo
> [4:11:22] 100.00%  107641 / 107641 packs
> repository contains 107641 packs (6187181 blobs) with 496.269 GiB bytes
> processed 6187181 blobs: 85 duplicate blobs, 6.100 MiB duplicate
> load all snapshots
> find data that is still in use for 27 snapshots
> [3:35:19] 100.00%  27 / 27 snapshots
> found 3547102 of 6187181 data blobs still in use, removing 2640079 blobs
> will remove 0 invalid files
> will delete 18105 packs and rewrite 13385 packs, this frees 109.168 GiB
> Exception 0xc0000006 0x8 0x8887b1 0x8887b1tten
> PC=0x8887b1
> 
> main.glob..func14(0xc06560, 0xc042148f00, 0x0, 0x2, 0x0, 0x0)

## What backend/server/service did you use?
x: is a windows samba mount 

## Expected behavior
No crash

## Actual behavior
The call crashes unexpectedly

## Steps to reproduce the behavior
calling prune on my large repository

## Do you have any idea what may have caused this?
no

## Do you have an idea how to solve the issue?
no

**Comment by fd0** [comment]
Thanks for reporting this, I have no idea what's going on. Maybe the SMB mount went away? I noticed that the restic binary is also on `x:`, can you retry with a local binary?

**Comment by stuertz** [comment]
Maybe that was one cause. After updating and using a local binary it worked.
Thanks for your hints.

**Comment by fd0** [comment]
Thanks for the feedback. Let us know when this happens again.
