### ISSUE TITLE
snapshot of hidden directory is empty :-(

### ISSUE THREAD

**Issue by sgeisbacher** [restic/restic#1408]
## Output of `restic version`
restic 0.5.0 (v0.5.0-39-g67a2ac2)
compiled with go1.7.4 on darwin/amd64

## How did you run restic exactly?

`AWS_ACCESS_KEY_ID=${RESTIC_AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${RESTIC_AWS_SECRET_ACCESS_KEY} restic -r s3:https://s3.amazonaws.com/****-bkp -p ~/.restic-passwd backup ~/.password-store` 

## What backend/server/service did you use?
AWS-S3

## Expected behavior
that all my files in ./password-store are backed up. non `.`-dirs work fine for this same repository

## Actual behavior
if i mount my repository locally all other snapshots (from other directories eg. ~/business) are fine, but the `.password-store`-snapshots are empty. 

## Steps to reproduce the behavior
backup a `.`-directory and check the snapshot afterwords

## Do you have any idea what may have caused this?
hidden directory

## Do you have an idea how to solve the issue?
no

**Comment by fd0** [comment]
Hu, that is odd. Can you retry with the latest version of restic? 0.5.0 is really old.

To be honest, I don't have any idea what's going on here. Restic does not exclude directories which start with a dot.

Is maybe `~/.password-store` a symlink?

**Comment by fd0** [comment]
Since there wasn't any feedback I'm going to close this issue for now, please feel free to add further comments. Thanks!

**Comment by rawtaz** [comment]
Oh I wish GitHub didn't send a separate e-mail for the close and one for your comment, but instead sent ONE e-mail with both close information and the comment..
