### ISSUE TITLE
Mention backup storage size, comparison fair?

### ISSUE THREAD

**Issue by Siilwyn** [restic/restic#1418]
:wave: Hi there, restic looks good but after reading [this backup storage size comparison](https://github.com/gilbertchen/benchmarking#backing-up-the-linux-code-base) it looks very space insufficient. Wondering if this comparison is fair, it seems to conflict the 'efficient' point in the documentation.

**Comment by fd0** [comment]
We've covered this topic [in the forum](https://forum.restic.net/t/restic-dedup-strategy/129) already, and you're right: We haven't reached our self proclaimed goal here yet. The main reason for that seems to be the missing compression (see #21). I'm going to close this issue for now, please feel free to add further comments (maybe in the forum, that's the more appropriate place)!
