### ISSUE TITLE
TLS handshake timeout when using S3

### ISSUE THREAD

**Issue by aut0** [restic/restic#1421]
## Output of `restic version`
C:\restic>restic.exe version
restic 0.7.3
compiled with go1.9.2 on windows/amd64

## How did you run restic exactly?
C:\restic\restic.exe backup --force D:\SomeFolder D:\SomeOtherFolder

## What backend/server/service did you use?
set RESTIC_PASSWORD=password
set RESTIC_REPOSITORY=s3:https://s3.amazonaws.com/bucket
set AWS_ACCESS_KEY_ID=KEY-ID
set AWS_SECRET_ACCESS_KEY=keykeykey

C:\restic>C:\restic\restic.exe backup --force D:\SomeFolder D:\SomeOtherFolder
scan [D:\SomeFolder D:\SomeOtherFolder]
scanned 6560 directories, 215853 files in 0:28
[1:11:25] 70.15%  9.506 MiB/s  39.778 GiB / 56.707 GiB  160259 / ... ETA 30:23
error while saving data to the repo: Post https://foo.s3-eu-central-1.amazon
aws.com/bar/foo[...] : net/http: TLS
 handshake timeout
client.PutObject
github.com/restic/restic/internal/backend/s3.(*Backend).Save
        src/github.com/restic/restic/internal/backend/s3/s3.go:228
github.com/restic/restic/internal/repository.(*Repository).savePacker
        src/github.com/restic/restic/internal/repository/packer_manager.go:122
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:203
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:529
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:104
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:161
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
panic: client.PutObject: Post https://foo.s3-eu-central-1.amazonaws.com/bar/foo: net/http: TLS handshake t
imeout

## Expected behavior

Restic should take the snapshot

## Actual behavior
Takeing the snapshot fails with error message above

**Comment by fd0** [comment]
Thanks for the report. I believe this is already resolved in the master branch, you can find compiled binaries here: https://beta.restic.net/?sort=time&order=desc

I'm going to close this issue for now. If it persists with the master branch, please leave a comment.  Thanks!

**Comment by ejel** [comment]
I ran into a similar issue with restic-0.8.3. Would you mind pointing out the commit that fixes the issue so maybe I could check if what I encounter is the same issue or a new one. Thanks!
