### ISSUE TITLE
Restic does not work with B2

### ISSUE THREAD

**Issue by CurtWarfield** [restic/restic#1425]
## Output of `restic version`
restic 0.7.3
compiled with go1.9 on linux/amd64

## How did you run restic exactly?

$ restic -r b2:bucketname:/ init

create backend at b2:bucketname:/ failed: b2.NewClient: b2_authorize_account: 401: Invalid authorization token

The key and account have been exported correctly.

## Expected behavior
It doesn't work at all.

**Comment by jtrott** [comment]
Test your keys with the following command:

curl https://api.backblazeb2.com/b2api/v1/b2_authorize_account -u "ACCOUNT_ID:APPLICATION_KEY"

I had the same problem and it turned out I had an incorrect application key and needed to get a fresh one.

**Comment by CurtWarfield** [comment]
The keys and account ID were just testing via the b2 api command and with a duplicity backup that uses the account ID and keys

**Comment by CurtWarfield** [comment]
Even though my account/keys were working for duplicity and for b2 cli, I wiped out my B2 bucket and created and new one along with a new key. Now it's working. Still doesn't make sense but this can be marked as closed.
