### ISSUE TITLE
USR1 does not report progress if --quiet is passed

### ISSUE THREAD

**Issue by pmkane** [restic/restic#1427]
Reasonable people could disagree about this, but I think that a USR1 signal should always trigger a progress report, even if restic has been passed the --quiet flag.  It's useful for debugging what's going on with a scripted backup, without relying on strace/lsof.

Currently, --quiet suppresses this output when USR1 is received.

Thoughts from fd0 or others?  Happy to submit a PR implementing this, but don't want to do so if it's a design decision.

**Comment by fd0** [comment]
Fine with me, go ahead with a PR. At the moment, the progress callback functions aren't installed when `--quiet` is passed.

**Comment by FiloSottile** [comment]
Judging from the docs, this was implemented.

> Setting the RESTIC_PROGRESS_FPS environment variable or sending a SIGUSR1 signal prints a status report even when –quiet was specified.

**Comment by rawtaz** [comment]
Looks like it, nice catch!
