### ISSUE TITLE
error loading tree: id <VARIOUS ID's> not found in any index

### ISSUE THREAD

**Issue by man-deli** [restic/restic#1430]
## Output of `restic version`
```
restic 0.7.3
compiled with go1.9 on windows/amd64
```

## How did you run restic exactly?

`.\restic -r b2:<B2_BUCKET_NAME>:school backup "D:\My Documents\School"`

With both environment variables set to their applicable values:
B2_ACCOUNT_ID
B2_ACCOUNT_KEY

The following output was seen:
```
using parent snapshot 27a98a72
scan [D:\My Documents\School]
scanned 240 directories, 2009 files in 0:00
error loading tree: id 8db501448cc184533bb7b6c1140ffed4d7d6081433198900358f8e60b8a19e91 not found in any index
error loading tree: id e7c6023375ad827abfbd21d006c06de669d88b3ee204c7642334ebd0e55f3440 not found in any index
error loading tree: id 570949418d8a7b590b332ac5d1a293159220e7e977836e9f23b118e47f9deb91 not found in any index
error loading tree: id 4ccee502233588f826acadf61541025701bfa983ef02843577f2118c5e9b20fa not found in any index
error loading tree: id 63d5a38a6c1732b8182722b47aae37791db147dd0751b196e982e56983a7bd26 not found in any index
error loading tree: id 0a79f1e41f954ca48b305fcc902dd494b9bf1cb885d08f864279b600ee5d6456 not found in any index
error loading tree: id e62259c2549820f049c2ba428b72606f09e40563eb254ab9b5c41eb6f75f98d8 not found in any index
error loading tree: id 0cccda861703c498f9eeea3b3ed0b3c9c93d0081c160aedb1765b9ebe22d1a6d not found in any index
error loading tree: id 2a8215dc64a3f79f56fb65cf11541b2dd8300b54c88450cb9c3922b27ef5dce6 not found in any index
error loading tree: id 120c25720d54613fedbb408f4e6debfd4602c61733b1887f24be734650486a85 not found in any index
error loading tree: id 799aceed453e4adf84b2178d8446b0b89e5b40c3ab99e14ab047dfab32049515 not found in any index
error loading tree: id 49c0a6a8788c7fb2dc6df291779b500f085945dd3927dd2b36b62d5aca207abd not found in any index
error loading tree: id 7d44af60627ed135789166c23d639758d2052dbb947347c8baecf9b328b77d61 not found in any index
error loading tree: id 09586222e71a58b6157c96e260690c9aa960e6acab2b454d122db155d6297b64 not found in any index
error loading tree: id 6e70a3b03701e032e2236c3ff28c5b95c984d7110aa3f1ba174f4695f34b5490 not found in any index
error loading tree: id 527d8681426a440b06fd6850cbb39dfc82f82871ecab8d5a406ded0ac2a6d464 not found in any index
error loading tree: id e7b9f2165cc1036a5f41db7ac4ff20d3eb27b2432522f926397b613dc9fd6940 not found in any index
error loading tree: id 030d0861cf2d3df800c30c11a44763941a58fc2a4dd276bb076a8469cd6f9dc5 not found in any index
error loading tree: id 3c5c7c1cdf24424e0484a32478252ce4807899124b74c02dc312ce6dd3ef2a29 not found in any index
error loading tree: id 7139fd85551f9d80ee395d4af62ce8c8e3abba522608bfde807638dcb4a631b1 not found in any index
[39:34] 100.00%  90.414 KiB/s  209.614 MiB / 209.614 MiB  2249 / 2249 items  0 errors  ETA 0:00
duration: 39:34, 0.09MiB/s
snapshot b227d925 saved
```

## What backend/server/service did you use?

Backblaze B2

## Expected behavior

Was not expecting any errors.

## Actual behavior

See sections above for output from command.

## Steps to reproduce the behavior

Execute the command above from Windows 10 PowerShell

## Do you have any idea what may have caused this?

No, these errors were seen when performing the second snapshot of this backup. There was no change to the source data between the first and second snapshots. I restored the first snapshot and diff'd against the original source data, and it looks good. I did notice that the B2 bucket is now 371 MB, whereas the data that was backed up is only 209 MB.

## Do you have an idea how to solve the issue?

No

**Comment by fd0** [comment]
Thanks for the report. Can you reproduce the issue (fresh repo, first backup works, second backup shows the errors)? Does it happen every time?

**Comment by man-deli** [comment]
Hello, unfortunately I was unable to reproduce this issue on B2 with a fresh repo and multiple backups to that fresh repo.

**Comment by rawtaz** [comment]
@man-deli Can you please provide the technical information like you did in your initial post? I suppose you're running with a newer restic and what not. FYI, the latest version is 0.8.3, try reproducing it with that for starters, please report back with technical info if the problem persists.

**Comment by fd0** [comment]
Thanks for the feedback, a bit more details would be nice (at least the restic version). I suspect you ran into https://github.com/restic/restic/pull/1589.

I'm closing this issue for now, please do add further comments if you have some :)

Thanks!
