### ISSUE TITLE
Better exclude handling

### ISSUE THREAD

**Issue by michaeldorner** [restic/restic#1438]
Currently, you exclude folders or files via `--exclude(-file)`. But if one backups 

    restic /data backup --exclude-file=data/exclude_file

the exclude file must have absolute paths to exclude top level folders and their sub-directories. In the example above, all paths have to start with `/data/...`

Wouldn't it be nice, to add `BACKUP` files to a directory, specifying which folders shall be excluded. Google uses a similar approach with their `OWNER` files within the repository, e.g. in [Chromium](https://chromium.googlesource.com/chromium/src/+/lkcr/docs/code_reviews.md#owners-files).

What do you think?

**Comment by fd0** [comment]
Thanks for the suggestion. While it would be nice it'll add a considerable amount of code and complexity.

**Comment by MichaelEischer** [comment]
Closing this as it's a duplicate of #1514.
