### ISSUE TITLE
restic and usage cpu

### ISSUE THREAD

**Issue by scialo** [restic/restic#1441]
when crontab running command -> nice -n 19 restic -r /repository backup /mydir i check usage of restic with command top and in % CPU restic use 185,0%.

**Comment by rawtaz** [comment]
1) What is the actual problem you are having/reporting?

2) Why did you not fill out the issue template that you're presented with when opening a new issue form? It's there for a very good reason, and would have given us more information and also answered question # 1 above.

**Comment by fd0** [comment]
I'm going to close this issue, you did not fill out the issue template and we don't have enough information.
