### ISSUE TITLE
Homebrew Restic now in Homebrew

### ISSUE THREAD

**Issue by abraithwaite** [restic/restic#1448]
Looks like github.com/restic/homebrew-restic was removed without any mention in the release notes.

Also, link to installation notes is broken from github pages: https://restic.github.io/#installation

http://restic.readthedocs.io/en/v0.7.3/installation.html

http://restic.readthedocs.io/en/latest/020_installation.html

Thanks for the great work!

Might also be worth keeping around the old repo with a deprecation notice when trying to install.  I'm not sure how to do this but I've seen other packages include instructions for upgrading to new version.  Then again, I tend to ignore these so maybe breaking it is the best option.

**Comment by fd0** [comment]
Uh, ah, you're right. I'm sorry, I'll restore the repo, and add a note to it. Do you maybe know if we can publish a Formula there which prints a warning?

**Comment by abraithwaite** [comment]
No worries!  I'm not sure what the standard process is for deprecating or moving taps is since I'm just a user.  This is what the error looks like:

```
09:08:48 $ brew update && brew upgrade
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/restic/homebrew-restic failed!
```

> Btw, the installation instructions for the latest docs are fine, there's just brew install restic mentioned.

Yep, that's how I found out it had merged into mainline.  The link to the installation is broken from pages now, due to the new `020_` prefix (presumably for sorting).

**Comment by fd0** [comment]
Indeed, it would've been good to mention that in the changelog. Can you try again? I've reinstated the repo, added a warning in the readme and archived it (so it is read-only).
