### ISSUE TITLE
Add option to lower amount of output from 'forget' command

### ISSUE THREAD

**Issue by naffit** [restic/restic#1449]
## Output of `restic version`
restic 0.7.3
compiled with go1.9 on windows/amd64

## How did you run restic exactly?
RESTIC_REPOSITORY=L:\restic\files
RESTIC_PASSWORD_FILE=<file>
restic_0.7.3.exe forget --prune --keep-last 112 --keep-daily 30 --keep-weekly 52 --keep-monthly 24 --keep-yearly 10

## What backend/server/service did you use to store the repository?
Local networkdrive (L:)

## Expected behavior
Less logging when running a 'forget --prune' command after each scheduled backup in a script.

## Actual behavior
A massive amount of snapshots listed.

## Steps to reproduce the behavior
Run lots of backups.. :)

## Do you have any idea what may have caused this?
Running a scheduled backup every 3rd hour followed by a 'forget --prune' using the following --keep-* options:

--keep-last 112 (which works out to keeping all backups taken every 3rd hour (=8 each day) for 14 days)
--keep-daily 30
--keep-weekly 52 
--keep-monthly 24 
--keep-yearly 10

This works out to a massive amount of snapshots beeing listed over and over and over again - especially if there are several paths within the snapshot - like so (here omitting the 62 snapshots inbetween the 2 listed):

```
snapshots for (host [redacted], paths [E:\<redacted1>, E:\<redacted2>, E:\<redacted3>, N:\<redacted4>, N:\<redacted5>, N:\<redacted6>, N:\<redacted7>, N:\<redacted8>, N:\<redacted9>, N:\<redacted10>]):

keep 64 snapshots:
ID        Date                 Host         Tags        Directory
----------------------------------------------------------------------
8dee10e5  2017-11-27 21:02:47  naff-backup          ┌── E:\<redacted1>
                                                    │   E:\<redacted2>
                                                    │   E:\<redacted3>
                                                    │   N:\<redacted4>
                                                    │   N:\<redacted5>
                                                    │   N:\<redacted6>
                                                    │   N:\<redacted7>
                                                    │   N:\<redacted8>
                                                    │   N:\<redacted9>
                                                    └── N:\<redacted10>
...
df3ffe20  2017-11-19 23:05:01  naff-backup          ┌── E:\<redacted1>
                                                    │   E:\<redacted2>
                                                    │   E:\<redacted3>
                                                    │   N:\<redacted4>
                                                    │   N:\<redacted5>
                                                    │   N:\<redacted6>
                                                    │   N:\<redacted7>
                                                    │   N:\<redacted8>
                                                    │   N:\<redacted9>
                                                    └── N:\<redacted10>
```

## Do you have an idea how to solve the issue?
Some option to lower the amount of logging without using --quiet to supress everything, but still log "enough" to keep a log of everything done when using restic in a scripted version with often run backups.

Perhaps by removing all paths (or collapses them to 1 line), but keeps the list of snapshot IDs, date and host
I've also noticed issue #1235 and perhaps this new issue could be weaved into that too..

**Comment by fd0** [comment]
Good point, thank for raising it!

**Comment by MichaelEischer** [comment]
@naffit Does the `--compact` option (available since restic 0.8.0) solve the issue for you, or do you have something more compact in mind?

**Comment by naffit** [comment]
I'll have a look as soon as possible - I've scripted everything and havn't had a look at my forget-log for quite some time

**Comment by naffit** [comment]
Seems to work like a charm (yeah, it's been a while since I ran a forget..)!
```
Running command 'restic forget --prune --keep-last 112 --keep-daily 30 --keep-weekly 52 --keep-monthly 24 --keep-yearly 10' 
Applying Policy: keep the last 112 snapshots, 30 daily, 52 weekly, 24 monthly, 10 yearly snapshots
snapshots for (host [naff-backup], paths [<redacted>):
keep 164 snapshots:
ID        Time                 Host         Tags
--------------------------------------------------
c922f693  2018-05-30 22:25:40  naff-backup
bfbe2278  2018-06-29 23:33:39  naff-backup
...
ae768b60  2020-04-03 18:16:35  naff-backup
93485dae  2020-04-04 19:37:40  naff-backup
--------------------------------------------------
164 snapshots

remove 266 snapshots:
ID        Time                 Host         Tags
--------------------------------------------------
a21945e5  2018-05-27 22:49:03  naff-backup
18d195b7  2018-05-28 22:15:57  naff-backup
...
cebec67b  2019-12-10 17:19:54  naff-backup
2b6b26fd  2019-12-10 21:59:24  naff-backup
--------------------------------------------------
266 snapshots
```
Much much better - and more or less as I suggested it - please go ahead and close the issue.. :)

**Comment by MichaelEischer** [comment]
^^ . Thanks for the quick feedback!
