### ISSUE TITLE
Memory consumption is high

### ISSUE THREAD

**Issue by linsomniac** [restic/restic#1453]
## Output of `restic version`

restic 0.7.3
compiled with go1.9 on linux/amd64

## How did you run restic exactly?

restic backup -o b2.connections=5 --one-file-system --exclude /tmp --exclude /var/tmp --exclude-file /etc/restic/excludes / /data /var /home /tmp

## What backend/server/service did you use to store the repository?

Backblaze B2

## Expected behavior

"Reasonable" memory consumption.

## Actual behavior

I have a 500GB backup repository on Backblaze B2, which is the backups of ~100 machines.  Backups of machines are using a lot of memory, for example one system which has 85GB of data is using 6.4GB of memory and counting.  It spends around 40 minutes building the file list before it starts the backup. But that is not the only memory consumer.  During the backup job, memory continues to go up.  Running "vmstat 60" I see over 5 minutes that the swap usage has grown from 200MB to 250MB just while I have been writing this message.

## Do you have any idea what may have caused this?

Not sure.  Perhaps it is related to the 500GB backup repository?  Perhaps it is related to the number of files to back up?

## Do you have an idea how to solve the issue?

Perhaps memory isn't being freed?  Perhaps references to block hashes are being kept in memory and need to be LRU freed?

**Comment by fd0** [comment]
Thanks for the report. We're aware that restic uses way too much memory right now. This is tracked in #979, so I'm going to close this issue for now. Feel free to add further comments. Thanks!
