### ISSUE TITLE
Retain original directory structure

### ISSUE THREAD

**Issue by swalladge** [restic/restic#1456]
Currently the behaviour seems to be the following - with:

```
restic backup /path/to/some/file/NAME /another/path/to/different/NAME
```

warns that there was a filename collision and will end up with files `NAME` and `NAME-1` in the snapshot.
I'd like to be able to use a flag that tells it to keep the directory structure so that the snapshot will contain `path/to/some/file/NAME` and `another/path/to/different/NAME`.

My use case is wanting to up backup a selection of important files (documents, keys, etc.) spread over the filesystem of my personal computer. I realize I _could_ probably use something like `restic backup --exclude-file some_huge_list_of_files.txt /`, but that is going to be difficult to maintain.
If there is already a simple way to set this up, I'll be interested to know,
but I couldn't find anything in the docs.

Thanks.

**Comment by pvgoran** [comment]
This problem (and development of a solution) is already tracked in #549.

**Comment by swalladge** [comment]
Thanks! Closing as duplicate. :)
