### ISSUE TITLE
Allow repository path to be passed in from a file, instead of passed explicitly via CLI or an environment variable

### ISSUE THREAD

**Issue by pmkane** [restic/restic#1458]
Currently, the only ways to pass a repository path to restic is explicitly with -r or via the RESTIC_REPOSITORY environment variable.

For users using the rest-server, however, this presents security problems similar to those discussed in https://github.com/restic/restic/issues/278.

By using ps or ps e, non-trusted users on a machine being backed up could discover the basic authentication credentials used to access the rest-server.  At best, this would allow them to delete backups.  At worst, if the admin unwisely chooses the same password for rest-server as for their backups, they could access backup data.

I suggest offering a command-line option, similar to -p, that allows a repository path to be passed in from a file.

Happy to submit a PR if this approach sounds desirable.

**Comment by rawtaz** [comment]
I think it's not a bad idea, it wouldn't pollute the options very much. The repository URL and the password are two of the most fundamental things needed for restic to run, and since there's a `--password-file` it makes sense that there's a `--repository-file` as well, regardless of use case. It would seem "complete" in a way :)

**Comment by fd0** [comment]
Hm, to be honest I'd prefer implementing a configuration file, so everything gets a bit less messy.

**Comment by pmkane** [comment]
A configuration file would be awesome (especially since I just opened a separate issue about adding another option), but since this is a security issue and mirrors https://github.com/restic/restic/issues/278, I'd like to submit a PR to add support for this as an option.  When a config file is available, I'd be happy to see the CLI option either deprecated or removed.

**Comment by fd0** [comment]
Go ahead then :)
