### ISSUE TITLE
Document workflow for contributing

### ISSUE THREAD

**Issue by fw42** [restic/restic#146]
I think if we want to encourage more people to contribute to this repo, it would be helpful that all contributors follow the same workflow. In particular, it would be nice to discourage everyone from pushing straight to master (I guess right now only @fd0 and @scoddy have that permission anyway). Also I think force-pushing master should be an exceptional thing since it can mess up people's forks, which is annoying.

I'm not saying @fd0 should necessarily wait for others to review his code, but even just creating pull requests (that will generate notifications for the people who watch this repository) would be useful (even if merged immediately after creation). Also it would encourage micro-committing and separating concerns (only change one thing at a time as one small unit).

Thoughts?

**Comment by fd0** [comment]
This is a good idea, I have to check how this works. In addition, the workflow with Go on and multi-package git repository hosted at Github is slightly more complex for contributors. This should be documented and enforced, at least after the alpha release.

**Comment by fd0** [comment]
The file `CONTRIBUTING.md` describes the process, I think this is sufficient for now.
