### ISSUE TITLE
Should ignore UNIX domain sockets

### ISSUE THREAD

**Issue by rfc1036** [restic/restic#1463]
## Output of `restic version`
restic 0.8.0
compiled with go1.9.2 on linux/amd64

## How did you run restic exactly?
```
restic init -r /tmp/repository/
restic backup -r /tmp/repository/ ~/.ssh/
restic mount -r /tmp/repository/ /tmp/restore/
restic restore -r /tmp/repository/ --target /tmp/restore/ latest
```

## Expected behavior

```~/.ssh/``` contains some UNIX domain sockets. They should not be backed up since the listening programs will just create them again when needed.

## Actual behavior

The sockets are not restored by ```restic restore``` but they are in the repository:

```
md@bongo:~$ restic ls -r /tmp/repository/ latest
enter password for repository: 
password is correct
snapshot dd92f0a1 of [/home/md/.ssh] at 2017-12-03 12:04:42.505715915 +0100 CET):
/.ssh
/.ssh/.control_attila.bofh.it_22_md
/.ssh/.control_ra.example.net_22_md
/.ssh/authorized_keys
```

And ```restic mount``` is a bit confused:

```
md@bongo:~$ ls -lA /tmp/restore/snapshots/latest/.ssh/
/bin/ls: cannot access '/tmp/restore/snapshots/latest/.ssh/.control_ra.example.net_22_md': No such file or directory
/bin/ls: cannot access '/tmp/restore/snapshots/latest/.ssh/.control_attila.bofh.it_22_md': No such file or directory
total 5547
?????????? ? ?  ?        ?            ? .control_attila.bofh.it_22_md
?????????? ? ?  ?        ?            ? .control_ra.example.net_22_md
-rw-r--r-- 1 md md     508 May  1  2014 authorized_keys
[...]
```

**Comment by fd0** [comment]
Good point, thanks!

**Comment by fd0** [comment]
I'll fix the display in the fuse mount, I'm not sure what to do with sockets. I think it may sometimes be nice to view what sockets were present in a directory, and what the ownership and access modes were. What's your opinion on that?

**Comment by rfc1036** [comment]
There is no point at all in backing up UNIX domain sockets since they cannot be restored, or else bind(3) would fail because the file already exists: in the best case they would just be deleted again when the program creating them is started.
In my experience people do not manually change the permission of a UNIX domain socket after it has been created, so I see no value in this even as "documentation". Since UNIX domain sockets are not created "manually" then all the information needed to create them again is in the programs which create them.

**Comment by fd0** [comment]
Thanks for the explanation.

**Comment by fd0** [comment]
#1465 correctly handles all cases where sockets (and other types) are displayed/used. Ignoring them from being archived requires more work.

**Comment by dlitz** [comment]
fwiw, I'm glad that restic errs on the side of storing everything even if the value of the information isn't immediately apparent.

It's useful when comparing directory listings to verify a backup, and can help to answer questions about the state of a system after a catastrophic failure.
