### ISSUE TITLE
Cache directory and the root user

### ISSUE THREAD

**Issue by dsommers** [restic/restic#1473]
## Output of `restic version`
restic 0.8.0 (v0.8.0-0-gc02923fb)
compiled with go1.8.3 on linux/amd64

## Issue
When running restic as the root user to take a system backup, the default cache directory is /root/.cache/restic. I propose to use /var/cache/restic as the cache directory when restic is run as root.

## Reason
/root is often part of the root file system.  This file system might not be as big, particularly on servers where more advanced partitioning schemes are used.  Those places /var is more commonly more spacious and some might even have split /var over multiple partitions as well to avoid system havoc if some lesser critical partitions goes empty; like /var/cache.  Filling up / can easily cause issues - and with restic repositories with thousands of files with lots of changes, the cache directory can easily grow quite a bit.

**Comment by zcalusic** [comment]
Thinking a bit about your proposition, it makes a lot of sense. /var/cache is standard FHS location for various system caches. Thanks for opening this issue.

Not to mention that I've already symlinked /root/.cache/restic to another bigger partition with more space on ALL of my restic client hosts. ;)

But, even if it's easy to symlink, sane defaults are always welcome. Probably restic could also emit a line saying Using cache: /var/cache/restic (or /home/user/.cache/restic for ordinary users), so there's no confusion. And user always knows where the cache ended.

**Comment by zcalusic** [comment]
As always, migration is hard, @fd0, you could probably put in code that works for both locations, but for newly created repos, /var/cache would be chosen. So, restic client would first check the current /root/.cache/restic, and use that if found. Maybe another info line (not warning 😄) that would suggest user to move cache to the new default /var/cache/restic.

**Comment by fd0** [comment]
To be honest, I'd like to leave it as is for now. Adding this requires more code and even more special cases, even checking two different cache dirs or a migration. If needed, people can easily set `XDG_CACHE_HOME` to `/var/cache` and be done with it.

**Comment by dsommers** [comment]
That approach is fine when only considering non-admin users running backups.  But once starting to use this for system wide backups, where the backup tools needs to be run as root to have access to all files being backed up, this will be a growing issue.

**Comment by dstosberg** [comment]
Just a note on the side: If you are on Linux, you don't have to run `restic` as root to make a full system backup. Yes, restic needs to be able to read all files, but it does not need any of the other privileges that root has. On Linux you can assign that specific single capability to the restic binary and run it as an ordinary user:

```bash
# create restic user
root@a3e580b6369d:/# useradd -m restic

# install restic
root@a3e580b6369d:/# mkdir ~restic/bin
root@a3e580b6369d:/# curl -L https://github.com/restic/restic/releases/download/v0.8.0/restic_0.8.0_linux_amd64.bz2 | bunzip2 > ~restic/bin/restic

# make restic binary executable by root and restic user only
root@a3e580b6369d:/# chown root:restic ~restic/bin/restic
root@a3e580b6369d:/# chmod 750 ~restic/bin/restic

# assign capability to read all files to restic binary
root@a3e580b6369d:/# setcap cap_dac_read_search=+ep ~restic/bin/restic
```

Starting at this point, the restic user can backup the whole system without having to run anything as root.

**Comment by jojomi** [comment]
@dstosberg @fd0 Might be interesting to document this for everyone? :-)

**Comment by fd0** [comment]
Great idea, anyone up for a PR? :)

**Comment by prosoitos** [comment]
mmm... @dstosberg I must be doing something wrong as I am still getting a bunch of "permission denied".

I created a user "restic" and gave it permission as you suggest. I made sure to run restic from that user and to run `/home/restic/bin/restic` rather than simply `restic` to make sure I am not running the restic I have installed in the root bin folder. I wrote a new rclone config file and a new exclusion file for the restic user. It all works, except that I am getting all these "permission denied".

What am I doing wrong??

**Comment by fd0** [comment]
@prosoitos I think this issue is not the right place for debugging such issue, would you mind heading over to [the forum](https://forum.restic.net) and posting there? We're trying to use the GitHub issue tracker for actionable things like bugs and feature requests. Thanks!

I'm also closing this issue for now as a decision has been made. Thanks all!

**Comment by prosoitos** [comment]
Thank you for pointing me to the forum. I had not realized that this resource existed.
