### ISSUE TITLE
restic 0.8.0 on windows - s3 invalid backend

### ISSUE THREAD

**Issue by ronopitz** [restic/restic#1485]
## Output of `restic version`

restic 0.8.0 - (binary on Windows 10)

## How did you run restic exactly?

set AWS_ACCESS_KEY_ID="***"
set AWS_SECRET_ACCESS_KEY="***"
set RESTIC_REPOSITORY="s3:http://10.100.10.140:9001/backup-laptop"
set RESTIC_PASSWORD="***"
c:\Programme\restic\restic init
create backend at "s3:http://10.100.10.140:9001/backup-laptop" failed: invalid backend

## What backend/server/service did you use to store the repository?

minio on raspberry pi (current version)

## Expected behavior

Get more details about the error. - Is s3 not supported or a problem with the url or a problem with the backend.

## Actual behavior

An access to the minio browser from Windows is possible. No network issues.

This is not a problem with the backend/service.
It runs with the same credentials/params on mac (restic 0.8.0 darwin bin).
An backup on mac is possible.

The minos

## Steps to reproduce the behavior

See above.

## Note

I find no indication that s3 is not supported on Windows.
If so, please expand the documentation.

**Comment by fd0** [comment]
I'm guessing that the double quotes (`"`) work different than on Mac/Linux, because they seem to be part of the value. Can you try again without them?

```
set AWS_ACCESS_KEY_ID=***
set AWS_SECRET_ACCESS_KEY=***
set RESTIC_REPOSITORY=s3:http://10.100.10.140:9001/backup-laptop
set RESTIC_PASSWORD=***
c:\Programme\restic\restic init
```

**Comment by ronopitz** [comment]
Thanks for the hint. It works perfect.
Windows is not my preferred os.

**Comment by fd0** [comment]
> Windows is not my preferred os.

I can relate to that very well ;)
