### ISSUE TITLE
" Invalid authorization token" trying to create repo on B2

### ISSUE THREAD

**Issue by mikeburr** [restic/restic#1490]
I'm having problems setting up a B2 repository for restic.

## Output of `restic version`
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

$ restic version    # not current, but it's what synaptic found
restic 0.7.1
compiled with go1.8.1 on linux/amd64

## How did you run restic exactly?
$ set | grep B2
B2_ACCOUNT=abc
B2_ACCOUNT_KEY=def123

$ restic -r b2:foobar:test init
create backend at b2:foobar:test failed: b2.NewClient: b2_authorize_account: 401: Invalid authorization token

## What backend/server/service did you use to store the repository?
B2

## Expected behavior
repository is created

## Actual behavior
repository not created

## Steps to reproduce the behavior
Run the command above.

## Do you have any idea what may have caused this?
No clue what is causing this.  This is my first time using restic and I'm hoping it's just me doing something stupid. I'm using the same B2 credentials in a different app on my NAS with no problems, so I don't *think* there's anything wrong with them.

**Comment by fd0** [comment]
Hey, we had this issue already a few times, e.g. in #1425. Can you please report back what the output of the following command is:
```
$ curl -u "$B2_ACCOUNT_ID:$B2_ACCOUNT_KEY" https://api.backblazeb2.com/b2api/v1/b2_authorize_account
```

**Comment by fd0** [comment]
Oh, I just saw that you've got one of the variable names wrong: `B2_ACCOUNT` instead of `B2_ACCOUNT_ID`...

**Comment by mikeburr** [comment]
That was indeed the problem. Many thanks for the quick response!
