### ISSUE TITLE
S3 api calls for buckets in regions other than us-east-1

### ISSUE THREAD

**Issue by tamalsaha** [restic/restic#1492]
Restic does not allow users to tell the `region` for s3 buckets. Say, I want to store backup in a bucket in us-west-2 region using restic. Does that mean every request gets redirected (resulting in twice the number of http requests)?

I am referring to https://github.com/minio/minio-go/blob/0306684c438ecbb3aab0532016f25d8aad07dd75/api.go#L428

@harshavardhana

**Comment by fd0** [comment]
As far as I understood the code, minio-go once queries which region the bucket is in, and then uses the correct endpoint directly.

**Comment by harshavardhana** [comment]
Yes region is cached upon a lookup . There is no redirection

**Comment by fd0** [comment]
Ok, so we can close this issue. Thanks for the clarification!

**Comment by tamalsaha** [comment]
Thanks for the quick response, folks! I am using the AWS SDK for one of our repos directly and it seems that we have to provide the region correctly for AWS sdk to work correctly with buckets in non us-east-1 region.
