### ISSUE TITLE
Sort Output of "restic find" by snapshot date

### ISSUE THREAD

**Issue by lingej** [restic/restic#1495]
## Output of `restic version`

restic 0.8.0 (v0.8.0-55-g95b6e4e9)
compiled with go1.9.2 on linux/amd64

## Actual behavior

`restic snapshots` show alle snapshots orders by date
`restic find` shows all found files but not ordered by snapshot date

## Expected behavior

 - Output should be sorted by snapshot timestamp.
 - Add snapshot id to long output of `restic find -l ` if possible

**Comment by fd0** [comment]
Good idea, thanks for reporting it!

**Comment by MichaelEischer** [comment]
Sorting by snapshot timestamp should be fairly easy to implement: just sort the snapshots before starting the actual snapshot processing.

To print the full id it would be necessary in `cmd_find.go` to adapt `statefulOutput.PrintPatternNormal` accordingly.
