### ISSUE TITLE
[discussion] Google Archival Cloud - Coldline storage

### ISSUE THREAD

**Issue by amenk** [restic/restic#1496]
I am searching for a cheap offsite storage and have read

Backend: Amazon Glacier #541

to find out that glacier is not very suitable.

What about GCS coldline [1] storage? Is that more suitable from the pricing? Is anybody using it and can estimate prices?

The pricing modle seems to be a bit easier than glacier, but still not very transparent.

I think it is about estimating how many class A / class B actions restic would run during a backup?

[1] https://cloud.google.com/storage/pricing#storage-pricing

**Comment by MatthewVance** [comment]
I've been using Google Cloud Storage as my backend. It's been cost effective for my needs. The thing with AWS and GCS to keep in mind when using their less expensive storage tiers is reads and the like are more expensive. What I do is backup to a local repo and then have a cron job to sync the repo to cloud storage. Within GCS, I have a lifecycle policy that tiers the data down as it ages. I can restore from my local repo without any expense. In the event of a disaster, I can pull the copy of the repo from the cloud and then restore.

You can accomplish something similar with AWS S3. You can life cycle from Standard to Infrequent Access Storage to Glacier. Writing directly to Glacier, as you've noted, is not very suitable for Restic.

https://cloud.google.com/storage/docs/lifecycle
https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html

https://cloud.google.com/storage/pricing#archival-pricing
https://aws.amazon.com/s3/pricing/

By the way, this discussion is probably better suited for the forum at https://forum.restic.net/.

**Comment by fd0** [comment]
Thanks for the explanation (and the link to the forum). I'll close this issue for now, please feel free to add further comments. Thanks!
