### ISSUE TITLE
--exclude-if-present seems missing from docs

### ISSUE THREAD

**Issue by alphapapa** [restic/restic#1498]
The `--exclude-if-present` option to the `backup` command seems to be missing from http://restic.readthedocs.io/en/latest/

**Comment by fd0** [comment]
Hm, you're right. That can be improved. Thanks for the report!

**Comment by whereisaaron** [comment]
There is some mention now, but I can't discern a some things from the documentation:

1. It says it excludes the contents of the folder, but does that include subdirectories?

2. Does the filename match only exactly or support the restic wildcards?

3. The help text mentions you can specify a 'header' to match in the file, but not the syntax for the header or how it is matched. It is a match from byte 0? Or a literal sub-string match anywhere in the file?

It would be great if people could contribute examples of using this option. E.g. I'd like to use it to exclude MySQL data folders, maybe on the `auto.cnf` file will work? But will it exclude sub-folders with the table data?

http://restic.readthedocs.io/en/latest/040_backup.html?highlight=--exclude-if-present
> --exclude-if-present Specified one or more times to exclude a folders content if it contains a given file (optionally having a given header)

http://restic.readthedocs.io/en/latest/manual_rest.html?highlight=--exclude-if-present
> --exclude-if-present stringArray   takes filename[:header], exclude contents of directories containing filename (except filename itself) if header of that file is as provided (can be specified multiple times)

**Comment by whereisaaron** [comment]
I found the older code and looks like 'header' is a comparison from byte zero. In newer code in the master this has gone somewhere else the github search can't find.

https://github.com/restic/restic/blob/c22c582546976a5153cf41b95231fdb7ec3d0d4c/cmd/restic/cmd_backup.go#L584-L634

**Comment by alphapapa** [comment]
@whereisaaron These are great points, but I guess you should probably open a new issue for them.
