### ISSUE TITLE
Potential issue or different implementation with --limit-upload

### ISSUE THREAD

**Issue by nixguru** [restic/restic#1506]
When uploading data (at least to B2) using --limit-upload 90 (in kB), data flows are bursting to sometimes 1MiB/s or higher, with long delays typically between each large burst.

I suspect the --limit-upload was done by averaging upload data over time.  That would result in 90kB/s over time, but there is no rate limiting of the actual upload itself in real time.  Is this a correct understanding of how it was implemented, or was it supposed to work another way and therefore a bug?

There are other mechanisms by which I could see a more smooth data flow, but it'd require modifications to the firewall rules or a tool to shape restic network traffic.

## Restic version details
restic 0.8.0 (b9441a1)
compiled with go1.9.2 on linux/amd64

## Output of `restic v0.80`
(incomplete -- lots of data to upload -- still in progress)
scan [/some/dir /some/dir]
[0:06] 17482 directories, 139992 files, 1.011 TiB
scanned 17482 directories, 139992 files in 0:06

## How did you run restic exactly?
(removed some specific directories -- not relevant)
/usr/bin/restic --cache-dir=/some/dir/restic-cache --limit-upload 90 backup --one-file-system /some/dir /some/dir --exclude /some/dir --exclude /some/dir

## What backend/server/service did you use to store the repository?
Backblaze B2

## Expected behavior
Smooth, consistent data flows according to --limit-upload.  Expected doesn't imply it is what was intended by the developers.

## Actual behavior
Bursting, with long delays between bursts

## Steps to reproduce the behavior
Just run the command with a lot of files :)

## Do you have any idea what may have caused this?
I suspect the implementation of the upload limit was done over time and does not actually limit rate.

## Do you have an idea how to solve the issue?
Implement rate/throughput limit differently

## Did restic help you or made you happy in any way?
This is a great tool for cloud backup.

**Comment by fd0** [comment]
Yeah, thanks for bringing this up again. We're aware of the issue, which is on the boundary between restic and the library (blazer) we're using to access B2.

**Comment by fd0** [comment]
This will be addressed in #1511, which limits the bandwidth at the `http.RoundTripper` layer.

**Comment by fd0** [comment]
You can try the branch `improve-http-limiting`
