### ISSUE TITLE
Encryption documentation very hidden

### ISSUE THREAD

**Issue by rugk** [restic/restic#1508]
I looked at this project for the first time and it was hard to find the encryption details, which is something I always look at in such a kind of projects.

## Actual behavior

I finally found it in the references doc with the search funtcion, but that was hard. On the intro page it just mentions that it dopes it "safely". That is okay to day, but it does not mean anything. As a user I want to see facts.

## Expected behaviour

It should mention AES on the first page, already. Details maybe somewhere more obvious, e.g. on the "Encryption" doc page.

**Comment by fd0** [comment]
Good idea, thanks

**Comment by jtagcat** [comment]
I think this issue could be closed, though I think docs [on encryption](https://restic.readthedocs.io/en/stable/070_encryption.html) isn't the best. For that see below:

**Comment by rawtaz** [comment]
@rugk Given https://github.com/restic/restic.net/commit/2a79fdc2fc2bf9ff85019083ba48926f091697df , do you still think there's something missing? Otherwise feel free to close this issue.

**Comment by rugk** [comment]
Yep, confirmed fixed, thanks.
