### ISSUE TITLE
Add to Wikipedia

### ISSUE THREAD

**Issue by rugk** [restic/restic#1509]
BTW one should add this project to https://en.wikipedia.org/wiki/List_of_backup_software.

**Comment by rawtaz** [comment]
I just did. Not a fan of the "Last updated" column, but well, it is there so I filled it out. Didn't create a link for the Package column, because there's currently no Wikipedia page for restic and I'm not sure what they're like to put in quotes for it.

**Comment by fd0** [comment]
Cool, nice idea! I think we can close this issue, thanks @rawtaz!

**Comment by rugk** [comment]
Great, just for the reference: On https://en.wikipedia.org/wiki/Comparison_of_backup_software it is already there.

**Comment by rawtaz** [comment]
@rugk I'm preparing a Wikipedia page about restic. Once it's published (requires review and acceptance, so it can take some time), I'll add it to the comparison you linked to above.

**Comment by rawtaz** [comment]
I have now created a draft article at https://en.wikipedia.org/wiki/Draft:Restic - please provide any feedback you have, preferrably with suggestions on what to add.

**Comment by rawtaz** [comment]
FWIW, I've added more text.

**Comment by rawtaz** [comment]
Submitted it for review as it is now. Apparently that process can take months, so we'll see.

**Comment by rugk** [comment]
IMHO you can already add the comparison before the main article as the colored table also already helps.

I can have a look, but I'm not familiar with restic. Anyway, I'll have a look as for general Wikipedia things and so on.

**Comment by fd0** [comment]
You could add a bit more details for the deduplication: It uses Content Defined Chunking based on [Rabin Fingerprints](https://en.wikipedia.org/wiki/Rabin_fingerprint), https://github.com/restic/chunker has a few links.

**Comment by rawtaz** [comment]
For various invalid reasons a Wikipedia reviewer declined the article.

I've deleted it as it's currently a waste of time to try making the reviewer understand that notability is not what the common user visiting Wikipedia cares about.

Until there's more material for notability (from other than well known people in the field as well as large external parties writing about restic completely on their own) it's just a waiting game.

**Comment by rugk** [comment]
Okay, so at least complete the table there. IMHO that's more important and useful anyway.
