### ISSUE TITLE
Microsoft OneDrive storage backend

### ISSUE THREAD

**Issue by ifedorenko** [restic/restic#1510]
I'd like to propose adding MS OneDrive storage backend support. They are priced fairly competitively with 1TB for USD70/year and I think it is possible to use their "5 user 5TB" USD$100/year plan with some tweaks too. I plan to have working implementation in next few days (all existing storage backend tests pass but I haven't tested with real data yet). I can open pull request if there is interest.

**Comment by fd0** [comment]
Hey, what's the current state of the "client secret" for OneDrive? Does software need such a secret (and does it need to be kept secret)?

Before merging a new backend, we must find solutions for:
 * Is it suitable for saving backup data? There was the drama with Amazon Cloud Drive and rclone (for details see #212) that we need to avoid.
 * Does the authentication (e.g. oauth) workflow support running it unattended e.g. on a server? Some services require a workflow that needs a website/server.
 * How is the backend tested on Travis? Is there a free test account we can use, or is somebody willing to step up to paying an account to run the tests on? With the ability to debug the backend and run continuous tests on it, we cannot merge it.

**Comment by ifedorenko** [comment]
> Is it suitable for saving backup data? 

I can't speak for Microsoft and don't know how they feel about using OneDrive as a backup backend. They did have [their own little drama about unlimited accounts couple of years ago](https://blogs.office.com/en-us/2015/11/02/onedrive_changes/?eu=true) but their current website does not appear to be hostile to "file storage" usecases. (Amazon Cloud Drive, on the other hand, very explicitly does not want encrypted files).

> Does the authentication (e.g. oauth) workflow support running it unattended e.g. on a server? Some services require a workflow that needs a website/server.

My current implementation uses standard oauth2 workflow and assumes the user will register application in MS developer console and request oauth2 access/refresh tokens outside of restic. According to discussion in https://github.com/OneDrive/onedrive-api-docs/issues/325, oauth2 refresh tokens are not supposed to expire, so everything should work unattended after initial cumbersome setup. There may be better options, I'd need to check.

> How is the backend tested on Travis? 

You get 5GB storage allowance with their free account. You do oauth2 dance to get application id, secret plus access and refresh tokens. Then you can store the secrets either in travis as (encrypted) environment variables or in an (encrypted) config file.

**Comment by jaccoh** [comment]
If rclone can do it...? :D 👍

**Comment by ifedorenko** [comment]
I have working implementation, what I use for my personal backup. Initial oauth2 setup isn't for fainthearted, for sure, but this is a one-time thing and everything works quite well after that. Let me know if you want to try.

**Comment by jaccoh** [comment]
well, I do have the set of credentials I use for rclone. I can also use that same trick to produce one for restic?
Am I correct in assuming those are the configs I need?

**Comment by ifedorenko** [comment]
rclone (mostly) automates this for you, doing it manually is more tedious. First, you need to register an app with MS, which gives you app id and secret. Then you need to authorize the app to access you OneDrive, a two-step process that gives you access and refresh tokens. Then you need to write all this into a json file for restic to find. I can provide more detailed instructions if you still want to try ;-)

**Comment by jaccoh** [comment]
Sure :)

**Comment by ifedorenko** [comment]
Sorry, totally forgot about this, will try to document configuration steps later tonight (eastern time).

**Comment by ifedorenko** [comment]
Let me know if https://github.com/ifedorenko/restic/blob/onedrive/ONEDRIVE.md gives you enough details.

Note that you probably want to build restic from my [igordev](https://github.com/ifedorenko/restic/tree/igordev) branch, which also includes more reliable Load retry implementation (as per #1560).

**Comment by jaccoh** [comment]
Awesome. Looks ‘easy’ enough. I’m more of a Python guy, but this looks scriptable.

I’ll give it a shot without scripting. Might be a few days as I’m a bit busy these days.

**Comment by fd0** [comment]
This backend can be used via rclone, I'm therefore closing this issue for now. Please feel free to add further comments. Thanks!
