### ISSUE TITLE
Windows backups restore with wrong permissions on linux

### ISSUE THREAD

**Issue by addos** [restic/restic#1512]
## Output of `restic version`
restic 0.8.1
compiled with go1.9 on linux/amd64

## How did you run restic exactly?
restic -r myrepo restore id -t directory

## What backend/server/service did you use to store the repository?
usb flash storage

## Expected behavior
When restoring a directory, it should have the necessary permissions set to be able to create files and subdirectories in the directories that are being created.

## Actual behavior
The directories that restic creates as part of the restore have 555 permissions, which prevent it from creating files and subdirectories, unless I am root when doing the restore.

## Steps to reproduce the behavior
1. Take a backup of a directory on windows with restic.
2. Try to restore the directory on a linux machine without being root.

## Do you have an idea how to solve the issue?
Directory permissions need to be at least 755 or 775.

## Did restic help you or made you happy in any way?

**Comment by alphapapa** [comment]
What are the permissions of the restic repository directory on the mounted USB drive?

**Comment by fd0** [comment]
Thanks for the report, I'm almost certain this is a bug. Can you please answer the question from @alphapapa? Can you maybe backup a sample directory with a sample file containing nothing secret, test that the issue occurs, and then zip and upload the repository somewhere (or attach it to this issue) so I can have a look? I don't have a Windows development environment...

**Comment by addos** [comment]
fd0, I just made a test repo here. I am not sure if this one has the problem, but it is small and should be easy to test on linux. I am going to have to boot linux to see what the permissions are on the repo, but I am pretty sure it should be something like 775 since the repo is on a fat32 filesystem and won't have any linux permissions.

**Comment by addos** [comment]
[test.zip](https://github.com/restic/restic/files/1609753/test.zip)

**Comment by fd0** [comment]
Thanks for the test repo, I don't see the issue here. When I'm restoring, the directory and the file are created with 777 and 666 permissions, exactly as recorded in the repo:
```
$ restic restore --target /tmp/restore latest
password is correct
restoring <Snapshot 9ca3922d of [C:\Users\Admin\Desktop\test\test_dir] at 2018-01-07 07:38:16.5294763 -0500 -0500 by DESKTOP-GKMF23F\Admin@DESKTOP-GKMF23F> to /tmp/restore
ignoring error for /test_dir: Lchown: lchown /tmp/restore/test_dir: operation not permitted
ignoring error for /test_dir/test.txt: Lchown: lchown /tmp/restore/test_dir/test.txt: operation not permitted
There were 2 errors

$ ls -alR /tmp/restore
/tmp/restore:
total 0
drwx------   3 fd0  users   60 Jan  7 14:03 .
drwxrwxrwt 249 root root  7580 Jan  7 14:06 ..
drwxrwxrwx   2 fd0  users   60 Jan  7 13:38 test_dir

/tmp/restore/test_dir:
total 4
drwxrwxrwx 2 fd0 users 60 Jan  7 13:38 .
drwx------ 3 fd0 users 60 Jan  7 14:03 ..
-rw-rw-rw- 1 fd0 users  7 Jan  7 13:37 test.txt
```

The owner of the files is stored as UID 0 (which is `root` on Linux), and since I'm not running `restic restore` as root correcting the ownership fails. But apart from that I don't see any issue here.

Thoughts?

**Comment by addos** [comment]
When I am trying to restore on my linux system from the repo that has the problem it says this:

enter password for repository: 
password is correct
restoring <Snapshot bf6e412e of [C:\Users\John Doe\Documents] at 2017-12-24 23:42:25.3294172 -0500 -0500 by John\John Doe@John> to a
ignoring error for /Documents: Lchown: lchown /home/ubuntu/Downloads/a/Documents: operation not permitted
ignoring error for /Documents/2015 Dalmation Coast Cruise.doc: OpenFile: open /home/ubuntu/Downloads/a/Documents/2015 Dalmation Coast Cruise.doc: permission denied
ignoring error for /Documents/Wine Cellar Pond Info.doc: OpenFile: open /home/ubuntu/Downloads/a/Documents/Wine Cellar Pond Info.doc: permission denied
ignoring error for /Documents/ASUS: Mkdir: mkdir /home/ubuntu/Downloads/a/Documents/ASUS: permission denied
ignoring error for /Documents/ASUS/LifeFrame: mkdir /home/ubuntu/Downloads/a/Documents/ASUS: permission denied
ignoring error for /Documents/ASUS/LifeFrame/Audio: mkdir /home/ubuntu/Downloads/a/Documents/ASUS: permission denied
ignoring error for /Documents/ASUS/LifeFrame: UtimesNano: no such file or directory
ignoring error for /Documents/ASUS: UtimesNano: no such file or directory
ignoring error for /Documents: UtimesNano: no such file or directory
There were 9 errors

**Comment by addos** [comment]
When I cd to the a directory I was trying to restore to and I do a ls -l on the Documents directory it was trying to create and restore into, I see it has the following permissions:
dr-xr-xr-x 2 ubuntu ubuntu 40 Dec 20 21:48 Documents/

**Comment by fd0** [comment]
Can you please upload a repo with test files that I can use to reproduce the issue?

**Comment by addos** [comment]
When I run restic ls -l from the snapshot id, it shows the permissions as the following:
dr-xr-xr-x     0     0      0 2017-12-20 16:48:44 /Documents

**Comment by addos** [comment]
So apparently this was restic setting the permissions in the snapshot to 555 for some reason when it took the backup on windows.

**Comment by fd0** [comment]
Ah, thanks, then maybe I can come up with a repo myself, I'll have a look.

**Comment by addos** [comment]
I'd have to reboot back to windows again to do more testing.

**Comment by addos** [comment]
Looks like every directory I backed up on windows: Documents, Pictures, Desktop, Downloads. They all have the 555 permissions on the root directory, and some of the sub directories. Not entirely sure why restic thinks they should be 555.

**Comment by fd0** [comment]
It's returned by `os.Lstat()` on Windows apparently, because that's what restic copies to the repo...

**Comment by fd0** [comment]
Ok, I can reproduce it locally, just create a dir, run `chmod -R -w dir`, backup and restore that. Thanks!

**Comment by addos** [comment]
I just created a new test repo too on windows.
[test.zip](https://github.com/restic/restic/files/1609811/test.zip)

**Comment by fd0** [comment]
Thanks! By the way, this issue is not specific to Windows. :)

**Comment by Bharathkumarraju** [comment]
I am also same issue while restoring the backup from s3, 

```
+ sudo -u restic bash -c 'source /home/restic/.restic-env ; /usr/bin/restic restore latest --target /tmp/123'
repository a05404d2 opened successfully, password is correct
restoring <Snapshot f6cd3bb9 of [/home/vagrant/raju1] at 2018-07-25 16:25:49.700224984 +0200 CEST by restic@client.backup.vagrant> to /tmp/123
ignoring error for /home/vagrant/raju1/123.txt: Lchown: lchown /tmp/123/home/vagrant/raju1/123.txt: operation not permitted
ignoring error for /home/vagrant/raju1/1234.txt: Lchown: lchown /tmp/123/home/vagrant/raju1/1234.txt: operation not permitted
ignoring error for /home/vagrant/raju1/hello.txt: Lchown: lchown /tmp/123/home/vagrant/raju1/hello.txt: operation not permitted
ignoring error for /home/vagrant/raju1: Lchown: lchown /tmp/123/home/vagrant/raju1: operation not permitted
ignoring error for /home/vagrant: Lchown: lchown /tmp/123/home/vagrant: operation not permitted
ignoring error for /home: Lchown: lchown /tmp/123/home: operation not permitted
There were 6 errors
[vagrant@client ~]$
```
