### ISSUE TITLE
Optionally suppress warnings

### ISSUE THREAD

**Issue by weiss** [restic/restic#1513]
It would be nice if there was a way to suppress warnings (by specifying `-q` twice or whatever).  I don't want my backup cron job to send emails on events that can occur during normal operation (e.g. `file has changed`), while I *do* want to be notified of actual errors.

**Comment by fd0** [comment]
Hm, I'm not sure I understand: When restic reports that a file has changed, it was not able to archive a stable/deterministic version of that file, so it is probably corrupt when you restore it. Wouldn't you want to be notified of that? Why not exclude the file if it isn't important to archive?

**Comment by weiss** [comment]
> it is probably corrupt when you restore it.

This consequence wasn't obvious to me.

> Wouldn't you want to be notified of that?

From what I can tell, this is something that can happen during normal operation, and something I can't do anything about.  In this case, the notification serves no purpose for me.  But I see your point, and I'm not suggesting to suppress such warnings by default.

> Why not exclude the file if it isn't important to archive?

Well, it would be nice if those (log) files were archived.  So if I exclude them, I'd do so because archiving them doesn't work reliably, not because they're less important than others.

**Comment by fd0** [comment]
Okay, thanks for the feedback. I'll think about it and keep this issue open as a feature request.

**Comment by MichaelEischer** [comment]
Is this still relevant? The `file has changed` warning no longer exists. Since restic 0.10.0 you can use the exit code to determine whether the backup succeeded (0), failed completely (1) or failed to read some files/encountered repository problems (3)

**Comment by MichaelEischer** [comment]
Closing this as there has been no feedback. Silencing warnings about disappeared files is tracked in #3098.
