### ISSUE TITLE
Metadata only repository for indexing and verification

### ISSUE THREAD

**Issue by eruffaldi** [restic/restic#1516]
It could be interesting to add a modality that is not writing down "data" blob content but only metadata (trees). This would allow to use the tool for verification of filesystem or tracking without additional storage.

Possible implementation: add a "vdata" blob type without offset/length data

**Comment by fd0** [comment]
Thanks for taking the time to suggest this feature. In my opinion, this is out of scope for restic, at least for now. So I'm closing this issue for now, please feel free to add further comments. Thanks!

**Comment by eruffaldi** [comment]
My usage scenario is for tracking the content of external USB hard disks. Restic provides all the other features needed: history management and mounting using FUSE. 

Eventually I will play with that in a fork.

Thanks and happy end of 2017!

**Comment by eruffaldi** [comment]
Patch (using empty data blobs): https://github.com/eruffaldi/restic/tree/metadataonly

**Comment by fd0** [comment]
Hm, what's your use case here exactly? It feels to me I haven't fully understood what you're trying to do.

What would be the difference to running `ls -alR`, saving the result and comparing that with e.g. diff?

**Comment by eruffaldi** [comment]
Using restic I can mount the offline tree of the external media hard drive browsing the structure and searching preserving metadata. Also one single restic repository allows for keeping multiple disk in a easy to manage way. 

In the patch I have implemented a second different approach that skips completely the chunking of data emitting content=[] for file objects while preserving the original file size. A filter could be added easily for storing the content of selected file types (e.g. txt, lst, md).

Now that the patch is ready I will test a bit for this usage. Thanks!

**Comment by eruffaldi** [comment]
I have indexed some of my disk using this technique. Indexing 7 external disk I have obtained 1.5M files (2 TB of data) with a repository of 500MB over 390 packs. Obtaining the listing requires 5 minutes on my machine.

Although some of the disks contain the same files the metadata stored in the tree objects are different.

**Comment by donat-b** [comment]
I think this feature is quite useful and it would be great if it was merged.
