### ISSUE TITLE
HTTPS TLS Client Certificate Authentication

### ISSUE THREAD

**Issue by brycied00d** [restic/restic#1522]
I propose adding support for TLS client certificate authentication with HTTPS connections.

The change is relatively straight-forward as it only requires feeding the paths to a certificate/key pair to [`tls.LoadX509KeyPair`](https://golang.org/pkg/crypto/tls/#LoadX509KeyPair) and appending the result to [`tls.Config.Certificates`](https://golang.org/pkg/crypto/tls/#Config).

I've already written and tested a branch with this feature implemented.

Background: We're using rest-server behind nginx (terminating and validating TLS) to receive and store backups from LAN-connected computers. We wanted to expand this to external devices, however corporate policy requires the use of TLS and client certificates across untrusted networks.

I checked the forums and the GitHub issue/PR trackers but it seems nobody else has needed this capability. I'm creating this "issue" first so that I can reference it in the PR, 

## Did restic help you or made you happy in any way?

Yes! I don't think I would be suggesting features to improve it, much less to fit it into our corporate environment, if Restic didn't make me happy.

**Comment by fd0** [comment]
Nice proposal, I'll have a look at the PR now.

**Comment by bjoe2k4** [comment]
Looks like it is implemented in the meantime in #1524. Close?

**Comment by fd0** [comment]
Oh, indeed, thanks for the reminder, closing!
