### ISSUE TITLE
TLS handshake timeout while backing up large dataset to B2

### ISSUE THREAD

**Issue by mikeburr** [restic/restic#1525]
## Output of `restic version`

$ restic version
restic 0.7.3
compiled with go1.9 on linux/amd64

## How did you run restic exactly?

(B2_ACCOUNT_ID, B2_ACCOUNT_KEY, RESTIC_PASSWORD_FILE, TMPDIR all set and exported)
$ /usr/bin/restic -r b2:xyz:def backup /path/to/large/files -e '\*\*/ghi/\*\*' (+7 more -e's)

## What backend/server/service did you use to store the repository?
 B2

## Expected behavior
backup takes awhile, but eventually succeeds

## Actual behavior
[0:01] 37 directories, 208 files, 84.403 GiB
scanned 37 directories, 208 files in 0:01
unable to refresh lock: Delete: net/http: TLS handshake timeout
unable to refresh lock: Delete: net/http: TLS handshake timeout

The errors happen some hours into the backup, then restic appears to hang until I ctrl-c it.

## Steps to reproduce the behavior
backup a large dataset to B2

## Do you have an idea how to solve the issue?
 sometimes unlocking the repo and rerunning the backup works, other times not so much...

**Comment by fd0** [comment]
Hi, thanks for the report. The version of restic you're using (0.7.3) is quite old, and this problem has been addressed in 0.8.0 (#1291, #1301). Can you please retry with restic 0.8.1?

I'm going to close this issue for now, please feel free to add further comments. Thanks!

**Comment by mikeburr** [comment]
I'll certainly try, but that might take some doing. This is on a QNAP NAS & I'm not certain if it can use the standard binaries or if I need to set up a toolchain specifically for it.

Regardless, thanks for the quick response!

**Comment by fd0** [comment]
You can either try the released binaries (we also have binaries for Linux on `arm` and `arm64`), or just cross-compile from your workstation, just use: `go run build.go --goos linux --goarch arm` (or whatever architecture that is).

**Comment by mikeburr** [comment]
For the benefit of anyone who runs across this thread in the future, replacing /share/MD0_DATA/.qpkg/Restic/restic with the 0.8.1 linux_amd64 binary seems to have done the trick on my QNAP TS-569L running 4.3.4 firmware.

**Comment by fd0** [comment]
Huh, is restic somehow bundled with the qnap software? I didn't know that, but it seems there's https://www.qnapclub.eu/en/qpkg/496

How did you install restic?

And the version is pretty old, 0.7.3 was released in September 2017, the current version is 0.8.1 (released at the end of December 2017).

**Comment by mikeburr** [comment]
I installed restic from the link you referenced - it's still at 0.7.3. AFAIK the packages on qnapclub are all maintained by volunteers on a best-effort basis, so it's not unusual for them to be several months behind. The version in the default Ubuntu repos is even older (0.7.1).

**Comment by fd0** [comment]
Ok, thanks. Maybe you can bug them somehow? The distributions are a different issue. Although we have an active Debian maintainer for our Debian packages, unstable even has 0.8.1 :)
