### ISSUE TITLE
Windows: find does not work when using sftp backend via plink

### ISSUE THREAD

**Issue by timdeluxe** [restic/restic#1527]
## Output of `restic version`
```
restic 0.8.1
compiled with go1.9.2 on windows/amd64
```

## How did you run restic exactly?
```
restic -o sftp.command="plink -s -l remoteuser -P 555 -i C:/Users/myuser/mykey_id_rsa.ppk remotehost.com sftp" --repo sftp:remotehost.com:/data -p C:\restic\backup_password.txt find "*.jpg"
password is correct
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 424.299009ms: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 820.816511ms: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 1.595350505s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 1.706752043s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 1.708019731s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 2.993481402s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 7.305435739s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 12.813524732s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 18.405802039s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 18.081587274s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 694.45101ms: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 396.599007ms: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 1.579901293s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 1.12004651s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 2.739828981s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 1.907598448s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 3.703924617s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
Load(<index/e8c3f5c568>, 0, 0) returned error, retrying after 11.190125771s: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
```
Needed to kill the process via windows task manager, cleanup after CTRL-C also wasnt able to finish.

"snapshots" command works

## What backend/server/service did you use to store the repository?
SFTP on remote Linux host, via plink because i want to use a key + a different SFTP port.

## Expected behavior
find files

We discussed in the restic forum: I tried the find directly on the remote Linux server (because it is mine) with the local dir (so without SFTP) and there it works, just the pathes are not Windows like anymore.

Example:
```
root@server /home/myuser/jail/data # restic --repo /home/myuser/jail/data/ find "*.jpg"
password is correct
Found matching entries in snapshot xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/Wohnung/neu1.jpg
/Wohnung/neu2.jpg
/Wohnung/neu3.jpg
/Wohnung/neu4.jpg
/Wohnung/neu5.jpg
/Wohnung/neu6.jpg
```

## Actual behavior
got errors, see above.

## Steps to reproduce the behavior
- create SFTP backend with pubkey authentication
- "install" restic on windows (=download the windows binary)
- download plink from the PuTTY project
- initialize a repo with the SFTP backend
- backup some snapshots
- try to find files

## Do you have any idea what may have caused this?
Looks like it is something with the special plink-ish SFTP connection, because the find on the local dir on the remote server works.

## Do you have an idea how to solve the issue?
No, i have no idea which permission to what could be denied.

## Did restic help you or made you happy in any way?
Yes, a lot :)

**Comment by timdeluxe** [comment]
Additional info: Working on the remote server directly might have destroyed something, because new backups also do not work anymore.
"check" also brings the same error.
Only "snapshots" works :(

**Comment by fd0** [comment]
Hm, that's odd. What's the backend? Maybe a NAS?

**Comment by fd0** [comment]
This smells like a path issue, hm. Can you build restic with `go run build.go -tags debug`, then run it on Windows while setting the environment variable `DEBUG_FILES` to the value `sftp.go`? That should print all debug messages from the sftp backend implementation, maybe we see something there.

**Comment by timdeluxe** [comment]
Thanks to debug log i spotted the error by myself.
The activity (forget/prune) on the Linux backend rewrote the index file - while rewriting that, it changed the owner:
```
root@server /home/remoteuser/jail/data/index # l
total 184K
-rw------- 1 root root 181K Jan  4 23:41 e8c3f5c568xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
(i x-ed the hash to not present sensitive data)

After chowning it back to the right user all works again now. Sorry that i didn't see it from the start, on the parent level all still belonged to the correct user and i didnt do a find.

Lessons learnt: If i do those forget/prune actions on the remote host, i should chown to the remote user.

Idea: Maybe it can be catched, if some file on the repo can not be written and output some more meaningful error message like "can not write file xxxx on repository". But would just nice to have.

**Comment by fd0** [comment]
Ah, thanks for the feedback!

> (i x-ed the hash to not present sensitive data)

For the record: The names of the files in the repo is just the SHA256 hash of the encrypted content, that data is meant to be seen by an attacker (according to our threat model) and is not secret at all. :)
