### ISSUE TITLE
Add code generator to test Node equality

### ISSUE THREAD

**Issue by fd0** [restic/restic#153]

**Comment by fw42** [comment]
More context: Come up with something less repetitive than what we currently do in [Node.Equal()](https://github.com/restic/restic/blob/adcde1988e48e17ec03e031031d5d1dd3f498852/node.go#L233-L290).

**Comment by fd0** [comment]
This can easily be done with https://github.com/tkrajina/go-reflector

**Comment by fd0** [comment]
Works for now, closing.
