### ISSUE TITLE
FYI: restic-runner

### ISSUE THREAD

**Issue by alphapapa** [restic/restic#1531]
Hi,

Just wanted to share this script I put together to make it easier to configure Restic repos and backup sets:

https://github.com/alphapapa/restic-runner

Thanks for this great program!

**Comment by rawtaz** [comment]
This would probably be better to post in the forum.

May I ask though, what problem or use case does this solve?

It seems to me that all you specify in the config file is the very same things you'd specify on the command line, so what is the point of wrapping that in the first place?

**Comment by alphapapa** [comment]
The point is that it's easy to backup multiple sets of data to multiple repositories, with certain complex configuration consistent between them, without writing long command lines every time.  For example:

```sh
# Backup music locally
restic-runner --set music --repo local backup

# Backup same music remotely
restic-runner --set music --repo remote backup
```

Compare to:

```sh
# Backup music locally
RESTIC_REPOSITORY=/mnt/backup/restic RESTIC_PASSWORD_FILE=/mnt/backup/restic/password_file restic --tag music --include --one-file-system --exclude-caches --exclude-if-present .nobackup --exclude "*.m3u" --exclude "*.mood" --tag music ~/Music 

# Backup same music remotely
RESTIC_REPOSITORY=sftp://remote.server/backups/restic RESTIC_PASSWORD_FILE=/mnt/backup/restic/password_file restic --tag music --include --one-file-system --exclude-caches --exclude-if-present .nobackup --exclude "*.m3u" --exclude "*.mood" --tag music ~/Music 
```

It also makes the `diff` command much easier to use, as well as summarizing repo size changes, etc.

I spent some time documenting it thoroughly in the readme, so please read it if you have questions.

**Comment by fd0** [comment]
Thanks for the explanation and the hint to the project, it looks nice and until we get config file support it may serve other users.

I'm going to close this issue for now, please feel free to add further comments. Thanks!
