### ISSUE TITLE
"unable to open B2 backend" but why not?

### ISSUE THREAD

**Issue by MatthiasKauer** [restic/restic#1533]
Hi, I'm having trouble accessing my restic repo on B2.

It is kind of similar to https://github.com/restic/restic/issues/1490.
However, I am pretty sure I am not mixing up the environment variables here.

## Output of `restic version`
I tried three releases I downloaded from github.
Originally, I created the repo with 0.7.1

```
x 16G37 matt@hp840:~/Dropbox/restic $ bin/restic_0.7.1_linux_amd64 version
restic 0.7.1
compiled with go1.8.3 on linux/amd64
o 16GNT matt@hp840:~/Dropbox/restic $ bin/restic_0.7.3_linux_amd64 version
restic 0.7.3
compiled with go1.9 on linux/amd64
o 16GNc matt@hp840:~/Dropbox/restic $ bin/restic_0.8.1_linux_amd64 version
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```

## How did you run restic exactly?
'sncli-latest' is a Python venv that contains the b2 client. I activated it along the way to demonstrate that my credentials work with this client.

```
o 16FuA matt@hp840:~/Dropbox/restic $  B2_ACCOUNT_ID=<ID>
o 16FuC matt@hp840:~/Dropbox/restic $  B2_ACCOUNT_KEY=<KEY>
o 16FuK matt@hp840:~/Dropbox/restic $  RESTIC_PASSWORD=<PW>
(sncli-latest) o 16GJk matt@hp840:~/Dropbox/restic $ bin/restic_0.7.1_linux_amd64 -r b2:restic-backup-personal snapshots
unable to open repo at b2:restic-backup-personal: b2.NewClient: b2_authorize_account: 401: Invalid authorization token
(sncli-latest) x 16GK0 matt@hp840:~/Dropbox/restic $ bin/restic_0.7.3_linux_amd64  -r b2:restic-backup-personal snapshots
unable to open repo at b2:restic-backup-personal: b2.NewClient: b2_authorize_account: 401: Invalid authorization token
(sncli-latest) x 16GKN matt@hp840:~/Dropbox/restic $ bin/restic_0.8.1_linux_amd64  -r b2:restic-backup-personal snapshots
unable to open B2 backend: Account ID ($B2_ACCOUNT_ID) is empty
(sncli-latest) x 16GKX matt@hp840:~/Dropbox/restic $ echo $B2_ACCOUNT_ID
[not empty]
(sncli-latest) o 16GKl matt@hp840:~/Dropbox/restic $ b2 list-buckets
[lists my buckets]
```

## What backend/server/service did you use to store the repository?
Backblaze B2.

## Expected behavior
I'd like to see the snapshots I created.

## Actual behavior
See above. restic tells me my  $B2_ACCOUNT_ID is empty or wrong.

## Steps to reproduce the behavior
See above.

## Do you have any idea what may have caused this?
B2 may have changed their API but I wouldn't know about that.
I accessed the repo with 0.7.1 a couple of weeks ago.

## Do you have an idea how to solve the issue?
Not really.
I'll try the same steps again just to make sure it's not a fluke.

## Did restic help you or made you happy in any way?

restic is an amazing project and I really like its feature set.
Currently, I'm still building up trust before I can really use it.

**Comment by MatthiasKauer** [comment]
Ok, I may be mixing something up with the way I am setting the environment variables after all.
The `b2` tool appears to have its own cache and probably doesn't even read env vars.
Let me see about that some more.

**Comment by fd0** [comment]
Hey, this is caused by the way you use the environment variables. I don't know how the Python b2 client works, but the environment variables aren't passed to subprocesses you start in the shell:

```
$ FOO=xxx
$ echo foo is: $FOO
foo is: xxx
$ sh -c 'echo foo is: $FOO'
foo is:
```

If you want to pass environment variables to subprocesses, you need to `export` them:

```
$ export FOO
$ sh -c 'echo foo is: $FOO'
foo is: xxx
```

Does that work?

**Comment by MatthiasKauer** [comment]
Yeah, I just got there as well.
Should have known that `export` is necessary.
The b2 client really threw me off but it seems to store its parameters in a different way. Probably a file somewhere.
