### ISSUE TITLE
Implement getgrnam() for group names

### ISSUE THREAD

**Issue by fd0** [restic/restic#154]
Or use a library, e.g. https://github.com/kless/osutil

**Comment by fw42** [comment]
For a bit more context: This is to have something similar to [node.fillUser()](https://github.com/restic/restic/blob/adcde1988e48e17ec03e031031d5d1dd3f498852/node.go#L346-L351), but for groups, i.e. look up the group name by the group id.

**Comment by fd0** [comment]
FYI, the functions have been added to `os/user`: https://godoc.org/os/user#LookupGroup
