### ISSUE TITLE
Unnecessary backend.Test calls during check

### ISSUE THREAD

**Issue by ifedorenko** [restic/restic#1541]
Current `restic check` implementation first performs [`backend.Test`](https://github.com/restic/restic/blob/v0.8.1/internal/checker/checker.go#L194) to verify all pack files referenced in the index are indeed available in the backend, then it performs [`backend.List`](https://github.com/restic/restic/blob/v0.8.1/internal/checker/checker.go#L245) to locate orphaned pack files. 

For 500GB repository this results in ~100K remote http requests (assuming 5MB average pack file size), and with average 100ms http roundtrip time `restic check` on 5 concurrent connections takes ~33 minutes.

I think the same check can be implemented with single `backend.List` to get set of all available packs, which can then be matched with packs referenced in the index to determine missing and orphaned packs without additional remote calls.

**Comment by fd0** [comment]
Thanks for the hint!

**Comment by fd0** [comment]
Resolved in #1548
