### ISSUE TITLE
Output snapshot ID in quiet mode from `restic backup` command

### ISSUE THREAD

**Issue by skriss** [restic/restic#1546]
It would be nice to have **just** the snapshot ID output when running `restic backup /foo --quiet`. This would make it easy to record the snapshot that was just created without having to do text parsing on the normal verbose output.

I'd be happy to contribute a PR for this if it seems like a reasonable change.

**Comment by dimejo** [comment]
Please don't do that. I'm using `--quiet` to run snapshots with a cronjob. Adding a single line to `--quiet` would send me an e-mail for every snapshot (and requiring me to read them all) instead of sending e-mails only when something went wrong.

**Comment by alphapapa** [comment]
@skriss You might find https://github.com/alphapapa/restic-runner useful.  You can easily get the last snapshot ID like:

```
restic-runner --repo REPO snapshot-ids | tail -n1
```

@dimejo Not that I disagree with you, but in general you will probably find `chronic` from `moreutils` very useful for cronjobs, as it only sends output if a job exits with non-zero status: https://joeyh.name/code/moreutils

**Comment by dimejo** [comment]
> @dimejo Not that I disagree with you, but in general you will probably find chronic from moreutils very useful for cronjobs, as it only sends output if a job exits with non-zero status: https://joeyh.name/code/moreutils

You are right, using chronic on a cronjob isn't difficult. But ist it really necessary to install an additional package to make a command behave as it should in the first place? Do most people use `--quiet` and still want to see the snapshot-id?

**Comment by alphapapa** [comment]
> Not that I disagree with you...

;)

**Comment by fd0** [comment]
I don't think we'll implement this, in my opinion it's too specific.

I'm planning to add a `--json` output mode to `backup` when #1494 is finished, then you can use `jq` to filter just the fields that you like.

For now I'm closing this issue. Thanks!
