### ISSUE TITLE
/: name collision for "home", renaming to "home-1"

### ISSUE THREAD

**Issue by erikw** [restic/restic#1557]
## Output of `restic version`
```
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```

## How did you run restic exactly?

I'm using a B2 backend, with configured environment with `RESTIC_REPOSITORY, B2_ACCOUNT_ID1,.. etc.

My system looks like this:
```bash
$ df
Filesystem                      1K-blocks      Used Available Use% Mounted on
...
/dev/mapper/system-root    48232448  15513536  31734240  33% /
/dev/sda2                  507748    380252    101282  79% /boot
/dev/mapper/system-home   61065216  35948420  24398956  60% /home
```

and my **goal** is to back up  all of `/, /boot, /home` except for Linux system directories like `/dev/, /sys`.

My **strategy** to do this is to
*  use the backup option `--one-file-system` to not back up dirs like `/dev` (I read in the documentation that this option will achieve this.
* set the backup destinations to `/ /boot /home`.

Thus I run the full back up command like this, and I get the output as listed:

```bash
$ restic backup --one-file-system / /boot /home
password is correct
using parent snapshot xxxx
scan [/ /boot /home]
scanned 160501 directories, 1082390 files in 3:55
/: name collision for "boot", renaming to "boot-1"686 GiB  1242880 / 1242891 items  0 errors  ETA 2:57
/: name collision for "home", renaming to "home-1"
[1:34:18] 100.00%  47.736 MiB/s  263.761 GiB / 263.686 GiB  1242897 / 1242891 items  0 errors  ETA 0:00
duration: 1:34:18, 47.72MiB/s
snapshot yyyyy saved
```

If I now check how this looks, it looks like this:

```bash
$ restic snapshots
ID        Date                 Host        Tags               Directory
----------------------------------------------------------------------
xxx  2018-01-14 00:58:19    xxxx                             /  
                                                             /boot
                                                             /home
$ restic mount /tmp/restic-mnt
$ ls -l /tmp/restic-mnt/snapshots/latest/
total 0
lrwxrwxrwx   1 root  root  0 Oct 17 09:32 bin -> usr/bin/
drwxr-xr-x   6 root  root  0 Jan 11 19:00 boot/
drwxr-xr-x   6 root  root  0 Jan 11 19:00 boot-1/
drwxr-xr-x 109 root  root  0 Jan 13 21:46 etc/
drwxr-xr-x   4 root  root  0 Jan 15  2015 home/
drwxr-xr-x   4 root  root  0 Jan 15  2015 home-1/
drwxrwxrwx   2 root  root  0 Aug 13  2016 keybase/
lrwxrwxrwx   1 root  root  0 Oct 17 09:32 lib -> usr/lib/
lrwxrwxrwx   1 root  root  0 Oct 17 09:32 lib64 -> usr/lib/
drwxr-xr-x   5 erikw users 0 Jan 14 02:21 media/
drwxr-xr-x   3 root  root  0 Nov 15  2014 mnt/
drwxr-xr-x  14 root  root  0 Jan  6 13:03 opt/
drwxr-x---  16 root  root  0 Jan 14 02:56 root/
lrwxrwxrwx   1 root  root  0 Oct 17 09:32 sbin -> usr/bin/
drwxr-xr-x   4 root  root  0 Oct 25  2014 srv/
drwxr-xr-x  11 root  root  0 Jan 13 17:13 usr/
drwxr-xr-x  11 root  root  0 Jan 13 12:40 var/
```

So indeed, both `boot` and `boot-1`, and `home` and `home-1`; not what I want!

So I was thinking maybe I should not specify `/boot` and `/home` then as they are mounted under `/`, so  I tried skipping that

```bash
$  restic backup --one-file-system /
$ restic snapshots
ID        Date                 Host        Tags               Directory
----------------------------------------------------------------------
xxx  2018-01-15 18:53:13  yyy      systemd.timer    /
$ ls -l /tmp/restic-mnt/snapshots/latest/
total 0
lrwxrwxrwx   1 root  root  0 Oct 17 09:32 bin -> usr/bin/
drwxr-xr-x 109 root  root  0 Jan 13 21:46 etc/
drwxrwxrwx   2 root  root  0 Aug 13  2016 keybase/
lrwxrwxrwx   1 root  root  0 Oct 17 09:32 lib -> usr/lib/
lrwxrwxrwx   1 root  root  0 Oct 17 09:32 lib64 -> usr/lib/
drwxr-xr-x   5 erikw users 0 Jan 14 02:21 media/
drwxr-xr-x   3 root  root  0 Nov 15  2014 mnt/
drwxr-xr-x  14 root  root  0 Jan  6 13:03 opt/
drwxr-x---  16 root  root  0 Jan 14 02:56 root/
lrwxrwxrwx   1 root  root  0 Oct 17 09:32 sbin -> usr/bin/
drwxr-xr-x   4 root  root  0 Oct 25  2014 srv/
drwxr-xr-x  11 root  root  0 Jan 13 17:13 usr/
drwxr-xr-x  11 root  root  0 Jan 13 12:40 var/
```

So when I skip adding backup paths `/boot /home` they are not included. But when I include them they are backed up twice (not really, I except that they point to the same data blobs internally). It could be the `--one-file-system` flag that skips `/boot /home`, which makes sense, they are from another filesystem and should imo be skipped if this flag is sent. But if I omit `--one-file-system` I would get `/dev/ /run /proc` and all that crap which I don't want either.

So what is the correct way of making a full system backup with several disks mounted under root?

## What backend/server/service did you use to store the repository?

Backblaze b2

## Expected behavior

No name collisions

## Actual behavior

Name collisions

## Steps to reproduce the behavior

As outlined previously

## Do you have any idea what may have caused this?

Miss-understanding from user how to implement his use case?

## Do you have an idea how to solve the issue?

Post this issue here to consult the experts!

## Did restic help you or made you happy in any way?

Yes sure it looks great so far, except from this!

**Comment by rawtaz** [comment]
This is already tracked in #549.

**Comment by erikw** [comment]
@rawtaz hey, thanks for answering! It looks like #549 is another issue where that user wants to backup files with actual same name, and he has problem restoring them.

However in my case, I want to backup one directory `/home`and also `/` where the first one is mounted, but it turns out the home directory is backed up twice instead, as `home` and `home-1`.

The issues might be related, but the set is up is quite different at least.

**Comment by dimejo** [comment]
The archiver code is currently rewritten in #1494 which might solve your problem. Maybe @fd0 can give you an ETA on this.

**Comment by fd0** [comment]
Hey Erik, thanks for the report. @rawtaz is right, it's indeed cause by the issue we're tracking as #549. I don't have a timeline for you regarding #1494, but rest assured that it will be solved by the new archiver code.

In the meantime, you can use the workaround mentioned here: https://forum.restic.net/t/full-system-restore/126/8?u=fd0

I'm closing this issue as a duplicate, please let us know (and leave a comment) if this does not work for you. Thanks!

**Comment by erikw** [comment]
@fd0 Ok cool, I'm looking forward to the rewrite!

**Comment by erikw** [comment]
I can confirm that with restic version `0.9.0`, this problem is not resolved.!
