### ISSUE TITLE
"Load(<data/...>, i, n) returned error, retrying"

### ISSUE THREAD

**Issue by cafuego** [restic/restic#1558]
I am mostly wondering if the messages I'm seeing are debug output caused by the backend library retrying the API call through backend/backend_retry.go and working as expected on the second attempt, which would mean I can ignore them.

## Output of `restic version`

restic 0.8.1
compiled with go1.9.2 on linux/amd64

## How did you run restic exactly?

```
$ export GOOGLE_PROJECT_ID=project-id
$ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/creds.json
$ export RESTIC_PASSWORD=super-secret
$ export RESTIC_REPOSITORY=gs:bucket:/restic
restic prune
```

## What backend/server/service did you use to store the repository?

gs

## Expected behavior

Check what's in use and delete unused packs.

## Actual behavior

```
password is correct
counting files in repo
building new index for repo
Load(<data/32d1f24726>, 4, 4211807) returned error, retrying after 428.293977ms: googleapi: got HTTP response co
de 503 with body: Service Unavailable
Load(<data/975adda33a>, 4, 4557216) returned error, retrying after 614.670252ms: googleapi: got HTTP response co
de 503 with body: Service Unavailable
Load(<data/a5784ca161>, 4, 5267878) returned error, retrying after 599.886743ms: googleapi: got HTTP response co
de 503 with body: Service Unavailable
Load(<data/ac07eadf40>, 4, 5809614) returned error, retrying after 663.000122ms: googleapi: got HTTP response co
de 503 with body: Service Unavailable
Load(<data/c62e947ee6>, 4, 5322550) returned error, retrying after 295.470429ms: googleapi: got HTTP response code 503 with body: Service Unavailable
Load(<data/de5950e35b>, 69, 5250866) returned error, retrying after 330.091256ms: googleapi: got HTTP response code 503 with body: Service Unavailable
[3:02:18] 100.00%  121008 / 121008 packs
```

Restic then panics and exits due to a *different* reason, as per ticket https://github.com/restic/restic/issues/1359

## Steps to reproduce the behavior

This happens any time I try to forget/prune old snapshots only on this repository.

## Do you have any idea what may have caused this?

My guess it's an API rate limiter and after a retry the API calls in fact succeed, but I'm not certain. I'd expect restic to error out if it can't access data, not continue and end up on 100% of packs.

## Do you have an idea how to solve the issue?

If this is a debug message and the API call works eventually, the Load(...) messages should perhaps only be printed if I run restic with a debug / verbose option or mention that on retry the call succeeded. If not, should restic exit when they happen?

## Did restic help you or made you happy in any way?

Yes, it makes me and my team very happy to have working backups when (not if) someone accidentally deletes production data :-)

**Comment by cafuego** [comment]
After trying a suggested fix for https://github.com/restic/restic/issues/1359 it seems that these messages do in fact correspond to actual errors and should *probably* make restic panic & exit when they happen.

**Comment by fd0** [comment]
Thanks for the report. I agree that this should be a bit more user friendly. In your case, the backend requests fail, restic retries them, and they eventually succeed. When there's an error that could not be solved by retry, restic will bail out, so that did not happen in your case. So everything is fine.

I think we can close this issue, I'll rework the user interface after I'm done with #1494... Thoughts?

**Comment by cafuego** [comment]
Sounds good to me :-)  The behaviour is now explicitly documented in this issue, so if someone else should encounter the same question before you get the chance to rework the interface, they can find the answer.

**Comment by fd0** [comment]
So, then I'm closing this issue. Thanks!
