### ISSUE TITLE
better error handling reading contents from backend

### ISSUE THREAD

**Issue by ifedorenko** [restic/restic#1559]
Was troubleshooting apparent deadlock during `restic check --read-data` when I noticed couple of problems with error handling when reading remote file contents.

### file contents reader is not closed in case of errors

Here is simplified code snippet that highlights the problem:
```go
rd, err := be.Load(ctx, h, 0, 0)
if err != nil {
	return err
}
size, err := io.Copy(wr, rd)
if err != nil {
	return err // XXX the reader is not closed here
}
```
[checker checkPack is one example](https://github.com/restic/restic/blob/v0.8.1/internal/checker/checker.go#L666-L689), but there are few more.

This problem is particularly severe for `b2`, `swift` and other backends that use `Semaphore.ReleaseTokenOnClose` to limit the number of concurrent connections. Leaked open readers exhaust available connection tokens, which deadlocks restic (can't even stop it with control-c).

### errors reading file contents are not retried

Here is [RetryBackend.Load() implementation](https://github.com/restic/restic/blob/v0.8.1/internal/backend/backend_retry.go#L91-L100) as of version 0.8.1:
```go
func (be *RetryBackend) Load(ctx context.Context, h restic.Handle, length int, offset int64) (rd io.ReadCloser, err error) {
	err = be.retry(ctx, fmt.Sprintf("Load(%v, %v, %v)", h, length, offset),
		func() error {
			var innerError error
			rd, innerError = be.Backend.Load(ctx, h, length, offset)

			return innerError
		})
	return rd, err
}
```

Note that the reader is returned to the clients as-is without any retry logic.

----

I see two possible ways to address these two problems:

* One is keep current backend API; add all missing `rd.Close()` calls; change `RetryBackend.Load()` to return reader implementation that resumes download from the point of failure. 
* Change `Backend.Load()` API to enable correct retry behaviour and guarantee contents reader is always closed. I have an idea how to do this, but will need to prototype it before I am sure it's workable.

**Comment by fd0** [comment]
Huh, nice catch with the checker :)

**Comment by fd0** [comment]
Ah, I think we can close this issue, #1583 is already merged.
