### ISSUE TITLE
Correct output of init command

### ISSUE THREAD

**Issue by scoddy** [restic/restic#1565]
## Output of `restic version`
restic 0.8.1

## How did you run restic exactly?

$ restic -r restic-repository init
enter password for new backend:
enter password again:
created restic backend 79d7d54034 at restic-repository

## What backend/server/service did you use to store the repository?
N/A

## Expected behavior

$ restic -r restic-repository init
enter password for new **repository**:
enter password again:
created restic **repository** 79d7d54034 at restic-repository

## Actual behavior

$ restic -r restic-repository init
enter password for new **backend**:
enter password again:
created restic **backend** 79d7d54034 at restic-repository

## Steps to reproduce the behavior

N/A

## Do you have any idea what may have caused this?

Oversight and too little caffeine. 

## Do you have an idea how to solve the issue?

N/A

**Comment by fd0** [comment]
> Oversight and too little caffeine.
Indeed, for sure a combination of both. Thanks for the report!
