### ISSUE TITLE
Support password as environment variable

### ISSUE THREAD

**Issue by jpic** [restic/restic#1566]
Hello !

For situation where we don't want to store the password on the server, and control everything through a remote orchestration such as ansible which can execute one shot commands using crypted inventory variables, it would be great to support password as environment variables. (Meanwhile, I'll just create the file and delete it, and hope no human interrupts the software or whatever and leaves the cleartext password file on the server).

What do you think ?

**Comment by rawtaz** [comment]
@jpic There's already what you're looking for, `RESTIC_PASSWORD`as well as `RESTIC_PASSWORD_FILE` and `RESTIC_REPOSITORY`.

**Comment by rawtaz** [comment]
BTW, It's mentioned here: https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html

**Comment by fd0** [comment]
Thanks for the answer @rawtaz, closing.
