### ISSUE TITLE
support for Illumos/Solaris

### ISSUE THREAD

**Issue by hadret** [restic/restic#1576]
## Output of `restic version`

I was trying to build latest stable release, 0.8.1.

## How did you run restic exactly?

I didn't run it, I was only trying to build it.

## What backend/server/service did you use to store the repository?

macOS, build was done with reproducible builder via docker image.

## Expected behavior

I would love to see restic building properly on Illumos/Solaris OS.

## Actual behavior

It fails with the following error messages:

```
docker run --rm --volume $PWD:/home/build restic/builder v0.8.1.tar.gz
Go version is go version go1.9.2 linux/amd64
path is /tmp/restic-release-JzlHL4
version is 0.8.1
outputdir is /home/build/restic-0.8.1-20180124-104215
restic_0.8.1_solaris_amd64
# github.com/restic/restic/vendor/bazil.org/fuse
github.com/restic/restic/vendor/bazil.org/fuse/error_std.go:27:20: undefined: errNoXattr
github.com/restic/restic/vendor/bazil.org/fuse/fuse.go:1345:26: undefined: attr
github.com/restic/restic/vendor/bazil.org/fuse/fuse_kernel.go:166:28: undefined: syscall.O_DIRECTORY
github.com/restic/restic/vendor/bazil.org/fuse/fuse_kernel.go:404:17: undefined: attr
# github.com/restic/restic/internal/restic
github.com/restic/restic/internal/restic/node.go:231:14: node.restoreSymlinkTimestamps undefined (type Node has no field or method restoreSymlinkTimestamps)
github.com/restic/restic/internal/restic/node_unix.go:21:18: cannot use statUnix(*s) (type statUnix) as type statT in return argument:
        statUnix does not implement statT (missing atim method)
github.com/restic/restic/internal/restic/node_xattr.go:16:10: undefined: xattr.Get
github.com/restic/restic/internal/restic/node_xattr.go:26:10: undefined: xattr.List
github.com/restic/restic/internal/restic/node_xattr.go:35:7: undefined: xattr.Set
build failed: exit status 2
exit status 1
```

## Steps to reproduce the behavior

Try to build restic for solaris/amd64 platform via https://github.com/restic/builder

## Do you have any idea what may have caused this?

Likely lack of support for Solaris platform.

## Do you have an idea how to solve the issue?

No, but I would hope having OpenBSD and FreeBSD support in place already, that it won't prove super difficult to include one more. Especially knowing that rest-server does support it.

## Did restic help you or made you happy in any way?

I honestly think it's the best backup solution out there and I would love to have it running on my SmartOS machines.

**Comment by jasperla** [comment]
@hadret have a look at the PR I've just submitted. I've been able to run a number of backups/restores in a SmartOS instance with that.

**Comment by hadret** [comment]
@jasperla & @fd0 thank you so much for this! I'm super happy and excited to see the PR merged! You guys are awesome! :)

**Comment by dave-fl** [comment]
This fix skirts around the issue by basically not implementing acl or xattr. 

Would it make sense to add the actual fix to the xattr package? This would require the use of cgo. 

Solaris operates differently in the sense that the syscall interface is not considered stable and calls should go through libc.

**Comment by fd0** [comment]
> Would it make sense to add the actual fix to the xattr package?

Yes

> This would require the use of cgo.

We're trying very hard to avoid `cgo`, so that won't work with restic as of now.

**Comment by dave-fl** [comment]
Given that Solaris has a different architecture that requires the use of C to make its system calls is this not a valid use case?  If the interface between xattr and restic remains identical, does it matter what must be used to get the job done?

**Comment by fd0** [comment]
Requiring C to interface with Solaris to get extended attributes means at least for compiling a binary for that platform we need a cross-compilation setup or access to a machine. Both is hard to do and makes reproducible builds (and cross-compilation in general) much more complicated or even impossible.

We could in theory add this as an optional thing, only compile support for extended attributes when `cgo` is available, but then this particular code is never compiled in our integration tests and I fear that it'll be rarely used and/or built, so we will notice build errors and bugs much later (if at all).

It feels to me that adding a `cgo` dependency to allow extended attributes in Solaris is not something we can support. Restic is a spare-time for-fun project after all. I'd rather state it clearly in the manual that we don't support extended attributes on Solaris.

**Comment by dave-fl** [comment]
Thanks for explaining that.  I see your point.  If there were changes on the go side to add the calls to the os or syscall package would that help at all or would it still leave things in the same boat?

**Comment by fd0** [comment]
> if there were changes on the go side to add the calls to the os or syscall package would that help at all or would it still leave things in the same boat?

Oh, that'd be quite different. We still would not have any integration tests for Solaris, but at least the code would be built automatically for all PRs and commits, so we'd notice failures and syntax errors very early.
