### ISSUE TITLE
Using env var for backup --exclude-file

### ISSUE THREAD

**Issue by ergl** [restic/restic#1586]
Restic already uses environment variables for repository paths (`RESTIC_REPOSITORY`) and
password files (`RESTIC_PASSWORD_FILE`), so I was wondering if maybe using another one
(e.g. `RESTIC_EXCLUDE_FILE`) for the `--exclude-file` backup option would make sense.

Another option would be to support some sort of configuration file (json, yaml, whatever), and
store repository information there (per-repo password, per-repo exclude file, etc).

**Comment by rawtaz** [comment]
For reference, here's the issue tracking implementing config file support: #16

**Comment by MatthewVance** [comment]
Is the idea for the RESTIC_EXCLUDE_FILE environment variable to point to a config file that lists folders and files to exclude? If so, I think the config file feature being discussed in #16 would provide this benefit and reduce the need for the proposed environment variable. If you agree, could we close this issue?

**Comment by ergl** [comment]
Yes, that was my original idea. I also think the config file proposal is much better, but I don't know how long it would take for that to get implemented. Adding support for RESTIC_EXCLUDE_FILE is much less invasive so I think it still has merit on it's own.

I'm closing the issue anyway, since I'd very much prefer a configuration file than adding env vars for everything.

**Comment by rawtaz** [comment]
While waiting for either enhancement, why don't you just set RESTIC_EXCLUDE_FILE in your environment, and then call restic like `restic .. --exclude-file $RESTIC_EXCLUDE_FILE`?

**Comment by fd0** [comment]
That'd be one option, probably.
