### ISSUE TITLE
Error path can leave lock file behind.

### ISSUE THREAD

**Issue by tholin** [restic/restic#1587]
Running restic with an invalid path in TMPDIR will result in an error (as expected). After that any command requiring an exclusive lock like prune will complain that the repo is locked already. Seems like the lock file is left after the error.

    $ mkdir /mnt/libra.1cay.3T/Backups/restic_temp
    
    $ RESTIC_PASSWORD="asdf" TMPDIR="/mnt/libra.1cay.3T/Backups/restic_temp" ./restic -r /mnt/libra.1cay.3T/Backups/restic init
    created restic repository 49d6b221bc at /mnt/libra.1cay.3T/Backups/restic
    
    Please note that knowledge of your password is required to access
    the repository. Losing your password means that your data is
    irrecoverably lost.
    
    $ RESTIC_PASSWORD="asdf" TMPDIR="ENOENT" ./restic -r /mnt/libra.1cay.3T/Backups/restic backup /mnt/virtual/random_data
    password is correct
    scan [/mnt/virtual/random_data]
    scanned 0 directories, 1 files in 0:00
    
    error while saving data to the repo: open ENOENT/restic-temp-pack-192466236: no such file or directory
    fs.TempFile
    github.com/restic/restic/internal/repository.(*packerManager).findPacker
            src/github.com/restic/restic/internal/repository/packer_manager.go:68
    github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
            src/github.com/restic/restic/internal/repository/repository.go:234
    github.com/restic/restic/internal/repository.(*Repository).SaveBlob
            src/github.com/restic/restic/internal/repository/repository.go:606
    github.com/restic/restic/internal/archiver.(*Archiver).Save
            src/github.com/restic/restic/internal/archiver/archiver.go:105
    github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
            src/github.com/restic/restic/internal/archiver/archiver.go:170
    runtime.goexit
            /usr/lib64/go/src/runtime/asm_amd64.s:2337
    
    error while saving data to the repo: open ENOENT/restic-temp-pack-178340715: no such file or directory
    fs.TempFile
    github.com/restic/restic/internal/repository.(*packerManager).findPacker
            src/github.com/restic/restic/internal/repository/packer_manager.go:68
    github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
            src/github.com/restic/restic/internal/repository/repository.go:234
    github.com/restic/restic/internal/repository.(*Repository).SaveBlob
            src/github.com/restic/restic/internal/repository/repository.go:606
    github.com/restic/restic/internal/archiver.(*Archiver).Save
            src/github.com/restic/restic/internal/archiver/archiver.go:105
    github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
            src/github.com/restic/restic/internal/archiver/archiver.go:170
    runtime.goexit
            /usr/lib64/go/src/runtime/asm_amd64.s:2337
    panic: fs.TempFile: open ENOENT/restic-temp-pack-192466236: no such file or directory
    
    goroutine 14 [running]:
    github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc42010c180, 0xe5c920, 0xc4200614c0, 0xb41b1, 0xa1387, 0x1a59f10d400000, 0xc4203b6000, 0xa1387, 0xc8000, 0xc4222740b0, ...)
            src/github.com/restic/restic/internal/archiver/archiver.go:175 +0x41b
    created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
            src/github.com/restic/restic/internal/archiver/archiver.go:249 +0x3d0
    panic: fs.TempFile: open ENOENT/restic-temp-pack-178340715: no such file or directory
    
    goroutine 13 [running]:
    github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc42010c180, 0xe5c920, 0xc4200614c0, 0x0, 0xb41b1, 0xa4f0fd1600000, 0xc42026e000, 0xb41b1, 0xc8000, 0xc4222740b0, ...)
            src/github.com/restic/restic/internal/archiver/archiver.go:175 +0x41b
    created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
            src/github.com/restic/restic/internal/archiver/archiver.go:249 +0x3d0
    
    $ RESTIC_PASSWORD="asdf" TMPDIR="/mnt/libra.1cay.3T/Backups/restic_temp" ./restic -r /mnt/libra.1cay.3T/Backups/restic prune
    password is correct
    Fatal: unable to create lock in backend: repository is already locked by PID 8224 on multivac by tholin (UID 1000, GID 1000)
    lock was created at 2018-01-26 18:17:24 (7.815653304s ago)
    storage ID f0848bac

### Output of `restic version`
restic 0.8.1 (v0.8.1-92-g164acceb)
compiled with go1.9.2 on linux/amd64

Also tested with 0.8.1 release version.

**Comment by fd0** [comment]
That's a bug, thanks for reporting it!

**Comment by colans** [comment]
#1494 was merged.  This should be revisited.  Is it still a problem?  If not, we can close it.

**Comment by fd0** [comment]
Yep, it is resolved, this is what happens now:
```
$ TMPDIR=foobar ./restic backup .
repository 5ec3a5df opened successfully, password is correct
Fatal: unable to save snapshot: fs.TempFile: open foobar/restic-temp-pack-167656098: no such file or directory

$ ./restic list --no-lock locks
repository 5ec3a5df opened successfully, password is correct
```

It complains, but removes the lock file from the repo correctly.

I'm closing this issue. Thanks a lot for the hint, I appreciate your help in issue gardening :)
