### ISSUE TITLE
backing up files with spaces in them with  --files-from argument

### ISSUE THREAD

**Issue by mdemoulin** [restic/restic#1590]
## Output of `restic version`
restic 0.8.1
compiled with go1.9.2 on linux/amd64

## How did you run restic exactly?
/usr/local/lib/restic_0.8.1_linux_amd64 backup --password-file=/usr/local/etc/chbackup/private/chbackup-passwd --repo=b2:xxx --files-from=/usr/local/etc/chbackup/dirs.conf --exclude-file=/usr/local/etc/chbackup/exceptions.conf --hostname=xxx --tag=system

## What backend/server/service did you use to store the repository?
B2, but I don't think it matters

## Expected behavior
I would like to be able to back up files and directories with spaces in the name

## Actual behavior
/'a\ b' does not exist, skipping
/a\ b does not exist, skipping
/'a b' does not exist, skipping

## Steps to reproduce the behavior

Just have a directory with a space in the name in a file referenced by the files-from argument. I tried 

## Do you have an idea how to solve the issue?
I tried various quoting methods with no joy
## Did restic help you or made you happy in any way?
I do love restic, but do need to be able to back up such files

**Comment by mdemoulin** [comment]
Thanks. I did try this, and then went to trying out various quoting options when it did not work. I took another look upon getting your reply, and it turns out I had a space at the end of that line (referenced by --files-from). Live by the not quoting, die by the not quoting, I suppose

Thanks again

**Comment by fd0** [comment]
That's an interesting failure case. For `--files-from`, restic takes each line as a literal file/dirname, without unquoting or stripping any spaces.

**Comment by underhillian** [comment]
FWIW, the required syntax for "--files-from" files and "--exclude-file" files appears to be different.

"--files-from" entries work as described above.  "--exclude-files" entries appear to require quoted special characters (blanks in particular).  

I'm only now trying to learn to read Go (I'm a slow learner!) so not clear to me why this is.

**Comment by fd0** [comment]
> FWIW, the required syntax for "--files-from" files and "--exclude-file" files appears to be different.

Oh, good point, that's an issue. For `--exclude-file`, spaces are stripped at the start and end of each line, and I'll open a PR which also will do that for `--files-from`.
