### ISSUE TITLE
`restic backup` progress report misleading

### ISSUE THREAD

**Issue by rumpuslabs** [restic/restic#1591]
[was: `restic backup` hangs uploading initial snapshot to B2]

## Output of `restic version`

```
$ restic version
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```

## How did you run restic exactly?

```
$ cat restic-backup.sh 
#!/bin/bash

export RESTIC_PASSWORD="redacted"
export RESTIC_REPOSITORY=b2:redacted-bucket-name:restic
export B2_ACCOUNT_ID=redacted
export B2_ACCOUNT_KEY=redacted
restic backup /home/tim --exclude-file /home/tim/restic-exclude-file
```

## What backend/server/service did you use to store the repository?

B2 and SFTP

## Expected behavior

Complete the initial backup to a B2 repository.

## Actual behavior

Appears to hang after uploading 50-65 MB, similar to #1526.

Golang stacktrace attached: [restic-stacktrace.txt](https://github.com/restic/restic/files/1669907/restic-stacktrace.txt)

## Steps to reproduce the behavior

`restic init` worked fine on the B2 repository, and `restic backup` of the same files to a local repository also worked, but every time I try to upload my initial backup to B2 it stalls.

## Do you have any idea what may have caused this?

No

## Do you have an idea how to solve the issue?

No

**Comment by rumpuslabs** [comment]
I tried a smaller backup of just over 4MB, the upload finished imperceptibly fast but hung at 100% for a minute before completing. I don't know if this is normal behaviour but it looked the same as the indefinite hang, in that the amount uploaded wasn't changing but the kBps was steadily going down and the ETA going up.

I then tried the full 10GB backup again, it stalled at just over 50MB and I left it running overnight (12+ hours). In the morning it had apparently made no more progress but there was 4GB in the `data` folder on B2. I cancelled the backup and ran `restic prune` and it showed the following:

```
password is correct
counting files in repo
building new index for repo
[4:50] 100.00%  940 / 940 packs
repository contains 940 packs (83496 blobs) with 4.233 GiB
processed 83496 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 0 snapshots
[0:00]   0 / 0 snapshots
found 0 of 83496 data blobs still in use, removing 83496 blobs
will remove 0 invalid files
will delete 940 packs and rewrite 0 packs, this frees 4.230 GiB
counting files in repo
[0:00]   0 / 0 packs
finding old index files
saved new index as e00c19c4
remove 58 old index files
[9:27] 100.00%  940 / 940 packs deleted
done
```

So perhaps it was making progress, although not reporting it on the command line.

**Comment by rumpuslabs** [comment]
I've just tried doing an SFTP backup to another machine and it's behaving the same way. Monitoring the size of the repository on the other machine shows that although `restic` says its progress is steady at `52.164 MiB / 11.036 GiB`, it is in fact transferring the data starting from well below 50MB. Once it passed 52MB of size on the remote machine, the progress report updated to `76.570 MiB / 11.036 GiB`.

A brief calculation shows that maxing out my upload bandwidth, I should expect an upload of 11GB to take around 24 hours, so leaving it overnight and having ~4GB uploaded is what I should expect. So as suggested in the previous comment, the problem here appears to be with the progress report, not with the upload.

Perhaps this is not a bug at all, but as a new user of restic, I did not understand the behaviour of the progress report. It appears that it is reporting upload progress on a file-by-file or block-by-block basis, but also reporting each file/block as complete when it has just started. This had the effect of making the progress appear artificially high to begin with, and then to stall on large files/blocks.

**Comment by rumpuslabs** [comment]
I have edited the issue title and report slightly to reflect the later comments.

**Comment by fd0** [comment]
Thanks for the report, it was already raised in #1581 and #1033.

The background story is that restic splits files into smaller blobs of about ~1MiB in size, and bundles these blobs together into so-called "pack files". The pack files are uploaded to the repo as soon as they reach the right size.

At the start, restic starts reading data happily, writing the blobs into temporary files. When such a file has reached the size of a few megabytes, it is uploaded to the backend (B2 in your case). During the upload, the thread blocks, and won't read more data. When all threads are blocked, no further read-progress is reported, so it seems to stall. In reality, restic is busy uploading files to the backend.

The reporting architecture was designed at a time when restic did not support any cloud backends, just the local and sftp backend. We'll get around to reworking the reporting structure (e.g. displaying "read progress" and "backend upload progress" separately) when #1494 is done.

I'm closing this report as a duplicate, please subscribe to one of the issue I mentioned to get notified of any progress. Thanks!

**Comment by fd0** [comment]
Ah, I forgot to mention: As a workaround to get better reporting in a situation with low upstream bandwidth, you can try limiting the number of concurrent uploads to B2 to 2, like this: `-o b2.connections=2`. Please report back if you try this!

**Comment by rumpuslabs** [comment]
> As a workaround to get better reporting in a situation with low upstream bandwidth, you can try limiting the number of concurrent uploads to B2 to 2, like this: `-o b2.connections=2`. Please report back if you try this!

I did not try running the same backup again, so it's not an apples-to-apples comparison, but I am backing up some other data using this setting and it doesn't appear to have made a great deal of difference to the quality of the reporting.

**Comment by fd0** [comment]
Ok, thanks for the feedback!
