### ISSUE TITLE
Small changes, long prune time

### ISSUE THREAD

**Issue by larsks** [restic/restic#1599]
## Output of `restic version`

```
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```

## How did you run restic exactly?

restic -r b2:my-bucket-name forget --prune --tag mytag --keep-weekly 2

## What backend/server/service did you use to store the repository?

Backblaze B2

## Expected behavior

I'm using `restic` to back up some data to Backblaze B2.  In a single repository I have a large filesystem (~ 100G) and a small directory (approx 50M).  I used `restic forget --prune` to remove some snapshots of the smaller directory, which triggered a re-indexing operation.

I expected the reindexing would be a relatively short process because the snapshots I removed were small.

## Actual behavior

The reindexing operation triggered by `--prune` seems to involve the entire repository, and resulted in a very long running process.   This caused a number of problems:

- The entire repository is locked for the duration of the reindexing process, which means I  am unexpectedly unable to interact with the repository.
- Since I'm using a service that meters data transfer, I am concerned that if re-indexing requires a lot of i/o that this will be a financially expensive operation.

## Do you have an idea how to solve the issue?

One option is perhaps to configure backblaze + b2 to use one repository per bucket. This seems to run counter to the design of restic, but maybe it's the best way to prevent small changes from triggering time- and money-intensive results. If this sounds like a good idea, maybe it should be mentioned in the documentation.

I would prefer an option that would allow a prune operation on a mixed repository like this to complete in a shorter amount of time, particularly when the changes are "small", but I don't know anything about how restic is managing the index right now so I'm unable to suggest a practical solution.

Separately, a lock-free solution or at least one that would permit read operations (particularly restores) during the reindexing process would be great.

## Did restic help you or made you happy in any way?

Other than my surprise at the run time of the `prune` operation I've been very happy so far: it's been very easy to work with and the command line seems sane.

**Comment by dimejo** [comment]
#1470 discusses ways to make `prune` less aggressive, which should decrease runtime in your use case.

**Comment by ifedorenko** [comment]
There are several issues here.

* Reindex is slow. This is partially addressed in master and I'll likely propose tuning this some more in the near future. You should see ~3x reindex time improvement when this is all done. My longer term plan is to provide an option to disable reindex during prune.

* Prune is slow. Several possible improvements are discussed in #1470, but I don't have clear idea how much room for improvement we have. Personally I am leaning towards lock-free, so long-running prune does not block backup/restore/check.

* Prune *downloads* significant amount of data. I believe this is inherited from Restic "pack" repo file format and the only way to reduce downloads is to run prune less frequently. To better support B2 and other metered storage providers, Restic should probably provide `check-and-prune` command to read all repository data and remove any unused blobs in one go.

**Comment by fd0** [comment]
@larsks can you retry with the laster master branch and report back if the sitation improves? You can find a beta here: https://beta.restic.net/?sort=time&order=desc

We've merged several pull requests which should improve performance with cloud backends and B2 especially.

For the record: The `prune` operation can be improved a lot, I have many ideas on how to do that, in addition to the ones @ifedorenko already suggested.

**Comment by larsks** [comment]
@fd0 I just tried this with 0.8.3, which I believe includes these changes.  For a repository on Backblaze B2 (backblaze tells me about 65GB in 12,500 files), a prune operation took about 1.5 hours:

```
counting files in repo
building new index for repo
[59:00] 100.00%  12576 / 12576 packs
repository contains 12576 packs (548421 blobs) with 60.011 GiB
processed 548421 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 3 snapshots
[0:22] 100.00%  3 / 3 snapshots
found 547967 of 548421 data blobs still in use, removing 454 blobs
will remove 0 invalid files
will delete 6 packs and rewrite 66 packs, this frees 135.990 MiB
[9:16] 100.00%  66 / 66 packs rewritten
counting files in repo
[35:24] 100.00%  12546 / 12546 packs
finding old index files
saved new indexes as [567da2fa 922ed923 4c941d7b 962f8dbb b45b7b48]
remove 6 old index files
[0:39] 100.00%  72 / 72 packs deleted
done

```

Looking through my logs, it looks as if previous prune operations took around 2 hours.  The operation I just ran took...maybe 20 minutes less?  It seems a mild improvement at best (also, looking into this, I find myself wishing that restic would print the total runtime of the operation when it exits).
