### ISSUE TITLE
Can't get backup working with shell script run via cron

### ISSUE THREAD

**Issue by jjarolim** [restic/restic#1601]
Hi!

Since i saw Alexanders talk on media.ccc.de i'm exited about restic.

Unfortunately i seem only to be able to get it running from bash - but every try to get it automated over crontab fails :/

I created a shell script which calls restic backup and restic check afterwards.

If i call the script manually via bash, everything runs fine.

If i call the script via crontab, restic outputs nothing and does nothing. The cron seems syntactically right and runs - but i only receive my own echo output and no output from restic at all.

Obviously, my lack of unix profiency let's me missing a key point here :(

## Output of `restic version`

restic 0.8.1
compiled with go1.9.2 on linux/amd64

## How did you run restic exactly?

shell script:
```

#!/bin/bash

echo "## Backup"

restic --password-file /etc/restic/credentials -r /media/backup-hdd backup /etc /home /opt /root /usr/local/bin /var/databases /var/subversion /media/diskstation/DigiCam /var/www

echo "## Check"

restic --password-file /etc/restic/credentials -r /media/backup-hdd check
```

crontab:

`0 0 * * * /usr/local/bin/backup | mail -s Backup my@email.address`

## What backend/server/service did you use to store the repository?

the repository lies on a mounted usb drive

## Expected behavior

I'd expect restic to do the backup and to receive the restic ouput in the mail

## Actual behavior

no backup, no output in email

## Steps to reproduce the behavior

mount a drive
create the shell script
run it from bash: works
run it via cron: don't work

## Do you have any idea what may have caused this?

lack of unix experience

## Do you have an idea how to solve the issue?

nope

## Did restic help you or made you happy in any way?

The software concept behind restic is very neat, backups are running lightning fast.
Couldn't be happier if i manage to get it running automatically ;-)

Best Regards from Salzburg, Austria!

**Comment by dimejo** [comment]
> crontab:
> ```
> 0 0 * * * /usr/local/bin/backup | mail -s Backup my@email.address
> ```
Is this the global crontab (`/etc/crontab`) or the personal crontab? You might be missing the username.


> Best Regards from Salzburg, Austria!

Greetings from Graz! :)

**Comment by jjarolim** [comment]
Hi!

Thanks for you help!

Today i looked on the topic with fresh eyes and discovered that the run context of cron doesn't seem to know the path variable of root - including /usr/local/bin. So cron couldn't find and start restic at all.

I've modified the bash script to 

```
#!/bin/bash

echo "## Backup"

/usr/local/bin/restic --password-file /etc/restic/credentials -r /media/backup-hdd backup /etc /home /opt /root /usr/local/bin /var/databases /var/subversion /media/diskstation/DigiCam /var/www

echo "## Check"

/usr/local/bin/restic --password-file /etc/restic/credentials -r /media/backup-hdd check
```

where /usr/local/bin/restic is a soft link to the current restic binary and
/etc/restic/credentials is a file containing only my repository password (chmod 400).

Now my restic automation runs like a "Glöckerl" ;-)

## Proposal

Since backup is a topic everybody needs - and automation is a core part of a neat backup - i propose that this topic could be a small, but valuable addition to the documentation?

Some real world, basic examples of backup scripts (*nix and windows) and how to get them to work would help us adepts out there to get a good backup too. Restic itself is _very_ easy to use - despite the complex concepts behind it. 

I myself struggled to get it running in the context of my OS even as i'm used to search and find information on the interwebs: A short paragraph with a sample would have helped tons.


Thanks again for the cool software and

Best regards from Salzburg!

- Johannes

**Comment by fd0** [comment]
Heh, nice that it worked out well for you. I'd accept a PR adding a bit of documentation. This has also been discussed in the forum.
