### ISSUE TITLE
Restore hangs/does nothing

### ISSUE THREAD

**Issue by nithin-bose** [restic/restic#1604]
## Output of `restic version`
restic 0.8.1
compiled with go1.9.2 on darwin/amd64

## How did you run restic exactly?

I created a backup from an external hard disk, restic backup showed it to be 214 GB. Tried restore from the back up to a new hard disk (empty) with the following command:
```
 restic -r ./my-disk restore latest --target /Volumes/My-Disk
``` 

## What backend/server/service did you use to store the repository?
Local

## Expected behavior
The restore command shows some output/error. Anything at all really. 

A method to check if the backup and restore are at parity with each other

## Actual behavior

The restore command has been running for hours. The disk usage for the new hard disk has been at 233 GB for some time now. Haven't seen any errors or output so far. Is there any way to know whats happening?? Not even sure if it hanged.

``ctrl + c`` says ``signal interrupt received, cleaning up``.  Reissuing the restore command does not seem to do anything, probably because the files already exist. I suppose stopping in between a restore and restarting the restore later behaves like a resume?? 

The disk usage does not seem to change either. Randomly checking the files found no issues. There are no duplicate files created either. Which is good. Is there a way to check if the backup and the restore are at parity?

## Steps to reproduce the behavior

Backup a large folder with significant size and restore it else where. 

## Do you have any idea what may have caused this?
The large backup/restore size

## Do you have an idea how to solve the issue?
Displaying something, maybe the file that is currently being restored or processed or just displaying what is happening should help the user a lot. Ideally, an ETA, displaying the progress so far in terms of GB of data restored versus the amount of data to be restored, just like in the back up process  would be great.

## Did restic help you or made you happy in any way?
Restic had the best backup process I have ever seen. It showed all the data I needed to monitor the process. Back up experience was really wonderful

**Comment by fd0** [comment]
Hey, thanks for the report. When the project was started, we concentrated on making the backup process as frictionless as possible, I think that worked out really well :)

So, we need to do that with the restore process also, there's a pull request in the making which adds concurrency, since right now the restore process is single-threaded and not very efficient.


In order to diagnose what's going on, can you maybe start the restore process again and then monitoring with `strace` what restic does?

```
# strace -f -p $(pgrep restic)
```

Is the directory you're restoring to (`/Volumes/My-Disk`) empty? Can you see that restic creates new files there?

**Comment by nithin-bose** [comment]
It did complete (exit) successfully after a few tries. I still have no idea what happened. None of the files seems to be corrupted. Is this a one off issue or has somebody else faced this as well, especially with large restores?

Like I said in the issue, the directory I was restoring to was empty, fills up to 233GB and hanged. Because of the large size and the restore time, I did not try to restore into an empty folder again.

I am kinda ok with the restore time, its the lack of status updates that got me lost. I did expect to find a `-v` or `--debug` tag to give me some (any) details about whats happening. 

Apart from this glitch, my experience was really great. I am sure this will be fixed as well. Great piece of software, keep up the good work!!

**Comment by fd0** [comment]
Thanks for the feedback!

**Comment by MazeChaZer** [comment]
I'm still having this problem, waiting > 2h without any output, on a backup with about ~10.000 snapshots and a total repository size of ~500GB.

**Comment by rawtaz** [comment]
@MazeChaZer Please provide relevant information about your configuration and how you run restic and the output you get.

**Comment by MichaelEischer** [comment]
@MazeChaZer Please test restic 0.10.0, which includes a much faster `restore` implementation.

**Comment by rawtaz** [comment]
Closing this for now as there hasn't been any feedback despite request for it. Feel free to re-open if relevant!
