### ISSUE TITLE
Using --limit-upload/download w. restic 0.8.1 and sftp backend does not work

### ISSUE THREAD

**Issue by martinseener** [restic/restic#1607]
## Output of `restic version`
restic 0.8.1
compiled with go1.9.2 on linux/amd64

## How did you run restic exactly?
restic -p restic_repo.pass -r sftp:uxxx@uxxx.your-storagebox.de:/ --limit-upload 2 backup /var/log

## What backend/server/service did you use to store the repository?
I'm using a Hetzner Storagebox with the SFTP backend (stored an ssh key there beforehand)

## Expected behavior
When using --limit-upload i expected that the upload speed capped at that rate (more or less).

## Actual behavior
I wanted to upload with very limited speed but it saturates my overall bandwith of (almost) 1Gbit/s (the output tells 78MB/s but this varied while testing with the --limit-x options. I also had output of 9xMiB/s. Using different --limit-upload (and -download) with the same values like "2" above or even "250" doesn't had any difference. It always used my full line speed.

## Do you have any idea what may have caused this?
A bug in the --limit-x methods? I'm unsure.

## Did restic help you or made you happy in any way?
I love restic by the way and already using it for other things where the bandwith cap is not used (this is the first project with limited bandwith caps for restic). Besides this "bug" restic works really great for me!

**Comment by fd0** [comment]
Hey, thanks for the report! Since 0.8.1 was released, we've fixed a few things with the limit, and I'm confident the issue is already resolved by #1511. Would you mind giving a beta build a try? You can find them here (or just build it yourself from master): https://beta.restic.net/?sort=time&order=desc

Please be aware that the displayed bandwidth is the "processed bandwidth", not the bandwidth at which data is sent to the backend... We've removed the output in the master branch because it was confusing to many users.

Please report back!

**Comment by martinseener** [comment]
I tried the latest beta today (from Feb 5th) and it seems that the --limit-upload now (more) works as intended. Using `200` means 200kb/s and i can see this in `iftop -B`. When trying `2000` i can see that it more or less floats around 2MB/s. But when using higher values like `20000` it does not go higher than about 3.3MB/s (3.3 Megabytes per second). The output looks like this for a file generated with /dev/urandom count=102400 bs=1024

`[0:30] 100.00%  100.000 MiB / 100.000 MiB  1 / 1 items  0 errors  ETA 0:00
duration: 0:30` 

But when NOT using any limits it's also stuck at about those 3.3MB/s, so i really think this is more a problem of the network or receiving sftp than restic itself. So i think we can close this one!

**Comment by martinseener** [comment]
Tested another Server and got faster there, so it seems in this case, the Hetzner Storage Box is under some load right now (because all customers share the network bandwith!) So my restic "bug" is fixed with the latest beta. Thanks for helping me, @fd0 !

**Comment by fd0** [comment]
Ok, that was easy :)

Thanks for the feedback!
