### ISSUE TITLE
--time not usable for backups from stdin

### ISSUE THREAD

**Issue by kaleng** [restic/restic#1608]
## Output of `restic version`
restic 0.8.1 (57dc605)
compiled with go1.9.2 on linux/amd64

## How did you run restic exactly?
cat backupfile | restic -r rest:http://backuphost/ backup --time "2011-10-15 17:45:37" --hostname "myhost" --stdin --stdin-filename backupfile

## Expected behavior
Restic creates a new snapshot with the given time, hostname and filename.

## Actual behavior
Restic creates a new snapshot with the given hostname and filename but timestamp of the execution of restic instead of the time given with --time

## Steps to reproduce the behavior
1. Create repository
1. create new backup, use --stdin and --time
1. list created snapshots
1. snapshot time is set to time of backup, not the time given by --time

## Do you have any idea what may have caused this?
time.Now() is used in https://github.com/restic/restic/blob/e17f65b23a425923fcfb679e76d5094452acbda6/internal/archiver/archive_reader.go#L31 which is called by readBackupFromStdin

## Do you have an idea how to solve the issue?
nope

## Did restic help you or made you happy in any way?
What? Are you kidding? Of course it did! Finally a nice and easy way to do backups. You're doing great work! Thank You!

**Comment by fd0** [comment]
Thanks for the report, I consider this a bug :)
