### ISSUE TITLE
discourse.restic.net, referenced in the issue template, does not exist

### ISSUE THREAD

**Issue by iluvcapra** [restic/restic#1609]
## Output of `restic version`

This is a project infrastructure issue.

## How did you run restic exactly?

`curl http://discourse.restic.net`

## Expected behavior

Connect to a web forum.

## Actual behavior

`curl: (6) Could not resolve host: discourse.restic.net`

## Do you have an idea how to solve the issue?

Update the issue template.

## Did restic help you or made you happy in any way?

Oh very much! I was going to ask a question about parity and redundancy data but came upon this issue...

**Comment by fd0** [comment]
Oh, thank you very much for pointing this out! We've used `discourse.restic.net` initially, but then switched to `forum.restic.net` quickly. Somehow, the old name ended up in the issue template and wasn't updated.

**Comment by iluvcapra** [comment]
Thanks for the info.
