### ISSUE TITLE
Define filter function semantic

### ISSUE THREAD

**Issue by fd0** [restic/restic#161]
It's not the same in restorer and archiver

**Comment by fw42** [comment]
What exactly do you mean by "semantic" here? Do you mean they should have the same function signature (some parameter types)? And what's the advantage of unifying that even? Or are you saying the return values are interpreted differently?

**Comment by fd0** [comment]
I have the impression that the return values for the filter functions mean different things. I'd like to specify the meaning of that explicitely for both functions. We'll need filter functions in other places in the future, so this should be done right so we can reuse it.
