### ISSUE TITLE
[RELEASE SCRIPTS] binaries don't ship chmod +x -ed

### ISSUE THREAD

**Issue by blaggacao** [restic/restic#1612]
```bash
$ docker run -ti busybox sh
/ # wget https://github.com/restic/restic/releases/download/v0.8.1/restic_0.8.1_linux_amd64.bz2
/ # bzip2 -d restic_0.8.1_linux_amd64.bz2 && mv restic_0.8.1_linux_amd64 /bin/restic
/ # /bin/restic
sh: /bin/restic: Permission denied
```

I know I can just chmod +x it, however that's not the point.

**The subtle logic, I claim:**

- It's intended to be an executable binary, 
- so it should be executable.

Obviously, unless I'm missing some limitation in bzip2 itself when it comes to preserving file permissions.

I quickly looked at the go build script, but actually could not identify the exact point where such chomd +x could be injected rightfully.

Fruehlingsputz :)

**Comment by fd0** [comment]
Thanks for taking the time to report this. I don't think this is an issue with restic.

HTTP does not have a concept of "executable" or even "permissions/mode bits" (in contrast to e.g. FTP), so `wget` creates a file with default permissions, usually 0644.  `bunzip2` will preserve the permissions, so the resulting file still has a mode of 0644.

Apart from wrapping the `restic` binary within a `tar` (which seems not worth the effort) I don't see a way how we could change that.

I'm therefore closing this issue for now, please add do add further comments!
