### ISSUE TITLE
[Discussion] restic on busybox docker

### ISSUE THREAD

**Issue by blaggacao** [restic/restic#1614]
Hi, I wanted to drop this into the discussion on the actual upstream repo...
I've started fiddling around with a tiny busybox restic container based on @Lobaro 's work.

https://github.com/xoes/restic-backup-docker

As I want to use an external scheduler, I find the following approach interesting:
- Keep the crond doing the scheduling of the backups (not the external scheduler)
- Put make pid=1 fail when the actual sync fails so that the scheduler is alerted that something's wrong. - I'm actually not sure how to achieve that...

As it is only intended to be a fully automatic sidekick, no fuse filesystem libraries are necesary...
However, what needs to be done, I guess is a more elegant log forwarding.

Actually, I liked the delegated approach from @Labaro very much, as it is made for humans, but keeping the logs just there is not so optimal neither...

**Comment by MatthewVance** [comment]
The Restic forum at https://forum.restic.net/ may be a better place to have a general discussion about this one. If you are looking for a log enhancement so the scheduler can be alerted if something is not working, I recommend bringing that up in the existing log enhancement feature request (https://github.com/restic/restic/issues/1455).

**Comment by blaggacao** [comment]
You're right... :+1:
