### ISSUE TITLE
Error loading tree: ciphertext verification failed / nonce is invalid

### ISSUE THREAD

**Issue by infernix** [restic/restic#1617]
## Output of `restic version`
restic 0.8.1
compiled with go1.8.3 on linux/amd64

## How did you run restic exactly?
```
export B2_ACCOUNT_ID=XXXXX
export B2_ACCOUNT_KEY=XXXXXX
export RESTIC_REPOSITORY="b2:spirit"
export RESTIC_PASSWORD='XXXXXX'
ionice -c2 nice -n19 restic backup --exclude-file  /root/resticstuff/excludelist  --exclude-caches /
```

## What backend/server/service did you use to store the repository?
Backblaze B2

## Expected behavior
N/A

## Actual behavior
```
password is correct
using parent snapshot 3c27f3e8
scan [/]
scanned 136336 directories, 1338801 files in 5:55
error loading tree: decrypting blob 5dfa561313e14aaa2cbcb0aa68a88ea552b244a33b7d615c39139dbf95b9f3d0 failed: ciphertext verification failed
error loading tree: decrypting blob 59468d2ef324d53a3a20cc5de09a735bfca1c6945ab58be9c4cc154f331f045e failed: ciphertext verification failed
error loading tree: decrypting blob c461ba880aa14bca96abafc395b7692b187277a1b46855174372b6c82bddce6e failed: ciphertext verification failed
error loading tree: decrypting blob 2328b63e39ec031cbc0eedadfe374d11d214a0e4d5904a61461cb54ff0ed5595 failed: ciphertext verification failed
error loading tree: decrypting blob b441e137bed15b72b1beca6380fe6e5bbf8de65423013dad693f48e1efbce245 failed: ciphertext verification failed
error loading tree: decrypting blob a3e9e610678880fe8727ce4ba0bfb33cea6a28d3ae25f5a08e5ff4016561c237 failed: ciphertext verification failed
error loading tree: decrypting blob fb6e4139fbe9c1110552c6e2ffab874170f1fd7fed1baa12dcd08c28259391ce failed: ciphertext verification failed
error loading tree: decrypting blob 41dd98673e64b41d1e55562d672f43260cfdf5710fc80200d9515b63e433dba9 failed: ciphertext verification failed
error loading tree: decrypting blob de5b664c8a9b569d4acf48dd2c92e595f292a8cdc71d282cdcf7218f5de57346 failed: ciphertext verification failed
error loading tree: decrypting blob d46eb2584d922a446a777eccba30f11c85bac60048d5f37dbd94f121f6d866ac failed: ciphertext verification failed
error loading tree: decrypting blob a420c85e1f10cd46d598ff0c055b18ce2f332a77ac66fd04dd54a5ab915dc8de failed: ciphertext verification failed
error loading tree: decrypting blob 76cb626111c8b5229d840cc38d4ad19cc183cd996e8adaad9225b5db85c626a0 failed: ciphertext verification failed
error loading tree: decrypting blob fefbbd3b8a1f66a194704176bca35170b425fea911ff8d9adb65455ee0e1bad7 failed: ciphertext verification failed
error loading tree: decrypting blob 5a44b78c494ec275352e188237164479d0ed1262ff7bd9eee502a0ba13fcc318 failed: ciphertext verification failed
error loading tree: decrypting blob 51c2295791901a61a67681dc3f2e7e3e60f8234895fbbb3a19d1c7a19209f3b5 failed: ciphertext verification failed
error loading tree: decrypting blob 49a532a41179b09e4224ce02af9395b07a0a9b0a52e0ff8796a0b1009037220a failed: nonce is invalid
error loading tree: decrypting blob bf4e224d47e1082c6c7a5660481b6cafcde2223ed2c42c18f5a0c6ec21de58d9 failed: ciphertext verification failed
error loading tree: decrypting blob 532e3d3e7c56b2a81a4a19709c649f87dbf5ff14b81e9857e381e8468147d898 failed: nonce is invalid
error loading tree: decrypting blob b426c7df1979aac35f8886e097f53af3514349c1d117f44c5feaad73ea305e08 failed: nonce is invalid
error loading tree: decrypting blob 7882ab35ce6061592acb4bac7323942f14a9a635fc268aa3bef3f4434280e896 failed: ciphertext verification failed
error loading tree: decrypting blob d1bc83af09d5d3973ada1974ee613b88c0627ae14bd8341652fe02ae874e7ab5 failed: ciphertext verification failed
error loading tree: decrypting blob 4df0f1dc644286b693e9c95ee9d87f3297efafb160aaf39901d71109d5496fba failed: ciphertext verification failed
error loading tree: decrypting blob 6393fb3eb55ee506293538d6ca23d499ba9983e0d6a381f30407442284e165cc failed: ciphertext verification failed
error loading tree: decrypting blob c57c57b9886fa955121837bb74b3f804ecacbabec47674b3996899ee0a634662 failed: ciphertext verification failed
warning for /var/lib/collectd/rrd/spirit.infernix.net/cpu-4/cpu-idle.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/cpu-4/cpu-interrupt.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/cpu-4/cpu-nice.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/cpu-7/cpu-system.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/cpu-7/cpu-user.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/cpu-7/cpu-wait.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/disk-dm-3/disk_io_time.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/interface-virbr3-nic/if_packets.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/interface-virbr4/if_dropped.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/nfs-v4server/nfs_procedure-create_session.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/nfs-v4server/nfs_procedure-delegpurge.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/nfs-v4server/nfs_procedure-delegreturn.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/smart-sdb/smart_attribute-available-reserved-space.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/smart-sdb/smart_attribute-end-to-end-error.rrd: file has changed
warning for /var/lib/collectd/rrd/spirit.infernix.net/smart-sdb/smart_attribute-endurance-remaining.rrd: file has changed
warning for /var/log/daemon.log: expected 53619283 bytes, saved 53619493 bytes items  0 errors  ETA 2:06
warning for /var/log/journal/33518f3ddb3ff9846852d3b4498f8997/user-1000.journal: file has changed
warning for /var/log/syslog: expected 13880640 bytes, saved 13881138 bytes5137 items  0 errors  ETA 1:21
[1:29:31] 100.00%  192.012 MiB/s  1007.127 GiB / 1007.103 GiB  1475138 / 1475137 items  0 errors  ETA 0:00
duration: 1:29:31, 192.00MiB/s
snapshot 85af8fde saved
```
## Steps to reproduce the behavior
Not sure

## Do you have any idea what may have caused this?
I had to do a restore of the entire filesystem (including restic cache dirs) from local backup media. Some of the data may not be recent or valid, including any caches.

I'm just trying to understand the failure mode here. Does it mean that the backed up data is unreadable/wrong/corrupted? Does it mean that the local cache indices need to be updated? The error is not very meaningful by itself.

## Do you have an idea how to solve the issue?
No

## Did restic help you or made you happy in any way?
1TB to B2 in a few days, then updates in 1.5hrs. So yes, very ;)

**Comment by rawtaz** [comment]
For reference, a similar discussion going on in parallel is [here](https://forum.restic.net/t/ciphertext-verification-failed-during-restore-restic-check-found-no-errors/455) and @fd0's reply to more or less what you're asking is [here](https://forum.restic.net/t/ciphertext-verification-failed-during-restore-restic-check-found-no-errors/455/13).

**Comment by infernix** [comment]
well, after all this, there are still about 20 `ciphertext verification failed` or `nonce is invalid` errors.

I suppose i have to do a `restic check --read-data` on a B2 repo to find out what packs are corrupted, but that's going to cost $20(!) for 1TB so I'm better off just creating a new bucket+repo and backing up to that one.

There really needs to be a better solution than reading all data back, it's not an acceptable solution where reading costs money.

**Comment by fd0** [comment]
Hey, thanks for the report. I'm trying to summarize what I understood:

 * You saved some data to B2 with restic
 * Something happened, and you had to restore your machine, including the restic cache dir
 * The next run of `restic backup` printed the error messages
 
Is that correct? How did you restore your machine? With restic?

We could indeed manually drill down on the data a bit, and I agree that restic needs to handle this kind of situation better. You could start by removing the cache, so it is re-filled from the backend (B2 in this case).

What happens is that during  backup, restic tries to read old metadata from the repo, and failed to decrypt the data because it was modified. The error message `nonce is invalid` means that the first part of the file only consists of zeroes, which is always invalid, so restic refuses decryption. For `backup` that's not an issue because restic will just re-upload metadata it could not decrypt earlier, so then at least the newly created snapshot does not reference any unreadable metadata.

But apart from improving restic and/or manually trying to find out what's going on here, I'm at loss on what restic could do (on a fundamental level). If you want to ensure that the data you saved to B2 is valid and unmodified, you need to read it from the backend. There's no way around it...

**Comment by infernix** [comment]
> - You saved some data to B2 with restic

Correct. More than once, too.

> - Something happened, and you had to restore your machine, including the restic cache dir

What happened is that the root FS got corrupted, so I restored everything from local backup (using backuppc locally, not restic).

> -The next run of restic backup printed the error messages

Correct.

> But apart from improving restic and/or manually trying to find out what's going on here, I'm at loss on what restic could do (on a fundamental level). If you want to ensure that the data you saved to B2 is valid and unmodified, you need to read it from the backend. There's no way around it...

But does it need to read _everything_? Can't it intelligently decide to just read what seems to be corrupted/wrong?

Or otherwise print out what files are connected to the data that failed to decrypt? Let's suppose it's some logfiles in /var/log; I could care less about those, and would then not have to worry about the inability to restore it.

**Comment by fd0** [comment]
> But does it need to read everything? Can't it intelligently decide to just read what seems to be corrupted/wrong?

How would it decide that? restic could look at the file size and check if it roughly matches the expected file size, so it could maybe detect truncated files, but e.g. bit-rot or files corrupted during transfer or while being stored at BackBlaze won't be detected.

After all, you can really only make sure that the right data is returned by the service when you regularly read it back.

Maybe we're talking about different things here: I was talking about regularly checking that the data in the repo is unmodified and can be read and decrypted.

Were you maybe referring to finding out which files are affected by data corruption in the repo? That is way easier, it is just not implemented yet...

**Comment by infernix** [comment]
> Were you maybe referring to finding out which files are affected by data corruption in the repo, once restic detected that corruption? That is way easier, it is just not implemented yet...

Exactly that. You say:

> What happens is that during backup, restic tries to read old metadata from the repo, and failed to decrypt the data because it was modified. 

I understand it can't detect bit-rot etc without rereading everything, but it detects a problem when it reports these messages. If the user knows what part of the data is affected, they can then decide what to do next: spend the $20 doing a check with re-read, or live with the fact that the list of files affected by it cannot be restored. 

So if it can print out affected files, the user can take appropriate action. Sort of like a verify run on old tape backup :)

**Comment by fd0** [comment]
Ah, now I understand! thanks for the clarification. The `check` command would be a good idea to print such information.

**Comment by MichaelEischer** [comment]
For reference if someone with a similar problem finds this issue: Use `restic find --tree ids-of-trees-that-failed-to-load...` to find out which snapshots and folders are affected. Then you can either `forget` the snapshots, delete the damaged pack files (pass `--show-pack-id` to `find`), then `rebuild-index`, run backup again and then remove any remaining damaged snapshots, or wait until repair functionality for snapshots is added some time in the future.

**Comment by MichaelEischer** [comment]
Restic by now can repair pack files and snapshots, see https://restic.readthedocs.io/en/stable/077_troubleshooting.html . Providing information on damaged snapshots is best handled via https://github.com/restic/restic/issues/720 .
