### ISSUE TITLE
unable to add password

### ISSUE THREAD

**Issue by jgranduel** [restic/restic#1618]
## Output of `restic version`
restic 0.8.1
compiled with go1.9.2 on windows/amd64

## How did you run restic exactly?
Powershell> restic -r C:/path/to/repo key add

## What backend/server/service did you use to store the repository?
test on local drives

## Expected behavior
add new password

## Actual behavior
```
enter password for repository:
password is correct
read /dev/stdin: Descriptor not valid
ReadFull
main.readPassword
        src/github.com/restic/restic/cmd/restic/global.go:249
main.ReadPassword
        src/github.com/restic/restic/cmd/restic/global.go:285
main.ReadPasswordTwice
        src/github.com/restic/restic/cmd/restic/global.go:302
main.getNewPassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:68
main.addKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:74
main.runKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:155
main.glob..func10
        src/github.com/restic/restic/cmd/restic/cmd_key.go:22
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:195
runtime.goexit
        /usr/local/go/src/runtime/asm_386.s:1635
unable to read password
main.ReadPassword
        src/github.com/restic/restic/cmd/restic/global.go:289
main.ReadPasswordTwice
        src/github.com/restic/restic/cmd/restic/global.go:302
main.getNewPassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:68
main.addKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:74
main.runKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:155
main.glob..func10
        src/github.com/restic/restic/cmd/restic/cmd_key.go:22
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:195
runtime.goexit
        /usr/local/go/src/runtime/asm_386.s:1635
```

## Steps to reproduce the behavior
issue with restic-0.8.1, but works with restic-0.8.0

## Do you have any idea what may have caused this?
no

## Do you have an idea how to solve the issue?
no

## Did restic help you or made you happy in any way?
just testing.

**Comment by rawtaz** [comment]
Thanks for a good report. May I ask if you compiled both 0.8.0 and 0.8.1 yourself? If yes, did you check out the release tags or some other commit? What command did you use to compile them?

**Comment by jgranduel** [comment]
Hi, 

I've just downloaded the versions from [releases](https://github.com/restic/restic/releases), tested with x86 and x64 versions with not change.

**Comment by jgranduel** [comment]
Well, the issue is not well described.
I replaced the downloaded restic-0.8.1 by the compiled restic to and run into the same problem!?
In one case, I had registered the RESTIC_PASSWORD as an environment variable and then removed it. As soon as I removed it, the problem reoccured.
When there's no RESTIC_PASSWORD, we're prompted for the repo password, and then it crashes.
I reproduced it hereafter:
````powershell
PS>$env:RESTIC_PASSWORD='pass'
PS>restic -r path/to/repo key add
password is correct
enter password for new key:
enter password again:
saved new key as...
PS>$env:RESTIC_PASSWORD=$null
PS>restic -r path/to/repo key add
enter password for repository:
password is correct
read /dev/stdin: Descriptor not valid
ReadFull
main.readPassword[...]
````
Sorry if this feature was documented somewhere and that I hadn't seen it.
Thanks

**Comment by fd0** [comment]
Thanks for the report!

It is related to the issue, it looks like asking for a new password is broken on Windows when using PowerShell. The workaround is passing the password to restic via the environment variable.

Somebody with a Windows development environment and knowledge of Go is needed to help debugging this.

**Comment by gituser30** [comment]
I’m new to github and reporting issues, so I hope this can help.

I’m also getting the same issue as originally described, however I can also add the following:

* While testing with the latest version of the restic_0.8.2_windows_amd64 (from the releases page) I have seen the issue on both Windows 7 and Windows 2016 server

* The issue also does not seem to be restricted to PowerShell environment, I have been able to duplicate the error on both these platforms in the Windows Command Line

* Downgrading to restic_0.8.0_windows_amd64 the issue goes away. I am able to add keys in either PowerShell or Command line environments

One final thing, all my testing involved “one liners” with no environmental variables set, and being prompted for password.

**Comment by peterbladen** [comment]
I used  the following without powershell and still errors :-

restic 0.8.3
compiled with go1.10 on windows/amd64

**Comment by cd1188** [comment]
hi
i had the same problem and no enviroment was set with the binary 0.8.3 download

but after compiling from the current source, i have no problems now
so i think it is fixed now?

restic 0.8.3 (v0.8.3-221-g26757ae) compiled with go1.10.1 on windows/amd64

**Comment by fd0** [comment]
Can someone please confirm what's the current status here? Is this still an issue? I don't have a Windows machine at hand...

**Comment by 12delta** [comment]
The downloaded version has still this issue:

```
> restic version
restic 0.8.3
compiled with go1.10 on windows/amd64
> restic key add -r data
enter password for repository:
password is correct
read /dev/stdin: Descriptor not valid
ReadFull
main.readPassword
        src/github.com/restic/restic/cmd/restic/global.go:251
main.ReadPassword
        src/github.com/restic/restic/cmd/restic/global.go:287
main.ReadPasswordTwice
        src/github.com/restic/restic/cmd/restic/global.go:304
main.getNewPassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:72
main.addKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:78
...
```

SHA1 hash of `restic.exe`: CAD7174FC452429705B2468ABCFB5C2D07E75FF6

Is it maybe a bug fix in the Go toolchain? *cd1188* is using Go 1.10.1. Is the Go version of the download binary 1.10.0?

**Comment by cd1188** [comment]
download 0.8.3 as binary 64bit has this error by me in cmd and powershell on windows 10
(compiled with go1.10 on windows/amd64)
SHA1 CAD7174FC452429705B2468ABCFB5C2D07E75FF6

`read /dev/stdin: Descriptor not valid` -> is that not a linux path or is that also valid in windows?

compiling from source has no error... 
I do not know more.. sorry

**Comment by cd1188** [comment]
Hello
i downloaded now the old 0.8.3 source from the homepage and compiled it with the new go-compiler 1.10.1 and the old error is present...
so i can say this error is in the old source-code and not in the go-toolchain

i used this old-src
restic-0.8.3.tar.gz
SHA1 4617F0FAC9CC804C46465A17F569ED237566472A

C:\restic_src\restic-0.8.3>restic version
restic 0.8.3
compiled with go1.10.1 on windows/amd64

C:\restic_src\restic-0.8.3>restic -r C:\repo key add
enter password for repository:
password is correct
read /dev/stdin: Das Handle ist ungültig.
ReadFull
main.readPassword
        src/github.com/restic/restic/cmd/restic/global.go:251
main.ReadPassword
        src/github.com/restic/restic/cmd/restic/global.go:287
main.ReadPasswordTwice
        src/github.com/restic/restic/cmd/restic/global.go:304
main.getNewPassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:72
main.addKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:78
main.runKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:159
main.glob..func11
        src/github.com/restic/restic/cmd/restic/cmd_key.go:22
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        C:/Users/XXXX/AppData/Local/Temp/restic-build-134152615/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        C:/Users/XXXX/AppData/Local/Temp/restic-build-134152615/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        C:/Users/XXXX/AppData/Local/Temp/restic-build-134152615/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        C:/Go/src/runtime/proc.go:198
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2361
unable to read password
main.ReadPassword
        src/github.com/restic/restic/cmd/restic/global.go:291
main.ReadPasswordTwice
        src/github.com/restic/restic/cmd/restic/global.go:304
main.getNewPassword
        src/github.com/restic/restic/cmd/restic/cmd_key.go:72
main.addKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:78
main.runKey
        src/github.com/restic/restic/cmd/restic/cmd_key.go:159
main.glob..func11
        src/github.com/restic/restic/cmd/restic/cmd_key.go:22
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        C:/Users/XXXX/AppData/Local/Temp/restic-build-134152615/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        C:/Users/XXXX/AppData/Local/Temp/restic-build-134152615/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        C:/Users/XXXX/AppData/Local/Temp/restic-build-134152615/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        C:/Go/src/runtime/proc.go:198
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2361

C:\restic_src\restic-0.8.3>

**Comment by fd0** [comment]
Ok, thanks for the confirmation. We can then close this issue, as it is not present in the code in the master branch any more (we're using a library for reading the password from the user, and that has been updated since 0.8.3, I think this solved it).

I'm closing this issue for now, please feel free to add further comments. Thanks!
