### ISSUE TITLE
Recovery duration S3 backend

### ISSUE THREAD

**Issue by zout** [restic/restic#1619]
## Output of `restic version`
```
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```
## How did you run restic exactly?
Using a S3 bucket to store backups encrypted offsite.

## What backend/server/service did you use to store the repository?
A Amazon S3 bucket.

## Expected behavior
I expected that the recovery be somewhat near the speed of backing up.

## Actual behavior
The backup I make every day is about 6 GB in size and has 400k files+. While making the initial backup (including transfer to S3) takes 112 seconds. A recovery takes 3 hours and 10 minutes. Please note that I used a server with SSD's, a 10 Gbit internet connection and a 8-core modern Xeon CPU.

I get much better results when I copy the entire S3 bucket over with `mc` (minio client) and use that as a local repository. Transfer takes about 2 minutes, and recovery 5 minutes.

## Steps to reproduce the behavior
Backup a few gigabytes to S3 bucket and restore them on the same sort of device.

## Do you have any idea what may have caused this?
I see almost no load, and almost no network traffic spikes. I guess it's due to a lack of threading. Also I see a lot of WAIT state connections in netstat.

## Do you have an idea how to solve the issue?
Invest some time in making it possible to use more connections and more parallelisation.

Maybe merge in this: https://github.com/restic/restic/pull/1371 ?

## Did restic help you or made you happy in any way?
Backup speeds are amazing, recovery is also very nice when using a local repo.

**Comment by fd0** [comment]
Thanks for the report, it's a known issue as you've already discovered. We decided to first optimize backup, which is already very fast, now we still need to do that with prune. I'll close this issue for now, please feel free to add further comments, thanks!
