### ISSUE TITLE
number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by rinzes** [restic/restic#1621]
restic 0.8.0
compiled with go1.9 on linux/amd64

I got the above when I ran restic prune

**Comment by rawtaz** [comment]
Next time, *please* use the issue template. It's great to have issues reported in the same format, and it's not uncommon that issue subject lines change, and then we have to move your message around, etc. It's just messy, please use the templates ;)

**Comment by rinzes** [comment]
Will do...
Additional Info: this was performed on Backblaze

**Comment by rinzes** [comment]
I upgraded to version 0.82 and got the following:

restic prune /home/ldevries/Documents/
password is correct
counting files in repo
building new index for repo
[0:28] 100.00%  106 / 106 packs
repository contains 106 packs (2585 blobs) with 349.974 MiB
processed 2585 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 22 snapshots
[0:01] 100.00%  22 / 22 snapshots
number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

**Comment by fd0** [comment]
Hm, odd. What happened here is that restic found data that is referenced by some snapshots, but the data is not present in the repo. Can you try running `restic rebuild-index` and try again?

**Comment by rinzes** [comment]
I tried the above with no luck. I wound up deleting/init a new bucket. You can close this
