### ISSUE TITLE
Restic retrying forever because of an error?

### ISSUE THREAD

**Issue by larsks** [restic/restic#1628]
## Output of `restic version`

restic 0.8.1

## How did you run restic exactly?

    RESTIC_REPOSITORY=/run/media/lars/backups/home
    restic backup --exclude-if-present=.nobackup \
      --exclude-file exclude --tag volatile /home/lars

## What backend/server/service did you use to store the repository?

Local filesystem

## Actual behavior

Restic encountered an error during the backup run on 2/13/2018:

> Feb 13 00:07:52 [...] Load(<data/3d91522b15>, 0, 0) returned error, retrying after 498.605701ms: open /run/media/lars/backup/backups/home/data/3d/3d91522b158bef28c84b5f1a71b958cddef859199cd826cf60e14f447fed2ac5: no such file or directory

It then proceeded to issue essentially the same error message for the same file 3480 times, with the final message showing up several hours later:

> Feb 13 03:34:51 [...] Load(<data/3d91522b15>, 1863, 3980974) returned error, retrying after 22.262323134s: open /run/media/lars/backup/backups/home/data/3d/3d91522b158bef28c84b5f1a71b958cddef859199cd826cf60e14f447fed2ac5: no such file or directory

After which is started in on similar errors for other files, with the final error message occurring this morning when I force killed restic:

> Feb 18 09:08:57 [...] Load(<data/4d697828c4>, 45, 3839904) returned error, retrying after 17.677804896s: open /run/media/lars/backup/backups/home/data/4d/4d697828c4d0af6eb3c25b5ff9a58c49584281ad6bbea31c30a00a1ac12c0b18: no such file or directory

During the intervening 464465 seconds, no other backs using this backend could proceed.

Something seems broken here.  It's a local filesystem: if the file is missing the first time, it's still going to be missing the 4000th time as well.

This seems like excessive effort for a local filesystem: if the file is missing, it's gone.  It's never coming back.

**Comment by fd0** [comment]
Hey, thanks for your report! I think this is a bug, we need to handle this corner case a lot better.

What happens here is restic tries to access part of a file (which does not exist), so it is retried after a while for several times. Ultimately, the operation fails and returns an error. Then, the next part of exactly the same file is accessed, is retried again, fails, and so on. This sums up to quite a lot of time in your case...

In general, I think it's valuable to also retry requests for the local (and sftp) backends. Many people seem to use `fuse` based file systems to store the restic repo somewhere else, and this may well be backed by a cloud service in the backend that we don't know about. Not handling local/sftp as a special case also means less code.

So, we need to fix this bug, e.g. by remembering which files ultimately failed and only try once in this case.

I'm curios: Which restic operation did you run when the errors occurred? How did you get into the situation that a local file is missing?

**Comment by larsks** [comment]
> I'm curios: Which restic operation did you run when the errors occurred?

This was just a `restic backup ...`.

> How did you get into the situation that a local file is missing?

I have no idea! My best guess would be media error, maybe?  Although subsequently running "restic check" against the repository didn't show any problems (and last night's backup run completed without any errors).

**Comment by fd0** [comment]
Huh, odd. Files usually don't vanish into thin air from any file system, there should at least be errors in the kernel log... And restic will only make a note in the index file once it has successfully written the file (and called `fsync()` on the file descriptor before closing).

**Comment by larsks** [comment]
Yeah, it's weird. There are no kernel errors for the relevant disk.  I'm not really sure what's behind this.

**Comment by fd0** [comment]
Odd, indeed. It could also be a bug in restic, but I haven't heard that particular issue recently, especially not with the local backend. But of course I cannot rule out a but here :)

Anything else that was unusual?

**Comment by AlBundy33** [comment]
maybe an antivirus-scanner moved the file to quarantaine? 🤔

**Comment by larsks** [comment]
I'm going to close this issue since I'm no longer experiencing it and we never were able to pinpoint a cause.
