### ISSUE TITLE
compartmentalization

### ISSUE THREAD

**Issue by jirib** [restic/restic#1629]
backup often run as root but this priviledge is too open - although linux provides capabilities to limit that.

could you make your code to use compartmentalization so a part of restic reading filesystem under root priviledge could be "restricted" via OS dependent features (eg. OpenBSD pledge) to just read the filesystem and other part of restic (under less priviledge for example) would accept the data and write them to repository?

**Comment by fd0** [comment]
Thanks for the suggestion. You can already run restic as a non-root user, by restricting its abilities. We've added a description in the manual recently on how to do that on Linux: https://restic.readthedocs.io/en/latest/080_examples.html#backing-up-your-system-without-running-restic-as-root

For backup, just the `cap_dac_read_search` capability is needed.

If you want compartmentalization, you could run an `sftp` server locally, and specify the command with the `-o sftp.command="/usr/lib/ssh/sftp-server"` command. This way, you have two different processes.

Further compartmentalization is IMHO not needed.

So, I'm going to close this issue for now as what you're describing is already possible with the current code. Please feel free to add further comments. Thanks!

**Comment by jirib** [comment]
Well,

I'm not specialist but my concern was:

- after write mode to destination repo is done, reading files on filesystem don't need any write mode, thus
   restic is "save" not to mess with filesystem when doing traversal of filesystem if there would be any bug and
   this would cause the restic would be able to create new files
- "server mode" of restic, ie. one which writes data to repo would not need any read of other filesystem
   except its own destination (could chroot) or just open network socket

Thus, IMO in ideal world restic while doing backup (ie. reading files and passing it to part for write) would spawn "server part" (responsible for writing data) which would either open network socket and local directory and chroot to them, this part would try to descrease its priviledges, main part would switch to just "client" mode (no writing to filesystem or network while restricting its abilities) and would pass data to server part. One could investigate how OpenSSH is done where multiple parts communicate with each other.
