### ISSUE TITLE
Progress is inaccurate when files are added/removed during backup

### ISSUE THREAD

**Issue by minusf** [restic/restic#1630]
## Output of `restic version`

```
restic 0.8.2
compiled with go1.10 on darwin/amd64
```

## How did you run restic exactly?

```
$ restic backup -r /Volumes/backup/restic --exclude-caches ~
```

## What backend/server/service did you use to store the repository?

local backup

## Expected behavior

complete to reach 100%

## Actual behavior

```
scanned 76950 directories, 344828 files in 0:23
[20:06] 99.96%  10.066 GiB / 10.071 GiB  421780 / 421778 items  0 errors  ETA 0:00
duration: 20:06
```

## Steps to reproduce the behavior

1. start backup
2. while big backup operation running, add/delete files

## Do you have any idea what may have caused this?

so i think restic simply gets to the end of the list (obtained at scan time) of files to process.  some files were added, some removed, so the total number of items has changed.

## Do you have an idea how to solve the issue?

tbh, i dont think this is a huge issue and i am not sure what the fix could be :}

maybe some notes about the files that disappeared after scanning?
`borgbackup` prints error lines about those.

## Did restic help you or made you happy in any way?

it's much quicker than `borgbackup`! :}

**Comment by richard-scott** [comment]
You are lucky, since 0.8.2 I've lost my status updates and only get this:

```
[0:45] 4781 directories, 33095 files, 434.231 MiB
scanned 4781 directories, 33095 files in 0:45
```

and nothing else. If I enable debugging I can see more info and files getting uploaded to B2 etc.

**Comment by fd0** [comment]
Thanks for the report, we'll come to such details eventually.

**Comment by MichaelEischer** [comment]
It would probably be possible to let the `backup` command pretend that it reached 100% by adjusting the expected backup size in retrospect. But that feels like unnecessary complexity without much of a benefit. So I'm closing this issue for now.
