### ISSUE TITLE
Documentation for Telekom S3 Object Store needed

### ISSUE THREAD

**Issue by hagenbauer** [restic/restic#1642]
Telekom is providing in a S3 compatible Object Storage Service (OBS). Looking for somebody with more AWS Skills to add necessary steps to the documentation. 
https://cloud.telekom.de/infrastruktur/open-telekom-cloud/spezifikationen/object-storage-service/

**Comment by fd0** [comment]
Hm, what exactly is needed here? As far as I understood it, you can get access credentials from the management console and start using them with restic's s3 backend. It'd be nice if someone can confirm this, though.

**Comment by hagenbauer** [comment]
yes. its probably only documentation. I tried to use your perfect tutorial for Amazon for the Telekom user interface but there are some differences. I got stuck where I needed to apply bucket policies due to my lack of S3 know how. I am happy to work with somebody to adapt your tutorial for a "Telekom S3" Tutorial. 

I assume that getting closer to the DSGVO Date in May people might switch from a American cloud provider for backup to a TÜV Verified provider (yes and I know there is no technical reason for this)

**Comment by fd0** [comment]
Hm, I doubt that the service will provide something similar to AWS S3 bucket policies, but somebody else knows...

**Comment by cgroschupp** [comment]
I already use the OBS from the OTC (Open Telekom Cloud) and had no problems with the aws documentation.

@hagenbauer what is your current problem?

**Comment by fd0** [comment]
@cgroschupp thanks for the confirmation, I'll close this issue for now.

If someone wants to add additional documentation, I'd be willing to merge a PR, but in general I think it's documented well enough. Thanks!

**Comment by hagenbauer** [comment]
@cgroschupp currently I have troubles finding any documentation how to create a bucket on the telekom cloud. Do you have a link to start with
