### ISSUE TITLE
File size totals don't add up correctly.

### ISSUE THREAD

**Issue by richard-scott** [restic/restic#1644]
## Output of `restic version`

```
debug enabled
restic 0.8.3 (21f67a0)
compiled with go1.10 on linux/arm
```

## How did you run restic exactly?

```
restic --cleanup-cache --option b2.connections=9 backup --exclude-caches --exclude-file=/etc/restic/exclude.list --files-from=/etc/restic/include.list
```

## What backend/server/service did you use to store the repository?

B2

## Expected behavior

I've already backed up 225GB of data, and I added another folder (via the include file) of 320GB.
Restic now tells me that I am backing up 645GB. That's a 100GB over estimate.

`scanned 15738 directories, 97900 files in 0:29
[4:05] 0.09%  565.289 MiB / 644.701 GiB  12 / 113638 items  0 errors  ETA 79:24:38`

My Disk usage is as follows:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/md127      927G  555G  367G  61% /data
```

## Actual behavior

Ideally the totals should be accurate.

I have also noticed that this happens at other times when using the `--one-file-system` option as at that time I wanted to try and find a solution to the lack of a full path in the snapshot.

## Steps to reproduce the behavior

Just run a backup with lots of data, you'll see that the totals may not add up.

## Do you have any idea what may have caused this?

Nope, on the off chance, perhaps its something to do with running restic against files on BTRFS?

## Do you have an idea how to solve the issue?

No.

## Did restic help you or made you happy in any way?

Restic makes me happy as I only have to upload GB's of data once, and I don't need to keep uploading full snapshots each week/month. Saves me hours of time.

**Comment by fd0** [comment]
The number of bytes restic uses in the progress display is the sum of the size of all files and can be quite different (in both directions) from what the file system reports. On the one hand, sparse files (which aren't handled specially by restic right now) make the numbers reported by restic larger, on the other hand having many many small files of just a few bytes when on disc each file occupies a 512 byte or even 4k block may make the numbers smaller.

Other file system features such as built-in deduplication will also lead to different numbers.

In your case I suspect that you may have docker installed, which uses a 100GiB sparse file somewhere in `/var`. You can check by comparing `du` with and without the `--apparent-size` option (which is what restic roughly uses).

What's displayed by restic is also the number of bytes "processed", which either means "read" (for new files) or "check if modified and use the old data" if the file has been saved before.

I'm closing this

**Comment by richard-scott** [comment]
None of my files are under 1MB as they are mostly photos, music, or binary exe files downloaded from the web.

```
 du -sh --apparent-size /etc/restic /data/Documents /data/Downloads /data/Server /data/Music /data/Pictures /data/Videos /root /usr/local/bin /usr/local/sbin
4.2K    /etc/restic
1.5K    /data/Documents
421G    /data/Downloads
381M    /data/Server
87G     /data/Music
122G    /data/Pictures
16G     /data/Videos
161M    /root
15K     /usr/local/bin
7.8K    /usr/local/sbin
```

/data/Downloads was the last folder to be added to the include list, and restic tells me that the 412GB of files on disk equals almost 645GB of files to process:

```
scanned 15738 directories, 97900 files in 0:52
[13:08] 0.21%  1.361 GiB / 644.701 GiB  12 / 113638 items  0 errors  ETA 103:27:26
```

232GB is quite a big difference? There aren't that may files in that folder either:
```
$ find /data/Downloads/ | wc -l
32973
```

**Comment by rawtaz** [comment]
Counting only the GBs in your `du` output gives 421+87+122+16 = 646, which is quite close to restic's 644 GiB, so that part seems right to me, assuming the output from restic that you included is for all those folders. What's the complete command that produced that output (please always include that)?

If for some reason the restic output is from all those folders that could explain the larger count of files as well.

**Comment by fd0** [comment]
Thanks for the feedback. I think @rawtaz is right, the numbers add up quite well. I'm not sure what's happening here, and why the file system reports only 555GiB used. The filesystem (btrfs) also supports built-in deduplication, https://btrfs.wiki.kernel.org/index.php/Deduplication, maybe it's that?
