### ISSUE TITLE
Update OpenSUSE package

### ISSUE THREAD

**Issue by rawtaz** [restic/restic#1645]
@cyphar Are you still able to maintain the OpenSUSE package for restic? There's been quite a lot of fixes since 0.8.1 :) Most current is 0.8.3 which has e.g. solved some issues with B2.

**Comment by cyphar** [comment]
Yes. Just in future, you can leave a comment on the OBS project (Archiving/restic) rather than opening an issue on the upstream tracker in GitHub -- since upstream folks usually don't like to be bothered by distro-specific issues.

**Comment by rawtaz** [comment]
@cyphar Very nice, thanks. Regarding OBS, can you tell me where on that site I can leave a comment without having to register an account just to ping you (or the other maintainer) about the package needing an update?

**Comment by cyphar** [comment]
Ah, sorry, I assumed you had an OBS account. At the moment I don't believe you can comment without creating an account. I am setting up an automated job to alert me when `restic` is updated so I can push it to openSUSE as soon as possible.

**Comment by rawtaz** [comment]
Maybe one day I will!

Cool, that's even better. Thanks a lot for your efforts in making restic easily available, I was very happy to see there was a package for it in OpenSUSE when I did a random search for it :)

Don't hesitate to let us know if there's anything you need to make your work on that part easy/easier.

**Comment by cyphar** [comment]
https://build.opensuse.org/request/show/581452 is the Factory SR. Since it's not a core project, it should be merged soon and out in the next few snapshots.

**Comment by rawtaz** [comment]
Awesome, thanks again @cyphar!
