### ISSUE TITLE
0.8.3 suddenly giving "Fatal: unable to create lock in backend: load <lock/09517dea1e>: invalid data returned"

### ISSUE THREAD

**Issue by lpar** [restic/restic#1652]
## Output of `restic version`

    restic 0.8.3
    compiled with go1.10 on linux/amd64

## How did you run restic exactly?

    restic prune

## What backend/server/service did you use to store the repository?

Filesystem.

## Expected behavior

Restic prunes the data.

## Actual behavior

    password is correct
    Fatal: unable to create lock in backend: load <lock/09517dea1e>: invalid data returned

## Steps to reproduce the behavior

Run any command.

## Do you have any idea what may have caused this?

None at all. I just upgraded to restic 0.8.3 after previously using 0.7.1, and my previously valid backups no longer work at all.

## Do you have an idea how to solve the issue?

None at all. `restic migrate` doesn't work either.

**Comment by lpar** [comment]
Downloading 0.8.2 and trying that, it seems to retry and eventually succeed:

```
> ~/Downloads/restic_0.8.2_linux_amd64 check
password is correct
create exclusive lock for repository
List(lock) returned error, retrying after 702.716398ms: load <lock/09517dea1e>: invalid data returned
List(lock) returned error, retrying after 612.589808ms: load <lock/e31b905e19>: invalid data returned
List(lock) returned error, retrying after 437.279766ms: load <lock/09517dea1e>: invalid data returned
List(lock) returned error, retrying after 778.334438ms: load <lock/e31b905e19>: invalid data returned
load indexes
check all packs
check snapshots, trees and blobs
```

**Comment by fd0** [comment]
Hey, thanks for reporting this issue! Is there any way I can reproduce it? Can you please paste the output of `sha256sum /path/to/repo/locks/*`?

**Comment by lpar** [comment]
```
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  /run/media/meta/backup/restic/locks/09517dea1ef9f3954931f6710ce857862b642ed3fee8c08f05cb4d3b51329920
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  /run/media/meta/backup/restic/locks/e31b905e19e0a76f50c578943d72ff8d5685b4c921dbf2feb9ed9a6e4b3985c7
```

Here's `ls -la`:

```
-rw-------. 1 meta meta 0 2017-08-11 21:40 /run/media/meta/backup/restic/locks/09517dea1ef9f3954931f6710ce857862b642ed3fee8c08f05cb4d3b51329920
-rw-------. 1 meta meta 0 2017-08-11 18:11 /run/media/meta/backup/restic/locks/e31b905e19e0a76f50c578943d72ff8d5685b4c921dbf2feb9ed9a6e4b3985c7
```

**Comment by fd0** [comment]
Heh, interesting. Was your disc full in August 2017? ;)

I can reproduce the issue, working on a fix. As a short-term fix, just delete all the old files in `locks/`, then you're fine.

**Comment by lpar** [comment]
Yes, my disk did fill up at one point, that sounds about the right timeframe.

**Comment by Mebus** [comment]
Same problem here, disk full, too... I should mess with Icinga a bit more....

**Comment by lpar** [comment]
Confirmed that removing the lock files fixes it.

**Comment by fd0** [comment]
Awesome, thanks for the quick feedback! It'll be resolved in https://github.com/restic/restic/pull/1653
