### ISSUE TITLE
filter for json output

### ISSUE THREAD

**Issue by unclesamwk** [restic/restic#1654]
Hey,

an nice option will be an filter for output.

Example: I need only short_id 
```
restic -r path snapshots --json --filter=ID
```
greetings 
Sam

**Comment by fd0** [comment]
Thanks fThanks for the suggestion. I don't think it's valuable to implement this in restic, there are several command-line programs which already provide this option, [jq](https://stedolan.github.io/jq/) is one of them:

```text
$ restic snapshots --json | jq -r '.[].id'
[...]
af2bfe2b72bc533329cb302be1c45eb630050c6e92d5ddbdc2e197a25c7401c1
191a9198e65031631217c8af81d35a2edc8193325cb00544754fa8c6c22a59ab
b737d44d132036336213c3c936da8fa096373d71f41de69086400b0f4fa26b67
[...]
```

I'm therefore closing this issue. Please feel free to add further commements! Thanks!
