### ISSUE TITLE
Add a manpage for the repository layout

### ISSUE THREAD

**Issue by mathstuf** [restic/restic#1655]
It'd be nice to have manpage format documentation for the repository layout (basically the [Design](https://restic.readthedocs.io/en/stable/100_references.html#design) page) into `restic(5)` or `restic(7)`.

## Do you have an idea how to solve the issue?

Converting the existing docs to man.

## Did restic help you or made you happy in any way?

A wonderful replacement for `obnam`. And the performance is great.

**Comment by fd0** [comment]
Nice idea actually, thanks for the report. At the moment, we let Cobra (the Go library we're using for the CLI) generate the man pages. We need to check how to add data to it.

So, I'll leave this open for now. Anyone reading this: Ping me if you'd like to work on it.

**Comment by j6s** [comment]
@fd0 Ping. I have some capacity at the moment and am looking for something to contribute to restic.

**Comment by MichaelEischer** [comment]
Closing as this issue is probably more work than it is worth: to avoid confusion there must only be a _single_ source of truth for the repository format. This means we'd need an automatic documentation to man page conversion.
