### ISSUE TITLE
sync two folder , is it possible?

### ISSUE THREAD

**Issue by fg-dev** [restic/restic#1664]
I have two folder that need to be in sync, one at home and the other at work

i want to use restic to create a buck up repository in an external hard drive  from one folder and restore it to the other folder: like this

               
 folder1   <----------> restic repo  <----------> folder2
             
the problem is when  restoring,  restic does note delete files deleted in the first folder
                

thanks in advance

**Comment by rawtaz** [comment]
Restic is made for backing up, not syncing, even though they're related. What you encounter is one of the differences.

For syncing, I'm thinking you're better off using `rclone` or `rsync`, or if you want more "real time" (not literally), `syncthing`.

**Comment by rawtaz** [comment]
PS: As the issue template you got when starting this issue says, your questions is a better fit for the [forum](https://forum.restic.net/). For questions that are not bugs or similar, please use that instead. Thanks!

**Comment by fg-dev** [comment]
than you for the response

i am already  using syncthing for my local folder and rclone to buckup to my google drive
but they both don't use incremental  sync, and i looked for restic as a better solution
thx

**Comment by rawtaz** [comment]
Once the rclone backen in restic is done (very soon) you can use a backup tool to do you backups, instead of a sync tool.

Regarding your sync, AFAIK rclone only sends the data that changed, which I presume is what you mean by "incremental", so one of us is mistaken :) Wouldn't be much of a sync tool if it didn't do this.

**Comment by fg-dev** [comment]
i use rclone from windows, and when a file change the whole file is sent  (i don't speak about small sizes)

**Comment by rawtaz** [comment]
I see. The reason for that is mentioned in this FAQ entry: https://rclone.org/faq/#why-doesn-t-rclone-support-partial-transfers-binary-diffs-like-rsync - in summary it's because your target is a cloud service.

**Comment by fg-dev** [comment]
thank you for your response.

**Comment by fd0** [comment]
I've been using `unison` for the last decade to sync two dirs in a bi-directional way. It does not support any cloud-based backends though.
