### ISSUE TITLE
Backing up more files than the scan found to backup

### ISSUE THREAD

**Issue by richard-scott** [restic/restic#1678]
## Output of `restic version`
restic 0.8.3 (4a524da)
compiled with go1.10 on linux/amd64

## How did you run restic exactly?

` nice -n 19 ionice -c2 -n7 /usr/local/opt/restic/latest --cleanup-cache --option b2.connections=36 backup --one-file-system --exclude-caches --exclude /sys --exclude /net --exclude /dev --exclude /proc --exclude /run --exclude-file=/etc/restic/exclude.list /var/lib/docker/plugins /boot /`

## What backend/server/service did you use to store the repository?

B2

## Expected behavior
I'd expect the totals to be relevant to what I'm backing up.

## Actual behavior

`[4:18:50] 100.00%  89.224 GiB / 85.357 GiB  687314 / 619002 items  0 errors  ETA 0:00`

## Steps to reproduce the behavior

Nothing special to reproduce, just backup lots of data.

## Do you have any idea what may have caused this?
Nope.

## Do you have an idea how to solve the issue?
Nope.

## Did restic help you or made you happy in any way?
Yes, restic rocks! :-)

**Comment by bowensong** [comment]
This is actually expected. This is because the scan happens before the upload, and if there is new files created after the scan has started, the number of uploaded files will exceed the number of files scanned.

**Comment by bowensong** [comment]
BTW, this is the same as #1630

**Comment by fd0** [comment]
Thanks for the report. I'm going to close this issue as a duplicate (as @bowensong correctly noted). Displaying progress information is hard if the files to be saved change. Please let us know if you have any idea on how to improve the situation. Thanks!

**Comment by richard-scott** [comment]
@bowensong Thanks for the info... However the system was static (not being used) during update, so 4GiB of files would not have been created post scan.

**Comment by fd0** [comment]
@richard-scott should you ever find a hint what causes restic to archive more data than it detected in the first scan without the files being modified, please let us know. I'm highly interested :)

**Comment by richard-scott** [comment]
@fd0 I was being a dope. I moved a folder from inside an excluded path into an included path. That folder was about 4GB in size.

**Comment by fd0** [comment]
Hah, glad you found the reason! thanks  for the feedback :)
