### ISSUE TITLE
Restoring same subdirectories not user friendly

### ISSUE THREAD

**Issue by dirk777** [restic/restic#1687]
## Output of `restic version`

restic 0.8.3
compiled with go1.10 on darwin/amd64

## How did you run restic exactly?

1. restic backup -r testtest  /Users/adam/Documents/ /Users/test/Documents/
> password is correct
> scan [/Users/adam/Documents /Users/test/Documents]
> scanned 27 directories, 48 files in 0:00
> /Users/test: name collision for "Documents", renaming to "Documents-1"00 
> [0:00] 100.00%  7.558 MiB / 7.558 MiB  75 / 75 items  0 errors  ETA 0:00 
> duration: 0:00
> snapshot 2a394ae1 saved

2. restic restore -r testtest 2a394ae1 --target restore_restic
> password is correct
> restoring <Snapshot 2a394ae1 of [/Users/adam/Documents /Users/test/Documents] at 2018-03-25 11:45:40.626193821 +0200 CEST by d...@s....com> to restore_restic

3. ls restore_restic
> Documents	
> Documents-1

## What backend/server/service did you use to store the repository?

local storage

## Expected behavior

ls restore_restic
> Users/adam/Documents
> Users/test/Documents

## Actual behavior

 ls restore_restic
> Documents	
> Documents-1

## Steps to reproduce the behavior

see above

## Do you have any idea what may have caused this?

it is more a questions of define and design user friendliness

## Do you have an idea how to solve the issue?

when restoring please use the absolute path it is more user friendly. Internally it is fine to rename name collisions. I guess users won't keep in mind the original hint: 

> /Users/test: name collision for "Documents", renaming to "Documents-1"

## Did restic help you or made you happy in any way?

of course, it saved me time and nerves by restoring missing files

**Comment by fd0** [comment]
Hey, thanks for the report! This bug is already known, it's a limitation of the archiver code that I'm currently rewriting. For details please see #549. I'm closing this as a duplicate.

**Comment by dirk777** [comment]
ooh, i missed #549. Thx
