### ISSUE TITLE
create repository failed: client.BucketExists: Access Denied for eu-west-3 S3 region (Paris)

### ISSUE THREAD

**Issue by trompx** [restic/restic#1691]
## Output of restic version

restic 0.8.3
compiled with go1.8.3 on linux/amd64

## How did you run restic exactly?

I run restic init from bash script inside docker container with all the env vars setup correctly.

## What backend/server/service did you use to store the repository?

Just like mentioned on this page : https://forum.restic.net/t/aws-s3-eu-paris/384, trying to init a restic repo on an amazon S3 EU-Paris bucket still fails.

Just tested with EU-Francfort and it is working.

## Actual behavior

Fatal: create repository at s3:s3.amazonaws.com/my-bucket-name failed: client.BucketExists: Access Denied.

## Do you have any idea what may have caused this?

I thought the minio package were updated in the last version to support eu-west-3 region so that's weird.

Would be great to have a -v / -vvv tag to have more verbose logs as they are not very explicit.

**Comment by trompx** [comment]
Tried again after removing the bucket then creating again and now it is working..
Closing for now

**Comment by fd0** [comment]
Hm, thanks for the report. As far as I know restic is able to create buckets in the aws-eu-paris region. Did the bucket exist before, and the credentials you've used for accessing it with restic did not have enough permissions on it?

**Comment by edpichler** [comment]
I am having this issue with region `eu-north-1`. My user has full permissions on all s3 buckets.
