### ISSUE TITLE
restic check --with-cache does not populate the metadata-cache

### ISSUE THREAD

**Issue by kamudadreieck** [restic/restic#1694]
## Output of `restic version`
```
restic 0.8.3 (v0.8.3-0-g272ccec7)
compiled with go1.10 on linux/amd64
```

## How did you run restic exactly?
```bash
export RESTIC_PASSWORD=geheim
export RESTIC_REPOSITORY=rest:http://localhost:8000/rest-repo
restic check --with-cache --cache-dir /tmp/empty-folder
```
## What backend/server/service did you use to store the repository?
`rest-server 0.9.7 compiled with go1.10 on linux/amd64` listening on `127.0.0.1:8000`
`restic-server --log /tmp/restic-server.log`

## Expected behavior
`restic check --with-cache --cache-dir /tmp/empty-folder` creates a new cache and populates it, thus requesting data-blobs containing meta-data only once.

## Actual behavior
Data-blobs are requested very often, and are not cached at all (empty cache/data folder).
In the example below a total of 38773 requests are issued yet the repository consists only of 72 files.

## Steps to reproduce the behavior
Launch `rest-server 0.9.7 compiled with go1.10 on linux/amd64` listening on `127.0.0.1:8000`
Initalize new repository:
```bash
export RESTIC_PASSWORD=geheim
export RESTIC_REPOSITORY=rest:http://localhost:8000/rest-repo
restic init
```

Create some dummy backups, I used the `vendor` directory of restic since it contains many folders and small files.

```bash
for _ in `seq 20`; do restic backup ~/restic/vendor; done

find ~/restic/vendor | wc -l              
8857
find /tmp/restic/test-repo -type f | wc -l
72

du -hs /tmp/restic/test-repo ~/restic/vendor 
184M	/tmp/restic/test-repo
203M	/home/robert/restic/vendor

du -hs ~/.cache/restic/984f4f579e..
4,5M	/home/robert/.cache/restic/984f4f579e..
find ~/.cache/restic/984f4f579e../data | wc -l
7
```

Now check the repo:
```
debug log file /tmp/restic-debug.log
debug enabled
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
restic check --with-cache --cache-dir /tmp/empty-folder  72,53s user 7,64s system 608% cpu 13,168 total

du -hs /tmp/empty-folder
1,1M	/tmp/empty-folder
find /tmp/empty-folder/984f4f579e../data | wc -l
1

cat /tmp/restic-server.log | grep b8632c130b79f220d08e4faf201dbdbbd57c41f89a980843b2983b052735c08a | wc -l
14640
wc -l /tmp/restic-server.log 
38773 /tmp/restic-server.log
cat /tmp/restic-server.log | grep e778a194f8d22d6865872b75ec59e99413f102d52bae9d25720e35ff57194fb3 | wc -l
14360
cat restic-server.log | grep ceab8c4d7ca0d7c58db4068c922ef46b2f3ee10d40797bc284009416d703724b | wc -l
9740
```
Restart `rest-server` with different log-file and use the cache created by `restic backup`:
```bash
debug log file /tmp/restic-debug.log
debug enabled
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
restic check --with-cache --cache-dir ~/.cache/restic  34,27s user 2,66s system 525% cpu 7,033 total

wc -l /tmp/restic-server2.log
12 /tmp/restic-server2.log
```

So `restic check` can utilize existing cache-data, but not create it by itself.

## Do you have any idea what may have caused this?
`restic check` does not seem to populate the cache correctly, no data-blobs are being cached.

## Do you have an idea how to solve the issue?
Save metadata-blobs once requested like `restic backup`, maybe do not request the metadata with multiple range-requests, but with only one request and split them locally.

**Comment by fd0** [comment]
This is a bug, thank you very much for taking the time to report it!
