### ISSUE TITLE
Key Export?

### ISSUE THREAD

**Issue by stevesbrain** [restic/restic#1700]
Hey all,

Is copying the "config" file, and the "keys" directory all that's required to "backup" the encryption keys? Or are there more folders/files necessary? Is the config file necessary, or can that be rebuilt if lost? Just looking at what files I have to back up that cannot be rebuilt/skipped if corrupted :)

**Comment by fd0** [comment]
This would be a good post for the forum. I'll try to answer briefly and close the issue, please move to the forum for an in-depth discussion.

The `keys` directory is absolutely necessary. If you lose that, it's game over. The `config` file is not really necessary for restoring, but you'll lose the chunker configuration, so you'll end up with different blobs on the next backup. So, for now I also consider the `config` file essential.

**Comment by stevesbrain** [comment]
Thanks @fd0 - wasn't aware of the forum, but will check that out. Appreciate the response nonetheless!
