### ISSUE TITLE
Restic warnings like file changed or sizes differ are not explained

### ISSUE THREAD

**Issue by martinseener** [restic/restic#1708]
## How did you run restic exactly?
restic --no-cache -p passfile.pass -r sftp:user@sftp:/ backup --limit-download 20000 --limit-upload 20000 /var/log

## What backend/server/service did you use to store the repository?
I run restic on our central log server, and we have several subfolders in /var/log which include all log files collected from all other servers in our environment and currently /var/log is about 150GB in size. One run takes now about 8-10min. Thats totally fine!

My question is: Since these are log files, they grow in size every minute and so restic runs hourly and we constantly get messages like those 2:

```
warning for /var/log/server1/2018/04-06.log: expected 771037 bytes, saved 771429 bytes
```
or
```
warning for /var/log/server2/2018/04-06.log: file has changed
```

## Expected behavior
I expected that those files are backupped again (with the new size/state in the new snapshot) but preferably only the diff to the last state and not the full file again.
Also i don't find anything about those 2 warnings in the documentation (or i didn't searched hard enough) regarding what that means.

## Actual behavior
I don't really know how restic behaves on the 2 warnings above and i don't want to read through all the source-code but instead want to have a notice in the documentation at best. I can do a MR for the docs if someone could explain the behaviour to me, so we could post this question/answer to the FAQ part for example.

## Steps to reproduce the behavior
Backup some changing log files with restic

**Comment by martinseener** [comment]
Hey, does your explanation apply to both warnings "File changed" and "expected, saved bytes"? Because >per file< i only get one of both warnings but not both at the same time.

So if i understand you correctly, in this case, restic >does not< backup those files where one of both warnings occur but does backup them later (the next day?) when the log file doesn't get any more data written to?

I´d like to write a PR for the FAQ, yes. I love helping getting restic better and better for everyone! But at first, i need to fully understand this one of course ;)

Thanks and have a nice weekend. It's super sunny and warm here in Berlin ;)

**Comment by fd0** [comment]
> Hey, does your explanation apply to both warnings "File changed" and "expected, saved bytes"? Because >per file< i only get one of both warnings but not both at the same time.

Yes, the difference is when restic notices that the file has changed. The current archiver code (which I'm replacing at the moment, see #1494) has two places where it may be detected. The new code will only have one.

> So if i understand you correctly, in this case, restic >does not< backup those files where one of both warnings occur but does backup them later (the next day?) when the log file doesn't get any more data written to?

Not quite: restic tries to backup what it can read, but the file content that ends up in the repo may be corrupt (in the case when the file contents is replaced while restic reads it). In most cases, especially for text log files, this means that the last line may be truncated. In practice that's usually not an issue.

Cheers from sunny Aachen, on the other end of Germany ;)

**Comment by martinseener** [comment]
Hi @fd0 ,

before i start with the PR, one more question that i faced which may add up information here: In every run for one of my backups i get the following error. The backup seems to run fine though. Can you tell me what that means and also if i can fix it somehow.
`error for some/random/path/somefile.pdf: Lstat: lstat /var/some/random/path/somefile.pdf: no such file or directory`

The first part is really starting at "some/random/path" (not exactly the folders are named alike) and after the LStat thing /var/ is added in front. Does this error maybe somehow relates to the "new archiver code" with the same files in 2 folders issue that it fixes or is it unrelated?

**Comment by fd0** [comment]
Good question, I've got no idea. The new archiver code is now merged to master, would you mind re-running your test so we can see if the error is still there?

**Comment by MichaelEischer** [comment]
Closing this as the discussed backup warnings no longer exist and the Lstat error was probably fixed by the new archiver code.
