### ISSUE TITLE
Make testsuite more portable

### ISSUE THREAD

**Issue by ckeen** [restic/restic#171]
This is related to #87; As the shell scripts are currently, they will not run under OpenBSD (and probably other BSDs as well). There are a couple of things that could be done to make them work under all supported OSs, such as the du changes or the mktemp changes in my [ckeen/openbsd_tests](https://github.com/ckeen/restic/tree/openbsd_tests) branch.

Unfortunately my base system does not ship with the timeout command, so that's still another open issue for me.

As I can see the others could go in to at least improve the situation for my OS a bit. I have not tested whether that breaks anything in MacOS X, as that machine has been occupied so far, so I will update this issue when I get to that.

**Comment by fd0** [comment]
This has been addressed in #179.
