### ISSUE TITLE
Restic exits with zero exit code on Ctrl-C (SIGINT)

### ISSUE THREAD

**Issue by youam** [restic/restic#1710]
## Output of `restic version`
$ restic version  
restic 0.3.3
compiled with go1.7.4 on linux/amd64

## How did you run restic exactly?
The exact command line does not matter, any longer-running restic process will do.
While restic is running, kill it by sending it a SIGINT, e.g. by sending it a CTRL-C or by running a command like this:
```
$ timeout --preserve-status -s INT 2 restic -r /home/youam/.restic -p /dev/null backup .Mail
scan [/home/youam/.Mail]
Interrupt received, cleaning up
$ echo $?
0
```

## Expected behavior
restic exits with code 1 or anything else != 0. Restic did not complete the job it's been executed for, so it should not report success. That it got killed by a signal doesn't matter.

## Actual behavior
restic exits with code 0.

## Steps to reproduce the behavior
send a running restic command a SIGINT (2).

## Do you have any idea what may have caused this?
https://github.com/restic/restic/blob/6a34e0d10fb978cb8988a460bf4b04e9976cca17/cmd/restic/cleanup.go#L67

## Do you have an idea how to solve the issue?
The above code was added in 
https://github.com/armhold/restic/commit/0ed2401711a4dd50fedae13846af09616a440f7e to not exit 0 for some other signals, while explicitly exiting 0 for SIGINT. I suppose it should always exit 1.

## Did restic help you or made you happy in any way?
It's replaced a few rsnapshots and ancient baculas already, so: yeah.

**Comment by fd0** [comment]
Hm. This is maybe more of a philosophical problem :) When restic is cancelled with ^C (SIGINT), is this an error? After all, the user requested restic to finish up and exit. So you could argue that restic does what the user wants, and as no error occurs...

I've just looked up what `tar` does, and it does indeed exit with code 130 (128+2 (SIGINT)). So we should probably do that.

**Comment by ebastos** [comment]
> I've just looked up what tar does, and it does indeed exit with code 130 (128+2 (SIGINT)). So we should probably do that.

Looking around the interwebs this seems to be the convention. 
PR incoming.

**Comment by ebastos** [comment]
I believe this one can be closed.

**Comment by fd0** [comment]
Indeed, thanks!
