### ISSUE TITLE
Repo contains error and can't be repaired

### ISSUE THREAD

**Issue by wiatrotech** [restic/restic#1711]
## Output of `restic version`
restic 0.8.3 (v0.8.3-52-g4a524da)
compiled with go1.10 on linux/386

## How did you run restic exactly?
restic -r <repo> snapshots (one available snapshot)
restic -r <repo> check (repo contains errors, see ## Actual behavior)
restic -r <repo> rebuild-index (## Actual behavior)
restic -r <repo> check (## Actual behavior)
restic -r <repo> prune (## Actual behavior)
restic -r <repo> check (## Actual behavior)

## What backend/server/service did you use to store the repository?
local repo/catalog on the server, commands gave on server.

## Expected behavior
Repair of damaged repo

## Actual behavior
Repo still contains error

**Log of command check:**
password is correct
create exclusive lock for repository
load indexes
check all packs
pack fe317e842cc76a0e28f95e870c4e83d2573e1c13697a452ea7e627f496ed6718: not referenced in any index
pack 99a32090bfa380b1bb9eb7cfed0bb31e55ecc062a3a43277a20618b3723ed5e5: not referenced in any index
pack c95f2fb4930c7db4499541cdfd65271670b4b40fd6f2df65ca10f98cc2116b74: not referenced in any index
pack d024e8d1f02c4fde25ae9acef447df3aa3ee1fb71b3a812f72319dcf035ff38e: not referenced in any index
pack 8dc00c2f63202e6d12f60c1d9283fdef32f17201b33b2d14b3c28aeb8eb426e6: not referenced in any index
pack 630e0ee9d288c2c4b6428a29d0239da2f32a5820b3505a5f4047396df852aac4: not referenced in any index
pack e8db4bbb5a50b4830cce97d36c88c78cd0464781a3f6ebd001babdd2de341507: not referenced in any index
pack aafd80a4f864223ae6c793142df019f8a1700f95f7fffda92149421514c80164: not referenced in any index
pack f919e2aa315d61ed953fc998e22918cf9e10bbc60973a124cd4f37c8d8f99a39: not referenced in any index
pack f55eb9039365df1d2b2a3b9b22e6bfcf14f1c98250598994b114041615ce59de: not referenced in any index
check snapshots, trees and blobs
Fatal: repository contains errors

**Log of command rebuild-index:**
password is correct
counting files in repo
[1:35] 100.00%  6917 / 6917 packs
finding old index files
saved new indexes as [4f5fce94 b92f6024 746d02ee]
remove 3 old index files

**Log of command check**
password is correct
create exclusive lock for repository
load indexes
check all packs
pack fe317e842cc76a0e28f95e870c4e83d2573e1c13697a452ea7e627f496ed6718: not referenced in any index
pack 8dc00c2f63202e6d12f60c1d9283fdef32f17201b33b2d14b3c28aeb8eb426e6: not referenced in any index
pack d024e8d1f02c4fde25ae9acef447df3aa3ee1fb71b3a812f72319dcf035ff38e: not referenced in any index
pack e8db4bbb5a50b4830cce97d36c88c78cd0464781a3f6ebd001babdd2de341507: not referenced in any index
pack c95f2fb4930c7db4499541cdfd65271670b4b40fd6f2df65ca10f98cc2116b74: not referenced in any index
pack 99a32090bfa380b1bb9eb7cfed0bb31e55ecc062a3a43277a20618b3723ed5e5: not referenced in any index
check snapshots, trees and blobs
Fatal: repository contains errors

**Log of command prune:**
password is correct
counting files in repo
building new index for repo
[0:00] 100.00%  6917 / 6917 packs
incomplete pack file (will be removed): 8dc00c2f63202e6d12f60c1d9283fdef32f17201b33b2d14b3c28aeb8eb426e6
incomplete pack file (will be removed): 99a32090bfa380b1bb9eb7cfed0bb31e55ecc062a3a43277a20618b3723ed5e5
incomplete pack file (will be removed): c95f2fb4930c7db4499541cdfd65271670b4b40fd6f2df65ca10f98cc2116b74
incomplete pack file (will be removed): d024e8d1f02c4fde25ae9acef447df3aa3ee1fb71b3a812f72319dcf035ff38e
incomplete pack file (will be removed): e8db4bbb5a50b4830cce97d36c88c78cd0464781a3f6ebd001babdd2de341507
incomplete pack file (will be removed): fe317e842cc76a0e28f95e870c4e83d2573e1c13697a452ea7e627f496ed6718
repository contains 6911 packs (38705 blobs) with 33.409 GiB
processed 38705 blobs: 158 duplicate blobs, 85.303 MiB duplicate
load all snapshots
find data that is still in use for 1 snapshots
[0:01] 100.00%  1 / 1 snapshots
found 38547 of 38705 data blobs still in use, removing 158 blobs
will remove 6 invalid files
will delete 6 packs and rewrite 34 packs, this frees 85.303 MiB
hash does not match id: want a54bc70cdf79c004d25f38c9f9a6f260b5faf6fda148fc563137352b4e64d8a7, got 48d166d7129e8a54f82591ad5acd5ef03e4d2c1c0554c83cd18d4c20b16969ec
github.com/restic/restic/internal/repository.Repack
        src/github.com/restic/restic/internal/repository/repack.go:35
main.pruneRepository
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:278
main.runPrune
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:85
main.glob..func17
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:25
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:71
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_386.s:1665

**Log of command check again:**
password is correct
create exclusive lock for repository
load indexes
check all packs
pack 5c648bf98715ecdf856429d16f0bb57f6867793d99f6c996883fffb0aa967145: not referenced in any index
pack e8db4bbb5a50b4830cce97d36c88c78cd0464781a3f6ebd001babdd2de341507: not referenced in any index
pack 4db02fec5c7dbe6363c49c720b338bdf07c5d088d8a4e66d9af2905669de7452: not referenced in any index
pack c95f2fb4930c7db4499541cdfd65271670b4b40fd6f2df65ca10f98cc2116b74: not referenced in any index
pack 99a32090bfa380b1bb9eb7cfed0bb31e55ecc062a3a43277a20618b3723ed5e5: not referenced in any index
pack e7c08827c824348e969fda0fae7352fda322eb4df32cf545abea13a0c8b54deb: not referenced in any index
pack d024e8d1f02c4fde25ae9acef447df3aa3ee1fb71b3a812f72319dcf035ff38e: not referenced in any index
pack 6d046556c1961d2c35094d96ca380938b817f16885455a37d4fe42b1eb5d62b8: not referenced in any index
pack fe317e842cc76a0e28f95e870c4e83d2573e1c13697a452ea7e627f496ed6718: not referenced in any index
pack 11ea9558685c176627d755b7dd3799954676f02aa7a761aec944ce3a72d5a859: not referenced in any index
pack 8dc00c2f63202e6d12f60c1d9283fdef32f17201b33b2d14b3c28aeb8eb426e6: not referenced in any index
pack d991bef788d2f50968aefc7af6b9a77edc9a4c854577bd75ce79a3fed36839c3: not referenced in any index
check snapshots, trees and blobs
Fatal: repository contains errors

## Steps to reproduce the behavior
Tried to rebuild-index / prune / check repo few times, no possitive effect.
Did restore of the repo - gave an error on 3 files, for example:
ignoring error for <path_to_file>: decrypting blob 0522d3675a0ea4cef20196132dc41e26210aa2cb26b81fb1ed6e7eeaa1214f1f failed: ciphertext verification failed

## Do you have any idea what may have caused this?
Something's wrong with the file system or files maybe? I did the fsck, no errors on the disk.

## Do you have an idea how to solve the issue?
No

## Did restic help you or made you happy in any way?
Not yet

**Comment by fd0** [comment]
Hey, thanks for the report! You can ignore all errors about files not referenced in the index, that's not actually an error (it happens when you abort a backup, then restic may leave half-written files in the repo which do not harm), and we've recently changed the wording.

The underlying error is this one:
```
hash does not match id: want a54bc70cdf79c004d25f38c9f9a6f260b5faf6fda148fc563137352b4e64d8a7, got 48d166d7129e8a54f82591ad5acd5ef03e4d2c1c0554c83cd18d4c20b16969ec
```

Can you please run `sha256sum` on the file `data/a5/a54bc70cdf79c004d25f38c9f9a6f260b5faf6fda148fc563137352b4e64d8a7` and report back?

**Comment by wiatrotech** [comment]
hi,
This is the output:
48d166d7129e8a54f82591ad5acd5ef03e4d2c1c0554c83cd18d4c20b16969ec  a54bc70cdf79c004d25f38c9f9a6f260b5faf6fda148fc563137352b4e64d8a7

**Comment by fd0** [comment]
Thanks, that's what I though. What apparently happned is that the file was modified. Usually, this is a sign that there's a hardware problem: RAM, disc or CPU (we had all of them already). In all of the previous cases I witnessed, most of the data in the modified file could still be recovered, but I'd recommend running memtest and other testing tools on the machine to find out how that happened.

All files in the repo have a name that equals the SHA-256 hash of its contents, so you (and restic) can easily check for bit-rot, that's what likely happened here.

So, all in all it's not a problem in restic, but I agree that we need to handle the situation a lot better.

I'd like to close this issue for now, please feel free to add further comments!
I'm very very interested if you find out what's going on!

**Comment by wiatrotech** [comment]
In this moment I'm doing bad blocks check on the source disk. Before it I ran "forget" on the whole repo to be sure that's not the server problem (hope the forget command clears the whole repo). Did backup again and got same errors, so I'm quite sure that's source problem...

**Comment by fd0** [comment]
Hm, where is the repository stored? I'm pretty sure if that's a different disc than the "source" disc, that could not have caused the issue due to the way restic packs and encrypts files. If the hash does not match with the file name, either disc the repository is stored on is bad, or it's the memory of the machine that restic ran on (where the encryption happened).

Can you confirm the source and repo storage discs are separate devices?

**Comment by wiatrotech** [comment]
storage and repo are on separate computers, only on storage (source) is a bananapi r1 board with ubuntu 16 installed. We had some integrity problems with that board before, so I think this could be an issue.
The badblock check didn't find anything.
We have such errors only on this one repo from about 20 repos on the server. It could be that some files from source are actually damaged...

**Comment by stevesbrain** [comment]
I think what @fd0 is trying to say though, is that restic is only checking if the hash of the file in the backup differs from the hash of the file expected in the backup. I.e. if the file changed on the source, it wouldn't matter at all (restic is only concerned with if the files in the backup are changing or not). Have you memtested that backup server yet?

**Comment by fd0** [comment]
Exactly, restic will happily encrypt and save broken files from the source just as they are read. What you experienced is that data in a file was modified after restic was done encrypting it, so it happened in memory afterwards, on the transport to the storage server or on the storage server itself (memory or harddisk/flash).
