### ISSUE TITLE
file "data_0" has nil blob list

### ISSUE THREAD

**Issue by moritzfriedrich** [restic/restic#1714]
## Output of `restic version`
restic 0.8.3 (v0.8.3-148-g2c76e724) compiled with go1.9.4 on linux/amd64

## How did you run restic exactly?
./restic -r sftp:user@bla:/foo/bar -p pw check

## What backend/server/service did you use to store the repository?
SFTP

## Expected behavior
```
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```

## Actual behavior
```
using temporary cache in /tmp/restic-check-cache-157786933
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree b75f44fc:
  tree b75f44fc: file "data_0" has nil blob list
Fatal: repository contains errors
```

## Steps to reproduce the behavior
Run the command.

## Do you have an idea how to solve the issue?
No. I do not understand the error message.

**Comment by fd0** [comment]
Hey, thanks for the report. I'm sorry that the error message is confusing, we originally added it to keep track of a small bug which created a slightly different JSON data structure (`content: nil` instead of `content: []` for empty files).

Did you maybe create this repo with a very old version of restic?

**Comment by moritzfriedrich** [comment]
Yes, is do.
Do you need any further informations (debug logs etc.)?

**Comment by MichaelEischer** [comment]
Once we have a repair command, the best option is to just let it fix the incomplete blob list.

**Comment by clonejo** [comment]
This seems to be blocking me to upgrade the repo to v2 (#3704). My oldest snapshot is from 2016-11. Still remember one of fd0's early presentations :)

Is there a way to repair it? I don't feel like deleting old snapshots, but i guess i could find out the affected files and remove them from those snapshots?

**Comment by MichaelEischer** [comment]
@clonejo #2876 will fix such snapshots. The current experimental code should work, but I haven't had time to review it so far.
