### ISSUE TITLE
lock/ directory not created upon repository initialization

### ISSUE THREAD

**Issue by stefankoop** [restic/restic#1716]
## Output of `restic version`

Local backupserver
```
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```

/tmp/restic_0.8.3_linux_amd64 version
```
restic 0.8.3
compiled with go1.10 on linux/amd64
```

Both versions seem to have this bug

## How did you run restic exactly?
export RESTIC_PASSWORD=***
export RESTIC_REPOSITORY=***
restic snapshots

## What backend/server/service did you use to store the repository?

local repository on ZFS while discovering the bug on a restore

Generally endpoints do their backups through the s3 backend to a minio server behind a nginx.

## Expected behavior

A list of snapshots

## Actual behavior

```
password is correct
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x75052f]

goroutine 24 [running]:
github.com/restic/restic/internal/backend/local.(*Local).List.func1.1(0xc420016600, 0x3d, 0x0, 0x0, 0xe329e0, 0xc42000fb30, 0x0, 0x3d)
	src/github.com/restic/restic/internal/backend/local/local.go:257 +0x6f
path/filepath.Walk(0xc420016600, 0x3d, 0xc4201240c0, 0xc422217701, 0xc4201240c0)
	/usr/local/go/src/path/filepath/path.go:401 +0x76
github.com/restic/restic/internal/fs.Walk(0xc420016600, 0x3d, 0xc4201240c0, 0xc420016600, 0x3d)
	src/github.com/restic/restic/internal/fs/file.go:113 +0x3f
github.com/restic/restic/internal/backend/local.(*Local).List.func1(0xc42011c720, 0xc4201bebd0, 0xae893f, 0x4, 0xe397a0, 0xc420012120)
	src/github.com/restic/restic/internal/backend/local/local.go:256 +0x141
created by github.com/restic/restic/internal/backend/local.(*Local).List
	src/github.com/restic/restic/internal/backend/local/local.go:252 +0x111
```

## Steps to reproduce the behavior

Remove the repositories lock/ directory

## Do you have any idea what may have caused this?

Then lock/ directory is not created

## Do you have an idea how to solve the issue?

Create the lock/ directory manually

## Did restic help you or made you happy in any way?

Yes!

**Comment by fd0** [comment]
Hey, thanks for the report. It's primarily an issue with how the S3 protocol and the Minio server work: S3 does not have the concept of an "empty folder". If there's no file in a folder, the folder does not exist. That's what Minio also implements.

In the meantime we have already resolved this issue in the latest master branch so it'll be contained in the next release of restic. For listing files, non-existing directories will silently be ignored. When a new file is saved and the containing directory does not exist yet, it is created. This is contained in #1712, the create-on-safe is already contained in 0.8.3 (#1529).

I'm closing this issue for now. Can you please retry with the latest master branch and report back? You can find compiled binaries of the restic master branch here: https://beta.restic.net/?sort=time&order=desc

**Comment by dimejo** [comment]
> You can find compiled binaries of the restic master branch here: https://beta.restic.net/?sort=time&order=desc

Is there a link to the development builds somewhere on the website? Unfortunately was unable to find anything.

**Comment by fd0** [comment]
That is an excellent question, I don't think there's a link yet. Do you have an idea where to put it, besides the README in the repo?

**Comment by fd0** [comment]
There's a  link in the docs in the right chapter, here: https://restic.readthedocs.io/en/latest/020_installation.html#unstable-builds

**Comment by dimejo** [comment]
Looks like this entry was added just recently. I clicked [Installation](https://restic.net/#installation)  on the homepage which leads to the documentation for the stable version which doesn't have this entry yet.

**Comment by fd0** [comment]
Ah, thanks for the explanation.
