### ISSUE TITLE
Add 'cache' command with '--cleanup' flag

### ISSUE THREAD

**Issue by meisterluk** [restic/restic#1721]
## Output of `restic version`

```
restic 0.8.3
compiled with go1.10 on linux/amd64
```

## How did you run restic exactly?

My cache files do not seem to get cleaned up.

```
found 1 old cache directories in /home/meisterluk/.cache/restic, pass --cleanup-cache to remove them
```

This warning is shown whenever I run (e.g.)

```
restic-0.8.3 -r "sftp:some-hetzner-config:." backup ~ --tag home
```

I can run

```
restic-0.8.3 -r "sftp:some-hetzner-config:." check --cleanup-cache
```

afterwards but the cache files will outlive the cleanup. Hence, the warning above will show up again at the next `backup` command execution.

## What backend/server/service did you use to store the repository?

SFTP for a Hetzner Storage Box

## Expected behavior

1. `backup` shows cache file warning
2. `check --cleanup-cache` cleans up the cache
3. `backup` does not show any cache file warning

## Actual behavior

1. `backup` shows cache file warning
2. `check --cleanup-cache` cleans up the cache
3. `backup` **shows** cache file warning

## Steps to reproduce the behavior

I don't know how to reproduce it.

1. Please ask for any information, you need.
2. xubuntu 16.04 is my operating system.
3. A new OS installation is actually a solution for me right now. Still, I was wondering whether you want to think about this issue to make restic even more awesome.

## Do you have any idea what may have caused this?

1. Might it be related to the fact that backing up `~` includes `~/.restic/cache`?
2. I sometimes experience connection issues due to bad infrastructure. Maybe one interruption corrupted the cache?

## Do you have an idea how to solve the issue?

Is it safe to delete the `~/.restic/cache` directory? If so, I would do so.

## Did restic help you or made you happy in any way?

restic is awesome. It is the first convenient backup solution for me. @fd0 is super cool. Thanks a lot for being so positive. I totally liked your talk at CCC Cologne e.V. in 2016.

**Comment by ebastos** [comment]
I tried like this:

```
$ restic ...
password is correct
found 3 old cache directories in /data/home/main/.cache/restic, pass --cleanup-cache to remove them
...
restic -r gs:bucket:/ backup /data/home --cleanup-cache
enter password for repository: 
password is correct
removing 3 old cache dirs from /data/home/main/.cache/restic
... 
$ restic -r gs:bucket:/ backup /data/home 
enter password for repository: 
password is correct
using parent snapshot ab21f6e1
...
```

Did you try to add --cleanup-cache to the backup run instead of the check?

**Comment by meisterluk** [comment]
```
meisterluk@lagrange ~ % restic-0.8.3 -r "sftp:some-hetzner-config:." backup ~ --cleanup-cache
enter password for repository: 
password is correct
removing 1 old cache dirs from /home/meisterluk/.cache/restic
using parent snapshot e2d2c9cb
[...]
[1:41] 100.00%  39.349 GiB / 39.349 GiB  245605 / 245605 items  2 ... ETA 0:00 
duration: 1:41
snapshot 5d47be02 saved
58.41user 25.88system 3:11.09elapsed 44%CPU (0avgtext+0avgdata 351412maxresident)k
9230608inputs+1153232outputs (1318major+90092minor)pagefaults 0swaps
```

Indeed. It works with `backup` :smile: 
Do we consider it as UI issue?

```
meisterluk@lagrange ~ % restic-0.8.3 check --help

The "check" command tests the repository for errors and reports any errors it
finds. It can also be used to read all data and therefore simulate a restore.

By default, the "check" command will always load all data directly from the
repository and not use a local cache.

Usage:
  restic check [flags]

Flags:
      --check-unused              find unused blobs
  -h, --help                      help for check
      --read-data                 read all data blobs
      --read-data-subset string   read subset of data packs
      --with-cache                use the cache

Global Flags:
      --cacert stringSlice       path to load root certificates from (default: use system certificates)
      --cache-dir string         set the cache directory
      --cleanup-cache            auto remove old cache directories
      --json                     set output mode to JSON for commands that support it
      --limit-download int       limits downloads to a maximum rate in KiB/s. (default: unlimited)
      --limit-upload int         limits uploads to a maximum rate in KiB/s. (default: unlimited)
      --no-cache                 do not use a local cache
      --no-lock                  do not lock the repo, this allows some operations on read-only repos
  -o, --option key=value         set extended option (key=value, can be specified multiple times)
  -p, --password-file string     read the repository password from a file (default: $RESTIC_PASSWORD_FILE)
  -q, --quiet                    do not output comprehensive progress report
  -r, --repo string              repository to backup to or restore from (default: $RESTIC_REPOSITORY)
      --tls-client-cert string   path to a file containing PEM encoded TLS client certificate and private key
```
Hence, `--cleanup-cache` should work for `check`

**Comment by ebastos** [comment]
It looks like it should be running with check as well:

https://github.com/restic/restic/blob/6a34e0d10fb978cb8988a460bf4b04e9976cca17/cmd/restic/global.go#L378

**Comment by meisterluk** [comment]
Thanks for the pointer @ebastos! I can confirm that `GlobalOptions.CleanupCache` is set to true:

```
goopts: {sftp:some-hetzner-config:.  false false false /tmp/restic-check-cache-174362119 false []  true 0 0 0xc420138e40  0xc42000c018 0xc42000c020 [] map[]}
```
Please recognize `[]` followed by empty string and then `true`.

*Related question:* Does anyone know why `check` ignores the `GlobalOptions.CacheDir`? If some conditions are met, then it will trigger `ioutil.TempDir` to retrieve a new temporary directory and overwrite whatever `GlobalOptions.CacheDir` has contained. Hence, previous values of `--cache-dir` are ignored.
https://github.com/restic/restic/blob/6a34e0d10fb978cb8988a460bf4b04e9976cca17/cmd/restic/global.go#L48
https://github.com/restic/restic/blob/6a34e0d10fb978cb8988a460bf4b04e9976cca17/cmd/restic/cmd_check.go#L148

**Comment by meisterluk** [comment]
To solve this issue:

If ignoring `GlobalOptions.CacheDir` is a desired behavior, the answer can be easily given:

1. `runCheck` is called to run the `check` command
    https://github.com/restic/restic/blob/6a34e0d10fb978cb8988a460bf4b04e9976cca17/cmd/restic/cmd_check.go#L161
2. `prepareCheckCache(opts, &gopts)` overwrites the cache directory with some new, temporary cache.
    https://github.com/restic/restic/blob/6a34e0d10fb978cb8988a460bf4b04e9976cca17/cmd/restic/cmd_check.go#L166
3. `OpenRepository(gopts)` is called to (e.g.) remove files in the cache living there for more than 30 days. A new, temporary directory does not contain such files. Hence, no file satisfies this condition.
    https://github.com/restic/restic/blob/6a34e0d10fb978cb8988a460bf4b04e9976cca17/cmd/restic/cmd_check.go#L172
    https://github.com/restic/restic/blob/6a34e0d10fb978cb8988a460bf4b04e9976cca17/cmd/restic/global.go#L378

If ignoring is undesired, I could fix the bug.

**Comment by fd0** [comment]
The cache behavior with `check` has been changed in #1696, but the issue persists unless you use `check --with-cache`.

I don't like the `--cleanup-cache` option as the only way to remove old cache directories, so I'd like to add a `cache` command which has a `--cleanup` flag. We can then change the text to:

```
found 3 old cache directories in /data/home/main/.cache/restic, run "restic cache --cleanup" to remove them
```

So I consider this not a bug, but an enhancement.
