### ISSUE TITLE
Set lifecycle rules for backblaze bucket (or document it)

### ISSUE THREAD

**Issue by mlissner** [restic/restic#1725]
## Output of `restic version`

restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?

N/A

## What backend/server/service did you use to store the repository?

Backblaze

## Expected behavior

When a new bucket is established by restic in Backblaze, the default lifecycle rules for that bucket are in place. These rules keep every version of every uploaded file. This takes up space and costs money as incremental backups are completed. Instead, restic should use Backblazes lifecycle rules to not save old versions of the data. 

## Actual behavior

The default lifecycle rules are applied, which keeps all versions of all files.

## Steps to reproduce the behavior

Init a new backblaze repo.

## Do you have an idea how to solve the issue?

You should be able to tweak the code that creates the bucket in backblaze to include different lifecycle rules, as described in their docs: https://www.backblaze.com/b2/docs/lifecycle_rules.html

## Did restic help you or made you happy in any way?

I've been loving the restic concept and UX. That it uses backblaze at all is wonderful. 

For us, it's going to come down to a matter of performance whether I *get* to continue using restic. I hope so, but it seems like 4TB may be a bit too much for restic.

**Comment by fd0** [comment]
Thanks for the report! So, if I understood this correctly, at the moment restic will accumulate data in a B2 bucket? Even if files are deleted (by `prune` and `forget`)?

@kurin Is that correct?

If that's the case, I'm all for setting a different lifecycle policy for files created by restic.

Or is this only applied for overwritten files? In this case it's not relevant for restic: Due to the way the repo is designed, no files are overwritten at any point.

**Comment by kurin** [comment]
If restic is deleting instead of hiding objects, this shouldn't really matter.

https://www.backblaze.com/b2/docs/file_versions.html

But you could always set the lifecycle rules anyway.  I've never been fond of the hiding/deleting mechanic.

**Comment by fd0** [comment]
restic uses `Delete()` https://godoc.org/github.com/kurin/blazer/b2#Object.Delete so we should be fine.

**Comment by mlissner** [comment]
Sounds great. Just so long as we never get to a point where we're overwriting files, I think we'll be OK. I'll close unless those with more expertise see a problem here. (There is an argument that doing this is good *just in case* though, to cover the possibility that we accidentally start overwriting files.)
