### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by rinzes** [restic/restic#1728]
## Output of `restic version`

Fatal: create key in repository at /media/r9000/dva-debian failed: chmod /media/r9000/dva-debian/keys/21c68f82b884d2f61c8f042bbf9701fa4ad6df6f1890307f683cf4ca24eb591e: permission denied

## How did you run restic exactly?

restic -r /media/r9000/dva-debian -p restic-pw.txt init

## What backend/server/service did you use to store the repository?

This is with the following Fstab config on a Debian 9.2 OS. The dva-debian folder was created and I'm able to access the system
.
//r9000.local/usb_storage  /media/r9000 cifs rw,uid=1000,noauto,user  0   0

## Expected behavior

create keys in config file

**Comment by fd0** [comment]
Please add the version of restic that you're using (as instructed in the issue template).

For newly created files in the repo, restic sets the permissions to read-only. That's what failed.

What's the CIFS server's OS and implementation?

**Comment by rinzes** [comment]
Version = restic 0.8.2
compiled with go1.10 on linux/amd64

cifs os = ntfs file system

**Comment by rinzes** [comment]
sudo chmod 600 /media/r9000/dva-debian/keys/
chmod: changing permissions of '/media/r9000/dva-debian/keys/': Permission denied

**Comment by dimejo** [comment]
> sudo chmod 600 /media/r9000/dva-debian/keys/
chmod: changing permissions of '/media/r9000/dva-debian/keys/': Permission denied

Are you able to write to any part of the mounted share? To me it looks like you configured the samba share to disallow writes.

**Comment by rinzes** [comment]
Yes, I am able to transfer files

**Comment by ebastos** [comment]
As per your comment above, this seems to be a permission issue, not a restic issue, since even a manual "chmod" fails.

**Comment by rinzes** [comment]
Was reconfigured in the fstab.

**Comment by fd0** [comment]
Thanks for the feedback
