### ISSUE TITLE
sha256sum hashes for every release

### ISSUE THREAD

**Issue by lea-anthony** [restic/restic#1733]
Hi,

Each release has the SHA256 hashes of the tarballs, however is there an easy way to get the hashes for the actual binaries without me downloading every release, untarring and hashing them manually? I am developing a tool which uses restic and need a way to determine if the provided binary is indeed a valid restic binary.

Many thanks.

**Comment by fd0** [comment]
There's currently no way to do that.

What we're doing is a pretty standard approach: Provide a `SHA256SUMS` file which can be used with `sha256sum -c --ignore-missing` to verify a downloaded file. Then extract it and use it.

Can you elaborate on your use case? Do you really need the hash for every released version of restic? Why do you need to verify the already downloaded/available restic binary?

**Comment by lea-anthony** [comment]
I'm writing a utility that calls the restic binary and wanted to ensure it was genuine. It's really to protect people from themselves. Just doing "restic version" and parsing the text seems a bit too hacky.

**Comment by fd0** [comment]
I can't think of an easy way to do that with our current workflow, so I'm going to close this issue for now. Please feel free to add further comments. Thanks!
