### ISSUE TITLE
"Everything is ok"-Error message

### ISSUE THREAD

**Issue by mik-at** [restic/restic#1734]
How about adding a "Everything is ok"-Message, after restic printed a does not exist errormessage?

## Expected behavior

Load(<data/xxxxxxxxxx>, 0, 0) returned error, retrying after xxx.xxxxxxms: <data/xxxxxxxxxx> does not exist
Load(<data/xxxxxxxxxx>, 0, 0) found it after x retries: <data/xxxxxxxxxx> is ok

## Actual behavior

Load(<data/xxxxxxxxxx>, 0, 0) returned error, retrying after xxx.xxxxxxms: <data/xxxxxxxxxx> does not exist

## Do you have an idea how to solve the issue?

Add another errormessage which tells your that the data was found.

## Did restic help you or made you happy in any way?

yep, made me very happy that fd0 is always listening to my bullshit in IRC ;)

**Comment by fd0** [comment]
Good idea :)

**Comment by rawtaz** [comment]
Anyone up for this?

**Comment by creativeprojects** [comment]
I'm always a bit worried when my Azure Storage backend is sometimes misbehaving overnight and I get these emails in the morning...

`Save(<data/956b9ced99>) returned error, retrying after 357.131936ms: CreateBlockBlobFromReader: Put https://example.blob.core.windows.net/restic/data/95/956b9ced99d4cb236e2cf2f0de4a140f8cafb500ea1617db8bf6452f6c7d1aac: write tcp 192.168.11.18:51620->1.2.3.4:443: write: connection reset by peer`

I'll try to post a quick fix for it :)
