### ISSUE TITLE
brew upgrade restic - go version issue

### ISSUE THREAD

**Issue by novski** [restic/restic#1737]
## Expected behavior

`$ brew upgrade restic `
update restic to latest

## Actual behavior

aarau:~ novski$ restic version
restic 0.7.3
compiled with go1.9.2 on darwin/amd64
aarau:~ novski$ brew upgrade restic
==> Upgrading 1 outdated package, with result:
restic/restic/restic 0.7.3 -> 0.8.0
==> Upgrading restic/restic/restic 
==> Downloading https://github.com/restic/restic/releases/download/v0.8.0/restic
==> make

go run build.go
Go version go1.10.1 detected, restic requires at least Go 1.8
exit status 1
make: *** [restic] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/restic/homebrew-restic/issues     <------ unavailable!!! ----

Error: curl failed! 
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed

## Steps to reproduce the behavior

Install Homebrew 1.6.2
brew install go
brew install restic

## Do you have any idea what may have caused this?

malformed strings?

## Do you have an idea how to solve the issue?

no

## Did restic help you or made you happy in any way?

Restic is great!

**Comment by fd0** [comment]
Yeah, we've discussed this before: The restic package has been merged into upstream homebrew, so you don't need the custom tap any more. I think you can resolve the situation via `brew untap restic/restic`, please report back!

https://twitter.com/resticbackup/status/968967692559433729

**Comment by novski** [comment]
Yes that works:

```
aarau:~ novski$ brew untap restic/restic
Untapping restic/restic... (53 files, 34.5KB)
Untapped 1 formula
aarau:~ novski$ brew upgrade restic
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
restic 0.7.3 -> 0.8.3
==> Upgrading restic 
==> Downloading https://homebrew.bintray.com/bottles/restic-0.8.3.high_sierra.bo
==> Downloading from https://akamai.bintray.com/93/93fa732cd990a24769b710a122407
######################################################################## 100.0%
==> Pouring restic-0.8.3.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/restic/0.8.3: 6 files, 11.6MB
```

Thanks!

**Comment by fd0** [comment]
Great, thanks for the feedback!
