### ISSUE TITLE
windows: passwords with a paragraph character have a problem

### ISSUE THREAD

**Issue by cd1188** [restic/restic#1738]
## Output of `restic version`
restic 0.8.3
compiled with go1.10 on windows/amd64

## How did you run restic exactly?
on windows 10 in german and windows cmd
password in the file pwd.txt is test§§test and saved as ANSI
[pwd.txt](https://github.com/restic/restic/files/1958736/pwd.txt)

C:\restic>restic -r c:\backup_test init -p c:\restic\pwd.txt
restic -r c:\backup_test snapshots

## What backend/server/service did you use to store the repository?
test on local drives

## Expected behavior

C:\restic>restic -r c:\backup_test snapshots
password is correct

## Actual behavior

C:\restic>restic -r c:\backup_test snapshots
enter password for repository:
Fatal: wrong password or no key found

## Steps to reproduce the behavior

only passwords with a paragraph character in it have problems on the following situation
-> password is here always test§§test

C:\restic>restic -r c:\backup_test init -p c:\restic\pwd.txt
restic -r c:\backup_test snapshots
ERROR

C:\restic>restic -r c:\backup_test init
restic -r c:\backup_test snapshots -p c:\restic\pwd.txt
ERROR

C:\restic>restic -r c:\backup_test init
restic -r c:\backup_test snapshots
WORK

C:\restic>restic -r c:\backup_test init -p c:\restic\pwd.txt
restic -r c:\backup_test snapshots -p c:\restic\pwd.txt
WORK

## Do you have any idea what may have caused this?

ascii-ansi / windows codepage problem?
german-problem?

## Do you have an idea how to solve the issue?

no

**Comment by fd0** [comment]
Thanks for the report, I'll summarize what I understood so far:

 * You initialize a repository with the password `test§§test`, the password is read from a file encoded as `latin1`/`ISO-8859-1` (I've verified that on the file you've uploaded)
 * When you try to access the repository, typing the password manually, it does not work
 * When you try to access the repository while reading the password from the file again, it works

Is that correct?

If so, the reason is that the string `test§§test` has different bytes, depending on the encoding:

`latin1`/`ISO-8859-1`:

```
00000000: 7465 7374 a7a7 7465 7374              test..test
```

`UTF-8`:

```
00000000: 7465 7374 c2a7 c2a7 7465 7374         test....test
```

So for restic, that's two different passwords. I guess when the password is read in a different encoding than `latin1` (I'm guessing `UTF-8`). For solving this issue, you need to save the password in the file in the same encoding as entered, e.g. in UTF-8.

This is not an issue in restic, therefore I'm closing this issue for now. Please feel free to add further comments, thanks!

**Comment by cd1188** [comment]
Hi
i cant bring it to run
the terminal is in codepage 850 and if i make 
`echo § > test.txt`
in the hex-editor there is only the byte F5

so if i make a password in the terminal with only § and in the textfile i tried the bytes from 00 to FF there is always the password incorrect..

is it possible that restic convert the character § (byte F5) internal to unicode or something?
i think restic want a password now with more then 1 byte in the textfile?

changing the password from a existig repro also does not work in windows... :(
-> i found an issue post about that...

**Comment by fd0** [comment]
> in the hex-editor there is only the byte F5

Hm, that's a third encoding, it's even different from the file you attached to the first post in this issue...

> is it possible that restic convert the character § (byte F5) internal to unicode or something?

No, restic takes the literal bytes as they are read via the prompt.

Do you have a Go compiler installed, or can you install one? If so, please add the following line in `cmd/restic/global.go`:

```patch
diff --git a/cmd/restic/global.go b/cmd/restic/global.go
index 6fe026bc..b5637f2b 100644
--- a/cmd/restic/global.go
+++ b/cmd/restic/global.go
@@ -274,6 +274,7 @@ func readPasswordTerminal(in *os.File, out io.Writer, prompt string) (password s
        }
        password = string(buf)
+       fmt.Printf("password is: %q (%02x)\n", password, password)
        return password, nil
 }
```

This will read the password, then print it on stdout, as a string and as the hex bytes.

**Comment by cd1188** [comment]
Hi
wow i compiled now my fist GO program :)
so here is the output

`C:\rest_git\restic>restic -r c:\test_rc init
enter password for new repository:
password is: "§§" (c2a7c2a7)

C:\rest_git\restic>restic -r c:\test_rc init
enter password for new repository:
password is: "test§§test" (74657374c2a7c2a774657374)
`
it looks like restic reed it as utf-8
i saved now a textfile in windows as utf-8 and in hex it shows me this
`EF BB BF 74 65 73 74 C2 A7 C2 A7 74 65 73 74 .....  ï»¿testÂ§Â§test` 
i found in the wiki that the first 3 bytes are called BOM for identify utf8 and if i remove that 3 byte manual , the password works now in restic!

are under linux also that 3 bytes at the beginning ??
so what is the best solution for this in the future?
always remove that 3 bytes if found or only show a warning if loading a file with that 3byte?
before restic i worked with RAR and there was btw no problem with § and ansi-text-files


THX for restic!
i like it because restic is for windows and borg was not 👍

**Comment by fd0** [comment]
I'm glad you found the issue! On Linux, it's unusual to have a BOM. We could, however, try to detect if the password file has a BOM, the same could be done for other files (like the exclude files). This was already mentioned in #1433...

**Comment by cd1188** [comment]
ok
hopefully nobody init a repository with a password-file and BOM in it..
if so you cant enter the password then i the terminal.
so a warning should be in that case.  :-)

**Comment by fd0** [comment]
I've added the code in #1748

**Comment by fd0** [comment]
Did you find some time to test the new code?

**Comment by cd1188** [comment]
hi
with the new master-branch, i can now use password-textfiles with utf-8 encoding in windows without problems, but other things like file-lists in utf-8 i have not tested.

but i found out that umlauts like äöü are encoded in the promt also as unicode and umlauts can also be in standard ansi-textfiles  (ä=hex A4 in ansi)
and i mostly use ansi-textfiles in windows, but i think that is only a  usa and german thing :)
the rest of the world should use utf-8 text-files...
but its curious that other people had no problem with that BOM thing in the file

`C:\restic>restic_pwd -r c:\repo snapshots`
`enter password for repository:`
`password is: "ä" (c3a4)`

`C:\restic>restic_pwd -r c:\repo snapshots`
`enter password for repository:`
`password is: "a" (61)`

i think the savest way is always init a new repository at first with a password in the promp, and if after that a password-file in ansi encoding do not work, the user should re-save the file than as utf-8

but always restrict the user to not use a password-file for init could be bad, because some users want maybe use binary-files as a key-file like .jpg or .mp3 ???    :-)

btw, i think i try now to use restic as my main backup

**Comment by fd0** [comment]
Thanks for the feedback. Almost all other people I asked about that use utf-8 encoded files. But it's great to know that restic now detects (and correctly processes) a BOM :)
