### ISSUE TITLE
Unable to back up OneDrive on Windows 10

### ISSUE THREAD

**Issue by bherila** [restic/restic#1758]
## Output of `restic version`

restic 0.8.3
compiled with go1.10 on windows/amd64

## How did you run restic exactly?

Both directly through "restic backup -r ... c:\users\ben" and also tried backing up a VSS shadow copy in case that was causing the problem.

## What backend/server/service did you use to store the repository?

Filesystem (local drive).

## Expected behavior

It should back up the OneDrive files.

## Actual behavior

warning for C:\shadowcopy\Users\ben\OneDrive - Herila.net: Readlink: readlink \\?\C:\shadowcopy\Users\ben\OneDrive - Herila.net: The process cannot access the file because it is being used by another process.

(and the OneDrive files are skipped/excluded from the backup)

## Steps to reproduce the behavior

Try to use restic to back up a OneDrive synced folder on Windows 10. 

## Do you have any idea what may have caused this?

OneDrive new files on demand feature? I do have the entire directory synced/stored locally, however (in other words all the files are fully "hydrated"). Also, crashplan is able to read the files.

## Do you have an idea how to solve the issue?

Perhaps a different syscall other than Readlink should be used to open files on Windows? Not really sure though.

## Did restic help you or made you happy in any way?

I love restic and I want to use it to replace Crashplan when my Crashplan Home subscription expires. Thanks for all your hard work on this project!!

**Comment by bherila** [comment]
Adding info: The problem still happens when I disable "Files On Demand" option in OneDrive.

Appears to be a Go issue, https://github.com/golang/go/issues/22579 and https://github.com/arduino/arduino-builder/issues/254

Apparently fixed in Go 1.11 however for now that requires building restic off of the golang master branch. Seems like a risky proposition, since the prerelease compiler could introduce a regression in compiled restic.exe and compromise my backups (right?)

**Comment by fd0** [comment]
Thanks for the report. I don't have a Windows machine so I cannot reproduce it. This issue will be solved once Go 1.11 is released, which should be in August.

Building restic with the Go master branch is not something you should do lightly, but in general I'm confident that it doesn't eat your data :)

If you attempt to do this, please report back how it goes!

**Comment by jojomi** [comment]
@bherila At least there is the pretty comprehensive testsuite you could run before you use the binary you build youself, right @fd0? It should work on Windows too as far as I know.

**Comment by fd0** [comment]
Oh yes, we have a comprehensive test suite, which is run on a native Windows machine via Appveyor for every commit that is pushed to master, and for every PR. So in general I'm quite confident :)

**Comment by bherila** [comment]
I got it to work, just needed the latest vendor packages from https://github.com/golang/sys and https://github.com/golang/crypto

Version is restic 0.8.3 (v0.8.3-226-gabdd59ea-dirty) compiled with devel +bcdbd58ce4 Fri May 4 15:39:02 2018 +0000 on windows/amd64

Here's the bin in case it helps anyone else:
[restic.zip](https://github.com/restic/restic/files/1978156/restic.zip)

**Comment by fd0** [comment]
I'll update the libs in master, then it should be resolved (and included in the next release).

**Comment by bherila** [comment]
Thank you @fd0 and @jojomi !
