### ISSUE TITLE
Restic 0.8.3 seems to forget --limit-upload after 24 hours or so

### ISSUE THREAD

**Issue by barenada** [restic/restic#1760]
## Output of `restic version`
restic 0.8.3
compiled with go1.8.3 on linux/amd64
(This is on CentOS 7.4)

## How did you run restic exactly?
RESTIC_REPOSITORY="b2:xxxxx-backups"
WHAT=/jbook/xxxx (This is 787GiB)
restic backup --limit-upload 500 $WHAT

## What backend/server/service did you use to store the repository?
B2

## Expected behavior

Honor the --limit-upload setting for the duration of the backup.

## Actual behavior

For the first 24 hours or so, I can see (using the nethogs command) that restic stays at a little over 400. Then, after 24 hours or so (maybe exactly 24 hours for all I know) it either forgets about that limit or decides to ignore it, and bandwidth goes up to between 800 and 1200. This kills my ISP connection for any other work.

## Steps to reproduce the behavior

I've stopped and restarted this thing about 10 times in 10 days. Once restarted, it honors the --limit-upload for a while, but then after a day or so it stops honoring it again and I have to CTL-C it again.

## Do you have any idea what may have caused this?

I was hoping someone here could tell me.

## Do you have an idea how to solve the issue?

None at all.

## Did restic help you or made you happy in any way?

It's quite wonderful, and once this issues goes away I'll probably start naming my pets Restic.

**Comment by fd0** [comment]
Huh, that is very odd, thanks for the report! Does it happen all the time?

I need to run some long-term tests with the library we're using for limiting, https://github.com/juju/ratelimit

**Comment by barenada** [comment]
So far it's happened 10 times in a row, with 3 different backup sets.

**Comment by fd0** [comment]
I've opened an issue for the library we're using https://github.com/juju/ratelimit/issues/27

**Comment by barenada** [comment]
I was afraid of that.

**Comment by barenada** [comment]
Suspended it this morning before the 24 hours had passed. Just got home and resumed - it's at 1125.

**Comment by fd0** [comment]
I know what's happening: The rate limiting library remembers the time stamp when the process was started. Based on that timestamp it computes how much data is allowed for each second. When you suspend and resume the process, much time has passed in between, so the library allows for much data in the next segments.

I'll try to explain this to the authors and try to get it fixed ;)

**Comment by fd0** [comment]
Hm. I still cannot reproduce it.

@kurin is there anything in blazer that may explain this behavior?

**Comment by kurin** [comment]
You know what, this actually might be a blazer issue.  After 24 hours the initial auth token expires and blazer grabs a new one; it looks like when it attempts to do that, it fails to pass in client modifications, including modified round-trippers.

**Comment by fd0** [comment]
Oh, that'd explain it!
