### ISSUE TITLE
restored file has wrong "type"

### ISSUE THREAD

**Issue by rinzes** [restic/restic#1762]
file not being restored correctly

## Output of `restic version`

restic 0.8.2
compiled with go1.10 on linux/amd64

## How did you run restic exactly?

```
restic -r backup_name -p mypass restore "id" --target "target"
```
no output when the item is being restored

## What backend/server/service did you use to store the repository?

local

## Expected behavior

restore video to the same type ie video_file_name.ts

## Actual behavior

restored file type to" Text (text/vnd.trolltech.linguist)"

## Do you have any idea what may have caused this?
no idea

## Do you have an idea how to solve the issue?
nope

**Comment by rinzes** [comment]
The file type that was marked as a video file however, when I did a restore it was marker as a TEXT file.

**Comment by fd0** [comment]
Would you mind answering the other questions?

Can you please describe what it means that "it was marked as a TEXT file"?

**Comment by fd0** [comment]
Like, is there a graphical file browser toll (which one?) that shows you the restored file with the icon of a text file? I'm really guessing here, please help me out!

**Comment by rinzes** [comment]
Strange I did a reboot and all the file types were corrected so this is not a problem now. Sorry
