### ISSUE TITLE
lchown operation not permitted

### ISSUE THREAD

**Issue by petabyteboy** [restic/restic#1766]
## Output of `restic version`
```
restic 0.8.1 (v0.8.1-134-g2debb5c0)
compiled with go1.9.3 on linux/amd64
```

## How did you run restic exactly?
```
rm -rf /foo/bar
mkdir -p /foo/bar
chown restic /foo/bar

sudo -u restic /usr/local/bin/restic restore latest \
    -r "sftp:backup:bar" \
    -p /home/restic/.restic-password \
    --target="/foo/bar/../" \
    --cache-dir=/home/restic/.cache/restic
```

## What backend/server/service did you use to store the repository?

sftp

## Expected behavior

Run without errors and return 0.

## Actual behavior

All permissions seem to be accurate after the restore, but restic tries to lchown the directories and files and somehow fails with that:

```
ignoring error for /bar/a: Lchown: lchown /foo/bar/a: operation not permitted
ignoring error for /bar/b: Lchown: lchown /foo/bar/b: operation not permitted
ignoring error for /bar/c: Lchown: lchown /foo/bar/c: operation not permitted
ignoring error for /bar/d: Lchown: lchown /foo/bar/d: operation not permitted
```

## Steps to reproduce the behavior

Restore a backup that contains files that are owned by a different user than the one used to restore the files. 

## Do you have an idea how to solve the issue?

I'm not sure if I am missing something here, but maybe don't call lchown on all files and directories?
Isn't lchown only for symlinks?

## Did restic help you or made you happy in any way?
Very :)

**Comment by rfjakob** [comment]
I believe running `lchown` on everything is correct, as restic tries to preserve the owner. (Note that `lchown` works on everything, including symlinks, while `chown` only works on regular files)

One could argue if the error message should be suppressed if restic is not running as root. I just tested with `cp -a`, and it does call `lchown` on the files, but suppresses the error message if it is not running as root. Here's the code ( http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/copy.c#n3015 ):
```
chown_failure_ok (struct cp_options const *x)
{
  /* If non-root uses -p, it's ok if we can't preserve ownership.
     But root probably wants to know, e.g. if NFS disallows it,
     or if the target system doesn't support file ownership.  */

  return ((errno == EPERM || errno == EINVAL) && !x->chown_privileges);
}
```
It seems that `rsync -a` behaves similar - you don't get an error message if you are not running as root.

@fd0 If you agree that the message could be suppressed in that case I can take a look if it is doable without causing a lot of code churn.

**Comment by fd0** [comment]
@rfjakob thanks a lot for the triage! I agree with your analysis, if you're up for a PR which hides the error messages then please go ahead!

**Comment by JusticeForMikeBrown** [comment]
Any idea on how to address? 

Followed the guide and created a service account called restic then set these permissions on binary at '/usr/bin/restic'

> 0750
> 
> setcap cap_dac_read_search=+ep

`-rwxr-x---. 1 root restic 12M Jun 14 11:08 /usr/bin/restic`

**I think it would be ideal if restic could restore the original permissions**.  What if you lost a large directory with crazy permissions, ACLs, etc, which were never documented anywhere?

So should we add the ability for restic to chown using '/etc/sudoers' perhaps?

**Comment by rfjakob** [comment]
> Any idea on how to address?

If you want to restore the original permissions, you will have to run restic as root

**Comment by rfjakob** [comment]
(I don't think playing with sudo is worth it - just as with `rsync` and `cp`, if you don't run as root, the owner is not preserved)

**Comment by JusticeForMikeBrown** [comment]
@rfjakob 

Why not?

'sudo' makes it work.

```
[restic@server ~]$ sudo restic restore --target /tmp/shadow b5bfd502 --include /etc/shadow
repository b6cc200c opened successfully, password is correct
restoring <Snapshot b5bfd502 of [/] at 2018-07-26 17:03:28.435993154 -0400 EDT by restic@server> to /tmp/shadow

[restic@server ~]$ ls -ltr /tmp/ | tail -n 1
drwx------. 3 root     root          16 Jul 27 08:31 shadow
```

Use this example sudo file:

```
Defaults    env_keep += "RESTIC_REPOSITORY AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY RESTIC_PASSWORD"

restic ALL        = (root) NOPASSWD: /usr/bin/restic *

```

**Comment by rfjakob** [comment]
You can run restic as root via sudo, yes, no problem. Any way to run it as root is fine.

**Comment by rfjakob** [comment]
I misunderstood that you want restic to call "sudo chown".

**Comment by JusticeForMikeBrown** [comment]
Ah @rfjakob gotcha.  No, running it with sudo I think is the best solution as you're not running all of it as root only those commands which are needed.

**Comment by fd0** [comment]
The thing that isn't mentioned in the guide: `cap_dac_read_search` gives restic superpowers to override the permission system to read all files. This does not imply restic is allowed to change the ownership of files it creates to some other user (e.g. `root`), that's a different permission. You can either find out which one it is and add it via setcap (maybe `cap_dac_override`?) or restore files as root if you want the ownership and permissions for other users preserved.

**Comment by whereisaaron** [comment]
When you are restoring files, it will often not be to the original environment, which is quite possibly now dead and gone. The file permissions (especially groups and users) in the back-up may make no sense in the new environment. As such it is a pretty common restore option in backup software to restore file without trying to apply the original permissions. If you are restoring as root there is no easy way to avoid this this unwanted behavior, and option to disable it would be welcome.

**Comment by whereisaaron** [comment]
Just doing some restore tests. It painful getting 100,000 `lchown` errors filling my screen and log. It is also 100,000 unnecessary system calls and exceptions. I guess I can pipe it though grep to hide the errors, but a `--no-perms` to not make the lchown calls doesn't see like feature bloat?

**Comment by rfjakob** [comment]
These messages should be suppressed automatically when not running as root. I will implement this in september.

**Comment by rfjakob** [comment]
As "rsync -a" and "cp -a" does exactly the same thing, I think it is actually expected for restic to do the same.

As for the unneccessary syscalls, my guess is that it has neglegible performance impact, but if you have a test that proves otherwise, I'd gladly be wrong.

**Comment by fd0** [comment]
> These messages should be suppressed automatically when not running as root. I will implement this in september.

Awesome!

**Comment by whereisaaron** [comment]
It's more a style question than a performance question @rfjakob. Either way it's an improvement. So cool. Yes please!

**Comment by achrjulien** [comment]
> The thing that isn't mentioned in the guide: `cap_dac_read_search` gives restic superpowers to override the permission system to **read** all files. This does not imply restic is allowed to change the ownership of files it creates to some other user (e.g. `root`), that's a different permission. You can either find out which one it is and add it via setcap (maybe `cap_dac_override`?) or restore files as root if you want the ownership and permissions for other users preserved.

`setcap cap_fowner,cap_chown,cap_dac_override=+ep /path/to/restic` if that can be useful to anybody
