### ISSUE TITLE
Restic 'list' broken on Windows/amd64

### ISSUE THREAD

**Issue by nizedk** [restic/restic#1783]
... but 'ls' 'restore' 'check' 'backup' still works.
## Output of `restic version`
restic 0.8.3
compiled with go1.10 on windows/amd64

## How did you run restic exactly?
```
C:\Users\user\Desktop\restic>restic init -r c:\restictest
enter password for new repository:
enter password again:
created restic repository f0d1dfdeca at c:\restictest

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

C:\Users\user\Desktop\restic>restic list -r c:\restictest
Fatal: type not specified

C:\Users\user\Desktop\restic>restic list -r c:\restictest\
Fatal: type not specified

C:\Users\user\Desktop\restic>restic backup -r c:\restictest c:\bin
enter password for repository:
password is correct
scan [c:\bin]
scanned 596 directories, 14100 files in 0:01
[0:28] 100.00%  1.783 GiB / 1.783 GiB  14696 / 14696 items  0 errors  ETA 0:00
duration: 0:28
snapshot 262da89f saved

C:\Users\user\Desktop\restic>restic list -r c:\restictest\
Fatal: type not specified

C:\Users\user\Desktop\restic>restic list -r c:\restictest
Fatal: type not specified

C:\Users\user\Desktop\restic>restic check -r c:\restictest
enter password for repository:
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found

C:\Users\username\Desktop\restic>restic ls -r c:\restictest 262da89f
enter password for repository:
password is correct
snapshot 262da89f of [c:\bin] at 2018-05-17 14:49:35.4865423 +0200 CEST):
\bin
[listing of files as intended]

C:\Users\user\Desktop\restic>restic version
restic 0.8.3
compiled with go1.10 on windows/amd64

C:\Users\user\Desktop\restic>

C:\Users\username\Desktop\restic>restic restore -t extracttest -r c:\restictest 262da89f
enter password for repository:
password is correct
restoring <Snapshot 262da89f of [c:\bin] at 2018-05-17 14:49:35.4865423 +0200 CEST by FLEX\username@hostname> to extracttest

[files restored correctly]
```

## What backend/server/service did you use to store the repository?

Local NTFS file system

## Expected behavior

Ask for passphrase + List the snapshots in the repository
## Actual behavior
Exits with the message: '''
Fatal: type not specified
'''
Does not ask for passphrase.

## Steps to reproduce the behavior
See above in 'how do did you run restic exactly'?

## Did restic help you or made you happy in any way?

Restic still makes me smile because of the possibilities that lies in it; because of the diverse backends and because it has a native win64 port. You guys are awesome - keep up the good work! Thanks!

**Comment by fd0** [comment]
Oh, this is not a bug, but a user interface issue: the `list` command is a low-level one to list objects in the repo:
```
$ restic list --help

The "list" command allows listing objects in the repository based on type.

Usage:
  restic list [blobs|packs|index|snapshots|keys|locks] [flags]
```

So in order to list snapshots in the repo you could use `restic list snapshots` - but that's not very user friendly.

The command you're looking for is the `restic snapshots` command.

**Comment by nizedk** [comment]
My bad; it comes from using borg ; 'borg list' is equivalent of 'restic snapshots'. 

Sorry. Soooorrryyyyy.

:-)

**Comment by fd0** [comment]
Don't worry about it, I like to see the positive thing here: A confusing error message got improved :)

Thanks for taking the time to report this!
