### ISSUE TITLE
Change --cacert to exclusively use the provided certs and ignore system's cacerts

### ISSUE THREAD

**Issue by cfcs** [restic/restic#1789]
The current behaviour is to load the file path provided by the `--cacert` argument and use the contained CA keys *in addition* to the ones provided by the system.

I propose changing this to exclusively using the provided keys as trust root.
This prevents MITM in cases where the attacker has access to one of the ~200 CA keys, or can trick one of them to issue a rogue certificate (for example by BGP or DNS hijacking in combination with LetsEncrypt certs).

This change will break setups where people use `--cacert` to provide a set of keys that is *not* used while relying on the trust root to be loaded from the system cacerts file. I think it is unlikely that someone is actually doing that.

The default behaviour would remain to use the system cacerts file.

I tried to identify the relevant place to change this, but was not successful:
- https://github.com/restic/restic/blob/master/internal/backend/http_transport.go#L94-L109
- it reads to me like the default is already to exclude the system pool if a valid `--cacert` path is provided? https://golang.org/pkg/crypto/x509/#NewCertPool

This documentation would have to be updated:
- https://github.com/restic/restic/blob/master/doc/030_preparing_a_new_repo.rst

ping @fd0

**Comment by davidlt** [comment]
Some organizations are using their own CA certificates which are not part of Mozilla CA bundle, or similar. These also could be deployed in non-standard system location. This is popular in HEP (High Energy Physics) environments. E.g., CERN Certification Authority ( https://ca.cern.ch/ca/ ) and it's not part of standard CA bundle.

**Comment by fd0** [comment]
@davidlt it's already possible to use `--cacert` for that, this issue is just about changing the meaning of the option slightly.

**Comment by fd0** [comment]
Turns out, the feature already works as described here, so we only need to make sure the documentation is accurate.
