### ISSUE TITLE
Creating backup from stdin fails

### ISSUE THREAD

**Issue by youam** [restic/restic#1790]
## Output of `restic version`
```
restic 0.8.3 (v0.8.3-277-gc284712c) compiled with go1.10.2 on linux/amd64
```

## How did you run restic exactly?
```
# cat /dev/vg/vm-win10 | restic_v0.8.3-277-gc284712c_linux_amd64 -r rest:http://vmimages:RESTPASS@backpi:8000/vmimages  --password-file /etc/restic/vm-pass backup --stdin
repository e7b6b597 opened successfully, password is correct
error: invalid combination of flags 0x20800

Files:           0 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added:      0 B  

processed 0 files, 0 B in 0:02
snapshot 636ca5a5 saved
```

## What backend/server/service did you use to store the repository?
```
rest-server 0.9.7 compiled with go1.10 on linux/arm64
```

## Expected behavior

Full stdin read and stored in repository, without error, status 0

OR

when some error occurs, status != 0

This is the case with release 0.8.3

## Actual behavior

`--stdin` flag seems to always throw the warning `error: invalid combination of flags 0x20800`

## Steps to reproduce the behavior

Try to backup something from stdin

## Do you have any idea what may have caused this?

Regression in the code since release 0.8.3 (this feels like saying "water is wet")

**Comment by youam** [comment]
I just did a git bisect on this, resulting in:

```
c83c03ed63df305dfeedcc39bb56a83ff67e0e07 is the first bad commit
```

**Comment by fd0** [comment]
Thanks for the comprehensive report!
