### ISSUE TITLE
incomplete documentation for --exclude-if-present

### ISSUE THREAD

**Issue by whereisaaron** [restic/restic#1792]
## Output of `restic version`

```
restic 0.8.3
compiled with go1.10 on linux/amd64
````

## How did you run restic exactly?

Read the documentation at: http://restic.readthedocs.io/
Looking for '--exclude-if-present'

## What backend/server/service did you use to store the repository?

B2

## Expected behavior

Documentation explains how '--exclude-if-present' is configure and works, e.g.

1. It says it excludes the contents of the folder, but does that include subdirectories?

2. Does the filename match only exactly or support the restic wildcards?

3. The help text mentions you can specify a 'header' to match in the file, but not the syntax for the header or how it is matched. It is a match from byte 0? Or a literal sub-string match anywhere in the file?

## Actual behavior

http://restic.readthedocs.io/en/latest/040_backup.html?highlight=--exclude-if-present

--exclude-if-present Specified one or more times to exclude a folders content if it contains a given file (optionally having a given header)

http://restic.readthedocs.io/en/latest/manual_rest.html?highlight=--exclude-if-present

--exclude-if-present stringArray takes filename[:header], exclude contents of directories containing filename (except filename itself) if header of that file is as provided (can be specified multiple times)

## Steps to reproduce the behavior

Read the documentation at: http://restic.readthedocs.io/
Looking for '--exclude-if-present'

## Do you have any idea what may have caused this?

Overworked developers :+1:

## Do you have an idea how to solve the issue?

Read the code, if I can find it.

## Did restic help you or made you happy in any way?

B2 support is working great and smoothly so far.

It would be great if people could contribute examples of using this option. E.g. I'd like to use it to exclude MySQL data folders, maybe on the auto.cnf file will work? But will it exclude sub-folders with the table data?

**Comment by whereisaaron** [comment]
I found the older code and looks like 'header' is a comparison from byte zero. In newer code in the master this has gone somewhere else the github search can't find.

https://github.com/restic/restic/blob/c22c582546976a5153cf41b95231fdb7ec3d0d4c/cmd/restic/cmd_backup.go#L584-L634

**Comment by fd0** [comment]
FYI, the code was moved to a separate file, here: https://github.com/restic/restic/blob/master/cmd/restic/exclude.go

**Comment by rawtaz** [comment]
I'm taking the liberty of closing this now, for the following reasons relating to the questions in the original post:

1. *It says it excludes the contents of the folder, but does that include subdirectories?* - Yes, it includes subdirectories too, as they are a part of the contents of the folder. All contents is excluded, and I think this is what you'd expect if you were to ponder what the documentation is telling you on this topic. Doesn't need clarifying.

2. *Does the filename match only exactly or support the restic wildcards?* - The documentation has been updated to state that wildcards are not supported for this filename, so this is considered fixed.

3. *The help text mentions you can specify a 'header' to match in the file, but not the syntax for the header or how it is matched. It is a match from byte 0? Or a literal sub-string match anywhere in the file?* - I argue that a "header" is something that pretty much everyone would consider being "the first part of the file", i.e. starting from byte 0. I can't think of a single person I know that would think a header starts from some other byte than the very beginning of the file. It's so common that we don't need to mention this. If someone ever need to know, they can ask in the forum or somewhere else, this is too detailed to be worth a PR (but we wouldn't dismiss one, if anyone is up for it).

**Comment by shtratos** [comment]
Playing devil's advocate here : restic itself writes "headers" at the end of the file 😆

**Comment by rawtaz** [comment]
@shtratos What/where are you thinking of? :)

**Comment by shtratos** [comment]
https://github.com/restic/restic/blob/master/doc/design.rst#pack format

Here in the pack format description it says that headers are written at the end of file.

**Comment by rawtaz** [comment]
Nice catch ❤️
