### ISSUE TITLE
Does not compile on Solaris

### ISSUE THREAD

**Issue by fd0** [restic/restic#1795]
Reminder issue: This needs to be fixed, probably by not calling the syscall directly, but via `golang.org/x/unix`:

```
GOOS=solaris go build
# github.com/restic/restic/internal/ui/termstatus
../../internal/ui/termstatus/terminal_unix.go:35:35: undefined: syscall.SYS_IOCTL
```

Also, we need to build for Solaris on Travis to catch this earlier next time.

**Comment by michaelkoetter** [comment]
I think this is an easy fix - unix.IoctlGetWinsize seems to do the job.
It builds and runs on SmartOS now.

**Comment by fd0** [comment]
Cool, thanks!

**Comment by fd0** [comment]
This issue is resolved in master, closing.
