### ISSUE TITLE
Not found in repository <-> no error when checking

### ISSUE THREAD

**Issue by Taapo** [restic/restic#1797]
## Output of `restic version`

restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?

/usr/local/bin/restic -r sftp:xxxxxxxxx@xxxxxxxxx.xxxxxxxxx.xx:/restic.xxxxxxxxx restore latest --target /

## What backend/server/service did you use to store the repository?

SFTP (Hetzner Storage Box)

## Expected behavior

I expect no errors. 

When I run the following command:
/usr/local/bin/restic -r sftp:xxxxxxxxx@xxxxxxxxx.xxxxxxxxx.xx:/restic.xxxxxxxxx check --read-data

I get the following result:
xxxxxxxxx@xxxxxxxxx.xxxxxxxxx.xx's password:
enter password for repository:
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
read all data
[10:30:24] 100.00%  51187 / 51187 items
duration: 10:30:24
no errors were found          

## Actual behavior

When restoring I get these errors (truncated):

ignoring error for /www/xxxxxxxxx/_combined-5745.pdf: id 503eda8ba97951f19dbcf0f6ea94d0c6576e0e9a91942e9a2640fe7a338f80d3 not found in repository
ignoring error for /www/xxxxxxxxx/_combined-5746.pdf: id 47687078cee87101caa22c0e4345782201f5193e935b4e5ffac8d8e3f605637a not found in repository
ignoring error for /www/xxxxxxxxx/_combined-5763.pdf: id b8756cd759871d4a9350e258ea42f21c56357a417e932b5bf7e98b283157285f not found in repository
ignoring error for /www/xxxxxxxxx/_combined-5781.pdf: id 88b50858a4c42b8c46026e063a366fe55e9c4d003baa08d9c8bad7ff664d4a43 not found in repository
ignoring error for /www/xxxxxxxxx/_combined-5819.pdf: id 8142c934d18844512e5a13bedbfc07c65c2d50e09b3071dc0785d9dc39224249 not found in repository
ignoring error for /www/xxxxxxxxx/_combined-5856.pdf: id 57fdb16ff8bc2017a683e0490cda15bd932239ff250cec144e569eb52c30c334 not found in repository
ignoring error for /www/xxxxxxxxx/_combined-5912.pdf: id 1d6fa838e56116af06949a4775da636262b35d71269fe8433ba189fa63a7aba4 not found in repository

## Do you have any idea what may have caused this?

I'm currently doing an new restore (might take a while and I'll report back). I'm hoping it is related to a transport error, but the phrase "not found in repository" makes me wonder if there is an error somewhere?

Also, when restoring those error files, they show up as zero byte files - which is contradictory to the "ignoring error" phrase.

## Do you have an idea how to solve the issue?

Nope. If it is related to transport error, it should display something else as an error message. Now it looks like there is an error in the repository while restoring ...

**Comment by fd0** [comment]
Uh, this is odd. The `restic check` command will read all data for all snapshots and make sure the right data is returned. I'm confident that when `check` returns no errors, all data is there.

I don't have any idea what may have happened here. You can try to help debugging this:
 * Restore a subset of the data which still shows the error, by using the `--include` option to `restic restore`, ideally that'd be just a single file or a directory with a few files in it.
 * Rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs))
 * Run `restic restore` with the debug log and attach it to the issue. Please make sure to replace any sensitive details included in there (file names, passwords etc) before posting it.

Maybe we can see what's going on...

Let us know if you got stuck somewhere.

**Comment by Taapo** [comment]
Ok, so I'm now into 80% of my additional restore, and I don't get any "ignoring errors" anymore (and the previous zero byte files are now extracted perfectly), so I'm thinking either: the previous transmission was interrupted, or the storage box I was using was overloaded. 

Either way, the notification was not completely correct - since the file *is indeed* in the repository. So maybe you could adjust the wording a bit there? My initial thought was: "Ah, bollocks ... and there I thought Restic was reliable. Not." while actually, it was :)

**Comment by fd0** [comment]
Thanks for the feedback. It's hard to say from the outside what's going on here... Did you get any other messages at the start of the restore, complaining that index files couldn't be loaded? That's the only way I can come up with how this error message could have happened...

**Comment by Taapo** [comment]
Nope. No additional errors in the beginning. Can it be that the connection was interrupted that it starts showing error messages?
