### ISSUE TITLE
tree e5457a72: file "XX": metadata size (8770356) and sum of blob sizes (8770808) do not match

### ISSUE THREAD

**Issue by dionorgua** [restic/restic#1799]
Hi,

Just updated to restic 0.9 and found that restic now reports errors for my existing repo (that was ok with 0.8.3 and was not changed after upgrade):

```error for tree e5457a72:
  tree e5457a72: file "mail.err": metadata size (1085858) and sum of blob sizes (1085966) do not match
  tree e5457a72: file "mail.info": metadata size (8770356) and sum of blob sizes (8770808) do not match
  tree e5457a72: file "mail.log": metadata size (8770356) and sum of blob sizes (8770808) do not match
  tree e5457a72: file "mail.warn": metadata size (1091226) and sum of blob sizes (1091334) do not match
```
Probably files were changed while backup was running. 

## Output of `restic version`
`restic 0.9.0 compiled with go1.10.2 on linux/amd64`

## How did you run restic exactly?
`restic check`

## What backend/server/service did you use to store the repository?
local directory and rest-server

## Expected behavior

I understand that restic can't do anything to make sure backup is consistent (for example that a few dependent files have matched content). 

But I'm pretty sure that restic should make sure it's own repository is consistent in such case (repository metadata should match repository data). If something was appended to file after `stat` was called,but before whole file is read, probably restic should read only up to expected file size, or just update metadata with number of bytes that were actually read.

PS. Probably this issue is fixed on 0.9 and this will not happens for new snapshots. 
But unfortunately `restic rebuild-index` doesn't fix it.

**Comment by fd0** [comment]
I agree, this should either be a warning or not shown at all. It's a bug in the old archiver code, which wrote the wrong size to the repo when the file was appended to while restic was reading it. The new archiver doesn't do that, and all the other functions will work just fine (they just use the correct size, the sum of the file chunks).

**Comment by deweysasser** [comment]
How does one deal with this issue?  It's causing my weekly automatic checks to fail on several of my backup repos.

**Comment by zcalusic** [comment]
That is a good question! All my repos except one are in error now... thinking about disabling check stage alltogether, but then again, it was and will be a good way to detect possible future regressions. Hard to tell what is the best way going forward...

@fd0, this is quite a serious bug, is there any workaround to make repos silent again?

**Comment by fd0** [comment]
Sorry for that, I've disabled the check in #1887. You can cherry-pick the commit if you like.
