### ISSUE TITLE
Backup fails to continue with `panic: runtime error: slice bounds out of range`

### ISSUE THREAD

**Issue by aloysbaillet** [restic/restic#1803]
## Output of `restic version`
`restic 0.9.0 compiled with go1.10.2 on linux/amd64`

## How did you run restic exactly?
```
export B2_ACCOUNT_ID=XXX
export B2_ACCOUNT_KEY=XXX
export RESTIC_PASSWORD=XXX
restic --repo b2:XXX:/Data backup /XXX/Data
repository XXX opened successfully, password is correct
panic: runtime error: slice bounds out of range

goroutine 34 [running]:
github.com/restic/restic/internal/ui/termstatus.(*Terminal).SetStatus(0xc42016e5a0, 0xc4204280a0, 0x1, 0x1)
	src/github.com/restic/restic/internal/ui/termstatus/status.go:310 +0x319
github.com/restic/restic/internal/ui.(*Backup).update(0xc42028d450, 0x1, 0x0, 0xd306c00, 0x0, 0x0, 0x0, 0x0, 0xc42058fd00, 0x0)
	src/github.com/restic/restic/internal/ui/backup.go:181 +0x69e
github.com/restic/restic/internal/ui.(*Backup).Run(0xc42028d450, 0xc06fa0, 0xc4200b5200, 0x0, 0x0)
	src/github.com/restic/restic/internal/ui/backup.go:139 +0x5d5
main.runBackup.func2(0x0, 0x0)
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:360 +0x75
github.com/restic/restic/vendor/gopkg.in/tomb%2ev2.(*Tomb).run(0xc4202402d0, 0xc4202383e0)
	src/github.com/restic/restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b
created by github.com/restic/restic/vendor/gopkg.in/tomb%2ev2.(*Tomb).Go
	src/github.com/restic/restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xb9
```

## What backend/server/service did you use to store the repository?
Backblaze

## Expected behavior
Backup continues from where it stopped. Or maybe there could be an error logged to tell me to revert to the previous version of restic to finish the backup.

## Actual behavior
Backup cannot continue.

## Steps to reproduce the behavior
I had a backup running for a week (uploading 350GB to B2 via a crappy ADSL2 line) on restic 0.8.3 and after a reboot I updated to 0.9.0 and tried to continue my backup, unfortunately it now fails with this error.

## Do you have any idea what may have caused this?
I'm guessing that backup that started on 0.8.3 and that have not yet completed cannot be resumed with the newer restic version.

## Do you have an idea how to solve the issue?
Not sure if continuing the backup between version is even thinkable...

## Did restic help you or made you happy in any way?
Really liking the simplicity of restic! It is a great replacement for the convenient-but-bloated CrashPlan home!

**Comment by fd0** [comment]
How do you run restic? It seems this bug occurs when restic is run without a proper terminal, there's a duplicate bug in #1819.

**Comment by fd0** [comment]
I've tried this, but it doesn't produce the error:
```
setsid sh -c 'tty; ./restic backup -v -v .' < /dev/null 2>&1 | cat
```

**Comment by aloysbaillet** [comment]
Sorry about this, I didn't realise that the terminal would be the source of the problem! I am running restic via a patched up version of restique...
Here's the equivalent python code:
```
#!/bin/env python
import pty
import tty
import select
import os
import subprocess
import sys

def run_restic(cmd):
    master, slave = pty.openpty()

    process = subprocess.Popen(
        cmd,
        stdin=slave, stdout=slave, stderr=slave,
        bufsize=1,
        universal_newlines=True,
        close_fds=True
    )

    timeout = .04 # seconds
    while process.poll() is None:
        ready, _, _ = select.select([master, pty.STDIN_FILENO], [], [], timeout)
        if master in ready:
            data = os.read(master, 1024)
            if not data:
                break
            os.write(pty.STDOUT_FILENO, data)
        if pty.STDIN_FILENO in ready:
            data = os.read(pty.STDIN_FILENO, 1024)
            while data != '':
                n = os.write(master, data)
                data = data[n:]
    ret = process.wait()
    return ret

if __name__ == '__main__':
    c = run_restic(sys.argv[1:])
    sys.exit(c)
```
Save this as `run_restic.py` and call it this way:
`python3 run_restic.py restic ...`
with `...` being all the needed arguments.

**Comment by fd0** [comment]
Thank you very much, I'm able to reproduce it, fix incoming.

**Comment by aloysbaillet** [comment]
Thanks a lot! I confirm my backup is now running smoothly from master!

**Comment by fd0** [comment]
Awesome, thanks for the feedback!
