### ISSUE TITLE
Error message "check has no arguments" not helpful

### ISSUE THREAD

**Issue by tyll** [restic/restic#1812]
## Output of `restic version`

restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?

restic check /srv/restic/
restic check

## What backend/server/service did you use to store the repository?

fs

## Expected behavior

`restic check /srv/restic/`  should check the repository at `/srv/restic` or at least tell me that it requires the repository to be specified with `-r`.

## Actual behavior

Restic only tells me that check has no arguments:
```restic check /srv/restic/
Fatal: check has no arguments
```
And

```
restic check
Fatal: Please specify repository location (-r)
```

I guess restic considers `-r` an option and not an argument but it is IMHO not a useful error message.

## Steps to reproduce the behavior

see above

## Do you have any idea what may have caused this?

N/A

## Do you have an idea how to solve the issue?

Improve the error message or accept the repo as an argument.

## Did restic help you or made you happy in any way?

**Comment by fd0** [comment]
Good point, the error message needs to be improved.
