### ISSUE TITLE
Unclear what to do with unreferenced packs mentioned by restic check

### ISSUE THREAD

**Issue by tyll** [restic/restic#1813]
## Output of `restic version`
restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?
RESTIC_PASSWORD_FILE=/root/restic-password RESTIC_REPOSITORY=/srv/restic/ restic check

## What backend/server/service did you use to store the repository?
fs

## Expected behavior

I get lots of lines like 
```

pack 9b1f020fbaa954ba0c456b4ac70c579ec8d8c68ea9cad67262d47eacaa221557: not referenced in any index
pack 158ed155e15d3d0ac3444b5ce62c055a75dca3bd840ba54c6aadd426c6166fc2: not referenced in any index
pack 8492c4a4f913d99b668c2d618c9417349d52017140bdac1126dba438cd00d88a: not referenced in any index
pack a61d84e22a7f668bbf86dd2401b25d5dcd6cabb3f42de8ff8b498dc50446f1c2: not referenced in any index
pack c13bd7c2d4e6b5054d42fd5076bdee9701ae53ec89acc10a2d91f315a3ac6932: not referenced in any index
```

#but nothing tells me what to do about it. `man restic-check` does not menion error conditions and what to do about them.

## Actual behavior

I get error but no help in fixing them or understanding what the packs contain.

## Steps to reproduce the behavior

Not sure how I got these errors. I only had 12 snapshots and did not notice any errors when I created them.

## Do you have any idea what may have caused this?

Missing documentation.

## Do you have an idea how to solve the issue?

Add help about how to inspect what the packs contain and how to remove or add them properly.

**Comment by fd0** [comment]
Yep, these errors need to be improved as well. For the record, what's going on here is that `check` finds files in the repo not mentioned in the metadata files anywhere, they were probably leftover files from an aborted/interrupted run of `backup`.

The next run of `restic prune` will take care of the files and remove them properly.

**Comment by tyll** [comment]
Thank you, `restic prune` helped.

**Comment by rawtaz** [comment]
Thanks for reporting the need for better documentation @tyll. I'm closing this issue in favor of #2683.
