### ISSUE TITLE
Debian 8, restic 0.9 amd64 compiled, segmentation fault

### ISSUE THREAD

**Issue by guidtz** [restic/restic#1817]
Hello,

 I test restic 0.9 on Debian 8 installation and I have some segmentation faults.
Restic 0.9 amd64 compiled
Debian 8
swift backend

How can I degug that and send you a report ?

Regards

**Comment by fd0** [comment]
Start by filling out the [issue template](https://raw.githubusercontent.com/restic/restic/master/.github/ISSUE_TEMPLATE.md), that should give us a good starting point. Make sure to paste all the output of restic and how you started it.

**Comment by guidtz** [comment]
Hello,
  perhaps a timeout problem with swift provider
`Save(<data/41bbbe7c63>) returned error, retrying after 356.702582ms: client.PutObject: Timeout when reading or writing data
Save(<data/41bbbe7c63>) returned error, retrying after 817.570795ms: client.PutObject: Timeout when reading or writing data
Save(<data/41bbbe7c63>) returned error, retrying after 749.329993ms: client.PutObject: Put https://storage.gra1.cloud.ovh.net/v1/AUTH_******/restic-client1/data/41/41bbbe7c63c0d79e898b36fcce95e41ab60c5e2c916a44851c6648538e48729b: dial tcp: i/o timeout
Save(<data/41bbbe7c63>) returned error, retrying after 968.495736ms: client.PutObject: Timeout when reading or writing data`

**Comment by fd0** [comment]
This looks like a timeout. I'm closing this issue for now, please fill out the issue template if you want us to look into it.
