### ISSUE TITLE
restic-mount under FreeBSD: open /dev/fuse: no such file or directory

### ISSUE THREAD

**Issue by erikw** [restic/restic#1818]
## Output of `restic version`
`restic compiled manually compiled with go1.10.2 on freebsd/amd64`
Somehow the version number is not printed out, but I see in /usr/ports/sysutils/restic/distinfo that the version is `0.9.0`.

## How did you run restic exactly?

```bash
$ # set envvars RESTIC_REPOSITORY, B2_ACCOUNT_ID, ...
$ restic mount /mnt/restic
repository xxx opened successfully, password is correct
Mountpoint /mnt/restic doesn't exist, creating it
open /dev/fuse: no such file or directory
unable to umount (maybe already umounted?): unmount /mnt/restic: invalid argument
```

## What backend/server/service did you use to store the repository?
Backblaze B2

## Expected behavior
The virtual file system to be mounted to /mnt/restic. The above command works fine on my Arch Linux machine.

## Actual behavior
Some fuse error.

## Steps to reproduce the behavior
1. Set up restic and remote backend
2. Make a full backup.
3. Verify with restic-check
4. Try to mount, as in "How did you run restic exactly?"

## Do you have any idea what may have caused this?
Missing requirement. Is there a list of required packages, I did not find such list. I guess the package maintainers might have missed something for the FreeBSD port.

## Do you have an idea how to solve the issue?
Figure out which dependencies restic has.

**Comment by erikw** [comment]
Uh, found it.

```
kldload fuse
```

fixed it

**Comment by fd0** [comment]
Cool, thanks for the feedback on how to resolve this issue! Awesome that you found it yourself ;)

**Comment by fd0** [comment]
Added in 0882aca3a87e02a3c0bdac86c3a23a6e392dda9b, thanks!
