### ISSUE TITLE
Restic backup /w Azure backend - 413 RequestBodyTooLarge

### ISSUE THREAD

**Issue by francoismiquel** [restic/restic#1822]
## Output of `restic version`

restic 0.9.0 compiled with go1.10.2 on linux/amd64

## How did you run restic exactly?

/usr/bin/nice -n 19 /usr/bin/ionice -c 2 -n 7 restic -r azure:$AZURE_CONTAINER_NAME:/ backup --cache-dir $backup_cache_dir --tag basebackup-$domain_to_backup $pg_datadir

Restic password pass with environment variable
## What backend/server/service did you use to store the repository?

Microsoft Azure Blob Storage

## Expected behavior

The file is correctly upload

## Actual behavior

Time:2018-05-28T04:25:58.4479485Z, RequestInitiated=Mon, 28 May 2018 04:25:57 GMT, RequestId=4b25e7f9-001e-00df-763b-f6d66c000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=
Save(<data/30283c2078>) returned error, retrying after 28.071907844s: CreateBlockBlobFromReader: storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.

## Steps to reproduce the behavior

Just run backup command

## Do you have any idea what may have caused this?

Restic try to create a blob with a size who exceeds the maximum permissible limit.

## Do you have an idea how to solve the issue?

May be a bug in Azure Go SDK or may be i can set a maximum blob size in option (like azure.connections=10 with -o flag) but i don't know how to do this.

## Did restic help you or made you happy in any way?

Restic is a very good backup tool. I switch from duplicity and Restic is faster and more reliable for my use case. 

I run this command on many server with a similar dataset with no problems.

EDIT : I already have this issue with restic 0.8.3

**Comment by fd0** [comment]
Thanks for the report!

**Comment by fd0** [comment]
We had this problem once already, but that was for a file larger than 256MiB (see #1386), this should not be the case for a simple data file.

**Comment by francoismiquel** [comment]
Hello, 

Thanks for reply !

This dataset contains 22329 files for 2.4TB and lot of them are small.

I compared similar dataset, successfully backed up with Restic : 19376 files for 1.9TB.

This 2 datasets are very similar in their struct because it's PostGreSQL data directory and contains many files with size bigger than 256MB.

**Comment by fd0** [comment]
Ah, I'm sorry, I should have made it clearer: Large files saved by restic are cut into smal chunks which are then bundled together and uploaded to the repo. Such files are between 4 to 16MiB in size, only metadata files may be larger. I don't know how you ended up with such a large file being uploaded to the repo.... Or maybe it's a glitch at the Azure service? Can you retry?

**Comment by francoismiquel** [comment]
Hi,

I use Restic to backup approximative 20 similar dataset and i have problems with only one.

Yesterday, i used restic backup command with twice verbose flag : 

new       /data/xx/xx/db/pg_xlog/000000010000094A000000B9, saved in 4.511s (16.000 MiB added)
Save(<data/e4ee03eb56>) returned error, retrying after 626.265717ms: CreateBlockBlobFromReader: storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.

The problem occur only in pg_xlog directory, with many files of 16MB. This directory contains 637 files but before browse this folder, restic browse almost 20K files and uploaded new files with no problem. 

I thought it was an issue with Azure but i have this problem only here, and restic browse and upload lot of data on Azure without any problems.

**Comment by fd0** [comment]
Hm, interesting! I have an idea: Can you please create a new local repository, backup the same data into it, and then check how large the files in `data/` are? Maybe we can then find out what's going on...

**Comment by francoismiquel** [comment]
Hello,

I created a fresh new repository in local, execute the backup with the same dataset and i founded that : 

-rw------- 1 root root 312M May 31 07:05 data/1d/1dd4eed1c59ed43d0a710c78b3d5edc5ac041d4a45ad66bcb57e02846f424e74

Restic has created a file of 312MB so .... can't upload it in Azure.

Also, Restic has returned many "lstat error : No such file or directory". I found similar issue but in this case, happened only where some directories excluded and the path are in these directories. In my case, no exclude flag are present in my backup command

**Comment by fd0** [comment]
Hm, so restic indeed tries to upload a large file. Can you please try the following (using the local repo, with the tool `jq`):
 * run `restic rebuild-index`
 * find the ID of the index: `restic list index`
 * dump the index and list the contents of the specific pack:
```
restic dump index <ID> | jq '.packs[] | select(.id == "1dd4eed1c59ed43d0a710c78b3d5edc5ac041d4a45ad66bcb57e02846f424e74")'
```

Please post the result

**Comment by francoismiquel** [comment]
I launched <code> restic rebuild-index </code> but i'm not sure about **"find the ID of the index"**.

If i execute <code> restic list index </code>, i obtain a list of index, but 1dd4eed1c59ed43d0a710c78b3d5edc5ac041d4a45ad66bcb57e02846f424e74 not present in this list.

After execute <code> restic rebuild-index </code>, i had a new file of 320MB, with new ID but this new ID not present in <code> restic list index </code> anymore

**Comment by francoismiquel** [comment]
Ok, i think you meant <code> restic cat index <ID> </code> instead of <code> restic dump index <ID> </code>.

I found ID and i had this output : 

{
  "id": "1dd4eed1c59ed43d0a710c78b3d5edc5ac041d4a45ad66bcb57e02846f424e74",
  "blobs": [
    {
      "id": "03a5dedeec080af38cccee3fb19cd1e46df624d42ce7ba23a1a944f67ab3d865",
      "type": "tree",
      "offset": 0,
      "length": 94709
    },
    {
      "id": "c4f13ec17965111935757dc6291c751d44a06f7d2ad81eaca11c505cf9cf9fbd",
      "type": "tree",
      "offset": 94709,
      "length": 94795
    },
    {
      "id": "7fd53c19af29b4d248fdb8e5bc651bb38ca140ca293c4baa589d327e000b9dc0",
      "type": "tree",
      "offset": 189504,
      "length": 95165
    },
    {
      "id": "a038ceadf07e2f3905280d4d06b276ec8c7fe458008283ba67edb0c2f5223bf2",
      "type": "tree",
      "offset": 284669,
      "length": 352526
    },
    {
      "id": "b5f1c950a0a8b104b9a76727f772a47d70da0c96e34df647e9a9f4213a2a3099",
      "type": "tree",
      "offset": 637195,
      "length": 166605
    },
    {
      "id": "51ee042fb139d016c4b8e8123a35683d7efa3648f0b8bbab1cb17779cf4f5d73",
      "type": "tree",
      "offset": 803800,
      "length": 20298
    },
    {
      "id": "bb42558a2a3c513be7b5daca6ddc7f4dbdb5c4a0d979bb81397f2d6d7fff2a03",
      "type": "tree",
      "offset": 824098,
      "length": 412
    },
    {
      "id": "536943371bc736c23771872d593f4f2237da99ac916d8ccb9b4bb6ca37fdca19",
      "type": "tree",
      "offset": 824510,
      "length": 779
    },
    {
      "id": "a0d694b5130c61b2244b730dc8fc21fc8d5a5b62bf99b67e17e0d99557a070d8",
      "type": "tree",
      "offset": 825289,
      "length": 411
    },
    {
      "id": "e219e0050cfa9cf105ffaa6b96ee00279a19202e9b7e92e2b1f76d87b04eedd8",
      "type": "tree",
      "offset": 825700,
      "length": 410
    },
    {
      "id": "abdcd79239d82c0e9d86130c089c14281411e5306b395926ac89defd2ce2db15",
      "type": "tree",
      "offset": 826110,
      "length": 776
    },
    {
      "id": "c6a4f8fa78c8e356fa45056340d9d347e51f897f9380bc772b28216a10178526",
      "type": "tree",
      "offset": 826886,
      "length": 410
    },
    {
      "id": "eb9f272cfbb90f80ef2118d6a27407af919a7963b8782b887d599ffa768b4980",
      "type": "tree",
      "offset": 827296,
      "length": 412
    },
    {
      "id": "13459b02e158a478ef56201997344d84bedd1ef17c8ec3bc01fcf51901e073a9",
      "type": "tree",
      "offset": 827708,
      "length": 325359912
    }
  ]
}

**Comment by fd0** [comment]
Thanks for the feedback. It looks like you have a directory with **many** entries (files/dirs, at least 19 973 of them). restic then serializes the information on it as JSON, which leads to a JSON document of more than 300MiB, which restic fails to upload.

This is indeed a limitation in restic, we need to add code to upload such large files via the API (which must be done differently).

**Comment by francoismiquel** [comment]
Yes, i have folder with 21134 entries.

Ok, that is the limitation of Restic due to his mode of operation.

Are you going to make a fix?

If so, I will follow developments closely ;-)

**Comment by francoismiquel** [comment]
Wow, you're fast ! 

I need to build my own release from the master branch or will you published a new release ? 

Thanks

**Comment by francoismiquel** [comment]
New code not merge in master branch for now.

I'll be waiting for it ;-)

Thank you !

**Comment by fd0** [comment]
It's merged now, you can find beta binaries on https://beta.restic.net/?sort=time&order=desc, everything after `v0.9.0-18` contains the fix.
