### ISSUE TITLE
restic find

### ISSUE THREAD

**Issue by Nonstop999** [restic/restic#1823]
I want to find all file that in specific date time.
somehow it work only if i know the filename.

I have try didn't work.

`restic find '*' -s dcd15c38 -O '2018-05-20 00:00'`

And how to restore file's find.

Thank you

**Comment by fd0** [comment]
This may be a bug, would you mind filling out the issue template?

**Comment by fd0** [comment]
I think this is the same underlying issue as #1825.

**Comment by mholt** [comment]
@Nonstop999 Can you build from the latest `master` branch and try again? It's possible that it was fixed in a recent commit.

**Comment by fd0** [comment]
I've verified that it's resolved in the latest master branch. Thanks for pointing out this issue!
