### ISSUE TITLE
tls: handshake message of length 10066439 bytes exceeds maximum of 65536 bytes

### ISSUE THREAD

**Issue by Markusli** [restic/restic#1826]
## Output of `restic version`

restic 0.8.3
compiled with go1.10 on linux/amd64

## How did you run restic exactly?

I have a script that populates environment:  
```
unset HISTFILE
export AWS_ACCESS_KEY_ID=XXXX
export AWS_SECRET_ACCESS_KEY=XXXXX
export RESTIC_REPOSITORY="s3:https://s3.amazonaws.com/xxxxxxxx"
export RESTIC_PASSWORD="XXXXXX"
```
Then I have a script that runs the backup:  

#!/usr/bin/env bash
```
source <env-populating-file>
restic --exclude={/dev,/media,/proc,/run,/sys,/tmp,/var/tmp,/mnt/*.swap,/var/run,/var/cache,/lib,/lib64,.cache,.pyc} backup /
restic forget --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 5
restic prune
restic check
```

When running the backup script I get the following output:

```
password is correct
scan [/]
scanned 349725 directories, 2651882 files in 7:04
Save(<data/1b292f47f4>) returned error, retrying after 473.946327ms: client.PutObject: Put https://mt-vegan-backup.s3-eu-central-1.amazonaws.com/data/1b/1b292f47f4612bcd5b2882aca1afe2066c0875dbe983c4ed543dc6ef8a765ead: net/http: HTTP/1.x transport connection broken: write tcp 192.168.1.110:50630->52.219.72.21:443: write: connection reset by peer
Save(<data/abc3824246>) returned error, retrying after 300.360561ms: client.PutObject: Put https://mt-vegan-backup.s3-eu-central-1.amazonaws.com/data/ab/abc3824246d997fdd68013d16f8d5af55e98a8319873c1e57ba1c3c896dab94a: tls: handshake message of length 10066439 bytes exceeds maximum of 65536 bytes
password is correct GiB / 960.853 GiB  5668 / 3001607 items  0 errors  ETA 27:12:05 
```

## What backend/server/service did you use to store the repository?

AWS S3

## Expected behavior

Backups complete and get checked.

## Actual behavior

Failure to backup with the following error message:

```
Save(<data/1b292f47f4>) returned error, retrying after 473.946327ms: client.PutObject: Put https://mt-vegan-backup.s3-eu-central-1.amazonaws.com/data/1b/1b292f47f4612bcd5b2882aca1afe2066c0875dbe983c4ed543dc6ef8a765ead: net/http: HTTP/1.x transport connection broken: write tcp 192.168.1.110:50630->52.219.72.21:443: write: connection reset by peer
Save(<data/abc3824246>) returned error, retrying after 300.360561ms: client.PutObject: Put https://mt-vegan-backup.s3-eu-central-1.amazonaws.com/data/ab/abc3824246d997fdd68013d16f8d5af55e98a8319873c1e57ba1c3c896dab94a: tls: handshake message of length 10066439 bytes exceeds maximum of 65536 bytes
```

## Steps to reproduce the behavior

Try to backup to S3 with the version of restic used here and the scripts used here.

## Do you have any idea what may have caused this?

No.

## Do you have an idea how to solve the issue?

No. I've actually tried the 0.9 version too. This fails as well and also prints out the path of every file that it uploads so finding the error message gets more complicated.

## Did restic help you or made you happy in any way?

So far no. I've tried backing up with it to both S3 and GCP and it somehow continues to fail me. Maybe something's wrong with me? I'm behind Fortigate SSLVPN, but some of the errors I get seem completely unrelated.

**Comment by francoismiquel** [comment]
Hello,

I have the same issue with Restic, but with backend Azure (https://github.com/restic/restic/issues/1822).

I discover that this @fd0  after trying this : 

- Create a new local repository
- Backup the same dataset
- Find a file bigger than 64 MB

If you are on Linux system : <code> sudo find /repo_path/data -size +64M

You should have results. If so, you are in the same situation as me

It's a bug of Restic and @fd0 is aware of the situation

**Comment by francoismiquel** [comment]
Ok, my apologies. The error message <code> length 10066439 bytes exceeds maximum of 65536 bytes </code> seemed to really match with my problem, but on Amazon. Sorry.

**Comment by fd0** [comment]
Don't worry, I can understand why you thought it might be related ;)

**Comment by Markusli** [comment]
Thanks for the reply @fd0!
I didn't interrupt it, it crashed on its own without further messages. I previously had tls: Bad MAC record errors, but these seemed to go away once sysadmin switched the Fortigate VPN SSL port to 443 not 8000 that it was set to.

The issues with 0.9 error messages was that it printed all filenames that were processed and so buried the error lines (and also turned tmux cpu usage to 100%). 
But this might have been some other issue, as currently I can't reporduce this. Will try some more and post here when I manage to reproduce this.

 So you say I should look further into the Fortigate device?

**Comment by fd0** [comment]
Since we haven't received any feedback in a long time I'm closing this issue for now. Please add a comment or open a new issue if the problem persists. Thanks!
