### ISSUE TITLE
Restic deduplication not workiing as expected

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [restic/restic#1829]
## Output of `restic version`
restic 0.8.3 (v0.8.3-266-g9f5565b0) compiled with go1.10.2 on linux/amd64

## How did you run restic exactly?

export RESTIC_REPOSITORY="/run/media/Seagate EXT"
export RESTIC_PASSWORD="foo"
restic init
[user@host Seagate EXT]$ restic backup --verbose --exclude-file=/usr/local/etc/restic-exclude.txt .

Added: 125.150
processed 26122 files, 189.374 GiB in 3:53:54

## What backend/server/service did you use to store the repository?
local external storage

## Expected behavior

Restic deduplication should have considerably reduced the size of the backup that was restored because I had several larger folders ( 15 G < folderSize < 50 ) with overlapping data, expected 125.150 GB to be restored as shown above.
## Actual behavior
Instead restic restored exactly thesame total size (i.e. 190 GB) of the directories before the backup process (i.e. the processed size) so there was no change.
```
# restic restore a332d674 --verbose --target /home/user/myFolder
repository 8g334gda opened successfully, password is correct
restoring <Snapshot c223s445 of [/run/media/Seagate EXT"] at 2018-05-24 18:08:42.660621652 +0100 BST by user@host> to /home/user/myFolder

# du -sh /home/user/myFolder
190G /home/user/myFolder
```

## Steps to reproduce the behavior
test deduplication

## Do you have any idea what may have caused this?

No but the large folders which shared overlapping data consisted of documents and a lot of .cfd and .cad simulation files. Is restic deduplication restricted to certain file formats?

## Do you have an idea how to solve the issue?

No but I planned my backups to make use of restics deduplication abilities and it would be nice to get it working.

**Comment by dionorgua** [comment]
Hi,

As far as I understand, you've some identical files in your ~190GB directory. So you've performed backup of your data via `restic backup` and then restored data using `restic restore`. And now you are expecting that after restore you'll get smaller amount of data. 

I think that you're using just wrong tool for this. `restic` provide deduplication only for it's storage. So by performing backup of two large files with same content restic will consume that space only once (this is how deduplication work). But once restored, you'll get exactly same directory with two files as it was before.

If you want just to get rid of duplicate files in directory by replacing them with hardlinks or something like this, you should consider some other tools like `rmlint`.

**Comment by ChukwuemezieChristopherAneke** [comment]
Thanks @dionorgua  for clarifying how restic's deduplication actually works. My mistake was thinking that the deduplication carried over to the restoration and not just for storage. According to what your telling me then restic's deduplication does thesame thing as tar only that tar uses compression to make archives smaller. 

I read a bit about rmlint, its exactly what I am looking for, thanks.
I will go ahead and close this now.

**Comment by fd0** [comment]
Thanks for helping out @dionorgua!
