### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by tharale** [restic/restic#1832]
Hi,
I would like to ask a couple of questions before I download and use.

Will Restic preserve the file permissions of the data it backs up and also how do I restore from scratch say if my system is blown up and I loose all local data. That is, is it possible to have a boot CD that I boot from and restores my system from the backup?

Please help...

Alex.

**Comment by dimejo** [comment]
> I  would like to ask a couple of questions before I download and use.

In general, [the forum](https://forum.restic.net/) is a better place to ask questions and get help.

> Will Restic preserve the file permissions of the data it backs up

Yes.

> how do I restore from scratch say if my system is blown up and I loose all local data. That is, is it possible to have a boot CD that I boot from and restores my system from the backup?

You can always use a Live CD to restore a backup onto a disk. But beware that restoring from a complete disk/system failure is more complicated than simply restoring some files. There was a [discussion on the forum](https://forum.restic.net/t/lack-of-documentation-on-how-to-do-a-full-system-back-up/659/17) about this topic.

If you are looking for a tool which was designed to do a full system recovery you should probably take a look at [Relax-and-Recover (Rear)](http://relax-and-recover.org/) or [Clonezilla](https://clonezilla.org/).

**Comment by fd0** [comment]
I think the question is answered, if not please move over to the forum. We're using the issue tracker exclusively for bugs. Thanks!
