### ISSUE TITLE
NetBSD support

### ISSUE THREAD

**Issue by iquiw** [restic/restic#1847]
Hi, I'd like to add NetBSD support.
I  made changes to make `restic` built on NetBSD in the following branch.

https://github.com/iquiw/restic/tree/netbsd-support

The tests passed as [attached](https://github.com/restic/restic/files/2107955/restic-test-NetBSD.txt)
Can I send PR?

**Comment by fd0** [comment]
Please send a PR so we can discuss the code. Thanks!
