### ISSUE TITLE
makefile doesn't pick up changes in go code

### ISSUE THREAD

**Issue by fw42** [restic/restic#185]
* Run `make`
* Make changes to some .go source files
* Run `make` again or run `make test`. Thing will not get recompiled (unless you delete the `restic` binary).

Also, `make -B` (force a rebuild) is broken because the symlink already exists.

**Comment by fd0** [comment]
I've addressed most of this in #188, but I can't reproduce that `make test` isn't run. It's in the `.PHONY` list, so make should always run `go test`. Could you clarify on that?

**Comment by fd0** [comment]
I've reopened this issue to clarify what happens on `make test`.

**Comment by fd0** [comment]
The `Makefile` isn't really used any more, it's only present for convenience, so I'll close this bug.
