### ISSUE TITLE
URL broken: https://github.com/restic/restic/blob/master/doc/design.rst

### ISSUE THREAD

**Issue by SebastianApel** [restic/restic#1852]
Hi, the "Design Documentation" is referenced from several locations in the forum and in other sources. But Github shows a http 404 response:

URL: https://github.com/restic/restic/blob/master/doc/design.rst
Expected behaviour: See the design doc. If that's not possible (or desired), maybe put a small document there that explains where the information can be found now...
Cheers,
Sebastian

**Comment by fd0** [comment]
Good point, thanks for the hint. I've pushed a commit which moves the design document back to `doc/design.rst`, so the links will work again.
