### ISSUE TITLE
Backing up multiple filesystems at different mountpoints fails with --one-file-system (-x)

### ISSUE THREAD

**Issue by JPPhoto** [restic/restic#1854]
## Output of `restic version`
restic 0.9.0 compiled with go1.10.2 on linux/amd64

## How did you run restic exactly?
restic -r sftp:backup:/restic backup -x -e "/mnt/Z/backups/dir1" / /mnt/Z/backups

## What backend/server/service did you use to store the repository?
sftp

## Expected behavior
I expected / and /mnt/Z/backups to be backed up, but /mnt/Z/backups/dir1 to be excluded from the backup. Getting a snapshot listing shows /mnt/Z/backups, but nothing from that path is visible in a listing (ls -l) of the snapshot.

## Actual behavior
Restic backed up /, without traversing any other mounted filesystems - including /mnt/Z/backups.

## Steps to reproduce the behavior
Run restic with multiple filesystems as command line arguments and --one-file-system. I don't believe excluding a directory has anything to do with the issue at hand.

## Do you have any idea what may have caused this?
I believe restic is using the first path on the backup command line as its source filesystem for checking against with --one-file-system instead of treating each path on the command line as its own source filesystem for traversal of that path.

## Do you have an idea how to solve the issue?
No. In the past I'd backed up all paths individually but now with fixes to 0.9.0 I wanted to back them all up in a single command line. I can return to backing things up individually but that's a workaround.

## Did restic help you or made you happy in any way?
I love restic!

**Comment by JPPhoto** [comment]
This looks like the same issue as in #907, #908, etc.

**Comment by fd0** [comment]
Can you please paste the output of `findmnt /mnt/Z/backups`, so I can understand what the structure is?

**Comment by JPPhoto** [comment]
TARGET SOURCE   FSTYPE OPTIONS
/mnt/Z /dev/md2 ext4   rw,relatime,errors=remount-ro,user_xattr,barrier=1,stripe=76...

**Comment by fd0** [comment]
Ah, I've edited the message after you've read it, can you paste the output of `findmnt`, for the whole system?

**Comment by JPPhoto** [comment]
It's hard to do this from my phone but basically, / is one md array and /mnt/Z is a mount point for a different md array.

**Comment by fd0** [comment]
Ok, thanks for the confirmation. So what you tried to do was backup `/` without e.g. `/sys` and `/dev` and so on, but including `/mnt/Z/backups` (which resides on a different file system, `/mnt/Z`), is that right?

**Comment by fd0** [comment]
I can reproduce it, thanks!

**Comment by fd0** [comment]
Unfortunately it's rather complex. T

**Comment by fd0** [comment]
Unfortunately it's rather complex. The first thing the restic archiver code does is to build a tree of the target files/directories. If it detects that a parent directory is already included (e.g. `restic backup /foo /foo/bar/baz`), it'll ignore or prune it from the tree. This is the case her.

Without `--one-file-system`, that's perfectly valid: If `/foo` is to be archived, it will include `/foo/bar/baz`. But with `--one-file-system`, `/foo/bar/baz` may reside on a different file system, so it won't be included with `/foo`.

I'm not sure how to solve that, I'm leaving the cause here as a comment (so I don't have to find the cause of the issue again later) ;)

**Comment by JPPhoto** [comment]
I think that's valid behavior IF any given directory is part of the same filesystem as the initial path given in the traversal. Perhaps the resulting backup set should instead be a union of traversals of each path with exclusions, single file systems, etc. applied. Or maybe you can do the exlusions and options earlier in the evaluation rather than at the end (if I'm understanding this correctly).

**Comment by fd0** [comment]
Would you mind testing if the code in the branch `fix-1854` resolves this issue? You can easily build restic yourself just by running `go run build.go`...

Please report back!

**Comment by JPPhoto** [comment]
I'll try to get to it later tonight. I have to find a box with go installed or install it on a dev VM.

**Comment by JPPhoto** [comment]
I'm testing it now. Preliminary results look good. I'll confirm tomorrow morning.

**Comment by JPPhoto** [comment]
Looks like that works! I haven't tried the case where --one-file-system isn't specified; maybe that's something you can test.

**Comment by fd0** [comment]
Thanks for the feedback, I've tested that myself (and we've pretty extensive tests for it).
