### ISSUE TITLE
Cannot exclude files with --exclude-file, which have a $DOLLAR sign

### ISSUE THREAD

**Issue by bjoe2k4** [restic/restic#1857]
## Output of `restic version`
$ restic version
restic 0.9.1 compiled with go1.10.3 on linux/amd64

## How did you run restic exactly?

`restic -r restictest -v -v --exclude-file ex.txt backup testdir`

`ex.txt`
```
$bc
\\$bc
\\\\$bc
a$c
a\\$c
a\\\\$c
ab$
```
```
$ find testdir
testdir
testdir/$bc
testdir/ab$
testdir/a$c
```

## What backend/server/service did you use to store the repository?

local folder

## Expected behavior

```
start scan on [testdir]
start backup on [testdir]
scan finished in 3.744s: 0 files, 0 B
```

## Actual behavior

```
start scan on [testdir]
start backup on [testdir]
scan finished in 4.335s: 2 files, 0 B
new       /testdir/$bc, saved in 0.007s (0 B added)
new       /testdir/a$c, saved in 0.000s (0 B added)
```

## Steps to reproduce the behavior

```
mkdir testdir restictest
touch testdir/\$bc testdir/a\$c testdir/ab\$
restic -r restictest init
#create ex.txt from above
```

## Do you have any idea what may have caused this?
I have the suspicion that somewhere variables might be expanded since `$` at the end of the file name is not affected.

## Do you have an idea how to solve the issue?
sorry, not familiar with golang, but the code is surprisingly easy to read. After reading the code i think
https://github.com/restic/restic/blob/63779c1eb4d7136099203cd53e841e90c1d6a80b/cmd/restic/cmd_backup.go#L261 is responsible.

```
package main
import (
    "fmt"
    "os"
)
func main() {
    fmt.Printf("%s\n",os.ExpandEnv("ab$"))
    fmt.Printf("%s\n",os.ExpandEnv("a$c"))
    fmt.Printf("%s\n",os.ExpandEnv("$bc"))
}
```
results in (compiled and execute on my Windows Desktop, note that the third line is an empty line):
```
PS C:\UsersUser\go> .\go.exe
ab$
a

```

The question is, if environment variables need to be expanded at all in this case, since i could not find any documentation about it in the restic docs. A workaround (taken from https://github.com/michaelsauter/crane/issues/51, which also mentions another workaround by replacing os.ExpandEnv with a custom version and allows `$$` as an excape sequence for a literal `$`) seems to be to declare an environment variable `DOLLAR=$` and use the following `ex.txt`:
```
${DOLLAR}bc
a${DOLLAR}c
ab${DOLLAR}
```
Custom ExpandEnv:
https://github.com/bjaglin/crane/blob/997332f8cf4ff10b77b297a15013b3ba43b5375f/crane/crane.go#L163-L167

the `--exclude` option does not expand environment variables, since the following command works as expected:
```
restic -r restictest -v -v --exclude='$bc' --exclude='a$c' --exclude='ab$' backup testdir
```

This also explains the problems mentioned in https://github.com/restic/restic/issues/722.

Whatever solution will be taken, i think `--exclude-file` and `--exclude` should behave the same way. If not, it should be documented accordingly.

## Did restic help you or made you happy in any way?

restic has become my primary backup program which i use every day - interactive and automatic. Thank you may times for the countless hours of developing and debugging. Cannot wait for new features like compression ;-)

**Comment by fd0** [comment]
Hey, thanks for the report. I consider this a bug. I like the workaround you've already found, adding a special `$$` escape for a literal dollar sign, by using `os.Expand` with a custom function instead of `os.ExpandEnv`. I'll quickly do that now.

It's documented in the manual that environment variables are expanded in exclude files by restic, and only there. For command-line arguments, it's the same as with #722: the shell is responsible and will do that for us. Implementing it again leads to all sorts of nasty problems very similar to the one you've described in this issues.

**Comment by bjoe2k4** [comment]
Thanks! Must have overseen this in the docs.
