### ISSUE TITLE
New logo for Restic

### ISSUE THREAD

**Issue by reallinfo** [restic/restic#1859]
Hello @fd0 @restic

I want to contribute to open source software by designing logos. If you like, I can design a logo for the restic. What do you think?

**Comment by fd0** [comment]
Thank you very much for the offer! At the moment I'm quite happy with the logo we have (the umbrella gopher), which was also contributed...

**Comment by reallinfo** [comment]
Oh, okay :) If you need a logo for another project, you can contact me.

**Comment by reallinfo** [comment]
Btw, I've already designed a logo. If you want to see more logo sample visit my profile. As I said, do not hesitate to write to me. 

Have a nice day!

![restic](https://user-images.githubusercontent.com/36298335/41812144-fd213656-7725-11e8-8112-14cea91b53d3.jpg)

**Comment by fd0** [comment]
Thank you very much for the offer, we'll keep the Gopher for now and I'll let you know should that change. Thanks!
