### ISSUE TITLE
restic find -i (case insensitive) buggy in v0.9.1

### ISSUE THREAD

**Issue by McKael** [restic/restic#1862]
## Output of `restic version`

restic 0.9.1

## Actual behavior

`restic find -i PATTERN` is broken in restic 0.9.1, when the file/directory contains uppercase characters.

## Do you have any idea what may have caused this?

I believe this is related to the code refactoring that introduced walker.Walk() into the find command.

## Do you have an idea how to solve the issue?

I've created PR https://github.com/restic/restic/pull/1861

## Did restic help you or made you happy in any way?

Sure, I know I can mess with my data...

**Comment by fd0** [comment]
Resolved in #1861
