### ISSUE TITLE
backup statistics: wrong number of Dirs!

### ISSUE THREAD

**Issue by bjoe2k4** [restic/restic#1863]
## Output of `restic version`
restic 0.9.1 compiled with go1.10.3 on linux/amd64

## How did you run restic exactly?
`restic -r restictest backup oxygen`

## What backend/server/service did you use to store the repository?
local folder

## Expected behavior
```
$ restic -r restictest init
$ restic -r restictest backup oxygen
 Files:       45629 new,     0 changed,     0 unmodified
 Dirs:     12549 new,     0 changed,     0 unmodified
 Added:      140.442 MiB
$ find oxygen -type d | wc -l
 12549
$ mkdir oxygen/testdir
$ echo "test" > oxygen/testdir/test.txt
$ find oxygen -type d | wc -l
 12550
$ restic -r restictest backup oxygen
Files:           1 new,     0 changed, 45629 unmodified
Dirs:            1 new,     0 changed, 12549 unmodified
Added:      376 B
```

## Actual behavior
```
$ restic -r restictest init
$ restic -r restictest backup oxygen
 Files:       45629 new,     0 changed,     0 unmodified
 Dirs:            0 new,     0 changed,     0 unmodified
 Added:      140.442 MiB
$ find oxygen -type d | wc -l
 12549
$ mkdir oxygen/testdir
$ echo "test" > oxygen/testdir/test.txt
$ find oxygen -type d | wc -l
 12550
$ restic -r restictest backup oxygen
Files:           1 new,     0 changed, 45629 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added:      376 B
```

## Steps to reproduce the behavior
see above

## Do you have any idea what may have caused this?
Not really. Also not sure if it was different before since i started using restic only recently.

According to the docs, I assume it was working before:
http://restic.readthedocs.io/en/latest/040_backup.html

## Do you have an idea how to solve the issue?
Maybe some bug introduced with the new archiver?

## Did restic help you or made you happy in any way?
restic is super!

**Comment by bjoe2k4** [comment]
Considering that this issue is nearing an age of 2y and the dircount in the output is something users are confronted with every time they make a backup, are there any intentions to get this fixed?

Looking at the recent commit history i see there is a lot of fine tuning going on. So how about just removing the counter completely for the time being? After all `restic stats` doesn't report the dircount either.

**Comment by MichaelEischer** [comment]
I have a fix for this issue, it just needs a test then I'll open a PR for it.

**Comment by darkdragon-001** [comment]
Thanks to @dp-github for the hint in https://github.com/restic/restic/issues/2508#issuecomment-642785030 that _directories changed_  doesn't make sense.

@MichaelEischer Could you remove the output of directories changed since this is always 0 by definition (renames are not tracked, right?).

**Comment by MichaelEischer** [comment]
> @MichaelEischer Could you remove the output of directories changed since this is always 0 by definition (renames are not tracked, right?).

No, it is not always zero. _directories changed_ refers to whether the content of a directory has changed. That is after renaming a file, the containing directory will count as changed. If you rename a directory then that will count as one removal and one addition, that is the behavior is basically equivalent to that for files.

**Comment by dp-github** [comment]
> the content of a directory has changed

I assume this means that the following will be counted as directory changes:
* Adding files or directories within a directory
* Removing files or directories within a directory

But the following will not be counted as directory changes:
* Altering the contents of a file within a directory
* Altering the metadata for a file within a directory
* Altering the metadata for a directory within a directory 
* Altering the contents of a directory within a directory (i.e. no recursion when tracking directory changes)


Is that all correct?

**Comment by MichaelEischer** [comment]
> > the content of a directory has changed
> 
> I assume this means that the following will be counted as directory changes:

I took another look at the exact implementation: What happens is that all of the points you've mentioned count as a change. That is a changed directory is one for which restic had to upload the tree again.

As a directory/tree contains the hashes of all contained files, direct subdirectories and metadata for each element in the directory, this means that any change to arbitrarily deeply nested subdirectories also changes the parent directories.
