### ISSUE TITLE
Data load failed on prune

### ISSUE THREAD

**Issue by sascha-andres** [restic/restic#1864]
## Output of `restic version`

restic version: 0.9.1

## How did you run restic exactly?

restic -r rest:http://server:8000 -p ~/.restic-password prune

Output of command:

    repository dfdfdcf8 opened successfully, password is correct
    counting files in repo
    building new index for repo
    [0:00] 100.00%  6789 / 6789 packs
    repository contains 6789 packs (340146 blobs) with 31.881 GiB
    processed 340146 blobs: 40565 duplicate blobs, 526.955 MiB duplicate
    load all snapshots
    find data that is still in use for 10 snapshots
    [0:13] 100.00%  10 / 10 snapshots
    found 294322 of 340146 data blobs still in use, removing 45824 blobs
    will remove 0 invalid files
    will delete 22 packs and rewrite 218 packs, this frees 726.468 MiB
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 510.663857ms: unexpected EOF
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 924.624999ms: unexpected EOF
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 724.591722ms: unexpected EOF
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 2.260853386s: unexpected EOF
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 3.524390437s: unexpected EOF
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 3.671670787s: unexpected EOF
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 2.931187255s: unexpected EOF
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 8.282989639s: unexpected EOF
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 9.228605943s: unexpected EOF
    Load(<data/719633af1d>, 0, 0) returned error, retrying after 9.970940036s: unexpected EOF
    hash does not match id: want 719633af1d49b464f172266c08872f9d62e7d11a8930487ce839b2246ad626e4, got 98f551548e2bbbcf493f49321c3b6c13a764239303d8c60a2e156bde8c10adaa
    github.com/restic/restic/internal/repository.Repack
            src/github.com/restic/restic/internal/repository/repack.go:35
    main.pruneRepository
            src/github.com/restic/restic/cmd/restic/cmd_prune.go:278
    main.runPrune
            src/github.com/restic/restic/cmd/restic/cmd_prune.go:85
    main.glob..func18
            src/github.com/restic/restic/cmd/restic/cmd_prune.go:25
    github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
            src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:756
    github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
            src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:846
    github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
            src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:794
    main.main
            src/github.com/restic/restic/cmd/restic/main.go:86
    runtime.main
            /usr/local/go/src/runtime/proc.go:198
    runtime.goexit
            /usr/local/go/src/runtime/asm_amd64.s:2361

Anyhow, I can append and forget

## What backend/server/service did you use to store the repository?

rest

## Expected behavior

A successful cleanup

## Actual behavior

Not cleaning up the repository

## Steps to reproduce the behavior

Running the command above

## Do you have any idea what may have caused this?

no

## Do you have an idea how to solve the issue?

no

## Did restic help you or made you happy in any way?

Saved me a lot of work rebuilding a vm as I had a backup

**Comment by fd0** [comment]
Thanks for the report! Would you mind retrying with a fresh cache directory, removing `~/.cache/restic`?

**Comment by sascha-andres** [comment]
Tried but has not helped. I reset the server repository and will observe what happens

**Comment by fd0** [comment]
You can also try running `sha256sum` on the file in question on the server, or running `restic check --read-data`...

**Comment by sascha-andres** [comment]
check --read-data printed out no error

**Comment by fd0** [comment]
I think this has been resolved by #2099, which is contained in restic 0.9.4 and later, so I'm closing this issue for now. Please add a comment or open a new issue if the problem persists. Thanks!
