### ISSUE TITLE
Empty directories are omitted from 'restic ls'

### ISSUE THREAD

**Issue by roeebar** [restic/restic#1865]
## Output of `restic version`

`restic compiled manually compiled with go1.10.2 on freebsd/amd64`
but it's actually restic 0.9.1

## How did you run restic exactly?
`restic ls -r b2:<my-bucket> latest`

## What backend/server/service did you use to store the repository?
Backblaze B2

## Expected behavior
List all files, including empty directories, e.g.

    /mnt/dir
    /mnt/dir/file
    /mnt/empty-dir
 
## Actual behavior
Empty directories are omitted from the output:

    /mnt/dir
    /mnt/dir/file

Empty directories are actually stored in the snapshot (verified by mounting the snapshot), but are not displayed in `ls` output.

**Comment by fd0** [comment]
Thanks for the report, this issue has already come up as #1849 and is already resolved in master. You can find compiled binaries of the restic master branch here: https://beta.restic.net/?sort=time&order=desc

I'm closing this as a duplicate.
