### ISSUE TITLE
Files missing at restore: "not found in repository"

### ISSUE THREAD

**Issue by johndoe31415** [restic/restic#1868]
## Output of `restic version`
restic 0.8.3 (v0.8.3-0-g272ccec7)
compiled with go1.10.1 on linux/amd64

## How did you run restic exactly?
```
# restic  -p /etc/restic_key.txt -r sftp:backup:/data/joe/restic restore 2f7b5f23 -t .
password is correct
found 1 old cache directories in /root/.cache/restic, pass --cleanup-cache to remove them
load <index/a3c299ed05>: invalid data returned, ignoring
load <index/715e196044>: invalid data returned, ignoring
load <index/329507db1d>: invalid data returned, ignoring
restoring <Snapshot 2f7b5f23 of [/] at 2018-06-28 11:39:35.792757667 +0200 CEST by root@reliant> to .
ignoring error for /boot/initrd.img-4.16.5: id acd4ea6ae2b9e2cc03f5dcd658d623d734a3be69928b5092644b26666af6bcdb not found in repository
ignoring error for /etc/X11: tree 9d22fff0b2aedd2ebdd59b0abdcd73196ce7c17d2fa3416e6cbd6d0f8357b349 not found in repository
ignoring error for /etc/apt: tree 432b17f94ba76ec240481354ba5061ccb9fa19cb175f0961aa5ed66f09163286 not found in repository
ignoring error for /etc/dbus-1: tree cf72a8a9880b3fab2b3411d5d75596af0b58a6571ab9a0275b9b9021204acc08 not found in repository
ignoring error for /etc/fonts: tree d00a2faf99cc53457e2596327ed8b11d75b325a9155c11de2f34fa08eac1faab not found in repository
ignoring error for /etc/kernel: tree 243a80e77ef089d14e16d3a98424c8a3024b8c0f68ced11720bae5334cd9367c not found in repository
ignoring error for /etc/menu: tree e3ac613ed9aef3a92fb905efe65e9b20f7809f06f152ca9f9eb280226f5de562 not found in repository
ignoring error for /etc/menu-methods: tree d16d7ed53392ad4c0a9631017ae10118d16e2cccc3e0cec03f06f5a5934a8fde not found in repository
ignoring error for /etc/passwd: id 4d0df51284ed600601418798f19d5fcf0cd267f78974368b12c4a1cd2b231400 not found in repository
ignoring error for /etc/passwd-: id a5ef2266dc6d1e1eb8a0a31b2400d4b257bcd4dbdd23b38f65455b7ff577d136 not found in repository
ignoring error for /etc/shadow: id a4fe64b9cd2f2dd6c2238bae872777f271835efe97643757ff96a589086fd1a0 not found in repository
ignoring error for /etc/shadow-: id a4fe64b9cd2f2dd6c2238bae872777f271835efe97643757ff96a589086fd1a0 not found in repository
ignoring error for /etc/systemd: tree 4c037ba7ade1984cb5115f1adf5ac38298d191c01a4b10203a09fa402091aa0a not found in repository
[...]
```

## What backend/server/service did you use to store the repository?
sftp.

## Expected behavior
I expect restic to fully restore the backup. However, some files are missing from my regular backups.

## Actual behavior
Files are missing, especially some (/etc/passwd, /etc/shadow) that are *critical* for a full system restore. Luckily this was only a test, I'm doing hard disk migration in the background and was trying to check my backup fidelity at the same time. Turns out fidelity isn't given, even though I regularly run checks like this:

```
$ restic check --read-data -r /data/joe/restic/
enter password for repository: 
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
read all data
[6:08:30] 100.00%  297661 / 297661 items

duration: 6:08:30
no errors were found
```

These issue was *not* discovered. I.e., in the worst case I would not have been able to recover my backup (at least not fully to a point where I get back a usable system).

## Steps to reproduce the behavior
Try to restore from backup?

## Do you have any idea what may have caused this?
Unfortunately not. Not doing anything fancy or weird.

## Do you have an idea how to solve the issue?
"restic check" should at least discover that full system recovery isn't possible because blobs are missing. But then again, they shouldn't be missing in the first place. Actually, fun fact. The files aren't missing. Here's what happens when I fusemount the volume:

```
reliant joe [~/back/ids/2f7b5f23/etc]: ls -l passwd
-rw-r--r-- 1 root root 2747   26.06.2018 15:57:17 passwd
```

So the file *is* there. Just "restic restore" doesn't find it for some reason, while "restic mount" does.

## Did restic help you or made you happy in any way?
Restic's great, but this really is a *bad* issue. I need to be able to trust my backups and this has dented my confidence quite a bit.

**Comment by fd0** [comment]
Thanks for the report! I have a hunch what's going on here, would you mind testing restore again, but using a new cache directory, e.g. passing `--cache-dir ~/.restic-cache-restore-test` (and the dir must not exist before)?

**Comment by fd0** [comment]
I've thought about this for a bit, and I'm confident that the repo is fine and consistent and the data is still there (that's why `restic check` does not return any errors), but the index files in the local cache within `~/.cache/restic` are corrupt. It looks like restic does not handle this situation well. Using a new, pristine cache directory or disabling the cache entirely will temporarily resolve this and allow you to restore all files.

As a side effect, running `restic rebuild-index` would also work, because it creates a new index and removes the corrupt files from the cache.

So, first I'd like to confirm that my hunch is correct (and your data is in the repo and can be restored), then we can fix this issue.

**Comment by johndoe31415** [comment]
You're right -- with the "--cache-dir" switch, the restore worked flawlessly. Faith restored :-)

I'll try out 0.9.1 as well to check if this issue is fixed there.

**Comment by fd0** [comment]
> You're right -- with the "--cache-dir" switch, the restore worked flawlessly. Faith restored :-)

Phew, crises averted. :)

Since you've verified that the issue isn't present in 0.9.1, is it okay to close it? Or is there anything we still need to do?

**Comment by johndoe31415** [comment]
Absolutely okay to close it -- I just though you wanted to do it. I'm closing it :-)

Thanks again for the super quick help!
