### ISSUE TITLE
Empty hosts directory with fuse mount

### ISSUE THREAD

**Issue by OlliC** [restic/restic#1869]
## Output of `restic version`
restic 0.9.1 compiled with go1.10.2 on linux/amd64

## How did you run restic exactly?
restic -r /run/media/user/OffsiteBackup/restic-repo mount /mnt/backupTmpMount
enter password for repository: 
repository 7e9143e0 opened successfully, password is correct
Now serving the repository at /mnt/backupTmpMount
Don't forget to umount after quitting!

## What backend/server/service did you use to store the repository?
local backend on an external 1TB hdd connected via usb formatted with ext4 

## Expected behavior
The restic repo has snapshots from two hosts. Sometimes when i mount the repo with fuse the hosts directory is empty in the fuse mount. It does not happen on every mount. I did not found a working pattern, but unmounting and mounting again works sometimes. Every other directory in the fuse mount is always filled correctly (ids, snapshots, etc.). 

## Actual behavior
The hosts directory in the fuse mount is empty more often than not.

## Steps to reproduce the behavior
1. Mount a restic repo with fuse
2. Check if hosts directory is empty 

## Do you have any idea what may have caused this?
No

## Do you have an idea how to solve the issue?
No

## Did restic help you or made you happy in any way?
Yes, restic is very cool. Using it now for two of my three backups. The other one is borg ;-)

**Comment by fd0** [comment]
Thanks for the report. Can you please paste the output of `restic snapshots` here? Let's see if the hostname field is correctly filled.

**Comment by OlliC** [comment]
Yes, no problem. But i have deleted the directory information.

```
$ restic -r /run/media/user/OffsiteBackup/restic-repo snapshots 
enter password for repository: 
repository 7e9143e0 opened successfully, password is correct
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
21fe9bce  2018-06-15 13:15:57  viki  
209d400c  2018-06-19 17:03:10  redqueen   
83663536  2018-06-23 18:00:04  redqueen  
74f8bb5f  2018-06-23 20:52:09  redqueen   
6b66a0b1  2018-06-25 17:49:42  redqueen     
25dc5702  2018-06-25 18:06:20  redqueen     
488134d2  2018-06-26 14:37:25  redqueen       
c8342f00  2018-06-26 15:02:45  redqueen      
7df7b1cb  2018-06-26 20:17:48  viki       
d4a34916  2018-06-26 21:42:37  viki        keys  
42d828d1  2018-07-01 14:16:06  redqueen    
----------------------------------------------------------------------
11 snapshots
```

**Comment by OlliC** [comment]
Would it help if run a debug version of restic while mounting my repo? Dont know if you can reproduce this or not.

**Comment by fd0** [comment]
Yes, that might help. You can remove the debug log before running `restic mount` and only keep the log where the issue occurs, maybe we can see something...

**Comment by OlliC** [comment]
Ok i have the log and the hosts directory is also empty in this run. Is it safe to post the log here? Does it contain the repo password somewhere? I only saw my username and repo path which are fine for me to post.

**Comment by sorcix** [comment]
I'm having the same issue.

```
$ restic version
restic 0.9.2 compiled with go1.10.3 on linux/amd64
```

Snapshots list works (I've removed most of them):
```
$ restic -v --repo rclone:dropbox:Backup snapshots   
enter password for repository: 
repository 6d460b29 opened successfully, password is correct
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
abc426a8  2018-05-12 07:57:26  seraph                  /
c3529eb7  2018-05-12 09:10:19  morpheus                /
479d653d  2018-05-15 19:07:36  seraph                  /
bda20323  2018-05-16 11:32:35  seraph                  /
feb92801  2018-06-29 20:08:51  morpheus                /
ddb9f0c3  2018-07-02 23:52:44  morpheus                /
f239c7aa  2018-07-03 09:11:49  seraph                  /
0cd01eaf  2018-07-11 16:28:13  seraph                  /
2fb63983  2018-07-12 10:33:48  seraph                  /
5f5eabb8  2018-07-17 21:23:04  morpheus                /
f22baeb6  2018-08-16 11:31:50  seraph                  /
8f0a6799  2018-08-20 09:45:01  seraph                  /
----------------------------------------------------------------------
41 snapshots
```

Mount seems work fine:
```
$ restic -v --repo rclone:dropbox:Backup mount backup
enter password for repository:
repository 6d460b29 opened successfully, password is correct
Now serving the repository at backup
Don't forget to umount after quitting!
```

But all directories inside the mount are empty:
```
$ find backup -ls                                                                                                                                                                                      [0/1]
        1      0 dr-xr-xr-x   1  vic      vic             0 Sep 14 11:54 backup
11966682851649564941      0 dr-xr-xr-x   1  vic      vic             0 Sep 14 11:54 backup/tags
 9551839091146849951      0 dr-xr-xr-x   1  vic      vic             0 Sep 14 11:54 backup/hosts
18047884018718799214      0 dr-xr-xr-x   1  vic      vic             0 Sep 14 11:54 backup/ids
  255262462188919481      0 dr-xr-xr-x   1  vic      vic             0 Sep 14 11:54 backup/snapshots
```

I've used the mount option with this repository before, without any issues.

**Comment by alexeymuranov** [comment]
I have just experienced a similar issue with `restic 0.9.2 compiled with go1.11 on linux/amd64`: in my case, the `snapshots` directory appeared empty in Nautilus.  The snapshots could still be seen in `hosts` subdirectories.  Remounting made the shapshots appear in `snapshots`.

**Comment by sam-artuso** [comment]
I'm experiencing the same issue too, with `restic 0.9.5 compiled with go1.12.4 on linux/amd64`.

**Comment by MichaelEischer** [comment]
Is this issue still reproducible with restic 0.10.0? We have updated the fuse library in the meantime.

**Comment by MichaelEischer** [comment]
Seems like this problem still exists in restic 0.10.0 (might also be an unrelated race condition): https://travis-ci.com/github/restic/restic/jobs/401402678

**Comment by MichaelEischer** [comment]
The snapshot directory creation has been rewritten and is now also synchronized so maybe this helps. If the issue still persists, we can reopen this issue.
