### ISSUE TITLE
Feed multi-file data to restic from external backup "helper" programs and scripts.

### ISSUE THREAD

**Issue by tim-seoss** [restic/restic#1873]
I'd like to use restic to backup VMs.  An external program would use the virtualisation system's management APIs (in this case libvirt) to determine what data needs to be backed up (e.g. block devices, NVRAM contents etc.) and (for running VMs) create an atomic point-in-time snapshot of the data.

A backup of a VM would consist of a consistent set of: the VM metadata, and 1 or more storage blobs (which restic could just treat as files).

There isn't a method which can be used to easily do this with restic, except possibly invoking restic multiple times with the `--stdin` option, but then you end up with a single VM backup being split over multiple snapshots, which feels a bit messy...

A few options would be:

- Extend restic to allow "appending" (i.e. add another file) to a snapshot, so that it could be invoked multiple times to build-up a complete VM snapshot in multiple stages.
- Extend restic so that for each "file" to be backed up, it can be given file metadata and already-open file descriptors (e.g. over stdin, or a unix domain socket) so that the VM backup helper application can feed the data to restic.
- Extend restic to be able to read a stream type archive format (e.g. "ar" or "tar") on stdin.

There are other applications which have a similar set of requirements e.g. database backup helpers.

In many cases the backup program can also provide metadata like the last modification time of the "file", which restic could use to skip unchanged data.  That would be very useful for my use-case, because for some of the servers I have in mind, most of the VMs are only rarely booted up, so it would save reading multiple TBs data (and the corresponding time and CPU overhead).

BTW, I'm currently using restic to backup file-system contents, and very happy with the feature set and performance etc. Thanks very much for writing and maintaining restic!

**Comment by fd0** [comment]
I'm very sorry for not responding earlier, this issues fell off the radar (well, at least my radar).

I can see what you're trying to do, thanks for reporting this as an issue. Unfortunately, I'm not convinced that this is a good thing to add to restic. It would mean changing restic's internal workings a lot. After all, restic is meant as a tool to backup files. That it can read whole disc images, possibly via stdin, is already a stretch for its primary goal of taking care of files.

The most likely thing to happen would be your suggestion three, allowing restic to read a `tar` file from stdin, which is then made available as a snapshot. But I don't see that happening in the near future :)

I'm sorry if my comment comes across as negative, it's not meant that way. We are a Free Software project for which most people (at least me) work in their spare time, and our development/maintenance/debugging time is very limited. So we're trying to keep restic's scope as small as possible. :)

**Comment by MichaelEischer** [comment]
Closing in favor of #2226.
