### ISSUE TITLE
Why should I choose restic over borg?

### ISSUE THREAD

**Issue by stephane-archer** [restic/restic#1875]
Hi,

I try to choose a backup system for a linux server.
Restic and Borg looks really similar and I'm wondering if you can help me decide :)

Thank you

**Comment by dimejo** [comment]
The most obvious differences that come to my mind:
* restic supports a huge number of backends (borg supports only SSH)
* native Windows support with restic
* borg allows for compression (multiple algorithms)
* borg allows for unencrypted backups

When I was starting to evaluate different backup software about 1 year ago, borg was a bit faster and less demanding on the hardware. But restic didn't use a cache back then. I haven't made any comparisons since then.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/3954

**Comment by enkore** [comment]
AFAIK restic's crypto works.

**Comment by fd0** [comment]
This would have been better in the [forum](https://forum.restic.net). It's really just a matter of your exact use case, I suggest you try both programs and decide for yourself.

I'll close this issue, feel free to add further comments!

**Comment by dabreese00** [comment]
ArchWiki compares them in a chart, along with other allegedly similar solutions:

https://wiki.archlinux.org/index.php/Synchronization_and_backup_programs#Chunk-based_increments

**Comment by dhilgarth** [comment]
This comparison from about 1.5 years ago is also pretty good: https://stickleback.dk/borg-or-restic/

The question to the team would be if the mentioned shortcomings of restic have been addressed in the meantime?

**Comment by fd0** [comment]
This would have been better in the forum, nobody will find the information buried in a closed GitHub issue. If you create a new forum post asking the question, I'll go through the shortcomings mentioned in the article and respond to you.

**Comment by dhilgarth** [comment]
You are right, sorry about that. Here is the forum post: https://forum.restic.net/t/comparison-with-borg-shortcomings-in-restic/1690 Thanks

**Comment by DannyBen** [comment]
> This would have been better in the forum, nobody will find the information buried in a closed GitHub issue. 

Actually, google seems to favor Github issues - closed or not - over proprietary forums (unless the forums are wildly popular and serve as a de-facto source of information).

Not saying this post should or should not be here, just debunking the "nobody will find" part... :)

**Comment by perfecto25** [comment]
Adding to a closed thread, but heres my takeaway after using both,

I have to backup roughly 20TB of data every day (market data)

Using restic takes much longer and has used up a lot of memory on the server doing the backup. Also, restic creates a cache file that can grow to over 10G in size depending on the sizeof backup, which can cause issues if disk space is limited

Borg ran much faster, and uses almost no memory. The only upside to Restic is if you need to use S3 or Backblaze as backend (Borg doesnt support this). Performance-wise, Borg is much faster, uses less memory and less caching disk space.

**Comment by rawtaz** [comment]
@perfecto25 As you can read in previous comments, this would have been better put in the forums.

It's clear that each of us have our individual use cases. For me, Borg is never an option, while for @perfecto25 clearly it's the opposite. Both are valid use cases. We should be happy both tools exist!

**Comment by perfecto25** [comment]
Totally agree, Im not criticizing Restic, its perfect for some cases, just pointing out differences between 2 projects
