### ISSUE TITLE
Error backing up to SFTP source: SSH_FX_FAILURE.

### ISSUE THREAD

**Issue by gkoerk** [restic/restic#1877]
## Output of `restic version`

```restic 0.9.1 compiled with go1.10.3 on linux/amd64```

## How did you run restic exactly?

```
export RESTIC_REPOSITORY="sftp:admin@koerk2.myqnapcloud.com:/share/Backup/resticrepo"
export RESTIC_PASSWORD="***************"
export TMPDIR="/share/Apps/restic/tmp/offsite"

restic unlock

restic backup \
    --tag Apps \
    --cache-dir /share/Apps/restic/cache/offsite \
    --exclude-caches \
    --exclude='.data/mysql' \
    --exclude='container-station-data' \
    --exclude='transcode' \
    --exclude='transcoding' \
    --exclude='@__thumb' \
    --exclude='@Recycle' \
    /share/Apps/*
```

## What backend/server/service did you use to store the repository?

SFTP to another NAS Server.

## Expected behavior

Successful backup.

## Actual behavior

Failure writing to SFTP target:
```
repository f07b9428 opened successfully, password is correct
successfully removed locks
repository f07b9428 opened successfully, password is correct
Save(<data/fbd9338a3b>) returned error, retrying after 415.007417ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/266eef9609>) returned error, retrying after 552.852908ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/266eef9609>) returned error, retrying after 402.450941ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/2f32fe39d4>) returned error, retrying after 708.269732ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/ae6b5f18d0>) returned error, retrying after 380.947755ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/839969e38e>) returned error, retrying after 303.678083ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/abb58ea69f>) returned error, retrying after 354.380121ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/266eef9609>) returned error, retrying after 1.681968779s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/abb58ea69f>) returned error, retrying after 416.037568ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/839969e38e>) returned error, retrying after 439.875238ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/ae6b5f18d0>) returned error, retrying after 750.673235ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/2f32fe39d4>) returned error, retrying after 760.891699ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/abb58ea69f>) returned error, retrying after 868.982702ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/839969e38e>) returned error, retrying after 1.6708041s: Write: sftp: "Failure" (SSH_FX_FAILURE)
```

## Steps to reproduce the behavior

I can reproduce it every time I run the restic backup command to the SFTP source. Local repository backups work fine.

## Do you have any idea what may have caused this?

No. I am able to ssh to the server via host-key exchange.

## Do you have an idea how to solve the issue?

No.

**Comment by fd0** [comment]
Thanks for the report. The error code you see is some kind of generic "something failed" in sftp. Would you mind checking if the drive is full? Is the path correct? Can you try running `sftp admin@koerk2.myqnapcloud.com` then run `ls -l /share/Backup/resticrepo`?

**Comment by gkoerk** [comment]
```[/share/Apps/backup] \# sftp admin@koerk2.myqnapcloud.com```
```admin@koerk2.myqnapcloud.com's password:```
```Connected to admin@koerk2.myqnapcloud.com.```
```sftp> ls -l /share/Backup/resticrepo```
```-rw-------    1 admin    administrators      155 Jul  9 11:57 config```
```drwx------  258 admin    administrators     5160 Jul  9 11:57 data```
```drwx------    2 admin    administrators       40 Jul  9 11:57 index```
```drwx------    2 admin    administrators       60 Jul  9 11:57 keys```
```drwx------    2 admin    administrators       40 Jul  9 12:16 locks```
```drwx------    2 admin    administrators       40 Jul  9 11:57 snapshots```

**Comment by gkoerk** [comment]
BTW - I can do passwordless SSH via key exchange but not SFTP,

**Comment by fd0** [comment]
Hm, looks fine so far. You could try to rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue, maybe that gives us a clue...

**Comment by gkoerk** [comment]
I used the pre-built binary as I'm running on a QNAP NAS without a full flavor of linux.

**Comment by gkoerk** [comment]
Do you think I have a bad install of SFTP? I had to install that using Entware and opkg install.

**Comment by fd0** [comment]
I'm not sure what's going on :)

You can easily cross-compile from any OS to any other OS with Go, just install the Go compiler somewhere (e.g. on your workstation), then run:
```
$ go run build.go --goos linux --goarch amd64
```

In the first post you wrote that you're using restic on `linux/amd64`, that's the machine you need to compile for, and it doesn't sound like it's the NAS...

**Comment by fd0** [comment]
Since we haven't received any feedback in a long time I'm closing this issue for now. Please add a comment or open a new issue if the problem persists. Thanks!
