### ISSUE TITLE
check command doesn't obey the --cache-dir argument and writes to TMPDIR

### ISSUE THREAD

**Issue by xor-gate** [restic/restic#1880]
## Output of `restic version`

`restic 0.9.1 compiled with go1.10.3 on linux/amd64`

## How did you run restic exactly?

```
restic -v=10 -r . --cache-dir /data/backup/cache --cleanup-cache check
```

## What backend/server/service did you use to store the repository?

local backend

## Expected behavior

Obey to the given `--cache-dir` where it should place the temporary check cache. For people with mounted TMPDIR as tmpfs with fixed size this can be a problem.

## Actual behavior

```
using temporary cache in /tmp/restic-check-cache-219828007
enter password for repository:
repository 6bc46502 opened successfully, password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```

## Steps to reproduce the behavior

Pass the `--cache-dir` and see it storing the check cache in `TMPDIR`

## Do you have any idea what may have caused this?

The `--cache-dir` parameter is not used.

## Do you have an idea how to solve the issue?

Use the `--cache-dir` when given instead of `TMPDIR`.

## Did restic help you or made you happy in any way?

Yes, because it is written in golang and has a nice commandline interface 👍

**Comment by fd0** [comment]
Uh, that's not good, it's a bug. Thanks for the report!

**Comment by xor-gate** [comment]
I was migrating my own backup from borgbackup to restic. And did notice this behaviour. Good its an actual bug, not hard to fix 👍

**Comment by garrmcnu** [comment]
As a temporary workaround, could specify '--with-cache' to use an OS-specific cache directory (typically somewhere in the user's home directory). On Linux can set the XDG_CACHE_HOME environment variable and '--with-cache' to use a specific directory.

Adding a check for the global option before creating the temporary directory fixes the issue.

**Comment by fd0** [comment]
That's not quite correct, a workaround would be to set `TMPDIR` (which restic respects) to some directory with enough space, e.g.:
```
$ TMPDIR=/data/backup/cache restic -v=10 -r . --cleanup-cache check
```
