### ISSUE TITLE
Backup --stdin bad behaviour since v0.9

### ISSUE THREAD

**Issue by zcalusic** [restic/restic#1881]
## Output of `restic version`

restic 0.9.1 compiled with go1.10.2 on linux/amd64

## How did you run restic exactly?

restic backup --stdin --stdin-filename vmimage < /dev/md1

## What backend/server/service did you use to store the repository?

local

## Expected behavior

Don't mess with configured --stdin-filename

## Actual behavior

Since I think v0.9, restic prepends working directory from which restic backup command was run, to --stdin-filename parameter. This is ugly and confusing, and it looks like it messes with forget schedule (now each of those backups is considered separately).

restic snapshots returns:

Directory
-----------
vmimage
vmimage
/root/vmimage
/some/path/vmimage
/some/other/vmimage

But it was all the same backup run, just fired from different directories.

## Steps to reproduce the behavior

restic backup --stdin --stdin-filename

## Do you have any idea what may have caused this?

Probably #1494 

## Do you have an idea how to solve the issue?

Nope.

## Did restic help you or made you happy in any way?

Of course, it takes care of all my backups. :)

**Comment by fd0** [comment]
Thanks for the report, it's a bug we're tracking as #1809. I'm closing this issue as a duplicate.
