### ISSUE TITLE
restic hangs when not connected to the internet

### ISSUE THREAD

**Issue by roeebar** [restic/restic#1883]
## Output of `restic version`

`restic 0.9.1 compiled with go1.10.3 on darwin/amd64`
Also tested on freebsd.

## How did you run restic exactly?
Any restic command, e.g.:
`restic unlock`

## What backend/server/service did you use to store the repository?
B2

## Expected behavior
Report an error

## Actual behavior
Hangs (even when the connection is back)

## Steps to reproduce the behavior
Disconnect from the network and run almost any restic command

## Did restic help you or made you happy in any way?
Yes! It enables me to backup my NAS reliably and efficiently to B2

**Comment by roeebar** [comment]
Might be similar to Issue #1713

**Comment by roeebar** [comment]
Might be related to issue #1713

**Comment by fd0** [comment]
oh, interesting corner case, thanks for reporting it! I think it'll only happen with the B2 backend, because the service requires basically retrying forever. I think we can handle the situation better.

**Comment by tbm** [comment]
I just experienced this myself.  I run restic every hour from systemd but I was on a train without Internet and I noticed that restic was just waiting.

I think there are different scenarios to consider:

1) When you start restic and it can't open a connection to B2: I think in that case restic should terminate with an error message.  I think this is what this error is about.

2) If restic makes a connection to B2 but it later gets no reply.  This is different and I think that's covered in issue #1713.  Also, @fd0 suggested in issue #519 that you can just use `timeout 40m restic backup` if you have a slow connection.

@roeebar regarding your comment:
> Actual behavior
> Hangs (even when the connection is back)

I don't think that's the case here.  I'm fairly sure that once Internet resumes, restic makes a connection to B2 successfully.

**Comment by tbm** [comment]
Adding @kurin since he seems to know a lot about B2.

**Comment by kurin** [comment]
Yeah, calls like Client.Bucket() will retry forever, and maybe they shouldn't.  I don't actually have a personal computer at the moment and I'm reluctant to write personal code on an employer's machine, but this has come up often enough in the past that I should probably get something out.

A hacky workaround would be for restic to make new contexts with short (~seconds) timeouts for operations that we don't expect to be long running, or which happen early in a restic run.

The b2 library can also export metrics about what it is doing/has done.  This could be used to verify whether restic actually does pick up again after a network outage.

**Comment by jacquesh** [comment]
I just ran into this as well but in a slightly different form. In my case one of Backblaze's B2 URLs was accidentally blocked by my pihole (imported as part of a 3rdparty list) and restic kept retrying it (after a DNS failure, not even a failure to connect to B2) at ~100 requests per minute for upwards of 24 hours.

After unblocking the failing domain, restic continued and completed without issue.

**Comment by MichaelEischer** [comment]
As it seems to be somewhat common to end up with a hanging initial call to b2, it would a good idea to add a timeout of for example one minute to `b2.newClient` (see https://github.com/restic/restic/issues/3859 for the full stacktrace). That should fix the endless hangs in most cases.

Other cases during a backup are much harder to resolve as we can't tell from the outside whether we're stuck or not.

Anyone up for a PR?
