### ISSUE TITLE
Restoring timestamps of symlinks doesn't work

### ISSUE THREAD

**Issue by fw42** [restic/restic#189]
Follow-up to #24 and #186. At this time, there is no way to use the [lutimes](http://linux.die.net/man/3/lutimes) system call in Go or to pass the `AT_SYMLINK_NOFOLLOW` flag to the [utimesnat](http://man7.org/linux/man-pages/man2/utimensat.2.html) syscall (used by restic [here](https://github.com/restic/restic/blob/aa5fd9e9bc0adbf4b4219018283859cb9cf6fd19/node.go#L174)). However, a patch for this has been merged upstream (see https://go-review.googlesource.com/#/c/9379/).

This issue can be closed once the new code makes it into a major Go release and is in use in restic.

**Comment by fd0** [comment]
We can come up with a workaround: Implement the call to `lutimes` ourselves. Shouldn't be too hard.

**Comment by fd0** [comment]
This is done in #191, closed.
