### ISSUE TITLE
Suspicious calling code for rclone backend 

### ISSUE THREAD

**Issue by mpsrig** [restic/restic#1896]
https://github.com/restic/restic/blob/master/cmd/restic/global.go#L652

`rclone.Open` is called here instead of `rclone.Create`

This additionally means that `rclone.Create`is unused code (except for tests).

`rclone.Open` and `rclone.Create` contain almost identical code.  The main difference is that `rclone.Create` calls `rest.Create` and `rclone.Open` calls `rest.Open`.  

There are a few other minor discrepancies that should probably be resolved (e.g., via a common helper function): https://github.com/restic/restic/blob/master/internal/backend/rclone/backend.go#L254 vs https://github.com/restic/restic/blob/master/internal/backend/rclone/backend.go#L282 and https://github.com/restic/restic/blob/master/internal/backend/rclone/backend.go#L260 vs https://github.com/restic/restic/blob/master/internal/backend/rclone/backend.go#L288

@fd0

**Comment by mpsrig** [comment]
I've taken an initial pass at this. Opening PR.

**Comment by fd0** [comment]
Thank you very much for your contribution. Can we please discuss the changes first, and then break them down into manageable work items? I don't have so much time for code review right now (for a bit of background see [the forum](https://forum.restic.net/t/answering-issues-preventing-burnout/417)).

**Comment by fd0** [comment]
I've taken a look, we should make sure that the `Create` function for the rclone backend (and therefore the `Create` function for the REST backend) is used. The difference is that `Create` issues an HTTP request according to the [REST protocol](https://github.com/restic/restic/blob/master/doc/REST_backend.rst#post-pathcreatetrue) which tells the server that the repo should be created.

Let me know if you need any help, and thanks for taking care of this issue!
