### ISSUE TITLE
Feature Request: Log when creating a new local cache

### ISSUE THREAD

**Issue by whereisaaron** [restic/restic#1897]
## Output of `restic version`

`restic 0.9.1 compiled with go1.10.3 on linux/amd64`

## How did you run restic exactly?

`restic backup --stdin`

## What backend/server/service did you use to store the repository?

B2

## Expected behavior

Log that restic was creating a new local cache, enabling me to realize this was happening on even run (due to my omission to provide persistent local storage).

## Actual behavior

No log message

## Did restic help you or made you happy in any way?

Restic worked perfectly, this is a small feature request to assist the user.

**Comment by fd0** [comment]
Good point, thanks!

**Comment by MichaelEischer** [comment]
This was implemented in #1973 which is part of restic 0.9.3
