### ISSUE TITLE
Feature Request: Hot vs Cool storage tier in Azure

### ISSUE THREAD

**Issue by Cova** [restic/restic#1903]
Output of `restic version`
--------------------------
restic 0.9.1 compiled with go1.10.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
If possible, when creating block-blobs in Azure storage, automatically assign them the most appropriate storage tier at creation time.  'Hot' blobs have no cost associated with read/write bandwidth, but higher per-GB costs, while 'Cool' blobs are cheap GB/month but you pay every time you read them.  I'm not super familiar with Restic's directory layout yet, but it would seem to me that it is likely optimal to have the config file, index/key directories, and maybe the snapshots directory use hot blobs, while all of the data that I think is only ever read for check/restore stored as cool data.

Taking it a step further - an optional future feature would be able to allow the user to tag backups for long-term retention, and move that data down to 'archive' tier, which carries even higher access-charges, as well as high access latency.

What are you trying to do?
--------------------------
Get the most value for my money.

Did restic help you or made you happy in any way?
-------------------------------------------------
Loving Restic so far - just trying to figure out how to get the most backup value I can into the monthly free Azure credits that I receive through my employer.  Many thanks for all the effort that's gone into getting this software to where it is today.

**Comment by rubenbe** [comment]
This feature could be generalized to:
* Amazon S3/Glacier
* OVH object storage/archive
* Azure Cold&Hot blobs
* (possibly others?)

Where restic uploads (a part of) its readonly data in the cold storage and keeps the metadata in the hot storage.

I've found this OVH howto for duplicity: https://docs.ovh.com/gb/en/storage/pca/duplicity/

IMHO the most generic solution would be that
* you can specify two backends (one hot and one cold)
* the age of a blob before moving it to the cold storage. Where zero would mean "keep all data in the cold storage"

**Comment by fd0** [comment]
While this is a nice idea (thanks for the request), it requires restructuring restic internally, so it won't be possible short-term.

**Comment by MichaelEischer** [comment]
Closing in favor of #3202
