### ISSUE TITLE
B2 init repo doesn´t work / hangs

### ISSUE THREAD

**Issue by julled** [restic/restic#1906]
Got an Issue when trying to initalize an repo on B2. I got the keys from the web-interface of b2.
If i try to run the commands below, simply nothing happens, for at least 10minutes.
The --verbose argument doesnt give any additional info.

I can init a local repo with restic without a problem.

If i use the b2 cli tool i can successfully authenticate and upload files to my bucket. 
So i think this is not an issue based on too less rights of the executable or a firewall (i dont have one).

I tried to run older versions (0.81 x64, 0.83 x64 / 386 ) resulting to the same issue.

Output of `restic version`
--------------------------
restic 0.9.1 compiled with go1.10.3 on linux/amd64
Ubuntu 16.04

How did you run restic exactly?
-------------------------------
export B2_ACCOUNT_ID=xxx 
export B2_ACCOUNT_KEY=xxx (Master App Key)
chmod 777 restic_0.9.1_linux_amd64
./restic_0.9.1_linux_amd64 -r b2:bucketName init

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
b2

Expected behavior
-----------------
init repo

Actual behavior
---------------
nothing happens

Steps to reproduce the behavior
-------------------------------
run the commands

Do you have any idea what may have caused this?
-----------------------------------------------
maybe restic executable got too less rights , gets blocked somewhere?

**Comment by mholt** [comment]
So, to clarify, you hit "Enter" to run the command and then it just sits there, nothing to stdout, stderr, or any other activity? Any network activity going on?

**Comment by julled** [comment]
has been resolved, thx!

**Comment by mholt** [comment]
What was the solution?

**Comment by julled** [comment]
Not related to restic. It was a typo in my credentials. 
So stupid.

**Comment by fd0** [comment]
Thanks for the feedback! We're always interested in what the solution was :)

**Comment by julled** [comment]
But the thing is: there was no error reply in restic on that issue. It simply hang without any output.
Duplicati at least returned the b2 errormsg "ERROR 500 internal_error Unexpected exception".
Maybe some error handling in restic would receive that b2-message and print it, as i was really confused that simply nothing was replied.

**Comment by fd0** [comment]
Hm, that's odd. I agree that an error message should be printed...

I'm unable to reproduce it here... what was the typo? any hints on how to reproduce it?

For the record, changing the last character of my key and running restic gives me:
```
$ restic init
Fatal: create repository at b2:bucket:/path failed: b2.NewClient: b2_authorize_account: 401: Invalid authorization
```

@kurin can you have a look? Is there anything we should do from restic's side?

**Comment by fd0** [comment]
Reopening for now.

**Comment by julled** [comment]
It was a typo in my account id.

**Comment by fd0** [comment]
Yeah, that's a change Backblaze implemented just a few days ago, and other keys than the Master Application Keys are not supported yet (but we're working on that). We need to update the docs also then.

**Comment by julled** [comment]
ahh, okey that explains my confusion.

**Comment by fd0** [comment]
Sorry about that, I've just tested the master branch of the blazer library and it's working with restricted application keys now, so @kurin hopefully tags a release the next couple of days and then we can update restic and fully support the new keys :)
