### ISSUE TITLE
b2 application key permissions

### ISSUE THREAD

**Issue by rphillips** [restic/restic#1907]
Output of `restic version`
--------------------------
0.9.1

How did you run restic exactly?
-------------------------------
Generated application key on b2 with bucket only read/write permissions. restic calls into b2 with a list_buckets which is not permitted with bucket level only permissions.

`restic init`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
b2, bucket level only permissions

Expected behavior
-----------------
I would expect a b2 application key to be generated for a specific bucket. Giving the key access to 'all' buckets works as expected.

Actual behavior
---------------
restic errors out with a 401 error with the the list_buckets call.

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------
API level permissions

Do you have an idea how to solve the issue?
-------------------------------------------
Perhaps the list_buckets call can be avoided on an init?

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic is awesome!

**Comment by mholt** [comment]
It appears that the call to listBuckets is required to verify that the bucket exists: https://github.com/kurin/blazer/blob/c83da4d7069325fe34d9ed0f09883c02aedac140/b2/b2.go#L285

This is how the B2 client library works, and isn't really specific to restic. I'm not sure what the implications are of skipping the existence check, or if it's even possible to bypass it: many operations are called on the Bucket once it is obtained.

**Comment by rphillips** [comment]
This is definitely a user story for restic... I looked into the blazer library and b2_list_buckets errors with the given bucket the key has permissions to. Another alternative is to call b2_list_buckets with bucketName to list only the specified bucket. I know it doesn't fit into this project, but the blazer library could be improved to pass the specific bucket with `bucketName` to b2_list_buckets so the operation is not O(N).

**Comment by fd0** [comment]
Ah, this is an issue with how application keys work: they cannot just be used instead of the master keys, but need to be handled differently, so all libraries/programs will need explicit support for them. I had a discussion with @kurin and people from Backblaze about that, and there's a fix in the blazer library (in the `master` branch that I haven't tested yet). If you'd like to try it, then you need to build restic with the latest version of the library.

I had exactly the same effect when I tested the application keys feature last week.

If you do, please report back!

**Comment by kurin** [comment]
For what it's worth, when we're not dealing with bucket-specific application keys, a b2_list_buckets request requesting the specific bucket name won't really be faster than getting all the buckets and then filtering.  There are a maximum of 100 buckets per account, and so the b2_list_buckets call doesn't support pagination.  You're going to incur exactly one round-trip no matter what you do.

**Comment by fd0** [comment]
I've just merged #1914, so the code in the master branch now supports application keys! You can build restic yourself to try it out, or download a compiled beta version here: https://beta.restic.net/?sort=time&order=desc

**Comment by rphillips** [comment]
Thank you!
