### ISSUE TITLE
Reduce unnecessary lstat calls on excluded files to improve scan speed

### ISSUE THREAD

**Issue by askielboe** [restic/restic#1909]
Output of `restic version`
--------------------------
restic 0.9.1 compiled with go1.10.3 on darwin/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Currently restic runs `lstat` on files even if they're excluded by filename. This can result in unnecessarily long scan times when e.g. a lot of files are excluded by extension. restic needs to run `lstat` on exclude files in certain circumstances, such as when checking for `--one-file-system`, but if the files checked are already excluded by filename there should be no need to run `lstat` on those files. Reducing the use of `lstat` can speed up backup times significantly in some cases.

Quote from @fd0 on [forum.restic.com](https://forum.restic.net/t/restic-runs-lstat-on-files-excluded-by-extension-intended-behaviour/831/4):

> This is an architectural limitation restic currently has: some of the exclude functions (e.g. --one-file-system) need to have the information lstat returns, and so we’re currently running lstat on the files before checking the excludes. The solution would be to have two types of excludes:
> 
>  - The ones which can decide by name/path if a file is to be excluded
>  - The ones which need the lstat information (e.g. --one-file-system)
>
> Until this is implemented, restic runs lstat() on all files. Sorry about that. You could add a bug report to the GitHub issue tracker so we can track improving the exclude function, that’d help.

What are you trying to do?
--------------------------
This issue can significantly increase scan (and therefore backup) times when a lot of files are excluded by filename.

In one case I observed an increase in backup time of > 20 minutes when excluding 1.000.000 `.pb` files using a wildcard exclude pattern `*.pb`, rather than excluding the files by path.

It would be convenient to be able to apply general filename wildcard exclude patterns on a large number of files without having to worry about long backup times.

Did restic help you or made you happy in any way?
-------------------------------------------------
restic has significantly strengthened my backup strategies and made it much simpler to deploy robust backup in a number of different environments. The general approach to backup and the active community around restic makes it a pleasure to use. Thanks a lot to everyone involved!

**Comment by fd0** [comment]
Thanks for giving this a try, it's highly appreciated!

**Comment by whereisaaron** [comment]
This improvement not only reduce system calls, it reduced file system operations, which could save a lot of time on network file systems like NFS or SMB. 🎉

**Comment by fd0** [comment]
We're interested in feedback at how this change improved the runtime for you :)
