### ISSUE TITLE
Fatal: wrong password or no key found when try to backup with stdin

### ISSUE THREAD

**Issue by abstractart** [restic/restic#1911]
Output of `restic version`
--------------------------
```restic 0.9.1 compiled with go1.10.3 on linux/amd64```

How did you run restic exactly?
-------------------------------
```
pg_dump database | restic -r /tmp/restic-repo backup --stdin --stdin-filename prod.sql
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local filesystem

Expected behavior
-----------------
Create snapshot in repository

Actual behavior
---------------
Error output:
```
Fatal: wrong password or no key found
```
Steps to reproduce the behavior
-------------------------------
```
restic -r /tmp/restic-repo init
pg_dump database | restic -r /tmp/restic-repo backup --stdin --stdin-filename prod.sql

```

**Comment by richard-scott** [comment]
I think that's how its supposed to work, you can't enter a password, as anything going to stdin will get backed up. Two alternatives are that you can create a file with the password in and then set this:

```
$ echo "1234" > /my/password/file
$ export RESTIC_PASSWORD_FILE=/my/password/file
```

or use the '-p' option
```
$ restic -p /my/password/file backup --stdin ...
```
