### ISSUE TITLE
Old minio-go library ignoring documented env vars

### ISSUE THREAD

**Issue by erictcgs** [restic/restic#1918]
Current master (3422c1ca83408a5e796f5ceafd9ec47a5db8f0a5) contains an old version of the minio-go library, which has a bug where it is ignoring the documented environment variable `MINIO_SHARED_CREDENTIALS_FILE`.

Line in restic repo: 
https://github.com/restic/restic/blob/master/vendor/github.com/minio/minio-go/pkg/credentials/file_minio_client.go#L63

Minio-go issue: https://github.com/minio/minio-go/issues/1007
Minio-go PR/merge: https://github.com/minio/minio-go/pull/1008

Did restic help you or made you happy in any way?
-------------------------------------------------
Fantastic tool!!!

**Comment by fd0** [comment]
Ah, thanks for the hint. While the minio-go version in restic is not the newest, the fix you're talking about is not contained in any release yet...

**Comment by fd0** [comment]
#1919 updates minio-go to 6.0.5. I'll keep this issue open for now, can you please ping me when they release a new version with the fix?

**Comment by erictcgs** [comment]
Will do

**Comment by fd0** [comment]
ok ,cool, I'll update :)

**Comment by fd0** [comment]
We're using 6.0.7 now.
