### ISSUE TITLE
Check minimum backup size

### ISSUE THREAD

**Issue by Miouge1** [restic/restic#1928]
Output of `restic version`
--------------------------

```
restic 0.9.1 compiled with go1.10.3 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Add a `restic backup --min-size 1234` flag that checks the size of the backup and exit with non zero exit code if the backup is smaller than specified by the flag.

What are you trying to do?
--------------------------

Make it easier to detect when a backup is smaller than expected.

**Comment by fd0** [comment]
Thanks for the suggestion. Can you clarify, what does "size of the backup" mean? The size of the data to be saved as stored on the local machine? Or the size of data newly added to the repo? Or something else entirely?

**Comment by Miouge1** [comment]
I think the most common use case is "the size of the data to be saved as stored on the local machine", as to detect when the backup is empty or "too small" (empty tar file etc...):

### Files
```
$ restic backup ~/work --min-size 1234
```
Would compare the size of the ~/work folder vs `--min-size 1234` and fail if minimum size is not met.
### Stdin
```
$ mysqldump [...] | restic backup --stdin --min-size 1234
```
Would compare the size of `stdin` vs `--min-size 1234` and fail if the minimum size is not met.

**Comment by rawtaz** [comment]
@Miouge1 I'm curious; What is the actual use case here (what you wrote in your first sentence isn't a use case, but a description of what it should measure)? What practical problem are you trying to solve with this suggestion?

**Comment by smlx** [comment]
This use case seems like it will be covered by #1729, right?

E.g. `restic backup ... && [[ $(restic stats ... | cut ...) -gt 1234 ]]`

**Comment by Miouge1** [comment]
Let me detail the `mysqldump` example then:

- there is a daily cron job with `mysqldump [...] | restic backup --stdin` (same as in the [doc](https://restic.readthedocs.io/en/stable/040_backup.html#reading-data-from-stdin))
- backups are working well, no problems
- for an external reason `mysqldump` fails or returns an empty dataset (maybe somebody changed the password or the DB name but forgot to update the backup cron job)
- `restic backup` and the cron job still works, but now we are taking backups of an error message or empty DB

It's doable with some scripting but it would be a nice thing for `restic backup` to be able to check (optional and disabled by default) to make life a little easier for situation where min backup size is known

**Comment by fessmage** [comment]
I agree with @rawtaz , what you send to restic for backup isn't restic's concern. If you want check files for backup, you must process it before send to restic.

Also i can advise using in backup shellscript the so called "[bash strict mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/)" approach, with that if your mysqldump fails with non-zero error code, then backup script will exit, restic will not backup wrong data and you will see that your backup was failed with `restic <repo> snapshots --last` for example, by last date.

**Comment by Miouge1** [comment]
@smlx from what I tested `restic stats latest' ` is not that simple to parse, here are a couple of example of the output of `restic stats latest | grep 'Total Size'`:
```
        Total Size:   0B
        Total Size:   7B
        Total Size:   12.788 MiB
```
I didn't find any flag to disable the human readable units which are a pain to parse in bash/awk (example https://stackoverflow.com/a/26621833).

A downside of using `restic stats` is that the snapshots has to be removed if something is wrong. The initial idea was to fail/cancel the backup.

I like the idea from @fessmage since checking the dumps before sending them to `restic backup` allows to fail early.

**Comment by fd0** [comment]
@Miouge1 you can just use the json output mode:
```
$ restic --json stats latest
{"total_size":25371420,"total_file_count":70}
```

**Comment by Miouge1** [comment]
@fd0 thanks, I didn't know about the `--json` flag! I can do something like `[[ $(restic --json stats latest | jq .total_size) -gt 1234 ]]`
