### ISSUE TITLE
Simple shell script for installing the latest release

### ISSUE THREAD

**Issue by x86dev** [restic/restic#1930]
Hi,

just wanted to share a simple 4-line script to download and install the latest release of restic from Linux shell using cURL to /usr/local/bin:

```
RESTIC_TAG_LATEST=$(curl --silent "https://api.github.com/repos/restic/restic/releases/latest" | grep -Po '"tag_name": "v\K.*?(?=")')
echo "Downloading and installing restic v$RESTIC_TAG_LATEST ..."
RESTIC_URL=https://github.com/restic/restic/releases/download/v${RESTIC_TAG_LATEST}/restic_${RESTIC_TAG_LATEST}_linux_amd64.bz2
sudo curl -L --silent ${RESTIC_URL} | bunzip2 > /usr/local/bin/restic
```

Note: **Assumes** running on a x86 64-bit (x86_64) machine.

Might be handy to someone, or even worth for the docs in case there isn't any official PPA.

**Comment by mholt** [comment]
Thanks for sharing this!

I'll also note that we've found this script useful when distributing Caddy: https://getcaddy.com/

And rclone does similarly: https://rclone.org/install.sh

I know a lot of people have issues piping into bash but honestly I feel like if you do it right, it's really convenient and works almost anywhere.

**Comment by mfsu** [comment]
You should never download and install something without integrity and cryptographic signature checking.

**Comment by mholt** [comment]
> You should never download and install something without integrity and cryptographic signature checking.

TLS takes care of this.

If you mean something else, you'll need to be more specific and specify a clear threat model.

**Comment by fd0** [comment]
Thanks for posting the script. I'm not really sure what to do with it, hm.

**Comment by rawtaz** [comment]
I agree, updating itself is not a concern of restic. Leave that to others to manage.

**Comment by mholt** [comment]
This is really cool! I had thought about doing something like this for Caddy but never got around to it.

**Comment by fd0** [comment]
I like that it's so simple, and it only uses the infrastructure we already have in place :)

**Comment by mfsu** [comment]
Thanks Alexander for addressing this so quickly. I want to note that my
original intent was to draw attention to the curl based method, which was
used even by docker at some point.

**Comment by x86dev** [comment]
Oh wow, very nice, fd0! I'll give it a try soon. Cheers!

**Comment by fd0** [comment]
So, the overwhelming majority of users I asked were in favor, so I'm merging this command. Please be aware that until the next release this won't really work.

**Comment by necenzurat** [comment]
Unearthing this just to let you know that i made a platform agnostic shell script just for installing restic.
Check it [necenzurat/restic-installer](https://github.com/necenzurat/restic-installer)
