### ISSUE TITLE
Add pidfile / runfile support

### ISSUE THREAD

**Issue by x86dev** [restic/restic#1931]
Hi,

it would be handy to have a (global) option to let restic create pidfiles(s) (at least on POSIX, for Windows some global mutexes should do). That would enable telling more easily if restic (already / still) is running.  

Doing so there would be an official way of doing it, especially for scripts, without implementing any custom heuristics.

**Comment by mholt** [comment]
How about `pgrep restic`?

**Comment by x86dev** [comment]
This will do it on Linux / POSIX systems, but is not really tied to restic itself / platform agnostic.

**Comment by mholt** [comment]
Well, neither is a pidfile -- either way, it'll require some platform-dependent code.

**Comment by MichaelEischer** [comment]
@x86dev What is your use case for this? Normally (at least in my experience) pid files are used when a process forks itself into the background, which is not the case with restic. And if you use a shell to start restic e.g. as `restic &`, then the PID is stored in `$!`

**Comment by MichaelEischer** [comment]
Closing this issue for now as there has been no feedback to determine the use case. Feel free to provide more information and reopen this.
