### ISSUE TITLE
Ugly stats unknown parameter error.

### ISSUE THREAD

**Issue by fbarbeira** [restic/restic#1933]
Output of `restic version`
--------------------------
restic 0.9.2 compiled with go1.10.3 on linux/amd64

How did you run restic exactly?
-------------------------------

```
./restic stats sdafsadfsafd
```

Expected behavior
-----------------

Maybe restic should output the "./restic stats --help" output because I'm using an unknown parameter.

Actual behavior
---------------

It outputs an ugly error:

```
./restic stats dfssdafasdf
repository 6f476039 opened successfully, password is correct
no ID found
github.com/restic/restic/internal/restic.init
	src/github.com/restic/restic/internal/restic/backend_find.go:11
github.com/restic/restic/internal/archiver.init
	<autogenerated>:1
main.init
	<autogenerated>:1
runtime.main
	/usr/local/go/src/runtime/proc.go:186
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2361
```

**Comment by fd0** [comment]
Oh yeah, you're completely right, that's ugly. Thanks for the report!

**Comment by mholt** [comment]
Oops -- I think I can look into this.
