### ISSUE TITLE
Backward compatibility issue between 0.8.3 and 0.9.x

### ISSUE THREAD

**Issue by hossainemruz** [restic/restic#1934]
We use `restic` for backup in [Stash](https://appscode.com/products/stash/). Currently we are upgrading restic version from 0.8.3 to 0.9.2. As archiver code has been changed in 0.9.x,  we are facing some issue while restore a repository that has been created using 0.8.3.

**How we did recover before:**
1. Let, user took backup `/home/nobody/source/data` folder. So, snaphot contain `/data` as root level directory.
2. We recover the snapshot in `/home/nobody/source` directory. As a result recovered data would have `/home/nobody/source/data` structure which is same structure as original data.

**What is happening now:**
1. If the snapshot is taken by restic 0.9.x then snapshot has `/home/nobody/source/data` as root level directory. Now if we restore in `/home/nobody/source` directory, final directory structure will be `/home/nobody/source/home/nobody/source/data` which is not expected.
2. We can restore in root directory(`/`) which will result expected structure but if the snapshot was taken by 0.8.3 and we are recovering with 0.9.2 in root directory we will end up with `/data` directory structure for recovered data which is not expected.

**What we can do:**
1. Recover in root directory and forget about the snapshots created by '0.8.3'. (Not expected)
2. Recover in `/home/nobody/source` directory and check if the directory has nested `/home/nobody/source`. If nested directory exit then move `/data` few level up to fix the directory structure. (Don't think a good approach).

**Is there any way to detect which snapshot is created by 0.8.3 and which by 0.9.x?** And it would be great to have a `--strip-components=NUMBER` flag just like **tar**.

**Comment by fd0** [comment]
Indeed, the behavior has changed on purpose, and it is documented in the changelog here: https://github.com/restic/restic/blob/master/changelog/0.9.0_2018-05-21/issue-549

The old behavior was a source of endless confusion and pain, a few cases are listed in #549.

> Is there any way to detect which snapshot is created by 0.8.3 and which by 0.9.x?

No, there isn't.

But I've got a better idea: you can make restic 0.9.x behave like restic 0.8.y by first changing the directory to the parent directory of the data you like to archive, then passing a relative path:

```
$ cd /home/nobody/source
$ restic backup source
```

Then the top-level directory in the snapshot will be `/source` again. Problem solved :)

> And it would be great to have a --strip-components=NUMBER flag just like tar.

This feature request is tracked as #555. Unfortunately, it comes with its own set of problems and corner cases we need to handle :)

So, I'm closing this issue for now as I think the questions have been answered. Please feel free to add further comments!
