### ISSUE TITLE
Stream JSON output during long-running operations

### ISSUE THREAD

**Issue by mholt** [restic/restic#1937]
Output of `restic version`
--------------------------

```
restic 0.9.2 (v0.9.2-0-gbeb208e1) compiled with go1.10.2 on darwin/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When executing long-running commands such as `restic backup` or `restic restore`, I'd like to track the status programmatically (non-interactively) by having JSON stream through stdout. For example, during backup, a JSON object like this would be helpful (sans formatting, which I've added for readability):

```json
{
	"elapsed_time": "14:03",
	"estimated_time": "1:53:19",
	"percent_done": 0.6786,
	"total_files": 6223,
	"files_done": 1092,
	"total_bytes": 123456789,
	"bytes_done": 123456,
	"error_count": 0,
	"current_files": ["/my/file.txt", "/other/file.tar.gz"]
}
```

I figure an object like this could be written as often as the standard terminal UI is updated when in interactive mode.

Then I think something similar for restore, prune, check, and rebuild-index (in that order) would be useful -- but for now what matters most is backup.

I'm willing to submit the PR to do it, but I have to admit I looked through the [cmd_backup.go file](https://github.com/restic/restic/blob/beb208e1597a4b7d18705c12f045413056eafcdb/cmd/restic/cmd_backup.go#L362) and am a little lost at where the output is actually happening... there's a lot of indirection. Do you have any suggestions on how to go about this?

(This request is similar, but unrelated, to #1905)

Did restic help you or made you happy in any way?
-------------------------------------------------

Of course it has -- it's close to being ready for the rest of my family to use. :) Thanks for all the work you put into restic! I hope you find it as enjoyable to make as I do to use it.

**Comment by fd0** [comment]
Agreed, great idea! I'll briefly give you a few hints, let me know if you need more.

The old archiver code (pre-0.9.0) was tightly coupled with the progress reporting, that was not a good thing. So for the new archiver, there is not tight coupling. The archiver itself just provides a few callback functions that can be set and will be called at the right times to report progress:

https://godoc.org/github.com/restic/restic/internal/archiver#Archiver

Please be aware that the archiver assumes that these functions return almost immediately, and do not block.

On the other hand, functions with the same signature (and name) are implemented by the `Backup` type in the `ui` package:

https://godoc.org/github.com/restic/restic/internal/ui#Backup

This type uses a small terminal library I've written called `termstatus`, which I've imported into restic:

https://godoc.org/github.com/restic/restic/internal/ui/termstatus

It provides printing messages (single lines) and one or more status lines which can be replaced during runtime.

I already had streaming JSON output in mind when building the new archiver, so what I would do if I were to implement this is building a `Backup` struct maybe in the `internal/ui/json` package which implements functions to use as callbacks for the `Archiver` and print JSON items to stdout.

Let me know what you think!

**Comment by mholt** [comment]
Thanks! This is really helpful.

Hmm, I was expecting an interface of some sort to satisfy. The `ui.Backup` struct calls `fmt.Printf` directly with the human-readable output. So it looks like I'll have to make a new concrete `Backup` struct type separate from the `ui.Backup` struct? I could make a new package like you suggested (although for consistency I might call it `jsonstatus`, next to the `termstatus` package). But then I have to use a condition in `cmd_backup.go` to choose whether to call `ui.NewBackup` or `jsonstatus.NewBackup`. It just feels a little unclean. So I think I misunderstood... :smile:

**Comment by fd0** [comment]
> So it looks like I'll have to make a new concrete Backup struct type separate from the ui.Backup struct? 

Yes, that's what I had in mind.

> It just feels a little unclean.

It feels like this to me, too, so if you have ideas on how to improve it, please let me know :)

**Comment by mholt** [comment]
Unfortunately, making a separate concrete Backup type forces the entirety of the `runBackup` function to be duplicated, since we cannot declare a single `p` variable like `var p ui.Backup`. In other words, [these 100+ lines need to be essentially repeated](https://github.com/restic/restic/blob/beb208e1597a4b7d18705c12f045413056eafcdb/cmd/restic/cmd_backup.go#L362-L487) with the main difference being the first line: `p := ui.NewBackup(...)` vs. `p := jsonstatus.NewBackup(...)`

However, I've gone ahead and copied the Backup struct into its own file and package and the core changes look something like this:

```go
type statusUpdate struct {
	SecondsElapsed   uint64   `json:"seconds_elapsed,omitempty"`
	SecondsRemaining uint64   `json:"seconds_remaining,omitempty"`
	PercentDone      float64  `json:"percent_done"`
	TotalFiles       uint64   `json:"total_files,omitempty"`
	FilesDone        uint64   `json:"files_done,omitempty"`
	TotalBytes       uint64   `json:"total_bytes,omitempty"`
	BytesDone        uint64   `json:"bytes_done,omitempty"`
	ErrorCount       uint     `json:"error_count,omitempty"`
	CurrentFiles     []string `json:"current_files,omitempty"`
}

// update updates the status lines.
func (b *Backup) update(total, processed counter, errors uint, currentFiles map[string]struct{}, secs uint64) {
	status := statusUpdate{
		SecondsElapsed:   uint64(time.Since(b.start) / time.Second),
		SecondsRemaining: secs,
		TotalFiles:       total.Files,
		FilesDone:        processed.Files,
		TotalBytes:       total.Bytes,
		BytesDone:        processed.Bytes,
		ErrorCount:       errors,
	}

	if total.Bytes > 0 {
		status.PercentDone = float64(processed.Bytes) / float64(total.Bytes)
	}

	for filename := range currentFiles {
		status.CurrentFiles = append(status.CurrentFiles, filename)
	}
	sort.Sort(sort.StringSlice(status.CurrentFiles))

	json.NewEncoder(b.StdioWrapper.Stdout()).Encode(status)
}
```

I'm not sure how to detangle the Backup from the status. It still seems very intimately tied to the terminal...

**Comment by fd0** [comment]
There's a natural abstraction boundary as far as I can see, at the border of the `Archiver` struct: It gets passed three callback functions:
 * `CompleteItem`
 * `StartFile`
 * `CompleteBlob`

A couple of more functions are used in `cmd_backup.go`, e.g.:
 * `ScannerError`
 * `ReportTotal`
 * `Error`
 * `V`

And so on.

That'd make a good interface, e.g. `ArchiveProgressReporter` or so. I admit it's a bit bigger than normal interfaces, but well.

Then you could replace only this line:
```go
p := ui.NewBackup(term, gopts.verbosity)
```
by a function which returns the interface I mentioned, the functions can then be used for the Archiver.

The implementation satisfying the interface (e.g. `ui.Backup`) would then be responsible for handling all output, either to the terminal in verbatim with status, or as a JSON stream.

What do you think?

**Comment by mholt** [comment]
> That'd make a good interface ... Then you could replace only this line:

Almost, except that there are some concrete fields being accessed, for example: https://github.com/restic/restic/blob/beb208e1597a4b7d18705c12f045413056eafcdb/cmd/restic/cmd_backup.go#L377

Otherwise, I love the idea of an interface. :+1: Maybe that part where we access the concrete field could use a type assertion...

I'll revisit this soon!

**Comment by fd0** [comment]
> Maybe that part where we access the concrete field could use a type assertion...

Or just make it a function and add it to the interface...

**Comment by mholt** [comment]
Alright -- thanks again for the guidance! Got an initial WIP pushed in the linked PR to track progress.
