### ISSUE TITLE
Restic failing to complete when run from cron as root (stuck on 'create exclusive lock for repository')

### ISSUE THREAD

**Issue by virtualbeck** [restic/restic#1938]
Output of `restic version`
--------------------------
restic 0.9.1 compiled with go1.10.3 on linux/amd64

How did you run restic exactly?
-------------------------------
```
crontab -l
# Chef Name: postgres_restic_backup
0 8 * * * /var/lib/pgsql/scripts/postgres_restic_backup.sh >> /var/lib/pgsql/scripts/postgres_restic_backup.log
```

postgres_restic_backup.sh:
```
#!/bin/bash
export ENV=$(hostname -d | awk -F. '{print $1}')
export RESTIC_PASSWORD='PASSWORD'
export DBPORT='5432'

su - postgres -c 'psql -t -A -c "SELECT datname FROM pg_database" | grep -v "^template[0-9]"' | while read database; do
  export RESTIC_DB_REPO="s3:s3.amazonaws.com/blah/$ENV/$database"
  echo "Backing up database '$database' to restic repo $RESTIC_DB_REPO"

  # check or initialize repo
  restic --repo $RESTIC_DB_REPO check || restic --repo $RESTIC_DB_REPO init

  # perform backup
  su - postgres -c "pg_dump -Fc -p $DBPORT $database" \
    | restic --repo $RESTIC_DB_REPO backup --stdin --stdin-filename $database.pg_dump

  # prune old backups
  restic forget --repo $RESTIC_DB_REPO --keep-last 2 --keep-hourly 1 --keep-daily 7 --keep-weekly 4 --keep-monthly 24 --keep-yearly 5 --keep-tag keep --prune
done
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3

Expected behavior
-----------------
```
Backing up database 'postgres' to restic repo s3:s3.amazonaws.com/blah/uat/postgres
using temporary cache in /tmp/restic-check-cache-071325828
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found

Files:           0 new,     1 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added:      1.896 KiB

processed 1 files, 0 B in 0:01
snapshot 8f25247d saved
Applying Policy: keep the last 2 snapshots, 1 hourly, 7 daily, 4 weekly, 24 monthly, 5 yearly snapshots and all snapshots with tags [[keep]]
...
```

Actual behavior
---------------
```
Backing up database 'postgres' to restic repo s3:s3.amazonaws.com/edo-backups/CLO/postgres-restic/uat/postgres
using temporary cache in /tmp/restic-check-cache-473124124
create exclusive lock for repository
```
no more output

Steps to reproduce the behavior
-------------------------------
Run as root in cron produces actual behavior;
Run as root manually produces desired output.

Do you have any idea what may have caused this?
-----------------------------------------------
Only difference is running in cron seems to have the process hang

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes, this will be great to do DB snapshots daily if this can be ironed out!

**Comment by virtualbeck** [comment]
USER ERROR! 😂

Closing, as I've solved the issue.
There are multiple dbs with same schema name 'postgres' trying to access the same file in s3 at once. One backup completes, as it has a lock on the file, but other backups fail.

**Comment by fd0** [comment]
Ah, interesting! Thanks for the report and feedback. I'd like to clarify: You're saying that there are multiple instances of restic accessing the same repository stored at s3? Or that multiple instances of your script access the same postgres database? Which operation is the one that blocks?

restic is able to backup to the same repository concurrently, so that should not be an issue. If there's an exclusive lock in the restic repo (e.g. while a `prune` operation is in progress), restic returns an error and won't hang.

**Comment by fd0** [comment]
Hm, that should not be an issue at all. Multiple restic clients can backup arbitrary data to the same repository at the same time...

Although, now that I re-read your script, the `check` operation creates an exclusive lock in the repo, so at that time no other instance of restic can backup to the repo. For your purpose (just checking if the repo already exists) you can use `restic snapshots` instead.
