### ISSUE TITLE
prune reports about 16777216 TiB will be freed from an x86 backup on ARM.

### ISSUE THREAD

**Issue by chrestomanci** [restic/restic#1954]
Output of `restic version`
--------------------------
restic 0.9.2 compiled with go1.10.3 on linux/arm

How did you run restic exactly?
-------------------------------
I have a scheduled backup that runs on 64 bit windows (little endian), but the weekly job to prune the backups runs on a Debian Linux box running on ARM hard float (big endian)

export B2_ACCOUNT_ID="XXXXXX"
export B2_ACCOUNT_KEY="ZZZZZZZZZZZ"
export RESTIC_REPOSITORY="b2:jonah-users-backup"
export RESTIC_PASSWORD_FILE="/etc/restic_passwords/jonah-users-backup"

echo -n 'Running forget then prune '; date
restic forget --verbose --keep-daily 8 --keep-weekly 8 --keep-monthly 24
restic prune  --verbose

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze B2

Expected behaviour
-----------------

Log messages:
....  this frees 438.610 MiB

(Or some such sensible figure)

Actual behaviour
---------------

Log messages:
... 
found 331948 of 355330 data blobs still in use, removing 23382 blobs
will remove 0 invalid files
will delete 243 packs and rewrite 867 packs, this frees 16777215.998 TiB

Steps to reproduce the behavior
-------------------------------

I suspect this is caused by the backup being created on one processor architecture, and maintenance on a different one. I have not done a minimal test to confirm this.

Do you have any idea what may have caused this?
-----------------------------------------------
That 16777215.998 TiB looks like a bug from byte ordering, but this is speculation.

Do you have an idea how to solve the issue?
-------------------------------------------
Hopefully when someone who is familiar with the code sees this bug report he will know where the problem lies. Otherwise it may be necessary to tweak the data storage format.

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic is a very useful backup tool and easy to script. I just wish it where a bit faster for incremental backups and pruning.

NB: This is only a cosmetic issue for me. It would not affect me if you never fix it, but I am raising the bug as it might be a symptom of a more serious underlying problem.

**Comment by mholt** [comment]
Oh, fun! This is a 32-bit ARM system, right? I wonder if there's some overflow/wrapping issue going on when adding a `uint` to an `int` here: https://sourcegraph.com/github.com/restic/restic@49d95e9a50d318a896a9d0f909a5395711c001d2/-/blob/cmd/restic/cmd_prune.go#L255:1

Because for some reason this condition is triggered in `formatBytes`: https://sourcegraph.com/github.com/restic/restic@49d95e9a50d318a896a9d0f909a5395711c001d2/-/blob/cmd/restic/format.go#L15

**Comment by mholt** [comment]
Is the x86 machine 64-bit?

**Comment by chrestomanci** [comment]
Yes. it is running windows.

I also have a 64 bit linux box, but I have not attempted to prune it's backups one my ARM box.

**Comment by mholt** [comment]
Gotcha, thanks for reporting this. I'm guessing/hoping it's just some funky integer overflow/underflow issue, but I'm not _quite_ savvy enough to diagnose it without tinkering a bit.

**Comment by chrestomanci** [comment]
Would you like to give me a debug build of restic for ARM that I can use to collect diagnostics for you?

**Comment by fd0** [comment]
Hey, thanks for the report! I'm pretty sure it's a minor issue with the integer conversion, it seems we're not using a uint64 (which is 64 bit wide) everywhere... 

I'm sure it's not a byte-ordering issue, but I agree it looks like it. We're saving the metadata as JSON, which means all integers are written into the repo as strings and converted when read as necessary.

I'll have a look. A debug build won't help, it won't tell you anything new.

**Comment by fd0** [comment]
Do you maybe have the rest of the `prune` output? It would be interesting to look at the other numbers restic prints...

**Comment by fd0** [comment]
Gah, you triggered my curiosity :)

I'm guessing (without spending too much time on the issue) that it's caused by `duplicateBytes` being an int (so it's either 32 bit or 64 bit wide, depending on the architecture) here: https://sourcegraph.com/github.com/restic/restic@49d95e9a50d318a896a9d0f909a5395711c001d2/-/blob/cmd/restic/cmd_prune.go#L153:2

Then `removeBytes` inherits the type of `duplicateBytes` here: https://sourcegraph.com/github.com/restic/restic@49d95e9a50d318a896a9d0f909a5395711c001d2/-/blob/cmd/restic/cmd_prune.go#L235:2

Then all bob lengths are subtracted from `removeBytes` here: https://sourcegraph.com/github.com/restic/restic@49d95e9a50d318a896a9d0f909a5395711c001d2/-/blob/cmd/restic/cmd_prune.go#L255:4

So, if more than 2GiB are to be remove, the int becomes negative. When it is converted to `uint64`, this will be a **very** large number.

I've verified this hypothesis with [a small sample program](https://gist.github.com/208d08171022b75f572bf49f37a49ac1):
```
$ go run formattest.go
removeBytes before: 2147483647 2.000 GiB
removeBytes after: -2147483549 16777215.998 TiB
```

Fix incoming :)

**Comment by chrestomanci** [comment]
My cron script sets up the necessary secrets then does:
<pre>
echo -n 'C:\users directory on Jonah. Weekly rebuild index. '; date
restic rebuild-index --verbose
echo -n 'Running forget then prune '; date
restic forget --verbose --keep-daily 8 --keep-weekly 8 --keep-monthly 24
restic prune  --verbose
echo -n 'All cleanups done, script finishing: '; date
</pre>

Today's email from the cron job read:
<pre>


C:\users directory on Jonah. Weekly rebuild index. Tue 14 Aug 03:45:01 BST 2018
counting files in repo
[39:51] 100.00%  12189 / 12189 packs

finding old index files
saved new indexes as [27912e55 5146c7eb c93d8b9b ffc97171 1885147f]
remove 45 old index files
Running forget then prune Tue 14 Aug 04:33:15 BST 2018
Applying Policy: keep the last 8 daily, 8 weekly, 24 monthly snapshots
snapshots for (host [Jonah], paths [C:\Users]):

keep 23 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
d23c2e66  2017-11-30 01:16:25  Jonah                   C:\Users
efff726e  2017-12-31 01:16:39  Jonah                   C:\Users
0223f9e7  2018-01-31 01:15:43  Jonah                   C:\Users
68459ce8  2018-02-28 01:15:37  Jonah                   C:\Users
a3a2ebae  2018-03-31 01:15:58  Jonah                   C:\Users
31d75f46  2018-04-30 01:25:35  Jonah                   C:\Users
1821bf49  2018-05-31 01:15:39  Jonah                   C:\Users
3c090c71  2018-06-30 23:15:00  Jonah                   C:\Users
2e3e91af  2018-07-01 23:15:01  Jonah                   C:\Users
664956f4  2018-07-08 23:15:01  Jonah                   C:\Users
281f5d9b  2018-07-15 23:15:00  Jonah                   C:\Users
a50667c9  2018-07-22 23:15:01  Jonah                   C:\Users
9afa722b  2018-07-29 23:15:01  Jonah                   C:\Users
2ae4a845  2018-07-30 23:15:01  Jonah                   C:\Users
6c360c3e  2018-08-05 23:15:01  Jonah                   C:\Users
9227c7b0  2018-08-06 23:15:01  Jonah                   C:\Users
7f920491  2018-08-07 23:15:01  Jonah                   C:\Users
56fb610c  2018-08-08 23:15:01  Jonah                   C:\Users
a9bfe513  2018-08-09 23:15:01  Jonah                   C:\Users
e8dda3b0  2018-08-10 23:15:00  Jonah                   C:\Users
b3b404c1  2018-08-11 23:15:00  Jonah                   C:\Users
73ca41e5  2018-08-12 23:15:00  Jonah                   C:\Users
c6cbf242  2018-08-13 23:15:01  Jonah                   C:\Users
----------------------------------------------------------------------
23 snapshots

remove 5 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
7ea9218b  2018-06-24 01:15:01  Jonah                   C:\Users
9f0ba09f  2018-08-01 23:15:00  Jonah                   C:\Users
b4c6c20f  2018-08-02 23:15:00  Jonah                   C:\Users
3ae80f4a  2018-08-03 23:15:01  Jonah                   C:\Users
81278f7f  2018-08-04 23:15:01  Jonah                   C:\Users
----------------------------------------------------------------------
5 snapshots

counting files in repo
building new index for repo
[26:10] 100.00%  12189 / 12189 packs

repository contains 12189 packs (355330 blobs) with 56.446 GiB
processed 355330 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 23 snapshots
[4:29] 100.00%  23 / 23 snapshots

found 331948 of 355330 data blobs still in use, removing 23382 blobs
will remove 0 invalid files
will delete 243 packs and rewrite 867 packs, this frees 16777215.998 TiB
[7:45:39] 100.00%  867 / 867 packs rewritten

counting files in repo
[37:02] 100.00%  11615 / 11615 packs

finding old index files
saved new indexes as [23b326dc 5d9fee95 07cc4db6 7a50f8c8]
remove 5 old index files
[13:19] 100.00%  1110 / 1110 packs deleted

done
All cleanups done, script finishing: Tue 14 Aug 13:49:24 BST 2018
</pre>

Sorry, no more huge numbers :-)

**Comment by chrestomanci** [comment]
I have used your nightly build to re-do the prune, and I am now getting sensible numbers:
<pre>
found 333852 of 334452 data blobs still in use, removing 600 blobs
will remove 0 invalid files
will delete 20 packs and rewrite 82 packs, this frees 204.517 MiB
[43:54] 100.00%  82 / 82 packs rewritten
</pre>
Thanks for the incredibly quick fix!

**Comment by fd0** [comment]
Thanks for the feedback! :)
