### ISSUE TITLE
New directory/added data totals in verbose output don't add up

### ISSUE THREAD

**Issue by gsauthof** [restic/restic#1956]
Output of `restic version`
--------------------------

    restic 0.9.2 compiled with go1.10.3 on linux/amd64

How did you run restic exactly?
-------------------------------

    restic -r sftp:restic@example.org:/restic-repo -v backup /etc /home /opt /srv /var

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

sftp

Expected behavior
-----------------

- the number of reported new directories is greater than 1
- the reported 'added to the repo'  space matches the 'processed' amount

Actual behavior
---------------

    lock repository
    load index files
    start scan on [/etc /home /opt /srv /var]
    start backup on [/etc /home /opt /srv /var]
    scan finished in 4.646s: 44955 files, 86.558 GiB
    uploaded intermediate index b80f7afc
    uploaded intermediate index b0ef6087
    
    Files:       44955 new,     0 changed,     0 unmodified
    Dirs:            1 new,     0 changed,     0 unmodified
    Data Blobs:  57306 new
    Tree Blobs:      2 new
    Added to the repo: 20.895 GiB
    
    processed 44955 files, 86.558 GiB in 7:16

Note that:

- the specified backup locations certainly contain more than 1 directory (vs. `Dirs: 1 new`).
- the total reports on the one hand `Added to the repo: 20.895 GiB` but before and later reports that it scanned/processed `86.558 GiB`

Steps to reproduce the behavior
-------------------------------

1. make sure that restic repository destination is empty (such that it's created from scratch in the next backup command
2. call `restic -r ... -v backup ...` (see above)
3. check out the verbose output

Do you have any idea what may have caused this?
-----------------------------------------------

no

Do you have an idea how to solve the issue?
-------------------------------------------

no

Some additional information - one day later, a 2nd  run (same backup as above) to create a 2nd snapshot yields this output:

    [..]
    scan finished in 2.963s: 44934 files, 86.569 GiB
    
    Files:          14 new,   743 changed, 44177 unmodified
    Dirs:            0 new,     1 changed,     0 unmodified
    Data Blobs:    122 new
    Tree Blobs:      2 new
    Added to the repo: 49.436 MiB
    
    processed 44934 files, 86.569 GiB in 0:08
    snapshot 8a03dc7b saved

Again, the output reads as if the last snapshot just contained one directory which is clearly incorrect.

Did restic help you or made you happy in any way?
-------------------------------------------------

yes, its documentation is very well written and thus a joy to read; restic is very fast for what it does and otherwise seems to work fine

**Comment by fd0** [comment]
Hey, thanks for the report. The directory numbers are wrong, we're already aware of this bug and it this is tracked as #1863.

The second expectation you mentioned ("the reported 'added to the repo' space matches the 'processed' amount") is, I think, based on a misunderstanding:

 * `processed` is the sum of all data in the files/dirs to backup
 * `added to the repo` is the amount of newly added data to the repository

Since restic uses clever deduplication, it is realistic that for an initial backup of file/dirs with ~86GiB data in them, the deduplicated data is only ~21GiB in size.

Does that make sense to you? Please let us know if you have ideas on how to improve the documentation on this...

I'm going to close this issue for now. The main bug is tracked as #1863, please subscribe over there to get a notification once we resolve it.

Please feel free to add further comments. Thanks!

**Comment by gsauthof** [comment]
Yes, makes sense - the space difference can be explained by the deduplication.

Is it possible to tweak the verbose output to make it obvious to new users that deduplication is going on?

For example, instead of

    Added to the repo: 49.436 MiB

perhaps something like this:

    Added to the repo: 49.436 MiB (deduplicated)

In the documentation, the start of the 'Backing up' section already has a verbose output example. Perhaps it makes sense to tweak the numbers a bit such that a bigger difference between added and processed volume is easily noticed. A small paragraph after that output could then explain that the (in some cases quite dramatic) difference is a result of the clever deduplication.

**Comment by fd0** [comment]
I've added a bit of text as you suggested: https://github.com/restic/restic/commit/31176d212b796906115b01d612c30d356060e7e2
