### ISSUE TITLE
Restic stats returns incorrect values for B2 backend

### ISSUE THREAD

**Issue by firecat53** [restic/restic#1960]
Output of `restic version`
--------------------------

    # restic version
    restic 0.9.2 compiled with go1.10.3 on linux/amd64

How did you run restic exactly?
-------------------------------

    # export $(cat .restic_backup_env|xargs)
    # env|grep -i 'restic\|b2'
    RESTIC_PASSWORD=<pass>
    B2_ACCOUNT_KEY=<key>
    B2_ACCOUNT_ID=<id>
    RESTIC_REPOSITORY=b2:<bucket-name>

    # restic stats
    repository 5451d26a opened successfully, password is correct
      Total File Count:   14124172
            Total Size:   13.125 TiB

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

B2

Expected behavior
-----------------

Expected values to at least somewhat match those shown by Backblaze on the
Bucket list page:

Current Files: 98,177
Current Size: 501.2 GB

Actual behavior
---------------

See above results for `restic stats`:

Total File Count:   14124172
Total Size:   13.125 TiB

Steps to reproduce the behavior
-------------------------------

I've only got the one repository, so I'm assuming anyone with a B2 repo could
reproduce this.

Do you have any idea what may have caused this?
-----------------------------------------------

Looks like maybe it's adding all the files in each snapshot and totaling them all?

Do you have an idea how to solve the issue?
-------------------------------------------

I don't, sorry! Haven't learned Go yet.

Did restic help you or made you happy in any way?
-------------------------------------------------

It seems much less fragile and easier to use than duplicity, which I used for
many years!

**Comment by mholt** [comment]
> Expected values to at least somewhat match those shown by Backblaze on the
Bucket list page

I think this is the bug. :wink: `restic stats` has several counting modes, and the default is the restore size. And when no snapshot is given, all snapshots are counted. So you're not counting disk usage here, you're counting the size it would be required to restore _all_ your snapshots. It's documented here: https://restic.readthedocs.io/en/stable/manual_rest.html#getting-information-about-repository-data

Also note that B2 lifecycle settings will usually make any size calculation differ slightly unless you account for their versioning. (Even changing your lifecycle settings to "keep only the last version of a file" will keep multiple versions until the next day when the lifecycle rules are applied.)

**Comment by firecat53** [comment]
Ahh, my bad. I read help output, but failed to go read the docs for the detailed version. Sorry for the noise and thanks for the quick reply!

**Comment by fd0** [comment]
Hm, we could add a line explaining what is being displayed in the current mode... are you interested in doing that @mholt? ;)

**Comment by fd0** [comment]
@firecat53 btw, what does `restic stats --mode raw-data` print for the repo?

**Comment by firecat53** [comment]
@fd0:

    # restic stats --mode raw-data
    repository <repo-id> opened successfully, password is correct
      Total Blob Count:   1146228
            Total Size:   466.535 GiB

**Comment by fd0** [comment]
Ok, than looks a lot better ;)
