### ISSUE TITLE
--hostname isn't fully deprecated

### ISSUE THREAD

**Issue by ProactiveServices** [restic/restic#1967]
restic 0.9.1 (v0.9.1-45-g4503c896) compiled with go1.10.3 on windows/amd64

`restic backup` uses the `--hostname` parameter, but all of the other verbs use `--host` and prune suggests it's deprecated. `backup` doesn't seem to support `--host` at all. The short parameter `-H` doesn't seem to be specified for all of the verbs, either.

**Comment by fd0** [comment]
Good point, that's something we need to clean up. thanks!
