### ISSUE TITLE
Prevent hosts from reading each others' data

### ISSUE THREAD

**Issue by colans** [restic/restic#1972]
Restic version:  `restic 0.9.1 compiled with go1.10.1 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

From https://github.com/restic/restic/issues/784:
> Better host separation, which allows a host to read only its own data (or more generically, only read data it has rights to). This does allow a host to recover its own files, without accessing other hosts' data.

What are you trying to do?
--------------------------

Prevent hosts from reading each others' data.

I think this would make the most sense as an `rclone serve restic` option so that each host can't override the Restic setting, but I'm not sure that rclone understands the concept of hosts.  If it does, we should move this issue over there.   Otherwise, we'd have to figure out a way to do it on the Restic side that prevents the option from being overridden (if that's even possible).

Did restic help you or made you happy in any way?
-------------------------------------------------

It's the best component of a backup system I've ever seen!

**Comment by rawtaz** [comment]
Why did you create a new issue when there seems to be existing issues that already discuss what you want? How is this issue different from the discussion you're already referencing?

**Comment by colans** [comment]
One possible way to handle this would be for each host to have its own repository, but then you'd lose deduplication.

**Comment by matthijskooijman** [comment]
I wonder if making a write-only option work would need changes to the restic repository format? It should at least be possible to know if an object exist, which might involve reading index files when these objects are inside packs?

**Comment by fd0** [comment]
Thanks for creating a separate issue. It is different from #187 (which is about separation of backup and restore), and it is also different from #784 (which is about only being able to add data, not delete data).

We can leave this issue open for now, but be aware that it is **very** hard to implement in my opinion, and I'm not sure if it's worth the development time. If you need isolation between hosts, use separate repos. That's easy to understand and control. :)

> Or does the serve restic command already handle looking inside the repository rather than just serving files dumbly?

The server components don't have any means to look into files, besides the directory, there's no way the server knows what's in it. All encryption happens exclusive on the client.

**Comment by rawtaz** [comment]
After discussing this with @fd0 we came to the agreement to close this issue. The reason isn't that it's a bad idea (not saying that), but that it's not even on the long term roadmap for now. If there's an opportunity and more concrete thoughts on a practical approach to implement it later on we'll just reopen it. Thanks regardless!

**Comment by colans** [comment]
Even though I'm the one that opened this, I now agree that it should be out or scope because you can simply run another instance with different storage.
