### ISSUE TITLE
Output only on errors, otherwise completely silent

### ISSUE THREAD

**Issue by jkaberg** [restic/restic#1974]
Output of `restic version`
--------------------------

restic 0.9.1 compiled with go1.10.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I would like to see an feature that only outputs incase of error, and is completely silent otherwise. The reason for this is I run restic on cron with mail sending. And I only really want to be notified (mail) in case there is an error, otherwise I trust restic to do what it does best.

What are you trying to do?
--------------------------

If/when the feature is implemented, I see myself using an flag like restic --no-errors backup and it would only output stuff in case of errors.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes. I love how restic operates, how efficient it is and that it supports so many backends (through rclone). Very well done, much appreciated!

**Comment by fd0** [comment]
Hm, isn't this exactly what `--quiet` does? For `backup` this already works, which other commands do you run with cron?

Besides, there's a very handy tool called `chronic` (Debina package `moreutils`) which silences a program unless it exits with an error code, then all output is printed:

```
chronic runs a command, and arranges for its standard out and standard error to only be displayed if the
command fails (exits nonzero or crashes).  If the command succeeds, any extraneous output will be hidden.

A common use for chronic is for running a cron job. Rather than trying to keep the command quiet, and having
to deal with mails containing accidental output when it succeeds, and not verbose enough output when it
fails, you can just run it verbosely always, and use chronic to hide the successful output.

        0    1 * * * chronic backup # instead of backup >/dev/null 2>&1
        */20 * * * * chronic -ve my_script # verbose for debugging
```

**Comment by jkaberg** [comment]
I'm sorry @fd0, you are complely right. `--quiet` does indeed do what I want, I don't know how I overlooked that.

Thanks!

**Comment by fd0** [comment]
Cool, thanks for the feedback!
