### ISSUE TITLE
How do I manage repos ?

### ISSUE THREAD

**Issue by rprihoda** [restic/restic#1977]
Maybe I am just missing something in the docs, but is there a way to delete repos? What is the proper way to insure restic forgets a repo ?

**Comment by rprihoda** [comment]
Ok , I get that, but restic itself has no way of doing that , correct ? I'd have to manually purge the files that restic created in the repo whether it be s3 b2 or local storage, correct ?

**Comment by mholt** [comment]
Yes, I believe so.

However, you could try running a very aggressive prune, although I'm not sure that will delete every single snapshot.

**Comment by fd0** [comment]
You can forget all snapshots with `restic forget --keep-last; restic forget latest` and then run `restic prune`, but this will keep the directories and a few files e.g. in `keys/` in the backend. There's no way to let restic delete a repository completely. I think having a way to delete an entire repo is not so important...

**Comment by tnatanael** [comment]
+1 for this feature...

**Comment by jtagcat** [comment]
@tnatanael On GitHub and other platforms, please do not comment "+1, me too" and more. Instead use the reaction "+1" on the original comment.
![image](https://user-images.githubusercontent.com/38327267/65380157-779d2980-dcc4-11e9-8072-48ca5aaf44bc.png)

**Comment by rawtaz** [comment]
I'm closing this. It won't happen in the foreseeable future from what I can tell due to activity and previous comments.

**Comment by MichaelEischer** [comment]
@asche77 Please open a new issue if you think there is still a problem. From the log snippet you provided, everything looks as it should. After deleting a repository, restic obviously won't be able to read from it.
