### ISSUE TITLE
Show cache dir defaults with `restic --help`

### ISSUE THREAD

**Issue by tjrana** [restic/restic#1979]
Output of `restic version`
--------------------------
`restic 0.9.2 compiled with go1.10.3 on darwin/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
The `restic --help` command should display location defaults for `--cache-dir` used, similar to how it shows defaults for `--repo` and `$RESTIC_REPOSITORY`.

What are you trying to do?
--------------------------
I am trying to identify the default cache directory location using `restic --help`.

Did restic help you or made you happy in any way?
-------------------------------------------------
I think restic makes backups quickly by utilizing the cache. I can save time by preventing the cache from accidentally being deleted. I like how restic makes it simple to make deduplicated backups.

**Comment by j6s** [comment]
This issue can be closed if I am not mistaken.

**Comment by fd0** [comment]
Yep, thanks! Including the text `Closes #1979` or `Fixes #1979` in the text of a pull request, that issue will be closed when the PR is merged (for next time!) ;)
