### ISSUE TITLE
Parse "global flags" after sub-command

### ISSUE THREAD

**Issue by cfcs** [restic/restic#198]
When a user initially takes `restic` for a spin, the user is met by this confusing message:

```
user@godev:~/restic$ ./restic init
Please specify repository location (-r)
user@godev:~/restic$ ./restic init -r ./mydir
unknown flag `r'
```

Regular users can't reasonably be expected to guess that `-r ./mydir` must be specified before the `init`:
```
user@godev:~/restic$ ./restic -r ./mydir init 
enter password for new backend: 
enter password again: 
created restic backend 22727efc8d at ./mydir
```

This should either be documented, or (if at all possible) global flags should be allowed after the sub-command.

**Comment by fw42** [comment]
Agree. This is super confusing and unintuitive. (It is documented though.)

We should at least fix the error message and show an example command.
