### ISSUE TITLE
Allow setting local host name by an environment variable.

### ISSUE THREAD

**Issue by alexeymuranov** [restic/restic#1984]
Output of `restic version`
--------------------------

 `restic 0.9.2 compiled with go1.11 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When the host name of my machine changes, making a new backup takes almost as much time as if it was the very first backup (though deduplication still works).  I think `restic` should allow setting host name with an environment variable, for example, `RESTICLOCALHOSTNAME`, by analogy with [`UNISONLOCALHOSTNAME`](http://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html#archives) for Unison.

What are you trying to do?
--------------------------

I would like to be able to make "incremental" backups quickly even when the local host name of my machine changes.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes, I use it for backing up my personal files.

**Comment by fd0** [comment]
Hey, thanks for the suggestion. Did you know there's a command-line option to do exactly that?

```
$ restic backup --help
[...]
  --hostname hostname        set the hostname for the snapshot manually. To prevent an expensive rescan use the "parent" flag
[...]
```

You can pass a host name explicitly, which is then used by restic.

**Comment by alexeymuranov** [comment]
No, i didn't know, sorry. Then it may be enough for me, thanks.

**Comment by fd0** [comment]
Cool, then I'll close this for now. I'd like to avoid adding more environment variables, at least unless we have a consistent story for configuring restic. Thanks a lot for taking the time to file this issue though! :)

**Comment by alexeymuranov** [comment]
Indeed, command line parameters are fine.

However, I just tried it on a dual-boot system where the same partition is mounted as `/home`, so i tried to make a backup under the same host name, but with different versions of restic: first `0.9.2`, then `0.8.3`.  The parent snapshot was correctly chosen as the previous one, but the operation took like 25 minutes, though the were no changes.  Is this because of different restic versions?

**Comment by fd0** [comment]
You've run into the new behavior of the new archiver code introduced in 0.9.0: https://github.com/restic/restic/blob/master/changelog/0.9.0_2018-05-21/issue-549

**Comment by alexeymuranov** [comment]
Ok, thanks for the explanation.  I suppose then that with the same version there will be no problems.
