### ISSUE TITLE
pack not referenced in any index

### ISSUE THREAD

**Issue by durcom** [restic/restic#1986]
When running restic check I get multiple errors of "pack xxx not referenced in any index"

So I ran a prune as suggested elsewhere...get multiple "unable to list pack xxx header is larger than file"

So I ran a rebuild-index and also get the header is larger than file errors...

Is there any way to fix this or is the repo hopelessly corrupted?

**Comment by fd0** [comment]
Sadly, you did not fill out the issue template :cry: 

`restic prune` takes care of these files. When it is finished, the files have been removed.

**Comment by durcom** [comment]
Sorry about the template thingy, but as noted in my description, restic prune does NOT take care of this.
I ran prune multiple times and the error persists.  Also ran restic rebuild-index several times.  Still get errors running restic check.

  Running restic 0.5.0 on ubuntu 14

**Comment by durcom** [comment]
Just realized I’m running very old version of restic.  Will try latest version and hopefully it works better.

**Comment by saberya** [comment]
hello,maybe it doesnot work better;
-----
restice 0.12.0 centos 7.5
-----
```
pack fe0cb3dd: not referenced in any index
pack 4389dc1c: not referenced in any index
pack de6d2ff1: not referenced in any index
316 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
check snapshots, trees and blobs
no errors were found
[0:00] 100.00%  40 / 40 snapshots
```
i encounter this problem frequently；i dont know what lead to this problem i just backup a file.
i have no idea how to reslove it.
hi,bro,do you have some idea? or you already gave up.

**Comment by rawtaz** [comment]
@saberya There is no error in the output you show above. The fact that there are paths "not referenced in any index" is not a problem, your repository's integrity is healthy according to the "no errors were found". You can however add `--read-data` to your `check` command to make sure that the actual data is intact as well, in case of bit rot, etc.

If you are having another problem, please open a new issue about it, and make sure to fill out the issue template when asked to (including the actual commands you run, and all of their output, where applicable).

**Comment by saberya** [comment]
OK,thanks for your advice.i'll open a new issue.
i have looked up many issues,and I found this problem a couple of times in some issues.
so i just want to confirm if this problem was resloved.
but i'd better to discuss it in a new issue.
thank you @rawtaz
