### ISSUE TITLE
Unexpected behaviour from --keep-last

### ISSUE THREAD

**Issue by aventrax** [restic/restic#1987]
Output of `restic version`
--------------------------
restic 0.9.2 compiled with go1.10.3 on linux/amd64

How did you run restic exactly?
-------------------------------
```
$ restic forget --host livingroom --keep-last 1                                                        
repository 764a05e0 opened successfully, password is correct
found 1 old cache directories in /home/user/.cache/restic, pass --cleanup-cache to remove them
Applying Policy: keep the last 1 snapshots snapshots
snapshots for (host [livingroom], paths [/home/user/Projects/python/]):

keep 1 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
a8171c66  2018-09-07 00:28:45  livingroom  pluto       /home/user/Projects/python/
----------------------------------------------------------------------
1 snapshots

snapshots for (host [livingroom], paths [/home/user/Downloads]):

keep 1 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
e8cdd0c9  2018-09-07 08:30:35  livingroom  pluto       /home/user/Downloads
----------------------------------------------------------------------
1 snapshots
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local Repository

Expected behavior
-----------------
Using --keep-last 1 I expected to have only the last snapshot kept. 

Actual behavior
---------------
Both snapshots are still there, it seems like using --keep-last 2

Did restic help you or made you happy in any way?
-------------------------------------------------
Sure. Very nice software!

**Comment by aventrax** [comment]
Maybe I found the reason of this on the documentation.

> When forget is run with a policy, restic loads the list of all snapshots, then groups these by host name and list of directories. The grouping options can be set with --group-by, to only group snapshots by paths and tags use --group-by paths,tags. The policy is then applied to each group of snapshots separately. This is a safety feature.

So, the two snapshots are there because of different directories? If confirmed, the issue can be closed.

**Comment by dimejo** [comment]
> So, the two snapshots are there because of different directories? If confirmed, the issue can be closed.

Yes, that's exactly the reason. The default behaviour is equally to using `--group-by host,paths`. In your case you would use `--group-by paths`.

**Comment by aventrax** [comment]
Thanks!
