### ISSUE TITLE
--limit-upload not working with GCP Coldline Storage

### ISSUE THREAD

**Issue by kobuki** [restic/restic#1989]
Output of `restic version`
--------------------------

restic 0.9.2 compiled with go1.10.3 on linux/amd64

How did you run restic exactly?
-------------------------------

./restic_0.9.2_linux_amd64 -v --limit-upload 100 backup /full/path/to/source

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Using `RESTIC_REPOSITORY="gs:xxx-backup-1:/backup"`

Expected behavior
-----------------

BW limit goes into effect at around the set limit.

Actual behavior
---------------

Restic uploads full throttle @ 50 Mbps.

Steps to reproduce the behavior
-------------------------------

See command line above.

Do you have any idea what may have caused this?
-----------------------------------------------

No.

Do you have an idea how to solve the issue?
-------------------------------------------

No.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yeah, all in all a very nice and featureful tool, using on B2 with success so far elsewhere. I'm testing it with GC's cold storage to do my home backups.

**Comment by fd0** [comment]
Thanks for the report, this is probably a bug.

**Comment by awused** [comment]
I ran into this on 9.2 compiled on FreeBSD, and it's not specific to coldline. It was definitely working in the past, though it's been a while since the last time I had a significant amount of data churn so I can't say with any confidence when it was last working.

**Comment by fd0** [comment]
Hm, can you please retry with 0.9.3? I forgot this bug existed, so I'd like to confirm it's still a problem first.
