### ISSUE TITLE
restic stats EOF

### ISSUE THREAD

**Issue by aventrax** [restic/restic#1995]
Output of `restic version`
--------------------------
$ restic version
restic 0.9.2 compiled with go1.10.3 on linux/amd64

How did you run restic exactly?
-------------------------------

RESTIC_REPOSITORY, RESTIC_PASSWORD, RESTIC_STAUTH, RESTIC_USER, RESTIC_KEY

restic snapshots --> list all snapshots (no issue)

restic stats --mode raw-data --json
EOF

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

QNAP Object Storage App (OpenSwift keystone v1).

Expected behavior
-----------------
I expected to see the normal/json output.

Actual behavior
---------------
It seems to timeout after a minute:

$ time restic stats --mode raw-data --json
repository a84f0978 opened successfully, password is correct
EOF

real	1m4.149s
user	0m59.944s
sys	0m1.935s

Steps to reproduce the behavior
-------------------------------
Anytime I run the command it exits with same timings.

Do you have any idea what may have caused this?
-----------------------------------------------
A 60s timeout. I'm through a VPN but both lines are 30/30Mbit. Same command launched remotely returns the correct values. Adding strace to the command results in a few...

futex(0xf91720, FUTEX_WAIT, 0, {0, 100000}) = -1 EAGAIN (Resource temporarily unavailable)

Do you have an idea how to solve the issue?
-------------------------------------------
Maybe the issue is on the QNAP old and buggy swift v1 stack, anyway it seems only a timeout issue and maybe it could be easly fixed.

Did restic help you or made you happy in any way?
-------------------------------------------------
:)

**Comment by fd0** [comment]
Since we haven't received any feedback in a long time I'm closing this issue for now. Please add a comment or open a new issue if the problem persists. Thanks!
