### ISSUE TITLE
Unable to remove lock via Minio S3 Gateway

### ISSUE THREAD

**Issue by penguinpowernz** [restic/restic#1997]
Output of `restic version`
--------------------------

```
restic 0.9.2 compiled with go1.10.3 on linux/386
```

How did you run restic exactly?
-------------------------------

```
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=yyy
RESTIC_PASSWORD_FILE=/etc/restic.passwd
TMPDIR=/bkp/restic.tmp
RESTIC_REPOSITORY=s3:http://172.31.0.1:9000/mybucket
$ restic snapshots
Remove(<lock/4a0090c388>) returned error, retrying after 660.575679ms: client.RemoveObject: Access Denied.
...snip...
Remove(<lock/4a0090c388>) returned error, retrying after 16.182032929s: client.RemoveObject: Access Denied.
error in cleanup handler: client.RemoveObject: Access Denied.
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Minio `2018-09-09T22:55:16Z` using the same AWS creds for user ZZZ:

```
MINIO_ACCESS_KEY=xxx
MINIO_SECRET_KEY=yyy
./minio gateway s3
```

User ZZZ has this policy attached:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::mybucket"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::mybucket/*"
        }
    ]
}
```

Expected behavior
-----------------

Be able to remove the lock.

Actual behavior
---------------

It doesn't seem able to remove the lock although it does seem to put the data up there as they appear in the snapshot list.  However subsequent locking operations fail unless you use the `--no-lock` option.

Interestingly, when I run it direct to S3 it works fine I don't get the errors.

Steps to reproduce the behavior
-------------------------------

1. setup an AWS user ZZZ as per the example: https://restic.readthedocs.io/en/stable/080_examples.html#setting-up-restic-with-amazon-s3
1. start minio S3 gateway with ZZZ credentials
1. setup environment vars using AWS creds for ZZZ 
1. `AWS_ACCESS_KEY_ID=xxx`
1. `AWS_SECRET_ACCESS_KEY=yyy`
1. `RESTIC_PASSWORD_FILE=/etc/restic.passwd`
1. `TMPDIR=/bkp/restic.tmp`
1. `RESTIC_REPOSITORY=s3:http://172.31.0.1:9000/mybucket`
1. run `restic backup`
1. see errors about `client.RemoveObject: Access Denied.`
1. run `restic snapshots`
1. see errors about `client.RemoveObject: Access Denied.`
1. run `restic check`
1. see errors about locked repo `Fatal: unable to create lock in backend: repository is already locked by PID 9209 on 0001c0170383 by root (UID 0, GID 0)`
1. run `restic check --no-lock`
1. see no errors
1. change repo to point directly to S3 `RESTIC_REPOSITORY=s3:s3-us-west-2.amazonaws.com/mybucket`
1. run `restic snapshots`
1. see no errors

Do you have any idea what may have caused this?
-----------------------------------------------

Seems to be related to issues seen in #1544 that I found via https://forum.restic.net/t/append-only-mode-with-s3-wasabi/845/3

Do you have an idea how to solve the issue?
-------------------------------------------

It must be permissions as my admin AWS account doesn't suffer the same issues.  However I tried giving total access to the bucket in the policy attached to user ZZZ and it didn't help.

Did restic help you or made you happy in any way?
-------------------------------------------------

Absolutely love it.  Previously I was battling with getting duplicity working on a legacy debian squeeze system and was about to jump into python dependency hell when I found this.  Single binary.  All the functionality of duplicity. Got it working in 5 minutes.  Beautiful.  Thank you for this great tool.

**Comment by fd0** [comment]
Hey, thanks for the report. I haven't used the Minio gateway myself, can you test using restic directly against AWS?

**Comment by penguinpowernz** [comment]
Yea it works beautifully against AWS directly.

**Comment by fd0** [comment]
@harshavardhana can you maybe have a look what's going on here? To me, it feels like a bug in minio rather than restic...

**Comment by penguinpowernz** [comment]
You know I didn't try the latest latest version of minio.  I think there was 1 new release when I made this ticket.  I'll give the latest a go and see what happens.

**Comment by harshavardhana** [comment]
@penguinpowernz with gateway if you created the policy you need to enable etcd, I am assuming you did that already? a

You should try the latest release which fixes an issue with `minio gateway s3` and multi-users.

**Comment by penguinpowernz** [comment]
Sorry for the wait, I've given it a try an am happy to report it all works fine now!

```
$ minio version
Version: 2019-02-26T19:51:46Z
Release-Tag: RELEASE.2019-02-26T19-51-46Z
Commit-ID: 78d116c487278350406e8957d7d35e47caa963d6
```

Thanks a lot for the help guys, keep up the good work.
