### ISSUE TITLE
Docker build.sh improper escape

### ISSUE THREAD

**Issue by stonewareslord** [restic/restic#2001]
Output of `restic version`
--------------------------
N/A, but this occurs on current master, 6bc99ce4 and tag v0.9.2, beb208e1

How did you run restic exactly?
-------------------------------
N/A

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
N/A

Expected behavior
-----------------
When building in a path which contains spaces, `docker run` succeeds.

Actual behavior
---------------
`pwd` is not escaped, so paths with spaces cause `docker run` to fail.

Steps to reproduce the behavior
-------------------------------
Simply run `docker/build.sh` in a directory with spaces:
```bash
git clone https://github.com/restic/restic/ "res tic"
cd "res tic"
docker/build.sh
```
which prints
```
Build binary using golang docker image
docker: invalid reference format.
See 'docker run --help'.
```

Do you have any idea what may have caused this?
-----------------------------------------------
Yes: unescaped pwd

Do you have an idea how to solve the issue?
-------------------------------------------
Yes. 
```
`pwd`
```
should be escaped as
```
"`pwd`"
```

Did restic help you or made you happy in any way?
-------------------------------------------------
Yeah. I loved borg, but it does not distribute static binaries, so I had to compile it from source for android, which constantly caused problems. Having a single static binary backup utility (specifically for arm/aarch64) has been pretty great.

**Comment by stonewareslord** [comment]
Here's a patch:
```patch
diff --git a/docker/build.sh b/docker/build.sh
index ded3e601..34b5e2ac 100755
--- a/docker/build.sh
+++ b/docker/build.sh
@@ -4,7 +4,7 @@ set -e
 
 echo "Build binary using golang docker image"
 docker run --rm -ti \
-    -v `pwd`:/go/src/github.com/restic/restic \
+    -v "`pwd`":/go/src/github.com/restic/restic \
     -w /go/src/github.com/restic/restic golang:1.8.3-alpine go run build.go
 
 echo "Build docker image restic/restic:latest"
```

**Comment by j6s** [comment]
@stonewareslord In an attempt to help the maintainers in clearing out simple / almost done issues I took the liberty of providing your patch in an PR.
