### ISSUE TITLE
Crash with illegal instruction on 32 bit CPU

### ISSUE THREAD

**Issue by edysli** [restic/restic#2007]
I just downloaded and tried the i386 build of restic 0.9.2, but it crashes on a 32bit machine.

Output of `restic version`
--------------------------

    # ./restic_0.9.2_linux_386 version
    Illegal instruction

How did you run restic exactly?
-------------------------------

    # ./restic_0.9.2_linux_386 -v
    Illegal instruction

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

none

Expected behavior
-----------------

no crash

Actual behavior
---------------

Crash with illegal instruction (exit code 132).

Steps to reproduce the behavior
-------------------------------

1. Download and extract restic_0.9.2_linux_386 on a 32 bit machine and OS.
2. Run any restic command.

Do you have any idea what may have caused this?
-----------------------------------------------

Bad compilation flags maybe?

The file appears to be a valid 32bit executable:

    # file restic_0.9.2_linux_386 
    restic_0.9.2_linux_386: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped

The machine is:

    # uname -a
    Linux <name> 3.16.0-6-586 #1 Debian 3.16.57-2 (2018-07-14) i586 GNU/Linux

```
# cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 5
model		: 10
model name	: Geode(TM) Integrated Processor by AMD PCS
stepping	: 2
microcode	: 0x8b
cpu MHz		: 498.037
cache size	: 128 KB
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 1
wp		: yes
flags		: fpu de pse tsc msr cx8 sep pge cmov clflush mmx mmxext 3dnowext 3dnow vmmcall
bogomips	: 996.07
clflush size	: 32
cache_alignment	: 32
address sizes	: 32 bits physical, 32 bits virtual
power management:
```

**Comment by smlx** [comment]
This is due to your processor not supporting SSE instructions.

To run restic on a Geode you'll have to compile it yourself. See here: https://github.com/golang/go/wiki/MinimumRequirements#386

**Comment by edysli** [comment]
I see, thank you for the explanation. I'll check whether the Debian-provided package has the same requirement.

Does restic make use of SSE instructions on purpose?

**Comment by fd0** [comment]
No, but it's used by the Go runtime (which restic uses indirectly). I'll close this for now, please report back if you have any further information. Thanks!
