### ISSUE TITLE
restic init fails when using S3 with SSE:KMS enabled

### ISSUE THREAD

**Issue by cwiggs** [restic/restic#2008]
Output of `restic version`
--------------------------
`restic 0.9.2 compiled with go1.9.6 on linux/amd64`

How did you run restic exactly?
-------------------------------
`restic snapshots --repo s3:s3.amazonaws.com/<removed_s3_bucket>/backups/dev-techops-nexus-efs || restic init --repo s3:s3.amazonaws.com/<removed_s3_bucket>/backups/dev-techops-nexus-efs --verbose 2>&1 | tee -a /tmp/restic.log`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
KMS encrypted S3 bucket

Expected behavior
-----------------
Restic should init the repo if it doesn't already exist

Actual behavior
---------------
I get this error: `Fatal: create key in repository at s3:s3.amazonaws.com/<removed_s3_bucket>/backups/dev-techops-nexus-efs failed: client.PutObject: Access Denied`

Steps to reproduce the behavior
-------------------------------
1. Create KMS (probably works with Amazons AES256) encrypted S3 bucket
2. restic init the s3 bucket

Do you have any idea what may have caused this?
-----------------------------------------------
I believe the restic program is making an AWS API call to create the S3 key and put the restic metadata on the S3 bucket.  However when an S3 bucket is encrypted you have to provide the sse (sse=aws:kms for kms) option to PUT an object.

To verify that this was an issue with server side encryption (SSE) I disabled SSE on the bucket and was able to `restic init`.

Do you have an idea how to solve the issue?
-------------------------------------------
Provide a option for `restic init` so you can tell restic the S3 bucket has SSE.  If so, provide the correct SSE flag to the AWS API call.

Did restic help you or made you happy in any way?
-------------------------------------------------
restic is awesome, I appreciate all the work you all do.

**Comment by fd0** [comment]
Hm, it looks like restic does not support SSE, but rclone does: https://rclone.org/s3/ You can retry using the `rclone` backend (please report back if you do!)

It feels to me that restic won't benefit in supporting SSE at the moment. After all, we're already properly encrypting all data client side and it looks like rclone supports it. So I'm closing this issue for now, please feel free to add further comments. Thanks!

**Comment by amaltson** [comment]
Unfortunately, many organizations require SSE to be enabled to actually use. Would it be possible to reopen this?

**Comment by fd0** [comment]
Adding complexity to restic means more work for us in the long run, so I'm trying to avoid that.

Why can't you use rclone together with restic?
