### ISSUE TITLE
Should restic mount quit with Exit code 130?

### ISSUE THREAD

**Issue by jkirk** [restic/restic#2015]
Output of `restic version`
--------------------------
restic 0.9.2 compiled with go1.10.3 on linux/amd64

How did you run restic exactly?
-------------------------------
```
# restic mount --allow-other --password-file /root/.restic_data_password -r /srv/backups/restic/hera01/ /mnt
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
N/A

Expected behavior
-----------------
Not sure, but we think `restic mount` should not exit with exit code 130, see: https://forum.restic.net/t/should-restic-mount-quit-with-exit-code-130-after-ctrl-c-sigint/1027

Actual behavior
---------------
Exit code 130.

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------
* https://github.com/restic/restic/pull/1722
* https://github.com/restic/restic/issues/1710

Do you have an idea how to solve the issue?
-------------------------------------------
See: https://forum.restic.net/t/should-restic-mount-quit-with-exit-code-130-after-ctrl-c-sigint/1027

Did restic help you or made you happy in any way?
-------------------------------------------------
Simple answer: yes! :+1:  :smile:

**Comment by fd0** [comment]
Probably not, in the special case of `mount`, restic should not return an error code for `^C`. Thanks for the report!

**Comment by fd0** [comment]
Ah, thank you very much for the offer! Unfortunately I think it'd be best to rework the user interface around `restic mount` completely, and cleanup this mess in the process. But that's not really beginner friendly, let me know if you want to try anyhow!
