### ISSUE TITLE
support for the new Scaleway Object Storage (S3 compatible)

### ISSUE THREAD

**Issue by tapionx** [restic/restic#2023]
Output of `restic version`
--------------------------
0.8.3

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Add a new backend supporting the new Scaleway Object Storage

https://www.scaleway.com/docs/object-storage-feature/

What are you trying to do?
--------------------------

I would like to use restic to backup my VPS on Scaleway.
Since the internal traffic will be free, i would love to use that Object Storage.

Did restic help you or made you happy in any way?
-------------------------------------------------

Restic is awesome!

**Comment by rawtaz** [comment]
@tapionx Thanks for filling out the issue template!

First, please update your restic version, the latest version is 0.9.2 and has lots of improvements and fixes since 0.8.3. You can go to https://github.com/restic/restic/releases to get a binary for your OS, if your package manager isn't updated.

Second, Scaleway say on their website that the object storage is S3 compliant, so you should be able to use it straight off with restic using the S3 backend. They do say that they "currently support a subset of S3 operations", but give it a shot and see how it works. More info is at https://www.scaleway.com/docs/s3-object-storage-api/ apparently.

**Comment by tapionx** [comment]
i think version is not relevant here..
I will try indeed! Do you think it's just a matter of replacing `s3.amazonaws.com` with Scaleway endpoint?

**Comment by rawtaz** [comment]
Yes, the version note was just a friendly suggestion, considering your current version is very old. If you can, I recommend you update.

Yeah, that's the first thing to do; Try to use it as regular S3 (but obviously with a valid endpoint, as you say). See https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#amazon-s3 for more detailed instructions 👍

**Comment by fd0** [comment]
I agree with @rawtaz, it should work out of the box with either the s3 backend or with the rclone backend, given that it works with programs like `aws-cli`: https://computingforgeeks.com/how-to-backup-files-to-scaleway-object-storage-using-aws-cli/

I'm going to close this issue for now, please feel free to add further comments when you try it. Thanks!

**Comment by juzam** [comment]
It seems that Scaleway Object storage is unusable if you are using V4 Signatures (works fine with V2, at least using https://s3browser.com/) 
with restic 0.9.2 i get:

```
Fatal: create repository at s3:s3.nl-ams.scw.cloud/restic-test failed: client.BucketExists: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

which is consistent with what I get when using V4 signature with s3browser:

![image](https://user-images.githubusercontent.com/1434180/46664708-0d2dcf00-cbc2-11e8-869b-e0724f2e8365.png)

**Comment by fd0** [comment]
Hm, as far as I know the s3 library we're using (minio-go) supports v2 and v4 signatures. Can you maybe say a word on that @harshavardhana?

Did you try using the `rclone` backend yet?

We're trying not to add new backends for now, doing so creates a lot of maintenance and testing work...

**Comment by juzam** [comment]
> Did you try using the `rclone` backend yet?

@fd0 not yet, I'll try and report back 

> We're trying not to add new backends for now, doing so creates a lot of maintenance and testing work...

Ack. no need to add new backends if we can manage with the existing ones.

@harshavardhana From my limited testing it seems that Scaleway only supports v2 signatures but it should still be useable with minio-go, isn't it? maybe I'm missing something obvious, sorry for that.

**Comment by harshavardhana** [comment]
> @harshavardhana From my limited testing it seems that Scaleway only supports v2 signatures but it should still be useable with minio-go, isn't it? maybe I'm missing something obvious, sorry for that.

yes, in that case, you need to use minio.NewV2() - I don't think restic supports that @fd0 ?

**Comment by fd0** [comment]
thank you very much for leaving feedback! :)

**Comment by ston3o** [comment]
Actually, I use this command `restic --repo rclone:scaleway:my-bucket init`

```
# ~/.config/rclone/rclone.conf 

[scaleway]
type = s3
provider = Other
env_auth = false
access_key_id = MY_ACCESS_KEY
secret_access_key = MY_SECRET_KEY
endpoint = s3.nl-ams.scw.cloud
acl = private
region = other-v2-signature
```

Thanks @juzam

**Comment by juzam** [comment]
just a quick update to anyone is looking to use Scaleway service. I had trouble saving backups to the `nl-ams` region and the support suggested changing the region parameter to `region = nl-ams` and the issue was resolved. I didn't try any bucket in the now available 'fr-par' region.

**Comment by newtoncorp** [comment]
FYI, this works both on `nl-ams` or `fr-par` region (with no `~/.aws/*`):

```
ip route add blackhole 169.254.169.254/32
mc config host add s3 https://s3.fr-par.scw.cloud:443 ACCESS SECRET
sed -i 's/S3v4/s3v2/g' ~/.mc/config.json
./restic_0.9.5_linux_amd64 -r s3:https://s3.fr-par.scw.cloud/BUCKETNAME init
```

We do support SigV4, but we don't have a "common" endpoint and Minio does not switch region (`The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'fr-par'`)

Cheers

**Comment by harshavardhana** [comment]
Restic should update to latest minio-go we have done some changes to handle region requirements appropriately.

**Comment by juzam** [comment]
> Restic should update to latest minio-go we have done some changes to handle region requirements appropriately.

@fd0 is this hard to implement? even if it works via rclone, using the s3 backend directly is more straightforward (and clean if you ask me). thank you for your time :)

**Comment by ston3o** [comment]
Due to errors, I recently changed my rclone.conf : 

```conf
# ~/.config/rclone/rclone.conf 

[scaleway]
type = s3
provider = Scaleway
env_auth = false
access_key_id = MY_ACCESS_KEY
secret_access_key = MY_ACCESS_KEY
region = fr-par
endpoint = s3.fr-par.scw.cloud
```

Inspired of https://habd.as/post/borg-backup-minio-scaleway/ article

**Comment by wintamute** [comment]
I had the same issue and added support for Scaleway to minio-go. Then rebuilt restic (and mc) with the updated version and both work fine, no further changes required, just use the s3 backend.
My changes automatically set the correct region based on the endpoint URL.
I submitted a PR to minio-go (https://github.com/minio/minio-go/pull/1188), lets see if they get merged.

**Comment by Kaan88** [comment]
It seems it's up to restic developers to add region support. Should this issue be reopened?

**Comment by rawtaz** [comment]
@Kaan88 Does https://github.com/restic/restic/pull/2484 solve what you just asked about (region support)?

**Comment by Kaan88** [comment]
@rawtaz It definitely  does. I didn't need to set the environment variable.

**Comment by rawtaz** [comment]
Awesome!
