### ISSUE TITLE
Feature: Print size of cache directories

### ISSUE THREAD

**Issue by j6s** [restic/restic#2028]
Output of `restic version`
--------------------------
Current master: 
```
$  ./restic version 
restic 0.9.2 (v0.9.2-130-g0916ff71-dirty) compiled with go1.10.4 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
It would be nice if restic would print the total size of the cache in the table outputted by `restic cache`.  This would increase the usefulness of the command.

Currently the output of the command is as follows (in this instance including the output of #2027:
```
$ ./restic cache
Repo ID     Last Used     Old
-----------------------------
426f9cb6c8  244 days ago  yes
469099403b  0 days ago
-----------------------------
2 cache dirs in /home/j/.cache/restic
```

Having an additional column containing the size of the cache directory would be cool ideal.

```
$ du -h --max-depth=1 $HOME/.cache/restic/
362M	/home/j/.cache/restic/426f9cb6c8d17fa92318ac340a68a4480b685f4fb9df864e3ecbde820e5f5afd
682M	/home/j/.cache/restic/469099403b967aaba024805d666f87ec0392828656ed61ac2ff75df1ff124aa6

$ ./restic cache 
Repo ID     Last Used     Old    Size
--------------------------------------
426f9cb6c8  244 days ago  yes    326M
469099403b  0 days ago           682M
--------------------------------------
2 cache dirs in /home/j/.cache/restic
```

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic backs up all of my data as well as most people around me. About half of my NAS is filled with restic repositories. Thankfully I have never been in the situation where I needed those backups - but restic helps me sleep at night.

**Comment by fd0** [comment]
Hm, I like the idea, but walking the directories is going to be expensive for large cache directories... maybe optionally disable it? `restic cache --no-size`?

**Comment by mholt** [comment]
^ How about optionally enabling it? That way it's fast by default.

**Comment by fd0** [comment]
I thought about that, but the 'cache' command is probably only seldomly use, so it does not matter so much if it's slow... Hm. We should print a message along the lines of "determining cache sizes (disable with --no-size)" or so?

**Comment by mholt** [comment]
Good point; it's probably not _that_ slow on most systems anyway. I'm indifferent -- sizes would be useful I guess.
