### ISSUE TITLE
Windows OS: Restic does not back up important files because they are being used by another process

### ISSUE THREAD

**Issue by zemb** [restic/restic#2035]
Output of `restic version`
--------------------------
restic 0.9.2 compiled with go1.10.3 on windows/amd64

How did you run restic exactly?
-------------------------------
restic_0.9.2_windows_amd64.exe  backup --repo E:\Backup\ Restic C:\

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local

Expected behavior
-----------------
File accessed and backed up.

Actual behavior
---------------
error: open \\?\C:\Users\...\Documents\encrypted: The process cannot access the file because it is being used by another process.

Steps to reproduce the behavior
-------------------------------
Open a file (in this case, it is a mounted Veracrypt volume) and keep it open/mounted
Try to back it up
Restic cannot access it

Do you have any idea what may have caused this?
-----------------------------------------------
It is opened by another process (in this case, Veracrypt).

Do you have an idea how to solve the issue?
------------------------------------------
It is technically possible because I have tried EaseUS Todo Backup trial version to back it up and restoring it successfully.
I have tried to Google it up, how to solve it.
Some web page mentioned making a 'shadow copy' of the file and read it.
I wonder if opening it in some read-only mode would work.

Did restic help you or made you happy in any way?
-------------------------------------------------
The variety of supported platforms and storage locations is awesome.
Features, de-duplicating.
Good documentation.
It is open-source!
I am happy that I found it today.

**Comment by fd0** [comment]
Thanks for the report, @cfbao is right: You will need to create a volume shadow copy yourself (or via the mentioned powershell script) and backup that instead. I'm closing this issue as a duplicate for now, please subscribe to #340. Please feel free to add further comments. Thanks!
