### ISSUE TITLE
Stats command fatal error

### ISSUE THREAD

**Issue by djoke** [restic/restic#2040]
Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.11.1 on linux/amd64

How did you run restic exactly?
-------------------------------
```
restic stats latest
restic stats --mode raw-data latest
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
sftp

Expected behavior
-----------------
```
scanning...
Stats for the latest snapshot in restore-size mode:
  Total File Count:   14368
        Total Size:   77.911 GiB
scanning...
Stats for the latest snapshot in raw-data mode:
  Total Blob Count:   100348
        Total Size:   71.916 GiB
```

Actual behavior
---------------
```
scanning...
Fatal: latest snapshot for criteria not found: no snapshot found
```

Steps to reproduce the behavior
-------------------------------
Running the following commands:
```
restic stats latest
restic stats --mode raw-data latest
```

Do you have any idea what may have caused this?
-----------------------------------------------
No.

Do you have an idea how to solve the issue?
-------------------------------------------
No.

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes! Restic is the best backup solution I've ever tested so far.

**Comment by fd0** [comment]
Thank you very much for the report, this should not happen.

Also, I think it'd be a good idea to print info about the snapshot the numbers belong to.

**Comment by djoke** [comment]
That would be a great addition. I wish I knew how to code so I would be able to do more besides opening an issue.

**Comment by garrmcnu** [comment]
The default value for the `--host` flag is 'H' (the shorthand version of the flag) which causes the lookup for the latest snapshot to fail.

As a workaround, can specify an empty host, e.g. `restic stats --host "" latest`

@fd0 you mentioned it would also be good to print info about the snapshot, what would be useful (perhaps something similar to output of `snapshots` command)?

**Comment by fd0** [comment]
Yes, I thought something similar to what `restic ls` or `restic snapshots` prints, e.g.:
```
$ restic ls latest
snapshot b25aa0fa of [/home/fd0/restic] filtered by [] at 2018-11-24 19:03:40.950883531 +0100 CET):
[...]
```

Maybe a bit less verbose.
