### ISSUE TITLE
self-update: Figure out correct path to the restic binary

### ISSUE THREAD

**Issue by fd0** [restic/restic#2041]
The restic `self-update` command uses the wrong path to the restic binary to update. When restic is in the `PATH` and `restic self-update` is run, it'll leave a new binary in the current directory.

For a user report see https://github.com/restic/restic/pull/1949#issuecomment-429615790

**Comment by wscott** [comment]
FYI, I think this is the API you want:
https://tip.golang.org/pkg/os/#Executable
(as of go 1.8)

**Comment by fd0** [comment]
Cool, thanks!
