### ISSUE TITLE
Compilation error in Android (termux) with go get

### ISSUE THREAD

**Issue by All3xJ** [restic/restic#2046]
After I followed the instructions here https://github.com/bettercap/bettercap/wiki/Compilation-on-Android and have installed dependencies, I get this error during go compilation: 

```
go get github.com/bettercap/bettercap
# github.com/bettercap/bettercap/network
go/src/github.com/bettercap/bettercap/network/net_gateway_android.go:14:8: undefined: str
```

**Comment by fd0** [comment]
Uhm, I'm confused. This is the restic (the backup program) issue tracker, but it looks like you're having troubles installing bettercap?

**Comment by fd0** [comment]
I'm going to close this issue for now, please feel free to add further comments. Thanks!

**Comment by All3xJ** [comment]
I'm sorry, I don't know how the hell I wrote here... Typing and surfing from my phone is not the same of doing It from my laptop. Sorry again
