### ISSUE TITLE
self-update replaces binary even though there is no new version

### ISSUE THREAD

**Issue by jojomi** [restic/restic#2048]
Output of `restic version`
--------------------------
> restic 0.9.3 compiled with go1.11.1 on linux/amd64

How did you run restic exactly?
-------------------------------
> restic self-update

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
irrelevant.

Expected behavior
-----------------
```
find latest release of restic at GitHub
latest version is 0.9.3
your version is up-to-date.
```

Actual behavior
---------------
```
find latest release of restic at GitHub
latest version is 0.9.3
download SHA256SUMS
download SHA256SUMS.asc
GPG signature verification succeeded
download restic_0.9.3_linux_amd64.bz2
downloaded restic_0.9.3_linux_amd64.bz2
saved 14421056 bytes in restic
successfully updated restic to version 0.9.3
```

Steps to reproduce the behavior
-------------------------------
> restic self-update

Do you have any idea what may have caused this?
-----------------------------------------------
no comparison between current and remote version?

Do you have an idea how to solve the issue?
-------------------------------------------
Compare local and remote version and skip update in case they are the same. Or is there a reasoning behind this? Is it a feature? I would imagine this command to be essentially no-op whenever there is no update available, so it could be called often.

Did restic help you or made you happy in any way?
-------------------------------------------------
It is awesome. I love it if people decide to solve a problem once and for all (even though it is never finished). Also like the professional take on community handling by @fd0. Great work!

**Comment by fd0** [comment]
Yep, I know. This has already been resolved in https://github.com/restic/restic/pull/2042

I'm closing this issue for now. Please feel free to add further comments.

**Comment by jojomi** [comment]
I'm sorry I missed that, thanks for fixing it!

**Comment by fd0** [comment]
Ah, don't be sorry, it was buried in the fix for the path to the binary ;)
