### ISSUE TITLE
Restic fails to recognize that files didn't change after mount cycle on fat32

### ISSUE THREAD

**Issue by 5paceToast** [restic/restic#2058]
Output of `restic version`
--------------------------
`restic 0.9.2 compiled with go1.10.3 on linux/amd64`

How did you run restic exactly?
-------------------------------
```sh
cd /run/media/toast
r=$PWD/Toast-Backup/usb
restic -r $r backup ./TOASTRESCUE
udisksctl unmount -b /dev/sdX1 # corresponds to /run/media/TOASTRESCUE
udisksctl mount -b /dev/sdX1
restic -r $r backup ./TOASTRESCUE
restic -r $r snapshots # note the last two snapshots, we'll say deadbeef and feebdaed
restic -r $r diff deadbeef feebdaed
# output => 
```
```
Files:           0 new,     0 removed,     0 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:      0 new,     0 removed
Tree Blobs:     60 new,    60 removed
  Added:   162.455 KiB
  Removed: 162.257 KiB
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Directory

Expected behavior
-----------------

Nothing changed except for the filesystem to get unmounted and remounted. As such, all files should be marked as unchanged.

Actual behavior
---------------

All 60 files in the directory are marked as changed.

Steps to reproduce the behavior
-------------------------------

See the "How did you run restic exactly?" section.

Do you have any idea what may have caused this?
-----------------------------------------------

The restic repository is on a removable usb3 drive (UAS-enabled) formatted as exfat.
The directory being backed up is a removable usb3 stick (no UAS) formatted as fat32.
If I run two backups at once (no unmount remount), I do not see this behavior.
As such, I suspect the problem is with the interaction between restic and fat32.

Do you have an idea how to solve the issue?
-------------------------------------------

No clue, sorry. This does make verifying that nothing went wrong pretty hard, and diminishes the whole "incremental backup" thing, so this is likely quite important.

Did restic help you or made you happy in any way?
-------------------------------------------------

I just find restic to be the most convenient (except for this issue) backup system.
I did need to restore one file once, which, thankfully, went ok.

**Comment by fd0** [comment]
Hey, thanks for the report. Sometimes non-native file systems behave in ways that restic does not expect. I suspect that the so-called "inode" for the file changes, can you please confirm my hunch by running `stat` on a file, remounting the drive, then running `stat` again and paste the output here? Thanks

**Comment by 5paceToast** [comment]
No problem, though it'll have to wait until next Monday (this is work related). I'll mark it on my todo and get back to you with multiple samples of (redacted) data.

**Comment by 5paceToast** [comment]
The inodes do indeed change. Closing this in favor of #2047.
