### ISSUE TITLE
More items than exists processed

### ISSUE THREAD

**Issue by rawtaz** [restic/restic#206]
I ran a few backups yesteday, over different directories, and a couple of them gave these results:

~~~
[5:51] 100.00%  1.995 MiB/s  700.156 MiB / 700.156 MiB  28200 / 28192 items  0 errors  ETA 0:00
[47:20] 100.00%  10.192 MiB/s  28.268 GiB / 28.268 GiB  129944 / 128915 items  4 errors  ETA 0:00
~~~

As you can see, there are more items processed than what was initially scanned.

It's possible that files in these folders change during the backup, especially the latter one.

**Comment by fw42** [comment]
Do you know how to reproduce this issue? Anything special in your directory? (sockets, pipes, weird permissions, unreadable files, anything that stands out)

**Comment by rawtaz** [comment]
Sure thing. I checked the last few backups I made, and they all have more items than there should be (processed). I ran one backup just now, and without touching anything I see the symptoms again (135338 / 134315 items processed this time). During this run I did nothing on the computer that as far as I know would affect the files that were backed up.

There are some files that cannot be read by restic (4 files in total). It's really just my ~/Documents, so it should be all regular files. I can search for pipes etc if you wish.

**Comment by fw42** [comment]
so which number is correct? how many files are actually in your directory?

**Comment by rawtaz** [comment]
Here's the entire output:

~~~
$ ./restic -r sftp://host/restic backup ~/Documents
enter password for repository:
using parent snapshot foo
scan [/Users/user/Documents]
scanned 21507 directories, 112808 files in 0:12
error for someFile: permission denied
error for someFile: permission denied
error for someFile: permission denied
error for someFile: permission denied
[8:31] 100.00%  56.894 MiB/s  28.392 GiB / 28.392 GiB  135338 / 134315 items  4 errors  ETA 0:00
duration: 8:31, 56.84MiB/s
snapshot bar saved

$ find ~/Documents -type d|wc -l
   21507

$ find ~/Documents -type f|wc -l
  112808

$ find ~/Documents -not -type f -and -not -type d|wc -l
    1027

$ find ~/Documents -not -type f -and -not -type d -and -not -type l|wc -l
       0

$ find ~/Documents -type l|wc -l
    1027
~~~

Looks like all of the "extra" items are simply symbolic links (all numbers add up).

Perhaps restic should list the number of symbolic links it found/scanned as well (on the "scanned ..." line), assuming they are really backed up?

**Comment by fw42** [comment]
Confirmed.
```
$ ls -la bla
total 20
drwxr-xr-x  8 flo staff  272 Jul  7 21:29 ./
drwxr-xr-x 49 flo staff 1666 Jul  7 21:28 ../
lrwxr-xr-x  1 flo staff    3 Jul  7 21:29 bar -> foo
lrwxr-xr-x  1 flo staff    3 Jul  7 21:29 bar2 -> foo
lrwxr-xr-x  1 flo staff    3 Jul  7 21:29 bar3 -> foo
lrwxr-xr-x  1 flo staff    3 Jul  7 21:29 bar4 -> foo
lrwxr-xr-x  1 flo staff    3 Jul  7 21:29 bar5 -> foo
-rw-r--r--  1 flo staff    0 Jul  7 21:28 foo
```
```
$ ./restic -r /tmp/bla backup bla
enter password for repository:
scan [/Users/flo/Projects/go/src/github.com/restic/restic/bla]
scanned 1 directories, 1 files in 0:00
[0:00]   0B/s  0B / 0B  7 / 2 items  0 errors  ETA 0:00
duration: 0:00, 0.00MiB/s
snapshot 8f70f1db saved
```

**Comment by rawtaz** [comment]
Does restic back up symbolic links too, and restore them as such?

**Comment by fw42** [comment]
yeah symbolic links are backed up and restored

**Comment by fd0** [comment]
Ha, thanks for figuring out what causes this bug (and especially for the PR fixing it :P)!
