### ISSUE TITLE
0.9.3 not reproducible anymore

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#2061]
Output of `restic version`
--------------------------

restic 0.9.3 compiled with go1.10.4 on linux/amd64

How did you run restic exactly?
-------------------------------

Automatic Debian reproducibility checking.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Expected behavior
-----------------

Be reproducible, as 0.9.2 was.

Actual behavior
---------------

https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/restic.html

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Maybe the change suggested in https://github.com/restic/restic/issues/1958#issuecomment-413972449 ? Maybe some other thing?

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you or made you happy in any way?
-------------------------------------------------

**Comment by fd0** [comment]
Ah, no, the change discussed in #1958 can not be the cause. I've briefly read over the diffs, the changes are paths to the source code embedded into the binaries, e.g. the first hunk is about the path `/build/1st/restic-0.9.3+ds` for the left file, and the path `/build/restic-0.9.3+ds/2nd` for the right file.

For now (until https://github.com/golang/go/issues/28008 is resolved), reproducing Go binaries requires that the paths to the source code are exactly the same.

I'm not sure what's going on, but I'm pretty sure that this is an issue in Debian's system/scripts which try to reproduce binaries.

What strikes me as very odd is that the strings `1st` vs. `2nd` are at different depths in the path.

For 0.9.2, it looks like the build-path stays the same: for the [first build](https://tests.reproducible-builds.org/debian/buildinfo/buster/amd64/restic_0.9.2+ds-2_amd64.buildinfo) and the [second build](https://tests.reproducible-builds.org/debian/logs/buster/amd64/restic_0.9.2+ds-2.build2.log.gz) it's set to `/build/restic-0.9.2-ds`...

**Comment by fd0** [comment]
The lines 64 and 65 of https://tests.reproducible-builds.org/debian/logdiffs/unstable/amd64/restic_0.9.3+ds-1.diff.gz show this:
```diff
@@ -1173,7 +1189,7 @@
 fakeroot is already the newest version (1.23-1).
 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 I: Building the package
-I: Running cd /build/1st/restic-0.9.3+ds/ && env PATH="/usr/sbin:/usr/bin:/sbin:/bin:/usr/games" HOME="/nonexistent/first-build" dpkg-buildpackage -us -uc -b --buildinfo-id=amd64 -rfakeroot
+I: Running cd /build/restic-0.9.3+ds/2nd/ && env PATH="/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/i/capture/the/path" HOME="/nonexistent/second-build" dpkg-buildpackage -us -uc -b --buildinfo-id=amd64 -rfakeroot
 dpkg-buildpackage: warning: --buildinfo-id is deprecated, it is without effect
 dpkg-buildpackage: info: source package restic
 dpkg-buildpackage: info: source version 0.9.3+ds-1
```

**Comment by fd0** [comment]
Ah, it looks like the Debian Go build system runs into an issue I discovered earlier this year, restic is build this way:
```
cd obj-x86_64-linux-gnu && go install -gcflags=\"-trimpath=/build/1st/restic-0.9.3\+ds/obj-x86_64-linux-gnu/src\" -asmflags=\"-trimpath=/build/1st/restic-0.9.3\+ds/obj-x86_64-linux-gnu/src\" -v -p 15 -ldflags "-X \"main.version=0.9.3\"" github.com/restic/restic/cmd/restic
```

So the scripts are trying to strip the build path via `-trimpath=/build/1st/restic-0.9.3+ds[...]`. This does not work reliably with Go 1.10, it would need to pass `-trimpath=all=/build/1st/restic-0.9.3+ds[...]` (mind the `all=`).

This will break again in Go 1.11 (see https://github.com/golang/go/issues/28008). For the binaries I'm uploading to GitHub, we're now using a fixed path for the source code (`/restic`) and dropped the `-trimpath` entirely.

**Comment by fd0** [comment]
This will also be an issue with all other Go programs packaged in Debian, e.g. rclone shows the same differences: https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/rclone.html

**Comment by legrostdg** [comment]
I kept the attribution in the commit and the changelog :-). See https://salsa.debian.org/go-team/packages/dh-golang/merge_requests/6 (and feel free to join salsa if you want to)

**Comment by fd0** [comment]
Cool. I think that should resolve most of the reproducibility issues with Go binaries :)

**Comment by fd0** [comment]
Ah, the commenter on Salsa was right, there was a typo. Would you mind updating the PR? I've also updated the patch I posted earlier.

**Comment by fd0** [comment]
Ok, it's merged. Now what needs to happen before a rebuild in Debian is triggered? `dh-golang` needs a new release, then restic needs to be uploaded again?

I'm inclined to close this issue for now, it has nothing to do with restic... What do you think?

**Comment by legrostdg** [comment]
Sure, let's close this. I guess a rebuild of all Go packages should be triggered. And, if this does fix the issue, the bug can be reopened. Thanks!
