### ISSUE TITLE
Allow separate directory for keys, stored outside of the repository

### ISSUE THREAD

**Issue by cdhowie** [restic/restic#2062]
Fork of discussion from #187.  [My comment there](https://github.com/restic/restic/issues/187#issuecomment-433157426):

> As an aside, there is a middle ground that could currently be implemented (probably) rather easily: allow keys to be stored outside of the repository.
> 
> One of the attack vectors being addressed is that the attacker gets his hands on a key password, and then (since the keys are stored with the repository) he can decrypt a key with ease.
> 
> What if we allow specification of a separate key directory, where the key files are stored? This directory could be stored locally on each machine that needs to do backups, and it could itself be backed up to a different cloud provider, or even a QR code (~500 bytes is plenty small to be QR-encoded) for cold offline storage in a safety deposit box, for example.
> 
> If the encrypted keys never touch a cloud provider, the attack vector goes away completely. The keys would have to be compromised from the physical premises or exfiltrated with malware, for example.
> 
> This can be done on Restic already if a local copy of the repository is kept -- just exclude the keys directory from being synced to the untrusted remote when running rclone. This cannot be done if there is no local copy and restic directly interacts with the untrusted remote.

CC: @tcely

**Comment by tcely** [comment]
I don't understand why this couldn't be done remotely. Would you elaborate on why you think so?

**Comment by cdhowie** [comment]
Because restic only looks in one location for keys: the `keys` directory on the remote.  E.g. if you don't want your keys on S3, but you are using S3 as the repository location, there is no way to give Restic the key to use _except_ by having it exist on S3.

**Comment by tcely** [comment]
Here are my current theories on how this could operate.

A newly initialized repository:
1. Generate a new public / private key pair within the restic client.
1. Generate a new key from the user input using a new salt and a strong and secure KDF.
1. Encrypt the generated private key using the new key from the KDF output.
1. Store the generated public key into the restic repository as the enrollment key.
1. Offer to (optionally) store the encrypted private key in the restic repository as the recovery key.
1. Provide the user with instructions to store the encrypted private key offline to allow for recovering backups with the user providing the key file and decryption passphrase to the client later.

The upgraded repository task:
1. Generate a new public / private key pair within the restic client.
1. Ask the operator to unlock the repository symmetric key.
1. Generate a new key from the user input using a new salt and a strong and secure KDF.
1. Encrypt the generated private key using the new key from the KDF output.
1. Store the generated public key into the restic repository as the enrollment key.
1. Encrypt the current repository symmetric key using the (generated public) enrollment key to allow recovery of existing backups.
1. Offer to (optionally) store the encrypted private key in the restic repository as the recovery key.
1. Provide the user with instructions to store the encrypted private key offline to allow for recovering backups with the user providing the key file and decryption passphrase to the client later.

Enroll a new restic client as a user of a repository:
1. Generate a new public / private key pair within the restic client for automated backups.
1. Store the public key in the restic repository with a unique identifier.
1. Encrypt the private key using enrollment key and store this in the restic repository using the same unique identifier.
1. Encrypt the private key again using a random generated key and show it to the operator so they can sign backups generated by this client or restore them unassisted later.
1. Backup an enrollment flag file with this client's unique identifier and the client's current UTC timestamp as a tag to the restic repository encrypted with the public key and signed with the private key.

Do you see any problems that would prevent this from operating on both local / remote repositories with only minor changes to the current restic client?

**Comment by cdhowie** [comment]
@tcely This sounds more like it should be a comment on #187? This issue is specifically for just taking the way Restic works today, but allowing the "keys" data to come from somewhere other than the repository.

**Comment by fd0** [comment]
To be honest, I don't see the benefit and I dislike the added complexity. In my opinion, a situation where attackers get access to a repository password and the files in the repository itself, but not a locally stored keys directory is unlikely and not realistic.

We may come back to this once we revisit adding asymmetric crypto, but for now I'd like to close this issue. Please feel free to add further comments. Thanks!
