### ISSUE TITLE
Filesystem-level errors are undetected: file subsequently omitted from backup, even though you're going to want to restore this file

### ISSUE THREAD

**Issue by lgommans** [restic/restic#2064]
Output of `restic version`
--------------------------

restic 0.9.2 compiled with go1.10.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I'm not sure what the solution is, but a solution without solving a problem makes no sense, so let's start with the problem.

Currently, a filesystem-level checksum error (such as from Btrfs) is not detected by restic. Restic does not say anything explicitly, even with `-v`, and just omits the file from the "tree" (if I understand the output correctly).

While the "scrub" feature of such a filesystem is meant to catch checksumming errors, the last thing you want to find after scrubbing is that your backup no longer contains the file. Unfortunately, that is the current behaviour if you're not explicitly prepared for this precise failure.

The way to set this up correctly is to configure scrubbing, have any scrubbing errors emailed to you (or regularly do it manually, I guess), test it, and have a backup retention period longer than your scrub interval + however long you might take to look at it in a worst-case scenario (e.g. multi-week holiday). I feel like people are not only unaware of these necessary steps for their checksumming to be useful at all, they are also typically used to keeping only the latest backup: all you want is a copy to recover from, why even bother with keeping history? The chances of someone setting this up optimally are pretty low.

This could be made a lot more robust if restic detected the filesystem-level issue and handled it. That is the feature request, although I have no specific implementation in mind.

The only reasonable solution I can think of is to take the previous version of the file. Other ideas, like flagging the file and not removing it when someone uses `restic forget`, do not seem right. At a minimum, restic should return a non-zero exit status when it tried to read a file but failed to get its contents.

What are you trying to do?
--------------------------

I'm trying to protect my backup against bit rot. Without even having a lot of data (or maybe I just have really ambitious friends that make my couple terabytes seem like nothing), I've had a couple too many drive failures to be fully comfortable with a situation in which random errors could just propagate into backups completely undetected.

Did restic help you or made you happy in any way?
-------------------------------------------------

Restic generally works well and fast. I've recently started to use it for another system and while a write-only key would have been even more perfect ("most users think your software is pretty neat, but it would be perfect with this *one* extra feature!" I remember reading somewhere :-) ), it's pretty damn good compared to lots of other backup software! Especially encryption being a first-class citizen makes this really great.

**Comment by lgommans** [comment]
I completely forgot to mention that I have steps to reproduce! This script will create a btrfs filesystem (apt install btrfs-progs), make a backup, introduce an error, create another backup, and check the results:

https://gist.github.com/lgommans/8b12aad3065e47bdaa526a2dadbada82

**Comment by lgommans** [comment]
The `strace cat` output is this:

    openat(AT_FDCWD, "mnt/testfile", O_RDONLY) = 3
    fstat(3, {st_mode=S_IFREG|0644, st_size=12000, ...}) = 0
    fadvise64(3, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
    mmap(NULL, 139264, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9e16a41000
    read(3, 0x7f9e16a42000, 131072)         = -1 EIO (Input/output error)
    write(2, "cat: ", 5)                    = 5
    write(2, "mnt/testfile", 12)            = 12
    openat(AT_FDCWD, "/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    openat(AT_FDCWD, "/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    write(2, ": Input/output error", 20)    = 20
    write(2, "\n", 1)                       = 1

It looks like the read call does return an error (`= -1`).

> If the metadata (`mtime`, `inode`) is returned unmodified, then restic will (by default) not re-read the file and reference the data from the last snapshot.

True, that mitigates the risk somewhat. If the data is modified right before corruption occurs, though, restic would try to back it up.

Adding the `-f` flag to `restic backup` does not make any difference in the output it prints.

**Comment by fd0** [comment]
Ah, I can see where you're coming from. Restic's policy is "report the error but carry on", hm. I'm not entirely sure what to do here.

**Comment by lgommans** [comment]
I think setting a non-zero exit status is the most standard way of indicating that an error occurred. When my backup returns with a non-zero status, I would either manually re-run the backup to see what's up, or view the stderr output (if my backup script saves that).

Beyond signaling that there is an issue, I am also not sure what the best course of action is to minimize the damage without introducing odd/unexpected behaviour. In the first post, I mentioned taking the previous version of the file, or flagging the file and not removing it when someone uses `restic forget`, but both are kind of odd, so i'm not sure. Signaling there was an issue, though, is something I would expect my backup software to definitely do.

**Comment by MichaelEischer** [comment]
@lgommans Would returning non-zero exit codes as requested in #2526 solve this issue for you? Or should there be additional changes?

**Comment by lgommans** [comment]
@MichaelEischer Since any other solution would be potentially unexpected behaviour, I guess setting a non-zero exit status makes the most sense. That would solve it for me.
