### ISSUE TITLE
restore --verify: too many open files

### ISSUE THREAD

**Issue by davidak** [restic/restic#2069]
Output of `restic version`
--------------------------
restic 0.9.2 compiled with go1.11 on linux/amd64

How did you run restic exactly?
-------------------------------

```
[davidak@X230:~/tmpp]$ restic restore -i '/home/davidak/nixpkgs' -t /home/davidak/tmpp/ 342c8da4
...
ignoring error for /home/davidak/tmpp/home/davidak/nixpkgs/default.nix: open /home/davidak/tmpp/home/davidak/nixpkgs/default.nix: too many open files
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

minio on NixOS

https://github.com/davidak/nixos-config/blob/25568c70f50eae29aee4ec1d8025fd76d1589673/machines/nas/configuration.nix#L110-L115

Expected behavior
-----------------

restore files without errors

Actual behavior
---------------

restic wants to open more than 1024 files while verifying, but that's not allowed.

without `--verify` the restore only opens one file at a time and has 10 file handlers open, at the end 14.

```
[davidak@X230:~]$ lsof -c restic
COMMAND   PID    USER   FD      TYPE  DEVICE  SIZE/OFF     NODE NAME
restic  28778 davidak  cwd       DIR   254,2      4096  3419056 /home/davidak/tmpp
restic  28778 davidak  rtd       DIR   254,2      4096        2 /
restic  28778 davidak  txt       REG   254,2  13922760 12329434 /nix/store/69sdyzk1xs5pycn9s1pm7qzp23j0pw3b-restic-0.9.2-bin/bin/restic
restic  28778 davidak    0u      CHR   136,7       0t0       10 /dev/pts/7
restic  28778 davidak    1u      CHR   136,7       0t0       10 /dev/pts/7
restic  28778 davidak    2u      CHR   136,7       0t0       10 /dev/pts/7
restic  28778 davidak    3u     IPv4 1948771       0t0      TCP X230.lan:53256->nas.lan:cslistener (ESTABLISHED)
restic  28778 davidak    4u  a_inode    0,12         0     8978 [eventpoll]
restic  28778 davidak    5w      REG   254,2 124270774  4729399 /home/davidak/tmpp/home/davidak/nixpkgs/.git/objects/pack/pack-18195059b4b6532d1d5f9ca4240f52da29b3dd3f.pack
```

Steps to reproduce the behavior
-------------------------------

restore big directory (more than 1024 files) and `--verify`

Do you have any idea what may have caused this?
-----------------------------------------------

`--verify` probably opens unlimited files. maybe opens new files faster than reading already opened ones.

Do you have an idea how to solve the issue?
-------------------------------------------

limit files verify opens at a time.

a similar problem was already solved in https://github.com/restic/restic/issues/101 ;)

Did restic help you or made you happy in any way?
-------------------------------------------------

it's the best backup tool i have used so far and using it feels great most of the time. i like that it's open source, so i can contribute and help solve problems still exists.

**Comment by mholt** [comment]
Hmm, weird. Every code path in `restorer.VerifyFiles()` closes the file when it returns... https://github.com/restic/restic/blob/920727dd343bc2b1c5a4f48fbe15fcd1e7d49f60/internal/restorer/restorer.go#L295-L337

(I am not quite sure why it doesn't use `defer` though)

So if the bug is in this function, it is not obvious...

**Comment by fd0** [comment]
This bug is already resolved in #2044, which (unfortunately) is not included in any released version of restic yet. Can you retry with the master branch?

I'm closing this issue, please feel free to add further comments. Thanks!

**Comment by fd0** [comment]
> (I am not quite sure why it doesn't use defer though)

I don't like using `defer()` for anything that involves error handling, it tends to get very complicated very fast, which negates the convenience of using it in the first place.

**Comment by davidak** [comment]
> Can you retry with the master branch?

When i try to build master i get this error:

```
building '/nix/store/6anxgz7bafflz13jggdik99yiwf5qjfs-restic-2018-11-03.drv'...
unpacking sources
unpacking source archive /nix/store/jbzgy67584fxk0p9v1nki0zssfir01iv-source
source root is source
patching sources
configuring
building
go: cannot use modules with build cache disabled
build failed: exit status 1
exit status 1
builder for '/nix/store/6anxgz7bafflz13jggdik99yiwf5qjfs-restic-2018-11-03.drv' failed with exit code 1
```

Nixpkgs has this build steps defined: https://github.com/NixOS/nixpkgs/blob/3074027738f5ca724ddbd92bbb26ee059926fedc/pkgs/tools/backup/restic/default.nix

I just override the name, version and git commit hash:

```
  nixpkgs.config = {
    packageOverrides = super: let self = super.pkgs; in {
      restic = super.restic.overrideAttrs (oldAttrs: rec {
        name = "restic-${version}";
        version = "2018-11-03";
        src = super.fetchFromGitHub {
          owner = "restic";
          repo = "restic";
          rev = "c0572ca15f946c622d9c4009347dc4d6c31cba4c";
          sha256 = "1ydyqm5hn35iyhg2mg1lbscssks6n3v83qj7v1rjy8n93d711znc";
        };
      });
    };
  };
```

Have you seen that error? Does the build of latest master work differently than 0.9.2?
