### ISSUE TITLE
Direct ceph support as backend

### ISSUE THREAD

**Issue by pooh22** [restic/restic#2073]
Output of `restic version`
--------------------------
restic 0.8.0 (v0.8.0-15-gbb44855)
compiled with go1.9.2 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
The current list of backends supports a lot of options, including S3 and swift. Both are supported interfaces to Ceph cluster storage, but it's not native. That means that running multiple restic backups (from multiple clients) to a ceph backend via S3 requires a gateway, which is a bottleneck in the bandwidth and possibly a single point of failure.

There's a ceph library for Go: https://github.com/ceph/go-ceph

What are you trying to do?
--------------------------
We are currently experimenting with ceph and restic via S3, also looking at Bareos (fork of Bacula), which has librados support.

If restic would support a direct libRADOS based backend, all clients could use all the available bandwidth to the entire ceph cluster storage nodes. This would be good for performance and reliability.

Did restic help you or made you happy in any way?
-------------------------------------------------

I like restic a lot as a backup tool (using it for private backups), it could be useful to replace our daily backups at the university where I work.

**Comment by fd0** [comment]
Thanks for the suggestion. At the moment, we're trying to avoid adding more backends, because they tend to be hard to debug and causes maintenance work. We'll keep it in mind. Doesn't rclone support Ceph directly? If so, you can use the `rclone` restic backend: https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone

**Comment by pooh22** [comment]
If I understand correctly, rclone uses S3 to access ceph: https://rclone.org/s3/#ceph

It would really be a performance and reliability feature to use librados to write backup-objects to all the storage nodes directly (rather than going through a gateway using S3)

I hope you will consider using rados as an additional backend!

Cheers

/Simon

**Comment by fd0** [comment]
Hm, that's a C library, right? If so, I don't think we can link against it, we're trying hard to keep restic free of C-dependencies and only use Go code (which makes the builds and cross-compilation much less complicated).

**Comment by fd0** [comment]
As far as I can see these are Go bindings for the C libraries, that's a C dependency and requires a C compiler and a C linker. Which is exactly what we're trying to avoid :)

**Comment by pooh22** [comment]
Hmm, that's too bad :-(
I can't find any other golang interface to rados, it seems to me the ceph developers want to keep a single library with interfaces to other languages through that library. I doubt that's going to change, because librados is actually writing directly into the cluster... 
I suppose an alternative would be to define multiple s3 gateways on the ceph cluster and distributing the clients over those nodes.

**Comment by ifedorenko** [comment]
Depending how much time/resources you are willing to invest into this, it is certainly possible to implement ceph backend in a "light" restic fork, like I did for MS OneDrive. And if it proves to be wildly popular, who knows, maybe you'll be able to convince fd0 to change his mind.

**Comment by fd0** [comment]
Another option would be to add Ceph support to rclone, which (as far as I know) already has several C dependencies, and therefore the necessary infrastructure.

**Comment by pooh22** [comment]
@ifedorenko At the moment it would be a nice to have, because we still haven't done extended testing and noticed any performance problems.
Perhaps adding librados support to rclone would indeed be an easier path...

It would take me a long time to even start to think about doing this myself, currently I'm more sysadmin than developer ;-)

**Comment by fbarbeira** [comment]
We are using Ceph as backend storage and performance is really good.

Maybe the shortest path for you is to make the radosgw HA starting a few instances and put an haproxy or nginx on top to use as a load balancer.

You can try as well Beast wich is the new Ceph radosgw frontend replacing the civetweb server. It was introduced in the last Ceph LTS version (mimic):

http://docs.ceph.com/docs/mimic/radosgw/frontends/#beast

With this way you can keep your OSD servers in a separate network with private address and you have only one point of access to your cluster, keeping all the S3 compatible features.

**Comment by pooh22** [comment]
@fbarbeira Thanks for that info, I'll check it out tomorrow :-)

**Comment by MichaelEischer** [comment]
We still want to avoid adding new backends. As ceph supports an S3 and Swift API please use one of those.
