### ISSUE TITLE
Directory and file attribute "hidden" not restored

### ISSUE THREAD

**Issue by KeithGrant** [restic/restic#2075]
Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.11.1 on windows/amd64
running in Windows 10

How did you run restic exactly?
-------------------------------
.\restic restore --repo D:\test\ --target '/restore' latest --host XXX --password-file password.txt 

No environmental variables were used in this test.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local file system - no backend server

Expected behavior
-----------------
All files and directories are restored along with their attribute settings. Specifically - the hidden attribute.

Actual behavior
---------------

All files and directories were restored perfectly except the hidden attribute was lost.  For example a .git directory will be fully restored but was visible in the restore. This behavior is consistent across multiple scenarios.

Steps to reproduce the behavior
-------------------------------
Create a Windows file and directory marked hidden. Backup and restore then and the hidden attribute is unset.

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
I cannot tell if the hidden attribute is lost in the backup phase or the restore phase.

Did restic help you or made you happy in any way?
-------------------------------------------------
I think restic is a great tool.

**Comment by fd0** [comment]
Sorry for not responding earlier (I'm currently going through all issues), I think the hidden attribute used on Windows is not saved in the repo right now. I consider this a feature request, thanks for reporting it!

**Comment by heapxor** [comment]
hello, was that issue fixed? thanks!

**Comment by KeithGrant** [comment]
I just completed a test with a hidden directory. The restored directory does not have its hidden attribute set true, so the test failed.

Sorry

**Comment by heapxor** [comment]
@KeithGrant hm weird... so seems its still broken ;/ is there a chance it will be fixed?
not sure if thats connected with https://github.com/restic/restic/pull/3622 ?

**Comment by KeithGrant** [comment]
I have no idea, I’m just a user.
