### ISSUE TITLE
Update threat model

### ISSUE THREAD

**Issue by fd0** [restic/restic#208]
The threat model (section in `doc/Design.md`) should be updated to the latest structure, e.g. there is no `id` or `version` file any more.

Furthermore, remove implementation specific details from it as much as possible. A good example is https://pond.imperialviolet.org/threat.html

Clarify on when the local machine is trusted, e.g. only during backup or when the password is present.

**Comment by MatthewVance** [comment]
When I have some time, I don't mind trying to revise the existing threat model. I'll need some more guidance though to make sure I'm covering it the right way. Also, the example link no longer works, but the Way Back machine has a snapshot of it at https://web.archive.org/web/20150913065100/https://pond.imperialviolet.org/threat.html.

**Comment by fd0** [comment]
Oh, thanks for pointing this out. If you drop by at `#restic` on irc.freenode.net (if you use IRC) sometime in the evening, I'd be happy to discuss this. Thanks for the offer!

**Comment by MatthewVance** [comment]
I haven't had much free time today to get back to you so I just wanted to send this brief note to let you know I haven't forgotten. I don't typically use IRC, but don't mind jumping on one evening when I have some time. I'm not much of a coder, but like the work you're doing here so I wanted to offer to contribute in some small way.

**Comment by fd0** [comment]
Heh, don't rush anything, the threat model will be here tomorrow. I've just realized that we don't live in the same timezone, so "in the evening" is probably something else for you. We can also discuss the threat model in this issue (or have a PR or something else).

**Comment by MatthewVance** [comment]
Thanks. I haven't forgotten about this. I've started drafting something, but it'll take me a bit longer to finish the initial draft up. I'll share some of the ideas here before submitting a pull request.

**Comment by MatthewVance** [comment]
Right now, I'm thinking the following are among the threats I need to address:
- Physical access
- Network access (local and/or remote)
- Malware
- Weak passwords
- Advances in cryptography or computing yields underlying crypto algorithm broken

Please let me know if you think I should add or remove any.

Below is a rough draft of what I have thus far (it doesn't touch on all the above yet). I wanted to go ahead and share it to see if it is along the lines of what you have in mind.

An attacker with access to your backup storage location could:
- Delete or manipulate your backups, thereby impairing your ability to restore files from the comprised storage location.
- Attempt a brute force password guessing attack against a copy of the repository.

An advisory who can passively monitor all Internet traffic could:
- Defer where you are storing your remote backups via http headers (URLs).
- Defer from where you create your backups (i.e., the location where the requests originate).

An attacker who compromises (vial malware, physical access, etc.) the host system making backups could:
- Render the entire backup process untrustworthy (e.g., intercept password,  copy files, manipulate data).

**Comment by fd0** [comment]
There's another thing that came up in a discussion on IRC with @viric the last couple of days: I've added an experimental local cache (see PR #607). We agreed that the cache should be encrypted (at least by default), so that no metadata leaks e.g. when encrypted filesystems are mounted.

This is a temporal perspective: What if attackers gain access to the user's machine or home directory some time after the backup was completed? Especially what happens when the users didn't store the password anywhere (so the attackers are unable to decrypt anything from the repo)?

**Comment by MatthewVance** [comment]
@FiloSottile mentioned a couple of items in his recent [blog post](https://blog.filippo.io/restic-cryptography/) that could be good additions to the threat model. Here's a couple that stood out to me:

> attacker-supplied data can lead to straightforward fingerprinting attacks on any kind of deduplicated system. (This should have been in the threat model.)

> I imagine file/backup sizes are not protected, but it's not mentioned.

**Comment by colans** [comment]
I just noticed:
> The host system a backup is created on is trusted. This is the most basic requirement, and essential for creating trustworthy backups.

Should we say anything about how integrity of the backups can be maintained even if the host does get compromised (with the `rclone serve restic` + SSH forced command set-up)?

**Comment by fd0** [comment]
That's not an easy thing to add. Attackers with the ability to add data to the repo (but not remove something) could still upload pack files with wrong headers. For example, the header says that the file contains the blob with a specific hash, but that's not really the case. I'm not sure what the implications are right now.

**Comment by rawtaz** [comment]
@MatthewVance Is this something that you're still able to tackle? It would be great if we could finish it and close the issue.

**Comment by MatthewVance** [comment]
Yes, I'm still willing to contribute. I'm not confident we can make it
comprehensive, but I think I can help enhance the existing threat model.
It'll take me a few days to pull some info together.

**Comment by MatthewVance** [comment]
@rawtaz I'd like some more eyes on this before submitting a PR. 

I didn't include anything about file/backup sizes not being protected, but can if needed.  I also did not include much detail regarding the local cache (beyond noting it is encrypted by default to also prevent metadata leaks when encrypted filesystems are mounted).

Lastly, what level of detail needs to be added to clarify when the local machine is trusted (during backup, when the repo password is present, etc.)?

https://gist.github.com/MatthewVance/c3888ea022589ea0861acb16be9d4e56

**Comment by rawtaz** [comment]
@cdhowie Can you review this work in progress? You are better suited for commenting on this than I am. Current threat model article is [here](https://restic.readthedocs.io/en/latest/100_references.html#threat-model).

**Comment by cdhowie** [comment]
General copyediting:

* Line 19: comprised -> compromised
* Lines 29 and 30: Defer -> Determine
* Line 29: http -> HTTP
* Line 33: vial -> via

Content notes:

* HTTP header sniffing (line 29) is mitigated by HTTPS, which everyone _should_ be using in 2019.
* Adding data (lines 38-43) has an additional threat: if `forget` with time-based policies is regularly run against the repository, particularly when automated, an attacker could introduce new snapshots (that are empty or contain garbage data) with specifically-crafted timestamps in an attempt to get a future `forget` operation to remove some or all existing good snapshots from the repository.

**Comment by MatthewVance** [comment]
Thanks for the feedback. I plan to work on incorporating the suggested
updates.

**Comment by fd0** [comment]
@MatthewVance thanks for your work on this issue! Please feel free to just submit a PR, which makes the discussion much easier :)

**Comment by MatthewVance** [comment]
Sure thing. PR submitted: https://github.com/restic/restic/pull/2536
