### ISSUE TITLE
Verbose output and password prompt race, sometimes hiding the prompt

### ISSUE THREAD

**Issue by dominikh** [restic/restic#2080]
Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.11.1 on linux/amd64

How did you run restic exactly?
-------------------------------
```
$ restic init --repo /tmp/restic-repo
enter password for new repository: 
enter password again: 
created restic repository d6f13ba7f1 at /tmp/restic-repo

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

$ restic -r /tmp/restic-repo -v backup notes.testing
open repository

Fatal: wrong password or no key found
```

Expected behavior
-----------------
Output should not hide the password prompt

Actual behavior
---------------
The `open repository` debug line overwrites the password prompt. One can still type the password; I chose to type an incorrect one in the example.

The raw terminal output looks like this (the caret escapes unprintable characters):

```
enter password for repository: ^M^[[2Kopen repository^M
```

That is, first the prompt is printed, then the line is cleared and "open repository" is displayed.

This doesn't always happen. Sometimes events occur in the right order, first displaying "open repository", then displaying the password prompt on its own line:

```
^M^[[2Kopen repository^M
enter password for repository: ^M
```

**Comment by fd0** [comment]
Oh, interesting, that's a bug. Thanks for the report!
