### ISSUE TITLE
Windows cache directory not created if LOCALAPPDATA is missing

### ISSUE THREAD

**Issue by Progman2k** [restic/restic#2084]
Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.11.1 on windows/386

How did you run restic exactly?
-------------------------------
In an old Windows NT 5.1 / XP SP3 testbed VM, I ran:
restic -r sftp:elrond:/files/BACKUPTEST -o sftp.command="sftp_elrond.bat" backup "C:\Documents and Settings"

repository 00980320 opened successfully, password is correct
unable to open cache: unable to locate cache directory (APPDATA unset)
[Snipping the rest]

From 'set' we see that APPDATA is set, but LOCALAPPDATA is missing:
APPDATA=C:\Documents and Settings\username\Application Data

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SFTP to a Linux system (CentOS 7.5)

Expected behavior
-----------------
1) When LOCALAPPDATA is undefined, fall back to something else (semi-)gracefully.
2) When stating that an environment variable is missing, specify the right one.  :)

Actual behavior
---------------
From what I can see restic simply tries to push on without a cache directory.  The error message suggests APPDATA is not set but that is incorrect.

Steps to reproduce the behavior
-------------------------------
Run a restic backup on a Windows system that (for one reason or another) lacks the LOCALAPPDATA environment variable.  The variable was reportedly introduced in WinNT 6.0 / Vista.

Do you have any idea what may have caused this?
-----------------------------------------------
In the function linked below LOCALAPPDATA is correctly used if present, but there is no fall-back to APPDATA or TEMP.
[https://github.com/restic/restic/blob/c0572ca15f946c622d9c4009347dc4d6c31cba4c/internal/cache/dir.go#L32](https://github.com/restic/restic/blob/c0572ca15f946c622d9c4009347dc4d6c31cba4c/internal/cache/dir.go#L32)
I haven't followed the code far enough to see what side-effects this might have.

Do you have an idea how to solve the issue?
-------------------------------------------
I would extend the 'if' to check the other possible variables in sequence and use the first one that is valid.  If the lack of a proper cache directory is going to create other issues later, I would suggest extending the error text to indicate this.

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes, Restic is about to make my home backups something I trust again.  Once I've got the hang of it I'll be spreading it to some other places I help manage.

**Comment by fd0** [comment]
Hm, interesting point. I've just fixed the error message, thanks for pointing this out!

I'm inclined to leave the rest as it is. Windows XP has been out of support for some time, and it isn't even officially supported by the Go environment anyway (which needs Windows 7 or later), so we can reasonably assume that `LOCALAPPDATA` is set. That's also what the Go compiler does: 

https://github.com/golang/go/blob/f9fff4554c7ac2c9fa51150d57b163132338b51b/src/os/file.go#L346-L354

If the variable is not set, the error message will point users in the right direction, so they can either set the variable or use `--cache-dir`, or even let restic continue without a cache (which works just fine, it's just slower on incremental backups for non-local backends).

I'll close this issue for now, please feel free to leave any thoughts you have on the issue :)
