### ISSUE TITLE
Increase the granularity of the "keep within" snapshot retention policy

### ISSUE THREAD

**Issue by plumbeo** [restic/restic#2089]
Output of `restic version`
--------------------------

restic 0.9.3 compiled with go1.11.1 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

`restic forget --keep-within` currently accepts time ranges with a minimum granularity of one day. It would be nice to be able to pass to the command ranges measured in hours.

What are you trying to do?
--------------------------

I have a few clients that make a backup daily at a random time between 14 and 18 when they're powered on and connected to the internal network and I want to apply a retention policy that keeps the snapshots made in the last N days.

Neither `--keep-daily N` nor `--keep-last N` help because the number of snapshots taken in the range can change and `--keep-within=Nd` preserves the Nth day snapshot or deletes it according to the (random) times it and the last snapshot were made. 

I'd like to use `--keep-within=Nd6h` to consistently keep the Nth day snapshot.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes, it's great to be able to backup our data on local hard drives, on a local (trusted) storage and on (untrusted) cloud storage using the same software.

**Comment by dimejo** [comment]
Any reason not to use `--keep-last` in this case?

**Comment by plumbeo** [comment]
> Any reason not to use `--keep-last` in this case?

There's no guarantee there will be exactly N snapshots taken in the last N days, it could be fewer.

**Comment by plumbeo** [comment]
https://github.com/restic/restic/pull/2090 merged

**Comment by fd0** [comment]
Ah, forgot this issue, thanks!
