### ISSUE TITLE
prune performance restic vs borg

### ISSUE THREAD

**Issue by cberni** [restic/restic#2091]
I'm running restic 0.9.3 to backup 100gb of files and the prune operation takes too long time (2 hours).
Is the any forecast of performance improvement and make it fast like prune in borg backup?

**Comment by fd0** [comment]
This is the wrong place to ask such questions, we have [the forum](https://forum.restic.net) for that :)

But since you're here now: there are a *lot* of things to optimize in prune, and we'll get there eventually. A first step is #1994.
