### ISSUE TITLE
Add --json option to "restic backup" (feature)

### ISSUE THREAD

**Issue by Mebus** [restic/restic#2096]
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

The "backup" command should support the "--json" flag, because it's one of the essential commands.

What are you trying to do?
--------------------------

I am trying to integrate restic into a GUI.

**Comment by fd0** [comment]
See #1944

**Comment by MichaelEischer** [comment]
This feature is available since restic 0.9.5
