### ISSUE TITLE
Optimize metadata size

### ISSUE THREAD

**Issue by e2b** [restic/restic#210]
While the metadata is just JSON, some file operations might create a lot of data, e.g. when timestamps are changed the whole metadata is rewritten.

Some ideas:
- optimize JSON size/structure (memory vs. speed constraints), e.g. parameter name mapping or using MessagePack/BSON
- inherit information from previous snapshot (management hassle), e.g. with a link to previous version

If I recap correctly, tree elements are shared between snapshots and e.g. moving a folder does only affect its parent tree definition. Also currently each metadata file is saved compressed?

Please share your ideas though this is likely an optimization for later releases.

**Comment by grigorig** [comment]
FWIW, binary JSON style formats often do not save that much space, particularly if you use maps. They are faster to parse, though. Schema-based formats such as Protocol Buffers, Flatbuffers or Cap'n'Proto are universally better, so IMHO that would be the only sensible path to go.

**Comment by MichaelEischer** [comment]
With #3666 merged, the new repository format version always compresses the metadata which should avoid most of the overhead of the json format.
