### ISSUE TITLE
Request: ignore errors when printing to standard out

### ISSUE THREAD

**Issue by mholt** [restic/restic#2102]
Output of `restic version`
--------------------------
2434ab210675cb9995b862032bdb42382bcbf1c6

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
It would be nice if printing to stdout was not a fatal error.

Mostly this line of code (and similar): https://github.com/restic/restic/blob/2434ab210675cb9995b862032bdb42382bcbf1c6/cmd/restic/global.go#L184

Makes it hard (impossible) to spawn restic then close the parent, and have restic still run successfully, simply because stdout is closed...

What are you trying to do?
--------------------------
Run restic with an inherited stdout, after the parent process' stdout is closed (shell closed, terminal window closed, etc.)

Open to discuss how to better handle errors printing to stdout (or stderr!) if possible.

Did restic help you or made you happy in any way?
-------------------------------------------------
Of course you know it has :heart:

**Comment by cdhowie** [comment]
Can't we just `nohup restic ... >/dev/null 2>&1`?

**Comment by mholt** [comment]
@cdhowie That might work (I haven't tested it) but only from bash. I'm using Go to spin up restic with a stdout that closes (and no, it's not one I can really keep open).
