### ISSUE TITLE
backup fails with "slice bounds out of range"

### ISSUE THREAD

**Issue by anarcat** [restic/restic#2104]
Output of `restic version`
--------------------------

    restic 0.9.3 compiled with go1.10.4 on linux/amd64

How did you run restic exactly?
-------------------------------

More or less simply: `restic ls /FILENAME`, see below for a full
console copy-paste.

This is a Debian stretch running restic from the Debian package from
sid.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Local filesystem.

Expected behavior
-----------------

I expected more or less the output of:

    [1366]anarcat@angela:test1$ restic -r repo4 ls latest
    enter password for repository: 
    repository 6cfc1fe1 opened successfully, password is correct
    snapshot 3e8a654c of [/home/anarcat/test/SHA256-533128ceb96cb2a6d8039453c3ecf202586c0e001dce312ecbd6a7a356b201dc] filtered by [] at 2018-11-27 02:02:26.319808687 -0500 EST):
    /SHA256-533128ceb96cb2a6d8039453c3ecf202586c0e001dce312ecbd6a7a356b201dc

Actual behavior
---------------

The program crashes with:

    panic: runtime error: slice bounds out of range

Steps to reproduce the behavior
-------------------------------

Basically those commands:

    restic init
    restict backup --stdin --stdin-filename SHA256-533128ceb96cb2a6d8039453c3ecf202586c0e001dce312ecbd6a7a356b201dc < foo
    restic ls /SHA256-533128ceb96cb2a6d8039453c3ecf202586c0e001dce312ecbd6a7a356b201dc

Here's a full log:

    [1361]anarcat@angela:test$ RESTIC_PASSWORD=test restic init -r repo4
    created restic repository 6cfc1fe1cb at repo4

    Please note that knowledge of your password is required to access
    the repository. Losing your password means that your data is
    irrecoverably lost.
    [1362]anarcat@angela:test$ RESTIC_PASSWORD=test time restic -r repo4 backup --stdin --stdin-filename SHA256-533128ceb96cb2a6d8039453c3ecf202586c0e001dce312ecbd6a7a356b201dc < ~/folipon.jpg
    repository 6cfc1fe1 opened successfully, password is correct
    created new cache in /home/anarcat/.cache/restic

    Files:           1 new,     0 changed,     0 unmodified
    Dirs:            0 new,     0 changed,     0 unmodified
    Added to the repo: 10.560 KiB

    processed 1 files, 0 B in 0:00
    snapshot 3e8a654c saved
    0.66user 0.02system 0:00.91elapsed 75%CPU (0avgtext+0avgdata 48384maxresident)k
    0inputs+120outputs (0major+9667minor)pagefaults 0swaps
    [1363]anarcat@angela:test$ RESTIC_PASSWORD=test restic -r repo4 ls /SHA256-533128ceb96cb2a6d8039453c3ecf202586c0e001dce312ecbd6a7a356b201dc
    repository 6cfc1fe1 opened successfully, password is correct
    panic: runtime error: slice bounds out of range

    goroutine 27 [running]:
    github.com/restic/restic/internal/restic.Find.func1(0x13e, 0xc4202d4330, 0x40, 0x40, 0xc4202dc3e8)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/restic/backend_find.go:27 +0xcf
    github.com/restic/restic/internal/backend.(*RetryBackend).List.func1.1(0x13e, 0xc4202d4330, 0x40, 0x40, 0x1)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/backend/backend_retry.go:133 +0xd7
    github.com/restic/restic/internal/backend/local.(*Local).List.func1(0xc4202d4320, 0x50, 0xc17580, 0xc420226c30, 0x0, 0x0, 0x40, 0xc4222fd4c0)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/backend/local/local.go:267 +0x295
    path/filepath.walk(0xc4202d4320, 0x50, 0xc17580, 0xc420226c30, 0xc42014c6c0, 0x0, 0x0)
    	/usr/lib/go-1.10/src/path/filepath/path.go:357 +0x402
    path/filepath.walk(0xc42014f220, 0xf, 0xc17580, 0xc420226b60, 0xc42014c6c0, 0x0, 0x0)
    	/usr/lib/go-1.10/src/path/filepath/path.go:381 +0x2c2
    path/filepath.Walk(0xc42014f220, 0xf, 0xc42014c6c0, 0xc420010001, 0xc42014c6c0)
    	/usr/lib/go-1.10/src/path/filepath/path.go:403 +0x106
    github.com/restic/restic/internal/fs.Walk(0xc42014f220, 0xf, 0xc42014c6c0, 0xc42014f220, 0xf)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/fs/file.go:99 +0x3f
    github.com/restic/restic/internal/backend/local.(*Local).List(0xc42020ac60, 0xc15640, 0xc42014c600, 0xb86eb6, 0x8, 0xc42020b410, 0x712201, 0xc42020b410)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/backend/local/local.go:238 +0x17a
    github.com/restic/restic/internal/backend.(*RetryBackend).List.func1(0xc42021a7a0, 0xc42021a7a0)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/backend/backend_retry.go:127 +0x12a
    github.com/cenkalti/backoff.RetryNotify(0xc4222fd9d8, 0xc0fd20, 0xc42021a7a0, 0xc4222fd920, 0xc42021a7a0, 0xc42021a7a0)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/cenkalti/backoff/retry.go:37 +0x88
    github.com/restic/restic/internal/backend.(*RetryBackend).retry(0xc42021a520, 0xc15640, 0xc42014c680, 0xc42014f210, 0xe, 0xc42005d9d8, 0xe, 0x40)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/backend/backend_retry.go:36 +0x138
    github.com/restic/restic/internal/backend.(*RetryBackend).List(0xc42021a520, 0xc15640, 0xc42014c600, 0xb86eb6, 0x8, 0xc42021a760, 0x0, 0x0)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/backend/backend_retry.go:126 +0x235
    github.com/restic/restic/internal/restic.Find(0x7f9a6cb71100, 0xc4200a16b0, 0xb86eb6, 0x8, 0x7ffd72e56900, 0x48, 0x0, 0x0, 0x0, 0x0)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/restic/backend_find.go:26 +0x136
    github.com/restic/restic/internal/restic.FindSnapshot(0xc1d760, 0xc42029d110, 0x7ffd72e56900, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/internal/restic/snapshot_find.go:75 +0xb3
    main.FindFilteredSnapshots.func1(0xc420144540, 0xc42020ab10, 0x1, 0x3, 0xc15640, 0xc42014c5c0, 0xc42029d110, 0x0, 0x0, 0x0, ...)
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/cmd/restic/find.go:32 +0x1af
    created by main.FindFilteredSnapshots
    	/build/restic-XDCNVl/restic-0.9.3+ds/obj-x86_64-linux-gnu/src/github.com/restic/restic/cmd/restic/find.go:13 +0x126

Do you have any idea what may have caused this?
-----------------------------------------------

I suspect I might be trying to do something `restic ls` was not
supposed to do, which is to list files from all snapshots at once.

Do you have an idea how to solve the issue?
-------------------------------------------

No idea. This looks like #1803, but that was fixed back in may so it shouldn't still be occuring here.

Did restic help you or made you happy in any way?
-------------------------------------------------

Restic was incredibly fast at doing those tests. I wanted a comparison
with borg on stdin archival, and it beats it hands down, which makes
me happy and shows how things can be improved in borg, hopefully. ;)

You rock, and I hope the backtrace is useful!

**Comment by fd0** [comment]
Whoopsi, that shouldn't happen. Thanks for the report!

**Comment by fd0** [comment]
I'm able to reproduce it: The issue here is that the `ls` command does not support listing all snapshots any more. The bug is that it interprets the path as the ID for the snapshot to list, and since the path is longer than all snapshot IDs, the panic occurs here:

https://github.com/restic/restic/blob/2434ab210675cb9995b862032bdb42382bcbf1c6/internal/restic/backend_find.go#L27

Should be a trivial fix.

**Comment by anarcat** [comment]
i was wondering what was up with the argument parsing too... i found it difficult to convince restic to list paths across multiple archives, it would always interpret the path as an archive name and fail to find it. i'm not sure how i finally got it to treat it as a filename (or, in this case, just crash). :)

**Comment by treymo** [comment]
Hey, I can work on this bug

**Comment by fd0** [comment]
Oh, please do! We can use some help :)

**Comment by treymo** [comment]
I've got PR  #2243 ready, just need to figure out how to locally debug the build failure with the older Go version

**Comment by fd0** [comment]
Thank you very much! Don't bother with Go < 1.11, you would need to setup a `GOPATH` for it to find the source code. The rclone test you stumbled upon is flaky, I've restarted the test and will merge the PR later.
