### ISSUE TITLE
restic mount fails in macOS Mojave

### ISSUE THREAD

**Issue by roeebar** [restic/restic#2105]
Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.11.2 on darwin/amd64

How did you run restic exactly?
-------------------------------

    export RESTIC_REPOSITORY=b2:<my-repo>
    export B2_ACCOUNT_ID=<account-id>
    export B2_ACCOUNT_KEY=<account-key>
    export RESTIC_PASSWORD=<password>
    /usr/local/Cellar/restic/0.9.3_1/bin/restic mount ~/b2

Output:

    repository 12090b5b opened successfully, password is correct
    exit status 2
    unable to umount (maybe already umounted?): unmount /Users/user/b2: invalid argument

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
b2

Expected behavior
-----------------
Mount the provided repo on ~/b2

Actual behavior
---------------
Exit with error code 2

Steps to reproduce the behavior
-------------------------------
Try to mount a repo on macOS Mojave

Do you have any idea what may have caused this?
-----------------------------------------------
Full Disk Access requirement in Mojave? I have tried giving restic, bash and Terminal Full Disk Access permissions but that didn't help. I have also tried running this in 'sudo' which didn't work.

I have also tested this on restic 0.9.1 which has worked before, but it fails. That's why I believe something has changed in macOS rather than in restic.

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you or made you happy in any way?
-------------------------------------------------
restic is the best

**Comment by fd0** [comment]
Just to confirm: You did install/upgrade osxfuse, right? Do any other fuse-based file systems work? sshfs?

**Comment by roeebar** [comment]
Thanks! Totally forgot about that. I now updated FUSE by installing the latest version and it now works!(checking for updates within FUSE Settings reported there were no updates, which is wrong)

**Comment by fd0** [comment]
Thanks for the feedback
