### ISSUE TITLE
--limit-upload/download w. restic 0.9.3 and gcs backend doesn't work

### ISSUE THREAD

**Issue by fomichev** [restic/restic#2106]
Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.11.1 on linux/amd64

How did you run restic exactly?
-------------------------------
export GOOGLE_PROJECT_ID=xxx
export GOOGLE_APPLICATION_CREDENTIALS=xxx
sudo -E restic -r gs:xxx:/ --verbose --limit-upload 128 --exclude-file /home/sdf/src/dotfiles/.restic-exclude backup /

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Google Cloud Storage

Expected behavior
-----------------
Upload bandwidth should be limited.
Observed by running `ifpps enp2s0f0`.

Actual behavior
---------------
Upload bandwidth is not limited.
Observed by running `ifpps enp2s0f0`.

Steps to reproduce the behavior
-------------------------------
Just run restic backup with --limit-upload xxx

Do you have any idea what may have caused this?
-----------------------------------------------
Yes: https://github.com/restic/restic/commit/0dfdc11ed909f3ec8f8c0f0fdcbc342ed4602608
http.RoundTripper with the limiter is no longer passed to the http client.

Do you have an idea how to solve the issue?
-------------------------------------------
So far I'm wrapping "gs" backend in `be = limiter.LimitBackend(be, lim)` in cmd/restic/global.go:open [https://github.com/restic/restic/blob/2434ab210675cb9995b862032bdb42382bcbf1c6/cmd/restic/global.go#L591].
The proper way would be to pass RoundTripper to the GCS API.
I haven't looked deep enough, but should be possible with something like https://github.com/googleapis/google-api-go-client/commit/f71c6d4abd9757df4168c39856698c341d07251f

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic is awesome, keep up the good work!

**Comment by pvgoran** [comment]
Looks like a duplicate of #1989.

**Comment by fomichev** [comment]
Yes, it does indeed look like a duplicate. I have retested with fix-1989 branch and everything seems to be working. Waiting patiently for this to be merged :-) Thank you!
