### ISSUE TITLE
BTRFS subvolumes and one-file-system

### ISSUE THREAD

**Issue by Progman2k** [restic/restic#2109]
### I'm going to preface this by saying that I think the current behavior is arguably **correct**, it was just surprising.

Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.9.4 on linux/amd64

How did you run restic exactly?
-------------------------------
```
nice -n 10 "${SCRIPTHOME}/restic" ${SFTPOPT} -r "${REPOBASE}/${SET}" \ 
  --password-file="${SCRIPTHOME}/${SET}/password.txt" \ 
  backup **--one-file-system** \ 
  --exclude-file="${TMPEXCLUDE}" \ 
  --files-from="${SCRIPTHOME}/${SET}/include.txt" 2>&1 | tee "${LOG}"
```

The include.txt contents in this case are:
/boot/
/etc/
/root/
/var/
/files/

Those paths cover three filesystems, / (xfs), /boot (xfs), and /files (btrfs).

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
This backup set writes to a locally-mounted directory.

Expected behavior
-----------------
I expected to get the full contents of the /files mount, minus one directory that was listed in the exclusion file.

Actual behavior
---------------
In /files, only the directories that were **not** a subvolume were backed up.  

Steps to reproduce the behavior
-------------------------------
Create a btrfs filesystem, then within it create both normal subdirectories and subvolumes.
```
dd if=/dev/zero of=testdevice.dd bs=1M count=100  
mkfs.btrfs testdevice.dd  
mkdir test  
mount -o loop testdevice.dd test  
btrfs subvolume create test/subvol  
mkdir test/directory  
echo "Foo" > test/subvol/file1.txt  
echo "Bar" > test/directory/file2.txt
```
Once that is done run a backup against the mount point with "--one-file-system".  Restic will backup "test/directory/file2.txt", but not "test/subvol/file1.txt".

Do you have any idea what may have caused this?
-----------------------------------------------
A BTRFS subvolume has some characteristics that make it look like a different filesystem.  For instance, moves between subvolumes are not atomic.  All BTRFS volumes contain an automatically created subvolume called "top-level".
[https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-subvolume](https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-subvolume)

I suspect that restic's "--one-file-system" logic is aware of the distinctions and correctly (from its view) treats them as separate file systems.

Do you have an idea how to solve the issue?
-------------------------------------------
If the code is indeed correct, I suggest adding a caution statement to the documentation.  Perhaps something like this:

> Note that some file systems (such as BTRFS) support subvolumes, and these may be treated by restic as separate file systems.

One could argue that "--one-file-system" should not behave this way, but I think that starts to get into the particulars of individual expectations and goals.  Rather than adding complexity to the code base to handle these possibly conflicting goals, I think it is simplest to document the behavior and let people work around it as desired (specify each subvolume path, or just don't use that flag at all).

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic provides peace of mind on a budget.  :)

**Comment by cdhowie** [comment]
The flag name is indeed a bit misleading; it was inherited from tar, I believe.  In fact, you'd see the same behavior with tar.

Instead of "one file system," the actual behavior (of both restic and tar) is more like "don't cross into a different mount when recursing."

(Note that bind-mounts are a bit special; if the bind mountpoint is within the same filesystem as the bind source, restic (and tar) _will_ cross that mountpoint, since the "other side" is the same filesystem it came from.)

**Comment by fd0** [comment]
Interesting case, thanks for reporting it! Can you paste the output of `stat` on `file1.txt` and `file2.txt`? Internally, restic uses the `Device` field to distinguish different file systems. If it's different, then that's the reason for restic's behavior.

**Comment by Progman2k** [comment]
Indeed, 'stat' is showing them as different.

```
[root@Voyager btrfs_test]# stat test/subvol/file1.txt 
  File: ‘test/subvol/file1.txt’
  Size: 4               Blocks: 8          IO Block: 4096   regular file
Device: 45h/69d Inode: 257         Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:unlabeled_t:s0
Access: 2018-12-11 15:03:38.683938664 -0600
Modify: 2018-12-11 15:03:38.683938664 -0600
Change: 2018-12-11 15:03:38.683938664 -0600
 Birth: -
[root@Voyager btrfs_test]# stat test/directory/file2.txt 
  File: ‘test/directory/file2.txt’
  Size: 4               Blocks: 8          IO Block: 4096   regular file
Device: 44h/68d Inode: 258         Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:unlabeled_t:s0
Access: 2018-12-11 15:03:41.880962892 -0600
Modify: 2018-12-11 15:03:41.881962899 -0600
Change: 2018-12-11 15:03:41.881962899 -0600
 Birth: -
```
