### ISSUE TITLE
Storage Backend: Google Cloud Storage

### ISSUE THREAD

**Issue by e2b** [restic/restic#211]
Google's [Cloud Storage Nearline](https://cloud.google.com/storage-nearline/) has a pricing similar to Amazon Glacier, but with ~3 sec response times and free ingress (upload) traffic.

**Comment by kurin** [comment]
I'd like to add this feature.  I'll send a pull request in a few days.

**Comment by fd0** [comment]
Cool, please go ahead! :+1:

**Comment by fd0** [comment]
As just said in the PR #449: I'd like to move forward with adding GCS backend support natively. What is needed in order to access it? A client ID or a client secret?

**Comment by fd0** [comment]
According to @gebi, no such thing is needed, so that's good news.
