### ISSUE TITLE
Docker-Compose Configuration

### ISSUE THREAD

**Issue by QantumEntangled** [restic/restic#2110]
I have been using restic for a few months and today I've decided I want to make setting up restic on other computers as simple as possible in a secure and repeatable way. So I want to add a docker-compose configuration to the `docker/` directory to make it simple to setup backups in many environments.

I can also include updates to the `README.md` with instructions for using `docker-compose` to configure restic.

**Comment by fd0** [comment]
While this is a nice idea (and I appreciate your offer to contribute), it feels to me that we should instead move the docker configuration stuff out of the restic repository to somewhere else. It's a way to run restic, but it's not the only way, so there will be other users who want to run restic in some other way and over time we'll accumulate all kind of stuff in the restic repo which has to be maintained.

Would you like to start a separate repo somewhere else? :)

**Comment by toastie89** [comment]
I've prepared a docker compose file as well. Possibly we could group up? Mine's right here:
https://git.in-ulm.de/ulpeters/minio/src/master/restic

**Comment by MichaelEischer** [comment]
The docker-compose configuration seems to be highly specific to the target environment, so it's probably better suited for the recipes section of the forum.

**Comment by toastie89** [comment]
In 2020 it was very generic, but I recently added support for Prometheus what bloated it up. If you like I can make a PR with a generic variant?

**Comment by MichaelEischer** [comment]
Thanks, but I'd prefer to keep it in the recipes section of the forum.
