### ISSUE TITLE
restic fails with ciphertext verification failed

### ISSUE THREAD

**Issue by afunix** [restic/restic#2113]
Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.11.1 on linux/amd64

How did you run restic exactly?
-------------------------------
```
export RESTIC_PASSWORD="..."
export B2_ACCOUNT_ID="..."
export B2_ACCOUNT_KEY="..."
restic --repo "b2:scarlett--restic:restic" backup --verbose "/etc" "/root" <...>
open repository
lock repository
load index files
ciphertext verification failed, ignoring
...
ciphertext verification failed, ignoring
Error loading snapshot 3a4f06b0: ciphertext verification failed
github.com/restic/restic/internal/restic.FindLatestSnapshot.func1
        /restic/internal/restic/snapshot_find.go:39
github.com/restic/restic/internal/repository.(*Repository).List.func1
        /restic/internal/repository/repository.go:585
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1.1
        /restic/internal/backend/backend_retry.go:133
github.com/restic/restic/internal/backend/b2.(*b2Backend).List
        /restic/internal/backend/b2/b2.go:289
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1
        /restic/internal/backend/backend_retry.go:127
github.com/cenkalti/backoff.RetryNotify
        /restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        /restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).List
        /restic/internal/backend/backend_retry.go:126
github.com/restic/restic/internal/cache.(*Backend).List
        <autogenerated>:1
github.com/restic/restic/internal/repository.(*Repository).List
        /restic/internal/repository/repository.go:579
github.com/restic/restic/internal/restic.FindLatestSnapshot
        /restic/internal/restic/snapshot_find.go:36
main.findParentSnapshot
        /restic/cmd/restic/cmd_backup.go:353
main.runBackup
        /restic/cmd/restic/cmd_backup.go:437
main.glob..func2
        /restic/cmd/restic/cmd_backup.go:56
github.com/spf13/cobra.(*Command).execute
        /restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /restic/cmd/restic/main.go:86
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
```

```
restic --repo "b2:scarlett--restic:restic" --verbose check
using temporary cache in /tmp/restic-check-cache-070143816
repository eee0798b opened successfully, password is correct
created new cache in /tmp/restic-check-cache-070143816
create exclusive lock for repository
load indexes
error: error loading index 014a6a57: ciphertext verification failed
error: error loading index 003ab26b: ciphertext verification failed
...
error: error loading index ff03546a: ciphertext verification failed
error: error loading index fd8c26ac: ciphertext verification failed
Fatal: LoadIndex returned errors
```

```
restic --repo "b2:scarlett--restic:restic" --verbose snapshots
repository eee0798b opened successfully, password is correct
could not load snapshot 3a4f06b0: ciphertext verification failed
could not load snapshot 697ff09f: ciphertext verification failed
could not load snapshot 78e05e1d: ciphertext verification failed
could not load snapshot c306d943: ciphertext verification failed
could not load snapshot cd30883f: ciphertext verification failed
could not load snapshot cf96bbd4: ciphertext verification failed
ID  Time  Host        Tags        Paths
---------------------------------------
---------------------------------------
0 snapshots
```

```
restic --repo "b2:scarlett--restic:restic" --verbose key list
repository eee0798b opened successfully, password is correct
 ID        User  Host      Created
----------------------------------------------
*24afc56c  root  scarlett  2018-12-06 13:58:56
 9f7538c3  root  scarlett  2018-11-24 13:34:51
 afca6020  root  scarlett  2018-12-06 13:17:06
----------------------------------------------
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
B2

Expected behavior
-----------------
Successful backup, check, restore.

Actual behavior
---------------
Ciphertext verification failures.

Steps to reproduce the behavior
-------------------------------
Have no idea.
Just backed up 1.2 Tb of data (which was a pain for more than a week) which finished successfully.
However the second attempt to backup the same set of directories fails.

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No
Tried to clean cache, won't help.

Did restic help you or made you happy in any way?
-------------------------------------------------
It backs up lots of my servers with some hiccups here and there (mostly stale locks), but never rendered the whole backup set unusable so far.

**Comment by fd0** [comment]
Huh, that's very odd. It looks like as if something is interfering with the connection to B2. What's the setting in which you use restic? Do you maybe have a TLS interception device or security proxy in between you and B2?

Long shot question: Did you merge two separate repos?

What restic is telling you is that the signature on the data it got back from B2 does not verify. Can you download (using the web UI or e.g. rclone) a few of the files restic is complaining about and run `sha256sum` on them? Does the hash match the filename?

We had similar issues in the past, sometimes we could make out faulty hardware (mostly memory). But in this case it looks like as if almost any file does not verify any more...

**Comment by afunix** [comment]
I don't see any problems connecting to B2.
Browser access works. 
Other servers from the same physical location, but different repo backup fine.

That's the first time I see verification errors.

I didn't merge repos. I've created repo and started a backup around 20th of November and it took about 8 days to upload data.

Among others restic complained:
```
error: error loading index ff158f1c: ciphertext verification failed
error: error loading index ff03546a: ciphertext verification failed
error: error loading index fd8c26ac: ciphertext verification failed
```

These are SHA256 of files I believe correspond to these failures:
```
$ shasum -a256 restic*
fd8c26ac8f37eae0b8425762aceb7c41a0bb5431bf5e42c273d109fe2207a915  restic_index_fd8c26ac8f37eae0b8425762aceb7c41a0bb5431bf5e42c273d109fe2207a915
ff03546a5ac5b1f3f0350dc531dcc2f9e0d878bbdbe19fe6000087e7e4fa7ba7  restic_index_ff03546a5ac5b1f3f0350dc531dcc2f9e0d878bbdbe19fe6000087e7e4fa7ba7
ff158f1c314c453b407c36545f8cdc478e41167a9577e664e29378f0aa2e21c8  restic_index_ff158f1c314c453b407c36545f8cdc478e41167a9577e664e29378f0aa2e21c8
```
These hashes match.

**Comment by afunix** [comment]
Ok. I've spend another two weeks to upload the same 1.2 Tb directory by directory (in separate snapshots) to a new repo.
All the backups were successful.
Now my usual cron-based backup with all the directories included is successful too.
So I prefer to close this issue, since it doesn't look like I'll be able to reproduce or provide more details on what happened.

**Comment by fd0** [comment]
Thanks for the feedback, it's a bit of a bummer that we won't find out what went wrong though :)
