### ISSUE TITLE
backup: Show files skipped in JSON output

### ISSUE THREAD

**Issue by mholt** [restic/restic#2114]
Output of `restic version`
--------------------------

restic 0.9.3 (v0.9.2-192-g7cbcb6d3) compiled with go1.11 on darwin/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

(This is mostly a memo to self, since I'd be happy to work on the change for this.)

When files are skipped because of errors opening or reading them, report that in the JSON output -- either to stderr or stdout, whichever you think is more correct -- when the `--json` flag is used. 

What are you trying to do?
--------------------------

Make it easy for supervising programs and scripts to know which files are NOT being backed up, rather than the user having to read the lengthy logs.

Did restic help you or made you happy in any way?
-------------------------------------------------

Awwww yis 😎  I love restic, it's a great tool.

**Comment by mholt** [comment]
@fd0 Can you assign me to this issue? I'd be happy to look into this.

**Comment by MichaelEischer** [comment]
This has been implemented in #1937 which is included in restic 0.9.5.
