### ISSUE TITLE
--verbose 2 error: unknown command "2" for "restic"

### ISSUE THREAD

**Issue by bits01** [restic/restic#2116]
Output of `restic version`
--------------------------
`restic 0.9.3 compiled with go1.11.1 on linux/amd64`

How did you run restic exactly?
-------------------------------
`restic --verbose 2 -r <repo> backup <src>`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local fs

Expected behavior
-----------------
Should work, but instead it returns an error:
`unknown command "2" for "restic"`

Note that using `--verbose=2` works, so either a documentation/help issue or cmd line parsing bug.

**Comment by fd0** [comment]
Oh, interesting. Thanks for pointing it out!

**Comment by bits01** [comment]
I also ran into a problem with `--repo` not being recognized, I was going to file the bug but I can't reproduce it now and don't recall the exact combination of flags I had on the cmd line. Could have been my error because it seems to work now. Not sure whether it's an indication of more or the same issue with cmd line flag parsing.

**Comment by cdhowie** [comment]
Note that `--verbose=2` works.  I'm guessing that `--repo=...` also works.  So it sounds like the way restic currently uses its parameter-parsing library, the `=` is required when using the long form of a switch that takes a parameter.

**Comment by bits01** [comment]
`--repo` without `=` seems to work in some combinations, but I've seen it fail when used with more flags on the command line which I cannot reproduce now.

**Comment by danindiana** [comment]
Getting a similar error with 0.8.3 version: 

$restic -r /media/igor/8d3581ea-ed6e-4b98-90f4-10cdf705ec66/ryuchanAug2019/restic-repo --verbose  backup
Returns
unknown flag: --verbose
Probably b/c I forgot to add ~/ at the end of the string?

**Comment by fd0** [comment]
No, 0.8.3 did not have `--verbose` yet. :)

**Comment by danindiana** [comment]
@fd0 Oh OK. Well that explains that. I should have used a different version for Debian than the apt install pulled version. 

Lenovo-V330-14ARR
 OS: Ubuntu 18.04 bionic
 Kernel: x86_64 Linux 5.0.0-23-generic
 Uptime: 15h 24m
 Packages: 2638
 Shell: bash 4.4.20
 Resolution: 1920x1080
 DE: LXDE
 WM: OpenBox
 WM Theme: Onyx
 GTK Theme: Lubuntu-default [GTK2]
 Icon Theme: Lubuntu
 Font: Ubuntu 11
 CPU: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx @ 8x 2GHz [58.0°C]
 GPU: AMD/ATI Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]
 RAM: 4130MiB / 5920MiB

**Comment by jdrch** [comment]
Just an FYI to folks that you can experience a similar error if your `restic` command contains environment variables that aren't properly exported. I encountered that problem last night.

**Comment by MichaelEischer** [comment]
This has been fixed in #2874. See #2805 for further details.
