### ISSUE TITLE
Permissions of files lost/not updated between backups

### ISSUE THREAD

**Issue by albie** [restic/restic#2117]
Output of `restic version`
--------------------------
```
# restic version
restic 0.9.3 compiled with go1.11.1 on linux/amd64
```

How did you run restic exactly?
-------------------------------

```
# restic -r restic_repository/ init
created restic repository 05efc28aee at restic_repository/

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

# tree -p demo_data/
demo_data/
├── [drwxr-xr-x]  directory
│   ├── [-rw-r--r--]  file1
│   └── [-rw-r--r--]  file2
├── [-rw-r--r--]  file1
└── [-rw-r--r--]  file2

1 directory, 4 files

# restic -r restic_repository/ backup --host example demo_data
repository 05efc28a opened successfully, password is correct

Files:           4 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 357 B

processed 4 files, 0 B in 0:00
snapshot 3fc20cfd saved

# restic -r restic_repository/ ls 3fc20cfd -l
repository 05efc28a opened successfully, password is correct
snapshot 3fc20cfd of [/root/demo_data] filtered by [] at 2018-12-18 02:24:18.470788806 +0000 UTC):
drwxr-xr-x     0     0      0 2018-12-18 02:21:11 /demo_data
drwxr-xr-x     0     0      0 2018-12-18 02:21:05 /demo_data/directory
-rw-r--r--     0     0      0 2018-12-18 02:21:05 /demo_data/directory/file1
-rw-r--r--     0     0      0 2018-12-18 02:21:05 /demo_data/directory/file2
-rw-r--r--     0     0      0 2018-12-18 02:20:46 /demo_data/file1
-rw-r--r--     0     0      0 2018-12-18 02:20:46 /demo_data/file2

# chmod 755 demo_data/file1
# chmod 750 demo_data/directory

# tree -p demo_data/
demo_data/
├── [drwxr-x---]  directory
│   ├── [-rw-r--r--]  file1
│   └── [-rw-r--r--]  file2
├── [-rwxr-xr-x]  file1
└── [-rw-r--r--]  file2

1 directory, 4 files

# restic -r restic_repository/ backup --host example demo_data
repository 05efc28a opened successfully, password is correct

Files:           0 new,     0 changed,     4 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 357 B

processed 4 files, 0 B in 0:00
snapshot 4a780932 saved

# restic -r restic_repository/ ls -l 4a780932
repository 05efc28a opened successfully, password is correct
snapshot 4a780932 of [/root/demo_data] filtered by [] at 2018-12-18 02:26:09.640110167 +0000 UTC):
drwxr-xr-x     0     0      0 2018-12-18 02:21:11 /demo_data
drwxr-x---     0     0      0 2018-12-18 02:21:05 /demo_data/directory
-rw-r--r--     0     0      0 2018-12-18 02:21:05 /demo_data/directory/file1
-rw-r--r--     0     0      0 2018-12-18 02:21:05 /demo_data/directory/file2
-rw-r--r--     0     0      0 2018-12-18 02:20:46 /demo_data/file1
-rw-r--r--     0     0      0 2018-12-18 02:20:46 /demo_data/file2
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local or S3 the results are the same.

Expected behavior
-----------------
I would expect the permissions of the file to change in the restic repository, and mountpoint.

Actual behavior
---------------
The new file permissions don't stick, and retain the permissions of the previous snapshot.

Steps to reproduce the behavior
-------------------------------

Already described in how i used restic.

Did restic help you or made you happy in any way?
-------------------------------------------------

So far yes, restic has helped, or should i say will be helping.

**Comment by fd0** [comment]
That seems to be a bug, thanks for the report!

**Comment by fbarbeira** [comment]
I tried in different operating systems with restic 0.9.5 and has the same behaviour.

To preserve data integrity (owner and permissions) we have been forced to use "acl" utilities from linux and perform an additional full backup of file permissions, owner and groups:

https://linux.die.net/man/1/getfacl

It's a pity because those 'getfacl' does not perform very well, restic is faster but we cannot trust in permissions restored from a on restic repository.

**Comment by dimejo** [comment]
This should be covered by #2252 but AFAICT is not included in the latest release. Can you try again with a [beta release](https://beta.restic.net/?sort=time&order=desc)?

**Comment by fbarbeira** [comment]
I tried again with latest beta release and it works! :)

restic_v0.9.5-33-g1e9eefa0_linux_amd64

**Comment by MichaelEischer** [comment]
Can this be closed now that restic 0.9.6 has been released?

**Comment by fbarbeira** [comment]
I think so because it's working with the last upstream version (0.9.6).

**Comment by rawtaz** [comment]
Thanks for the maintenance effort guys!
