### ISSUE TITLE
corruption (missing blobs) with a b2 target

### ISSUE THREAD

**Issue by doudou** [restic/restic#2121]
Output of `restic version`
--------------------------

~~~
restic 0.9.2 compiled with go1.10.3 on linux/amd64
~~~

and

~~~
restic 0.9.3 compiled with go1.11.1 on linux/amd64
~~~~

How did you run restic exactly?
-------------------------------
The 0.9.2 version is used to periodically (twice a day) snapshot and upload a backup folder to B2, as well as run forget (forget is systematically executed after each backup). Both calls are done in the idle IO class.

~~~
export B2_ACCOUNT_ID=$ID B2_ACCOUNT_KEY=$KEY
ionice -c 3 /opt/restic --cleanup-cache -r b2:$TARGET_B2_BUCKET_AND_PATH backup $BACKUP_DIRECTORY --limit-download 1000 --limit-upload 1000
ionice -c 3 /opt/restic --cleanup-cache -r b2:$TARGET_B2_BUCKET_AND_PATH forget  --keep-hourly 48 --keep-daily 30 --keep-weekly 8 --keep-monthly 12 --keep-yearly 20 --prune --limit-download 1000 --limit-upload 1000
~~~

Typical backup output:

~~~
Dez 18 15:04:33 octopus restic-service[23464]: 2018-12-18 15:04:33 -0200 - Synchronizing sylvain.joyeux
Dez 18 15:04:33 octopus restic-service[23464]: ionice: ignoring given class data for idle class
Dez 18 15:07:36 octopus restic-service[23464]: Files:           0 new,     0 changed, 752328 unmodified
Dez 18 15:07:36 octopus restic-service[23464]: Dirs:            0 new,     0 changed,     2 unmodified
Dez 18 15:07:36 octopus restic-service[23464]: Added to the repo: 0 B
Dez 18 15:07:36 octopus restic-service[23464]: processed 752328 files, 95.728 GiB in 3:02
Dez 18 15:07:36 octopus restic-service[23464]: snapshot bb3dea66 saved
~~~

Typical forget output is just a long list of snapshots.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------

That `check` does not start failing without foreseeable reason ...

Actual behavior
---------------

It's been the third time that 'check' detects objects that are not present. I've seen reports about this, that were fixed by a `rebuild-index`, but that did not work for me (I used 0.9.3 to run rebuild-index). The first two times this happened, I've deleted older snapshots until the objects in question were not needed. I'd like to have another way to handle the problem this time ...

Bizarrely, even though `forget --prune` passes without issues, `check` complains about packs that are not present in any indexes, and that `prune` should fix the issue. Isn't `forget --prune` the same than `forget` followed by `prune` ?

An example error I get under `check` is:

~~~
error for tree 46a947c5:
  tree 46a947c5: file "next" blob 0 size could not be found
  tree 46a947c5: file "rock1408" blob 0 size could not be found
  tree 46a947c5: file "stable" blob 0 size could not be found
  tree 46a947c5: file "toolchain-2.2" blob 0 size could not be found
  tree 46a947c5: file "toolchain-2.5" blob 0 size could not be found
  tree 46a947c5: file "toolchain-2.7" blob 0 size could not be found
  tree 46a947c5: file "toolchain-2.8-rock-15.05" blob 0 size could not be found
  tree 46a947c5: file "toolchain-2.9" blob 0 size could not be found
  tree 46a947c5, blob b298576f: not found in index
  tree 46a947c5, blob 4a963c00: not found in index
  tree 46a947c5, blob 1d757e05: not found in index
  tree 46a947c5, blob f139b0af: not found in index
  tree 46a947c5, blob 37581be1: not found in index
  tree 46a947c5, blob c9da0f53: not found in index
  tree 46a947c5, blob d581ab8a: not found in index
  tree 46a947c5, blob 721fcf19: not found in index
~~~

Steps to reproduce the behavior
-------------------------------

I don't know of a method to reliably reproduce it.

Do you have any idea what may have caused this?
-----------------------------------------------

No idea.

Do you have an idea how to solve the issue?
-------------------------------------------

Nope ... :(

The best would IMO to have a `repair` call which would try to replace the missing blobs with data present on disk.

Did restic help you or made you happy in any way?
-------------------------------------------------

I think restic is a great idea, and I really liked the overall idea and design. I wouldn't be taking time reporting this otherwise ;-)

**Comment by fd0** [comment]
Very odd, thanks for the report! How many snapshots do you have in the repo?

**Comment by doudou** [comment]
Currently 91 snapshots.

**Comment by bachp** [comment]
Could this be the same as https://github.com/restic/restic/issues/2045?

**Comment by MichaelEischer** [comment]
@doudou `forget --prune` only runs prune if some snapshots were removed. The repair command you've asked for already exists: Just run `restic backup --force ...` then restic will read all files from the backup set again and reuploaded missing blobs. This usually has to be preceded by `rebuild-index` to make sure that the repository index correctly reflects which packs and blobs exist in the backup repository.

**Comment by MichaelEischer** [comment]
`backup` in restic 0.10.0 will now automatically recover any missing blobs it comes across. Running `rebuild-index` beforehand is still required to ensure that restic knows exactly which blobs exist and which don't. In addition `prune` now includes several stricter sanity checks to ensure that prune can't accidentally damage a repository.

@doudou Is there anything actionable left in this issue?

**Comment by dimejo** [comment]
> @doudou Is there anything actionable left in this issue?

Maybe add a note about running `rebuild-index` to the FAQ?

**Comment by MichaelEischer** [comment]
Adding documentation for recovering damaged repositories is tracked in #2683.

**Comment by MichaelEischer** [comment]
Closing this as there's currently nothing to investigate here. Please open a new issue is the problem shows up again with a recent restic version.
