### ISSUE TITLE
[Feature request] Show upload speed in archiver

### ISSUE THREAD

**Issue by pzmarzly** [restic/restic#2131]
`restic backup` doesn't display current upload speed, just ETA and %done. Would be nice to know if the bottleneck is my PC's fault or my cloud storage provider's one.

Relevant: https://github.com/restic/restic/pull/1595

**Comment by mholt** [comment]
How can you tell from a single transfer if a slow upload is the result of your own computer (do you mean your own network?) or the cloud provider?

**Comment by pzmarzly** [comment]
I don't want restic to detect what the bottleneck is, just to give the upload speed in Mbps, which I later can compare to speedtest.net results. Sorry for causing confusion.

Of course right now it's possible to use e.g. [nethogs](https://github.com/raboof/nethogs) to monitor restic  network I/P, but I would prefer a built-in feature.

**Comment by MichaelEischer** [comment]
Closing this as duplicate of #1581.
