### ISSUE TITLE
Unexpected Repository Corruption

### ISSUE THREAD

**Issue by stubevan** [restic/restic#2132]
Output of `restic version`
--------------------------
restic 0.9.3 compiled with go1.11.2 on darwin/amd64

Installed via homebrew

How did you run restic exactly?
-------------------------------
From the command line.  Backups are triggered from rundeck

    restic -r  /Volumes/Drobo5n/*****/1/Backups/restic/mac-backups rebuild-index --password-file ~/*****
    restic -r  /Volumes/Drobo5n/*****/1/Backups/restic/mac-backups prune --password-file ~/****

Had the same problem when accessing the repository through sftp.

    stu.mrbadger.~> restic -r  /Volumes/Drobo5n/*****/1/Backups/restic/mac-backups rebuild-index --password-file ~/.*****
    repository 957966c2 opened successfully, password is correct
    counting files in repo
    [2:57:59] 100.00%  270874 / 270874 packs
    finding old index files
    saved new indexes as [586137df a7434b64 d9288258 8e23bf80 bbf5e818 b041a9aa b58255ca 0e045d85 a3587fbf 67a253d3 dcf6aee4 3d5d2882 58d34ac2 e0213e07 d559d62f f4f12ec6 c44df692 ca63fb9e ed4111a7 84cfa994 1821875a aa9e89b2 8963993b 357c0644 e8ae4d0f 3a69ddee 0e144e0b 6bbdf5e2 6650618f 56e32ef6 ab44ea67 5276fda2 19eba4e1 2bffaada 9e24686e 34851533 bba65855 54f0bafe 9f20b52a f3c0a9f5 6d175e16 9bec0862 38ca098c b670328d 1dfe2fb5 3a14de38 7ce8ac4c af4aee22 6fed2702 a7d208fd 6d87e8e6 e3c997d9 ce667b20 f71875cd 8453fa19 d5430ea9 c89c5639 b94ddd9e b021d9af d1f768bc 6a8db897 46123965 ab833432 2402fe5c afde773d cb44e3e2 aea1b16b f3fda449 24fa8d69 6ded0ba7 c151afc1 39da796f 97fd9eeb f5a13b8f 6e9831d8 67f8a888 83a54431 77045b2a c2f9857f 87a5ec13 3795f6f8 7f03e22b f804c406 21bbcaa6 c0a3f443 00e5b9c3 657ece4c cfaf889b b2d678cf bd9513b1 059a9041]
    remove 91 old index files
    
    stu.mrbadger.~> restic -r  /Volumes/Drobo5n/*****/1/Backups/restic/mac-backups prune --password-file ~/****
    
    repository 957966c2 opened successfully, password is correct
    counting files in repo
    building new index for repo
    [2:14:44] 100.00%  270874 / 270874 packs
    incomplete pack file (will be removed): 18b45fca6e67adf45f7680e25589a887dfe1fbedcfb88e3ca55fab8d40938a88
    incomplete pack file (will be removed): 421b6dd7aeec7958af91b6d6609dbd5231dafd04b927b9ca07a568a316a5111e
    incomplete pack file (will be removed): b31a5915aaff1a7fc9572fc7f6b098c8678dc784bfe6f473916522fa817ae817
    incomplete pack file (will be removed): d748e5f5e2e135f507ade5d020da662f1b24e1cd56bf084b29eb402a1aeaec16
    incomplete pack file (will be removed): eb148cd28c7e31e82b4eac79830592a9880c0a99adf20c9c9736b6040fcb78b0
    incomplete pack file (will be removed): fda02880a719ba027c4e4b4c58f5517e0abc93026795168d508ec5626b3a1ba9
    repository contains 270868 packs (5650082 blobs) with 1.242 TiB
    processed 5650082 blobs: 115882 duplicate blobs, 110.538 GiB duplicate
    load all snapshots
    find data that is still in use for 150 snapshots
    tree 44f9c10f916d33a679f04f19c85a04344dfb653fea09627d7972670271876c02 not found in repository
    github.com/restic/restic/internal/repository.(*Repository).LoadTree
    	internal/repository/repository.go:654
    github.com/restic/restic/internal/restic.FindUsedBlobs
    	internal/restic/find.go:11
    github.com/restic/restic/internal/restic.FindUsedBlobs
    	internal/restic/find.go:31
    github.com/restic/restic/internal/restic.FindUsedBlobs
    	internal/restic/find.go:31
    github.com/restic/restic/internal/restic.FindUsedBlobs
    	internal/restic/find.go:31
    github.com/restic/restic/internal/restic.FindUsedBlobs
    	internal/restic/find.go:31
    main.pruneRepository
    	cmd/restic/cmd_prune.go:191
    main.runPrune
    	cmd/restic/cmd_prune.go:85
    main.glob..func18
    	cmd/restic/cmd_prune.go:25
    github.com/spf13/cobra.(*Command).execute
    	vendor/github.com/spf13/cobra/command.go:762
    github.com/spf13/cobra.(*Command).ExecuteC
    	vendor/github.com/spf13/cobra/command.go:852
    github.com/spf13/cobra.(*Command).Execute
    	vendor/github.com/spf13/cobra/command.go:800
    main.main
    	cmd/restic/main.go:86
    runtime.main
    	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/proc.go:201
    runtime.goexit
    	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:1333

-->

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
NAS (Drobo5n).  Initially accessed through sftp.  Had the same issue when mounting via smb

Expected behavior
-----------------
I 'forgot' multiple snapshots - both manually and through a policy.  Prune should then have recovered the released disk space

Actual behavior
---------------
Looks like the repository has become corrupted.  I had previously successfully run a prune

Steps to reproduce the behavior
-------------------------------
get the same behavior every time I prune

Do you have any idea what may have caused this?
-----------------------------------------------
No - although I'm wondering is a backup had got terminated prematurely

Do you have an idea how to solve the issue?
-------------------------------------------
I suspect I'll have to create a new repoitory

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic always makes me happy :)  This is the first time ive seen this

**Comment by fd0** [comment]
Hm, interesting, thanks for the report! What happens here is that during `prune`, restic detected that the tree object `44f9c10f916d33a679f04f19c85a04344dfb653fea09627d7972670271876c02` (containing metadata like file names and so on) could not be found in the repo.

Let's try to find out what's going on. Can you please try the following and paste the output (if any):
 * `restic list blobs | grep 44f9c10f916d33a679f04f19c85a04344dfb653fea09627d7972670271876c02`
 * `restic find --tree 44f9c10f916d33a679f04f19c85a04344dfb653fea09627d7972670271876c02`

In addition, please run `restic check --read-data`.

**Comment by stubevan** [comment]
Morning

Output of first command was empty.  The second is below.  I'm running the check now but reckon it will take some time as the repository is pretty big.

Cheers and thanks for th swift response

Stu

repository 957966c2 opened successfully, password is correct
tree 44f9c10f916d33a679f04f19c85a04344dfb653fea09627d7972670271876c02 not found in repository
github.com/restic/restic/internal/repository.(*Repository).LoadTree
	internal/repository/repository.go:654
github.com/restic/restic/internal/walker.walk
	internal/walker/walker.go:107
github.com/restic/restic/internal/walker.walk
	internal/walker/walker.go:127
github.com/restic/restic/internal/walker.walk
	internal/walker/walker.go:127
github.com/restic/restic/internal/walker.walk
	internal/walker/walker.go:127
github.com/restic/restic/internal/walker.Walk
	internal/walker/walker.go:56
main.(*Finder).findIDs
	cmd/restic/cmd_find.go:341
main.runFind
	cmd/restic/cmd_find.go:549
main.glob..func9
	cmd/restic/cmd_find.go:33
github.com/spf13/cobra.(*Command).execute
	vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
	vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
	vendor/github.com/spf13/cobra/command.go:800
main.main
	cmd/restic/main.go:86
runtime.main
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/proc.go:201
runtime.goexit
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:1333

**Comment by stubevan** [comment]
Hi,

Ive appended the out of the check command!  
[restic.txt](https://github.com/restic/restic/files/2730294/restic.txt)

Thanks

Stu

**Comment by stubevan** [comment]
Hi,  Thats strange .... Are we looking at the same file?  I don't see the comments you mention above?

Check was run with: `restic -r /Volumes/****/Backups/restic/mac-backups check --read-data --password-file /***`

Many Thanks


I have the following at the top of the file ...

`using temporary cache in /var/folders/pm/l1_k1v0d09lcbfs3jtd4jk7r0001yj/T/restic-check-cache-201047900
repository 957966c2 opened successfully, password is correct
created new cache in /var/folders/pm/l1_k1v0d09lcbfs3jtd4jk7r0001yj/T/restic-check-cache-201047900
create exclusive lock for repository
load indexes
check all packs
pack b37e30d3: not referenced in any index
pack aabcffd7: not referenced in any index
pack 97c3b19c: not referenced in any index
pack 23a5deeb: not referenced in any index
pack e01291a2: not referenced in any index
pack 4b0b904c: not referenced in any index
pack 957dd0b1: not referenced in any index
pack 475f5b20: not referenced in any index
pack cdf99526: not referenced in any index
pack 62d6a3cf: not referenced in any index`

**Comment by fd0** [comment]
Oh wow, I'm sorry, I was indeed looking at the wrong file. Please disregard my comment.

It lists almost 2000 files as not referenced in any index. But the previous run of `restic prune` only reported six files as being invalid, and `restic rebuild-index` did not report any errors reading the files.

So, it looks like there's data (almost 2k files with data) in the repo but restic doesn't know about it. Usually, that's exactly what `rebuild-index` should take care of. Can you please re-run it, then run `restic list blobs | grep 44f9c10f916d33a679f04f19c85a04344dfb653fea09627d7972670271876c02` again?

Please log or copy the output of both commands, maybe we can then see something.

Long-shot question: Do you maybe have several repos, and ran `rebuild-index` on a different one?

**Comment by stubevan** [comment]
HI Alexander,

Thanks for all the work on this ... Output below.  In answer to your question ... There is only one rep

Cheers

Stu

'stu.mrbadger.~> restic -r  /Volumes/Drobo5n/****/Backups/restic/mac-backups rebuild-index --password-file ~/****
repository 957966c2 opened successfully, password is correct
counting files in repo
[2:55:06] 100.00%  280298 / 280298 packs
finding old index files
saved new indexes as [97c99dff 0d008e3e 6171bbd1 625c12e1 dc9aa107 f91091b7 5747082f 96fc22d7 064239cd 87598c31 a82dd9b4 44643c76 22160f07 e1f3707c ce03ffd4 174bd4df ab378bf1 616782fd 5f389acb aaece37d d8299414 bb9db0ea 0dc8e33c 055b803c 043be110 53762d3e 76d8918b 7d1cbefa 1abbf1fd 1d7ae950 2a99846d b6cc5dab e0bd74aa 646dc842 24cb9dfa da0a7b64 2aef66e6 fa776890 ea47812b a40065c9 d980367e e665ec38 5710aa35 b2f6c9ea 426e03bf 26951cf2 fca95ad5 5e249322 5a4663a0 0591813d 19157f24 fd5610d3 ec5a4338 f84e729a 7b9ac015 220d3ddf ee6db1e3 b5c58aaa a1b031b2 a4bb1243 c86a7652 399b9862 f9a82d5c fbd3cd6d 3cd3a44f 09799ba2 d226eb37 86190851 5988975b 48346089 fa0d9a0f f538cdd1 3e1249f0 77679e40 132607ed 5a2e6ae2 d64f15b3 5636a755 8a2c0ff3 efdf90c0 7dd9d5af 8c7fc678 b053f136 ed581da7 cf4cacf0 8fab85c3 462a4e51 32664b4a 6ccf8baf c4ecef30 80d542df c63eabdc 7dd3471a 447729f5]
remove 117 old index files
stu.mrbadger.~> restic  -r  /Volumes/Drobo5n/drb133601a00498/1/Backups/restic/mac-backups list blobs --password-file ~/.restic/drobo5n.password | grep 44f9c10f916d33a679f04f19c85a04344dfb653fea09627d7972670271876c02'

**Comment by stubevan** [comment]
I’m putting this down to the use of an unjournalled file system.  It hasn’t happened again

**Comment by fd0** [comment]
Thanks for the feedback anyway :)
