### ISSUE TITLE
restic 0.9.4 `-q` outputs `open repository`

### ISSUE THREAD

**Issue by axllent** [restic/restic#2140]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on linux/amd64

How did you run restic exactly?
-------------------------------
`restic -r /<repo> backup /<dir> -q`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local

Expected behavior
-----------------
No output unless an error is encountered.

Actual behavior
---------------
Outputs `open repository`

Do you have any idea what may have caused this?
-----------------------------------------------
Upgrade from 0.9.3 to 0.9.4

**Comment by fd0** [comment]
Huh, interesting. Are you sure this does not also happen on 0.9.3? FYI: This line won't be printed if stdout is not a terminal (e.g. for cron).

**Comment by axllent** [comment]
I didn't have this issue before on 0.9.3, and yes, this happens when using cron (system backups etc) ;-)

**Comment by fd0** [comment]
Oh, hm. That's annoying. I'll look into it. :)

**Comment by kusalananda** [comment]
I don't know if it makes any difference, but I'm seeing this exact thing on macOS (latest) too using `restic` ("`restic 0.9.4 compiled with go1.11.4 on darwin/amd64`") installed from Homebrew from cron.
