### ISSUE TITLE
Please add an environment variable for the cache directory

### ISSUE THREAD

**Issue by joshtriplett** [restic/restic#2143]
Output of `restic version`
--------------------------

restic 0.9.4 compiled with go1.11.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Please add an environment variable `RESTIC_CACHE_DIR` to set the cache directory. (Passing `--cache-dir` should override that, but a command run without `--cache-dir` should use `$RESTIC_CACHE_DIR`.)

What are you trying to do?
--------------------------

Run a series of commands that all use the same cache directory, without having to specify it for each command.

Did restic help you or made you happy in any way?
-------------------------------------------------

I switched from duplicity to restic, and I love the fast, always-incremental backups. Thank you!

**Comment by ProactiveServices** [comment]
I've had restic bomb out from exhausting /tmp on little NASes before, as I had forgotten to use the --cache-dir command when running it manually. This would be great!

**Comment by fd0** [comment]
There's two things at play here:
 * restic uses the temp directory specified via the `TMPDIR` environment variable, or `/tmp` if it isn't set
 * For the cache directory, restic follows the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), which states that you can set the cache directory via `XDG_CACHE_HOME`.

I wonder if we should add these standard variables to the manual, e.g. here: https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables

Does this answer your question?

**Comment by joshtriplett** [comment]
@fd0 Ah, `$XDG_CACHE_HOME` would indeed work for my use case, if it were documented. That does slightly differ from `--cache-dir`, in that the latter directly sets the directory rather than setting the parent directory. But that'll work fine.

**Comment by fd0** [comment]
Ok, then let's treat this as a documentation issue :)

**Comment by ProactiveServices** [comment]
It seems that for `restic check`, `--with-cache` is also required before restic will use `$XDG_CACHE_HOME`. `--with-cache` isn't mentioned anywhere in the docs. This will somewhat frustrate me when using manual `check`s as it'll take a while for me to remember to use it, and each time I forget, the check will run for some time, then bomb out. This might be an argument for having a `check`-only cache environment variable, which will help folk with small `/tmp` directories.

Ugh, bikeshedding :-)

**Comment by fd0** [comment]
Well, it's not that easy: the cache should speed up all operations by caching metadata. But when `restic check` is used, we cannot depend on the cache, we must load and verify the data from the repo.

The first idea we had was to just disable the cache for check, so data is always loaded directly from the repo, but that makes the whole operation really slow. So we implemented a compromise: we use a cache, but not the existing one on disc (which we do not fully trust). Instead, a new cache is created i a temporary directory, which over the runtime of `restic check` fills with data freshly loaded from the repo. If you still want to use the existing cache, that's what `--with-cache` is for.

So, for normal operation, `$XDG_CACHE_HOME` is used, and a temporary dictory in `$TMPDIR` for `restic check`. If you just want the temp files for the `check` operation to reside somewhere else, just set `$TMPDIR` and you're fine. :)
