### ISSUE TITLE
restic --quiet is not quiet anymore

### ISSUE THREAD

**Issue by sebasgo** [restic/restic#2145]
Output of `restic version`
--------------------------

`restic 0.9.4 compiled with go1.11.4 on linux/amd64`

How did you run restic exactly?
-------------------------------
 I run

    restic --quiet backup /home/$user/ --exclude /home/$user/.cache 

with the `RESTIC_PASSWORD_FILE`, `RESTIC_REPOSITORY`, and `user` set.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

sftp

Expected behavior
-----------------

Unless there is an error, restic produces no output on stdout / stderr.

Actual behavior
---------------

Starting with version **0.9.4**, restic prints

    open repository
    
when doing a backup.

This is inconvinient for me, because now I get a mail from cron for each backup and not only for failed backups.

Version 0.9.3 and earlier was not affected by the issue. Also, ``restic --quiet forget`` is still quiet in verions 0.9.4. I have not tested any other command, though.

Steps to reproduce the behavior
-------------------------------

1. Setup restic with the sftp backend.
2. Run restic with `--quiet`

Do you have any idea what may have caused this?
-----------------------------------------------

Nope.

Do you have an idea how to solve the issue?
-------------------------------------------

Nope.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yep, it's great piece of software.

**Comment by fd0** [comment]
Thanks for the report, this was reported in #2140 and is already resolved in master. You can either compile restic yourself, or download a beta build from here: https://beta.restic.net/restic-v0.9.4-3-g1107eef2/
