### ISSUE TITLE
Accept dates with T as per ISO-8601 for --time CLI option

### ISSUE THREAD

**Issue by rich123** [restic/restic#2149]
Output of `restic version`
--------------------------
0.9.4

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
The --time CLI parameter will scan timestamps of the form "YYYY-MM-DD HH:MM:SS" but will not scan timestamps of the form "YYYY-MM-DDTHH:MM:SS".

Preferably both forms (with space and with T) would be acceptable to --time.

What are you trying to do?
--------------------------

Use an ISO-8601 timestamp with a "T" separator (which avoids needing to add quotes for the shell).

Did restic help you or made you happy in any way?
-------------------------------------------------

So far, very happy, and lack of parsing timestamps with a "T" separator is not a big deal, but should also make for an easy enhancement as well.

**Comment by fd0** [comment]
Thanks for the report! We already have an issue dealing with inconstistently formatted date/times, so I'm closing this as a duplicate (and note that we should maybe accept the time formats restic prints automatically), please subscribe over at #1306. Thanks!
