### ISSUE TITLE
Swift: add Openstack application credential support

### ISSUE THREAD

**Issue by kayrus** [restic/restic#2155]
Output of `restic version`
--------------------------

```
restic 0.9.4
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Backups are usually made by a service/background/cron job. If you don't have a possibility to create an additional user and you don't want to put your secrets on the shared server, which runs restic backups, you'd probably gonna use Openstack Application Credential auth method: https://docs.openstack.org/keystone/queens/user/application_credentials.html

Application Credential can have limited permissions and an owner can always revoke these credentials or set an expiry date.

**Comment by fd0** [comment]
Ah, I forgot closing this issue, thanks for taking care of it!
