### ISSUE TITLE
Unable to create restic repo on exfat file system

### ISSUE THREAD

**Issue by jrkoiter** [restic/restic#2157]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on linux/amd64

How did you run restic exactly?
-------------------------------
restic init --repo /media/usb2disk/restic-backups
Fatal: create key in repository at /media/usb2disk/restic-backups failed: chmod /media/usb2disk/restic-backups/keys/xxxxxxx129a57e88671f14799366326da40305693822a32de797a2591078e984: operation not permitted

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local file on exfat filesystem:
lsblk -f | grep usb2disk
└─sdb1                exfat             6A4F-0A7F                              /media/usb2disk

Expected behavior
-----------------
Repository to be created without issues.

Actual behavior
---------------
Repository partially created, but not usable.

Steps to reproduce the behavior
-------------------------------
Create repo on exfat filesystem.

Do you have any idea what may have caused this?
-----------------------------------------------
exfat filesystem, I suspect, as it doesn't support chmod.

Do you have an idea how to solve the issue?
-------------------------------------------
No.

Did restic help you or made you happy in any way?
-------------------------------------------------
Using restic already with local repo (on ext4), and also backblaze b2. It's great!

**Comment by fd0** [comment]
Thanks for the report! I consider this a bug, it should try to run `chmod`, but if it fails it should not abort. Maybe (if we can find a good way) it could print the error.

**Comment by gyorb** [comment]
Hi,

With the latest release it seems to work now.
I do not get the error when I try to initialize a repo on exfat file system.
````
restic version
restic 0.9.6 compiled with go1.13.4 on linux/amd64
````
