### ISSUE TITLE
Prune fails with unable to open TempFile

### ISSUE THREAD

**Issue by SamirBanjanovic** [restic/restic#2160]
Output of `restic version`
--------------------------
`restic 0.9.4 compiled with go1.11.4 on windows/amd64`

How did you run restic exactly?
-------------------------------
Ran `restic check` then `restic prune`  and received `The system cannot find the path specified.
TempFile`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Running on `Windows Server 2019 Datacenter` with connection set up to `B2 Backblaze`

Expected behavior
-----------------
Successful completion of `prune`

Actual behavior
---------------
Received error that `prune` failed due to missing `TempFile`, complete error is:

```
repository 12799516 opened successfully, password is correct
counting files in repo
building new index for repo
[10:59:33] 100.00%  220282 / 220282 packs
repository contains 220282 packs (888245 blobs) with 1.051 TiB
processed 888245 blobs: 1749 duplicate blobs, 1.367 GiB duplicate
load all snapshots
find data that is still in use for 3 snapshots
[0:20] 100.00%  3 / 3 snapshots
found 886496 of 888245 data blobs still in use, removing 1749 blobs
will remove 0 invalid files
will delete 0 packs and rewrite 473 packs, this frees 1.367 GiB
open C:\Users\samir\AppData\Local\Temp\2\restic-temp-685705799: The system cannot find the path specified.
TempFile
github.com/restic/restic/internal/repository.DownloadAndHash
        /restic/internal/repository/repository.go:707
github.com/restic/restic/internal/repository.Repack
        /restic/internal/repository/repack.go:26
main.pruneRepository
        /restic/cmd/restic/cmd_prune.go:278
main.runPrune
        /restic/cmd/restic/cmd_prune.go:85
main.glob..func17
        /restic/cmd/restic/cmd_prune.go:25
github.com/spf13/cobra.(*Command).execute
        /restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /restic/cmd/restic/main.go:86
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
Repack
github.com/restic/restic/internal/repository.Repack
        /restic/internal/repository/repack.go:28
main.pruneRepository
        /restic/cmd/restic/cmd_prune.go:278
main.runPrune
        /restic/cmd/restic/cmd_prune.go:85
main.glob..func17
        /restic/cmd/restic/cmd_prune.go:25
github.com/spf13/cobra.(*Command).execute
        /restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /restic/cmd/restic/main.go:86
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
```

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------
My best guess is that Windows is doing a temp file deletion. I've ran `prune` with the same result, I am currently running another test to see if remove temp file deletion fixes the problem.

Do you have an idea how to solve the issue?
-------------------------------------------
See above.

Did restic help you or made you happy in any way?
-------------------------------------------------
Makes me very happy to have a solid backup application that I can run from my home server.
It would be very helpful if documentation had a  list (and steps) of standard commands to execute when running a daily backup. I currently run `restic backup` every night, then `restic check` and `restic prune` weekly. Is there anything else I should do? Such as `forget` or something else?

Update (2/4/2019)
-------------------------------------------------
I did another test with temp file deletion completely off and received the same error.

**Comment by fd0** [comment]
Huh, that's odd. Does the directory `C:\Users\samir\AppData\Local\Temp\2\` exist? Can you write to it?

restic received an error returned from the function `TempFile` from the [Go standard library](https://godoc.org/io/ioutil#TempFile) that a temporary file in the directory configured as the standard directory for temporary files could not be created. That directory seems to be `C:\Users\samir\AppData\Local\Temp\2\`, it must exist and be writeable for the current user.

If you need to set the temporary directory a different location, use the environment variable `TMPDIR`.

Does that work for you?

**Comment by SamirBanjanovic** [comment]
When I checked the directory it didn't exist. Which is why I initially thought Windows auto deleted the dir. Tried disabling auto del temp dirs, which didn't help. I ran it sometime later and it seemed to work

**Comment by fd0** [comment]
Ok, so the directory exists now and the error does not occur any more?

**Comment by SamirBanjanovic** [comment]
The `appdata/locsl/temp` for exists. But not `2`

**Comment by fd0** [comment]
I'm closing this issue for now, please feel free to add further comments. Thanks!

**Comment by lucgirardin** [comment]
On Ubuntu, running prune with a non-root user also results in a similar error: restic 0.9.6 tries to create a temporary file in /run instead of /tmp:
open /run/restic-temp-698985503: permission denied
TempFile
github.com/restic/restic/internal/repository.DownloadAndHash
	/restic/internal/repository/repository.go:767
github.com/restic/restic/internal/repository.Repack
	/restic/internal/repository/repack.go:26
main.pruneRepository
	/restic/cmd/restic/cmd_prune.go:278
