### ISSUE TITLE
Feature request: .backupignore (like .gitignore)

### ISSUE THREAD

**Issue by micw** [restic/restic#2161]
Output of `restic version`
--------------------------

0.9.3

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Currently it's possible to exclude files given by command line (exclude, exclude-file) or exclude whole directories by markers (exclude-if-present). But it's not possible to exclude a file by marker.

It would be great if there's something like "--exclude-file-name" which can be set to a filename which it (if pressent) be used as exclude-file for the directory where the file is in. This would work like .gitignore or .dockerignore files.

What are you trying to do?
--------------------------

See above.

Did restic help you or made you happy in any way?
-------------------------------------------------

It does both, it helps me and it makes me happy ;-)

**Comment by fd0** [comment]
Nice idea, thanks for the report. We already have an issue adding such a feature, so I'm closing this as a duplicate. Please subscribe over at #1514 to be notified of any (eventual) progress implementing it. Thanks!
