### ISSUE TITLE
restic backup crashes with s3 - requested hostname contains part of file path

### ISSUE THREAD

**Issue by cryptoluks** [restic/restic#2163]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on linux/amd64

How did you run restic exactly?
-------------------------------
Env vars:
```
RESTIC_REPOSITORY
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
RESTIC_PASSWORD
```

Command:
`restic backup /path/to/folder --exclude="/path/to/*/*/.stversions" --exclude="/path/to/other/folder" `

Output:
```
open repository
repository 12345678 opened successfully, password is correct
Fatal: unable to save snapshot: client.PutObject: Put https://s3.wasabisys.com/XXXXXXXX/data/50/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: net/http: HTTP/1.x transport connection broken: write tcp <local_ip>:<local_port>-><remote_ip>:443: write: no route to host_<PART_OF_PATH!!>
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3 (Wasabi)

Expected behavior
-----------------
Should upload snapshot without error and without requesting a host with contains part of the path of a file!

Actual behavior
---------------
It seems that restics stops doing the snapshot always at the same file. I am a bit scared, because it seems part of the path is interpreted as hostname.

`connection broken: write tcp <local_ip>:<local_port>-><remote_ip>:443: write: no route to host_<PART_OF_PATH!!>`

Steps to reproduce the behavior
-------------------------------
I can reproduce it by running `restic backup` again, it breaks always on the same file.

Do you have any idea what may have caused this?
-----------------------------------------------
No.

Do you have an idea how to solve the issue?
-------------------------------------------
No.

Did restic help you or made you happy in any way?
-------------------------------------------------
New restic user here, just spent couple of hours with it.

**Comment by fd0** [comment]
Hm, odd. Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it. You'll see all HTTP requests/responses, maybe we can see something there...

**Comment by MichaelEischer** [comment]
Closing this as we got no response within a year. I'm also suspecting that error message got garbled by the backup progress display.
