### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by andrewsav-datacom** [restic/restic#2164]
On <https://github.com/restic/restic/blob/4609b5c24d82c2307fe826af54fd65ad1a54680b/doc/030_preparing_a_new_repo.rst> The first link in the paragraph `You can workaround this by using a special tool` links to <https://sourceforge.net/p/msys2/wiki/Porting/> which is a dead link.

**Comment by moritzdietz** [comment]
Thanks to archive.org there is a live snapshot from 2015. https://web.archive.org/web/20151212033152/http://sourceforge.net/p/msys2/wiki/Porting/

Now we can either remove the link or link to the copy of it.

**Comment by AndrewSav** [comment]
This seems to be the modern version of this: https://github.com/msys2/msys2/wiki/Porting

**Comment by moritzdietz** [comment]
Ok so I created a PR with the new link in place. Now we wait for it to be merged :-)

**Comment by fd0** [comment]
Thanks!
