### ISSUE TITLE
Username missing from snapshot?

### ISSUE THREAD

**Issue by fukawi2** [restic/restic#2168]
Output of `restic version`
--------------------------
`restic 0.9.4 compiled with go1.11.4 on linux/amd64`

Describe the issue
------------------
When restoring from a snapshot, the following line is displayed:

     restoring <Snapshot accc8e2f of [/vm-disks] at 2019-02-15 02:04:49.595453279 +1100 AEDT by @kvm1807.example.com> to /tmp

Note what appears to be text missing from before `@kvm1807.example.com`. I'm assuming this is supposed to be the local username of the initiating user?

I run my backups under systemd as service/timer units as root using this unit file for the service:

```
[Unit]
Description=restic "%I" backup
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
Nice=10
CPUShares=512
IOSchedulingClass=idle
Environment=HOME=%h
EnvironmentFile=/etc/restic/%i.env
ExecStart=/usr/local/bin/restic backup \
  --tag %I --verbose \
  --exclude-file /etc/restic/%i.exclude \
  --files-from /etc/restic/%i.include \
  --exclude-caches
```

`EnvironmentFile` contains `RESTIC_REPOSITORY` and `RESTIC_PASSWORD` variables.

Obviously not a huge problem, just cosmetic most probably.

I'm guessing it's something missing in this function maybe? https://github.com/restic/restic/blob/4c2072d875e14cf0c50ac449396e26297208e473/internal/restic/node.go#L542

**Comment by MichaelEischer** [comment]
@fukawi2 restic just calls the Go standard library function to retrieve the current username. Is this still a problem? You could take a look at a recent snapshot using `restic cat snapshot <id>`. But I'm not sure we can do anything about it when the username retrieval fails.

**Comment by fukawi2** [comment]
This looks like it did get fixed somewhere along the line 🎉 

```
$ restic restore -i /guacamole-1602342082.xml -t /tmp ce342758
repository 85ed8a29 opened successfully, password is correct
restoring <Snapshot ce342758 of [/guacamole-1602342082.xml] at 2020-10-11 02:01:22.784996047 +1100 AEDT by root@kvm1807.example.com> to /tmp
$
```

**Comment by MichaelEischer** [comment]
I'm closing this issue for now as the issue no longer shows up. Feel free to reopen it when the problem shows up again.
