### ISSUE TITLE
Password not accepted when entering it into console instead of using RESTIC_PASSWORD

### ISSUE THREAD

**Issue by c0ldplasma** [restic/restic#2170]
Output of `restic version`
--------------------------
`restic 0.9.4 compiled with go1.11.4 on linux/amd64`

How did you run restic exactly?
-------------------------------
1. export B2_ACCOUNT_ID=[b2AccountId]
2. export B2_ACCOUNT_KEY=[b2AccountKey]
3. restic -r b2:[BucketName]:[FolderName] snapshots

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze b2

Expected behavior
-----------------
Password should be accepted like it is when using the environment variable RESTIC_PASSWORD.

Actual behavior
---------------
Password is rejected when entering it after `enter password for repository:` with this output: `Fatal: wrong password or no key found`. When using RESTIC_PASSWORD it works.

Steps to reproduce the behavior
-------------------------------
Try to open a b2 repository with entering the password in the console, NOT with environment variable RESTIC_PASSWORD.

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
Workaround: Use the environment variabele RESTIC_PASSWORD for the password.

Did restic help you or made you happy in any way?
-------------------------------------------------
Well, in the end i could recover the backup. That's good i think 👍

**Comment by fd0** [comment]
Huh, that's very odd. Does your password maybe contain any characters outside of the ASCII set? How do you set `$RESTIC_PASSWORD`, can you paste the command (replace the actual password with `XXX`, but leave the quotation marks (if any) in place).

**Comment by c0ldplasma** [comment]
My password does not contain any characters outside of the ASCII set, but it does contain a $ sign. I did some testing and it seems like the part from the $ sign until the next special character got interpreted as a variable, which was of course empty. So basically my actual password is the password without the $ sign and without the part after it until the next special character. (Tested it with both the interactive and the environment variable method. Works both.) Actually i wonder if this is just normal bash behavior and thereby my own fault -.- ? If this is the case sorry for wasting your time.

For the sake of completeness:
For setting $RESTIC_PASSWORD i use: `export RESTIC_PASSWORD=XXX` (No quotation marks at all.)

**Comment by c0ldplasma** [comment]
For better understanding, I set my password to something like: `neiqd$mdiw*wdw2`
The part `$mdiw` gets interpreted as variable in is thereby just an empty string. So the actual password would be `neiqd*wdw2`.

**Comment by OmenWild** [comment]
>  For setting $RESTIC_PASSWORD i use: `export RESTIC_PASSWORD=XXX` (No quotation marks at all.)

Change your export to add single quotes around your password:

`export RESTIC_PASSWORD='neiqd$mdiw*wdw2'`

Then your shell will not try to interpret the `$mdiw` part as a variable to expand.

**Comment by mholt** [comment]
Great, the case is closed then!
