### ISSUE TITLE
Feature-Request: gopass support

### ISSUE THREAD

**Issue by shibumi** [restic/restic#2173]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.5 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Retrieving keys via `gopass` (https://www.gopass.pw/) would be super awesome, because environment variables are insecure.

What are you trying to do?
--------------------------
I like to pipe my repository passwords to restic in a secure manner, without storing them in cleartext password files or environment variables

Did restic help you or made you happy in any way?
-------------------------------------------------
restic is awesome!

**Comment by Crest** [comment]
Can't you just read the key from /dev/stdin?

**Comment by fd0** [comment]
> because environment variables are insecure.

Why is that? I think it's a common misconception, I've written a bit about it here: https://forum.restic.net/t/read-password-from-gnome-keyring/1094/6?u=fd0

If you still don't like to use environment variables, you can use the shell to read the password:
```
$ restic --password-file <(pass restic/password) [...]
```

**Comment by shibumi** [comment]
thanks this works for me.
