### ISSUE TITLE
Invalid mtimes (year > 9999) fails snapshot

### ISSUE THREAD

**Issue by labkode** [restic/restic#2174]
Hi,

we are evaluating  restic for performing a multi-user multi-petabyte daily backup of our storage repository. The preliminary results are very promising and we are very satisfied on the performance and friendly usage of the tool, specially the fuse based snapshot view (awesome!). From time to time we find files that has invalid mtimes because our storage system [EOS](http://eos.web.cern.ch/) allows arbitrary utimes system calls from end-users. Unfortunately, these files causes restic to not backup the user home directory.

This issue is related to https://github.com/restic/restic/issues/1173

Output of `restic version
--------------------------
```
restic 0.9.4 compiled with go1.11.4 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```
restic --cache-dir /var/cache/restic/user0 --cleanup-cache -o s3.connections=32 -r s3:s3.xxxx/cboxback-user backup  --parent=39fb6be1 --exclude='*.sys.a#*' --exclude='*.sys.v#*' /home/user0
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
```
S3
```

Expected behavior
-----------------

Files with invalid mtimes should be backed up and the creation of the snapshot should not fail because of this

Actual behavior
---------------

With file mtimes where the year is not in the range 0-9999 the backup fails.

Steps to reproduce the behavior
-------------------------------

1) ```touch future.zip```
2) Create utime.c
```
#include <utime.h>
#include <time.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

main() {
  int file_descriptor;
  char fn[]="future.zip";
  struct utimbuf ubuf;
  struct stat info;

  if ((file_descriptor = creat(fn, S_IWUSR)) < 0)
    perror("creat() error");
  else {
    close(file_descriptor);
    puts("before utime()");
    stat(fn,&info);
    printf("  utime.file modification time is %ld\n",
           info.st_mtime);
    ubuf.modtime = 9223372036854775807;       /* set modification time to max int64 */
    time(&ubuf.actime);
    if (utime(fn, &ubuf) != 0)
      perror("utime() error");
    else {
      puts("after utime()");
      stat(fn,&info);
      printf("  utime.file modification time is %ld\n",
             info.st_mtime);
    }
  }
}
```

3) ```gcc utime.c -o utime```
4) ```./utime```
5)
 ```  $ stat future.zip 
  File: `future.zip'
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 22h/34d	Inode: 798         Links: 1
Access: (0644/-rw-r--r--)  Uid: (95491/user0)   Gid: ( 2763/      it)
Access: 9223372036854775807
Modify: 9223372036854775807
Change: 2019-02-19 09:18:30.828784073 +0100
```
6) Restic outputs: ``` invalid modtime```

Do you have any idea what may have caused this?
-----------------------------------------------
Yes,
https://github.com/restic/restic/blob/4c2072d875e14cf0c50ac449396e26297208e473/internal/restic/node.go#L336

Do you have an idea how to solve the issue?
-------------------------------------------
Yes, but I would like to understand what are the consequences of allowing bigger year ranges in the validation or even disabling the validation. Would allowing invalid mtimes/atimes impact the backup logic?

Thanks a lot !

**Comment by labkode** [comment]
Ping @fd0 @ifedorenko

**Comment by labkode** [comment]
Hi @fd0 @ifedorenko could you please gives us some light on this issue? We find some backups that fail because of this and `touching` user files to make the backup running is invasive. Thanks!

**Comment by fd0** [comment]
Hey, thanks for the report. I'm a bit under the weather time-wise, so it takes me a while to respond. The issue is that we're using JSON for storing our internal data structures, and the JSON representation of a timestamp returns an error when the year is larger than 9999, see here:
 * https://golang.org/src/time/time.go#L1258
 * https://github.com/golang/go/issues/4556#c15

I'm not sure what to do here. We could do several things:
 * Convert the error to a warning, store either "0000" or "9999" as the year (depending on what the year is). The value is bogus anyway, but this way the file would get at least stored. You won't get the same timestamp restored though.
 * Store the timestamps in a different format, or add a new field to the repo format which contains the raw values. I don't like modifying the repo format, especially for such obviously bogus values. Hm.

Thoughts?

**Comment by labkode** [comment]
@fd0 Thanks for the time to go through the issue. My preferred option would be to go for the 0000 and 9999 values, it is easy to understand from a user running Restic and for developers, the other alternatives increase the complexity of the code base.

**Comment by fd0** [comment]
I'll implement a prototype then we can play with it.

**Comment by fd0** [comment]
See #2253 and the branch `fix-2174` if you want to try it :)
