### ISSUE TITLE
Specify user and/or host when adding key

### ISSUE THREAD

**Issue by cdhowie** [restic/restic#2175]
Output of `restic version`
--------------------------
```
restic 0.9.4 compiled with go1.11.4 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
It would be nice to be able to override the user and/or host values when adding a host to restic.

* Sometimes I am adding a key for a new host, but from a different host.
* Sometimes the short hostname on the new machine is ambiguous, so the key is added with the host `www`.  We might have multiple hosts with the short hostname `www`, so this is not useful.

What are you trying to do?
--------------------------
Add a new key with the FQDN of the current host, which does not seem possible.

**Comment by ahktenzero** [comment]
I've also run into this problem. I'm working on configuring restic backups on my systems using Salt and as part of that I want to be able to add passwords for each of the backup clients by running ``restic key add`` on the server and have the right user and host details on the keys. 

I've had a go at implementing this in my feature/set-user-host-keys branch, you can override the user and hostnames for the new key by adding ``key-username=<name>`` and/or ``key-hostname=<host>`` to the arguments for ``restic key add``, I will be submitting a PR soon.
