### ISSUE TITLE
restic self-update fails with Fatal: unable to update restic: context deadline exceeded

### ISSUE THREAD

**Issue by CristianCantoro** [restic/restic#2181]
Output of `restic version`
--------------------------
```bash
# restic version
restic 0.9.3 compiled with go1.11.1 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```bash
# restic self-update                    
find latest release of restic at GitHub
latest version is 0.9.4
download SHA256SUMS
download SHA256SUMS.asc
GPG signature verification succeeded
download restic_0.9.4_linux_amd64.bz2
Fatal: unable to update restic: context deadline exceeded
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
N/A

Expected behavior
-----------------
restic gets updated

Actual behavior
---------------
restic is not updated

Steps to reproduce the behavior
-------------------------------
run `restic self-update` as root or `sudo restic self-update`

`restic` is installed at `/usr/local/bin/restic`:
```bash
# command -v restic
/usr/local/bin/restic
```

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you or made you happy in any way?
-------------------------------------------------
restic is fantastic, I am using it to backup my laptop and I am going to use it at work as well!

**Comment by dimejo** [comment]
I'm wondering if this has something to do with #2041. Did you run the command in the same directory in which restic is located?

**Comment by CristianCantoro** [comment]
@dimejo wrote:
> I'm wondering if this has something to do with #2041. Did you run the command in the same directory in which restic is located?

No, I have run it from several locations, but not in `/usr/local/bin/`.

**Comment by fd0** [comment]
Huh, interesting! You've run into the hard-coded 30 second timeout. Initially, it was meant for GitHub API requests, but it looks like it is also used for the download. So if the download does not finish in 30 seconds, this error is returned. I'll fix this in a minute.
