### ISSUE TITLE
Expose internal filerestore options for performance tuning

### ISSUE THREAD

**Issue by labkode** [restic/restic#2182]
Output of `restic version`
--------------------------

 restic 0.9.4 compiled with go1.11.5 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Expose file restore options for tuning the restore procedure: https://github.com/restic/restic/pull/2178

What are you trying to do?
--------------------------

Did restic help you or made you happy in any way?
-------------------------------------------------

**Comment by MichaelEischer** [comment]
Closing this as the corresponding PR has also closed.
