### ISSUE TITLE
Rare race on restore: ignoring error for filename: write filename: file already closed

### ISSUE THREAD

**Issue by d3zd3z** [restic/restic#2183]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on linux/amd64

How did you run restic exactly?
-------------------------------
```sh
export RESTIC_REPOSITORY="s3:https://s3.wasabisys.com/bucketname/directory"
export AWS_ACCESS_KEY_ID="xxx"
export AWS_SECRET_ACCESS_KEY="xxx"
export RESTIC_PASSWORD="xxx"
sudo restic restore --target . 896b87d9
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Wasabi

Expected behavior
-----------------
Restore of files

Actual behavior
---------------
During restore, I got a message like:
```
ignoring error for path/to/filename: write path/to/filename: file already closed
```

After the restore, I looked at the file, and it had been created, but was 0 bytes long.

Steps to reproduce the behavior
-------------------------------
Unfortunately, it doesn't seem to happen consistently. I'm reporting this since it suggests a race where the file is closed before being restored.

Do you have any idea what may have caused this?
-----------------------------------------------
I suspect a race and one thread is closing the file before another thread has a chance to write data to it.

Do you have an idea how to solve the issue?
-------------------------------------------
Probably need to find the race.

Did restic help you or made you happy in any way?
-------------------------------------------------
All of the files have restored on subsequent restores. I will be testing restores repeatedly to see if this happens any more for me.

**Comment by ifedorenko** [comment]
Thank you for the report. Will try to fix over the weekend.

The race is here https://github.com/restic/restic/blob/master/internal/restorer/fileswriter.go#L46. When file write cache overflows, it may purge writer used by concurrently running gorouting.
