### ISSUE TITLE
Increase the effective granularity of `--read-data-subset`

### ISSUE THREAD

**Issue by cfbao** [restic/restic#2186]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
`restic check --read-data-subset n/m` currently only uses the first byte of pack ID to divide packs into subsets. This limits the effective granularity to at most 1/256.

I hope restic can use a few more bytes instead (e.g. 2 bytes or 4 bytes) so the effective granularity can be increased. It can also help make packs more even distributed among subsets when m ≈ 100 - 200.

What are you trying to do?
--------------------------
Do data checks of random subsets more frequently without using too much data each time.

Did restic help you or made you happy in any way?
-------------------------------------------------
Absolutely. Having efficient daily backups is so great. Already saved my ass multiple times.

**Comment by ifedorenko** [comment]
The idea behind current `--read-data-subset` implementation is to do rolling check of _all_ packs over period of time, so you are certain each pack is checked at least once during the period.

Do you really want to randomly check (very) small subset of packs without checking every pack at least once during any given period of time? Or did I misunderstand the request?

**Comment by cfbao** [comment]
> Do you really want to randomly check (very) small subset of packs without checking every pack at least once during any given period of time?

Yes, that's exactly what I want to do. Just a random sample to make sure nothing has gone terribly wrong with my storage.
If I want to do rolling checks, a longer period of time (say 512 subsets in 2 years) is also fine by me.

Even with rolling checks over a shorter period of time, I think there's still some (perhaps limited) benefits to use more than the first byte.
One benefit is to more equally divide the packs, as mentioned earlier.
Another is to break the data subfolder boundaries when building subsets (if using big endian byte order when converting to integer), because subfolders are also arranged using the first byte of pack IDs. Breaking subfolder boundaries makes it likely that most/all subfolders would have at least some of their contained packs checked in a much shorter period of time. Should something funny happen to all files in a particular subfolder (perhaps due to an improper file operation that truncated them), the error can be discovered a lot earlier.
(Ok, I might be stretching a bit here.)

**Comment by julianbrost** [comment]
Should be an easy fix, I'd work on it.

Changing this will inevitably change the behavior in a way that might result in users thinking they now have read the whole repo when they actually haven't. For this reason I'd prefer little endian encoding as this will at least stay compatible if m=2^k. And for other cases, you could still somewhat emulate the existing behavior by using multiple calls with m=256. But I see the point of spreading the reads across subdirectories in the repo, so if I'd build the feature from scratch, I'd also go that way. Any other opinions on what to choose?

(I also briefly thought about using `big.Int` and the full hash, but I think that's overkill, even if you only want to do some random sampling, I wouldn't expect very large values for m (like >10^6), so the buckets should be roughly the same size even using only 32 bits from the hash. I'd still go for 64 bit though.)

**Comment by BenWiederhake** [comment]
To give another data point: I'm using `--read-data-subset` so that `check` checks for a little bit more than the bare minimum, but do so all the time in the background.

Assume a repository of roughly 1 TiB.  Like cfbao, I want to do "just a random sample".  Specifically, I don't really like having only the choice between transferring 4 GiB (1/256 TiB unless I'm too tired) or not reading the data at all.
