### ISSUE TITLE
Support 0.9.4 on Ubuntu Bionic (18.04 latest LTS) as a package

### ISSUE THREAD

**Issue by stunney** [restic/restic#2188]
I would like to see 0.9.4 of restic available as a supported package on the latest LTS (18.04.2 as of this writing) of Ubuntu.  Right now 0.8.3 is the one that installs but I cannot use this with B2 (blackblaze) accounts for backups.

Thank you :)

**Comment by fd0** [comment]
Hm, we don't provide any packages for distributions, you would need find someone at Ubuntu to do that. We don't have the resources to provide packages.

You could use the released binaries though, they are statically linked and don't depend on anything.

**Comment by stunney** [comment]
Thanks for the tip!  I will do that instead.

Cheers!

**Comment by stunney** [comment]
Okay, so I'm running 0.9.4 and I've configured (I think) my env vars properly

**B2_ACCOUNT_ID** is the name of my application key
example
`export B2_ACCOUNT_ID="myappkeyname"`

**B2_ACCOUNT_KEY** is the key
example
`export B2_ACCOUNT_KEY="<base64 stuff copied from blackblaze web UI>"`

RESTIC_REPOSITORY is the name of the bucket itself prepended with b2: in front of it
example
`export RESTIC_REPOSITORY="b2:mybucket"`
when I run 
`restic init` 
I get the following error:
`Fatal: create repository at b2:bigboy failed: b2.NewClient: b2_authorize_account: 401:`

Even
`restic -r "b2:bucketname" init`
or
`restic -r "b2:appkeyname" init`

produce the exact same error.

Any thoughts on what I'm doing wrong?

**Comment by stunney** [comment]
Nevermind.  B2_ACCOUNT_ID is not the NAME of the "keyName" but rather the "applicationKeyId" found in the blackblaze UI.  All is well.  Thanks!

**Comment by fd0** [comment]
Thanks for taking the time and leaving your solution here, this will help people :)
