### ISSUE TITLE
Restic should clean the environment for subprocesses

### ISSUE THREAD

**Issue by jo-so** [restic/restic#2192]
# Output of `restic version`

`restic 0.9.4 compiled with go1.11.5 on linux/amd64`

It seems restic doesn't clean up the environment of subprocesses. I've replaced the *ssh* command by a script that dumped the environment and it still contained the *RESTIC_PASSWORD*.

This way I could steal the password from a script that I had called via *sudo*.

```
% cat ~/bin/ssh
#!/bin/sh

env |grep RESTIC_PASSWORD >&2
exit 1

% sudo run-remote-backup
subprocess ssh: RESTIC_PASSWORD=…
Fatal: unable to open repo at sftp:s1:Backup/backup: unable to start the sftp session, error: EOF
```

I know, this is very special, but I think it would the useful to remove the *RESTIC* entries from the environment of subprocesses.

**Comment by fd0** [comment]
Oh, that's a good point, thanks for reporting it!
