### ISSUE TITLE
Bandwidth limits don't seem to apply properly to Backblaze B2

### ISSUE THREAD

**Issue by coreagile** [restic/restic#2194]
Output of `restic version`
--------------------------
`restic 0.9.4 compiled with go1.11.4 on linux/amd64`

How did you run restic exactly?
-------------------------------
`restic backup -r b2:b2-dest --cleanup-cache --exclude-file /home/user1/.restic_exclusions --limit-download 1024 --limit-upload 640 /mnt/user1 /mnt/user2`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
For the total bandwidth consumption to max out at 1M download, 640K upload.

Actual behavior
---------------
The total bandwidth consumption was 24.6M download, 4.42M upload. When I ran `iftop` I noticed 5 separate connections to known Backblaze IPs, each exceeding the limits I set for restic.

Steps to reproduce the behavior
-------------------------------
Run a backup against a Backblaze repository with bandwidth limits.

Do you have any idea what may have caused this?
-----------------------------------------------
Maybe the Backblaze connector doesn't respect these limits?

Do you have an idea how to solve the issue?
-------------------------------------------
Make the Backblaze connector respect the limits?

Did restic help you or made you happy in any way?
-------------------------------------------------
Of course! It has saved my bacon many times using local NAS backups.

**Comment by MichaelEischer** [comment]
@coreagile Do you still have the bandwidth limit problem? Could you try whether it works with a newer restic version?
The code itself implements a bandwidth limit across all connections. The limiting itself works similar to other backends, for which the bandwidth limit definitely works.

**Comment by fd0** [comment]
I'll close this issue for now, please add a comment so we can reopen it if the issue is still present. Thanks a lot!
