### ISSUE TITLE
SHA256SUMS outdated

### ISSUE THREAD

**Issue by guedou** [restic/restic#2198]
It seems that the SHA256SUMS are not updated since the 0.8.2 release.

The downloaded file from https://github.com/restic/restic/releases/download/v0.9.4/SHA256SUMS does not contains sums for 0.9.4.

**Comment by fd0** [comment]
That's not the case:
```
$ curl -L https://github.com/restic/restic/releases/download/v0.9.4/SHA256SUMS
c7dca90fb6fd83cee8b9f6a2776f5839794341af1953d251bf06a91870be7a8e  restic-0.9.4.tar.gz
43836fc05af4c552cb500cdc87a6ca06a6fb0f6b8f179171f1a971aee0a4d6f7  restic_0.9.4_darwin_386.bz2
df278eebd151b6ff62ceae968e3a4203a58d447712ec3fdb62551b25299a61e1  restic_0.9.4_darwin_amd64.bz2
[...]
```

I'm guessing you had an old `SHA256SUMS` file in your `Downloads` directory, so the new one was saved under a different name. Can you please recheck?

I'm closing this issue for now, please do add feedback!

**Comment by guedou** [comment]
It checks and f works as expected. Thanks.

**Comment by fd0** [comment]
Thanks for the feedback :)
