### ISSUE TITLE
Environment variables are not expended when used in include or exclude files on Windows

### ISSUE THREAD

**Issue by ProactiveServices** [restic/restic#2201]
Note: The below behaviour seems to be the same for both --files-from and --exclude-file.

Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on windows/amd64

How did you run restic exactly?
-------------------------------

Desktop folder has A.txt through D.txt.

`restic backup -r tmp --exclude-caches --exclude-file excludes.txt --exclude ""%userprofile%\Desktop\D.txt" .`

exclude.txt contains:
```
`%userprofile%\Desktop\A.txt
%USERPROFILE%\Desktop\B.txt
C.txt
```

```
restic ls -r tmp latest
repository 429dbf49 opened successfully, password is correct
snapshot 72b5a390 of [C:\Users\Test\Desktop] filtered by [] at 2019-03-08 17:35:12
.4313035 +0000 UTC):
/A.txt
/B.txt

```
What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local

Expected behavior
-----------------
None of A.txt, through D.txt to be present in the repo.

Actual behavior
---------------

A.txt and B.txt are present in the repo; entries referenced via envvars in the exclude file are not excluded. Such entries referred by --exclude or --include are considered.

Do you have any idea what may have caused this?
-----------------------------------------------

Envvars not being expanded in the exclude/include logic when reading patterns from files. I presume the OS is expanding when read directly from the command line.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes, by being a trustworthy backup program <3

**Comment by MichaelEischer** [comment]
related to #2825 and #2826

**Comment by Pradesh-GH** [comment]
I was successful using the following syntax in the exclusion file:
```
## $userprofile  = C:\Users\User
## $localappdata = C:\Users\User\AppData\Local
## $appdata      = C:\Users\User\AppData\Roaming

## reparses points
$localappdata\Microsoft\Windows\INetCache\Low\Content.IE5
$localappdata\Microsoft\WindowsApps\

#Local
$localappdata\Comms\
$localappdata\D3DSCache\
$localappdata\ElevatedDiagnostics\
$localappdata\Microsoft\Internet Explorer\
$localappdata\Microsoft\Windows\Explorer\
$localappdata\Microsoft\Windows\Notifications\
$localappdata\Microsoft\Windows\UsrClass.*
$localappdata\Microsoft\Windows\WebCache\
$localappdata\NVIDIA\DXCache\
$localappdata\Packages\
$localappdata\Temp\

#Roaming
$appdata\Microsoft\Windows\Recent\

#Profile
$userprofile\ntuser*
$userprofile\NTUSER*

#Global
Thumbs.db
```

**Comment by MichaelEischer** [comment]
Then let's close this as "works as documented" for exclude files. We could add remark to the documentation, that the `$` syntax must also be used on Windows. Environment variable in include files are already tracked in #2825.
