### ISSUE TITLE
rclone parallel uploads

### ISSUE THREAD

**Issue by cvillabrille** [restic/restic#2204]
Output of `restic version`
--------------------------
restic 0.9.4 (v0.9.4-37-g7b8d1dc0) compiled with go1.11.4 on linux/arm64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
uploading more files in parallel through rclone.

What are you trying to do?
--------------------------

restic uploads 4 files in parallel through rclone. Due to some weird limitations on the remote storage, they only allow 500kb speed or so per file uploaded, however, if we increase the number of parallels connections we can use more bandwidth and reduce backup time (tested and confirmed with rclone sync).

Example of current rclone uploads to Jotta Cloud (just as an example, it can be with oneDrive, hubic, opendrive, b2, etc...) command used:

`restic  backup /srv/dev-disk-by-label-DATAdroid  --exclude-file=/root/filter.restic -v -v  --repo rclone:oDroid-Jotta:/restic/dataDroid -o rclone.connections="10"   -o rclone.args="serve restic --stdio --rc --rc-addr localhost:5582 --rc-no-auth --config /root/.config/rclone/rclone.conf --log-file /mnt/cache/log/restic.jotta -v --transfers 10 --stats=20s"`

achieving the following output...

```
Transferred:        1.307G / 1.316 GBytes, 99%, 1.616 MBytes/s, ETA 5s
Errors:                 0
Checks:                 0 / 0, -
Transferred:          275 / 279, 99%
Elapsed time:    13m48.1s
Transferring:
 *     data/45/45a7f45c3de3…0be968fb3887a4f3316f:  7% /4.005M, 163.955k/s, 23s
 *     data/4a/4a9a4b16f1a9…668a9089f9602d2c731e: 27% /4.593M, 451.721k/s, 6s
 *     data/97/97965e0121dc…c76f0b070a9b9876f7d4: 97% /4.146M, 565.974k/s, 0s
 *     data/e4/e4562dd9205e…1dfd2c0b293fa66dfc4b: 54% /4.599M, 520.954k/s, 4s
```

how it should be...

as many files as the parameter rclone.connections (10 in this command), or a new parameter, is set up, so then we could be uploading 10 files (instead of our current 4, the default by rclone with no modifiers) reducing the time of the backups.

I have seen in the code (restic/internal/backend/rclone/config.go), we can configure the number of connections, however, that does not change the number of uploads through rclone.

`Connections uint option:"connections" help:"set a limit for the number of concurrent connections (default: 5)"`

and in 

```
func NewConfig() Config {
        return Config{
                Connections: 5,
        }
}
```
Nevertheless, I guess above configurations are more about the number of connections to rclone rather than the amount of files to be uploaded in parallel. am I right?

Did restic help you or made you happy in any way?
-------------------------------------------------
I am starting to use this great piece of software and I guess that can help me to keep my data safe, I would really like the idea of having a software fully customizable. Please, allow setting up a new parameter that will be the amount of parallels files to be uploaded. We can then extensively use more bandwidth uploading more files.

I have a lot of experience uploading backup to cloud storage providers, and is very annoying having enough bandwidth to upload 1Tb in less than 12hours and spend 3 days or more in doing so....
 
(1Tb of data to be uploaded to jotta through restic/rclone is taking 170hours).

Keep doing such a good stuff!!, you rock!

**Comment by cvillabrille** [comment]
A quick update.

within the file "internal/archiver/archiver.go" I have found a parameter which....

        // SaveBlobConcurrency sets how many blobs are hashed and saved
        // concurrently. If it's set to zero, the default is the number of CPUs
        // available in the system.
        SaveBlobConcurrency uint


by default is setup to the number of CPUs
if o.SaveBlobConcurrency == 0 {
                o.SaveBlobConcurrency = uint(runtime.NumCPU())
        }

which is fine, as that fits on the amount of parallel uploads I am having (4 CPUs = 4 Parallel uploads). however, what happens if there is only one CPU available?

Is there any way to stablish this value by adding a -o SaveBlobConcurrency="X" option?

I have tried with some attempts however, it did not work. Still was using the amount of CPUs.

-o SaveBlobConcurrency=8
-o saveblobconcurrency=8
-o o.SaveBlobConcurrency=8


I have finally update the value to something that fit my needs (around 10) in order to do so (if anyone interested)...

on line 8, comment "runtime" (we are replacing SaveBlobConcurrency with a fix value)
        //"runtime"


and then on this line...

                o.SaveBlobConcurrency = uint(runtime.NumCPU())

with 
                o.SaveBlobConcurrency = 8


So it will look like... 

        if o.SaveBlobConcurrency == 0 {
                o.SaveBlobConcurrency = 8
        }


and then compile. **Please, be aware you are increasing this parameter to all future backups (does not matter if those are through rclone or not), be responsible on this change.** I am not planing to backup in orther way than trhough rclone, hence... it fit my requirements, which does not mean will fit others. **Do it at your own risk. Remember, developers are always right on what they have designed.**

if you still want to reduce the parallel uploads, you can always add

-o rclone.args="--transfers 5" and the amount of parallels uploads will fit that number.


@fd0 Can we have this SaveBlobConcurrency parameter setup through the -o modifier? (I guess that will make easier and dynamic the number of uploads). Naming convention to set up this parameter can be at your decision :)

If this is already in place, what is the parameter to add to -o to make it work?

**Comment by gliptak** [comment]
Is there a list of the various ```-o``` flags (against ```rclone``` in particular)?

I also observed ```rclone``` processing stopping, various timeouts and reset connections, which seem to have improved by forcing ```rclone.connections=1``` and ```concurrency=1```

https://github.com/restic/restic/commit/c43c94776b13053afccef4341a488e68d102f700 https://github.com/ncw/rclone/issues/2166 https://github.com/restic/restic/issues/928

**Comment by dimejo** [comment]
> Is there a list of the various -o flags (against rclone in particular)?

No need to use `-o flags` for rclone as every option can be configured by [environment-variables](https://rclone.org/docs/#environment-variables).

**Comment by ezbik** [comment]
Yes we need concurrency limit for rclone backend. 
E.g. some FTP hosts don't support more than N connections.
Error output from restic:

```
Save(<data/bab97b811c>) returned error, retrying after 791.085236ms: server response unexpected: 500 Internal Server Error (500)
rclone: 2020/06/14 10:32:40 ERROR : ftp://ftp........net:21/restic/: Error while Logging in into ftp......ovh.net:21: 421 I can't accept more than 3 connections as the same user

```

**Comment by dimejo** [comment]
Note that there is a difference between the number of connections restic uses to communicate with rclone and the number of connections rclone uses to communicate with the backend (i.e. FTP).

For configuration of rclone (and communication to its backend) you can use [environment variables](https://rclone.org/docs/#environment-variables). If you want to limit the number of connections rclone makes to the backend, you need to set [RCLONE_TRANSFERS](https://rclone.org/docs/#transfers-n) and (depending on your backend) [RCLONE_CHECKERS](https://rclone.org/docs/#checkers-n).

**Comment by MichaelEischer** [comment]
The number of backend connections can now be controlled for each backend using `-o rclone.connections=42` starting from restic 0.14.0 (not yet released).

**Comment by cvillabrille** [comment]
Thanks a lot for closing it as completed. Much appreciated.
