### ISSUE TITLE
Follow symlinks

### ISSUE THREAD

**Issue by ruiztulio** [restic/restic#2211]
Output of `restic version`
--------------------------

restic 0.9.4 compiled with go1.11.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Reading the doc I found this:

> **Symlinks**  are archived as symlinks,  `restic`  does not follow them. When you restore, you get the same symlink again, with the same link target and the same timestamps.

Which is ok for most of the use cases (actually is desired y you're making a server backup or somethink like that), but it would be nice to have an option to overide this in some cases.

What are you trying to do?
--------------------------

My case: we use restic to "pack" the backups bcause in this way we can restore them in other location and run some tests against them, but we don't have the destinatino of such symlink, also this save us a lot of time.

ATM we copy the link content to a folder and then backup the "pack", but we are talking about 8 - 20G each time we do this and even when restic is very fast doing its job (takes about 2 minutes to complete the backup) the time it takes to copy the files is huge compared to this,

I know this is a very particular use case, but it would really help to have al option like: --override-and-follow-symlink (not an actual proposal)

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes, is actually part of our new standard for backups. It is being integrated with our toolchain

**Note** I created an [entry](https://forum.restic.net/t/option-to-force-follow-symlink/1508) in the forum and cdhowie reminded me that tar have a similar option: 

![a](http://screenshots.vauxoo.com/tulio/14394907819-7OWHgjwE3m.jpg)

which is a nice precedent for this one.

Regards.

**Comment by cdhowie** [comment]
I might take a stab at implementing this if @fd0 is open to the idea.

**Comment by nicola-zen** [comment]
First of all, thank you for restic. It is a great tool.

Secondly, I would also appreciate this feature.
I have a folder were I maintain a structure to be backed up that has a bunch of symlinks to the folders where the actual data is stored. This just to have a folder hierarchy that makes maintaining and consuming the back up easier, as the value of the data is not tied to the location of it. For instance, I have backups of my Nextcloud instance per each user, and I am only interested in the data and not in the fact that it is stored in /foo/bar.

I currently worked around it by `mount --bind`ing all the folders, but it is quite impractical.

**Comment by Sweenu** [comment]
I would also be very interested in that feature as I am using the https://github.com/Lobaro/restic-backup-docker image and it backs up everything from a same directory, mounted on /data.
This feature would allow me to make symlinks to every directory I want to back up on my host in the mounted directory instead of having to copy them.

**Comment by MichaelEischer** [comment]
Following symlinks during backup is discussed in #542. Closing this as duplicate.
