### ISSUE TITLE
Restic can not remove index files

### ISSUE THREAD

**Issue by jbrepogmailcom** [restic/restic#2215]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on linux/amd64

How did you run restic exactly?
-------------------------------
sudo restic prune -r /mnt/Restic --password-file pwd

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
WD My Book World connected over NFS

Expected behavior
-----------------
no error

Actual behavior
---------------
Many errror messages like
Remove(<index/f61a3dea44>) returned error, retrying after 27.215310727s: Chmod: chmod /mnt/Restic/index/f61a3dea446306f46f13dc3263b375e2a6edf91e8caeebcd056e146b7b419560: operation not permitted

Steps to reproduce the behavior
-------------------------------
Failed backup after lost connection to NAS. The only way how to get rid off the error messages is to create completely new backup repository

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you or made you happy in any way?
-------------------------------------------------

**Comment by ibib** [comment]
This seems like an issue with the rights management on your NAS to me.
Maybe the My Book mixed something up with the failed backup.

Can you check if you have write permission to the files without restic?

**Comment by jbrepogmailcom** [comment]
When I ssh to NAS as root I can rm the file. The error says it happens during chmod, but does not say what chmod command it is trying to perform.

Attributes of files that can not be deleted are:
ls -l  f0833d52559a321d876ce82798076928952fb5c9a71a5ab26bc1c672f8a3f2fd
-rwxrwxr-x    1 root     jewab      461213 Mar 22 08:33 f0833d52559a321d876ce82798076928952fb5c9a71a5ab26bc1c672f8a3f2fd

Is there any way I can change attributes so the file can be remotely deleted? I think I tried changing to 777 and it did not help.

**Comment by jbrepogmailcom** [comment]
I fixed it al local NAS by changing owner of files from root to nfsnobody

**Comment by fd0** [comment]
Cool, glad you figured it out!

**Comment by jbrepogmailcom** [comment]
Well, this worked with index files, but not with data files. I even crippled access to keys directory by giving it chmod 777 and owner root or owner nfsnobody. Restic could not access keys directory at all, claiming permissions problem. It turned out that problem was NFS implementation at My Book World. I have remounted as CIFS/SMB and so far it is working.
