### ISSUE TITLE
Error backing up to SFTP

### ISSUE THREAD

**Issue by cstegm** [restic/restic#2216]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.5 on linux/amd64

How did you run restic exactly?
-------------------------------
```
export REPO="sftp:stor:/data/restic_freenas/"
PW='/root/restic/pw'

folders="/var/log/ /usr/lib/nagios/plugins/ /root/ /etc/ /var/log/"
restic -p $PW -r $REPO --cleanup-cache --tag back backup $folders
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backend: sftp
Server: virtual server with debian, same restic version

Expected behavior
-----------------
A backup should run normally

Actual behavior
---------------
Restic throws error messages:
```
Save(<lock/f60401c8da>) returned error, retrying after 281.260441ms: ssh command exited: exit status 255
Save(<lock/f60401c8da>) returned error, retrying after 915.781864ms: ssh command exited: exit status 255
Save(<lock/f60401c8da>) returned error, retrying after 577.487361ms: ssh command exited: exit status 255
Save(<lock/f60401c8da>) returned error, retrying after 1.158568906s: ssh command exited: exit status 255
Save(<lock/f60401c8da>) returned error, retrying after 2.346885354s: ssh command exited: exit status 255
Save(<lock/f60401c8da>) returned error, retrying after 2.281932241s: ssh command exited: exit status 255
Save(<lock/f60401c8da>) returned error, retrying after 4.983026999s: ssh command exited: exit status 255
Save(<lock/f60401c8da>) returned error, retrying after 10.686693637s: ssh command exited: exit status 255
Save(<lock/f60401c8da>) returned error, retrying after 12.898044748s: ssh command exited: exit status 255
Save(<lock/f60401c8da>) returned error, retrying after 13.333977076s: ssh command exited: exit status 255
unable to refresh lock: ssh command exited: exit status 255
```

Steps to reproduce the behavior
-------------------------------
IDK

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No.
Its not a permission problem, because restic runs and logs in as root user in this case:
```
root@stor:/data/restic_freenas# ls -l
insgesamt 216
-rw-------   1 root root    155 Apr  8  2018 config
drwx------ 258 root root   4096 Apr  8  2018 data
drwx------   2 root root 172032 Mär 23 01:25 index
drwx------   2 root root   4096 Apr  8  2018 keys
drwx------   3 root root   4096 Mär 24 15:25 locks
drwx------   2 root root  24576 Mär 17 00:05 snapshots
```

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes it is awesome, and worked over a year very well until i run into this bug. Keep your awesome work going!

**Comment by cdhowie** [comment]
You may have the same issue as [this user](https://forum.restic.net/t/robustness-of-repository-issue-resolved/1475/14?u=cdhowie).  An intermediate firewall was dropping the ssh connection due to inactivity.  Try configuring your ssh client to send heartbeats by adding the following to your `~/.ssh/config`:

```
ServerAliveInterval 60
ServerAliveCountMax 240
```

**Comment by cstegm** [comment]
Thank you very much! Now my backups are running again 
```
processed 127137 files, 384.902 GiB in 4:46:17
snapshot 87b68162 saved
```

**Comment by fd0** [comment]
Awesome, thanks @cdhowie for the hint!
