### ISSUE TITLE
Run script/program on backup/restore events

### ISSUE THREAD

**Issue by Pernat1y** [restic/restic#2222]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.5 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Run script/program on backup/restore events.

For example:
restic backup --password-file .pass --repo /backups **--on-start '/root/stop_software.sh' --on-finish '/root/start_software.sh' --on-error '/root/send_email.sh %code'**

Scripts '/root/stop_software.sh' and '/root/start_software.sh' will be executed on backup start/stop and script '/root/send_email.sh' will be executed on error with argument '%code' replaced with actual error code/description from restic.

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes :)

**Comment by fd0** [comment]
Hey, thanks for the suggestion. I'm always concerned about the overall complexity of restic. While this seems easy to implement, why not call restic in a shell script, in addition to your scripts? The shell can check restic's exit code, so you know if an error has happened...

**Comment by Pernat1y** [comment]
Yes, I currently using shell script as wrapper.
Maybe it is better to keep it in that way. Feel free to close issue.

Thanks for your software, by the way :)

**Comment by fd0** [comment]
I'll close this for now, thanks!
