### ISSUE TITLE
The find command should not fail when objects are missing from the repository

### ISSUE THREAD

**Issue by cdhowie** [restic/restic#2224]
This issue has arisen a few times on the forum:

* https://forum.restic.net/t/unable-to-check-or-prune/1239/6?u=cdhowie
* https://forum.restic.net/t/repository-damaged-after-accidentally-deleting-data-files/1516/10?u=cdhowie

Output of `restic version`
--------------------------
Various; the problem is still present on 0.9.4.

How did you run restic exactly?
-------------------------------
Any variant of `restic find` that looks for a specific object can exhibit this problem.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
This is not relevant to the issue.

Expected behavior
-----------------
Restic should determine what objects reference the object named on the command line.

Actual behavior
---------------
Sometimes restic will crash with a message that an object is missing from the repository, which can include the object that was named.  For example:

```
tree cee759a90802904dcdbe733403dd452f8d709dc637d8fc97b966fc7c07838476 not found in repository
github.com/restic/restic/internal/repository.(*Repository).LoadTree
        /restic/internal/repository/repository.go:653
github.com/restic/restic/internal/walker.walk
        /restic/internal/walker/walker.go:107
github.com/restic/restic/internal/walker.walk
        /restic/internal/walker/walker.go:127
github.com/restic/restic/internal/walker.walk
        /restic/internal/walker/walker.go:127
github.com/restic/restic/internal/walker.walk
        /restic/internal/walker/walker.go:127
github.com/restic/restic/internal/walker.walk
        /restic/internal/walker/walker.go:127
github.com/restic/restic/internal/walker.Walk
        /restic/internal/walker/walker.go:56
main.(*Finder).findIDs
        /restic/cmd/restic/cmd_find.go:341
main.runFind
        /restic/cmd/restic/cmd_find.go:549
main.glob..func9
        /restic/cmd/restic/cmd_find.go:33
github.com/spf13/cobra.(*Command).execute
        /restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /restic/cmd/restic/main.go:86
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
```

Steps to reproduce the behavior
-------------------------------
There are not yet consistent steps to reproduce the issue since it can depend on how objects are packed.  Creating a repository, backing up enough data to generate a dozen or so packs, deleting a pack, and running `restic rebuild-index` might get the repository in this specific failure state, but is not guaranteed.

**Comment by cdhowie** [comment]
@fd0 Would the fix be as simple as changing this line ...

https://github.com/restic/restic/blob/c012fccd22e9e6d812817382f1c759faf9ba512b/cmd/restic/cmd_find.go#L263

... to this?

```
return false, nil
```

I don't like the idea of masking errors, but I also know that find is partially a recovery tool to help figure out what snapshot(s) are affected by a missing object and therefore find should generally try to push through errors where possible.

**Comment by fd0** [comment]
Good suggestion, print a warning but move on if possible, which exactly aligns which restic's error policy :)
