### ISSUE TITLE
Password prompt sometimes is not printed

### ISSUE THREAD

**Issue by alexeymuranov** [restic/restic#2225]
Output of `restic version`
--------------------------
```console
$ restic version
restic 0.9.4 compiled with go1.11.5 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```console
$ restic -r "$REPOSITORY" backup\
  --exclude-file ~/.restic/exclude .\
  --host Alexey-BU403UA
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

An external hard drive.

Expected behavior
-----------------

I'd like to see the password prompt.

Actual behavior
---------------

Sometimes password prompt is printed, sometimes not.  Even when it is not printed, i still can type it in and `restic` accepts it.

Steps to reproduce the behavior
-------------------------------

Run `restic` on a repository multiple times.

Do you have any idea what may have caused this?
-----------------------------------------------

This looks as if `stdout` was not flushed, or as some kind of a race condition.

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes.

**Comment by fd0** [comment]
hey, thanks for the report, that should not happen. I'm a bit confused, because we already resolved #2080 last year, can you please confirm that this is really restic 0.9.4?

**Comment by alexeymuranov** [comment]
I've posted `restic version` output.  I'll try to reproduce this with `cat`.

**Comment by cdhowie** [comment]
I just ran into this same problem.  It is 100% reproducible for me on a freshly-initialized repository, but then never seems to appear again.

```
$ restic -r test-repo init
...
$ restic -r test-repo backup /some/path
open repository
```

At this point, restic appears to hang but is actually just waiting for the password.

**Comment by alexeymuranov** [comment]
I've just tried it several time in a row.  I could not reproduce the issue with `| cat`, but without it it happened once again.

I noticed that with `| cat` the line

> repository ... opened successfully, password is correct

does not show up, i do not know if this is expects.

**Comment by fd0** [comment]
Thanks for the info, I need to dig into the code ;)

**Comment by alexeymuranov** [comment]
This does not occur anymore since upgrade to 0.9.5.

**Comment by riksteri** [comment]
I am still experiencing this kind of race condition with 0.9.5 on Windows. The repository does not need to be fresh, but I cannot reliably reproduce this. I've seen two variants of this, one with a lot of whitespace:

```
>restic.exe backup -r "$repository" --files-from "$inclusion_file"
                               open repository
```
and another one with both expected output lines on a single line:
```
>restic.exe backup -r "$repository" --files-from "$inclusion_file"
enter password for repository: open repository
```

Output of `version` is
`restic 0.9.5 compiled with go1.12.4 on windows/amd64`
