### ISSUE TITLE
for unattended backup: log uploaded/changed files

### ISSUE THREAD

**Issue by daviehh** [restic/restic#2234]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on darwin/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

It'll be nice to have `restic diff` (i.e. without specifying snapshot id) print out the diff between the 2 most recent diffs (except when there's 0 or 1 snapshot, in which case it should error)

Or, with `backup -v`, print the uploaded/changed files.

What are you trying to do?
--------------------------
For unattended/automated backup script, I would like to keep a log of files changed in each run. for the `backup` command, level-2 verbose (`-v -v`) prints all files scanned regardless of whether it's changed or not (can get around with ` | grep -v "^unchanged"` but again, would be a nice to have thing with native restic).

One could save `restic snapshots -c --last --json | jq -r '.[-1].short_id'` before and after the backup to get the 2 required snapshot id, but it would be nice to have this done in restic

**Comment by cdhowie** [comment]
The pipeline you propose wouldn't necessarily even work when you take multiple snapshots each backup (we do system and database backups as separate snapshots).  What you would want to find is the parent snapshot of each.  Consider a script like:

```
for snap in $(restic snapshots --last --json | jq -r '.[].id'); do
  parent=$(restic snapshots --json $snap | jq -r '.[].parent')
  if [ "$parent" != null ]; then
    restic diff $parent $snap
  fi
done
```

I'm not suggesting that restic shouldn't add this feature, but until then you can use a script like this.

Note that `restic diff` will fail with an error if the parent snapshot for the latest snapshot(s) doesn't exist.  This is expected.

**Comment by MichaelEischer** [comment]
@daviehh Would something like #1805 solve your problem? If yes, we should close this issue in favor of #1805. Printing changed files during backup seems to be the proper way to do this to me.

**Comment by daviehh** [comment]
great, thanks!
