### ISSUE TITLE
"Open repository" is printed in quiet mode for B2 backend

### ISSUE THREAD

**Issue by greyhare** [restic/restic#2236]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on linux/arm

How did you run restic exactly?
-------------------------------
    $ cat backup-to-b2 
    #!/bin/bash
    source /etc/restic/settings.bash
    restic --quiet backup /home
    restic --quiet backup /data/svn
    $ cat /etc/restic/settings.bash
    export B2_ACCOUNT_ID='application-key-id'
    export B2_ACCOUNT_KEY='application-key-password'
    export RESTIC_REPOSITORY="b2:bucket-name-here"
    export RESTIC_PASSWORD_FILE="/etc/restic/bucket-pw.txt"
    $ sudo ./backup-to-b2 
    open repository
    open repository
    $ 

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2 Cloud Storage

Expected behavior
-----------------
No output from the restic command.

Actual behavior
---------------
Printed "open repository" once per invocation (see above).
Backup was successful.

Steps to reproduce the behavior
-------------------------------
See above. The B2 bucket was created with default access control settings.

Do you have any idea what may have caused this?
-----------------------------------------------
Someone forgot to check the quiet flag in the B2 backend before they printed a message.

Do you have an idea how to solve the issue?
-------------------------------------------
Add an if statement? I don't know Go.

Did restic help you or made you happy in any way?
-------------------------------------------------
The backup worked. And it didn't take much to get this going. I just need the message gone because this is in a cron job and I only want email if there's a problem. For the time being I'm redirecting to /dev/null.

**Comment by fd0** [comment]
Hey, thanks for the report. We've already resolved this issue in master, can you that? You can find a pre-compiled binary here: https://beta.restic.net/restic-v0.9.4-57-g20223558/

Here's the other issue: #2140, I'm closing this as a duplicate.

**Comment by greyhare** [comment]
Ah, it was closed so that's why search didn't turn the other report up.

Any idea when this fix graduates to stable?

**Comment by fd0** [comment]
When the next version of restic is released, but there's no timeline. ;)
