### ISSUE TITLE
docs: locking

### ISSUE THREAD

**Issue by tbm** [restic/restic#2240]
I plan to run restic periodically from a cronjob.  If there's a big sync, restic might still be running while cron starts restic again.

The documentation doesn't cover locking at all, so it's not clear whether running restic again while it's running already will do The Right Thing, or whether I should make sure restic has completed before starting it again.

**Comment by lbausch** [comment]
@tbm I think your question is (partially) answered in #711

**Comment by tbm** [comment]
Thanks for the @lbausch.  This ticket didn't come up when I searched.  My current issue can be closed since #711 covers it already.
