### ISSUE TITLE
Don't echo authentication passwords

### ISSUE THREAD

**Issue by jonohill** [restic/restic#2241]
Output of `restic version`
--------------------------
`restic 0.9.4 compiled with go1.11.4 on darwin/amd64`

How did you run restic exactly?
-------------------------------

```
export RESTIC_REPOSITORY=rest:https://redacted-username:redacted-password@redacted-host/redacted-path/
export RESTIC_PASSWORD=redacted
restic init -v
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

`rclone serve restic` (via an nginx reverse proxy)

Expected behavior
-----------------

I have chosen to use a remote restic server (actually rclone) over TLS and requiring http authentication. However restic is a little too eager to echo the full repository URL that includes the http password. Needless to say this password is sensitive, since it allows access to push/pull data to the rclone server. It would be better for this not be visible in the output (and therefore logs etc)

Actual behavior
---------------

Full repository url is echoed that includes the remote password.

Steps to reproduce the behavior
-------------------------------

```
$ restic init
created restic repository debc97928d at rest:https://redacted-username:redacted-password@redacted-host/redacted-path/
```
Do you have any idea what may have caused this?
-----------------------------------------------

Not sure, presumably repository URLs are assumed not to be sensitive, but those that include a password are.

Do you have an idea how to solve the issue?
-------------------------------------------

Suggestions:
- Parse the repository url, censor the password portion when echoed
- Allow restic rest protocol credentials to be provided as environment variables (RESTIC_REST_USERNAME / RESTIC_REST_PASSWORD ?)

Did restic help you or made you happy in any way?
-------------------------------------------------

I love the simplicity and flexibility and I'm confident it'll be a really useful part of my backup strategy.

**Comment by fd0** [comment]
Oh, good point, thanks for the report!

**Comment by rawtaz** [comment]
If someone could make a nice PR (including tests) that just censors the password whenever it's output (I guess replacing the entire password with a *static* number of `*` characters, e.g. `********` , would do), that'd be great!

**Comment by creativeprojects** [comment]
I got the issue today after a backup failed and I received an email from my cron job:

`Fatal: unable to open config file: client.Head: Head http://user:***@server:8000/seafile/config: dial tcp 192.168.22.2:8000: i/o timeout`
`Is there a repository at the following location?`
`rest:http://user:password@server:8000/seafile`

The tag `good first issue` looks perfect for me, I'll have a go at fixing it :)
