### ISSUE TITLE
`restic backup` hangs indefinitely

### ISSUE THREAD

**Issue by tkphd** [restic/restic#2242]
Output of `restic version`
--------------------------

```bash
$ restic version
restic 0.3.3
compiled with go1.7.4 on linux/amd64
```

How did you run restic exactly?
-------------------------------

I'm testing Restic's behavior when a backup is interrupted, for science!

- The `test-data` directory contains one folder, generated [synthetically](https://github.com/tkphd/synthetic-data-generator), with 20 GiB of random data and an average file size of 128 KiB; and an exact duplicate of that folder, with a modified folder name.
- Both folders (40.000 GiB) have been backed up as snapshot 11b17ede.
- Four characters were changed in one of the files, and a backup was started and deliberately interrupted.
- The Bug appears upon resuming the backup.

```bash
$ restic backup --password-file ~/.restic.key -r sftp:backup-host:/path/to/backups
using parent snapshot 11b17ede
scan [test-data]
scanned 13 directories, 327687 files in 0:00
Command terminated by signal
$ restic backup --password-file ~/.restic.key -r sftp:backup-host:/path/to/backups
using parent snapshot 11b17ede
scan [test-data]
scanned 13 directories, 327687 files in 0:00
[1:55:51] 50.00%  2.959 MiB/s  20.000 GiB / 40.000 GiB  163844 / 327700 items  0 errors ETA 1:55:51
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

SFTP

Expected behavior
-----------------

Exit with an error, rather than hanging indefinitely, so that I know it's gone wrong.

Actual behavior
---------------

The backup starts out strong, and synced 20 GiB in the first 5 minutes at a reported rate of 25 to 250 MiB/s. Then the transfer rate monotonically decreases, ETA monotonically increases, data and items transferred hold constant, and the process doesn't exit (at least, not after 2.25 hours).

<details>
<summary>strace output</summary>
<p>
```bash
$ strace -f -p $(pgrep restic)
strace: Process 31463 attached with 13 threads
[pid 31491] futex(0xc420197110, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31476] restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid 31473] futex(0xc42009c510, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31474] futex(0xc420126d10, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31472] futex(0xc420196110, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31471] futex(0xc420126910, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31469] read(3,  <unfinished ...>
[pid 31468] futex(0xc42000f910, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31467] waitid(P_PID, 31470,  <unfinished ...>
[pid 31466] futex(0xc42000f110, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31465] futex(0xb2c060, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31464] restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid 31463] write(6, "\206\274Yb\30\343\322N\335?\31\235\324\337\212s\317_\200\5\256\262\302\371\251\0G\364eL\\\33"..., 12288 <unfinished ...>
[pid 31476] <... restart_syscall resumed> ) = -1 ETIMEDOUT (Connection timed out)
[pid 31476] futex(0xb0f758, FUTEX_WAKE, 1) = 1
[pid 31464] <... restart_syscall resumed> ) = 0
[pid 31476] futex(0xc420196110, FUTEX_WAKE, 1 <unfinished ...>
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31476] <... futex resumed> )       = 1
[pid 31472] <... futex resumed> )       = 0
[pid 31472] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=3} <unfinished ...>
[pid 31476] futex(0xc420197110, FUTEX_WAKE, 1) = 1
[pid 31491] <... futex resumed> )       = 0
[pid 31476] futex(0xb0f058, FUTEX_WAIT, 0, {tv_sec=0, tv_nsec=999371197} <unfinished ...>
[pid 31491] ioctl(0, TIOCGPGRP <unfinished ...>
[pid 31472] <... select resumed> )      = 0 (Timeout)
[pid 31491] <... ioctl resumed> , [31461]) = 0
[pid 31472] futex(0xc420196110, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31491] getpgid(0 <unfinished ...>
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31491] <... getpgid resumed> )     = 31461
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31491] ioctl(1, TIOCGWINSZ, {ws_row=39, ws_col=147, ws_xpixel=0, ws_ypixel=0}) = 0
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31491] ioctl(1, TCGETS <unfinished ...>
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31491] <... ioctl resumed> , {B38400 opost isig icanon echo ...}) = 0
[pid 31491] ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31491] write(1, "\33[2K[1:33:09] 50.00%  3.664 MiB/"..., 106 <unfinished ...>
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31491] <... write resumed> )       = 106
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31491] futex(0xc420197110, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31464] futex(0xb0f758, FUTEX_WAIT, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
[pid 31476] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 31476] futex(0xb0f758, FUTEX_WAKE, 1) = 1
[pid 31464] <... futex resumed> )       = 0
[pid 31476] futex(0xc420197110, FUTEX_WAKE, 1 <unfinished ...>
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31491] <... futex resumed> )       = 0
[pid 31476] <... futex resumed> )       = 1
[pid 31491] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=3} <unfinished ...>
[pid 31476] ioctl(0, TIOCGPGRP <unfinished ...>
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31491] <... select resumed> )      = 0 (Timeout)
[pid 31476] <... ioctl resumed> , [31461]) = 0
[pid 31491] futex(0xc420196110, FUTEX_WAKE, 1 <unfinished ...>
[pid 31476] getpgid(0 <unfinished ...>
[pid 31491] <... futex resumed> )       = 1
[pid 31476] <... getpgid resumed> )     = 31461
[pid 31491] futex(0xb0f058, FUTEX_WAIT, 0, {tv_sec=0, tv_nsec=998414629} <unfinished ...>
[pid 31472] <... futex resumed> )       = 0
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31476] ioctl(1, TIOCGWINSZ <unfinished ...>
[pid 31472] futex(0xc420196110, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31476] <... ioctl resumed> , {ws_row=39, ws_col=147, ws_xpixel=0, ws_ypixel=0}) = 0
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31476] ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31476] ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31476] write(1, "\33[2K[1:33:10] 50.00%  3.664 MiB/"..., 106 <unfinished ...>
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31476] <... write resumed> )       = 106
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31476] futex(0xc42009c910, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31464] futex(0xb0f758, FUTEX_WAIT, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
[pid 31491] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 31491] futex(0xb0f758, FUTEX_WAKE, 1) = 1
[pid 31464] <... futex resumed> )       = 0
[pid 31491] futex(0xc42009c910, FUTEX_WAKE, 1 <unfinished ...>
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31491] <... futex resumed> )       = 1
[pid 31476] <... futex resumed> )       = 0
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31491] ioctl(0, TIOCGPGRP <unfinished ...>
[pid 31476] futex(0xc420196110, FUTEX_WAKE, 1 <unfinished ...>
[pid 31491] <... ioctl resumed> , [31461]) = 0
[pid 31476] <... futex resumed> )       = 1
[pid 31491] getpgid(0 <unfinished ...>
[pid 31476] futex(0xb0f058, FUTEX_WAIT, 0, {tv_sec=0, tv_nsec=997983880} <unfinished ...>
[pid 31491] <... getpgid resumed> )     = 31461
[pid 31472] <... futex resumed> )       = 0
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31491] ioctl(1, TIOCGWINSZ <unfinished ...>
[pid 31472] futex(0xc420196110, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 31491] <... ioctl resumed> , {ws_row=39, ws_col=147, ws_xpixel=0, ws_ypixel=0}) = 0
[pid 31491] ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 31464] <... select resumed> )      = 0 (Timeout)
[pid 31491] ioctl(1, TCGETS <unfinished ...>
[pid 31464] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=20} <unfinished ...>
[pid 31491] <... ioctl resumed> , {B38400 opost isig icanon echo ...}) = 0
*&c.*
```
</p>
</details>

Steps to reproduce the behavior
-------------------------------

This has occurred twice:
1. Attempted to backup 50 GiB over 1 GbE, wired. This was to be a snapshot of brand new data.
2. Attempted to backup 40 GiB over the Internet. This was to be a small increment of previously-captured data.

Do you have any idea what may have caused this?
-----------------------------------------------

~~No.~~ *Edit:* Maybe. `futex()` shows up in the `strace` output, as it did in #1526.
It's likely that the remote (SFTP sever) closed the connection while Restic was busy scanning for changes. See [below](https://github.com/restic/restic/issues/2242#issuecomment-484176912).

Do you have an idea how to solve the issue?
-------------------------------------------

`^C` and trying over, especially over a high-bandwidth low-latency network, would mask the symptom, but it's not a solution.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes! This is my first encounter with deduplicating backups, and seeing 40 GiB of raw random data occupying less than 20 GiB on my backup server's disk is pure joy to behold :+1: 

cc @reid-a

**Comment by tkphd** [comment]
[Preparing a New [SFTP] Repository](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp) notes

> Please be aware that sftp servers close connections when no data is received by the client. This can happen when restic is processing huge amounts of unchanged data. To avoid this issue add the following lines to the client’s .ssh/config file:
> ```
> ServerAliveInterval 60
> ServerAliveCountMax 240
> ```

This seems likely to be the case, since the first instance of this error was encountered while preparing to back up 50 GiB of data, and the second while scanning for 4 B changed out of 40 GiB total.

It would be preferable for Restic to return with an error, instead of hanging indefinitely, when the remote hangs up.

**Comment by BenWiederhake** [comment]
Based on your version 0.3.3 I'm going to guess that you want to read this part: https://restic.readthedocs.io/en/stable/020_installation.html#debian

Maybe this issue already has been resolved in the two years since then?

**Comment by tkphd** [comment]
Maybe? Has it been? I'm never going to install *testing* or *unstable* in a production environment to find out. Thanks anyway.

**Comment by fd0** [comment]
@tkphd 

> It would be preferable for Restic to return with an error, instead of hanging indefinitely, when the remote hangs up.

Usually restic does, it looks like in your case the sftp client hasn't exited yet. Which ssh client are you using? Which server?

> Maybe? Has it been? I'm never going to install testing or unstable in a production environment to find out. Thanks anyway.

This comment comes across as aggressive, which is not justified since @BenWiederhake is trying to help. Please tone it down, thanks!

**Comment by tkphd** [comment]
That's useful feedback. Thank you for responding constructively. My intent was not hostile: with my response, I sought (1) to ask more directly whether the issue *has* been resolved in the past 2 years and (2) to state the fact that I can not test the advice in the link provided, since I am constrained to using the version of Restic packaged for Debian Stretch and perhaps stretch-backports.

I'm curious, based on the [documentation]() encouraging users to try the *testing* and *unstable* Debian distributions, if you (@fd0) have any control over the packaged version for *stable*. Stretch is a relatively new release, and the fact that the packaged version of Restic is 2 years old (v0.3.3, Jan. '18) is mildly alarming. That might be a tangent.

To answer your question,
- Server: `OpenSSH_8.0p1, OpenSSL 1.1.1b  26 Feb 2019`
- Client:  `OpenSSH_7.4p1, Debian-10+deb9u6, OpenSSL 1.0.2r  26 Feb 2019`

**Comment by tkphd** [comment]
Further testing suggests this is due to a high-latency/low-bandwidth, possibly intermittent connection with the older version of Restic, especially when using the default SSH settings.

Over the weekend, numerous Restic backups with `{10, 20, 50} GiB` datasets over 1 GbE had no difficulties. Today, backing up the data with ~`60 B` changed of `75 GiB` total over the Internet has triggered this indefinite hang numerous times.

Per @BenWiederhake's suggestion, I've sourced `restic-0.9.4` from an Arch Linux desktop, and am testing with the same settings. The backup chugs along until 40.599 GiB have been synchronized, which is where `restic-0.3.3` hangs indefinitely. With the newer version, however, it forged ahead and looks like it should successfully finish.

**Comment by fd0** [comment]
Awesome, thanks for the feedback. I'm glad your problem is resolved with a recent version of restic :)

> Thank you for responding constructively. My intent was not hostile

I have no doubts about that, and I'm also glad you took my comment as constructive feedback.

> with my response, I sought (1) to ask more directly whether the issue has been resolved in the past 2 years

It's very hard to say from your report alone without digging in deeper.

> and (2) to state the fact that I can not test the advice in the link provided, since I am constrained to using the version of Restic packaged for Debian Stretch and perhaps stretch-backports.

That's a valid constraint.

We (as the restic project) try very hard to keep our releases (and even the master branch) "stable" in a sense that it's backwards compatible so it can read older repositories. So from our point of view it's perfectly safe to use a newer version of restic than the one packaged for Debian stable.

I'm not sure how familiar you are with Debian's packaging guidelines. In shorty, once a distribution is released as "stable", there's no way to update it to a newer version (short of exceptional circumstances). The "backports" repository can optionally be enabled, but each package contained therein must be manually packaged for Debian stable. For restic, that hasn't been done by anybody yet.

While I have been a Debian maintainer once, I'm not part of Debian any more and I don't have any control over the Debian packages for restic.

Since restic is written in Go, it compiles to a statically linked binary which does not have any runtime dependencies, so it's easy to build restic somewhere (even cross-compilation is easy) and then just copy the binary to the server. It'll just work, which is one of the greater aspects of Go.

> I'm curious, based on the documentation encouraging users to try the testing and unstable Debian distributions, if you (@fd0) have any control over the packaged version for stable.

I don't understand, how is control over the packaged versions relate to what we recommend?

We (as the project) encourage our users to run the latest version of restic, similar to most other projects, because it contains many bug fixes and improvements which aren't present in the old version packaged with Debian stable.

> Stretch is a relatively new release, and the fact that the packaged version of Restic is 2 years old (v0.3.3, Jan. '18) is mildly alarming. That might be a tangent.

This is just how Debian works. The software is "stable", which implies that nothing changes. :)

Stretch was released in June 2017, the package freeze is usually 4-6 months earlier, which matches with the release date of restic 0.3.3 on 2017-01-08.

Perhaps this is just a misunderstanding how Debian works? ;)

**Comment by tkphd** [comment]
> Perhaps this is just a misunderstanding how Debian works? ;)

Perhaps it is. My understanding is that *Stable* does not imply unchanging versions, but rather that changes are guaranteed (as much as possible) not to break the rest of the system. There have been several minor releases since June 2017, and my belief is that updates to Restic could have accompanied some of them.

> I don't understand, how is control over the packaged versions relate to what we recommend?

If you did have some control over packaging Restic for *Stable*, then an updated version that fixed this bug (and perhaps a few others closed since June 2017) might be in place.

I've been using Debian for a few years, and yes, the pace of package updates is rather slow due to its philosophy. I have not attempted to maintain a package for Debian myself, so I'm not intimately familiar with the process, but there are mechanisms in place to update its components.

**Comment by fd0** [comment]
> My understanding is that Stable does not imply unchanging versions, but rather that changes are guaranteed (as much as possible) not to break the rest of the system.

That's not the case. Apart from security updates, Debian tries to keep all packages at the same version for the duration the release is supported. There are mechanisms to update packages without security incidents, but that needs one of the reasons outlined here:

https://lists.debian.org/debian-devel-announce/2011/03/msg00010.html

Once enough of such changes have accumulated, a new point release is made which contains these packages as well as all security updates which have happened in the past. All other packages are not updated, not even in a point release.

**Comment by tkphd** [comment]
That's good info, @fd0.
My take-away here is that Restic moves too fast for the Debian Stable philosophy, and should probably be installed as a backport or from source directly.
