### ISSUE TITLE
Add environment variable $RESTIC_EXCLUDE_FILE

### ISSUE THREAD

**Issue by rnkn** [restic/restic#2245]
Output of `restic version`
--------------------------
~~~
restic 0.9.4 compiled with go1.11.4 on darwin/amd64
~~~

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Please add a `RESTIC_EXCLUDE_FILE` environment variable. This would save having to enter it with each backup.

What are you trying to do?
--------------------------

Exclude git repository data and OS generated files.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes, I love restic. I use it as my primary off-site backup tool.

**Comment by rawtaz** [comment]
@rnkn If you are concerned about having to type that stuff out, why don't you simply make an alias or a simple wrapper script that includes all the stuff you have to type out to run restic?

Thing is, if we're going to have this environment variable, what about all the other exclude variants? One for each of them too? It can become messy, and you can bet that if one user needs this one (that you are suggesting), another user needs another variable. It never ends once you go down that rabbit hole :) In general, better to use wrappers.

**Comment by rnkn** [comment]
@rawtaz while I currently use a wrapper script, I'm surprised you'd suggest that a wrapper script is  neater than or preferable to a program being configurable via environment variables.

I don't really see that the conclusion of messiness follows from the premise of a program having more or even all of its configuration exposed to environment variables. Rather, I'd consider this to be the clean way, and I'm not alone in this assessment (https://12factor.net/config). It's not uncommon for a program to treat every command line flag as interchangeable with a prefixed environment variable (e.g. ledger-cli).

It could be argued that the messiness of a program is directly proportional to the number of wrapper scripts users require to run it, and judging from https://forum.restic.net/search?q=wrapper I think restic could benefit here!

**Comment by dimejo** [comment]
I'm wondering if all of this feature requests would become obsolete once a configuaration file (#16) is added to restic.

**Comment by rnkn** [comment]
@dimejo probably!

**Comment by MichaelEischer** [comment]
restic currently only has environment variables for option which affect more than one command. The discussion whether we want command-specific environment variables should happen in #1233.
