### ISSUE TITLE
restic dump handles root level files incorrectly

### ISSUE THREAD

**Issue by cfbao** [restic/restic#2254]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on windows/amd64

How did you run restic exactly?
-------------------------------
Prepare a test data directory, and back it up so that
```
>>> restic ls af55bc75
repository c96b5ed2 opened successfully, password is correct
snapshot af55bc75 of [C:\<...>\restic-test\data] filtered by [] at 2019-04-24 13:31:03.9490076 -0400 EDT):
/abc
/abc/0
/abc/1
/abc/2
/abc/3
/random0
/random1
/random2
```
Then try dumping one file in the root folder
```
>>> restic dump af55bc75 /random0 > dump
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local filesystem

Expected behavior
-----------------
`dump = /random0`

Actual behavior
---------------
`dump` is a tarball of `/abc` including all files in it, except the directory name "abc" is replaced with "random0".

More generally, anytime when the `file` argument to `dump` is of the form `slash + one name`, it always dumps the first node in the snapshot, whatever it is.

Steps to reproduce the behavior
-------------------------------
Described above.

Do you have any idea what may have caused this?
-----------------------------------------------
Probably this:
https://github.com/restic/restic/blob/fad9f65c65b1dc426bd00c962beb68834289c37c/cmd/restic/cmd_dump.go#L60-L62

Do you have an idea how to solve the issue?
-------------------------------------------
return `{d, f}` when `d == "/"` in `splitPath`.

Did restic help you or made you happy in any way?
-------------------------------------------------
Everyday.

**Comment by fd0** [comment]
Thanks for the report! @Kidswiss can you please take a look?

**Comment by Kidswiss** [comment]
Sure, I'll have a look at that, thanks for reporting the bug.

**Comment by Kidswiss** [comment]
While debugging this I also found that if `/` contains multiple nodes that only the first one is processed. That's partly the root cause for this bug, too.

I decided to revert `splitPath` back to the original form before the tar feature as that will avoid any wrong splittings.

Instead I handle the case `/` completely different as we don't really need to go through the `printFromTree` magic to handle that one as it is always a folder.

Here are the edge cases I tested:

Given structure:
```➜ tree /
/
├── another
│   ├── a
│   ├── b
│   └── c
├── test
└── test2
    ├── 2
    ├── 3
    ├── a
    ├── b
    └── c
```

Case 1, dumping the file `test` containing the string `test`:
```➜ go build && ./restic dump latest /test      
repository 51cd4118 opened successfully, password is correct
test
``` 

Case 2, dumping the whole `/`:
```➜ go build && ./restic dump latest / | gtar tv
gtar: Removing leading `/' from member names
drwxr-xr-x 0/0               0 2019-04-25 09:42 /another
-rw-r--r-- 0/0               0 2019-04-25 09:42 /another/a
-rw-r--r-- 0/0               0 2019-04-25 09:42 /another/b
-rw-r--r-- 0/0               0 2019-04-25 09:42 /another/c
-rw-r--r-- 0/0               5 2019-04-25 09:31 /test
drwxrwxrwx 0/0               0 2019-04-25 13:58 /test2
-rwxrwxrwx 0/0               5 2019-04-25 13:59 /test2/2
-rwxrwxrwx 0/0               5 2019-04-25 13:59 /test2/3
-rwxrwxrwx 0/0               5 2019-04-25 13:59 /test2/a
-rw-rw-r-- 1000/1000         5 2019-04-25 13:59 /test2/b
-rw-rw-r-- 1000/1000         5 2019-04-25 13:59 /test2/c
```
(the UID/GUID weirdness comes from my hacky test setup, please ignore)

Case 3, dumping one subfolder:
```➜ go build && ./restic dump latest /test2 | gtar tv
gtar: Removing leading `/' from member names
drwxrwxrwx 0/0               0 2019-04-25 13:58 /test2
-rwxrwxrwx 0/0               5 2019-04-25 13:59 /test2/2
-rwxrwxrwx 0/0               5 2019-04-25 13:59 /test2/3
-rwxrwxrwx 0/0               5 2019-04-25 13:59 /test2/a
-rw-rw-r-- 1000/1000         5 2019-04-25 13:59 /test2/b
-rw-rw-r-- 1000/1000         5 2019-04-25 13:59 /test2/c
```

Case 4, dumping a file in a subfolder (containing the string `asdf`):
```➜ go build && ./restic dump latest /test2/3 
repository 51cd4118 opened successfully, password is correct
asdf
```

@fd0 Are you aware of any other constellations that could cause these kinds of issues? I wasn't aware that the `/` tree could contain multiple nodes and that the Windows version does that weird substitution thing.

**Comment by fd0** [comment]
No other test cases that I know of, but the code could use a bit of cleaning ;)

**Comment by hoelzro** [comment]
Hello! I came across the multiple node bug that @Kidswiss mentioned in https://github.com/restic/restic/issues/2254#issuecomment-486790838 - should I file a separate issue?

**Comment by Kidswiss** [comment]
Hi @hoelzro 

Thanks for mentioning it! I'm currently working on solving (hopefully) all these bugs in this PR: https://github.com/restic/restic/pull/2255. The fixes should already work, I'm currently trying to implement some automated tests to cover these cases.

Maybe you could give the branch in the PR a try and see if it fixes your issues?

Thanks

**Comment by hoelzro** [comment]
@Kidswiss I just tried out your branch and it does indeed fix my issue - thanks!

**Comment by hoelzro** [comment]
@Kidswiss Hello again!  Just curious - how is this fix coming along?  I have a workaround using `restic-restore`, but I'd really like to be able to `restic-dump` again!

**Comment by Kidswiss** [comment]
@hoelzro 

Due to Corona lockdowns I had some time to really clean up the merge request and ping the maintainers again for a review. Let's see. I'd really like to get this into the next version of Restic.

**Comment by hoelzro** [comment]
Ok, thanks for the update @Kidswiss!
