### ISSUE TITLE
semver ?

### ISSUE THREAD

**Issue by danielb2** [restic/restic#2258]
Any thoughts on following [semver](https://semver.org/) ?  seems restic should be 1.x.x by now.

**Comment by fd0** [comment]
Restic follows semantic versioning, see https://restic.readthedocs.io/en/latest/090_participating.html#compatibility

**Comment by danielb2** [comment]
@fd0   See https://semver.org/#spec-item-5

**Comment by mholt** [comment]
That's correct. I believe it's intentional that restic is not 1.0 yet.

**Comment by danielb2** [comment]
So basically restic is not production ready and is considered unstable ?

**Comment by fd0** [comment]
No. We just haven't released 1.0.0 yet. Take it or leave it :)

**Comment by danielb2** [comment]
All I will say then, is that if it's not 1.0.0+ after being stable and production ready, is that semver is _not_ followed
