### ISSUE TITLE
User Interface: Ignoring files/dirs for backup and restore?

### ISSUE THREAD

**Issue by fd0** [restic/restic#226]
I'd like to propose a user interface for selecting and ignoring files to backup and restore (this connects to #86):

Add `--exclude` and `--include` to `backup` and `restore`, both parameters can be added multiple times and each specifies a pattern.
- If neither `--exclude` nor `--include` is specified, all files are backed up or restored.
- If only `--include` is specified (at least once), only the items that match the given pattern are backed up or restored.
- If only `--exclude` is specified (at least once), all items except those that match the given pattern are backed up or restored.
- If both `--exclude` and `--include` are specified, only those items are backed up that either
  - don't match any exclude pattern
  - match an exclude pattern and at least one include pattern

As for the pattern, I'd like to implement something that is easy to use. Some examples:
- `/proc` matches all items below `/proc`, e.g. `/proc/kcore`
- `foo/*` matches all items in a subdirectory of a directory called `foo`, e.g. `/home/user/foo/test.txt`
- `foo/**/bar*/*.c` matches all items with the extension `.c` in a directory whose name begins with `bar` that somewhere has a parent directory called `foo`.

So, the rules are roughly:
- If the pattern starts with a slash, the following name is meant absolute
- If the pattern matches a directory, it matches all subdirs/items below, e.g. `/proc` is the same as `/proc/*`
- Similar to shell globbing, `*` matches everything

Usage examples:
- Backup everything except `/proc`,`/sys` and all vim swap files: `restic backup --exclude /proc --exclude /sys --exclude "*.swp" /`
- Backup only c source code files ignoring everything else: `restic backup --include "*.c" /home/user`
- Backup the user's home directory, excluding everything except c source code from the directory `work`: `restic backup --exclude /home/user/work --include "*.c" /home/user`

I think this can be implemented fairly easy by using `filepath.Match`.

What do you think about this approach? Are you aware of any use cases that aren't covered?

@restic/devs, @ceh, @rubenv, @howeyc, @rakoo

connects to #223 #161 #86

**Comment by fd0** [comment]
Anyone? You can also just leave a :+1:, then I'll go ahead and implemented it so it can be tested...

**Comment by rubenv** [comment]
Makes total sense. Feels like the {{.gitignore}} format, which works really well.

I'd definitely also support a file format like rsync (e.g. `--exclude-from`), as these excludes typically tend to grow in numbers.

**Comment by fd0** [comment]
Sure, that'll be added afterwards, and is easy to do once the general functionality is there.

**Comment by howeyc** [comment]
LGTM :+1:

**Comment by rawtaz** [comment]
I think this sounds very good, especially as a starting point.

I'd like to propose that aside from `*` the globbing/patterns also handle `?` and `[]`, such that `?` matches any single character, and `[]` is the usual character class style of matching (preferrably just like they work in the shell, as I guess that makes more sense than making it work like in PREG). Examples of the latter could be `[a-z]`, `[a-zA-Z0-9]`.

An example of use case is when I tried to make restic back up all my `~/.*` earlier. It ended up including `.` and `..` in that match, so it effectively tried to back up `~` instead of just the dot files under `~`. I fixed that for now by changing the pattern to `.[a-zA-Z0-9]*`.

One question though; How can non-english characters (such as Swedish å, ä and ö) and other special characters be defined in the pattern?

**Comment by rubenv** [comment]
@rawtaz Wouldn't the proper fix here be that `.` and `..` should never be matched? A bunch of regexes might make things needlessly complex / slow.

**Comment by rawtaz** [comment]
@rubenv I agree. Was thinking of making a separate issue of that. But I still think the ? and [] should be supported :) This is standard globbing in the shell AFAIK.

**Comment by fd0** [comment]
If we implement this by using `filepath.Match`, it will be automatically supported, see http://godoc.org/path/filepath#Match

Regarding the example from @rawtaz above: `~/.*` is expanded by the shell and restic is called with a list of items to back up, which (depending on the shell) includes `.` and `..`. This is clearly out of scope. Compare `echo ~/.*` for `zsh` and `bash`, the former doesn't include `.` and `..`, the latter does.

**Comment by rawtaz** [comment]
@fd0 Yeah. I think . and .. should be excluded automatically. If one want to reference what those reference, one would use another pattern to target those folders.

**Comment by fd0** [comment]
@rawtaz I disagree, restic should do as it is told, so `restic backup .` should create a backup of the current directory and not try to be smarter as the user by filtering `.` as an argument. I'm not so sure about filtering `..`, I think this is used only seldomly.

Bash can be configured to include items starting with a dot in the regular expansion of `*` by setting an option, see http://unix.stackexchange.com/questions/1168/how-to-glob-every-hidden-file-except-current-and-parent-directory

**Comment by rawtaz** [comment]
Well I guess I should/could use `.?*` instead of `.*`. Fair enough.

**Comment by fd0** [comment]
> Well I guess I should/could use .?* instead of .*. Fair enough.

That's no solution, it will still expand to `..`, better set the bash option (see the stackoverflow link) and use `*` instead of `.*`.

**Comment by rawtaz** [comment]
Yes, understood. I prefer solutions that are not dependant on specifics of the shell such as globbing settings. I'd personally change the patterns instead of that option.

**Comment by fw42** [comment]
just use zsh and we can all be happy, ok?

**Comment by fd0** [comment]
For the record, a pattern that works both in bash and zsh is `.[^.]*`.

**Comment by rakoo** [comment]
:+1: for this, it is similar enough to other softwares to be easily understandable !

**Comment by fd0** [comment]
While implementing this I came around an interesting thing I didn't foresee: When both `--exclude` and `--include` patterns are specified, all trees that are normally excluded need to be walked to find items that may again be included (it's obviously no problem if only one of `--include` and `--exclude` is specified).

Is this something we should address? Or just leave it in (and document this behavior)? Or make `--include` and `--exclude` mutually exclusive?

**Comment by rubenv** [comment]
What does rsync do in those cases?

**Comment by fd0** [comment]
After a bit of experimentation I think that rsync discards files/dirs once they match an exclude rule, I could not bring rsync to include a file that was matched by a broader exclude rule. With `strace` I can see that rsync doesn't even try to open excluded directories.

**Comment by rawtaz** [comment]
IMO The point of both exclude and include isnt to speed up scanning, but to make the backup set contain only what one wants. So i think its fine to scan it all to find things that are to be included even though theyre coverred by a "wider" exclude.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Från: Alexander NeumannSkickat: tisdagen den 14:e juli 2015 08:50Till: restic/resticSvara till: restic/resticKopia: rawtazÄmne: Re: [restic] User Interface: Ignoring files/dirs for backup and restore? (#226)While implementing this I came around an interesting thing I didn't foresee: When both --exclude and --include patterns are specified, all trees that are normally excluded need to be walked to find items that may again be included (it's obviously no problem if only one of --include and --exclude is specified).

Is this something we should address? Or just leave it in (and document this behavior)? Or make --include and --exclude mutually exclusive?

—Reply to this email directly or view it on GitHub.

**Comment by fd0** [comment]
I've had a long phone call with @scoddy about this and we've decided to do the following:
 * For the first release, only allow `--exclude` for backup and restore, that should cover most use cases already
 * Create a second issue that allows mixing `--exclude` and `--include`, tackle that one later

**Comment by frou** [comment]
I can imagine a flag which instructs restic to recognise .gitignore files and derive its exclusions from them.  Would that be a fundamentally bad idea?

**Comment by fd0** [comment]
I'm closing this issue, as it is already resolved (or superseded by #233).

**Comment by fd0** [comment]
Ah, it was already closed, hm.
