### ISSUE TITLE
restic should sanitize filenames in output

### ISSUE THREAD

**Issue by julianbrost** [restic/restic#2260]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on linux/amd64

How did you run restic exactly?
-------------------------------
```
$ truncate -s 1M $'x\e[31m\nred\nis\nbeautiful\nand\nnewlines\nare\nannoying\n'
$ restic -r repo init
$ restic -r repo backup x*
$ restic -r repo ls latest
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
not relevant

Expected behavior
-----------------
Output not messing up the terminal.

Actual behavior
---------------
I got the following output in the terminal with parts of it being red due to the escape sequence included in the filename:
```
$ restic -r repo backup x*                                                     
repository 5d1e95b3 opened successfully, password is correct
[0:00] 1 files 1024.000 KiB, total 1 files 1024.000 KiB, 0 errors
/x
red
is
beautiful
and
newlines

[0:00] 1 files 1024.000 KiB, total 1 files 1024.000 KiB, 0 errors
/x
red
is
beautiful
and
newlines
Files:           1 new,     0 changed,     0 unmodified
[0:00] 1 files 1024.000 KiB, total 1 files 1024.000 KiB, 0 errors
/x
red
is
beautiful
and
newlines
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 512.500 KiB

processed 1 files, 1024.000 KiB in 0:00
snapshot 0e0b6872 saved
$ restic -r repo ls latest
repository 5d1e95b3 opened successfully, password is correct
snapshot 0e0b6872 of [/tmp/tmp.XgxPfBNlHs/x
red
is
beautiful
and
newlines
are
annoying
] filtered by [] at 2019-04-30 23:45:43.594055711 +0200 CEST):
/x
red
is
beautiful
and
newlines
are
annoying


```

Steps to reproduce the behavior
-------------------------------
See "How did you run restic exactly?"

Do you have any idea what may have caused this?
-----------------------------------------------
restic outputs filenames without any kind of sanitization so any included escape sequences are interpreted by the terminal and special characters like `\n` can mess up the output.

Do you have an idea how to solve the issue?
-------------------------------------------
Sanitize filenames when outputting them to a terminal.

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes, it's a pleasure to use, especially when compared to some enterprise™ backup "solutions".

**Comment by fd0** [comment]
Oh, good point! This should be something our terminal abstraction should handle. Thanks!
