### ISSUE TITLE
Bug on 32 bit version

### ISSUE THREAD

**Issue by tnatanael** [restic/restic#2262]
Hy gys i'm getting this error on restic 9.5 x86  running on a 32bit Windows XP machine...

I can say that this error only ocurs in the 9.5 version, the 9.4 appears to be working good!

Seems like a simple kernel resource (syscall) not available...

 ExitCode: 2

panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: NÃ£o foi possÃ­vel encontrar o procedimento especificado.goroutine 1 [running]:syscall.(*LazyProc).mustFind(0x11845a00)	/usr/local/go/src/syscall/dll_windows.go:311 +0x42syscall.(*LazyProc).Addr(0x11845a00, 0x119fe1c0)	/usr/local/go/src/syscall/dll_windows.go:318 +0x21internal/syscall/windows.GetFileInformationByHandleEx(0xf70, 0x9, 0x11a2dd50, 0x8, 0x3, 0x11828048)	/usr/local/go/src/internal/syscall/windows/zsyscall_windows.go:353 +0x27os.newFileStatFromGetFileInformationByHandle(0x118de900, 0x5b, 0xf70, 0x0, 0x57, 0x0)	/usr/local/go/src/os/types_windows.go:52 +0x135os.(*File).Stat(0x11806c68, 0x118de540, 0x57, 0x0, 0x0)	/usr/local/go/src/os/stat_windows.go:55 +0x133github.com/restic/restic/internal/archiver.(*Archiver).Save(0x119eb630, 0xd68a80, 0x118b3540, 0x118de5a0, 0x57, 0x118de540, 0x57, 0x0, 0x118de5a0, 0x57, ...)	/restic/internal/archiver/archiver.go:366 +0x3a3github.com/restic/restic/internal/archiver.(*Archiver).SaveDir(0x119eb630, 0xd68a80, 0x118b3540, 0x1181ffc0, 0x40, 0xd6c300, 0x1184f4a0, 0x1181fe40, 0x40, 0x0, ...)	/restic/internal/archiver/archiver.go:236 +0x34fgithub.com/restic/restic/internal/archiver.(*Archiver).Save(0x119eb630, 0xd68a80, 0x118b3540, 0x1181ffc0, 0x40, 0x1181fe40, 0x40, 0x0, 0x1181ffc0, 0x40, ...)	/restic/internal/archiver/archiver.go:413 +0xbcbgithub.com/restic/restic/internal/archiver.(*Archiver).SaveDir(0x119eb630, 0xd68a80, 0x118b3540, 0x1181f680, 0x32, 0xd6c300, 0x1184ec60, 0x1181f640, 0x32, 0x0, ...)	/restic/internal/archiver/archiver.go:236 +0x34fgithub.com/restic/restic/internal/archiver.(*Archiver).Save(0x119eb630, 0xd68a80, 0x118b3540, 0x1181f680, 0x32, 0x1181f640, 0x32, 0x0, 0x1181f680, 0x32, ...)	/restic/internal/archiver/archiver.go:413 +0xbcbgithub.com/restic/restic/internal/archiver.(*Archiver).SaveDir(0x119eb630, 0xd68a80, 0x118b3540, 0x118227e0, 0x26, 0xd6c300, 0x1184eba0, 0x118227b0, 0x26, 0x0, ...)	/restic/internal/archiver/archiver.go:236 +0x34fgithub.com/restic/restic/internal/archiver.(*Archiver).Save(0x119eb630, 0xd68a80, 0x118b3540, 0x118227e0, 0x26, 0x118227b0, 0x26, 0x0, 0x118227e0, 0x26, ...)	/restic/internal/archiver/archiver.go:413 +0xbcbgithub.com/restic/restic/internal/archiver.(*Archiver).SaveDir(0x119eb630, 0xd68a80, 0x118b3540, 0x11821440, 0x1f, 0xd6c300, 0x1184e900, 0x118202c0, 0x1f, 0x0, ...)	/restic/internal/archiver/archiver.go:236 +0x34fgithub.com/restic/restic/internal/archiver.(*Archiver).Save(0x119eb630, 0xd68a80, 0x118b3540, 0x11821440, 0x1f, 0x118202c0, 0x1f, 0x0, 0x11821440, 0x1f, ...)	/restic/internal/archiver/archiver.go:413 +0xbcbgithub.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0x119eb630, 0xd68a80, 0x118b3540, 0x11821420, 0x18, 0x118b38e0, 0x0, 0x3fff, 0x4099c5, 0x11806890)	/restic/internal/archiver/archiver.go:517 +0x48agithub.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0x119eb630, 0xd68a80, 0x118b3540, 0x1182ec9a, 0x2, 0x118b38c0, 0x0, 0x0, 0x1182ec50, 0x499e24)	/restic/internal/archiver/archiver.go:545 +0x819github.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0x119eb630, 0xd68a80, 0x118b3540, 0xc1eed2, 0x1, 0x118b2f20, 0x0, 0x0, 0x0, 0x0)	/restic/internal/archiver/archiver.go:545 +0x819github.com/restic/restic/internal/archiver.(*Archiver).Snapshot.func1(0x119eb630, 0xd68a80, 0x118b3540, 0x118b2f20, 0x0, 0x0, 0x0, 0x119baa80, 0xd, 0x0, ...)	/restic/internal/archiver/archiver.go:775 +0xb9github.com/restic/restic/internal/archiver.(*Archiver).Snapshot(0x119eb630, 0xd68a80, 0x119d11e0, 0x119ce238, 0x1, 0x1, 0x0, 0x0, 0x0, 0x119baa80, ...)	/restic/internal/archiver/archiver.go:785 +0x1a3main.runBackup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)	/restic/cmd/restic/cmd_backup.go:589 +0xd3cmain.glob..func2(0x12fac00, 0x119bce80, 0x1, 0x8, 0x0, 0x0)	/restic/cmd/restic/cmd_backup.go:62 +0x1b5github.com/spf13/cobra.(*Command).execute(0x12fac00, 0x1184fd40, 0x8, 0xc, 0x12fac00, 0x1184fd40)	/restic/vendor/github.com/spf13/cobra/command.go:762 +0x337github.com/spf13/cobra.(*Command).ExecuteC(0x12fb600, 0x8, 0x119ce1e0, 0x11805400)	/restic/vendor/github.com/spf13/cobra/command.go:852 +0x244github.com/spf13/cobra.(*Command).Execute(...)	/restic/vendor/github.com/spf13/cobra/command.go:800main.main()	/restic/cmd/restic/main.go:86 +0x7b

**Comment by fd0** [comment]
Hey, thanks for the report. Windows XP is not supported by the [Go runtime](https://github.com/golang/go/wiki/MinimumRequirements#Windows). We (as a project) don't have the resources to support it, sorry about that.

I'm closing this report as there's nothing we can do. Please feel free to add further comments. Thanks!

**Comment by fd0** [comment]
If 0.9.4 worked (which was built with Go 1.11) you could try building restic 0.9.5 yourself with Go 1.11, then it may work. The limitation is the in the Go runtime, it's not even in our code. If you try that, please report back!

**Comment by tnatanael** [comment]
Maybe a simple error massage error can be added in the code for the event of not supported platform?

I'll try to do a PR
