### ISSUE TITLE
restic json output invalid

### ISSUE THREAD

**Issue by mpetrazzo** [restic/restic#2281]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.12.1 on linux/amd64

How did you run restic exactly?
-------------------------------
restic -r s3:http://minioip:9000/bucket --json find * -s id | jq .

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
s3

Expected behavior
-----------------
jq read restic json output correctly

Actual behavior
---------------
jq return me an error:
parse error: Invalid numeric literal at line 1, column 657818146

Steps to reproduce the behavior
-------------------------------
On windows system, create a file called randomfilename.%202018 and after run restic backup
After the backup, run find command and export the output in json format. You'll see that it's malformed:
[cut]
"path":"/path/randomfilename.%!"(MISSING),"permissions":"-rw-rw-rw-",...
[cut]

Do you have any idea what may have caused this?
-----------------------------------------------
no

Do you have an idea how to solve the issue?
-------------------------------------------
no

Did restic help you or made you happy in any way?
-------------------------------------------------
tooooo much!
thanks for this very useful tool!

**Comment by mholt** [comment]
Probably we are using `Printf` when we should be using `Println` instead.
