### ISSUE TITLE
repository is already locked by PID xxxx

### ISSUE THREAD

**Issue by makedevelop** [restic/restic#2282]
Output of `restic version`
--------------------------
restic 0.3.3
compiled with go1.7.4 on linux/amd64

How did you run restic exactly?
-------------------------------
RESTIC_REPOSITORY=rest:http://user:pass@192.168.4.5:8000/restic-repo-name
RESTIC_PASSWORD=pass
export RESTIC_PASSWORD
export RESTIC_REPOSITORY
restic backup /srv/samba -q

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local debian server with restic docker and rest

Expected behavior
-----------------
Normal Backup

Actual behavior
---------------
repository is already locked by PID xxxx

Steps to reproduce the behavior
-------------------------------
Kill prune process before finish
the unlock command is no efective

Do you have any idea what may have caused this?
-----------------------------------------------
Yes, kill restic prune process

Do you have an idea how to solve the issue?
-------------------------------------------
Where restic store the locks in local computer to clear it?

Did restic help you or made you happy in any way?
-------------------------------------------------
restic has simplified my hundreds of backups and gives me incredible confidence

**Comment by fgma** [comment]
Restic locks are stored inside the `locks` directory in the repository. You can use `restic unlock` to unlock a repository or delete the files in the `locks` directory inside the repository.

BTW: I guess you are running 0.3.3 because you are using debian stable. You can manually install the deb package from testing or unstable because the restic binary has the same dependencies: https://packages.debian.org/search?keywords=restic&searchon=names&suite=all&section=all

**Comment by makedevelop** [comment]
Thanks fgma but unlock is no efective in this case. I think that restic store too a lock in client side...

**Comment by dimejo** [comment]
restic doesn't store a lock on the client. Please check the file and directory permissions on your respository.

**Comment by makedevelop** [comment]
Ok, i have looking for lock on other repository, excuse me for trouble.

**Comment by makedevelop** [comment]
I close this issue, thanks to everyone

**Comment by MichaelEischer** [comment]
@makedevelop Did you intend to reopen this issue?
