### ISSUE TITLE
`check` slows down quadratically with number of snapshots

### ISSUE THREAD

**Issue by BenWiederhake** [restic/restic#2284]
3 seconds for every 200 snapshots.  At 72 snapshots per day (3 per hour), this makes `restic check` painful to run.

Output of `restic version`
--------------------------

`restic 0.9.5 compiled with go1.12.4 on linux/amd64`

How did you run restic exactly?
-------------------------------

I make backups every 20 minutes, so 500 snapshots per week.  Please consider the following numbers in this light.

I'll skip my actual setup, and dive right into the:

Steps to reproduce the behavior
-------------------------------

Call `backup` and `check` somewhat often.

[This MRE repo](https://github.com/BenWiederhake/restic-slow) does everything, and collects the data in a nice, somewhat usable format.

Specific setup:
- `RESTIC_REPOSITORY=destdir/ RESTIC_PASSWORD=1234 restic backup fromdir`
- `RESTIC_REPOSITORY=destdir/ RESTIC_PASSWORD=1234 restic check`
- Few changes to the repository, just like my actual home folder doesn't change completely all the time.  The MRE makes no changes at all.  However, this is *unrelated* to #662.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

sftp for my actual setup, and "filesystem" for the MRE.

This should be irrelevant, as I'm complaining about an excessive CPU load.

Expected behavior
-----------------

With more snapshots, `restic check` has more to do, I get it.  But I expect something along the lines of 1 ms per "empty" snapshot.

Actual behavior
---------------

It looks like each snapshots makes `check` slower by roughly 15 ms in terms of actual CPU usage as reported by `/usr/bin/time`.  Here are the measurements from the MRE:

![chart that shows quadratic growth, x axis is the number of snapshot, y axis is time](https://user-images.githubusercontent.com/2690845/58382236-26a44f80-7fc8-11e9-9c4f-d5ea34a44cbc.png)

Note that the quadratic fit is so perfect you can barely see it.  The first few checks take virtually no time, and then it blows up into tens of seconds of high CPU load.  This can be neither explained by latency, nor number of files ("hundreds" is not enough for that kind of slowdown).

I'd like to mention again: You can recreate this with the [MRE script](https://github.com/BenWiederhake/restic-slow).

Do you have any idea what may have caused this?
-----------------------------------------------

My initial guess was that there is an "accidentally quadratic" bug, so I was pretty surprised to see linear growth on the graph.  So it's probably not that.

My current guess is that snapshot parsing/scanning is unreasonably slow.  Maybe some computation has to run several times per snapshot, whereas one run would suffice?

On the other hand, I cannot reproduce this using "fs" as backend.  So the issue could be related to sftp.  Or maybe it's quadratically many IO operations, and with my harddrive it's so fast the latency doesn't matter anymore.

Do you have an idea how to solve the issue?
-------------------------------------------

No idea, but it seems to be between `check snapshots, trees and blobs` and `no errors were found`.  Maybe I'll sprinkle some `println`s to bisect *when* the issue happens.

"Snapshot packs" (#523) probably don't help, but it depends on what the actual issue is.

Did restic help you or made you happy in any way?
-------------------------------------------------

Absolutely!  I'm about to switch away from my old backup system, which needed `root` to restore anything, and uses system-wide configuration.  With restic, both are better! :)

**Comment by dimejo** [comment]
> 3 seconds for every 200 snapshots. At 72 snapshots per day (3 per hour), this makes restic check painful to run.

> I make backups every 20 minutes, so 500 snapshots per week. Please consider the following numbers in this light.

Even if you would keep all your snapshots for half a year this would only add ~3min to `restic check`. This is not as dramatic as you make it sound compared to the remaining runtime of check (assuming a repository > 50GB).

IMHO, there are parts of restic where performance tuning will have a much higher impact.

Nevertheless I agree that fetching snapshot information could be impoved. It takes ~30sec for me to perform `restic snapshots` for ~350 snapshots on a S3 backend with an outdated cache.

**Comment by BenWiederhake** [comment]
I'm using a repository of roughly 5 GiB.  Also, the MRE triggers this bug with 200 MiB, and notice how during the first few snapshots it takes less than a second.  I don't see how you find **3 minutes** a reasonable time if it apparently ran much faster beforehand.

This issue is also not about an outdated cache, but rather something that takes quadratic time when it should be linear.  (Or ideally constant, but that's wishful thinking.)

**Comment by BenWiederhake** [comment]
I think I figured out the reason:  The command `check` eventually calls the function `(*Repository).LoadTree`, which calls `(*Repository).loadTree`, which calls `(*Repository).loadBlob`, which calls `(*MasterIndex).Lookup`, which does a **linear search on all indexes** (and calls `(*Index).Lookup` on each).  Since `check` calls `loadBlob` extremely often, it is a bad idea to walk all indexes.

To make it more explicit: After n snapshots, there are n indexes and at least n trees.  In my MRE, I whittled it down so far until there was only very few blobs left, say 3.  So there are basically n-many searches for blobs.  Each search looks in all n indexes, which means n^2 calls to `(*Index).Lookup`.

(Technically, `(*MasterIndex).Lookup` stops when it finds a result.  However, the searched-for blob is only in one specific index, so it "usually" has to search through half of all indexes to find the result.  But that's still O(n^2) expected time.)

I guess that this bug didn't get detected earlier because people run `prune` from time to time.  That's going to the manual work-around for now.

If anyone is interested in the [flamegraphs](http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html) I generated, you can find them in [the MRE repo](https://github.com/BenWiederhake/restic-slow).

I have no idea how to fix this.  I'd be happy to chat on IRC about it.  I'm @BenWi there.

**Comment by MichaelEischer** [comment]
The check slowdown can be even worse than quadratic: For every `s` Snapshots all `t` Trees of that Snapshot (even if trees are shared between snapshots) are loaded which walks through all `i` Indices. As all three variables tend to grow for larger repos, this ends up being O(n^3).

Running `prune` or `rebuild-index` helps only slightly to fix this scaling issue for large repositories. I have a 8 TB repository containing roughly 40 million files and it still has 600 index files. Before running `rebuild-index` the repository had a whopping 3600 index files which resulted in a `check` run that took approximately 7 days (aka. a full week) to complete.

A lot of that time is spent for decoding and finding each tree blob several times. I've opened a merge request #2328 that would fix that problem. (The merge request also gets rid of the LookupSize call from within LoadTree, thus reducing the Index Lookups)

Regarding the index scalability issue my suggestion would be to decouple the in-memory index structure from the packed version on disk. The `MasterIndex` could then either manage one gigantic HashMap (might cause a lot of memory overhead) or use some means to partition it based on the object IDs. Indices that are currently work-in-progress would have to be stored separately, which is probably no problem as there shouldn't be too many of them (probably just 2?).

**Comment by vext01** [comment]
I'd just like to add that `restic check` is also quite memory hungry. I'm backing up about 5GB of data. I have only a handful of snapshots and the memory consumption of `check` is 1.2GiB.

When I ran this on my server, it swapped itself to death.

**Comment by MichaelEischer** [comment]
@vext01 Your memory usage seems to be way higher than it should be. Which restic version are you using? With restic built from the current master, I see a memory consumption for `check` of 1.06GiB for a repository with 190 GB and somewhere above 1 million files. With my merge request #2328 memory consumption is down to 0.9GiB.

In case you are able to build restic yourself, please try a build with the `profile` tag, run restic with the memory profiling server enabled `--listen-profile localhost:12345` and collect a heap profile via `curl 'localhost:12345/debug/pprof/heap'`.

**Comment by MichaelEischer** [comment]
This is solved now that #2328 and #2818 are merged
