### ISSUE TITLE
Pretend to have hardlinks in mount

### ISSUE THREAD

**Issue by BenWiederhake** [restic/restic#2290]
Output of `restic version`
--------------------------

`restic 0.9.5 compiled with go1.12.4 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I request that files that are backed by the *same blobs* in the repository end up having the *same inode* in the mounted fs.  Likewise, if files have entirely *distinct blobs*, I would like to see *distinct inodes*.  I'm not sure about the behavior in between, but distinct inodes sound like a safe approach.

Actual behavior:
```
/mnt/snapshots$ LC_ALL=C sha256sum 2019-05-27T18\:54\:*/tmp/fromdir/important_file_zEumatq.txt
a2e201ddc4bafc8e0c5a8d22c7192e9ad0702a9af1c6225f36f4df7ac2ccbfb8  2019-05-27T18:54:36+02:00/tmp/fromdir/important_file_zEumatq.txt
a2e201ddc4bafc8e0c5a8d22c7192e9ad0702a9af1c6225f36f4df7ac2ccbfb8  2019-05-27T18:54:44+02:00/tmp/fromdir/important_file_zEumatq.txt
a2e201ddc4bafc8e0c5a8d22c7192e9ad0702a9af1c6225f36f4df7ac2ccbfb8  2019-05-27T18:54:51+02:00/tmp/fromdir/important_file_zEumatq.txt
a2e201ddc4bafc8e0c5a8d22c7192e9ad0702a9af1c6225f36f4df7ac2ccbfb8  2019-05-27T18:54:59+02:00/tmp/fromdir/important_file_zEumatq.txt
/mnt/snapshots$ LC_ALL=C ls -li 2019-05-27T18\:54\:*/tmp/fromdir/important_file_zEumatq.txt
11979788605512256226 -rw------- 1 user user 79 May 27 17:39 2019-05-27T18:54:36+02:00/tmp/fromdir/important_file_zEumatq.txt
 3192125267856502679 -rw------- 1 user user 79 May 27 17:39 2019-05-27T18:54:44+02:00/tmp/fromdir/important_file_zEumatq.txt
 3797808363755990842 -rw------- 1 user user 79 May 27 17:39 2019-05-27T18:54:51+02:00/tmp/fromdir/important_file_zEumatq.txt
13064527522241212731 -rw------- 1 user user 79 May 27 17:39 2019-05-27T18:54:59+02:00/tmp/fromdir/important_file_zEumatq.txt
```

Expected behavior:
```
/mnt/snapshots$ LC_ALL=C ls -li 2019-05-27T18\:54\:*/tmp/fromdir/important_file_zEumatq.txt
12345678901234567890 -rw------- 1 user user 79 May 27 17:39 2019-05-27T18:54:36+02:00/tmp/fromdir/important_file_zEumatq.txt
12345678901234567890 -rw------- 1 user user 79 May 27 17:39 2019-05-27T18:54:44+02:00/tmp/fromdir/important_file_zEumatq.txt
12345678901234567890 -rw------- 1 user user 79 May 27 17:39 2019-05-27T18:54:51+02:00/tmp/fromdir/important_file_zEumatq.txt
12345678901234567890 -rw------- 1 user user 79 May 27 17:39 2019-05-27T18:54:59+02:00/tmp/fromdir/important_file_zEumatq.txt
```

What are you trying to do?
--------------------------

`restic mount` is an excellent tool to inspect the repository.  However, the inodes within the mounted fs seem to be essentially random IDs, so further analysis would need to re-discover whether files are identical.

Specifically: With my previous backup system, I could use `du` and `baobab` (basically a graphical display of `du`) to see what's going on, what eats up backup size, and give me a good idea how quickly the repository is growing.  These two programs detect duplicates by hardlinks, so it would still work perfectly fine with `restic mount`, if unchanged files were represented as hardlinks among each other.

After reading the design document for the first time, I think a sane way to achieve this is by hashing the node information (name, type, mode, mtime, atime, ctime, uid, gid, user, inode, size, links, content) in some form.  This way, the generated inodes are impossible ("cryptographically unlikely") to clash by accident (distinct implies distinct), and matches when the files caused no actual additional data (same implies same).

What do you think of this way to get the inode numbers?

Did restic help you or made you happy in any way?
-------------------------------------------------

Absolutely!  Like I said, `restic mount` is an excellent tool to inspect the snapshots.

**Comment by MichaelEischer** [comment]
Inodes are 64-bit numbers. Simply hashing them will likely lead to collisions. Even worse: a snapshot can include files from different devices, but we cannot expose that information through fuse. So the only option left would be to fake hardlinks by reassigning inodes in some way. And that sounds like more complexity than it's worth.

**Comment by BenWiederhake** [comment]
Can't the blob ID be re-used somehow? For example, truncate the blob ID to 64 bits, and claim that to be the inode number.

**Comment by MichaelEischer** [comment]
That would tie the inode to the file content, which is very likely to result in identical inodes for files with identical content which however should not be linked together. And it won't solve the problem that for 4 billion files, the chance of an inode collision is already 50%. So just take millions of snapshots containing a million files and you'll see an inode collision.

**Comment by MichaelEischer** [comment]
Implemented by https://github.com/restic/restic/pull/4020 and https://github.com/restic/restic/pull/4255 .

The current solution isn't perfect, but should be good enough :TM: .
