### ISSUE TITLE
B2 Application Keys still not working?

### ISSUE THREAD

**Issue by rlue** [restic/restic#2293]
Output of `restic version`
--------------------------

#### on a Raspberry Pi

* `restic 0.9.5 compiled with go1.12.4 on linux/arm` (binary from GitHub)
* `restic 0.9.5 (v0.9.5-30-g5bd5db42) compiled with go1.12.5 on linux/arm` (compiled locally)

#### on an x64 laptop

* `restic 0.9.4 compiled with go1.11.5 on linux/amd64` (installed via Debian testing repositories)

How did you run restic exactly?
-------------------------------

```sh
$ export RESTIC_REPOSITORY=b2:<REDACTED>
$ export RESTIC_PASSWORD_COMMAND="pass backblaze/bucket.repo"

$ export B2_ACCOUNT_ID=<ACCOUNT_ID>
$ export B2_ACCOUNT_KEY=<MASTER_KEY>
$ restic init
created restic repository b2:<REDACTED> at <REDACTED>
$ restic backup /media/data
repository <REDACTED> opened successfully, password is correct
  signal interrupt received, cleaning up

# (tried with two sets of permissions: "readFiles,writeFiles" / "writeFiles")
$ export B2_ACCOUNT_ID=<APPLICATION_KEY_ID>
$ export B2_ACCOUNT_KEY=<APPLICATION_KEY>
$ restic init
Fatal: create repository at b2:<REDACTED> failed: NewBucket: b2_list_buckets: 401:
$ restic backup /media/data
Fatal: unable to open repo at b2:<REDACTED>: Bucket: b2_list_buckets: 401:
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze B2

Expected behavior
-----------------

I saw that support for B2 application keys was [introduced ten months ago in version 0.9.2](https://github.com/restic/restic/releases/tag/v0.9.2), following changes in the [blazer](https://github.com/kurin/blazer) library.

Based on the discussion in #1907 and the patch in #1914, I would have expected these operations to succeed, but they're failing for me. At first, I thought it was only on ARM, but then I tried it on x64 as well, and it's failing there, too!

Actual behavior
---------------

As you can see from the code sample above, it failed with the error `b2_list_buckets: 401:`, which appears to be identical to the error reported in #1907.

Steps to reproduce the behavior
-------------------------------

I'm on a Raspberry Pi 3B+, running Raspbian Stretch, and also on a ThinkPad running Debian Buster. I've tried precompiled binaries and compiling restic myself. 

```sh
$ b2 create-bucket foo  # Create a bucket
$ b2 create-key --bucket foo foo-restic writeFiles  # Create an application key
```

Then follow code examples above.

Do you have any idea what may have caused this?
-----------------------------------------------

Nope.

Do you have an idea how to solve the issue?
-------------------------------------------

Nope.

Did restic help you or made you happy in any way?
-------------------------------------------------

I've used restic before, and it's amazing! Can't wait to get it set up with application keys soon. :)

**Comment by chandwki** [comment]
I'm also having this issue on Ubuntu 18.04.2 LTS.

**Comment by fd0** [comment]
Hm, that's odd. Thanks for the report!

An application key consists of a `B2_ACCOUNT_ID` (which is longer than the master account ID) and a `B2_ACCOUNT_KEY`. A common error is using the master account ID together with an application key.

Can you please verify that both are set correctly?

**Comment by rlue** [comment]
100%, definitely using the 26-character application key ID and the 32-character application key.

Happy to provide any further debugging output, at your instruction.

**Comment by joncar** [comment]
I've been doing this successfully with restic 0.9.5 compiled with go1.12.4 on linux/amd64. I use an application key limited to a single bucket and with permissions: deleteFiles, listBuckets, listFiles, readFiles, shareFiles, writeFiles. This is the permission set that Read & Write generates in the Backblaze web UI.

**Comment by rlue** [comment]
Well this is terribly embarrassing. I filed this bug report under the faulty assumption that restic could be used with a write-only Backblaze application key.

Thanks @joncar for pointing out the obvious, and sorry @fd0 to bother you!

**Comment by fd0** [comment]
Don't worry, it's fine :) If it happened to you, other people may run into the same issue. I've changed the subject so that it's easier to find. Thanks for the feedback!

**Comment by gsauthof** [comment]
> I've been doing this successfully with restic 0.9.5 compiled with go1.12.4 on linux/amd64. I use an application key limited to a single bucket and with permissions: deleteFiles, listBuckets, listFiles, readFiles, shareFiles, writeFiles. This is the permission set that Read & Write generates in the Backblaze web UI.

Are all of these default capabilities (you grant when creating the key in the web UI) required by restic, though?

For example, does restic need `shareFiles` ? From the b2 documentation it doesn't sound like it:

> Lets the client create authorization tokens for downloading files.

Rather seems like such a token would only be required when sharing files with a third party.

Perhaps it would make sense to add the list of required capabilities to the Backblaze B2 section in the restic manual?

**Comment by gsauthof** [comment]
So I've tested this and - as expected - `restic init` and `restic backup` do work without the `shareFiles` capability.

What surprised me is that `restic init` fails without the `listBuckets` capability. I mean I don't see why restic needs to list all my buckets when the backup target is a single bucket.

Thus, the minimal set of b2 api key capabilities for restic is:

    listBuckets,listFiles,readFiles,writeFiles,deleteFiles

**Comment by rawtaz** [comment]
> What surprised me is that restic init fails without the listBuckets capability. I mean I don't see why restic needs to list all my buckets when the backup target is a single bucket.

Could this be because listing information about just one single bucket also requirest this capability?

**Comment by gsauthof** [comment]
> Could this be because listing information about just one single bucket also requires this capability?

Yes, looks like it. For example, the `b2_list_file_names` operation requires a bucket-ID and `b2_list_buckets` seems to be the only way to get it. Thus, it makes sense that the b2 go library lists the buckets when working with a single bucket, e.g.:

https://github.com/kurin/blazer/blob/3ad36f176f10c391369dd258d09ce187882f876e/b2/b2.go#L285

Even if it would add the optional `bucketName` parameter to [`b2_list_buckets`][1] that call would still need the `listBuckets` capability.

[1]: https://www.backblaze.com/b2/docs/b2_list_buckets.html
