### ISSUE TITLE
Support for Azure SAS (Shared Access Signatures)

### ISSUE THREAD

**Issue by gitgruub** [restic/restic#2295]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.2 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Currently, Restic supports authenticating with Azure Storage Account credentials, but does not support Azure SAS (shared access signatures: https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1)

SAS is important as it allows granular, time limited, per-container permissions to be used, instead of using the storage account key which gives read/write over the entire account and all resources (including all containers, tables, queues and fileshares).

Currently, with Restic requiring the use of the storage account key, any secure deployment at scale is forced to create many separate storage accounts housing single containers. This is clearly not the intended way to use Azure storage.

Moreover, storage account names are within a global namespace, and have a limited charset, meaning creating many accounts can be a problem.

SAS support was added to Duplicity with minimal changes, which may mean the same would be true with Restic:
https://bazaar.launchpad.net/~duplicity-team/duplicity/0.8-series/revision/1179#duplicity/backends/azurebackend.py

What are you trying to do?
--------------------------
Use Restic on Azure with SAS, and avoid using the Storage Account "master key", making backup containers easier to manage.

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic is great, easy to deploy and backed up by good documentation. I'm happy that this is my only significant problem so far.

**Comment by shtratos** [comment]
You can workaround this by using rclone backend:
https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone

rclone supports SAS authentication for Azure accounts and containers:
https://rclone.org/azureblob/#sas-url
