### ISSUE TITLE
Forget and prune but same number of snapshots

### ISSUE THREAD

**Issue by gizmo15** [restic/restic#2296]
Hi,

I try to make some clean on a repo with those commands :
restic forget --keep-monthly 3 -r /media/backup_storage/restic/target
restic prune -r /media/backup_storage/restic/target

But i have the same number of snapshots.
When i run the forget command, a list of snapshots but nothing else (no error).

I have one snapshot per day.
It's an Ubuntu 18.04 with restic 0.8.3.

I miss something but i don't what.

Thanks for your help.

**Comment by MichaelEischer** [comment]
@gizmo15 If you still have that problem, we'd need the output of the forget and prune command to help. My guess would be that you don't have three monthly snapshots for each host+backup paths pair. By the way, this issue looks like a usage question, which should in general be asked on the [forum](forum.restic.net/). Please close this issue if it's no longer needed.
