### ISSUE TITLE
can't use --path with ls

### ISSUE THREAD

**Issue by bbigras** [restic/restic#2299]
NixOS
bash shell

Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.1 on linux/amd64

How did you run restic exactly?
-------------------------------
`export RCLONE_CONFIG_PASS=somepass`
`restic -r rclone:onedrive:somename ls --path=/home/bbigras/something`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
onedrive with rclone

Expected behavior
-----------------
Seing the files from the last snapshot containing the specified path.

Actual behavior
---------------
I get:
```
enter password for repository:
repository <something> opened successfully, password is correct
Ignoring "", it is not a snapshot id
Ignoring filters as there are explicit snapshot ids given
```

Steps to reproduce the behavior
-------------------------------

do the steps from "How did you run restic exactly". Probably don't even need a real restic repo.

Do you have any idea what may have caused this?
-----------------------------------------------
I guess restic thinks a snapshot id was specified when it wasn't and then ignored the filter.

Do you have an idea how to solve the issue?
-------------------------------------------
no

Did restic help you or made you happy in any way?
-------------------------------------------------

restic is awesome.

**Comment by dimejo** [comment]
> restic -r rclone:onedrive:somename ls --path=/home/bbigras/something

Is this the directory that contains the restic files? Can you please check with:
`rclone lsd onedrive:somename`

**Comment by bbigras** [comment]
```
rclone lsd onedrive:somename
          -1 2019-05-24 16:13:37       159 data
          -1 2019-05-24 16:16:47         2 index
          -1 2019-05-24 16:09:21         1 keys
          -1 2019-05-24 16:12:04         0 locks
          -1 2019-05-24 16:27:16         7 snapshots
```

**Comment by dimejo** [comment]
You are right, I was able to reproduce it on 2 of my repositories (Windows & Linux). Contrary to what the help message states the `restic ls` command seems to require a `snapshotID` (or `latest`).
