### ISSUE TITLE
check with --read-data-subset behaves weirdly when t > 256

### ISSUE THREAD

**Issue by akalin** [restic/restic#2301]
Output of `restic version`
--------------------------
`restic 0.9.5 compiled with go1.12.4 on freebsd/amd64`

How did you run restic exactly?
-------------------------------
I have a few layers of scripts, but roughly:

```
export RESTIC_PASSWORD_FILE=...
export RESTIC_REPOSITORY=b2:...

SIZE=1000
for x in `seq 1 $SIZE`; do
  echo $x/$SIZE
  ./restic_0.9.5_freebsd_amd64 check --read-data-subset=$x/$SIZE
done
```

with output

```
1/1000
using temporary cache in /tmp/restic-check-cache-329094628
created new cache in /tmp/restic-check-cache-329094628
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
read group #1 of 2047 data packs (out of total 510823 packs in 1000 groups)
[23:29] 100.00%  2047 / 2047 items

duration: 23:29
no errors were found

2/1000
...

256/1000
using temporary cache in /tmp/restic-check-cache-299737614
created new cache in /tmp/restic-check-cache-299737614
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
read group #256 of 2043 data packs (out of total 510823 packs in 1000 groups)
[23:24] 100.00%  2043 / 2043 items

duration: 23:24
no errors were found

257/1000
using temporary cache in /tmp/restic-check-cache-357372670
created new cache in /tmp/restic-check-cache-357372670
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
read group #257 of 0 data packs (out of total 510823 packs in 1000 groups)
[0:00]   0 / 0 items

duration: 0:00
no errors were found
...

```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
b2

Expected behavior
-----------------

restic should have errored/warned that 256 is the effective maximum for the t value in --read-data-subset, or have it in the docs somewhere. When run with n > 256, it should perhaps have returned immediately instead of re-downloading the indexes, checking the packs, etc.

Actual behavior
---------------
When n > 256, it did a normal check, and then checked 0 data packs.

Steps to reproduce the behavior
-------------------------------
Run `restic check` with `--read-data-subset=n/t` where n, t > 256.

Do you have any idea what may have caused this?
-----------------------------------------------
From https://github.com/restic/restic/issues/2186 , it looks like `--read-data-subset` only looks at the first byte of the pack ID, so there's an effective maximum of 256 for t.

That issue is arguing for increasing the granularity to more than one byte, but this issue is more for better reporting/warning for when the effective maximum is exceeded.

Do you have an idea how to solve the issue?
-------------------------------------------
Warnings/errors when n, t > 256 for ``--read-data-subset`, docs for effective maximums for those values.

Did restic help you or made you happy in any way?
-------------------------------------------------
restic is great otherwise! I've been very happy with it.

**Comment by ifedorenko** [comment]
Agree this is a bug, `check --read-data-subset` should validate parameter values and fail fast and with clear error message if values are not valid. Please open PR and I will try to find time to review and merge it (I think I have powers to merge, but not 100% sure).
