### ISSUE TITLE
Intermittent b2 errors (?) cause "pack ID does not match" errors during "restic check --read-data"

### ISSUE THREAD

**Issue by akalin** [restic/restic#2302]
Output of `restic version`
--------------------------
`restic 0.9.5 compiled with go1.12.4 on freebsd/amd64`

How did you run restic exactly?
-------------------------------
I have a few layers of scripts, but roughly:

```
export RESTIC_PASSWORD_FILE=...
export RESTIC_REPOSITORY=b2:...

SIZE=1000
for x in `seq 1 $SIZE`; do
  echo $x/$SIZE
  ./restic_0.9.5_freebsd_amd64 check --read-data-subset=$x/$SIZE
done
```

The output relevant to this issue is, e.g.:

```
18/1000
using temporary cache in /tmp/restic-check-cache-158036280
created new cache in /tmp/restic-check-cache-158036280
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
read group #18 of 2021 data packs (out of total 510823 packs in 1000 groups)
Pack ID does not match, want 11ec3b05, got f54a743e
[23:05] 100.00%  2021 / 2021 items

duration: 23:05
Fatal: repository contains errors
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
b2

Expected behavior
-----------------

restic should use check b2 full file downloads against the sha1 integrity information given by b2, retrying if necessary. This will help distinguish between transient errors and more serious errors.

Actual behavior
---------------

restic catches the transient corruption and reports "pack ID does not match".

Steps to reproduce the behavior
-------------------------------
Due to the nature of the bug, there's really no way to reproduce this. I saw it happen with 5 pack files in a 2.5TB repository, so perhaps running check against a large enough b2 repo will eventually encounter it.

Do you have any idea what may have caused this?
-----------------------------------------------

Yes, after I had manually verified that the pack files had the correct sha256 sum (using the info from https://github.com/restic/restic/issues/2191 ), I dug into the b2 backend code and noticed that the b2 library it's using (blazer) already keeps track of sha1 info returned by b2 and exposes methods to check it, but the b2 backend doesn't use it.

Do you have an idea how to solve the issue?
-------------------------------------------

Yes, I will send a PR with an initial solution.

Did restic help you or made you happy in any way?
-------------------------------------------------

restic is great otherwise! I've been very happy with it.

**Comment by ifedorenko** [comment]
There are seems to be two independent issues/ideas here: a) use b2-specific file checksum and b) retry failed checksum validation. 

As I mentioned in #2303, I am not in favour of b2-specific checksum validation as it seems redundant. 

I am on the fence about retries. On one hand I agree it makes sense to retry failed checksum validation during `restore`. On the other hand, failed checksum validation does indicate a problem somewhere, be that backend, network or local system, so it is probably useful to know about them during `check`.

**Comment by akalin** [comment]
I'm not tied to the b2-specific checksum validation. I think we do need some sort of retry on checksum failure during check (not sure if that currently happens during restore?), as it apparently can happen transiently.

My suggestion is, during checksum failure in check, print a warning with the failed checksum and retry some small number of times, and if it continues to fail treat it as it is now, as a failure. How does that sound?
