### ISSUE TITLE
hashed password in the password-file

### ISSUE THREAD

**Issue by osscombat** [restic/restic#2309]
Hi!
Maybe I missed something in the docs, but is there an option not to use the plain-text file with the password for the repo that is passed with the -p key, but to have password's MD5 hash or else to have more secure scripts?

**Comment by ProactiveServices** [comment]
The  `--password-command` switch can help you here:
`--password-command string: specify a shell command to obtain a password (
default: $RESTIC_PASSWORD_COMMAND)`

**Comment by osscombat** [comment]
Sure, thanks, I didn't though of that option! Case closed.

**Comment by xeor** [comment]
Awesome.. @osscombat , can you close the issue?

**Comment by fd0** [comment]
For the record: you could also do that with shell magic:
```
$ restic --password-file <(gpg --decrypt ~/restic-password.gpg) [...]
```

But `--password-command` also works :)
