### ISSUE TITLE
restic backup runs forever

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [restic/restic#2312]
Output of `restic version`
--------------------------
`restic 0.8.3 (v0.8.3-266-g9f5565b0) compiled with go1.10.2 on linux/amd64`

How did you run restic exactly?
-------------------------------
`$ su -c 'strace -o /home/usr/files/restic_trace_output.txt -f restic backup --exclude-file=/usr/local/etc/restic-exclude-two.txt --tag="root-backup-20" --verbose /'`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local backend on external hard drive

Expected behavior
-----------------
restic should exit when the backup size equals the scan size. restic should also locate a previous snapshot because the same directory was backed up only yesterday

Actual behavior
---------------
restic did not exit when the backed up size reached the scan size and restic did not locate a previous snapshot as it normally would when the same directory was backed up again 

Steps to reproduce the behavior
-------------------------------
1. upgrade your distro e.g. upgrade from fedora 29 to fedora 30
 2. run the command `$ su -c 'strace -o /home/usr/files/restic_trace_output.txt -f restic backup --exclude-file=/usr/local/etc/restic-exclude-two.txt --tag="root-backup-20" --verbose /'`

Note: the exclude file here is basically equivalent to the --one-file-system backup option

Do you have any idea what may have caused this?
-----------------------------------------------
- The only other time this (i.e. restic failed to use a previous (parent) snapshot) happened was when I tried backing up right after upgrading my system (in that case backing up after upgrading from fedora 28 to fedora 29), I created an #1872 for that problem . So I believe restic does not use a previous snapshot when you upgrade your system between backups.
- As for restic backup running forever I have no idea but may be somehow running restic backup (i.e. passing restic backup) as an argument to `strace` may have something to do with this however running restic backup as an argument to `strace` was recommended by @fd0 in the referenced issue so it shouldn't have caused an issue

Do you have an idea how to solve the issue?
-------------------------------------------
no

Did restic help you or made you happy in any way?
-------------------------------------------------
restic has made backing up so effortless that I'm no longer daunted at the prospect of backing up files. Now I always backup anything important

## update
So I ran `restic backup` again, this time without running `restic backup` through `strace` and `restic backup` did not run forever instead `restic backup` exited after the scanned files size was backed up which is expected

**Comment by onionjake** [comment]
@ChukwuemezieChristopherAneke Do you still see this issue if you use the latest version? (0.9.5)

**Comment by MichaelEischer** [comment]
I'm closing this issue as the archiver code has been rewritten in restic 0.9.0, reproducing with strace didn't work and we didn't get a confirmation that this is still a problem.

If the issue still exists, feel free to comment and reopen the issue.
