### ISSUE TITLE
Limit maximum file size to backup

### ISSUE THREAD

**Issue by fukawi2** [restic/restic#2313]
Output of `restic version`
--------------------------
`restic 0.9.5 compiled with go1.12.4 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Allow exclusion of files to backup based on file size. eg, a `--max-file-size` flag.

What are you trying to do?
--------------------------
I have scheduled backups of my desktop every hour to a remote repository. As a system administrator, sometimes I have very large files (40+ GB) that I'm working with temporarily, but I don't want them put into the restic repository; it takes a long time (delaying later backups), and inflates the repository size (until the relevant snapshot it pruned).

Examples of these kinds of files include ISO images, and tarball archives of business data.

These are 'random' files so the filenames and paths aren't predictable so I can't use a normal exclude flag. I can safely say anything over Xgb I don't care about for backup purposes.

At the moment I have to remember to manually stop the restic schedule until I'm finished with these files and delete them. (then I have to remember to start it again!)

Did restic help you or made you happy in any way?
-------------------------------------------------
restic is awesome. Thank-you for all your hard work.

**Comment by MichaelEischer** [comment]
This is supported since recstic 0.10.0, see #2569.
