### ISSUE TITLE
Issue with prune

### ISSUE THREAD

**Issue by killmasta93** [restic/restic#2314]
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.12.4 on linux/amd64

How did you run restic exactly?
-------------------------------
restic -r /path to repo prune

incomplete pack file (will be removed): 36b03acb232328eca8458d8bfa7df0a8c29fd08abb922d8e1a07b024cb63fca1
incomplete pack file (will be removed): 37a3c908ec7b8b06c80405f74fa6acd4179b37c97e608f699fe0ab49d9e7fd2e
incomplete pack file (will be removed): 3856948909d67a7109d1b9bf641bacdf85bb8caac617a1b2a194988622e81658
incomplete pack file (will be removed): 38c0fdcec1f9294703a3799a9b0d9b49768e23933a37008c75059bf1bdd6f8f6
incomplete pack file (will be removed): 3ba6a4ba08032478bead445034433f0f7253400345b0db44aeb9cad289e433e2
incomplete pack file (will be removed): 3cf2b2aa57b58effb7c4a67771d8d576ebc0739df76dc2c091966692980d2648
incomplete pack file (will be removed): 3e14e161808d45c2bd3b1d6f65b22b1b80c584be835757ec20de9c18afb29f0a
incomplete pack file (will be removed): 3fba2c4625e5511ac0dc3bcec3f6e30a8ba27288116ea61d17aa4bd0e968a442
incomplete pack file (will be removed): 3fea81573da080f870a8ab30b70463349b826aa97f61186d8750d3225c7f30ae
incomplete pack file (will be removed): 40470f3dcb2f7e484313cf16c8a6a3a7a046e202e929cda4014e213abef248b7
incomplete pack file (will be removed): 405f6af708360647aebed6678284c73d031015fb5d7839ea683f2f5f19117f76
incomplete pack file (will be removed): 40c8bf9a65cbb75fce27f56829380a38083e6f1a55171b728d33e52f3f97f52a
incomplete pack file (will be removed): 41f255cc99c38b4957d024cd02d47bb0ec493497b0408061a71b8402e95a5fe5
incomplete pack file (will be removed): 491e7f638a2f2514ea48f6eced65eea8ebd8ec443575900de4cac395c552aa1a
incomplete pack file (will be removed): 4e5caf20c96d19d489336c9e2a3f61c40742bbc8923b7f3da8f51b1b58a536d8
incomplete pack file (will be removed): 4eda2bfeef7bfe3da8829d5ea6e28b2833d8d25bb8c90350a1c55ef7c0844c68
incomplete pack file (will be removed): 5020f77feca4bc89e817ef41ae3a504ec1b2f6e1b307b9bf8d9ff069c7e2d99e
incomplete pack file (will be removed): 5087d6b2d8f3c562ab8df2c851aa407a54125ca12fdd8f3ef5140487645df797
incomplete pack file (will be removed): 51e31fa6820306be497d665948753d6a3b696f00fa9155cebb02439d8df4d23f
incomplete pack file (will be removed): 52710884fad5d222f3d75ad4ab73edacf5d91fec9ceac5339ff789aa40c2818f
incomplete pack file (will be removed): 52ae38929421daf633ec65471fc64df876e221592ebfabb97f9f9722bb7121bf
incomplete pack file (will be removed): 53e22d99e1fbebd805ecc625128ab7d0a0c2dcb5c1137443a24308137763992b
incomplete pack file (will be removed): 54fcadf6b04a295fa4c54f18317d44caa205a7c361db610eceba1d05d0b8ca6a
incomplete pack file (will be removed): 56ea853481daebf24700fe2f809da1c287c8cca104c13c3563f0ab620f85ce1a
incomplete pack file (will be removed): 576fb294c1d587c3797663d2734f195f89be67e9f179f447a767215d81aa4b72
incomplete pack file (will be removed): 584355662b4e5cc53e73b4d53b8ae731cabe6e141056bfd9124b333c119f0418
incomplete pack file (will be removed): 5925b592d7c50ae649ce7bfeead534bfd0c25b03dc0d4d00f16ef929178cabdd
incomplete pack file (will be removed): 594d93989c1eb3a33cbc0b9e0c0c681b3f733bbd1cadea228e5b6969bfe49196
incomplete pack file (will be removed): 5b623c37aefc0c4612386954b451d3c304432b683e591ce9cf5b5035f03f8dbe
incomplete pack file (will be removed): 5ffd229d6a249a27cc118ab5f83466baad07310734de897f3355470b2773fa0a
incomplete pack file (will be removed): 61aa1c961a2e1cc4f4d3857667bcb252b171fcafd6315c23b0653684e85a3ba0
incomplete pack file (will be removed): 674a761ab15853245440328285d222e2f885e1a878614c364a2a3ab7a7df013b
incomplete pack file (will be removed): 678de0ab823e92e6bfd3ee617e2e2237719191bc86109aa76841ffb3a7f44a40
incomplete pack file (will be removed): 67eaf39f4b56176d765191ea8b1c7f0ea3e769838b46185740e75ef271e2773c
incomplete pack file (will be removed): 68a1116b9533471a37da3f5d768527facee0a4075729341d956a31504851c388
incomplete pack file (will be removed): 68fcdf4ddc30b2e533eab8233899111ad16c4ead63313a00b8b16e5ef29f9122
incomplete pack file (will be removed): 6b3ee15588f62669ddcb88040fc8ae3db9aa11f693a6e342b338ecacef57427a
incomplete pack file (will be removed): 6de7e95ce9ca42591f184ec4f4b8376ec89fef5907327bbc837d8711d60cd0f0
incomplete pack file (will be removed): 70fc3dcab452fd356feed29c36b3bd3c9ece384240bfaafdd47090c7d0278b0f
incomplete pack file (will be removed): 7366468bc5f2056573564851f43b9d71c1c6e0b08a9542a39c7cba27dab0af8b
incomplete pack file (will be removed): 73a5474d071d1da437dd3819220604f20de2ff03be363de2ae42332b337ecdb9
incomplete pack file (will be removed): 7490a7145d681b48eded80f00d50feb2dc1168d7a68896d1e7b4f4c74da7ae35
incomplete pack file (will be removed): 787a2e28a57e84310e905a08d44bc9bc93b31562d4c65cbc4141a4784ba33709
incomplete pack file (will be removed): 7a6cd2a88bea18dcd1604dfeeb85ad598fdd6167623056aa36cd707856878622
incomplete pack file (will be removed): 7a72454d48c4916e6c4bb215b344d383dd00bdd9eab0c41f46b40bbedb288fb5
incomplete pack file (will be removed): 7d429dfe395c7cae3feaa562775f08459461d297c1f90f59689fda2db91cc15b
incomplete pack file (will be removed): 89917582dec6ae339c170c094944f40c83acb002642852ea0abc9161c0408977
incomplete pack file (will be removed): 89f79b7e5bf5d284da2032c1f0d56f62295e57238e1c1fc47a99c942114bac7f
incomplete pack file (will be removed): 8b528f07234e566ea7dba1f37691c1dc4f5b877b5e881354417661ded8bf7422
incomplete pack file (will be removed): 8d302101ae264c9817564772b3b86970b50435ed0f1ce5d310e17d71b6120e33
incomplete pack file (will be removed): 8df3ceb1ddbc9e13aebc3a3dfd376a1349c36659dd13c8e53cccdf6350eb10c7
incomplete pack file (will be removed): 8e58734cfe1cee65931d0df29959e9362bc8eff614daa14dba437483d1999a41
incomplete pack file (will be removed): 91371024ae152b258560bbaa8a4689d4aa8e5b1af8bf140cae741959dd7ac376
incomplete pack file (will be removed): 9159133d59d5410bf8b54b6faa35b7715a2b50cb7e4267d847008d70933be99b
incomplete pack file (will be removed): 92953454d09d3ce6b05eebb444ef4fc83bc8119a90dd4e9f69a245f728b409b4
incomplete pack file (will be removed): 9445b74cda2eb577dde1e31ff1e2cf09109ebefa95e4b838c624ec0d47e8fe62
incomplete pack file (will be removed): 96ab45db3c8aa7be11afa17505e8b696cee017a65a68151cf538864d80145680
incomplete pack file (will be removed): 96f3c04a22184b59352989df38a817010516c7af576dce02c5c3bdae6e16ddc9
incomplete pack file (will be removed): 9893ecfa88065ac78b9e097e9bcd368a29b41ac3c909f2fd651a482ad8b2f0a8
incomplete pack file (will be removed): 98c233ac645106364a5c7c02ed737b2dfadead12c2fd44d63bfae7295a152d69
incomplete pack file (will be removed): 995e4a901fa25562df6adf69f9ca449fcda2e09e817f3023fb773b8bf97cc0f4
incomplete pack file (will be removed): 99bb74e9205be9fd766b17b05c5e23d0426e87533ee50ddef6ab823e85148026
incomplete pack file (will be removed): 9d57180d0af5984e9240a9bc48a15f3108f584236078e86138f170d6d549b481
incomplete pack file (will be removed): 9fadeb4a570ecff25c009d2e9527eb741b7f00c62d5afa3ccc8c02c219f6fe3d
incomplete pack file (will be removed): a17da2004664cfe60c40039992a31c2791119ddc704fe0471c9ad7a28bff692f
incomplete pack file (will be removed): a23cf9b305fd24bb4592aee78a469091542f0064157bab74cea52e214e04283f
incomplete pack file (will be removed): a25d3ed230c22cee18bb9f7c699d06fd80b678b7eb12351782c25b08b4b45faa
incomplete pack file (will be removed): a31fcd694d346b2a342f3da234e86f69b84605ac05b188a3761f09d2ccde4d3e
incomplete pack file (will be removed): a33013980ad8ebda0e49a90afaa36b14e579ca4beb432eee74368672d0668eab
incomplete pack file (will be removed): a663bc095f88280fc89fd046b507aa754f45175b79b2401539303de6e6a2155d
incomplete pack file (will be removed): a66ce9fa0a5225d4e0d7dcc3f98842aee5204b67082f7683d6690e441d40a042
incomplete pack file (will be removed): a9606104edfa0c6fe049c426bfefd49ff1b57e5186eab8abc50c54c7d47b4430
incomplete pack file (will be removed): ab054ae3ef6324083a0184e621aec75a6b0900e0592c3172bdbba606f69a6c30
incomplete pack file (will be removed): ad141d82c72686a1a337ec85b72b116f881ca511a2a977353af34fc6465ca033
incomplete pack file (will be removed): ad70c2d0bf7ff81094890354bbaa444567407cfc2dddf61e7dcf15dcc74e315d
incomplete pack file (will be removed): add9869f5e0da38a11ab2df16dc53bdff76009c4ab10efe213d8798f15a0ac72
incomplete pack file (will be removed): b05e7cc3d28426728c7df4768312b689c116eeaec4085f618e24e0ef1b11aad5
incomplete pack file (will be removed): b0fc355fd584d638ab0a55475de919bb3bf4985006d14e2573d08d9d4b5f286e
incomplete pack file (will be removed): b425b2d117f5ba692f8e8e56ee09064794f53b0f0d869aa244bfc568cd8c3f07
incomplete pack file (will be removed): b9a069007bd54734e5320a9c8169f3741d8a62b30d0b05d5f8443814e36441f4
incomplete pack file (will be removed): b9c58a1d2a16c00e6cc27d3609e307379d2a678489c879c59c50d81cab5cba7f
incomplete pack file (will be removed): bb3219b4c98ad65d7e2557115a95c678b78bcb0f3b9f0a228c6f536684f6dccd
incomplete pack file (will be removed): bbdc001dd2a4084a9bf7a1e7e2998e78a7280085593c64780a6c34fcb4b03bd8
incomplete pack file (will be removed): bc56640166c86aa1f91efc5f0084b1ae3d01f25004b9dc81a6e518fcbf954792
incomplete pack file (will be removed): bd8ecdf7ff1c80084e5988dce7950a56afdf8ff24308c1be2b4fc834724e7be3
incomplete pack file (will be removed): bd9af4c2cdbda0681309917f8b70d3c4c861fd96efbbe635fcfdb920e3df8909
incomplete pack file (will be removed): be481b0be6d6f2446e1554aae7a532738181e1ccc044a6d2744aa33d92df9011
incomplete pack file (will be removed): c02858e62f697c92660cf71820081c2987211fbe5a0761844c935306cee50a93
incomplete pack file (will be removed): c0b2ec8e8261ba261cabb090e13e3adc3d11a78d9fcb166d7a4bed1936f79875
incomplete pack file (will be removed): c5fbb969e0a00b47c08b1170a4f309f1ae6fef2096ca0482f666df0cf25d8854
incomplete pack file (will be removed): c692b9da69512844bc5b9a5c7d4a0924856a06c0ef4e20461363c814afe3f4a7
incomplete pack file (will be removed): c74d795c02833992cb38d8d3f829ca5d88f813f2a62e2bc6d709ad1fb1afb666
incomplete pack file (will be removed): c9b1d90832e1bce58688dcff263763080e85682258709b34a3ba7b0cda9020b8
incomplete pack file (will be removed): cc82271673b9e29cb5ed78541d125cc537d113f123d2d8180859653136a62e63
incomplete pack file (will be removed): cd14af66a91b8d11d837a4c63ed4ba8155bb0e31277d349dd3c816a696d4b826
incomplete pack file (will be removed): cd74a9d8a0d066fa29e58b089428685de93d415c4959d0b6b5dbe3ba9dd41dbe
incomplete pack file (will be removed): cdce680ba959c8fc1159b81a27ff8f3cc1e324dd10e062079b4837d0c153a990
incomplete pack file (will be removed): ce6a29732dca0775d432acb37ccdc1dd437810e1aacfe130c3b0efb5e1a59b91
incomplete pack file (will be removed): d2e1c294ea201aa78c7c2e0810eb0a852ac89c01bb486d558e13ee7800cdbe12
incomplete pack file (will be removed): d3a9a14f7a226344c73733e5ee02802100aa2c487f02ae2a118c38c9ebfd1c2e
incomplete pack file (will be removed): d515ca01a82b93a7be51f00acac91654bd05c04778ddf3569fd3dea9b955e71d
incomplete pack file (will be removed): d59b0b71408e803c200e2061fbbddb946589bdb6d76e2b0340fb04d4f65ddf29
incomplete pack file (will be removed): da92cd97399a97e6f4676953662d8b7eac24fa51a477231dbf46dbe5a95cc9b2
incomplete pack file (will be removed): da934e8292bb7e53bc3f220fab8481551564660300059ad4873b2f8d73357ca5
incomplete pack file (will be removed): db3a4c4295c1a8ece0238dcf46d4c91ad991c185505fcac50a59538b64438364
incomplete pack file (will be removed): ded57b7f054ca3720709931dda438ccc0cdfe1318584ff7dc1714236ba704b36
incomplete pack file (will be removed): df017d398be68596307949eae582979f74613bcdd2904dfdaed636cc3afca360
incomplete pack file (will be removed): e2899459426726f02f2522b31931107f7c3b9870223513d920b2899e7c0020bc
incomplete pack file (will be removed): e2e1ca435658a3811d11ff56871b8b006d4181bbbd7b6d40f030a99538ed4ba2
incomplete pack file (will be removed): e571c2f157a674dcd2e6fa3d48097b9001588719a7fd31997a148da0469f8c79
incomplete pack file (will be removed): e6834e3dfb5ec2caf24560811d3f6a2c22bc4c3d03126d54c5f5a2aae803e89d
incomplete pack file (will be removed): e6c55ad6455d20f4c83e09a936a50e2cc952e650502e18ff61d2ed454f41de92
incomplete pack file (will be removed): ea795c1b5c639c90edd7720c47ca602a38c9f1c6b83c878dea2910c48d00dff9
incomplete pack file (will be removed): f07c138c3ef11de1d59c9049803cd3483133300687252fb3abd529906066b27c
incomplete pack file (will be removed): f39d521465b9ff272bb0cec7821c7ecd4fc51c0490193928d4ba94287be084cc
incomplete pack file (will be removed): f5836a61916ff95d56d38c7dd80d2ea6a6fb340e4500cdf1286a6b6ad53cde04
incomplete pack file (will be removed): f7e29e1c0b6f9f8ab75df90926f6aedd0f245a5dfbfeba083d20b71699b0a4c8
incomplete pack file (will be removed): fc28c9f572ea23e85b9e1f13667ee9c2ef61d07e0f3a8307b06a47f7f43d76dc
incomplete pack file (will be removed): fcbad2263cf398050947acdc5861ce74405aa7df22e9d64a4f45ab77e7349236
incomplete pack file (will be removed): fd19e954363bd1f78d97e6579474b8219bb080590a68b3219a63120186364f6e
repository contains 66393 packs (120712 blobs) with 479.626 GiB
processed 120712 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 132 snapshots
[0:50] 100.00%  132 / 132 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
NAS

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you or made you happy in any way?
-------------------------------------------------

**Comment by onionjake** [comment]
@killmasta93 are you still getting this error?  Were you able to work around it somehow?

**Comment by killmasta93** [comment]
nah i ended up deleting it doing it again

**Comment by rawtaz** [comment]
@killmasta93 Thanks for taking the time to create an issue. It would be great if next time you could try to make the issue template more complete (mostly thinking about the type of backend - "NAS" doesn't say much.

But anyway, I'll close this issue because we've seen this error message before and either way there's nothing to do about it now in this specific case.
