### ISSUE TITLE
Restic silently fails to backup memory mapped files

### ISSUE THREAD

**Issue by sorcix** [restic/restic#2317]
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.12.4 on darwin/amd64

How did you run restic exactly?
-------------------------------

```
sudo /usr/local/bin/restic backup \
   -r "$RESTIC_REPOSITORY" \
   --cache-dir "/tmp/restic-root-cache" \
   --exclude-file "/etc/backup-ignore" \
   --exclude-caches \
   --exclude-if-present ".nobackup" \
   --host "$hostname" \
   /
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Can reprocude the issue using both webdav(rclone) and a local directory.

Expected behavior
-----------------

Restic creates complete backups or returns an error when it fails to backup a file.

Actual behavior
---------------

Restic reports no issues when creating a backup.
Afterwards, restic check complains about missing blobs:

```
error for tree 150d2442:
  tree 150d2442: file "Outlook.sqlite" blob 105 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 110 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 111 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 112 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 289 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 290 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 291 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 292 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 293 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 294 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 297 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 301 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 672 size could not be found
  tree 150d2442: file "Outlook.sqlite" blob 675 size could not be found
  tree 150d2442: file "Outlook.sqlite.bak" blob 104 size could not be found
  tree 150d2442: file "Outlook.sqlite.bak" blob 105 size could not be found
  tree 150d2442: file "Outlook.sqlite.bak" blob 106 size could not be found
  tree 150d2442: file "Outlook.sqlite.bak" blob 107 size could not be found
  tree 150d2442: file "Outlook.sqlite.bak" blob 108 size could not be found
  [...]
```

Last time this occurred I've removed the snapshots as [suggested on the forum](https://forum.restic.net/t/outlook-sqlite-blob-size-could-not-be-found/1368). However, it looks like I'd have to delete every single snapshot of my laptop's disk to make `restic check` happy.

This happens with `Outlook.sqlite`, `Outlook.sqlite.bak` and `mercury.db` (Spotify). Using `vmmap` on mac shows that all these files were memory mapped at the time `restic backup` ran.

Steps to reproduce the behavior
-------------------------------

Create backups of memory mapped files being modified.

Do you have any idea what may have caused this?
-----------------------------------------------

I suspect memory mapped files being the issue.

Do you have an idea how to solve the issue?
-------------------------------------------

No. I'm not sure if its possible to fix this, but it should return an error during backup.

**Comment by MichaelEischer** [comment]
I've never seen that issue myself. Please test whether it still reproduces, with a recent restic version.

**Comment by MichaelEischer** [comment]
Closing this issue as there has been no feedback and there is not enough information to find the actual problem cause.
