### ISSUE TITLE
Allow limiting outgoing bandwith for backup

### ISSUE THREAD

**Issue by fd0** [restic/restic#232]
Currently when using a remote backend (e.g. sftp) restic saves data with the maximum bandwidth available. Add an option like `--bwlimit` (like rsync) which limits the outgoing bandwidth.

**Comment by cfcs** [comment]
This would be neat. Examples of nice/ionice/namespaces configurations in Linux would also be neat, even if those are external mechanisms.

**Comment by fd0** [comment]
#483 lists an example for using `ionice` and `nice` with restic.

**Comment by fd0** [comment]
Whoops, wrong button.

**Comment by wpbrown** [comment]
I'm testing out the new backblaze b2 support (uploading 4300 files, 28GiB). You did such a good job on this one it's forced me to look up this issue. restic is crushing my 15Mbps upload so hard I can't do anything else :laughing:

**Comment by fd0** [comment]
For b2, you can limit the number of parallel connections with `-o b2.connections=2` (by default it's 5).

**Comment by sfrique** [comment]
@wpbrown you probably can use trickle if you are on linux.

**Comment by cgonzalez** [comment]
@sfrique No, you can't use trickle (with the restic's standalone binary). From the [trickle man page](https://www.systutorials.com/docs/linux/man/1-trickle/):

> Furthermore, trickle will not work with statically linked executables...

**Comment by sfrique** [comment]
@cgonzalez you are right. I just remember I've use trickle before. My bad!

**Comment by fd0** [comment]
Ah, this was added in #1336 already, restic now supports `--limit-upload` and `--limit-download`. I'm closing this issue.
