### ISSUE TITLE
Display date for snapshot in find command

### ISSUE THREAD

**Issue by jpds** [restic/restic#2326]
I usually want to restore the latest copy of a file I have in my repo, similar to #1495 - the output of:

```
Found matching entries in snapshot 1434baeb
```

...should display a date/timestamp of the snapshot so I can plunk out which one is latest easily.

**Comment by lorenzbausch** [comment]
@jpds See https://github.com/restic/restic/pull/2271

**Comment by jpds** [comment]
@lorenzbausch :man_facepalming: - awesome!
