### ISSUE TITLE
Accept both singular/plural options for --group-by

### ISSUE THREAD

**Issue by akrabu** [restic/restic#2330]
Output of `restic version`
--------------------------

v0.9.5-31-g3ca42405

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

In `forget` and `snapshots`, the `--group-by` switch accepts `host, paths, tags` - but elsewhere in restic, `tag` and `path` are used (singular instead of plural).  To avoid confusion, it'd be nice if `--group-by host / hosts`, `--group-by path / paths`, and `--group-by tag / tags` could be used interchangeably. 

What are you trying to do?
--------------------------

With this feature, I wouldn't have to remember if --group-by takes the singular or plural form of whatever I'm grouping by.

Did restic help you or made you happy in any way?
-------------------------------------------------

I'd wear a restic t-shirt if you sold them.  <3

**Comment by akrabu** [comment]
First mentioned here: https://forum.restic.net/t/minor-quibble-with-group-by/1883/2

**Comment by rawtaz** [comment]
It would be better to consolidate so that all relevant arguments take singular and nothing else.

**Comment by akrabu** [comment]
That was my original suggestion, but as @fd0 mentioned in my forum thread, that could break existing scripts and such.

**Comment by rawtaz** [comment]
Yeah, it would. But sometimes one has to correct defects and make minor adjustments. Better get it right than have an ugly set of parameter values and code that shouldn't have to be there.

At the very least, deprecate the plural parameter values but still accept them, then in the next major version get rid of them.

**Comment by rawtaz** [comment]
I am proposing that we fix this by modifying `restic/snapshot_group.go` `GroupSnapshots` such that it:

- When given a singular keyword, accepts it without further notice (like plural keywords works now).
- When given a plural keyword, accepts it (like it does now) but also emits a *deprecation warning* asking the user to use singular keywords instead.

Q: Are there other places that need changing too than this single file? From what I've read, it seems the concern/confusion is just due to the `--group-by` argument. If that's true, this should fix it.

Q: Do we have any established routine for how to communicate deprecation warnings when restic runs?

**Comment by fd0** [comment]
I think we should accept both, singular and plural forms. E.g. refactor this:

https://github.com/restic/restic/blob/6a89c0f0ef2d6b11e1a7a0095bc41a90ea085070/internal/restic/snapshot_group.go#L33-L39

to this:

```go
		switch option {
		case "host", "hosts":
			GroupByHost = true
		case "path", "paths":
			GroupByPath = true
		case "tag", "tags":
			GroupByTag = true
```

By the way, there's a reason why `host` is singular and `paths` and `tags` are plural: every single snapshot hat exactly one host name, but many paths and tags. So I thought that'd be logical, but apparently people who haven't written the code to handle that are confused (understandably).

> Q: Are there other places that need changing too than this single file? From what I've read, it seems the concern/confusion is just due to the --group-by argument. If that's true, this should fix it.

This should be enough.

> Q: Do we have any established routine for how to communicate deprecation warnings when restic runs? What Go function should I use to output such a warning properly?

I don't think that's necessary here. In general, we do have what the `cobra` framework provides for command-line options, like this: https://github.com/restic/restic/blob/6a89c0f0ef2d6b11e1a7a0095bc41a90ea085070/cmd/restic/cmd_forget.go#L65

**Comment by LensHunnel** [comment]
@akrabu , waiting to see you in your restic t-shirt 😄

**Comment by akrabu** [comment]
> @akrabu , waiting to see you in your restic t-shirt 😄

The real issue here is that there isn’t one yet! 😂👍

**Comment by fd0** [comment]
I've thought about it and printed two shirts for FOSDEM 2017 for @fawick and me, but that's about it ;)

**Comment by fawick** [comment]
Great shirt, though...

;)
