### ISSUE TITLE
mdns/bonjour/avahi hostname support

### ISSUE THREAD

**Issue by daviehh** [restic/restic#2335]
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.12.4 on darwin/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Support dns name resolution for mdns/bonjour/avahi hosts

What are you trying to do?
--------------------------

e.g. For devices in my home wifi network whose ip is dhcp-assigned but has local domain name `foo.local` assigned by mdns/bonjour/avahi, I can connect to them using e.g. `raspberrypi.local`; I can ping/ssh `raspberrypi.local` or access via web browser without issue, but using restic (or nslookup for that matter) fails since restic is unable to resolve such names.

Did restic help you or made you happy in any way?
-------------------------------------------------

being able to use `foo.local` with restic

**Comment by moritzdietz** [comment]
Could you please give us an example command that you ran just so we can get it right with what you are asking about.

**Comment by daviehh** [comment]
@moritzdietz Thanks! For example, `restic -r s3:http://raspberrypi.local:9000/backups init` fails with e.g.

> Fatal: unable to open config file: Stat: Get http://raspberrypi.local:9000/backups/?location=: dial tcp: lookup raspberrypi.local on 1.1.1.1:53: no such host
> Is there a repository at the following location?
> s3:http://raspberrypi.local:9000/backups

while `restic -r s3:http://192.168.1.211:9000/backups init` runs fine.

**Comment by moritzdietz** [comment]
I think your problem is that your computer tries to contact the Cloudflare DNS to lookup the domain `raspberrypi.local` which obviously fails.
I get the suspicion that this is unrelated to restic, but rather a DNS problem on your end.
What you can do is try to put this hostname in your `/etc/hosts` file and see if this works.

**Comment by daviehh** [comment]
Yes, I understand FDQN works, this is not a big report but a feature request to support multicast dns, i.e. `.local` domains; https://en.m.wikipedia.org/wiki/Multicast_DNS

in the same terminal window, ping/ssh such `.local` domain works; I want to avoid hosts file for now since the ip assigned by dhcp may change every now and then.

**Comment by moritzdietz** [comment]
Oh my bad! I totally misread that. I kind of think this would be very low priority if not even out of scope for the restic project. But I leave this for the maintainers to decide.

**Comment by smlx** [comment]
The reason mDNS name resolution fails is that [Go doesn't natively support it](https://github.com/golang/go/blob/21f548400650e4e7047202ee1894ee6ddd44de82/src/net/conf.go#L189). It can work if cgo is enabled, but on [restic's official builds it isn't](https://github.com/restic/restic/blob/master/doc/developer_information.rst#reproducible-builds).

You might get mDNS working if you build restic yourself with cgo enabled.

**Comment by daviehh** [comment]
@smlx Thanks a lot! Setting `CGO_ENABLED=1` works for the mdns name resolution.
