### ISSUE TITLE
Corrupted repository; can't recover

### ISSUE THREAD

**Issue by akrabu** [restic/restic#2347]
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.12.4 on darwin/amd64

Describe the issue
------------------

Ran scheduled maintenance (rebuild-index; prune; check).  Had errors.  Tried again, more errors.

See logs:

> **akrabu-mac-mini:~ akrabu$ restic rebuild-index**
> repository 3cc4819d opened successfully, password is correct
> counting files in repo
> [3:02:12] 100.00%  859253 / 859253 packs
> finding old index files
> saved new indexes as [3bc2bfb2 9338a0fc bbe75cd7 1d7ac9d6 f9585e98 13e0e05f 4ed72191 4b133214 66af19f9 beaf9db0 e5dc601b e9780b08 ed3bf4cd a32f0ce0 a253102d 552eccb0 b530e839 b0d64c58 58503816 8f99a7e1 56458a90 07e2aaae 9ae5ed41 936f478
> 9 b664b7ed c20aa869 6c4d3f6f 9b97d5fe 81b9b058 8607928b 3dbadea5 92c60c60 99be77b0 8ce2e081 8ec8a185 f5b9b757 93e73899 c75bdf2b e8718b14 8be09b60 a0eb8b67 21772570 01972249 43944bd6 7728e908 5f3a8337 c947debd 3724d599 907da999 ed00409b
> f2af6ff8 c772ca31 969f0262 ebd08837 dcfedf1d dd711ba7 a0c50fae 59dddcd7 78547c61 6ca3dbd0 e93fb0c4 1adfe81e 1e8c59c6 6e389fa8 f730b8ae 3d2c5d37 a44bad46 002b733f 639a4d6f a9d94e62 9d9b42dc 7aed5268 b08720a3 41a74155 4dc7ef4f ef307402 da
> da9fc3 3327584b 3b5eee01 2bfb1b93 f84c9c29 7a352980 96f7eab6 9e4a5bf4 751785fe f210fd2e 459d6415 c665bf25 e24d577f dcb91e8f a155e810 d12e7da2 985337e0 e36a3948 5daf8da9 e380ab2d 491fbfd0 f2d6e54b 84a28c9f 4a02a188 db985145 2ed9dd00 c33a
> ecde 2526edfc 4f92836c d21af2e2 023e5d26 cd7d9e4b 91b697e2 2369f042 22362ea1 3cfc007a fec1bfd4 7c3f6b64 1e044bc9 f1e04dfa b96d6da8 e940794d d8feb1c8 a1c278d7 3977b36f 969bca0c 64bf338d c70d01a7 6b807845 2dc5ab13 bd509efc 41d6726b 1c915c
> 1a d325ca33 25facb2c 54e25ac3 29737094 6a057ec8 e85ae1f1 3f4d49d9 e242f2cd ab221683 b34ce4e4 41f30d84 c6552312 3d397c08 f05cef55 76330e8c 267fe673 f1145f51 aa28ff84 814c1e13 35a97e25 f621d9c6 ff9bad4a 9a9b4cee 96dea7c0 055a14b8 9fa0fcaa
>  8dbf6932 135e7836 3ed3bfb6 a103905e e9e8cf30 2809d3e2 6037f72b 3e347f72 77a6a00a 97156dbd dcfa5032 f66e29d2 5226fde9 ec449838 d220b9ae 03d12141 af579d63 2345364e 43cfcd17 44cd6d11 649a6ecf 58064cd9 538b9426 1cd34b92 1ac62b23 8cb599a9 2
> 6fde68f 9440061e e17bd661 35c5121c 897193a7 ea3e37ea 87e6dc0a 34fca347 f849b381 b33e48f2 3309ac6a 2525a13a 1e82d9dd 58983cd8 ccb4180c 164539ca 266ed2b1 bfd3c03b 35b10d18 c729e988 aa13ab6a ffea3d64 ae915a84 51e32f3d 968714e9 9c3868f8 151
> 3aad4 877d4102 a9c8c9ed cba65424 79ab22aa fce324af 33f18d1f 584ddfc6 32ef0db4 6764ad73 0e4d058d bbba6a4a 4c99c0ce 5003631f 6ed34850 4cf533ff 33206b19 01daddf6 952e0aa6 102384a6 4981b675 17efd8a4 87b89363 0791dbef 7ed5d86d cd10ad8c c71e3
> 25a c9047b89 75944e17 72ea12e1 2647b942 2ed39fe0 3e7530b8 51e8618e df88a45e a1015150 e1ea19df d1da88d0 c28fc1f3 aaf3223e 0027be4f 7363d09d 2125e971 a7ed7fb8 367ff3ca dc4547ad 76ed1dbd 2f99eb98 781f4d74 02a5b3be 942152d6 b84343fa 73713ea
> 8 c0daf098 4deb6de3 918389e2 79b56f4d 66d6a33d c0b7da45 45fa9b93 11c93cff e4a5822c 2c98a89b 4f7944f2 68a4d08e 39b8cf3c f7bcdd1d c21537f2 b2fce9d4 9a1791eb 9cc91155 1eff81ff 43edfd34 5bf596e8 1bf3757f 6a9a0867 1e5e654e c288f811 627847fb
> a0e3e114]
> remove 1537 old index files
> 
> **akrabu-mac-mini:~ akrabu$ restic check**
> using temporary cache in /var/folders/z5/x7mpskwd2m54cz0l4wvx807h0000gn/T/restic-check-cache-591499488
> repository 3cc4819d opened successfully, password is correct
> created new cache in /var/folders/z5/x7mpskwd2m54cz0l4wvx807h0000gn/T/restic-check-cache-591499488
> create exclusive lock for repository
> load indexes
> check all packs
> pack 0eb0df47: not referenced in any index
> pack c9f1beb9: not referenced in any index
> pack d2ca838f: not referenced in any index
> pack b303120c: not referenced in any index
> pack d0701fe5: not referenced in any index
> pack 531b4ccc: not referenced in any index
> pack 4326d96d: not referenced in any index
> 7 additional files were found in the repo, which likely contain duplicate data.
> You can run `restic prune` to correct this.
> check snapshots, trees and blobs
> error for tree b8d5a4c8:
>   tree b8d5a4c8: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree b8d5a4c8, blob 2b0a0f2d: not found in index
> error for tree 86a95941:
>   tree 86a95941: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree 86a95941, blob 2b0a0f2d: not found in index
> error for tree c1de8831:
>   tree c1de8831: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree c1de8831, blob 2b0a0f2d: not found in index
> error for tree 28c9bd82:
>   tree 28c9bd82: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree 28c9bd82, blob 2b0a0f2d: not found in index
> error for tree fdcb8a77:
>   tree fdcb8a77: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree fdcb8a77, blob 2b0a0f2d: not found in index
> error for tree e6eb0d8d:
>   tree e6eb0d8d: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree e6eb0d8d, blob 2b0a0f2d: not found in index
> error for tree 50210267:
>   tree 50210267: file "renamed-file-for-privacy.exe" blob 455 size could not be found
>   tree 50210267: file "renamed-file-for-privacy.exe" blob 456 size could not be found
>   tree 50210267: file "renamed-file-for-privacy.rar" blob 286 size could not be found
>   tree 50210267: file "renamed-file-for-privacy.rar" blob 287 size could not be found
>   tree 50210267, blob 75ac3db0: not found in index
>   tree 50210267, blob 10ba19c1: not found in index
>   tree 50210267, blob e26bac8c: not found in index
>   tree 50210267, blob 9b4bc577: not found in index
> error for tree db541381:
>   tree db541381: file "renamed-file-for-privacy.exe" blob 455 size could not be found
>   tree db541381: file "renamed-file-for-privacy.exe" blob 456 size could not be found
>   tree db541381: file "renamed-file-for-privacy.rar" blob 286 size could not be found
>   tree db541381: file "renamed-file-for-privacy.rar" blob 287 size could not be found
>   tree db541381, blob 75ac3db0: not found in index
>   tree db541381, blob 10ba19c1: not found in index
>   tree db541381, blob e26bac8c: not found in index
>   tree db541381, blob 9b4bc577: not found in index
> error for tree d96189be:
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 997 size could not be found
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 998 size could not be found
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 1003 size could not be found
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 1004 size could not be found
>   tree d96189be, blob c8a1b47d: not found in index
>   tree d96189be, blob 5686f170: not found in index
>   tree d96189be, blob 9f486bb2: not found in index
>   tree d96189be, blob fff87063: not found in index
> Fatal: repository contains errors
> 
> **akrabu-mac-mini:~ akrabu$ restic prune**
> repository 3cc4819d opened successfully, password is correct
> counting files in repo
> building new index for repo
> [3:02:02] 100.00%  859253 / 859253 packs
> incomplete pack file (will be removed): 0eb0df47e51e151dc245dc05c19746098880514ab8ced99db0b16ebca1c22a36
> incomplete pack file (will be removed): 4326d96d449f8ce22318a6a9f37167ef1d0d2cdd504b8c3903535425aaa300f5
> incomplete pack file (will be removed): 531b4ccc6440b24955cf0c68bc6366ccbdb0c5746bf29c007bdb76b85c3fd974
> incomplete pack file (will be removed): b303120cdc73cb8e8122abe1fa4a9cebe5844f6ef2620d2abd13f2f9b343f746
> incomplete pack file (will be removed): c9f1beb9efb9ecf518e6137de041450b24733f418c1b61d2c1017590b6ac8a75
> incomplete pack file (will be removed): d0701fe5ab091fd7fcaa0fa3263a58483420e2ac6a121fdd320deb35c695f8e4
> incomplete pack file (will be removed): d2ca838f94c3f446d7aad5777b742743214daee1749be1df7ee6317fd341f6ab
> repository contains 859246 packs (11939496 blobs) with 3.869 TiB
> processed 11939496 blobs: 26052 duplicate blobs, 8.553 GiB duplicate
> load all snapshots
> find data that is still in use for 897 snapshots
> [21:12] 100.00%  897 / 897 snapshots
> found 10729128 of 11939496 data blobs still in use, removing 1210368 blobs
> will remove 7 invalid files
> will delete 28831 packs and rewrite 13021 packs, this frees 153.993 GiB
> [4:07:26] 100.00%  13021 / 13021 packs rewritten
> counting files in repo
> [2:51:14] 100.00%  825174 / 825174 packs
> finding old index files
> saved new indexes as [b235ef05 960e4ee6 b9f1d849 61770fdc b3e5bf19 e6666cfc d059ef5e f52ebed6 5ee978ca ba1fba50 9826a2e7 9c22e2d3 307f8d92 1b07a19a ee3c0556 58747541 f5c388a3 98cca955 53d3557e da2a2987 f6607089 2de03ccf 6dd722de 6447659
> 5 9622561c c7a2d811 1a6f75b0 948c28b3 61534aeb de727524 3e27b034 e066961f fb9b3d54 ec32a008 22168c17 7b85fa68 d4d7dfac 661d1d6f 34da7971 f0bc7e49 a1d90107 8709bbab d2b1551d 86d14d58 a2d55a8b 00b20312 285a3e2c 9b9cbf6e f553a35a b06187c6
> be3bca29 4942c8bd 1afca3bd f311451f 1433e1b9 ef12e189 1d75eda3 712f755e 879f171f 2aaf64dc ab5f31d0 9ef5100a b6c5017a 7346c8b5 1cc67596 2dfcfc22 a4e0b071 cd036071 7c6f568b 9934bd06 135d1bc9 44ff66da 0df287fc 4486474a f047e0ea 8acab509 38
> 2d047e bcb7fdd0 8ce52cab 4c4f36f4 9fa124b9 fc9f4eac 704e4a0b 6a64353c 0cbbe98b fa6b2278 55840a66 11b5c743 b877a762 f9ab9167 5c58ccd5 42df97b0 1c4d3334 6df4e7a6 b20595ed 24e9cb46 28882186 202ded8f e4650d77 3099c22f 5607b013 6407f8ca 0a47
> 6b5c 872efcef 64a54884 3cc7fd33 721c09f4 2d87480c 7929441a e794b99d b3077311 8e2bdb94 5865fe8f 22da2c96 18e68e89 c7606467 c9773b9e 704afce5 d27a33b4 13922f11 11a3b913 3c327ced e7658467 2bf5f14b 1a3b82f3 48b46de6 f574e799 af89ed4e fbad1b
> 88 8a995838 3333b6d7 e763e3cb 4ae7e592 44e1f7a3 23927a7b c8b6f91a fc024353 a23f2984 fade597c a3358aec 2720cb76 e2192fd3 66f78c48 c7f70ced da2a72d6 25a095d0 5e3d8571 b489c8bb 930c35e9 afb40a65 74e1c371 83683c5d 399aa9c2 da026a9a 532897f3
>  327a6e3e 77bdc77e 93e7cc3e 09e4afbd 25030591 de51cb4a b24e6f10 3568b24c c3439ade 0bdda59e 1062ef1a ac3dee66 59ab0e27 c225b810 6e2ab5d0 ee35b729 25c0f80f 61b03f96 0723e3a0 aeabbcd5 9be2460c e897ab52 712893be 050e52ef 3dfddce7 b7be724d 5
> 70dc85b 061c70dd 35594a81 0b7227b2 ddbbb8ec f0f32ac0 15b6a6a1 b288c3b5 2c6441e1 aa8f7a98 43d1aede 58b3ba8c 8939b0eb 59a6a9c2 540c3b17 55399cf0 d03092b0 86145efb 476d9d78 4cd99857 3b06c088 b2e4a700 81b27a9d a7cc32d7 d9584034 fa37431b a62
> 82feb d413eb72 d10f7a32 d8ac5ae5 55a50c12 85a739b2 66d4d50c 1b7e2080 4329130d e8110514 74828a39 43d47da5 1c9252aa a083d649 a0210620 47d8ed89 9df29c30 dd822805 39ccb385 3d9ecb6c 733347fe 2a869a35 699c41a6 d5606563 ea97d2d9 1c1cb3ed 392dc
> 13e 94302833 67f90d21 a70ba2c4 a5d7eb7d 8a0b98c9 d07bba57 e51d2e3b e29bc92f a1f5bac8 410d4d07 3d0e13bc 7deb7d5a 1bc25116 731c1e52 52c483a2 ccc41234 85a8793a 239a9401 7e1a256a b2533d38 1aa6ef08 7d08f5aa f36bda24 1f7f3934 662faf4b 14802df
> b 5cac7b67 874d853d 84d0e62b 675b7007 979ff414 55155652 a232be1e a071f8b8 1e82ef21 efc18332 6a442fc4 caef3ae9 1fa89ee2 821f919e cf1ab194 20f56928]
> remove 287 old index files
> [7:13:12] 100.00%  41852 / 41852 packs deleted
> done
> 
> **akrabu-mac-mini:~ akrabu$ restic check**
> using temporary cache in /var/folders/z5/x7mpskwd2m54cz0l4wvx807h0000gn/T/restic-check-cache-788227694
> repository 3cc4819d opened successfully, password is correct
> created new cache in /var/folders/z5/x7mpskwd2m54cz0l4wvx807h0000gn/T/restic-check-cache-788227694
> create exclusive lock for repository
> load indexes
> check all packs
> check snapshots, trees and blobs
> error for tree b8d5a4c8:
>   tree b8d5a4c8: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree b8d5a4c8, blob 2b0a0f2d: not found in index
> error for tree 86a95941:
>   tree 86a95941: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree 86a95941, blob 2b0a0f2d: not found in index
> error for tree c1de8831:
>   tree c1de8831: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree c1de8831, blob 2b0a0f2d: not found in index
> error for tree 28c9bd82:
>   tree 28c9bd82: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree 28c9bd82, blob 2b0a0f2d: not found in index
> error for tree fdcb8a77:
>   tree fdcb8a77: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree fdcb8a77, blob 2b0a0f2d: not found in index
> error for tree e6eb0d8d:
>   tree e6eb0d8d: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree e6eb0d8d, blob 2b0a0f2d: not found in index
> error for tree 50210267:
>   tree 50210267: file "renamed-file-for-privacy.exe" blob 455 size could not be found
>   tree 50210267: file "renamed-file-for-privacy.exe" blob 456 size could not be found
>   tree 50210267: file "renamed-file-for-privacy.rar" blob 286 size could not be found
>   tree 50210267: file "renamed-file-for-privacy.rar" blob 287 size could not be found
>   tree 50210267, blob 75ac3db0: not found in index
>   tree 50210267, blob 10ba19c1: not found in index
>   tree 50210267, blob e26bac8c: not found in index
>   tree 50210267, blob 9b4bc577: not found in index
> error for tree db541381:
>   tree db541381: file "renamed-file-for-privacy.exe" blob 455 size could not be found
>   tree db541381: file "renamed-file-for-privacy.exe" blob 456 size could not be found
>   tree db541381: file "renamed-file-for-privacy.rar" blob 286 size could not be found
>   tree db541381: file "renamed-file-for-privacy.rar" blob 287 size could not be found
>   tree db541381, blob 75ac3db0: not found in index
>   tree db541381, blob 10ba19c1: not found in index
>   tree db541381, blob e26bac8c: not found in index
>   tree db541381, blob 9b4bc577: not found in index
> error for tree d96189be:
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 997 size could not be found
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 998 size could not be found
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 1003 size could not be found
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 1004 size could not be found
>   tree d96189be, blob c8a1b47d: not found in index
>   tree d96189be, blob 5686f170: not found in index
>   tree d96189be, blob 9f486bb2: not found in index
>   tree d96189be, blob fff87063: not found in index
> Fatal: repository contains errors
> 
> **akrabu-mac-mini:~ akrabu$ restic rebuild-index**
> repository 3cc4819d opened successfully, password is correct
> counting files in repo
> [2:47:06] 100.00%  825174 / 825174 packs
> finding old index files
> saved new indexes as [c787a45a a7dfd8e0 903d06c1 b7269c00 52fdfdc2 4942a003 b34fab35 1427f051 aca37d00 f2284bd5 3dd4877f e50f1b15 a3d06be3 89c6279d 9444fa9b af455d06 7e92e8d7 c2b12db6 58d9d9e7 bddffbf0 174d817b ffe668ca 7a082654 b9efaa9
> 7 5679c697 d4b57098 ce0b53f9 a7fe27b6 835e75ba 3233dff2 039d14ec e565c722 bd701854 c1607efc d6f2c973 fae7799f 3fd1bb71 32e158aa 43156b44 ee20a6aa e1b3302f cb86f623 938d6e8b 9b001e86 0d76b515 cd06ea51 1081eb80 c6ef0624 6efc5352 fd54800e
> 2f9d76b7 eff99f5d 0e15bd5f 8af65b73 eac8895c 1dfc9fb6 cd437140 8f7a5468 2cbf67f6 51e96162 6c843a05 c6a368be 5349cca7 1e9dd717 65f57505 b5e3e316 63dd9e98 c257c64d a399a195 e51c769c d57fb6b3 8376263b 5dbc97f8 4efd36b2 96ae0d86 25c33b59 2a
> e99cba 185049c5 ea440b9f 614334b6 8e5ae202 cfb47146 2b7dbca1 7bf80c88 9624d54a 2fac0ad0 0a5da120 3903da33 df515379 6b01e606 8b3973ab d548e13c a1cb61b8 3d06db4d 1eb5b119 fc56ba12 38762741 b7d0dda8 aca298df f6a8dbe5 dbc3a124 a1fa1f08 96fb
> 890a 32fa1870 8d3fe91d 497eef71 3b89d193 64be228f 356f0051 b9c88e03 420b8bdc c8f5995d aebe4c65 c4769387 d856b74d af616b1d b662f119 6d81ba0a 6c7912fd 3e795bc1 a7ffe275 bdb8ceb1 9e668581 309d7b0d 596e0cca 705e141e 68077e9e a50b75b3 19ac70
> 41 e098aafc b94f28a9 8bc081b7 346428c0 e7bb25c0 6efabc17 4f257f18 b3c46365 79f21c2c 7e3f31f4 13d6ea4b 126f333c edf0151b 40625ed5 2ee1f644 81d04e31 259b0c9f a5b7c6e9 fe2e5df8 9d50015e 33e804e0 89e5fd31 64fdef2f 45238299 caf73cda 211a7d4e
>  78bb32d9 bb3052cd 61ff8ba0 9d4ad4e5 f6176931 be620b8e 5cea1f93 af2e4eb4 07156dd5 fbb7b638 42fa4295 738702b2 5aa7e3d6 0b8afd36 5bde039d 71d862bb fec93bbc 20413584 724a9e2d be9f707e cf9977be 9aedf982 bc1e0144 35128cad 16979e93 68a2f118 6
> bfa82d2 eaec4186 dd357866 8396c701 f5e45555 1de8d6c0 ad91fb16 9d251eb6 e95a759d 56a9292a fe61873b 1b53264f 50f11d26 4a6a598f 9c936bb2 4d168190 1b2f8143 85628245 4cfdace7 e825e71e 310f7df7 6f5608ac e0decd04 99e33b6d 9c532391 1970afb1 d5a
> ded6b 66029902 e532d9b6 a24d6a79 3c3a6aa1 e64cecf9 9dec9f6c be299d04 895ae433 f5c26478 e0c1b6b5 c2ad9565 9bcf3eae b53f15d4 e88f11ac c7b7a519 8076fd86 653cbe1f ee48efcd f4dab8bb 0340fc61 ceea73f0 d8cb0884 e8b39b87 39e6060d 019b0a1a 500d5
> 4b4 f9cb1089 cec2877c 962a4aba d306aace 2e274dbb 6abe818a b9177812 94a3eca3 5dd96b51 1b1e0f4a 0d73ef68 ca0afdfb 5daab2b9 d189b7d3 c9d7c865 55d3bc16 70329f81 6ad3dd76 78ee875a fe16ceb5 38235000 5f1293f3 3f287143 1a3c6b14 ecbb8e79 233d364
> e 80639269 51042631 8397b79f db7f03a0 291c2c14 05d6896e e599b2f8 0d8103af 3914707b 93f1bb38 8c015a49 f6850448 f188aca6 289908ca d619e138 6bfc0edd]
> remove 276 old index files
> 
> akrabu-mac-mini:~ akrabu$ restic prune
> repository 3cc4819d opened successfully, password is correct
> counting files in repo
> building new index for repo
> [2:46:49] 100.00%  825174 / 825174 packs
> repository contains 825174 packs (10729119 blobs) with 3.719 TiB
> processed 10729119 blobs: 0 duplicate blobs, 0 B duplicate
> load all snapshots
> find data that is still in use for 897 snapshots
> [20:27] 100.00%  897 / 897 snapshots
> Fatal: number of used blobs is larger than number of available blobs!
> Please report this error (along with the output of the 'prune' run) at
> https://github.com/restic/restic/issues/new
> 
> **akrabu-mac-mini:~ akrabu$ restic check**
> using temporary cache in /var/folders/z5/x7mpskwd2m54cz0l4wvx807h0000gn/T/restic-check-cache-207344503
> repository 3cc4819d opened successfully, password is correct
> created new cache in /var/folders/z5/x7mpskwd2m54cz0l4wvx807h0000gn/T/restic-check-cache-207344503
> create exclusive lock for repository
> load indexes
> check all packs
> check snapshots, trees and blobs
> error for tree b8d5a4c8:
>   tree b8d5a4c8: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree b8d5a4c8, blob 2b0a0f2d: not found in index
> error for tree 86a95941:
>   tree 86a95941: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree 86a95941, blob 2b0a0f2d: not found in index
> error for tree c1de8831:
>   tree c1de8831: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree c1de8831, blob 2b0a0f2d: not found in index
> error for tree 28c9bd82:
>   tree 28c9bd82: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree 28c9bd82, blob 2b0a0f2d: not found in index
> error for tree fdcb8a77:
>   tree fdcb8a77: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree fdcb8a77, blob 2b0a0f2d: not found in index
> error for tree e6eb0d8d:
>   tree e6eb0d8d: file "renamed-file-for-privacy.pdf" blob 0 size could not be found
>   tree e6eb0d8d, blob 2b0a0f2d: not found in index
> error for tree 50210267:
>   tree 50210267: file "renamed-file-for-privacy.exe" blob 455 size could not be found
>   tree 50210267: file "renamed-file-for-privacy.exe" blob 456 size could not be found
>   tree 50210267: file "renamed-file-for-privacy.rar" blob 286 size could not be found
>   tree 50210267: file "renamed-file-for-privacy.rar" blob 287 size could not be found
>   tree 50210267, blob 75ac3db0: not found in index
>   tree 50210267, blob 10ba19c1: not found in index
>   tree 50210267, blob e26bac8c: not found in index
>   tree 50210267, blob 9b4bc577: not found in index
> error for tree db541381:
>   tree db541381: file "renamed-file-for-privacy.exe" blob 455 size could not be found
>   tree db541381: file "renamed-file-for-privacy.exe" blob 456 size could not be found
>   tree db541381: file "renamed-file-for-privacy.rar" blob 286 size could not be found
>   tree db541381: file "renamed-file-for-privacy.rar" blob 287 size could not be found
>   tree db541381, blob 75ac3db0: not found in index
>   tree db541381, blob 10ba19c1: not found in index
>   tree db541381, blob e26bac8c: not found in index
>   tree db541381, blob 9b4bc577: not found in index
> error for tree d96189be:
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 997 size could not be found
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 998 size could not be found
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 1003 size could not be found
>   tree d96189be: file "renamed-file-for-privacy.mov" blob 1004 size could not be found
>   tree d96189be, blob c8a1b47d: not found in index
>   tree d96189be, blob 5686f170: not found in index
>   tree d96189be, blob 9f486bb2: not found in index
>   tree d96189be, blob fff87063: not found in index
> Fatal: repository contains errors

**Comment by rawtaz** [comment]
@akrabu How did this turn out in the end for you? Did you create a new repository or how did you tackle it? The times I've seen those types of errors it's been due to corrupted hardware or disk. Personally I've then made a fresh backup because that was easier than fixing the old one.

**Comment by akrabu** [comment]
Brand new drives in a Synology unit.  I just created a new repo and started from scratch.

**Comment by rawtaz** [comment]
Okay, makes sense. If it happens again, please open a thread in the forum instead, that's a better forum for this type of issue, and has a higher chance of getting attention/help. Thanks!
