### ISSUE TITLE
Restic silently won't init on FreeBSD 11.U2

### ISSUE THREAD

**Issue by Henry78** [restic/restic#2355]
Output of `restic version`
--------------------------
```
B2_ACCOUNT_ID=<replaced>
B2_ACCOUNT_KEY=<replaced>
B2_BUCKET=<replaced>
```

`restic 0.9.5 compiled with go1.12.6 on freebsd/amd64`

How did you run restic exactly?
-------------------------------
`restic -r b2:bisChcA2KHVJN8MfoEA9Q init`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze

Expected behavior
-----------------
Ran the same script (env + command) on my Linux Box from same network, yes on an already initialized repo/bucket:
`Fatal: create repository at b2:<replaced> failed: config already exists`

Actual behavior
---------------
restic just hangs - forever(? at least 20 minutes)

Steps to reproduce the behavior
-------------------------------
(Fresh) Install FreeBSD 11 or 12 in VirtualBox or use a FreeBSD jail on FreeNAS 11.U2
```
pkg install restic
source init_restic # set env
restic -r b2:<replaced> init
```

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

**Comment by fd0** [comment]
Hm, interesting. Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it.

**Comment by Henry78** [comment]
**Hu!**

It works now. Creating the debug binary and wondering why after the build restic works as expected, i dug around.

Found out, restic works after installing the package `security/ca_root_nss`. On a fresh installation of FreeBSD (11.U2 and 12) `ca_root_nss` isn't installed.

Sadly I don't know about FreeNAS packaging, but the problem appears to be a missing dependency on `ca_root_nss`. I vote for at least a note about this dependency in the docs.

Rest of this post is a console log of a test:
```
[root@free112 ~]# pkg remove ca_root_nss
No packages matched for pattern 'ca_root_nss'

Checking integrity... done (0 conflicting)
1 packages requested for removal: 0 locked, 1 missing
[root@free112 ~]# 
[root@free112 ~]# . init_restic 
[root@free112 ~]# sh run_restic 
Wed Jul 31 20:36:45 CEST 2019
Init repo...
  signal interrupt received, cleaning up
Wed Jul 31 20:37:49 CEST 2019
[root@free112 ~]# 
[root@free112 ~]# 
[root@free112 ~]# pkg install ca_root_nss
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	ca_root_nss: 3.45

Number of packages to be installed: 1

Proceed with this action? [y/N]: y
[1/1] Installing ca_root_nss-3.45...
[1/1] Extracting ca_root_nss-3.45: 100%
Message from ca_root_nss-3.45:

********************************* WARNING *********************************

FreeBSD does not, and can not warrant that the certification authorities
whose certificates are included in this package have in any way been
audited for trustworthiness or RFC 3647 compliance.

Assessment and verification of trust is the complete responsibility of the
system administrator.

*********************************** NOTE **********************************

This package installs symlinks to support root certificates discovery by
default for software that uses OpenSSL.

This enables SSL Certificate Verification by client software without manual
intervention.

If you prefer to do this manually, replace the following symlinks with
either an empty file or your site-local certificate bundle.

  * /etc/ssl/cert.pem
  * /usr/local/etc/ssl/cert.pem
  * /usr/local/openssl/cert.pem

***************************************************************************
[root@free112 ~]# 
[root@free112 ~]# 
[root@free112 ~]# 
[root@free112 ~]# sh run_restic 
Wed Jul 31 20:38:01 CEST 2019
Init repo...
Fatal: create repository at b2:bisChcA2KHVJN8MfoEA9Q failed: config already exists

Wed Jul 31 20:38:05 CEST 2019
[root@free112 ~]# 
[root@free112 ~]# pkg remove ca_root_nss
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
	ca_root_nss-3.45

Number of packages to be removed: 1

Proceed with deinstalling packages? [y/N]: y
[1/1] Deinstalling ca_root_nss-3.45...
[1/1] Deleting files for ca_root_nss-3.45: 100%
[root@free112 ~]# 
[root@free112 ~]# sh run_restic 
Wed Jul 31 20:38:14 CEST 2019
Init repo...
  signal interrupt received, cleaning up
Wed Jul 31 20:39:28 CEST 2019
[root@free112 ~]# 

```

**Comment by rawtaz** [comment]
Hm, I wonder if there's a way we can catch this in the restic code.

**Comment by garrmcnu** [comment]
Can reproduce this on FreeBSD as described, the reason for the hang is the call to `b2.NewClient()` never returns because it is stuck in an infinite loop. The `b2_authorize_account` request fails with an error "x509: certificate signed by unknown authority", this is treated as a transient error and so it retries indefinitely (and keeps failing).

Can also reproduce on Linux by using a self-signed certificate for the root certificates

    restic --cacert ~/certs/self-signed.crt -r b2:<repo> snapshots

Have tested with a patch to [kurin/blazer](https://github.com/kurin/blazer) module that handles this error by returning it to application instead of retrying and the `restic` command then fails as expected with the above error message.

As an alternative, Backblaze has recently introduced support for the [S3 API](https://www.backblaze.com/blog/backblaze-b2-s3-compatible-api), don't see this issue with this interface, i.e. command doesn't loop indefinitely, it fails immediately with the same error message.
