### ISSUE TITLE
Long enough host-names are truncated and can be used as such.

### ISSUE THREAD

**Issue by Ricky-Tigg** [restic/restic#2356]
`restic 0.9.5 compiled with go1.12.2 on linux/amd64`

Long enough host-names are truncated and can bu used as such.

Original situation:
```
$ hostnamectl status;echo "/etc/hosts is:";cat /etc/hosts;echo "/etc/hostname is:";cat /etc/hostname
   Static hostname: localhost.localdomain
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: 04e340f14e664fd390d2753dd07c44eb
           Boot ID: d1e8f26c18ee4ba881d5e5da4b1809b9
  Operating System: Fedora 30 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:30
            Kernel: Linux 5.1.20-300.fc30.x86_64
      Architecture: x86-64
/etc/hosts is:
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
/etc/hostname is:
localhost.localdomain
```
Execute command:
```
$ restic -r /run/media/$USER/maxell/Varmuuskopiot snapshots
(...)
ID        Time                 Host                  Tags        Paths
----------------------------------------------------------------------------------------
0e9c0bd4  2019-07-30 19:28:39  localhost-localdomai              /var/lib/libvirt/images
----------------------------------------------------------------------------------------
```
As noticeable in Host column, mentioned name is truncated. Let's ensure no change have been applied to the system by running `sudo systemctl restart systemd-hostnamed`. You also might close and reopen the terminal emulator to ensure that no change have occurred and execute once more the first mentioned command.

At last the truncated name could even be used as illustrated as follow.
```
$ restic -r /run/media/$USER/USB forget --host localhost-localdomai --keep-last 1
(...)
ID        Time                 Host                  Tags        Reasons        Paths
-------------------------------------------------------------------------------------------------------
0e9c0bd4  2019-07-30 19:28:39  localhost-localdomai              last snapshot  /var/lib/libvirt/images
-------------------------------------------------------------------------------------------------------
```

**Comment by Ricky-Tigg** [comment]
Despite the fields `Transient` or/and `Pretty` host-names were not exhibited in the first command, nevertheless truncated host-name had to be registered by one of them; since when I rebooted the system the host-name was at last recognised properly by Restic.

**Comment by fd0** [comment]
Ah, yeah, when the host name is displayed in the CLI it may be truncated. It's not in the underlying data structure, you can check this with `restic cat snapshot 0e9c0bd4` which gives you the JSON data structure saved in the repo.
