### ISSUE TITLE
`os.Exit(0)` in lock.go prevents clean exit in main command

### ISSUE THREAD

**Issue by rakoo** [restic/restic#236]
Because of [this line](https://github.com/restic/restic/blob/3f8f391d0b917d3daa711d17421f3c35f8a756bc/cmd/restic/lock.go#L139), an interrupt signal automatically closes the application and a command can't have any proper cleanup of its own

**Comment by fd0** [comment]
Any suggestion on how to work around that?

**Comment by fd0** [comment]
Proposal: have a global list of cleanup handlers that are run when SIGINT is received, so that e.g. the mount command can leave a umount cleanup handler. Thoughts?
