### ISSUE TITLE
New Server Same Data

### ISSUE THREAD

**Issue by todd1794** [restic/restic#2360]
Output of `restic version`
--------------------------

restic 0.9.4 compiled with go1.11.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

To use a snapshot from another host as the source for new host. Example I just rebuilt the system disk of a file server and so now it is a NEW host. So the couple of years of snapshots that I have don't line up and I need to start over the backups from scratch.  I would like a:

restic --host-equivalent <host_hash>  

which might need a:

restic --host-hash [Which outputs existing hash]

and

restic --snapshot-host-hash [Yeah which outputs the hash of the snapshot] 

What are you trying to do?
--------------------------

Use existing snapshots even when the host has changed. Because the data did not. 

Did restic help you or made you happy in any way?
-------------------------------------------------

Every freaking day! In case that is not clear RESTIC makes me happy EVERY freaking DAY! I sleep better knowing that my data is safe.

**Comment by todd1794** [comment]
In the meantime solved with 0.9.5 and --ignore-inode option and rename the host back to old hostname.

**Comment by MichaelEischer** [comment]
The backup command already has the `--parent` option which should solve this use case.
@todd1794 Did I miss something here or can we close this issue?

**Comment by MichaelEischer** [comment]
Closing as there has been no feedback.
