### ISSUE TITLE
Better documentation on how to fix various restic check 

### ISSUE THREAD

**Issue by Narfinger** [restic/restic#2361]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
restic check and prune give various errors such as
`tree 5316c81c: file "ref.bib" blob 0 size could not be found`      

I think the documentation should have a rough idea on what will fix these errors in addition to some ways to fix them. For example, fixing some pack checksum mismatch errors can be solved by deleting the pack file, updating index and pruning (of course this will potentially delete data).
Having these in one central part in the documentary (instead of various github issues) will be really helpful. Of course, appropriate warnings are required but otherwise it is difficult to know which files are savely backed up and which are not.

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes! On my bad setup it is much better than other solutions I tried and the gcs backup saves me quite a bit of money :D

**Comment by rawtaz** [comment]
Thanks for reporting the need for better documentation @Narfinger. I'm closing this issue in favor of #2683.
