### ISSUE TITLE
Upload partial index on SIGINT

### ISSUE THREAD

**Issue by HaleTom** [restic/restic#2367]
Output of `restic version`
--------------------------

    restic 0.9.5 compiled with go1.12.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Upload partial index on receiving ^C / SIGINT

Forum discussion:
https://forum.restic.net/t/checkpoints-for-large-snapshots/1910/12

What are you trying to do?
--------------------------

Reduce data costs and time spent resuming backups

Did restic help you or made you happy in any way?
-------------------------------------------------
I'm really glad you asked this question!

I imagine it would be very easy to just see issues on software that people generally use without issue every day. From the squeaky wheel effect, a skewed view could easily form.

I recently evaluated (all?) linux backup programs. restic was the winner for technical reasons.

restic was also the winner because of the community - the positive and supportive forum and the exemplary way that @fd0 communicates.

restic saves my memories of my loved ones and experiences in the form of photos and videos.

restic also stores my mp3 library which I use to lift my mood.

Thanks to all involved for creating and maintaining this software <3

**Comment by MichaelEischer** [comment]
Restic already uploads an intermediate index every few minutes. The remaining part to quickly resume interrupted backups is already tracked in #1183 and #2280.
