### ISSUE TITLE
Error messages 'build failed: exit status 2', 'exit status 1' while Fedora default go-packages are installed

### ISSUE THREAD

**Issue by Ricky-Tigg** [restic/restic#2371]
Model took from section [Backing up your system without running restic as root.](https://restic.readthedocs.io/en/stable/080_examples.html#backing-up-your-system-without-running-restic-as-root).

Error messages `build failed: exit status 2`, `exit status 1`while _Fedora_ default go-packages are installed:

Commands executed while _Fedora_ distribution default _go_ packages are installed:
```
# useradd -m citser -p <password>; mkdir -p ~citser/{bin/restic,restic}; git clone https://github.com/restic/restic.git ~citser/restic/
# go version
go version go1.12.2 gccgo (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1) linux/amd64
# export GOOS=linux GOARCH=amd64 go build; cd ~citser/;
# chmod +x restic/build.go; cd restic/
```
Commands beginning with `go: finding` were replaced by `(...)`.
```
# LANG=C go run build.go -o ~/bin/restic/
go: finding golang.org/x/lint v0.0.0-20190227174305-5b3e6a55c961
(...)
go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
go build: when using gccgo toolchain, please pass compiler flags using -gccgoflags, not -gcflags
go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
# github.com/restic/restic/internal/restic
internal/restic/node_linux.go:22:18: error: incompatible type for field 1 in struct construction (cannot use type syscall.Timespec_sec_t as type int64)
   22 |   {Sec: utimes[0].Sec, Nsec: utimes[0].Nsec},
      |                  ^
internal/restic/node_linux.go:22:39: error: incompatible type for field 2 in struct construction (cannot use type syscall.Timespec_nsec_t as type int64)
   22 |   {Sec: utimes[0].Sec, Nsec: utimes[0].Nsec},
      |                                       ^
internal/restic/node_linux.go:23:18: error: incompatible type for field 1 in struct construction (cannot use type syscall.Timespec_sec_t as type int64)
   23 |   {Sec: utimes[1].Sec, Nsec: utimes[1].Nsec},
      |                  ^
internal/restic/node_linux.go:23:39: error: incompatible type for field 2 in struct construction (cannot use type syscall.Timespec_nsec_t as type int64)
   23 |   {Sec: utimes[1].Sec, Nsec: utimes[1].Nsec},
      |                                       ^
build failed: exit status 2
exit status 1
```

**Comment by fd0** [comment]
Hey, there are two different implementations of the Go compiler: `go` and `gccgo`. You have the latter installed, but need the former, that's the package `golang` in Fedora. Unfortunately, `gccgo` is [not supported](https://restic.readthedocs.io/en/latest/020_installation.html#from-source) (and apparently it does not compile).

Please report back if this resolves your issue!

**Comment by Ricky-Tigg** [comment]
Hi. here was few component's installed states at report time:
```
$ dnf list installed | grep -Ei 'gcc|gccgo|golang'
gcc.x86_64                                 9.1.1-1.fc30                      @updates
gcc-gdb-plugin.x86_64                      9.1.1-1.fc30                      @updates
gcc-go.x86_64                              9.1.1-1.fc30                      @updates
golang.x86_64                              1.12.7-1.fc30                     @updates
golang-bin.x86_64                          1.12.7-1.fc30                     @updates
golang-src.noarch                          1.12.7-1.fc30                     @updates 
libgcc.x86_64                              9.1.1-1.fc30                      @updates
```
Suggested packages by Bash when attempting to execute `go run build` while no go-packages were yet installed were `gcc-go` and `golang-bin`.

From now _gcc-go_ has been removed
```
$ go version
go version go1.12.7 linux/amd64
$ sudo su
# pwd
/home/yk
# chmod +x ~citser/restic/build.go; go run ~citser/restic/build.go -o ~citser/bin/restic/
copying files from /home/yk to /tmp/restic-build-240242709/src failed: open /home/yk/.config/opera/oauc_pipe: no such device or address
exit status 1
```
Apparently _Go_ attempted to copy from the place within a desktop session I am logged in.

**Comment by fd0** [comment]
Ok, now we're one step closer. You need to follow the instructions from [the documentation](https://restic.readthedocs.io/en/latest/020_installation.html#from-source) now, which tells you to run `go run -mod=vendor build.go` **within the directory containing the source code**. In your case, it's probably:

```
# su - citseer
$ cd restic
$ go run -mod=vendor build.go
```

**Comment by Ricky-Tigg** [comment]
Hey,  I realized relevant information was in that documentation; thank you for the link. These are the outputs from the commands executed:
```
$ su - citser && cd restic
[...]
$ go run -mod=vendor build.go -o ~citser/bin/restic/
go build github.com/restic/restic/cmd/restic: build output "/home/citser/bin/restic/" already exists and is a directory
build failed: exit status 1
exit status 1
$ exit
[...]
$ su - citser && cd restic
[...]
$ go run -mod=vendor build.go -o ~citser/bin/restic/
build flag -mod=vendor only valid when using modules
```
Since that, the last output is produced when iterating `go run -mod=vendor build.go -o ~citser/bin/restic/`.

**Comment by fd0** [comment]
I have no idea what's going on. Are you sure the paths are exactly as you copied them to this issue? What does `go env` print?

**Comment by Ricky-Tigg** [comment]
Verification:
```
$ pwd
/home/citser
[citser@localhost ~]$ tree -ifdL 2 -P restic
.
./bin
./bin/restic
./restic
[...]
```
I probably lack knowledge to interpret this output:
```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/citser/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/citser/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build860850753=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by moritzdietz** [comment]
I think your problem is `CGO_ENABLED="1"`. Turn that off and see if it works.

**Comment by Ricky-Tigg** [comment]
There is no indication at which location _Restic_ would attempt to install itself by default, so I kept on using the _go_-tool's option `-o` to specify a directory same as the one in _Restic_'s documentation.
```
$ export CGO_ENABLED="0"; go env | grep CGO_ENABLED
CGO_ENABLED="0"
$ go run -mod=vendor build.go -o ~citser/bin/restic/
go build github.com/restic/restic/cmd/restic: build output "/home/citser/bin/restic/" already exists and is a directory
build failed: exit status 1
exit status 1
```

**Comment by moritzdietz** [comment]
Normally go produces the binary alongside the source code in the same directory. This is when you run `go build`. When you run `go install` the binary will instead be placed in the `bin` directory inside your defined `GOPATH`; in your case this is `GOPATH="/home/citser/go"`.

**Comment by Ricky-Tigg** [comment]
Hey, I might have solved present case winch then was not an issue neither then [#2365](https://github.com/restic/restic/issues/2365).  `CGO_ENABLED` has been set back to default value, `1`.

Since an error message was still produced with those legitimate commands:
```
[root@localhost yk]# cd ~citser/restic/; chown root:citser ../restic/; chmod 750 ../restic/
# su - citser
[citser@localhost ~]$ go run -mod=vendor build.go
build flag -mod=vendor only valid when using modules
```
I deducted that _Go_ had been expected along with option `-o` a **file**'s path while from the beginning i had been specifying a **directory**'s path. Therefore some modifications were brought to those commands which affected favourably some outputs:
```
[citser@localhost ~]$ exit
[root@localhost restic]# go run -mod=vendor build.go && ls -l
[...]
-rwxr-xr-x.  1 root root 19069024 15. 8. 11:15 restic
```
In _GNOME_ environment v. 3.32.2 , instead of a **generic** application icon here illustrated, a _Restic_-**specific** icon would be welcome if there is time enough to be  implemented.

![GNOME_v  3 32 2_Restic_binary](https://user-images.githubusercontent.com/26058215/63083732-27f37180-bf52-11e9-919c-7c7ee355bf07.png)

**Comment by fd0** [comment]
Ah, you specified a directory with `-o`? That does not work, I'm glad you figured that out!

The other thing is this:
```
[root@localhost yk]# cd ~citser/restic/; chown root:citser ../restic/; chmod 750 ../restic/
# su - citser
[citser@localhost ~]$ go run -mod=vendor build.go
build flag -mod=vendor only valid when using modules
```
I'm not sure what you're trying to do here, but it looks like the restic source code is put into `/home/citser/restic`. When you switch to that user using `su - citser`, you'll end up in `/home/citser`. Running `go run -mod=vendor build.go` in `citser`'s home directory can't work, the file `build.go` is in the subdir `restic/`.

The error message you get (something about "Modules") is probably related: Go informs you (in its own cryptical way) that in the current directory (`/home/citser`) there's no `go.mod` file.

Can you try changing to `/home/citser/restic` and then run the command again?

**Comment by Ricky-Tigg** [comment]
I might have been lucky to find out option `-o` expected a file since apparently official go lacks manual:
```
$ man go run
No manual entry for go
```
Neither `rpm -ql golang` returned anything related to it. Attempting to run _Go_ as user `cister `produced an unexpected message related to permissions, which are set to cover enough  `cister 's needs.
```
[root@localhost restic]# cd ~citser/; chown root:citser bin/; chmod 750 bin/; ls -l
[...]
drwxr-x---.  2 root   citser 4096 15. 8. 10:29 bin
drwxrwxr-x.  3 citser citser 4096 14. 8. 21:08 go
drwxr-x---. 12 root   citser 4096 16. 8. 10:34 restic
# su - citser
[citser@localhost ~]$ cd restic/; go run -mod=vendor build.go -o ../bin/restic
go build github.com/restic/restic/cmd/restic: open /home/citser/bin/restic: permission denied
build failed: exit status 1
exit status 1 
```

**Comment by fd0** [comment]
Uhm, the option `-o` is for the program `build.go` that I wrote, so you won't find anything in documentation related to Go.

**Comment by Ricky-Tigg** [comment]
Hey. Adequate permissions do not allow Restic to perform from dedicated user. Commands used:
```
# pwd; export RESTIC_REPOSITORY=/run/media/yk/ULKO/Varmuuskopiot/Fedora/ RESTIC_PASSWORD=password; cd /run/media/yk/ULKO/Varmuuskopiot/
/home/citser/bin
# chown -R root:citser Fedora/; chmod -R 770 Fedora/;ls -l Fedora/; exit
[...]
-rwxrwx---.   1 root citser  155 20. 8. 13:07 config
drwxrwx---. 258 root citser 4096 20. 8. 13:07 data
drwxrwx---.   2 root citser 4096 20. 8. 13:07 index
drwxrwx---.   2 root citser 4096 20. 8. 13:07 keys
drwxrwx---.   2 root citser 4096 20. 8. 13:07 locks
drwxrwx---.   2 root citser 4096 20. 8. 13:07 snapshots
```
External drive aimed to receive the backup has those capabilities:
```
$ mount | fgrep /run/media/$USER
/dev/mapper/luks-70ede6de-2bdb-433a-8ee4-f97cd4ef711a on /run/media/yk/ULKO type ext4 (rw,nosuid,nodev,relatime,seclabel,uhelper=udisks2)
```
Several outputs persist to involve permissions while above outputs indicate that they were already set at their higher level:
```
$ su - citser
$ export RESTIC_REPOSITORY=/run/media/yk/ULKO/Varmuuskopiot/Fedora/ RESTIC_PASSWORD=password; cd ~/bin/; restic --exclude={/dev,/media,/mnt,/proc,/run,/sys,/tmp,/var/tmp,$RESTIC_REPOSITORY} backup /
Fatal: unable to open repo at /run/media/yk/ULKO/Varmuuskopiot/Fedora/: ReadDir: open /run/media/yk/ULKO/Varmuuskopiot/Fedora/keys: permission denied
```
May Restic be involved in that state?

**Comment by moritzdietz** [comment]
If I may: since this doesn't have anything to do with the initial issue description, wouldn't it be better to move this troubleshooting to the forum maybe? https://forum.restic.net/

**Comment by fd0** [comment]
I agree, let's move this to the forum, which will also involve more people so we get more ideas. We can always come back to the issue tracker (which we're using to track bugs and feature requests exclusively) when we decide it's a bug.

From what I've seen so far I'm quite confident that it's not a problem in restic, but I don't have any idea what it may be. The next step would be to run `strace` on it to find out what restic is doing exactly. It looks like restic is calling the `readdir` or `getdirents` syscall on the `keys/` subdir, but gets `EPERM` back from the kernel.

But please, move this to the forum. Thanks! :smile:

**Comment by Ricky-Tigg** [comment]
I was prompt to put in action, [here](https://forum.restic.net/t/execution-as-unprivileged-users-to-perform-a-complete-backup-in-conflict-with-linux-permissions/2018/3) visible, an undoubtedly wise suggestion. Discussion's tittle there may be appealing enough but not accurate in case there is **no conflict**.
