### ISSUE TITLE
TestMetadataChanged fails on systems with UID 51234 taken by a user

### ISSUE THREAD

**Issue by vrusinov** [restic/restic#2372]
Output of `restic version`
--------------------------

$ ./restic version
restic 0.9.5-dev (compiled manually) compiled with go1.12.5 on linux/amd64

How did you run restic exactly?
-------------------------------

`go test ./...` in a fresh git checkout

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

n/a

Expected behavior
-----------------

tests pass

Actual behavior
---------------

```
--- FAIL: TestMetadataChanged (0.01s)
    testing.go:30: using low-security KDF parameters for test
    config.go:65: disabling check of the chunker polynomial
    archiver_test.go:2043: chdir to /tmp/restic-test-488507700
    archiver_test.go:2091: metadata does not match:
        {*restic.Node}.User:
        	-: ""
        	+: "<username>"
    panic.go:406: chdir back to /<...>/restic/internal/archiver
```

Steps to reproduce the behavior
-------------------------------

Run tests on a system where UID 51234 is defined and occupied by a user.

$ id 51234 > /dev/null && echo "UID exists"
UID exists

Do you have any idea what may have caused this?
-----------------------------------------------

Yes, this part of the test:

```
	if runtime.GOOS != "windows" {
		want.UID = 51234
		want.GID = 51235
	}
	// no user and group name
	want.User = ""
	want.Group = ""

	// make another snapshot
	snapshotID, node3 := snapshot(t, repo, fs, snapshotID, "testfile")

	// make sure that metadata was recorded successfully
	if !cmp.Equal(want, node3) {
		t.Fatalf("metadata does not match:\n%v", cmp.Diff(want, node3))
	}
```

Do you have an idea how to solve the issue?
-------------------------------------------

One of:
- don't check for username at all (check for UID)
- pick UID which is guaranteed to be unoccupied (negative? will this work?)

Did restic help you or made you happy in any way?
-------------------------------------------------

yup :)

**Comment by vrusinov** [comment]
Please see proposed (although dumb) fix in https://github.com/restic/restic/pull/2373

**Comment by rawtaz** [comment]
Seems like a pretty solid fix even if it's a bit ugly. But trying to guess or use "known" to be unused IDs seem like more of a gamble. Either what you're doing now, or removing the names from `want` and `node3` entirely seems like a proper fix to me. Preferrably the latter. Or simply copying the names from `node3` into `want` before comparison.
