### ISSUE TITLE
Remove username and password from REST repo URLs in output

### ISSUE THREAD

**Issue by monkeyhybrid** [restic/restic#2379]
Output of `restic version`
--------------------------

`restic 0.9.5 compiled with go1.12.4 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Currently, the username and password for HTTP basic auth needs to be included as part of the repo URL string, e.g. `rest:https://foo:pass@host:8000/foo`.

This means that whenever the repo URL is displayed in Restic's normal output, it shows potentially sensitve credentials. This isn't so bad if you're running the command interactively, but it's not ideal for logging Restic's output.

It would be great if Restic didn't show the HTTP username and password in output. It would be even better if the HTTP username and password can be passed to Restic via their own command-line arguments or environment variables, like S3 auth, and never add them to the URL string at all.

What are you trying to do?
--------------------------

Use HTTP Basic Auth without the username and password being output in clear text.

Did restic help you or made you happy in any way?
-------------------------------------------------

All the time. :)

**Comment by MichaelEischer** [comment]
This has been fixed by #2658 which will be include in the next released restic version. In addition the URL to a repository can be passed via a file #2910.
