### ISSUE TITLE
 S3 repo prune fails with fatal error

### ISSUE THREAD

**Issue by underhillian** [restic/restic#2382]
Output of `restic version`
--------------------------

> restic 0.9.5 compiled with go1.12.8 on linux/amd64

Describe the issue
------------------

I attempted to run a routine "forget and prune" operation on an S3 repo via:

> export RESTIC_REPOSITORY=...
> export RESTIC_PASSWORD_FILE=...
> restic --cache-dir="/var/restic/cache/"  --prune  --option=s3.connections=16 \
> 	--keep-daily=15 --keep-weekly=9 --keep-monthly=7 --keep-yearly=1 
> 	forget
> 
The "forget" phase appeared to complete normally, but the "prune" phase produced about 10k lines of the general forms:

> Load(<data/03b4da09e5>, 591, 7077923) returned error, retrying after 2.426057524s: The operation is not valid for the object's storage class
> 
> pack file cannot be listed 003ace659843d3b00a980052f532dadb6f2b62b597f703c942606747281ee229: The operation is not valid for the object's storage class

followed by

> repository contains 2098 packs (7065 blobs) with 10.511 GiB
> processed 7065 blobs: 0 duplicate blobs, 0 B duplicate
> load all snapshots
> find data that is still in use for 24 snapshots
> [0:01] 100.00%  24 / 24 snapshots
> 
> Fatal: number of used blobs is larger than number of available blobs!
> Please report this error (along with the output of the 'prune' run) at
> https://github.com/restic/restic/issues/new
> 

Subsequently attempting to rebuild the repo index failed with similar errors.  A subsequent automated backup (which ran before I noticed any problems) (apparently) succeeded.

I use the same script to "forget and prune" other S3 repos.   Interestingly, these operations (carried out on the same day with the same version of restic, etc.) all succeeded.  So the issue must be somehow connected to one specific repo.

No idea what happened or what I might do to repair the repo at this point.

**Comment by underhillian** [comment]
Oops, my error.

I had somehow set up an S3 transition rule that transitioned objects to glacier class.  The problematic objects had been transitioned, and this was the source of the issue.

I apologize for the wasted bandwidth.

**Comment by fd0** [comment]
Don't worry, thank you very much for leaving feedback after identifying the cause! :)
