### ISSUE TITLE
Switch off duplication 

### ISSUE THREAD

**Issue by git001** [restic/restic#2384]
Output of `restic version`
--------------------------

future Version

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Is it possible to tell restic do not duplicate?

What are you trying to do?
--------------------------
Our compliance have the rule that no backup tool should de-duplicate data.
What's your opinion about this topic and are there any plans to add a switch not to de-duplicate?

**Comment by pvgoran** [comment]
I think it's plainly impossible with restic. Because it employs content addressing, that is, chunks of data are stored in files whose names are derived from content hashes.

**Comment by git001** [comment]
@cfbao yep, that's an option. I just wanted to ask the community if it's an option.

**Comment by moritzdietz** [comment]
As @cfbao already said, the code in restic is built on having the deduplication built in and is a core functionality.
There won't be an option to disable this functionality.

**Comment by fd0** [comment]
While we may add a little bit of redundancy (see #256), maybe by just storing all blobs twice, such a feature would mean restructuring how restic works. That's not realistic. So, I'm closing this feature request for now, I hope you find another backup system you can use! :)
