### ISSUE TITLE
OneDrive Prune error : Fatal: number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by sharjeelsayed** [restic/restic#2385]
Output of `restic version`

restic version
restic 0.9.5 compiled with go1.12.4 on darwin/amd64

restic -r rclone:onedrive:restic_folder prune
repository avcdefgh opened successfully, password is correct
found 1 old cache directories in /Users/username/Library/Caches/restic, pass --cleanup-cache to remove them
counting files in repo
building new index for repo
Load(<data/hijklmopqr>, 591, 5147704) returned error, retrying after 720.254544ms: <data/hijklmopqr> does not exist
[30:08] 100.00%  5117 / 5117 packs
repository contains 5117 packs (30325 blobs) with 24.201 GiB
processed 30325 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 18 snapshots
[0:01] 100.00%  18 / 18 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
ERROR: passthrough failed.

--------------------------

Describe the issue

I get the above error when I run restic prune on onedrive
------------------

**Comment by MichaelEischer** [comment]
@sharjeelsayed You might want to take a look at #2642 and #2663 which also have the same problem.
