### ISSUE TITLE
S3: Incomplete credentials (supplied from env) not reported

### ISSUE THREAD

**Issue by alexswerner** [restic/restic#2388]
Output of `restic version`
--------------------------
restic 0.9.4 (v0.9.4-0-gcd9b2295) compiled with go1.10.4 on linux/amd64

How did you run restic exactly?
-------------------------------
```
$ export RESTIC_REPOSITORY="s3:https://s3.amazonaws.com/SOMETHING"
$ export AWS_ACCESS_KEY_ID="SOMETHING"
$ export AWS_SECRET_ACCES_KEY="SOMETHING"
### NOTE THE TYPO!
$ export RESTIC_PASSWORD="SOMETHING"
$ restic init
Fatal: create key in repository at s3:https://s3.amazonaws.com/SOMETHING failed: client.PutObject: Access Denied
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
AWS S3

Expected behavior
-----------------
Report on error about incomplete credentials (`AWS_SECRET_ACCESS_KEY` not found) like the aws tool from the awscli package does:

```
aws s3api list-buckets --query Owner.ID 
Partial credentials found in env, missing: AWS_SECRET_ACCESS_KEY
```

Actual behavior
---------------
Misleading error was reported that the authentication fails.

Steps to reproduce the behavior
-------------------------------
Do supply authentication for S3 backend with environment variables, but do not supply `AWS_SECRET_ACCESS_KEY`

Do you have any idea what may have caused this?
-----------------------------------------------
Not checking if the `AWS_SECRET_ACCESS_KEY` is available through any input.

Do you have an idea how to solve the issue?
-------------------------------------------
Check if the AWS_SECRET_ACCESS_KEY has been supplied before querying the server.

Did restic help you or made you happy in any way?
-------------------------------------------------
I greatly appreciate that this software. My duplicity repo got corrupted on a aborted upload and there is no way to fix it. This looks more modern and maintainable.

**Comment by garrmcnu** [comment]
Looks like this has already been done for B2, an error is reported if account ID/key is not set (#1490), added similar checks for S3 credentials.
Does it make sense to do the same for Google Cloud Storage and Azure?
