### ISSUE TITLE
Update Lock.Time as part of Refresh

### ISSUE THREAD

**Issue by ewhamilton** [restic/restic#2390]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on linux/amd64

How did you run restic exactly?
-------------------------------
I observed problem during code reading.

I confirmed issue by modifying `TestLockRefresh()` in `internal/restic/lock_test.go` and running  `go test -v lock_test.go`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
TestRepository.

Expected behavior
-----------------
Calls to lock.Refresh such as by `cmd/restic/lock.go: refreshLocks()` should update the Time field in the newly written lock so it doesn't become stale.

Actual behavior
---------------
Calls to lock.Refresh() writes a new lock with same Lock.Time value.

Steps to reproduce the behavior
-------------------------------
Run updated unit test.

Do you have any idea what may have caused this?
-----------------------------------------------
My guess is oversight in initial implementation and lack of check in test case.

Do you have an idea how to solve the issue?
-------------------------------------------
Yes.  I'll post PR shortly.  In meantime, here's the diff:
```
diff --git a/internal/restic/lock.go b/internal/restic/lock.go
index 3e3a27a6..142fa4b7 100644
--- a/internal/restic/lock.go
+++ b/internal/restic/lock.go
@@ -221,6 +221,7 @@ func (l *Lock) Stale() bool {
 // timestamp. Afterwards the old lock is removed.
 func (l *Lock) Refresh(ctx context.Context) error {
        debug.Log("refreshing lock %v", l.lockID)
+       l.Time = time.Now()
        id, err := l.createLock(ctx)
        if err != nil {
                return err
diff --git a/internal/restic/lock_test.go b/internal/restic/lock_test.go
index daadd479..09dce3c7 100644
--- a/internal/restic/lock_test.go
+++ b/internal/restic/lock_test.go
@@ -225,6 +225,7 @@ func TestLockRefresh(t *testing.T) {
 
        lock, err := restic.NewLock(context.TODO(), repo)
        rtest.OK(t, err)
+       time0 := lock.Time
 
        var lockID *restic.ID
        err = repo.List(context.TODO(), restic.LockFile, func(id restic.ID, size int64) error {
@@ -238,6 +239,7 @@ func TestLockRefresh(t *testing.T) {
                t.Fatal(err)
        }
 
+       time.Sleep(time.Millisecond)
        rtest.OK(t, lock.Refresh(context.TODO()))
 
        var lockID2 *restic.ID
@@ -254,5 +256,9 @@ func TestLockRefresh(t *testing.T) {
 
        rtest.Assert(t, !lockID.Equal(*lockID2),
                "expected a new ID after lock refresh, got the same")
+       lock2, err := restic.LoadLock(context.TODO(), repo, *lockID2)
+       rtest.OK(t, err)
+       rtest.Assert(t, lock2.Time.After(time0),
+               "expected a later timestamp after lock refresh")
        rtest.OK(t, lock.Unlock())
 }
```

Did restic help you or made you happy in any way?
-------------------------------------------------
Restic makes me happy that I don't have to worry about object store APIs and data correctness.  Thanks!

**Comment by fd0** [comment]
Thank you very much!
