### ISSUE TITLE
number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by MichaelSmolle** [restic/restic#2400]
Hi,

i tried to prune my repository and got the following Error: 

Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
ERROR: passthrough failed.

Could you please assist me?

**Comment by MichaelEischer** [comment]
Is this issue still relevant for you? If yes, then please fill in the issue template from https://github.com/restic/restic/issues/new?template=Bug.md . If you no longer have the prune error, then I'd suggest to close this issue.

**Comment by MichaelEischer** [comment]
Closing this as the requested information was not provided in months.
