### ISSUE TITLE
Question - can unfinished snapshots be restored from?

### ISSUE THREAD

**Issue by jim-collier** [restic/restic#2402]
## Intro

As I mentioned in a previous issue, I was evaluating Duplicacy, but have moved on to evaluating Restic. I also haven't found the answer to this question on the Restic site, this github repository, or web search.

## Background

Without clever use of folder inclusion & file exclusion, my initial backup will likely take 1 to 2 years. With Crashplan (and as with many other commercial "all-in-one cloud backup" products), that wasn't a problem. Those products typically back up newest files first (which happen to match my needs), and assuming any given file was fully backed up, that file can be restored at any time during the backup. (There's also no real concept of "snapshots", other than historical file versions and filtering by version date.)

Not so with Duplicacy and apparently some other products. If the snapshot is not complete, it cannot be restored from. Which strikes me as incredibly risky, as that's the whole point of a backup: If my home burns down between now and the next two years (not at all unlikely), I'm boned. Of course, I could get creative with `mount --bind` and exclude filters to make many quick snapshots, but I don't have that kind of time for frequently manual intervention.

Borg, for example, executes a "checkpoint" every 30 minutes. (But lack of cloud support rules it out.) A snapshot is valid, at minimum, to the last checkpoint.

## The question

So with that context in mind: Does Restic implement some kind of checkpoint concept, or otherwise allow restoring files that have been fully backed up, but in an otherwise incomplete snapshot? (Forgive me if I'm using imprecise terminology in the context of Restic-specific vocabulary.)

Thanks!

**Comment by cfbao** [comment]
Restic doesn't have checkpoints, but it has the `recover` command (see #2056) that can recover data from repo even if it's not saved in a snapshot yet.

**Comment by jim-collier** [comment]
> Restic doesn't have checkpoints, but it has the `recover` command (see #2056) that can recover data from repo even if it's not saved in a snapshot yet.

@cfbao  Awesome! And perfect. Thanks.

**Comment by fd0** [comment]
I'd like to close this issue when it has been answered. We're using the issue tracker only for bugs and feature requests, please use [the forum](https://forum.restic.net) for questions. More people regularly read it :)
