### ISSUE TITLE
fuse mount: decide what to do with UID/GID of files/dirs/symlinks

### ISSUE THREAD

**Issue by fd0** [restic/restic#241]
At the moment, restic uses `root` (UID/GID 0) for all files and directories in the fuse mount. The original authorship information is available in the node, but this data is machine specific. As soon as the repo is mounted on a different machine, it doesn't make sense any more.

Should we leave it that way (using `root`) for browsing snapshots, or maybe offer a switch to display real ownership?

**Comment by fw42** [comment]
What do other people do? For example nfs or sshfs etc.?

**Comment by fd0** [comment]
NFS has a static mapping table, sshfs has:

       -o idmap=TYPE
              user/group ID mapping, possible types are:
               none   no translation of the ID space (default)
               user   only translate UID of connecting user
               file   translate UIDs/GIDs based upon the contents of uidfile  and gidfile

       -o uidfile=FILE
              file containing username:uid mappings for idmap=file

**Comment by fd0** [comment]
Access modes on fuse filessytems aren't enforced by the Kernel, so I think we should take same approach as sshfs: display the original ownership information.

**Comment by fw42** [comment]
sounds good to me

**Comment by fd0** [comment]
In addition we could try to look up the owner's name on the current system. If it is there, use the uid as the owner...

**Comment by fw42** [comment]
> I think this is an enhancement for later.

Agree, I think we should stick to what other systems (sshfs, nfs, rsync, ...) do unless someone explicitly complains about it...
