### ISSUE TITLE
Docs: Check --read-data-subset explenation confusing.

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#2412]
In the [check docs](https://restic.readthedocs.io/en/stable/045_working_with_repos.html#checking-a-repo-s-integrity-and-consistency), the explenation for --read-data-subset was indefinitely confusing for me. I wouldn't of understood it without examining the examples.
I don't have any better wording for it, but I think there should be.
![image](https://user-images.githubusercontent.com/38327267/65380334-e11f3700-dcc8-11e9-918f-26729c570c00.png)

**Comment by rawtaz** [comment]
Closing this as it will be fixed in #2476 soon.
