### ISSUE TITLE
Hostname conflicts

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#2413]
How does restic automatically determine the hostname? From the hostname?

What happens when hostname `laptop` backs up? Everything works.
Then comes laptop 2, hostname `laptop`. Do they act as the same machine? There don't seem to be any checks when adding a new repo to check for hostname conflicts.

**Comment by bjoe2k4** [comment]
It's your responsibility to assign proper (unique) hostnames in case you need them. I don't think restic cares in any way except documenting the hostname in the snapshots.

**Comment by jtagcat** [comment]
@bjoe2k4 in a way it matters.
When multiple machines back up to one location, filtering snapshots may have unattended consequences. When restoring, one could accidentally assume that they are seeing snapshots from one machine, though they actually are seeing snapshots from multiple machines.

**Comment by lorenzbausch** [comment]
@jtagcat This sounds more like a hypothetical issue to me since you may specify `--host` when performing backups.

**Comment by jtagcat** [comment]
@lorenzbausch Well it would be a feature request for when setting up a repo, Restic checks, if the same hostname exists and warns.

**Comment by cfbao** [comment]
How would restic tell if it's a conflict or really the same host?

**Comment by jtagcat** [comment]
@cfbao as I mentioned before: on first repo setup
When a new host is entering and sees their name, the new host will go 'hold on, are you sure, I'm the same machine'

**Comment by cfbao** [comment]
You may have the wrong idea of what a restic repo or "repo setup" is.
A restic repository only needs to be set up _once_ across _all_ machines, and whatever new machines/hosts that use this repo don't need any setup whatsoever. In fact, a host wouldn't know if it is new or old itself.

**Comment by jtagcat** [comment]
@cfbao by across all machines you mean setting it up on one and shipping the config file around?

**Comment by cfbao** [comment]
@jtagcat I mean setting it up on one machine, and you can use it directly on another machine.
There is no local config file.

**Comment by jtagcat** [comment]
@cfbao Yes, from that perspective, it would be useless (though getting an unique component like the mac address or something else)
I would not use Restic as you explained. Though it's up to each user and Restic should provide a neutral solution, if at all.

**Comment by jtagcat** [comment]
Closing as out of scope, pardon for being a dick earlier.
