### ISSUE TITLE
Set up donations?

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#2415]
Restic is one of the best open-source backup solutions, yet you do not allow any way of donating or sponsoring.

**Comment by shtratos** [comment]
@fd0  You can apply for Github sponsorship and get up to $5000 donations matched by Github in the next year.
https://github.com/sponsors

https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors

Also time is of the essence:
> To be eligible for the GitHub Sponsors Matching Fund, you must apply to GitHub Sponsors by January 1, 2020.

**Comment by jtagcat** [comment]
addons.mozilla.org allows you to link to the following domains: buymeacoffee.com, (donate.mozilla.org), flattr.com, liberapay.com, micropayment.de, opencollective.com, patreon.com, paypal.com, paypal.me

I'd also encourage gh sponsors and discourage paypal (known to drop you from logging in, take your funds and not reply to support requests).

**Comment by rawtaz** [comment]
It's been considered and discussed before, but there hasn't been a proper format for it (even if it would be something the author would accept).

Given that (it's not long since it was last discussed) I don't think there's much point in keeping this issue open based on that, so I'm closing it.

Sorry about that, because it's a lovely gesture and I understand that everyone raising this is serious about it (FWIW, I too would be happy to financially contribute to restic and @fd0's work) :/

**Comment by ShawnMilo** [comment]
Hey. Just found this thread and wanted to throw my 2¢ in. I was looking for a way to contribute $5/month, as I do for other projects like Tails and TOR. If you make this a possibility please let me know.

**Comment by jtagcat** [comment]
I'd say some distribution should take place, for example @rawtaz has done significant work as well.. but I don't know..

![image](https://user-images.githubusercontent.com/38327267/98287027-b3fd1900-1f9c-11eb-8467-fe506609301d.png)

Looking at commits, yep @fd0, but everything can't be captured in commits.

I don't have the largest overview of who how much what does. @fd0 what is your take?

Open Collective would be a thing, but then you need to charge related costs, what doesn't really work.

If distribution is in place, it should go directly to pocket.

**Comment by ShawnMilo** [comment]
I don't know the details, but TOR and Tails both use PayPal. I'm sure it's simple to set up. I don't know how much PayPal takes, though.

**Comment by shtratos** [comment]
Github sponsors is the built in way with prominent sponsor button in the
repo page.
It just needs to be set up.

**Comment by rbrunner7** [comment]
Another vote for setting up some way to donate. Even if you all work for free for the pure joy of creating useful software, you certainly have some expenses for servers and such which could be covered that way.

**Comment by AlertSubject** [comment]
checked here and https://github.com/restic/restic/issues/884
Found no way to donate

Ping me when it becomes possible, restic is worth it

**Comment by JohnMaguire** [comment]
Watching. I would like to sponsor this immensely valuable project.

**Comment by stylerw** [comment]
Also following. Restic is incredibly valuable to me and my workflow, and I'd love to support you all via Liberapay or similar.

**Comment by samliu** [comment]
Following. Restic has been meeting my needs so well that I felt compelled to donate, but was surprised that I couldn't. Thanks for all the hard work on this <3

**Comment by zutto** [comment]
Yet another reminder here that a way to contribute financially would be great, even if its just for cup of coffee to the maintainers!

**Comment by molecular** [comment]
My crypto is still waiting for restic to accept donations.

I LOVE restic :heart:

**Comment by tjcrowder** [comment]
I too would be happy to donate if/when a mechanism is available. But regardless: **Thank you** @fd0, @MichaelEischer, and everyone else who's contributed to this project. It is simply excellent.

**Comment by molecular** [comment]
Donations still not easy, I periodically come back to find the same status... ok, fine, I'll praise instead:

restic is one of the projects that have fundamentally and substantially changed my life for the better. I've lost data in major ways twice in my life and it's been devastating each time. Until I found restic I just couldn't figure out a good way to automate backups.

Finally with restic I now have secure automated backups (off- and on-site) with good data retention (even against deletion) over decades and probably across generations.

Thanks to restic I can sleep well and worry much less.

I love you guys! :heart:

**Comment by kon-foo** [comment]
Just another one to follow this. Please take my money.

**Comment by marcelklehr** [comment]
Seconded, Please take my money.

**Comment by gduhra68-ui** [comment]
Can see the discussion is still ongoing on funding --so have made a oneoff GBP 75  ($100) donation to charity (Red Cross if ok) for the use of restic. Hope this is satisfactory for you guys for some impressive software.
