### ISSUE TITLE
Add Pushover support

### ISSUE THREAD

**Issue by wuast94** [restic/restic#2417]
Would be nice to have pushover support to get a notification of an error or warning occurs :)

**Comment by ZacharyDuBois** [comment]
That’s what scripting is for! Just write a shell script to get the exit code. If it’s not 0, send a message with the restic output. I can’t see this being added just because then everyone will want to see X service. I’m sure the authors/maintainers will not want to deal with that.

**Comment by fd0** [comment]
Thanks for the recommendation, but I think that's out of scope for restic. We're trying to limit the things restic can do so that it keeps being maintainable. Every feature we add also adds to the maintenance burden.

I'm closing this issue for now, thanks for understanding (and feel free to add further comments!)

**Comment by wuast94** [comment]
I understand this and I agree. 
I know how to push to the pushover API but how I get the output from restic the best way? I wrote just one script in my life and don't know how I get the Infos from restic and how to trigger the script.

**Comment by ZacharyDuBois** [comment]
@wuast94 I’ll see if I can whip one up later today for you. I assume you just want it to tell you if Restic fails a backup?

**Comment by wuast94** [comment]
> @wuast94 I’ll see if I can whip one up later today for you. I assume you just want it to tell you if Restic fails a backup?

I think the best is after a backup say if it was OK (a bit of metrics..duration,size,speed) and if it fails what error occurs.

**Comment by ZacharyDuBois** [comment]
@wuast94 I have just finished it and pushed it to my random scripts repository. Let me know what you think :)

[restic-pushover.sh](https://github.com/ZacharyDuBois/Random-Scripts/blob/master/restic-pushover.sh)
