### ISSUE TITLE
Restic Backups and Duplicate Data

### ISSUE THREAD

**Issue by nunoperalta** [restic/restic#2418]
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.12.4 on linux/amd64

Duplication
-------------

I'm currently doing some tests with Restic and trying to ensure this is the way to go with our backups.

Everything seems to work perfectly, but I'm concerned about duplicate data vs costs.
My repository is in S3, **with S3 encryption enabled (with KMS)**.

I noticed that even if there are no changes at all, a snapshot will still be created, with the same files.
**Are all these duplicates are taking space in S3?
Or are these snapshots reusing older versions of the files, but show in the latest snapshot for convenience?**

Tests
------

I copied the actual "restic" program (18MB) to the test folder,
then ran backup,
and then "restic stats", which showed:

>     Stats for all snapshots in restore-size mode:
>       Total File Count:   26
>             Total Size:   18.024 MiB

Ran backup again, and then stats showed:

>     Stats for all snapshots in restore-size mode:
>       Total File Count:   30
>             Total Size:   36.049 MiB

And then once more, and stats showed:

>     Stats for all snapshots in restore-size mode:
>       Total File Count:   34
>             Total Size:   54.073 MiB

Even if I put a "--tag test", and keep the same tag on every backup, it still increases.

So, to me, this is not ideal at all.
I'd like to understand whether I'm doing something wrong, or does Restic do a FULL backup on every "restic backup" call.

**Comment by cfbao** [comment]
No. Deduplication is restic's thing.
Every snapshot contains *references* to all files, but file content isn't uploaded unless it's new.

You're running `restic stats` in the default "restore-size" mode, which computes the total disk space needed if you restore every single snapshot separately. This mode is designed to hide the deduplication restic has done.

For your purpose, you should run `restic stats --mode raw-data` to see the actual size of the repository.

**Comment by nunoperalta** [comment]
Perfect! Thank you very much!!
