### ISSUE TITLE
0.9.5 does not build anymore

### ISSUE THREAD

**Issue by djmaze** [restic/restic#2420]
Because [git.apache.org is gone](https://blogs.apache.org/infra/entry/subversion-to-git-service-git) and 0.9.5 has a [dependency on that site](https://github.com/restic/restic/blob/v0.9.5/go.sum#L14-L15), it is currently not possible to build this (latest stable) version. 

It seems `master` already includes updated dependencies. Maybe it makes sense to publish a new version with the dependency fixed?

**Comment by rawtaz** [comment]
@djmaze Thank you for raising this issue. It's unfortunate that it didn't get any attention earlier.

Given the age of this ticket and a [recent post by @fd0](https://forum.restic.net/t/future-of-restic-development-maintenance/2250/2) I think it makes sense to close this issue now and wait for the next release. A re-release of 0.9.5 seems a bit out of date currently.
