### ISSUE TITLE
Case insensitive exclude file

### ISSUE THREAD

**Issue by cfbao** [restic/restic#2427]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Add case insensitive versions of the `--exclude-file`.

What are you trying to do?
--------------------------
Exclude files properly and easily on Windows.
Actually, not me personally, but I've seen some Windows users very confused about file path letter cases. For example:
https://forum.restic.net/t/exclude-file-to-block-folders-from-windows-drives/2070
Even at the end when the problem was resolved, I don't think they really understood the reason properly.
restic already has case insensitive include/exclude. I think it makes sense to extend it to `--exclude-file`.

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes, every day.

**Comment by jim-collier** [comment]
This is kind a glaring missing option.

To be consistent with `--exclude` and `--iexclude`, and dodge a bullet of adding syntax to the exclude file (both from points of view of restic programmers and users), perhaps an option could be added: `--iexclude-file`.

And yes, restic makes me happy too.

**Comment by rawtaz** [comment]
I think there's a use case for this too, reading that forum thread it seems the author did what they were able to, but it was problematic even though they kind of understood it. So yeah, let's have someone file a PR for this, adding `--iexclude-file`! Maybe @aawsome or @greatroar?

**Comment by aawsome** [comment]
I just had a quick lock at it; it'll be only a few lines of code to add...
I can submit a PR.
