### ISSUE TITLE
Files failing to download in restic 0.9.5 mainline as well as 0.9.5 patched with PR 2244

### ISSUE THREAD

**Issue by Church-** [restic/restic#2430]
Output of `restic version`
--------------------------
restic 0.9.5 (v0.9.5-34-gd2a492c1) compiled with go1.11.5 on linux/amd64
(restic mainline with PR 2244 and PR 2340)
(Also repro'd with restic 0.9.5 master)

How did you run restic exactly?
-------------------------------
Ran restic via the following script:
```
#!/bin/sh

download_files() {
	local snapshot=$1

	#Downloads only phase-1 files
	restic -o b2.connections=400 restore "$snapshot" --target / \
		--exclude "_objects" --exclude "minidump" --exclude "symbold"
	echo "Finished phase-1"
	
	#Choose whether to copy over coronerd.db, coronerd.conf, etc to the host from backup
	echo "Copy /backtrace/etc/coronerd/* to /etc/coronerd/? Y/N:"
	read COPY_OVER
	if [ "$COPY_OVER" = "Y" ]; then
		cp -r /backtrace/etc/coronerd/* /etc/coronerd/
		echo "Copied over coronerd files."
	fi
	
	if [ ! -d "/backtrace/var/symbold/queue" ]; then
		mkdir -p /backtrace/var/symbold/queue
	fi

	echo "Restarting coronerd"
	systemctl restart coronerd

	#Start downloading phase-2 files
	restic -o b2.connections=400 restore "$snapshot" --target / \
		--include "minidump" --include "symbold"
    echo "Finished Phase 2"

	#Start downloading phase-3 files
	restic -o b2.connections=400 restore "$snapshot" --target / \
		--include "_objects"
        echo "Finished Phase 3"
	echo "Time to restart coronerd to pick up object files."
}

main() {
	export RESTIC_REPOSITORY="b2:bucket:/"
	export RESTIC_PASSWORD="pass"
	export B2_ACCOUNT_ID="id"
	export B2_ACCOUNT_KEY="key"
	snapshot="latest"
	download_files "$snapshot"
}
main
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze

Expected behavior
-----------------
Expected behavior is for restic to download files with no errors.

Actual behavior
---------------
A large list of files that failed to download, giving the error: "UtimesNano: dir/file does not exist"

Sample file list:
```
ignoring error for /backtrace/var/coronerd/backtrace/lolmeeee/_objects/0000/050C.050B.dmp: UtimesNano: no such file or directory
ignoring error for /backtrace/var/coronerd/backtrace/lolmeeee/_objects/0000/050D.050C.dmp: UtimesNano: no such file or directory
ignoring error for /backtrace/var/coronerd/backtrace/lolmeeee/_objects/0000/050F.050E.dmp: UtimesNano: no such file or directory
ignoring error for /backtrace/var/coronerd/backtrace/lolmeeee/_objects/0000/0510.050F.dmp: UtimesNano: no such file or directory
ignoring error for /backtrace/var/coronerd/backtrace/lolmeeee/_objects/0000/0511.0511.dmp: UtimesNano: no such file or directory
```

Steps to reproduce the behavior
-------------------------------
Error has only popped up whilst being run via this script, error might be occuring due to our backups being done in three tiers.
Tier one for files the service needs to start up, followed by starting the service.
With tier two and three continuing to restore to the target dir whilst our service is able to read and write to the dir.
```
sudo sh /root/restore-test.sh
```

Do you have any idea what may have caused this?
-----------------------------------------------
Might be caused because our service is able to read/write/mmap stuff in the dir tree while we restore to it.

However this issue hasn't been reproduced since I patched restic with PR 2244.

Do you have an idea how to solve the issue?
-------------------------------------------
None.

Did restic help you or made you happy in any way?
-------------------------------------------------
Generally yes, couple issues that are popping up and being a bit of a pin however.

**Comment by Church-** [comment]
Adding a strace log showing only the openat,open,close,utimesnat syscalls as it's an issue with utimesnano.

This is only a sample log as the full log was 1.1GB.
[strace.log](https://github.com/restic/restic/files/3678284/strace.log)

**Comment by djmaze** [comment]
I had the same error during a restore inside a container. Turned out the target directory was mount read-only -_-

**Comment by MichaelEischer** [comment]
Closing this as the restorer code has been rewritten in the meantime and #2244 is also fixed. If this is still a problem with a recent restic version, feel free to reopen the issue.
