### ISSUE TITLE
sftp panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by enboig** [restic/restic#2432]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on linux/amd64

How did you run restic exactly?
-------------------------------
export RESTIC_REPOSITORY="rclone:resticserver:/mnt/restic"
export RESTIC_PASSWORD="*****************************"
restic backup '/home/user'

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
The copy is over SSH, i tried direct connection, but I use a non standard port, I changed the ~/.ssh/config, but as it wasn't working I configured over rclone

Expected behavior
-----------------
Make a backup.

Actual behavior
---------------
repository 67a738e9 opened successfully, password is correct
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b82c8]

goroutine 73 [running]:
github.com/restic/restic/internal/repository.(*Index).ID(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/restic/internal/repository/index.go:377 +0x38
github.com/restic/restic/internal/repository.(*Repository).LoadIndex.func5(0x8, 0xe6c288)
	/restic/internal/repository/repository.go:467 +0xce
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000117590, 0xc0003fa420)
	/restic/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
	/restic/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66

Do you have any idea what may have caused this?
-----------------------------------------------
No idea, over lan it works, but over internet no. rclone works as expected

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes, it saved my work a lot of times.

**Comment by enboig** [comment]
When I type ```rclone ls resticserver:/mnt/restic``` it responds:
```
      155 config
      467 keys/56d......0f7551
     1921 index/0037....50153
    10102 index/006....9653
```
So rclone is configured ok.
The problem appeared when trying to access the server over SSH remotely over a non standard port. Over LAN and with standard port it worked. I changed direct sftp to rclone to try to avoid "non standard port" problem, but the problem continues.

**Comment by hyperfekt** [comment]
Encountered this while trying to list a file in snapshots, using a new cache fixed it. Probably some kind of corruption in that?

**Comment by enboig** [comment]
I endend using rclone as a restic server:
https://rclone.org/commands/rclone_serve_restic/

Using direct SFTP didn't work.
Using rclone to mount filesystem didn't work.

**Comment by hyperfekt** [comment]
I don't think this is a protocol issue, as I was using S3.
