### ISSUE TITLE
B2 Backblaze connection refused part way through backup

### ISSUE THREAD

**Issue by richard-scott** [restic/restic#2435]
Output of `restic version`
--------------------------

debug enabled
restic 0.9.5 (604b18aa) compiled with go1.10.4 on linux/amd64

How did you run restic exactly?
-------------------------------

> $ restic --cleanup-cache --option b2.connections=30 backup --exclude-caches --exclude /dev --exclude /proc --exclude /net --exclude /run --exclude /sys --exclude /mnt/sshfs --exclude /var/lib/lxcfs --exclude-file=/etc/restic/exclude.list /

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze B2

Expected behavior
-----------------

Backup should finish.

Actual behavior
---------------

I get this repeated in the logs:

> 2019/10/04 10:29:30 debug/round_tripper_debug.go:82     debug.loggingRoundTripper.RoundTrip     185     RoundTrip() returned error: dial tcp 206.190.211.201:443: connect: connection refused
2019/10/04 10:29:31 debug/round_tripper_debug.go:77     debug.loggingRoundTripper.RoundTrip     185     ------------  HTTP REQUEST -----------
POST /b2api/v1/b2_upload_file/5dbeb941b946af20614b0d16/c001_v0001017_t0025 HTTP/1.1
Host: pod-000-1017-10.backblaze.com
User-Agent: blazer/0.5.3
Content-Length: 5295953
Authorization: 4_001de9196f01bd60000000000_018f55f1_62367b_upld_ImYhg1oGmvOuVShmHMHtdBobGRE=
Content-Type: application/octet-stream
X-Blazer-Method: b2_upload_file
X-Blazer-Request-Id: 13186
X-Bz-Content-Sha1: hex_digits_at_end
X-Bz-File-Name: data/eb/eb0242e8299e64afd1f3130286dd86bb25fb278678c9fcf5a8e4810f8b967228
Accept-Encoding: gzip

Steps to reproduce the behavior
-------------------------------
Run a backup to B2.

Do you have any idea what may have caused this?
-----------------------------------------------
Nope.

Do you have an idea how to solve the issue?
-------------------------------------------
Nope.

Did restic help you or made you happy in any way?
-------------------------------------------------

Restic is the ONLY backup tool I use on my Linux Dev server!

**Comment by richard-scott** [comment]
If it helps, when I do not set DEBUG_LOG to a file (aka disable "debug mode") it seems to be OK, 

Restic is built with the following command:
> $ go run build.go -tags debug

**Comment by MichaelEischer** [comment]
Closing this issue as it's quite old and has probably solved itself in the meantime. Feel free to complain if the issue still exists.
