### ISSUE TITLE
prune fail with some ftp backend

### ISSUE THREAD

**Issue by WooDragon** [restic/restic#2437]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on linux/amd64

and

restic 0.9.5-dev (compiled manually) compiled with go1.11.1 on linux/amd64 with chunk size modify

How did you run restic exactly?
-------------------------------
```shell
restic -o rclone.args="serve restic --stdio --fast-list --ignore-checksum --b2-hard-delete --drive-use-trash=false --ftp-concurrency 1 --bwlimit 20M --transfers=1" -o rclone.connections=1 -r rclone:ftp:dir prune -v
```

>Load(<data/0404b22780>, 591, 4290657) returned error, retrying after 3.281583603s: <data/0404b22780> does not exist
Load(<data/040481a05c>, 591, 5660995) returned error, retrying after 4.642864798s: <data/040481a05c> does not exist
Load(<data/0404e57a33>, 591, 6294419) returned error, retrying after 2.504612092s: <data/0404e57a33> does not exist
Load(<data/0405e85efe>, 591, 5323919) returned error, retrying after 2.421662296s: <data/0405e85efe> does not exist
Load(<data/040655db0a>, 591, 5122848) returned error, retrying after 3.123349936s: <data/040655db0a> does not exist
Load(<data/0402ce807b>, 591, 4499323) returned error, retrying after 13.315171692s: <data/0402ce807b> does not exist
Load(<data/0404c6a9cc>, 591, 6432658) returned error, retrying after 6.098834659s: <data/0404c6a9cc> does not exist

those file that seems not exist, is actually exist.

the check is passed with no error.

I've try to use fuse to found what's going on

```
rclone -vv mount --debug-fuse  ftp: /mnt/ftp/
restic -r /mnt/ftp prune -v
```

then rclone output many Command not found,restic output same like before.

>2019/10/09 12:58:55 ERROR : ftp/data/0a/0a2bb469a76e57258ad8f2cdc1e0bcb1a00bb45dd84753907cffa32b7a3bf16f: ReadFileHandle.Read error: low level retry 7/10: open: 500 Command not found
2019/10/09 12:58:55 DEBUG : ftp/data/0a/0a2bb469a76e57258ad8f2cdc1e0bcb1a00bb45dd84753907cffa32b7a3bf16f: ReadFileHandle.seek from 67567616 to 67567616
2019/10/09 12:58:55 DEBUG : ftp/data/0a/0a2bb469a76e57258ad8f2cdc1e0bcb1a00bb45dd84753907cffa32b7a3bf16f: ReadFileHandle.Read seek close old failed: file already closed
2019/10/09 12:58:55 DEBUG : ftp/data/0a/0a2bb469a76e57258ad8f2cdc1e0bcb1a00bb45dd84753907cffa32b7a3bf16f: ChunkedReader.RangeSeek from -1 to 67567616 length -1
2019/10/09 12:58:55 DEBUG : ftp/data/0a/0a2bb469a76e57258ad8f2cdc1e0bcb1a00bb45dd84753907cffa32b7a3bf16f: ChunkedReader.openRange at 67567616 length 134217728
2019/10/09 12:58:55 DEBUG : ftp/data/1c/1c80f07c910a72a8e70e9397bb48b542b1baf30675450e9a1a26096956cc526d: ReadFileHandle.Read seek failed: open: 500 Command not found
2019/10/09 12:58:55 ERROR : ftp/data/1c/1c80f07c910a72a8e70e9397bb48b542b1baf30675450e9a1a26096956cc526d: ReadFileHandle.Read error: low level retry 7/10: open: 500 Command not found
2019/10/09 12:58:55 DEBUG : ftp/data/1c/1c80f07c910a72a8e70e9397bb48b542b1baf30675450e9a1a26096956cc526d: ReadFileHandle.seek from 67227648 to 67227648
2019/10/09 12:58:55 DEBUG : ftp/data/1c/1c80f07c910a72a8e70e9397bb48b542b1baf30675450e9a1a26096956cc526d: ReadFileHandle.Read seek close old failed: file already closed
2019/10/09 12:58:55 DEBUG : ftp/data/1c/1c80f07c910a72a8e70e9397bb48b542b1baf30675450e9a1a26096956cc526d: ChunkedReader.RangeSeek from -1 to 67227648 length -1
2019/10/09 12:58:55 DEBUG : ftp/data/1c/1c80f07c910a72a8e70e9397bb48b542b1baf30675450e9a1a26096956cc526d: ChunkedReader.openRange at 67227648 length 134217728
2019/10/09 12:58:55 DEBUG : ftp/data/0e/0e241f5257ba5b9d2cae9d0ea215338b806e1ff5a7a190afcdf11b19807f17f7: ReadFileHandle.Read seek failed: open: 500 Command not found
2019/10/09 12:58:55 ERROR : ftp/data/0e/0e241f5257ba5b9d2cae9d0ea215338b806e1ff5a7a190afcdf11b19807f17f7: ReadFileHandle.Read error: low level retry 6/10: open: 500 Command not found

I think maybe restic is tring to seeking file and backend not support that,then I add option --no-seek to rclone and now restic output like this

>Load(<data/0e241f5257>, 591, 67697653) returned error, retrying after 1.907399392s: seek ftp/data/0e/0e241f5257ba5b9d2cae9d0ea215338b806e1ff5a7a190afcdf11b19807f17f7: illegal seek
Load(<data/0a2bb469a7>, 591, 67569998) returned error, retrying after 1.979642518s: seek ftp/data/0a/0a2bb469a76e57258ad8f2cdc1e0bcb1a00bb45dd84753907cffa32b7a3bf16f: illegal seek
Load(<data/093fdfd705>, 591, 67369728) returned error, retrying after 3.261781191s: seek ftp/data/09/093fdfd7058d31e8d2fb70e3cf5f962f478c82f9c21b921e192a80ffea2fabcd: illegal seek
Load(<data/17f9262597>, 591, 67492377) returned error, retrying after 3.272167684s: seek ftp/data/17/17f9262597378c8eb97c8a85e5d1353438963365882a34bf0fe7260f73140f10: illegal seek
Load(<data/1c80f07c91>, 591, 67227837) returned error, retrying after 3.49449978s: seek ftp/data/1c/1c80f07c910a72a8e70e9397bb48b542b1baf30675450e9a1a26096956cc526d: illegal seek

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone ftp backend

[http://docs.upyun.com/](http://docs.upyun.com/api/developer_tools/#_3)

ftp is not good choice but I need it for some reason...

I can provide test account if needed.

Expected behavior
-----------------

maybe restic can support option like --no-seek?

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------
maybe restic is try to seeking file and backend not support that

Do you have an idea how to solve the issue?
-------------------------------------------
add an option that not seek when doing prune or rebuild-index

maybe will solve this issue?

Did restic help you or made you happy in any way?
-------------------------------------------------
yes, I like restic,I use restic for backup btrfs snapshot,like
```
btrfs send ./1565928061.snapshot/ |restic-dev -o rclone.args="serve restic --stdio --b2-hard-delete --drive-use-trash=false --transfers 10 --verbose" --password-file=/dev/shm/ps -r rclone:gdbackup:btrfs backup --stdin --stdin-filename 1565928061.snapshot
```
I've try many tools and no one can handle this use case.

this method help me avoid massive number of small files slow down the backup progress,because btrfs send is fully sequential io.

**Comment by WooDragon** [comment]
I've solve this problem with rclone.
I found mount ftp with rclone --vfs-cache-mode full , then all things goes well.

**Comment by fd0** [comment]
Great, thanks for leaving feedback how you resolved the issue!
