### ISSUE TITLE
Restore operation ignores verbose flag

### ISSUE THREAD

**Issue by rbuchberger** [restic/restic#2438]
Sorry if this should be a feature request instead of a bug report; I chose bug report because --verbose is explicitly documented as a valid option in the restore man page, yet it appears to do nothing.

Output of `restic version`
--------------------------
```
❯ restic version
restic 0.9.5 compiled with go1.12.8 on linux/amd64
```
How did you run restic exactly?
-------------------------------

Input:

```
restic restore 0abb5d86 \
	-r /mnt/local_backups/charybdis \
	--target / \
	--password-file="/root/backup_password_file" \
	--verbose=2 \
	--include=/bucket/ \
	--verify
```

Output:
```
repository 125e44d6 opened successfully, password is correct
restoring <Snapshot 0abb5d86 of [/ /home /efi /bucket] at 2019-10-06 10:52:49.584344959 +0200 CEST by root@charybdis> to /

```

(Note that this restore operation is very large, and is still in progress.)

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Local filesystem

Expected behavior
-----------------

Provide more output on what exactly the restore operation is doing. Useful information would be the level of progress, current files being restored, etc. 

Actual behavior
---------------

Currently it appears to ignore both levels of the --verbose flag, only notifying the user that the password is correct and that the restore is in progress. (Presumably it also notifies when the restore is complete.) For very long operations, this leads to some concern that the operation has failed or stalled, and no way to know when it can be expected to finish other than using system resource monitoring tools and such.

Steps to reproduce the behavior
-------------------------------

Run a restore operation with the --verbose flag set.

Do you have any idea what may have caused this?
-----------------------------------------------

Sorry, no.

Do you have an idea how to solve the issue?
-------------------------------------------

I'd love to learn rust, maybe this is a good opportunity?

Did restic help you or made you happy in any way?
-------------------------------------------------

Oh absolutely. This big restore I'm going? I'm into photography, and it's basically all the photos I've taken over the years. I had a power failure and broke an LVM RAID array in a weird way, and if it weren't for my restic backups I'd probably have lost them.

 Y'all have the best backup tool out there, I'm incredibly thankful for your efforts. Keep up the good work!

**Comment by MichaelEischer** [comment]
I agree that some progress output would be useful. We already have #426 and #1154 for this issue.
