### ISSUE TITLE
--exclude and --exclude-file: missing examples with spaces in path

### ISSUE THREAD

**Issue by novoid** [restic/restic#2440]
Output of `restic version`
--------------------------

It's about the documentation:
https://restic.readthedocs.io/en/latest/040_backup.html#including-and-excluding-files

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I want to know how to handle exclude paths such as "/home/user/this has spaces/foo.txt".
The documentation does not mention nor show how to do this. This can be done multifold and it may differ between `--exclude` and `--exclude-file`:

Possible exclude syntax examples for doing a backup for "/home/user":
```
"this has spaces/foo.txt"
this\ has\ spaces/foo.txt
"this has spaces"/foo.txt
this has spaces/foo.txt
```

I don't want to try it out myself for each case.

What are you trying to do?
--------------------------

Excluding files from my backup.

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes, the documentation is quite helpful in general and I want to improve even the high standard. :-)

**Comment by cdhowie** [comment]
The syntax in an exclude file is simple: just put one space:

```
this has spaces/foo.txt
```

The syntax for `--exclude` depends on your OS and/or shell. Restic does not need any escaping itself, but your shell may need some escaping in order to pass the argument as a single argument to restic. Consult the documentation for your shell.

On most Unixy shells, you can either quote or use backslashes.  That is, any of these would work:

```
--exclude='this has spaces/foo.txt'
--exclude="this has spaces/foo.txt"
--exclude=this\ has\ spaces/foo.txt
```

**Comment by novoid** [comment]
Thanks @cdhowie for explaining me here in this issue.
Are you able to include this also in the documentation I linked above so that new users are able to find it out themselves?
Thanks!

**Comment by rawtaz** [comment]
I've added a PR that is supposed to fix this. Thanks @novoid for working to keep the documentation up to date!
