### ISSUE TITLE
The future of restic development

### ISSUE THREAD

**Issue by carlodippolito** [restic/restic#2443]
Hello,
I see that the most recent commit was on 27 July 2019.

I have to schedule some installations of different hosts and I would like to know if the development of Restic will continue.

Thank you

**Comment by fd0** [comment]
It will continue, I just don't have much time right now. For such questions, [the forum](https://forum.restic.net) would have been better.

I'm closing this issue, please feel free to add further comments, thanks!

**Comment by carlodippolito** [comment]
Ok thanks

**Comment by legrostdg** [comment]
@fd0 maybe you could consider adding co-maintainers? @ifedorenko seems very active, and probably others...

**Comment by mholt** [comment]
So, my two cents on maintainership:

A lot of the changes that are being proposed (and in some cases, demanded -- which kind of rubs maintainers the wrong way) are _really big_ changes. As a collaborator -- but not the author -- I don't feel comfortable reviewing or approving changes like this. I know a lot of people are pushing for that, but the harder it is pushed, the more uncomfortable it makes me, without the author's direct reviews and approvals. I trust @ifedorenko and other maintainers, but @fd0's vision for the project is something that I can't speak for him on. Maybe other collaborators understand it better than I do, but at some point, it comes down to fd0. I have not yet mastered the skill of intuitively receiving the author's same vision. And that vision is something that I feel is important that we as a community respect, along with his free time. :)
