### ISSUE TITLE
Paths in --files-from files that include brackets aren't backed up

### ISSUE THREAD

**Issue by tomwassenberg** [restic/restic#2448]
Output of `restic version`
--------------------------
`restic 0.9.5 compiled with go1.12.4 on windows/amd64`

How did you run restic exactly?
-------------------------------
To circumvent #233, I'm using the `--files-from` flag to pass a file containing a pre-filtered list of paths to backup. This file consists of absolute paths to files/dirs on an NTFS disk, without any escaping performed on them. I use the following (simplified) command to do this:
```
D:\> restic -r local:E:\ backup --files-from path-test.txt
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
A local repository.

Expected behavior
-----------------
Restic should parse file paths in a `--files-from` file that include brackets, and include these in the backup if they exist.

Actual behavior
---------------

The contents of a `--files-from` file seem to be evaluated as glob patterns. Paths containing brackets, that are allowed in paths on NTFS volumes, are never matched.

Steps to reproduce the behavior
-------------------------------
```
D:\> dir /B D:\[example].txt
[example].txt

D:\> type path-test.txt
D:\[example].txt

D:\> restic -r local:E:\ backup --files-from path-test.txt
pattern "D:\\[example].txt" does not match any files, skipping
Fatal: nothing to backup, please specify target files/dirs
```

Do you have any idea what may have caused this?
-----------------------------------------------
Looking at the git history, the desired behavior seems to have been present until #1892 was merged. Parsing asterisks as wildcards isn't a problem for me, since these are not allowed in filenames on most filesystems. However `filepath.Glob` treats more characters as special, which seems to cause the problem at hand as a side-effect.

Do you have an idea how to solve the issue?
-------------------------------------------
Restic should parse all valid file paths from a `files-from` file literally, which is implied by the [docs](https://restic.readthedocs.io/en/latest/040_backup.html#including-and-excluding-files). That makes is possible to pass all filenames that are valid in the containing filesystem, without having to do any escaping.

`--files-from` could also remain using `filepath.Glob` patterns, but that would be counter-intuitive to the use case that is mentioned in the docs. That use case states that `--files-from` is useful to pass a _pre-filtered_ list of file paths, using e.g. `find | grep`.

If `--files-from` keeps interpreting the paths in the file as glob patterns, the docs should be updated to include that certain characters (that are considered "special" in a glob pattern) within a path should be escaped. However, that wouldn't fix the problem on Windows, since escaping doesn't seem to be [possible](https://golang.org/pkg/path/filepath/#Match) there. (Currently, I replace brackets by question marks in the file, which makes it work for now, but isn't the same.)

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes, the encryption and deduplication functionality, and the extensive backend support make Restic my tool of choice for my personal backup setup :)

**Comment by rawtaz** [comment]
@tomwassenberg I think you nailed the analysis completely on this one. Your assessment is correct from what I can tell, and you also noticed the inability to escape brackets on Windows.

FWIW I've slightly updated the documentation about this in PR #2472.

In general I agree that whether the globbing should still apply for `--files-from` should definitely be discussed/reconsidered. I'm thinking there are use cases for both - some might want to list paths that should be globbed in the `--files-from`, while some might want to just list as you say pre-filtered paths directly.

**Comment by tomwassenberg** [comment]
@rawtaz Thanks for improving the docs a bit in this regard already. I agree there are use cases for both behaviors, so perhaps adding an extra flag could be another option.

I wasn't aware of #2276 by the way, which seems to describe the same problem, so I'll close this issue in favor of that one.
