### ISSUE TITLE
Enhance build process

### ISSUE THREAD

**Issue by jooola** [restic/restic#2457]
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

The build process seems to be working well for restic itself. I see that the change log generator `calens` has already been moved in its own repo.

I suggest moving the build tools in its own repo (maybe in the existing https://github.com/restic/builder repo ?), so that in the long run we can use it for the https://github.com/restic/rest-server repo and finally close https://github.com/restic/rest-server/issues/77.

@fd0 seem to be the person to ask regarding the build process, could you give us your input ?

Should I open a dedicated ticket in https://github.com/restic/rest-server in order to get the automated build process enhanced ?

What are you trying to do?
--------------------------

Enhance the global restic build process.

Did restic help you or made you happy in any way?
-------------------------------------------------

Not yet, but it will surely replace my existing backup system.

**Comment by jooola** [comment]
Also, this would be the chance to deprecated the vendor and Gopkg* files and use go.mod.

**Comment by rawtaz** [comment]
@jooola If the ticket you ask about opening in the `rest-server` repo is about the same thing, or is depending on this one, let's keep it to this one for now. No point in redundant issues.

**Comment by MichaelEischer** [comment]
We'll stick with goreleaser for rest-server for now.
