### ISSUE TITLE
--keep-hourly policy retains given count of snapshots instead of last snapshot for given hours

### ISSUE THREAD

**Issue by qrkourier** [restic/restic#2458]
Output of `restic version`
--------------------------
```bash
❯ restic version
restic 0.9.5 compiled with go1.12.9 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```bash
restic  -r ${RESTIC_REPO} --cleanup-cache forget --keep-tag keepers --host kpop4 --keep-hourly 24 --keep-daily 14 --keep-weekly 6 --keep-monthly 12 --keep-yearly 5
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

a local filesystem

Expected behavior
-----------------

from [the docs](https://restic.readthedocs.io/en/latest/060_forget.html#removing-snapshots-according-to-a-policy):
> --keep-hourly n for the last n hours in which a snapshot was made, keep only the last snapshot for each hour.

I expected restic to forget snapshots that were older than n hours.

Actual behavior
---------------

Restic remembered n snapshots for reason "hourly" where n is the argument to option `--keep-hourly` despite those snapshots being much older than n hours.

Steps to reproduce the behavior
-------------------------------

I noticed this because I have snapshots that are retained for reason "hourly" that are weeks older than the `--keep-hourly` policy dictates. I used the hourly policy in conjunction with daily, weekly, and other policies as shown above.

To reproduce this could start with a number of hourly snapshots that are days old, and then exec `restic forget --dry-run --keep-hourly 24` and I expect you'll (unexpectedly) observe that restic will retain exactly 24 hourly snapshots even if the oldest ones are more than 24 hours old.

Do you have any idea what may have caused this?
-----------------------------------------------

Restic seems to be retaining a count of snapshots instead of the last snapshot for the period dictated by the policy.

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you or made you happy in any way?
-------------------------------------------------

So happy! Thank you to the devs! This app has changed the way I think about durability of versions.

**Comment by cfbao** [comment]
I think you're seeing the (not very intuitive) expected behaviour, not a bug.
See this forum thread for more details:
https://forum.restic.net/t/restic-forget-confusion/2052
