### ISSUE TITLE
Is restic still being maintained?

### ISSUE THREAD

**Issue by timkgh** [restic/restic#2459]
Interested in what the future holds for `restic`. Safe to start using it and rely on it? There have not been any commits or releases in a few mmonths, while the list of issues keeps growing.

**Comment by PrplHaz4** [comment]
You are not alone. There was some recent activity on the compression feature...But still lots of PRs and open issues. 

My assessment is you are safe to start using it if you're good with the current feature set.  

Also see #2443

**Comment by cfbao** [comment]
Many people are already relying it, so yeah I'd say it's safe to start using it. @fd0 is busy but shows no sign of abandoning. As mentioned in #2443, it's best to use the forum for such questions, and use GitHub only for technical issues.

**Comment by timkgh** [comment]
Thank you and understood re forums, though not ideal for someone who just wants to ask about the project status going forward to go through forum signup.

**Comment by cfbao** [comment]
If you have a GitHub account, you can just sign into the forum directly. No signup needed.

**Comment by rawtaz** [comment]
Thank you @timkgh for your concern for rustic and its future, it's clear that you have the best of intentions. Thanks also everyone else who chimed in.

FWIW, @fd0 wrote [a reply in the forum](https://forum.restic.net/t/future-of-restic-development-maintenance/2250/2), addressing similar concerns. I agree that you shouldn't need to worry about restic at this point, it's highly usable and not going anywhere downhill in the near future.

I'm closing this issue for now, as this type of question is better suited for the forum. Feel free to continue the discussion in the thread I linked to above if you have any other thoughts.
