### ISSUE TITLE
The forget --tags flag documentation is incorrect (or the implementation is incorrect)

### ISSUE THREAD

**Issue by 8176135** [restic/restic#2460]
Output of `restic version`
--------------------------
`restic 0.9.5 compiled with go1.13.1 on linux/amd64`

Problem description
---------------------------
The documentation here: https://restic.readthedocs.io/en/latest/060_forget.html states:

> To only keep the last snapshot of all snapshots with both the tag foo and bar set use:
>
> `$ restic forget --tag foo,tag bar --keep-last 1`

However from testing this syntax seems to be incorrect, with the correct syntax being:

`restic forget --tag foo,bar --keep-last 1`

How did you run restic exactly?
-------------------------------

What was documented, and the working version stated above

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local

Expected behavior
-----------------

Remove all but the last snapshot with both foo and bar as tags

Actual behavior
---------------

Running the documented command tells you that bar is not a valid snapshot id (I think that it thinks `tag` is the other tag I want to use)

Steps to reproduce the behavior
-------------------------------

1. Add 2 backups with both foo and bar as tags
2. run the forget commands above, the documented one does not work.

Do you have any idea what may have caused this?
-----------------------------------------------
N/A

Do you have an idea how to solve the issue?
-------------------------------------------
Update the documentation, the current implementation is far better compared to the documented version (for automating)

Did restic help you or made you happy in any way?
-------------------------------------------------

Yep, my main backup solution

**Comment by rawtaz** [comment]
@8176135 Can you make a PR out of that small fix you made? Please reference this issue in it.
