### ISSUE TITLE
Timeout pruning via sftp

### ISSUE THREAD

**Issue by stenwt** [restic/restic#2467]
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.12.4 on linux/arm

How did you run restic exactly?
-------------------------------

RESTIC_PASSWORD=foo
RESTIC_REPOSITORY=sftp:rsync.net:restic-repo

command line invocation was: restic --cache-dir /srv/store1/restic/cache/ prune
(to keep caching on my SATA disc, vs the host's SD card where the os is loaded)

/root/.ssh/config contains:
Host rsync.net
  HostName usw-s001.rsync.net
  User flooble
  IdentityFile /srv/store1/restic/conf/.ssh/rsync
  ServerAliveInterval 60
  ServerAliveCountMax 20000000

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

rsync.net, see ssh config above

Expected behavior
-----------------

Restic should prune the repository.

Actual behavior
---------------

I've tried this several times, each time increasing the ServerAliveCountMax. Each time it fails, my repo grows by about 5GB of duplicated data. 

root@sync1:~# restic --cache-dir /srv/store1/restic/cache/ prune
repository 6ab47cc5 opened successfully, password is correct
counting files in repo
building new index for repo
[1:01:10] 100.00%  45080 / 45080 packs
incomplete pack file (will be removed): 65106f1569f0c833a58d10cc32007493fde27e81ec7102c6d8e37396539643f7
repository contains 45079 packs (322136 blobs) with 214.532 GiB
processed 322136 blobs: 81573 duplicate blobs, 21.871 GiB duplicate
load all snapshots
find data that is still in use for 19 snapshots
[0:50] 100.00%  19 / 19 snapshots
found 197000 of 322136 data blobs still in use, removing 125136 blobs
will remove 1 invalid files
will delete 4343 packs and rewrite 7369 packs, this frees 45.300 GiB
subprocess ssh: packet_write_wait: Connection to 64.62.236.72 port 22: Broken pipe
Save(<lock/2d1b52a6c9>) returned error, retrying after 552.330144ms: OpenFile: EOF
Save(<lock/2d1b52a6c9>) returned error, retrying after 1.080381816s: ssh command exited: exit status 255
Save(<lock/2d1b52a6c9>) returned error, retrying after 1.31013006s: ssh command exited: exit status 255
Save(<lock/2d1b52a6c9>) returned error, retrying after 1.582392691s: ssh command exited: exit status 255
Save(<lock/2d1b52a6c9>) returned error, retrying after 2.340488664s: ssh command exited: exit status 255
Save(<lock/2d1b52a6c9>) returned error, retrying after 4.506218855s: ssh command exited: exit status 255
Save(<lock/2d1b52a6c9>) returned error, retrying after 3.221479586s: ssh command exited: exit status 255
Save(<lock/2d1b52a6c9>) returned error, retrying after 5.608623477s: ssh command exited: exit status 255
Save(<lock/2d1b52a6c9>) returned error, retrying after 7.649837917s: ssh command exited: exit status 255
Save(<lock/2d1b52a6c9>) returned error, retrying after 15.394871241s: ssh command exited: exit status 255
unable to refresh lock: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 507.606314ms: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 985.229971ms: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 803.546856ms: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 1.486109007s: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 2.070709754s: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 3.67875363s: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 4.459624189s: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 6.775444383s: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 15.10932531s: ssh command exited: exit status 255
Save(<lock/2a35da8f7e>) returned error, retrying after 13.811796615s: ssh command exited: exit status 255
unable to refresh lock: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 351.593438ms: failed to send packet: write |1: file already closed
Remove(<lock/d4377d3272>) returned error, retrying after 645.653563ms: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 1.204507436s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 2.299204301s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 2.007570431s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 3.026422858s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 7.133794867s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 6.0363136s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 17.496021524s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 23.002952479s: ssh command exited: exit status 255
Save(<lock/a709c28014>) returned error, retrying after 511.910153ms: ssh command exited: exit status 255
failed to send packet: write |1: file already closed
github.com/pkg/sftp.sendPacket
        /restic/vendor/github.com/pkg/sftp/packet.go:135
github.com/pkg/sftp.(*conn).sendPacket
        /restic/vendor/github.com/pkg/sftp/conn.go:31
github.com/pkg/sftp.(*clientConn).dispatchRequest
        /restic/vendor/github.com/pkg/sftp/conn.go:117
github.com/pkg/sftp.(*clientConn).sendPacket
        /restic/vendor/github.com/pkg/sftp/conn.go:108
github.com/pkg/sftp.(*Client).close
        /restic/vendor/github.com/pkg/sftp/client.go:477
github.com/pkg/sftp.(*File).Close
        /restic/vendor/github.com/pkg/sftp/client.go:770
github.com/restic/restic/internal/backend.DefaultLoad
        /restic/internal/backend/utils.go:63
github.com/restic/restic/internal/backend/sftp.(*SFTP).Load
        /restic/internal/backend/sftp/sftp.go:340
github.com/restic/restic/internal/limiter.rateLimitedBackend.Load
        /restic/internal/limiter/limiter_backend.go:44
github.com/restic/restic/internal/backend.(*RetryBackend).Load.func1
        /restic/internal/backend/backend_retry.go:79
github.com/cenkalti/backoff.RetryNotify
        /restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        /restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).Load
        /restic/internal/backend/backend_retry.go:77
github.com/restic/restic/internal/cache.(*Backend).Load
        /restic/internal/cache/backend.go:197
github.com/restic/restic/internal/repository.DownloadAndHash
        /restic/internal/repository/repository.go:766
github.com/restic/restic/internal/repository.Repack
        /restic/internal/repository/repack.go:26
main.pruneRepository
        /restic/cmd/restic/cmd_prune.go:278
main.runPrune
        /restic/cmd/restic/cmd_prune.go:85
main.glob..func18
        /restic/cmd/restic/cmd_prune.go:25
github.com/spf13/cobra.(*Command).execute
        /restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /restic/cmd/restic/main.go:86
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_arm.s:868
Load
github.com/restic/restic/internal/repository.DownloadAndHash
        /restic/internal/repository/repository.go:782
github.com/restic/restic/internal/repository.Repack
        /restic/internal/repository/repack.go:26
main.pruneRepository
        /restic/cmd/restic/cmd_prune.go:278
main.runPrune
        /restic/cmd/restic/cmd_prune.go:85
main.glob..func18
        /restic/cmd/restic/cmd_prune.go:25
github.com/spf13/cobra.(*Command).execute
        /restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /restic/cmd/restic/main.go:86
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_arm.s:868
Repack
github.com/restic/restic/internal/repository.Repack
        /restic/internal/repository/repack.go:28
main.pruneRepository
        /restic/cmd/restic/cmd_prune.go:278
main.runPrune
        /restic/cmd/restic/cmd_prune.go:85
main.glob..func18
        /restic/cmd/restic/cmd_prune.go:25
github.com/spf13/cobra.(*Command).execute
        /restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /restic/cmd/restic/main.go:86
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_arm.s:868
Save(<lock/a709c28014>) returned error, retrying after 396.227312ms: ssh command exited: exit status 255
Save(<lock/a709c28014>) returned error, retrying after 740.619312ms: ssh command exited: exit status 255
Save(<lock/a709c28014>) returned error, retrying after 1.868490179s: ssh command exited: exit status 255
Save(<lock/a709c28014>) returned error, retrying after 3.734205348s: ssh command exited: exit status 255
Save(<lock/a709c28014>) returned error, retrying after 2.200112976s: ssh command exited: exit status 255
Save(<lock/a709c28014>) returned error, retrying after 6.235277092s: ssh command exited: exit status 255
Save(<lock/a709c28014>) returned error, retrying after 4.776550251s: ssh command exited: exit status 255
Save(<lock/a709c28014>) returned error, retrying after 15.275143199s: ssh command exited: exit status 255
Save(<lock/a709c28014>) returned error, retrying after 15.406612236s: ssh command exited: exit status 255
unable to refresh lock: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 336.633119ms: failed to send packet: write |1: file already closed
Remove(<lock/d4377d3272>) returned error, retrying after 780.824891ms: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 1.17467502s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 1.313731612s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 2.33672901s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 3.913005138s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 4.291648632s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 6.6812935s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 16.51276728s: ssh command exited: exit status 255
Remove(<lock/d4377d3272>) returned error, retrying after 16.565348898s: ssh command exited: exit status 255
error in cleanup handler: ssh command exited: exit status 255

Steps to reproduce the behavior
-------------------------------

Attempt to prune a repository ~190GB on rsync.net

Do you have any idea what may have caused this?
-----------------------------------------------

SSH timeout, possibly at the server end? Possibly contributing is that my machine running the prune operation is an Odroid HC-1, which has a Samsung Exynos5422 Cortex-A15 2Ghz and Cortex-A7 Octa core CPUs and 2GB RAM; the prune operation if successful would take approximately 2 days based on the progress meter before the crash. So there's definitely some periods when we're not actively transferring files over ssh as the little mobile cpu crunches data. 

Do you have an idea how to solve the issue?
-------------------------------------------

Send more keepalives? Maybe other tunings needed for my ssh client? Let Restic close the SSH tunnel when it's not actively needed, and re-open it when it is? 

Did restic help you or made you happy in any way?
-------------------------------------------------

I also back up to Backblaze B2, and previously used S3 and Google object storage. Those backups and restores have been reliable and, aside from this issue, which is definitely frustrating, Restic has been super, super awesome.

**Comment by cromo** [comment]
I'm currently trying to backup ~2TB of data to rsync.net and seeing a similar issue, e.g. it ends with
```
Remove(<lock/a463fe1407>) returned error, retrying after 27.337308488s: ssh command exited: exit status 255
error in cleanup handler: ssh command exited: exit status 255
```
It appears to keep going when re-running the command, though it has to pour over all the data it's already uploaded before it can continue, making for slow progress. It also appears to cause a small increase in disk usage on the remote end, but I can't confirm that it's not just normal metadata growth.

**Comment by stenwt** [comment]
The SD card running my OS was dying: 

```
[2748819.177296] Buffer I/O error on dev sdb2, logical block 0, lost sync page write
[2748819.177311] EXT4-fs: 165 callbacks suppressed
[2748819.177312] EXT4-fs (sdb2): I/O error while writing superblock
```

Replacing that, and setting TMPDIR to use my SATA drive to avoid further wear on my new SD card, seems to have resolved my issues. I also ran a build with https://github.com/restic/restic/pull/2340 which may have helped as well by cutting my prune time down by ~80%

**Comment by matthijskooijman** [comment]
@stenwt, did you actually solve this problem? Or why did you close it?

I seem to be running into pretty much exactly the same problem now, where the remote end closes the SSH connection while restic is busy with "building new index for repo". Maybe modifying the ssh command with some keepalive options could help?

**Comment by stenwt** [comment]
I solved the issue; it was not restic's fault (at least in my case), but was due to a failing SD card which held the OS and filesystem where I was running restic.
