### ISSUE TITLE
Lack of parameter "azure domain" when use azure blob storage as a repository

### ISSUE THREAD

**Issue by diddowill** [restic/restic#2468]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.11.5 on linux/amd64

Describe the issue
------------------
According to the manual here (https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#microsoft-azure-blob-storage),
we need to provide account name and access key when use azure block storage as a repository.
But that does not work if you azure domain is not azure global, like azure China and azure Germany. 
Error is returned as below:
> storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

The solution from Azure tech. support is, we must specify azure domain in this case as their tool Azure Storage Explore does.

**Comment by whs-dot-hk** [comment]
hi

looks like the `NewBasicClient`

https://github.com/restic/restic/blob/604b18aa7426148a55f76307ca729e829ff6b61d/internal/backend/azure/azure.go#L38

is used here

which uses the default base url

https://github.com/restic/restic/blob/604b18aa7426148a55f76307ca729e829ff6b61d/vendor/github.com/Azure/azure-sdk-for-go/storage/client.go#L45

**Comment by shtratos** [comment]
You can workaround this by using rclone backend:
https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone

rclone supports specifying the azure endpoint via `--azureblob-endpoint`
https://rclone.org/azureblob/#advanced-options

**Comment by MichaelEischer** [comment]
Adding a configuration parameter for the azure backend that allows overriding the default BaseURL should be enough to solve this issue.

**Comment by arjunajesh** [comment]
@MichaelEischer I would like to work on this issue. 
Just to be sure, should the domain be passed through an env variable (for example AZURE_DOMAIN)

**Comment by arjunajesh** [comment]
I believe that I have a solution for this issue. Does anyone have a Chinese Azure account for me to test my fix?
