### ISSUE TITLE
restic diff says 16777215.998 TiB added/removed.

### ISSUE THREAD

**Issue by trrk** [restic/restic#2469]
Output of `restic version`
--------------------------
```
restic 0.9.5 compiled with go1.12.4 on linux/arm
```

How did you run restic exactly?
-------------------------------
Run on Raspberry Pi 2.
```
$ ./restic_0.9.5_linux_arm --repo rclone:local:/path/to/repo diff 17b7d2e8 e5566ee1
enter password for repository:
repository bfe93af8 opened successfully, password is correct
comparing snapshot 17b7d2e8 to e5566ee1:

( omit this part... )

Files:         229 new,   229 removed,     0 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:   4412 new,  4583 removed
Tree Blobs:     43 new,    43 removed
  Added:   16777215.998 TiB
  Removed: 16777215.998 TiB
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone:local

Expected behavior
-----------------
```
Files:         229 new,   229 removed,     0 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:   4412 new,  4583 removed
Tree Blobs:     43 new,    43 removed
  Added:   6.204 GiB
  Removed: 6.428 GiB
```
This output is from the same command run on Windows 7.

Actual behavior
---------------
```
Files:         229 new,   229 removed,     0 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:   4412 new,  4583 removed
Tree Blobs:     43 new,    43 removed
  Added:   16777215.998 TiB
  Removed: 16777215.998 TiB
```
Restic reports wrong added/removed size.

Steps to reproduce the behavior
-------------------------------
I think it will be reproduced when run diff between snapshots which added or removed 2 GB or more.

Do you have any idea what may have caused this?
-----------------------------------------------
Integer overflow?

Do you have an idea how to solve the issue?
-------------------------------------------
It seems that 16777215.998 TiB had been displayed on the other issue. #1954
I think the cause is the same as it.

Did restic help you or made you happy in any way?
-------------------------------------------------
I use restic for backup of music data. I'm happy with taking snapshots and deduplication.

**Comment by rawtaz** [comment]
@trrk Can you possibly see if the PR https://github.com/restic/restic/pull/2487 fixes the issue? Let me know if you need help checking out and building the code to test it. Thanks a lot!

**Comment by fd0** [comment]
Great catch, thanks for the report!

**Comment by trrk** [comment]
Thank you for writing the patch. I built it and check whether restic works as expected.

It works great!
```
$ ./restic version
restic 0.9.6 (v0.9.6-2-g77ef92b9) compiled with go1.13.4 on linux/arm
```
```
$ ./restic --repo rclone:local:/path/to/repo diff 17b7d2e8 e5566ee1

....

Files:         229 new,   229 removed,     0 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:   4412 new,  4583 removed
Tree Blobs:     43 new,    43 removed
  Added:   6.204 GiB
  Removed: 6.428 GiB
```

**Comment by rawtaz** [comment]
@trrk Thanks you, appreciate it.
