### ISSUE TITLE
fuse mount: high memory usage

### ISSUE THREAD

**Issue by fd0** [restic/restic#248]
I discovered that restic seems to keep all data that is read over the fuse mount in memory, so reading a 2GiB file needs 2GiB of memory. Could you take a look @rakoo?

**Comment by fd0** [comment]
It looks like this is caused by https://github.com/restic/restic/blob/master/cmd/restic/fuse/file.go#L49-L61, which loads blobs into memory and keeps the reference to the slice, so that it is never garbage collected.

**Comment by rakoo** [comment]
Do you think an LRU at the file level would be enough ? Since the same blob is often read many times at different offset and most use cases are forward reading, I'd think about that first.

**Comment by fd0** [comment]
I'm working on this at the moment, it's a combination of two different things:
 * `repository.LoadBlob()` always creates a new buffer
 * the fuse code doesn't release blobs (by removing the pointer to it), so they are never garbage collected, this can be fixed by implementing the `HandleReleaser` interface

**Comment by rakoo** [comment]
AFAICS `HandleReleaser` only works on fuse-visible stuff, so you would release the whole 2GB file or none of it. We'll have to manually GC old blobs.

**Comment by fd0** [comment]
In my tests, `Release()` was nicely called when the file was closed, so we can at least release the blobs then. Please have a look at #249.

**Comment by fd0** [comment]
I think this is enough for now.
