### ISSUE TITLE
Folder changelog/unreleased/ doesn't exist when empty

### ISSUE THREAD

**Issue by rawtaz** [restic/restic#2485]
When here are no pending changeling entries in the unreleased/ folder, the folder isn't tracked by git anymore. Add a .gitkeep file to the changelog/unreleased/ folder in order to make the folder always exist. This makes it less confusing for new contributors when the contributing instructions reference this folder.

**Comment by fd0** [comment]
Ah, we need to take care when we move the directory for a new release so that we don't accidentally remove the file. I think it'd be best to add the changelog workflow to our helper program.

**Comment by rawtaz** [comment]
I see, you move the unreleased dir to a new name and location. Makes sense.

Yeah we should probably make calends only move the files in this folder instead of the entire folder.

Regardless this file in the PR should be kept, don't you think? For an empty folder we need it there.

**Comment by fd0** [comment]
Yep, keep it. I'll fix calens.

**Comment by fd0** [comment]
Hah, awesome. I think this fix helps prevent this in the future: https://forum.restic.net/t/psa-attention-anyone-not-using-a-recent-master-ie-0-9-5-version-restic-will-not-detect-changed-files-if-mtime-is-reset-by-the-application-eg-ms-excel-and-xls-xlsx-files-on-macos/1772/7

**Comment by rawtaz** [comment]
Really peculiar thing to happen :D For those interested in a more elaborate analysis, please see [this thread in the forum](https://forum.restic.net/t/1772/8).
