### ISSUE TITLE
"self-update --output" fails to create a new file on Windows

### ISSUE THREAD

**Issue by guyshapiro** [restic/restic#2491]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on windows/amd64

How did you run restic exactly? (/Actual behavior/Steps to reproduce the behavior)
-------------------------------
Got the following error when running restic self-update:
```
$ restic self-update --output restic-new.exe
CreateFile restic-new.exe: The system cannot find the file specified.
```

If I create an empty file named `restic-new.exe` on the current directory, the command runs successfully:

```
$ touch restic-new.exe

$ restic self-update --output restic-new.exe
writing restic to restic-new.exe
find latest release of restic at GitHub
restic is up to date
```

I was able to update from 0.9.4 by creating such empty file.

Expected behavior
-----------------
Restic should check for new version even when the output file doesn't exist.

Related Issues
---------------
On #2248 (self-update doesn't work on Windows), the suggested workaround is to use "--output". 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It's the best backup solution I could find!

**Comment by rawtaz** [comment]
@guyshapiro Thanks for the report! Can you please update (edit) the initial post in this issue such that both examples (when it doesn't work and when it does work) contains the entire command and all the output from restic?

**Comment by guyshapiro** [comment]
_[I updated the report according to @rawtaz request.]_

**Comment by andreaso** [comment]
This doesn't appear to be specific to Windows, but also something I'm seeing on my Linux systems, that `restic self-update --output` requests the specified path to be an existing file.

```
$ mktemp --directory
/tmp/tmp.N7OIm2e9MO
$ /opt/restic/0.9.6/restic self-update --output /tmp/tmp.N7OIm2e9MO/restic
lstat /tmp/tmp.N7OIm2e9MO/restic: no such file or directory
$ touch /tmp/tmp.N7OIm2e9MO/restic
$ /opt/restic/0.9.6/restic self-update --output /tmp/tmp.N7OIm2e9MO/restic
writing restic to /tmp/tmp.N7OIm2e9MO/restic
find latest release of restic at GitHub
latest version is 0.10.0
download SHA256SUMS
download SHA256SUMS.asc
GPG signature verification succeeded
download restic_0.10.0_linux_amd64.bz2
downloaded restic_0.10.0_linux_amd64.bz2
saved 18378752 bytes in /tmp/tmp.N7OIm2e9MO/restic
successfully updated restic to version 0.10.0
$
```

The newly released _restic 0.10.0_ shows a corresponding behavior.

```
$ mktemp --directory
/tmp/tmp.ABJ89sJRmw
$ /opt/restic/0.10.0/restic self-update --output /tmp/tmp.ABJ89sJRmw/restic
lstat /tmp/tmp.ABJ89sJRmw/restic: no such file or directory
$ touch /tmp/tmp.ABJ89sJRmw/restic
$ /opt/restic/0.10.0/restic self-update --output /tmp/tmp.ABJ89sJRmw/restic
writing restic to /tmp/tmp.ABJ89sJRmw/restic
find latest release of restic at GitHub
restic is up to date
$
```

Unless I'm missing something this definitely feels like a bug, just the right size for me to take a stab at.

**Comment by rawtaz** [comment]
> just the right size for me to take a stab at

Go pher it ;-)

**Comment by andreaso** [comment]
Ok, here we go! https://github.com/restic/restic/pull/2937
