### ISSUE TITLE
restic --json and StdErr

### ISSUE THREAD

**Issue by schmitch** [restic/restic#2492]
Hello, it would be cool if std error output stream would also support json output. maybe with a new flag to not break existing users, like --json-std-err.

currently if a previous backup failed somebody would probably want to trigger the following:
1. check if repo exists (this can already fail with a locked error) `restic snapshots`
2. check repository (probably with read data) `restic check`

however when we would only look at the output of the exit value, we would already fail at the first command, besides that we only need to do a command in between `restic unlock`.
if we look at StdError we would see a string message that our program would need to parse to understood whats happened.
so maybe it would be good to have StdError output as json, maybe even with a predefined error enum. so that we cleary know if a repo exists, is locked, does not exists, etc...

**Comment by rawtaz** [comment]
I don't get it. If you are parsing JSON output to determine the result of the operation, and find that there is an error, why not just look in that JSON? Why do you need that JSON to be on stderr instead of stdout?

**Comment by rawtaz** [comment]
@schmitch 👀

**Comment by schmitch** [comment]
actually Stdout is empty.

**Comment by MichaelEischer** [comment]
For standard problems like a repository being locked, I think it would be much more useful to just return a specific exit code as suggested in #956. But it would probably still be a good idea to eventually also provide JSON formatted messages on stderr.

**Comment by MichaelEischer** [comment]
Closing in favor of https://github.com/restic/restic/issues/1804 . To determine whether a repository exists / is locked, specific exit codes are the way to go: #956  .
