### ISSUE TITLE
0.9.6 Is not able to perform any action other than backup

### ISSUE THREAD

**Issue by thetooth** [restic/restic#2496]
Output of `restic version`
--------------------------
restic 0.9.6 (v0.9.6-23-g6c700f95) compiled with go1.11.6 on solaris/amd64

How did you run restic exactly?
-------------------------------
```
[root@208d07d6-bfd3-e22c-ec08-93dc7aefad49 ~]# restic -r ./data check --read-data
using temporary cache in /tmp/restic-check-cache-685837441
enter password for repository: 
repository 7c0cb9de opened successfully, password is correct
created new cache in /tmp/restic-check-cache-685837441
create exclusive lock for repository
load indexes
error: error loading index ac3431bb: ciphertext verification failed
Fatal: LoadIndex returned errors
[root@208d07d6-bfd3-e22c-ec08-93dc7aefad49 ~]# sha256sum data/index/ac3431bbd377cc657348015f2598cb15daa611a4ba61f51e37d2b683489097d0                                        
ac3431bbd377cc657348015f2598cb15daa611a4ba61f51e37d2b683489097d0  data/index/ac3431bbd377cc657348015f2598cb15daa611a4ba61f51e37d2b683489097d0
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
solaris zone in a zpool consisting of 6 disks, single parity

Expected behavior
-----------------
Be able to restore and list snapshots

Actual behavior
---------------
Not possible to do any operation succefully other than the backup itself, of note the very first snapshot with a given tag will always succeed but any further backups that would result in deduplication cause index and snapshots to fail ciphertext verification.

Steps to reproduce the behavior
-------------------------------
```
restic backup /mnt/ps-data --tag ps-data
restic backup /mnt/ps-data --tag ps-data
restic snapshot <-- reports second snapshot as corrupt
restic prune <-- reports index as corrupt
```

**Comment by rawtaz** [comment]
Never seen this before, could it be Solaris specific? Can someone else running rustic on Solaris (if there is anyone else doing that ;) try to reproduce this?

**Comment by thetooth** [comment]
I believe it must be solaris specific, running 0.9.6 on an identical server with ubuntu as the bare metal image works fine obviously. This is smartos so it would be a matter of booting the live image and setting up a zone with go installed, 0.9.2, albeit with some complaining about gcc, works fine on the same data set created by the latest version:
```
[root@208d07d6-bfd3-e22c-ec08-93dc7aefad49 ~]# restic -r ./data check --read-data
password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
read all data
[23:38] 100.00%  22689 / 22689 items
duration: 23:38
no errors were found
```

**Comment by smlx** [comment]
what is the architecture of the server? x86-64 or something else?

**Comment by fd0** [comment]
Huh, that's really odd! Can you try to run the tests please?
 * Clone the repo
 * Run `go test ./...`
 * Can you retry using Go 1.13?

Please report back! This may be a bug in either restic or even Go.

**Comment by MichaelEischer** [comment]
@thetooth Could you provide the information requested by @fd0? Without it we won;t be able to investigate this any further.

**Comment by MichaelEischer** [comment]
Closing this as we don't have enough information to investigate this further. Feel free to provide the requested information and reopen this issue.
