### ISSUE TITLE
repository implementation: writing/reading config file from backend is inconsistent

### ISSUE THREAD

**Issue by aawsome** [restic/restic#2498]
The backend-interface works as follows:

- Files are accessed by a Handle
- the Handle consists of a Type of the file and the ID
- usually the ID should be equal to the SHA-256 Hash of the content

For the config file, there is an exception which is implemented for each backend and also in the repository implementation.
For instance in internal/repository/repository.go func LoadAndDecrypt the Hash is not checked for ConfigFile. This is necessary as the config file is accessed without knowing the ID (i.e. with zero ID).

But in fact, in the same repository implementation in func SaveUnpacked the  ID is computed as Hash of the content.

So the backends get a Save request for (ConfigFile, ID) with the correct Hash ID and a Read request for (ConfigFile, ID{}) (empty ID).

Luckily all backends handle ConfigFile requests as special case and hence this is no real bug ATM.
However I consider this a inconsistent design and suggest to correct it.

I'm about to file a pull request and just want to discuss it in advance.

**Comment by MichaelEischer** [comment]
I don't really see how your proposed changes avoid special casing the backends for the config file. Even if you only hand out default IDs for the config file, the backends still needs special case handling for the config file.

The special casing is usually handled via DefaultLayout / S3LegacyLayout . The only exception is the memory backed which directly uses `restic.Handle` as hash map key. I would expect new backends to use one of the existing Layouts which already handles the special case.

The `test.Suite` for backends also check that a backend properly ignores the ID of a config file.

**Comment by aawsome** [comment]
@MichaelEischer Thank you for your reply!

I understand your point. However, I'm not talking about the layout the backend finally uses to store the data. I'm talking about the interface `Backend`. When writing a new implementation of this interface I would not think a call of `Load` with `(ConfigFile, 0)`should return the content previously saved by `(ConfigFile, 12345...)`.

An example where no handling of this special case is covered is the `Cache` implementation which also fulfills the interface `Backend`. This is why #2516 (which improves speed a lot for high-latency backends by also caching the config file) only works in combination with #2505 .

Of course there could also be the decision that `ConfigFile` is a special case for backends. Then I would propose to add functions `LoadConfig`, `SaveConfig`, `TestConfig` to the interface `Backend`.

So I see the following possibilities:

1. Change repository implementation such that config file access is standard w.r.t. `Backend`
2. Change `Backend` interface (would not suggest this)
3. Live with this inconsistency :smile: - in that case I would have to add code to handle `ConfigFile` in #2516 - and so would all future backends which do not depend on a directory-based storage and thus may not use DefaultLayout...

**Comment by MichaelEischer** [comment]
I agree that either 1 or 3 are good candidates for a solution. As the config file is a special case, there's probably no really clean solution. On second thought, consistently using `(ConfigFile, 0)` is probably the cleaner variant. The cleanest solution would be a changed repository format with a `config` folder. That way restic could consistently use `(ConfigFile, 12345...)`.

I'm not sure whether there are plan to allow repository format upgrades when repository v2 materializes. In case that is possible, the cache needs some way to detect config file changes. The id `(ConfigFile, 0)` would be of no use for that.
