### ISSUE TITLE
Ability to change password

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#2500]
It would be nice, if you could change the repository password. If you ever get compromised...

Output of `restic version`
restic 0.9.5 compiled with go1.13beta1 on linux/amd64

**Comment by rawtaz** [comment]
Already exists, please see `restic help key`. Also please fill out the issue template ;)

**Comment by jtagcat** [comment]
Interesting, searched the docs and issues. I guess I'll have to make docs for `Changing your repository password`.

**Comment by rawtaz** [comment]
It's already there in the documentation. Second hit in https://duckduckgo.com/?q=restic+change+password , it links to https://restic.readthedocs.io/en/latest/070_encryption.html .

**Comment by jtagcat** [comment]
Confused, I missed it.
Ok.
