### ISSUE TITLE
Global cache and system file list

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#2501]
version: `restic 0.9.5 compiled with go1.13beta1 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Currently started backup and stopped it many times, to exclude mainly caches. With excluding sysfiles, you could back up 'everything' (root of the system or C:\)
2 new flags: `--exclude-known-caches` and `--exclude-sysfiles`

They are 2 program-global (built in) `--exclude-file` lists.
- It would probably only make sense, if this list changes, depending on the operating system.
- Instead of making our own local lists, make collaborative lists, saving time.
- Ideally this would be built in and on by default.
- I think it is best to let this be off by default, until we feel more confident.

- By built in, it's probably better to have it independent of the binary, download the list from github, check integrity, cache the file (say get it every month).
-  How do you verify, that the list actually comes from Restic?
- Have `--online-exclude-list https://something`?

What are you trying to do?
--------------------------
Make Restic easier to get started and free up backup storage.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Decided to start hourly backups until I get up better infra.

**Comment by rawtaz** [comment]
@jtagcat Nice thinking to consolidate many people's efforts that are probably spread out and very redundant. I agree that it's unlikely that this would be a thing to maintain in the restic project itself, it's better that it's a collaborative resource in the community.

Have you seen https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files ? I think that the existing exclude flags supports what's needed.

Imagine you have a couple of files from the community, collaboratively built to contain excludes for your OS and what not. You can simply download it and start using it with these existing exclude flags. It would be similar to what people are already doing with dotfiles and IDE exclusion lists, there's a lot of this going on already.

So, I'd say the real suggestion is to agree on where to keep such lists. The forum could be one place.

**Comment by jtagcat** [comment]
I'd propose github.com/restic/exclude-lists

As I'm planning to set up quite a large operation of backups and have decided on restic :tada: I'm willing to be the maintainer of the repository. So I'd ask @fd0 to create the repository.

As far as integrating the lists, I'd say first make the lists, see how people are using them, test, test, test, create stable, beta, nightly (or equivelant) branches and then even think of direct integration.

**Comment by rawtaz** [comment]
In case it happens, I'd suggest github.com/restic/lists instead. It's be impractical to make the repo specific to exclude lists, in case restic gets include support later on (something that's been requested). Let's always try to think ahead when deciding on naming and stuff.

It should also be made clear in the repository that the data in there is community driven and not kept up to date by the restic project.

**Comment by rawtaz** [comment]
@jtagcat Have you started those lists yet? Can you put them in the Recipes section in the forum? I'm inclined to close this issue, because what we're discussing here is not something that will currently be maintained in the restic repository. But it would be a great addition to the community in that Recipes section, it's exactly what it's there for!

**Comment by jtagcat** [comment]
@rawtaz https://github.com/jtagcat/restic-lists
Will do!

**Comment by darkdragon-001** [comment]
Why not just using [`github/gitignore`](https://github.com/github/gitignore)?
- [Linux](https://github.com/github/gitignore/blob/master/Global/Linux.gitignore)
- [Windows](https://github.com/github/gitignore/blob/master/Global/Windows.gitignore)
