### ISSUE TITLE
Clarify "Modification time" in backup reference

### ISSUE THREAD

**Issue by rawtaz** [restic/restic#2502]
In the bullet list at https://restic.readthedocs.io/en/latest/040_backup.html#backing-up there is mention of "Modification time" as one of the things restic looks at to determine if a file changed or not.

In https://github.com/restic/restic/pull/2212 restic changed from using mtime to using ctime for detecting file changes (amongst other methods).

I'm not sure if "Modification time" is still a good description of the new behavior. In a non-technical sense it might accommodate for both mtime and ctime, but perhaps it's too coupled with mtime? In that case, we should probably change this little item in the list to something else.

Thoughts? If changed, would simply making it "Change time" be enough (still not very clear or specific, but perhaps that's how we want it in this usage type of documentation)?

**Comment by MichaelEischer** [comment]
The documentation section has been reworked in PR #2823.
