### ISSUE TITLE
json output for diff

### ISSUE THREAD

**Issue by rrossouw01** [restic/restic#2508]
Output of `restic version`
--------------------------
0.9.6

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
diff output recognize the --json flag

What are you trying to do?
--------------------------
when trying to scale restic we run --quiet on backups with millions of files on NFS mounts to eliminate the scan.  however that mean we do not have results of the backup for later processing/monitoring.  So diff provides kind of a workaround to get at least some of the statistics.  It would be nice if that was json though and possibly also an option not to print the 1000's of +, -, M lines just the file/dir etc changes.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
love it!

**Comment by rrossouw01** [comment]
Even the feature request to have diff honor --json would be nice I need to clarify something.  I thought --quiet would mean no stats at all.  That is not correct if using --quiet and --json together during backup the --json flag provides the stats I need.  It may only provide it if redirecting output to a file I did not check specifically, regardless it works for us.  So I was incorrect to think we have to use diff.

**Comment by rawtaz** [comment]
Is there still a use case for such a feature now that you know you have the JSON output from `backup`? I see you filed a PR, but it seems like there's no problem to solve given what you wrote in this issue :)

**Comment by rrossouw01** [comment]
Correct personally I do not need diif --json for what I am doing.  Thanks for checking.

**Comment by MichaelEischer** [comment]
I've noticed a small misunderstanding regarding the `--quiet` flag: Adding `--quiet` to the backup command currently doesn't disable the scanner, see #2336 .

**Comment by darkdragon-001** [comment]
I do still have a need for this. Especially since the `backup` stats are wrong (#2756). Furthermore, they don't contain `others` (what is this anyways?). `diff` doesn't contain _dirs changed_ though.

**Comment by dp-github** [comment]
What would you consider to be a 'dir changed' condition?

**Comment by darkdragon-001** [comment]
@dp-github I just noticed it is output in the `backup` command. Meta-data (like modified date) could be a reason to qualify as _changed_, but I would prefer not. Since renames are not tracked if I know correctly, this indeed doesn't make sense. Thanks for the hint!

**Comment by dp-github** [comment]
No problem. 

IIRC,  [my pull request](https://github.com/restic/restic/pull/2542#issuecomment-586637449) implementing this feature also honors --quiet.

**Comment by darkdragon-001** [comment]
If I see it correctly, `--quit` controls the changed files list, right? Does this also work in combination with `--json`? I would like to have the changed files list as json as well, but often it is not needed...

**Comment by Mrodent** [comment]
I'd really like to see this. I'm a restic newb, so please bear with me, but I express in [this forum post](https://forum.restic.net/t/efficient-check-for-unchanged-source/3729/8?u=mrodent) a few doubts about whether the JSON output from restic backup is necessarily comprehensive enough for all purposes.

From my experiments so far, it appears that all the figures in this JSON object can be at 0, and yet that it is possible that things may have changed relative to the snapshot of interest to you... in particular, I am currently tagging snapshots "10-minutes", "hour", "day", etc. to identify the "snapshot strands" within the repo to which they belong: each time you do a new snapshot, the stats produced will be relative to whatever it can find (blobs, etc.) in the repo, not to other snapshots which happen to have the same tag.

So I've now switched to using `restic diff` and this is slightly irksome because the output is non-JSON and has to be parsed (Python, after `subprocess.run`):

    pattern_string = fr'^Files:\s+(\d+)\s+new,\s+(\d+)\s+removed,\s+(\d+)\s+changed$'

etc.

**Comment by MichaelEischer** [comment]
After taking another look at the json output for the diff command suggested in #3592 and #2542, let's do it the following way:

The output should be a streaming format as in the backup command. That is each JSON message is encoded as a single line and different JSON messages are separated by a single line break. The messages also include a `MessageType` field to simplify decoding. This yields the following JSON message types:

Adapted from https://github.com/restic/restic/pull/3592/files#diff-be71d8d0dfca54ae1d6d65c1189fc8a91ba960c928247057f92774807cf8da8bR241-R244
```go
type Change struct {
	MessageType  string  `json:"message_type"` // "change"
	Path     string `json:"path"`
	Modifier string `json:"modifier"`
}
```
That change struct is the direct equivalent to the current text output and only contains the bare minimum of information. We could also use a more extensive output format as in `borg diff --json-line`: 
https://borgbackup.readthedocs.io/en/stable/usage/diff.html


Adapted from https://github.com/restic/restic/pull/2542/files#diff-be71d8d0dfca54ae1d6d65c1189fc8a91ba960c928247057f92774807cf8da8bR69-R75
```go
type DiffStat struct {
	MessageType  string  `json:"message_type"` // "statistics"
	Files     int    `json:"files"`
	Dirs      int    `json:"dirs"`
	Others    int    `json:"others"`
	DataBlobs int    `json:"data_blobs"`
	TreeBlobs int    `json:"tree_blobs"`
	Bytes     uint64 `json:"bytes"`
}
```
The statistics are output last after all other changes. If the diff command is started using `diff --quiet` then only the statistics should be output. That way it remains trivial to just parse the statistics if that's all one is interested in.
