### ISSUE TITLE
restic support alibaba cloud OSS

### ISSUE THREAD

**Issue by haoshuwei** [restic/restic#2512]
restic should add to support alibaba cloud OSS (Object Storage Service)

**Comment by dimejo** [comment]
Restic supports Alibaba cloud OSS via [rclone](https://rclone.org/). Please have a look at the [documentation on restic & rclone](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone) on how to use them.

IMHO there's no need to add yet another backend to restic.

**Comment by haoshuwei** [comment]
@dimejo thanks, i'll have a try

**Comment by rawtaz** [comment]
Closing this as the support is already available through rclone.
