### ISSUE TITLE
Group commands in help/usage

### ISSUE THREAD

**Issue by aawsome** [restic/restic#2514]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Please group the restic commands in the help page. At the moment they are just sorted by name:
```
Available Commands:
  backup        Create a new backup of files and/or directories
  cache         Operate on local cache directories  
  cat           Print internal objects to stdout
  check         Check the repository for errors
  diff          Show differences between two snapshots
  dump          Print a backed-up file to stdout
  find          Find a file, a directory or restic IDs
  forget        Remove snapshots from the repository
  generate      Generate manual pages and auto-completion files (bash, zsh)
  help          Help about any command
  init          Initialize a new repository
  key           Manage keys (passwords)
  list          List objects in the repository
  ls            List files in a snapshot
  migrate       Apply migrations
  mount         Mount the repository
  prune         Remove unneeded data from the repository
  rebuild-index Build a new index file
  recover       Recover data from the repository
  restore       Extract the data from a snapshot
  self-update   Update the restic binary
  snapshots     List all snapshots
  stats         Scan the repository and show basic statistics
  tag           Modify tags on snapshots
  unlock        Remove locks other processes created
  version       Print version information
```

I would like to start the discussion about a good grouping in this issue. My first suggestion is:
```
Available Commands:

Every-day usage:
  init          Initialize a new repository
  key           Manage keys (passwords)
  backup        Create a new backup of files and/or directories
  check         Check the repository for errors
  snapshots     List all snapshots
  stats         Scan the repository and show basic statistics
  tag           Modify tags on snapshots

Retrieving from backup:
  diff          Show differences between two snapshots
  find          Find a file, a directory or restic IDs
  ls            List files in a snapshot
  restore       Extract the data from a snapshot
  mount         Mount the repository

Cleaning backups:
  forget        Remove snapshots from the repository
  prune         Remove unneeded data from the repository

General:
  generate      Generate manual pages and auto-completion files (bash, zsh)
  help          Help about any command
  self-update   Update the restic binary
  version       Print version information

Expert commands:
  cache         Operate on local cache directories  
  migrate       Apply migrations
  rebuild-index Build a new index file
  recover       Recover data from the repository
  unlock        Remove locks other processes created

For technical insights:
  cat           Print internal objects to stdout
  dump          Print a backed-up file to stdout
  list          List objects in the repository
```

I know that cobra doesn't support this at the moment. But there is an open issue about this, see spf13/cobra#836

Having already discussed a grouping structure would lead to a quick implementation once the cobra issue is solved.

What are you trying to do?
--------------------------

Make the restic help more helpful and let people faster find the restic command they need.
I think grouping would also increase chance that non-experts don't get unexpected results when using expert commands. This would increase user acceptance.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I like using it and I like contributing to it :smile:

**Comment by rawtaz** [comment]
I started to write a lot of examples but it became too much to write so I'll skip that and just say that IMO this isn't a good idea.

Reason is that everyone and their cat is using restic their own way, so which commands belongs in which groups is individual. Personally I never had to use the `key` and `stats` commands, yet in your example they are listed under "every day commands".

However you group the commands, you'll always be miscategorizing them for a huge amount of users. IMO it's better to just keep a neutral presentation of them. E.g. as it is now, an alphabetical one.

**Comment by rawtaz** [comment]
After some consideration I'm closing this issue now for the following reasons:

- The feature needed in Cobra isn't implemented yet and who knows if and when it will be.
- I think that restructuring the restic documentation (which I'm looking into right now) might alleviate the need for the suggestions in this issue quite a bit.

Let's re-open it if/when appropriate. Thanks for your input and example @aawsome!
