### ISSUE TITLE
Provide FreeBSD aarch64 binaries

### ISSUE THREAD

**Issue by mathstuf** [restic/restic#2517]
Output of `restic version`
--------------------------

N/A

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Pre-built binaries for FreeBSD aarch64. This is the recommended architecture for FreeBSD on modern Raspberry Pi devices.

What are you trying to do?
--------------------------

Run restic on my Raspberry Pi.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Reliable backups and easy restoration :) . About to restore to a new laptop this week (already done this for another new machine before and it's a breeze).

**Comment by rawtaz** [comment]
@mathstuf Have you built restic on that platform successfully (and maybe even ran the tests)?

**Comment by mathstuf** [comment]
My hardware is probably a bit anemic for it right now (plus, I'd like to avoid unnecessary wear on the SD card it has). I'll see if I can dig up other aarch64 hardware to test on.

However, I see that Fedora builds it on aarch64 at least, so that should be sufficient from the arch angle. I assume FreeBSD's API is not so radically different to make that implausible either.

For CI, [sr.ht](https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd) is likely the closest to being there, but Cirrus-CI is also plausible (FreeBSD is already supported there).

**Comment by rawtaz** [comment]
I'm not in charge of the building so I can't say, but I would expect/guess that whatever platforms we support binaries for must be suitable in the current build system we use. Regardless, this one is for core maintainers to take a look at. Thanks @mathstuf.

**Comment by mathstuf** [comment]
It looks like support just landed in the toolchain recently: https://github.com/golang/go/issues/24715 so the fact that this is missing shouldn't be too much of a surprise I suppose.

**Comment by mathstuf** [comment]
FWIW, `pkg install restic` now works. I'm going to close this as that process also makes it easier to keep it up-to-date.
