### ISSUE TITLE
restic has very high memory usage

### ISSUE THREAD

**Issue by CendioOssman** [restic/restic#2519]
Output of `restic version`
--------------------------

`restic 0.9.5 compiled with go1.11.5 on linux/amd64`

How did you run restic exactly?
-------------------------------

`/usr/bin/restic --quiet --repo b2:<repo> <backupdir>`

With `$RESTIC_PASSWORD`, `$B2_ACCOUNT_ID` and `$B2_ACCOUNT_KEY` set. The backup directory is about 1.4 TB.

Same issue seen trying to do restore using similar conditions.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze.

Expected behavior
-----------------

restic completes the task with modest memory usage.

Actual behavior
---------------

restic baloons to 10+ GB memory usage. On one machine the OOM killer nuked it because of this.

Steps to reproduce the behavior
-------------------------------

Seems to happen every run.

Do you have any idea what may have caused this?
-----------------------------------------------

Not really. Large backup directory?

Do you have an idea how to solve the issue?
-------------------------------------------

Nope.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

In general restic does what it is supposed to do. It does seem to have some scaling issues though, like this memory usage.

**Comment by dimejo** [comment]
High memory usage with a lot of files is a know issue (#1988). Running `export GOGC=20` before your backup might help.

**Comment by rawtaz** [comment]
As @dimejo writes, this is known since before. For that reason I'll close this issue. Feel free to add further comments, and don't hesitate to let us know if you managed to ease the situation with that `GOGC=20` environment!
