### ISSUE TITLE
add alibaba cloud oss backend in restic

### ISSUE THREAD

**Issue by haoshuwei** [restic/restic#2520]
Restic supports Alibaba Cloud OSS as a backend. Export the Alibaba Cloud access key and secret as follows:
```
$ export ALIBABA_CLOUD_ACCESS_KEY_ID=<ACCESS_KEY_ID>
$ export ALIBABA_CLOUD_ACCESS_KEY_SECRET=<ACCESS_KEY_SECRET>
```
Afterwards you can use the ``oss:`` backend type to initialize a repository in the bucket ``foo`` at the root path:

```
$ restic -r oss:oss-cn-hangzhou.aliyuncs.com/foo init
enter password for new backend:
enter password again:
created restic repository 62494f11a1 at oss:oss-cn-hangzhou.aliyuncs.com/foo
[...]
```

The number of concurrent connections to the OSS service can be set with the
``-o oss.connections=10`` switch. By default, at most five parallel connections are
established.

**Comment by rawtaz** [comment]
@haoshuwei Your initial post in this issue states that restic *does* support Alibaba. This isn't the case. I presume you wanted to say that with your PR, it does.

There is no need for a new backend in restic, because you can already use Alibaba through the clone backend. Introducing another backend in restic to support Alibaba means additional maintenance for a feature that is already supported.

Please see https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone for general instructions on how to use the clone backend, which then gives you access to Alibaba.

**Comment by dimejo** [comment]
@ncw wrote in [this post](https://github.com/restic/restic/issues/1354#issuecomment-453763202) that Alibaba OSS is S3 compatible. Maybe adding a note to the documentation of [restic & Amazon S3](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#amazon-s3) would be enough to make this work?

@haoshuwei Can you verify that Alibaba OSS works with the S3 backend?

**Comment by rawtaz** [comment]
Would be best if this was done through https://github.com/restic/restic/issues/2490 :)

**Comment by haoshuwei** [comment]
> @ncw wrote in [this post](https://github.com/restic/restic/issues/1354#issuecomment-453763202) that Alibaba OSS is S3 compatible. Maybe adding a note to the documentation of [restic & Amazon S3](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#amazon-s3) would be enough to make this work?
> 
> @haoshuwei Can you verify that Alibaba OSS works with the S3 backend?

Alibaba OSS now only support `Virtual hosted style` (S3 v2), so it has some problems when using restic.

**Comment by haoshuwei** [comment]
> @haoshuwei Your initial post in this issue states that restic _does_ support Alibaba. This isn't the case. I presume you wanted to say that with your PR, it does.
> 
> There is no need for a new backend in restic, because you can already use Alibaba through the clone backend. Introducing another backend in restic to support Alibaba means additional maintenance for a feature that is already supported.
> 
> Please see https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone for general instructions on how to use the clone backend, which then gives you access to Alibaba.

Yes, I mean that with my PR, restic can support alibaba cloud oss in the way `restic -r oss:oss-cn-hangzhou.aliyuncs.com/foo init`.  It's right that `rclone` can also do this, but it involves a rclone binary file and an established configuration. In addition, I'm working on the [velero](https://github.com/vmware-tanzu/velero) project to backup files to oss through restic, it is convenient to use restic directly instead of involving a new rclone tool.

**Comment by haoshuwei** [comment]
I suggest that we should supoort oss backend directly in restic instead of using another rclone tool, releated [PR #2521](https://github.com/restic/restic/pull/2521). Maybe in the future, restic can support a plugin architecture to let users contribute and maintain there own backend

**Comment by haoshuwei** [comment]
I really expect that I can add the `Alibaba Cloud Object Storage` which is already widely used just like `Microsoft Azure Blob Storage` and `Google Cloud Storage`.

**Comment by rawtaz** [comment]
> Alibaba OSS now only support Virtual hosted style (S3 v2), so it has some problems when using restic.

Can you elaborate? What are the exact problems? Are you effectively saying that clone doesn't work with ACOS?

**Comment by haoshuwei** [comment]
> > Alibaba OSS now only support Virtual hosted style (S3 v2), so it has some problems when using restic.
> 
> Can you elaborate? What are the exact problems? Are you effectively saying that clone doesn't work with ACOS?

these are the commands and outputs below:
```
$ export RESTIC_REPOSITORY="s3:https://oss-cn-hangzhou.aliyuncs.com/restic-demo"
$ export AWS_ACCESS_KEY_ID=xxx
$ export AWS_SECRET_ACCESS_KEY=xxx
$ export RESTIC_PASSWORD=xxx
$ restic init
Fatal: create repository at s3:https://oss-cn-hangzhou.aliyuncs.com/restic-demo failed: client.BucketExists: Please use virtual hosted style to access.
```
as I say above, Alibaba OSS now only support Virtual hosted style (S3 v2), so if i change to use Virtual hosted style:
```
$ export RESTIC_REPOSITORY="s3:https://restic-demo.oss-cn-hangzhou.aliyuncs.com"
$ restic init
Fatal: create repository at s3:https://restic-demo.oss-cn-hangzhou.aliyuncs.com failed: s3: bucket name not found
```
restic doesn't support Virtual hosted style yet.

**Comment by smlx** [comment]
it looks as though the path-style bucket access is [going away in less than a year](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/):
> Support for the path-style model continues for buckets created on or before September 30, 2020. Buckets created after that date must be referenced using the virtual-hosted model.

the existing s3 backend will have to either be updated to support the virtual-hosted model, or deprecated in favour of rclone I guess.

either way, probably no point in adding a special backend just for alibaba cloud.

**Comment by rawtaz** [comment]
@haoshuwei And what if you use it through/with clone? Are you saying that doesn't work either?

**Comment by haoshuwei** [comment]
> @haoshuwei And what if you use it through/with clone? Are you saying that doesn't work either?

rclone works with oss， but it involves a binary file and an established configuration which is inconvenient to be integrated by other tools, such as [velero](https://github.com/vmware-tanzu/velero) project.

**Comment by cuericlee** [comment]
> it looks as though the path-style bucket access is [going away in less than a year](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/):
> 
> > Support for the path-style model continues for buckets created on or before September 30, 2020. Buckets created after that date must be referenced using the virtual-hosted model.
> 
> the existing s3 backend will have to either be updated to support the virtual-hosted model, or deprecated in favour of rclone I guess.
> 
> either way, probably no point in adding a special backend just for alibaba cloud.

AlibabaCloud is No.3 biggest IaaS provider world wide, and it is most popular cloud in Asia.  See [Gartner report](https://www.gartner.com/en/newsroom/press-releases/2019-07-29-gartner-says-worldwide-iaas-public-cloud-services-market-grew-31point3-percent-in-2018). It is why @haoshuwei  contribute object store backend oss of AlibabaCloud to project restic to make  end users of cloud easily leverage tools like restic at Asia. Considering the huge users numbers of Alibabacloud from Asia, pls re-think about PR #2521 .

**Comment by cuericlee** [comment]
@smlx scott, would you like to review PR #2521 , thanks!

**Comment by ncw** [comment]
Getting restic to support virtual hosted style would be easier than merging an entire backend wouldn't it?  That is the approach I took with rclone.  Rclone uses the AWS SDK and it is just a matter of using `WithS3ForcePathStyle`.

I think to make this work with the minio s3 sdk restic uses, you'd have to set `BucketLookup` in `Options` to `BucketLookupDNS` or `BucketLookupPath` which should be a couple of lines of code only.

**Comment by fd0** [comment]
@haoshuwei thank you very much for your contribution! Unfortunately, adding a new backend to restic comes with a high maintenance burden, which remains with us, the developers and maintainers. We're very reluctant to do that if there's a viable alternative.

In this case I fully agree with @ncw, we should fix the s3 backend so that it can be used with Alibaba. That's much easier to do. Then users have two ways of using Alibaba: either via `rclone` or via the native s3 backend.

So, if you're interested in making this work, please look into how [minio-go](https://github.com/minio/minio-go) (the s3 library we're using for accessing s3) can be used with Alibaba. @ncw provided some helpful hints.

Since I don't have an account with Alibaba, I cannot test this myself.

I'm closing this issue for now, we prefer not adding a new backend but rather fixing the `s3` backend. I've created issue #2528 for that. Please feel free to add further comments. Thanks!
