### ISSUE TITLE
Restic backup reports success exit status even when there were issues during backup

### ISSUE THREAD

**Issue by rigtorp** [restic/restic#2526]
Related to #2364 and #2461 

Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.13beta1 on linux/amd64

How did you run restic exactly?
-------------------------------

```bash
$ restic init -r testrepo
enter password for new repository: 
Fatal: an empty password is not a password
$ restic init -r testrepo
enter password for new repository: 
enter password again: 
created restic repository be2d96646f at testrepo

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
$ mkdir testbak
$ touch testbak/testfile
$ chmod -r testbak/testfile 
$ restic -r testrepo backup testbak
enter password for repository: 
repository be2d9664 opened successfully, password is correct
created new cache in /home/erkki/.cache/restic
error: open testbak/testfile: permission denied

Files:           0 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 494 B

processed 0 files, 0 B in 0:00
snapshot ff4e4672 saved
$ echo $?
0
```

Expected behavior
-----------------

Restic returns non-zero exit status so that automated backups can be monitored for failure.

Actual behavior
---------------

Restic returns 0 exit status even though there were issues reading files during the backup process.

Steps to reproduce the behavior
-------------------------------

See above

Do you have any idea what may have caused this?
-----------------------------------------------

Correct behavior was never implemented.

Do you have an idea how to solve the issue?
-------------------------------------------

Backup function should return a special warning error for these types of non-fatal errors. In main.go this error should be detected with `error.Is()` and return a special warning exit status.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Everyday I receive an email informing me my scheduled backup was successful, I feel reassured my data is stored safely by restic!

**Comment by Summerdave** [comment]
Currently, the backup code just counts errors as they occur but does not take any action on them. I created a PR that changes this behavior, by simply throwing an error after the backup is done. However I think error handling should be more fine-grained than this. For instance, one might not want "incomplete" snapshots, and would want the `backup` command to fail, once an error occurs, or one might simply want to backup everything possible.

**Comment by rawtaz** [comment]
I'd love to merge this PR, but I'm hesitant before it's been established that it's okay to do so considering backwards compatibility. I imagine a lot of people have restic running by scripts and some might see very different results when this PR is merged.

So basically, should we just go ahead and merge it? Personally I'm *for* making changes that cleans up and corrects things, even if one has to adjust stuff when upgrading (after all, there's a changeling). Just want to make sure everyone is on the same page.

**Comment by diegosainz** [comment]
We just got bitten by this behavior: some files were not being backed up due to access denied (err 13).

This was a surprise when trying to restore a backup: the file was not there and no errors were reported from the automation scripts (due to our fault on monitoring only the exit code as usual and not the JSON output):

```json
{"message_type":"error","error":{"Op":"open","Path":"/some/important/file","Err":13},"during":"archival","item":"/some/important/file"}
{"message_type":"summary","files_new":0,"files_changed":1,"files_unmodified":1861,"dirs_new":0,"dirs_changed":5,"dirs_unmodified":0,"data_blobs":1,"tree_blobs":6,"data_added":1204232,"total_files_processed":1862,"total_bytes_processed":1085946412,"total_duration":6.430003623,"snapshot_id":"45f60183"}
{"message_type":"status","seconds_elapsed":6,"percent_done":0.980055420082736,"total_files":1951,"files_done":1862,"total_bytes":1085946412,"bytes_done":1064287667,"error_count":99}

Return code: 0
```

I think it would be correct to exit with error code > 0 on any error: when a backup completes without an error code it should be trusted that everything was backed up as expected. This simplifies using restic in scripts, without parsing the output (text or JSON).

To keep previous behavior maybe adding a flag `--ignore-access-errors` or something similar to allow backup completion even if errors occurs?

**Comment by bclermont** [comment]
I confirm @diegosainz issue, was sure our backup was complete until:

```console
{"message_type":"status","percent_done":0,"total_files":1,"total_bytes":13275}
{"message_type":"error","error":{"Op":"open","Path":"/acme/acme.json","Err":13},"during":"archival","item":"/acme/acme.json"}
{"message_type":"summary","files_new":0,"files_changed":0,"files_unmodified":0,"dirs_new":0,"dirs_changed":0,"dirs_unmodified":0,"data_blobs":0,"tree_blobs":1,"data_added":353,"total_files_processed":0,"total_bytes_processed":13275,"total_duration":0.222863199,"snapshot_id":"4f47a906"}
$ echo $?
0
```

**Comment by rigtorp** [comment]
@rawtaz I think the last two comments shows why it's preferable to change this behavior than to preserve backwards compatibility.

**Comment by lgommans** [comment]
> Personally I'm *for* making changes that cleans up and corrects things, even if one has to adjust stuff when upgrading (after all, there's a changelog). Just want to make sure everyone is on the same page.

I agree, I'd much rather my backup *script* breaks (I should notice that, either due to manual monitoring or some alert system) than that my backup *data* turns out to be incomplete upon restore!

The change could simply be merged or it could be announced that it will be merged at some defined point in the future, but either way a change like this should definitely be included. We could additionally make apt-listchanges display/report this upon upgrading, for those that get restic from the repositories.
