### ISSUE TITLE
Correct design documentation re: "cat tree"

### ISSUE THREAD

**Issue by dp-github** [restic/restic#2527]
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.11.5 on linux/amd64

Describe the issue
------------------

The [Restic Design Documentation page ](https://restic.readthedocs.io/en/v0.3.2/Design/#keys-encryption-and-mac)includes a section entitled "Trees and Data" which describes the `restic cat tree` command.  This command is not actually supported by the program.  This documentation should be updated to describe the `restic cat blob` command which actually performs the function described.

**Comment by fd0** [comment]
Oh, thanks for the hint! Are you maybe up for a PR? :)

**Comment by dp-github** [comment]
Actually, looking into this further, I learned three things:

- The design documentation is included in the git repository
- This problem was already corrected there
- The online documentation linked in the issue description is out of date.  

So perhaps this issue should be updated to 'refresh the documentation at **https://restic.net** and *https://restic.readthedocs.io/en/stable/**

**Comment by MichaelEischer** [comment]
@dp-github https://restic.readthedocs.io/en/stable/ already mentions `restic cat blob`. And I couldn't find links to old documentation version at https://restic.net . Did you notice any further outdated links/documentation?

**Comment by dimejo** [comment]
> And I couldn't find links to old documentation version at https://restic.net . Did you notice any further outdated links/documentation?

I was linked to the same site (v0.3.2) when I was searching for something on Google and barely noticed that it's outdated. I'm wondering if it would be possible to exclude old documentation from search results or display a header when browsing documentation for older versions of restic.

**Comment by MichaelEischer** [comment]
read the docs seems to have an option to display a version warning on old versions of the documentation:
https://docs.readthedocs.io/en/stable/versions.html#version-warning

**Comment by MichaelEischer** [comment]
The version warning on readthedocs is enabled. Thus there's nothing left to do here.
