### ISSUE TITLE
s3: Support virtual hosted access (e.g. for Alibaba)

### ISSUE THREAD

**Issue by fd0** [restic/restic#2528]
@haoshuwei reported that the s3 backend cannot be used at the moment with Alibaba, restic seems to use the wrong kind of access method (path-style vs. virtual-hosted style). This issue tracks fixing that using `minio-go`. @ncw did some research already in https://github.com/restic/restic/issues/2520#issuecomment-569545758

**Comment by ncw** [comment]
I've made an attempt at this - see #2535 

It seems to work for me :-)

See the PR for instructions
