### ISSUE TITLE
Redownload cached index file if invalid

### ISSUE THREAD

**Issue by MichaelEischer** [restic/restic#2533]
Current restic version: `0.9.6`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
The cache used by restic sometimes ends up with a cache containing broken index files, see #2320, #2455, #2270. restic should try to redownload the index files when decoding the index fails.

My envisioned implementation is rather simple: Drop the index file from the cache when decoding fails and try the whole index decoding again. In case only the locally cached copy is broken, this will automatically fix the problem. In all other cases the index file will be downloaded one more time than with the currently implementation.

It would also be possible to just check for the file size, which is returned from the `repository.List` call. Or to only delete the snapshot when it's content hash doesn't match the filename. Just checking for failed decoding is simpler though and should cover all possible data corruptions.

What are you trying to do?
--------------------------
Make restic more resilient to slightly broken files.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
So far restic kept all my backed up data safe :-) (unlike some other software...).

**Comment by MichaelEischer** [comment]
This also applies to invalid snapshots.

**Comment by molecular** [comment]
Running into this (see my comment in #3313)
