### ISSUE TITLE
Restore is slower on newer versions (s3)

### ISSUE THREAD

**Issue by seqizz** [restic/restic#2539]
Output of `restic version`
--------------------------
Since this is a comparison between, both of them:
- restic 0.9.6 compiled with go1.13.4 on linux/amd64
- restic 0.9.3 compiled with go1.11.1 on linux/amd64
(both binaries downloaded from `releases` page

How did you run restic exactly?
-------------------------------
`time restic restore --no-cache -t test_restore 65735d82`

Output for both cases,
0.9.6:
```
repository 81d34315 opened successfully, password is correct
restoring <Snapshot 65735d82 of [/home /backup] at 2020-01-07 02:15:43.014065079 +0000 UTC by root@myhostname> to test_restore
restic restore --no-cache -t test_restore 65735d82  3461.48s user 107.45s system 102% cpu 57:59.47 total
```
0.9.3:
```
repository 81d34315 opened successfully, password is correct
restoring <Snapshot 65735d82 of [/home /backup] at 2020-01-07 02:15:43.014065079 +0000 UTC by root@myhostname> to test_restore
restic restore --no-cache -t test_restore 65735d82  223.43s user 36.25s system 42% cpu 10:17.70 total
```

Environment:
```
AWS_ACCESS_KEY_ID=myid
AWS_SECRET_ACCESS_KEY=myaccesskey
RESTIC_PASSWORD_FILE=/etc/backup/myresticpassfile
RESTIC_REPOSITORY=s3:http://myminio.endpoint:8888/mybucket
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Minio server:
```
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
```

Expected behavior
-----------------
Restore in same time (or maybe a bit faster?)

Actual behavior
---------------
0.9.6 takes 50+ minutes to restore 13GB snapshot, while 0.9.3 completes it in 10 minutes.

Steps to reproduce the behavior
-------------------------------
- Create a bucket
- Backup a 10+ GB folder with 10000+ files in it
- Try to restore

Do you have any idea what may have caused this?
-----------------------------------------------
Initial restore took suspiciously long with the latest release.
Quick check on release notes pointed to the parallel restore change on 0.9.4. This is why I've re-tried with 0.9.3 specifically.

Do you have an idea how to solve the issue?
-------------------------------------------
Maybe testing with different parallel workers? (I am relatively new on restic so I'd be thankful if you show the way, I can build it but not sure which values to change)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Are you kidding? It's the best backup tool I've used :smiley_cat:

**Comment by ifedorenko** [comment]
Any chance you can test restore performance with restic built from https://github.com/ifedorenko/restic/tree/out-of-order-restore-no-progress branch? (see https://github.com/restic/restic/pull/2195 for more details about the branch)

**Comment by seqizz** [comment]
Thanks for quick reply. Here is the result:
```
~> ./restic_alternate version                                                                                                                          
restic 0.9.6 (v0.9.6-23-gab23ab91) compiled with go1.12.9 on linux/amd64
~> time ./restic_alternate restore --no-cache -t test_restore 65735d82                                                                                 
repository 81d34315 opened successfully, password is correct
restoring <Snapshot 65735d82 of [/home /backup] at 2020-01-07 02:15:43.014065079 +0000 UTC by root@myhostname> to test_restore
./restic_alternate restore --no-cache -t test_restore 65735d82  211.05s user 32.49s system 103% cpu 3:54.30 total
```
Way better :tada:

**Comment by ifedorenko** [comment]
My guess that you restore a number of large files, which are particularly affected by the O(N^2) bug I mentioned in the PR. I am closing this issue, please follow #2195 for further updates.

**Comment by seqizz** [comment]
Alright, sounds good.
Also tried that build with a bigger repo (140+gb, 1M+ files) which finished under an hour. Terribly better. Thanks again.
