### ISSUE TITLE
About restic backup success or failure

### ISSUE THREAD

**Issue by aaa3060** [restic/restic#2549]
When I check the content of the backup log, which looks like as below, I can only identify how many files were backed up and how much space was occupied. Since there are neither error nor success messages, how can I make sure the backup completed successfully and without errors? Do no warnings and errors seen in this log mean "backup completed successfully and without errors"?

Files:           6 new,     0 changed,     6 unmodified
Dirs:            0 new,     3 changed,     0 unmodified
Added to the repo: 8.802 GiB

processed 12 files, 128.390 GiB in 52:25
snapshot 0863adf4 saved

If there are some files and part of them were backed up with errors while the others were backed up successfully without errors, can those backed up successfully be restored normally?

**Comment by MichaelEischer** [comment]
Your backup log doesn't contain any lines saying "error" thus all files were read successfully. See #2526 for an example of a log containing errors. The last line `snapshot 0863adf4 saved` indicates that restic successfully created a snapshot from which you can restore later on. Note that the exit status of restic currently does not reflect whether there have been any errors or not.

Even if there were some errors, restic would still backup every file it can read. That is you should be able to restore all files which were backed up without printing an error.

**Comment by rawtaz** [comment]
@aaa3060 This is a usage question (as opposed to a bug report or feature request), which belong in the [forum](https://forum.restic.net/) (as mentioned in the issue template). @MichaelEischer cave you the answer, so I'm closing this now. Feel free to use the forum for usage discussions, it's actually pretty active!
