### ISSUE TITLE
Update Go version to 1.13.6 in Docker build script

### ISSUE THREAD

**Issue by iambryancs** [restic/restic#2551]
## Output of `restic version`
n/a

## How did you run restic exactly?
The issue is not directly related to restic but with the way its Docker image is built when you run:
```
./docker/build.sh
```

## What backend/server/service did you use to store the repository?
n/a

## Expected behavior
A `restic/restic:latest` Docker image is built

## Actual behavior
```
go build github.com/restic/restic/internal/errors: module requires Go 1.13
go build github.com/restic/restic/internal/debug: module requires Go 1.13
go build github.com/restic/restic/internal/hashing: module requires Go 1.13
go build github.com/restic/restic/internal/textfile: module requires Go 1.13
go build github.com/restic/restic/internal/ui/table: module requires Go 1.13
go build github.com/restic/restic/internal/selfupdate: module requires Go 1.13
build failed: exit status 1
exit status 1
```

## Steps to reproduce the behavior
From the root of the repo, run:
```
./docker/build.sh
```

## Do you have any idea what may have caused this?
Yes. During the build of binary, it requires Go version 1.13. The current version used is 1.11.

## Do you have an idea how to solve the issue?
Yes. Use Docker image of Go with version 1.13

## Did restic help you or made you happy in any way?
Absolutely!

**Comment by fd0** [comment]
Closed in #2552
