### ISSUE TITLE
support TLS v1.3 for rest backend

### ISSUE THREAD

**Issue by Josua-SR** [restic/restic#2553]
Output of `restic version`
--------------------------

restic 0.9.6 (v0.9.6-40-gd70a4a93) compiled with go1.12.15 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Connect successfully to a restic rest server that is secured by TLS v1.3 **only**

What are you trying to do?
--------------------------

I have a restic rest server behind an nginx reverse proxy that enforces TLS v1.3 - and I am trying to backup to this rest server.

```
./restic -r rest:https://secret.com/path/ init
Fatal: create repository at rest:https://secret.com/path/ failed: Post https://secret.com/path/?create=true: remote error: tls: protocol version not supported
```

By playing with the nginx configuration I was able to verify that this error occurs when TLS v1.2 (or lower) is disabled:
```
ssl_protocols TLSv1.3; # <-- causes restic client to fail with above error message
ssl_protocols TLSv1.3 TLSv1.2; # <-- works with restic
```

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Not yet, sorry folks ::/ .. maybe later

**Comment by MichaelEischer** [comment]
Can you try to set the environment variable `GODEBUG="tls13=1"`? Go 1.12 does not enable TLS 1.3 by default.

A more permanent solution would be to build restic with Go 1.13 which would enable TLS 1.3 by default or to use the following snippet to automatically set the environment variable for builds with Go 1.12: https://github.com/golang/go/commit/48bb61166711f47eb401f245c704a5a4887d4503

**Comment by Josua-SR** [comment]
@MichaelEischer that environment variable works a charm.
I wasn't expected tls1.3 to be disabled - because my google foo actually revealed tls 1.3 as a feature of golang 1.12 - but I didn't notice the part about opting in explicitly :(

**Comment by fd0** [comment]
Building restic with Go >= 1.13 (or using one of the release binaries) will automatically enable TLS 1.3 by default, so there's nothing we need to do here. I think this is resolved, so I'm closing this issue. Please feel free to add further comments. Thanks!
