### ISSUE TITLE
 ciphertext verification failed   

### ISSUE THREAD

**Issue by puzich** [restic/restic#2557]
Output of `restic version`
--------------------------
0.9.6

How did you run restic exactly?
-------------------------------
export AWS_ACCESS_KEY_ID="******"
export AWS_SECRET_ACCESS_KEY="******"
export RESTIC_REPOSITORY="s3:backup.******.com:9000/backup"
CACERT_FILE="/root/s3_bucket.crt"

restic check

and

restic prune

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Minio

Expected behavior
-----------------
To check the Repo and to delete old snapshots

Actual behavior
---------------
I get the following errors:

# restic check
check snapshots, trees and blobs                                                                                                                                 
error for tree 477eaa0e:                                                                                                                                         
  tree 477eaa0e: node with empty name                                                                                                                            
Fatal: repository contains errors

# restic prune                                                                                                                       
enter password for repository:                                                                                                                                   
repository 8bd877c6 opened successfully, password is correct                                                                                                     
counting files in repo                                                                                                                                           
building new index for repo                                                                                                                                      
[3:51] 100.00%  48518 / 48518 packs                                                                                                                              
repository contains 48518 packs (2121985 blobs) with 127.387 GiB                                                                                                 
processed 2121985 blobs: 39374 duplicate blobs, 2.994 GiB duplicate                                                                                              
load all snapshots                                                                                                                                               
find data that is still in use for 6215 snapshots                                                                                                                
decrypting blob 7a624f7903cc49b396e5c1745098f69e30290f2dc121b6770dc8d8ccbfef9687 failed: ciphertext verification failed                                          
github.com/restic/restic/internal/repository.(*Repository).loadBlob                                                                                              
        github.com/restic/restic/internal/repository/repository.go:179                                                                                           
github.com/restic/restic/internal/repository.(*Repository).LoadTree                                                                                              
        github.com/restic/restic/internal/repository/repository.go:719                                                                                           
github.com/restic/restic/internal/restic.FindUsedBlobs                                                                                                           
        github.com/restic/restic/internal/restic/find.go:11                                                                                                      
github.com/restic/restic/internal/restic.FindUsedBlobs                                                                                                           
        github.com/restic/restic/internal/restic/find.go:31                                                                                                      
github.com/restic/restic/internal/restic.FindUsedBlobs                                                                                                           
        github.com/restic/restic/internal/restic/find.go:31                                                                                                      
github.com/restic/restic/internal/restic.FindUsedBlobs                                                                                                           
        github.com/restic/restic/internal/restic/find.go:31                                                                                                      
github.com/restic/restic/internal/restic.FindUsedBlobs                                                                                                           
        github.com/restic/restic/internal/restic/find.go:31                                                                                                      
github.com/restic/restic/internal/restic.FindUsedBlobs                                                                                                           
        github.com/restic/restic/internal/restic/find.go:31                                                                                                      
github.com/restic/restic/internal/restic.FindUsedBlobs                                                                                                           
        github.com/restic/restic/internal/restic/find.go:31                                                                                                      
main.pruneRepository                                                                                                                                             
        github.com/restic/restic/cmd/restic/cmd_prune.go:191                                                                                                     
main.runPrune                                                                                                                                                    
        github.com/restic/restic/cmd/restic/cmd_prune.go:85                                                                                                      
main.glob..func18                                                                                                                                                
        github.com/restic/restic/cmd/restic/cmd_prune.go:25                                                                                                      
github.com/spf13/cobra.(*Command).execute                                                                                                                        
        github.com/spf13/cobra/command.go:762                                                                                                                    
github.com/spf13/cobra.(*Command).ExecuteC                                                                                                                       
        github.com/spf13/cobra/command.go:850                                                                                                                    
github.com/spf13/cobra.(*Command).Execute                                                                                                                        
        github.com/spf13/cobra/command.go:800                                                                                                                    
main.main                                                                                                                                                        
        github.com/restic/restic/cmd/restic/main.go:86                                                                                                           
runtime.main                                                                                                                                                     
        /usr/lib/go-1.13/src/runtime/proc.go:203                                                                                                                 
runtime.goexit                                                                                                                                                   
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:1357

Steps to reproduce the behavior
-------------------------------
I don't know

Do you have any idea what may have caused this?
-----------------------------------------------
I don't know

Do you have an idea how to solve the issue?
-------------------------------------------
Sorry, no!

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Until some weeks ago, all worked really fine. But I hadn't a look on the daily backup, because it worked perfectly.

**Comment by rawtaz** [comment]
Hey @puzich, can you locate the file named 7a624f7903cc49b396e5c1745098f69e30290f2dc121b6770dc8d8ccbfef9687 and run sha256sum (or equivalent) on it, and see what the hash of the file contents is?

**Comment by puzich** [comment]
Sorry, but I figured out the failed backup, deleted it and the backup runs now again.  I can't do the sha256sum anymore 😩

**Comment by rawtaz** [comment]
Okay, I'm sorry we didn't look into it before you recreated the repo (but I understand that doing so was the simple way forward). Please let us know if you run into problems again. I think the forum would be a good place to report things like this. Thanks!
