### ISSUE TITLE
Return different exit codes for different errors

### ISSUE THREAD

**Issue by seqizz** [restic/restic#2559]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Currently, restic only exits with either 0 or 1 as exit codes. This is not so desirable for automating stuff (e.g. I need to check the stdout/stderr in order to understand the reason of the failure in wrapper code which runs restic).
Can we have a different error code for different failure types? Afaik non-zero exit codes mean failure anyway and we can use any non-generic exit code to ease scripting.

What are you trying to do?
--------------------------
I'm trying to automate restic operation via crons. Since multiple hosts are backing up to same repository, maintenance operations which needs exclusive lock is making restic fail as expected. If I can catch what was the issue, I can react on those specific case: E.g. authentication failed == do not retry, repository is locked == retry in x minutes etc.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I can't express how useful this tool is :+1:

**Comment by ibib** [comment]
Seems like a duplicate of this. https://github.com/restic/restic/issues/956

**Comment by seqizz** [comment]
Aaah yes sorry. My search skills failed me again. I'll comment there, thanks.
