### ISSUE TITLE
Wrong Permissions when restoring backup

### ISSUE THREAD

**Issue by floriplum** [restic/restic#2563]
Output of `restic version`
restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
I executed the following command as a root user.
time restic --password-file=restic_password.txt -r sftp:desktop_sftp@southbridge:/desktop_sftp/.restic restore latest --target=/home/florian/Daten/ --include="/home/florian/Daten"

What backend/server/service did you use to store the repository?
A SFTP Server using the OPENSSH included SSH Server with a ZFS Pool as backend.

Expected behavior
Restore the Data with the same permissions that they had before.

Actual behavior
Restoring the Backup but with root as owner and group.

Steps to reproduce the behavior
Backup Data as root user from another user and Restore it as a root user.

Do you have any idea what may have caused this?
Since the Permissions are correct in the Backup when i mount the Backup i guess there is something wrong with the restore.

Do you have an idea how to solve the issue?
No

Did restic help you today? Did it make you happy in any way?
It made my backup way easier.

**Comment by dimejo** [comment]
Was the restore successfully completed (see #2447)? Did you restore to the original system where the backup was made?

**Comment by floriplum** [comment]
The restore was made on the same PC where i made the backup.
And it looks like the restore was done without problems.

**Comment by dimejo** [comment]
Sorry, but I've no idea what's going on. Restoring permissions works fine for me.

**Comment by yourfate** [comment]
Was the PC set up with a fresh operating system? If so the user ID would be different.

**Comment by lgg42** [comment]
I also faced this, not file permission but not the original user/group

**Comment by titou10titou10** [comment]
Same for us with velero+restic on OpenSHift 4.3.13. 
The PVC backuped/restored are held on NFS and the backup in azure blob
For all files/folders, original versions where gitea/root, restored permissions where 1000120000/1000120000

**Comment by floriplum** [comment]
Sorry dor the late answer, i restored the backup from the system that i took 1 day ago(back then) from a HDD that had signs of failure. 

I then restored it after the new HDD arrived.

**Comment by titou10titou10** [comment]
In my case it was du to the way the nfs client provisionner was mouting the nfs sshare and the root_squash attribute that was forcing the uid/gid to 1000120000/1000120000. Using no_root_squash solved the problem and the file permissions are correct now on restore

**Comment by kazigk** [comment]
Same issue on CentOS 8 and XFS filesystem

**Comment by MichaelEischer** [comment]
@kazigk Can you check whether the permissions listed with `restic ls --long latest` are correct? If that's not the case then the problem probably already exists during the backup. Which then poses the question how exactly you run restic and which version?

@floriplum Do all files have the wrong permissions or just the folders not explicitly covered by the include path? If the latter is the case, then that's fixed in #2906 which is currently available via a beta release (https://beta.restic.net/?sort=time&order=desc).

**Comment by ganwell** [comment]
@MichaelEischer 

Neither `restic restore` nor `restic mount` set the right owners, but `restic ls -l` shows the right owners. chmod is correct in restore/mount.

I updated to latest beta, now the owner is restored correctly. So at least for me it was #2906.

**Comment by MichaelEischer** [comment]
@ganwell #2906 is already included in restic 0.11.0. How did you run `restic mount`? restic already passes on the permissions and owner to fuse.

**Comment by ganwell** [comment]
> @ganwell #2906 is already included in restic 0.11.0. How did you run `restic mount`? restic already passes on the permissions and owner to fuse.

Summary: Mount seems to report all folders belonging to root.

That is confusing. I think because I didn't differ between files and folders, what I reported was incorrect. This data is from the beta-version of restic and a completely new repo.
 
* The version I had before:

```
$> pamac info restic | grep Version
Version              : 0.11.0-1
```

* The version I downloaded:

```
restic_v0.11.0-139-gcac48163_linux_amd64
```

* My mount command

```
sudo restic -r /local-repo/ mount -H host --tag home /mnt/host
```

* In mount all folders belong to root:

```
-rw-r--r-- 1 ganwell ganwell  11M 21. Nov 12:33 cv.odt
-rw-r--r-- 1 ganwell ganwell 111K 21. Nov 13:45 cv.pdf
drwxr-xr-x 2 root    root       0 19. Nov 13:16 Letters
drwxr-xr-x 2 root    root       0 19. Nov 16:04 Date
```

* My restore command

```
sudo restic -r /local-repo/ restore -H host --tag home latest --include /somepath -t /tmp/out
```

* Restore is now correct:

```
-rw-r--r--  1 ganwell ganwell  11M 21. Nov 12:33 cv.odt
-rw-r--r--  1 ganwell ganwell 111K 21. Nov 13:45 cv.pdf
drwxr-xr-x  8 ganwell ganwell  300 19. Nov 13:16 Letters
drwxr-xr-x 15 ganwell ganwell  680 19. Nov 16:04 Data
```

I am pretty sure I restored that folder with the distro-version of restic and the old repo and everything belonged to root. I will only go back and compare, if you think it gives useful information.

`-H host` is currently not needed I have only one host, but I scripted everything so I can migrate my other hosts to restic: so a host/tag tuple would reference a single "backup".

**Comment by ganwell** [comment]
@MichaelEischer [this part](https://git.io/Jko5Q) of my backup script might be relevant.

**Comment by ganwell** [comment]
The part that I reported is fixed in latest beta. @MichaelEischer thanks!

**Comment by CoolCold** [comment]
I second that:
```
[root@server~]# restic ls --long latest
repository fd0b3794 opened successfully, password is correct
snapshot e16e695f of [/var/opt/gitlab/backups] filtered by [] at 2020-12-17 12:30:01.602065352 -0500 EST):
drwxr-xr-x     0     0      0 2020-03-21 04:04:09 /var
drwxr-xr-x     0     0      0 2020-04-18 16:32:07 /var/opt
drwxr-xr-x     0     0      0 2020-11-08 16:57:51 /var/opt/gitlab
drwx------   988     0      0 2020-12-17 01:06:28 /var/opt/gitlab/backups
-rw-------   988   984 7135406080 2020-12-17 01:03:21 /var/opt/gitlab/backups/1608184989_2020_12_17_12.8.7_gitlab_backup.tar
```
while restored file is owned by `root`.

version: `restic 0.11.0 compiled with go1.15.3 on linux/amd64`
OS: Centos 7
storage: Gdrive via rclone

**Comment by ganwell** [comment]
> while restored file is owned by `root` (user who runs `restic restore`)

There is currently no new release, but you can use a beta: https://beta.restic.net/?sort=time&order=desc . Or if you don't currently need to restore something, just wait for the next release.
