### ISSUE TITLE
Migrate restic repository from one URL to another

### ISSUE THREAD

**Issue by shibumi** [restic/restic#2572]
Hi,
It would be cool if it would be possible to migrate a repository from one backup repository to another.

Let's imagine the following config:

```
export RESTIC_REPOSITORY=s3:s3.wasabisys.com/<my repository>
```

I would like to migrate the whole repository to:
```
export RESTIC_REPOSITORY=s3:s3.newdomain.tld/<my repository>
```

Is this do-able right now? If not, what is the easiest way to do this?

Problem: I don't have enough space to checkout the whole repository (and I don't even know if this is possible).

**Comment by bjoe2k4** [comment]
Easily doable, but not with `restic`. Use `rclone` instead.

**Comment by rawtaz** [comment]
@shibumi You say you don't have enough space to "check out" the whole repository.

If by that you mean to "restore" the entire repository from the old S3, and then back the restored files up to the new S3, then yeah, no point in trying that.

If you mean that the new S3 doesn't have enough space to accomodate the entire old S3 repository, there's no simple way to deal with that (besides of course just making a new repository and start backing up to it, losing your history from the old one).

However, @middelink wrote some code to copy specific snapshots from one repo to another. Please see [her comment](https://github.com/restic/restic/issues/323#issuecomment-457218490) and [this other comment](https://github.com/restic/restic/issues/323#issuecomment-579834678) to see if it might be useful to you.

**Comment by seqizz** [comment]
If you're dealing with s3 endpoints, check out [mc](https://github.com/minio/mc) from Minio. It has a mirror command you might find useful. Otherwise, you can loop copying snapshots with the branch @rawtaz commented above.

**Comment by shibumi** [comment]
I am overwhelmed by this much feedback. Thanks guys. I will have a look on `rclone` and `mc`.
@rawtaz yes, I meant local storage. The s3 storage is no problem. I thought about switching from wasabi.com to backblaze (I hate the wasabi.com UI.. it's awful. Although they have better pricing than blackbaze mhh)

**Comment by rawtaz** [comment]
I'm closing this as it's a usage question rather than a bug or feature request as it stands now. Please continue the discussion in the [forum](https://forum.restic.net) if need be :)
