### ISSUE TITLE
Extend the consistency and integrity check to the pack files

### ISSUE THREAD

**Issue by bchapuis** [restic/restic#258]
The command ```restic check``` verifies the integrity of some internal files. When pack files are modified the command fail at detecting the modification.

It is possible to reproduce this issue by following the following procedure:

```
$ restic -r /tmp/backup init
$ restic -r /tmp/backup backup ~/dir
$ sudo chmod -R 777 /tmp/backup
$ echo “boom” >> /tmp/backup/data/aa/aaaaa…
```

In this case, the shasum of the pack file does not correspond to the filename anymore but the integrity check is not producing errors and it is still possible to restore the snapshot

```
$ restic -r /tmp/backup check
$ restic -r /tmp/backup restore id —target /tmp/restore-backup
```

**Comment by bchapuis** [comment]
#247 seems to be related.

**Comment by fd0** [comment]
This is resolved, modified pack files are detected:
```
$ echo boom >> /tmp/repo/data/42/4213bd7d4ea844f9a4b5114f84532cfc30e8fba48df4067634bb816d01d89b19
```

Check detects it:
```
$ restic check --read-data
Create exclusive lock for repository
Load indexes
Check all packs
Check snapshots, trees and blobs
Read all data
Pack ID does not match, want 4213bd7d, got 56ebcc38
[0:00] 100.00%  19 / 19 items
duration: 0:00
repository contains errors
[1]    3033 exit 1     restic check --read-data
```
