### ISSUE TITLE
Lock.Stale doesn't operate as advertised

### ISSUE THREAD

**Issue by klauspost** [restic/restic#260]
In the [Lock.Stale](https://github.com/restic/restic/blob/master/lock.go#L199) function the documentation says:

>A lock is stale if [...] it was created on the current machine and the process isn't alive any more.

However, I see no tests in the code to check if it was created on the current machine. Instead it seems like it will always return as stale if it was created on another machine.

This should probably be added:
```Go
	// check if lock was created on this host
	hn, err := os.Hostname()
	if err != nil {
		debug.Log("Lock.Stale", "could not retrieve current host name: %v\n", err)
	}

	if l.Hostname != hn {
		debug.Log("Lock.Stale", "lock created on different host, probably not stale\n")
	}
```

**Comment by fd0** [comment]
This is indeed a bug, good catch!

**Comment by klauspost** [comment]
It probably also deserves a test or two.

**Comment by fd0** [comment]
Have a look at the code in #261, is that enough?

**Comment by klauspost** [comment]
LGTM!

**Comment by fd0** [comment]
OK, cool.
