### ISSUE TITLE
sftp fails with `Could not resolve hostname sftp`

### ISSUE THREAD

**Issue by ifedorenko** [restic/restic#2627]
sftp backend support appears to be broken on current master, at least on on macOS 10.14.6 and likely on Ubuntu 18.04.4 LTS too.

Output of `restic version`
--------------------------
    restic 0.9.6-dev (compiled manually) compiled with go1.14 on darwin/amd64

How did you run restic exactly?
-------------------------------

    mbp:restic igor$ ./restic -r 'sftp:igor@192.168.2.145:/data/var/tmp/restic-test-repo' restore --target=/tmp/restic-restore-output latest
    subprocess ssh: ssh: Could not resolve hostname sftp: nodename nor servname provided, or not known
    Fatal: unable to open repo at sftp:igor@192.168.2.145:/data/var/tmp/restic-test-repo: unable to start the sftp session, error: EOF

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

sftp

Expected behavior
-----------------

Expected restic to connect to remote repository and restore the backup from there.

Actual behavior
---------------

Restic fails to start sftp session

Steps to reproduce the behavior
-------------------------------

Run restic restore using sftp backend

Do you have any idea what may have caused this?
-----------------------------------------------

Almost certainly caused by e1969d1e3360fd268184b810b5f08ad327725c66, reverting that commit makes the problem go away.  I also don't see any ssh version that supports `-- host` syntax on [Ubuntu](http://manpages.ubuntu.com/manpages/bionic/man1/ssh.1.html).  @greatroar fyi.

**Comment by rsanden** [comment]
Confirming this on Ubuntu 18.04. Putting the host last makes sense, but I don't see anything about `--` in `man ssh`. It might be a very recent addition.

**Comment by greatroar** [comment]
Please pull #2633 (or revert some other way).
