### ISSUE TITLE
Add rate limit to progress updates.

### ISSUE THREAD

**Issue by rubenv** [restic/restic#263]
Might want to rate-limit the progress updates (more than once every 16.6 ms would be > 60fps and thus pointless): https://youtu.be/AuYHXvgwKE8

**Comment by rubenv** [comment]
This hunger for redraws causes this:

![screen shot 2015-08-17 at 14 20 04](https://cloud.githubusercontent.com/assets/42904/9304698/233e4d12-44eb-11e5-838b-a9d6e5b7faf7.png)

Which in turn means that restic becomes ridiculously slow, because CPU cycles are wasted elsewhere :-)

**Comment by fd0** [comment]
Indeed, that's a good idea.

**Comment by rubenv** [comment]
Mind you, this is mostly a problem because the terminal in OSX is somewhat crappy

But anything faster than what we can see isn't really needed either

**Comment by fd0** [comment]
I agree, but since the OSX terminal is widely in use, I consider this a bug. Adding a rate limit isn't that hard to do.

**Comment by fd0** [comment]
This has been fixed in #266.
