### ISSUE TITLE
restic list snapshot

### ISSUE THREAD

**Issue by nzncngz** [restic/restic#2634]
Hi all I am using Velero for backups on K8s.
Velero install on below using restic.
velero install --provider aws --bucket kubedemo --secret-file ./minio.credentials --backup-location-config region=minio,s3ForcePathStyle=true,s3Url=http://10.154.2.189:9000 --plugins velero/velero-plugin-for-aws:v1.0.0 --use-restic --wait

I  want  backup files.I dont know how it.

(https://user-images.githubusercontent.com/22845579/76169716-15f64c00-618c-11ea-88ee-9167e09831f4.png)

(https://user-images.githubusercontent.com/22845579/76169723-2ad2df80-618c-11ea-96dc-cb3357779d70.png)

[root@minio3 wordpress2]# restic init
Fatal: Please specify repository location (-r)
[root@minio3 wordpress2]#

Could you please help me?

**Comment by MichaelEischer** [comment]
Please use the forum at https://forum.restic.net/ for questions on how to use restic.

**Comment by rawtaz** [comment]
@nzncngz When you open a new issue you are presented with three options:

- Bug report (Report a problem with restic to help us resolve it and improve)
- Feature request (Suggest a new feature or enhancement for restic)
- restic forum (Please ask questions about using restic here, do not open an issue for questions)

What part of this is unclear to the extent that you still choose open an issue (even though it says in the third item above that for usage questions you should use the forum)?

If there's a problem with that information, we need to improve it.

**Comment by rawtaz** [comment]
Please open a thread in the forum instead, that will get more eyes on the problem you're having.
