### ISSUE TITLE
Make restic more faster for rebuild-index

### ISSUE THREAD

**Issue by ediazrod** [restic/restic#2639]
100 hour for rebuild the index of 5Tb

I don't know but rebuild a index  is too much. there is any way to go faster? parallel downloads?

[1:02:56] 2.42%  26301 / 1087537 packs

I have a 500Mb symmetric Fiber Line.

In my opinion on a dissarter rebuild the index is critical, and two days restore a backup...

**Comment by MichaelEischer** [comment]
Please fill out the bug report template unless you have a _very good_ reason to ignore it.

The performance of `rebuild-index` highly depends on the used backend, e.g. for a local repository accessed via rclone it took me approx. one hour to rebuild the index for a 8 TB repository.

**Comment by ediazrod** [comment]
Sorry is true:

restic 0.9.6 compiled with go1.13.4 on linux/amd64

try tor recreate the cache index.

the backend is B2

https://www.backblaze.com/b2

**Comment by rawtaz** [comment]
From what I've read, it's quite common to see people report slowness with Backblaze backends. I don't understand why people keep using that stuff..

**Comment by ediazrod** [comment]
Is cheap.. very cheap.

I use this comand line to upload the number of conexion.

 -o b2.connections=20

With this default parameter:
root@servidorjuanbravo23:~#  ls -l /proc/$(pgrep restic)/fd | grep socket: | wc -l
5

With the new conexions =20
root@servidorjuanbravo23:~#  ls -l /proc/$(pgrep restic)/fd | grep socket: | wc -l
10


There is a diference (and I see on the speed, at least double).

**Comment by MichaelEischer** [comment]
The default limit for b2 connections is 5. `rebuild-index` is currently limited to 10 workers, thus increasing the number of connections beyond 10 does not help. You would need to modify `const listPackWorkers = 10` in `internal/index/index.go`.

It would probably be useful if `index.New` would max out the number of allowed simultaneous backend connections.

**Comment by MichaelEischer** [comment]
Closing this in favor of #1467 .
