### ISSUE TITLE
installation and defaults: zsh-completion

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#2646]
restic version: `restic 0.9.5 compiled with go1.13beta1 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
-------------------------------------------------------------------------------------------------------------

Restic can be installed in many ways, if possible, automatically run: 
`# restic generate --zsh-completion /usr/share/zsh/vendor-completions/_restic` 
when installing (updating) restic.

When running `restic generate --zsh-completion` without a specified file, also default to `/usr/share/zsh/vendor-completions/_restic`.

What are you trying to do?
--------------------------
Have the completions automagically be there, without thinking about it.

**Comment by greatroar** [comment]
/usr, except /usr/local, is off-limits to anyone but the OS package manager: "local software must not be placed outside of /usr/local without good reason" ([FHS](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html)).

**Comment by jivanpal** [comment]
Suggestion to do this automatically, but in `/usr/local/share/zsh/site-functions` instead, which is usually in `$fpath` by default. For example, on Ubuntu and macOS installations of ZSH, it is the first element of `$fpath` by default.

**Comment by fd0** [comment]
I don't think we should have a default for the path, it may vary widely between distributions. Adding documentation on how to do that (see #3689) should be enough.
