### ISSUE TITLE
unknown blob

### ISSUE THREAD

**Issue by yadu-boss** [restic/restic#2653]
Hi team,

I got this error while i try to get restore from snapshots 

could you please resolve 

Unknown blob f68ac127ff4eca90940d7581af44eca64856443853e5ca1c07ea7e33a011f68b
github.com/restic/restic/internal/restorer.(*filePackTraverser).forEachFilePack.func1
        /restic/internal/restorer/filepacktraverser.go:21
github.com/restic/restic/internal/restorer.(*filePackTraverser).forEachFilePack
        /restic/internal/restorer/filepacktraverser.go:32
github.com/restic/restic/internal/restorer.newPackQueue
        /restic/internal/restorer/packqueue.go:52
github.com/restic/restic/internal/restorer.(*fileRestorer).restoreFiles
        /restic/internal/restorer/filerestorer.go:118
github.com/restic/restic/internal/restorer.(*Restorer).RestoreTo
        /restic/internal/restorer/restorer.go:252
main.runRestore
        /restic/cmd/restic/cmd_restore.go:183
main.glob..func20
        /restic/cmd/restic/cmd_restore.go:26
github.com/spf13/cobra.(*Command).execute
        /restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /restic/vendor/github.com/spf13/cobra/command.go:800
main.main
        /restic/cmd/restic/main.go:86
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by rawtaz** [comment]
@yadu-boss Please fill out the complete issue template so we get the information we asked for when you opened the issue. If you can't do that, please post in |the forum](https://forum.restic.net/) instead and close this issue (it can be re-opened if need be).

**Comment by rawtaz** [comment]
@yadu-boss There's not enough information in what you wrote, so at this point we cannot help you. Please either provide the information that is requested when you open a new bug report issue, or use the forum. For now, I'll close this issue, feel free to reopen it when you're ready to provide the information.
