### ISSUE TITLE
Add a flag to skip TLS verification for self-signed certificates

### ISSUE THREAD

**Issue by mansam** [restic/restic#2656]
Output of `restic version`
--------------------------

restic 0.9.6

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

It would be helpful if Restic had a flag to skip TLS verification for self-signed certificates, as an alternative to passing a certificate bundle via `--cacert`.

What are you trying to do?
--------------------------

Velero supports a `--insecure-skip-tls-verify` flag that allows turning off TLS verification for self-signed certificates when talking to storage backends which is handy for development purposes. However, that doesn't work with Velero's Restic integration for backing up Kubernetes volumes, since Restic doesn't support an equivalent flag.

I'll put up a PR with a possible implementation shortly.

**Comment by MichaelEischer** [comment]
What's preventing you from using `--cacert`? I understand that Velero right now misses the option to specify a custom cacert for a backup storage location, but that should be fixed once https://github.com/vmware-tanzu/velero/issues/2332 is resolved.

**Comment by mansam** [comment]
Nothing specifically is preventing the use of `--cacert` other than the present lack of support for it in Velero, which as you noted is being worked on. This issue is really about allowing Velero's already existing `--insecure-skip-tls-verify` flag to work with Restic. Velero supports turning off TLS verification for self signed certs, but since Restic doesn't have a corresponding switch there's no way to propagate that setting, and the Restic volume backup will fail even though it will look like the rest of the Velero backup succeeded. And of course even once `--cacert` is implemented in Velero this workflow would still be broken. This issue and attached PR would solve that discrepancy, just as https://github.com/vmware-tanzu/velero/pull/2353 will solve the lack of a corresponding `--cacert` flag in Velero. :)

**Comment by sokoow** [comment]
any update here ?

**Comment by rmoriz** [comment]
Use case where `--cacert` isn't working: 

QNAP NAS offer a s3 compliant app called QuObjects. Basically the s3/swift endpoint is running on port 8010 with a self-signed certificate for CN "QNAP NAS" (!) which is almost always not working. Even if one uses the certificate with `--cacert` hostname won't match.

e.g. when accessing via IP

```
Fatal: create repository at swift:https://10.5.5.5:8010/user/restic failed: conn.Authenticate: Get "https://10.5.5.5:8010/auth/v1.0": x509: cannot validate certificate for 10.5.5.5 because it doesn't contain any IP SANs
```

**Comment by jsainzvela** [comment]
> Using `--insecure-tls` might work. But the proper fix is to ask QNAP to fix the certificate created by their service.

Thanks @MichaelEischer , tried that but `--insecure-tls` does not seem to be valid (at least in my installation):

```
jsainz@munich:~  $ restic -r swift:objects:/munich init --insecure-tls
unknown flag: --insecure-tls
```

I am using version 0.12.1 (under Fedora):

```
jsainz@munich:~  $ restic version
restic 0.12.1 compiled with go1.16.13 on linux/amd64
```

Thanks!

**Comment by fd0** [comment]
> Thanks @MichaelEischer , tried that but --insecure-tls does not seem to be valid (at least in my installation):

The flag was [added in 0.13.0](https://github.com/restic/restic/blob/master/CHANGELOG.md#changelog-for-restic-0130-2022-03-26).
