### ISSUE TITLE
Not so clear at first how to get the B2 Application Key

### ISSUE THREAD

**Issue by manuel-plavsic** [restic/restic#2672]
I set up restic + B2, but It took me more than 30 minutes to realize that one cannot simply fetch the Application Key from the App Keys section on backblaze.com. I figured it out **only after I logged out** and I visited https://www.backblaze.com/b2/docs/application_keys.html (which is not directly accessible if someone is already logged in).

In this page https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#backblaze-b2 I recommend to add the following information regarding B2 Application Keys: to get the Application Key ID, a user can go to the App Keys section; but for the Application Key a new user has to request a new application key (master for example). Then he will be given a new Application Key ID, and also a new **Application Key**, which the user will have to note since **it will appear only once**.

It took me a while to realize it, and I think it could be helpful to a lot of people.

**Comment by rawtaz** [comment]
I would like to see a documentation change that both references https://www.backblaze.com/b2/docs/application_keys.html and in short mentions the important parts @manuel-plavsic mentioned above.

We should try to keep the documentation as neutral as possible and not too specific such that it can become outdated.

In other words, it should be pointers/directions to the important info that's needed by the user to set things up, rather than a complete description on where to go/click in the B2 GUI, because that might change without us noticing it.

Thanks for pointing this out @manuel-plavsic!

**Comment by fermulator** [comment]
@metalsp0rk, I inspected those documentation changes and at a high level they look good.  Are you going to create a pull request?

I couldn't comment on your branch/commits directly, so just wanted to provide some ideas/feedback
* the bits on app keys definitely addresses the main spirit of this issue - LGTM :heavy_check_mark: 
* the little note on the "backup error handling" seems fine too
* in the "strong password", might want to also reference: https://www.random.org/passwords/?num=12&len=24&format=html&rnd=new, as a "easy way to get a random string" and have the user replace/add a few non-alphanumeric characters (!@&etc)

**Comment by Carioca** [comment]
Should we add images to the tutorial?

**Comment by rawtaz** [comment]
Images require a whole other level of maintenance than text. As far as practically possible, let's use text and work with annotations.

**Comment by gum3ng** [comment]
Hi can I submit a PR for this?

**Comment by metalsp0rk** [comment]
If you've got something already, go for it.  I can't believe I forgot to open this PR.  

If you'd prefer I open that PR, I've still got the branch; `documentation-enhance` on my fork.  I can rebase and fix any conflicts than open a PR.

**Comment by metalsp0rk** [comment]
Rebased; I can open this as a PR, or if you've got something better, I'm happy to hand this off.

https://github.com/metalsp0rk/restic/tree/documentation-enhance

**Comment by gum3ng** [comment]
No issues you can go ahead with the PR
