### ISSUE TITLE
Ability to customize Google Storage base URL

### ISSUE THREAD

**Issue by cretz** [restic/restic#2676]
Output of `restic version`
--------------------------

    restic 0.9.6 compiled with go1.13.6 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I need to change the base URL from `https://storage.googleapis.com/storage/v1/` to my own value (not to be confused with `HTTPS_PROXY` or any other "proxy" settings).

What are you trying to do?
--------------------------

Change the base URL from `https://storage.googleapis.com/storage/v1/` to my own value. I plan on making a minimal patch that I'll submit as a PR to do this soon. Simply put, I am going to accept a `-o gs.baseurl=http://whatever:1234/whatever` option that I'll put on the backend config and set the `BasePath` exported field on the service when present.

**Comment by MichaelEischer** [comment]
Closing this issue as judging from the PR there's no more interest in this feature. Feel free to reopen the issue if you're still interested in this feature.
