### ISSUE TITLE
High fragmentation and very slow backups

### ISSUE THREAD

**Issue by JsBergbau** [restic/restic#2679]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on windows/amd64

How did you run restic exactly?
-------------------------------
restic -r D:\restic backup C:\ G:\ --exclude-file
No enviroment variables

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
External USB 3.0 HDD drive

Expected behavior
-----------------
High throughput during backup, almost no fragmentation on the drive.
 

Actual behavior
---------------
When I get 30 MB/s write speed on the drive I'm very happy. Mostly it is < 10 MB/s while the utilisation is always > 90 % mostly stuck at 100 %.
I've found this issue with restoring https://github.com/restic/restic/issues/2675 
I think while backup up it is the same.
Restic syncs so heavily or uses so heavily IO that my whole USB3.0 subsystem crashes after a while. The external Seagate 4 TB USB 3.0 2.5" HDD drive disappears, comes back and so on. Disconnecting and reconnecting doesn't help. I have to reboot the whole PC. I've tried a lot backup applications with this disk so far. That never happend. To get the disk work I have to reboot. Could be a general hardwareproblem as well, but just to mention in this issue.

Take a look at windows taskmanager. > 18 seconds response time of the drive. A lot of time 0 write speed
![grafik](https://user-images.githubusercontent.com/37013344/78332436-8ae45800-7577-11ea-8552-ba22c748966e.png)

After this backup failed I ran defrag command. It showed 64 % (!) fragmentation.

This behaviour also puts high load on the drive, wearing it faster.

Don't know how exactly restic creates files, but small files (I think < 4 KB) are created on NTFS within the MFT Table. When the size gets bigger it has to be transfered out of the MFT-Table to the disk area. This puts additional load on the drive. With ressource monitor I also see a lot of traffic to MFT-Table. Could be because of creating new files or because my assumption is correct.

```
defrag /A D:
Microsoft-Laufwerksoptimierung
Copyright (c) Microsoft Corp.

"Analyse" wird für "Volume (D:)" aufgerufen...


Der Vorgang wurde abgeschlossen.

Post Defragmentation Report:

        Volumeinformationen:
                Volumegröße                 = 3,63 TB
                Freier Speicherplatz        = 3,38 TB
                Fragmentierter Speicherplatz insgesamt      = 64%
                Größter freier Speicherplatz     = 3,38 TB

        Hinweis: Dateifragmente, die größer als 64 MB sind, sind nicht in den Fragmentierungsstatistiken enthalten.

        Es wird empfohlen, dieses Volume zu defragmentieren.

```

Steps to reproduce the behavior
-------------------------------
Use a USB HDD and make a large backup with data size of about 3 TB.

Do you have any idea what may have caused this?
-----------------------------------------------
The way restic creates the backup files.

Do you have an idea how to solve the issue?
-------------------------------------------
Since the individual pack files are only 4-8 MB you could hold them in RAM and then write them out at once.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I like the idea and the concept behind restic, but to be honest I took me so far a lot of time to try and figure out what is happening. I know you want to make a great job and thats why I create this bug report to help the community with restic, so that we have a very powerful and fast backup tool. I'm confident that this issue will be solved fast so that restic is my new backuptool.

**Comment by ibib** [comment]
Is your HDD a CMR or a SMR drive?

**Comment by JsBergbau** [comment]
Hi. Thanks for your very fast response.

How can I find out if it is CMR or SMR?
PS: I've updated the first post about MFT-table.

**Comment by ibib** [comment]
Usually you find in in the spec sheet to your hdd.
SMR disks are a little bit cheaper than CMR disks but go to hell if you try to write highly concurrent to them. They are optimized vor sequential writes. 

As restic tries to write with a parallelism of 5 (I think)... You see the result.
For HDD's it might be a good idea to limit the concurrency to a lower amount.

But this is only a guess. Could you try using restic with a non SMR drive to make sure the limitation is not anywhere else?

**Comment by JsBergbau** [comment]
Ok it is really a SMR disk. Didn't know that writing to such disks can be such a big problem. Still there is the problem with the file fragmentation.

Currentyl I'm try with a Seagate Barracuda ST3500413AS 500 GB. After 140 GB backed up I still see write rates of about 60 MB/s. So it really seems that SMR disk causing the problems with parallel writes. So how to to limit write parallelism?

**Comment by MichaelEischer** [comment]
Restic already collects all data that belongs into a pack file in a temporary file (stored in one of the usual temp directories) and then passes the full pack on to the operating system for writing into the backup repository. Actually the data is passed to the OS in smaller blocks (32kB) but restic basically hands over all blocks directly after each other to the OS. Windows should then be able to write a pack file in one go. The performance numbers you get, look somewhat like that's not happening properly. Maybe this has to do with the changed disk removal policy: https://docs.microsoft.com/en-us/windows/client-management/change-default-removal-policy-external-storage-media . However, I couldn't find a proper explanation whether and how this affects file writes by an application.

A backup run can write up to `number of CPUs` packs at the same time. And as disk IO is the major performance bottleneck for you, it's very likely that restic tries to write that many files at once. There's currently no option though that could limit disk I/O parallelism.

After writing restic forces the file to be flushed to disk, which probably doesn't help throughput either on SMR disks. It might also be the cause of the disk fragmentation you're seeing (or maybe just making it worse than it already would be).  Regarding the time spent on the MFT table, the cause is simple: Each file creation / file size change etc. must be recorded in the MFT. That is every newly created file also enforces a modification of the MFT.

**Comment by JsBergbau** [comment]
> Restic already collects all data that belongs into a pack file in a temporary file (stored in one of the usual temp directories) and then passes the full pack on to the operating system for writing into the backup repository.

Since my OS and tempdata are on C: I looked for such a behaviour. I know that from duplicati and its very bad if you have a SSD and then backup a full 5 TB HDD. That means 5 TB written to SSD causing massive wear. I was glad not to detect such a behaviour. With Duplicati I've mounted a RAM disk for that but still thats annoying.

> After writing restic forces the file to be flushed to disk, which probably doesn't help throughput either on SMR disks.

I've even setup in Windows to disregard this forced sync and just report to application that sync has took place. Selected "Turn off windows write-cache buffer flushing on the device" https://www.lacie.com/de/de/support/kb/how-to-improve-performance-of-an-external-drive-in-windows/  I know thats not recommended, just wanted to see if it gets better. I had the impression that in the beginning write speed was higher than without this setting, but this is very subjective since I didn't note down the values.

Back to the fragmentation problem. Still with the fast working 500 GB HDD I have 67 % fragmentation which is really a lot.

```
defrag /A D:
Microsoft-Laufwerksoptimierung
Copyright (c) Microsoft Corp.

"Analyse" wird für "Volume (D:)" aufgerufen...


Der Vorgang wurde abgeschlossen.

Post Defragmentation Report:

        Volumeinformationen:
                Volumegröße                 = 465,75 GB
                Freier Speicherplatz        = 2,91 MB
                Fragmentierter Speicherplatz insgesamt      = 67%
                Größter freier Speicherplatz     = 3,37 MB

        Hinweis: Dateifragmente, die größer als 64 MB sind, sind nicht in den Fragmentierungsstatistiken enthalten.

        Es wird empfohlen, dieses Volume zu defragmentieren.

```

**Comment by MichaelEischer** [comment]
> Since my OS and tempdata are on C: I looked for such a behaviour. I know that from duplicati and its very bad if you have a SSD and then backup a full 5 TB HDD. That means 5 TB written to SSD causing massive wear. I was glad not to detect such a behaviour. With Duplicati I've mounted a RAM disk for that but still thats annoying.

restic definitively creates a `restic-temp-pack-[...]` file for every pack file. It might just be the case that Windows manages to avoid writing that file to disk.

> Back to the fragmentation problem. Still with the fast working 500 GB HDD I have 67 % fragmentation which is really a lot.

Afaik "Turn off windows write-cache buffer flushing" only disables the automatic write-back run by windows. If a program like restic, explicitly flushes a file to disk, then that request should still be honored.

You could try to build restic yourself (you basically just need the go compiler and the restic source code) and modify the following lines:

https://github.com/restic/restic/blob/c03bc88b297f960868d171e098771255f6f11be1/internal/archiver/archiver.go#L113

Assign `1` or `2` to the `SaveBlobConcurrency` variable, to have restic write no more than 1 or 2 packs in parallel.

https://github.com/restic/restic/blob/c03bc88b297f960868d171e098771255f6f11be1/internal/backend/local/local.go#L117-L120

Comment out these four lines to remove the call to `Sync`. Note that this may damage your backup repository if the external harddisk is not properly ejected or when the computer crashes.

**Comment by cd1188** [comment]
I have a extern WD 4TB USB3 CMR drive since more than a year running and windows shows me 0% fragmentation?
The only problem I had is with the check-comand in this issues #1763 but i compiled it with defaultParallelism=2 and have no problem.
Maybe its really a SMR-problem but thats strange if you use a new drive without deleting much on it
