### ISSUE TITLE
doc: Add troubleshooting section

### ISSUE THREAD

**Issue by rawtaz** [restic/restic#2683]
The current documentation at [restic.readthedocs.io](https://restic.readthedocs.io/) does not contain a proper troubleshooting section, where users can find common problems and how to (initially) handle them. This needs to be addressed.

I propose the following:

- Use [the FAQ](https://restic.readthedocs.io/en/latest/faq.html) as the starting point.
- Replace the items in the FAQ that are about specific error messages with a reference to the new troubleshooting section.
- Make sure to cover what's currently in the FAQ in the new troubleshooting section.
- Make sure that the troubleshooting section references the forum as a place to get further help if the troubleshooting section isn't sufficient, and the issue tracker as a place to report what the user believes is a bug.
- Once we have the troubleshooting section in place, in the various commands of restic, update the current references to creating a new issue/bug report, so that they instead point to the troubleshooting section in the documentation.

This issue supersedes issues #1813 and #2361.

**Comment by aawsome** [comment]
Is there any update on this? I have the impression that the pruning bug report issues are increasing recently. I think a troubleshooting howto would help a lot!

**Comment by rawtaz** [comment]
I started this a while back, but the last month has been insane so I haven't done more on it since then. I do however plan to do more restic work in a week or two, so it's definitely one of the things I intend to finish soon. If you want to make any adjustments, feel free to do so!

**Comment by MichaelEischer** [comment]
I wonder whether there's some way to give us an impression of how often backup repositories break. At least for the time being it would probably be useful to still ask for bugreports such that we have a chance to investigate.
