### ISSUE TITLE
Windows: Symlinks are not backuped

### ISSUE THREAD

**Issue by JsBergbau** [restic/restic#2699]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on windows/amd64

How did you run restic exactly?
-------------------------------

```
1. restic -r symlinktest init
2. restic -r symlinktest backup resticsymlinktest
```

This prints
```
repository 17418abd opened successfully, password is correct
created new cache in C:\Users\JsBerbau\AppData\Local\restic

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 343 B

processed 1 files, 31 B in 0:00
snapshot 5f283900 saved
```

The folder resticsymlinktest contained:
File.txt containing

```
Hallo,
I'm the "real" testfile
```

A symlink to that file, created via
`mklink link File.txt`

Tested restore via
`restic -r symlinktest restore -t resticsymlinkrestoretest latest`
Only 1 file was restored, missing the symlink.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Filesystem

Expected behavior
-----------------
The symlink file is included in the backup and restored when restoring.

Actual behavior
---------------
Symlinkfile is not added to backup and thus also not restored.

Steps to reproduce the behavior
-------------------------------
See above

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
Include symlink files into backup and restore them

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is a very great tool and I hope that symlinks are also restored. Then I'm calm that the backup contains all my files and I can recover everything in case of a disaster.

**Comment by MichaelEischer** [comment]
I wonder whether this is in some way related to #1078.

Could you run `restic ls --long latest` to check whether the symlink is actually missing or is just not restored?

**Comment by JsBergbau** [comment]
Hi. Thanks for your fast reaction. Indeed it seems the file is included in the backup but just not restored.

````
restic -r symlinktest ls --long latest
repository 87787b63 opened successfully, password is correct
snapshot c0857f7d of [G:\resticsymlinktest] filtered by [] at 2020-04-22 08:51:11.1914357 +0200 CEST):
drwxrwxrwx     0     0      0 2020-04-21 13:10:00 /resticsymlinktest
-rw-rw-rw-     0     0     31 2020-04-21 13:08:53 /resticsymlinktest/File.txt
Lrw-rw-rw-     0     0      0 2020-04-21 13:10:00 /resticsymlinktest/link -> File.txt
```

**Comment by fgma** [comment]
@JsBergbau Please have a look at my PR. I hope I fixed the issue.
