### ISSUE TITLE
dump works, but restore not

### ISSUE THREAD

**Issue by shibumi** [restic/restic#2712]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.6 on linux/amd64

How did you run restic exactly?
-------------------------------

I tried to restore the following file out of my snapshots: `/etc/caddy/Caddyfile`. The snapshots
are taken via `restic backup --one-file-system /`. I tried restoring the file on two ways:

1. `restic restore latest --target / --path "/etc/caddy/Caddyfile"`
2. `restic dump latest etc/caddy/Caddyfile > /etc/caddy/Caddyfile`

The latter worked, the first not. Can you explain why? Is this a bug? I've also tried different variations on `restic restore`. For example: `restic restore latest --target /tmp --path "etc/caddy/Caddyfile`. I always get the same error:

```
repository 8b027187 opened successfully, password is correct
latest snapshot for criteria not found: no snapshot found Paths:[etc/caddy/Caddyfile] Host:
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

S3 Backend stored on wasabi.com

Expected behavior
-----------------

I expect that `restic restore` works, when `restic dump` works.

Actual behavior
---------------

`restic restore` fails while `restic dump` works.

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Is this a path issue? Does `dump` and `restore` handle paths differently?

Do you have an idea how to solve the issue?
-------------------------------------------

No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Well, I really like restic. I had to access some backups today, because one of my servers crashed. I just downloaded restic + config and everything worked out of the box. This is cool. The bad part is: I couldn't get a full system restore working, so I just did a rebuild of my server and now I try to get the server up again via dumping single files out of my backup and moving them at the right place.

It would be cool if you could add some documentation about full system backups + restore(!) of linux systems.

**Comment by MichaelEischer** [comment]
You've got the wrong flags for restore. `--path` is used to select snapshots based on their backup paths. In order to select which files should be restore, you need the `--include` option.

**Comment by MichaelEischer** [comment]
Closing this issue as this seems to a usage problem, but we got not feedback on the proposed solution.
@shibumi Feel free to comment on this issue if your problem persists.
