### ISSUE TITLE
"Say Thanks" link goes to a 404

### ISSUE THREAD

**Issue by philipmw** [restic/restic#2726]
I want to make a donation to restic. The github README includes a "Say Thanks" link, which goes to https://saythanks.io/to/restic, but that URL returns a 404!

Please update the README to include one or more ways I can financially support this project.

**Comment by rawtaz** [comment]
@philipmw Unfortunately donations won't happen, see #2415. But the link is indeed not working, I'll leave this issue open so we can look into that at some point (not a high priority right now). Thanks!

**Comment by greatroar** [comment]
Duplicate of #2590.

**Comment by rawtaz** [comment]
Nice catch @greatroar.
