### ISSUE TITLE
restic for AIX 7.2

### ISSUE THREAD

**Issue by Mikesch-mp** [restic/restic#2727]
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

i need an agent for aix 7.2 on ppc63 platform, cross compiling leads to an error.

What are you trying to do?
--------------------------

i tried to cross compile for aix/ppc64 and run into errors

```
[root@guacamole restic]# go run build.go --goos aix --goarch ppc64
# bazil.org/fuse
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/error_std.go:27:20: undefined: errNoXattr
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse.go:171:12: undefined: mount
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse.go:238:17: undefined: maxWrite
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse.go:409:32: undefined: maxWrite
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse.go:649:11: undefined: setattrIn
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse.go:801:12: undefined: openFlags
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse.go:819:18: undefined: openFlags
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse.go:1357:26: undefined: attr
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse_kernel.go:404:17: undefined: attr
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse_kernel.go:430:16: undefined: attr
../go/pkg/mod/bazil.org/fuse@v0.0.0-20191225072544-27e78e7d88df/fuse.go:819:18: too many errors
# github.com/restic/restic/internal/restic
internal/restic/node.go:188:12: undefined: lchown
internal/restic/node.go:243:14: node.restoreSymlinkTimestamps undefined (type Node has no field or method restoreSymlinkTimestamps)
internal/restic/node.go:313:9: undefined: mknod
internal/restic/node.go:313:47: node.device undefined (type *Node has no field or method device, but does have Device)
internal/restic/node.go:317:9: undefined: mknod
internal/restic/node.go:317:47: node.device undefined (type *Node has no field or method device, but does have Device)
internal/restic/node.go:586:14: undefined: toStatT
internal/restic/node.go:679:9: undefined: mknod
build failed: exit status 2
exit status 1
```

Please provide a binary for AIX 7.2 or help to get rid of the build errors.

Thanks,
Carsten

**Comment by rawtaz** [comment]
Anyone up for helping to fix this? Not to dismiss AIX, but it's not high on our priority list as there are many other issues and things that the core developers need to focus their time on. Would be great if someone could look into this issue. Thanks!

**Comment by greatroar** [comment]
This might be easy to solve: add a build tag

```
// +build !aix
```

to all the files in internal/fuse, and add aix to the build tags in internal/restic/node_unix.go. No guarantees that restic will work even if it builds, though.

**Comment by rawtaz** [comment]
@Mikesch-mp Can you try what @greatroar suggested? Do you need help figuring out how to do that?

**Comment by greatroar** [comment]
Actually, it's more difficult than this. A new internal/restic/node_aix.go has to be written (maybe copied from node_solaris.go?).

**Comment by Mikesch-mp** [comment]
When ever i can help i will try my best. But iam not good in golang :)

**Comment by greatroar** [comment]
I have a branch with an AIX port in my fork of restic. It compiles, but is otherwise completely untested; it's mostly a copy of Solaris code with some additional hacks. @Mikesch-mp, if you want to try it out, please run

```
git remote add greatroar https:////github.com/greatroar/restic
git fetch greatroar
git checkout greatroar/aix
```

in a local clone of the repo, then build, run all the tests and see if backup/restore works as expected.

If this works, then we need to discuss how to move forward.

**Comment by Mikesch-mp** [comment]
I will test it asap :), thanks for your help

**Comment by Mikesch-mp** [comment]
Looks like iam way to stupid to get it compiled. I treid it under CentOS7 and Ubuntu 20.25 with gcc 9 and golanf 1.14.2

i only get this error
```
fork/exec /tmp/go-build877034127/b001/exe/build: exec format error
```

Can you assist me please?

**Comment by MichaelEischer** [comment]
@Mikesch-mp Please post the exact command you use to build restic.

**Comment by Mikesch-mp** [comment]
Just the one mentioned in the docs, but i set GOOS=aix and GOARCH=ppc64

**Comment by greatroar** [comment]
```bash
cd whereyoukeepsourcecode/restic/cmd/restic
GOOS=aix GOARCH=ppc64 go build
```

That produces an AIX binary in that dir.

**Comment by Mikesch-mp** [comment]
Yippy i got it build, i will now beginn test to run it on AIX, Thanks for your help :)

**Comment by MichaelEischer** [comment]
> Just the one mentioned in the docs, but i set GOOS=aix and GOARCH=ppc64

`build.go` expects the target platform to be passed as `--goos value` and `--goarch value`. Depending on where you look at the documentation, you'll find `go run build.go` or `go build`.

**Comment by Mikesch-mp** [comment]
The binary works great so for on AIX 7.2 on Power8/9. Test with local for backup/restore/repository cleanup worked flawless. Going to test backups to the rest-server now.

I cant thank you all enough for your help ❤️ Will try to get the customer donate to the project.

**Comment by Mikesch-mp** [comment]
Backup/restore with use of rest-server works also great :)

**Comment by Mikesch-mp** [comment]
As expected it doesnt work with AIX 7.1, since its not supperted by Golang.

**Comment by greatroar** [comment]
@Mikesch-mp Have you checked the timestamps on files? Those are the only things that need special handling for AIX.

**Comment by Mikesch-mp** [comment]
Will check that tomorrow

**Comment by Mikesch-mp** [comment]
> 
> 
> @Mikesch-mp Have you checked the timestamps on files? Those are the only thing that needs special handling for AIX.

iam too stupid again, how can i see the timestamps in the backup?

**Comment by greatroar** [comment]
Mount the repo on Linux or Mac, then stat some files in the mountpoint (`stat snapshots/latest/some/file`). `ls -l` also works, but stat gives very precise timestamps by default.

**Comment by Mikesch-mp** [comment]
Finaly found tie to test wqith the timestamps, looks good for me :) First pic is the AIX system, second is a linux system mounting the backup.

![grafik](https://user-images.githubusercontent.com/6574967/86559825-31683c80-bf5d-11ea-89a8-8a307998b8ee.png)

![grafik](https://user-images.githubusercontent.com/6574967/86559787-1e556c80-bf5d-11ea-868d-e1c55986c28c.png)


Thanks again for all the help, hope AIX (7.2) will make it into the official supported os list

**Comment by greatroar** [comment]
@Mikesch-mp Any chance you can get a more precise timestamps on AIX? The rounded mtime on Linux is suspicious.

**Comment by Mikesch-mp** [comment]
i used perl `lstat` on both sides on test file
AIX:
```
File is /root/test,
atime is 1594013706
ctime is 1574779227
mtime 1574779164
```

Mount repository on Linux:

```
File is /mnt/snapshots/latest/root/test,
atime is 1574779164
ctime is 1574779227
mtime 1574779164
```

**Comment by greatroar** [comment]
That's look good. I'll submit a PR.

**Comment by Mikesch-mp** [comment]
Forgot to mention that only AIX 7.2 is supported by GOlang

**Comment by MichaelEischer** [comment]
Closing as #2833 has been merged.
