### ISSUE TITLE
s3/minio -> The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by unclesamwk** [restic/restic#2734]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
-------------------------------
```~ $ restic -r s3:http://192.168.1.193:9000/testnew init
Fatal: create repository at s3:http://192.168.1.193:9000/testnew failed: client.BucketExists: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```
Did you have any idea how to fix it?

greetings
sam

**Comment by rawtaz** [comment]
@unclesamwk Please fill out the complete issue template as requested when opening the issue. Thanks!

**Comment by unclesamwk** [comment]
I doesnt
