### ISSUE TITLE
Change implementation of `restic.Blob`

### ISSUE THREAD

**Issue by aawsome** [restic/restic#2735]
Output of `restic version`
--------------------------

restic 0.9.6 (v0.9.6-45-g9596fb47-dirty) compiled with go1.13.8 on linux/amd64 :wink: 

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

The actual implementation of `Blob` and `BlobHandle` is:
```
type Blob struct {
	Type   BlobType
	Length uint
	ID     ID
	Offset uint
}
type BlobHandle struct {
	ID   ID
	Type BlobType
}
```

Functions sometimes expect to be called with a `Blob` and sometimes with a `BlobHandle`. In PR #2718 I added a function.
```
func (b Blob) Handle() BlobHandle {
	return BlobHandle{ID: b.ID, Type: b.Type}
}
```
This is, however, a non-optimal compromise. I suggest to change `Blob` to:
```
type Blob struct {
	BlobHandle
	Length uint
	Offset uint
}
```

What are you trying to do?
--------------------------

Make developing easier when handling `Blob`s and `BlobHandles`

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

It's fun using it and fun developing for the project!

**Comment by fd0** [comment]
Hm, good idea. There are quite a few "warts" in the restic code base that could be cleaned up. :)
