### ISSUE TITLE
info on empty listings

### ISSUE THREAD

**Issue by alexanderadam** [restic/restic#2737]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Some info on empty listings (i.e. `no snapshot could be found` if `$ restic -r /path/to/my/repo list snapshots` finds nothing).

What are you trying to do?
--------------------------

Get some information about the repository.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, I love it.

**PS:** I also asked [in the forum](https://forum.restic.net/t/listing-snapshots/2728) about it.

**Comment by stefangehn** [comment]
`restic snapshots --quiet --json` responds with `null` which happens to be a null object in JSON notation. In case you are parsing restic output you might want to give the JSON output a try.

**Comment by alexanderadam** [comment]
I'm not parsing anything here. I was typing it manually and was surprised what happened here.

But [Michael already posted the answer regarding this issue](https://forum.restic.net/t/listing-snapshots/2728/10) and it seems that there's `restic snapshots` and `restic list snapshots` each with its own purpose.
