### ISSUE TITLE
restic backup --json --quiet is not quiet at all

### ISSUE THREAD

**Issue by bjoe2k4** [restic/restic#2738]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/arm

How did you run restic exactly?
-------------------------------
`restic backup --json --quiet`
called from a python3 script.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone/local

Expected behavior
-----------------
output only one line with `"message_type":"summary"`

Actual behavior
---------------
MANY lines with `"message_type":"status"`

According to `restic help` these should not be there:
```
-q, --quiet                     do not output comprehensive progress report
```

Steps to reproduce the behavior
-------------------------------

see above

Do you have any idea what may have caused this?
-----------------------------------------------
no

Do you have an idea how to solve the issue?
-------------------------------------------
probably add an `if` somewhere?

Did restic help you today?
------------------------------------------------------------
Every day!

**Comment by stefangehn** [comment]
If I'm not mistaken the point of adding json output to the backup command was to offer these progress updates.

You can however lower the frequency of these updates by setting the environment variable `RESTIC_PROGRESS_FPS` to limit the number of status updates per second. The smallest allowed value seems to be 1 and the biggest one seems to be 60 which also happens to be the default.

**Comment by darkdragon-001** [comment]
Actually, I expected the same behavior as @bjoe2k4. I still want the summary as json, but do not need status messages.

**Comment by tommysitehost** [comment]
I would prefer this behavior. Upgraded to v0.12.0 from v0.9.4 and this was unexpected.

**Comment by wlkns** [comment]
Just started using restic, great piece of software but this was also unexpected (progress output with --json and --quiet)

**Comment by wlkns** [comment]
Just to add to this, I've achieved what I needed (only the summary output) piping the command against `grep -v "percent_done"` which removed any lines containing percent_done.
