### ISSUE TITLE
`restic cat` does not respect `--no-lock` flag

### ISSUE THREAD

**Issue by neoautomata** [restic/restic#2739]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
-------------------------------
`restic --no-lock --json cat lock <LOCK_ID>`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3 (minio)

Expected behavior
-----------------
restic should ignore the exclusive lock in the repo (due to an ongoing check operation) and output the details of the lock.

Actual behavior
---------------
restic fails with an error message:  
`Fatal: unable to create lock in backend: repository is already locked exclusively by PID XXX on YYY by root (UID 0, GID 0)`

Steps to reproduce the behavior
-------------------------------
1. Start an operation that requires an exclusive lock (e.g. check, forget, prune)
1. List the locks:
   `$ restic --no-lock --json list locks`
   `<LOCK_ID>`
1. Attempt to cat a lock:
   `$ restic --no-lock --json cat lock <LOCK_ID>`
   `Fatal: unable to create lock in backend: repository is already locked exclusively by PID XXX on YYY by root (UID 0, GID 0)`

Do you have any idea what may have caused this?
-----------------------------------------------
The code in `restic/cmd/restic/cmd_cat.go` does not check the `opts.NoLock` before acquiring a lock:

```golang
	lock, err := lockRepo(repo)
	defer unlockRepo(lock)
	if err != nil {
		return err
	}
```

Do you have an idea how to solve the issue?
-------------------------------------------
Adding an if around the lock code in `restic/cmd/restic/cmd_cat.go` should solve the issue:

```golang
	if !opts.NoLock {
		lock, err := lockRepo(repo)
		defer unlockRepo(lock)
		if err != nil {
			return err
		}
	}
```

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
In general I'm very happy with restic and especially the speed and space savings it provides!

**Comment by rubiojr** [comment]
I was trying to `restic cat` a read-only repo today and found this. I'd be happy to take a stab at this and open a PR if it's a desired feature/fix.

It'd be interesting to know (for my own learning purposes) if running `restic cat` with `--no-lock` (always a read only operation, right?) is undesired for some reason, assuming the risk of reading a file being changed or removed by other parallel operations is acceptable.

**Comment by MichaelEischer** [comment]
Yep, `cat` is a read-only operation. The worst that can happen should be a disappearing file which will just cause an error message.
