### ISSUE TITLE
Limit CPU usage

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#2744]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
(Somehow) limit CPU usage by a CLI parameter.

What are you trying to do?
--------------------------
Hourly backups, on T460s. Every hour, for 3-5 minutes, restic takes around 30% of (1 or 4 cores?) CPU.
Since I already have many, many things open, I can feel restic running.

This could also be useful on IoT (low performance) devices (though I would argue that IoT should be replaceable, backup is better than no backup).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restored from a thunderbird backup, saved Migadu's admins time, around an hour or so.

**Comment by ibib** [comment]
30% somhow feels like an odd number. Are you sure you don't have another bottleneck like network or harddrive?

Also there are ways on linux to limit ressource usage or impact from the system side for certain processes. Like nice, ionice or cpulimit. Do you know about them?

**Comment by creativeprojects** [comment]
There are few wrappers available acting on the CPU _nice_ or _ionice_ which can limit the disk activity, like [resticprofile](https://github.com/creativeprojects/resticprofile) (yes, I made this one :p)

**Comment by jtagcat** [comment]
I did forget about other ways on linux. I'll be sure to use them. Though it would be nice for an universal way on all platforms to limit usage.
On linux, restic could just call itself with a widely used wrapper (as a dependency).

As far as the environment is, 1gbps and pretty much unlimited on backend rest-server, m.2 sata 1tb with around 100gb free, a few gb max added each time, usually on around 100/20mbps.

**Comment by rawtaz** [comment]
I think there needs to be a limit to how many concerns restic should manage, we can't build every single feature into restic. That said, I'm leaving it open for review when the times comes.

**Comment by adamsmd** [comment]
For those who come after me, I have found using https://github.com/opsengine/cpulimit to be relatively effective for the CPU side of this issue.  Not as convenient as being built-in to restic though.

(Also, it's not perfect.  For some reason, when the program first starts, it takes a while for the limiter to kick in.  But that might just be something strange about my setup. (Not restic's responsibility; just a fair warning.))
