### ISSUE TITLE
Export go "cmd"s as accessible package.

### ISSUE THREAD

**Issue by darkdragon-001** [restic/restic#2752]
For scripting and automation, Python is quite popular. Therefore, I would like to have a python wrapper to call the restic commands directly without the detour of converting parameters to strings and parsing those strings again in order to create native types. This way, compatibility can easily be tested in CI and breaking API changes will be detected automatically.

The most important command is _backup_ which is defined as
https://github.com/restic/restic/blob/84475aa3a8c6816074fa664378891d8ae3d25d8a/cmd/restic/cmd_backup.go#L396
together with the struct definitions. I already created a [go `io.Writer` to python `logging.getLogger()` wrapper](https://github.com/sinnwerkstatt/runrestic/issues/35#issuecomment-633542290) (it's basically a callback which is called whenever new output data is available) which can be used to create a new
https://github.com/restic/restic/blob/84475aa3a8c6816074fa664378891d8ae3d25d8a/internal/ui/termstatus/status.go#L55

Your commands reside in the `main` package though. The called functions are `internal`. Is it possible to export the commands as a _go package_?

Are you interested in implementing the python wrapper directly in restic/restic and building and publishing it as part of your CI or would you prefer to have it as an external module?

**Comment by MichaelEischer** [comment]
There's #2403 which seems pretty similar to this issue. There are currently no plan export an API in the foreseeable future.

**Comment by darkdragon-001** [comment]
@MichaelEischer Thanks! Closing this in favor of #2403.

**Comment by varac** [comment]
For the record, there's also [resticpy](https://mtlynch.github.io/resticpy/), a `Minimal Python wrapper around the restic backup command-line interface.`, although it haven't been updated since 2021-04.
