### ISSUE TITLE
Add number to "restic snapshots --last"

### ISSUE THREAD

**Issue by darkdragon-001** [restic/restic#2753]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.12.12 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Add integer parameter to `--last` in order to show last `n` snapshots.

Alternatively, add `--sort` and `--limit` parameters.

What are you trying to do?
--------------------------
Find out how many files have been removed in the latest snapshot. When more than 10% of the files are removed, submit a ticket. Therefore, I need to get the snapshot ids of the last two snapshots and then run `restic diff` to compare them.

**Comment by MichaelEischer** [comment]
This has been implemented in #3167 which is included in restic 0.12.1
