### ISSUE TITLE
Support Amazon S3 signature version 4?

### ISSUE THREAD

**Issue by ar-jan** [restic/restic#276]
I tried creating a repository in the eu-west-1 region, and got:

    restic -r s3://eu-central-1/my.backup.bucket init
    creating key in backend at s3://eu-central-1/my.backup.bucket failed:
    The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

I guess Frankfurt was an unlucky choice, since it's the one [region](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) that doesn't support the old V2. Still, maybe consider switching to version 4?

P.S. I saw the video of today's restic presentation, very cool. I look forward to trying it out further!

**Comment by fd0** [comment]
Thanks for your report. The s3 backend was implemented by @howeyc. Maybe we can combine solving this with switching to the official AWS s3 Go sdk.

@howeyc could you take a look?

**Comment by howeyc** [comment]
Pull request #285 has been updated and should take care of this issue.

I tested it myself and was able to create/use a bucket on eu-central-1.

**Comment by fd0** [comment]
cool, thanks a lot!

**Comment by ar-jan** [comment]
Wow, that was quick, thanks!
