### ISSUE TITLE
[Documentation] Environment variables

### ISSUE THREAD

**Issue by darkdragon-001** [restic/restic#2763]
There is an overview of environment variables in the [docs](https://restic.readthedocs.io/en/latest/040_backup.html?highlight=environment#environment-variables). It seems to be missing [`$RESTIC_CACHE_DIR`](https://restic.readthedocs.io/en/latest/manual_rest.html#caching).

Furthermore, it would be nice to include usage of additional general environment variables like [`$XDG_CACHE_HOME/restic`](https://restic.readthedocs.io/en/latest/manual_rest.html#caching), [`$TMPDIR`](https://restic.readthedocs.io/en/latest/manual_rest.html#temporary-files), [`$HOME/.cache/restic`](https://restic.readthedocs.io/en/latest/manual_rest.html#caching), `$PATH/fusermount` together with links to the corresponding manual sections. Is there anything missing? If no, please tell me so that I can prepare a PR.

Furthermore, it would be nice to have _(introduced in VERSION)_ for lately introduced variables. For example `$RESTIC_CACHE_DIR` was introduced in #2425 (Unix) and #2607 (Mac, Win). How can I find the version number for a specific commit? Or could someone who knows the version history help me finding this information (for all environment variables)?

**Comment by greatroar** [comment]
After you've fetched the tags (git fetch --tags), use git describe:

```
$ git describe upstream/master
v0.9.6-209-gcba6ad8d
$ git describe 907c201693f661a2e5fa915ab9d68ed54a6d93c5
v0.6.1-67-g907c2016
```

So cba6ad8d is version 0.9.6 + 209 commits and 907c201693f661a2e5fa915ab9d68ed54a6d93c5 is 0.6.1 + 67 commits.

**Comment by darkdragon-001** [comment]
@greatroar Thanks for the new insights on git usage. The command I was looking for is `git tag --contains COMMIT` which will show me the tag which _contains_ a specific commit. This functionality is also built-in into Github on the page for a specific commit. _([StackOverflow](https://stackoverflow.com/q/27886537))_
