### ISSUE TITLE
Using --exclude-if-present may crash restic

### ISSUE THREAD

**Issue by liancea** [restic/restic#2764]
Output of `restic version`
--------------------------
`restic 0.9.6 compiled with go1.12.12 on linux/amd64`
(installed through Ubuntu 20.04 repositories)

How did you run restic exactly?
-------------------------------

```
export B2_ACCOUNT_ID=00xxxxxxxxxxxxxxxxxx
export B2_ACCOUNT_KEY=*****************************
export RESTIC_REPOSITORY="b2:bucketname:/"
export RESTIC_PASSWORD_FILE="/root/restic-backup/repository-password"
/usr/bin/restic backup --verbose --exclude-file=/root/restic-backup/excludes.txt --exclude-caches --exclude-if-present=RESTIC_DO_NOT_BACKUP --limit-download=7000 --limit-upload=3500 /
```
After some time (<=10min), as an example this gives
```
open repository
repository 2f226a3a opened successfully, password is correct
lock repository
load index files
start scan on [/]
start backup on [/]
uploaded intermediate index dc963861
Assertion 'set_remove(iterator->links, link) == link' failed at src/shared/userdb.c:314, function userdb_on_query_reply(). Aborting.
SIGABRT: abort[rest of a path that was written here before]
PC=0x7fd53b54818b m=33 sigcode=18446744073709551610[rest of a path that was written here before]
```
and then a very long list of goroutine stack traces and register contents, I can post them later if desired.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
restic makes a backup and doesn't crash

Actual behavior
---------------
restic crashes after some time

Steps to reproduce the behavior
-------------------------------
Running the command shown above on my data (3995485 files, 4.540 TiB according to restic) reproduces the error. It crashes on the same assertion, but not exactly on the same files (as seen on the last two lines of output during the run). No directory actually contains a `RESTIC_DO_NOT_BACKUP` file, yet. The filenames restic reached on crash looked something like this (may or may not be a coincidence):

- /abcdef/ghijk-lmnopq/rstuvwxyz_abcd/2019_07_12_efghijk-lmnopqrstu
- /abcdef/ghijk-lmnopq/rstuvwxyz_abcd/2019_10_09_efghijk.tar.gz
- /abcdef/ghijk-lmnopq/rstuvwxyz_abcd/efghijk/lmn_opqrstu/vwxyz/abcdefgh-ijk/lmnop/qrstuv-wxyzabcd.sh

Do you have any idea what may have caused this?
-----------------------------------------------
Possibly the option `--exclude-if-present`. If I remove it, the backup chugs along fine.

Do you have an idea how to solve the issue?
-------------------------------------------
No, unfortunately.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Not just today! restic seems really great for my use case, which is backing up files over a slowish link to a somewhat untrusted location. I used a hacky DIY approach before; restic saved me from having to maintain all those backup scripts and gifts deduplication on top. Nice work!

**Comment by greatroar** [comment]
Looks like an OS bug, not a restic bug. The error message about a failed assertion is coming from [systemd](https://github.com/systemd/systemd/blob/eed44b715d18295d9f408fe240c29e3c6a7f5272/src/shared/userdb.c#L314), not restic, and is the same one reported [here](https://bugs.launchpad.net/ubuntu/+source/autofs/+bug/1880193).

**Comment by liancea** [comment]
Interesting, makes me wonder how this bug gets triggered. I'm going to close the issue since it doesn't seem to be restic's fault. Moreover, it's possible to work around this by first preparing another --exclude-file through find/locate. Thanks for your help!
