### ISSUE TITLE
Rest url subpath not working

### ISSUE THREAD

**Issue by quequiere** [restic/restic#2766]
### Hello !

So got a problem with **rest server repo initialization**.

**When I try to initialize a repo with a subpath on a restic-rest-server it doesn't work.**

For example :

- ```
  restic init -r rest:http://mydomain.io/foo
  ```

- ```
  restic init -r rest:http://mydomain.io/bar
  ```

- ```
  restic init -r rest:http://mydomain.io/
  ```

  

These commands have the same effect and **create data in the base root server side**.

------

As you can see on the screenshot this is a client side problem. 
![img](https://user-images.githubusercontent.com/2946661/83356911-764ef100-a369-11ea-811e-5306a831225e.jpg)



The generated post request always requesting :

```
post http://mydomain.io/?create=true
```

**instead of** 

```
post http://mydomain.io/{subpath}?create=true
```

------

I voluntary disable server side to prompt this error. So it is not a server side problem but a client problem.

When I send by myself post request to the server with postman, it's work perfectly.

```
With postman ==> post http://mydomain.io/toto?create=true
```

------

Can you confirm and fix this issue ?

Thank you =)

**Comment by MichaelEischer** [comment]
Closing this issue as this is a usage problem and we got no feedback within a month. Feel free to comment if this issue isn't resolved with my reply yet.
