### ISSUE TITLE
Fatal: number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by sarapayne** [restic/restic#2767]
1 snapshots have been removed, running prune
counting files in repo
building new index for repo
[2:30] 100.00%  1150 / 1150 packs
repository contains 1150 packs (41230 blobs) with 5.557 GiB
processed 41230 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 1 snapshots
[0:04] 100.00%  1 / 1 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

but i have no idea what where that output might be found

**Comment by MichaelEischer** [comment]
Closing this issue in favor of #2663, please add the error message there if you still need help resolving this problem.
