### ISSUE TITLE
MacOS HFS+ Creation Date Issue.

### ISSUE THREAD

**Issue by DiagonalArg** [restic/restic#2768]
In a two+ year old, very thorough bug report, #1622, @MacLemon tested Restic's behavior when backing up and restoring HFS+ disks.  The tests he ran were a partial success, but missing 3 (4?) components:

1. creating date
2. bsd-flags (which includes finder-locks)
3. ACL's
4. apparently also extended attributes on symlinks

While this report has been put under the heading of a Feature Request, the OP suggested that the creation date issue, which [may be the highest priority](https://github.com/restic/restic/issues/1622#issuecomment-450749840), might [actually be a bug](https://github.com/restic/restic/issues/1622#issuecomment-366467500):

> The creation-date is currently set to the modified-date of the file, not the timestamp when it was restored which is why I personally would consider this a bug, not an enhancement. (Also was unexpected, since the mtime is already restored correctly.) To my laypersons eyes this feels more like “picking the wrong timestamp property we have stored” upon restore rather than not having anything to restore at all. Upon which I'd expect it to just set the creation time to the point in time of the restore.

Therefore, in the interest of this potentially being fixable as a bug, I am moving this to a bug report, so that it isn't lost.

**Comment by MichaelEischer** [comment]
restic only explicitly restores the modification and access times, the creation time is not modified explicitly. restic currently doesn't have a concept of a creation date (also called birth date on Linux), thus that issue is an enhancement just like the rest of #1622.
