### ISSUE TITLE
error in handling lock file causes loop of lock refresh errors and log spam

### ISSUE THREAD

**Issue by GilGalaad** [restic/restic#2771]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.14.1 on freebsd/amd64

How did you run restic exactly?
-------------------------------
RESTIC_REPOSITORY=rclone:gsuite:/restic
RESTIC_PASSWORD=my_strong_pasword
restic backup --cache-dir /store/backup/restic/cache --cleanup-cache --files-from filelist.txt --limit-upload=8000

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Google Drive via rclone

Expected behavior
-----------------
restic should be able to recover from failures on lock files just like any other data or index file

Actual behavior
---------------
when an operation on a lock file fails, restic tries indefinitely to refresh the nonexistent lock, filling logs witht the same information over and over, like the folowing line.
```
Remove(<lock/1412d8a053>) returned error, retrying after 525.882525ms: <lock/1412d8a053> does not exist
```
additionally, there is a small glitch with the console buffer, that does not overwrites the progress line completely
```
unable to refresh lock: <lock/1412d8a053> does not existles 6.145 TiB, 0 errors ETA 155:32:21
```
the backup process is going on correctly anyway.
execution log is attached.
[restic.log](https://github.com/restic/restic/files/4729072/restic.log)

Steps to reproduce the behavior
-------------------------------
I think you can reproduce the issue manually deleting a lock file while upload is running.
or you can backup a 6TB folder and wait until it happens :P

Do you have any idea what may have caused this?
-----------------------------------------------
a temporary failure of the storage provider while deleting the lock
```
rclone: 2020/06/03 21:44:09 ERROR : locks/1412d8a0538ac5e73ff812098d8a8d629eb6b5ec2d1722382e493ddbd38b8823: Delete request remove error: googleapi: Error 404: File not found: 16X-_9ERts7gCDBXkijJGLSoHZAGAXqOE., notFound
Remove(<lock/1412d8a053>) returned error, retrying after 430.90274ms: blob not removed, server response: 500 Internal Server Error (500)
```

Do you have an idea how to solve the issue?
-------------------------------------------
no. unfortunately i don't know golang enough to study restic internals.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
restic makes me happy in many ways.

**Comment by MichaelEischer** [comment]
Closing this as duplicate. See #2715 (second bullet point) for a list of relevant issues. Feel free to comment, if I've missed something.
