### ISSUE TITLE
--limit-upload not working with S3 backend

### ISSUE THREAD

**Issue by msilano** [restic/restic#2772]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
-------------------------------
restic -v --limit-upload=4096  --files-from=/var/services/homes/admin/backup
-restic/vault.txt --exclude-file=/var/services/homes/admin/backup-restic/exclude.txt  -r s3:https://s3.wasabisys.com/xx/yy

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
wasabi

Expected behavior
-----------------

Restic upload capped at the limit

Actual behavior
---------------

Restic went full throttle and took all available upload bandwidth

Steps to reproduce the behavior
-------------------------------

run restic again.  

Do you have any idea what may have caused this?
-----------------------------------------------
no

Do you have an idea how to solve the issue?
-------------------------------------------
Searched for similar issues recently but didn't find anything.   

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is awesome, just want my son to be able to play fortnite without complaint when restic is active.

**Comment by MichaelEischer** [comment]
How much upload bandwidth do you have? 4MByte/s / 32MBit/s sounds like a substantial fraction of the upload bandwidth available via residential internet access.

I just took a look at the code: The HTTP connection for S3 definitely is configured to limit its upload bandwidth. So this would mean that something there isn't working properly.

**Comment by msilano** [comment]
Dammit.  Read that as bits not bytes.   Will try again; thanks for looking
and apologies for the misstep.

**Comment by msilano** [comment]
Confirmed working.  Thanks again.

**Comment by MichaelEischer** [comment]
Closing this as the issue seems to be solved.
