### ISSUE TITLE
failed to unmount /mnt/restic: Device or resource busy

### ISSUE THREAD

**Issue by nunoperalta** [restic/restic#2774]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
-------------------------------

```
[root@server restic]# . restic.env; restic mount /mnt/restic
repository xxxxxx opened successfully, password is correct
created new cache in /root/.cache/restic
Now serving the repository at /mnt/restic
When finished, quit with Ctrl-c or umount the mountpoint.
  signal interrupt received, cleaning up
unable to umount (maybe already umounted?): exit status 1: fusermount: failed to unmount /mnt/restic: Device or resource busy
[root@server restic]# ps aux | grep restic
root      8052  0.0  0.0 112812   972 pts/0    S+   07:41   0:00 grep --color=auto restic
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

CentOS 7

Expected behavior
-----------------

When I sent Ctrl+C signal, the "restic" mount should be un-mounted.

Actual behavior
---------------

```
[root@server mnt]# ll
ls: cannot access restic: Transport endpoint is not connected
total 8
drwxr-xr-x.  3 root root 4096 2020-04-01 16:13 .
dr-xr-xr-x. 19 root root 4096 2019-06-13 08:33 ..
d??????????  ? ?    ?       ?                ? restic
[root@server mnt]# ll restic
ls: cannot access restic: Transport endpoint is not connected
[root@server mnt]# df -h
df: ‘/mnt/restic’: Transport endpoint is not connected
(...)
[root@server mnt]# umount restic
[root@server mnt]# df -h
(all good)
```

--

In above command outputs, please notice the following:

> unable to umount (maybe already umounted?): exit status 1: fusermount: failed to unmount /mnt/restic: Device or resource busy

and

> ls: cannot access restic: Transport endpoint is not connected

> df: ‘/mnt/restic’: Transport endpoint is not connected

The "restic" mount apparently failed to un-mount automatically.
Doing manually worked, though.

**Comment by rawtaz** [comment]
I never saw this before, and I've been using the mount feature a number of times, but it's been mostly on macOS. Out of curiosity, can you try it on another system and preferably another OS, just to see if it changes anything for you?

**Comment by nunoperalta** [comment]
Hello. Thank you for your reply.
I only have access to CentOS servers at the moment.

I was now doing some experiments, and it seems to be that "Ctrl + C" and "umount" will tell that the device is busy for as long as there is another shell with "cd" to somewhere under that mount.
Once I move somewhere else (e.g. "cd /"), the un-mount works smoothly.

Maybe this is as expected?

**Comment by rawtaz** [comment]
> the device is busy for as long as there is another shell with "cd" to somewhere under that mount

This is highly expected. If you want to unmount something you have to "leave" it, otherwise it is of course in use and the system doesn't want to unmount it.

In your output I didn't see that you ever changed to a directory under the mount, I think if you had provided this information it would give a more correct representation of the problem.

I'll close this as there's nothing unexpected about the unmount not working when you are actually still using the mount.

**Comment by nunoperalta** [comment]
Perfect - no problem, and good to know!

I would just like to suggest improving the following message:

> unable to umount (maybe already umounted?):

to:

> unable to umount (maybe already umounted or still in use?):


Other than that - thanks!

**Comment by rawtaz** [comment]
@nunoperalta That's a good idea, thanks for the suggestion!

I'm curious, would you mind opening a pull request for that change? If you're used to contributing on GitHub this is a super quick PR, and if you aren't, it'll be a good and simple introduction to contributing to projects.

You just have to edit this line: https://github.com/restic/restic/blob/84475aa3a8c6816074fa664378891d8ae3d25d8a/cmd/restic/cmd_mount.go#L183

Let me know if you need help. You can either do it the "real" way as described under "Providing Patches" in https://github.com/restic/restic/blob/master/CONTRIBUTING.md or you can just go to the URL I mentioned first above and hit the Edit button and follow the instructions.

**Comment by nunoperalta** [comment]
Thanks - see https://github.com/restic/restic/pull/2776
