### ISSUE TITLE
Cannot init repo on Backblaze B2 - restic creates local repo instead

### ISSUE THREAD

**Issue by Stinocon** [restic/restic#2775]
Output of `restic version`
-----------------
restic 0.3.3
compiled with go1.7.4 on linux/amd64

How did you run restic exactly?
-----------------
export B2_ACCOUNT_ID=MyMasterKey
export B2_ACCOUNT_KEY=MyAccountKey
restic -r b2:BucketNameCaseSensitive:RepoName init

What backend/server/service did you use to store the repository?
-----------------
BackBlaze B2

Expected behavior
-----------------
Create everything you need in the indicated bucket of Backblaze b2.

Actual behavior
---------------
A local repository is created, nothing backblaze side is generated.

Steps to reproduce the behavior
-------------------------------
1) Create a new bucket on backblaze
2) SSH on the server on which restic is run and login as root
3) Export the necessary keys
4) Execute the init command

Do you have any idea what may have caused this?
-----------------------------------------------
Introduction:
I have two Debian 9 Linux servers to back up. On the first one, a file server, I initialized the bucket correctly and made the first backup. Everything is perfect.
I decided to implement restic on the second server as well.

At first I thought I couldn't use a bucket already initialized for restic to back up another server (different restic server, same bucket, different repo) so I created a new bucket and tried to make the init with both the master key and a specially generated key for that bucket.
The repo is always created inside the folder I'm in (in this case /home/myuser but also tried other locations)

I also looked at the commands and the procedure carried out on the first server... 
The procedures are really identical. Only the repository names change, but no, there are no typing errors (which I avoid by copying and pasting names and keys).

Do you have an idea how to solve the issue?
-------------------------------------------
Nope :(

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I was definitely impressed with the ease of use. At least on first use. 
I was able to write the backup and put it all into a cron and it works perfectly with my b2 instance.
So I was able to have an offsite cloud backup of important files.

Let's see if I can get it from the second server too.

**Comment by rawtaz** [comment]
@Stinocon Where did you get that 0.3.3 version of restic from? It's over three years old :)

Backblaze support was introduced in version 0.7.0 so what you are seeing is expected.

Please use the latest release of restic, 0.9.6, or if you are happy to do so the latest master build from https://beta.restic.net/?sort=time&order=desc , and it will be fine 🚀
