### ISSUE TITLE
Add s390x architecture into restic release binaries

### ISSUE THREAD

**Issue by e-desouza** [restic/restic#2780]
Output of `restic version`
--------------------------

0.9.6+

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

No difference in functionality. This request is to ensure s390x binaries are available on the release page [here](https://github.com/restic/restic/releases/tag/v0.9.6). Restic is already available from Ubuntu etc on s390x so no additional porting is needed. This will enable consistency across platforms instead of having to do something different for s390x (i.e download binary from the release page vs having to build from source or pull from distro repo).

What are you trying to do?
--------------------------

Download s390x binary for Restic

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes ! The [Velero project](https://github.com/vmware-tanzu/velero) uses capabilities from Restic and I'd like to port that awesome functionality to s390x.

**Comment by J0WI** [comment]
And probably also MIPS and PowerPC

**Comment by hoytk** [comment]
This item is closed but I don't see s390x packages to download.  Am I missing them or was this issue abandoned?

**Comment by rawtaz** [comment]
> This item is closed

Nope, this issue is still open :)

**Comment by hoytk** [comment]
Doh!  2633 caught my eye at the wrong moment :-)

I'd like to vote for this item.
It's been open for a year, is there a planned date?

**Comment by rawtaz** [comment]
No. Any activity on this specific issue will be noted here in this issue.

**Comment by MichaelEischer** [comment]
I've created a PR to add release binaries for s390x. However, please note that we only have Linux on amd64 test coverage and not Linux on s390x. So someone should manually build and test restic for that architecture to make sure that it actually works, although I don't expect any surprises.

**Comment by hoytk** [comment]
My team will test and open bugs as needed.

Thank you!
