### ISSUE TITLE
Vagrant/Restic big big problem

### ISSUE THREAD

**Issue by Vartkat** [restic/restic#2782]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on darwin/amd64

How did you run restic exactly?
-------------------------------
not relevant

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Wasaby but not relevant

Expected behavior
-----------------
files not deleted

Actual behavior
---------------
vagrant files are deleted but I'm not sure restic is involved

Steps to reproduce the behavior
-------------------------------
On OS X Mac Mojave.
I've made a bash script to backup a Virtualbox vm (vdi file). 
The vm has been built using Vagrant.
The script shuts down the vm using the "vagrant halt" command.
It runs restic which goes without problem.
The moment it treis to reboot the vm using the "vagrant up" command, vagrant deletes a bunch of file in the 
.vagrant/machines/default/virtualbox/ directory
a directory where are stored an "id" file (this file tells which vm has to be addressed) and some ssh key files.

Why do I say vagrant is the culprit is because I ran an fs_enventer to see who was deleting the files and the answer is a ruby process. As far as I know restic is not written in ruby but vagrant is.

Result of the files deleting is that vagrant is rebuilding a brand new vm when "vagrant up" is invoqued.

I know that it sound strange to post this problem in restic forum (I'm also posting in vagrant) but I was wondering if restic is changing any meta data on the files which could be a reason for vagrant to delete them.

Do you have any idea what may have caused this?
-----------------------------------------------
I suspect some files meta data change by restic which vagrant doesn't like.

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Without this case I'm very happy with restic which saved a ton of hours thanks to the backup. Perhaps the prune and forget could be done faster but that's not my subject here

**Comment by rawtaz** [comment]
> I was wondering if restic is changing any meta data on the files

Restic itself doesn't make any changes to the files it reads, it has no reason to do so - it's job is just to read the directories and files that you are asking it to back up.

Perhaps your filesystem is changing metadata for files that restic reads, you can check that using e.g. `stat` on the files right before and right after the restic backup run.

Sorry to not be of more help :/ I'll close this issue as it's not really a restic bug or feature request. The question would have been better posted in the restic forum.
