### ISSUE TITLE
using an empty password on initial creation will create an unusable repository

### ISSUE THREAD

**Issue by MirkoDziadzka** [restic/restic#279]
# how to reproduce

init a new repository and enter an empty password

```
$ ./restic -r foo  backup ~/tmp
enter password for repository: 
an empty password is not a password
```

So just try it again, this time willing to enter a non-empty password

# expected result

Can do this again and enter a password this time.

# actual result

```
$ ./restic -r ~/tmp  init
creating backend at /Users/mirko/tmp failed: dir /Users/mirko/tmp/data already exists
```

I can do nothing except deleting ```~/tmp```. This maybe a problem with other backends.

# proposal

Do the *i want a non empty password* check before initializing the repository.

**Comment by fw42** [comment]
This is somewhat similar to https://github.com/restic/restic/issues/199... Agree that it should be fixed.

**Comment by fd0** [comment]
Thanks for reporting it, that's a bug.
