### ISSUE TITLE
restic mount for Windows?

### ISSUE THREAD

**Issue by jmpq** [restic/restic#2791]
Hi,
I am wondering if anyone is interested in `restic mount` for Windows?

I am trying to implement restic mount for Windows using the cgofuse/winfsp library, now it works on my windows 10 desktop. 

I tried to use the existing fuse code as much as possible. so I basically moved unix/linux related code to a separate file and remained the code path for unix/linux untouched. A new file windows.go was added to implemented the windows fs operations.

You may check it here:
https://github.com/jmpq/restic/tree/win-mount

If it is helpful, I will do more testing and polish the code.

Looking forward to your comments, have a good day.

**Comment by rawtaz** [comment]
This has been discussed before in various issues, see https://github.com/restic/restic/issues?q=fuse+windows . Using CGO isn't something we want to do in restic, we wish to keep it pure Go, so unfortunately this is not a working approach. Sorry :/

**Comment by jmpq** [comment]
Thanks for your reply.

It looks like cgofuse/winfsp supports both cgo and !cgo build. 

For !cgo, it load the dll with syscall.LoadDLL() and get the function entry point using dll.MustFindProc(func_name) and call the function

Would this be regarded as pure Go?

**Comment by jmpq** [comment]
Thanks for your reply.

It looks like cgofuse/winfsp supports both cgo and !cgo build.

For !cgo, it load the dll with syscall.LoadDLL() and get the function entry point using dll.MustFindProc(func_name) and call the function

Would this be regarded as pure Go?

**Comment by fd0** [comment]
Maybe, somebody would need to figure out if it works, implement it, and support it for our users...

**Comment by fgma** [comment]
@jmpq I've just opened a PR for the same feature. I did not see this issue before because it was already closed.
