### ISSUE TITLE
Restore expected absolute windows paths

### ISSUE THREAD

**Issue by krabat** [restic/restic#2792]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.4 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

restic's usage should be easy, but windows handling seems to be more complicated than it needs to be:

backup: `restic -r X:\repo backup C:\dev\projects`
restore: `restic -r X:\repo restore latest -t C:\`

expected path restored: `C:\dev\projects`
actual path restored: `C:\C\dev\projects`

Changing it to `-t D:\` should restore it to `D:\dev\projects`.

(I know there is a workaround for this, but it complicates my backup script a lot and I would be glad to see restic's vision of simple handling implemented for windows, too)

What are you trying to do?
--------------------------

cover a simple backup/restore scenario

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I think restic is great! The deduplication mechanic is super neat and the speed is top notch. I was in the same boat as the restic author: trying different backup solutions, but none really fit, but restic does it - and all with one portable binary. Also, thank you for releasing windows binaries!

**Comment by jbsilva** [comment]
Hello. What is the workaround?
On Linux I could just `cd` into the parent directory and use a relative path, but this is not working on Windows.

**Comment by krabat** [comment]
Hi, the workaround: 

- change working dir to drive's root dir, e.g. "C:\"
- bkup with relative dirs, e.g. ".\data"
- restore to "C:\" to re-create the data in the original path: "C:\data"

__Sidenote__: `restic snapshots` still shows "C:\data", but the real path is shown via `restic ls <snap>` with path "/data"

**Comment by MichaelEischer** [comment]
The `snapshotID:subfolder` allows removing unneceessary path prefixes. As backups can contains files from multiple drives, it's not possible to generalize this. Closing in favor of https://github.com/restic/restic/issues/4575 .
