### ISSUE TITLE
Fatal: unable to save snapshot: node "https+++www.youtube.com" already present

### ISSUE THREAD

**Issue by msedv** [restic/restic#2795]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on windows/amd64

How did you run restic exactly?
-------------------------------
```
restic_0.9.6_windows_amd64.exe -p restic.password -r sftp:backup@nas1.local.xxx.net:ms.backup --exclude 'NTUSER.DAT'  backup c:\Users\ms
```

gives:

```
Fatal: unable to save snapshot: node "https+++www.youtube.com" already present
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
sftp on FreeNAS

Expected behavior
-----------------
Continue to backup

Actual behavior
---------------
Backups stops with error

Steps to reproduce the behavior
-------------------------------
See below

Do you have any idea what may have caused this?
-----------------------------------------------
C:\Users\ms\AppData\Roaming\Mozilla\Firefox\Profiles\zyt4njvn.default-release\storage\default contains:

```
12:16    <DIR>          https+++www.youtube.com
12:36    <DIR>          https+++www.youtube.com.
```

Do you have an idea how to solve the issue?
-------------------------------------------
Don't ignore trailing dots - or, as I did, put the directory in the exclude-list. :-)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I love it - as long as my backups finish. :-)

**Comment by MichaelEischer** [comment]
This is a problem of the path normalization on windows which unfortunately removes trailing dots from filename. That problem is already tracked in #2745 so I'm closing this as duplicate.
