### ISSUE TITLE
Atomic snapshots

### ISSUE THREAD

**Issue by darkdragon-001** [restic/restic#2800]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.12.12 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
When backing up large running services, file integrity is at risk when the first file has been backed-up at quite a different time than the last one.

Add feature for atomic snapshots:
1. Use file-system capabilities to create a local snapshot (LVM, Btrfs, ZFS)
2. Backup folder within that snapshot

It would be awesome, if this would be possible with a flag (e.g. `--atomic-source`). Restic should determine the actions automatically based on the mount table and file system type.

It could be implemented with pre/post-hooks:
1. Create snapshot
2. Mount snapshot to folder
3. The mount folder is the source of the backup

What are you trying to do?
--------------------------
Backup a large running service on modern file systems (Btrfs, ZFS).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is running quite stable for some weeks now :smile:

**Comment by greatroar** [comment]
Why should restic do this? Why not script it?

**Comment by darkdragon-001** [comment]
Because it would save a lot of users from the problems of non-atomic snapshots. This type of problems is only visible when you restore a backup. Often it is not visible during premature tests since the load is significantly lower. Furthermore, features in restic are way more trustable than features in some scripts you find in the internet.

Nevertheless, if restic does not plan to add such a feature this issue can be closed.

**Comment by rawtaz** [comment]
While I completely agree that oftentimes one has to coordinate these things for larger services, each individual use case and requirements are too specific to be supported by a tool like restic. The closest to supporting it we'd come is to have pre/post hooks, which you suggested, but it's still very hard to get to a point where you don't need scripts anyway. I mean, your hooks would be scripts or commands I presume, and in the end it's easier to just wrap it all in a script or similar.

Feel free to correct me if I'm wrong in any way, or to provide more feedback on this topic, but at this point in time it won't be implemented so I'm closing this issue. The topic can be revisited in the future if need be :)
