### ISSUE TITLE
Archiver generates one GetReader requests per directory

### ISSUE THREAD

**Issue by bchapuis** [restic/restic#282]
When walking the file tree, the archiver generates one LoadJSONPack call per directory, each of which generates a GetReader request on the backend with a length and an offset. These requests seems to usually occur on a small number of pack files that contain blobs of type pack.Tree. When dealing with remote backends, it may be more efficient to load and cache these files.

**Comment by fd0** [comment]
Thanks for reporting this!

Indeed, good point. It's on my (internal) todo list to cache this. I suspect that this is the reason why an "incremental" backup takes a bit longer than a full backup for me :)

**Comment by fd0** [comment]
This will be solved by #1040.
