### ISSUE TITLE
Use new chunker

### ISSUE THREAD

**Issue by greatroar** [restic/restic#2820]
The restic chunker got some performance enhancements (e.g., restic/chunker@be7f5d823c60401be30ac77dcab9e824e4017691) as of recent, but it hasn't seen a new release yet. If it got a release (which means pushing a tag to a repo, AFAIK), restic could import the new version with go get -u. Would someone with push access please do a release?

**Comment by fd0** [comment]
Done

**Comment by greatroar** [comment]
Thanks!
