### ISSUE TITLE
Build with go1.14.4 doesn't works well in backup

### ISSUE THREAD

**Issue by egoistzqw** [restic/restic#2822]
Output of `restic version`
--------------------------
restic 0.9.6(master-commit:cba6ad8d8e) compiled with go1.14 on windows/386

How did you run restic exactly?
-------------------------------
```
go run build.go --goos windows --goarch 386
set AWS_ACCESS_KEY_ID=XXXX
set AWS_SECRET_ACCESS_KEY=XXXX
restic.exe -r s3:http://xxxx:xxxx/xxxx  init
restic.exe -r s3:http://xxxx:xxxx/xxxx  backup ./xxxx  
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
minio server

Expected behavior
-----------------
Restic should backup correctly.

Actual behavior
---------------
debug enabled
runtime: out of memory: cannot allocate 12582912-byte block (1731166208 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xbf4f72, 0xd)
	runtime/panic.go:1116 +0x64
runtime.largeAlloc(0x820600, 0x101, 0x1)
	runtime/malloc.go:1154 +0x103
runtime.mallocgc.func1()
	runtime/malloc.go:1047 +0x39
runtime.systemstack(0x0)
	runtime/asm_386.s:395 +0x53
runtime.mstart()
	runtime/proc.go:1041

goroutine 5202 [running]:
runtime.systemstack_switch()
	runtime/asm_386.s:356 fp=0x2b963bbc sp=0x2b963bb8 pc=0x45dde0
runtime.mallocgc(0x820600, 0xb03da0, 0x2001, 0x2000)
	runtime/malloc.go:1046 +0x686 fp=0x2b963c10 sp=0x2b963bbc pc=0x40b256
runtime.makeslice(0xb03da0, 0x820600, 0x820600, 0x0)
	runtime/slice.go:49 +0x4f fp=0x2b963c24 sp=0x2b963c10 pc=0x4475df
bytes.makeSlice(0x820600, 0x0, 0x0, 0x0)
	bytes/buffer.go:229 +0x64 fp=0x2b963c40 sp=0x2b963c24 pc=0x474974
bytes.(*Buffer).grow(0x138929c0, 0x8000, 0x8000)
	bytes/buffer.go:142 +0x11c fp=0x2b963c68 sp=0x2b963c40 pc=0x4743cc
bytes.(*Buffer).Write(0x138929c0, 0x6eb9a000, 0x8000, 0x8000, 0x6eb9a000, 0x8000, 0x8000)
	bytes/buffer.go:172 +0xb5 fp=0x2b963c7c sp=0x2b963c68 pc=0x474635
io.(*multiWriter).Write(0x13913910, 0x6eb9a000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	io/multi.go:60 +0x6d fp=0x2b963ca8 sp=0x2b963c7c pc=0x46cf0d
net/http/httputil.(*dumpConn).Write(0x13913920, 0x6eb9a000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	<autogenerated>:1 +0x45 fp=0x2b963cc8 sp=0x2b963ca8 pc=0x69ae05
io.copyBuffer(0x342e4300, 0x13913920, 0xd3a370, 0x13913940, 0x6eb9a000, 0x8000, 0x8000, 0xb2c760, 0xb73d80, 0x13ae8e01, ...)
	io/io.go:407 +0x190 fp=0x2b963d08 sp=0x2b963cc8 pc=0x46c400
io.Copy(...)
	io/io.go:364
net/http.persistConnWriter.ReadFrom(0x149aa5a0, 0xd3a370, 0x13913940, 0x342e42e8, 0x149aa5a0, 0x1, 0x34d)
	net/http/transport.go:1672 +0x75 fp=0x2b963d38 sp=0x2b963d08 pc=0x685395
bufio.(*Writer).ReadFrom(0x13892a60, 0xd3a370, 0x13913940, 0x342e42d0, 0x13892a60, 0x40ae01, 0x13913940)
	bufio/bufio.go:714 +0x2dd fp=0x2b963d90 sp=0x2b963d38 pc=0x6044dd
io.copyBuffer(0xd391b0, 0x13892a60, 0xd3a370, 0x13913940, 0x0, 0x0, 0x0, 0xd3a370, 0x139138c0, 0x139138c0, ...)
	io/io.go:391 +0x29b fp=0x2b963dd0 sp=0x2b963d90 pc=0x46c50b
io.Copy(...)
	io/io.go:364
net/http.(*transferWriter).doBodyCopy(0x139459f0, 0xd391b0, 0x13892a60, 0xd3a370, 0x13913940, 0x1000, 0x286, 0x0, 0x0)
	net/http/transfer.go:400 +0x55 fp=0x2b963e10 sp=0x2b963dd0 pc=0x67b9e5
net/http.(*transferWriter).writeBody(0x139459f0, 0xd391b0, 0x13892a60, 0x2, 0x2)
	net/http/transfer.go:359 +0x602 fp=0x2b963e8c sp=0x2b963e10 pc=0x67b8e2
net/http.(*Request).write(0x13b0cb80, 0xd391b0, 0x13892a60, 0x0, 0x13892a80, 0x0, 0x0, 0x0)
	net/http/request.go:685 +0x5b2 fp=0x2b963f3c sp=0x2b963e8c pc=0x665c82
net/http.(*persistConn).writeLoop(0x149aa5a0)
	net/http/transport.go:2280 +0x15d fp=0x2b963fe8 sp=0x2b963f3c pc=0x68780d
runtime.goexit()
	runtime/asm_386.s:1337 +0x1 fp=0x2b963fec sp=0x2b963fe8 pc=0x45f6f1
created by net/http.(*Transport).dialConn
	net/http/transport.go:1648 +0xa5c

goroutine 1 [select, 2 minutes]:
github.com/restic/restic/internal/archiver.(*FutureFile).Wait(0x142bb540, 0xd43de0, 0x13c158c0)
	github.com/restic/restic/internal/archiver/file_saver.go:26 +0xb9
github.com/restic/restic/internal/archiver.(*FutureNode).wait(0x142bb4f8, 0xd43de0, 0x13c158c0)
	github.com/restic/restic/internal/archiver/archiver.go:284 +0xf3
github.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0x13944370, 0xd43de0, 0x13c158c0, 0xbebb71, 0x1, 0x13c15840, 0x0, 0x0, 0x0, 0x0)
	github.com/restic/restic/internal/archiver/archiver.go:602 +0x102d
github.com/restic/restic/internal/archiver.(*Archiver).Snapshot.func1(0x13944370, 0xd43de0, 0x13c158c0, 0x13c15840, 0x0, 0x0, 0x0, 0x13820580, 0xf, 0x0, ...)
	github.com/restic/restic/internal/archiver/archiver.go:754 +0xb9
github.com/restic/restic/internal/archiver.(*Archiver).Snapshot(0x13944370, 0xd43de0, 0x138471e0, 0x138063e8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x13820580, ...)
	github.com/restic/restic/internal/archiver/archiver.go:764 +0x1d0
main.runBackup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/restic/restic/cmd/restic/cmd_backup.go:600 +0xe15
main.glob..func2(0x1230ee0, 0x138784b0, 0x1, 0x9, 0x0, 0x0)
	github.com/restic/restic/cmd/restic/cmd_backup.go:71 +0x1b4
github.com/spf13/cobra.(*Command).execute(0x1230ee0, 0x13b80000, 0x9, 0xc, 0x1230ee0, 0x13b80000)
	github.com/spf13/cobra@v0.0.3/command.go:762 +0x313
github.com/spf13/cobra.(*Command).ExecuteC(0x1232560, 0x24, 0x13adff64, 0x4)
	github.com/spf13/cobra@v0.0.3/command.go:852 +0x243
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	github.com/restic/restic/cmd/restic/main.go:86 +0x151

goroutine 19 [chan receive, 2 minutes]:
github.com/restic/restic/internal/restic.init.0.func1.1()
	github.com/restic/restic/internal/restic/lock.go:258 +0xe7
created by github.com/restic/restic/internal/restic.init.0.func1
	github.com/restic/restic/internal/restic/lock.go:255 +0x2b

goroutine 34 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	runtime/sigqueue.go:147 +0x12f
os/signal.loop()
	os/signal/signal_unix.go:23 +0x1a
created by os/signal.Notify.func1
	os/signal/signal.go:127 +0x33
.....

Steps to reproduce the behavior
-------------------------------
build with go1.14, windows/386
running a backup(large file, my test file is 18.5G, small file may not happen)

Do you have any idea what may have caused this?
-----------------------------------------------
 Building restic work well with older versions of Go1.12 and Go1.13 and may be the Go1.14 new feature influence it?
 Actually, there is no obvious problem compiling with windows/amd64, but crash with windows/386.

Do you have an idea how to solve the issue?
-------------------------------------------
no, i just try to recompiled it with GO1.13.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
yes

**Comment by MichaelEischer** [comment]
Please try restic 0.10.0. Could you also try updating your go compiler to 1.15 or 1.14.9?

**Comment by fd0** [comment]
I'm closing this for now, no feedback has been received. Please feel free to add further comments, thanks!
