### ISSUE TITLE
restic check should report if superseded index files still exist

### ISSUE THREAD

**Issue by aawsome** [restic/restic#2824]
Output of `restic version`
--------------------------
restic 0.9.6 (v0.9.6-253-g642da0a0-dirty) compiled with go1.14.3 on linux/amd64

How did you run restic exactly?
-------------------------------
Use the repo from `/cmd/restic/testdata/repo-obsolete-index.tar.gz`from 
https://github.com/restic/restic/pull/2718/commits/abd85e65c0d23c6ce20807edc410e7393f36d828
(password is "geheim").

This repo contains two index files: {392240e9 e88b8990} which are identical except that  392240e9 supersedes e88b8990. This can be easily checked by running `restic cat index` on both files.

run `restic check -r /path/to/repo` with the path to the unpacked repo.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local backend

Expected behavior
-----------------
`check` should warn that superseded index files still exist in the repo.

Actual behavior
---------------
```
pack f5c03970 contained in several indexes: {392240e9 e88b8990}
pack 88128df7 contained in several indexes: {392240e9 e88b8990}
This is non-critical, you can run `restic rebuild-index' to correct this
```

Steps to reproduce the behavior
-------------------------------

see above

Do you have any idea what may have caused this?
-----------------------------------------------

superseded index information is not handled by the `check` command

Do you have an idea how to solve the issue?
-------------------------------------------

implement handling of superseded indexes within `check`

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Makes me happy most days as I learned a lot about go programming when working on restic.
Sometimes makes my family unhappy because I'm spending too much time on it. :smirk:

**Comment by MichaelEischer** [comment]
The superseded field in the index has been removed in https://github.com/restic/restic/pull/4812
