### ISSUE TITLE
key passwd prompt incorrect

### ISSUE THREAD

**Issue by bdillahu** [restic/restic#2829]
If you issue a "key passed" command, you get the same prompt as if you are entering a new key... works fine, but a little confusing:

repository 0f983225 opened successfully, password is correct
enter password for new key:
enter password again:

I think it should read:

enter new password:

Just thought I would mention it.

**Comment by rawtaz** [comment]
@bdillahu Can you elaborate in what way you think the current text is nofusing? What you are doing is entering a new key, so the text seems rather appropriate to me.

**Comment by bdillahu** [comment]
@rawtaz Maybe it's user error, but I read the docs:

"The key command allows you to set multiple access keys or passwords per repository. In fact, you can use the list, add, remove, and passwd (changes a password) sub-commands to manage these keys very precisely:"

And I have used the list, add and remove commands successfully - all good. My understanding (although I didn't find much documentation about it) was that the "passed" command lets you change the password on an existing key. And in my testing that is what I think it does... not creating a new key (although maybe behind the scenes, it did and I didn't realize that).

So in this instance I gave a:

restic.... key passed

command... and it prompted for a password for a new key - which I thought I was just changing the password on the existing key.

At least that was my thought process.

Thanks,
Bruce

**Comment by rawtaz** [comment]
Thanks for the clarification, I see what you mean. It's probably just a message being reused. Let's leave it open.

**Comment by bdillahu** [comment]
Yes, line 98 of cmd_key.go is the "getNewPassword" function... which gets called for both new keys and password changes.

Not sure what the best/most desired change would be - I could duplicate the function and tweak the text, or come up with some more generic prompt...

**Comment by nicodemusjls** [comment]
I think generic is fine.
Enter password (new)
Enter password (again)

If situational clarification is needed, it can be offered before the function is called. Like:
Updating password for *key*.
Enter password (new)
Enter password (again)

**Comment by bdillahu** [comment]
I decided to not do the "situational clarification" - looking deeper at the code, figured out that changing the password really just creates an entire new key anyhow, so it's really correct. I think your phrasing does help clarify things.

Thanks!
