### ISSUE TITLE
Failed to init on S3 bucket after assume-role

### ISSUE THREAD

**Issue by pcoves** [restic/restic#2836]
Output of `restic version`
--------------------------

```
Fatal: create repository at s3:s3.amazonaws.com/<S3_bucket> failed: client.BucketExists: The AWS Access Key Id you provided does not exist in our records.
```

How did you run restic exactly?
-------------------------------

1. `aws sts assume-role` that gives me *public* and *secret* key to put in `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
2. Export of `AWS_DEFAULT_REGION`, `RESTIC_REPOSITORY` and `RESTIC_PASSWORD`.
3. `restic init`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

AWS S3 here.

Expected behavior
-----------------

Newly created `restic` repository. 

Actual behavior
---------------

It's all in the error : `restic` fails to init the repository.

Steps to reproduce the behavior
-------------------------------

Here is the thing : if I keep steps 1 and 2 from the previous section, I end up with those environment variables:
* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`
* `AWS_DEFAULT_REGION`
* `RESTIC_REPOSITORY`
* `RESTIC_PASSWORD`

At this point, the command `aws s3 cp <file> <bucket>` works just fine.
So, I can write to the bucket.

But, `restic init` gives me the `Fatal: create repository at s3:s3.amazonaws.com/<S3_bucket> failed: client.BucketExists: The AWS Access Key Id you provided does not exist in our records.` error.

The *fun* thing is, if I work with my default AWS account (so, no `assume-role`), everything from `aws s3 cp` to `restic init` works perfectly.

Do you have any idea what may have caused this?
-----------------------------------------------

I'd first look at how/where does `restic` fetch the `aws` account it uses.
Seems like it uses the good key pair (from the env) but not the good account/profile.

Do you have an idea how to solve the issue?
-------------------------------------------

Nopity nop, sorry.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Damn yeah!

Fantastic tool that saved us from an EC2 crash yesterday.

10/10, would backup again.

**Comment by rkoehn** [comment]
Hi @pcoves,

As far as I know, AWS assume role also returns you a session token in addition to the access key id and secret access key, so you may need another env variable. 

> AWS_SESSION_TOKEN
>
>   Specifies the session token value that is required if you are using temporary security credentials that you retrieved directly from AWS STS operations. For more information, see the Output section of the assume-role command in the AWS CLI Command Reference. 

see https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Comment by pcoves** [comment]
As a matter of fact, I do have this one as well.

I did not mention it as I thought it was irrelevant.

**Comment by ctonsing** [comment]
Hey guys, just wondering whether there has been any progress with restic supporting the session token for S3?

**Comment by MichaelEischer** [comment]
Which restic version did you use? Have you tried whether restic 0.12.1 works? Judging from a brief look in the code, restic should be able to use `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`.

**Comment by ctonsing** [comment]
Thank you @MichaelEischer , sorry, I haven't tried it at all as I didn't know that this env variable is available and it is something we may need in future only. Since this ticket was still open and the AWS_SESSION_TOKEN env variable is not mentioned in the docs as far as I could see, I assumed this was not available.

**Comment by rawtaz** [comment]
@MichaelEischer Where in the code are you seeing AWS_SESSION_TOKEN? I see the two others you mentioned but not this one.

**Comment by MichaelEischer** [comment]
That environment variable is included via `credentials.EnvAWS` in this line:

https://github.com/restic/restic/blob/c898f7a6bfa8929b38868b028338281cc2229cb7/internal/backend/s3/s3.go#L55

I'm currently even wondering why we still use the `Static` credentials provider. Afaict `EnvAWS` is used whenever the Static provider has any configuration.
