### ISSUE TITLE
Backup: <index/xxxxxxxx> does not exist

### ISSUE THREAD

**Issue by jneuhauser** [restic/restic#2846]
Output of `restic version`
--------------------------
```
PS C:\restic> .\restic.exe version
restic 0.9.6 compiled with go1.13.4 on windows/amd64
```

How did you run restic exactly?
-------------------------------

`PS C:\restic> .\restic.exe -q -r rest:http://192.168.65.221:8000/win2k19-dc -p .\win2k19-dc.passwd backup D:\freigaben`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

```
root@debian-vmhost:~# rest-server version
rest-server 0.9.7 compiled with go1.10 on linux/amd64
```

Expected behavior
-----------------

Finish the backup successfully all the time.

Actual behavior
---------------

Sometimes the backup prints many of the following errors:
```
Load(<index/00266c2bad>, 0, 0) returned error, retrying after 969.531165ms: <index/00266c2bad> does not exist
Load(<index/00266c2bad>, 0, 0) returned error, retrying after 2.32966652s: <index/00266c2bad> does not exist
Load(<index/00266c2bad>, 0, 0) returned error, retrying after 2.01769041s: <index/00266c2bad> does not exist
```

And after some time the backup fails with:
```
Fatal: unable to load index 008087f8: <index/008087f800> does not exist
```

Steps to reproduce the behavior
-------------------------------

I don't know because it happens only sometimes.

Probably backup a folder with many sub folders and files on a windows machine to a rest server on linux.

Do you have any idea what may have caused this?
-----------------------------------------------

As i have such errors only on the windows machine, it's probably related to the os specific implementation.

Network error/timeout???

My windows machine is a virtual machine on a debian vm host which runs the rest server and there exists a dedicated virtual network between the vm host and the windows vm.

Do you have an idea how to solve the issue?
-------------------------------------------

I don't know. The error message is totally unclear to me.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is my favorite backup solution for all my server systems.

**Comment by MichaelEischer** [comment]
Hmm, the "does not exist" error is probably returned by the rest-server, so the restic run on windows is just the bearer of bad news. How do you trigger/start the restic runs? Is that Windows VM the only user of the repository or is it shared with other hosts? If you use scripts, are there any calls to `unlock`? Do you run `prune` from time to time on that repository?

**Comment by jneuhauser** [comment]
> How do you trigger/start the restic runs?

I'm runing restic with a powershell script that is executed as SYSTEM by a scheduled task.

> Is that Windows VM the only user of the repository or is it shared with other hosts?

Yes, every host or vm has it's own repo on the same server.

> If you use scripts, are there any calls to unlock?

I haven't used `unlock` in any script, only `snapshots`, `init` and `backup`.

> Do you run prune from time to time on that repository?

Only manually after i called `forget`. But this happened on this repo only one times...

I'll try to backup over ssh and see if this issues still exists. Probably this is related to **rest-server** instead of restic itself.

**Comment by MichaelEischer** [comment]
> I'll try to backup over ssh and see if this issues still exists. Probably this is related to rest-server instead of restic itself.

The error looks like the rest-server returned a list of indexes which contains filename which don't actually exit. I've no clue how that's supposed to happen, unless these indexes were deleted concurrently. But that could only happen by a concurrent prune or rebuild-index run.

**Comment by jneuhauser** [comment]
Problem solved... 

> The error looks like the rest-server returned a list of indexes which contains filename which don't actually exit.

This was really the case.

The power supply of the backup hard disk was defective and has caused defects in the file system through sporadic failures.
I think since the backup from the windows system was a multiple of the backup from the other systems, the error was only found here.

Many thanks for your thought and for this awesome project.
