### ISSUE TITLE
restic stats latest --tag

### ISSUE THREAD

**Issue by ederator** [restic/restic#2858]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

With restic stats latest there is the possibility to filter on --host. But there is no possibility to filter on --tag. This makes it difficult if different backups are in the same repo and you want to check the backups automatically using stats latest.

With restic snapshots latest you have the possibility to filter on --tag so I would like to have it also with restic stats.

Would be cool if someone could integrate --tag into restic stats :)

What are you trying to do?
--------------------------

I am trying to provide metics for prometheus using restic stats and restic snapshots as described in https://forum.restic.net/t/restic-grafana-dashboard/1662.

**Comment by buschjost** [comment]
I'll prepare a PR for this.
