### ISSUE TITLE
diff command: allow specifying root paths

### ISSUE THREAD

**Issue by wojas** [restic/restic#2872]
Output of `restic version`
--------------------------

v0.9.6-337-g0b21ec44-dirty

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Allow specifying a root path for both snapshots in the `diff` command.

This would allow a user to:

- Compare a specific subpath between two snapshots made of different roots (e.g. snapshots of `~` and `~/Pictures`)
- Compare a subpath that was moved between snapshots
- Only compare a subset of two snapshots

PR coming up.

What are you trying to do?
--------------------------

Compare the same data in two snapshots where the root paths differ.

**Comment by MichaelEischer** [comment]
As commented in #2873, I think we should use the syntax suggested in https://github.com/restic/restic/issues/3871 instead.
