### ISSUE TITLE
Pack(File) or DataFile?

### ISSUE THREAD

**Issue by aawsome** [restic/restic#2877]
What are you trying to do?
--------------------------

When working on implementations, I always get a bit confused whether to use the name "pack"/"pack file" or "data file".

In the users documentation part "Terminology", it is referred as "Packs", but the dir in the repository layout is `/data`.

Also, in the implementations, the constant is called `DataFile` which may be mixed up with `DataBlob` but I've seen may places where variables/comments or user outputs refer to "packs".

I suggest to:

- change `DataFile` into `PackFile`
- look for "data file" et al in code/comments and change if necessary
- add an explanation in `resign.rst` that packs are stored under `/data` for historic reasons

Is this a common view? I can prepare an PR if we agree that this clarifies things.

**Comment by greatroar** [comment]
I've noticed the inconsistency too and I'd welcome a patch that fixes it. Given that packs/data files can store data blobs and/or tree blobs, I think pack files is a better name.

>  an explanation in resign.rst that packs are stored under /data for historic reasons

I'm not sure if that is needed, though. Expressing regret over a naming convention in the docs doesn't really help anyone, if it's not extremely confusing.

**Comment by aawsome** [comment]
I hope I hit ever place in #2885
