### ISSUE TITLE
Add aliases for backups

### ISSUE THREAD

**Issue by saschalalala** [restic/restic#288]
Hey, I saw you at the Froscon and I really like restic. I played around with it a little bit and I have an idea for an improvement. I would love to be able to store different backups in a config file so that I could just run something like
`restic backup foo`
and restic knows that this backup "foo" has a source dir and a destination dir (that could be stored in a json config file in ~/config/restic or something). This would be nice for some different backups that always have the same options, such as: "backup ~/devel to my external harddrive" or "backup ~/Documents to my server" and so on. Of course, I could write bash scripts to do that kind of thing, but integrating it into restic directly would be nice, I guess.

Connect #16

**Comment by fd0** [comment]
Thanks for your comment! This is very similar to #16 and will probably be implemented at some point.

**Comment by fd0** [comment]
This issue will be resolved when we add a config file, that's #16. 
I'm going to close this issue for now, please feel free to add further comments. Thanks!
