### ISSUE TITLE
Full check with checksums?

### ISSUE THREAD

**Issue by JsBergbau** [restic/restic#2888]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

restic check should not only check if all files exist, but also do a checksum / crc check of files content. 

What are you trying to do?
--------------------------

Trying to verify if all the files are really intact or if they've been changed because of RAM errors, HDD errors or stuff like that.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yeah, restic does a very good job in backup data. Its a good feeling to know your data is safely backuped

**Comment by rawtaz** [comment]
`restic check --read-data` does what you want.
