### ISSUE TITLE
find doesn't seem to work or I am doing it wrong

### ISSUE THREAD

**Issue by saschalalala** [restic/restic#289]
I created a test backup repo and backuped some files and snapshots. I tried finding a file by doing the following
`/tmp/restic_bin -r /tmp/backup find settings.html`
and after entering my password it says
`id f3a29ce51d511cfd27d30d3d711b753b2b5f719f9e7636a0285d5ca9a0230ac0 not found in index`
but the file exists, I checked it using 
`find ./ -name "settings.html"` in the fuse mounted directory. Am I missing something or is find not completely implemented at the moment? It's also not documented on https://restic.github.io/manual.html

**Comment by fd0** [comment]
Thanks for raising this issue, this is indeed a bug.

**Comment by fd0** [comment]
This is fixed in #290, thanks for reporting!
