### ISSUE TITLE
Possible restore output information

### ISSUE THREAD

**Issue by martijnderidder** [restic/restic#2891]
Is it possible to show information about the restore information? When we are restoring data, we dont know how long it will take.

Is it somehow possible to create some console output that refreshed every x seconds? Something like this:

```
Directory size: 115GB
|######--------------------------------------------------------------------|
Already downloaded: 8,9GB | Estimated time: 03:14:59
```

**Comment by rawtaz** [comment]
@martijnderidder Thanks for your question, but please post it in [the restic forum](https://forum.restic.net/) as requested by the issue template you were presented with when opening this issue (usage question). Cheers!
