### ISSUE TITLE
Avoid credential leak from environment or command-line

### ISSUE THREAD

**Issue by mtdcr** [restic/restic#2900]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When running restic in an insecure environment, e.g. on a webserver executing php scripts, it would be preferrable if restic wouldn't risk exposing its repository string to other processes.

To avoid that in a portable way, it is my understanding that the repository string needs to be read from a file. In the absence of a configuration file, it would be possible to introduce a special URL scheme like `-r file:///dev/stdin` or add a new command-line option, like it was done with `--password-file` or `--password-command`.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I'd like to hide passwords exposed on the command-line or through $RESTIC_REPOSITORY.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I really like restic and am already using it on a lot of machines. I couldn't replace all older backup solutions yet, but I hope to be able to do so. Thank you all for your work so far!

**Comment by rawtaz** [comment]
I'm sorry, but can you elaborate on how the environment variables `RESTIC_REPOSITORY` and `RESTIC_PASSWORD` doesn't solve the problem of not having to expose the repository URI and/or the password on the command line?

**Comment by mtdcr** [comment]
It's not about the restic password, because there's already a --password-file option.

Using environment variables for credentials is bad practice, because they may leak to child processes. It's possible that restic doesn't invoke any child processes, or, in case it does, that it cleans up its environment before executing a child process. However, I did not read the source code of restic and its dependencies, and I think most people won't.

Setting an environment variable in a crontab will leak it to all cron jobs, depending on the implementation.

Setting an environment variable on a command-line may or may not leak to other processes, depending on which program interprets the command-line, e.g. a shell or a process manager.

Environment variables may end up in log files stored with insecure permissions.

There are many workarounds to avoid all this stuff, but the easiest one is to not put credentials into the environment at all. The most sane way seems to be using a file. I just assumed that's the reason why --password-file exists in the first place, which https://github.com/restic/restic/issues/278 seems to confirm.

**Comment by rawtaz** [comment]
I see. Personally I like the `-r file:///dev/stdin` suggestion, in particular because it utilizes the already existing `-r` option instead of adding Yet Another Flag.

**Comment by mtdcr** [comment]
Sorry, I just noticed this duplicates https://github.com/restic/restic/issues/1458. But it looks like @pmkane abandoned his idea of sending a PR.

**Comment by pmkane** [comment]
@mtdcr -- all yours if you want it, I got dragged onto other stuff and never came back to this.

**Comment by rawtaz** [comment]
We've discussed this and feel that the `--repository-file` option is preferrable, along with the corresponding `REPOSITORY_FILE` environment variable. We'll skip the `-r file://...` syntax and go for just the option and env var. If anyone is up for a PR, go for it :)

**Comment by mtdcr** [comment]
I gave it a try at https://github.com/mtdcr/restic/tree/repository-file, but couldn't test it yet. Please ping me, if you don't hear from me within a week.

**Comment by rawtaz** [comment]
@mtdcr That's cool, but can you please open a pull request here in this repository (referencing this issue)? It makes it much easier to work with your contribution and comment on it, etc.

**Comment by aawsome** [comment]
While I agree that reading the repository from a file solves this specific security problem, I also must state that solving #16 would allow an easy workaround for this and maybe other future security issues... :wink:

**Comment by rawtaz** [comment]
Yes, we know. But that will not happen right now, but if someone writes a PR for this issue that could happen, which would be better than nothing I suppose.

**Comment by mtdcr** [comment]
> @mtdcr That's cool, but can you please open a pull request here in this repository (referencing this issue)? It makes it much easier to work with your contribution and comment on it, etc.

Sure. I just wanted to test it first. Will send a PR in a minute.
