### ISSUE TITLE
restore: Support options to improve file overwrite/selection behavior

### ISSUE THREAD

**Issue by systemmonkey42** [restic/restic#2901]
Output of `restic version`
--------------------------

**restic 0.9.6 compiled with go1.13.4 on linux/amd64**

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Provide options to control file overwriting behaviour/policy.

Suggestions include:

* --overwrite  / --no-overwrite
* --ignore-existing / --skip-existing
* --update-existing
* --overwrite-if-newer
* --overwrite-if-older

What are you trying to do? What problem would this solve?
-------------------------------------------------------
During a restore, its difficult to restore only files which are missing, or restore only files where the backup is newer/older than the existing disk contents.

I am currently restoring a directory with 300k files, and the only way to do this is seems to require restoring all the files into a new location and use a tool like 'rsync' to merge the differences.
The total restore is about 3TB.  Finding a free 3TB to restore the files, then attempting to merge them manually is a daunting task.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
always

**Comment by rawtaz** [comment]
More or less a duplicate of #2662. Using the mount command is an option that might be useful to you, but perhaps you already tried or considered that?

**Comment by systemmonkey42** [comment]
Sorry, I missed searching for "changed" when checking for duplicates.

**Comment by rawtaz** [comment]
No problem! But have you tried using the mount command? If you do, I suggest using the [latest master build](https://beta.restic.net/?sort=time&order=desc) as I think it contains a few improvements/optimizations to the mount command.

**Comment by systemmonkey42** [comment]
I have tried using the mount command before, but it didn't feel stable with a slow backend (remote host).  I've give the master build a go.

Mount and rsync would be the answer.   Thanks, and sorry for the duplicate.
