### ISSUE TITLE
Wasabi object storage support

### ISSUE THREAD

**Issue by bscott** [restic/restic#2903]
A simple request for Wasabi object Storage support as a backend. https://wasabi.com

Output of `restic version`
--------------------------

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by rawtaz** [comment]
@bscott You can already use Wasabi in restic, please see https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#wasabi . If you for some reason experience that this isn't working, please make sure that you use the latest version of restic (0.9.6) or [the latest master build](https://beta.restic.net/?sort=time&order=desc).

**Comment by bscott** [comment]
Got it, just realized that yesterday Thanks

**Comment by rawtaz** [comment]
No problem! Glad it works for you :)
