### ISSUE TITLE
show snapshots in datetime-tree in fuse-mount

### ISSUE THREAD

**Issue by bAndie91** [restic/restic#2907]
Output of `restic version`
--------------------------

`restic 0.9.6 (v0.9.6-0-gb723ca3) compiled with go1.13.8 on linux/386`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Restic should either represent the snapshots in a directory tree with date and time as separate path elements or show tags with slash as subdirectories under tags directory in fuse mount.
By separate date and time path elements I mean eg. `snapshots-by-date/2020/08/31/08/15` for a snapshot which was created at 2020-08-31 08:15:ss. It may be configured, because everyone has different snapshotting frequency: who does snapshots hourly he may want this 5 level depth, who does it daily he may want only 3 levels, etc. The last directory (before the snapshot's content) can be the snapshot ID to distinguish snapshots with the same date/time up to the indicated precision: `snapshots-by-date/2020/08/31/SNAPSHOTID/home/joe/backup/...`. 
But IMO it'd be easier to show tags with slash in their name as directory structure. Currently tags with slash are not shown in fuse mount. In this way users could organize huge number of snapshots simply by tags.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I have many snapshots (eg. for every hour in every day kept for years) and directory listing in fuse mount loads slowly and navigating through it by file managers are also challenging. I like to have directory structure which I can browse easier, ie. less entries per directory. IMO restic should show tags in dir structure (eg. `tags/2020/aug-31/...` for tag `"2020/aug-31"`) in fuse mount.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

yes, absolutely, i can not emphasize more.

**Comment by rawtaz** [comment]
I've thought about having a date path too, it would be very useful and effective. I think it should start with `/dates/..` though to keep it consistent with the other directory names though (tags, hosts, snapshots, etc).

**Comment by aawsome** [comment]
One reason of `restic mount` being slow on showing snapshots might be that restic always needs to read *all* snapshot files. A different directory structure would not solve this problem.

About the directory structure:
Actually there is already `--snapshot-template` which allows to specify how snapshots are listed under `/snapshots/`. It has the same problem as tags with slashes: It doesn't work (and here also prints an error message). So I would propose to change `mount` such that slashes in names (tags and in `--snapshot-template`) simply work. 
I can work on a PR if we agree that this is the way to go..

**Comment by aawsome** [comment]
I realized that implementing this also allows a lot of simplifications on the fuse code. The current state is in a draft PR now. I'll refine this and add the missing latest link soon...

**Comment by aawsome** [comment]
PR #2913 is now in a state that it can be tested.

@bAndie91 Your requirements can be fulfilled using #2913 with 
```
--dir-template "snapshots-by-date/%T" --time-template "2006/01/02/15/04"
```
and 
```
--dir-template "snapshots-by-date/%T/%i" --time-template "2006/01/02"
```

Looking forward to getting feedback!

**Comment by bAndie91** [comment]
does it reduce the load time?

**Comment by bAndie91** [comment]
```
$ restic version
restic 0.9.6 (v0.9.6-0-gb723ca3) compiled with go1.13.8 on linux/386
$ time ls ~/mnt/restic/snapshots/
real 254.645    user 0.204      sys 0.268       cpu 0.18%
$ time ls ~/mnt/restic/snapshots/
real 268.972    user 0.232      sys 0.404       cpu 0.23%

$ restic version
restic 0.9.6 (v0.9.6-395-gc670046) compiled with go1.13.8 on linux/386
$ restic mount ~/mnt/restic/ --path-template snapshots/%T --time-template 2006/01/02 &
$ time ls ~/mnt/restic/snapshots/
real 0.134      user 0.000      sys 0.000       cpu 0.00%
$ time ls ~/mnt/restic/snapshots/
real 0.072      user 0.004      sys 0.000       cpu 5.56%
$ time find ~/mnt/restic/snapshots/ -mindepth 3 -maxdepth 3
real 4.604      user 0.044      sys 0.148       cpu 4.17%
$ time find ~/mnt/restic/snapshots/ -mindepth 3 -maxdepth 3
real 2.556      user 0.056      sys 0.172       cpu 8.92%
```

it is faster. excellent work. thanks. 

when will it be stable? when a version tag is added?

**Comment by bAndie91** [comment]
i haven't found docs on the macros but found `"%i", "%I", "%u", "%h", "%t", "%T"` in the code for short and long snapshot IDs, username, hostname, tag, and time respectively.

**Comment by bAndie91** [comment]
(ok it's in  #2913 's description)

**Comment by aawsome** [comment]
Thanks for trying out #2913 @bAndie91 :+1: 

About your measurements: It seems to me you compared #2913 (on top of the current master branch) with version 0.9.6. Since version 0.9.6. there has been quite some improvements to the FUSE mount which already made it into master. I think the improved speed is mainly due to these changes.

To get #2913 stable, it must be reviewed by a project maintainer and get merged into the master branch first.
Then it will be included in the next release to come after the merge.

So I would advise you to leave this issue open until #2913 is merged. (Usually the issues are closed by maintainers during the merge)
