### ISSUE TITLE
Building issue on Fedora bazil.org/fuse".AllowRoot

### ISSUE THREAD

**Issue by copart** [restic/restic#2908]
Build command is long, but this is how rpm does it:
`/usr/lib/golang/pkg/tool/linux_amd64/compile -o $WORK/b001/_pkg_.a -trimpath "$WORK/b001=>" -shared -p main -complete -installsuffix shared -buildid m_yMPH6vwMA6DHUTghoY/m_yMPH6vwMA6DHUTghoY -goversion go1.15 -D "" -importcfg $WORK/b001/importcfg -pack ./acl.go ./cleanup.go ./cmd_backup.go ./cmd_cache.go ./cmd_cat.go ./cmd_check.go ./cmd_diff.go ./cmd_dump.go ./cmd_find.go ./cmd_forget.go ./cmd_generate.go ./cmd_init.go ./cmd_key.go ./cmd_list.go ./cmd_ls.go ./cmd_migrate.go ./cmd_mount.go ./cmd_options.go ./cmd_prune.go ./cmd_rebuild_index.go ./cmd_recover.go ./cmd_restore.go ./cmd_self_update.go ./cmd_snapshots.go ./cmd_stats.go ./cmd_tag.go ./cmd_unlock.go ./cmd_version.go ./doc.go ./exclude.go ./find.go ./format.go ./global.go ./global_release.go ./lock.go ./main.go
 github.com/restic/restic/cmd/restic`

This is the error:
`_build/src/github.com/restic/restic/cmd/restic/cmd_mount.go:118:39: undefined: "bazil.org/fuse".AllowRoot`

Do you have any idea what may have caused this?
-----------------------------------------------
No, however, I did notice that Fedora is trying to use as the bazil dependency:
`golang-bazil-fuse-devel                                                   noarch               0-0.15.20200722gitfb710f7.fc33`

Do you have an idea how to solve the issue?
-------------------------------------------
It looks like this is fixed in master, https://github.com/restic/restic/pull/2652. So the question is, can this patch be back ported to 0.9.6 safely

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Always makes me happy :)

Other info
------------------------------------------------------------
I am the maintainer of restic on Fedora

**Comment by rawtaz** [comment]
Please edit your post so it's clear exactly what commands you ran to build this, and please also wrap the commands and output in code blocks (see toolbar in message editor).

**Comment by copart** [comment]
Cleaned it up a lot, sorry about the formatting. It was really bad.

**Comment by rawtaz** [comment]
I'm sorry, but this is something you'll have to ask the package maintainer for that RPM/distribution. We don't maintain the packages out there, so how they build and not on different distributions is something they have to deal with. The restic source code should build properly including the dependencies as they are versioned, so I'm surprised it doesn't in this case.

**Comment by MichaelEischer** [comment]
@copart I see you have already backported the PR. The changes in the PR are simple enough to work without problems (it's mostly just removing an optional function call). 

The way I understand https://src.fedoraproject.org/rpms/restic/blob/master/f/restic.spec#_37 , it simply uses the latest version of each dependency?

**Comment by MichaelEischer** [comment]
@copart Is there anything left to do for this issue, or can we close it?

**Comment by MichaelEischer** [comment]
Closing this issue as apparently the problem was resolved and the outdated dependencies shouldn't be problem with restic 0.10.0
