### ISSUE TITLE
go run build.go - ERROR

### ISSUE THREAD

**Issue by hzensne1** [restic/restic#291]
Hi Alexander,

Tried to install restic on another machine, but got an error:
This was the sequence:
# git clone https://github.com/restic/restic
# go run build.go
/tmp/restic-build-588141355/src/github.com/pkg/sftp/client.go:5:2: no Go source files in /usr/lib/go/src/pkg/encoding
build failed: exit status 1
exit status 1

What could be the issue there?
Thanks.

**Comment by fd0** [comment]
Hi, thanks for reporting the issue.

Your installation of Go is broken, `$GOROOT` is set to a directory that does not contain an installation of Go. Have a look at the output of `go env`, and especially the directory `GOROOT` points to.

**Comment by fd0** [comment]
Did you get it working?

**Comment by hzensne1** [comment]
Hi,
I will try this afternoon when I can access the machine again. Anyhow I can already tell that non of the scenarios you mentioned applies to my issue. I have installed go via aptitude only. 
But I had a look at the available deb packages yesterday and it seems that there are less available for arm and amd64 platforms than for the i686 ones. My laptop is i686 and runs restic perfectly. So I decided to have restic on my cubieboard also (which is arm architecture) but this caused the error that I described. Then I found out that arm and amd64 platforms have less golang-* packages. Does this ring a bell?
Thanks.

**Comment by fd0** [comment]
Interesting, which version of Go did you install via aptitude?

The source of the problem is that the `go` tool is unable to find the `encoding` library, which is part of the standard library and should be installed with every Go environment. That's why I'm sure that it's not a problem with restic (and therefore closed this issue).

Have a look whether `/usr/lib/go/src/pkg/encoding` exists and the package `golang-src` is installed.

**Comment by hzensne1** [comment]
You are absolutely right. It seems not to be a restic problem and this ticket can be kept closed. I can not remember from the top of my head which version of go aptitude has installed. I will follow your hint tonight and check for the golang-src. I will keep you posted if you like.

**Comment by fd0** [comment]
Please do so! Maybe it helps others having the same problem to read through this issue later...

**Comment by tgulacsi** [comment]
```
go get -u github.com/restic/restic
cd $GOPATH/src/github.com/restic/restic
go run build.go
```

golang in Ubuntu 15.04 is just 1.3.3 - too old.
I'm using the golang.org official builds from https://golang.org/dl/ following https://golang.org/doc/install .

**Comment by fd0** [comment]
@tgulacsi Go 1.3 is officially supported and restic works with that version, even the integration tests are run (among others) on Go 1.3. The problem described in this issue is caused by an incomplete Go installation, not a too-old Go version.

**Comment by hzensne1** [comment]
@tgulacsi,

Thanks for stepping in and trying to help. I have your command line and got the following:
           
go get -u github.com/restic/restic
github.com/restic/chunker 
/usr/lib/go/src/pkg/github.com/restic/chunker/chunker.go:30: undefined: sync.Pool 
github.com/restic/restic/backend 
/usr/lib/go/src/pkg/github.com/restic/restic/backend/generic.go:19: undefined: sha256.Sum256
golang.org/x/crypto/poly1305
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:27 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:30 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:35 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:61 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:73 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:75 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:81 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:82 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:82 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:82 syntax error, last name: g
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:82 syntax error, last name: g
too many errors

**Comment by hzensne1** [comment]
@fd,
First thanks for your patience so far. I have gone through your questions and want to provide the output in this post. So it will become quite a large post unfortunately. The most important information first, for those who follow this thread: I could not get it working.

1. echo $GOROOT was empty

2. go env provided the following:
GOROOT="/usr/lib/go"
GOBIN=""
GOARCH="arm"
GOCHAR="5"
GOOS="linux"
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_arm"
GOGCCFLAGS="-g -O2 -fPIC"
CGO_ENABLED="0"

3. I have checked the path /usr/lib/go/src/pkg/encoding. It had content in there.
ascii85  asn1  base32  base64  binary  csv  gob  hex  json  pem  xml
Anyhow I have forced reinstall golang-src from the Debian wheezy repositories (System is arm-wheezy, too). This is the version by the way: golang-src (2:1.0.2-1.1)

4. I did set GOROOT=/usr/lib/go
root@cubie:~ export GOROOT
Then ran:
root@cubie:~/restic# go run build.go
/tmp/restic-build-878263641/src/github.com/pkg/sftp/client.go:5:2: no Go 
source files in /usr/lib/go/src/pkg/encoding
build failed: exit status 1
exit status 1

5. Ok, next steps is something you shouldn't be doing under any circumstances. Just typing in something that you do not know what it does. But that was the only thing I found by googling around:

root@cubie:~/restic# go get code.google.com/p/go.text/encoding
package code.google.com/p/go.text/encoding: Get 
https://code.google.com/p/go/source/checkout?repo=text: x509: certificate 
signed by unknown authority
root@cubie:~/restic# go run build.go
/tmp/restic-build-680307505/src/github.com/pkg/sftp/client.go:5:2: no Go 
source files in /usr/lib/go/src/pkg/encoding
/usr/lib/go/src/pkg/github.com/restic/restic/backend/s3/s3.go:11:2: import 
"gopkg.in/amz.v3/aws": cannot find package
/usr/lib/go/src/pkg/github.com/restic/restic/backend/s3/s3.go:12:2: import 
"gopkg.in/amz.v3/s3": cannot find package
build failed: exit status 1
exit status 1
root@cubie:~/restic# go get code.google.com/p/go.text/...
package code.google.com/p/go.text/...: Get 
https://code.google.com/p/go/source/checkout?repo=text: x509: certificate 
signed by unknown authority
root@cubie:~/restic# go run build.go
/tmp/restic-build-789711532/src/github.com/pkg/sftp/client.go:5:2: no Go 
source files in /usr/lib/go/src/pkg/encoding
/usr/lib/go/src/pkg/github.com/restic/restic/backend/s3/s3.go:11:2: import 
"gopkg.in/amz.v3/aws": cannot find package
/usr/lib/go/src/pkg/github.com/restic/restic/backend/s3/s3.go:12:2: import 
"gopkg.in/amz.v3/s3": cannot find package
build failed: exit status 1
exit status 1

Again thanks. Now for reading through this long post. Does all this make sense to anybody? Obviously go is installed properly with all required packages but I could not get restic to run on platforms like arm or amd.

Any help is highly appreciated.

**Comment by tgulacsi** [comment]
Do NOT eet GOROOT!

By the way I think sync.Pool was introduced in Go 1.4, so 1.3 is too old.
2015. szept. 1. de. 7:16 ezt írta ("hzensne1" <notifications@github.com>):

**Comment by tgulacsi** [comment]
I was wrong. 1.3 has symc.Pool.
Please remove go from your computer entirelly, then install go1.5 from the
binary distribution from golang.org.
2015. szept. 1. de. 7:23 ezt írta (gthomas@gthomas.eu):

**Comment by fd0** [comment]
@hzensne1 Your version of Go is tool old (1.0.2), restic needs at least Go 1.3.

**Comment by hzensne1** [comment]
@Those who follow this post:

I have purged golang 1.02 from my system in question and installed golang 1.3.3 from wheezy-backports which succeeded at least according to the messages from aptitude.

golang-src (2:1.3.3-1~bpo70+1) wird eingerichtet ...
golang-go-linux-arm (2:1.3.3-1~bpo70+1) wird eingerichtet ...
golang-go (2:1.3.3-1~bpo70+1) wird eingerichtet ...
golang-doc (2:1.3.3-1~bpo70+1) wird eingerichtet ...
golang (2:1.3.3-1~bpo70+1) wird eingerichtet ...

Anyhow I could not manage to compile restic. This is the error message I got:
                                                    
root@cubie:~# cd restic
root@cubie:~/restic# go run build.go
/usr/lib/go/src/pkg/github.com/restic/restic/backend/s3/s3.go:11:2: cannot find 
package "gopkg.in/amz.v3/aws" in any of:
        /usr/lib/go/src/pkg/gopkg.in/amz.v3/aws (from $GOROOT)
        /tmp/restic-build-731192434/src/gopkg.in/amz.v3/aws (from $GOPATH)
/usr/lib/go/src/pkg/github.com/restic/restic/backend/s3/s3.go:12:2: cannot find 
package "gopkg.in/amz.v3/s3" in any of:
        /usr/lib/go/src/pkg/gopkg.in/amz.v3/s3 (from $GOROOT)
        /tmp/restic-build-731192434/src/gopkg.in/amz.v3/s3 (from $GOPATH)
build failed: exit status 1
exit status 1

What I am planning to do next is:
Manually identify all files belonging to golang 1.0.2, delete those manually, purge golang 1.3.3 via aptitude. Manually identify all files belonging to golang 1.3.3 and delete those if there are still some in the system. Reinstall golang 1.3.3 again via aptitude from the wheezy-backport repositories.

**Comment by tgulacsi** [comment]
Please don't repeat your previous errors:
1. use "go get" to download restic and all its dependencies!
2. don't set GOROOT
3. please provide us the result of "go version" and "go env".

---
https://onename.com/tgulacsi

2015-09-02 8:24 GMT+02:00 hzensne1 <notifications@github.com>:

**Comment by fw42** [comment]
Feel free to drop by in #restic in the freenode IRC network if you want some live debugging help

**Comment by hzensne1** [comment]
Please stand-by as I can only access the machine in the evening hours to try the next steps.
Thanks.

**Comment by hzensne1** [comment]
Hi,
ok, go version returns:
go version go1.3.3 linux/arm

go env returns:
GOARCH="arm"
GOBIN=""
GOCHAR="5"
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_arm"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

When I try the command:
go get -u github.com/restic/restic
it is complaining:
/usr/lib/go/src/pkg/golang.org/x/crypto/poly1305/poly1305_arm.s:149 syntax error, last name: R9
every five lines or so until it stops with "too many errors"

I dont even get to the point to compile restic. Does anybody have any clew what this could mean?

Thanks

**Comment by tgulacsi** [comment]
Yup, 1.3 is too old for golang.org/x/crypto/poly1305, or so, but the best
would be to ask this on golang-nuts mailing list.

---
https://onename.com/tgulacsi

2015-09-02 17:43 GMT+02:00 hzensne1 <notifications@github.com>:

**Comment by hzensne1** [comment]
Thanks. But this is somewhat strange. Looking at my laptop (which is not troubling with restic says: go version go1.3.3 linux/amd64)

My Cubieboard has the same go version and makes that trouble (cubie is arm architecture). Could it be that the package maintainer did something strange to the go installation?

**Comment by tgulacsi** [comment]
That's why I suggest the golang-nuts list: Dave Cheney is the main arm
maintainer/tester, and he will be able to spot the problem, I'm sure.

Now I understand why don't you use the official binary, and use that
outdated package: no official binary exists.

But: http://denis.papathanasiou.org/posts/2015.08.30.post.html
or https://github.com/golang/go/wiki/GoArm
and http://dave.cheney.net/unofficial-arm-tarballs


---
https://onename.com/tgulacsi

2015-09-02 18:15 GMT+02:00 hzensne1 <notifications@github.com>:

**Comment by hzensne1** [comment]
I followed your first link and at least my system tells me I have: go version go1.5 linux/arm
But when compiling restic it throws even more errors now than before.
I will try the Cheney approach next. Thanks.

**Comment by hzensne1** [comment]
Hi all,
before I do a final wrap-up let me thank everybody here for the great help and patience. I very much appreciate the efforts you have all put in this topic.

What I describe now applies to Debian only. To recap: Installing golang was my problem here, not restic.

restic compiles fine with jessie on ix86 architecture when installing golang from the standard repositories.
Same applies to wheezy on amd64 when you install golang from the wheezy-backports.
In both cases Debian installs go version 1.3.3

What I could not get working was to have golang package installed on wheezy on arm architecture.

What I wanted to achieve:
Backing up data from Source (Cubieboard, wheezy, arm) to Destination (Standard-PC, wheezy, amd64) by nfs mounting Destination on Source. restic should run on Source.

My workaround:
I switched Source and Destination. So I now back up data to Destination (Standard-PC, wheezy, amd64) from Source (Cubieboard, wheezy, arm) to by nfs mounting Source on Destination. Restic runs on Destination now.

Thanks again to everybody.

**Comment by fd0** [comment]
Hey, thanks for leaving a comment describing your problem and your solution! This way, people can follow your process when they have the same problem on arm :)
