### ISSUE TITLE
"All rights reserved" in License

### ISSUE THREAD

**Issue by qlcom** [restic/restic#2911]
do you really want that?
where did you get that license text?

BSD 2-clause license doesn't have that sentence. https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_(%22Simplified_BSD_License%22_or_%22FreeBSD_License%22)

thanks.

**Comment by MichaelEischer** [comment]
The license text is probably from here: https://choosealicense.com/licenses/bsd-2-clause/ . You basically get that version if you remove the third clause from the BSD 3-clause license.

AFAICT it doesn't matters at all whether the "All rights reserved." line is part of the license or not.

**Comment by qlcom** [comment]
> AFAICT it doesn't matters at all whether the "All rights reserved." line is part of the license or not.

It does. Because it is in the license. No having that sentence makes the license better. only removing one clause from 3-clause license doesn't make it 2-clause license. you have to look at the history of 2-clause bsd license.

The bad thing is that Github has done this to a lot of projects.

**Comment by qlcom** [comment]
> AFAICT it doesn't matters at all whether the "All rights reserved." line is part of the license or not.

It does. Because it is in the license. No having that sentence makes the license better. only removing one clause from 3-clause license doesn't make it 2-clause license. you have to look at the history of 2-clause bsd license.

The bad thing is that Github has done this to a lot of projects.

**Comment by qlcom** [comment]
> AFAICT it doesn't matters at all whether the "All rights reserved." line is part of the license or not.

It does. Because it is in the license. No having that sentence makes the license better. only removing one clause from 3-clause license doesn't make it 2-clause license. you have to look at the history of 2-clause bsd license.

The bad thing is that Github has done this to a lot of projects.

**Comment by qlcom** [comment]
> Can you please explain to us non-lawyers

I am not a lawyer.

> I'm not sure why we're having a discussion.

read about 2-cluse bsd license on wikipedia. it don't contain that sentence.

**Comment by rawtaz** [comment]
@qlcom You are not answering the question. I understand that the 2-clause BSD license you reference does not contain the sentence in question. My question was not whether this is the case or not. My question was what your actual concern is, why do you think it is a problem that the LICENSE file in the restic repository contains that sentence? Again, what is the *actual problem* you are concerned about?

**Comment by qlcom** [comment]
because of that sentence the License isn't the 2-clause BSD License anymore as being used by projects that introduced it and using it. It has become a different license.

**Comment by rawtaz** [comment]
And how is that a problem. This is the third time I ask that.

Even if the copyright part contains the sentence in question, this doesn't change the rights that the rest of the license file gives. So again, how is it a *practical problem* that this sentence is present (or if you want to put ut this way, how is it a problem that the text in the LICENSE file differs slightly from the other one you reference)?

**Comment by SchnWalter** [comment]
> And how is that a problem.

@rawtaz, I think he's trying to state that by adding an extra phrase, you can no longer claim the project is licensed under the 2-Clause BSD License. You need to name it something else and you also can't use the same SPDX identifier (Software Package Data Exchange)

> https://spdx.org/licenses/

**Comment by qlcom** [comment]
SPDX and Github have done some serious bad things with BSD 2-clause license.

**Comment by MichaelEischer** [comment]
> Note, that enterprises (like GitHub's parent company: M$) rely on SPDX identifiers when they choose which software to use in their stack, so, having the wrong Identifier on a license can actually cause problems.

That is actually a _very strong_ argument for **leaving the license text exactly as it is** right now. The copyright line at https://spdx.org/licenses/BSD-2-Clause.html reads like this:

> Copyright (c) <year> <owner>. All rights reserved. 

> you have to look at the history of 2-clause bsd license.

Speaking of which we should take a quick look at the license text at https://web.archive.org/web/20170907193506/https://www.freebsd.org/copyright/freebsd-license.html . The `All rights reserved.` part still existed in 2017 and was removed some time afterwards. According to https://www.freebsd.org/internal/software-license.html:

> Historically, the phrase 'All Rights Reserved.' was included in all copyright notices. The BSD releases had it to comply with the Buenos Aires Convention of 1910 in the Americas. With the ratification of the Berne Convention in 2000, it became obsolete. As such, the FreeBSD project recommends that new code omit the phrase and encourages existing copyright holders to remove it. In 2018, the project updated its templates to remove it.

By the way the mentioned Wikipedia article was update on 16. December 2019 to also remove the "All rights reserved." line
So neither restic or Github use a "wrong" license text, it is simply a slightly older version, which according to FreeBSD is equivalent.

**Comment by rawtaz** [comment]
@SchnWalter We are already discussing it, if it turns out we need to change something we'll reopen it then.

The [GitHub Terms of Service](https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license) already make all contributions licensed the same way as the repository they end up in. There is no need for a CLA.

Regardless, the presence of the "All rights reserved" text right next to the copyright notice doesn't make the rest of the text any less valid than if this sentence didn't exist. The rest of the text gives rights to others, and these rights are still given. The two-clause license is still fully valid.

**Comment by MichaelEischer** [comment]
> The [GitHub Terms of Service](https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license) already make all contributions licensed the same way as the repository they end up in. There is no need for a CLA.

From what I can tell, that only applies for the current license of a repository. Changing the license of a project would still be a mess.

**Comment by rawtaz** [comment]
Sure, but that's not something we're going to do AFAIK.
