### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by ahmadyazdanii** [restic/restic#2912]
Output of `restic version`
--------------------------
```
restic version
restic 0.9.6 compiled with go1.12.12 on linux/amd64
```

How did you run restic exactly?
-------------------------------
`restic restore --target=file latest`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

> linux ubuntu20.04 amd64
> Minio Server [https://s3.ir-thr-at1.arvanstorage.com]

Expected behavior
-----------------

> restore my file ;)

Actual behavior
---------------
return this:
```
repository 2a489ff5 opened successfully, password is correct
restoring <Snapshot 1a96eacc of [/home/test/Desktop/project/test] at 2020-09-02 19:46:02.905062032 +0430 +0430 by test@test> to file
Load(<data/341a2a6e4a>, 37, 0) returned error, retrying after 395.311081ms: The request signature we calculated does not match the signature you provided. Check your key and signing method.
Load(<data/341a2a6e4a>, 37, 0) returned error, retrying after 867.919533ms: The request signature we calculated does not match the signature you provided. Check your key and signing method.
Load(<data/341a2a6e4a>, 37, 0) returned error, retrying after 786.239877ms: The request signature we calculated does not match the signature you provided. Check your key and signing method.
Load(<data/341a2a6e4a>, 37, 0) returned error, retrying after 1.973611906s: The request signature we calculated does not match the signature you provided. Check your key and signing method.
Load(<data/341a2a6e4a>, 37, 0) returned error, retrying after 2.72341156s: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Do you have any idea what may have caused this?
-----------------------------------------------

> i think related to https://github.com/minio/minio-go/issues/766 but i change my region and did not work again !

Do you have an idea how to solve the issue?
-------------------------------------------

> i connect to my provider for resolve this issue but i think this problem must be from restic and minio-go package 
> i can restore data from my service with 's3cmd' [https://github.com/s3tools/s3cmd] and in local i can use 'restic restore'
> 
> this problem occur again in remove data with this command:
> `restic forget --prune --keep-last 5`
> 
> and i think this occur for bad configuration of minio-go or s3 API in restic.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

> i try 2 month for resolve this issue but nothing .... please help me because restic is very good tools and i need it.

**Comment by MichaelEischer** [comment]
This looks similar to https://github.com/minio/minio/issues/7936 . Does the error still appear with a beta build of restic from https://beta.restic.net/?sort=time&order=desc ?

**Comment by ahmadyazdanii** [comment]
@MichaelEischer 
i try again with:
```
restic version
restic 0.9.6 (v0.9.6-377-gc34c7316) compiled with go1.14.3 on linux/amd64
```
but i have received:
```
Load(<data/120b8ac0fc>, 2406625, 2070512) returned error, retrying after 298.484759ms: The request signature we calculated does not match the signature you provided. Check your key and signing method.
Load(<data/ef276a33b0>, 3359202, 534087) returned error, retrying after 400.45593ms: The request signature we calculated does not match the signature you provided. Check your key and signing method.
Load(<data/5c53ec7358>, 4243839, 0) returned error, retrying after 507.606314ms: The request signature we calculated does not match the signature you provided. Check your key and signing method.
Load(<data/344a9e554a>, 1691457, 0) returned error, retrying after 656.819981ms: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Comment by MichaelEischer** [comment]
To debug this further, please use a debug build of restic, see https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs for the build instructions.

I'd assume that the http requests to minio should contain further clues on the problem. Before you post any parts of the debug log, make sure to mask private information in it (e.g. credentials, maybe repository names, etc.).

I just noticed something odd: According to your error logs, restic is able to successfully request a few files from the server (key / config / index files, otherwise restic wouldn't be able to request any data files) and only fails when loading some data files later on.

**Comment by MichaelEischer** [comment]
Closing this as the issue seems to originate from outside restic and we didn't get a reply with a month. Feel free to reopen this issue if you can provide further information.

**Comment by mghicas** [comment]
"$$" in the Minio secret key / AWS_SECRET_KEY casues this to fail as the shell takes the $$ and expands it:

AWS_SECRET_ACCESS_KEY="Backup123!@#$$$"

# env | grep AWS
AWS_SECRET_ACCESS_KEY=Backup123!@#88052$


hopefully this will help someone else.

**Comment by rawtaz** [comment]
@mghicas Can you please try making the `AWS_SECRET_ACCESS_KEY="Backup123!@#$$$"` line have single quotes instead, so `AWS_SECRET_ACCESS_KEY='Backup123!@#$$$'`? Does that work?
