### ISSUE TITLE
Allow changing repo password from file

### ISSUE THREAD

**Issue by count-null** [restic/restic#2915]
It would look something like this:

`key passwd --password-file /path/to/current-password.txt --new-password-file /path/to/new-password.txt`

The first file unlocks the repo (this currently works as expected) and the second file is used to set the new password.

I love how restic allows entering the password from file for scripting purposes. I'm working on a project which uses restic and it has a script called `chpasswd.sh` which changes the passwords for everything running on the system (linux user, mysql, etc.) would also be nice to change the restic password using this script without needing user input.

**Comment by andreaso** [comment]
Isn't this more or less exactly what restic already supports?

```
$ restic --repo /path/to/repo --password-file /path/to/current-password.txt key passwd --new-password-file /path/to/new-password.txt
```

**Comment by count-null** [comment]
You're correct! I didn't find anything like this in the docs so I assumed it had not been implemented. This is great thanks!
