### ISSUE TITLE
name collision for "rawdata", renaming to "rawdata-1"

### ISSUE THREAD

**Issue by pertoft** [restic/restic#2916]
Output of `restic version`
--------------------------
restic 0.8.3
compiled with go1.10 on linux/amd64
and
restic 0.9.6 compiled with go1.13.4 on darwin/amd64

How did you run restic exactly?
-------------------------------
`restic backup --files-from backupset.txt`

`splunk@splunk03:/pack/restic-s3-splunk-backup$ cat backupset-test.txt
/pack/splunk/var/lib/splunk/audit/colddb/db_1571223889_1571202293_252/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1479307937_1478588542_6/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1570831091_1570809496_246/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1560402345_1560380871_171/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1499438702_1499102886_31/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123/rawdata/`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Hitachi HCP S3

Expected behavior
-----------------
Files to be restored with their full path

Actual behavior
---------------
All paths are squashed 
`splunk@splunk03:/pack/restic-s3-splunk-backup$ restic ls bc5542f7
password is correct
snapshot bc5542f7 of [/pack/splunk/var/lib/splunk/audit/colddb/db_1479307937_1478588542_6/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1570831091_1570809496_246/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1560402345_1560380871_171/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1499438702_1499102886_31/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1571223889_1571202293_252/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123/rawdata] at 2020-09-09 08:26:18.139778761 +0200 CEST):
/rawdata
/rawdata/journal.gz
/rawdata/slicemin.dat
/rawdata/slicesv2.dat
/rawdata-1
/rawdata-1/journal.gz
/rawdata-1/slicemin.dat
/rawdata-1/slicesv2.dat
/rawdata-2
/rawdata-2/journal.gz
/rawdata-2/slicemin.dat
/rawdata-2/slicesv2.dat
/rawdata-3
/rawdata-3/journal.gz
/rawdata-3/slicemin.dat
/rawdata-3/slicesv2.dat
/rawdata-4
/rawdata-4/journal.gz
/rawdata-4/slicemin.dat
/rawdata-4/slicesv2.dat
/rawdata-5
/rawdata-5/journal.gz
/rawdata-5/slicemin.dat
/rawdata-5/slicesv2.dat
/rawdata-6
/rawdata-6/journal.gz
/rawdata-6/slicemin.dat
/rawdata-6/slicesv2.dat
/rawdata-7
/rawdata-7/journal.gz
/rawdata-7/slicemin.dat
/rawdata-7/slicesv2.dat
/rawdata-8
/rawdata-8/67227737
/rawdata-8/journal.gz
/rawdata-8/slicesv2.dat
/rawdata-9
/rawdata-9/journal.gz
/rawdata-9/slicemin.dat
/rawdata-9/slicesv2.dat`

Steps to reproduce the behavior
-------------------------------

`splunk@splunk03:/pack/restic-s3-splunk-backup$ restic backup --files-from backupset-test.txt
password is correct
using parent snapshot 5aff28be
scan [/pack/splunk/var/lib/splunk/audit/colddb/db_1571223889_1571202293_252/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1479307937_1478588542_6/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1570831091_1570809496_246/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1560402345_1560380871_171/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1499438702_1499102886_31/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230/rawdata /pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123/rawdata]
scanned 10 directories, 30 files in 0:00
/pack/splunk/var/lib/splunk/audit/colddb/db_1570831091_1570809496_246: name collision for "rawdata", renaming to "rawdata-1"
/pack/splunk/var/lib/splunk/audit/colddb/db_1560402345_1560380871_171: name collision for "rawdata", renaming to "rawdata-1"
/pack/splunk/var/lib/splunk/audit/colddb/db_1560402345_1560380871_171: name collision for "rawdata-1", renaming to "rawdata-2"
/pack/splunk/var/lib/splunk/audit/colddb/db_1499438702_1499102886_31: name collision for "rawdata", renaming to "rawdata-1"
/pack/splunk/var/lib/splunk/audit/colddb/db_1499438702_1499102886_31: name collision for "rawdata-1", renaming to "rawdata-2"
/pack/splunk/var/lib/splunk/audit/colddb/db_1499438702_1499102886_31: name collision for "rawdata-2", renaming to "rawdata-3"
/pack/splunk/var/lib/splunk/audit/colddb/db_1571223889_1571202293_252: name collision for "rawdata", renaming to "rawdata-1"
/pack/splunk/var/lib/splunk/audit/colddb/db_1571223889_1571202293_252: name collision for "rawdata-1", renaming to "rawdata-2"
/pack/splunk/var/lib/splunk/audit/colddb/db_1571223889_1571202293_252: name collision for "rawdata-2", renaming to "rawdata-3"
/pack/splunk/var/lib/splunk/audit/colddb/db_1571223889_1571202293_252: name collision for "rawdata-3", renaming to "rawdata-4"
/pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150: name collision for "rawdata", renaming to "rawdata-1"
/pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150: name collision for "rawdata-1", renaming to "rawdata-2"
/pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150: name collision for "rawdata-2", renaming to "rawdata-3"
/pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150: name collision for "rawdata-3", renaming to "rawdata-4"
/pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150: name collision for "rawdata-4", renaming to "rawdata-5"
/pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103: name collision for "rawdata", renaming to "rawdata-1"
/pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103: name collision for "rawdata-1", renaming to "rawdata-2"
/pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103: name collision for "rawdata-2", renaming to "rawdata-3"
/pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103: name collision for "rawdata-3", renaming to "rawdata-4"
/pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103: name collision for "rawdata-4", renaming to "rawdata-5"
/pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103: name collision for "rawdata-5", renaming to "rawdata-6"
/pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7: name collision for "rawdata", renaming to "rawdata-1"
/pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7: name collision for "rawdata-1", renaming to "rawdata-2"
/pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7: name collision for "rawdata-2", renaming to "rawdata-3"
/pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7: name collision for "rawdata-3", renaming to "rawdata-4"
/pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7: name collision for "rawdata-4", renaming to "rawdata-5"
/pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7: name collision for "rawdata-5", renaming to "rawdata-6"
/pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7: name collision for "rawdata-6", renaming to "rawdata-7"
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230: name collision for "rawdata", renaming to "rawdata-1"
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230: name collision for "rawdata-1", renaming to "rawdata-2"
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230: name collision for "rawdata-2", renaming to "rawdata-3"
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230: name collision for "rawdata-3", renaming to "rawdata-4"
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230: name collision for "rawdata-4", renaming to "rawdata-5"
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230: name collision for "rawdata-5", renaming to "rawdata-6"
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230: name collision for "rawdata-6", renaming to "rawdata-7"
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230: name collision for "rawdata-7", renaming to "rawdata-8"
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123: name collision for "rawdata", renaming to "rawdata-1"
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123: name collision for "rawdata-1", renaming to "rawdata-2"
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123: name collision for "rawdata-2", renaming to "rawdata-3"
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123: name collision for "rawdata-3", renaming to "rawdata-4"
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123: name collision for "rawdata-4", renaming to "rawdata-5"
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123: name collision for "rawdata-5", renaming to "rawdata-6"
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123: name collision for "rawdata-6", renaming to "rawdata-7"
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123: name collision for "rawdata-7", renaming to "rawdata-8"
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123: name collision for "rawdata-8", renaming to "rawdata-9"
[0:02] 100.00%  238.738 MiB / 238.738 MiB  40 / 40 items  0 errors  ETA 0:00
duration: 0:02
snapshot bc5542f7 saved`

`splunk@splunk03:/pack/restic-s3-splunk-backup$ cat backupset-test.txt
/pack/splunk/var/lib/splunk/audit/colddb/db_1571223889_1571202293_252/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1479307937_1478588542_6/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1570831091_1570809496_246/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1535349248_1534844455_103/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1479382139_1479307943_7/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1560402345_1560380871_171/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1499438702_1499102886_31/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1570364373_1570342779_230/rawdata/
/pack/splunk/var/lib/splunk/audit/colddb/db_1542089094_1541922369_123/rawdata/`

Do you have any idea what may have caused this?
-----------------------------------------------
All folders have the same structure (splunk index) and I have tested using the single file jourlan.gz and the folder. In any case, the name collision occurs.

`splunk@splunk03:/pack/restic-s3-splunk-backup$ ls -al /pack/splunk/var/lib/splunk/audit/colddb/db_1571223889_1571202293_252/rawdata/
total 5884
drwx------ 2 splunk splunk    4096 Oct 17  2019 .
drwx--x--- 3 splunk splunk    4096 Oct 17  2019 ..
-rw------- 1 splunk splunk 5977011 Oct 17  2019 journal.gz
-rw------- 1 splunk splunk    3763 Oct 17  2019 slicemin.dat
-rw------- 1 splunk splunk   31276 Oct 17  2019 slicesv2.dat
splunk@splunk03:/pack/restic-s3-splunk-backup$ ls -al /pack/splunk/var/lib/splunk/audit/colddb/db_1559112369_1559112085_150/rawdata/
total 24
drwx------ 2 splunk splunk 4096 May 29  2019 .
drwx--x--- 3 splunk splunk 4096 May 29  2019 ..
-rw------- 1 splunk splunk 4953 May 29  2019 journal.gz
-rw------- 1 splunk splunk    9 May 29  2019 slicemin.dat
-rw------- 1 splunk splunk   26 May 29  2019 slicesv2.dat
splunk@splunk03:/pack/restic-s3-splunk-backup$`

Do you have an idea how to solve the issue?
-------------------------------------------
Maybe its because of the very long paths?
Or because the --files-from list?
?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It made me very frustrated, as testing earlier on simple directories did work.

**Comment by pertoft** [comment]
Uninstalling the debian version and installing a binary version restic 0.9.6 solved the issue

**Comment by rawtaz** [comment]
Yeah, that 0.8.3 is really really old. This is when it's nice that restic is just a Go-built binary that you can drop and run anywhere!

**Comment by pertoft** [comment]
I would be nice if the Ubuntu package were update. That was why the error occurred in the first place

**Comment by rawtaz** [comment]
I completely agree.
