### ISSUE TITLE
Ubuntu package very old

### ISSUE THREAD

**Issue by pertoft** [restic/restic#2917]
The Ubuntu package is only 8.0.3 and it should be     updated.

Output of `restic version`
--------------------------

How did you run restic exactly?
-------------------------------

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by rawtaz** [comment]
Thank you, but this is completely outside of restic, it's the Ubuntu package maintainers that need to keep the packages up to date I'm afraid :)
