### ISSUE TITLE
Switch FUSE library used?

### ISSUE THREAD

**Issue by qbit** [restic/restic#2920]
Output of `restic version`
--------------------------

Some version in the future :D 

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Currently the FUSE library in use ([bazil/fuse](https://github.com/bazil/fuse)) has limited support for different operating systems. No support for OpenBSD for example.

Meanwhile [billziss-gh/cgofuse](https://github.com/billziss-gh/cgofuse) adds support for more systems.

It also seems that the cgofuse library is more compatible with restic (or at least it’s license is simpler :P).

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Is there interest in switching libraries? If so, I can take a crack at it!

**Comment by rawtaz** [comment]
Looks like that library only supports non-CGO for Windows and not the other platforms. That makes it a non-option because we don't want CGO in restic.

**Comment by qbit** [comment]
Bummer, OK. Thanks for the info!

**Comment by rawtaz** [comment]
Thanks for the suggestion though, it's appreciated that you try to help improve restic!
