### ISSUE TITLE
Restic message: Please report this error (along with the output of the 'prune' run) at

### ISSUE THREAD

**Issue by hklausing** [restic/restic#2921]
Here it is:

$ sudo /usr/bin/restic prune -r /net/nas1/backup/majestix -p /etc/bwr/password
[sudo] Passwort für heiko: 
repository 1fc6b2a7 opened successfully, password is correct
counting files in repo
building new index for repo
[11:33] 100.00%  123302 / 123302 packs
repository contains 123302 packs (1177127 blobs) with 582.225 GiB
processed 1177127 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 20 snapshots
[1:14] 100.00%  20 / 20 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

Return code was 1

$ restic version
restic 0.9.6 compiled with go1.13.4 on linux/amd64

**Comment by MichaelEischer** [comment]
I think we need a bit more details to do anything about this (see https://github.com/restic/restic/issues/new?template=Bug.md). However, given that the error message looks like one of the plenty other issues with prune failures, it's probably better to handle this in the forum https://forum.restic.net/ (and fix the repository). In any case please run `restic check` to get an impression of the repositories current state.

**Comment by hklausing** [comment]
Thanks for feedback.

I do a daily backup, all activies are logged and once a week the command forget is executed and . But the error was never shown before. I searched for some similar issues but I was not able to find them. Followed are some additional results I found (file/directory names renamed).

$ sudo /usr/bin/restic check -r /net/nas1/backup/majestix -p /etc/bwr/password
[sudo] Passwort für heiko: 
using temporary cache in /tmp/restic-check-cache-568786850
repository 1fc6b2a7 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-568786850
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree d47f5f93:
  tree d47f5f93: file "abcdefghi_12345678-987654.tar.gz" blob 34 size could not be found
  tree d47f5f93: file "abcdefghi_12345678-987654.tar.gz" blob 35 size could not be found
  tree d47f5f93: file "abcdefghi_12345690-765431.tar.gz" blob 36 size could not be found
  tree d47f5f93, blob ac811329: not found in index
  tree d47f5f93, blob c60d69e2: not found in index
  tree d47f5f93, blob 597dab62: not found in index
error for tree 35452630:
  tree 35452630: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.flac" blob 4 size could not be found
  tree 35452630: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.flac" blob 5 size could not be found
  tree 35452630: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.mp3" blob 0 size could not be found
  tree 35452630: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.mp3" blob 1 size could not be found
  tree 35452630, blob 153a51f5: not found in index
  tree 35452630, blob a113adae: not found in index
  tree 35452630, blob 91f626dc: not found in index
  tree 35452630, blob 2322ff8c: not found in index
error for tree 8d116e5d:
  tree 8d116e5d: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.flac" blob 4 size could not be found
  tree 8d116e5d: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.flac" blob 5 size could not be found
  tree 8d116e5d: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.mp3" blob 1 size could not be found
  tree 8d116e5d, blob 153a51f5: not found in index
  tree 8d116e5d, blob a113adae: not found in index
  tree 8d116e5d, blob 2322ff8c: not found in index
error for tree 5baf7b5b:
  tree 5baf7b5b: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.flac" blob 4 size could not be found
  tree 5baf7b5b: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.flac" blob 5 size could not be found
  tree 5baf7b5b, blob 153a51f5: not found in index
  tree 5baf7b5b, blob a113adae: not found in index
error for tree 755a0034:
  tree 755a0034: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.mp3" blob 1 size could not be found
  tree 755a0034, blob 2322ff8c: not found in index
error for tree dabefa65:
  tree dabefa65: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.flac" blob 4 size could not be found
  tree dabefa65: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.flac" blob 5 size could not be found
  tree dabefa65, blob 153a51f5: not found in index
  tree dabefa65, blob a113adae: not found in index
error for tree 5b523a29:
  tree 5b523a29: file "Abcd Efghijk - 1234 Lmn Opqrs, Tuv Wyxz, Abc Defgh - 56 - Ijk Mnopq.mp3" blob 1 size could not be found
  tree 5b523a29, blob 2322ff8c: not found in index
error for tree 4e3c5d03:
  tree 4e3c5d03: file "Zxywvu 123.MOV" blob 149 size could not be found
  tree 4e3c5d03: file "Zxywvu 123.MOV" blob 150 size could not be found
  tree 4e3c5d03: file "Zxywvu 456.MOV" blob 96 size could not be found
  tree 4e3c5d03: file "Zxywvu 456.MOV" blob 97 size could not be found
  tree 4e3c5d03: file "Zxywvu 456.MOV" blob 98 size could not be found
  tree 4e3c5d03, blob e77fc7a0: not found in index
  tree 4e3c5d03, blob 923e6e79: not found in index
  tree 4e3c5d03, blob 23f1ee3e: not found in index
  tree 4e3c5d03, blob 829b5d6d: not found in index
  tree 4e3c5d03, blob 3f4bc894: not found in index
error for tree 838cbdce:
  tree 838cbdce: file "Zxywvu 123.MOV" blob 149 size could not be found
  tree 838cbdce: file "Zxywvu 123.MOV" blob 150 size could not be found
  tree 838cbdce: file "Zxywvu 456.MOV" blob 96 size could not be found
  tree 838cbdce: file "Zxywvu 456.MOV" blob 97 size could not be found
  tree 838cbdce: file "Zxywvu 456.MOV" blob 98 size could not be found
  tree 838cbdce, blob e77fc7a0: not found in index
  tree 838cbdce, blob 923e6e79: not found in index
  tree 838cbdce, blob 23f1ee3e: not found in index
  tree 838cbdce, blob 829b5d6d: not found in index
  tree 838cbdce, blob 3f4bc894: not found in index
Fatal: repository contains errors

###

$ sudo /usr/bin/restic find --tree 838cbdce -r /net/nas1/backup/majestix -p /etc/bwr/password
repository 1fc6b2a7 opened successfully, password is correct
Found tree 838cbdce75da6f49393a2356e3e0925116563556e2754ae0af9fd94d0d22d677
 ... path /home/share/public/Data/Foo/Bar/Khitan/YXZ/Aaabbbccceee
 ... in snapshot 0d3a7c6f (2020-06-30 01:30:12)
Found tree 838cbdce75da6f49393a2356e3e0925116563556e2754ae0af9fd94d0d22d677
 ... path /home/share/public/Data/Foo/Bar/Khitan/YXZ/Aaabbbccceee
 ... in snapshot 105bdae4 (2020-04-30 01:30:48)
Found tree 838cbdce75da6f49393a2356e3e0925116563556e2754ae0af9fd94d0d22d677
 ... path /home/share/public/Data/Foo/Bar/Khitan/YXZ/Aaabbbccceee
 ... in snapshot 837882ae (2020-07-31 01:30:30)
Found tree 838cbdce75da6f49393a2356e3e0925116563556e2754ae0af9fd94d0d22d677
 ... path /home/share/public/Data/Foo/Bar/Khitan/YXZ/Aaabbbccceee
 ... in snapshot a0dec042 (2020-08-09 01:30:29)
Found tree 838cbdce75da6f49393a2356e3e0925116563556e2754ae0af9fd94d0d22d677
 ... path /home/share/public/Data/Foo/Bar/Khitan/YXZ/Aaabbbccceee
 ... in snapshot f00900cf (2020-05-30 02:43:12)
Found tree 838cbdce75da6f49393a2356e3e0925116563556e2754ae0af9fd94d0d22d677
 ... path /home/share/public/Data/Foo/Bar/Khitan/YXZ/Aaabbbccceee
 ... in snapshot fc7c8707 (2020-08-16 01:30:15)

###

$ sudo /usr/bin/restic prune -r /net/nas1/backup/majestix -p /etc/bwr/password
[sudo] Passwort für heiko: 
repository 1fc6b2a7 opened successfully, password is correct
counting files in repo
building new index for repo
[12:14] 100.00%  123504 / 123504 packs
repository contains 123504 packs (1178423 blobs) with 583.172 GiB
processed 1178423 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 21 snapshots
[1:17] 100.00%  21 / 21 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

###

$ sudo /usr/bin/restic rebuild-index -r /net/nas1/backup/majestix -p /etc/bwr/password
[sudo] Passwort für heiko: 
repository 1fc6b2a7 opened successfully, password is correct
counting files in repo
[11:35] 100.00%  123504 / 123504 packs
finding old index files
saved new indexes as [2e894def c985fdb7 93a4a831 8dd6e268 3a957749 d2083813 7ee8b43a f24bc949 602925d2 6c2d58ad 23cc0551 e261d185 8310a37d 8da1f84a 6c8acce2 e2fb3d09 b74eb090 79a2254b cc9f11ba c18f9db8 362d8b6b 9d7a3317 314045ea 4d88bd52 24cb3dbb 5c0f4af5 23f70e6f 95cbe89d 5b0d2bd8 25ec9523 a06b82b1 24b8f60a 033c44af 606f1467 090ea420 9d9e32ef 1b9d076a e9dd63b7 a302efe2 82382b90 4e68de53 ccc9a4de]
remove 43 old index files

**Comment by MichaelEischer** [comment]
Does `check` still report errors after the `rebuild-index` run? Judging from the filenames the missing blobs belong to some (probably) unchanged media files. In that case adding the `--force` flag to the next `backup` run should force restic to re-read every file and recover missing blobs from unchanged files.

You could also try a current beta version of restic (either from https://beta.restic.net/?sort=time&order=desc or build the current master branch), which should recover these blobs without passing any special flag. That newer version also speed up the `check` command a lot.

**Comment by hklausing** [comment]
Thanks to the infos. Yes, `check` still reports errors after `rebuild-index`. But after executing the `backup` with `--force` has reduced the issues to one tree/blob/file, not perfect but ok for me. I expect that over the time and using the `forget` command the issue will be passing.

I did also some tests with the beta version (-377). You are right the speed is much faster, but there was no changes due to me problem. Anyway, thank you again for your support.
