### ISSUE TITLE
Better feedback when using `restic copy`

### ISSUE THREAD

**Issue by propeeves** [restic/restic#2923]
Output of `restic version`
--------------------------
`restic 0.9.6 (v0.9.6-415-g97950ab8) compiled with go1.15.2 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
When using `restic copy`, I feel like more feedback should be given to the user. Currently it prints one line about what snapshot/label it's operating on and then prints error messages it encounters. Additional info about what it's currently working on, and what %/amount of files it has left to work on would be very useful, even if it meant slower wait upfront. 

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I'm currently trying to combine multiple repos I made previously into a single repo to reduce file size - they were made before I really understood the outline of restic repos and snapshots.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is my goto for anyone looking for backup software suggestions - I love how easy it is to use while staying pretty faithful to the norms of terminal software. I also love how I can integrate it with rclone and backup to my not-so-well-known cloud provider as easily as the more famous ones.

**Comment by rawtaz** [comment]
Sounds like something the verbose option should do.

**Comment by MichaelEischer** [comment]
Printing a progress in percent would require running a lot of the processing steps twice. On the other hand, just printing the currently processed files names would be relatively simple to implement.

> I'm currently trying to combine multiple repos I made previously into a single repo to reduce file size

Deduplication between snapshots which originate from different repositories will only work partially.

**Comment by dkotik** [comment]
I am interested in this getting fixed up. What can I do to help? The PR looks like it only lacks approval.
