### ISSUE TITLE
less matchy exclude-files

### ISSUE THREAD

**Issue by M1cha** [restic/restic#2926]
Output of `restic version`
---------------------------------
`restic 0.9.6 compiled with go1.14.4 on linux/amd64`

What should restic do differently? What problem would this solve?
----------------------------------------------------------------------------------
I found the documentation to `--exclude-file` rather lacking so I just read the code.
From what I understand it splits both the pattern and the absolute file path by `/` to form two arrays and does one the following (ignoring double-wildcards):
1) when the pattern array is longer than the path array, it's not a match
2) when the pattern array and the path array have the same length, they get `filepath.Match` is run on each item
3) if the pattern array is shorter than the path array, step 2 is being applied for each possible location of the pattern-array within the path-array

IMO this matches way too many paths(especially due to condition 3)
consider the following scenarios:
- I'm trying to exclude the absolute directory `/a/b/c` using pattern `a/b/c` but this will also match the directory `/x/y/z/a/b/c` due to 3)
- pattern: `a/b/c` will match `/a/b/c`, `/x/a/b/c`, `/a/b/c/y` and `/x/a/b/c/y` - especially for the last case I don't think anyone would expect that

**Comment by MichaelEischer** [comment]
Why don't you just specify `/a/b/c` as exclude? It is expected behavior for `a/b/c` to may _any_ part of the path, just like with other programs which support excludes.

**Comment by M1cha** [comment]
interesting. the doc actually says that leading slashes are supported - I just can't find that in the source code though. I'll try to find it and maybe test it as well and close the issue if it's actually supported because it would totally solve my issues with it.

**Comment by MichaelEischer** [comment]
The magic happens here: https://github.com/restic/restic/blob/b10dce541ec263a91e3248fd52694952a500526f/internal/filter/filter.go#L74-L75

For `/a/b/c` this yields `["", "a", "b", "c"]`. This happens for both filepath and pattern. Only absolute paths have that empty initial path segment and thus an absolute pattern matches only at the root of a path.

**Comment by fd0** [comment]
Very subtle magic, I agree :D
