### ISSUE TITLE
invalid generated manpages?

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#2938]
I'm trying to update the Debian package of `restic` to v0.10.0 (from v0.9.6). I noticed that the manpages got updated. For example in `doc/man/restic-backup.1`

    -.TH "restic backup" "1" "Jan 2017" "generated by `restic generate`" ""

got replaced by

    +.TH restic backup(1)Jan 2017
    +generated by \fB\fCrestic generate\fR

which seems to be invalid  (it gives a `backup(1)Jan` section).

**Comment by MichaelEischer** [comment]
The broken manpages are caused by the update of https://github.com/spf13/cobra, see https://github.com/spf13/cobra/issues/1049 . `v0.0.5` of cobra seems to be the last working version.
