### ISSUE TITLE
Support backing up user-provided list of files

### ISSUE THREAD

**Issue by chrahunt** [restic/restic#2944]
Output of `restic version`
--------------------------

```
restic 0.9.6 (v0.9.6-204-gf0b2dee7) compiled with go1.12.9 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Support a well-specified and simple way for users to tell restic to backup a specific set of files.

For example, consider this JSON list of files and assume that there are files with these exact names on the filesystem

```
[
  "/src/**",
  "/src/\n",
  "/src/\\"
]
```

restic could accept them as a JSON array, like

```
echo '["/src/**","/src/\n","/src/\\"]' | restic backup --files-from-json -
```

Alternatively, restic could accept them with NUL-delimiters, like

```shell
printf '%s\0' '/src/**' '/src/\n' "/src/\\" | restic backup --files-from-z -
```

which aligns with similar features in several other tools for producing output and receiving input in a consistent way: `find` (`-print0`), `xargs` (`-0`), `git ls-files` (`-z`).

Personally, I prefer the JSON-based approach since we can provide more meaningful errors, and there are fewer edge cases or decisions to make around the parsing of it (like how to treat an empty field or whether to consider a trailing newline as extraneous or as a path), but it may be a little less conventional.

To be forward-compatible, it may be worth putting the list of files under a key, like `{"files": []}`. I really do not want restic to do any processing at all here, but later someone may want to be able to provide globs in a similar way, without the caveats of `--files-from`. `{"patterns": []}` could be simpler than another argument in that case.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I have a specific list of files to back up, and want to use restic to do it. I want to back up only these specific files, and the paths may contain any character the OS/filesystem considers valid.

Currently, to be understood by restic in a compatible way, I have to carefully consider each path. The logic looks like:

1. Leave `$` as-is, since `$` does not need to be escaped in the paths provided via `--files-from` (as opposed to exclude files)
2. Make every path absolute
   - avoids needing to escape leading whitespace, which would be trimmed if in a `--files-from` file
   - avoids needing to escape a leading `#`, which would cause the line to be skipped if in a `--files-from` file
3. Pass paths that contain newlines via positional command-line arguments
   - files passed to `--files-from` are split by newline, so newline-having paths would get split incorrectly
   - currently, no other processing is done on paths provided this way
   - only passing newline-having paths as arguments, as opposed to all paths, reduces the chance of hitting an OS-specific limit (for example, `ARG_MAX` on Linux)
4. For paths without newlines, escape as described below and save them one-per-line to a file and pass the file path to `--files-from`
   1. Surround each `[`, `*`, and `?` with `[]`
      - necessary since all paths derived from `--files-from` are passed through `filepath.Glob`
      - putting special characters in a character class causes `filepath.Glob` to treat them as normal characters, without relying on `\`-escaping, which is not supported in `filepath.Glob` on Windows
   2. If there is any trailing whitespace, surround the last character with `[]`
      - currently, restic strips any leading and trailing whitespace from each line derived from a `--files-from` argument
      - preserves the trailing whitespace by eliminating it in a way that will be interpreted correctly by `filepath.Glob`
   3. On non-Windows OSes, replace `\` with `\\`
      - `\\` will be interpreted correctly as `\` by `filepath.Glob`

Which has these downsides:

1. Not obvious at all
2. Requires additional code to integrate with restic in a generic way
3. Minor performance drawback since we may be globbing for what are essentially plain paths to individual files, and taking the slower path in the Go std library
4. Very fragile. Any of the above could easily change if untested, and I wouldn't hold it against anyone that broke it either

If restic supports this feature, then none of the above is necessary and it gets a lot easier to use restic as a building block for different backup workflows.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes! I like the content-hash-based de-duplication a lot, especially where the modified time of a file may change, but not its contents. Other approaches like rclone with a crypt backend would unfortunately reupload the file.

**Comment by aawsome** [comment]
Do you know about `restic backup --files-from`?

**Comment by rawtaz** [comment]
@chrahunt Thanks for being so elaborate in your description, that's appreciated!

That said, do you have an actual concrete/practical use case where you need this? I have a hard time relating to anyone I know ever having needed this. Just as an example, when would you have newlines in your filenames?

The use case strikes me as very uncommon and for such a specialized case I spontaneously think it might be fair to have to do that externally.

**Comment by chrahunt** [comment]
> do you have an actual concrete/practical use case where you need this?

I don't want to rely on any specific app's include/exclude rule syntax or restrictions so I generate my own list of files to backup. I have a script that generates those files so I don't have to manually consider every single file. If any of those files happen to have any of `*`, `\`, `\n`, `[`, or `?` then just writing them into `--files-from` would lead to undesired behavior. That's not acceptable to me if I can help it. I need to run on both Linux and Windows, so I can't use `\` to escape characters. I can't guarantee that my files do not have newlines, so I can't blindly write into `--files-from`.

> Just as an example, when would you have newlines in your filenames?

There are two situations I've seen this specifically:

1. apps that use user-provided text as a filename without any encoding
2. test files, like those used to test that a script correctly reads and escapes filenames that contain `\n` :)

To me, omitting these files from the backup is not ideal.

> The use case strikes me as very uncommon and for such a specialized case I spontaneously think it might be fair to have to do that externally.

I don't think this is that uncommon. Consider #2276, #2448, and other forum posts. They essentially boil down to "provide restic a list of paths to back up", but users are getting caught off-guard by the interpretation of the paths. In some cases users are stuck with sub-optimal workarounds because of platform limitations.

We could also consider that similar features exist in other backup tools:

- [rsync](https://linux.die.net/man/1/rsync) has `--files-from`, which takes newline-delimited paths verbatim and `--from0`, which causes `--files-from` to expect null separators instead
- [rclone](https://rclone.org/filtering/#files-from-raw-read-list-of-source-file-names-without-any-processing) has `--files-from-raw`, which takes newline-delimited paths verbatim
- [duplicity](http://duplicity.nongnu.org/vers8/duplicity.1.html) has `--include-filelist`, which takes newline-delimited globs and `--null-separator`, which causes `--include-filelist` to expect null separators instead
- [borg](https://borgbackup.readthedocs.io/en/stable/usage/create.html): has `--patterns-from`, which takes a newline-delimited of [patterns](https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns), prefixing a line with `pf:` causes that line to be interpreted verbatim
