### ISSUE TITLE
Support a user-provided value for snapshot paths

### ISSUE THREAD

**Issue by chrahunt** [restic/restic#2993]
Output of `restic version`
--------------------------

restic 0.9.6 (v0.9.6-204-gf0b2dee7) compiled with go1.12.9 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Restic snapshots have a number of fields. `Paths`, a list of strings, is one of them.
Currently when a user runs `restic backup`, a snapshot gets created with `Paths` that
includes every target file passed on the command line or in `--files-from`, and there
is no option to change this behavior.

I propose that `restic backup` should accept an option, like `--snapshot-path`, which could be provided multiple
times. If that option is provided at least once, then restic would use its value(s) for the snapshot `Paths` instead
of the backup targets. If the option is not provided, then restic would use the backup targets for the snapshot `Paths`
like it does today.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I have a script that generates a list of files, about 100000 right now, writes that to a file, and passes it to restic, like
`restic backup --files-from files.txt`. This runs every 15 minutes.

These are the problems I have:

1. Every backup, a new 11MB snapshot file is created and uploaded. This results in about 1 GB/day extra storage usage.
2. `restic snapshots --compact latest` is slow, up to 15 seconds. I have to run this to retrieve the parent snapshot and avoid backup delays, similar to #2246.
3. When running `restic forget`, I need to specify `--group-by host`, since the snapshot paths are not usable to me for grouping.
4. If I want to list snapshots, I must always use `--compact`, so paths are excluded. I must never use `--json`, since paths are always included.

If restic accepted an option like I described above, then I can pass `--snapshot-path /`. All of the above problems would be solved:

1. Every backup, the bare minimum is created and uploaded for the snapshot file.
2. I no longer need to run `restic snapshots --compact latest`, because the automatic parent identification would work based on the path I specified.
3. Forgetting snapshots would not require a `--group-by` flag to find the right backups
4. No more fear of listing snapshots without passing a flag. No more need to parse a plain text format in my scripts because I can use `--json`.

I have tried a few alternatives unsuccessfully:

1. Use excludes instead of includes, as mentioned on [the forums](https://forum.restic.net/t/snapshots-display-unusable-with-files-from/1135). My excludes file contained 8026 paths and backup itself slowed to a crawl. A backup operation that should have had minimal changes took 10 minutes before I cancelled it (compared to 15 seconds normally), and it was not very far along.
2. Minimize the number of paths passed to restic by only putting parent directories if no contents needed to be excluded. This reduced the size of the snapshots file to about 3.5 MB. The downside of this is that it introduces the risk of backing up undesirable files, which could be added to directories after the file list gets generated but before restic walks over them.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

So far restic has helped keep my files safe!

**Comment by DRON-666** [comment]
Same situation here. Huge auto generated file lists lead to waste of time and space.
Also not all commands support compact mode: yesterday I extensively use copy command and console freezes for minutes trying to output megabytes of useless file names.

**Comment by MichaelEischer** [comment]
> Every backup, a new 11MB snapshot file is created and uploaded. This results in about 1 GB/day extra storage usage.

The current assumption in restic is that _all_ snapshots taken together are just a few megabytes in total. I wonder how much impact that has on the memory usage of restic.

A `--snapshot-path` option or similar is already tracked in #2714 (@chrahunt I've taken the liberty to add a part of your issue description to #2714). And the problem with poor performance of large exclude files was reported in #2694. Did I miss anything not covered by the two former issues or can this issue be closed?

**Comment by chrahunt** [comment]
I think those existing issues cover my concerns, and thank you for the comment over in #2714.

It may be worth considering whether this option (as tracked in #2714) would be a suitable workaround for #2246, but I don't feel strongly about that one way or another.

I'll close this issue in favor of tracking the work in the other issues mentioned above.
