### ISSUE TITLE
cannot complete backup test of 500000 files  (460GB) 

### ISSUE THREAD

**Issue by despiegk** [restic/restic#300]
I have now tried for 5th time, but did not succeed so far
the data is on an USB disk
it could be that there are issues with the USB disk because it went offline
so still investigating & trying in multiple situations

firs some questions
- if a backup fails in the middle, it looks like there is no optimisation for 2nd run (e.g. dedupe) and all backup needs to be redone from 0 (is this correct?)
- is there a description somewhere how the dedupe works, where do you keep the index, if backup is over remote sftp what gets downloaded to check if there is dedupe?

some observations:
- it would be ideal that there is an option for the backup application to keep on retrying for X hours if e.g. the source went offline because now the test everytime needs to start from 0
- or even better, if a partial log should be there and it can be reused so the backup does not try to redo all from scratch in the 2nd run

regards 

Kristof

PS: love this tool

**Comment by despiegk** [comment]
other observation there is at least 50% duplication in this dataset, I don't see this when doing backup, I am doing backup over sftp and it goes at 10MB/sec constantly, because of dedupe I would have expected at certain periods that the speed would go up?

**Comment by fd0** [comment]
Hi, thanks for reporting this, you're helping us to find bugs :)

To answer your questions:
 * If a backup fails e.g. because the backup location is unreachable, it is currently not possible to resume a backup. This is tracked in issue #59 and is not hard to add, which means it will not take much more time until that feature is finished.
 * The description of the Index and all the low-level format for the repository is documented in the file `doc/Design.md`, which you can find here: https://github.com/restic/restic/blob/master/doc/Design.md. In addition, I'm working on a blog post that explains the deduplication in a bit more detail.
 * The current throughput displayed in the console is only a rough estimation on how much data restic has read the last couple of seconds. I'm sure there is a bug in the calculation because I also observed strange values lately, but haven't gotten around to debugging this.

Adding a retry option for the backend/repository is a good idea, at the moment restic aborts when the first failure to save something in the repository occurs.

**Comment by despiegk** [comment]
another attempt:
if you want me to test something let me know

scanned 2758 directories, 210200 files in 1:51
panic: json: error calling MarshalJSON for type *restic.Node: json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]

goroutine 99 [running]:
github.com/restic/restic.(*Archiver).dirWorker(0xc20809d2c0, 0xc208053020, 0xc20c14a0c0, 0xc20809e1e0, 0xc20809e5a0)
        /tmp/restic-build-059564911/src/github.com/restic/restic/archiver.go:359 +0x542
created by github.com/restic/restic.(*Archiver).Snapshot
        /tmp/restic-build-059564911/src/github.com/restic/restic/archiver.go:616 +0xa67

goroutine 1 [semacquire, 225 minutes]:
sync.(*WaitGroup).Wait(0xc208053020)
        /usr/lib/go/src/sync/waitgroup.go:132 +0x169
github.com/restic/restic.(*Archiver).Snapshot(0xc20809d2c0, 0xc20c14a0c0, 0xc2080a8290, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/restic-build-059564911/src/github.com/restic/restic/archiver.go:621 +0xadd
main.CmdBackup.Execute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xac0b60, 0xc20809c080, 0x1, 0x4, ...)
        /tmp/restic-build-059564911/src/github.com/restic/restic/cmd/restic/cmd_backup.go:321 +0xdea
main.(*CmdBackup).Execute(0xc208030140, 0xc20809c080, 0x1, 0x4, 0x0, 0x0)
        <autogenerated>:12 +0xd9
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc20800a140, 0xc20800a010, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-059564911/src/github.com/jessevdk/go-flags/parser.go:278 +0x8c1
github.com/jessevdk/go-flags.(*Parser).Parse(0xc20800a140, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-059564911/src/github.com/jessevdk/go-flags/parser.go:154 +0xb1
main.main()
        /tmp/restic-build-059564911/src/github.com/restic/restic/cmd/restic/main.go:26 +0x1ca

goroutine 5 [syscall, 227 minutes]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive, 227 minutes]:
github.com/restic/restic.func·011()
        /tmp/restic-build-059564911/src/github.com/restic/restic/lock.go:262 +0x179
created by github.com/restic/restic.func·012
        /tmp/restic-build-059564911/src/github.com/restic/restic/lock.go:265 +0x25

**Comment by fd0** [comment]
Could you please try building restic with debug support by running `go run build.go -tags debug` from the latest master, then rerun the backup with the environment variable `DEBUG_LOG` set to a file name into which restic will write an extensive debug log. This way we can find the file or directory that is causing the strange behavior. If you like you can post the log somewhere (you can send me an email), but please be aware that it will contain sensitive things like the names of all files and dirs in the backup.

**Comment by despiegk** [comment]
it will be next week before I can try with that dataset because its on a
notebook I can't access this week,
i'll do next week for sure


On Sun, Sep 27, 2015 at 10:35 PM, Alexander Neumann <
notifications@github.com> wrote:

> Could you please try building restic with debug support by running go run
> build.go -tags debug from the latest master, then rerun the backup with
> the environment variable DEBUG_LOG set to a file name into which restic
> will write an extensive debug log. This way we can find the file or
> directory that is causing the strange behavior. If you like you can post
> the log somewhere (you can send me an email), but please be aware that it
> will contain sensitive things like the names of all files and dirs in the
> backup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restic/restic/issues/300#issuecomment-143583086>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by fd0** [comment]
Thanks, that's fine with me.

**Comment by fd0** [comment]
I've worked a lot on these issues in the last couple of days, could you give it a try again? If it fails again, please run it with a debug log file so we can investigate.

**Comment by despiegk** [comment]
will try

**Comment by despiegk** [comment]
started the test again, sorry for the long wait, I lost connection to the test PC

**Comment by despiegk** [comment]
I can already confirm that the resume function works (-:

**Comment by despiegk** [comment]
I got 70% through so its much better than last time, but my test machine attached USB disk disconnected and I can't get remote access to it.
I think you can close this issue, test worked, my disk not.

**Comment by despiegk** [comment]
will be further testing, if I find something i'll be back. Thanks a lot for your fantastic tool

**Comment by fd0** [comment]
Thanks for trying it again and coming back to us, such feedback is valuable. Please feel free to report all issues ;)
