### ISSUE TITLE
Describe target audience in changelog template

### ISSUE THREAD

**Issue by MichaelEischer** [restic/restic#3001]
What should be changed?
--------------------------

The changelog template currently does not describe the target audience of a changelog entry. Some of the details for writing a changelog entry are only described in point seven of [CONTRIBUTING.md](https://github.com/restic/restic/blob/88cc4447791abc4bf030f3099f74ad22812ec631/CONTRIBUTING.md#providing-patches):
> If your pull request changes anything that users should be aware of (a bugfix, a new feature, ...) please add an entry as a new file in changelog/unreleased including the issue number in the filename (e.g. issue-8756). Use the template in changelog/TEMPLATE for the content. It will be used in the announcement of the next stable release. While writing, ask yourself: If I were the user, what would I need to be aware of with this change?

I think it would be useful if the changelog template describes all relevant aspects for adding/writing a changelog entry (especially as the PR template directly links to the changelog template!). It currently IMHO misses the following aspects:
- How to decide what the changelog should describe?
- Who is the target audience?
- Which filename should the changelog entry get?

**Comment by greatroar** [comment]
For reference, this is the current template:

```
Bugfix: Fix behavior for foobar (in present tense)

We've fixed the behavior for foobar, a long-standing annoyance for restic
users.

The text in the paragraphs is written in past tense. The last section is a list
of issue URLs, PR URLs and other URLs. The first issue ID (or the first PR ID,
in case there aren't any issue links) is used as the primary ID.

https://github.com/restic/restic/issues/1234
https://github.com/restic/restic/pull/55555
https://forum.restic.net/foo/bar/baz
```

I think the second questions can be answered here: a changelog entry is always for the user. CHANGELOG.md says as much:

> The following sections list the changes in restic 0.10.0 relevant to restic users.

If I may take a stab at an expanded template:

```
# The first line must start with Bugfix:, Enhancement: or Change: (including the colon).

Enhancement: Allow custom bar in restic foo (in present tense)

# Describe the problem in the past tense, the new behavior in present tense.
# Mention the affected commands, backends, operating systems, etc.
# Focus on user-facing behavior, not the implementation.

restic foo always used the system-wide bar when deciding how to frob an item
in the baz backend. It now permits selecting the bar with --bar or the environment
variable RESTIC_BAR. The system-wide bar is still the default.

# The last section is a list of issue URLs, PR URLs and other URLs.
# The first issue ID determines the filename for the changelog entry, here issue-1234.
# If there are no relevant issue links, use the PR ID and call the file pull-55555.

https://github.com/restic/restic/issues/1234
https://github.com/restic/restic/pull/55555
https://forum.restic.net/foo/bar/baz
```

**Comment by rawtaz** [comment]
I think the suggestion from @greatroar is really good. I love the wording :)

I just have a few simple comments:

1. Please remove `restic` from the example subject line, as restic is already an obvious/given context and thereby redundant.

2. When starting a sentence with the word "restic" we ought to use a capital R, such as "Restic". This is how it's mostly done on the mail website, which was written by @fd0, and it also makes sense grammatically (even though we use restic all lowercase everywhere else).

3. I suggest restructuring the "main" paragraph like this to make it well within 80 columns wide, and I also changed a couple of words:

~~~
Restic foo always used the system-wide bar when deciding how to frob an
item in the baz backend. It now supports selecting the bar with --bar or
the environment variable RESTIC_BAR. The system-wide bar option is still
the default.
~~~
