### ISSUE TITLE
Cannot remove broken snapshot

### ISSUE THREAD

**Issue by c7hm4r** [restic/restic#3003]
Output of `restic version`
--------------------------
restic 0.10.0 compiled with go1.15.2 on linux/amd64

How did you run restic exactly?
-------------------------------

```
$ restic --repo=sftp:...:... --password-file=... check
using temporary cache in /tmp/restic-check-cache-308261100
repository 7ab848e2 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-308261100
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error: load <snapshot/56c17514f8>: invalid data returned
Fatal: repository contains errors
$ restic --repo=sftp:...:... --password-file=... forget 56c17514f8
repository 7ab848e2 opened successfully, password is correct
Ignoring "56c17514f8ad85451bb4be440a1aac375260eb66b02abe6bda9345de32a20f68", could not load snapshot: load <snapshot/56c17514f8>: invalid data returned
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SFTP

Expected behavior
-----------------
1. Snapshots should ideally not break.
2. There should be some way to recover easily from a broken snapshot.

Actual behavior
---------------
- Unable to `forget` a broken snapshot.

The respective snapshot file is empty (0B).

Steps to reproduce the behavior / Do you have any idea what may have caused this?
-------------------------------
- No real clue. The error was maybe caused by killing restic during backup or by unreliable network connection. Data corruption cannot be excluded.

Do you have an idea how to solve the issue?
-------------------------------------------
- Manually removing the affected snapshot file (that worked).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
- Being able to efficiently back up a 300GB HDD on a Raspberry Pi 3. (Not related to this issue)

**Comment by MichaelEischer** [comment]
That error looks like an interrupted upload. The upload via SFTP is currently not atomic, such that you can end up with incomplete or empty files when interrupted at just the wrong point in time. However, this is just a nuisance, as the upload was never completed these also aren't used for a snapshot.

Although it would be possible to modify `forget` to resolve snapshots in a special way when specified as IDs, that would just hide the problem. So I guess it's best to resolve this properly (which will take some time).

**Comment by c7hm4r** [comment]
So nice to see this. Thank you so much for removing this pain point!
