### ISSUE TITLE
Adding --ignore-inode to command line causes all files to be seen as "new"

### ISSUE THREAD

**Issue by jim-collier** [restic/restic#3004]
I've poured through other issues, and the forum. Many similar discussions, but none that (seem to) involve `--ignore-inode` as the cause of files being seen as "new". E.g.:

- [Excessive file/disk reading despite available parent and identical metadata #2819](https://github.com/restic/restic/issues/2819) 
- [restic 0.9.6 with new ctime behaviour causes all files to show as changed #2495](https://github.com/restic/restic/issues/2495)

Output of `restic version`
--------------------------

`restic 0.9.6 compiled with go1.13.4 on linux/amd64`

How did you run restic exactly?
-------------------------------

(Edit: As [requested](https://github.com/restic/restic/issues/3004#issuecomment-706424524) by @rawtaz, added more commands and their output, from the specific logged run in question, below. Using "`✽✽✽`" to mask user-specific information of debatable privacy.)

```
restic version
restic 0.9.6 compiled with go1.13.4 on linux/amd64

restic -r "${b2Bucket}" --cache-dir "/root/.cache/restic" list snapshots
20fc9ee03b5e771c9791fc95009a51bcbed2a2e1a801c8854a59448999c49eeb
221c8f81ee033997aa0b38d2f04befb5d061c4c3ca5e665325dd3b87d84bebfe
4ae00c9a0e0ffc3caa65bfde8bc79ce3a811c7e4f359048e6ff5914fef80a8e8
64ca94a813176ee662adf4d0fcf829935b16d2749943a47d6e976eb11295c4fc
8e0b1b6bc14527e400685d1bab98cb23a839256593c6b59837fb55f3e4ae53c3
90329c741c69fac7ff24521a9c48e39fc290fc5e09a208f5185360057d8db5ff
b70962d2a4e60b1849cb8bca6f1078e4e40fd15b3a5c2f279aec5392605a6857
bed6cd4f534ce46956269a1eee1e5943e71c17a8a72ea5d345d8ea79fac869fc
d198741a118698788096dec2ae9965aaa51a67009f22eaa78dfbacf350c474d2
ec74c0f9540fae9fda070b2c0f57d108fecee0f6e60c69c954ea8988a64da680
f5cf28357ba2e6355b02f1d74db6bab3b9dd3c9ebeb6d3bef896fdf014dbe79c
f8ec2c6d8dff9d4328e2c13b8aa0e108e9f49af4104977e69445252407b810d2

restic backup --verbose=2 -o b2.connections=8 -r ${b2Bucket}: --ignore-inode --exclude-caches --exclude-if-present .nobackup --cache-dir "/root/.cache/restic" --exclude-file "${excludeFilespec}"  "✽✽✽"
open repository
lock repository
load index files
start scan on [✽✽✽]
start backup on [✽✽✽]
new       ✽✽✽, saved in 0.149s (0 B added)
new       ✽✽✽, saved in 0.428s (0 B added)
...
...
...
new       ✽✽✽, saved in 0.148s (0 B added, 371 B metadata)

Files:       743386 new,     0 changed,     0 unmodified
Dirs:            4 new,     0 changed,     0 unmodified
Data Blobs:     33 new
Tree Blobs:      5 new
Added to the repo: 10.539 MiB

processed 743386 files, 8.800 TiB in 26:41:50
snapshot 678804fb saved
```

Environment (verified at script runtime):
```
echo -e "${XDG_CACHE_HOME}\n${PWD}\n${USER}\n${HOME}"
/root/.cache/restic
/root
root
/root
```

The value of PATH is verified to be my normal complete system path, not the stripped-down one that you get from cron without some extra work.

There's four differences between this command and environment, that now sees all files as "new" (but chunks do exist on server so nothing actually uploaded), and previous runs against existing data that has already been successfully backed up, which complete in mere minutes on a ~15TB volume with about 8TB to back up:

1. Added `--ignore-inode` because due to my specific requirements, I need to compare via mtime rather than ctime. (Being fully aware of the drawbacks of mtime.) I don't actually need to ignore inode, it's just apparently the only way to get restic to use mtime rather than ctime for now.
1. Explicitly specified `--cache-dir`, just in case the problem was that restic suddenly couldn't find it for some reason.
1. Explicitly export `XDG_CACHE_HOME`, for the same reason, just in case (I'm sure not necessary), and running out of ideas.
1. Run via cron (with su - root as part of that for a fuller environment, same environment I got when successfully running restic after sudo -i). This was my eventual goal anyway but I tried it now in case that somehow solved it / hail-mary.

Nothing on the actual filesystem itself has changed. No additions, deletions, modifications, or metadata changes.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze b2

Expected behavior
-----------------

1. Perform a quick scan of the filesystem using new comparison method of `--ignore-inode` (I believe using path, mtime, size?) ...
1. ...against existing cached data that presumably has those attributes already cached.
1. See that still nothing has changed for any file.
1. Create new snapshot based 100% on existing chunks, without re-scanning any files, within <1 hour if not mere minutes.

Actual behavior
---------------

My backup script, exludes, and data set have finally settled down to statis. I've purposely not changed anything on the backup set, to get to this point. Now, every additional run completes in minutes, with nothing new scanned or uploaded.

But since adding the `--ignore-inode` flag, _every_ file is reported as "new", and fully re-scanned (which involves 15 HDDs grinding very hard for a very long time). Very little is uploaded - clearly not any new content - according to `bmon`, just a couple of KiB/s.

Do you have any idea what may have caused this?
-----------------------------------------------

I suspect - but can't definitively prove without substantial effort and/or putting production data at risk - that adding the `--ignore-inode` was the cause. I'm afraid to try removing the flag - especially mid-way through the current run - due to 1) possibly causing some kind of cache corruption, and 2) I need to change the comparison method to mtime anyway, might as well bite the bullet and see what happens.

Do you have an idea how to solve the issue?
-------------------------------------------

Probably not, but if this speculation is close enough, then:

- If changing the comparison `--ignore-inode` method is explicitly, intentionally eventually triggering full re-scans, then be smarter about when and why a rescan should be done, and don't do it just because we're using different comparison criteria.
- If mtime is not stored in the cache by default (without `--ignore-inode`), then it should be. The cost of doing so should be trivial in the big picture: an int64 to store, and you're already inspecting file metadata anyway.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

What I love about Restic:

- Vibrant, active, and professional developer and user community 0- with very little snark, passive-aggression, and/or abusiveness
- Written in Go
- My backup is more in my hands and can't be arbitrarily revoked for disastrous business decisions (e.g. Crashplan).
- 130x faster backup speed than Crashplan (granted mainly due to cloud storage differences).

What I'm anxiously anticipating

- Faster prune.
    - My last prune took ~144 hours. 6 _days_! Yikes. That's not remotely OK. Thankfully, it was the rare 6-day stretch without a sustained power outage or even so much as a momentary blip to internet connectivity. But my use case calls for at least every-other-month prunes.
    - I'm going to keep going with Restic for personal use in spite of this, because of the "what I love" above, but sadly, restic lost the competition for business backup, solely due to this.
    - I also run Borg Backup on an identical mirror, with pretty close to identical excludes. (But Borg regex vs Restic glob, means I'm not sure they are identical.) On a close to identical backup and prune schedule, Borg prunes about the same data with roughly the same rules, every time, in less than 5 minutes! (Granted, it's to borgbase.com, which runs a Borg server. So maybe it has lots of server-side help. I appreciate Restic's back-end flexibility, but minutes vs days is a no-brainer.)
- New `--iexclude-file` that ignores case, so I don't have to make multiple case permutations of almost every exclude rule.
- Support regex in `--exclude-file` (or something like `--exclude-regex-file`).
- **For the love of god, don't treat `--files-from` entries as globbing**! That is a baffling decision. No other software on earth does this. Not rsync, rclone...just about any other tool that deals with includes and excludes. They expressly expect a raw dump of individual explicit files to include, that was generated with some other tool. ("Do One Thing Well.") Now we have to _escape_ all problematic characters out of this list? (To be fair, Borg backup doesn't even have this, not quite anyway - inexplicably. To me this seems like a "do not pass go" feature!)
    - If you don't want to break the API, maybe add something like a new `--files-raw-from` flag. Or an environment variable to override the default behavior (e.g. `RESTIC_FILESFROM_RAW`).
- Faster `rebuild-index`.
    - Learning that I don't actually need to do this after every backup interruption was a revelation.
    - That said, I still would like to do this about once a quarter. But at something like 4-5 days, that's _really_ sketchy. If a power or internet outage occurs during it, presumably my local cache is toast? And will never be good until a `rebuild-index` succeeds?

**Comment by jim-collier** [comment]
> New `--iexclude-file` that ignores case, so I don't have to make multiple case permutations of almost every exclude rule.

Hot dang! That's fantastic. It's possible [I might even be responsible for the name of this flag](https://github.com/restic/restic/issues/2427#issuecomment-680243452)? (but obviously the need long preceded me). Did...did I just contribute to this project (in a teensy way)? Do I get a `contributor` badge now? ;-)

@MichaelEischer and @rawtaz, I'll work on getting the output you requested, thanks.

FYI, when the job did finally finish (which took a long time), I ran it again the exact same way (just now), and it finished within minutes. So obviously it's working as intended now.

**Comment by jim-collier** [comment]
@MichaelEischer 

> The --ignore-inode option only disables a few conditions which can cause files to be regarded as changed, it does not in any way can cause a file to be regarded as changed. That flag is only ever evaluated in the fileChanged method, where it only disables two if conditions...

It may be a meaningless distinction, but it didn't see the files as _changed_, it saw them all - every one - as _new_. Given some additional reading and investigation since then, it sounds like restic may not have been correctly referencing the previous snapshot (or any snapshot)? Might it have ignored the existing cache altogether and build a new one? (Because a second run after this issue, succeeded in not seeing _any_ files as "new", but rather [accurately] as "unchanged".)

> Did the backup run print that it is `using parent snapshot 01234567`?

Greps of the logged output (which is an exact dump of anything sent to stdout or stderr), shows no results for greps with:

- "using parent"
- "parent snapshot"
- "01234567"

Nor does a visual inspection show that.

That said, second and subsequent runs now work as expected. But that was definitely weird. There seems to be several issues and discussions with similar keywords, all of which I read - but I'm still not clear (obviously since I don't even know what's going on under the hood), on whether they are all related to a single root problem. (Or if there's even a problem above and beyond user error.)

**Comment by jim-collier** [comment]
@rawtaz - I updated the original description with more commands, and output.

**Comment by smlx** [comment]
> -r "${b2Bucket}"
> -r ${b2Bucket}:

Aren't these are two different folders within the bucket, since one has a trailing `:`?

**Comment by MichaelEischer** [comment]
> It may be a meaningless distinction, but it didn't see the files as _changed_, it saw them all - every one - as _new_. Given some additional reading and investigation since then, it sounds like restic may not have been correctly referencing the previous snapshot (or any snapshot)?

Not finding a parent snapshot perfectly matches the symptoms you've described. Please take a look at `restic snapshots` on whether the hostname or paths have changed. If the paths have changed, then this is just issue #2246.

> Might it have ignored the existing cache altogether and build a new one?
The cache has nothing to do with the issue. You can delete the cache at basically any point in time (well, let's not do that while restic runs) and restic will just download the missing files again.

**Comment by jim-collier** [comment]
@smlx 

> > -r "${b2Bucket}"
> > -r ${b2Bucket}:
> 
> Aren't these are two different folders within the bucket, since one has a trailing `:`?

Oh wow good catch. Fascinating. My script does half a dozen optional things, with only the backup command containing the colon. Everything seems to work though, so that's a real head-scratcher. Now that everything seems to be working smoothly, I'm afraid to fix it! May have to and bite the bullet though. When it comes to backing up important data, doing the wrong thing without complaint, is not the same thing as doing the right thing :-)  Thanks! I'll run these commands (except backup) manually again with the colon, and see if the output is any different.

**Comment by MichaelEischer** [comment]
I'm closing this as the issue seems to have been caused by restic not finding a suitable parent snapshot (which is discussed in #2246) and there's no indication of other another problem cause.

**Comment by jim-collier** [comment]
Coincidental timing! Because I just noticed that a current running backup suddenly started seeing all files as "new", midway through. I don't know if it's the same cause, or unrelated. Or if it's worth reopening this; I'm not even sure what value this additional info might bring. (Unless someone randomly reading this recognizes specific side effects.)

Here's the sequence of events in a nutshell, that includes this issue. I should point out that this filesystem is a mirror, and I purposely have not updated it, until I get restic runs predictable and stabilized. So no files have been updated at any point during this. Also, all jobs were either run after sudo -i, or via cron. In other words, as user `root`.

1. First backup run completed.
1. I made many runs to test tweaked excludes.
1. After that was all stablized, I made about a half-dozen backups with no changes, all of which completed quickly, and all files were listed as "unchanged".
1. I added the `--ignore-inode` to the backup job, and also configured it to launch from cron. From this point on, all runs are via cron.
   - **All new files were seen as "new"** (this issues)
1. Waited for backup to complete (scanning all files took a long time).
1. Ran again (second time after adding `--ignore-inode` and running from cron). Job completed quickly, all files seen as "unchanged".
1. Ran a third time, same conditions. About half (first half) of the files seen as "unchanged". Second half seen as "new".

Nothing was changed on the system when this occurred.

**Comment by MichaelEischer** [comment]
can you take a look at a snapshot before and after running the backup via cron using `restic cat snapshot <snapshot-id>` and check the diff for unexpected differences?

**Comment by jim-collier** [comment]
@MichaelEischer - will do, thanks. I'll wait 'till this job completes, might be tomorrow.

**Comment by jim-collier** [comment]
@MichaelEischer 

Here's the best I can figure out. It seems there may have been two separate problems:

### Narrative

1. After I added the `--ignore-inode` flag and put the job in `cron`, it appears to have been unable to read the local cache, with an error of `Fatal: parsing repository location failed: invalid backend...`. That began the first round of scanning everything anew, with no parent snapshot.

1. After I let it complete a run (rescanning all files), on subsequent jobs it settled in and resumed backing up normally, with parent snapshots and no rescans. But then at about 10% of the way through a backup, it was unable to read from the volume for some reason. (A highly reliable array but who knows.) _This appears to have had the side effect of wiping out the existing locally cached references, corresponding to what it couldn't read on the previous run_ - because on the next run, that initial ~10% of files were seen as "unchanged", and the remainder as "new", with "(0 B added)".

After that rescanned ~90% of the volume again and completed, subsequent runs since then have gone as expected. (So it seems for now to be OK.)

### Underlying observations

Possibly unnecessary, unless the narrative above seems mysterious.

These are the basic observations and data I used to construct the above narrative. For the purpose of clarity, I've given the runs number, that starts arbitrarily at 10 for no reason, and are numbered sequentially from there:

- Run 10:
	- The last among a string of successful backups that correctly listed all files on the array in question as "unchanged".
- Made the following changes from now and all subsequent runs:
    - Added `--ignore-inode` to the command line
    - Ran it from `cron`
        - With an existing scripting cron wrapper that allows it to inherit the same environment as `sudo -i`, which is what the previous successful runs were made under.
- Run 11:
	- **Produced error: `Fatal: parsing repository location failed: invalid backend\nIf the repo is in a local directory, you need to add a `local:` prefix\nopen repository`**
		- Seems ominous and, perhaps unsurprisingly, it was after this that the problems started.
	- (_Log: x9backup_restic_20201008-111701.log_)
- Runs 12 - 18:
	- All files seen as "new" but with "(0 B added)".
    - Killed the restic processes somewhere between "quickly" and ~12 hours, to try to troubleshoot. (To retry again each time via cron.)
    - **In the logged output, it didn't say `using parent snapshot [8-char snapshot ID nickname]` near the beginning, as it usually does.**
	- (_Logs: x9backup_restic_20201008-115501.log, x9backup_restic_20201008-122602.log, x9backup_restic_20201008-132001.log, x9backup_restic_20201008-163501.log, x9backup_restic_20201008-183501.log, x9backup_restic_20201008-183724.log, x9backup_restic_20201008-183949.log_)
- Run 19:
	- All files seen as "new" but with "(0 B added)".
	- **This time I let it complete (about 26 hours)**.
    - In the logged output, it didn't say `using parent snapshot [8-char snapshot ID nickname]` near the beginning, as it usually does.
	- (_Log: x9backup_restic_20201008-231901.log_)
- Run 20:
	- Success! All files seen as "unchanged".
	- Parent snapshot listed belonging to Run 19.
	- (_Log: x9backup_restic_20201010-085001.log_)
- Run 21:
	- Parent snapshot listed belonging to Run 20.
	- Only about 10% of the files backed up.
	- **At the very end there were 85 `scan: lstat _path_: no such file or directory` errors in a row.**
	   - It seems that restic was not able to get into the remaining directories, but it otherwise completed.
	       - Almost as if the volume went offline or something about 10% of the way through, which I've never seen before but is possible.
	       - Program is running under cron, therefore with root access.
	- (_Log: x9backup_restic_20201011-085001.log_)
- Run 22:
	- Parent snapshot listed belonging to Run 21.
	- About 10% of the files (the first ones) listed as "unchanged". The rest were "new", but "(0 b added)".
		- Which corresponds with the files that completed on the previous run.
	- (_Log: x9backup_restic_20201012-062301.log_)
- Run 23 - 26:
	- Parent snapshots listed belong to previous runs.
	- (_Log: x9backup_restic_20201014-030001.log, x9backup_restic_20201015-062301.log, x9backup_restic_20201016-030002.log_)
	- Success! All files seen as "unchanged". Seems we're back on track.

**Comment by MichaelEischer** [comment]
@jim-collier

> 1. After I added the `--ignore-inode` flag and put the job in `cron`, it appears to have been unable to read the local cache, with an error of `Fatal: parsing repository location failed: invalid backend...`. That began the first round of scanning everything anew, with no parent snapshot.

(Run 11) That error has nothing to do with the local cache, it is a fatal error which prevents restic from doing anything. After all restic was unable to decode the passed repository location. The local cache is not yet setup at that point. For the command line 
```
restic backup --verbose=2 -o b2.connections=8 -r ${b2Bucket}: --ignore-inode --exclude-caches --exclude-if-present .nobackup --cache-dir "/root/.cache/restic" --exclude-file "${excludeFilespec}"  "✽✽✽"
```
That error looks like `b2Bucket` was not set, as `:` would trigger that error message.

> 2. After I let it complete a run (rescanning all files), on subsequent jobs it settled in and resumed backing up normally, with parent snapshots and no rescans. But then at about 10% of the way through a backup, it was unable to read from the volume for some reason. (A highly reliable array but who knows.) _This appears to have had the side effect of wiping out the existing locally cached references, corresponding to what it couldn't read on the previous run_ - because on the next run, that initial ~10% of files were seen as "unchanged", and the remainder as "new", with "(0 B added)".

> * **At the very end there were 85 `scan: lstat _path_: no such file or directory` errors in a row.**

(Run 21) Did that run complete with a message similar to `processed 743386 files, 8.800 TiB in 26:41:50` and `snapshot 678804fb saved`? Did you take a look at the reported paths? Are those valid? Errors starting with `scan: ` should only affect the statistics in the progress bar. Unless there were also errors without the `scan: ` prefix then these shouldn't affect the backup itself.

> Possibly unnecessary, unless the narrative above seems mysterious.

Plain error messages are usually quite helpful for investigating issues.

**Comment by jim-collier** [comment]
@MichaelEischer thanks for analysis!

> That error looks like b2Bucket was not set, as : would trigger that error message.

Good catch. And very confusing (to me). Another eagle-eyed member caught that in reference to a previous unrelated issue, noting that `:` was inconsistent across restic commands in the same wrapper script. He said (or at least I potentially incorrectly remember that he said) it was _supposed_ to have the `:`. Only the backup command had the `:`, everything else (e.g. check, prune, list snapshots) didn't, so it was inconsistent. So I updated everything to have `:` at the end.

But here's the weird thing:

- During the time the problems started, and well before including over a dozen successful runs, _nothing in my wrapper script changed_ regarding inconsistent use of `:` at the end of the b2 bucket name. The commands without the `:` are things like listing snapshots, check, optional (and rare) use of prune, check. All runs contain some mix of multiple commands, at minimum doing a check, listing snapshots, and backing up. All backup commands - the only thing including `:` at the end, either succeed, or failed due to apparently other reasons.
- Before I started having this problem (at "Run 11"), there were dozens of successful runs (all with the inconsistent wrapper script). (Remember that starting the narrative at "Run 10" was arbitrary just to have easy named references - I didn't actually count the number of prior runs.)
- After the initial problem, when at least one successful run was finally made, the script still had the inconsistent `:`.
- On the second problematic run (involving directories not found), still had inconsistent `:`.
- On subsequent successful runs afterward when everything finally settled down, still same, had inconsistent `:`.
- When it was pointed out I had inconsistent use of `:`, I "fixed" (?) my script so that _all_ commnands used `:` at the end of the bucket name.
- The 4 subsequent runs after "fixing" the script were flawless.

I [see now](https://help.backblaze.com/hc/en-us/articles/115002880514-How-to-configure-Backblaze-B2-with-Restic-on-Linux) that the correct syntax is to _not_ have colons afterward.

Given that, it _seems_ as if the colon, or lack thereof, doesn't matter either way? (Either way I'm going to remove the colons in my script for general correctness.)

> (Run 21) Did that run complete with a message similar to processed 743386 files, 8.800 TiB in 26:41:50 and snapshot 678804fb saved?

Yes, here's that output.

```
20201011-091006 scan finished in 1193.076s: 57318 files, 830.881 GiB
20201011-091007 
20201011-091007 Files:           0 new,    13 changed, 50926 unmodified
20201011-091007 Dirs:            0 new,     4 changed,     0 unmodified
20201011-091007 Data Blobs:     44 new
20201011-091007 Tree Blobs:      5 new
20201011-091007 Added to the repo: 26.583 MiB
20201011-091007 
20201011-091007 processed 50939 files, 823.558 GiB in 19:54
20201011-091007 snapshot 676f25ed saved
```

The number of files reported is about 10% of a typical run. The remaining were in the directories it reported as not found. I tend to doubt that a failure so fundamental (e.g. not being able to traverse directories) would be a problem with restic.

If there's any actual "bug" here, it might be that _on the next run, it saw all those files it was unable to scan before (e.g. due to something low-level like the volume falling offline), as "new"_. The snapshot ID it created here, was listed as the parent on the next run?

**Comment by MichaelEischer** [comment]
The following two lines also show something interesting:
```
20201011-091006 scan finished in 1193.076s: 57318 files, 830.881 GiB
20201011-091007 processed 50939 files, 823.558 GiB in 19:54
```
The inaccessible files/folders were not just a one-time hickup affecting a single syscall, but the problem had to exist long enough to affect both the "scan" and the actual "backup". 

> If there's any actual "bug" here, it might be that _on the next run, it saw all those files it was unable to scan before (e.g. due to something low-level like the volume falling offline), as "new"_. The snapshot ID it created here, was listed as the parent on the next run?

The expected result would be that the latter backup run used the snapshot affected by the inaccessible files. And then it's expected behavior that most files were regarded as new, after all the parent snapshot doesn't contain these files.

As it looks like the backup run just couldn't access the missing files for some reason, I'm tempted to close this issue for now and see whether it shows up again?

**Comment by jim-collier** [comment]
@MichaelEischer 

> The snapshot ID it created here, was listed as the parent on the next run?

Yes, that's correct.

> The inaccessible files/folders were not just a one-time hickup affecting a single syscall, but the problem had to exist long enough to affect both the "scan" and the actual "backup".

I don't know restic's internal flow, but from what I can infer by a typical run's observed output, is this about what it is?:

1. Scan all of the directories and below, of those specified to be backed up (in this case as specified on the command line).
2. During that scan, build a list files to back up, ultimately integrating exclude rules.
3. Go through that final list and back up each one, and along the way (or possibly during step 1), determining:
    - If it needs to be [re-]scanned.
    - If so, if it needs to [re-]uploaded (with chunking presumably happening somewhere along the way).

If that's roughly the case, then it would appear that step 1 and 2 succeeded, but step 3 started failing at some point, mid-backup, when it suddenly couldn't access files it was expecting to find from step 2. (Because maybe some high-level folder got renamed mid-backup [not the case here], or the device became inaccessible mid-backup [which I'm guessing happened in this case].

If I'm still on a close-enough track, then it seems to me, the appropriate action would be:

- Continue trying until the source list from step 2 is exhausted, emitting warning for each inaccessible/not found error, without actually aborting. Kind of (but not exactly) as it seems to have done.
- "Carry over" (what/however that means) from the _parent_ snapshot, any file references and internal metadata that were available to step 2, but which for whatever reason weren't found in step 3.
    - I realize this may require a substantial refactor if even realistic at all.
    - I'm thinking in terms of what ultimately winds up existing in the local cache for the next run, so my terminology regarding snapshots may not be accurate.
        - Maybe it's more accurate to say (?), _don't delete references from the local cache, even if it failed in step 3, as long as it was available to step 2_.
- Axiomatically, **only remove items from the local cache - or whatever the next run needs to skip over already backed-up unchnaged files - if they weren't seen by step 2, ignoring errors from step 3**.

The thing that makes me question this logic, is the logged output when it started being unable to find files it appeared to be expecting to see. Rather than emitting warnings for the remaining ~700,00 files it couldn't reach, it only emitted like 85 more warnings, and it seemed to be more or less higher-level directories each line, as if it were crawling up out of a recursive tree. (Or something similar. Since I have no dirs nested 85 levels deep, that can't be _exactly_ it.)

Anyway, aside from my probably poor inferences about the internals, what do you think about my last bulletpoint above?

**Comment by MichaelEischer** [comment]
The scan step is only used to count the files and data size to backup (it never looks at the file content!). These counts are then used to print the backup progress. The backup loop itself is independent from the scan loop, so there's no intermediate file list. The backup loop walks the filesystem and in that process reads and uploads new/changed files. It also loads the metadata for the current folder from the parent snapshot and reuses it when possible. As in your case both the backup and the scan loop couldn't access the files, that would mean that both your step 2 and 3 wouldn't know about these files.

The local cache only caches data files which also exist in the backup repository, there's no magic happening here. It is only a performance optimization, restic works perfectly fine (but slow) when disabling the cache using `--no-cache`.

A backup run regards files as changed/unchanged/new depending on whether these were part of the last snapshot. Retaining the metadata for inaccessible files/folders would basically require restic to inaccurately represent a folder in the backup.

The (usual) cause of `lstat _path_: no such file or directory` errors are files which were moved away/deleted at exactly the wrong point in time. There's no point in keeping the metadata for such files/folders in the backup. The case that the backup source became inaccessible during the backup is not something restic should or can reasonably work around. In fact the backup source reported that these files no longer exist, which judging from your description means that it has returned **wrong data** which is just something that can't be handled. How should restic know whether `ENOENT` refers to a vanished file (more likely) or a broken data source?

**Comment by jim-collier** [comment]
OK that makes sense. I'll hit the close button. Thanks for taking the time and sharing your knowledge!
