### ISSUE TITLE
Don't treat entries in --files-from as glob definitions

### ISSUE THREAD

**Issue by jim-collier** [restic/restic#3005]
I know (e.g. [2448](https://github.com/restic/restic/issues/2448)) that there is already disagreement on whether this is a "bug", or a "feature request", and in fact globbing was explicitly introduced as a "feature" at some point into `--files-from`.

My argument is that, given that no other software on Earth that I could find treats lines in a `--files-from` (or analogous feature) as glob specifications, Restic shouldn't either, and it's a bug.

But if you'd rather consider it a new feature request, fine with me - something like:

- A new flag that doesn't glob, e.g. `--files-raw-from`, and/or
- An environment variable that overrides `--files-from` default behavior so as to not glob

Why?

1. As far as I know and have been able to determine through google (surely with some obscure exceptions), all other software with such a flag expects the list to be a plain 1:1 raw dump of _exact_ file path specifications (whether absolute or relative).
1. The writers of such software know that such lists are generated by _some other tool_. Not by hand-crafting glob specifications.
    - Hand-crafted wildcard specifications are literally what a completely different set of related features are for: pattern-based "exclude" and "include" arguments and file pointers. Rsync, for example, supports at least _six_ variations of specifying pattern-based includes, excludes, and mixed definitions.)
1. The Linux way is "Do One Thing Well", and chain together the tools you need.
1. Treating `--files-from` entries as glob specifications, introduces unexpected errors, violating the principle of "least surprise". As I discovered, with brackets in filenames - which I now have to jump through additional hoops to programmatically process and escape.
    - There's deep personal irony here. The reason I have so many brackets in filenames, is because long ago when using primarily Windows, parentheses in filenames caused (and still does) errors in Windows CMD processor's half-baked attempt at a modern-ish "if exist fileX ( thenY )" branching syntax. So now with brackets instead of parentheses, I'm getting bugs in Windows. (Well at least these are solvable by escaping.)

As an example of what programs typically expect, when using `rsync`, `rclone`, and numerous other tools, users and admins often:

- Generate a list of regular (non-symlink/socket/named pipe) files, filtered by date or size, with something like `find . -f | sort > filelist1.txt`.
- Filter that list with something like `grep -iPv ".*\/local\/Trash\/.*" filelist1.txt > filelist2.txt` (etc.) As many times as necessary.
- `rsync --files-from filelist2.txt source/ dest/`

Why do users and administrators do that? Because as we all finally know by now, `rsync`s include/exclude syntax was carefully designed by the demons from "The Good Place", to torture a large swath of humanity and bring literally endless human suffering.

(I'm even writing a [utility](https://github.com/x9-testlab/x9incexc-bash) to generate such simple raw-dump-of-files list. [Surely others exist, seems like an obvious idea, but I haven't managed to find an existing, dedicated FLOSS one.] Benefits over, for example, `rsync`s arcane include/exclude syntax: Uses regex; user-definable regex macros; reverses the logic of rsync broaden/narrow filtering which is really hard to grasp and debug.)

Anyway the point is, treating a programmatic file list dump as a hand-crafted list of glob definitions, I feel was an objectively incorrect decision specifically intended to torture users.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes! Fix this issue, and drastically improve `prune` performance (I know it's in the works), and add `--iexclude-file`; and we'd have the One True Superior Backup Solution! Oh also, compression might be nice, but I feel that's less important than most people realize and more of a shopping list item, what with deduplication, and data file formats increasingly designed to already be as dense as possible. (Except for things like VM images.)

Edits: Bad at grammar and formatting.

**Comment by jim-collier** [comment]
@MichaelEischer 

Partially. If you consider these two issues a Venn diagram, there is some overlap in terms of topics discussed. But _not_ the purpose. One is a bug report of an existing feature. The other is asking for new feature that is completely different.

Although well-written, [that issue](https://github.com/restic/restic/issues/2944) is _obviously a feature request for **new functionality**_. And _not_ about fixing `--files-from`.
    1. Specifically, a his feature request is about parsing a JSON array containing wildcards.
    1. His opening description and later clarification hints at some of the problems this issue specifically addresses and calls a bug: glob characters causing problems in `--files-from` - but in his issue only in an incidental way.
    1. His feature request is a workaround for the problem that this issue addresses head-on, via completely new and different functionality.

More than one issue mentioning the same problem, doesn't make them duplicates. One issue might be "Fix the bug in the anti-lock-brakes program", a second issue might be "Add airbags so that when the brakes fail due to the ABS bug, there's a little less dying." Both are valid issues by themselves.

**Comment by MichaelEischer** [comment]
@jim-collier 
> The other (#2944) is asking for a _new feature_ that is completely different - only in part to work around the very same bug, but it's also an interesting feature idea on it's own, independent of any bug.
> 
>     1. Specifically, his feature request is about parsing a JSON array containing wildcards.

The issue description explicitly mentions both JSON _and_ null-byte terminated lines. Your suggested `--files-raw-from` variant is just a slightly different format to specify the file (i.e., using new lines as separators instead of the null-byte). The second comment in #2944 also lists variants used by other backup/file transfer programs, which also includes `--files-from-raw`.

>     2. His opening description and later clarification hints at some of the problems this issue specifically addresses directly and calls a bug: glob characters causing problems in `--files-from`.

The opening description also explicitly asks for restic not to interpret the file paths as globs. Just removing the interpretation of glob characters still leaves trimming and comments `#` as potential problems, so we'd also need a solution to handle that behavior. That is just removing the globbing still leaves a few special cases around, such that we have to discuss the variants mentioned in #2944 anyways. I don't see why we should break compatibility of an existing feature when a new option `--files-from-raw` (or special line prefixes as in borg) would be perfectly fine. As there is also a use-case for glob expansion (#1891 and maybe others), I'd say the `--files-from` option works as expected.

>     3. His is a feature request with a completely new and different feature idea, only in part as a workaround to the problem that this issue solely addresses. But his idea also happens to be a valid feature request, even if this bug were fixed and closed.

We don't want to have multiple different ways in restic to solve the same problem. That is we can't handle these two issues in isolation anyways. And if we'd have to break compatibility it would still be preferable to not do so repeatedly.

> More than one issue mentioning the same problem, doesn't automatically make them duplicates. One issue might be "Fix the bug in the anti-lock-brakes program", a second issue might be "Add airbags so that when the brakes fail due to the ABS bug, there's a little less dying." Both are valid issues by themselves. That's not always the case obviously - a workaround feature request might be completely moot if the bug issue is fixed and closed. But in this case - as purposely illustrated in this contrived example - they're both valid issues independently.

From my point of view we're discussing here whether to solve the ABS bug via solution A or B, with B being the comprehensive solution. Or in other words I still consider this issue to be a subset of #2944 (that's what I meant with "full duplicate").

**Comment by jim-collier** [comment]
@MichaelEischer I disagree with your analysis, but I do recognize (and appreciate) the inescapable fact that you've had eyes on this and the web of related issues far longer and intently than I, so I don't have much of a leg to stand on to keep flogging it.

I can however, disagree with (what I believe is) a fair degree of experience & subject matter expertise, over your assertion that

> the --files-from option works as expected

Definitely doesn't. Well, IMO. However, there's an implied "works as expected _for ..._" in there. Presumably, "for me ([meaning you](https://www.youtube.com/watch?v=wX1x7pfH8fw))". If so, then of course  that's not debatable. But for most others working in this general administrative or pseudo-administrative filesystem space, I could name half a dozen respected utilities or more that don't behave that way, and zero that do - in support of the notion that, for _most_ such people, it's not working as expected.

The top of that list is the legendary `rsync`, which has exented CLI interface standards for batchey-filey tools, for 2 or 3 human generations now, used by millions. So by saying that globbing is expected behavior, you're essentially arguing that `rsync`'s behavior for `--files-from` is _not_ expected behavior, since in the context of this narrow behavioral discussion, they are opposites by definition.

I mean look, I'm in not at all married to the redefining how `restic --files-from` works. It's pretty well established that changing what CLI interfaces do, in general, can break user scripts - and is really bad. That's arguably more important than being consistent with big-sister utilities and industry conventions. (Unless of course zero users currently rely on hand-crafted globbing behavior in `--files-from`. Which I'm guessing is impossible to know.)

In other words, I'm perfectly fine with having a new and different flag. (As referenced in my opening acknowledgement of more or less, "is this issue a bug report or new feature request?").

My only real "concern" here, is confusing this extremely narrow problem (treating a raw dump of file paths as individually hand-crafted glob statements), with talk about JSON, null-terminate strings, etc. It's clear the author spent time and care crafting the issue, but I'm _still_ not clear on exactly what end-state he would most ideally like to see. (Fair enough to say the same about my issues generally.)

Whereas this issue, if anything, is at least crystal clear on that: 

**_Either ditch the globbing logic in `--files-from`, or introduce a new flag that does, e.g. `--files-from-raw`_**.

Also, you mentioned the question of how to handle comments. And that highlights a key difference - I think - in how we perceive how `--files-from` should be interpreted. In `rsync` for example, _there explicitly is to be no comments, or anything that isn't a file path, not even empty lines or spaces that aren't part of a filename_. It's a raw text based list of files, terminated with newlines. Either the filespec listed on each line is a file, or it is assumed to no longer exist as one by that literal path. (And `rsync --files-from` does not, to my knowledge, deal with newlines in filenames. Either each individual line exists as an exact filename path, or it doesn't.)

To be fair, `rclone` does allow comments in `--files-from` and does some other very minimal preprocessing (e.g. leading spaces). But importantly, not globbing! _A straight dump of raw filenames will always work_.

`rclone --files-from-raw`, OTOH, is functionally identical to `rsync --files-from`, at least in what it expects of the actual contents. And, as far as I can tell, also doesn't correctly interpret newlines in filenames.

Well I've made my case, probably can't state it better, so if you still disagree and want to close this, I'll still disagree but can appreciate your desire to minimize the number of issues etc. It's never a perfect process, I'm not a direct contributor, nobody is getting paid here, and we don't always get what we want ;-) And there are considerably bigger problems in the world.

As for handling newline characters in filenames, I'm at a loss. That's a _much_ bigger issue than either of us or restic. Probably across time and space. I've never dealt with it before, personally, in spite of knowing it's possible. (Which is not the same as saying I know for sure I have, or manage, zero filenames with newlines! I've seen alot of strange stuff.) I know rsync can be _made_ to deal with newlines in names, but not in an obvious straightforward way, and not involving `--files-from`. As much as I hate suggestions of ad-hoc "preprocessing" kludges to fix another program's "flaws" (e.g. having to globally escape brackets in the filenames dump so that they don't glob in restic!), in this edge case it might suffice to say, "fix your filenames with newlines before doing anything else - in general, restic or not". Shouldn't be too hard to automate with a bash one-liner. That said, I'm happy to just say "I don't know" when it comes to newlines and be OK with it!

**Comment by jim-collier** [comment]
BTW if it would help clarify things if I change the title of this issue to "Add `--files-from-raw` feature", and remove mentions of `--files-from` having a "bug" or unexpected outcome, I'm more than happy to do so. That might also address your understandable heartburn of overlapping discussion of `--files-from` in other issues that discuss it.

**Comment by jim-collier** [comment]
With #3013, this can be closed.
