### ISSUE TITLE
[docs] Installation chapter doesn't mention Alpine Linux

### ISSUE THREAD

**Issue by bittner** [restic/restic#3010]
Expected behavior
-----------------

Restic's official documentation should mention how latest stable Restic is installed on Alpine Linux. [pkgs.org](https://pkgs.org/download/restic) lists the latest Alpine package, so it seems to be prepared for proper installation on Alpine.

Actual behavior
---------------

- [The latest generated docs](https://restic.readthedocs.io/en/latest/020_installation.html) don't mention Alpine.
- Same for [doc/020_installation.rst](https://github.com/restic/restic/blob/master/doc/020_installation.rst).
- Running `apk add restic` succeeds to install Restic, but - for example on the `python:3.8-alpine` image - only pulls in version 0.9.6-r1:

```console
$ restic version
restic 0.9.6 compiled with go1.13.10 on linux/amd64
$ apk info restic
restic-0.9.6-r1 description:
Fast, secure, efficient backup program

restic-0.9.6-r1 webpage:
https://restic.net/

restic-0.9.6-r1 installed size:
23924736
```

Do you have an idea how to solve the issue?
-------------------------------------------

Do you want a PR to add the missing information to the Installation chapter, or is there a reason why this has been left out?

What would be the correct (Alpine-specific) instructions for adding the latest stable `restic` package to Alpine?

**Comment by rawtaz** [comment]
Since we're listing a whole bunch of other distro's install instructions it's hard to argue against this one :P I opened a PR, let me know if you think it looks right or not!
