### ISSUE TITLE
Restic stuck on FUTEX_WAIT_PRIVATE

### ISSUE THREAD

**Issue by phochs** [restic/restic#3012]
Hi! I'm experiencing restic getting stuck with it's backup. Details are listed below. Haven't done bug reports before, so please let me know if something is missing.

Output of `restic version`
--------------------------
`restic 0.10.0 compiled with go1.15.2 on linux/amd64`

How did you run restic exactly?
-------------------------------
`restic -r sftp:restic-backup@10.2.2.10:/backup/restic/host backup --ignore-inode --exclude-caches --with-atime --tag host-client --exclude *.tmp --exclude *.log* /storage/docker/<path1> /storage/docker/<path2> /storage/docker/<pathn>`

```
enter password for repository:
repository <repo> opened successfully, password is correct
found 4 old cache directories in /home/restic-backup/.cache/restic, run `restic cache --cleanup` to remove them
error: open /storage/docker/<file>: permission denied
error: open /storage/docker/<file>: permission denied <14 more of these lines>
[23:54] 325 files 142.790 MiB, total 338 files 142.863 MiB, 15 errors
/storage/docker/<file>
/storage/docker/<file>
```

I also ran `strace -p PID`, which output:
```
strace: Process 14229 attached
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
nanosleep({tv_sec=0, tv_nsec=3000}, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc00004e548, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0xc00004e548, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
epoll_pwait(4, [], 128, 0, NULL, 1)     = 0
futex(0xc000180d48, FUTEX_WAKE_PRIVATE, 1) = 1
sched_yield()                           = 0
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 0
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 0
futex(0x15898f0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc000080948, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 2109448
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 2109441
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1215
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 2109442
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 5
getdents64(12, /* 99 entries */, 8192)  = 8120
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
getpid()                                = 14229
tgkill(14229, 14514, SIGURG)            = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
epoll_pwait(4, [], 128, 0, NULL, 18446744073709551615) = 0
futex(0x158bad8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x158b9d8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x158baf0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000}) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0x158bad8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x158b9d8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0x158bad8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x158b9d8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 0
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(0, TIOCGPGRP, [14225])            = 0
getpgid(0)                              = 14225
write(1, "\r\33[2K[20:23] 325 files 142.790 M"..., 74) = 74
write(1, "\r", 1)                       = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
ioctl(0, TIOCGPGRP, [14225])            = 0
getpgid(0)                              = 14225
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 14225
write(1, "\r\33[2K[20:24] 325 files 142.790 M"..., 74) = 74
write(1, "\r", 1)                       = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(0, TIOCGPGRP, [14225])            = 0
getpgid(0)                              = 14225
write(1, "\r\33[2K[20:28] 325 files 142.790 M"..., 74) = 74
write(1, "\r", 1)                       = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=14229, si_uid=1005} ---
rt_sigreturn({mask=[]})                 = 15802842
ioctl(1, TIOCGWINSZ, {ws_row=64, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0xc01d738548, FUTEX_WAKE_PRIVATE, 1) = 1
ioctl(0, TIOCGPGRP, [14225])            = 0
getpgid(0)                              = 14225
write(1, "\r\33[2K[20:32] 325 files 142.790 M"..., 74) = 74
write(1, "\r", 1)                       = 1
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x158c588, FUTEX_WAIT_PRIVATE, 0, NULL^Cstrace: Process 14229 detached
```

In a different issue I saw the request for exiting the command with `ctrl + \`, which output this: https://pastebin.com/HLNqT3zR (pastebin because of it's enougmous size).

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
I'm using SFTP over a local network.

Expected behavior
-----------------

Going through all files in the source folders, and creating backups of them.

Actual behavior
---------------

At file 325 it gets stuck, and remains there for over an hour. Sometimes it continues, but that isn't consistent. The 325 is consistent.

Steps to reproduce the behavior
-------------------------------

It happens consistently, regardless of repository. The file number does change when switching repos.

Do you have any idea what may have caused this?
-----------------------------------------------

I think it gets stuck, maybe waiting for I/O, or something is timing out.

Do you have an idea how to solve the issue?
-------------------------------------------

Absolutely no clue.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

It finally made me switch away from Syncthing for my personal backups. It has been poorly performing for months, meaning I didn't/don't have backups. When restic starts working this will be my go-to backup solution, it's options are amazing!

**Comment by fd0** [comment]
I've got no idea where restic is stuck. Maybe we'll get more information if you run strace on all threads via `strace -f`. The Go runtime uses many different OS threads under the hood, and `strace -p` by default only traces a single one of them.

Some questions to dig into:
 * Can you run restic with `strace -f -o /tmp/log` or so?
 * What is on the other side of the sftp connection? OpenSSH? A NAS?

**Comment by MichaelEischer** [comment]
@phochs On which type of filesystem are the `/storage/docker/<path1>` paths stored? I wonder whether we're seeing something similar to the problems between Go and CIFS. You could try setting the environment variable `GODEBUG="asyncpreemptoff=1"`.

**Comment by phochs** [comment]
@fd0 Output from `strace -f -o /tmp/log -p PID` reads this: https://pastebin.com/gJfnb9E1
The servers are both Debian 10 servers, I'm running the connection over OpenSSH.

@MichaelEischer The folder /storage is mounted as a ZFS share. It has this configuration:
```
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
storage  10.9T  5.67T  5.20T         -    40%    52%  1.00x  ONLINE  -
```

**Comment by MichaelEischer** [comment]
@phochs Did you try setting the GODEBUG environment variable? The strace log is quite boring: it shows the status prompt updates for 3 or 4 seconds and that the backup and scanner goroutine have listed about 15k directory entries from a single folder. There is not backend communication contained in the strace log. Do you have a folder with hundreds of thousands (or rather millions) of files?

**Comment by phochs** [comment]
Sadly the GODEBUG didn't change it getting stuck.
There are no folders which have that many files inside them. In total I have 32.136.509 files in the /storage directory, but not all are in the Restic backup paths up and they are spread in thousands of folders.

**Comment by MichaelEischer** [comment]
@phochs Can you generate another strace log with that environment variable set? Please also attach a stacktrace which you get by killing restic by sending it a SIGQUIT/SIGABRT. I've no clue yet what's going on.

32 millions and 6 TB shouldn't be a problem, you'll need about 5-10GB RAM for restic, but besides that it should just work.

**Comment by JaseKing** [comment]
We have a similar issue; restic stuck on FUTEX_WAIT_PRIVATE when backing up to B2.

We started seeing this issue on since upgrading to `restic 0.10.0 compiled with go1.15.2 on linux/amd64`

`export RESTIC_CACHE_DIR="/data/tmp/restic/cache"`
`/usr/bin/restic -r b2:pitr-prod:barman-repo backup --cache-dir $RESTIC_CACHE_DIR /var/lib/barman`

`strace` output with `GODEBUG=asyncpreemptoff=1` set:

[strace.log.gz](https://github.com/restic/restic/files/5474829/strace.log.gz)

**Comment by MichaelEischer** [comment]
@JaseKing That strace log looks like restic is still busy doing something. Can you provide the stack traces printed by restic after you've sent the SIGABRT signal?

In the log restic seems to read/write single null bytes from fd 5 and 6 (you might take a look at the output of `ls -la /proc/<pid of restic>/fd` for another stuck restic run whether that shows something suspicious). And fd 8 is busy reading/writing small TLS frames. So it looks like restic keeps receiving an error (?) from b2.

Please build restic using `go build -tags debug ./cmd/restic`. Then run restic with the environment variable `DEBUG_LOG=debug.log`. The debug log will contain lots of http requests and replies. Before you post any of these, _make sure to remove any authentication credentials or other sensitive data from the http headers_.

**Comment by fd0** [comment]
Adding `--decode-fds` to `strace` will make it print the file system object an fd is connected to...

**Comment by JaseKing** [comment]
@MichaelEischer Thanks for getting back to me.  I've not had chance to look into why yet but the issue stopped occurring about 3 days ago, backup times had jumped up to taking 3 days but are now back down to the around 11 hours its been taking since we started using Restic.  I've not changed restic or the host its running since my original comment.

If the issue re-occurs I'll endeavour to collect the info you need.

In the meantime; thanks for the help and thanks to all the devs for restic.

**Comment by MichaelEischer** [comment]
Closing this issue as there's currently nothing left to do. @phochs Feel free to reopen this issue when you can provide a stacktrace.
