### ISSUE TITLE
Separate environment variables for user/pass for rest backend

### ISSUE THREAD

**Issue by davidsmf** [restic/restic#3021]
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.12.5 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

As well as supporting user/password in the URL for a "rest:" backend, allow the username/password to 
be provided in environment variables e.g. `REST_SERVER_PASSWORD`

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I'm trying to use generated passwords (or user-provided), in a helm template, and helm doesn't appear to have
a function that will safely encode passwords with characters with meaning in URLs, like `@`, `]`, `:` or `/`. If I can create a 
second environment variable it's much easier to get the escaping right.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It's a really nice simple way of backing up to a variety of backends.

**Comment by MichaelEischer** [comment]
Fixed by https://github.com/restic/restic/pull/4480
