### ISSUE TITLE
Filecoin as a storage backend 

### ISSUE THREAD

**Issue by RubenKelevra** [restic/restic#3037]
I like to use filecoin as backend for restic, since the price per TB is very attractive compared to many other alternatives. 

Storing 1 TB for a year is currently at $ 3.16. [Source](https://twitter.com/Filecoin/status/1318697992656924675?s=19)

**Comment by rawtaz** [comment]
Thanks for the suggestion. It's highly unlikely that this will be implemented in the foreseeable future, as this is the first time we've heard of this, and there's many other and older feature enhancements and issues to deal with. Just to be realistic ;)

**Comment by fd0** [comment]
I'm closing this issue for now, maintaining a new backend means much work for us as maintainers. Please feel free to add further comments. Thanks!
