### ISSUE TITLE
Misleading representation of tags that contain a comma

### ISSUE THREAD

**Issue by OJFord** [restic/restic#3040]
Output of `restic version`
--------------------------

```
restic 0.10.0 compiled with go1.15.2 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

If, by user error or otherwise (:blush:), one sets a tag such as `backup --tag=foo,bar`, perhaps under the misguided belief that this will set two comma-separated tags, the output of `snapshots` makes it appear that they were correct e.g:
```
$ restic backup --tag=foo ./a
$ restic tag --add=bar dead
$ restic backup --tag=foo,bar ./b
$ restic snapshots
dead time host foo,bar /home/idiot/a
beef time host foo,bar /home/idiot/b 
```

But of course, they were not:
```
$ restic snapshots --tag=foo
dead time host foo,bar /home/idiot/a
$
```

I think creating such tags should either be completely disallowed, or when represented in `snapshots` output (for example) the comma should be 'escaped' for reading, such as `foo\,bar`, making it clear something's gone probably not as intended; or if, for some (probably not good!) reason it was intended, it makes clear that it _did_ go as intended, and is not a tag-separator per the other lines.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

This would prevent mis-tagging snapshots as `["a,b"]` where `["a", "b"]` was intended.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I realised my mistake by actually reading the docs properly (:blush:) which do make this clear, and the `--tag` filtering & `tag` subcommand made it pretty easy to rectify.

**Comment by MichaelEischer** [comment]
The plan is to change at least the `backup` command to properly split tags containing commas, see #2690.

**Comment by MichaelEischer** [comment]
Closing this issue as the behavior of options that process tag lists was unified in #2690 to always split tags containing commas. The changelog documents how to fix mistagged snapshots.
