### ISSUE TITLE
Some zsh completions don't work

### ISSUE THREAD

**Issue by jivanpal** [restic/restic#3044]
Output of `restic version`
--------------------------
restic 0.10.0 compiled with go1.15.2 on linux/amd64

How did you run restic exactly?
-------------------------------
N/A; this concerns zsh completions. In cases where the completion doesn't work, the zsh output is of the following form:

```
_arguments:comparguments:<zsh completion script line number>: invalid option definition: <zsh completion script line>
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
N/A

Expected behavior
-----------------
Show completions for all commands

Actual behavior
---------------
Zsh reports an error when trying to complete some commands, as above

Steps to reproduce the behavior
-------------------------------
Installed restic on Ubuntu 20.04 by downloading the 0.10.0 binary and putting it in `/usr/local/bin`. Generated the zsh completions with `restic generate --zsh-completion=/usr/local/share/zsh/site-functions/_restic`. Reloaded the shell; the line `autoload -Uz compinit && compinit -u` is in my `~/.zshrc`.

Do you have any idea what may have caused this?
-----------------------------------------------
The issue seems to lie upstream in Cobra, but I thought I'd mention it here. Characters in the documentation appear in the generated zsh completion script that should be escaped, but are not. For example, square brackets in the documentation that denote optional arguments to commands are not escaped, such as:

```
function _restic_backup {
  _arguments \
  # <snip>
  '*--exclude-if-present[takes `filename[:header]`, exclude contents of directories containing filename (except filename itself) if header of that file is as provided (can be specified multiple times)]:' \
  # <snip>
}
```

```
function _restic_forget {
  _arguments \
  # <snip>
  '--tag[only consider snapshots which include this `taglist` in the format `tag[,tag,...]` (can be specified multiple times)]:' \
  # <snip>
}
```

```
function _restic_stats {
  _arguments \
  # <snip>
  '--tag[only consider snapshots which include this `taglist` in the format `tag[,tag,...]` (can be specified multiple times)]:' \
  # <snip>
}
```

Do you have an idea how to solve the issue?
-------------------------------------------
The above snippets of the form `<flag>[<description>]:` should have square brackets that appear in `<description>` escaped. For example:

- `filename[:header]` should be `filename\[:header\]`; and
- `tag[,tag,...]` should be `tag\[,tag,...\]`.

Editing the script as such resolves the issue. I am not sure if other such problematic characters appear in the script; I only encountered this issue when typing `restic forget <TAB>`, and after inspecting the completion script, also noticed that it happens with `restic backup <TAB>` and `restic stats <TAB>`, as exemplified by the script excerpts above.

Looking at the code, the culprit seems to be `cmd_generate.go`, in `writeZSHCompletion()`, where there is a call to `cmdRoot.GenZshCompletionFile()`. As such, I expect this is an issue in Cobra, but perhaps you can resolve the issue here first by taking the output of `#GenZshCompletionFile()` and `sed`'ing it or similar to escape such problematic characters. I don't know Golang, so just spitballing.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is fabulous! I use it to do personal backups to an external hard drive, and hourly incremental backups of my servers to Wasabi S3, and just used it today to recover from an unexpected website issue that a client had; rolled back and sorted everything within a couple hours. Thanks for the excellent tool!

**Comment by fd0** [comment]
Thanks for the report. This will probably need to be fixed in the library we're using for CLI as well as generating the completions, it's https://github.com/spf13/cobra

**Comment by Syphdias** [comment]
I just stumbled into this bug, found that the unescaped brackets were the culprit and then found this issue.
I don't know much about go but I tried to dig into cobra to find the place where the zsh completion was generated and only found [this](https://github.com/spf13/cobra/blob/f64bfa1e08c3199f3e740b5f96a9dd07b727c368/zsh_completions.go#L78) (current [master](https://github.com/spf13/cobra/blob/master/zsh_completions.go#L78) which looks quite different.

Then I discovered [doc/zsh-completion.zsh](https://github.com/restic/restic/blob/c5300a2c56c7206b4062abd3bde438e02d4e64e8/doc/zsh-completion.zsh) which I thought was generated in the build process (by cobra) – which it is clearly not. So I assume you, @fd0, generated it by hand (via cobra).

I'm not sure how to retrigger that generation but since it is commited as a regular file and not dynamically generated, I'd suggest applying a patch to the static file until cobra is fixed.

This should do the trick
```zsh
sed -i -E 's#\[(.*)\[(.*)\](.*)\]#[\1\\[\2\\]\3]#' doc/zsh-completion.zsh
```
```diff
diff --git a/doc/zsh-completion.zsh b/doc/zsh-completion.zsh
index 2b2100d5..64e9636f 100644
--- a/doc/zsh-completion.zsh
+++ b/doc/zsh-completion.zsh
@@ -151,7 +151,7 @@ function _restic_backup {
     '(*-e *--exclude)'{\*-e,\*--exclude}'[exclude a `pattern` (can be specified multiple times)]:' \
     '--exclude-caches[excludes cache directories that are marked with a CACHEDIR.TAG file. See https://bford.info/cachedir/ for the Cache Directory Tagging Standard]' \
     '*--exclude-file[read exclude patterns from a `file` (can be specified multiple times)]:' \
-    '*--exclude-if-present[takes `filename[:header]`, exclude contents of directories containing filename (except filename itself) if header of that file is as provided (can be specified multiple times)]:' \
+    '*--exclude-if-present[takes `filename\[:header\]`, exclude contents of directories containing filename (except filename itself) if header of that file is as provided (can be specified multiple times)]:' \
     '--exclude-larger-than[max `size` of the files to be backed up (allowed suffixes: k/K, m/M, g/G, t/T)]:' \
     '*--files-from[read the files to backup from `file` (can be combined with file args/can be specified multiple times)]:' \
     '(-f --force)'{-f,--force}'[force re-reading the target files/directories (overrides the "parent" flag)]' \
@@ -381,7 +381,7 @@ function _restic_forget {
     '--keep-within[keep snapshots that are newer than `duration` (eg. 1y5m7d2h) relative to the latest snapshot]:' \
     '--keep-tag[keep snapshots with this `taglist` (can be specified multiple times)]:' \
     '*--host[only consider snapshots with the given `host` (can be specified multiple times)]:' \
-    '--tag[only consider snapshots which include this `taglist` in the format `tag[,tag,...]` (can be specified multiple times)]:' \
+    '--tag[only consider snapshots which include this `taglist` in the format `tag\[,tag,...\]` (can be specified multiple times)]:' \
     '*--path[only consider snapshots which include this (absolute) `path` (can be specified multiple times)]:' \
     '(-c --compact)'{-c,--compact}'[use compact output format]' \
     '(-g --group-by)'{-g,--group-by}'[string for grouping snapshots by host,paths,tags]:' \
@@ -760,7 +760,7 @@ function _restic_stats {
     '(*-H *--host)'{\*-H,\*--host}'[only consider snapshots with the given `host` (can be specified multiple times)]:' \
     '--mode[counting mode: restore-size (default), files-by-contents, blobs-per-file or raw-data]:' \
     '*--path[only consider snapshots which include this (absolute) `path` (can be specified multiple times)]:' \
-    '--tag[only consider snapshots which include this `taglist` in the format `tag[,tag,...]` (can be specified multiple times)]:' \
+    '--tag[only consider snapshots which include this `taglist` in the format `tag\[,tag,...\]` (can be specified multiple times)]:' \
     '*--cacert[`file` to load root certificates from (default: use system certificates)]:' \
     '--cache-dir[set the cache `directory`. (default: use system default cache directory)]:' \
     '--cleanup-cache[auto remove old cache directories]' \
```

**Comment by Syphdias** [comment]
PS: Since [doc/zsh-completion.zsh](https://github.com/restic/restic/blob/c5300a2c56c7206b4062abd3bde438e02d4e64e8/doc/zsh-completion.zsh) was last touch on 2020-11-05 this might have been fixed in cobra and only needs a proper regeneration. But again. I'm not sure how.

**Comment by MichaelEischer** [comment]
@Syphdias The zsh-completions are regenerated when releasing a new restic version. You can use `restic generate --zsh-completion completion-filename` to regenerate it manually.

**Comment by MichaelEischer** [comment]
The generated zsh completions have change completely starting from restic 0.12.1
