### ISSUE TITLE
Restic outputs invalid UTF-8 when printing long UTF-8 file names to stdout when the terminal is small

### ISSUE THREAD

**Issue by DarkKirb** [restic/restic#3046]
Output of `restic version`
--------------------------
restic 0.10.0 compiled with go1.15.3 on linux/amd64

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local/SFTP doesn't matter it's a frontend issue

Expected behavior
-----------------
filenames are truncated without cutting utf8 characters in half

Actual behavior
---------------
filenames are truncated and displayed with a replacement character at the end as if a utf8 character was cut in half

Steps to reproduce the behavior
-------------------------------
The following shell script, if run in a shell that is very narrow (for example termux on android), will output the partial filename as intended, but depending on width will output the file name of two of these directories will also show an �, indicating that invalid utf8 was printed out

```sh
export RESTIC_PASSWORD=1
mkdir 'ああああああああああああああああああああああああああああああああああ'
truncate -s 2G ああああああああああああああああああああああああああああああああああ/data
cp -r ああああああああああああああああああああああああああああああああああ aああああああああああああああああああああああああああああああああああ
cp -r ああああああああああああああああああああああああああああああああああ aaああああああああああああああああああああああああああああああああああ
rm -rf repo
restic -r repo init
restic -r repo backup *ああああああああああああああああああああああああああああああああああ
```

Do you have any idea what may have caused this?
-----------------------------------------------
something about filenames being handled as byte strings instead of regular strings (like they should except ideally not in the frontend)?

Do you have an idea how to solve the issue?
-------------------------------------------
try to decode the string as utf8 before trimming it

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
restic imo just works :tm: and has a binary release on basically every platform i actively use. Almost exactly maps to how i want to do backups, especially since #2606 was merged. Am using it to manage around 500GB of data on two repositories (one on a local external hard disk and one on backblaze, uploaded regularly) and it already has come in handy both after mistakes and reinstalling the OS

**Comment by MichaelEischer** [comment]
For output of the backup command that's probably caused by this line: https://github.com/restic/restic/blob/bb4b3481a655237f1b308f799d31c387c21b3691/internal/ui/termstatus/status.go#L282

We could use `strings.ToValidUTF8()` to just remove invalid UTF-8 characters. Maybe Go also has a function to shorten a string to a certain length? (although I'm not sure whether non-ascii UTF8 characters in a terminal are always one ascii character wide or not).

**Comment by DarkKirb** [comment]
characters with the east asian wide width property are typically rendered as double-width, this is (mostly, but not limited to) all cjk ranges, in c the wcwidth function returns how many columns are needed, here is an open source implementation of it https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c but i wouldn't be surprised if go didn't offer something similar
