### ISSUE TITLE
`restic forget` hangs indefinitely

### ISSUE THREAD

**Issue by andreasnuesslein** [restic/restic#3047]
Output of `restic version`
--------------------------
restic 0.10.0 (v0.10.0-138-g96a912b6) compiled with go1.15.2 on linux/amd64

How did you run restic exactly?
-------------------------------

`['restic', '-r', 'sftp:***@****:repo.restic', 'forget', '--keep-last', '40', '--keep-hourly', '4', '--keep-daily', '30', '--keep-weekly', '30', '--keep-monthly', '12']`

the weird format is because, and I'm assuming this is relevant: I'm spawning restic with a python `Popen` call. https://github.com/sinnwerkstatt/runrestic/blob/master/runrestic/restic/tools.py#L53

It used to work, but at some point it stopped working for multiple machines of mine. I can't _really_ find a reason why some work and others don't. It might be that the output of the ones that hang is just longer (more text).

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

it's sftp (with openssh-server)

Expected behavior
-----------------

restic should return

Actual behavior
---------------

it's hanging (I can't really see the output :S) but `strace -f -p $(pidof restic)` is just stuck on 
```
strace: Process 21245 attached with 15 threads
[pid 21259] futex(0xc00011a148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 24105] futex(0xc00268c148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 21262] futex(0xc002680148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 21261] futex(0xc002600148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 21260] futex(0xc0025c0148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 21257] futex(0xc00005d548, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 21253] futex(0xc000198148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 21252] futex(0xc000080948, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 21251] futex(0xc00005cd48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 21250] futex(0x1653c98, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 21249] futex(0x1653498, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 21248] futex(0x1653498, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 21247] futex(0x1653498, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 21245] write(2, "syscall", 7 <unfinished ...>
[pid 21246] futex(0x1653498, FUTEX_WAIT_PRIVATE, 2, NULL
```

a `SIGQUIT` will add:
```
[pid 21250] <... futex resumed> )       = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
[pid 21250] --- SIGQUIT {si_signo=SIGQUIT, si_code=SI_USER, si_pid=13437, si_uid=0} ---
[pid 21250] sched_yield()               = 0
[pid 21250] futex(0x1653498, FUTEX_WAIT_PRIVATE, 2, NULL
```

and a `SIGABRT`:
```
 <unfinished ...>
[pid 21251] <... futex resumed> )       = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
[pid 21251] --- SIGABRT {si_signo=SIGABRT, si_code=SI_USER, si_pid=13437, si_uid=0} ---
[pid 21251] sched_yield()               = 0
[pid 21251] futex(0x1653498, FUTEX_WAIT_PRIVATE, 2, NULL
```
as well.

Neither `SIGQUIT` nor `SIGABRT` terminate the process.

Steps to reproduce the behavior
-------------------------------

on those hosts where it gets stuck, it always gets stuck. running the same command outside of my python `Popen` process it works however.

Do you have any idea what may have caused this?
-----------------------------------------------

I'm assuming it has to do with the fact that I'm capturing the output, but I don't quite understand how.

Do you have an idea how to solve the issue?
-------------------------------------------

:'( no

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

`restic` didn't "help" me today as such [except for doing all my backups :see_no_evil: ], because I'm having trouble with this issue, BUT of course I'm really quite thankful for restic and for all the work you folks put into this :heart: 

Thank you :wave:

**Comment by andreasnuesslein** [comment]
PS, a `SIGTERM` yields this:
```
 <unfinished ...>
[pid 21257] <... futex resumed> )       = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
[pid 21257] --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=13437, si_uid=0} ---
[pid 21257] rt_sigprocmask(SIG_UNBLOCK, [TERM], NULL, 8) = 0
[pid 21257] getpid()                    = 21245
[pid 21257] gettid()                    = 21257
[pid 21257] tgkill(21245, 21257, SIGTERM) = 0
[pid 21257] --- SIGTERM {si_signo=SIGTERM, si_code=SI_TKILL, si_pid=21245, si_uid=0} ---
[pid 21257] rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=~[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x46d1e0}, NULL, 8) = 0
[pid 21257] rt_sigprocmask(SIG_UNBLOCK, [TERM], NULL, 8) = 0
[pid 21257] getpid()                    = 21245
[pid 21257] gettid()                    = 21257
[pid 21257] tgkill(21245, 21257, SIGTERM) = 0
[pid 21257] --- SIGTERM {si_signo=SIGTERM, si_code=SI_TKILL, si_pid=21245, si_uid=0} ---
[pid 21262] <... futex resumed>)        = ?
[pid 24105] <... futex resumed>)        = ?
[pid 21260] <... futex resumed>)        = ?
[pid 21251] <... futex resumed>)        = ?
[pid 21249] <... futex resumed>)        = ?
[pid 21250] <... futex resumed> )       = ? <unavailable>
[pid 21248] <... futex resumed>)        = ?
[pid 21253] <... futex resumed>)        = ?
[pid 21252] <... futex resumed>)        = ?
[pid 21262] +++ killed by SIGTERM +++
[pid 21252] +++ killed by SIGTERM +++
[pid 21247] <... futex resumed>)        = ?
[pid 21250] +++ killed by SIGTERM +++
[pid 21247] +++ killed by SIGTERM +++
[pid 21246] <... futex resumed>)        = ?
[pid 21245] <... write resumed>)        = ?
[pid 21246] +++ killed by SIGTERM +++
[pid 21251] +++ killed by SIGTERM +++
[pid 21253] +++ killed by SIGTERM +++
[pid 21249] +++ killed by SIGTERM +++
[pid 21248] +++ killed by SIGTERM +++
[pid 24105] +++ killed by SIGTERM +++
[pid 21260] +++ killed by SIGTERM +++
[pid 21259] <... futex resumed>)        = ?
[pid 21259] +++ killed by SIGTERM +++
[pid 21257] +++ killed by SIGTERM +++
[pid 21261] <... futex resumed>)        = ?
[pid 21261] +++ killed by SIGTERM +++
+++ killed by SIGTERM +++
```

**Comment by andreasnuesslein** [comment]
I actually managed to get some output:

```
/some/path/youd/see/in/restic/forget\n\x1b[2Ksignal interrupt received, cleaning up\n')]
```

It seems to hang at that path, until I hit ctrl-c at which point it apparently adds the rest and exits.

It's interesting to note that, no matter which bufsize I set on the `Popen`-call, it always gets stuck at the same position of the output.
Increasing the `Popen bufsize` to arbitrary values didn't help.

**Comment by andreasnuesslein** [comment]
Yeah...

![image](https://user-images.githubusercontent.com/320080/97800130-b4a74f80-1c2a-11eb-9ce8-a6f2fc161ac5.png)


nevermind and sorry for the SIGINT.  

thanks again for restic and have a nice day :)

**Comment by fd0** [comment]
😃
