### ISSUE TITLE
Enhancement of restic snapshots --last

### ISSUE THREAD

**Issue by tribor** [restic/restic#3057]
Output of `restic version`
--------------------------
```
/ # restic version
restic 0.9.6 compiled with go1.13.10 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
The `--last` flag  shows the last snapshot for each host and path:
```
/ # restic snapshots -g paths  --last
repository 1d504fe1 opened successfully, password is correct
snapshots for (paths [/dump-ali.sql.gz]):
ID        Time                 Host          Tags        Paths
-------------------------------------------------------------------------
97156663  2020-11-04 17:43:07  200428efa7d2              /db-dump.sql.gz
98480ef9  2020-11-04 17:43:13  d335c6e4cdf7              /db-dump.sql.gz
-------------------------------------------------------------------------
2 snapshots

```
It would be nice that if you run this command in combination with `--group-by` the **actual string of group-by** would be respected. In this example only one line should be returned.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I run a docker container with a backup script. For each run the hostname is always different. I'm looking for a clean way to get the ID of the last job. One can do this with the json-output format and some jq-magic, but I would prefer to have restic output it for me.

The prune command does this the exact way as I prefer it:
`restic forget $RESTIC_RETENTION --prune -g paths  `

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Not only today! I'm using restic for almost 2years and had never any problems.

**Comment by MichaelEischer** [comment]
@tribor The solution for your problem of changing docker hostnames would be to just pass a static one to the backup command using `--host hostname`. But besides that the feature suggestions looks like it might be useful.

**Comment by whereisaaron** [comment]
I have the same use case, I want to be able to list just the most recent snapshot, but can't find a set of `restic snaphots` options that can do that. If your host or path varies which each snapshot, you just always get _all_ snapshots listed with `--last`. And `--group-by` and `--tags` can't prevent that.

I am passing a static host name as suggested, but the path is a single file path with a timestamp in it, so '--last' still lists every single snapshot 😄

Even if you only pass one item to `--group-by` it still groups by every criteria, including those you didn't ask for. So if you have varying host name or paths, there is not way to get `--last` to just list the most recent snapshot.

If `--group-by` grouped only by the specified criteria, then it would be easy to e.g. group by just host, or group by just one tag, and get the last snapshot for that backup group.

**Comment by MichaelEischer** [comment]
This should work by now:
`restic snapshots --group-by path --latest 1 --path /some/path` only returns the latest snapshot of that group. No idea, when this has been fixed exactly, either while reworking `--group-by` or while transitioning from `--last` to `--latest 1`.
