### ISSUE TITLE
Change function signature of backend.List() to allow returning errors

### ISSUE THREAD

**Issue by fd0** [restic/restic#306]
All backends must implement `List()` which sends all IDs for objects of a specified type to a channel. Currently, there is no way to return an error to the caller. Find a good way to enable that.

**Comment by ebastos** [comment]
A quick peek seems to indicate this was implemented via #1571.
Is that correct? Maybe can be closed?

**Comment by fd0** [comment]
Oh, indeed. Thanks a lot for the hint!
