### ISSUE TITLE
Prune results in context canceled with b2 Backend

### ISSUE THREAD

**Issue by miterion** [restic/restic#3062]
Output of `restic version`
--------------------------
restic 0.11.0 (v0.11.0-24-g636b2f2e9) compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------
Just `restic prune` without any arguments.
Environment Variables set:
```
B2_ACCOUNT_ID
B2_ACCOUNT_KEY
RESTIC_REPOSITORY
RESTIC_PASSWORD
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze (B2) Backend

Expected behavior
-----------------
`restic prune` prunes the repository and exits with a zero status code.

Actual behavior
---------------
Restic exits with a non-zero status code and the following backtrace:
```
<ommittted previous lines>
[0:10] 100.00%  45 / 45 files deleted
repacking packs
[5:15] 100.00%  612 / 612 packs repacked
context canceled
Close
github.com/restic/restic/internal/backend/b2.(*b2Backend).Save
	github.com/restic/restic/internal/backend/b2/b2.go:211
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
	github.com/restic/restic/internal/backend/backend_retry.go:56
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
	github.com/cenkalti/backoff/v4@v4.0.2/retry.go:52
github.com/cenkalti/backoff/v4.RetryNotify
	github.com/cenkalti/backoff/v4@v4.0.2/retry.go:31
github.com/restic/restic/internal/backend.(*RetryBackend).retry
	github.com/restic/restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).Save
	github.com/restic/restic/internal/backend/backend_retry.go:50
github.com/restic/restic/internal/cache.(*Backend).Save
	github.com/restic/restic/internal/cache/backend.go:54
github.com/restic/restic/internal/repository.(*Repository).savePacker
	github.com/restic/restic/internal/repository/packer_manager.go:107
github.com/restic/restic/internal/repository.(*Repository).FlushPacks
	github.com/restic/restic/internal/repository/repository.go:344
github.com/restic/restic/internal/repository.(*Repository).Flush
	github.com/restic/restic/internal/repository/repository.go:321
github.com/restic/restic/internal/repository.Repack
	github.com/restic/restic/internal/repository/repack.go:190
main.prune
	github.com/restic/restic/cmd/restic/cmd_prune.go:477
main.runPruneWithRepo
	github.com/restic/restic/cmd/restic/cmd_prune.go:176
main.runPrune
	github.com/restic/restic/cmd/restic/cmd_prune.go:152
main.glob..func19
	github.com/restic/restic/cmd/restic/cmd_prune.go:36
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	github.com/restic/restic/cmd/restic/main.go:98
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_amd64.s:1374
```

Steps to reproduce the behavior
-------------------------------
Run `restic prune` on a repository stored in backblaze.

Do you have any idea what may have caused this?
-----------------------------------------------
It most likely is connected to the recent merge of the prune rewrite, since it worked before. I am not familiar with the code enough but my guess is that something is closing the context in a different go routine, which results in a failure during the `Write`-call.

Do you have an idea how to solve the issue?
-------------------------------------------
Not really, but I could take a closer look and try to debug it later. I am not the most versatile Go programmer though.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is an amazing backup tool and I use it every day. Fortunately I did not have a disaster where I needed to restore everything but having a great scriptable backup solution at my disposale really helps me sleep better at night :)
Thank you so much for this amazing tool!

**Comment by fd0** [comment]
Thanks for the report! @aawsome would you mind having a look?

**Comment by lorenzbausch** [comment]
Same behaviour here, but with Minio as backend.

**Comment by fd0** [comment]
Ah, okay. This means that it's independent of the backend, cool :)

**Comment by aawsome** [comment]
Thanks for reporting! I'll have a look.

**Comment by aawsome** [comment]
Mhh.. looks a bit like this happens in the repacking code.

@miterion  / @lorenzbausch : Is it possible that you test this without the parallel repacking code, i.e. with commit 5144141321404a6137ef596c40590d3ba2d426ca
https://github.com/restic/restic/commit/5144141321404a6137ef596c40590d3ba2d426ca

Just want to find out whether it's the new prune command or the new repacking...

**Comment by miterion** [comment]
I am running it now and will update as soon as it's done.

**Comment by lorenzbausch** [comment]
`restic 0.11.0 (v0.11.0-15-g51441413) compiled with go1.15.2 on linux/amd64`

```
loading all snapshots...
loading indexes...
finding data that is still in use for 31 snapshots
[8:07] 100.00%  31 / 31 snapshots

searching used packs...
collecting packs for deletion and repacking
[2:20] 100.00%  64168 / 64168 packs processed


to repack:       209521 blobs / 11.756 GiB
this removes     199206 blobs / 11.656 GiB
to delete:       280767 blobs / 40.466 GiB
total prune:     479973 blobs / 52.123 GiB
remaining:      2507760 blobs / 248.150 GiB
unused size after prune: 12.404 GiB (5.00% of remaining size)

deleting unreferenced packs
[0:00] 100.00%  24 / 24 files deleted

repacking packs
[1:40] 100.00%  2719 / 2719 packs repacked

counting files in repo
[2:59] 100.00%  53034 / 53034 packs

finding old index files
saved new indexes as [67db7d01 afeebe4a 40379130 208cb1fc 73cca320 21396a16 d4221bd0 41425cc4 c
62f295b fd2f8f6d afda21b1 9fe6116c 002e870b e1fe3eb5 adc1e572 1dfebb65 0a674691 1becc4f8]
remove 45 old index files
[0:00] 100.00%  45 / 45 files deleted

removing 11160 old packs
[0:30] 100.00%  11160 / 11160 files deleted

done

```

**Comment by aawsome** [comment]
Thanks @lorenzbausch 
I think I found it in the parallel repack code: `wg.Wait()` cancels the context that has been generated by `wg, ctx := errgroup.WithContext(ctx)`. I will submit a PR soon.

**Comment by greatroar** [comment]
I think the bug is in

https://github.com/restic/restic/blob/a5592e83f7445815f148e626fa1af16fac9deb5c/internal/repository/repack.go#L186-L192

wg is an errgroup with a cancel function. Waiting on it calls that cancel function. Flush shouls run in a different context.

**Comment by greatroar** [comment]
Looks like we had a race condition looking for the bug :)

**Comment by fd0** [comment]
Can anybody test the PR? :)

**Comment by fd0** [comment]
Uhm, are you sure? You both said that calling `Wait()` on the `errgroup.Group` cancels the context, but that's not the case: https://play.golang.org/p/-lL9ghuPkNJ

Am I missing something?

**Comment by aawsome** [comment]
> Uhm, are you sure? You both said that calling `Wait()` on the `errgroup.Group` cancels the context, but that's not the case: https://play.golang.org/p/-lL9ghuPkNJ
> 
> Am I missing something?
`Wait` waits for the `sync.WaitGroup`and then cancels the context.

From `errgroup.go`:

```
// Wait blocks until all function calls from the Go method have returned, then
// returns the first non-nil error (if any) from them.
func (g *Group) Wait() error {
	g.wg.Wait()
	if g.cancel != nil {
		g.cancel()
	}
	return g.err
}
```

**Comment by lorenzbausch** [comment]
I compiled  the PR using `restic/builder` and it worked:

```
[0:00] 100.00%  1 / 1 files deleted

1 snapshots have been removed, running prune
loading all snapshots...
loading indexes...
finding data that is still in use for 30 snapshots
[7:58] 100.00%  30 / 30 snapshots

searching used packs...
collecting packs for deletion and repacking
[7:54] 100.00%  53034 / 53034 packs processed


to repack:         4441 blobs / 432.541 MiB
this removes       3847 blobs / 422.438 MiB
to delete:          410 blobs / 256.338 MiB
total prune:       4257 blobs / 678.775 MiB
remaining:      2503503 blobs / 247.488 GiB
unused size after prune: 12.372 GiB (5.00% of remaining size)

repacking packs
[0:02] 100.00%  78 / 78 packs repacked

counting files in repo
[3:23] 100.00%  52901 / 52901 packs

finding old index files
saved new indexes as [f0973cdf c49db619 adc9ef54 42594b89 68dfba6f d26c2894 572f14db 2e6a3daa 38557246 8615f1a5 4a89b201 b2b1c12d 80254599 b5e22bbe ccfd1e61 687a3027 6de98365 2233156f]
remove 19 old index files
[0:00] 100.00%  19 / 19 files deleted

removing 137 old packs
[0:00] 100.00%  137 / 137 files deleted

done
```

I have to say though that I tested pruning with the master on several hosts and only one host had the `context canceled` problem so far.

**Comment by aawsome** [comment]
> I have to say though that I tested pruning with the master on several hosts and only one host had the `context canceled` problem so far.

This might be due to #2718. I think in many situations the default `max-unused=5%` means that there are no packs which need repacking.

**Comment by miterion** [comment]
> Can anybody test the PR? :)

Works for me too :+1:

**Comment by fd0** [comment]
Ah, thanks for the explanation! I was (vaguely) aware that the context for an errgroup is cancelled, but didn't have the details. It's clear to me now: `Wait()` cancels the context before returning (not on function entry). That makes much more sense. This shows it: https://play.golang.org/p/OjCn7VOo75v

**Comment by fd0** [comment]
> This might be due to #2718. I think in many situations the default max-unused=5% means that there are no packs which need repacking.

With `--max-unused 0b` I can reproduce it easily. The PR fixes the issue for me :)

**Comment by lorenzbausch** [comment]
Awesome, thank you for your work :rocket:
