### ISSUE TITLE
Fatal: number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by benchub** [restic/restic#3064]
As requested by restic 0.9.6 output....

$ restic --cleanup-cache -r rclone:pCloudTM:timemachine prune
enter password for repository:
repository b2b938c5 opened successfully, password is correct
counting files in repo
building new index for repo
[13:48:14] 100.00%  165606 / 165606 packs
incomplete pack file (will be removed): 052fec22965b952553ce52436c08e56578b1af1677d2acb3ed86047787b97973
incomplete pack file (will be removed): 08fd6b1528b24e54765dc62684601b2f42803baba7085199a87e3925573f9685
incomplete pack file (will be removed): 0ed97d373b58a24759a7865c25081b0ddaa411457a8f7a40144ff6ed0687beaf
incomplete pack file (will be removed): 213974a28494fed79ccd4639c0172c17e6a39bf55f336b0acae28e044c9b3f99
incomplete pack file (will be removed): 33e932bf513c5bace5afe28b7804f9a4ab84933fa814da3ebd0f1128226bb5d6
incomplete pack file (will be removed): 01dc4dc7b3b6951fadc1e4cb3a5ba479d4a5bb8a572f40b97e9090fddf85f72c
incomplete pack file (will be removed): 3d113cdb2c6eebede0875904a6bdd74577d236584962522b564a055fa26d2570
incomplete pack file (will be removed): 3ebf2515f6600ed7ec47a89a1f80f1e1885abbdfbcf5a2eb5c182206616bee9f
incomplete pack file (will be removed): 48d8c2e75b2bb07d069e7194863b6f5b1d480b4abf724d823e14ea8b0cf7b7a1
incomplete pack file (will be removed): 5341c65dfd6477690a927dd2ae18bf1c9545474957f5234a3b90cdefdeb37bca
incomplete pack file (will be removed): 650dbf42bf41a7b179aa8742dba4cdcf5f081b6474969c1b8e0b2d81aa83d6ef
incomplete pack file (will be removed): 6cfa0bc411e720950df84a7317a85f1395acb386bffbff616211d1d1a79bab14
incomplete pack file (will be removed): 6ea7234d8c6a7c5924bcc0f3b3c7c20ee92f1d84b5baf33b2899ac61bb1282ed
incomplete pack file (will be removed): 71c68922f0abbe73c4306681265d4dec346e4262603d9aa729f64cc65c3d013b
incomplete pack file (will be removed): 752a84fc05fd341dd50ce60d0e92f920b6405a8fd79b3328b1102405f83edf63
incomplete pack file (will be removed): 7401e78eb3d077d49e77b0179d384f2f365c416079a3807f133e90697cd385dd
incomplete pack file (will be removed): 7c6216babcee9e978076b46a59808545d788c59c916e9e48f532be9a8b71f218
incomplete pack file (will be removed): 892270c4191e4498d19c9f289c641af8e660a98de01b3ba52b6427c03effe16e
incomplete pack file (will be removed): 8c02d66f5fe6b1b86be3b492452a82d621913de3b0dfdaa0d304d532c1b08302
incomplete pack file (will be removed): 8c8b388503ee40a77d930b5ca39de527de3ca1eb8a9d94e87b8588f128376d2a
incomplete pack file (will be removed): a175c18f726b0670f7ba3bb2ed6e94d7f71d4357aab9633853d9da957b2cc639
incomplete pack file (will be removed): a23ffe3c7d34189489d72b0450be69d433f69e682dd0e60df0c92ca593d0f593
incomplete pack file (will be removed): a97e189afd0d2e942f4b9530e5ec62606d29d74f3b20796140348538060c950b
incomplete pack file (will be removed): abf96ab44b7f540eec4f637e1bbecf295d1243f1c6563d9614ea5158f762551a
incomplete pack file (will be removed): b0ebe214f6dd7343b20575bf8e53c99a516650f62484aad92b21a5deb1f334b0
incomplete pack file (will be removed): c0c703934b5b70b23fc00be19a753efaacb43b2b86c5fc14ed906b8c7c0a09c2
incomplete pack file (will be removed): cbe5a0de697f764506120100be204ecc96da4e34444eb97d6bae4d155681f5e3
incomplete pack file (will be removed): d129655fd406062cc60ddc307b234cae66d5ef608d19ea549b1e8f0dd809cd54
incomplete pack file (will be removed): b1dfd748e3e268dbe412c5f4ef56f44981bd2114580608f8bee7e61941e2779b
incomplete pack file (will be removed): ed2dd16a7ae6e8cd6439c9ec93dcc65b608b6576fe6ae1549aafeae1555846f1
incomplete pack file (will be removed): ef7e0d14280f9e4db51686185b4a96fe89faab673315eb2612b8afdcc754f492
incomplete pack file (will be removed): fe2c76752ff5ce240d15e710abe0b963f083800f19d890a32047584619f84614
repository contains 165574 packs (862216 blobs) with 763.514 GiB
processed 862216 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 3 snapshots
[0:08] 100.00%  3 / 3 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new

$ restic version
restic 0.9.6 compiled with go1.14.8 on freebsd/amd64

**Comment by fd0** [comment]
Thanks for the report. While I don't know what's going on exactly, restic detected a situation where it was unable to find all data, maybe because the files listed were truncated. Either the data was not correctly transferred, or something during upload happened.

 * Can you have a look at the cloud backend directly and look e.g. for the first file `052fec22965b952553ce52436c08e56578b1af1677d2acb3ed86047787b97973`? It should be stored within the directory `data/05`. How large is the file? Is it maybe empty?
 * Run `sha256sum` on it, does it match the file name?

You can try a more recent version of restic. The current version is 0.11.0, you can find the binaries here: https://github.com/restic/restic/releases/tag/v0.11.0

Also, we've recently rewritten the code for the `prune` operation, here you can find pre-compiled binaries for the `master` branch: https://beta.restic.net/restic-v0.11.0-37-g4707bdb2/

**Comment by benchub** [comment]
Thanks for getting back to me. The file does exists, and is 2.7MB in size, but the sha256sum does not match the filename. Should I just try a newer version and hope for the best, or is there more I can debug first?

**Comment by fd0** [comment]
> The file does exists, and is 2.7MB in size, but the sha256sum does not match the filename.

Ok, that's odd. It sounds like the file got corrupted (or rather truncated) after restic was done packaging it up and before you downloaded it. It's likely that this happened either in transit or at the cloud service, there's no way to find out.

Before writing restic I could not imagine such things happening in real life, but now I know better ;)

For all the IDs restic lists, you can try the following:
 * Find out which snapshots depend on the data in the files by running `restic find --pack <id>`
 * Forget the snapshot by running `restic forget <packid>`

Then you are able to run `prune` again :)

**Comment by MichaelEischer** [comment]
@benchub Is there anything left to do here? If you still have the broken pack file and want to keep the snapshots, you could try the instructions here: https://github.com/restic/restic/issues/1999#issuecomment-739398187 . The investigation on how the pack file was damaged should probably go into #3079.

**Comment by MichaelEischer** [comment]
Closing this issue as we didn't get any more feedback, so I assume it's been resolved by now. Feel free to reopen the issue if the problem still exists.
