### ISSUE TITLE
Backend support for S3 compatible Minio http://minio.io

### ISSUE THREAD

**Issue by eripa** [restic/restic#307]
I tried to setup a restic+minio setup a couple of days ago, my thinking being that running such setup would be a nice alternative to the typical restic+sftp setup. 

However it seems like minio doesn't exactly implement the same API as S3 (as they state in the docs), so something breaks. 

I'll update the issue with a message when I have the time to re-run it.  Is there a way to get more debug information out of restic?

**Comment by fd0** [comment]
You can build restic with debug, just use `go run build.go -tags debug`. Afterwards you can set the environment variable `DEBUG_LOG` to a file name and restic will write extensive debug information to this file, e.g.:
    $ DEBUG_LOG=/tmp/log restic -r s3://host backup foo

Please be aware that the debug log may contain sensitive things, especially file and directory names.

**Comment by fd0** [comment]
Did you have the chance to test it again while writing a debug log?

**Comment by harshavardhana** [comment]
> However it seems like minio doesn't exactly implement the same API as S3 (as they state in the docs), so something breaks.

Minio implements the same API as Amazon S3, `restic` internally uses goamz which only supports Signature V2, Minio only supports Signature v4. 

I am planning to converge

- https://github.com/minio/minio-go  (API for signature V4)
- https://github.com/minio/minio-go-legacy  (API for signature V2)

Also is there a chance that restic is willing to migrate to minio-go? or aws-sdk-go?

**Comment by harshavardhana** [comment]
> Also is there a chance that restic is willing to migrate to minio-go? or aws-sdk-go?

Or better yet willing to accept our pull request?

**Comment by fd0** [comment]
We're indeed willing to accept a PR! I personally like the scenario of beeing able to backup to a minio server :)

**Comment by fd0** [comment]
This is currently beeing worked on in #345.

**Comment by fd0** [comment]
This was implemented with #366, we now use the minio-go library.
