### ISSUE TITLE
beta.restic.net: binaries are invalid

### ISSUE THREAD

**Issue by lorenzbausch** [restic/restic#3078]
Starting with https://beta.restic.net/restic-v0.11.0-42-g9e4e0077/ the beta builds are only few bytes in size.
Last good build set seems to be https://beta.restic.net/restic-v0.11.0-40-g1758da85/

Executing such an invalid binary results in:
```
restic_v0.11.0-50-ga5989707_linux_amd64: line 1: syntax error near unexpected token `newline'
restic_v0.11.0-50-ga5989707_linux_amd64: line 1: `!<arch>'
```

Thank you all for restic!

**Comment by fd0** [comment]
Thanks for the report! I've worked on the service yesterday, maybe I broke something...

**Comment by fd0** [comment]
Dang, the service did not build `cmd/restic`, it's fixed. Thanks again!
