### ISSUE TITLE
Data blobs seem to be missing, aborting prune to prevent further data loss!

### ISSUE THREAD

**Issue by benchub** [restic/restic#3079]
Output of `restic version`
--------------------------

How did you run restic exactly?
-------------------------------

# ./restic_0.11.0_freebsd_amd64 -r rclone:pCloudMedia:pictures prune
enter password for repository:
repository cc558b1f opened successfully, password is correct
counting files in repo
building new index for repo
[16:03:57] 100.00%  101597 / 101597 packs
incomplete pack file (will be removed): 89989139f4fef5f163cee59290e831493605421e044268d0596d0cfc5012209b
incomplete pack file (will be removed): 9a7cca97c7f09f4ad68e3ca3f33d515f96221195f7ead767f39c3b01bb74cd48
incomplete pack file (will be removed): a022426850d2b456a33e632753eff162ae48f288158a49fceabef5a2bee18be5
incomplete pack file (will be removed): 7ac0ab4bb58e8a16223a2b50081116956e3c0656f5a3fb9bb4daa4bd33e44c9e
repository contains 101593 packs (387461 blobs) with 496.935 GiB
processed 387461 blobs: 310 duplicate blobs, 380.563 MiB duplicate
load all snapshots
find data that is still in use for 22 snapshots
[0:39] 100.00%  22 / 22 snapshots
Fatal: [<data/f78dc991> <data/5b9e4366> <data/ddd8c7d4> <data/4a097401> <data/33db76a4> <data/aa1dd331>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

rclone/pcloud

Expected behavior
-----------------

I ran prune because running check (with version 0.9.6) told me:

created new cache in /tmp/restic-check-cache-453150499
create exclusive lock for repository
load indexes
check all packs
pack 9a7cca97: not referenced in any index
pack 89989139: not referenced in any index
2 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
check snapshots, trees and blobs
no errors were found

Actual behavior
---------------

Those packs and more were listed as bad, and then also data blobs seemed to be missing. :(

Steps to reproduce the behavior
-------------------------------

Just run the command as shown.

Do you have any idea what may have caused this?
-----------------------------------------------

No.

Do you have an idea how to solve the issue?
-------------------------------------------

No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I do love the idea behind restic. I've recently started having issues with it, and its not clear to me if that's because of something on my end, something in restic itself, or my storage provider.

**Comment by MichaelEischer** [comment]
Please run `restic find --show-pack-id --blob f78dc991 5b9e4366 ddd8c7d4 4a097401 33db76a4 aa1dd331` to find out where the missing blobs should be stored. Afterwards we can take a closer look at the problematic pack file.

**Comment by benchub** [comment]
Oh, good to know about the cosmetic problem from the check. As for the find....

```
# ./restic_0.11.0_freebsd_amd64 -r rclone:pCloudMedia:pictures find --show-pack-id --blob f78dc991 5b9e4366 ddd8c7d4 4a097401 33db76a4 aa1dd331
enter password for repository:
repository cc558b1f opened successfully, password is correct
Found blob 4a097401e05ea207a86ed5eea59b9b5c81c7c6a45baf26e61dcbc972c3a573bd
 ... in file /mnt/snaps/pictures/Raws/2019/100_1210/IMGP9004.PEF
     (tree 23c7dcd8422fa96c8764a2f61ddc7756db0a745ed23237231cca7b38e834f295)
 ... in snapshot 4e5f76e8 (2020-11-01 21:57:23)
Found blob 5b9e43661fc06b0d44b3a8b0687a6c9d813e38bd1823e5517aa7e0c1a60276e3
 ... in file /mnt/snaps/pictures/Raws/Zara/107_FUJI/DSCF7316.MOV
     (tree df017726ed89709a8a2c3809e93ed6e7f81746a607a29a8bfaf8146051480c97)
 ... in snapshot 4e5f76e8 (2020-11-01 21:57:23)
Note: cannot find pack for object '33db76a4', unable to parse ID: invalid length for hash
Note: cannot find pack for object 'aa1dd331', unable to parse ID: invalid length for hash
Object belongs to pack a022426850d2b456a33e632753eff162ae48f288158a49fceabef5a2bee18be5
 ... Pack a0224268: <Blob (data) 4a097401, offset 0, length 2654921>
Note: cannot find pack for object 'f78dc991', unable to parse ID: invalid length for hash
Note: cannot find pack for object 'ddd8c7d4', unable to parse ID: invalid length for hash
Object belongs to pack 7ac0ab4bb58e8a16223a2b50081116956e3c0656f5a3fb9bb4daa4bd33e44c9e
 ... Pack 7ac0ab4b: <Blob (data) 5b9e4366, offset 0, length 2504401>
```

**Comment by MichaelEischer** [comment]
It looks like find is unable to properly handle multiple blobs in one call. Can you run
`restic find --show-pack-id --blob 33db76a4` and also once with `aa1dd331`, `f78dc991` and `ddd8c7d4`? I'd expect it to also report the same file(s) as damaged.

Do you still have to files listed by the find commands? If yes, then it should be quite easily possible to repair the repository.

> `Object belongs to pack a022426850d2b456a33e632753eff162ae48f288158a49fceabef5a2bee18be5`
> `Object belongs to pack 7ac0ab4bb58e8a16223a2b50081116956e3c0656f5a3fb9bb4daa4bd33e44c9e`

These two pack files are also reported by prune as incomplete. The other four missing data blobs are probably also part of these pack files.

Can you download these two pack files from pCloud and check their sha256 hash (using `shasum -a256`)? They should be located in `data/a0/a022426850d2b456a33e632753eff162ae48f288158a49fceabef5a2bee18be5` and `data/7a/7ac0ab4bb58e8a16223a2b50081116956e3c0656f5a3fb9bb4daa4bd33e44c9e` within the backup repository. How large are these files and when were they created? It would be interesting to investigate a bit whether we can find out how the pack files were damaged.

The recovery steps would then be those from the second half of https://github.com/restic/restic/issues/3023#issuecomment-724978137 (either Route 1 or 2).

**Comment by benchub** [comment]
OK, so, as you suspected, all missing blobs belong to those two packs. When I download the bad pack files from pCloud, they do not match their sha256. But! I noticed both packs were ~50% the size of everything else, which seemed odd, and I happened to also notice that there was a second revision of these packs. (pCloud versions files for you.) The _original_ version of the pack files are normal size, and when I download them, they do match their sha256. The interesting thing to me is that the "original" version is in the future of the more recent version, leading me to wonder if this is a pCloud issue, or, perhaps, the way that rclone is dealing with pCloud. 

I'll follow up with pCloud, but I did see in my most recent scrollback (both these packs are recent) errors in uploading these exact packs:

```
rclone: 2020/11/02 05:48:17 ERROR : data/a0/a022426850d2b456a33e632753eff162ae48f288158a49fceabef5a2bee18be5: Post request put error: Put "https://api.pcloud.com/uploadfile?filename=a022426850d2b456a33e632753eff162ae48f288158a49fceabef5a2bee18be5&folderid=3861146258&mtime=1604324815&nopartial=1": write tcp 10.2.3.12:53599->xx.xx.xx.xx:443: use of closed network connection
rclone: 2020/11/02 05:48:17 ERROR : data/a0/a022426850d2b456a33e632753eff162ae48f288158a49fceabef5a2bee18be5: Post request rcat error: Put "https://api.pcloud.com/uploadfile?filename=a022426850d2b456a33e632753eff162ae48f288158a49fceabef5a2bee18be5&folderid=3861146258&mtime=1604324815&nopartial=1": write tcp 10.2.3.12:53599->xx.xx.xx.xx:443: use of closed network connection
Save(<data/a022426850>) returned error, retrying after 396.550928ms: server response unexpected: 500 Internal Server Error (500)

rclone: 2020/11/03 00:38:22 ERROR : data/7a/7ac0ab4bb58e8a16223a2b50081116956e3c0656f5a3fb9bb4daa4bd33e44c9e: Post request put error: Put "https://api.pcloud.com/uploadfile?filename=7ac0ab4bb58e8a16223a2b50081116956e3c0656f5a3fb9bb4daa4bd33e44c9e&folderid=3861085895&mtime=1604392617&nopartial=1": write tcp 10.2.3.12:14274->xx.xx.xx.xx:443: use of closed network connection
rclone: 2020/11/03 00:38:22 ERROR : data/7a/7ac0ab4bb58e8a16223a2b50081116956e3c0656f5a3fb9bb4daa4bd33e44c9e: Post request rcat error: Put "https://api.pcloud.com/uploadfile?filename=7ac0ab4bb58e8a16223a2b50081116956e3c0656f5a3fb9bb4daa4bd33e44c9e&folderid=3861085895&mtime=1604392617&nopartial=1": write tcp 10.2.3.12:14274->xx.xx.xx.xx:443: use of closed network connection
Save(<data/7ac0ab4bb5>) returned error, retrying after 298.727309ms: server response unexpected: 500 Internal Server Error (500)
```

But, I also saw similar errors with dozens of other packs, none of which seem to have more than a single file version (of the ones I spot checked), so it only seems to be an intermittent issue.

**Comment by MichaelEischer** [comment]
@benchub Nice to hear that you were able to find the original file versions. Does prune work now with the correct versions of these files? It's sort of good news that the error happened during the upload and not somewhere internally in prune.

restic tries to remove a file which has failed to upload before trying again. Maybe that has removed older file version for other files? Do the first and second revision have timestamps? I suspect these are only a few seconds apart. Maybe pCloud uses timestamps to distinguish between old and new revision (I know at least one storage service, but don't remember the name, which uses timestamps with seconds granularity to decide between old/new file revisions, maybe something else happened here? Or maybe the failed upload was just "completed" later on?).

rclone requests that pCloud only stores complete uploads: https://github.com/rclone/rclone/blob/2708a7569eb18a3ca25f30b09a4df242d6293d2c/backend/pcloud/pcloud.go#L1122 . But it doesn't look like that works reliably, see line 1150.

**Comment by aawsome** [comment]
Actually this kind of problem (incomplete pack files) may show up for quite some users, once #3082 gets merged...

**Comment by MichaelEischer** [comment]
Closing this issue as it looks like a problem of pCloud. I don't think that restic could do anything here to avoid this problem.
