### ISSUE TITLE
(Minor) Bug "restic diff 123456  111111" gives proper error message but then abends.

### ISSUE THREAD

**Issue by 12edge** [restic/restic#3080]
Running Restic version 0.11 on Windows 10 with the diff 
.${RESTICEXE} diff 111111 222222
no matching ID found
github.com/restic/restic/internal/restic.init
        /restic/internal/restic/backend_find.go:11
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5625
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5620
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5620
runtime.main
        /usr/local/go/src/runtime/proc.go:191
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374

The "no matching ID found." is correct, but then there are these other messages which looks like Restic has abended. The program should exist gracefully. 
I'm not quite sure if a program which needs two parameters should check both inputs and issue two error messages that the ID are not found.
I would like the error message does not state which ID does not exist. For example ID "111111" does not exist.

**Comment by MichaelEischer** [comment]
Thanks for reporting this. restic is actually not crashing, it's just that the error message looks horrible. The snapshot loading in cmd_diff should return a  `Fatal` error using `errors.Fatal`. Anyone up for a patch?
