### ISSUE TITLE
restic 0.11.0 breaks with S3 compatible backends that don't (fully) support ListObjectsV2

### ISSUE THREAD

**Issue by LordGaav** [restic/restic#3083]
Output of `restic version`
--------------------------
Broken on: restic 0.11.0 compiled with go1.15.3 on linux/amd64
Works on: restic 0.10.0 compiled with go1.15.2 on linux/amd64 (and earlier)

How did you run restic exactly?
-------------------------------
Nightly backups are made to a S3 repository. When upgrading to the latest restic version, and trying to list snapshots, an error occurs.

```
# restic snapshots 
enter password for repository: 
repository beb6e91b opened successfully, password is correct
List(snapshot) returned error, retrying after 462.318748ms: Truncated response should have continuation token set
List(snapshot) returned error, retrying after 890.117305ms: Truncated response should have continuation token set
List(snapshot) returned error, retrying after 636.341646ms: Truncated response should have continuation token set
List(snapshot) returned error, retrying after 1.107876242s: Truncated response should have continuation token set
List(snapshot) returned error, retrying after 1.511079094s: Truncated response should have continuation token set
List(snapshot) returned error, retrying after 3.04096222s: Truncated response should have continuation token set
List(snapshot) returned error, retrying after 5.781953173s: Truncated response should have continuation token set
List(snapshot) returned error, retrying after 11.222385136s: Truncated response should have continuation token set
List(snapshot) returned error, retrying after 9.152900914s: Truncated response should have continuation token set
List(snapshot) returned error, retrying after 16.927710407s: Truncated response should have continuation token set
could not load snapshots: Truncated response should have continuation token set
```

This also happens during a restore command, which produces similar output.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3 backend, backed by Ceph on an OpenStack platform.

Expected behavior
-----------------
Listing snapshots and restoring should work normally.

Actual behavior
---------------
Listing snapshots and restoring does not work.

Steps to reproduce the behavior
-------------------------------
See above.

Do you have any idea what may have caused this?
-----------------------------------------------
This issue seems to be caused by Ceph's S3 compatible gateway. It advertises V2 API compatible endpoints, but doesn't implement them properly, specifically ListObjectsV2. Switching to the V1 API 'solves' this issue, in this case done by downgrading restic.

The issue is introduced in minio-go/v7 , see the bug report here: https://github.com/minio/minio-go/issues/1130 . There is also a bug report in the Thanos project, a workaround there is providing the option to use the V1 api: https://github.com/thanos-io/thanos/issues/3291 . There is also an issue tracking this by Ceph itself: https://tracker.ceph.com/issues/23908 .

Do you have an idea how to solve the issue?
-------------------------------------------
An option to select the V1 API would help, and would allow a user to use restic + S3 + Ceph on versions of Ceph that don't implement the V2 APIs (properly). May also help other S3 implementations.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
The 0.10 and 0.11 releases have a lot of nice features, and using restic is very easy.

**Comment by fd0** [comment]
Thanks for the report! I've read the linked websites you provided, thanks for digging into the issue. We'll probably add an option to enable `ListObjects` (v1), like `-o s3.listobjects=v1` or something similar, together with a hint in the docs that this is needed on Ceph.

Are you up for a PR?

You mentioned that the "issue is introduced in `minio-go/v7`", I'd like to clarify: The issue is not within `minio-go`, but within Ceph, which apparently does not implement `ListObjectsV2` properly :)

**Comment by LordGaav** [comment]
> Thanks for the report! I've read the linked websites you provided, thanks for digging into the issue. We'll probably add an option to enable `ListObjects` (v1), like `-o s3.listobjects=v1` or something similar, together with a hint in the docs that this is needed on Ceph.
> 
> Are you up for a PR?

I'll try, but I don't have a lot of experience with Go development. So please don't hold your breath ;).

> You mentioned that the "issue is introduced in `minio-go/v7`", I'd like to clarify: The issue is not within `minio-go`, but within Ceph, which apparently does not implement `ListObjectsV2` properly :)

Fair enough.
