### ISSUE TITLE
--use-fs-snapshot failed on windows/386

### ISSUE THREAD

**Issue by DRON-666** [restic/restic#3087]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.2 on windows/386

How did you run restic exactly?
-------------------------------
restic --use-fs-snapshot d:\test

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local filesystem repository

Expected behavior
-----------------
VSS don't failed

Actual behavior
---------------
~~~
repository 43e035ae opened successfully, password is correct
creating VSS snapshot for [d:\]
error: failed to create snapshot for [d:\]: VSS error: GetSnapshotProperties() failed: E_INVALIDARG (0x80070057)
.....
~~~

Steps to reproduce the behavior
-------------------------------
Use `windows/386` restic version on 32-bit Windows with `--use-fs-snapshot` flag.

Do you have any idea what may have caused this?
-----------------------------------------------
Nobody uses 32-bit Windows, and syscalls from `vss_windows.go` are hardly tested.
I was absolute sure this bug was fixed by @fgma, but this piece of code seems to be cursed.

Do you have an idea how to solve the issue?
-------------------------------------------
```diff
diff --git a/internal/fs/vss_windows.go b/internal/fs/vss_windows.go
index e24dade..8cee09f 100644
--- a/internal/fs/vss_windows.go
+++ b/internal/fs/vss_windows.go
@@ -482,7 +482,7 @@ func (vss *IVssBackupComponents) DeleteSnapshots(snapshotID ole.GUID) (int32, ol
        var result uintptr = 0
 
        if runtime.GOARCH == "386" {
-               id := (*[4]uintptr)(unsafe.Pointer(ole.IID_NULL))
+               id := (*[4]uintptr)(unsafe.Pointer(&snapshotID))
 
                result, _, _ = syscall.Syscall9(vss.getVTable().deleteSnapshots, 9,
                        uintptr(unsafe.Pointer(vss)), id[0], id[1], id[2], id[3],
@@ -506,7 +506,7 @@ func (vss *IVssBackupComponents) GetSnapshotProperties(snapshotID ole.GUID,
        var result uintptr = 0
 
        if runtime.GOARCH == "386" {
-               id := (*[4]uintptr)(unsafe.Pointer(ole.IID_NULL))
+               id := (*[4]uintptr)(unsafe.Pointer(&snapshotID))
 
                result, _, _ = syscall.Syscall6(vss.getVTable().getSnapshotProperties, 6,
                        uintptr(unsafe.Pointer(vss)), id[0], id[1], id[2], id[3],
```

I think restic needs integration tests with **real** testing of VSS. Perhaps carefully prepared VHD image with many partitions of different types, broken mount points and other edge cases.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes! Yes!

**Comment by rawtaz** [comment]
Related comment: https://github.com/restic/restic/pull/2274#issuecomment-663665640

**Comment by DRON-666** [comment]
No @rawtaz it's totally different issue.

**Comment by DRON-666** [comment]
[This comment](https://github.com/restic/restic/pull/2274#issuecomment-711080598) (and below) seemed more related.

**Comment by rawtaz** [comment]
I was mostly thinking about not supporting 32-bit Windows due to the reasons in the comment i linked to and that we'll mostly just handle the failures on it gracefully.

**Comment by DRON-666** [comment]
32-bit restic supports VSS on 32-bit Windows, but don't supports it on 64-bit Windows due to VSS limitations.

**Comment by fgma** [comment]
@DRON-666 I'm going to test this in a VM. Are you going to create a PR?

**Comment by DRON-666** [comment]
>Are you going to create a PR?

Not now.

**Comment by fgma** [comment]
Just tested it. Works as expected. Should I create a PR for it?

**Comment by DRON-666** [comment]
Yes. Please.
