### ISSUE TITLE
CI tests need a tar executable

### ISSUE THREAD

**Issue by aawsome** [restic/restic#3088]
Output of `restic version`
--------------------------
git master

How did you run restic exactly?
-------------------------------

`go run build.go -T`

Expected behavior
-----------------

Should run the integration tests.

Actual behavior
---------------

Fails if the `tar` executable is not available.

I suppose this is also the reason, why the CI tests for windows fail ATM.

Do you have an idea how to solve the issue?
-------------------------------------------

Reimplement the tar extraction by using `archive/tar`.
I can offer to do this implementation, if wanted.

**Comment by fd0** [comment]
Oh, that'd be great if you could look into it! I hope that either the new URLs (committed to master) work, or that Sourceforge recovers from their outage by now.

For CI, we could also look into caching the binaries somewhere (in an Actions cache or somewhere else).

**Comment by DRON-666** [comment]
> I suppose this is also the reason, why the CI tests for windows fail ATM.

On Windows `tar` is part of the `git` installation package. It's located in `c:\Program Files\Git\usr\bin` folder. This path simple don't included in `PATH` environment variable.

**Comment by fd0** [comment]
That's the case, but that's `bsdtar`, which does not support symlinks on Windows. Our tests test symlinks on Windows, so we need GNU `tar`, which we install from Sourceforge.

**Comment by DRON-666** [comment]
Thanks for clarification. Now I understand what was the reason for [missing symlinks](https://github.com/restic/restic/pull/3081#issuecomment-725406310) in the `dump` tests on Windows.

**Comment by fd0** [comment]
Indeed! :)

**Comment by MichaelEischer** [comment]
`tar` is downloaded from https://github.com/restic/test-assets which works very well.
