### ISSUE TITLE
diff command mis-reports metadata differences at top-level of repo

### ISSUE THREAD

**Issue by Ian2020** [restic/restic#3092]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.14 on linux/amd64

How did you run restic exactly?
-------------------------------

Some setup: so we have two snapshots in the repo with only a metadata change between them:

```
restic init -r repo
touch thing.txt && restic -r repo backup thing.txt
touch thing.txt && restic -r repo backup thing.txt
```
Now diff the last two snapshots, e.g.

```
> restic -r repo diff 9c2a58ee 0a5ddce8
repository 358a1f67 opened successfully, password is correct
comparing snapshot 9c2a58ee to 0a5ddce8:


Files:           0 new,     0 removed,     0 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:      0 new,     0 removed
Tree Blobs:      0 new,     0 removed
  Added:   0 B  
  Removed: 0 B  
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Plain old filesystem.

Expected behavior
-----------------

Referencing the [comment in this conversation](https://forum.restic.net/t/restic-diff-command-ignores-differences-in-file-timestamps/3266/3) we would expect the new tree blobs count to be 1 I believe:

```
> restic -r repo diff 9c2a58ee 0a5ddce8
repository 358a1f67 opened successfully, password is correct
comparing snapshot 9c2a58ee to 0a5ddce8:


Files:           0 new,     0 removed,     0 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:      0 new,     0 removed
Tree Blobs:      1 new,     0 removed
  Added:   0 B  
  Removed: 0 B  
```

Actual behavior
---------------

See above, all counts are 0s.

Steps to reproduce the behavior
-------------------------------

Steps are above.

Do you have any idea what may have caused this?
-----------------------------------------------

There must be a bug that doesn't count changes to tree blobs at the top-level...

Do you have an idea how to solve the issue?
-------------------------------------------

I'm not familiar with the code, so nope.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, it helps me every day - I am happy user! Thank you for this tool.

**Comment by fd0** [comment]
Thanks for the report!
