### ISSUE TITLE
Restic should not pass drive-use-trash to rclone (by default) anymore

### ISSUE THREAD

**Issue by tofran** [restic/restic#3095]
# What should restic do differently?

Restic should not provide `--drive-use-trash=false` by default to rclone.

https://github.com/restic/restic/blob/145830005b78ac221b9fbe9c91ac7cd0214afb4f/internal/backend/rclone/config.go#L20

# Why?

As stated in https://github.com/restic/restic/pull/1657#issuecomment-377707486 the reason why restic is spinning up rclone with  `--drive-use-trash=false` by default is because its trash policy.

But [as announced](https://workspaceupdates.googleblog.com/2020/09/drive-trash-auto-delete-30-days.html) from October 13 on google will no longer retain items in trash for more than 30 days.
![image](https://user-images.githubusercontent.com/5692603/99125423-ea214500-25fb-11eb-8481-d44371a7cccf.png)

Making the previous argument not valid.

# What problem would this solve?

This makes it easier to use restic because removes the necessity for specifying `rclone.args="serve restic --stdio"` every time you use it.
By not passing this param, rclone reads from the `drive-use-trash` config, making it possible to configure everything with env vars. Opposed to having to edit scripts to inject the `rclone.args`.

# Restic version

`restic 0.11.0 compiled with go1.15.3 on linux/amd64`

**Comment by fd0** [comment]
Fine with me, are you up for a PR? :)
