### ISSUE TITLE
init command does not honor $RESTIC_REPOSITORY_FILE

### ISSUE THREAD

**Issue by eliba** [restic/restic#3104]
Output of `restic version`
--------------------------
`restic 0.11.0 compiled with go1.15.3 on linux/amd64`

How did you run restic exactly?
-------------------------------
The mentioned file includes variable declaration in form of `VAR=value`
```
$ . /home/restic/.config/restic/backup.conf
$ export RESTIC_PASSWORD_FILE
$ export RESTIC_REPOSITORY_FILE
$ restic init
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
* [rest-server](https://github.com/restic/rest-server) backend, version 0.10.0 on Linux amd64
* Command run on server: `rest-server --path /opt/restic --private-repos --prometheus`

Expected behavior
-----------------
restic initializing a new repo on the backend

Actual behavior
---------------
```
$ restic init
Fatal: Please specify repository location (-r)
```
```
$ restic init -r rest:http://username:password@resticserver.example.com:8000/remote_repository
Fatal: Options -r and --repository-file are mutually exclusive, please specify only one
```
```
$ restic init --repository-file=/home/restic/.config/restic/repository
Fatal: Please specify repository location (-r)
```

Steps to reproduce the behavior
-------------------------------
```
$ echo "rest:http://username:password@resticserver.example.com:8000/remote_repository" > /home/restic/.config/restic/repository
$ export RESTIC_REPOSITORY_FILE=/home/restic/.config/restic/repository
$ restic init
Fatal: Please specify repository location (-r)
```

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
First it took my notebook, now it takes dem servers

**Comment by fd0** [comment]
Thanks!
