### ISSUE TITLE
checker.filterTrees does not evaluate treeJob.error

### ISSUE THREAD

**Issue by episource** [restic/restic#311]
**Restic version:** e738d35c4e

**Observed behavior:** During discussion of restic#292 it has been observed, that [`checker.filterTrees`](https://github.com/restic/restic/blob/e738d35c4ebb3fb26afb5b880357fbe3286cc7d4/checker/checker.go#L431-L442) does not check treeJob.error (channel `in`, local variable `j`) before accessing members of the treeJob struct. This might cause e.g. a nil pointer dereference error to happen.

**Expected behavior:** `treeJob.error`should be checked before reading any other member of the treeJob struct. Not sure what should be done with items that have `treeJob.error != nil`. Most probably they should be passed further along the pipe, just like done by the current implementation. In this case [`checker.checkTreeWorker`](https://github.com/restic/restic/blob/e738d35c4ebb3fb26afb5b880357fbe3286cc7d4/checker/checker.go#L338) and/or [`checker.checkTree`](https://github.com/restic/restic/blob/e738d35c4ebb3fb26afb5b880357fbe3286cc7d4/checker/checker.go#L489) might need to evaluate treeJob.error, too.

**Comment by fd0** [comment]
I'm able to reproduce it.
