### ISSUE TITLE
Prune stats calculation bug

### ISSUE THREAD

**Issue by dimejo** [restic/restic#3110]
Output of `restic version`
--------------------------
restic_v0.11.0-g5f3b802e

How did you run restic exactly?
-------------------------------
`restic_v0.11.0-g5f3b802e prune > prune.log`

Actual behavior
---------------
```
to repack:       308801 blobs / 178.132 GiB
this removes     308801 blobs / 178.130 GiB
to delete:       327405 blobs / 197.824 GiB
total prune:     636206 blobs / 375.955 GiB
remaining:      1163369 blobs / 748.739 GiB
unused size after prune: 16777215.894 TiB (100.00% of remaining size)
```
Note the `16777215.894 TiB`.

**Comment by chrestomanci** [comment]
You are on a very old version of restic. I suggest you update.

Also, I think that is a dupe of #1954 that I reported 2 years ago.

**Comment by dimejo** [comment]
Are you joking or did you confuse 0.11.0 with 0.1.0? Actually the version used is 2 days old and from [beta.restic.net](https://beta.restic.net/).

**Comment by chrestomanci** [comment]
Apologies, Yes I did confuse that release version with a much older release.

Anyway, the bug you reported looks very similar to the one that I reported two years ago. With luck the root cause will be the same, and the fix will be easy. (I am not a restic developer, just a user who monitors the bug reports).

**Comment by fd0** [comment]
@dimejo which architecture do you run restic on? What's the output of `restic version`?

**Comment by dimejo** [comment]
@fd0:
> @dimejo which architecture do you run restic on? What's the output of restic version?

`restic 0.11.0-dev (compiled manually) compiled with go1.15.4 on linux/amd64`
Sorry for not providing the full restic version output earlier, but as it didn't include the github commit I only provided the binary name. 

Some more information in case it helps.
```
Virtualization: KVM
Operating System: Fedora 33
Kernel: Linux 5.8.17-300.fc33.x86_64
Architecture: x86-64
CPU: AMD Epyc
```

**Comment by fd0** [comment]
Huh, that's a 64 bit CPU. @dimejo can you please confirm that the restic binary is x86_64? can you run `file` on it?

**Comment by fd0** [comment]
Hm, it's not an integer overflow as far as I can see, rather it's an unsigned integer becoming "negative" somewhere.

**Comment by fd0** [comment]
@aawsome do you maybe have an idea what's going on here? :)

**Comment by dimejo** [comment]
@fd0 Unfortunately the VM was created for testing purpose and is no longer available but I'm pretty sure I was using the amd64 binary. I will try to recreate the results on a new VM tomorrow.

**Comment by aawsome** [comment]
@dimejo Thanks for reporting this bug! If you can manage to reproduce it, can you please also increase the verbosity (`-v`)? Also you can use `--dry-run` which gives the output (and should also show this bug) without modifying the repository..

**Comment by fd0** [comment]
@dimejo if you do, please run `prune` with `-v -v`, so we can get more stats. using `--dry-run` should be sufficient to get the stats.

**Comment by aawsome** [comment]
The "unused size after prune" is computed by the "unused size before prune" (only shown with `-v`) and the total prune size, which is `375.955 GiB`.  Your output suggests that the computed "unused size before prune" is smaller than the ~376 GiB. 

So it seems to me that this unused size before pruning is wrongly calculated.

I had a deeper look into the code. There is an issue with this calculation if there are duplicate blobs in the repo which most likely is the case in your setting.

**Comment by aawsome** [comment]
I just tested the repo from `cmd/restic/testdata/repo-duplicates.tar.gz` and there the same bug in the statistics occurs:
```
to repack:            2 blobs / 220 B
this removes          2 blobs / 148 B
to delete:            4 blobs / 1.726 KiB
total prune:          6 blobs / 1.870 KiB
remaining:            4 blobs / 1.718 KiB
unused size after prune: 16777216.000 TiB (100.00% of remaining size)
```
(note that we also have the same "strange" effect that prune reports that all blobs that are repacked are also removed by the repacking. This is why I assume that duplicates are also present in the repo of @dimejo.

**Comment by dimejo** [comment]
> (note that we also have the same "strange" effect that prune reports that all blobs that are reported to be repacked are also reported to be removed by the repacking.

Could this explain why different prune options for us didn't seem to make any difference?

restic_v0.11.0-g5f3b802e prune:
```
to repack:       308801 blobs / 178.132 GiB
this removes     308801 blobs / 178.130 GiB
to delete:       327405 blobs / 197.824 GiB
total prune:     636206 blobs / 375.955 GiB
remaining:      1163369 blobs / 748.739 GiB
unused size after prune: 16777215.894 TiB (100.00% of remaining size)
```


restic_v0.11.0-g5f3b802e prune --max-repack-size 0:
```
to repack:       308801 blobs / 178.132 GiB
this removes     308801 blobs / 178.130 GiB
to delete:       327405 blobs / 197.824 GiB
total prune:     636206 blobs / 375.955 GiB
remaining:      1163369 blobs / 748.739 GiB
unused size after prune: 16777215.894 TiB (100.00% of remaining size)
```


restic_v0.11.0-g5f3b802e prune --max-unused 10G:
```
to repack:       308801 blobs / 178.132 GiB
this removes     308801 blobs / 178.130 GiB
to delete:       327405 blobs / 197.824 GiB
total prune:     636206 blobs / 375.955 GiB
remaining:      1163369 blobs / 748.739 GiB
unused size after prune: 16777215.894 TiB (100.00% of remaining size)
```


restic_v0.11.0-g5f3b802e prune --max-unused 200G:
```
to repack:       308801 blobs / 178.132 GiB
this removes     308801 blobs / 178.130 GiB
to delete:       327405 blobs / 197.824 GiB
total prune:     636206 blobs / 375.955 GiB
remaining:      1163369 blobs / 748.739 GiB
unused size after prune: 16777215.894 TiB (100.00% of remaining size)
```


restic_v0.11.0-g5f3b802e prune --repack-cacheable-only:
```
to repack:        10886 blobs / 68.826 MiB
this removes     195360 blobs / 108.563 GiB
to delete:       327405 blobs / 197.824 GiB
total prune:     522765 blobs / 306.387 GiB
remaining:      1276810 blobs / 818.306 GiB
unused size after prune: 16777215.962 TiB (100.00% of remaining size)
```

**Comment by aawsome** [comment]
> Could this explain why different prune options for us didn't seem to make any difference?

When duplicates are present, the decision whether to repack those is not affected by `--max-unused`. So this explains, why you don't see any differences in your first, third and fourth output.

I have to take a closer look in the code about the second example. This might be just the same statistics error, but honestly I'm not sure...

The last example clearly shows that there is also a bug in the "to repack"/"this removes" line. Restic cannot remove more than it's repacking. 

Can you retry your tests with #3113 included? I would be happy to have an example where in fact not all duplicates are repacked, you can get this by playing around with `max-repack-size` option.

**Comment by dimejo** [comment]
I've spent quite some time today to recreate the bug but without luck so far. Completely recreating yesterday's setup wasn't possible as the original repository has ~1.1TiB and redownloading it today would have taken too long.

Let me try to describe the difference between the 2 test setups, maybe someone has an idea what's going on.

### Original Setup:
* copied the repository to a network storage that was mounted on the VM
* a backup was in progress when the copy of the repository was started
* full `prune` runs (without `--dry-run`) for all the tests

### Today's setup:
* used the original repository (Wasabi via rclone)
* new snapshots were added meanwhile
* only used `prune --dry-run`

### Today's stats for completeness:
```
to repack:        51070 blobs / 31.044 GiB
this removes      43484 blobs / 26.560 GiB
to delete:       327485 blobs / 197.998 GiB
total prune:     370969 blobs / 224.558 GiB
remaining:      1356311 blobs / 861.043 GiB
unused size after prune: 43.052 GiB (5.00% of remaining size)
```
