### ISSUE TITLE
Add more sftp options

### ISSUE THREAD

**Issue by timdeluxe** [restic/restic#312]
Hi!
At first: I saw the video of your restic talk at Froscon. It sounds great and i want to use it! :)

I have some special setup regarding SSH and so it would be nice if it would be possible to use some options for sftp.
Especially i would like to use a separate private key file (ssh option "-i") and also a separate port (ssh option "-p"). I didn't find that yet in the docs or command help.

If it is not yet existing, consider this as a feature request.

**Comment by fd0** [comment]
Thanks for giving restic a try!

Why don't you configure your ssh access to the remote server via `~/.ssh/config`? restic just calls the `ssh` binary with the host and user you provide, the rest can be configured there, e.g. add the following to use a key file:
```
Host foo
    IdentityFile ~/.ssh/foo-secret-key-file
```

This also allows configuring everything else that sftp/ssh has to offer. At the moment, I don't like adding all the configuration options for sftp to restic, so I'll close this issue. At some point later on, we need a way to configure the different backends, but for ssh this is not a problem.

**Comment by timdeluxe** [comment]
Ah thanks for the information, you are completely right. I totally forgot about that one (and didn't know that restic can use that).
Works perfectly!

**Comment by doudou** [comment]
Hi ... 

I'm writing a high-level service (run in the background) that would provide backup using restic.

The tool uses sftp connections to do local-network backups and B2 in the cloud. Local targets are auto-detected using IP and SSH keys (e.g. do different backups at home or at work).

To achieve this, one well-working mechanism I found is to provide the backup host using an IP and the host keys as a separate file, part of the service configuration. It avoids relying on a well-configured local DNS (rare) or mDNS (which I personally found unreliable).

In this context, I'd like to pass the key file to the underlying sftp process. I'd rather use the SSH config file, as it would require spreading the configuration in two different places and would require the tool to modify the user's host file (which I find ... distasteful).

Would it be possible to reevaluate this issue ? What most tools that use SSH behind the scenes do is have an option that allows to pass-through command-line options to SSH (so, minimal impact on restic's CLI).

**Comment by fd0** [comment]
It's already available: You can use `restic -r sftp:host:/path -o sftp.command "ssh host -s sftp -o option=value"` to specify the command that restic runs in order to establish the sftp connection. There, you can specify arbitrary options to `ssh`.

**Comment by doudou** [comment]
Great ! Thanks !

**Comment by mafgh** [comment]
Using `-o sftp.command "ssh ...` gives me `unknown command "ssh ...`. According to `restic --help` it's:

> -o sftp.command "ssh host -s sftp -o option=value"

When using `=` it work's for me, e.g.: `-o sftp.command="ssh ...`

**Comment by fd0** [comment]
Uh, you're right! the `=` is required, the help is wrong. I'll fix that. Thanks!

**Comment by matthijskooijman** [comment]
Revisiting this issue once more, would it make sense to also have an `sftp.ssh_options` extended option?

> It's already available: You can use restic -r sftp:host:/path -o sftp.command="ssh host -s sftp -o option=value" to specify the command that restic runs in order to establish the sftp connection. 

This requires duplicating the hostname in two places on the commandline, which is of course easy to break when forgetting to change either one. One way to solve that would be to not specify a full ssh command using `sftp.command`, but supply some extra options to add to the autogenerated command instead (another alternative would be to interpolate `$HOST` into `sftp.command`, but that gets complex quickly).

Some variations on how this could look:
 - Specify commandline arguments to ssh completely, e.g. `-o sftp.ssh_argument="-o IdentityFile=/path/to/key"` or `-o sftp.ssh_argument="-i /path/to/key"`. This is the most flexible, since you just add arguments to the command. It's also a bit messy (the `-o` for restic and `-o` for ssh can be confusing, and you'll have to split a string into arguments, which can be tricky when you also want to support spaces inside arguments).
 - Specify just ssh config options, e.g. `-o sftp.ssh_option=IdentifyFile=/path/to/key`. This is slightly less flexible, but I believe pretty much everything can be controlled with ssh -o options. One question is how to pass multiple options. Ideally, you would pass multiple `-o sftp.ssh_option=...` to restic, but I'm not sure if the current option parsing supports that. An alternative would be to have e.g. `-o sftp.ssh_option=IdentityFile=/path/to/key,User=root`, but that prevents using comma's (or whatever separator used) in option values, so that would require some kind of escaping method.

**Comment by matthijskooijman** [comment]
One more thing about the command you suggested for this:

    $ ssh host -s sftp -i /path/to/key
    subsystem request failed on channel 0

`man ssh` says:
```
     -s      May be used to request invocation of a subsystem on the remote system.  Subsystems facilitate the use of SSH as a secure transport for other
             applications (e.g. sftp(1)).  The subsystem is specified as the remote command.
```

Iow, the subsystem is not an argument to the -s option, but is taken from the positionals. And once ssh consumes the first positional, it no longer accepts option, so the `-i` above (and the `-o` in your example) are no longer accepted. So your suggestion should be: `restic -r sftp:host:/path -o sftp.command="ssh host -s -o option=value sftp"` (note that I deliberately did not put -s at the end, to prevent others from adding more options and getting the same problem).

**Comment by fd0** [comment]
> This requires duplicating the hostname in two places on the commandline, which is of course easy to break when forgetting to change either one. 

That's not the case, the host name in the repository specification is ignored when `sftp.command` is set.

> Iow, the subsystem is not an argument to the -s option, but is taken from the positionals. And once ssh consumes the first positional, it no longer accepts option, so the -i above (and the -o in your example) 

You're right, I've updated my comment above.

Unfortunately, the option parsing is already very complex, and I dislike adding more options which make the code even more complicated and confusing for users. If you need advanced options, either specify the whole command restic should invoke with `-o sftp.command`, or define a special host name in `~/.ssh/config` like [mentioned in the manual](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp).

**Comment by fd0** [comment]
Yes, it is at least mentioned in the manual: https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp

We could add an example though. Are you up for a PR?

**Comment by matthijskooijman** [comment]
> We could add an example though. Are you up for a PR?

Nope, sorry no time (also emphasized by the time it took me to respond to this...)

**Comment by JortdeBokx** [comment]
Would it be possible to set the `-o sftp.command` option using environment variables?

**Comment by trompx** [comment]
Hey @fd0,

Just spent a few hours trying to figure out the right nomenclature to use sftp.command in a bash script to set the identity file. When building a command with multiple variables/spaces/single quotes/double quotes you encounter lots of issues.
Here is what is working for me if it may help:
```
REPO=(sftp::${REPO_FOLDER} -o sftp.command='ssh '${SFTP_USER}'@'${SFTP_IP}' -i /ssh/my_private_key -s sftp')
restic -r "${REPO[@]}" snapshots > /dev/null 2>&1
```

Unfortunately, I could not figure out **how to set the repository using environment variable** `export RESTIC_REPOSITORY="$REPO"` or in this particular case `export RESTIC_REPOSITORY="${REPO[@]}"` just like @JortdeBokx suggested.
It complicates things, for sftp command I need to prefix all my restic commands with -r "${REPO[@]}" while for b2/local repo I can just set the repo via environment variable which is way more convenient.
**Is this is doable ?**

**Comment by ppxl** [comment]
> Yes, it is at least mentioned in the manual: https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp
> 
> We could add an example though. Are you up for a PR?

Hey @fd0, we at Cloudogu use `restic` intensively for scripted backup and restore. I just had a hard time figuring out the right sftp option usage from within our golang application but finally I made it :smile: If you want I can give back to the community by providing some doc changes, both for Bash and Golang.

**Comment by deliciouslytyped** [comment]
I'm running a command like `restic -o sftp.command=ssh -v -i /key my_user@my_host -s sftp -r sftp://:/somepath/restic init -v` and it keeps putting the repo relative to my home folder instead of relative to root. What gives?

**Comment by matthijskooijman** [comment]
I've been using the following command which backups in the absolute `/mnt/...` path.

    exec /usr/bin/restic --repo sftp::/mnt/goflex/backups/restic/tika --option sftp.command="ssh root@hostname -p 2202 -s -i /etc/restic/ssh.key sftp"

**Comment by mrPsycho** [comment]
`-i` (or equivalent) is needed for windows instances, cause it is much easier to use it in native binary, then install cygwin/wsl/ssh/... additionaly just to run one binary. 

for example: 
```
C:\Custom>restic.exe -o sftp.ssh_argument="-i /path/to/key" -r sftp:service@10.18.10.248:/data/backup/dc-01 init        Fatal: create repository at sftp:user@ip:/data/backup/dc-01 failed: Fatal: option sftp.ssh_argument is not known 
```
