### ISSUE TITLE
Support for ORAS (docker registry) as storage backend

### ISSUE THREAD

**Issue by dexhorthy** [restic/restic#3143]
Output of `restic version`
--------------------------
N/A -- Architecture question here. Currently released version is [v0.11.0](https://github.com/restic/restic/releases/tag/v0.11.0)

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
I'm trying to use restic as a [Velero](https://velero.io/) backend and store my snapshot contents in an OCI registry, e.g. Docker Distribution or [Harbour](https://goharbor.io/). It would be really cool if this was a supported way to store my backups offsite. ORAS provides libraries and reference implementations for storing arbitrary data in an OCI registry: https://github.com/deislabs/oras

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I'd like to be able to use restic to power backup/restore in my application without requiring an NFS mount or an S3-compliant object store. Almost every environment I deploy to has a docker registry these days, and many of them don't have NFS or S3-compliant APIs readily available.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I haven't used restic today but here's a picture of a cute animal that I hope captures my feelings about restic 🙂 

<img width="503" alt="Screen Shot 2020-11-30 at 6 29 57 PM" src="https://user-images.githubusercontent.com/3730605/100681751-0f22f100-333a-11eb-8386-55876aaeaadd.png">

**Comment by rawtaz** [comment]
Thanks for the dog :D

I'm sorry to disappoint you, but at this point in time it's highly unlikely that additional backends are added to restic, especially less commonly requested ones. Development focus is more on other features and optimizations in restic, since there's tight integration with rclone such that you can use all backends that rclone supports.

With that in mind, have you checked if it can be added to rclone? If yes, you'd be able to use it in restic too.

**Comment by aawsome** [comment]
Please also note that restic is not restricted to NFS or S3-compatible storage. In fact it supports many storage backend directly (e.g. SFTP) and much more via rclone, as @rawtaz already mentioned.
Maybe you'll find a suitable backend for you use-case that is already available.

In docker environments people sometimes use the [rest-server](https://github.com/restic/rest-server) which provides a very simple HTTP REST protocol. Running this docker image seems to me as easy as running a docker registry.

**Comment by fd0** [comment]
Thanks for the suggestion.

Adding a new native backend to restic would mean setting up backend CI tests for it. Maintaining those tests and the backend itself is a lot of work, and we'd rather improve restic. One way to get this supported would be to get it supported in `rclone`, then you'll also be able to use restic with it.

I'm going to close this issue for now, please feel free to add further comments. Thanks!
