### ISSUE TITLE
S3 diff with none-existing snapshot IDs outputs traceback on exit

### ISSUE THREAD

**Issue by nekrondev** [restic/restic#3145]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------
```shell
export MINIOURL=https://<zapped>
export AWS_ACCESS_KEY_ID=<zapped>
export AWS_SECRET_ACCESS_KEY=<zapped>
export RESTIC_PASSWORD=<zapped>

./restic -r s3:https://<minio URL>/backup diff f0000 baaaa
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Self-hosted MinIO instance

Expected behavior
-----------------
Command should not print traceback for non-existing snapshot IDs

Actual behavior
---------------
```shell
./restic -r s3:https://<zapped>/backup diff f0000 baaaa
repository 79cd9c00 opened successfully, password is correct
no matching ID found
github.com/restic/restic/internal/restic.init
        /restic/internal/restic/backend_find.go:11
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5625
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5620
runtime.doInit
        /usr/local/go/src/runtime/proc.go:5620
runtime.main
        /usr/local/go/src/runtime/proc.go:191
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
```

Steps to reproduce the behavior
-------------------------------
see example above

Do you have any idea what may have caused this?
-----------------------------------------------
Didn't look into the sources yet.

Do you have an idea how to solve the issue?
-------------------------------------------
Not yet :(

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Many thanks for creating restic!
I found out about it while searching for an easy Docker-based backup solution for my local volumes and images.

**Comment by MichaelEischer** [comment]
Thanks for reporting. This has already been fixed in #3086.
