### ISSUE TITLE
Restic Swift : Authenticate failed when user is not in the same domain as container

### ISSUE THREAD

**Issue by Laayem** [restic/restic#3147]
Hi, 

I've encountered a bug on our staging environment (company openstack). A few days ago, all users of openstack have been moved in one domain. Since we have an authentication error on all action that I intend to do (init, backup, snapshots, stats, ...). If I changed my openrc file to go back on our previous domain, all actions works flawlessly. 

Output of `restic version`
--------------------------
restic 0.10.0 compiled with go1.15.2 on linux/amd64 install with yum
restic 0.11.0 compiled with go1.15.5 on linux/amd64 build from source
restic 0.11.0 compiled with go1.15.3 on windows/amd6

How did you run restic exactly?
-------------------------------
source openrc.sh

> #!/usr/bin/env bash
> export OS_AUTH_URL="https://keystone.url.tech:5000/v3"
> export OS_PROJECT_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
> export OS_PROJECT_NAME="Company"
> export OS_USER_DOMAIN_NAME="Head_company"
> export OS_USERNAME="username"
> export OS_PASSWORD="password"
> export OS_PROJECT_DOMAIN_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
> export OS_REGION_NAME="Head"
> export OS_INTERFACE=public
> export OS_IDENTITY_API_VERSION=3

source restic-backup.config

> export RESTIC_REPOSITORY=swift:Folder:/SERVER-NAME
> export RESTIC_PASSWORD=password
> export RESTIC_BACKUPDIR="/folder1 /folder2 /folder3"

restic snapshots latest 

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Openstack Swift

Expected behavior
-----------------
```
restic@server:~>10:54 AM$./debug/restic-0.11.0/restic stats --json
{"total_size":2446320606,"total_file_count":14310}
```

Actual behavior
---------------
```
restic@server_name:~>10:54 AM$./debug/restic-0.11.0/restic stats --json
Fatal: unable to open repo at swift:BackupRecette:/SVU-INF-NSFTP: conn.Authenticate: Authorization Failed
```

Steps to reproduce the behavior
-------------------------------
On openstack, move the user used to authenticate through Keystone from one domain to an another.

Do you have any idea what may have caused this?
-----------------------------------------------
Based on debugging with a support team member of our openstack instance, we supposed OS_USER_DOMAIN_NAME is not send to Keystone.

Do you have an idea how to solve the issue?
-------------------------------------------
I don't know go but I can try to read files to understand how it works.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I use restic at home to backup my nas to B2, it works really nice. Setting up this new work environment, I wanted to use it for backing up instances.

**Comment by Laayem** [comment]
Hi again, 
Application credentials are still working though, even when the user is not in the same domain. So it's not blocking but it could be confusing for someone who managed many projects whith one account.

**Comment by MichaelEischer** [comment]
@Laayem Are you able to access the swift storage using the new openrc-file via the `swift` cli client (or maybe it's also integrated into the `openstack` one)? From a quite glance at the code it looks like the swift backend should properly pass on the configured domain (if necessary).

I'm not completely sure I understand the problem you're having: Does changing `OS_PROJECT_DOMAIN_ID` or `OS_USER_DOMAIN_NAME` back to it's old value let things work again?

You can take a look at the requests issued by restic by creating a debug log. For that you have to compile a debug build, see https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs .

**Comment by Laayem** [comment]
Hi, 
Sorry for the delay, yes, if I changed OS_USER_DOMAIN_NAME to the previous value it works. 
In both case, I can access swift via swift or openstack client. 
There is a fresh debug log, restic snapshots, first with the old OS_USER_DOMAINE_NAME, then with the new one which get error 401.

[restic-debug.log](https://github.com/restic/restic/files/5673705/restic-debug.log)

**Comment by MichaelEischer** [comment]
@Laayem Thanks for the logfile. restic did not use the `OS_PROJECT_ID` and `OS_PROJECT_DOMAIN_ID` environment variables. Can you test whether #3158 fixes that?
