### ISSUE TITLE
creating key in backend at s3://192.168.122.62/test-bucket failed:  unsupported protocol scheme ""

### ISSUE THREAD

**Issue by outbackdingo** [restic/restic#315]
I have a local S3 cluster, both riak cs and swift deployted in the lab, not on AWS

s3cmd and other tools can read/write/make/delete buckets and objects without issues
i set  AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment to match
my credentials, when running

restic init -r s3://192.168.122.62/test-bucket
enter password for new backend:
enter password again:
creating key in backend at s3://192.168.122.62/test-bucket failed: Put /test-bucket/restic/key/e2130523be50a1ced505d5607b8e35124c21d378cb901bd2de9952d550e72c30: unsupported protocol scheme ""

**Comment by fd0** [comment]
Could you take a look @howeyc?

**Comment by retrack** [comment]
+1 the ability to specify any s3 url would be a great plus.

**Comment by fd0** [comment]
I had a quick look yesterday: We need to specify a way to configured backends in general and the s3 backend in particular so that arbitrary servers can be specified. At the moment it only seems to work with Amazon, this is a limitation that should be rather easy to lift once we have a way to configure backends.

**Comment by episource** [comment]
Consider handling backend properties similiar to mount: `-o <optlist> [-o <optlist>]`  where <optlist> is passed to the backed as key(-value) list (multiple optlists joined together). In result it would look like `restic [...] -o some-flag,some-key=some-value,other-flag` with `restic [...] -o some-flag -o some-key=some-value -o other-flag` also being supported.

**Comment by fd0** [comment]
Yeah, that's similar to how openssh handles this, and I like it. Now we need to implement that ;)

**Comment by outbackdingo** [comment]
sweet, itll be nice since we dont all use AWS for S3 services........especially when we have it locally inhouse...

**Comment by aut0** [comment]
I have the same issue with

 creating key in backend at s3://eu-west-1.amazonaws.com/backup failed: Put /backup/restic/key/7bfc951b6db28bda3daea50ce02df8ffd77ea0bedd7eaae1d8e36bf9c: unsupported protocol scheme ""
