### ISSUE TITLE
Remote Prune Agent

### ISSUE THREAD

**Issue by Baker0052** [restic/restic#3153]
Output of `restic version`
--------------------------

restic 0.11.0 compiled with go1.15.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Add a Feature like Veeams "Data Mover".
If the Repo is reachable via SSH, restic could (s)cp itself to the repository and do the prune / package rewrite on the remote site "locally".
This would speed up the prune as there is no data tranfered from the local restic to the repo.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Like restic -r sftp:resticuser@restic-repo//remote-repo/ --remote-prune

------------------------------------------------------------

**Comment by rawtaz** [comment]
This would require the encryption keys being exposed on that remote system. Why don't you just run restic on that remote system yourself, if it's accessible via SSH?

**Comment by Baker0052** [comment]
Because it would be easier?
is it getting "exposed" if the local restic is passing the encryption key to the remote restic instance?

**Comment by rawtaz** [comment]
Yes, wherever a restic-like process that needs to look inside the encrypted repository is running, that system needs to have the encryption key in memory, otherwise restic can't do its work.

**Comment by Baker0052** [comment]
Okay if you think this is a bad idea then close this.
Just thought about it because Veeam is doing something similar.
https://helpcenter.veeam.com/docs/backup/vsphere/backup_architecture.html?ver=100

**Comment by rawtaz** [comment]
I don't see it happening any time soon, if I put it that way :) The topic of "agents" have been discussed before.

Regarding Veeam, it does all of it's encryption on the source side, before it's sent through the Data Mover (unless I'm misunderstanding that component).

**Comment by fd0** [comment]
While in theory it would be possible to do that, you can already achieve it by running restic on the server itself (if you trust it enough to give the password to the remote process). We'll concentrate on improving restic's other features instead of introducing new ones. :)

I'm closing this issue for now, please feel free to add further comments. Thanks!
