### ISSUE TITLE
Scality S3 repositories broken after the 0.10 release

### ISSUE THREAD

**Issue by rfc1036** [restic/restic#3154]
Output of `restic version`
--------------------------

```
restic 0.11.0-dev (compiled manually) compiled with go1.15.4 on linux/amd64
```

Downloaded from https://beta.restic.net/restic-v0.11.0-175-g3264eae9/.

How did you run restic exactly?
-------------------------------

Any access to the repository fails, `restic stats` is enough to show the issue.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

S3-compatible provided by Scality. My other SFTP-based repository still works.

Expected behavior
-----------------

This is a regression since 0.10, which used to work.

Actual behavior
---------------

Any access to the repository fails with:

```
List(key) returned error, retrying after 582.280027ms: A header you provided implies functionality that is not implemented.
...
List(key) returned error, retrying after 16.927710407s: A header you provided implies functionality that is not implemented.
Fatal: A header you provided implies functionality that is not implemented.
```

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic made doing backups pleasant for me.

**Comment by fd0** [comment]
Can you maybe check if the following option works: `-o s3.list-objects-v1=true`?

**Comment by rfc1036** [comment]
Confirmed. I will tell the vendor to fix their software, thank you.

**Comment by fd0** [comment]
Thanks for the feedback!
