### ISSUE TITLE
crash when reading data for check or prune

### ISSUE THREAD

**Issue by dwsail** [restic/restic#3159]
Output of `restic version`
--------------------------

`restic 0.11.0 compiled with go1.15.3 on darwin/amd64`

How did you run restic exactly?
-------------------------------

No environment variables
Running on macOS Big Sur on Apple Silicon

I did a 'restic check' and restic told me that `10359 additional files were found in the repo, which likely contain duplicate data.
You can run ``restic prune`` to correct this.`
This makes actually little sense because I never deleted a snapshot (or I don't remember anymore what I did during the past week). Nevertheless I decided that I should probably prune to clean the repo.

```
% ./restic -r /Volumes/Volume/backup --verbose prune
enter password for repository:
repository 61ff265e opened successfully, password is correct.
counting files in repo.
building new index for repo.
assertion failed [*ret_index + 2 == num_insts]: RET should be second last instruction in translation.
(StateRecovery.cpp:304 check_cfg)
```

`restic check --read-data-subset` also fails somewhere in the middle in the same way.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
- exFAT partition on external hard drive.
- repository created a few days ago (in Windows). Backed up 5PCs to it.
- Resized the partition. Afterwards copied the repo to a new partition.

Expected behavior
-----------------

- No crash ;-)
- prune operation and clean repository afterwards.

Actual behavior
---------------

Restic suddenly hangs somewhere in the middle with 100% CPU and no disk access. Then I kill it manually after a few minutes. Then I need to remove the stale lock and I can try again...

Steps to reproduce the behavior
-------------------------------

reproducible when pruning or checking data (`restic check` without `--read-data` works)

Do you have any idea what may have caused this?
-----------------------------------------------

Maybe the funky stuff that I did to this partition (resizing).
Nevertheless restic should never crash like this.

Do you have an idea how to solve the issue?
-------------------------------------------

No.

**Comment by MichaelEischer** [comment]
This seems to be a bug in the Rosetta 2 binary translation layer, see https://github.com/golang/go/issues/42700 .
The workaround for now seems to be to set the environment variable `GODEBUG=asyncpreemptoff=1`.

**Comment by dwsail** [comment]
Just tested it. It is the same issue. So I would not consider it an restic issue. Should I close the issue?

**Comment by MichaelEischer** [comment]
Let's close the issue for now as there's no fix needed for restic. Once Go 1.16 is released we can try to provide native binaries for the macOS on ARM.
