### ISSUE TITLE
Linux system freezes for several minutes during backups

### ISSUE THREAD

**Issue by SteveSimmons** [restic/restic#316]
I am using restic for a 200GB backup on Ubuntu 10.04 on an i7-5500 CPU with 8GB RAM. Several times during the 20 minute backup cycle, restic grabs all resources and the Linux GUI becomes completely unresponsive for a minute or two.  

Is this a known problem and are there any simple options within restic itself for limiting resource usage? I guess I could use 'nice' to start restic with a lower priority, though I only think of it once my system has locked up.

**Comment by fd0** [comment]
Hey, thanks for the report. I don't think that restic is able to freeze your system all on its own, I rather guess that restic consumes so much memory that your system starts to swap. At least that was what I observed sometimes. Could you check if my hypothesis is plausible? E.g. you could observe `htop` while running the backup and leave `vmstat 1` running?

For now, I'll classify this as (another, unfortunately) report of exhaustive memory usage.

**Comment by fd0** [comment]
I've worked a lot on memory issues in the last couple of days, could you give it a try again? If it fails again, please run it while watching `htop` and `vmstat 1` so we can investigate.

**Comment by cfcs** [comment]
On Linux:

CPU lockups: `nice` and `renice`

IO lockups (MOST likely your problem): `ionice`

**Comment by fd0** [comment]
I'm closing this issue, if you have the time to test it again, please add a comment.
