### ISSUE TITLE
Flags for the prune command are not shown in the cli help

### ISSUE THREAD

**Issue by ibib** [restic/restic#3160]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------
`restic snapshots -h && restic prune -h`

Expected behavior
-----------------
Show the prune relevant feature flags like for the snapshots command.

```
...
Usage:
  restic snapshots [flags] [snapshotID ...]

Flags:
  -c, --compact           use compact output format
  -g, --group-by string   string for grouping snapshots by host,paths,tags
  -h, --help              help for snapshots
  -H, --host host         only consider snapshots for this host (can be specified multiple times)
      --last              only show the last snapshot for each host and path
      --path path         only consider snapshots for this path (can be specified multiple times)
      --tag taglist       only consider snapshots which include this taglist (can be specified multiple times) (default [])

Global Flags:
....
```

Actual behavior
---------------

The help for max-unused, max-repack-size, repack-cacheable-only and dry-run is missing.

```
...
Usage:
  restic prune [flags]

Flags:
  -h, --help   help for prune

Global Flags:
....
```

Restic just lists the help flag and not 

Steps to reproduce the behavior
-------------------------------

run: `restic snapshots -h && restic prune -h`

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is as always a great piece of software. 😁

**Comment by ibib** [comment]
I did not test and think it through properly.
Apparently I can't use these commands in the current stable version.
I just assumed they were already released.

**Comment by fd0** [comment]
😃
