### ISSUE TITLE
restic 0.11.0 doesn't expand '~' sign in repo init command

### ISSUE THREAD

**Issue by ulimit1** [restic/restic#3169]
Just installed restic from official release page https://github.com/restic/restic/releases/tag/v0.11.0 on my ubuntu 18.04
There was previously installed version via apt-get. Previous version was:
restic 0.8.3
compiled with go1.10 on linux/amd64

However, I removed it via apt-get remove restic
On version 0.11.0, If run from home user folder e.g. /home/<user>
`restic init --repo=~/tmp/restic_repo`
it leads to creation of '~' folder in /home/<user> folder, so the real path is
`~/~/tmp/restic_repo`

Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

Steps to reproduce the behavior
-------------------------------
```
sudo cp ~/Downloads/restic_0.11.0_linux_amd64 /usr/bin/restic
sudo chmod 755 /usr/bin/restic
restic init --repo=~/tmp/restic_repo

**Comment by fd0** [comment]
That's an issue with your shell: restic does not expand `~`, and your shell only expands it at the beginning of a string. Use `restic init --repo ~/tmp/restic_repo`.

I'm closing this issue for now, please feel free to add further comments. Thanks!

**Comment by ulimit1** [comment]
Thank you for your fast feedback!
