### ISSUE TITLE
Connection error for Google Bucket with S3 backend

### ISSUE THREAD

**Issue by ppxl** [restic/restic#3172]
Hey, thank you for the awesome restic tool. We use restic for years in our production and test systems because of the very aspects of security, robustness, and speed.

I just updated my test stage from restic 0.9.6 to restic 0.11.0. When starting any restic command, strange errors occurred:
```
List(key) returned error, retrying after 462.318748ms: A header or query you provided requested a function that is not implemented.
```

No files could be backed up to our remote backup repository. Reading files from the remote backup repo did not work out either.

Output of `restic version`
--------------------------
`restic 0.11.0 compiled with go1.15.3 on linux/amd64`

How did you run restic exactly?
-------------------------------
```
export AWS_ACCESS_KEY_ID=magicKeyGoesHere
export AWS_SECRET_ACCESS_KEY=anotherMagicKeyGoesHere
export RESTIC_REPOSITORY="s3:https://storage.googleapis.com/my-backup-bucket/reponame"
restic snapshots
enter password for repository: 
List(key) returned error, retrying after 462.318748ms: A header or query you provided requested a function that is not implemented.
List(key) returned error, retrying after 890.117305ms: A header or query you provided requested a function that is not implemented.
List(key) returned error, retrying after 636.341646ms: A header or query you provided requested a function that is not implemented.
List(key) returned error, retrying after 1.107876242s: A header or query you provided requested a function that is not implemented.
List(key) returned error, retrying after 1.511079094s: A header or query you provided requested a function that is not implemented.
List(key) returned error, retrying after 3.04096222s: A header or query you provided requested a function that is not implemented.
List(key) returned error, retrying after 5.781953173s: A header or query you provided requested a function that is not implemented.
List(key) returned error, retrying after 11.222385136s: A header or query you provided requested a function that is not implemented.
List(key) returned error, retrying after 9.152900914s: A header or query you provided requested a function that is not implemented.
List(key) returned error, retrying after 16.927710407s: A header or query you provided requested a function that is not implemented.
A header or query you provided requested a function that is not implemented.. Try again
enter password for repository: 
                               signal interrupt received, cleaning up

# These commands failed as well in the same fashion but with different exponential backup timeout
# Also I panicked in my CLI calls
restic -v -v -v snapshots
restic -v -v -v stats
restic unlock
restic check
restic --cache-dir /root/.cache/restic snapshots
restic --cache-dir /root/.cache/restic migrate
restic --cache-dir /root/.cache/restic check
restic -v -v -v --cache-dir /root/.cache/restic migrate
# failed because --option s3.list-objects-v1=true sems not to be available any longer (I found it in the restic docs)
restic --option s3.list-objects-v1=true --cache-dir /root/.cache/restic snapshots

# a new repo was initialized without error
export RESTIC_REPOSITORY="s3:https://storage.googleapis.com/my-backup-bucket/reponamenew"
restic init
# anyhow accessing it failed again
restic snapshots
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
- restic S3 backend
- Google Bucket via S3 access
- Debian/Ubuntu (18.04 LTS bionic) running in a Google Compute Engine VM, n1-standard-4 (4 vCPUs, 15 GB RAM) , plenty of HDD

Expected behavior
-----------------
1. successful reading of restic snapshots
   - `restic snapshots`
1. successful writing of restic snapshots and tags
   - `restic backup --tag xyzzy /path/to/file`
2. usual response time

Actual behavior
---------------
1. long response time
   - ~ 16 seconds
2. error output
   - see above under `How did you run restic exactly?`
   - `List(key) returned error, retrying after 9.152900914s: A header or query you provided requested a function that is not implemented.`
3. restic's core functionality no longer works
   - I needed to ^C the restic because restic asked again for an encryption key

Steps to reproduce the behavior
-------------------------------
1. create a Google storage S3 access
   - f. i. by AWS S3 migration https://cloud.google.com/storage/docs/migrating
2. configure AWS access key
3. configure AWS secret key
4. configure backup repository path

Do you have any idea what may have caused this?
-----------------------------------------------
- possibly removing S3 List V1 requests against Google's S3 endpoint

Do you have an idea how to solve the issue?
-------------------------------------------
- downgrading to restic 0.10.0 worked out good

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Hah, not today :wink: but usually restic makes me and my team super happy. Keep on the good works! :muscle:

**Comment by MichaelEischer** [comment]
Can you check whether the following option works  `-o s3.list-objects-v1=true`? See #3083 for more details.

**Comment by Subaro** [comment]
Hi, thank you for fast feedback. We tested the flag `-o s3.list-objects-v1=true` with a beta version of restic and it worked without any problems. This issue can be closed from our point of view :+1:

**Comment by ppxl** [comment]
Thank you for your swift support! I am closing this issue if the beta works out. :clap:
