### ISSUE TITLE
Allow checking a read-only repository (e.g. disable locking)

### ISSUE THREAD

**Issue by episource** [restic/restic#318]
**Restic version:** e738d35

**Expected behavior:** `restic check` should support checking repositories stored on a read only mounted filesystem.

**Observed behavior:** restic fails to acquire exclusive lock, but the lock is not actually necessary due to the filesystem being read only
```
$ restic -r /media/backup-intern/restic/limucs-main.repo check
enter password for repository:
Create exclusive lock for repository
open /media/backup-intern/restic/limucs-main.repo/tmp/temp-278668902: read-only file system
```

**Comment by fd0** [comment]
Could you explain your use case, please? Is this something like an archived version of the repository that won't be written to again?

**Comment by episource** [comment]
Context: All my backup drives are mounted read-only per default. This is mainly to keep the backups save even in case of inexcusable adminstrative errors like doing `rm -rf /` as root. I know, something like that should never happen and in this dramatic form never happened to me, but I want to be on the safe side...

So, what about `restic check`: I do think a good integrity checker should not modify the backup set as per definition verifying integrity means **reading** all the data and making sure it is consistent, complete and unmodified (and can be restored without errors). As result, an integrity checker should get along with read only access as long as it is not told to fix errors. The reverse conclusion is, that an integrity checker that does not need write access is more convincing as it does not violate any implicit assumptions!

**Comment by fd0** [comment]
I can see your point. By default, the only thing `restic check` does is create an exclusive lock so that other processes won't move things around in the repo. What about adding a switch `--no-lock` that does not create a lock, so a read-only repository can be checked?

**Comment by episource** [comment]
This would work for me. However the solution appears incomplete: Restic should try to determine whether a repository is stored on read only storage. Usually I'd try to open/create any file using O_WRONLY and check whether open returns EROFS. Don't know whether this is possible in go...

**Comment by fd0** [comment]
This is certainly possible, but local storage is not the only backend, and the abstraction for the backends at the moment does not allow testing for this. So the easiest way would be to allow checking (and restore) without locking the repository.

**Comment by fd0** [comment]
I've retitled the issue to a more generic one, I suppose that you'd also like to e.g. restore from a read-only fs.

**Comment by episource** [comment]
Today I ran restic check on an repository last updated ~ 2 weeks ago and restic started to convert indices into a new format. While I can understand why restic does so, an integrity check should not modify existing data when not explicitly told do so. This confirms my decision mounting my backup media read-only per default. Now I'd even more like restic to support read only mounted repositories.

**Comment by fd0** [comment]
I can see your point. Do you have a proposal how we should handle things like the index conversion?

**Comment by episource** [comment]
#### Index Conversion
I think index conversion should require an explicit user action like `restic check --upgrade` and could also be integrated into a future repair option like `restic check --repair` or `restic check --rebuild-index`. 

Any operation that requires index conversion should exit with an informational text on how to convert the index to a new format. In general a user should be warned if an exisiting repository is modified such that he can't go back to the version initially used to create the repository! 

## Read Only Repository Support
Couldn't the backend interface be extended such that it allows checking whether the repository is stored read only? Alternatively it might be possible to tweak the local storage backend's (un)lock methods such  that they always return true in case of a read only repository without doing anything.

**Comment by fd0** [comment]
We will implement checking, restoring and fuse mount read-only with a flag. Index conversion will be handled by the new `rebuild-index` command and will be removed from `check`.

I don't think that it is possible for all backends to test whether they are mounted read-only, we'll add a manual switch for now. If you have a good idea how to do this automatically, please let us know.

**Comment by fd0** [comment]
This has been addressed in #350 (add `--no-lock` option) and #252 (remove automatic index conversion from check)

**Comment by episource** [comment]
#350 (+#252) makes restic comaptible with my usage scenario. So I'm happy with both improvements. 

However: You (and especially @fw42) want as few configuration parameters as possible, but good autoconfiguration instead (see also https://github.com/restic/restic/issues/322#issuecomment-150846444 and #312). This bites with the new `--no-lock` option. In the mid-term you should probably come up with an automated read-only backend detection... e.g. you might just ignore EROFS within local filesystem backend's lock implementation.

**Comment by fd0** [comment]
You're right, and I'll add an issue to track that, thanks.

**Comment by fd0** [comment]
I've added #351.
