### ISSUE TITLE
Can't give multiple --tag switches

### ISSUE THREAD

**Issue by seqizz** [restic/restic#3183]
Hi again :wave:

Since I’m using master as close as possible, [one of the recent commits](https://github.com/restic/restic/commit/ae441d31348ab714fbe3e0a09d2bc68847617dec) turned out to be backwards-incompatible.

Now if we give `--tag tag1 --tag tag2` while getting a backup, restic ignores previous switches and only applies last given tag.

Help switch after the change says:

```
add tags for the new snapshot in the format `tag[,tag,...]` (can be specified multiple times) (default [])
```

for --tag switch, which is a bit confusing. I can only specify multiple tags, not the --tag switch multiple times.

(Redirected from [forum](https://forum.restic.net/t/a-small-question-about-new-tag-syntax/3384))

**Comment by fd0** [comment]
It's a bug, thanks for the report!

**Comment by fd0** [comment]
@SkYNewZ would you mind having a look? I think it should be `restic.TagLists` (plural) instead of `restic.TagList` (singular), similar to the other commands. And the Archiver can maybe just take a `[]string` for the tags. Thoughts?

**Comment by SkYNewZ** [comment]
I will take a look yes. I remember using the "plural" type breaks lot of code and needs lot of refactoring.

**Comment by fd0** [comment]
Let me know if you need help :)

**Comment by MichaelEischer** [comment]
@fd0 We probably want to use `TagLists` and then add a `Flatten` method to merge these TagLists into a single list in the archiver. Wouldn't using `[]string` effectively revert the tagging cleanup PR?

**Comment by fd0** [comment]
I agree, we'll need a `Flatten()` method somewhere.

My comment about `[]string` was meant for this place here:

https://github.com/restic/restic/pull/2690/files#diff-736efc0255c6c13320a149b77163baaba32487f9d671a83d3c5dff27acdae22bR720

**Comment by MichaelEischer** [comment]
I think it's easier to use a `TagLists` here and just `Flatten()` it to a `TagList` when necessary. We'd still have to convert a `[]string` into individual tags.
