### ISSUE TITLE
QuObjects / S3: Unmarshal: invalid character 'c' after top-level value. Try again

### ISSUE THREAD

**Issue by jschanz** [restic/restic#3190]
Output of `restic version`
--------------------------

`
restic 0.11.0 compiled with go1.15.3 on linux/amd64
`

How did you run restic exactly?
-------------------------------
```
restic -r s3:http://192.168.4.200:8010/backup init

enter password for new repository: ***
enter password again: ***
created restic repository e1164b40d0 at s3:http://192.168.4.200:8010/backup

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
```
```
restic -r s3:http://192.168.4.200:8010/backup backup /data
enter password for repository: 
Unmarshal: invalid character 'c' after top-level value. Try again
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

QNAP - QuObjects with S3 compatibility layer

Expected behavior
-----------------
Backup should work

Actual behavior
---------------

init ist working, key and config will be created, but afterwards any access to the repo throws the following error message due some QuObject specific entries in all files

```
Unmarshal: invalid character 'c' after top-level value. Try again
```

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

It seems the key is "manipulated" by QuObjects S3 layer

```
1c3;chunk-signature=f71628090bede39a1d94115adbed4cd860c4ef30dd98536fb83e998b12a30e99
{"created":"2020-12-23T09:35:05.124988332+01:00","username":"root","hostname":"file-01","kdf":"scrypt","N":32768,"r":8,"p":1,"salt":"E/U3zZSq9dz7L98ek6uzIfLzS25buk3fn7S1jFgB7eZO6yyBQPqyswZRMrZJ1QfV/CNRYEk7IkH4aofCh8r19w==","data":"LfUjjIngZe5DAg1I2Ma/wl7PC6YkMpjJZPBr4HlnZMMk+NDKUWRb4JeeTepdThAmh28BV3z6CwBjpTLfcoz5da+a52xRv8ThnfsL/OaFCPGTGyN9uCz5CvhDVX7rdxcYtGxZ6a4tkwENDqzACIdVz5p67teXH4iLZ0dr4KzwhaLZlN5zkAdDV9YSw1BTyU9yAb5vRm/ani7hBRi80UmMEA=="}
0;chunk-signature=4246a697d4135afaeaaf94aba8b933d33e297ad38f614b171ad8e1cacd6efe00
```

There are two additional lines (line 1 and 3) I don't have on Minio or any other S3 compatible storages I tried yet. Maybe this is something QNAP-specific.

Also the config file will get two new lines on every change:

```
9b;chunk-signature=66ddcd9c0557789f020cb96659c3a84e9abe1e7d7aa825d38c324208a41807ef
j\F5PT\94U\C78\84t\E1/\D3\DC1\B0\(_KM\B2h7\F1\FB#\93\8B\C14\D9\D34v\E1\98\C1\8B\F1\F1\C8H@\EAr\A0\E4\F9bHs\B8Q9\DCcQ\CE\C3'b,X\EBhM\B6\85\A8*Ѫn\A7]11\E7rp \B1\B4M\9896K\B5\A2e\FD\C5N\A9\00\F8\B8x\DC׺\D9FwC>\99\8D\86\CDt\E4{\C0\9C\9B\E2
\AE 7\F5\F44\C1\CE\E3\D6\FC\9A
\8D_{L\EF\C8\CD
0;chunk-signature=1e24fc65824c33800a32d8caf7c91150c8c7e6aeba1ded629203103635ed9630
```

Do you have an idea how to solve the issue?
-------------------------------------------

Maybe we could skip lines which aren't in JSON for the key or include an option to detect or specify QNAPS QuObjects with his special characteristics?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic makes me alway happy :) Thanks...

**Comment by fd0** [comment]
Apparently, the QNAP service isn't really compatible with S3. The `chunk-signature` you're seeing is a standard feature of the AWS S3 protocol (as far as I know), see here: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

> Maybe we could skip lines which aren't in JSON for the key or include an option to detect or specify QNAPS QuObjects with his special characteristics?

Thanks for the suggestion, but I'm strictly against doing that. :)

Either QNAP is compatible with S3 or not, but we're not going to add high-maintenance workarounds that are hard to test against.

I'm closing this issue for now, please feel free to add further comments. Thanks!

**Comment by jschanz** [comment]
No problem... Thanks for feedback.
As a hint for others who want to use QuObjects, restic is working flawlessly with the OpenStack-Swift implementation of QuObjects.

**Comment by fd0** [comment]
Thanks for the feedback, glad you could get it working with your device! :)
