### ISSUE TITLE
Add MIPS architecture to releases

### ISSUE THREAD

**Issue by whysthatso** [restic/restic#3191]
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

offer mips architecture releases

What are you trying to do? What problem would this solve?
---------------------------------------------------------

i'm running a couple of mips devices all of which do have some state i'd like to backup with restic. they are usually so low on compute power and memory that compiling on them is wishful thinking. crosscompiling on my laptop is something i just haven't figured out, and i thought it might be an easy thing to add to the release process right here :)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

srsly :* i've just automated all my backups with ansible and restic :D

**Comment by fd0** [comment]
Which architecture(s) do you need? There are `mips` and `mipsle` as well as `mips64` and `mips64le`...

Cross-compilation in Go is **really** easy: Install the Go compiler, then build restic e.g. for `mips64` like this: `GOARCH=mips64 go build -o restic ./cmd/restic`. That's it, done. You can then run the resulting `restic` binary on mips.

**Comment by whysthatso** [comment]
ui, how neat. mipsle was the arch in question, for gnubee, a little opensource nas box.

crosscompiling worked like a charm, should have looked into [the docs](https://github.com/restic/restic/blob/master/doc/020_installation.rst)

thanks for the help

**Comment by fd0** [comment]
In your opinion, is it valuable if we offer binaries for all the MIPS architectures?

**Comment by whysthatso** [comment]
thank you for the consideration. indeed my use case is such that i manage my own and other infrastructure with ansible, and i'm using https://github.com/arillso/ansible.restic to manage restic backups which in turn depends on this very github repo's releases. so that would be the first argument.

the second argument is the problem of resources on a lot of mips* devices. usually they are extremely low end, and in my case i wouldn't be able to compile it on the target device, so i always have another machine dependency. this is probably true for a lot of devices that could be helped to manage their backups in a consistent manner with a tried and proven tool like restic.

so if this would be just another couple of entries in your ci, and given that backups is something that every architecture should get to do as easy as possible, it'll be a great favor to the public, for sure.

if you wanna go all bonkers it would be an interesting sidequest to minimize memory footprint, because as mentioned above - low end devices, every byte counts :D

**Comment by fd0** [comment]
Yeah, there's not so much we can do about the memory usage, but let's see how much longer our CI runs when cross-compiling for `mips*`
