### ISSUE TITLE
Improve progress information for non-interactive usage

### ISSUE THREAD

**Issue by Syphdias** [restic/restic#3194]
Output of `restic version`
--------------------------
```
$ /home/restic/bin/restic version
restic 0.11.0 (v0.11.0-215-g8efb874f) compiled with go1.15.6 on linux/amd64
```

How did you run restic exactly?
-------------------------------
I run restic backups, checks, forgets and prunes through systemd and I use templates for running it with different configurations. In this case: `bash -c '/home/restic/bin/restic $(</home/restic/restic.s3.check)'` will be executed by systemd which expands to `bash -c '/home/restic/bin/restic check --read-data -o s3.list-objects-v1=true'`. This leads to lot of stdout output which then "spams" the journal as you can see with `journalctl`.

```
❯ systemctl cat restic-run-s3@.service
# /usr/lib/systemd/system/restic-run-s3@.service
[Unit]
Description=Run restic job with parameters from /home/restic/restic.s3.%i
OnFailure=status-mail@%n.service

[Service]
Type=simple
Nice=10
IOSchedulingClass=best-effort
IOSchedulingPriority=7
User=restic
Environment="HOME=/home/restic"
EnvironmentFile=/home/restic/restic.s3.env
ExecStart=bash -c '/home/restic/bin/restic $(</home/restic/restic.s3.%i)'
❯ sudo systemctl start restic-run-s3@check.service && sudo journalctl -fu $_
-- Journal begins at Sun 2020-07-12 14:07:29 CEST. --
[...]
Dec 26 01:15:47 machine systemd[1]: Started Run restic job with parameters from /home/restic/restic.s3.check.
Dec 26 01:15:48 machine bash[77720]: using temporary cache in /tmp/restic-check-cache-618104479
Dec 26 01:15:49 machine bash[77720]: created new cache in /tmp/restic-check-cache-618104479
Dec 26 01:15:49 machine bash[77720]: create exclusive lock for repository
Dec 26 01:15:49 machine bash[77720]: load indexes
Dec 26 01:16:03 machine bash[77720]: check all packs
Dec 26 01:16:07 machine bash[77720]: check snapshots, trees and blobs
Dec 26 01:17:32 machine bash[77720]: read all data
Dec 26 01:17:33 machine bash[77720]: [0:01] 0.00%  0 / 23628 packs
Dec 26 01:17:34 machine bash[77720]: [0:02] 0.01%  2 / 23628 packs
Dec 26 01:17:35 machine bash[77720]: [0:03] 0.02%  4 / 23628 packs
Dec 26 01:17:36 machine bash[77720]: [0:04] 0.02%  5 / 23628 packs
Dec 26 01:17:37 machine bash[77720]: [0:05] 0.03%  7 / 23628 packs
Dec 26 01:17:38 machine bash[77720]: [0:06] 0.04%  9 / 23628 packs
Dec 26 01:17:39 machine bash[77720]: [0:07] 0.04%  10 / 23628 packs
Dec 26 01:17:40 machine bash[77720]: [0:08] 0.06%  14 / 23628 packs
Dec 26 01:17:41 machine bash[77720]: [0:09] 0.06%  15 / 23628 packs
Dec 26 01:17:42 machine bash[77720]: [0:10] 0.07%  16 / 23628 packs
Dec 26 01:17:43 machine bash[77720]: [0:11] 0.08%  19 / 23628 packs
Dec 26 01:17:44 machine bash[77720]: [0:12] 0.08%  20 / 23628 packs
[...]
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3

Note: I compiled it myself because I needed ListObjects v1. I could not test this, but I would except it to be unrelated to this flag.

Expected behavior
-----------------
The expected behavior would be to not have this output on stdout but on the tty so it is displayed in a interactive shell but not in the journal. I think the `restic backup` command does it like this or it registers the absence of a interactive session and behaves differently.

Actual behavior
---------------
restic is unaware of context and writes to much stdout logs (to the systemd journal).

Steps to reproduce the behavior
-------------------------------
Run `restic check --read-data` through a systemd service `restic-unit.service` and check the progress with `journalctl -fu restic-unit.service`.

I think this can also reproduced by running: `restic check --read-data -o s3.list-objects-v1=true | cat`

Do you have any idea what may have caused this?
-----------------------------------------------
The best guesses are that `restic check` is unaware that the context it is running in is non-interactive, for example through a pipe, or is writing progress to stdout instead to tty (unlike other commands that display progress).

Do you have an idea how to solve the issue?
-------------------------------------------
If my guesses are correct, I would check the other progress display commands and adjust the one for `restic check` accordingly.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I went from manual backup to 5min snapshots for my home directory and it is the best!

**Comment by fd0** [comment]
Thanks for the report. We've deliberately changed the behavior, but @MichaelEischer and I agreed that restic should not print progress information for non-interactive use by default. So we're using this issue for tracking.

restic should:
 * Print progress information by default on interactive terminals (limited by `$RESTIC_PROGRESS_FPS`)
 * Not print progress information on non-interactive terminals (like `restic | cat` and `cron`/`systemd`)
 * Print status information when certain signals are received (`SIGINFO`/`SIGUSR1`, similar to `dd`)

**Comment by MichaelEischer** [comment]
I've opened #3199 which reverts the progress progress updates to the old behavior. As an additional change `$RESTIC_PROGRESS_FPS` also applies to non-interactive terminals. That is it is possible to get the current behavior by setting `RESTIC_PROGRESS_FPS=1`, the possibility for continuous status updates was requested in #2706.

**Comment by MichaelEischer** [comment]
We could allow the usage of floating point numbers in `RESTIC_PROGRESS_FPS` to allow reducing the output to e.g. once every minute using `RESTIC_PROGRESS_FPS=0.01666`. That would also solve #2706. Using a new environment variable would also be possible, however, I'd like to only have a single environment variable to control the progress output frequency.

**Comment by Syphdias** [comment]
> Thanks for the report. We've deliberately changed the behavior, but @MichaelEischer and I agreed that restic should not print progress information for non-interactive use by default. So we're using this issue for tracking.

So if I understand correctly: The behavior of `restic check` was a change that is now being reverted to the (old) behavior like `restic backup`. But to enable some form of progress in non-interactive sessions two things should/will be implemented (one of them in #3199): Response to signals and awareness of `RESTIC_PROGRESS_FPS` (but only if set).

Did I understand that correctly?

**Comment by fd0** [comment]
> Did I understand that correctly?

As far as I remember yes. The "print status information when signal is received" is already implemented and #3199 does the rest.

**Comment by Syphdias** [comment]
I didn't know about either mechanics. As soon as `RESTIC_PROGRESS_FPS` will work for non-interactive, I will add it to my systemd environment (with a value >>1 :wink:).

Thank you very much for your work, both of you, @MichaelEischer, @fd0!

**Comment by MichaelEischer** [comment]
I've just noticed that the progress reporting of the backup command does not support `SIGUSR1` or `RESTIC_PROGRESS_FPS` for non-interactive terminals. That will require quite a few additional changes to keep the behavior consistent.

**Comment by anton-ryzhov** [comment]
> We could allow the usage of floating point numbers in RESTIC_PROGRESS_FPS to allow reducing the output to e.g. once every minute using RESTIC_PROGRESS_FPS=0.01666. … Using a new environment variable would also be possible, however, I'd like to only have a single environment variable to control the progress output frequency.

I find it rather confusing now. I was very surprised when I first found that it's possible to forcefully enable progress for non-interactive using "FPS". It turned out it was [first introduced to really fix rendering performance](https://github.com/restic/restic/pull/1384).

I'd expect something like RESTIC_PROGRESS_INTERVAL for non-interactive use-case and longer intervals, and RESTIC_PROGRESS_FPS for interactive mode.
