### ISSUE TITLE
restic forget fails "Data blobs seem to be missing"

### ISSUE THREAD

**Issue by FrankBBx** [restic/restic#3201]
Output of `restic version`
--------------------------
```
restic 0.11.0 compiled with go1.15.3 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```
restic forget -r "**********" -p /**** \
  --limit-download 10240 \
  --limit-upload 10240 \
  --keep-hourly 12 \
  --keep-daily 7 \
  --keep-weekly 4 \
  --keep-monthly 3 \
  --prune
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rest-server
```
rest-server 0.10.0 compiled with go1.15.2 on linux/amd64
```

Expected behavior
-----------------
I would expect an output like "all good".

Actual behavior
---------------

```
repository 417baf0b opened successfully, password is correct
Applying Policy: keep 12 hourly, 7 daily, 4 weekly, 3 monthly snapshots
keep 16 snapshots:
.......
remove 1 snapshots:
.......
[0:00] 100.00%  1 / 1 files deleted
counting files in repo
building new index for repo
[0:00] 100.00%  190 / 190 packs
repository contains 190 packs (5118 blobs) with 710.538 MiB
processed 5118 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 16 snapshots
[0:00] 100.00%  16 / 16 snapshots
Fatal: [<data/02f1c0c4> <data/0f4dc594> <data/af655ab0> <data/963eb571> <data/25895d37> <data/a6697040> <data/2819f7ae>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
```

Steps to reproduce the behavior
-------------------------------

- run `restic backup` - this seems to work
- run `restic forget` - fails as describe above

Do you have any idea what may have caused this?
-----------------------------------------------
No, I don't.

Do you have an idea how to solve the issue?
-------------------------------------------
I tried with `rebuild-index` and also tried `restic prune` after `forget` but it did not solve the problem.

**Comment by MichaelEischer** [comment]
As the backup repository is rather small please create a backup copy of it to allow investigation of the repository corruption if necessary.

Were all snapshots created using restic 0.11.0? Did you notice any errors reported during `backup` runs? Is the host creating the backups a pc / server which is always on or rather a portable laptop which might have been interrupted during a backup / prune run? Do you have scripts that automatically call `unlock`? Did you run `check` from time to time? Is the backup repository used for multiple hosts?

The first step to repair the repository is to assess the actual amount of damage. Please run `restic check --read-data` for this.

**Comment by FrankBBx** [comment]
Hi @MichaelEischer ,

to answer your questions:
- no, the backups were first created by an older restic version, then restic was updated when there was a new release and new snapshots were created with the new version. The problem started to occur recently but it was already there with restic 0.10.0. I updated to 0.11.0 as an attempt to fix it.
- During `backup` there are no error messages but with `forget` and `check` there are.
- the clients are servers, I tried running `backup` and `forget` manually and there was surely no interruption.
- I don't have scripts to `unlock` but I ran `unlock` manually.
- I have a script that does `backup`, `forget`, `check` - so after each backup there's a `check` as well.
- yes, the repository is used by multiple machines.


```
restic check --read-data .....
repository 417baf0b opened successfully, password is correct
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree afaa0023:
  tree afaa0023: file "*****" blob 0 size could not be found
  tree afaa0023: file "*****" blob 0 size could not be found
  tree afaa0023: file "*****" blob 0 size could not be found
  tree afaa0023: file "*****" blob 0 size could not be found
  tree afaa0023: file "*****" blob 0 size could not be found
  tree afaa0023: file "*****" blob 0 size could not be found
  tree afaa0023, blob 963eb571: not found in index
  tree afaa0023, blob 0f4dc594: not found in index
  tree afaa0023, blob 02f1c0c4: not found in index
  tree afaa0023, blob 2819f7ae: not found in index
  tree afaa0023, blob 25895d37: not found in index
  tree afaa0023, blob af655ab0: not found in index
error for tree de6cc784:
  tree de6cc784: file "*****" blob 0 size could not be found
  tree de6cc784, blob a6697040: not found in index
read all data
[1:15] 100.00%  207 / 207 packs
Fatal: repository contains errors
```

**Comment by MichaelEischer** [comment]
> The problem started to occur recently but it was already there with restic 0.10.0. I updated to 0.11.0 as an attempt to fix it.

Any idea when and using which restic version that happened? The reported error indicates damage to the repository, so upgrading restic can't help that much. Do you have logs of the first failing check run and the backup and forget before that?

> I don't have scripts to `unlock` but I ran `unlock` manually.

Do you know whether a `prune` run was active at that time? There was a problem with lock refreshes in restic 0.9.6 or older. However, that was only a problem for backup / prune runs taking longer than half an hour, which shouldn't be the case for your backup repository? Could it be the case that multiple machines try to run `forget --prune` at exactly the same time?

The standard repair procedure is to first run `rebuild-index` to ensure that restic knows which blobs still exist. It might be useful to run all `backup` tasks again now (using restic >= 0.10.0). That will automatically recover missing parts of files which still exist on disk. (I'm not sure whether it will help in your case). Then run `check --read-data` again to get a list of problems. Use these reported missing blobs to `find --blob 963eb571 0f4dc594 ...` the containing snapshots. Please take a look at the affected snapshots: were these created around the time when `check` failed initially? All created by a specific machine? Afterwards you can either `forget` these snapshots or try the experimental PR #2876 to salvage the still intact parts of these snapshots.

**Comment by FrankBBx** [comment]
Thank you for the advises, I managed to fix them first but the problem keeps coming back.

> Could it be the case that multiple machines try to run forget --prune at exactly the same time?

Yes, it is possible. Do you think it could be the source of my issues?

**Comment by MichaelEischer** [comment]
> Yes, it is possible. Do you think it could be the source of my issues?

It could be a possibility. At any given time there must be at most one active `prune` run. If multiple `forget --prune` runs start at the same time only one should execute the "prune" step and the others should fail and report a locked repository. If multiple prune runs are active at the same time then that could cause (in combination with a backup run in parallel) the missing blobs.

Do you have logs where you can check whether that could be the case? Or did the `backup` or `prune` runs since fixing the repository report any errors? Are all machines using restic 0.11.0?

**Comment by FrankBBx** [comment]
@MichaelEischer Thanks a lot for your help. The problem was on the server side (timeout).

**Comment by MichaelEischer** [comment]
@FrankBBx Could you explain a bit more? Which timeout was the problem? I'd love to understand what exactly was the problem here.
