### ISSUE TITLE
Configurable crypto

### ISSUE THREAD

**Issue by Skrupellos** [restic/restic#321]
Currently, the whole crypto setup is bound to the number "1", the current repo version number. But crypto algorithms can be broken and are a mater of trust (AES vs. GOST).

For the first scenario, the community should not have to wait until a new version with a new cypher suit has been released. The admin should be able to change the used cypher suit by its one on an already existing repo.

A solution for the first problem is also a solution for the second one. The admin should be able to select the used cypher suit with `init`.

This would require each blob to contain a header with meta data about the used cipher suit.

**Comment by fw42** [comment]
:-1: to making this configurable, imho. We should (and do) just have sane defaults... In the very unlikely event that the ciphers used by restic get broken, I think we can wait for a new release that addresses that problem. Adding complexity to the code for supporting multiple ones in advance seems not worth it to me.

**Comment by cfcs** [comment]
:+1: to what @fw42 said. Configurable crypto comes with a host of additional challenges and little to be gained. If you have actual concerns about the crypto used, let's discuss that instead.

Reading for your inspiration: https://news.ycombinator.com/item?id=10345965

**Comment by fd0** [comment]
Hey, thanks for your suggestion. However, I agree with @fw42 and @cfcs: The code complexity on making the cipher (and mac, obviously) configurable is not worth the risk. This has been shown numerous times in the past in TLS, but also applies to other software e.g. JWT (cf. https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/).

Another problem with this approach is that most people are unable to decide what encryption should be used. So for now there won't be options to configure the crypto used, I think AES and Poyl1305 are good choices.

Do you have any actual concerns regarding the crypto implemented in restic?

**Comment by fd0** [comment]
I will close this issue for now, as I'm not planning to make the crypto algorithms configurable. If you have any concerns regarding to the currently implemented algorithms or how they are used, please open a new issue.
