### ISSUE TITLE
check should display affected snapshots

### ISSUE THREAD

**Issue by aawsome** [restic/restic#3212]
Output of `restic version`
--------------------------

restic 0.11.0 (v0.11.0-248-g031709e6-dirty) compiled with go1.14.7 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

If check shows some errors, display which snapshots are affected by these errors.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Make troubleshooting easier for users. ATM users get list of defect pack files or missing/corrupt blobs and it is pretty complicated to find out which snapshots are actually affected. It would help a lot to get the list of affected snapshots directly from `check`

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Sure :smile:

**Comment by aawsome** [comment]
Is a duplicate of #720 (sorry, didn't find that earlier) but still relevant for version 0.11.0...

**Comment by aawsome** [comment]
I can propose to work on this, but I want to wait for #3106 to be merged...

**Comment by MichaelEischer** [comment]
@aawsome Then let's track this feature in it's original issue ;-) . I agree that it would be better to wait until #3106 is merged.
