### ISSUE TITLE
Data blobs seem to be missing, prune aborted

### ISSUE THREAD

**Issue by JPPhoto** [restic/restic#3213]
Output of `restic version`
--------------------------
`restic 0.11.0 compiled with go1.15.3 on windows/amd64`

How did you run restic exactly?
-------------------------------
`.\restic.exe forget --cache-dir ... -r rest:http://... --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75`
`.\restic.exe prune --cache-dir ... -r rest:http://...`
`.\restic.exe check --cache-dir ... -r rest:http://... --read-data`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
REST backend on a Linux system, formerly sftp to the same system; I have checked the Linux filesystem and RAID array and there are no physical or filesystem errors that would cause this problem.

Expected behavior
-----------------
No errors or issues

Actual behavior
---------------
Running prune reports:
```
find data that is still in use for 192 snapshots
[43:00:26] 100.00%  192 / 192 snapshots
Fatal: [<data/646827e1> <data/da50cbe1> <data/7aa023ab> <data/4016966d> <data/a8b17e2e> <data/ae39f37d> <data/1c7f8046> <data/1aff2452> <data/aeccbf74> <data/36bb177f>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
```
Running check confirms that blobs have gone missing.

Steps to reproduce the behavior
-------------------------------
N/A; I have a 12TiB repo that I use for active backups and I haven't played around with it.

Do you have any idea what may have caused this?
-----------------------------------------------
The repo seemed to be in fine condition prior to forgetting snapshots, and I'd run prune recently on it without error. This points to a combination of forget + prune as the source, but I can't verify or test that.

Do you have an idea how to solve the issue?
-------------------------------------------
I have rebuilt the index and I am still getting missing blobs when I run check (this time from Linux). I'd love to get things back to a stable state and I still have access to the original files that make up those blobs.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I generally love restic, but I'm not so thrilled at the prospect of data loss.

**Comment by MichaelEischer** [comment]
The repository damage must have happened some time earlier, before the failing `prune` run (at least the one from the log snippet). The log snippet shows that `prune` already failed during the initial integrity check during which no changes are made to the repository. An earlier `prune` run might have caused damage though.

Did you run `check` from time to time? Which errors does `check --read-data` report? Only missing trees/blobs during the `check snapshots, trees and blobs` phase or also damaged pack files during `read all data`?

As you've already run `rebuild-index` the missing data blobs won't affect future snapshots. If the missing data blobs still exist then the next `backup` run will fix the repository. Could you run `restic find --blob 646827e1 da50cbe1 ...` with the data IDs reported by prune? That could provide some insights into what might have gone wrong.

**Comment by JPPhoto** [comment]
I periodically run `check` and `prune` - especially when there's a backup that fails due to connectivity issues. This is the first time I've run `forget` in ages, as I wanted to free up some space on the server the repo lives on. **Is it possible that the damage happened as a result of the `forget` operation?**

I'm currently running `check --read-data` with the newly-rebuilt index, and here's partial sanitized output (it takes a while with a repo this large):

```
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree 12c9517d:
  tree 12c9517d: file "a" blob 3119 size could not be found
  tree 12c9517d: file "a" blob 3120 size could not be found
  tree 12c9517d: file "a" blob 3121 size could not be found
  tree 12c9517d: file "a" blob 3122 size could not be found
  tree 12c9517d: file "a" blob 3123 size could not be found
  tree 12c9517d: file "a" blob 3124 size could not be found
  tree 12c9517d: file "a" blob 3125 size could not be found
  tree 12c9517d: file "b" blob 91 size could not be found
  tree 12c9517d: file "b" blob 92 size could not be found
  tree 12c9517d: file "b" blob 93 size could not be found
  tree 12c9517d, blob 1c7f8046: not found in index
  tree 12c9517d, blob a8b17e2e: not found in index
  tree 12c9517d, blob 646827e1: not found in index
  tree 12c9517d, blob 4016966d: not found in index
  tree 12c9517d, blob da50cbe1: not found in index
  tree 12c9517d, blob ae39f37d: not found in index
  tree 12c9517d, blob 1aff2452: not found in index
  tree 12c9517d, blob aeccbf74: not found in index
  tree 12c9517d, blob 36bb177f: not found in index
  tree 12c9517d, blob 7aa023ab: not found in index
error for tree 1078b349:
  tree 1078b349: file "a" blob 3119 size could not be found
  tree 1078b349: file "a" blob 3120 size could not be found
  tree 1078b349: file "a" blob 3121 size could not be found
  tree 1078b349: file "a" blob 3122 size could not be found
  tree 1078b349: file "a" blob 3123 size could not be found
  tree 1078b349: file "a" blob 3124 size could not be found
  tree 1078b349: file "a" blob 3125 size could not be found
  tree 1078b349: file "b" blob 91 size could not be found
  tree 1078b349: file "b" blob 92 size could not be found
  tree 1078b349: file "b" blob 93 size could not be found
  tree 1078b349, blob 1c7f8046: not found in index
  tree 1078b349, blob a8b17e2e: not found in index
  tree 1078b349, blob 646827e1: not found in index
  tree 1078b349, blob 4016966d: not found in index
  ...
```

When this finishes, I'll try to `find` some of those blobs and trees and put things here. And then, I plan to run backup to get those blobs back in the repo, if that's what you think will work.

**Comment by MichaelEischer** [comment]
> **Is it possible that the damage happened as a result of the `forget` operation?**

`forget` only deletes snapshot files and leaves the cleanup to `prune`. So the answer here is no.

The `check` output looks like one or at most two pack file went missing. And it looks like the file / folder is contained in multiple snapshots. Do you still have the log output of the last successful prune run? Do you run `check` and then `prune` or the other way around? Is one of the snapshots containing the missing blobs older than the last successful prune run?

If the files with the missing blobs still exist in their original state, then restic (>= 0.10.0) will automatically backup the missing parts again. This works as long as the index correctly reflects which blobs exist and which don't, which is why the initial `rebuild-index` is  important.

**Comment by JPPhoto** [comment]
I'm sorry, I generally don't keep log outputs unless there are issues. Thus, I don't have anything from prior runs as they all succeeded without error.

When I ran `forget` this time, I immediately did a `prune` operation (both with Windows 10 20H2 running restic 0.11) and restic reported the errors displayed in the issue. I had verified the repo's integrity a while ago and pruned it and no external operations have touched those files since.

Since this is the case, it sounds like something internal in restic has corrupted or erased those blobs - I'm spitballing here, but perhaps there was some confusion within prune as those blobs existed in both snapshots I kept as well as ones I removed?

I'm still waiting for `check` to complete and I'll report back with more sanitized logs and results from `find` prior to running `backup` again.

**Comment by MichaelEischer** [comment]
`prune` does not have the concept of removed snapshots, it only looks at what is still required. It roughly works as follows: it first checks which blobs are used by the snapshots, then verifies that these blobs still exist in the repository. Afterwards partially used pack files are repacked and completely unused ones are deleted. These latter steps only care about whether blobs are used or not. The information by how many snapshots (or whether one of those was deleted) a blob is used, is not available at that point. So prune never learns that a snapshot was deleted, it just finds lots of blobs which are no longer in use and cleans those up.

Btw, the check/prune errors up to now look like 1 or 2 pack files are simply missing. At least the log snippets don't show any signs of data corruption.
Do you call `unlock` manually / automatically from time to time? 

So the timeline was as follows? `check`, `prune` --some-time-passes-without-any-repository-changes-> `forget`, `prune` -> error ? Were those earlier check and prune runs also done using restic 0.11.0?

**Comment by JPPhoto** [comment]
The only time I call `unlock` manually is if my connection to the repo gets interrupted and restic terminates. I figure that restic's locking semantics are established and I shouldn't mess with them unless I absolutely have to.

Your assessment of the timeline is mostly accurate. I called `backup` several times instead of letting time pass without changes, as I actively use it as a backup program. Earlier `prune`, `check`, and `backup` operations were with all manner of versions (I started using restic with 0.7.3 under Linux, but I try to keep up-to-date), but most recently 0.11.0. Since the files that are corrupted are both after 2020/11/26, I believe I was using 0.10.0 or 0.11.0 at the time.

**Comment by JPPhoto** [comment]
Here's a lazily sanitized snippet of the output for `find --blob`:

```
Found blob 1c7f80461a2e09c82a6f7b98c1267ea818ac69072abe8b4b14f45848b6396f34
 ... in file /mnt/Z/backups/site1/20201201/tree/www/site1/wp-content/uploads/backups/backup-www_site1_com-2020_11_26-full-tzc24w8dxg.zip
     (tree 5e65fcda2da22b11e965782d9cb0c541b66ee9fbe0023eeb37811d52a1e87de0)
 ... in snapshot 0aaf0e0a (2020-12-24 09:10:33)
Found blob aeccbf740bdf2e761d85b796ba9e45856ebfeacfe9676680a79093e4847a4e63
 ... in file /mnt/Z/backups/site1/20201201/tree/www/site1/wp-content/uploads/backups/backup-www_site1_com-2020_12_01-db-wn0rky2bvx.zip
     (tree 5e65fcda2da22b11e965782d9cb0c541b66ee9fbe0023eeb37811d52a1e87de0)
 ... in snapshot 0aaf0e0a (2020-12-24 09:10:33)
Found blob 1c7f80461a2e09c82a6f7b98c1267ea818ac69072abe8b4b14f45848b6396f34
 ... in file /mnt/Z/backups/site1/20201217/tree/mnt/site1-zips/backup-www_site1_com-2020_11_26-full-tzc24w8dxg.zip
     (tree b058b25e51e12e0375932eb2f4307d9dbb42d41595a849d91cd050cf07137a6e)
 ... in snapshot 0aaf0e0a (2020-12-24 09:10:33)
Found blob aeccbf740bdf2e761d85b796ba9e45856ebfeacfe9676680a79093e4847a4e63
 ... in file /mnt/Z/backups/site1/20201217/tree/mnt/site1-zips/backup-www_site1_com-2020_12_01-db-wn0rky2bvx.zip
     (tree b058b25e51e12e0375932eb2f4307d9dbb42d41595a849d91cd050cf07137a6e)
 ... in snapshot 0aaf0e0a (2020-12-24 09:10:33)
Found blob 1c7f80461a2e09c82a6f7b98c1267ea818ac69072abe8b4b14f45848b6396f34
 ... in file /mnt/Z/backups/site1/20201218/tree/mnt/site1-zips/backup-www_site1_com-2020_11_26-full-tzc24w8dxg.zip
     (tree ccc66649febd2d650a56e1f45ceaadd9137fe4e78bbfe1d39894fa0a50211830)
 ... in snapshot 0aaf0e0a (2020-12-24 09:10:33)
Found blob aeccbf740bdf2e761d85b796ba9e45856ebfeacfe9676680a79093e4847a4e63
 ... in file /mnt/Z/backups/site1/20201218/tree/mnt/site1-zips/backup-www_site1_com-2020_12_01-db-wn0rky2bvx.zip
     (tree ccc66649febd2d650a56e1f45ceaadd9137fe4e78bbfe1d39894fa0a50211830)
 ... in snapshot 0aaf0e0a (2020-12-24 09:10:33)
Found blob 1c7f80461a2e09c82a6f7b98c1267ea818ac69072abe8b4b14f45848b6396f34
 ... in file /mnt/Z/backups/site1/20201219/tree/mnt/site1-zips/backup-www_site1_com-2020_11_26-full-tzc24w8dxg.zip
     (tree e1a8bb13542c4aca4b4ecc81e7b37ca9e6a70727b350580abd5de1ddf1e507c6)
 ... in snapshot 0aaf0e0a (2020-12-24 09:10:33)
Found blob aeccbf740bdf2e761d85b796ba9e45856ebfeacfe9676680a79093e4847a4e63
 ... in file /mnt/Z/backups/site1/20201219/tree/mnt/site1-zips/backup-www_site1_com-2020_12_01-db-wn0rky2bvx.zip
...
```

I'm going to go ahead and run `backup` to hopefully get these blobs back into the backup.

**Comment by MichaelEischer** [comment]
Were there multiple snapshots reported by `find --blob`? Do you know whether you ran `prune` after the oldest of these snapshots was created? Or whether you ran prune after 2020_12_01?

`backup` should report two `parts of %v not found in the repository index; storing the file again` errors.

There's also the `check --read-data-subset x/y` option which can be useful to check parts of the repository data from time to time.

**Comment by JPPhoto** [comment]
I didn't let `find` complete because I need to resume backups. That said, I know those files are in multiple snapshots.

As for timing, I probably didn't `prune` after 2020/12/01 because it's so time-intensive.

I'm running `backup` now and I'll let you know whether or not I get those errors.

**Comment by JPPhoto** [comment]
This looks identical to #3201 in that we both did `forget` followed immediately by `prune` (disjointed in my case and as `forget --prune` in the other).

(If it matters, I have multiple machines running different operating systems backing up to the same repo - sometimes simultaneously.)

**Comment by JPPhoto** [comment]
@MichaelEischer I did indeed get two messages during `backup` that matched the errors that you indicated. The `backup` run is still going, but the missing blobs don't appear to be in the repo - what now? Do I rebuild the index or run `check` again after this `backup` is complete?

**Comment by MichaelEischer** [comment]
> but the missing blobs don't appear to be in the repo - what now?

How did you come to that conclusion? It can take at least a dozen minutes or longer (to be precise: until the backup has finished) before any of the other restic commands can see the recovered blobs.

The index should only be rebuilt when files in the repository went missing or were damaged. Neither is the case now, so don't rebuild the index. I'd recommend to run a plain `check` run. Unless `check` did report additional errors after printing `read all data`. In which case `check --read-data` is necessary.

**Comment by JPPhoto** [comment]
> How did you come to that conclusion? It can take at least a dozen minutes or longer (to be precise: until the backup has finished) before any of the other restic commands can see the recovered blobs.

I logged into the machine that houses the repo and looked under `data/1c` for the file `1c7f80461a2e09c82a6f7b98c1267ea818ac69072abe8b4b14f45848b6396f34` after restic completed its backup. That file isn't there. I thought this was where blobs were stored directly.

In any event, I am running `check` at the moment and I'll report back with my findings.

**Comment by MichaelEischer** [comment]
> I logged into the machine that houses the repo and looked under `data/1c` for the file `1c7f80461a2e09c82a6f7b98c1267ea818ac69072abe8b4b14f45848b6396f34` after restic completed its backup. That file isn't there. I thought this was where blobs were stored directly.

The files in `data/` are so called pack files: each of them contains multiple encrypted blobs. Especially for small files that packing is really important for performance. Based on the blob ID alone there's no way to determine in which pack file it is stored (except for reading each one). restic avoids that problem by using an index from blob ID to its storage location. Even if a pack file only contains a single blob, it will have a different filename.

**Comment by JPPhoto** [comment]
The `check` operation completed without error. What can I do to assist at this point? Is it safe to try another `prune`?

**Comment by MichaelEischer** [comment]
> The `check` operation completed without error. What can I do to assist at this point? Is it safe to try another `prune`?

That sounds like the repository is now repaired :-) . `prune` should now work without errors.

**Comment by JPPhoto** [comment]
> That sounds like the repository is now repaired :-) . `prune` should now work without errors.

I'm running `prune` now and I have the REST server's container writing to an overlay filesystem so I can see if it changes/breaks anything without causing potential issues with the repo. I wish I knew what had caused this corruption in the first place.

**Comment by JPPhoto** [comment]
```
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```
It looks like things are back to normal after `prune`. Thanks for the help. Wish we knew why this happened in the first place.

**Comment by MichaelEischer** [comment]
Closing this issue as the repository has been repaired and there are no traces left to investigate. In addition, the prune implementation has been rewritten in restic 0.12.0.
