### ISSUE TITLE
Init with empty password causes 1) directory structure without config file and 2) strack trace

### ISSUE THREAD

**Issue by martinleben** [restic/restic#3214]
Output of `restic version`
--------------------------
    restic 0.11.0 compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------
    $ restic init --repo .
    enter password for new repository:
    enter password again:
    an empty password is not a password
    main.ReadPassword
            /restic/cmd/restic/global.go:360
    main.ReadPasswordTwice
            /restic/cmd/restic/global.go:374
    main.runInit
            /restic/cmd/restic/cmd_init.go:65
    main.glob..func12
            /restic/cmd/restic/cmd_init.go:25
    github.com/spf13/cobra.(*Command).execute
            /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
    github.com/spf13/cobra.(*Command).ExecuteC
            /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
    github.com/spf13/cobra.(*Command).Execute
            /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
    main.main
            /restic/cmd/restic/main.go:98
    runtime.main
            /usr/local/go/src/runtime/proc.go:204
    runtime.goexit
            /usr/local/go/src/runtime/asm_amd64.s:1374

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local disk.

Expected behavior
-----------------
Since empty password is not allowed:
1) An error message.
2) No changes in the file system.

Actual behavior
---------------
a) Error message "an empty password is not a password" (This was in line with the expectations.)
b) A strack trace. (This was NOT expected.)
c) A lot of directories was created. (This was NOT expected.)
    $ tree
    .
    ├── data
    │   ├── 00
    │   ├── 01
    │   ├── 02
    │   ├── 03
    │   ├── 04
    │   ├── 05
    │   ├── 06
    │   ├── 07
    ...
    │   ├── fc
    │   ├── fd
    │   ├── fe
    │   └── ff
    ├── index
    ├── keys
    ├── locks
    └── snapshots

Steps to reproduce the behavior
-------------------------------

    $ mkdir tmp
    $ restic init --repo tmp
    (press enter twice at the password prompts without entering any password.)

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------
Adjust the handling when an empty password is detected...?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
Thanks for finding this issue. Fixing this should be quite simple: Currently the repository is created before asking the user for a password, swapping these two steps should be enough. And the stacktrace can be fixed by using `errors.Fatal` when reporting that `an empty password is not a password`.

Anyone up for a PR?

**Comment by martinleben** [comment]
Thank you for the hints, @MichaelEischer . I have never built restic myself, so give me some time and will make an attempt myself. :-)

**Comment by aawsome** [comment]
@martinleben Thanks for working on this! If you have any questions or are stuck at some point, please don't hesitate to ask!

**Comment by rawtaz** [comment]
Can't find a better first issue to attack than this one :)

**Comment by MichaelEischer** [comment]
Fixed by #3283.
