### ISSUE TITLE
restic should refuse to read from password/repository files which are readable by other users 

### ISSUE THREAD

**Issue by t-b** [restic/restic#3215]
Version:
```
restic 0.11.0 compiled with go1.15.3 on linux/amd64
```

OS: Debian 10 (buster) x64

The restic repository is of sftp type on a remote debian box.

```
# test holds the repository password
export RESTIC_PASSWORD_FILE=./test
export RESTIC_REPOSITORY=sftp:restic-backup:upload
chmod 0777 test 
restic stats --verbose
repository 792a3d78 opened successfully, password is correct
scanning...
Stats in restore-size mode:
Snapshots processed:   2
   Total File Count:   339341
         Total Size:   25.998 GiB
```

I would expect that restic refuses to read from a password/repository file which is readable by other users than the current one. Openssh does that already if it finds that your private key file is unprotected.

**Comment by rawtaz** [comment]
This is not a decision restic should make on behalf of the user, there may be use cases for people to have a password file that's readable by others. IMO it's also outside restic's scope.

**Comment by t-b** [comment]
Thanks for clarifying.
