### ISSUE TITLE
Prevent Windows going to sleep while restic operations in progress

### ISSUE THREAD

**Issue by JsBergbau** [restic/restic#3216]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I'd like that restic informs Windows not to go into sleepstates when restic is performing operations.

The way is documented here https://docs.microsoft.com/de-de/windows/win32/api/winbase/nf-winbase-setthreadexecutionstate?redirectedfrom=MSDN
I think "ES_SYSTEM_REQUIRED" is the right value.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

To save power my PC goes into sleep state after an hour of inactivity. However opertions like restic prune could last a lot longer.

Currently `powercfg /requests` does not show any request when restic is running.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, restic made me very happy today. Upgraded from 0.9.6 to 0.11.0 and noticed that backup is much faster now.

**Comment by DRON-666** [comment]
You can switch power schemes to 'Always on' and back by adding [`powercfg -setactive`](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/powercfg-command-line-options#setactive-or-s) to you scripts before and after `restic ...` command.
Or use some surrogates like [Caffeine](https://www.zhornsoftware.co.uk/caffeine/).

**Comment by JsBergbau** [comment]
Thanks for the hint. These tools could be an option. Still I'd prefer integrating the API call directly into restic.

**Comment by kmwoley** [comment]
If this were to be added, please do not make it on by default. It would result in an unexpected behavior for most people. For me, I *want* Windows to go to sleep during restic operations. Sleeping / saving power is more important to me than restic finishing a background operation.

I personally think this not be a feature of restic, but instead should be left to the person to implement something in a script to prevent Windows from sleeping.

FYI - Windows going to sleep during a backup (or other operation) doesn't cause any data loss, corruption or other errors in my experience.

**Comment by MichaelEischer** [comment]
Closing, see https://github.com/restic/restic/pull/3218#issuecomment-1220958504
