### ISSUE TITLE
Stale lock for several days

### ISSUE THREAD

**Issue by MarcAndreG** [restic/restic#3219]
Output of `restic version`
--------------------------
restic 0.10.0 compiled with go1.15.2 on linux/amd64

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
It's installed on our own servers with the rest server.

Expected behavior
-----------------
Not have stale lock for days

Actual behavior
---------------
We use restic on multiple servers. 1 repo per server.

It often happens that on a server it is impossible for us to list the snapshots because of repository locked.

Example of return on action:

```
repository 4c0fb312 opened successfully, password is correct
unable to create lock in backend: repository is already locked exclusively by PID 802602 on XX.HOSTANME.COM by root (UID 0, GID 0)
lock was created at 2020-12-04 13:53:29 (787h16m0.978965683s ago)
storage ID a590d73e
the `unlock` command can be used to remove stale locks
```

It is not possible to leave a repo several days or even months without backup.

After several tests, it seems that the locks causing the problem are those coming from the "prune" or from the "check" because it is possible to proceed
to other actions during locks created by other actions.

It is very problematic. Do you have a solution for this type of problem?

The best would be, that after a number X of hours we can ignore or a least purge the old stale lock before relaunching a new command or even that the system does it by itself.

Steps to reproduce the behavior
-------------------------------
Wait until one of our repo is completely lock for days.

Do you have any idea what may have caused this?
-----------------------------------------------
After several tests, it seems that the locks causing the problem are those coming from the "prune" or from the "check" because it is possible to proceed to other actions during locks created by other actions.

**Comment by MichaelEischer** [comment]
Something doesn't look right here. As you've written "server" I'd assume those to have a mostly uninterrupted power/network connection along restic with not being killed in the middle of a `prune` or `check` run. In that case check/prune shouldn't leave any locks behind. It is currently **NOT** possible to remove exclusive locks during check or prune as that would quite likely lead to false error reports in check or a damaged backup repository in prune (there are discussions in #1141 how that could be avoided). However, these commands refresh their locks while they run such that you shouldn't end up with stale locks. So the main question to answer here is: are my assumptions correct? And if yes, why are these locks left behind (prune/check should report errors or the kernel OOM killer)?

If you just want a list of existing snapshots then `restic snapshots --no-lock` would work. However, that won't help with the backup command.

**Comment by MichaelEischer** [comment]
@MarcAndreG Is there anything here not answered by my reply? Only failing / crashing prune runs should leave locks behind, see also my previous questions.

**Comment by MichaelEischer** [comment]
Closing this as there's been no response. Feel free to comment if there are still open questions here.
