### ISSUE TITLE
Limit number of retries especially for forget on append-only servers

### ISSUE THREAD

**Issue by joram-berger** [restic/restic#3223]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.12.12 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

A restic command like `backup` or `forget` should have an option like `--max-retries` or `--max-retry-count` after which it will stop retrying the activity.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

When using restic with a restic rest-server backend, the server can be configured to be "append-only", i.e. backup is allowed but forget is not. If I then try `restic forget`, I get:

```
repository … opened successfully, password is correct
Remove(<snapshot/703fc2e649>) returned error, retrying after 409.996243ms: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/703fc2e649>) returned error, retrying after 907.654304ms: blob not removed, server response: 403 Forbidden (403)
…
```
With the proposed option, the command would fail after n retries and not try any longer.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is awesome! I really is backups done right: encrypted, deduplicated, extremely fast, so many backends, open source, wow. The speed and small size really impresses me. I had to double check if a new snapshot really contained all the large files, I changed.

**Comment by dimejo** [comment]
I think this should be resolved with PR #2515.

**Comment by joram-berger** [comment]
Yes, PR #2515 definitely sounds like it covers what I had in mind. So you can close this issue as a duplicate (or whatever is appropriate).

**Comment by aawsome** [comment]
> Yes, PR #2515 definitely sounds like it covers what I had in mind. So you can close this issue as a duplicate (or whatever is appropriate).

In some sense I don't understand what you want to achieve. If you know your repo is read-only you should not add a `--retries=<small number>` to you `forget` command, but instead simply not run `forget`at all because it will definitively fail and not remove any snapshot. Maybe your request is related to #3195?

But I agree that there are situations in which you want to adjust the number of retries and this is what #2515 is supposed to do. I added this issue to be closed by that PR.

**Comment by joram-berger** [comment]
You are right. I should not run `forget` at all – it occurred to me later, too. But as you said, `--retries` is useful in other situations.

**Comment by MichaelEischer** [comment]
> A restic command like `backup` or `forget` should have an option like `--max-retries` or `--max-retry-count` after which it will stop retrying the activity.

restic already has a limit of 10 retries per operation. If you wait for a minute or two then the delete operation will fail. And for the `forget` command the first failure is fatal. #2515 merely adds an options that allows customizing the *maximum number* of retries.

**Comment by MichaelEischer** [comment]
Permission errors are no longer retried since https://github.com/restic/restic/pull/4803 .
