### ISSUE TITLE
Chunk size can be configurable?

### ISSUE THREAD

**Issue by nevermore-muyi** [restic/restic#3224]
Output of `restic version`
--------------------------
restic 0.11.0

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Can restic give an access to change the chunk and pack size ?
Currently, the chunk size mostly is in an average about 1MB, and pack size is larger then 4MB, this is general in some scenarios, but if the file is larger than 1T or larger, the size may be not reasonable.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Give an access to change the chunk size or pack size, the other config about CDC can be automatic changed depends on user's config.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes, restic helps me very much.

**Comment by rawtaz** [comment]
At this point in time the chunk size is not configurable. There's already an issue tracking this feature suggestion, please see #1071. I'm closing this one as a duplicate :)
