### ISSUE TITLE
windows restic init(possibly more?) broken

### ISSUE THREAD

**Issue by Nemerensis** [restic/restic#3226]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on windows/amd64

How did you run restic exactly?
-------------------------------
OS: Windows 10
1: (powershell, does not work)
```
$env:RESTIC_REPOSITORY="rest:http://172.17.70.201:8000/"
$env:RESTIC_PASSWORD="testing"
.\restic_0.11.0_windows_amd64.exe init

```
2: (powershell, does not work)
`.\restic_0.11.0_windows_amd64.exe init --repo "rest:http://172.17.70.201:8000/"`

3: (cmd, does not work)
`.\restic_0.11.0_windows_amd64.exe init -r "rest:http://172.17.70.201:8000/"`

4: (cmd, does not work)
`.\restic_0.11.0_windows_amd64.exe init --repo "rest:http://172.17.70.201:8000/"`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rest-server docker image hosted on a fresh default install of ubuntu linux 18.04* with authentication and tls disabled for testing in order to minimize possible trouble sources.
*no special settings, firewall is off with recommended basic docker install instructions 

`docker run -d -p 8000:8000 -v /data:/data -e OPTIONS="--no-auth" --name rest_server restic/rest-server`
(data volume at /data, I know that it is accessible to the image at least because I was able to create http auth users after running this test)
docker logs:
```
Data directory: /data
Authentication disabled
Private repositories disabled
Starting server on :8000
```

Expected behavior
-----------------
proper parsing/usage of repo flag on windows as well as reading environment variables in order to init the repo remotely.

Actual behavior
---------------
quick failure to stdout:
```
restic_0.11.0_windows_amd64.exe : Fatal: create repository at rest:http://172.17.70.201:8000/ failed: Post "http://172.17.70.201:8000/?create=true": dial tcp 172.17.70.201:8000: socket: An invalid argument was 
supplied.
At line:1 char:1
+ . .\restic_0.11.0_windows_amd64.exe init
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Fatal: create r...t was supplied.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Steps to reproduce the behavior
-------------------------------
1: 
set the restic repository and password environment variables
run restic init 
2:
run restic init with the "--repo" flag followed by the repository url

Do you have any idea what may have caused this?
-----------------------------------------------
improper parameter parsing perhaps? maybe a bug in a library?

Do you have an idea how to solve the issue?
-------------------------------------------
Unfortunately I do not, I have little experience in the Go language and the error is ambiguous.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Unfortunately I cannot use restic on windows at the moment, but I am excited to see the VSS feature added in! (In my opinion that's a very valuable piece of code for backups on windows)

**Comment by fd0** [comment]
Hey, thanks for the report! I don't have any idea what's going on, but it feels to me that argument parsing is not the core issue.

My ideas for the next steps would be:
 *  Does it work with a different backend than `rest`? Can you try creating a local repository in a directory or use a different backend than `rest`?
 * Can you please confirm that restic is not restricted by the Windows firewall? I've found the error message you're seeing (`An invalid argument was supplied`) in that context

**Comment by MichaelEischer** [comment]
Docker by default assigns IP from the `172.16.0.0/12` IP address range to its containers. So `172.17.70.201` looks like a container-internal IP which is not accessible from outside the docker host server. Please check whether this is really the external IP of the server. 

`--repo "rest:http://172.17.70.201/"` cannot work as it's missing a port and the default for HTTP is 80.

**Comment by Nemerensis** [comment]
Hey Michael, nice thought with the docker IP range, I examined it and the current range for docker0 on this fresh install for me was 172.18.0.0/16 (ending at 172.18.255.255) and I double checked to ensure there were no weird entries in the ip route table in its default state.

My test network for virtual machines does indeed use the 172.17.70.0/24 range externally.  This does not seem to be a network problem w.r.t. my setup as far as I can tell.

I double checked your comment about the port, that was a typo, my bad.  The copy of the output to stdout properly reflects the URL I entered.  I have updated the first two commands appropriately above.

-------

fd0, 
I can confirm that creation of a local repository works on windows.
My firewall does appear to be off on this network's profile.  I have also tried by adding an application exception to allow it through the windows firewall anywhere, init still fails with the same error however.  I will spin up a temporary windows machine tonight to verify with a fully disabled firewall.

I also installed and executed the linux client on my laptop and was able to init the repo with:
```
./restic_0.11.0_linux_amd64 init --repo rest:http://172.17.70.201:8000
enter password for new repository: 
enter password again: 
created restic repository 3242876ca8 at rest:http://172.17.70.201:8000/
```
verified creation on the rest-server vm:
```
administrator@test-backup:~$ ls /data
config  data  index  keys  locks  snapshots
```
---------

I'm wondering if this is somehow related to golang's net dial code? I've seen a couple of issues when searching the golang repo, but I'll wrap up my windows vm test later tonight before I'd recommend jumping down that rabbit hole.

**Comment by Nemerensis** [comment]
I may have figured this out, I do not believe windows firewall is the problem (or if it is, then when it is off, that would imply it isn't truly "off")
![image](https://user-images.githubusercontent.com/38839287/104806899-7557bc00-57a0-11eb-8c1c-537b979f6825.png)
The issue seems to occur no matter whether the firewall is on or off, rather I was calling the executable while it was present on a network share... and it was functioning in all cases except for when it tried to connect remotely it would seem.

Once the exe was on my desktop, it executed perfectly and could connect to the rest backend.

Unless you think this is an appropriate problem to handle in restic I think then that this problem is solved, feel free to close the issue if you think that is the case.

**Comment by MichaelEischer** [comment]
@Nemerensis The only error I could find which matches your problems is from 2018: https://stackoverflow.com/questions/50155482/after-windows-10-update-1803-my-program-cant-open-a-socket-when-running-from-ne . And that was a bug in Windows itself. Out of curiosity, is the network mount from which you ran restic a SMB1 mount as in the linked stackoverflow question?

I don't think there's anything to do on the restic side as this rather looks like a problem of the underlying OS.

**Comment by Nemerensis** [comment]
The share that the restic executable resided on was a default windows 10 client to server 2016 file server share running SMB 3.1.1 according to the output of:
`Get-SmbConnection`

**Comment by fd0** [comment]
Thanks for the feedback!
