### ISSUE TITLE
Add command to copy all data to another repository

### ISSUE THREAD

**Issue by fd0** [restic/restic#323]
During the discussion in #320 we discovered that functionality may be helpful to copy all data (data blobs, tree blobs, snapshots) from a repository to a new one, recreating pack files and indexes on the fly. This allows creating a new repository in a different location (e.g. moving from a local repository to an sftp-server) and using that from now on without losing any history and old snapshots.

This issues tracks the implementation of this feature and can be closed when it is implemented.

**Comment by Intensity** [comment]
Is this intended to handle a one-time copy from one repository (A) to a new one (B)?  Or is this meant to be more general by performing a "sync" or update of changed content between (A) and (B) since the last sync?

**Comment by fd0** [comment]
At the moment this is inteded to handle a one-time copy only.

**Comment by witeshadow** [comment]
Given a slow internet connection, I would like the possibility to backup to s3 and another location as efficiently as possible.

**Comment by middelink** [comment]
@witeshadow I'm not sure how that can be done efficiently, as the data is encrypted in repo A with master A', and needs to do to repo B with a different masterkey. We need to read all the data to copy, unencrypt, encrypt and write out. There is no way to optimize this for slow bandwidth. Its gonna hurt...

the only optimization I can think is having a selection criteria on the source repo A, by using the host, path and tags filters so you don't have to copy all. However, that depends on your use case.

**Comment by mholt** [comment]
@fd0 I just wanted to add my vote for this feature request. Anything I can do to make it happen?

**Comment by fd0** [comment]
You could implement it... The functionality itself is not hard to do, configuring the two backends is the hard thing. We don't support accessing more than one backend (e.g. there's only one `$B2_ACCOUNT_ID`)... so I think this feature depends on a proper config file (see #16).

**Comment by mholt** [comment]
Great! Thanks for the tips. I have this itch, so I will see if I can make time to scratch it -- but for the short-term I will have to go without this `restic merge` feature. If someone gets to it before I do, that's fine -- or I'll circle back around to this eventually!

**Comment by middelink** [comment]
I think I have the implemented already... /me scratches head and looks for it...
 ... https://github.com/middelink/restic/tree/fix-323
I need to check if it still compiles though, that branch is 228 commits behind ...

**Comment by sergeevabc** [comment]
Err… Any news for mere users without dev skills to compile and try out @middelink’s suggestion?

**Comment by klmitch** [comment]
This is mostly a "me too" comment, but I'd like to have the ability to copy only specific snapshots from one repo to another, rather than a "copy-all" or "sync" semantic; e.g., make daily backups to local storage, then once a week copy only the most recent daily to an s3 bucket, etc.

**Comment by middelink** [comment]
Well, then you are in luck, my copy cmd takes one or more snapshot ids. In fact copy-all is not something it does. You would have to list your snapshot ids first and then concatenate them on the "restic copy" cmdline. As I see this as a degenerate use-case, I'm good with it.

**Comment by Fjodor42** [comment]
Without delving too deep into this, perhaps some discussions with ncw/rclone could be of use...

**Comment by keesse** [comment]
I'm also interested in the merge/copy functionality, I have a repository on an USB-stick I would like to merge/copy to my central repository (same passwords).
Any news on this?

**Comment by theoretical2019** [comment]
Looks like the [fork branch](https://github.com/middelink/restic/tree/fix-323) was updated to `master`, but there's not yet a PR for it.

@middelink Is your code finished / mergeable?  If not, what still needs to be done?  This is a feature I really want :)

**Comment by middelink** [comment]
@theoretical2019 The code itself is finished, but each time I sit down to create an official PR, I keep finding things I need to do before it's ready. Like documentation, like a unreleased/changelog...

**Comment by seqizz** [comment]
@middelink Fyi, I have tested your branch by rebasing to upstream master and it works pretty good. It created a new snapshot with same host, tags and date :+1: 
Waiting for PR :tada: 

Now with such feature, I can create a secondary repository, which is used by the clients only when the first repository is locked for maintenance (e.g. prune). And prune task can trigger a copy from the secondary after it finishes, so no missing backups, hence zero downtime on backup service.

**Comment by rawtaz** [comment]
@middelink Would you be so kind as to create a PR of your code? When doing so, please also [allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) - this way, we can help you with the changelog, documentation and so on.

The important thing is that we get a base PR to work on. I'd love to get your great work moving, and so would others I think :) Let me know if you need any help creating the PR!

**Comment by middelink** [comment]
@rawtaz Sure. Let me sync up and all that stuff. For some reason I have not found the time to do so earlier, but it looks like I have some time now.

**Comment by lfrancke** [comment]
Thank you everyone for your work on this!

I've got one question left that's not answered by the docs (at least for me): Do I need to prune both or is it enough to do it in the source and snapshot deletions are propagated?

**Comment by rawtaz** [comment]
@lfrancke When using the `copy` command you specifically list the snapshots that you want to copy. Others, both existing, non-existing and previously-existing-but-now-pruned-and-no-longer-existing snapshots are not applicable.

If you copy snapshots from repo A to repo B and then forget and prune them in repo A, they will not be forgotten and pruned in repo B automatically, you'll have to do that in repo B yourself.

**Comment by lfrancke** [comment]
Excellent, thank you very much @rawtaz for the quick and helpful response.
