### ISSUE TITLE
prune option '--max-unused' missing

### ISSUE THREAD

**Issue by tonypilz** [restic/restic#3231]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on windows/amd64

How did you run restic exactly?
-------------------------------
**"c:\Program Files\Restic\restic_0.11.0_windows_amd64.exe" prune --help**

```
The "prune" command checks the repository and removes data that is not
referenced and therefore not needed any more.

EXIT STATUS
===========

Exit status is 0 if the command was successful, and non-zero if there was any error.

Usage:
  restic prune [flags]

Flags:
  -h, --help   help for prune

Global Flags:
      --cacert file                file to load root certificates from (default: use system certificates)
      --cache-dir directory        set the cache directory. (default: use system default cache directory)
      --cleanup-cache              auto remove old cache directories
      --json                       set output mode to JSON for commands that support it
      --key-hint key               key ID of key to try decrypting first (default: $RESTIC_KEY_HINT)
      --limit-download int         limits downloads to a maximum rate in KiB/s. (default: unlimited)
      --limit-upload int           limits uploads to a maximum rate in KiB/s. (default: unlimited)
      --no-cache                   do not use a local cache
      --no-lock                    do not lock the repository, this allows some operations on read-only repositories
  -o, --option key=value           set extended option (key=value, can be specified multiple times)
      --password-command command   shell command to obtain the repository password from (default: $RESTIC_PASSWORD_COMMAND)
  -p, --password-file file         file to read the repository password from (default: $RESTIC_PASSWORD_FILE)
  -q, --quiet                      do not output comprehensive progress report
  -r, --repo repository            repository to backup to or restore from (default: $RESTIC_REPOSITORY)
      --repository-file file       file to read the repository location from (default: $RESTIC_REPOSITORY_FILE)
      --tls-client-cert file       path to a file containing PEM encoded TLS client certificate and private key
  -v, --verbose n                  be verbose (specify multiple times or a level using --verbose=n, max level/times is 3)

```

Expected behavior
-----------------

The option `--max-unused` is listed as described [here](https://restic.readthedocs.io/en/latest/060_forget.html#customize-pruning).

Also invoking prune with the option will not fail with the option `unknown flag: --max-unused`.

Actual behavior
---------------

The option is not listed and prune cannot be invoked with  `--max-unused`

Steps to reproduce the behavior
-------------------------------

See above.

Do you have any idea what may have caused this?
-----------------------------------------------

No, the code actually contains the option. Maybe the option is not registered properly?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I am currently trying to setup a small backup solution at home via sftp onto an old arm odroid c1 device. The restic approach looks very promising to me, far better than all the other applications I looked at before. So thank a lot for writing it!

**Comment by rawtaz** [comment]
Thank you for keeping an eye on the documentation!

In this case you are looking at the documentation in the master branch, which is the development branch which has not yet been released in a version that includes the changes to prune that you mention. The next restic release will contain these changes.

If you want to look at the documentation for the latest stable release, you need to select the "v: stable" option at the bottom of the documentation website.

**Comment by tonypilz** [comment]
I see, my mistake, sry and thanks for the fast reply. Greetings Tony

**Comment by fd0** [comment]
Heh, thanks for the hint! I've configured readthedocs so that by default the `stable` version of the docs is shown (which matches the latest released version of restic). That should prevent some confusion for users. :)

**Comment by tonypilz** [comment]
Awesome :)
