### ISSUE TITLE
Stats are wrong for overlapping/multiply given files/dirs

### ISSUE THREAD

**Issue by dverzolla** [restic/restic#3232]
`restic 0.11.0 compiled with go1.15.3 on windows/amd64`
and
`restic 0.11.0 compiled with go1.15.3 on linux/amd64`

--------------------------

How did you run restic exactly?
-------------------------------

I’m using ‘–json’ parameter to get the backup output to stdout in JSON format.
I got an awkward ‘percent_done’ based in the folders I pass as parameter.

Command:

`restic -r /repo backup parent parent/child-1 parent/child-2 /parent/child-3 --json`
The percent_done returned doesn't go beyond 51~59%. However, the backup is done right.

If I pass only the parent folder, the percent_done works as expected (100%)
`restic -r /repo backup parent --json`

I know, doesn’t make sense to use the ‘child’ folders once I have already passed the ‘parent’. However I got this ‘error’.

Output:
`
{"message_type":"status","percent_done":0,"total_files":1,"total_bytes":102400000}
{"message_type":"status","percent_done":0.009508571428571429,"total_files":7,"total_bytes":716800000,"bytes_done":6815744,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.031451428571428575,"total_files":7,"total_bytes":716800000,"bytes_done":22544384,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.054857142857142854,"total_files":7,"total_bytes":716800000,"bytes_done":39321600,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.07826285714285715,"total_files":7,"total_bytes":716800000,"bytes_done":56098816,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.10020571428571429,"total_files":7,"total_bytes":716800000,"bytes_done":71827456,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.11483428571428571,"total_files":7,"total_bytes":716800000,"bytes_done":82313216,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.13458285714285714,"total_files":7,"total_bytes":716800000,"bytes_done":96468992,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.15872,"total_files":7,"total_bytes":716800000,"bytes_done":113770496,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.18285714285714286,"total_files":7,"total_bytes":716800000,"bytes_done":131072000,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.20553142857142856,"total_files":7,"total_bytes":716800000,"bytes_done":147324928,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.22308571428571428,"total_files":7,"total_bytes":716800000,"bytes_done":159907840,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.24429714285714285,"total_files":7,"total_bytes":716800000,"bytes_done":175112192,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.26843428571428574,"total_files":7,"total_bytes":716800000,"bytes_done":192413696,"current_files":["/parent/child-1/f.txt","/parent/child-2/f.txt"]}
{"message_type":"status","percent_done":0.29010285714285716,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":207945728,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.31204571428571426,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":223674368,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.33545142857142857,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":240451584,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.35812571428571427,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":256704512,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.3727542857142857,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":267190272,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.3932342857142857,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":281870336,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.41810285714285716,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":299696128,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.44004571428571426,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":315424768,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.46125714285714287,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":330629120,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.4846628571428571,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":347406336,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.5073371428571428,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":363659264,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.5314742857142857,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":380960768,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"status","percent_done":0.5534171428571428,"total_files":7,"files_done":2,"total_bytes":716800000,"bytes_done":396689408,"current_files":["/parent/child-3/f.txt","/parent/f.txt"]}
{"message_type":"summary","files_new":4,"files_changed":0,"files_unmodified":0,"dirs_new":4,"dirs_changed":0,"dirs_unmodified":0,"data_blobs":2,"tree_blobs":5,"data_added":743468,"total_files_processed":4,"total_bytes_processed":409600000,"total_duration":0.686637302,"snapshot_id":"0cf22fd6"}
`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
`local storage and S3`

Expected behavior
-----------------

Expected --json percent_done to be 1 (100%)

Actual behavior
---------------

Doesn't go beyond 51~59%

Steps to reproduce the behavior
-------------------------------

`restic -r /repo backup parent parent/child-1 parent/child-2 /parent/child-3 --json`
The percent_done returned don’t go beyond 51~59%. However, the backup is done right.

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is an amazing opensource software, I'm start using it and enjoying a lot. You guys are doing a great job. Congrats.

**Comment by moritzdietz** [comment]
This is the thread on the forum: https://forum.restic.net/t/restic-backup-percent-done-bug/3459/2
(just so we have cross links)

**Comment by dverzolla** [comment]
Just adding another behaviour... The problem still happen when passing the same file twice or more.

`restic backup A.exe A.exe --json` returns nothing more than 55%, this percentage sometime varies, it depends on total file size. Seems to be starting (or ending) here: https://github.com/restic/restic/blob/5fd3dbccb73e6e439b63c3c6be6840a414d3e68f/internal/ui/json/backup.go#L175

`status.PercentDone = float64(processed.Bytes) / float64(total.Bytes)` 

I'm gathering information so I could do a PR. I'll be more than happy if someone could share any clue. 

@mholt ?

**Comment by fd0** [comment]
Thanks for the report, it's a bug, and it's independent from the output mode. It also happens without `--json`. The reason is (as far as I remember) that the 'scanner' part of restic is not intelligent enough to realize that some dirs/files are specified twice and will add the size twice to `total.Bytes`. The part of restic which does the backup will realize that, so `processed.Bytes` will only include the size once.

**Comment by fd0** [comment]
Will be fixed in #3243, that was easier than I thought... :)
