### ISSUE TITLE
Ignore permission denied errors when reading local files

### ISSUE THREAD

**Issue by AndrewBelt** [restic/restic#3234]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
restic fails with
```
signal interrupt received, cleaning up
```
when local files cannot be read, e.g.
```
scan: Open: open /home/vortico/pkg/atom-editor/pkg: permission denied
scan: Open: open /home/vortico/pkg/visual-studio-code-git/pkg: permission denied
```
By default, restic should fail, but in my case, I don't care about backing up files I can't read.
If there was an option `--ignore-read-errors` or something similar, restic could continue with the backup while omitting the files it can't read locally.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
In some developers' home directories, there will be several "weird" files created by build scripts, Docker, VirtualBox, webservers, etc that cannot be read by my normal user UNIX account. I can safely ignore these files and my backups will be just as useful to me. rsync prints errors to stderr but continues to copy files. It would be nice if restic did the same.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes. Currently evaluating a number of backup programs and this one looks promising.

**Comment by MichaelEischer** [comment]
`signal interrupt received, cleaning up` means that a SIGINT signal was sent to restic. restic already happily ignores files it cannot read and will finish with a non-zero exit code. So I wonder where that signal originates from?

You could also tell restic to `--exclude` files you don't care about.

**Comment by AndrewBelt** [comment]
@MichaelEischer Interesting, thanks for the information. If restic continues but fails, it already has the best behavior (IMO). I will investigate again tonight when I have access to my backup drive again and update the issue with what's really happening. In the above example, restic indeed exited 30% through the backup.

**Comment by AndrewBelt** [comment]
Shortly after I created the issue but before your response, I deleted several folders that caused `permission denied` messages, and now after re-running the backup, it succeeds (even while there are other `permission denied` messages for other folders).
So now I can't reproduce the `signal interrupt received, cleaning up` exit. Will re-open if I can reproduce again.
