### ISSUE TITLE
B2: restic init does nothing forever

### ISSUE THREAD

**Issue by Suika** [restic/restic#3237]
Output of `restic version`
--------------------------
`restic 0.11.0 compiled with go1.15.3 on linux/amd64`

How did you run restic exactly?
-------------------------------
`XDG_CACHE_HOME="/XXXX/.cache" B2_ACCOUNT_ID=XXXX B2_ACCOUNT_KEY=XXXX RESTIC_PASSWORD=XXXX RESTIC_REPOSITORY=b2:XXXX:XXXX /usr/bin/restic init`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Wast trying to setup a repository.

Expected behavior
-----------------
After X second I would get a confirmation about the creation of the repository.

Actual behavior
---------------
Nothing, literally. But the process is doing something and then the load is falling off rapidly. `ps aux`:
```
root     32700 49.8  0.0 792840 85608 pts/7    Sl+  22:31   0:15 restic init
root     32700 37.2  0.0 793352 85836 pts/7    Sl+  22:31   0:16 restic init
root     32700 10.1  0.0 793864 86344 pts/7    Sl+  22:31   0:16 restic init
root     32700  8.3  0.0 794376 86344 pts/7    Sl+  22:31   0:16 restic init
```

Steps to reproduce the behavior
-------------------------------
See >How did you run restic exactly?

Do you have any idea what may have caused this?
-----------------------------------------------
Either it's B2 being an ass at this exact point in time or something in their endpoint changed.
Tested on another server with a lower restic version `restic 0.9.3 compiled with go1.11.1 on linux/amd64`. same result.

Do you have an idea how to solve the issue?
-------------------------------------------
¯\\_(ツ)_/¯

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Someday surely.

**Comment by rawtaz** [comment]
Just curious if you could use tcpdump or similar to check if there's any traffic going between your client and B2 when you try to init? Or see if adding `--verbose 3` yields some additional info.

**Comment by Suika** [comment]
Adding `-v=3` does nothing. Silence all the way throughout the whole process.
`XDG_CACHE_HOME="/XXXX/.cache" B2_ACCOUNT_ID=XXXX B2_ACCOUNT_KEY=XXXX RESTIC_PASSWORD=XXXX RESTIC_REPOSITORY=b2:XXXX:XXXX strace -f -e trace=network -s 10000 restic -v=3 init  2>&1 | tee -a /tmp/restic_init.txt`
Resulted in: [restic_init.log](https://github.com/restic/restic/files/5869525/restic_init.log)

In the duration of ~3-4 minutes 80 b2 IPs were poked.
<details><summary>Connected IPs</summary>
<p>

```
104.153.232.165
104.153.233.176
104.153.233.177
104.153.233.180
104.153.233.52
104.153.233.79
104.153.234.150
104.153.234.153
104.153.234.154
104.153.234.155
104.153.234.156
104.153.234.157
104.153.234.158
104.153.234.162
104.153.234.163
104.153.234.164
104.153.234.167
104.153.234.168
104.153.234.169
104.153.237.101
104.153.237.107
104.153.237.113
104.153.237.116
104.153.237.118
104.153.237.12
104.153.237.120
104.153.237.121
104.153.237.124
104.153.237.125
104.153.237.130
104.153.237.131
104.153.237.133
104.153.237.140
104.153.237.151
104.153.237.153
104.153.237.157
104.153.237.159
104.153.237.162
104.153.237.166
104.153.237.167
104.153.237.17
104.153.237.170
104.153.237.171
104.153.237.172
104.153.237.174
104.153.237.175
104.153.237.177
104.153.237.178
104.153.237.180
104.153.237.181
104.153.237.182
104.153.237.184
104.153.237.185
104.153.237.186
104.153.237.187
104.153.237.188
104.153.237.190
104.153.237.20
104.153.237.23
104.153.237.28
104.153.237.29
104.153.237.66
104.153.237.73
104.153.237.75
104.153.237.82
104.153.237.93
104.153.237.96
104.153.237.99
206.190.212.158
206.190.212.85
206.190.213.169
206.190.213.171
206.190.213.184
206.190.213.199
206.190.213.200
206.190.213.213
206.190.213.220
206.190.213.224
206.190.213.239
206.190.215.15
```

</p>
</details>

Checked my B2 caps, none of them are close to hitting the ceiling.
Checked my router and any type of DNS blocking, none of them blocked any requests to B2. 
Disabled the whole DNS Ad blocking setup, still no luck with restic and B2.

The strange thig is, I have a big ass automation setup running and the backups are running properly. None of them failed.
```
Files:       61384 new, 10761 changed, 3142038 unmodified
Dirs:        52900 new, 22442 changed, 4495956 unmodified
Added to the repo: 2.091 GiB

processed 3214183 files, 128.752 GiB in 45:29
snapshot f692ab66 saved
```

**Comment by Suika** [comment]
Ok, it was my stupid ass that forgot that the key I used was for a specific namePrefix. That is the reason it was not able to create a repository.
