### ISSUE TITLE
restic error /  storage: object doesn't exist

### ISSUE THREAD

**Issue by michbsd** [restic/restic#3238]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.6 on freebsd/amd64

How did you run restic exactly?
-------------------------------

Running: `restic  check` or `restic prune` (after running `restic forget  --keep-weekly 16`) - is giving: 

```
using temporary cache in /tmp/restic-check-cache-187733807
repository f71a7812 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-187733807
create exclusive lock for repository
load indexes
check all packs
pack 366e53a7: does not exist
check snapshots, trees and blobs
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 552.330144ms: storage: object doesn't exist
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 1.080381816s: storage: object doesn't exist
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 1.31013006s: storage: object doesn't exist
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 1.582392691s: storage: object doesn't exist
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 2.340488664s: storage: object doesn't exist
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 4.506218855s: storage: object doesn't exist
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 3.221479586s: storage: object doesn't exist
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 5.608623477s: storage: object doesn't exist
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 7.649837917s: storage: object doesn't exist
Load(<data/366e53a70a>, 0, 0) returned error, retrying after 15.394871241s: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 507.606314ms: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 985.229971ms: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 803.546856ms: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 1.486109007s: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 2.070709754s: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 3.67875363s: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 4.459624189s: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 6.775444383s: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 15.10932531s: storage: object doesn't exist
Load(<data/366e53a70a>, 401, 30734) returned error, retrying after 13.811796615s: storage: object doesn't exist
error for tree ca9d6be6:
  storage: object doesn't exist
Fatal: repository contains errors
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Google Cloud Storage

Expected behavior
-----------------

check and prune should complete successfully

Actual behavior
---------------

bombs out with the "storage: object doesn't exist error"

Steps to reproduce the behavior
-------------------------------

I think this is in the repo - so cannot be reproduced. But I would like to know how to fix.

**Comment by michbsd** [comment]
I tried rebuilding the index:

```
restic rebuild-index                                                                                                                                7773  11:34:33
enter password for repository:
repository f71a7812 opened successfully, password is correct
counting files in repo
[8:10] 100.00%  22911 / 22911 packs
finding old index files
saved new indexes as [f287c3b1 23619143 f28bc670 cd38a52e 5458c0c7 60b226fb 9c8f301c 5166b6fa]
remove 231 old index files
[0:02] 100.00%  231 / 231 files deleted
```

and, now I get the following error when running `restic check`

```
using temporary cache in /var/folders/w5/hrvprvzn62g5s08kq624bfnw0000gn/T/restic-check-cache-750211438
enter password for repository:
repository f71a7812 opened successfully, password is correct
created new cache in /var/folders/w5/hrvprvzn62g5s08kq624bfnw0000gn/T/restic-check-cache-750211438
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree ca9d6be6:
  id ca9d6be65fab3b4266b749da594d315516b490a5e3b6d16457e0b6ba4027466c not found in repository
Fatal: repository contains errors
```

**Comment by michbsd** [comment]
more stuff:

```
restic find --tree ca9d6be65fab3b4266b749da594d315516b490a5e3b6d16457e0b6ba4027466c                                                            
enter password for repository:
repository f71a7812 opened successfully, password is correct
Unable to load tree ca9d6be65fab3b4266b749da594d315516b490a5e3b6d16457e0b6ba4027466c
 ... which belongs to snapshot 6c81088d34d92a449c1a3aacf98e18833b5e4c80f9c5a56f7439bd37a29514e7.
```
 restic ls 6c81088d34d92a449c1a3aacf98e18833b5e4c80f9c5a56f7439bd37a29514e7                                                               
enter password for repository:
repository f71a7812 opened successfully, password is correct
snapshot 6c81088d of [REDACTED] filtered by [] at 2021-01-24 03:10:02.835424932 +0100 CET):
id ca9d6be65fab3b4266b749da594d315516b490a5e3b6d16457e0b6ba4027466c not found in repository
github.com/restic/restic/internal/repository.(*Repository).LoadBlob
	github.com/restic/restic/internal/repository/repository.go:156
github.com/restic/restic/internal/repository.(*Repository).LoadTree
	github.com/restic/restic/internal/repository/repository.go:723
github.com/restic/restic/internal/walker.Walk
	github.com/restic/restic/internal/walker/walker.go:37
main.runLs
	github.com/restic/restic/cmd/restic/cmd_ls.go:197
main.glob..func15
	github.com/restic/restic/cmd/restic/cmd_ls.go:44
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	github.com/restic/restic/cmd/restic/main.go:98
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_amd64.s:1374
```

**Comment by michbsd** [comment]
I then did:
```
restic forget 6c81088d34d92a449c1a3aacf98e18833b5e4c80f9c5a56f7439bd37a29514e7                                                                 
repository f71a7812 opened successfully, password is correct
[0:00] 100.00%  1 / 1 files deleted
```

and then my prune worked 😀

```
restic prune
repository f71a7812 opened successfully, password is correct
counting files in repo
building new index for repo
[7:49] 100.00%  22911 / 22911 packs
repository contains 22911 packs (386073 blobs) with 134.863 GiB
processed 386073 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 328 snapshots
[0:11] 100.00%  328 / 328 snapshots
found 377846 of 386073 data blobs still in use, removing 8227 blobs
will remove 0 invalid files
will delete 669 packs and rewrite 412 packs, this frees 3.154 GiB
[2:12] 100.00%  412 / 412 packs rewritten
counting files in repo
[7:38] 100.00%  22054 / 22054 packs
finding old index files
saved new indexes as [f5e098f8 a3e73b43 6b96b972 d5538ba5 ef23b05f 737ff6c2 30a180cf f953cb2f]
remove 9 old index files
[0:00] 100.00%  9 / 9 files deleted
remove 1081 old packs
[0:09] 100.00%  1081 / 1081 files deleted
```

**Comment by michbsd** [comment]
guess we can close this one again

**Comment by fd0** [comment]
Hm, that's an odd issue. Restic complained that a file it uploaded previously is not there any more. Any idea what went wrong here that the file was hidden/deleted?

**Comment by michbsd** [comment]
Maybe something went wrong when writing to Google Cloud Storage?

**Comment by fd0** [comment]
That'd be concerning, because the only explanation I can see is that the cloud backend reported a successful upload and then managed to lose the file. Restic will retry a failed upload a few times, bailing out with an error if the upload could not be completed successfully, and the to be uploaded file is not referenced anywhere afterwards. Hm. No idea what went wrong here.

Do you maybe have logs of the previous runs of `restic backup` that we could look at?

**Comment by michbsd** [comment]
Unfortunately not, restic is running from cron during the night - I do send a recap mail with the results, but those have since been deleted. 
I will have a look at GCP logs from around that timestamp if I can see something - but I doubt it. 
I will be vigilant if this happens again, so we can do some more digging.

**Comment by michbsd** [comment]
Nothing in GCP logs.

**Comment by fd0** [comment]
Ok, it was worth a try. :)
