### ISSUE TITLE
Data blobs seem to be missing, aborting prune to prevent further data loss!

### ISSUE THREAD

**Issue by RaffiOl** [restic/restic#3239]
restic 0.11.0 compiled with go1.15.3 on darwin/amd64

# restic prune
repository a9fd47a9 opened successfully, password is correct
counting files in repo
building new index for repo
[14:34] 100.00%  172118 / 172118 packs
repository contains 172118 packs (1537447 blobs) with 793.815 GiB
processed 1537447 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 112 snapshots
[0:19] 100.00%  112 / 112 snapshots
Fatal: [<data/a08568fc> <data/69d69781> <data/ae3a1fc6> <data/5f9fd49a> <data/a5359e9b> <data/d0dd7591> <data/d6a534ad>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose

**Comment by RaffiOl** [comment]
Close... dupllicate, sorry.

**Comment by MichaelEischer** [comment]
> Close... dupllicate, sorry.

I'm not so sure about that. At least not until we had a chance to investigate the exact damage. But for that I need a bit more information:

Did you notice any errors reported in prior restic runs or did something unexpected happen? Maybe an interrupted network connection or a did the host go into standby while restic was running?

How often do you run `backup`, `check` and/or `prune`?

Which backend are you using? Is the repository used by multiple hosts or just a single host?

Do you use the `unlock` command or is it called automatically from your backup scripts?

Please run also run `check` to get more details on the damage.

Did you run any commands previously to try to repair the damage? I'm especially interested in whether you ran `rebuild-index`. If the answer is no, then please create a backup of the repository index (the `index/` folder in the repository).
Please do **NOT** run `rebuild index` before you have created a backup of the repository index.

**Comment by RaffiOl** [comment]
Hi,

Normally, I'm using rest-server on a backup server and restic on the clients. I've used 'unlock' multiple times, caused by a lost vpn connection and "hanging" backup process. Backup two times a week, Windows/Linux/Mac Desktop/Servers but only relevant data no OS system specific ones.

After index rebuild, check returns this:

➜  root@backup  /Backups/restic restic -v check -r .
using temporary cache in /tmp/restic-check-cache-534078941
repository a9fd47a9 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-534078941
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree 26f610f3:
  tree 26f610f3: file "ARTIKEL.DBF" blob a5359e9be1732cd0b4a617d7f88cb651a7c04306082d93c6caf5b55e5a8d393d not found in index
  tree 26f610f3: file "ARTIKEL.DBF" blob 69d69781bee3fc5abfddc52ac81830807f774455fc0ca446045da9d09fb4d26a not found in index
  tree 26f610f3: file "KUNDEN.DBF" blob ae3a1fc669e9e3df6656ddbdbda63f824853892e389c0fe36d8f8c0e7342d5fe not found in index
  tree 26f610f3: file "KUNDEN.DBF" blob 5f9fd49a8700ac74d1ebaf0bc5857db697a75cc88c08255a1feacda5b5aa54fb not found in index
  tree 26f610f3: file "KUNDEN.DBF" blob a08568fc2dd32e7332ccd040af655a6b396d5ec8b4af498ef5bb97c68957778e not found in index
  tree 26f610f3: file "MEINHEIT.DBF" blob d0dd7591c497eec8c73e0befe4d75ddc1df45e53bab5c3e7daf8191ce31e6de3 not found in index
  tree 26f610f3: file "MEINHEIT.DBF" blob d6a534ad8a2b2ede4135370828ff5e33283597240939174d51a9c450263e3712 not found in index
Fatal: repository contains errors

Seems to be one damaged snapshot. 

I'l try to delete that one....

**Comment by RaffiOl** [comment]
➜  root@backup  /Backups/restic restic find --blob a5359e9be1732cd0b4a617d7f88cb651a7c04306082d93c6caf5b55e5a8d393d -r .
repository a9fd47a9 opened successfully, password is correct
Found blob a5359e9be1732cd0b4a617d7f88cb651a7c04306082d93c6caf5b55e5a8d393d
 ... in file /ARTIKEL.DBF
     (tree 26f610f3b3fdfdae16f73b75f85c134768115e00d4a4f86aa8b66be556522750)
 ... in snapshot c7eb6792 (2020-10-10 12:28:46)
Found blob a5359e9be1732cd0b4a617d7f88cb651a7c04306082d93c6caf5b55e5a8d393d
 ... in file /ARTIKEL.DBF
     (tree 26f610f3b3fdfdae16f73b75f85c134768115e00d4a4f86aa8b66be556522750)
 ... in snapshot 8b80c67e (2020-10-10 12:12:48)

➜  root@backup  /Backups/restic restic forget c7eb6792 8b80c67e -r .
repository a9fd47a9 opened successfully, password is correct
[0:00] 100.00%  2 / 2 files deleted

➜  root@backup  /Backups/restic restic prune -r .
repository a9fd47a9 opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 110 snapshots
[0:19] 100.00%  110 / 110 snapshots
searching used packs...
collecting packs for deletion and repacking
[0:00] 100.00%  172118 / 172118 packs processed

to repack:            0 blobs / 0 B
this removes          0 blobs / 0 B
to delete:         1057 blobs / 2.816 GiB
total prune:       1057 blobs / 2.816 GiB
remaining:      1536390 blobs / 790.940 GiB
unused size after prune: 302.326 MiB (0.04% of remaining size)

rebuilding index
[0:04] 100.00%  171641 / 171641 packs processed
deleting obsolete index files
[0:00] 100.00%  58 / 58 files deleted
removing 477 old packs
[0:01] 100.00%  477 / 477 files deleted
done
➜  root@backup  /Backups/restic restic check -r .
using temporary cache in /tmp/restic-check-cache-306170146
repository a9fd47a9 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-306170146
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found

**Comment by RaffiOl** [comment]
restic prune -r . -v
repository a9fd47a9 opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 117 snapshots
[0:24] 100.00%  117 / 117 snapshots
searching used packs...
{<data/25049b0c> <data/26d4f23e> <data/38ba2411> <data/45c8fe35> <data/46f9654d> <data/4ec23bca> <data/53ac0e3f> <data/62a4813f> <data/6e229de3> <data/6e7a832b> <data/e07fa718>} not found in the index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/chooseFatal: index is not complete

got the same error after backing up with an vpn reconnect:

restic backup . --iexclude "/restic/" --iexclude "*.tmp"
repository a9fd47a9 opened successfully, password is correct
Save(<data/74916b642e>) returned error, retrying after 552.330144ms: client.Post: Post http://192.168.1.240:8000/data/74916b642ecc9a7eaa8e48420dfcce854e0f57a1c12a854c2da2803069a8e1f7: net/http: HTTP/1.x transport connection broken: write tcp 192.x:55533->192.x:8000: wsasend: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
Save(<data/aaebf230fc>) returned error, retrying after 720.254544ms: client.Post: Post http://192.168.1.240:8000/data/aaebf230fc573dcda78a384937b4d4625a45cbc8731f39b27690911e701644c2: net/http: HTTP/1.x transport connection broken: write tcp 192.x:55200->192.x:8000: wsasend: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
Save(<data/2083b8bc2e>) returned error, retrying after 582.280027ms: client.Post: Post http://192.168.1.240:8000/data/2083b8bc2e57cdd8d5c9b8fa3d7e3039844a1fd629377c1615952fb6e5f256c9: net/http: HTTP/1.x transport connection broken: write tcp 192.x:55040->192.x:8000: wsasend: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.
Save(<data/2083b8bc2e>) returned error, retrying after 703.28564ms: server response unexpected: 403 Forbidden (403)
Save(<data/aaebf230fc>) returned error, retrying after 693.478123ms: server response unexpected: 403 Forbidden (403)

Files:       238069 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 396.931 GiB

processed 238069 files, 644.168 GiB in 27:58:28
snapshot 39842bfb saved

**Comment by MichaelEischer** [comment]
@RaffiOl Which parameters do you pass to the rest-server binary when running it on the server? I'd assume you're not using `--append-only`?

Could you check whether the following files exist in the repository on the server: `data/74/74916b642ecc9a7eaa8e48420dfcce854e0f57a1c12a854c2da2803069a8e1f7`, `data/aa/aaebf230fc573dcda78a384937b4d4625a45cbc8731f39b27690911e701644c2` and `data/20/2083b8bc2e57cdd8d5c9b8fa3d7e3039844a1fd629377c1615952fb6e5f256c9`?

**Comment by RaffiOl** [comment]
Good Morning,

rest-server is started with: "./rest-server --path /Backups/restic --no-auth", Version: rest-server 0.10.0 (v0.10.0-12-ga659f3d) compiled with go1.13.8 on linux/amd6

> data/74/74916b642ecc9a7eaa8e48420dfcce854e0f57a1c12a854c2da2803069a8e1f7, 
> data/aa/aaebf230fc573dcda78a384937b4d4625a45cbc8731f39b27690911e701644c2 and 
> data/20/2083b8bc2e57cdd8d5c9b8fa3d7e3039844a1fd629377c1615952fb6e5f256c9?

Theses files are missing.

**Comment by MichaelEischer** [comment]
@RaffiOl The `403 Forbidden (403)` error looks like the rest server didn't notice immediately that the network connection had failed. That could lead to a race condition with the retried uploads that would explain the missing files. I've opened a PR for the rest-server which fixes that scenario: https://github.com/restic/rest-server/pull/142

**Comment by RaffiOl** [comment]
Good Evening,

thanks a lot and have a nice day.....

**Comment by ymarcus93** [comment]
Is this race condition prevented by users who run `rest-server` with `--append-only`? Won't the retry fail in deleting the partial packfile?

**Comment by MichaelEischer** [comment]
@ymarcus93 

> Is this race condition prevented by users who run `rest-server` with `--append-only`? Won't the retry fail in deleting the partial packfile?

It is indeed. With `--append-only` the delete operation and all further upload retries will fail until the rest-server also learns that the initial upload has failed. So either the broken connection is detected before restic runs out of retries or the backup as a whole will fail.   The only exception here are the lock file which can still be deleted when `--append-only` is set. However, as the lock files are pretty small, the risk of an interrupted first upload try is rather low. 

My rest-server PR will also improve the situation here as an incomplete upload won't block further retries.

**Comment by MichaelEischer** [comment]
Closing as restic/rest-server#142 has been merged (although its not released yet)
