### ISSUE TITLE
"ls --json " does not output a size for all Windows files

### ISSUE THREAD

**Issue by LawrenceTattrie** [restic/restic#3247]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on windows/amd64

How did you run restic exactly?
-------------------------------
for backup
powershell script which runs restic with the following options
 -r $RESTIC_REPOSITORY --exclude-file $RESTIC_EXCLUDE_FILE  --use-fs-snapshot --verbose --verbose --cache-dir $CACHEDIR --json ${RESTIC_SOURCE_DRIVE}:\ 2>$RESTIC_STDERR_FILE | Out-File -FilePath .\restic_temp_stdout.log -encoding ascii
for ls
$snapid = 'latest'
ls $snapid -r $RESTIC_REPOSITORY --cache-dir $CACHEDIR | Out-File -FilePath $RESTIC_LS_FILE -encoding ascii

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
usb connect external harddrive

Expected behavior
-----------------
all files listed with ls should have a size in the json output.

Actual behavior
---------------
Note: there was no error for these files when the backup was run!
size was missing

Steps to reproduce the behavior
-------------------------------
On a Windows machine backup the whole C: drive. Do a "ls --json". Capture output and look for files which do not have the attribute size. I did this in python pandas.

Do you have any idea what may have caused this?
-----------------------------------------------
1) The files may have actually been of zero bytes. 
2) I run the backup program using an Administrator id but the directory
c:\Program Files\WindowsApps is so tightly constrained by windows security that some of the files are not readable.  
3) Are the files actually just links to other files meaning there is no bytes being used in a file at that directory location.

Do you have an idea how to solve the issue?
-------------------------------------------
Force the ls command to output a size of zero if there are no bytes being used. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes. Both the program and the community are wonderful.

**Comment by MichaelEischer** [comment]
The `size` field is currently omitted if it contains the value 0. That behavior is identical across platforms. For directories the `size` field is also omitted, as expected. So we'd need a special case for regular file for which `size` should always be included in the output. Anyone up for a PR?
