### ISSUE TITLE
Getting "Fatal: unable to open config file: Stat: Access Denied."

### ISSUE THREAD

**Issue by perfecto25** [restic/restic#3258]
Output of `restic version`
--------------------------
restic-0.10.0-1.el7.x86_64
restic 0.10.0 compiled with go1.15.2 on linux/amd64

running on Centos 7 x64

How did you run restic exactly?
-------------------------------
source /etc/restic/cred (contains AWS key, secret, password, repo path)
restic snapshots

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3

Expected behavior
-----------------
shows snapshots

Actual behavior
---------------
getting 

Fatal: unable to open config file: Stat: Access Denied.
Is there a repository at the following location?
s3:https://s3.amazonaws.com/my-bkup/restic/hostname123

Steps to reproduce the behavior
-------------------------------
export RESTIC_REPOSITORY=s3:https://s3.amazonaws.com/my-bkup/restic/hostname123
export AWS_SECRET_ACCESS_KEY=my secrete key
export AWS_ACCESS_KEY_ID=my key id
export RESTIC_PASSWORD="password"

restic snapshots

Do you have any idea what may have caused this?
-----------------------------------------------
possible CA cert issue? 

I was getting this prior to updating CA pem

```
Fatal: unable to open config file: Stat: Get "https://s3.amazonaws.com/my-bkup/?location=": x509: certificate signed by unknown authority
Is there a repository at the following location?
```
I fixed this issue by running 

```
    cd /etc/pki/ca-trust/source/anchors
    openssl s_client -showcerts -servername s3.amazonaws.com -connect s3.amazonaws.com:443 > s3amazonaws.pem
    openssl x509 -inform PEM -in s3amazonaws.pem -text -out certdata
    update-ca-trust
```

Do you have an idea how to solve the issue?
-------------------------------------------
we have Restic working on some hosts but not others, the S3 bucket permissions for the account have a wildcard giving it full access to all S3 objects and permissions, so I dont think its S3 issue. Feels like something with CA trust

**Comment by MichaelEischer** [comment]
I don't think that "Access Denied" is returned as error when there's a problem with the CA certificate. You could try though whether it helps to specify the s3 certificate using `--cacert file`. Have you tried to set the AWS region using `AWS_DEFAULT_REGION`?

**Comment by perfecto25** [comment]
looks like an issue with our corporate fortinet firewall, was blocking all access to S3.

**Comment by fd0** [comment]
Thanks for the feedback!

**Comment by ralismark** [comment]
For anyone trying to debug this error in the future:

I'm using backblaze via the s3-compatible api, and I also got `Fatal: unable to open config file: Stat: Access Denied.` from hitting the daily download bandwidth cap.

**Comment by unmanbearpig** [comment]
I had the same issue because my system clock was way off. Just in case someone encounters the same issue while restoring from backup.

**Comment by varchasgopalaswamy** [comment]
I had the same issue (using backblaze) because I exceeded my class B/C caps! Just in case someone has the same problem.
