### ISSUE TITLE
Repeated deadlocks using rclone backend 

### ISSUE THREAD

**Issue by martint17r** [restic/restic#3259]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------

Backup is run through a systemd timer.

```
export GOGC=20
export RESTIC_CACHE_DIR=/root/.cache/restic
export RESTIC_PASSWORD=<redacted>
export RESTIC_REPOSITORY=rclone:backblaze:<redacted>
restic backup --tag root --exclude-file=/etc/restic-backup/root.excludes --one-file-system / 
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone running in append only mode on a second host in the same datacenter transmitting to backblaze EU datacenter

The backblaze bucket currently contains 391 snapshots, occupying about 1,723 GB of data in 352,585 files.

Expected behavior
-----------------

backup usually takes 20 to 90 minutes, depending on the added data. Backup is run once every 24 hours. 

I expect restic to fail instead of hanging, even if the backend is not responding properly.

Actual behavior
---------------

restic does not finish the backup in an appropriate time, running until killed.

Steps to reproduce the behavior
-------------------------------

we can't reproduce it all the time, but in the last few days the backup only succeeded two out of five times on the first try.
After SIGQUITing the previous run, it has always completed in appropriate time.

Please find two stacktraces attached:
   * [restic.deadlock.20210202.txt](https://github.com/restic/restic/files/5909942/restic.deadlock.20210202.txt)
   * [restic.deadlock.20210131.txt](https://github.com/restic/restic/files/5909944/restic.deadlock.20210131.txt)

Do you have any idea what may have caused this?
-----------------------------------------------

no

Do you have an idea how to solve the issue?
-------------------------------------------

no

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic saved me so many times, using the mount feature to restore data is a real pleasure. 
restic check alerted me to bit rot on one of my servers, I did not notice before - really great feature.

**Comment by martint17r** [comment]
I have updated the rclone version on the remote host to 1.54 (released on 2021-02-02) from 1.45 (Debian stable default) and this seems to have alleviated some of the pain. It now hangs less frequently.

**Comment by MichaelEischer** [comment]
The two stacktraces look like restic got stuck waiting for a response for rclone. It would be interesting to get a stracktrace what's going on on the rclone side, just send a sigquit signal to rclone for that. Is there a reason why you are using rclone instead of the native B2 backend of restic?

**Comment by martint17r** [comment]
Will do that, once it crashes again - since upgrading to 1.54 it only hung once.

We use the restic<->rclone serve restic<->b2 pipeline to provide an append only backup solution.

**Comment by MichaelEischer** [comment]
Closing this issue as it seems to have been resolved by upgrading rclone. Feel free to reopen this issue if this is not the case.
