### ISSUE TITLE
Command `restic ls` consumes much RAM

### ISSUE THREAD

**Issue by saschalalala** [restic/restic#326]
Hey, 

I am working a bit more with restic right now and back up some folders from my home to a vhost via sftp, that works quite nice. I naively just started a restic -r backup ls <snapshot-id> and restic goes insane. It allocated all of my RAM and started swapping (16GB RAM, the backup contains a lot of development folders including their .git directories) and eventually started showing _all_ files that are included in the backup. I guess a more practical behaviour that also mimics the behaviour of a linux shell would be… well, the behaviour of a linux shell, not ls -R. This way, one could navigate through the folder structure and ls the folder he/she would like to access. I have no idea how that would affect the runtime and RAM usage etc.

**Comment by fd0** [comment]
Hi, thanks for the report. I've just yesterday fixed a really annoying bug that caused restic to create a huge number of redundant index files. Have a look at the "index" subdir of the repository, if it is really large with many files, you are affected by the bug.

Please update restic, run `restic check` and see if it advises you to run `restic rebuild-index`. If this is the case, please run it, afterwards everything should be fine (see #324). Please report back if this worked for you!

Regarding the `ls` command: It's rather basic at the moment, did you give the fuse mount a try?

**Comment by saschalalala** [comment]
Hey, thanks for the answer. I did that a few weeks ago and really like it but at the moment, I am playing around with restic in general so I also tried ls which could become handy for quick overviews (If it would be faster). I seem to be affected by the bug (3.8G index for ~6.5G of files). I updated and recompiled, and `restic -r backup check` consumes a huge amount of memory again (Is that a part of the bug) and rebuilding runs smooth at the moment. Just to be clear: I downloaded the backups from the vhost to work with it locally, I am free to unpack/move/whatever the backup repository and continue working with it without problems, right?

**Comment by fd0** [comment]
You can download/copy/move the repository and use it wherever you like, it's not a problem (at least for the local and sftp backends, s3 has a slightly different layout)

Yes, `check` is unfortunately also affected, but should run smoothly again after rebuild is finished. Please report back :)

**Comment by saschalalala** [comment]
The index shrinked from 3.8G to 22M, the `check` runs much faster now, but still reports errors like 
```pack be1b74b78a853adaf8ffc502141ff21857a0f180b7cba76ddb1e395d37bea45c: not referenced in any index```
and 
```unused blob 77cf5940```
but `ls` is really fast now.

**Comment by fw42** [comment]
>  index shrinked from 3.8G to 22M

:heart_eyes:

**Comment by fd0** [comment]
Not bad, huh? ;)

It was a really nasty bug.

I'm wondering about the unreferenced pack, that should've been added to the index in the `repack-index` process.

So, what's your proposal regarding the `ls` function? Shall we discuss this in a different issue (since the memory usage is solved)?

**Comment by saschalalala** [comment]
Yes, I had a few interruption when I wrote the initial backup, 3 or 4. Is there any way to repair that? The backup seems clean. We can address the `restic ls` functionality in another thread, of course. This one seems fixed, thanks ;)

**Comment by saschalalala** [comment]
By the way: I saw that restic is maintained in the AUR, perhaps you should contact the maintainer about that bug so that he pushes an update to the AUR.

**Comment by fd0** [comment]
Hm, the only package I'm aware of is `restic-git`, and that automatically installs the latest version in the master branch (and is maintained by @scoddy, who is a restic core team member).

So, I've opened a new issue to discuss enhancing the functionality of the `ls` command in #327.

**Comment by saschalalala** [comment]
Yeah, it's restic-git. But as far as I know, *-git packages in the AUR are built when they are installed, but updates need to be forced by the maintainer. There is no automatic git check when you update your packages using packer or yaourt.

**Comment by fd0** [comment]
Hm, interesting. I'll ask @scodyd to take a look.
