### ISSUE TITLE
Data blobs missing, aborting prune to avoid data loss.

### ISSUE THREAD

**Issue by x-8523** [restic/restic#3260]
Output of `restic version`
--------------------------
`restic 0.10.0 compiled with go1.15.1 on linux/amd64`

How did you run restic exactly?
-------------------------------
Environment variables:
```
# backup directory (ie what to back up)
export BACKUP_SOURCE="/backup_directory/"

# password for client side encryption
export RESTIC_PASSWORD="resticPassword"

# store URL (ie where to back up the data)
export STORE_URL="azure:xxx:/"

# azure credentials
export AZURE_ACCOUNT_NAME="azureName"
export AZURE_ACCOUNT_KEY="azureKey"
```

We execute:
`restic -r "${STORE_URL}" forget --limit-download 200000 --limit-upload 200000 --prune --keep-last 5 --keep-daily 7 --keep-monthly 12 --keep-yearly 5`

Output is:
```
Applying Policy: keep the last 5 snapshots, 7 daily, 12 monthly, 5 yearly snapshots
keep 14 snapshots:
[...]
14 snapshots

remove 1 snapshots:
ID        Time                 Host                  Tags        Paths
----------------------------------------------------------------------
35ce6a3e  2021-01-26 01:39:09  xxx              /backup_directory
----------------------------------------------------------------------
1 snapshots

[0:00] 100.00%  1 / 1 files deleted

counting files in repo
building new index for repo
pack file cannot be listed 267805c0377b66ef496154c315e086bccbf5a581555934c8b38e6d9015b73d1c: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:6f99d0eb-c01e-002c-2f06-f91338000000
Time:2021-02-02T01:52:14.6651614Z, RequestInitiated=Tue, 02 Feb 2021 01:52:14 GMT, RequestId=6f99d0eb-c01e-002c-2f06-f91338000000, API Version=, QueryParameterName=, QueryParameterValue=
[16:50] 100.00%  29083 / 29083 packs

repository contains 29082 packs (1574299 blobs) with 140.661 GiB
processed 1574299 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 14 snapshots
[0:41] 100.00%  14 / 14 snapshots

Fatal: [<data/e10abcb7> <data/b560d0dc> <data/9bae48c9> <data/9cd925fd> <data/ac5c58ce> <data/08e40397> <data/c97ff7b6> <data/3385e1f2>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
```

The error message is clearly this:
```
Fatal: [<data/e10abcb7> <data/b560d0dc> <data/9bae48c9> <data/9cd925fd> <data/ac5c58ce> <data/08e40397> <data/c97ff7b6> <data/3385e1f2>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
```

The `restic prune` outputs this:
```
repository afe59b03 opened successfully, password is correct
counting files in repo
building new index for repo
[5:14] 100.00%  29083 / 29083 packs
repository contains 29083 packs (1574307 blobs) with 140.665 GiB
processed 1574307 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 14 snapshots
[0:47] 100.00%  14 / 14 snapshots
found 1573688 of 1574307 data blobs still in use, removing 619 blobs
will remove 0 invalid files
will delete 0 packs and rewrite 16 packs, this frees 5.141 MiB
[0:53] 100.00%  16 / 16 packs rewritten
counting files in repo
[6:11] 100.00%  29080 / 29080 packs
finding old index files
saved new indexes as [54bda4e1 b7f7e97e d658eb3a bd7428b0 73ece8cb b1ade6d9 0a9baa69 362f56c1 45ddeaae 5fee2104]
remove 12 old index files
[0:00] 100.00%  12 / 12 files deleted
remove 16 old packs
[0:00] 100.00%  16 / 16 files deleted
done
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Azure Storage

Expected behavior
-----------------
Working without a crash. (it is the first time that restic is behaving like this)

Actual behavior
---------------
The "AuthenticationFailed" is weird because just before, the backup succeeded with the same environment variables. Moreover, it succeeded in listing the snapshots.

Steps to reproduce the behavior
-------------------------------
Honestly, I do not know how.

Do you have any idea what may have caused this?
-----------------------------------------------
No. (the failed authentication?)

Do you have an idea how to solve the issue?
-------------------------------------------
No and I wonder if I need to disable the tomorrow's backup.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
The most important part of the error message is actually the error returned while rebuilding the index:

```
pack file cannot be listed 267805c0377b66ef496154c315e086bccbf5a581555934c8b38e6d9015b73d1c: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

That looks like a temporary hick-up especially as it didn't occur again in the second prune run. So maybe a network packet got corrupted. The strange thing here is that restic apparently didn't retry the operation although it should have. Do you know at which time exactly the failing `forget` run was started?

> No and I wonder if I need to disable the tomorrow's backup.

As the `prune` run after the failing `forget` did work, it looks like the repository itself is ok. The failure in during `forget` also happened during the initial integrity check which doesn't modify anything in the repository yet.

**Comment by x-8523** [comment]
Sorry for not replying in time but I do not have the date/time for this failing.

The backup of the day after worked as expected. We had the same issue on another backup on the same day as the one above.
So this issue seemed to be temporary. It has been multiple days that the backup works as expected. So probably a network issue as you said.

**Comment by MichaelEischer** [comment]
Closing as the prune implementation has been rewritten in 0.12.0
