### ISSUE TITLE
SaveTree returned unexpected id

### ISSUE THREAD

**Issue by tmakarios** [restic/restic#3267]
Output of `restic version`
--------------------------
On machine X: `restic 0.10.0 compiled with go1.15.6 on linux/amd64` (from the Debian bullseye repository, though most of the other software on machine X is from Debian buster).
On machine Y: `restic 0.9.4 compiled with go1.11.6 on linux/amd64` (from Debian buster).

How did you run restic exactly?
-------------------------------
On machine X:
```bash
sudo restic \
        --repo $folder/repository \
        --password-file $folder/passphrase \
        init \
        --repo2 /var/restic-combined/repository \
        --password-file2 /root/restic-combined-passphrase \
        --copy-chunker-params
sudo restic \
        --repo /var/restic-combined/repository \
        --password-file /root/restic-combined-passphrase \
        copy \
        --repo2 $folder/repository \
        --password-file2 $folder/passphrase \
        --tag $1\
        latest
```
Where `--tag $1` identifies existing backups containing data from machine Y.  This succeeded.

On machine Y:
```bash
restic -r sftp:$HOSTNAME@restic:repository \
        --password-file /root/restic-passphrase \
        --exclude-caches \
        --exclude="/home/tim/.no-backup" \
        --exclude="/root/.no-backup" \
        --one-file-system \
        --quiet \
        backup --files-from /usr/local/etc/backup-list
```
This successfully made a new backup to the new repository that was created on machine X by the previous commands.

On machine X:
```bash
TMPDIR=$base_directory/.tmp
export TMPDIR
restic \
    --repo $home_path/repository \                         
    --password-file $home_path/passphrase \                
    copy \
    --repo2 $combined_repository \                         
    --password-file2 $combined_passphrase \                
    --cache-dir $cache_directory
```
This is meant to copy the newly-created backup of machine Y to the original repository that existed on machine X before any of the above commands were run.  However, I get the following output:
```
snapshot e048b0d8 of [/etc /home /root /var/lib/apt/extended_states /var/lib/dpkg] at 2021-01-30 20:33:43.941864928 +1300 NZDT)
  copy started, this may take a while...
SaveTree(14998703) returned unexpected id 8227620d
```

`restic check` indicates no errors in either repository.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local storage on machine X, accessed via SFTP from machine Y.

Expected behavior
-----------------
I expect restic to successfully copy the new backup of machine Y to the original repository on machine X.

Actual behavior
---------------
See the note above about the output obtained from the attempted copy.

Steps to reproduce the behavior
-------------------------------
See above.  This is reproducible with backups of machine Y, but I've had no problems when running the same procedure on backups of other machines.

Do you have any idea what may have caused this?
-----------------------------------------------
Just a guess, but are you using truncated hashes in any part of the code that are short enough that a collision is plausible?  Machine Y's backups are by far the biggest of any of my machines — about 80 GiB, I think.

Or maybe there's some incompatibility caused by using restic from Debian bullseye on an otherwise buster machine?

Do you have an idea how to solve the issue?
-------------------------------------------
If my wild guess above about hash collisions is correct, then don't truncate the hashes to be so short.

If it's caused by the buster/bullseye thing, then consider this a request to ensure that an up-to-date version of restic is always available in the Debian stable repository, or at least stable-backports.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is a great tool for automating deduplicated backups of lots of my machines.  I especially like that I can use `rsync` to make an offsite copy of a restic repository, and then use `sha256sum` alone to do an integrity check of the offsite copy, using the checksums in the filenames.

**Comment by fd0** [comment]
Huh, that's indeed an odd issue! Can you reproduce it with a small repo that you can share with us? During `copy`, restic will read and de-serialize metadata about files in so-called "tree" objects. We expect that when a tree is serialized as JSON again, we get exactly the same data, so the hash matches. But apparently you have a situation in which the serialization returns different data...

**Comment by tmakarios** [comment]
> Can you reproduce it with a small repo that you can share with us?

I'm not sure how, given that the same procedure works without problems for all my machines that have smaller repositories than machine Y.

I guess I could try some sort of binary search, to see if it's a particular file on machine Y that's causing the problem.  But that might take a while, and I'd also need to figure out whether the seed-the-new-repository-with-a-backup-from-the-original-repository step is crucial to reproducing the bug.

Actually, I guess that might be useful diagnostic information in itself — figuring out whether the seeding step is crucial.  But that step was there to save time in not having to send 80 GiB over WiFi from machine Y to machine X, so it could take a while to test.

And I might have unpredictable availability for a while, given this ongoing international health crisis in my family https://not-good-enough.nz/ (nothing to do with a pandemic you might have heard about recently).

**Comment by MichaelEischer** [comment]
@tmakarios You can run `restic list blob | grep 14998703` on the source repository to get the full ID of the blob and then run `restic cat blob 14998703[...]` to get the content of the problematic directory. Unfortunately the tree with the differing ID is not accessible, for that ti would be necessary to use a patched restic version.

@fd0 My assumption is that for some reason the tree node is encoded differently when storing it in the destination repository. Currently `copy` decodes the tree node and the encodes it again before writing it to the destination repository. On second thought that's a recipe for disaster: if we ever add new fields to tree nodes, this will break the copy command of older restic versions. Instead copy should just transfer the raw bytes.

**Comment by fd0** [comment]
> My assumption is that for some reason the tree node is encoded differently when storing it in the destination repository. Currently copy decodes the tree node and the encodes it again before writing it to the destination repository.

That's what I thought. Maybe the timestamps have a different timezone or so?

> On second thought that's a recipe for disaster: if we ever add new fields to tree nodes, this will break the copy command of older restic versions. Instead copy should just transfer the raw bytes.

Indeed! We should change that ASAP...

**Comment by tmakarios** [comment]
Thanks to @MichaelEischer's tips on how to narrow down the source of the error, I found it.  I can trigger the error by trying to copy (using restic 0.11.0) a backup (made with restic 0.9.4 to a fresh repository `init`ted by that same restic version) of just one folder containing just one symlink that points to `../i/\355\246\361d/samba` according to `tree`, or `'../i/'$'\355\246\361''d/samba'` according to `ls -lh`.  The destination repository was `init`ted using restic 0.11.0 and the `--copy-chunker-params` option (copying the parameters from the repository I was about to copy the backup from).

I'm pretty sure it was meant to point to `../init.d/samba`, but once upon a time I had a computer whose motherboard would randomly flip bits — often enough to cause the occasional problem like this, but not often enough to diagnose the problem till some time after the warranty had expired.

**Comment by tmakarios** [comment]
And now I can report that repeating my procedure, right from the start, but excluding the crazy symlink from ending up in the backup, is successful — no more "SaveTree returned unexpected id".

I don't know if you want to make restic cope with such crazy symlinks, or just force people like me to find and eliminate them.  I don't even know if such symlinks are valid in ext4 filesystems (or any other) — I certainly wouldn't have deliberately chosen that as the target of a symlink — but obviously it's _possible_ for ext4 to end up in a state with such symlinks.

**Comment by MichaelEischer** [comment]
@tmakarios Thanks for finding that symlink. I've been able to reproduce the `copy` failure. The issue also reproduces when creating the backup using the latest master branch! To address the copy failure I've opened PR #3310, which just copies the raw bytes for tree nodes. This also ensures compatibility with trees created by future restic versions.

Unfortunately the underlying problem is far more ugly, and probably can't be solved without changes to the repository format: The link target of a symlink is stored as a string, which in `json.Marshal` replaces invalid utf8 characters with the unicode replacement rune. (That rune is encoded differently depending on whether it is added to replace an invalid character or when it is encoded directly. And that is what broke the copy command). So restic stored `../i/\ufffd\ufffd\ufffdd/samba` as path for the crazy symlink, which is not ideal. I've opened #3311 for that specific problem.

**Comment by tmakarios** [comment]
@MichaelEischer Excellent; thank you!

**Comment by greatroar** [comment]
Such filenames/link targets are valid, since Linux's native filesystems are encoding-agnostic. As far as the kernel is concerned, filenames are binary strings, their interpretation up to user-level programs. This is also true for the BSDs, except MacOS.

**Comment by MichaelEischer** [comment]
> Such filenames/link targets are valid, since Linux's native filesystems are encoding-agnostic. As far as the kernel is concerned, filenames are binary strings, their interpretation up to user-level programs.

Sure. But nowadays I'd expect most linux systems to either use utf-8 or plain ascii. Otherwise there should be several encoding related issue in the bugtracker (at least that would be my expectation).
