### ISSUE TITLE
VSS constantly fails on Windows 10

### ISSUE THREAD

**Issue by Hoffenbar** [restic/restic#3269]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on windows/amd64

How did you run restic exactly?
-------------------------------
restic -r t:/backups/restic --verbose backup --use-fs-snapshot c:\Users\matthiasu\usr\pgm

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Filesystem on a locally attached USB Drive

Expected behavior
-----------------
VSS snapshot should be created normally

Actual behavior
---------------
error: failed to create snapshot for [c:\]: VSS error: async operation pending

Steps to reproduce the behavior
-------------------------------
Retry the backup command

Do you have any idea what may have caused this?
-----------------------------------------------
Actually no idea. The same does work on Windows Server 2016 without problems.
vssadmin list volumes shows no problems, I think:
```
PS C:\Users\matthiasu\usr\bin\pwsh> vssadmin list volumes
vssadmin 1.1 - Verwaltungsbefehlszeilenprogramm des Volumeschattenkopie-Dienstes
(C) Copyright 2001-2013 Microsoft Corp.

Volumepfad: C:\
    Volumename: \\?\Volume{a27b9cf1-f3e2-4640-98ad-a265abc11124}\
...
```

Do you have an idea how to solve the issue?
-------------------------------------------
No. I don't know whats wrong with (just my?) VSS. Googling the error gives numerous hits. Maybe it''s just like with many other Microsoft Features: Sometimes they work, sometimes they don't work...

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I'm still in the phase of testing, comparing with other tools :-)

Until now I feel that the commandline of restic and the whole tool is a little easier to master then kopia. What both of them make great is the single-executable approach. Sometime, a UI is helpfull, though, and there kopia and duplicati are shining :-) I will do further testing until I can decide which tool survives...

**Comment by DRON-666** [comment]
You can try [this PR](https://github.com/restic/restic/pull/3067). Specifically `-o vss.timeout` option.

**Comment by Hoffenbar** [comment]
I was not aware of such an option.
Just tried with `-option vss.timeout=240`, but the same error occurs. Since the backup continues anyway, I pressed Ctrl+Break. Tried again with `vss.timeout=480`, but the previous break probably damaged something. And then, a new error occurs:
```
PS C:\Users\matthiasu\usr\bin\pwsh> restic -r t:/backups/restic --verbose backup --use-fs-snapshot --option vss.timeout=480 c:\Users\matthiasu\usr\pgm
open repository
enter password for repository:
repository 5f8465d4 opened successfully, password is correct
lock repository
load index files
using parent snapshot 70d0c6c5
start scan on [c:\Users\matthiasu\usr\pgm]
start backup on [c:\Users\matthiasu\usr\pgm]
creating VSS snapshot for [c:\]
error: tree 0000000000000000000000000000000000000000000000000000000000000000 is not known; the repository could be damaged, run `rebuild-index` to try to repair it
error: failed to create snapshot for [c:\]: VSS error: StartSnapshotSet() failed: VSS_E_SNAPSHOT_SET_IN_PROGRESS (0x80042316)

signal interrupt received, cleaning up
PS C:\Users\matthiasu\usr\bin\pwsh>
```

**Comment by DRON-666** [comment]
VSS_E_SNAPSHOT_SET_IN_PROGRESS will be report if an old VSS shadow copy creation has not been completely terminated.
Unfortunately, I do not know what the `tree ... is not known` error mean, but during testing, I interrupted restic many times without damaging the repository.

**Comment by Hoffenbar** [comment]
Just tried another time, without any commands in between the last one reported above:
```
PS C:\Users\matthiasu\usr\bin\pwsh> restic -r t:/backups/restic --verbose backup --use-fs-snapshot --option vss.timeout=480 c:\Users\matthiasu\usr\pgm
open repository
enter password for repository:
wrong password or no key found. Try again
enter password for repository:
wrong password or no key found. Try again
enter password for repository:
repository 5f8465d4 opened successfully, password is correct
lock repository
load index files
Error loading snapshot e0508416: load <snapshot/e0508416f6>: invalid data returned
github.com/restic/restic/internal/restic.FindLatestSnapshot.func1
        /restic/internal/restic/snapshot_find.go:39
github.com/restic/restic/internal/repository.(*Repository).List.func1
        /restic/internal/repository/repository.go:666
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1.1
        /restic/internal/backend/backend_retry.go:133
github.com/restic/restic/internal/backend/local.(*Local).List.func1
        /restic/internal/backend/local/local.go:262
path/filepath.walk
        /usr/local/go/src/path/filepath/path.go:360
path/filepath.walk
        /usr/local/go/src/path/filepath/path.go:384
path/filepath.Walk
        /usr/local/go/src/path/filepath/path.go:406
github.com/restic/restic/internal/fs.Walk
        /restic/internal/fs/file.go:99
github.com/restic/restic/internal/backend/local.(*Local).List
        /restic/internal/backend/local/local.go:233
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1
        /restic/internal/backend/backend_retry.go:127
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
        /home/build/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.0.2/retry.go:52
github.com/cenkalti/backoff/v4.RetryNotify
        /home/build/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.0.2/retry.go:31
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        /restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).List
        /restic/internal/backend/backend_retry.go:126
github.com/restic/restic/internal/repository.(*Repository).List
        /restic/internal/repository/repository.go:660
github.com/restic/restic/internal/restic.FindLatestSnapshot
        /restic/internal/restic/snapshot_find.go:36
main.findParentSnapshot
        /restic/cmd/restic/cmd_backup.go:412
main.runBackup
        /restic/cmd/restic/cmd_backup.go:530
main.glob..func2
        /restic/cmd/restic/cmd_backup.go:71
github.com/spf13/cobra.(*Command).execute
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /restic/cmd/restic/main.go:98
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
PS C:\Users\matthiasu\usr\bin\pwsh>
```

**Comment by Hoffenbar** [comment]
Deleted a 0 byte file in the snapshots subdir. The did not help. Seems that everything is corrupted. Something that in no circumstance should happen....

**Comment by rawtaz** [comment]
> Something that in no circumstance should happen....

As long as computers and software running on computers are involved, there's no way you will never see anything like corruption. Restic does a lot of things to avoid it and handle it when it happens, regardless of root cause, and I encourage you to not jump to any conclusions until it's been investigated as much as is possible. It would probably be a good idea not to do much more with the repo at this point, as further changes or actions may make it harder to investigate.

**Comment by Hoffenbar** [comment]
You are right. In this case, as I'm only testing, it's not a big thing, but nevertheless it`s interesting to know, why that interrupt leads to such a situatuion :-)

**Comment by rawtaz** [comment]
I agree, and I'm surprised. Because restic is in general very resilient to cutoffs etc, when you back up it only *adds* stuff to your repo, so it shouldn't break any of what was previously added. But as experience has shown, there's often a lot of external factors that can intervene, and most of the corruption that has been found through the years have been to external factors (hardware or other problems in whatever services are used). Anyway, it needs to be looked at for anyone to have a clue.

**Comment by DRON-666** [comment]
What will `restic cat snapshot e0508416f6` print?

**Comment by Hoffenbar** [comment]
```
C:\WINDOWS\system32>restic -r t:/backups/restic cat snapshot e0508416f6
repository 5f8465d4 opened successfully, password is correct
Fatal: could not find snapshot: no matching ID found


C:\WINDOWS\system32>restic -r t:/backups/restic snapshots
repository 5f8465d4 opened successfully, password is correct
ID        Time                 Host             Tags        Paths
--------------------------------------------------------------------------------------
22d5d4c1  2021-02-01 18:23:03  DESKTOP-AI70A0O              c:\Users\matthiasu\usr\pgm
50b39f4a  2021-02-04 19:11:57  DESKTOP-AI70A0O              c:\Users\matthiasu\usr\pgm
0a3bc606  2021-02-04 21:58:43  DESKTOP-AI70A0O              c:\Users\matthiasu\usr\pgm
ab52bdee  2021-02-06 12:55:00  DESKTOP-AI70A0O              C:\Users\matthiasu\usr\pgm
d6963d29  2021-02-07 10:41:09  DESKTOP-AI70A0O              c:\Users\matthiasu\usr\pgm
70d0c6c5  2021-02-07 11:45:13  DESKTOP-AI70A0O              c:\Users\matthiasu\usr\pgm
--------------------------------------------------------------------------------------
```

**Comment by MichaelEischer** [comment]
@Hoffenbar The null snapshot is issue #3151. The only broken thing here is the snapshot. Just delete the file whose name starts with `e0508416f6` in the `snapshot/`.

**Comment by DRON-666** [comment]
@MichaelEischer #3067 (vss-options) was rebased after #3164 (fixes #3151) and I think @Hoffenbar already remove snapshot e0508416f6:
>Deleted a 0 byte file in the snapshots subdir. The did not help.

**Comment by DRON-666** [comment]
@Hoffenbar what version of restic you really use? Execute `restic version` command. I'm starting to think that you don't use #3067 version, but blindly run `0.11.0` with `--option vss.timeout`.

**Comment by MichaelEischer** [comment]
>  already remove snapshot e0508416f6:
> 
> > Deleted a 0 byte file in the snapshots subdir. The did not help.

The 0 byte file must be a different one. restic only complains about a null tree id, if there is a snapshot which contains such an id. And that means that the corresponding snapshot file cannot be empty.

**Comment by Hoffenbar** [comment]
```
C:\WINDOWS\system32>restic version
restic 0.11.0 compiled with go1.15.3 on windows/amd64
```

**Comment by Hoffenbar** [comment]
I`ve made new snapshots without using VSS. Then use `rebuild-index` again. This works ok, but the error message still apears:
```
error for tree [null]:
  id 0000000000000000000000000000000000000000000000000000000000000000 not found in repository
Fatal: repository contains errors
```

**Comment by MichaelEischer** [comment]
I've just noticed that the backup run which complained about the null tree, has used the snapshot `70d0c6c5`. @Hoffenbar what does `restic cat snapshot 70d0c6c5` print? You'll probably have to remove that snapshot.

**Comment by Hoffenbar** [comment]
```json
C:\WINDOWS\system32>restic -r t:/backups/restic cat snapshot 70d0c6c5
repository 5f8465d4 opened successfully, password is correct
{
  "time": "2021-02-07T11:45:13.8054149+01:00",
  "parent": "d6963d295dc42d993256c5ad50d393f0750b102bd49bb62fa2340551a39f3bac",
  "tree": "0000000000000000000000000000000000000000000000000000000000000000",
  "paths": [
    "c:\\Users\\matthiasu\\usr\\pgm"
  ],
  "hostname": "DESKTOP-AI70A0O",
  "username": "DESKTOP-AI70A0O\\matthiasu"
}
```

**Comment by MichaelEischer** [comment]
@Hoffenbar Please remove snapshot `70d0c6c5` if you haven't done so already. That should fix the null tree id error.

**Comment by DRON-666** [comment]
>C:\WINDOWS\system32>restic version
>restic 0.11.0 compiled with go1.15.3 on windows/amd64

@Hoffenbar This is why the timeout option didn't work for you: it's not supported in restic 0.11.0.

@MichaelEischer I think this is a bug, restic should not silently ignore unknown options, but print some warning.

**Comment by Hoffenbar** [comment]
Thank you all! I've done a `snapshotm forget ....`, and the message is gone.
