### ISSUE TITLE
Enhance functionality of the `ls` command

### ISSUE THREAD

**Issue by fd0** [restic/restic#327]
In #326 @saschalalala mentioned that the `ls` command does not behave as a normal, unix-style `ls`. This issue should be used to discuss enhancements to `ls`.

**Comment by saschalalala** [comment]
Well, in my opinion, `restic ls` should only display the path that one specifies, that means `restic -r backup ls <snapshot-id>` should display the root directory of the backup. In order to list files of directorys one had to specify this directory, e.g. `restic -r backup ls <snapshot-id> path/to/directory`. It should, imho, show them in a listed order, similar to the last column of `ls -l` in Linux and also show hidden files. Just for convenience.

**Comment by fd0** [comment]
Ok, I think we agree that this is a good idea.

**Comment by fwilhe** [comment]
I have two thoughts about this:

* If `restic -r backup ls <snapshot-id>` only shows the top level, I think a `recursive` command should be added, like in GNU ls.
* I think `restic -r backup ls` should be an alias for `restic -r backup ls latest`. This would in my opinion be more aligned with how the ls command works.

**Comment by fd0** [comment]
Good points. If you'd like to work on this and need help, please let me know. Otherwise start hacking, open a PR and then we can discuss your code!

**Comment by fwilhe** [comment]
Yes, I'll have a look at it.

**Comment by middelink** [comment]
Keep in mind this breaks backwards compatibility and also `restic ls` allows listing multiple snapshots.

While I have no problem with making `latest` the default snapshot, I think we should be consequent and do the same for all other restic cmds. In fact, if we're going to drop backwards compatibility, moving it from a positional argument to an (multi)flag would be nice as it frees up the args for cmd specific arguments.

I'm also not sure this recurse flag is a good thing. As fd0@ often quotes `tar` as his role model backup program, `tar` does not use a `-R` to recursively list files. Guess we need to make up our minds which gnutool to emulate ^^

**Comment by fwilhe** [comment]
Yes, I fully agree. My commits are currently not meant to be a solution for this issue, my goal is to explore what can be done. I think if the command's name is `ls`, then it should behave like I would expect `ls` to behave. I'm aware that this breaks backwards compatibility, but I think as long as version 1.0 is not released this is ok to do in a minor version. Maybe it would be best to line out how the cli should work first with some examples.

**Comment by fd0** [comment]
You raised some interesting points. From my point of view we can modify the `ls` command, I don't think many people use it.

**Comment by sgeisbacher** [comment]
what is the state here? i would like to help on that, if wanted. 
i like the idea but imho would love to keep the old style (listing the whole tree) too, as i often use it with grep to check if a file is part of that snapshot

**Comment by fd0** [comment]
Ah, there has been some work on `ls` in the last couple of releases:
 * We limited it to one snapshot #1941 
 * You can pass an optional path name, in which case restic will only list that path (#1941)
 * We added `--recursive` which will list the given path recursively (#1941)
 * By default, the complete snapshot is listed recursively if no path is given (for backwards compatibility)

**Comment by fd0** [comment]
Actually, I think all the things we discussed for enhancing `ls` have already been implemented. Is there anything else, or can we close this issue?

**Comment by sgeisbacher** [comment]
ah ok, nice. so imho there is nothing left here. i guess you could close it 🤔

**Comment by fd0** [comment]
Cool, I'm going to close this issue for now, please feel free to add further comments. Thanks!
