### ISSUE TITLE
Prune fails: data blobs seem to be missing

### ISSUE THREAD

**Issue by cmeyer23** [restic/restic#3271]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

How did you run restic exactly?
-------------------------------
The following is run daily by cron as root:
```
export B2_ACCOUNT_ID=...
export B2_ACCOUNT_KEY=...
export RESTIC_REPOSITORY="..."
export RESTIC_PASSWORD_FILE="password.txt"
restic backup --verbose --one-file-system --tag backup_daily --exclude-caches SOURCEDIR1
restic backup --verbose --one-file-system --tag backup_daily --exclude-caches SOURCEDIR2
restic backup --verbose --one-file-system --tag backup_daily --exclude-caches SOURCEDIR3
restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 3
```
Once a month, the backup is followed by prune and check:
```
export B2_ACCOUNT_ID=...
export B2_ACCOUNT_KEY=...
export RESTIC_REPOSITORY="..."
export RESTIC_PASSWORD_FILE="password.txt"
restic backup --verbose --one-file-system --tag backup_daily --exclude-caches SOURCEDIR1
restic backup --verbose --one-file-system --tag backup_daily --exclude-caches SOURCEDIR2
restic backup --verbose --one-file-system --tag backup_daily --exclude-caches SOURCEDIR3
restic forget --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 3
restic prune
restic check
```
I updated from 0.10.0 to 0.11.0 on January 31, 2021 . "restic backup" and "restic forget" ran completely without error on Jan 31, Feb 1, Feb 2, Feb 3, Feb 4, and then "restic prune" failed on Feb 5.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
'Restic prune' (version 0.10.0) completed without error on Jan 5, 2021 with the following output:
```
counting files in repo
building new index for repo
[7:29:36] 100.00%  244811 / 244811 packs

repository contains 244811 packs (3197228 blobs) with 1.128 TiB
processed 3197228 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 131 snapshots
[2:48] 100.00%  131 / 131 snapshots

found 3041292 of 3197228 data blobs still in use, removing 155936 blobs
will remove 0 invalid files
will delete 2647 packs and rewrite 2306 packs, this frees 15.754 GiB
[1:18:58] 100.00%  2306 / 2306 packs rewritten

counting files in repo
[7:38:03] 100.00%  240982 / 240982 packs

finding old index files
saved new indexes as [f2fb3449 50003987 4f296fe6 1e61f969 178783ba 424756fa 986d424d acd3e66f b499e14a 445dd7ae c5efe312 2b2e275f e554348f b3024223 17a111da ec57262a d236652a 41956495 d7df1745 676820d0 35c1099d 2b8e2f42 6427e23a fd0bca5b d4781b88 c9d4fd0e 2b327131 7c5664fb e1ca9c91 79210a30 09efcf54 6f7d7b60 459e0e5d f0dc71b1 8de553ca 1216b390 64963ea7 f7e1ff72 c7878d04 d78d94de 468827fa 75918435 74304d0e e6c499b6 f483b030 4660ec69 1d692570 2189a9bd bf31f0f4 5dd2bd18 49841953 938d6859 8ad0dd0e 12ba4565 f3b51da9 6cb4952d 463e90c6 3d039e41 286eab5b 2604ac0b c035f1ed 4a2d5ca7 442ad198 93cacb8a 6491f942 dc564a1d f5c7e948 48df8517 ba4aa7b4 f92d704c d832a476 39b4a733 efaeaf8d 46b943dd 267d2d5d 2360ec95 ceb42b55 f53b1ddc cd019454 3ab3f606 5c3dfbfb]
remove 210 old index files
[0:28] 100.00%  210 / 210 files deleted

remove 4953 old packs
[9:24] 100.00%  4953 / 4953 files deleted

done

```
Actual behavior
---------------
'Restic prune' (version 0.11.0) failed on February 5, 2021 with the following error:

```
counting files in repo
building new index for repo
[9:00:05] 100.00%  257271 / 257271 packs

incomplete pack file (will be removed): 04c1a0befa9aad7832ceed06cf08a1f59dca0368477a9e2cda627775e84a5806
incomplete pack file (will be removed): af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5
repository contains 257269 packs (3535261 blobs) with 1.181 TiB
processed 3535261 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 135 snapshots
[2:53] 100.00%  135 / 135 snapshots

Fatal: [<data/2ba7afa1> <data/d4a90b18> <data/ce8760e0> <data/8afd5294> <data/dcfe3324> <data/12a2346f> <data/96e7b557>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose

```

Steps to reproduce the behavior
-------------------------------
I have not attempted to re-run the prune command.

Do you have any idea what may have caused this?
-----------------------------------------------
The only thing that has changed was the upgrade from 0.10.0 to 0.11.0. I have logged the output from all restic commands going back to 2018 and could find no reference to the missing data blob identifiers that were listed. I could not find any prior instances of the "incomplete pack file (will be removed)" notification either.

Do you have an idea how to solve the issue?
-------------------------------------------
No, I have no clue what to do.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I hope that restic is helping me every day as I trust it for conducting my offsite backup.

**Comment by adworacz** [comment]
This sounds like my issue: https://github.com/restic/restic/issues/3266

**Comment by cmeyer23** [comment]
> This sounds like my issue: #3266

Yes I saw your issue and thought about just posting there, but I wasn’t sure if that might just confuse the issue. There were some differences here: I thought your issue might be related to lock files and your subsequent backup reported errors. I have not encountered any lock file problems and all subsequent backups have been completing without any reported errors.

Have you made any progress with your issue? I admit I am not wholly familiar with the inner workings of restic, so I don’t know where to start in looking for missing or corrupted index files or data blobs. I also don’t exactly know how best to ensure that my backup is sane (without having to download the whole thing).

**Comment by cmeyer23** [comment]
Following advice of @MichaelEischer posted in #3266 :
`restic check` ... no errors were found
`restic check --with-cache` ... no errors were found

**Checking SHA256 checksums on one "incomplete pack file" reported by the failed `restic prune`**
```
restic cat --quiet --no-cache pack 04c1a0befa9aad7832ceed06cf08a1f59dca0368477a9e2cda627775e84a5806 | shasum -a256
04c1a0befa9aad7832ceed06cf08a1f59dca0368477a9e2cda627775e84a5806  -

restic cat --quiet pack 04c1a0befa9aad7832ceed06cf08a1f59dca0368477a9e2cda627775e84a5806 | shasum -a256
04c1a0befa9aad7832ceed06cf08a1f59dca0368477a9e2cda627775e84a5806  -
```

Metadata from Backblaze web UI:
```
Name: data/04/04c1a0befa9aad7832ceed06cf08a1f59dca0368477a9e2cda627775e84a5806
Size: 4.9 MB
Sha1: 6cc5d16b3767b10a30822dac61be20013568a3c7
```

Comparing sha1 just for kicks:
```
restic cat --quiet --no-cache pack 04c1a0befa9aad7832ceed06cf08a1f59dca0368477a9e2cda627775e84a5806 | shasum -a1
6cc5d16b3767b10a30822dac61be20013568a3c7  -
restic cat --quiet pack 04c1a0befa9aad7832ceed06cf08a1f59dca0368477a9e2cda627775e84a5806 | shasum -a1
6cc5d16b3767b10a30822dac61be20013568a3c7  -
```
Everything seems to check out for that pack file.

**Trying the other reported "incomplete pack file"**
```
restic cat --quiet --no-cache pack af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5 | shasum -a256
Warning: hash of data does not match ID, want
  af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5
got:
  1cf001b2b290ea7d26dbdc087a0c9b6f7c14d2b172c2573ef334eca2ca63f477
1cf001b2b290ea7d26dbdc087a0c9b6f7c14d2b172c2573ef334eca2ca63f477  -

restic cat --quiet pack af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5 | shasum -a256
af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5  -
```
OK, so the repo pack file seems corrupted, but does this mean there's a good copy in the cache? I looked in `.cache/restic/....../data/af/` but could not find a local copy of the file.

Metadata from Backblaze web UI:
```
Name: data/af/af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5
Size: 4.6 MB
Uploaded: 11/04/2019 03:50
Sha1: 42f33026f8633a68c3ed6f76670cab96297e6b53
```

and comparing sha1 again for kicks:
```
restic cat --quiet pack af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5 | shasum -a1
42f33026f8633a68c3ed6f76670cab96297e6b53  -
restic cat --quiet --no-cache pack af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5 | shasum -a1
42f33026f8633a68c3ed6f76670cab96297e6b53  -
```
I tried sha256 again (twice actually), with the `--no-cache` option:
```
restic cat --quiet --no-cache pack af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5 | shasum -a256
af69cc3f1d40599d1648ba2ea3001453240336a73d16146f261430e21156f0e5  -
```

**Did the pack file fix itself?** When I downloaded it for the first check or maybe when I browsed to it on the web interface? At this point I'm not really sure what is going on.

I then ran `restic find --blob 2ba7afa1 d4a90b18 ce8760e0 8afd5294 12a2346f 96e7b557` on the blobs that were reported not found in the index. It looks like the blobs are associated with two image files (sizes 8.6MB and 8.7MB), both with file modification dates of 11/02/2019 (which makes sense because the Backblaze web UI reports uploaded date of 11/04/2019). These files are in many snapshots.

**Comment by MichaelEischer** [comment]
Thanks for digging into this. 

> OK, so the repo pack file seems corrupted, but does this mean there's a good copy in the cache? I looked in .cache/restic/....../data/af/ but could not find a local copy of the file.

That pack file probably just contains data blobs and no directory metadata in which case it won't be cached. That would essentially mean that `restic cat --quiet pack af69cc3f1[...]` got lucky this time and got the correct data while downloading the file from B2.
 
> Did the pack file fix itself? When I downloaded it for the first check or maybe when I browsed to it on the web interface? At this point I'm not really sure what is going on.

It is starting to look like this problem is caused by B2 itself. At least it's very suspicious to have multiple prune issues (#3266, #3268, #3271 and #3272) with the same strange symptoms to show up at the same time. Depending on where the root cause for the corrupted pack files is located, it is quite possible that either some error correction mechanism kicked in or some faulty hardware was replaced. Or that the error just didn't show up this time.

**Comment by cmeyer23** [comment]
It seems pretty clear to me that B2 was/is serving corrupted data pack files. This makes me think I should run `restic check --read-data` to ensure consistency of all the other pack files, which I have not done previously. What I don't understand though is what `restic prune` was doing that caused it to find these corrupted pack files. I hope someone can help check my understanding of what likely happened and how I should move forward.
- Did `prune` report these pack files as incomplete because the checksums did not check out?
- Does `prune` check all pack files for checksum consistency?
- Did `prune` report missing blobs because the pack files containing those blobs were ignored for inconsistency?
- Aside from `restic check --read-data`, are there any other actions to take? `rebuild-index`?

**Comment by MichaelEischer** [comment]
> * Did `prune` report these pack files as incomplete because the checksums did not check out?

The initial reindexing step during prune only reads the header part of each pack file. A corrupted size field there should also be enough to trigger the "incomplete pack file" warning. That is each prune run would have noticed when any of the pack headers breaks. So the corrupted downloads must have started sometime after the last successful prune run.

> * Does `prune` check all pack files for checksum consistency?

The initial reindexing reads the header parts of each files and check that for integrity. Later during the repack step restic also fully verifies every piece of data before moving data to new pack files.

> * Did `prune` report missing blobs because the pack files containing those blobs were ignored for inconsistency?

restic couldn't read the header of some of the pack files and thus didn't know which blobs are contained in these. This failed the integrity check which makes sure that all necessary blobs were found before proceeding further. This for example also ensure that restic doesn't (accidentally) deletes pack files which are temporarily unreadable.

> * Aside from `restic check --read-data`, are there any other actions to take? `rebuild-index`?

If `check` returns missing blobs/trees then you have to rebuild the index. With a beta build of restic the latter should complete within a few minutes. 

> What is still not clear to me is this: does restic prune check the checksum on all pack files?

`prune` only fully checks pack files which are repacked. For all others it only reads the pack files header (this last part will be removed after restic 0.11.0). 

>  By repeatedly requesting downloads of these files, the backblaze server is finding these errors and correcting them.

As B2 is a data storage system I'd expect it to run periodic (every few weeks(?)) data integrity checks and to repair damaged files. So these broken downloads should fix themselves eventually.

**Comment by cmeyer23** [comment]
Thanks

**Comment by kmwoley** [comment]
This is exactly the behavior I'm seeing in #3268 - I'm glad I'm not going crazy. But that's insane that Backblaze is having this type of issue.

**Comment by cmeyer23** [comment]
> This is exactly the behavior I'm seeing in #3268 - I'm glad I'm not going crazy. But that's insane that Backblaze is having this type of issue.

@kmwoley I agree, it concerns me that all these data files are coming back corrupt for multiple users and that it’s different files each time. I would also think that Backblaze would error check the file before serving it. It certainly makes me question the integrity of their system.
