### ISSUE TITLE
A secure method of storing cloud access, all passwords and global env vars without a config or any other file(s).  

### ISSUE THREAD

**Issue by jjim-01** [restic/restic#3276]
Output of `restic version`
--------------------------
Not Applicable

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
The ability to add/delete/change information contained in current global environment variables within restic itself 

There have been requests for a configuration file this would replace a config file and some people have different views on what they should be.  A configuration file should only be for the global environment variables, that are static, it should NEVER contain any backup or other information that changes.  Putting backup job information into a configuration file would mean repeatedly changing it.  This is not the job of any application configuration file.  This removes the idea of having a config file and other security access from any file or script. 

From what I've read so far a lot of effort has been put into restic security this could be easily defeated by hard-coding security access information into any file.   Using directory file permissions to securely lock down any file is easily defeated by somebody that has access to a backup app.  Often it is trivial to back up a file in a secure location, recover it to an insecure location/server.   

My thoughts would be not to have any permanent configuration file for security reasons, but rather store the information within restic and rely upon restic encryption and security.  Suggest:
1. Create a simple configuration file with each global env var setting on a single line something like
        :   
    B2_ACCOUNT_KEY=
    AZURE_ACCOUNT_NAME=
       :
   Each var doesn’t have to set, much like most app config files.  
2. restic to ingest the file into the repository and use that as the source for global environment variables.
3. Manually remove the simple config file contents added to restic

- Restic to have the ability dump what it read in, to a file of same format.  That could be checked, edited and ingested again if required. If nothing set it would dump a template. Passwords to be excluded from dump
- Any var not set would have to ever entered manually e.g. repository password. 
- Any global environment variables programmatically set by a script or manually would have precedence over what was ingested from the temporary configuration file. 

What are you trying to do? What problem would this solve?
---------------------------------------------------------
1. Remove the requirement to have hard-coded passwords and IDs etc in any scripts or files anywhere on the system.
2. Restic would remain a self contained app with no dependencies
3. It would make automation a lot simpler. No longer have to keep repeatedly setting the env vars within scripts and automation tools.  
4. Flexibility retained by having env vars precedence over internal settings.     
5. It makes things simpler for novice users to understand and use.  Reduces the learning curve for automation and scripting, even experienced people occasionally forget to set up the environment with cron jobs and the like.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Been testing it as a win10 standalone app running from external USB HDD containing repositories. Using it for home laptops and media server....when done,  a howto story for the forum.   The forum doesn't have much for the windows and good stuff novice users.

**Comment by MichaelEischer** [comment]
I have to admit that I haven't fully understood which problem exactly you are trying to solve. Wouldn't a simple wrapper script which sets the appropriate environment variable solve this? That would also avoid adding complexity to restic.

>  A configuration file should only be for the global environment variables, that are static, it should NEVER contain any backup or other information that changes.

Are you referring to any specific part of the discussion in #16? How is your suggestion different from a config file which e.g. only contains the repository configuration?

> From what I've read so far a lot of effort has been put into restic security this could be easily defeated by hard-coding security access information into any file. Using directory file permissions to securely lock down any file is easily defeated by somebody that has access to a backup app. Often it is trivial to back up a file in a secure location, recover it to an insecure location/server.

An attacker would need access to the password used to encrypt the backup repository. And if both the backup app and the password are only accessible for the root user, then an attacker which can access the password would also have complete access to the host in question?

> 2. restic to ingest the file into the repository and use that as the source for global environment variables.

This is a cyclic dependency. restic needs all environment variables before it can access the repository. Thus it can't read any variables from the repository.

**Comment by jjim-01** [comment]
The problem I see is security inconsistency.  Being forced to hard code passwords into wrappers, scripts and the like is not good security policy or design, it should be avoided where possible.    Size of the backup application, environment and site implementation should not determine the importance of security.

The location of the repository can still be done by an environment var or the --repository-file , -r flags 

_Correction:_ I updated and removed the idea of dumping passwords. 
Some admin and storage people do not like sharing their passwords with those that do backups.  Gives them the ability to add passwords without being retrieved by backup people. 

From my experience an “attacker” can be somebody in your own team or an APT (an opportunist threat hiding on your systems).  Commercially, backup/recovery systems are now a common target of cyberattacks because they can be used to cause damage and often destroyed first to prevent recovery.

**Comment by MichaelEischer** [comment]
> Being forced to hard code passwords into wrappers, scripts and the like is not good security policy or design, it should be avoided where possible. Size of the backup application, environment and site implementation should not determine the importance of security.

There's nothing stopping a wrapper script from loading the password from somewhere. You can even use the `--password-command <cmd>` flag to let restic retrieve a password on demand.

> Some admin and storage people do not like sharing their passwords with those that do backups. Gives them the ability to add passwords without being retrieved by backup people.

The restic backup process needs access to the repository password and credentials to access the storage. That is whoever controls the execution of the backup process will in some way or another be able to access the password. This is even true when restic would act as a password manager (that's my understanding of your proposal) to retrieve the symmetric encryption password for the repository. The _only_ way around that is asymmetric encryption. That feature request is tracked in issue #187.

I still don't understand at all how is should be possible to securely load passwords/credentials from somewhere, such that an attacker wouldn't be able to do the same. Loading the repository password from the repository just can't work.

> Commercially, backup/recovery systems are now a common target of cyberattacks because they can be used to cause damage and often destroyed first to prevent recovery.

That is a different problem than what you have been asking for so far. To prevent an attacker from damaging a backup you need some sort of append-only backup (which is already supported by e.g. the rest-server of restic) . Just obscuring access to passwords won't help. There's also some discussion on that point in #187.

**Comment by MichaelEischer** [comment]
I'm closing this issue as with the current symmetric crypto it is always necessary to provide restic with a password via some external means. Asymmetric encryption is already discussed in #187.
