### ISSUE TITLE
Restic question

### ISSUE THREAD

**Issue by hhradice** [restic/restic#3277]
Is there a way to automatically exclude files or directories such as a directory named cache or files ending with .tmp like some of the other backup programs?

**Comment by fd0** [comment]
Yes, there is. Please read the documentation at https://restic.readthedocs.io/en/stable/040_backup.html#excluding-files. For further questions, please use the forum at https://forum.restic.net. We're using the GitHub issue tracker exclusively for bugs and feature requests. Thanks!
