### ISSUE TITLE
restic diff single snapshot

### ISSUE THREAD

**Issue by cameronbraid** [restic/restic#3292]
I can diff two snapshots to find out what changes there were.  I would like to be able to get that information for the first snapshot, compared to an empty repo.  Then I thought this would also make sense for any single snapshot - giving you effectively the stats of what a restore of that snapshot would be.

**Comment by dimejo** [comment]
> I would like to be able to get that information for the first snapshot, compared to an empty repo.

You can use `restic ls latest` (or `restic ls --long latest`) to show all files of the latest snapshot (the first snapshot in your case).

> Then I thought this would also make sense for any single snapshot - giving you effectively the stats of what a restore of that snapshot would be.

You can use `restic stats SNAPSHOTID` to show stats about a specific snapshot. The stats command can display different counting modes when using the `--mode` flag. Please use `restic stats --help` for more information.


PS: Please use the [forum](https://forum.restic.net/) for questions about usage and the like.

**Comment by cameronbraid** [comment]
ok, thanks for the info, and will use the forum
