### ISSUE TITLE
Improve messaging from "restic check --check-unused" after forget and prune with --max-unused > 0

### ISSUE THREAD

**Issue by underhillian** [restic/restic#3295]
Output of `restic version`
--------------------------

restic 0.12.0 compiled with go1.15.8 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Running "restic check --check-unused" after successfully completing a forget --prune operation using the new (>= 0.12.0) prune version with a non-zero --max-unused value can produce thousands of "unused blob <data/xxxxxxxx>" messages followed by "Fatal: repository contains errors" even though the repository is perfectly healthy.

Apart from filling the log with unnecessary information, the casual user could easily interpret these messages as indicating a problem with the repo when in fact none exists. 

Some possible ways to address this (none of them great; hopefully others will have better ideas) include:

--have restic track which blobs are intentionally unused (i.e. exist as a consequence of a successful forget and prune) and suppress the --check-unused messages (especially any "Fatal" message) attributable to these blobs.

--put an explanation in the documentation of the "--check-unused" option alerting the user of the potential for these messages and appropriate interpretation

--phase out/deprecate the --check-unused flag to restic clean.  With the new default prune behavior, the value of this check may not be what it used to be.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Avoid user confusion associated by with seeing many unexpected messages and the word "Fatal" in restic check output when in fact no issue exists.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is great!  And the speed improvement with the "new prune" is amazing...many thanks!

**Comment by aawsome** [comment]
> --have restic track which blobs are intentionally unused (i.e. exist as a consequence of a successful forget and prune) and suppress the --check-unused messages (especially any "Fatal" message) attributable to these blobs.

This is only possible with changing the repo format, see also #628 for discussion on that topic in general.

> --phase out/deprecate the --check-unused flag to restic clean. With the new default prune behavior, the value of this check may not be what it used to be.

I agree. There are some tests which still use that flag (e.g. to test the `--max-unused=0` case)..

> --put an explanation in the documentation of the "--check-unused" option alerting the user of the potential for these messages and appropriate interpretation

I would vote for this. Are you willing to work on a PR to change this?

**Comment by MichaelEischer** [comment]
> --put an explanation in the documentation of the "--check-unused" option alerting the user of the potential for these messages and appropriate interpretation

In which case would that option convey useful information to users?

Just keeping that option usable as it is used in tests, but telling everyone to ignore its output sounds rather useless to me. In that case I'd rather deprecate the CLI option and only allow  the test case to actually use it.

**Comment by underhillian** [comment]
Well, running `restic check --check-unused` (after running `restic --forget --prune --max-unused=0`) will provide exactly the same information today as it did for a similar check under restic <0.12.0.  So if it was a useful thing to do for restic <0.12.0, it is presumably still useful today.

I agree that it is fair to ask if this information is (or ever was) sufficiently useful to justify including what has now become a potentially confusing option where is is available for everyday use.  Speaking for myself (as a reasonably knowledgeable but certainly non-expert user) I'd say "no"--which is why I made the suggestion to deprecate in the first place.  That would still be my preferred approach, but I' suggested updating the documentation as an alternative in case I'm missing something.

**Comment by MichaelEischer** [comment]
I don't think "--check-unused" was ever much use (for normal users), except maybe if one wants to know whether prune removes all unused blobs. But in that case one can now use `prune --dry-run`. It's probably most interesting as an internal sanity check for testing prune, but not something users should use. We just have to hope that nobody counts the number of unused blobs reported in check to decide whether to prune a repository or not ;-) .

I'd also prefer to just deprecate the option and just silently ignore it.

A quick search through the github issues and the forum hint at a high correlation between confused users and the use of `--check-unused`. Although that could also be biased as there are only few references to that option.
