### ISSUE TITLE
Make `restic diff` use last 2 snapshots by default

### ISSUE THREAD

**Issue by jniggemann** [restic/restic#3297]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/386

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

IMHO a lot of people use `restic diff` to compare the 2 latest snapshots. Not having to specify those explcitly makes life for those people easier. I don't know the code but I think it is most likely not difficult to implement. `restic diff` withoput any further parameters would then diff the two latest snapshots.

**Comment by aawsome** [comment]
IMO a duplicate of #1965

**Comment by jniggemann** [comment]
Oh, that's correct, thank you for pointing this out - closing this duplicate.
