### ISSUE TITLE
`check` and `rebuild-index` error with `fdopendir: not a directory`

### ISSUE THREAD

**Issue by rikchilvers** [restic/restic#3302]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.7 on darwin/amd64

How did you run restic exactly?
-------------------------------
❯ restic -r /Volumes/backup check
using temporary cache in /var/folders/8c/ydz8t7md7pz7gy6k4f3dlgww0000gn/T/restic-check-cache-127483548
repository d5249c9e opened successfully, password is correct
created new cache in /var/folders/8c/ydz8t7md7pz7gy6k4f3dlgww0000gn/T/restic-check-cache-127483548
create exclusive lock for repository
load indexes
check all packs
List(data) returned error, retrying after 552.330144ms: fdopendir: not a directory
List(data) returned error, retrying after 1.080381816s: fdopendir: not a directory
List(data) returned error, retrying after 1.31013006s: fdopendir: not a directory
List(data) returned error, retrying after 1.582392691s: fdopendir: not a directory
List(data) returned error, retrying after 2.340488664s: fdopendir: not a directory
List(data) returned error, retrying after 4.506218855s: fdopendir: not a directory
List(data) returned error, retrying after 3.221479586s: fdopendir: not a directory
List(data) returned error, retrying after 5.608623477s: fdopendir: not a directory
List(data) returned error, retrying after 7.649837917s: fdopendir: not a directory
List(data) returned error, retrying after 15.394871241s: fdopendir: not a directory
fdopendir: not a directory
pack a60f308d: does not exist
pack 2ba4128f: does not exist
pack 6bf9239d: does not exist
pack 7aa392f5: does not exist
.
.
.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
This happens on both external and internal SSDs formatted as APFS (macOS 11.2.1).

Expected behavior
-----------------
restic should be able to read all directories and check for errors in the backup.

Actual behavior
---------------
restic returns the above error. v0.11.0 does not return the error (tested on new repositories with a single snapshot and older repositories with many snapshots).

Running a backup, listing snapshots and restoring all work fine.

Steps to reproduce the behavior
-------------------------------
Run restic v0.12.0 (installed via homebrew) on macOS with an APFS formatted SSD.

Do you have any idea what may have caused this?
-----------------------------------------------
A change made between v0.11.0 and v0.12.0

Do you have an idea how to solve the issue?
-------------------------------------------
No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
restic is fantastic - thanks so much for all of your hard work! I'm happy to help track this bug down however I can.

**Comment by aawsome** [comment]
Thanks for reporting the bug. This is really weird. AFAIK there are only four commands that do a `List` on the `/data` dir: `check`, `rebuild-index`, `prune`, and `list packs`.

Can you please run `restic list packs`? (Should give the same error)
If there is the same error, can you please run `restic list index`, `restic list snapshots`, `restic list keys`, `restic list locks` to see if you get the same error? 

Can you try to find a minimal reproducable error setting? Some sequence of `restic init`, `restic check` (or maybe a `restic backup` in between)  that reproduces your error?

**Comment by kusalananda** [comment]
I'm chiming in with the same issue, using `restic 0.12.0 compiled with go1.15.7 on darwin/amd64` on macOS Catalina, with an HDD (spinning disk) that has an APFS on it.  This started with 0.12.0, but only after a few days. I'm running a prune every morning and that has been working well since I updated restic to 0.12.0 (at about Feb 15), but not this morning.

All directories are there, but I see
```
% restic -r /Volumes/Backup/backup list packs
611ced4155bd87584d33aa27a41a58d12478130b69c2f92aa9835b2f2139e539
61ef408f3659773397cb4674fb598540b46a12799dba0550525142533e6594ce
61ea8be4216e7c159c9ca21de5b643b28501eefcdd842f9ce2ee96f87c3495e3
61c4b083bf7f99273608fb126c7b1e295640b731f3d507127ed8033bd3eb84f0
[... many more ...]
330b9aa3dcceb73dbb4b6f38f61d7f2efcf1f60584013148f8dc9e6db9848a44
33bd8dd8a0e3eaf2f1efd2688c3fce0253bb781b4abd6a28d01f7797d9eb8f8b
List(data) returned error, retrying after 552.330144ms: fdopendir: not a directory
List(data) returned error, retrying after 1.080381816s: fdopendir: not a directory
List(data) returned error, retrying after 1.31013006s: fdopendir: not a directory
List(data) returned error, retrying after 1.582392691s: fdopendir: not a directory
List(data) returned error, retrying after 2.340488664s: fdopendir: not a directory
List(data) returned error, retrying after 4.506218855s: fdopendir: not a directory
List(data) returned error, retrying after 3.221479586s: fdopendir: not a directory
List(data) returned error, retrying after 5.608623477s: fdopendir: not a directory
List(data) returned error, retrying after 7.649837917s: fdopendir: not a directory
List(data) returned error, retrying after 15.394871241s: fdopendir: not a directory
fdopendir: not a directory
```

**Comment by fd0** [comment]
Really odd! I'd try to use something equivalent to `strace` on macOS (maybe `dtrace`?) to look at the syscalls restic does. We'd need to find out what restic tries to do with `fdopendir`...

**Comment by kusalananda** [comment]
The attached file is the compressed output from `dtruss`:

```
sudo dtruss -f '/usr/local/bin/restic -p pass -r /Volumes/Backup/backup list packs' 2>dtruss.out
```
(only the error stream, the stdout stream is empty)

Unfortunately, the trace output is out of sync with the actual output from `restic`, probably due to buffering.
Being slightly awkward outside my native Unix landscape (OpenBSD), I'm uncertain if I could have run `dtruss` in a better way.

[dtruss.out.gz](https://github.com/restic/restic/files/6052497/dtruss.out.gz)

**Comment by kusalananda** [comment]
Ok, I think I've found it.

I took the source `tar` archive and built my own copy of `restic` from it (thanks for making this easy!).

My `restic` is a bit more verbose with its errors:

```
[...]
List(data) returned error, retrying after 552.330144ms: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
List(data) returned error, retrying after 1.080381816s: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
List(data) returned error, retrying after 1.31013006s: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
List(data) returned error, retrying after 1.582392691s: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
List(data) returned error, retrying after 2.340488664s: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
List(data) returned error, retrying after 4.506218855s: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
List(data) returned error, retrying after 3.221479586s: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
List(data) returned error, retrying after 5.608623477s: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
List(data) returned error, retrying after 7.649837917s: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
List(data) returned error, retrying after 15.394871241s: fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
fdopendir /Volumes/Backup/backup/data/.DS_Store: not a directory
```
I think that the `.DS_Store` file, created by the macOS Finder when browsing that directory, is creating issues.

Removing it, I no longer have any issues running `list packs` etc.

Testing by creating an empty file called `this-is-not-a-dir`:
```
% touch /Volumes/Backup/backup/data/this-is-not-a-dir
% ./restic -p ~/pass -r /Volumes/Backup/backup list packs
[... much output ...]
List(data) returned error, retrying after 552.330144ms: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
List(data) returned error, retrying after 1.080381816s: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
List(data) returned error, retrying after 1.31013006s: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
List(data) returned error, retrying after 1.582392691s: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
List(data) returned error, retrying after 2.340488664s: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
List(data) returned error, retrying after 4.506218855s: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
List(data) returned error, retrying after 3.221479586s: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
List(data) returned error, retrying after 5.608623477s: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
List(data) returned error, retrying after 7.649837917s: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
List(data) returned error, retrying after 15.394871241s: fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
fdopendir /Volumes/Backup/backup/data/this-is-not-a-dir: not a directory
```

**Comment by rikchilvers** [comment]
Thanks @kusalananda for tracking this down! Removing that `.DS_Store` from the data directory fixed this for me.

**Comment by kusalananda** [comment]
Was this also an issue for other architectures or operating systems?

**Comment by MichaelEischer** [comment]
@kusalananda This issue can occur on any operating system which add (hidden) files to the `data/` folder. On macOS opening the folder in the Finder could be enough to add a `.DS_Store` file there. Something similar might happen on other operating systems.
