### ISSUE TITLE
restic check leaves a lockfile around

### ISSUE THREAD

**Issue by andreasscherbaum** [restic/restic#3304]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.12.12 on linux/amd64
(Ubuntu 20.04.2 LTS)

How did you run restic exactly?
-------------------------------
```
$restic --repo "$backup_path_backup" --cache-dir "$backup_path_cache" --verbose --verbose --verbose{% for exclude in backup.exclude | default([]) %} --exclude='{{ exclude }}'{% endfor %} backup "{{ backup.backup }}" 2>&1 | tee -a "$backup_path_logs/$ts-backup.log"
[check for locks]
$restic --repo "$backup_path_backup" --cache-dir "$backup_path_cache" --with-cache --verbose --verbose --verbose check 2>&1 | tee -a "$backup_path_logs/$ts-check.log"
[check for locks]
```

Broken down to:
```
restic --repo "/path/to/backup" --cache-dir "/path/to/cache" --verbose --verbose --verbose backup "/home/ads" 2>&1 | tee -a "/path/to/logfile.txt"
restic --repo "/path/to/backup" --cache-dir "/path/to/cache" --with-cache --verbose --verbose --verbose check 2>&1 | tee -a "/path/to/logfile.txt"
```

From the logfile:
```
processed 379707 files, 130.701 GiB in 5:53
snapshot 9333dd1b saved
Backup completed
Mi 24. Feb 04:28:41 CET 2021
Start check
Mi 24. Feb 04:30:43 CET 2021
Check completed
Mi 24. Feb 05:13:53 CET 2021
Backup 'home-ads' is locked!
```

This happens quite often, unfortunately, and even with more debugging I can not pin down the problem.
Taking a backup of /home/ads (my home directory) is the largest directory in the backups on this device. The directory is around 550 GB in size, but not everything goes into the backup.
One thing which happens quite regularly: whenever the Chrome browser is running during backups, this situation happens. However I don't know if and how that is related.

Over time I tried to debug the issue, and added checks for locks between the several steps. Turns out that the "backup" step runs fine, and it's always the "check" step which leaves the lock around. There is a difference between "check" runs which are ok, and which fail.

OK:
```
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```

fail:
```
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
```

"check" does not give any indication why it does find errors, or what kind of errors it finds.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local disk, attached to USB port.

Expected behavior
-----------------
"check" should not leave locks around all the time.
"check" should be more verbose about what kind of problems are found, if any.

Actual behavior
---------------

"check" leaves a lockfile around quite often. Suspicious connection to "Chrome" running, but no real evidence.

Steps to reproduce the behavior
-------------------------------

Backup runs at 4am in the morning. When this happens I find an email in the morning, telling me that the backup failed, and left a lockfile. Not sure how to reproduce this properly, it happens quite often though.

Do you have any idea what may have caused this?
-----------------------------------------------

See comments about Chrome, but there are no errors in the backup log about anything Chrome related.

Do you have an idea how to solve the issue?
-------------------------------------------

More information from "check" would be helpful.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Using "restic" all over the place, and I'm happy with it. Moved from duplicity a while ago, and never looked back. Also wrote a blog post about how I use restic, and got good feedback about this.

**Comment by MichaelEischer** [comment]
As you've mentioned that running Chrome might cause check to fail right in the middle: could it be that the system ran out of memory and restic got killed as a result? I'd recommend to upgrade to restic 0.10.0 or newer, which uses a lot less memory and is _much_ faster running `check`.

Did restic exit with a zero exit code for the failed runs? Or was it something else?

**Comment by andreasscherbaum** [comment]
I'm running [earlyoom](https://github.com/rfjakob/earlyoom) on this (and a couple other) desktop systems, and restic is excluded from this:
```
EARLYOOM_ARGS="--avoid '(^|/)(init|X|sshd|restic)$'"
```
Also there is no indication in the syslog that anything was killed because of OOM. The system just becomes non-responsible when "check" runs (I was awake once or twice when "check" runs), but that might be because of the I/O necessary to read from the attached disk.

The exit code is actually a good idea, I see that I integrate this into the script.
But even with rc>0 this still does not explain the lack of error messages, or any useful output.

**Comment by MichaelEischer** [comment]
>  The system just becomes non-responsible when "check" runs (I was awake once or twice when "check" runs), but that might be because of the I/O necessary to read from the attached disk.

`check` should be CPU-bound, this applies especially for older restic versions like 0.9.6. A non-responsive system sounds a lot like the system ran nearly out of memory.

> But even with rc>0 this still does not explain the lack of error messages, or any useful output.

When restic appears to exit without any indications, then it was usually killed by some external program. A crash or an error normally cause a lot of output. Could the way you run restic somehow cause it to receive a SIGPIPE?

**Comment by andreasscherbaum** [comment]
> > The system just becomes non-responsible when "check" runs (I was awake once or twice when "check" runs), but that might be because of the I/O necessary to read from the attached disk.
> 
> `check` should be CPU-bound, this applies especially for older restic versions like 0.9.6. A non-responsive system sounds a lot like the system ran nearly out of memory.

Given that this writes to USB disk first, I expect this to need plenty of CPU. It's a laptop, there is no good way to have faster storage. And it is a large repository.


> > But even with rc>0 this still does not explain the lack of error messages, or any useful output.
> 
> When restic appears to exit without any indications, then it was usually killed by some external program. A crash or an error normally cause a lot of output. Could the way you run restic somehow cause it to receive a SIGPIPE?

I will see OOM kills in syslog, and this does not happen here. Yes, the Chrome is just a hush: since this happened quite a lot I did check the syslog every time, and over time some patterns become clear. Some days I have Chrome (which I use for surfing, and end it several times a day) running until the next day, because some websites are still open. But I have to admit that I don't see how this can cause a problem, given that Chrome also is still running, and will be killed first by OOM.

I plan to upgrade this system at some point to a newer Ubuntu version, but at this point I probably wait until 21/04, and not go to 20/10.

**Comment by andreasscherbaum** [comment]
Haven't upgraded my system yet, but wasn't able to replicate the issue so far.
