### ISSUE TITLE
Fatal: load <index/213eb75246>: invalid data returned

### ISSUE THREAD

**Issue by constb** [restic/restic#3313]
This issue is regarding several different versions and platforms. I'll try to follow issue template as close as possible.

Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.7 on darwin/amd64
restic 0.9.5 compiled with go1.12.4 on darwin/amd64
restic 0.9.5 compiled with go1.12.4 on linux/amd64

How did you run restic exactly?
-------------------------------

RESTIC_REPOSITORY=sftp:username@hostname.com:/restic RESTIC_PASSWORD=secret restic mount ~/local/path

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

sftp

Expected behavior
-----------------

Restic mounts backup storage to the path.

Actual behavior
---------------

restic 0.12.0 compiled with go1.15.7 on darwin/amd64:

```
repository 066cb422 opened successfully, password is correct
Fatal: load <index/213eb75246>: invalid data returned
```

restic 0.9.5 compiled with go1.12.4 on darwin/amd64:

```
repository 066cb422 opened successfully, password is correct
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13b78f8]

goroutine 22 [running]:
github.com/restic/restic/internal/repository.(*Index).ID(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/restic/internal/repository/index.go:377 +0x38
github.com/restic/restic/internal/repository.(*Repository).LoadIndex.func5(0x8, 0x1a69708)
	/restic/internal/repository/repository.go:467 +0xce
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00013c690, 0xc0002363e0)
	/restic/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
	/restic/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

restic 0.9.5 compiled with go1.12.4 on linux/amd64:

```
repository 066cb422 opened successfully, password is correct
Now serving the repository at /root/tmp
When finished, quit with Ctrl-c or umount the mountpoint.
```

Steps to reproduce the behavior
-------------------------------

My repository is created and being used daily for backups by `restic 0.9.5 compiled with go1.12.4 on linux/amd64`. As I can see from the logs, the repository is being successfully updated, so at least this particular build seems content with its data and format. (Also via sftp)

I tried mounting it on Mac. It mount successfully but whenever I try to read its data, the error is printed to the console and restic process quits.

I tried reverting Mac version to match Linux version – same result, but different error this time.

I tried mounting on Linux, the very binary that does backups – it works as intended.

Do you have any idea what may have caused this?
-----------------------------------------------

Seems like some kind of cross-platform or cross-version incompatibility in restic. I didn't find any migration guide or advices to upgrade repository format version though…

Do you have an idea how to solve the issue?
-------------------------------------------

No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm generally happy with restic, its simplicity and the way it just gets exactly the thing I need done without being bloated or hackish. Just a perfect little piece of software that I like very much.

**Comment by constb** [comment]
Additionally I went to the Linux box and installed latest version separately:

restic 0.12.0 compiled with go1.15.8 on linux/amd64:

```
repository 066cb422 opened successfully, password is correct
Now serving the repository at /root/tmp
When finished, quit with Ctrl-c or umount the mountpoint.
```

It works too.

**Comment by aawsome** [comment]
Seems you have an index file that cannot be read on darwin/amd64 - for whatever reason. I suspect some JSON decoding problems...

Can you run `restic list index | grep ^213eb75246` and then `restic cat index <id>` with the ID(s) from the first command?

**Comment by constb** [comment]
> Can you run `restic list index | grep ^213eb75246` and then `restic cat index <id>` with the ID(s) from the first command?

```
$ restic list index | grep ^213eb75246
213eb75246aa62849695d2bbad04e21963904916ecb250c81c81c440f9aa9439
```

restic 0.12.0 compiled with go1.15.7 on darwin/amd64:

```
$ restic cat index 213eb75246aa62849695d2bbad04e21963904916ecb250c81c81c440f9aa9439
repository 066cb422 opened successfully, password is correct
load <index/213eb75246>: invalid data returned
github.com/restic/restic/internal/repository.(*Repository).LoadAndDecrypt
	github.com/restic/restic/internal/repository/repository.go:112
main.runCat
	github.com/restic/restic/cmd/restic/cmd_cat.go:83
main.glob..func4
	github.com/restic/restic/cmd/restic/cmd_cat.go:27
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	github.com/restic/restic/cmd/restic/main.go:98
runtime.main
	runtime/proc.go:204
runtime.goexit
	runtime/asm_amd64.s:1374
```

restic 0.9.5 compiled with go1.12.4 on darwin/amd64:

```
$ restic cat index 213eb75246aa62849695d2bbad04e21963904916ecb250c81c81c440f9aa9439
repository 066cb422 opened successfully, password is correct
load <index/213eb75246>: invalid data returned
github.com/restic/restic/internal/repository.(*Repository).LoadAndDecrypt
	/restic/internal/repository/repository.go:96
main.runCat
	/restic/cmd/restic/cmd_cat.go:77
main.glob..func4
	/restic/cmd/restic/cmd_cat.go:24
github.com/spf13/cobra.(*Command).execute
	/restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
	/restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
	/restic/vendor/github.com/spf13/cobra/command.go:800
main.main
	/restic/cmd/restic/main.go:86
runtime.main
	/usr/local/go/src/runtime/proc.go:200
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```

restic 0.12.0 compiled with go1.15.8 on linux/amd64 and restic 0.9.5 compiled with go1.12.4 on linux/amd64 both output 7.5Mb json. I couldn't make a pastebin out of it, since its larger than free limit, so I uploaded it to wetransfer – https://we.tl/t-i7C96edrXC – in case it contains something that would help solve the issue…

**Comment by aawsome** [comment]
@constb Sorry for the late reply and thanks for your information. Now, this is very strange. The errors you get on darwin/amd64 indicate that there is a mismatch between the SHA256 computed by restic from the file content and the filename (which eqals this hash). The working command using linux/amd64 indicates that the SHA256 does matches the file. 

Can you download the file `index/213eb75246aa62849695d2bbad04e21963904916ecb250c81c81c440f9aa9439` from your sftp and run `sha256sum` on it (both on darwin/amd64 and linux/amd64)? The result should equal the filename. And is this the same machine you run darwin and linux or are these different computers? In general, SHA256 mismatches can indicate broken hardware (storage/network/RAM/CPU), but I think we can rule the storage out here as it works under linux/amd64...

**Comment by MichaelEischer** [comment]
@constb Does `restic cat index --no-cache 213eb75246aa62849695d2bbad04e21963904916ecb250c81c81c440f9aa9439` work?

**Comment by constb** [comment]
@aawsome I tried downloading file with sftp command-line client  and on both platforms the result is identical.

I run darwin/amd64 build on my macbook (catalina) and linux/amd64 runs on production server (debian stretch).

The sftp server that holds backups is an old debian wheezy box (openssh 1:6.0p1-4, openssl 1.0.1e-2+deb7u20). This doesn't explain why restic would download index differently, whether it uses system provided or its own built-in implementation of sftp client, the result should be the same. System sftp clients works fine, built-in should be platform-independent…

Another difference that I spotted when downloading index files is that linux box downloads it instantaneously, it sits on 1Gb/s LAN in the same rack. But sftp from macbook takes almost a minute, because of my slow ISP. Could it be some sort of timeout-related problem? After all that index file is pretty huge…

I uploaded index to https://we.tl/t-OM2RuoeSzD

**Comment by constb** [comment]
> Does `restic cat index --no-cache 213eb75246aa62849695d2bbad04e21963904916ecb250c81c81c440f9aa9439` work?

@MichaelEischer actually it does! so, it's possible that restic caches broken incomplete downloaded index file? should I drop cache entirely before doing restic mount?

**Comment by MichaelEischer** [comment]
> @MichaelEischer actually it does! so, it's possible that restic caches broken incomplete downloaded index file? should I drop cache entirely before doing restic mount?

That's probably what has happened here. Do you still have a copy of the damaged index file somewhere? It would be interesting to know in which way the file was broken, that is whether it was just truncated or whether something else has happened. For a comparison, please compare the size of the file in the cache folder against that of the correct file. If the file size matches, please compare the files, e.g. using `diff <(xxd orig) <(xxd broken)`.

In regards to a truncated file that should be relatively simple to solve as the index size is already available when listing files. For other kinds of corruptions we'd need something like #2533.

**Comment by constb** [comment]
@MichaelEischer there was a bit of a problem that I have already deleted broken cache, so I was starting `restic mount` and stopping it with ctrl-c. first several times it was correctly continuing caching index from where is was stopped until it reached the very same `213eb75246aa62849695d2bbad04e21963904916ecb250c81c81c440f9aa9439` index.

I think several times it was leaving zero-sized incomplete files and was re-downloading those. but the index in question is not zero. It has 32768 bytes in it.

`diff <(xxd orig) <(xxd broken)` produced 32Mb diff that starts with:

```
2048a2049,468873
> 00008000: 2c06 df7d 8703 daa6 c539 f40b 8fe5 6bd7  ,..}.....9....k.
> 00008010: 2430 c97d a00f d673 0046 f48d 9fdf 6943  $0.}...s.F....iC
> 00008020: 7d45 17e5 cf29 6bbb 02be 06f7 e5e4 4cd7  }E...)k.......L.
> 00008030: 713a 9db1 8dde 49d6 d803 ad64 0428 ee61  q:....I....d.(.a
```

…which I assume indicates that those a correct first 32768 bytes of the index file. And the rest is missing.

Well, now I have restic failing again with the very same error message. I guess slow internet combined with stopping it with ctrl-c leaves the cache in some inconsistent state it can't recover from…

**Comment by MichaelEischer** [comment]
> …which I assume indicates that those a correct first 32768 bytes of the index file. And the rest is missing.

You're right. With a slow internet connection it's definitely possible to interrupt restic right in the middle of adding a file to the cache. Unfortunately there's currently no code (yet) to automatically get rid of incomplete snapshots and indexes.

**Comment by MichaelEischer** [comment]
Closing in favor of #2533. After taking a look at the code, it seems to be simpler to enhance `Repository.LoadAndDecrypt` (and ideally a few other places) to retry the download of broken index/snapshot files instead of passing the expected file length through the whole code.

**Comment by molecular** [comment]
Hi.

I'm running into this problem (with 

```
root@x :-) ~# /home/nick/restic/restic.sh synology_nick version                                                                                                                                                    ~
host=synology_nick
restic 0.12.1 compiled with go1.17.3 on linux/amd64
root@x :-) ~# /home/nick/restic/restic.sh synology_nick cat index 5e50e8d2577c12a29556fd98c609e35407e7ebef95175b828f5edfb2b25fb1f3                                                                                 ~
host=synology_nick
repository 35a5a6c3 opened successfully, password is correct
load <index/5e50e8d257>: invalid data returned
github.com/restic/restic/internal/repository.(*Repository).LoadAndDecrypt
        github.com/restic/restic/internal/repository/repository.go:112
main.runCat
        github.com/restic/restic/cmd/restic/cmd_cat.go:82
main.glob..func4
        github.com/restic/restic/cmd/restic/cmd_cat.go:27
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.2.1/command.go:902
main.main
        github.com/restic/restic/cmd/restic/main.go:98
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581
```

using --no-cache works:

```
root@x :-) ~# /home/nick/restic/restic.sh synology_nick cat index --no-cache 5e50e8d2577c12a29556fd98c609e35407e7ebef95175b828f5edfb2b25fb1f3 | sha256sum                                                          ~
c43e82f3566799ae5fe9d8689437ef3198e36dc8548fa8f4278eabe2aec3ebeb  -
```

What can I do to fix this?

Can I clear those caches somehow?
