### ISSUE TITLE
Feature to not exclude path even if parent was excluded, similar to what rsync does

### ISSUE THREAD

**Issue by power833** [restic/restic#3314]
Output of `restic version`
--------------------------

0.12.0

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

From what I could see, restic doesn't have a feature similar to rsync's:

--include=PATTERN don't exclude files matching PATTERN

which ensures PATTERN will always be included even if the parent folder might have been excluded for example. Could this be added?

What are you trying to do? What problem would this solve?
---------------------------------------------------------

This is very helpful if there's a directory containing many unneeded files (which must be excluded), and a single or a few files that need to be included.

**Comment by rawtaz** [comment]
Thanks, but this is already tracked in #233 so I'll close this one as a duplicate :)
