### ISSUE TITLE
rebuild-index: Incomplete pack list

### ISSUE THREAD

**Issue by vixns** [restic/restic#3317]
Output of `restic version`
--------------------------

restic 0.12.0 compiled with go1.15.8 on linux/amd64

How did you run restic exactly?
-------------------------------

restic -r s3:https://[REDACTED] -p /etc/restic.passwd rebuild-index --read-all-packs

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

on premise minio cluster

Expected behavior
-----------------

rebuild a complete index using all available packs

Actual behavior
---------------
I have to retry the same command dozens of times to reach the complete list of packs.
There seems to be some caching because each time the previously added packs are quickly added, then, after a long pause, some new packs are added. After a variable amount of pause/adding, restic stops adding packs and start to build an incomplete index.
Using --no-cache option does not affect 

[...]
adding pack file to index 9bd114d94c0949e2f8048f7cec7507627a4ca5713568aae595c7aaf059bd8348
adding pack file to index 9bd26edd1917f3675c43e4238bdc6eef385544982ce25aeffd508faaf5eb1a66
adding pack file to index 9bd2772f259097567e1cb0a0225a9c2d40dfe0d2b723eb4357842f6c2118e484
adding pack file to index 9bd2af8be869d58722e822a0cb7ea5a2794dc1f375d67fac175c41a1eacffa9e
adding pack file to index 9bd32880ea41b8b21a6430db00465730fc7c4aaa08fb9b99b1682df545671de8
reading pack files
  signal interrupt received, cleaning up

[ a few retries later ]

[...]
adding pack file to index a818a9411d25ad1a83df894e6e9fe020507fec7d348c3dc072a008d7bb4d9cf6
adding pack file to index a818ba00e83e74feb590a724758a3d61a98aef18fe542daa4d12f53bc13a4e19
adding pack file to index a818e8bb23a81d632a944de1077ae9d3a3694c4fb5c89bb31018ec25bc5cb76e
adding pack file to index a81adea7812f6f49e153964ba9421882274f38e3e2837db91955ea000c0d0560
adding pack file to index a81b4825cb72d66919b897e041af03b3a4ea74ce0b73d56da32c6b9c1092b0a2
reading pack files
  signal interrupt received, cleaning up

[ a few retries later ]

[...]
adding pack file to index cbf822cffb0d93eea3e6c3db517e1eecb7479d132f23db40e1dfd53a197b88ec
adding pack file to index cbf873a8c7dbb418fff107cae560b5e74e6824b16df5416e6fc13d4ab8585a7a
adding pack file to index cbf8a38be6a6c3d849d9432a2083cea9184f30dcabb1383458e8595b7723bae3
adding pack file to index cbf8a9d58b54f638a7ff537f579f7e8d0e2fe5f8c59892cd5c8668dfdf5db9fd
adding pack file to index cbf98f0c884d0502663dc54cf6ab6d692d7c91c8fe34185edc7cc5d42b116651
reading pack files
  signal interrupt received, cleaning up

[one retry later, lucky! ]

[...]
adding pack file to index d80a62ef205cf5b56119ef0859ca16ca7ff7c6cdf75848e27a144dbfa6d69f3d
adding pack file to index d80ae429816a4e7d103cc846e72b37e0bc54c565f83391f118ed7b55218fa389
adding pack file to index d80bf878c8b065dceca70d8491f05597cc92196822813545eef1fd99e2307e64
adding pack file to index d80c1dc20169835204fe528b93f384a36868626ba0ed074414458d4ffe197e8a
reading pack files
  signal interrupt received, cleaning up

[ a few retries later ]

[...]
adding pack file to index e3f058c44004e0427e7a932f653dd183b2d87096b28f8847597d3fefd44ace41
adding pack file to index e3f0e6e962bccbdcc65d65075ba6bc11291fb0800d7b5c692b0437b20c813f21
adding pack file to index e3f19003a48db5ef7597a5e00e49cdb6ae075dee209f022f95c89faf76437981
adding pack file to index e3f279bb58520c71d66e0d61de67305bc2ccd9d12186e81c224444feaee89893
reading pack files
  signal interrupt received, cleaning up

[ a few retries later ]

[...]
adding pack file to index fb99f27522f64a23480ae78e413c08bbc028183f118e8b7e4aae3e6903199fb0
adding pack file to index fb9ae5ef5c9af2277ea47aed290520f9bf45624ec97670216db48557e01152bd
adding pack file to index fb9c1fd9fd7f8e85b02b9d13e734747b2dca760d41235a11ca7c997859f19c15
adding pack file to index fb9cb9618c35fd4f86cad1bb2be974ddfc5868b1d42db351f1b33ba717a5c4cd
reading pack files
  signal interrupt received, cleaning up

[ a few retries later ]

adding pack file to index fffe3ab79439b50d63d2faec408791639e03e6281896b25570a967bcc24563d6
adding pack file to index fffea885aefe5709ea4fa31221258d489ef97620f3e82961d846b9f1acefab69
adding pack file to index ffff94853611ecec2307d5dbdf943d303cf7392f6dbd3d0f586fda50933ae79c
reading pack files
[0:21] 0.63%  668 / 106507 packs

\o/

Steps to reproduce the behavior
-------------------------------

You need a repository with lots of packs to reproduce, I have many repositories on similar hardwares using the same object store, only the repositories with lots of packs fire this issue.

Do you have any idea what may have caused this?
-----------------------------------------------

A timeout waiting for packs fetch / analysis ? 

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by vixns** [comment]
I may have fount the cause, I suspect minio's sidekick. I'll retry the same test bypassing it and update this issue.

**Comment by vixns** [comment]
I confirm minio's sidekick was the culprit.

**Comment by fd0** [comment]
Thanks for the feedback! Can you maybe explain a bit what went wrong there? I can see that Minio sidekick is an HTTP load balancer, but how did that cause the issue? And how did you resolve it? Thanks!

**Comment by vixns** [comment]
I don't know yet, the workaround was to bypass sidekick and talk to minio directly. I guess this is GC related according to these "waves" of packs and pauses during testing.
I don't like load balancers using GCs, but I still sporadically give them a try, even if, like for sidekick, I'm always deceived.
I will replace sidekick by haproxy, a rock solid C++ based http load balancer. It may not have this seamless minio integration, but I'm almost sure it will not cause this kind of issue.

**Comment by vixns** [comment]
I don't know yet, the workaround was to bypass sidekick and talk to minio directly. I guess this is GC related according to these "waves" of packs and pauses during testing.
I don't like load balancers using GCs, but I still sporadically give them a try, even if, like for sidekick, I'm always deceived.
I will replace sidekick by haproxy, a rock solid C++ based http load balancer. It may not have this seamless minio integration, but I'm almost sure it will not cause this kind of issue.

**Comment by vixns** [comment]
On our biggest indexes, we face the same issue with a direct link with minio. There is definitely an issue here.
How can I help debugging it ?

**Comment by aawsome** [comment]
Besides your problem with reading all pack files:

Is there a reason why you use `--read-all-packs`? For almost all scenarios a simple `rebuild-index` will give the same result and only needs to read pack files which are not yet contained in the index.

And, out of curiosity: What is the reason you run `rebuild-index` at all? This command should not be needed except in cases of broken repositories..

**Comment by MichaelEischer** [comment]
@vixns Could you run `restic list packs` a few times and compare the output? How large are the problematic repositories?

**Comment by vixns** [comment]
Minio's s3.ListObjectsV2 often takes 60 ~ 100s to return 4500 entries from HDD storage.
This may timeout the connection, especially when using a htttp proxy / load balancer.
This issue will be mitigated soon, see https://github.com/minio/minio/issues/11625

From a restic POV, shouldn't s3.ListObjectsV2 calls be retried a couple of times then exit the whole process on failure instead of continue with incomplete lists ?

**Comment by MichaelEischer** [comment]
> From a restic POV, shouldn't s3.ListObjectsV2 calls be retried a couple of times then exit the whole process on failure instead of continue with incomplete lists ?

restic already retries all backend operations up to 10 times when an error happens. But apparently restic never got an error from the backend and thus doesn't retry the operation. Could you build a debug version of restic according to the instructions at https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs and collect a debug log of a problematic `restic list packs` run? That would allow us to take a closer look at the problematic list request and it's reply.

**Comment by vixns** [comment]
I reproduce the same issue with the minio client, it returns incomplete lists without any error, scary.
I will investigate and open an issue on the minio project, I'm closing this issue and will reopen it needed.
