### ISSUE TITLE
restic tests fails on arm with unexpected error: operation not supported

### ISSUE THREAD

**Issue by stkw0** [restic/restic#3318]
We are having some issues with restic package in Gentoo, while trying to execute restic-0.11.0 tests on arm the next error occur: 

```

=== RUN   TestPreallocate/1
preallocate_test.go:25: unexpected error: operation not supported

=== RUN   TestPreallocate/4096
preallocate_test.go:25: unexpected error: operation not supported

=== RUN   TestPreallocate/1048576
preallocate_test.go:25: unexpected error: operation not supported

--- FAIL: TestPreallocate (0.01s)
    --- PASS: TestPreallocate/0 (0.00s)
    --- FAIL: TestPreallocate/1 (0.00s)
    --- FAIL: TestPreallocate/4096 (0.00s)
    --- FAIL: TestPreallocate/1048576 (0.00s)

```

Note that this error seems to happen also with version 0.9.6, and in both cases it happens in arm and arm64.

**Comment by MichaelEischer** [comment]
Which filesystem is used for the tmp directory? The tests currently assume that preallocate works there. However, it would be possible to skip that test if operation not supported is returned. The restorer code uses preallocate as an optional optimization and still works even if the preallocation fails.

That error cannot occur for restic 0.9.6, the preallocate implementation didn't exist back then.

**Comment by stkw0** [comment]
This error was reported by a gentoo dev (not myself), I'm still setting up an arm set-up to test this. Version 0.9.6 had also some tests failures on arm, maybe not the same, I will try it out myself when I had the arm set-up ready and report back.

Thank you, I was unaware that the preallocate feature was fs dependent.

**Comment by MichaelEischer** [comment]
The test works fine on my raspberry pi (using raspbian). Could you try whether #3319 solves the problem for you?

**Comment by stkw0** [comment]
Seems that the environment changed and now the tests passed. I don't why, it's very weird. I will close this issue for now.
