### ISSUE TITLE
manual: add note that fuse is not available on Windows

### ISSUE THREAD

**Issue by frederich** [restic/restic#332]
Fuse is not available on Window. Please leave a note at `https://restic.github.io/manual/#mount-repository`.

**Comment by fd0** [comment]
Thanks for raising the issue!

**Comment by frederich** [comment]
I'm on it and send a PR.

**Comment by fd0** [comment]
This was merged in https://github.com/restic/restic.github.io/commit/ef40606e31e2a1a135ae5e850fa4e5cf76e9ddbc
