### ISSUE TITLE
docs: ex: backing up w/o root: self-upgrade 

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#3322]
https://restic.readthedocs.io/en/stable/080_examples.html#backing-up-your-system-without-running-restic-as-root

Actual behavior; Do you have any idea what may have caused this?
-----------------------------------------------
The example/guide doesn't think of upgrading, 'From now on', etc. Self-upgrade either:
 - (restic user) fails
 - (root) mixes up the permissions

Do you have an idea how to solve the issue?
-------------------------------------------
There's not much point to `--output`, as we'll replace the binary anyway, and execute it.

Current command I have come up with:
```
export p=/home/restic/bin; export r=$p/restic; sudo -u restic $r self-update; chown root:restic $p $r; chmod 770 $p; chmod 750 $r; setcap cap_dac_read_search=+ep $r; sudo -u restic $r -r rest:… backup …
```

This is the 'set and forget, throw in crontab' (assuming we trust self-update to not bring in malicious code, what's fairly low risk).

***

/assign self

Should the (somewhat blind) auto-upgrade be added to the example, as the default, as an optional.. or rather a warning of you have to upgrade with _this_ now and then?

**Comment by rawtaz** [comment]
These are separate concerns. The documentation chapter you pointed to is about backing up the entire system. It is not about how to keep your restic binary/installation up to date, which is documented in https://restic.readthedocs.io/en/stable/020_installation.html .

So no, we shouldn't add the auto-upgrade to the example, nor a warning as the concern of keeping your restic up to date is no more relevant or applicable when you back up your entire system, than it is when you just back up a single file or folder.

I'm inclined to close this issue but will let you comment first in case there's something I'm totally missing here.

**Comment by ProactiveServices** [comment]
It would be useful if the instructions in this part of the docs would mention the changes being reset on a `self-upgrade` as I was caught out with this recently. As long as a user is aware of this they can enact their own method to reset permissions after an upgrade.

**Comment by jtagcat** [comment]
I somewhat unexpectedly caught it when setting up / testing the deployment as well.

At least a warning that:
 - the changes are reset
 - (restic can't self-update, at least with that guide (might fail silently to user, if user uses `&&` to chain a crontab, it might stop backups altogether, assuming the worst of the reader, though))

> It is not about how to keep your restic binary/installation up to date, which is documented in restic.readthedocs.io/en/stable/020_installation.html.

Requesting changes, then. The guide downloads restic with `curl`, what can be read as 'this guide includes installation'. Somewhat true, but misleading.

***

Even with a warning(s), the workarounds can be the user shooting themselves. It took me 2-3 tries plus 10-20m thinking it through, and crafting this command:
```
export p=~restic/bin; export r=$p/restic; sudo -u restic $r self-update; chown root:restic $p $r; chmod 770 $p; chmod 750 $r; setcap cap_dac_read_search=+ep $r; sudo -u restic $r -r rest:… backup …
```

***

The main point being, unfortunately examples and guides often end up in prod, copy-pasta. With backups, my thinking is to make it as idiot proof as possible. [And then they build a better idiot](https://pl.c7.ee/wendel-build-a-better-idiot.webm).

Go with warn: when setting and forgetting (setting up automatically recurring backups, crontab):
 - get some god damn failure and success (if no success within n period, something is wrong) to a place you read regularly
 - restic is not updated
 - if you self-update restic, permission changes are lost
 - here is a snippet that you can shove in to the root crontab after initial install (saves time, and possible human failure)
   - ~~optionally (I say not, to force the user to read), also, here's a snippet to install: (not tested, quickly done, also [depends on bzip2](https://github.com/restic/restic/issues/2705#issuecomment-618493679)) `export p=~restic/bin && useradd -m restic && mkdir -p $p && curl -L https://github.com/restic/restic/releases/download/v0.9.6/restic_0.9.6_linux_amd64.bz2 | bunzip2 > $p/restic`~~

***

![image](https://user-images.githubusercontent.com/38327267/110228079-2b649a00-7ef6-11eb-9a14-018ea2d3283e.png)
Heh, that caught me off guard.

**Comment by rawtaz** [comment]
> It would be useful if the instructions in this part of the docs would mention the changes being reset on a self-upgrade

Are you referring to the capabilities that were added to the downloaded restic binary? Indeed you can be "bitten" by this, but at the same time, are you not supposed to know that if you assign a capability to one binary, and then replace that with a completely different binary, the capabilities no longer applies? It's two different binaries.

@jtagcat It's hard to understand half of what you wrote, probably due to language barrier, but I'll add a warning/notice to the instructions, clearly pointing out to the user that the capabilities will be reset if they replace the restic binary with a new one or run `self-update`. That should address the concern you raised. We really should not make this part of the documentation an installation guide - that is not what it's written for.

**Comment by rawtaz** [comment]
Thanks for improving usability of restic!
