### ISSUE TITLE
Set staging area for restores from remote backend to save bandwidth

### ISSUE THREAD

**Issue by akrabu** [restic/restic#3330]
Output of `restic version`
--------------------------

restic 0.12.0 compiled with go1.15.7 on darwin/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

So, last I checked (a few versions ago), if you were doing a restore from an online backend, restic wasn't smart enough to just download a blob once.  For every file that references that blob, restic will download it again and again.  This may have changed, but I just had a "light bulb over my head" moment and wanted to share.

What if there was a --set-staging-path flag, where you could set a temporary staging area, in which restic would download all blobs referenced in a specific snapshot, and then work from that directory?  Say you have 100GB deduped to 70GB.  Instead of having to download that full 100GB (plus probably a little more with overhead?), it would just download 70GB to the staging area, then piece it all back together locally instead of remotely.  Make sense?

What are you trying to do? What problem would this solve?
---------------------------------------------------------

This would be especially helpful for backends that charge for egress.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Always!  :)

**Comment by rawtaz** [comment]
> Say you have 100GB deduped to 70GB. Instead of having to download that full 100GB (plus probably a little more with overhead?), it would just download 70GB to the staging area

What makes you think that restic will download 100 GB instead of the 70 GB that is actually in the repository (disregarding the overhead)?

**Comment by MichaelEischer** [comment]
> So, last I checked (a few versions ago), if you were doing a restore from an online backend, restic wasn't smart enough to just download a blob once. For every file that references that blob, restic will download it again and again. This may have changed, but I just had a "light bulb over my head" moment and wanted to share.

This has already been solved in the restore rewrite included in restic 0.10.0. The restored files themselves now serve as staging path: each downloaded blob is immediately written into each file which uses that blob. That way each blob is only downloaded once while at the same time there's no need for temporary storage.

**Comment by akrabu** [comment]
@rawtaz I think it was these threads, but it seems this has already been resolved.  Wasn't sure, but glad to hear it!  The notion of a workaround just popped in my head so I thought I'd share it.  Should have researched the change logs first.

https://forum.restic.net/t/reduce-restic-restore-read-amplification/2314
https://forum.restic.net/t/in-what-order-does-restic-restore-files-appears-random/2278/12
https://forum.restic.net/t/what-is-restic-restore-even-doing/2243

@MichaelEischer Ahh okay, yeah I wasn't sure if this had already been addressed or not.  Thanks!!
