### ISSUE TITLE
Windows SFTP Path Handling

### ISSUE THREAD

**Issue by JaCoB1123** [restic/restic#334]
Trying to Backup to an SFTP repository on Windows like this:

    > .\restic.exe -r sftp://user@host//files/Backup/restic backup "C:\Users\Jacob1123"
    \files\Backup\restic\data does not exist

Note that the error message contains Backslashes instead of forward slashes.

Also, when I init a new repository via SFTP I get the following folders instead of a single folder "restic" containing the others:

    restic/
    restic\\keys/
    restic\\locks/
    restic\\data/
    restic\\snapshots/
    restic\\index/
    restic\\tmp/

I also tried using a minGW-Terminal, but got the same results.

**Comment by fd0** [comment]
Oh, that's indeed a bug. Good catch!
