### ISSUE TITLE
Typo in check command

### ISSUE THREAD

**Issue by rrossouw01** [restic/restic#3344]
Just FYI may be missing a space in restic check output.  The line is "no errors were found49 snapshots"

````bash
# restic version
restic 0.12.0 compiled with go1.15.8 on linux/amd64
````
````bash
# restic check
using temporary cache in /tmp/restic-check-cache-358669417
repository 2601de52 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-358669417
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found49 snapshots
[0:51] 100.00%  49 / 49 snapshots
````

**Comment by rawtaz** [comment]
Thanks! Do you want to open a pull request for this, as a contribution? :)

**Comment by MichaelEischer** [comment]
The garbled output is actually a tiny race condition and not just a typo:
https://github.com/restic/restic/blob/88a23521ddec879694417bc493f18348d53b09b2/cmd/restic/cmd_check.go#L244-L250

The progress bar is started and stopped in the spawned goroutine. However, the `range errChan` does not wait for it to terminate. So this should use a `sync.WaitGroup` to ensure that the progress goroutine has stopped once the errChan-loop has completed.

**Comment by mathstuf** [comment]
I'll take this.
