### ISSUE TITLE
Time field seems to have too many digits after the decimal

### ISSUE THREAD

**Issue by Mrodent** [restic/restic#3349]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on windows/amd64

How did you run restic exactly?
-------------------------------

scripting (Python, using subprocess.run)

    snapshots_result = subprocess.run(['restic', '-r', repo_location, '--verbose', '--json',
        '-p', pwd_file, 'snapshots', '--tag', snapshot_frequency, ], 
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=60).stdout
    snapshots_result = snapshots_result.decode( 'utf-8' )
    snapshots_obj = json.loads( snapshots_result )
    if len(snapshots_obj) > 0:
        most_recent_snapshot = snapshots_obj[-1]
        most_recent_snapshot_datetime=datetime.datetime.fromisoformat(most_recent_snapshot['time'].replace( 'Z', ''))

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
file system (Windows 10 OS)

Expected behavior
-----------------

string delivered from "time" field in the JSON object: "2021-03-27T11:24:35.0439089Z"

    most_recent_snapshot_datetime=datetime.datetime.fromisoformat(most_recent_snapshot['time'].replace('Z', ''))

... this should parse the date-time as ISO (discarding trailing 'Z' is standard)

Actual behavior
---------------

    most_recent_snapshot_datetime=datetime.datetime.fromisoformat(most_recent_snapshot['time'].replace('Z', ''))

... this raises a "ValueError:  Invalid isoformat string"
So I have to do 
    
    most_recent_snapshot_datetime=datetime.datetime.fromisoformat(most_recent_snapshot['time'][:-2])

i.e. discard the last 2 characters, the last digit and the letter "Z". 
This is because for some reason the string given in the field "time" of the JSON object has 7 characters after the decimal point, rather than 6.

A few minutes later: just now I got a "time" field with a completely different problem, which also fails to parse:
"2021-03-28T08:35:28.543326+01:00"

... so now I'm doing 

    most_recent_snapshot_datetime=datetime.datetime.fromisoformat(most_recent_snapshot['time'][:26])

(first 26 characters only: discard the rest)

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------
Give "time" as a more standard ISO format string, and make its format consistent.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic is fantastic... hopefully someone is working on these minor niggles!

**Comment by greatroar** [comment]
Restic's dates are in the [RFC 3339](https://tools.ietf.org/html/rfc3339) format, which should be ISO 8601 compliant. JavaScript parses both dates from your example correctly: `new Date("2021-03-28T08:35:28.543326+01:00")`.

I think the problem is in Python. In the [datetime.fromisoformat](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) description it says:

> **Caution:** This does not support parsing arbitrary ISO 8601 strings - it is only intended as the inverse operation of datetime.isoformat(). A more full-featured ISO 8601 parser, dateutil.parser.isoparse is available in the third-party package dateutil.

**Comment by Mrodent** [comment]
OK, fair enough. Thanks.
