### ISSUE TITLE
restic init fails on s3

### ISSUE THREAD

**Issue by realsirjoe** [restic/restic#3351]
## version
    restic 0.12.0 compiled with go1.15.8 on linux/amd64

## command
    restic -r s3:s3.amazonaws.com/restic-repo init
## output
    Fatal: create key in repository at s3:s3.amazonaws.com/restic-repo failed: wrote 0 bytes instead of the expected 458 bytes
    
## reproduce

I tried to create a restic repository on s3 yesterday, which just worked as expected. 
### I used an IAM User with:
- ListBucket
- GetBucketLocation
- PutObject
- GetObject
- DeleteObject 

Basically I followed https://restic.readthedocs.io/en/latest/080_examples.html#setting-up-restic-with-amazon-s3

Then I ran

    restic -r ./repo1 copy --repo2 s3:s3.amazonaws.com/restic-repo

Which seemed to work but just took very long so I got

    client_loop: send disconnect: Broken pipe

So I fixed it, so that would not happen again. At that time I checked the bucket and the snapshots where copied to the repo ( about 50GB ) though I did not validate them, since I assumed the copying got interrupted. Thats why I deleted all the objects and ran 
        restic -r s3:s3.amazonaws.com/restic-repo init
again, which gave me the described error. I also tried to delete the entire bucket and recreate it, but that just gave me the same error

Here's the entire output of the command
    
    > restic -r s3:s3.amazonaws.com/restic-resort init
    enter password for new repository:
    enter password again:
    Fatal: create key in repository at s3:s3.amazonaws.com/restic-resort failed: wrote 0 bytes instead of the expected 458 bytes

## notes

It takes very long before I get the prompt "enter password for new repository:" about 5 minutes, before the error it appeared almost immediately

**Comment by fd0** [comment]
To be honest, I've got no idea what's going on. From the outside, it looks like your network connection to AWS is somehow broken. After establishing a TCP connection, restic tries to send data, but then the connection is reset(?). Is there anything unusual in your network, like a proxy or so?

Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and attach it to the issue? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it.

**Comment by jeshan** [comment]
repo should be provided in this format
`export RESTIC_REPOSITORY="s3:https://s3.amazonaws.com/restic-demo"`

which is on that page but does not match what you pasted above. double-check. I'm using restic right now and it works well.

**Comment by realsirjoe** [comment]
I built it from source ( before I just downloaded the binary ) and that resolved it! Don't know exactly what went wrong before. Thanks for your help!

**Comment by realsirjoe** [comment]
I was able to reproduce the issue by doing the exact same thing I interrupted the copying and emptied the entire s3 instance. After that the init command above gave the same error.

**Comment by rawtaz** [comment]
I'm curious what `err` is at the time that the error message is printed. Can you change the following [line 281](https://github.com/restic/restic/blob/master/internal/backend/s3/s3.go#L281) in `internal/backend/s3/s3.go` from `return errors.Errorf("wrote %d bytes instead of the expected %d bytes", info.Size, rd.Length())` to `return errors.Errorf("wrote %d bytes instead of the expected %d bytes with error %v", info.Size, rd.Length(), err)`, rebuild restic and then reproduce the problem, and tell me what the error message is?

**Comment by realsirjoe** [comment]
I did so however a message of that format (...bytes with error...) is not inside the debug log

**Comment by realsirjoe** [comment]
Also rebuilding restic this time did not fix the problem, so I immediately experienced the error this time

**Comment by rawtaz** [comment]
It's just an addition in the original error message, so look at the regular error output where you got the original error message.

**Comment by realsirjoe** [comment]
sorry, that one was actually on me, I didn't get the error this time (I screwed up on a different place and confused it with this error), it works perfect again and I am not able to reproduce it. So I guess it really was just the binary I used before building it myself. Thanks for all the help, I appreciate it!

**Comment by realsirjoe** [comment]
Since the error didn't even occur in the logs above I am going to remove them

**Comment by rawtaz** [comment]
Alright, let's keep this closed for now since you can't reproduce it. If the problem appears again, please make sure that you can reproduce it a couple of times using the then latest restic version. Thanks!

**Comment by marliotto** [comment]
Hello everyone,
I had the same problem.

```
> restic version
restic 0.12.0 compiled with go1.15.8 on linux/amd64
```

I ran the command

```
> restic -r s3:s3.amazonaws.com/bucketXXX init
```
I was waiting 5 minutes, then I interrupted command. No any result.

Then I found the same case in https://github.com/restic/restic/issues/2597.
Next try: command with concrete region
```
>restic -r s3:s3.amazonaws.com/bucketXXX -o s3.region="eu-west-3" init
... waiting 1 minutes and 30 seconds
enter password for new repository:
enter password again:
... waiting 1 minutes
Fatal: create key in repository at s3:s3.amazonaws.com/bucketXXX failed: wrote 0 bytes instead of the expected 456 bytes
```

I rebuilt restic binary to show error message (https://github.com/restic/restic/issues/3351#issuecomment-814465049)

```
>restic -r s3:s3.amazonaws.com/bucketXXX -o s3.region="eu-west-3" init
... 
enter password for new repository:
enter password again:
...
Fatal: create key in repository at s3:https://s3.eu-west-3.amazonaws.com/opo-restic-backup failed: wrote 0 bytes instead of the expected 455 bytes with error Access Denied
```
I saw an error "Access Denied"!
Interesting, but I didn't set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.
```
echo $AWS_SECRET_ACCESS_KEY

echo $AWS_ACCESS_KEY_ID

```
There are empty values.

I tried 
```
>AWS_ACCESS_KEY_ID=XXX AWS_SECRET_ACCESS_KEY=XXX restic -r s3:s3.amazonaws.com/bucketXXX -o s3.region="eu-west-3" init
```
It works, without any delays!!!
Also, I tried without region
```
>AWS_ACCESS_KEY_ID=XXX AWS_SECRET_ACCESS_KEY=XXX restic -r s3:s3.amazonaws.com/bucketXXX init
``` 
It works without any delays too!

## Conclusion
The main reason: AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID have empty or wrong values
