### ISSUE TITLE
Restic backup causes a file-system error leaving partition read-only

### ISSUE THREAD

**Issue by padraic-padraic** [restic/restic#3358]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/amd64

How did you run restic exactly?
-------------------------------
`Installed/restic_0.12.0_linux_amd64 -r backup/ backup --exclude 'backup .git ftp ftp_*' /home/padraic/ -v`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local (at ~/backup, or at /bkp/padraic, tried both)

Expected behavior
-----------------
Restic creates a backup of my home directory.

Actual behavior
---------------
The entire partition becomes read only. I get a number of error messages during the backup as follows
```
enter password for repository: 
repository a351f7d2 opened successfully, password is correct
created new cache in /home/padraic/.cache/restic
lock repository
load index files
no parent snapshot found, will read all files
start scan on [/home/padraic/]
start backup on [/home/padraic/]
scan: lstat /home/padraic/.cache/spotify/Browser/Cache/f_000142: bad message
Save(<data/3d0eecd91a>) returned error, retrying after 552.330144ms: Chmod: chmod backup/data/3d/3d0eecd91a30e3469a30691641b0c33963895326101e03c5ac50539d143c9625: read-only file system
scan: lstat /home/padraic/.cache/spotify/Browser/Cache/f_000a3c: bad message
Remove(<lock/f5f3ebb030>) returned error, retrying after 720.254544ms: Chmod: chmod backup/locks/f5f3ebb030d55c27d6677f31be2afb57682c92e5e0e85ba174e142ace411b29d: read-only file system
Remove(<lock/f5f3ebb030>) returned error, retrying after 873.42004ms: Chmod: chmod backup/locks/f5f3ebb030d55c27d6677f31be2afb57682c92e5e0e85ba174e142ace411b29d: read-only file system
Remove(<lock/f5f3ebb030>) returned error, retrying after 1.054928461s: Chmod: chmod backup/locks/f5f3ebb030d55c27d6677f31be2afb57682c92e5e0e85ba174e142ace411b29d: read-only file system
Remove(<lock/f5f3ebb030>) returned error, retrying after 1.560325776s: Chmod: chmod backup/locks/f5f3ebb030d55c27d6677f31be2afb57682c92e5e0e85ba174e142ace411b29d: read-only file system
Remove(<lock/f5f3ebb030>) returned error, retrying after 3.004145903s: Chmod: chmod backup/locks/f5f3ebb030d55c27d6677f31be2afb57682c92e5e0e85ba174e142ace411b29d: read-only file system
Remove(<lock/f5f3ebb030>) returned error, retrying after 2.147653057s: Chmod: chmod backup/locks/f5f3ebb030d55c27d6677f31be2afb57682c92e5e0e85ba174e142ace411b29d: read-only file system
Remove(<lock/f5f3ebb030>) returned error, retrying after 3.739082318s: Chmod: chmod backup/locks/f5f3ebb030d55c27d6677f31be2afb57682c92e5e0e85ba174e142ace411b29d: read-only file system
  signal interrupt received, cleaning up
Remove(<lock/f5f3ebb030>) returned error, retrying after 5.099891944s: Chmod: chmod backup/locks/f5f3ebb030d55c27d6677f31be2afb57682c92e5e0e85ba174e142ace411b29d: read-only file system
Remove(<lock/f5f3ebb030>) returned error, retrying after 10.263247495s: Chmod: chmod backup/locks/f5f3ebb030d55c27d6677f31be2afb57682c92e5e0e85ba174e142ace411b29d: read-only file system

```

Looking in /proc/mounts I find that the drive has encountered an error and remounted as read-only.
`/dev/mapper/data-root / ext4 ro,noatime,errors=remount-ro 0 0`

Steps to reproduce the behavior
-------------------------------
`restic init --repo ~/backupo`
`restic -r ./backup backup --exclude "backup .git"`

Do you have any idea what may have caused this?
-----------------------------------------------
Not sure if it's relevant, but my home drive is part of an LVM setup encrypted using LUKS.

Do you have an idea how to solve the issue?
-------------------------------------------
None

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
The tool seems very straightforward and fast, my only issue is I seem to be invoking it wrong :slightly_smiling_face:

**Comment by rawtaz** [comment]
I could be totally wrong but it sounds like you have a corrupt filesystem and/or misbehaving disk system. Can you perform a full fsck and perhaps also diagnose the disk?

**Comment by padraic-padraic** [comment]
Absolutely a possibility. I did an extended smart check which turned up no issues on the drive but will do fcsk to check the file system.

**Comment by padraic-padraic** [comment]
Fsck fixed it, thanks for that. Apologies for opening an issue over this!
