### ISSUE TITLE
Restic 0.12.0 SHA256SUMS does not match!

### ISSUE THREAD

**Issue by protoncoder** [restic/restic#3364]
I've downloaded Restic 0.12.0 from:
https://github.com/restic/restic/releases/tag/v0.12.0

I've tried to verify my download using provided SHA256SUMS but they don't match!

SHA256 hash of .\restic_0.12.0_windows_amd64.exe:                                                                       3fd50d284e92f3f68c9aacc67b8ba827af914c24764cd272be90bd3c174ca576

0440615136eecfa56e9844e37679738622563c126c9cafb96433cec4ba11699a  restic_0.12.0_windows_amd64.zip

**Comment by rawtaz** [comment]
You are comparing the SHA256 of a .exe file with the SHA256 of a .zip file, that's why they differ.

The SHA256 for the .zip file in your output is identical with the corresponding .zip file entry in https://github.com/restic/restic/releases/download/v0.12.0/SHA256SUMS so it should be all right :)
