### ISSUE TITLE
RFC: Exit with code 3 when paths don't exist during scanning?

### ISSUE THREAD

**Issue by rawtaz** [restic/restic#3369]
This is currently a bit open for debate, based on [this forum thread](https://forum.restic.net/t/restic-exit-code-in-a-bash-script-appears-to-be-wrong/3829/14).

Currently, restic returns exit code 3 for paths that it was told to back up, and that existed during its scanning phase, but then for some reason couldn't be read at the time that it would try actually back the path up. It currently does not return exit code 3 when there are paths it was told to back up, that did not exist during scanning either - it outputs a warning about these paths, but they don't cause an exit code 3 (this is true both for paths given on the command line and paths given in a `--files-from` file):

~~~
$ cat list.txt 
foo
foo2
foo3

$ ./restic -r apa backup --files-from list.txt bar
pattern "foo3" does not match any files, skipping
bar does not exist, skipping
enter password for repository: 
repository ba330420 opened successfully, password is correct
using parent snapshot 9af99ec5

Files:           0 new,     0 changed,     3 unmodified
Dirs:            0 new,     0 changed,     6 unmodified
Added to the repo: 0 B  

processed 3 files, 494 B in 0:00
snapshot e1f007b5 saved

$ echo $?
0
~~~

The question is; Should restic return exit code 3 for files that it was told to back up but that it can't read at the time of scanning too (e.g. paths it was told to back up that doesn't even exist)?

A reason to do this would be to make sure that the user gets a non-zero exit code whenever there's any problem backing up the paths they supplied (not only when the paths became unreadable between scanning and backing up).

A counter-reason would be when you have a script that tells restic to back up your regular stuff as well as some mounted device, e.g. a hard drive, but where you don't have that hard drive mounted all the time. As it is now, you will not get a non-zero exit code when this happens, and if we change this you will. But perhaps that's a good reason to modify your script so it doesn't ask restic to back up that path if the drive isn't mounted..

Thoughts?

**Comment by rawtaz** [comment]
Personally, I'm leaning towards making this change, so that restic returns exit code 3 (unless a different exit code would be more suitable) for all paths it was asked to back up but couldn't. It would be more on the side of caution than it currently is, and there's nothing worse than having backups where you thought something was backed up, but it wasn't (besides being unable to restore them for some reason).

**Comment by MichaelEischer** [comment]
Backup paths that don't exist also don't end up in the list of paths belonging to a snapshot, such that only including existing paths in the call to the backup command won't lead to different snapshots.

I wonder whether someone is depending on restic silently ignoring non-existing paths. Returning exit code 3 when some files cannot be read already caused quite some confusion.

**Comment by quinncomendant** [comment]
Related issue: Return different exit codes for different failures #956
