### ISSUE TITLE
no reference in any index

### ISSUE THREAD

**Issue by frederich** [restic/restic#337]
I've deleted my old backup with `rm -rf backup` and created a new one. Then I've run the check command and got `not referenced in any index` errors. What's wrong?

```
g:\restic -r backup init
...
g:\restic -r backup check
....
pack ffdd766820fb41ca712339258b0222a32439a81398c25cd9c0ac0ea91fe164f8: not referenced in any index
pack ffde5f7264a6d56f0f5208e7f4dd88031ed0bc5a23253f999ccd616aa3a3fc73: not referenced in any index
pack ffdfde3df401dca22975bc24b78a4c024b4c85ae6be1f47b76e23082f76e0f80: not referenced in any index
pack ffe04d75a2dc4597e83aff6743adad4645f9b16f7e651f5d5f5b28cb49e433b1: not referenced in any index
pack ffe2472ccfaa9815a8385c51f24260b1824ab1d9ebd5d764e9c7685ab274afaa: not referenced in any index
pack ffe27367f6257f1db0a4d200b04f825bebe2a9101a6dec55e099a15e50e7abda: not referenced in any index
pack ffeb6c618c1acba0ef0f2b4587fc9ed82e0af84057c3e1c682cd30b96bc28b37: not referenced in any index
pack fff68063c97c04cc490c639329f27da870d842c3e0dab72cb10dfc8b497969d5: not referenced in any index
pack fffb4aa8f9ea4e9a387a45c279e89311b25d1e85b229120a86d1874e0a4cf24f: not referenced in any index
Check snapshots, trees and blobs
error: ciphertext verification failed
error: ciphertext verification failed
repository contains errors
```

**Comment by fd0** [comment]
Hm, that, looks strange. Did you interrerupt and restart the backup? Did something modify the files? Could you check whether all files' names match their sha256sum?

Usually, unreferenced packs are the result of an interrupted backup (so the index wasn't written), but the ciphertext verification failures are really strange, that means something has tampered with the files...

**Comment by frederich** [comment]
Yes, I've interrupted a backup and later removed the backup folder. Then I've created a new backup folder and got the errors.

**Comment by fd0** [comment]
Hm, that's strange: At the moment, restic does not have any local state, all is in the repository. When the repo is removed, everything is gone. So if you did not interrupt a backup, I don't know where the unreferenced packs came from. Could you try to reproduce it, while writing a debug log file?

Run `go run build.go -tags debug`, then use `DEBUG_LOG=restic.log restic backup ...`. Please be aware that the debug log file contains extensive information, this includes possible sensitive things like file names.

**Comment by frederich** [comment]
It's not reproducable.

**Comment by sedrubal** [comment]
I have the same issue. I also interrupted the first backup run but I made the second and third to the same repository. The output of `restic check` is:

```
[...]
pack ffde5f7264a6d56f0f5208e7f4dd88031ed0bc5a23253f999ccd616aa3a3fc71: not referenced in any index
check snapshots, trees and blobs
Fatal: repository contains errors
```

The debug log file unfortunately grew up to over 10GiB. Is there something specific you're looking for?

**Comment by dimejo** [comment]
Does this happen with the newest release (0.8.3.)? Did you try running `rebuild-index`?

**Comment by sedrubal** [comment]
Yes this happened with 0.8.3 and `rebuild-index` solved the problem. Thanks :+1:

**Comment by fd0** [comment]
We should change the UI for this message, thanks for the feedback!
