### ISSUE TITLE
Fatal: number of used blobs is larger than number of available blobs!

### ISSUE THREAD

**Issue by fmarier** [restic/restic#3370]
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.12.12 on linux/amd64 (Ubuntu 20.04 package)

How did you run restic exactly?
-------------------------------
    TMPDIR=/var/tmp/restic-check-tmp RESTIC_PASSWORD=<snip> restic -r sftp:hostname.local: prune

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

ssh to my own local server

Expected behavior
-----------------

Successful prune.

Actual behavior
---------------
```
repository 1e424ff8 opened successfully, password is correct
counting files in repo
building new index for repo
[1:42:28] 100.00%  388033 / 388033 packs
repository contains 388033 packs (2638525 blobs) with 1.838 TiB
processed 2638525 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 23 snapshots
[1:38] 100.00%  23 / 23 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
```

Steps to reproduce the behavior
-------------------------------

Not sure.

Do you have any idea what may have caused this?
-----------------------------------------------

I ran into this problem:

    hash does not match id: want 4f0d26ae93d48ae9a274b0802c208fa47dcc2f97393378d63c208dd8dbcdf176, got 4f1eeb7ed1423358d4c579e641fe40a6340565c64f2df96ac19d28714a769806

and dropping a single snapshot is not an option because the invalid pack is used in **every** snapshot!

Digging more into this problem, I can trigger the error by requesting this pack specifically:

    $ restic -r sftp:hostname.local: cat pack 4f0d26ae93d48ae9a274b0802c208fa47dcc2f97393378d63c208dd8dbcdf176 | sha256sum
    Warning: hash of data does not match ID, want
      4f0d26ae93d48ae9a274b0802c208fa47dcc2f97393378d63c208dd8dbcdf176
    got:
      4f1eeb7ed1423358d4c579e641fe40a6340565c64f2df96ac19d28714a769806
    4f1eeb7ed1423358d4c579e641fe40a6340565c64f2df96ac19d28714a769806  -

If I ssh into my backup server and look at the pack file directly, I can see that the contents of it do not match its name:

    $ sha256sum /mnt/data/home/machine1/data/4f/4f0d26ae93d48ae9a274b0802c208fa47dcc2f97393378d63c208dd8dbcdf176
    4f1eeb7ed1423358d4c579e641fe40a6340565c64f2df96ac19d28714a769806  /mnt/data/home/machine1/data/4f/4f0d26ae93d48ae9a274b0802c208fa47dcc2f97393378d63c208dd8dbcdf176

After looking at the file that is involved in this data corruption:

    $ restic -r sftp:hostname.local: find --pack 4f0d26ae93d48ae9a274b0802c208fa47dcc2f97393378d63c208dd8dbcdf176
    Found blob aec3a1b637a09f173652d509c1f39b8248deeba83d6c74ca99749676d7a4fb75
     ... in file /mnt/pub/video.mkv
         (tree 7b83ceeb0cadb35a6e1103ebb37152e9b1338469fbc782256b95c0ddb6d4cc4e)
     ... in snapshot b0c7a69f (2021-04-16 09:41:47)

Since I still have the original video file, I figured I could just delete the pack and then trigger a new backup to re-upload it:

    $ cd /mnt/data/home/machine1/data/4f/
    $ mv 4f0d26ae93d48ae9a274b0802c208fa47dcc2f97393378d63c208dd8dbcdf176 /root/
    $ restic -r sftp:hostname.local: backup --force
    repository 1e424ff8 opened successfully, password is correct
    
    Files:       620161 new,     0 changed,     0 unmodified
    Dirs:            0 new,     0 changed,     0 unmodified
    Added to the repo: 392.716 MiB
    
    processed 620161 files, 1.637 TiB in 2:02:23
    snapshot 710af622 saved

Then I was able to run `restic prune` successfully.

After that, a simple check passed:

    $ restic -r sftp:hostname.local: check
    repository 1e424ff8 opened successfully, password is correct
    created new cache in /var/tmp/restic-check-tmp/restic-check-cache-878723178
    create exclusive lock for repository
    load indexes
    check all packs
    check snapshots, trees and blobs
    no errors were found

A more thorough check highlighted another corrupt pack:

    $ restic -r sftp:hostname.local: check
    using temporary cache in /var/tmp/restic-check-tmp/restic-check-cache-878723178
    repository 1e424ff8 opened successfully, password is correct
    created new cache in /var/tmp/restic-check-tmp/restic-check-cache-878723178
    create exclusive lock for repository
    load indexes
    check all packs
    check snapshots, trees and blobs
    no errors were found

    $ restic -r sftp:hostname.local: check --read-data
    using temporary cache in /var/tmp/restic-check-tmp/restic-check-cache-502831432
    repository 1e424ff8 opened successfully, password is correct
    created new cache in /var/tmp/restic-check-tmp/restic-check-cache-502831432
    create exclusive lock for repository
    load indexes
    check all packs
    check snapshots, trees and blobs
    read all data
    Pack ID does not match, want b6c9bd10, got 89dc2d85
    [9:30:09] 100.00%  385573 / 385573 items
    duration: 9:30:09
    Fatal: repository contains errors

I removed that one too:

    $ cd /mnt/data/home/machine1/data/b6/
    $ mv b6c9bd10c68347d6bb76328d4bcb4b07c5dbf4f0b9317a4268844ea6c8b0b179 /root/

    $ restic -r sftp:hostname.local: backup --force
    repository 1e424ff8 opened successfully, password is correct
    
    Files:       620209 new,     0 changed,     0 unmodified
    Dirs:            0 new,     0 changed,     0 unmodified
    Added to the repo: 12.156 GiB
    
    processed 620209 files, 1.655 TiB in 2:10:10
    snapshot b63f6890 saved

and the check failed:

    $ restic -r sftp:hostname.local: check --read-data
    using temporary cache in /var/tmp/restic-check-tmp/restic-check-cache-315342197
    repository 1e424ff8 opened successfully, password is correct
    created new cache in /var/tmp/restic-check-tmp/restic-check-cache-315342197
    create exclusive lock for repository
    load indexes
    check all packs
    pack b6c9bd10: does not exist
    check snapshots, trees and blobs
    read all data
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 458.926983ms: file does not exist
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 952.879588ms: file does not exist
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 1.512969815s: file does not exist
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 1.345233563s: file does not exist
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 2.502610537s: file does not exist
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 2.391042907s: file does not exist
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 4.49847416s: file does not exist
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 4.678015434s: file does not exist
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 19.187660462s: file does not exist
    Load(<data/b6c9bd10c6>, 0, 0) returned error, retrying after 14.884802036s: file does not exist
    checkPack: Load: file does not exist
    [9:36:58] 100.00%  388034 / 388034 items
    duration: 9:36:58
    Fatal: repository contains errors

and so I ran a prune:

    $ restic -r sftp:hostname.local: prune
    repository 1e424ff8 opened successfully, password is correct
    counting files in repo
    building new index for repo
    [1:42:28] 100.00%  388033 / 388033 packs
    repository contains 388033 packs (2638525 blobs) with 1.838 TiB
    processed 2638525 blobs: 0 duplicate blobs, 0 B duplicate
    load all snapshots
    find data that is still in use for 23 snapshots
    [1:38] 100.00%  23 / 23 snapshots
    Fatal: number of used blobs is larger than number of available blobs!
    Please report this error (along with the output of the 'prune' run) at
    https://github.com/restic/restic/issues/new

Do you have an idea how to solve the issue?
-------------------------------------------

I could delete all of my snapshots and start over, but I'd rather not lose all of my previous backups if possible.

**Comment by fmarier** [comment]
`check` currently fails due to the missing pack:
```
$ restic -r sftp:hostname.local: check
using temporary cache in /var/tmp/restic-check-tmp/restic-check-cache-975300867
repository 1e424ff8 opened successfully, password is correct
created new cache in /var/tmp/restic-check-tmp/restic-check-cache-975300867
create exclusive lock for repository
load indexes
check all packs
pack b6c9bd10: does not exist
check snapshots, trees and blobs
Fatal: repository contains errors
```

**Comment by aawsome** [comment]
You should first upgrade to 0.12.0. There
- `backup` heals your repo if `backup --force` would do
- `prune` is not only much fast but also able to remove pack file which are definitively not used
- `rebuild-index` is also much faster.

Then, the process is basically:
- manually remove damaged pack files 
- run `rebuild-index` 
- run a `backup` to heal your repo - if your data that was in the damaged pack files still exist to be backuped.

If this fails, you'll have data loss and either need to remove affected snapshots or try the experimental PR #2876

**Comment by fmarier** [comment]
Thanks @aawsome. I was able to fix my repo by following your instructions, even on restic 0.9.6:

1. manually delete the damaged pack
2. `rebuild-index`
3. `backup --force`
4. `prune`

I think the part I was missing was the `rebuild-index` step at the beginning.

**Comment by rawtaz** [comment]
Please update to 0.12.0, there's no reason to use such an old version of restic given the *immense* improvements it's seen since that version (0.9.6).

**Comment by MichaelEischer** [comment]
@fmarier Are there any clues on how the pack files were corrupted? Do you have logs reporting errors when saving the damaged pack files?

**Comment by fmarier** [comment]
> Are there any clues on how the pack files were corrupted? Do you have logs reporting errors when saving the damaged pack files?

Sadly no. I think I've carried those corrupt packs for a while and now thanks to https://github.com/restic/restic/issues/3370#issuecomment-826370979, they are gone.

I have also replaced the hardware which I assume was the root cause of all of this.

**Comment by fmarier** [comment]
That said, I wanted to say that I am very impressed at how robust Restic is in the presence of corruption. It's quite comforting to know that losing a few bytes here and there is not entirely fatal.

**Comment by MichaelEischer** [comment]
Then let's close this issue, as there's nothing left to investigate here.
