### ISSUE TITLE
Apple Silicon binaries

### ISSUE THREAD

**Issue by SebDanielsson** [restic/restic#3377]
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
With Go 1.16.0 merged and where we got official support for Apple Silicon, are there any other roadblocks or could we get binaries for darwin-armv8 now?

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I would like to use Autorestic but the installer wouldn't let me install it easily because of the missing armv8 support. It's possible to run using Rosetta but official support would be much easier.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is awesome. Now using it for all my server backups.

**Comment by MichaelEischer** [comment]
I'm not aware of any blockers. But we'd need someone to test whether the native restic binaries work on Apple Silicon. 

I've opened PR #3394 to also build release binaries of restic.

**Comment by SebDanielsson** [comment]
I can test it for you but I'm not a developer so I need a binary or a step by step tutorial on how to build it. Currently running a M1 MqcBook Air.

**Comment by MichaelEischer** [comment]
- Get the go compiler from https://golang.org/dl/ or if you use homebrew install it using `brew install go`.
- Download the current master branch of restic (https://github.com/restic/restic.git), either using git or just download a zip from Github https://github.com/restic/restic/archive/refs/heads/master.zip .
- Then switch to the folder with restic `cd /path/to/restic` and run `go build ./cmd/restic` then you should end up with a new `restic` binary in the current folder. Check that `./restic version` reports `darwin/arm64`.

**Comment by SebDanielsson** [comment]
Success 🎉

```
restic on master (27141ae) via go v1.16.3
➜ ./restic version
restic 0.12.0-dev (compiled manually) compiled with go1.16.3 on darwin/arm64
```

```
restic on master (27141ae) via go v1.16.3
➜ restic -r ~/backup backup ~/Blog
enter password for repository:
repository af4822b2 opened successfully, password is correct
created new cache in /Users/sebastian/Library/Caches/restic
no parent snapshot found, will read all files

Files:          87 new,     0 changed,     0 unmodified
Dirs:           36 new,     0 changed,     0 unmodified
Added to the repo: 741.457 KiB

processed 87 files, 698.452 KiB in 0:00
snapshot 5a894111 saved
```

**Comment by SebDanielsson** [comment]
Here's a binary if someone is eager to try it before release.
https://easyupload.io/hw55bp
