### ISSUE TITLE
RFC:Include repository name in -v and -v=2 output for backup command

### ISSUE THREAD

**Issue by nexar** [restic/restic#3378]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Include the repository name in -v and -v=2 output when running the backup command

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I am planning on having multiple repositories for my backups with different suppliers as well as locally.  Currently there is a TON of information provided by the -v & -v=2 flags which I re-direct to a file to act as a log of my backup.

It would useful when reviewing this 'log' to know which repository the backup related to.  Without this information I would have to search through my different repositories to find out where the particular snapshot was.

I'm hoping this is not a big change and given the other information already being provided, this key bit of information would be very useful when looking at an old log.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I started using restic less than a week ago.  The documentation is VERY CLEAR and the regulars on the forum are super helpful.  My learning curve for getting up and going was significantly shortened because of these 2 things.  I am looking forward to using restic for a very long time.  Thanks a TON for this great software.

**Comment by rawtaz** [comment]
This is what I get when running restic as usual, without any `-v` flags at all:

~~~
$ ./backup3.sh 
enter password for repository: 
repository fc232af8 opened successfully, password is correct
using parent snapshot ac1d15c3
~~~

So it already contains the identifier for the repository. Are you not seeing this in your output?

**Comment by nexar** [comment]
@rawtaz unfortunately the -v=2 command shows the following first 4 lines:

open repository
lock repository
load index files
using parent snapshot c5fcfd9c

So I guess the backup command without -v has the information we need.  

Although even in your output I would have preferred the actual location whether it was a path or a service provider end point etc which would mean one doesn't need to keep a table of actual repositories with restic repo names.

**Comment by rawtaz** [comment]
Interesting. I tried reproducing not seeing the repository ID by using `-v` and `-v=2` as well as `RESTIC_PASSWORD=...` but all of them still gives me output that includes the repository ID.

Looking into the related code it looks like this:

~~~
	if stdoutIsTerminal() && !opts.JSON {
		id := s.Config().ID
		if len(id) > 8 {
			id = id[:8]
		}
		if !opts.JSON {
			Verbosef("repository %v opened successfully, password is correct\n", id)
		}
	}
~~~

I presume that you don't run your restic instance in an interactive terminal, and this is the reason you're not seeing this text.

Meanwhile the code that outputs the first message for you doesn't care about there being an interactive terminal or not, it just outputs the text:

~~~
	if gopts.verbosity >= 2 && !gopts.JSON {
		Verbosef("open repository\n")
	}
~~~

I would suggest that we change it so that the repository ID is output regardless of the terminal, just like the other text. I'm not sold on outputting the entire repository URL though.

**Comment by nexar** [comment]
@rawtaz I'm piping my output from a cron job.  The repository ID is meaningful to restic but a URL is more meaningful to the user.

**Comment by rawtaz** [comment]
> The repository ID is meaningful to restic but a URL is more meaningful to the user.

Yes, understood. But given that it would be one line of code for your backup script, to append or prepend the repository URL to the log file, and a lot more code (more or less complicated) to do it in restic, my opinion is that it's not worth that additional code and maintenance for a use case that hardly ever comes up for discussion. It's simply not worth the added complexity, even if it's such a simple feature.

It would be one thing if it was some type of information you don't already have and can easily put in your log file, but that's not the case here.

**Comment by nexar** [comment]
@rawtaz Yes fully agree.  I should have thought about including the info in the output at the beginning.  Since this is a more elegant solution anyway I am going to close this request.
