### ISSUE TITLE
Handle "access denied" errors correctly

### ISSUE THREAD

**Issue by JaCoB1123** [restic/restic#338]
When I try to backup my Documents folder, I get the following output:

    C:\Git\restic>.\restic -r D:\Backups\restic backup "C:\Users\Jan Bader\Documents"
    enter password for repository:
    scan [C:\Users\Jan Bader\Documents]
    error for C:\Users\Jan Bader\Documents\Eigene Bilder: open C:\Users\Jan Bader\Documents\Eigene Bilder: Zugriff verweigert
    error for C:\Users\Jan Bader\Documents\Eigene Musik: open C:\Users\Jan Bader\Documents\Eigene Musik: Zugriff verweigert
    error for C:\Users\Jan Bader\Documents\Eigene Videos: open C:\Users\Jan Bader\Documents\Eigene Videos: Zugriff verweigert
    scanned 205 directories, 6787 files in 0:00 MiB
    [0:00] 2.36%  0B/s  5.929 MiB / 251.367 MiB  33 / 6992 items  0 errors  ETA 0:00
    duration: 0:00, 546.02MiB/s
    snapshot 92730b9b saved

Although a snapshot is created, no data is backed up:

    C:\Git\restic>.\restic -r D:\Backups\restic cat snapshot 92730b9b
    enter password for repository:
    {
      "time": "2015-11-03T19:02:30.594317+01:00",
      "tree": "ac08ce34ba4f8123618661bef2425f7028ffb9ac740578a3ee88684d2523fee8",
      "paths": [
        "C:\\Users\\Jan Bader\\Documents"
      ],
      "hostname": "...",
      "username": "..."
    }
    
    C:\Git\restic>.\restic -r D:\Backups\restic cat tree ac08ce34ba4f8123618661bef2425f7028ffb9ac740578a3ee88684d2523fee8
    enter password for repository:
    {
      "nodes": []
    }

**Comment by fd0** [comment]
Hm, strange. Thanks for the report. It looks as if restic is not allowed to open (and therefore: list) the listed directories. Could that be a permission issue?

**Comment by JaCoB1123** [comment]
I guess it's because the three folders are "Junctions" (not sure what they're called). Similar to Linux's symlinks.
When I open Explorer or use `dir` in cmd, the folders are not shown. My minGW Terminal's `ls` shows the following output though:

    lrwxrwxrwx 1 Jan Bader 197121   27 Aug 20 04:12 Eigene Bilder -> /c/Users/Jan Bader/Pictures/
    lrwxrwxrwx 1 Jan Bader 197121   24 Aug 20 04:12 Eigene Musik -> /c/Users/Jan Bader/Music/
    lrwxrwxrwx 1 Jan Bader 197121   25 Aug 20 04:12 Eigene Videos -> /c/Users/Jan Bader/Videos/

**Comment by episource** [comment]
Default permission set for these legacy junctions include: `Everyone (this folder only): Deny List folder / read data`. Those junctions are used for legacy application compatiblity only. Microsoft keeps users from using those folder directly by denying everyone the `List folder / read data` permission on these special folders. Most legacy applications can can continue access files below e.g. `My Documents`, as long as they do not try to iterate files directly below the `My Documents` junctions. You can try this yourself: Enter `C:\Users\<Your Username>\My Documents\AnySubfolder` into the explorer address bar. It will show you a directory listing of `Any Subfolder`. Entering  `C:\Users\<Your Username>\My Documents\` will however show you "Access is denied."

 Any other junction (without the mentioned ACL entry) behaves transparently in windows explorer.

**Comment by fd0** [comment]
Hm, it sounds like that the correct behaviour for restic would be to save them as symlinks instead of reading the content.

**Comment by episource** [comment]
The new title is probably wrong: The Documents folder backed up by `C:\Git\restic>.\restic -r D:\Backups\restic backup "C:\Users\XXX\Documents"` is a "real" folder, not a junction. However by default this folder contains some legacy name junctions ("My Music", "My Pictures", "My Videos") with permission `List folder / read data` denied for everyone. To me it rather looks like restic is not handling the access denied error correctly! 

Nevertheless backing up NTFS `Junctions (Junction Points)`, `Symlinks`, `Volume Mount Points` and `Hard Links` should be fully supported in the medium term. I suppose restic silently follows them right now (assuming necessary permissions).

**Comment by fd0** [comment]
Thanks for the clarification, I've changed the title. @JaCoB1123 was antyhing contained in your `Documents` folder? restic should try to continue despite of errors, so it should have saved everything besides the Junctions.

I suspect that other things like sym- and hardlinks are followed without any special handling. For people who want to help out: In `node_windows.go` code should be added to handle these special files.

**Comment by JaCoB1123** [comment]
Yes, my `Documents` folder is full of documents. 
The Backup is instant though and the resulting snapshot is empty.

**Comment by frederich** [comment]
@JaCoB1123 build your own version with:

```
e:\home\jf\src\github.com\restic\restic>go run build.go -tags debug
e:\home\jf\src\github.com\restic\restic>set DEBUG_LOG=restic.log
e:\home\jf\src\github.com\restic\restic>restic.exe -r e:\tmp\b1 backup e:\
```

Here is my debug [executable](https://drive.google.com/file/d/0B_5bx-2tKBnaOHNuRWxqTHhiOFE/view?usp=sharing).

@JaCoB1123 by the way, try to avoid file or folder names with blanks. That's a big command line pain.

**Comment by JaCoB1123** [comment]
@frederich Thanks, I already did that and got no meaningful output. 
Can't you "step through" somehow and analyze variable values at runtime?

**Comment by frederich** [comment]
@JaCoB1123 you mean interactive debugger? No, I don't like debuggers (see [Torvalds](https://static.lwn.net/2000/0914/a/lt-debugger.php3) why). One interactive Go debugger is [delve](https://github.com/derekparker/delve).

The best way is to add print statements to restic and to build a custom Go tool chain with more print statements at syscall packages. Or use the built-in detectors like [race](https://golang.org/doc/articles/race_detector.html).

@fd0 is it possible to use the `go tool` instead of `go run build.go`? Then @JaCoB1123 can use some detectors.

**Comment by fd0** [comment]
Of course it's possible, `build.go` is just a wrapper around the normal Go toolchain that additionally builds a GOPATH on the fly. Instructions on how to create a proper development environment and be able to use the toolchain directly can be found here: https://github.com/restic/restic/blob/master/CONTRIBUTING.md#development-environment
