### ISSUE TITLE
restic check doesn't obey the RESTIC_CACHE_DIR environment variable

### ISSUE THREAD

**Issue by amuckart** [restic/restic#3382]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
I would like restic to be able to take the configuration for its cache directory from an environment variable, e.g. RESTIC_CACHE_DIR as well as from the cli option --cache-dir.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
This would allow me to set the cache directory in the configuration file that gets sourced from the shell to gather the keys etc. and prevent the situation where someone forgetting to use --cache-dir fills up the root filesystem running an operation in restic that uses the cache.

Thank you.

**Comment by lbausch** [comment]
Couldn't you use `TMPDIR` for that?

**Comment by amuckart** [comment]
> Couldn't you use `TMPDIR` for that?

I could, and for a one-off thing it would work.

The problem is that it affects everything in the shell session, which isn't desirable. I have a specific directory for restic's cache because it gets enormous (over 300G on the system in question) and I don't want that littered with other files that belong in /tmp or to have to make /tmp enormous.

**Comment by lbausch** [comment]
We worked around this by invoking restic like this: `TMPDIR=/path/to/dir restic backup ...`

**Comment by rawtaz** [comment]
@amuckart I fail to understand what you are looking for that doesn't already exist. There's already a `--cache-dir` option to restic, as well as the `RESTIC_CACHE_DIR` environment variable, see: https://restic.readthedocs.io/en/stable/040_backup.html#environment-variables

What's missing?

Regarding `TMPDIR`, what @lbausch said. That's the way to set TMPDIR for that restic invocation only, not affecting anything else.

**Comment by amuckart** [comment]
Except that doesn't work, `restic check` (which creates enormous cache files) doesn't use it:

```Shell
root@prod-backup1:~# export RESTIC_CACHE_DIR=/var/backups/restic/cache/
root@prod-backup1:~# echo "${RESTIC_CACHE_DIR}"
/var/backups/restic/cache/

root@prod-backup1:~# cat /etc/restic/server-backups.env
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset RESTIC_REPOSITORY
unset RESTIC_PASSWORD
export AWS_ACCESS_KEY_ID=[REDACTED]
export AWS_SECRET_ACCESS_KEY=[REDACTED]
export RESTIC_REPOSITORY=[REDACTED]
export RESTIC_PASSWORD=[REDACTED]

root@prod-backup1:~# . /etc/restic/server-backups.env

root@prod-backup1:~# restic check
using temporary cache in /tmp/restic-check-cache-002290356
repository 920b7fbf opened successfully, password is correct
created new cache in /tmp/restic-check-cache-002290356
create exclusive lock for repository
[...]
```

`--cache-dir` is fine so long as you never, ever, forget to use it, but people do and Restic deals extremely poorly with running out of disk. Given that I never want restic's cache to go into TMPDIR, it would be great to be able to set this in the environment file without having to change TMPDIR for everything else in the shell.

**Comment by amuckart** [comment]
I've changed the title of this issue to reflect the problem more accurately.

**Comment by rawtaz** [comment]
Ok, I understand what you mean.

As you can see, `check` uses a temporary cache, and I'm not entirely clear on how it's expected to behave if you give it a cache directory setting where there's already a cache for the current repository. Off the top of my head I would suppose that it should work like this:

- If no cache directory was specified, create a temporary one like it's done currently.
- If a cache directory was specified, and there's already a cache for the current repository in there, give an error message and abort.
- Otherwise, make use of the specified cache directory for the new and temporary cache.

**Comment by amuckart** [comment]
> As you can see, `check` uses a temporary cache, and I'm not entirely clear on how it's expected to behave if you give it a cache directory setting where there's already a cache for the current repository. Off the top of my head I would suppose that it should work like this:

What I want is for it to put the temporary cache in RESTIC_CACHE_DIR not TMPDIR if RESTIC_CACHE_DIR is set. This is the behaviour you get when you set RESTIC_CACHE_DIR=$TMPDIR and I haven't seen it cause any issues.

I get that the cache that `restic check` creates is technically a temporary file, but it's usually an enormous temporary file and on VMs that get created with a 10G root filesystem by default that's a problem :)

**Comment by rawtaz** [comment]
Yes, but do you agree with the process of restic aborting with an error if in the cache dir you specified (regardless of that being through `RESTIC_CACHE_DIR` or `--cache-dir`)? It basically has to, because it's designed in such a way that it is not supposed to reuse an existing cache, so it needs to create a new one.

**Comment by amuckart** [comment]
> Yes, but do you agree with the process of restic aborting with an error if in the cache dir you specified (regardless of that being through `RESTIC_CACHE_DIR` or `--cache-dir`)? It basically has to, because it's designed in such a way that it is not supposed to reuse an existing cache, so it needs to create a new one.

I'm not sure what your question is, I think you might have missed a word.

If you are asking whether I think it should abort if there's an existing cache file in the directory you specify, then no, I don't because the temp cache is always created with a unique name, e.g. `restic-check-cache-811375344` so unless I'm missing something there's no conflict with the existing cache files in the directory.

At the moment I have:
```
~# ls -1rt /var/backups/restic/cache/
CACHEDIR.TAG
restic-check-cache-069606581
920b7fbf065fa0ca6d0d27774f848a32bda4fc99a67c14f09922c8554a0f5ef8
48150b9e7e12c6944e65b22a6fc7fd45ad297c2c1da1521be4343cc2676749d1
restic-check-cache-874316855
```
Running `restic check` isn't touching the existing cache files:
```
:/var/backups/restic/cache# stat --printf '%x %n\n' * | sort
2021-04-06 16:33:15.106277610 +1200 CACHEDIR.TAG
2021-05-04 10:19:21.978906604 +1200 restic-check-cache-069606581
2021-05-05 23:00:09.742938071 +1200 920b7fbf065fa0ca6d0d27774f848a32bda4fc99a67c14f09922c8554a0f5ef8
2021-05-05 23:29:14.663893517 +1200 48150b9e7e12c6944e65b22a6fc7fd45ad297c2c1da1521be4343cc2676749d1
2021-05-06 11:32:25.951288217 +1200 restic-check-cache-874316855
```

**Comment by rawtaz** [comment]
You're right the sentence wasn't complete. Well if restic creates a subfolder in the folder you specify, then it should work (but it should still make sure that the subfolder doesn't already exist of course).

**Comment by amuckart** [comment]
Ahh, right I see where you're coming from. Yes, Restic creates a new directory for the check cache file to go in.

**Comment by rawtaz** [comment]
Let's do this. Anyone care to make a PR out of this idea?
