### ISSUE TITLE
Can't find AuthVersion in AuthUrl - set explicitly

### ISSUE THREAD

**Issue by liambresnahan** [restic/restic#3385]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/amd64

How did you run restic exactly?
-------------------------------

Variables:
`$ export ST_AUTH=http://{{IP_ADDRESS}}:8010/auth/v1.0`
`$ export ST_USER=bkp-usr`
`$ export ST_KEY={{Password}}`
`$ sudo restic -r swift:backup:/new init -v`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Connecting to an OpenStack Swift implementation provided by a QNAP app call 'QuObjects'

Expected behavior
-----------------

Initialize the location 

Actual behavior
---------------

`Fatal: create repository at swift:backup:/new failed: conn.Authenticate: Can't find AuthVersion in AuthUrl - set explicitly`

Steps to reproduce the behavior
-------------------------------

This is reproducible based on the commands specified above. 

Do you have any idea what may have caused this?
-----------------------------------------------

This seems to be referencing a location in the swift library here - https://github.com/ncw/swift/blob/30f52fe4b03e8402805c31a00765762983511f60/auth.go#L55 - which is linked by this line in Restic - https://github.com/restic/restic/blob/74c0607c9222edec3b0c140bb6fee962d6d2e82d/internal/backend/swift/swift.go#L78 . According to the connection I don't see the 'AuthVersion' as set in Restic or how to set it explicitly. 

I also found this error in the forums here - https://forum.restic.net/t/cant-find-authversion-in-authurl-set-explicitly/550 which was fixed by add a /v1 to the URL. In my case adding `$ export ST_AUTH=http://{{IP_ADDRESS}}:8010/auth/v1.0/v1` did not fix the issue

**Comment by MichaelEischer** [comment]
`sudo` clears the environment when calling a child process. Either use `sudo -E` or set the environment variable after switching the user.

The code line you have mentioned checks that "v1" is contained somewhere in the AuthURL, this also matches `[...]/v1.0`.

**Comment by liambresnahan** [comment]
this fixed it. Thank you.
