### ISSUE TITLE
Print snapshot information when reporting tree ID not found in repository

### ISSUE THREAD

**Issue by amuckart** [restic/restic#3391]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
When `restic check` finds a missing tree in a snapshot it reports the tree ID, but not the containing snapshot ID, e.g.:
```
error for tree 6978d196:3 snapshots
  id 6978d1968ea81f413c53070606dc5747f86026b84c5e02380a51259b1509540f not found in repository
error for tree 4d539e4e:3 snapshots
  id 4d539e4e925d212b6e137826c0093738753650630f5c00bb5090af0298f12cbd not found in repository
```
If it reported the containing snapshot at the same time it would save the time of running `restic find --tree` afterwards to locate the snapshot with the problem.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Repairing errors reported by `restic check`

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It is saving me a whole bunch of cloud storage and messing around with s3cmd :)

**Comment by MichaelEischer** [comment]
Thanks for the report. I'm closing this in favor of #720.
