### ISSUE TITLE
Login/Logout Feature

### ISSUE THREAD

**Issue by DillFrescott** [restic/restic#3398]
Output of `restic version`
--------------------------

restic 0.12.0 compiled with go1.15.8 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

A way to "login" so that you don't have to enter the repo password everytime you run a command.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

It would solve having to enter in the repo password every time. This is especially helpful for longer/complex passwords.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes! I love it!

**Comment by rawtaz** [comment]
Well, this can be achieved by simply setting the `RESTIC_PASSWORD` environment variable, or [one of the other password related ones](https://restic.readthedocs.io/en/stable/040_backup.html#environment-variables), or by using e.g. the `--password-file` option. Does that solve the problem?

**Comment by DillFrescott** [comment]
Yes. Thank you
