### ISSUE TITLE
Annotate all error messages, drop external dependency

### ISSUE THREAD

**Issue by scoddy** [restic/restic#34]
Add a string that describes which function has thrown the error

**Comment by fd0** [comment]
Maybe arrar is not the right choice, see https://github.com/juju/errors

**Comment by fd0** [comment]
Drop the depedency on arrar, add functionality to attach a backtrace to all errors and pretty-printing code.

**Comment by fd0** [comment]
Drop the depedency on arrar, add functionality to attach a backtrace to all errors and pretty-printing code.

**Comment by fd0** [comment]
#163 addresses this in a small part by exchanging https://github.com/juju/arrar by https://github.com/juju/errors, but that's not a full solution for this issue.

**Comment by fd0** [comment]
It seems that https://github.com/pkg/errors does a great job for this.

**Comment by fd0** [comment]
Closing, long since implemented.
