### ISSUE TITLE
Retention Policy - A Comparison.

### ISSUE THREAD

**Issue by DiagonalArg** [restic/restic#3410]
I am using btrbk for btrfs snapshots and restic for backups, so I have been able to compare the two retention policies.  Here is [btrbk's](https://digint.ch/btrbk/doc/btrbk.conf.5.html#_retention_policy) and [restic's](https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy).  I find the former intuitive and easy to use.  I find the latter basically unworkable.  So, I'd like to suggest you consider the former.

Example:  I take backups every day and I want to save a backup 1 day old and a backup 1 week old.  If I use a `forget -w2` policy, then the last backup of each of the last two weeks will be retained.  If either of those weeks have no backup, they are ignored.  When starting my daily backups, I only have one backup in the most recent of the two weeks.  So `-w2` will only retain a backup in this most recent week and I will never generate a backup one week old.  I'll never get beyond a single backup one day old.  I am forced then to generate backups each day for 8 days before adding the `w2` policy to my script.  Consider how complicated this would get if I want to keep one backup one month old, one a week old and one a day old.

Btrbk, on the other hand, is very simple, eg:

> daily
> Defines how many days back daily backups should be preserved. The first backup of a day (starting at preserve_hour_of_day) is considered a daily backup.

Similarly for hourly, weekly, etc.  So, `snapshot_preserve 1d 1w` gives me what I want.

I'm using restic 0.12.0 on Ubuntu 20.04.

**Comment by fd0** [comment]
We're using GitHub for bugs and feature requests, discussions should be in the forum. I'll close this issue for now in favor of the following thread there: https://forum.restic.net/t/forget-policy/4014
