### ISSUE TITLE
json output for restore command

### ISSUE THREAD

**Issue by GPh83** [restic/restic#3413]
Output of `restic version`
--------------------------
`restic 0.12.0 compiled with go1.15.8 on windows/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
New functionality : Needed a json output for the restore command.
With it, UI can do report for long operation.
The same output structure as backup was very good.

When I am trying : `.\restic.exe restore latest -r "g:\backup\repo" --target "g:\tmp\"  --json`
There is no json output.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Report user progress of restore command in [resticterm](https://github.com/GPh83/resticterm).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes.
Very happy of this good tool.
Thanks

**Comment by MichaelEischer** [comment]
There's currently no progress information at all, see #426. So it would be necessary to implement both.
