### ISSUE TITLE
Improve output for HTTP errors

### ISSUE THREAD

**Issue by morremeyer** [restic/restic#3418]
Output of `restic version`
--------------------------

```
restic 0.12.0 compiled with go1.15.8 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

With version `0.12.0` and an nginx reverse proxy in front of a minio instance, the following is reported if the nginx configuration is left at default (with `client_max_body_size 1m;`, limiting the maximum size of a PUT/POST body to 1M(i?)B.

```
open repository
lock repository
load index files
no parent snapshot found, will read all files
start scan on [/data]
start backup on [/data]
scan finished in 0.432s: 62 files, 307.373 MiB
Save(<data/badfc598bc>) returned error, retrying after 507.606314ms: wrote 0 bytes instead of the expected 4240867 bytes
Save(<data/fd41e7678b>) returned error, retrying after 656.819981ms: wrote 0 bytes instead of the expected 4408966 bytes
…
```

I think the error handling here could be improved, informing the user about the actual HTTP error when e.g. using S3.
I’m opening this issue mainly to get feedback on the idea. If it’s taken positively, I’ll try to contribute this myself.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

This would make debugging with HTTP backends (at least S3) easier when some part in the request flow is misconfigured or not working correctly.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic is helping me each and every day, making backups something I don’t think about anymore. Thanks for this amazing piece of software!

**Comment by MichaelEischer** [comment]
This has been fixed in #3327. With that fix you'll get errors such as the following one:
```
Save(<data/f6d39f650f>) returned error, retrying after 738.458435ms: client.PutObject: Your socket connection to the server was not read from or written to within the timeout period.
```

That PR is not yet included in a released version of restic, so you can either try a beta release from https://beta.restic.net/?sort=time&order=desc or just restic 0.11.0 instead.
