### ISSUE TITLE
error: NodeFromFileInfo: Listxattr: xattr.list [...] : argument list too long

### ISSUE THREAD

**Issue by pille** [restic/restic#3422]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.5 on linux/amd64

How did you run restic exactly?
-------------------------------
```
/usr/bin/restic backup --verbose --one-file-system /
RESTIC_REPOSITORY="s3:http://s3-storage/restic"
```
What backend/server/service did you use to store the repository?
----------------------------------------------------------------
minIO

Expected behavior
-----------------

no error messages

Actual behavior
---------------
errors:
`error: NodeFromFileInfo: Listxattr: xattr.list /var/cache/dnf/[...] : argument list too long`

Steps to reproduce the behavior
-------------------------------
see above

Do you have any idea what may have caused this?
-----------------------------------------------
xattr module

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by greatroar** [comment]
From Linux's [listxattr(2)](https://man7.org/linux/man-pages/man2/listxattr.2.html):

> As noted in [xattr(7)](https://man7.org/linux/man-pages/man7/xattr.7.html), the VFS imposes a limit of 64 kB on the size of the extended attribute name list returned by listxattr().  If the total size of attribute names attached to a file exceeds this limit, it is no longer possible to retrieve the list of attribute names.

When this happens, E2BIG occurs, which is the error you observed. restic cannot fix this, but it should finish the backup, just with the xattr for this file missing. Is the file in the snapshot?

**Comment by pille** [comment]
the reported files are in the snapshot. they have no extended attributes, though (in source FS).

**Comment by greatroar** [comment]
What is the type of the source FS, and did you use the attr command on the file? I'm not completely sure, but I think lsattr displays a different kind of file attributes from the ones detected by listxattr.

**Comment by pille** [comment]
it's XFS. and you're right. i just tested with `getfattr` and got the exact same error message: `Argument list too long`
is it possible to reflect different types of "soft"-errors in the exit-code? for now everything (file access issues, xattr) is combined in value 3. maybe it's feasible to use a differentiate them as bits of the exit code.

**Comment by MichaelEischer** [comment]
The exit code only has few bits that would be usable. We'd pretty soon run out of bits when trying to differentiate various problems in the exit code. I think https://github.com/restic/restic/issues/1736 would be a better solution for your problem, as it would allow you to silence the xattr errors for specific files.
