### ISSUE TITLE
Copy fails with LoadTree(xyz) returned error id xyz not found in repository

### ISSUE THREAD

**Issue by jakubgs** [restic/restic#3432]
Output of `restic version`
--------------------------
```
restic 0.12.0 compiled with go1.15.8 on linux/amd64
```

How did you run restic exactly?
-------------------------------
I'm syncing a local repository with a remote repository using `sftp` protocol:
```
export RESTIC_REPOSITORY=/backups"
export RESTIC_PASSWORD_FILE=/home/restic/.local_repo_pass"
export RESTIC_REPOSITORY2=sftp:user@host.example.org:./restic"
export RESTIC_PASSWORD_FILE2=/home/restic/.remote_repo_pass"
restic --verbose copy
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Rsync.net

Expected behavior
-----------------
It works.

Actual behavior
---------------
```
LoadTree(a1cae849) returned error id a1cae84958e4c24e0aa731bf7efac1627ca891376ee2fe9dbb47b60eb08f6508 not found in repository
```

Steps to reproduce the behavior
-------------------------------
No idea.

Do you have any idea what may have caused this?
-----------------------------------------------
No idea.

Do you have an idea how to solve the issue?
-------------------------------------------
No idea. I tried removing the snapshot in question - `a1cae849` - but in both repos I just get back:
```
 $ restic snapshots a1cae849
repository 123qwe123 opened successfully, password is correct
Ignoring "a1cae849", it is not a snapshot id
```
So I have no idea what I'm supposed to do.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
What?

**Comment by jakubgs** [comment]
I might add that when I re-run the `copy` command sometimes it works fine without this error.

**Comment by jakubgs** [comment]
Okay. I think I know what's happening. I had another systemd timer running at the same time also doing `restic copy`.

Seems the issue is some kind of race condition when two instances of `restic` try to access the repo, one writing and one readin.

**Comment by MichaelEischer** [comment]
The id `a1cae849` in the log snippet is a tree id, not a snapshot id. That's why there's no corresponding snapshot. Please run `restic check` to make sure that the repository is not damaged.

What did the other systemd timer do? Run a `backup`?

> I might add that when I re-run the copy command sometimes it works fine without this error.

Is the error always the same or does it change?

**Comment by jakubgs** [comment]
>What did the other systemd timer do? Run a backup?

They both run `copy`, but on copies into the repo, and the other out of it.

>Is the error always the same or does it change?

The ID changes.

**Comment by jakubgs** [comment]
Yep, so I can confirm that changing timer schedules so they don't clash makes the error go away.

**Comment by MichaelEischer** [comment]
@jakubgs Does restic print for which snapshot it tried the failed `LoadTree`? My guess would be that that snapshot has just been copied by the other copy run.

What's probably happening here is the following: restic write pack files, indexes and snapshots in an order which ensures that all data on which a snapshot depends has been safely stored first. This essentially means that pack files are written first, then all indexes referencing the pack files and the snapshot is written last. The `copy` command now for copying snapshots loads the repository index first and the iterates over all existing snapshots. And here we have a race condition. Assume that two restic copy instances run in parallel:
restic A is already copying snapshots and currently writes a pack file, restic B starts and begins to load the repository index. restic A uploads a new index and snapshot. restic B finished reading the repository index without the new index from restic A. restic B now discovers the new snapshot from restic A and fails to find the snapshot's data in its repository index.

One way to fix this would be to retrieve the list of snapshots before loading the repository index. However, that would require rearchitecting the way snapshots are currently listed.

**Comment by jakubgs** [comment]
>Does restic print for which snapshot it tried the failed LoadTree?

Sorry, I think I've already purged all logs from those failures. If you want I could try re-creating such a failure again tho.

**Comment by MichaelEischer** [comment]
If it's not too much work, then it would be useful to confirm whether my guess is correct. I'm quite confident that it is, but one never  knows. Although, if the cause is indeed the snapshot listing problem, then it will probably take quite some time until it can be fixed.

**Comment by jakubgs** [comment]
Okay, I switched the timers to run at the same time. We'll see if it happens again today at night.

**Comment by jakubgs** [comment]
I've reproduced the error again, but I'm not sure what you mean by

>Does restic print for which snapshot it tried the failed LoadTree?

Do you want the log message before? It looks like this:
```
snapshot 15d04dd1 of [/docker/xyz/data] at 2021-07-09 01:00:04.546866181 +0000 UTC)
  copy started, this may take a while...
LoadTree(6bade011) returned error id 6bade011b16a6933207235612d049a6714715972c65a3974cae2c08f0eaba337 not found in repository
```

**Comment by MichaelEischer** [comment]
Could you check whether the output of `restic cat snapshot 15d04dd1` includes the following line?
```
    "tree": "6bade011b16a6933207235612d049a6714715972c65a3974cae2c08f0eaba337 ",
```

Judging from the timing that snapshot was probably copied by the other concurrent `copy` run?

**Comment by jakubgs** [comment]
Yes it does.

**Comment by nevermore-muyi** [comment]
I met the same problem when I use kubernetes to backup different PVC parallelly.
[Here ](https://forum.restic.net/t/why-dont-use-tags-to-find-latest-snapshot-when-backup/4824)is the talk.
