### ISSUE TITLE
Output of ls --json is not formatted correctly / invalid json

### ISSUE THREAD

**Issue by MrSlimbrowser** [restic/restic#3441]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on windows/amd64

How did you run restic exactly?
-------------------------------
restic ls latest -p passwort.txt -r repository --json > ls_json_output.txt

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local only

Expected behavior
-----------------
valid json file containing all files/folders from the given repository

Actual behavior
---------------
Output is not a valid json file (missing square bracket at beginning and end and missing commas to separate objects).
Also the first object represents the snapshot itself, not shure if that is supposed to be there.

**Comment by MichaelEischer** [comment]
The output format contains one JSON object per object which are separated by new lines. The intention here is to allow stream processing the output while restic is traversing the snapshot. What would be the benefit of providing the full output as a single JSON object? Unless there's a compelling reason to do so, I don't think we should sacrifice backwards compatibility here.

**Comment by MrSlimbrowser** [comment]
I never said you should fix it and break backwards compatibility in a minor version. But it's something that should be looked at and equalized between different restic --json outputs at some point.
So far, I can see different outputs with the --json option depending on the command:
- Some commands don't support it but don't seem to tell you (e.g. restic list) but give their normal output instead (which would be fine if the documentation would tell which commands support json output and which don't, instead of just the --json option saying "set output mode to JSON for commands that support it"
- "ls" gives objects sperated by new lines
_And besides that also two kinds of objects (having a field of either "struct_type":"snapshot" or "struct_type":"node") even though ls --help says "The "ls" command lists files and directories in a snapshot." and therefore shouldn't contain a snapshot object_
- "cat blob" gives compressed json output as one single "nodes" object containing all other objects
- "cat snapshot" gives formatted json output

Not really intuitive in my opinion and each of them needs to be handled differently.

**Comment by MichaelEischer** [comment]
Essentially there are two output formats: either a single JSON object or a stream of JSON objects separated by newlines. `cat blob` and `cat snapshot` fall into the first category and `ls` into the latter.

Regarding the missing documentation there's #2740 which I still have to review again. And we could also let all commands fail which don't support `--json`.

The initial json output of the ls command was initially a single JSON object #1953 and was changed to streaming output format in #1962. I tend to agree with the argument there about large output, e.g. `ls --recursive --json 12345678` results in 250MB for the backup of my computer.

**Comment by MichaelEischer** [comment]
The JSON output format is by now documented at https://restic.readthedocs.io/en/stable/075_scripting.html#json-output .
