### ISSUE TITLE
Check fails to locate pack files on version 0.12

### ISSUE THREAD

**Issue by fthdgn** [restic/restic#3443]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on windows/amd64
restic 0.12.0 compiled with go1.15.8 on darwin/amd64

How did you run restic exactly?
-------------------------------
.\restic_0.12.0_windows_amd64.exe -r Z:\backup\restic\ check
./restic_0.12.0_darwin_amd64 -r /Volumes/hdd/backup/restic check

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Samba drive

Expected behavior
-----------------
Check operation is completed without any error just like on version 0.11

Actual behavior
---------------
On Windows:
PS C:\Users\fatih\Desktop> .\restic_0.12.0_windows_amd64.exe -r Z:\backup\restic\ check
using temporary cache in C:\Users\fatih\AppData\Local\Temp\restic-check-cache-390842343
repository 1bd5819f opened successfully, password is correct
created new cache in C:\Users\fatih\AppData\Local\Temp\restic-check-cache-390842343
create exclusive lock for repository
load indexes
check all packs
pack cfa94e86: does not exist
pack c39ba9e1: does not exist
pack 12f71a4d: does not exist
pack a74ed5ce: does not exist

On Mac:
fatih@macbook Downloads % ./restic_0.12.0_darwin_amd64 -r /Volumes/hdd/backup/restic check
using temporary cache in /var/folders/s_/r753tsg13qn0mt93cr4ws4m40000gq/T/restic-check-cache-132253333
repository 1bd5819f opened successfully, password is correct
created new cache in /var/folders/s_/r753tsg13qn0mt93cr4ws4m40000gq/T/restic-check-cache-132253333
create exclusive lock for repository
load indexes
check all packs
List(data) returned error, retrying after 552.330144ms: fdopendir: not a directory
List(data) returned error, retrying after 1.080381816s: fdopendir: not a directory
List(data) returned error, retrying after 1.31013006s: fdopendir: not a directory
List(data) returned error, retrying after 1.582392691s: fdopendir: not a directory

Steps to reproduce the behavior
-------------------------------
I cannot find any way to reproduce the error. I'll describe the all events.

I have a restic repository on my Raspberry Pi which I access from Windows as Samba drive on Z:\backup\restic. I backup my Windows PC daily on this repo.

Today I decided to backup my Macbook to the same repository, and mounted the samba as /Volumes/hdd/backup/restic.
Later today I noticed that my repository gives error on Windows because it cannot find some files.  Then I run rebuild-index and it deleted all indices and kept a single 1KB index file, while data directory is over 50GB.

I could not recover my repository and deleted all the repository, and created a new repository from windows on the same location and waited cron jobs to run and backup from Mac and Windows.

After cron jobs run, I run check command from windows and it gives error about missing pack files. However, these pack files are not missing.

Then I run check command from Mac and it to raise some errors saying "fdopendir: not a directory".

Then I run check command from Raspberry Pi, which has "restic 0.9.4 compiled with go1.11.5 on linux/arm", directly, and it says "no errors were found".

Then I downloaded 0.11 version on both Windows and Mac, and they too says "no errors were found".

I created a second repository to reproduce the error, but I cannot reproduce the error. This new repository passes check on 0.12 on both mac and windows.

Summary:
I have a repository on Samba drive.
Version 0.12 on Mac and Windows fails to check this repository.
Mac says "List(data) returned error, retrying after 552.330144ms: fdopendir: not a directory"
Windows says:"pack cfa94e86: does not exist", even though pack file exists
Version 0.11 on Mac and Windows successfully checks the same repository.

**Comment by fthdgn** [comment]
I created local config from rclone
``` 
[loc]
type = local
``` 

And run ` .\restic_0.12.0_windows_amd64.exe -r rclone:loc:Z:\backup\restic check`
It completed without any error.

` .\restic_0.12.0_windows_amd64.exe -r Z:\backup\restic check` continues to report missing  pack files incorrectly.

**Comment by fthdgn** [comment]
[restic_copy.zip](https://github.com/restic/restic/files/6719856/restic_copy.zip)

I uploaded the repository. You don't need to run it on samba drive.  You can see the commands I run on README file inside the archive.

**Comment by MichaelEischer** [comment]
The `fdopendir` error has already been fixed by #3308. And my guess would be that it also fixes the problem on windows. Could you try whether a beta build of restic from https://beta.restic.net/?sort=time&order=desc fixes the issue?

**Comment by fthdgn** [comment]
I tried `restic_v0.12.0-122-g58be5172_windows_amd64.exe` and the problem is fixed.
