### ISSUE TITLE
Prune - option to repack based on per-pack unused

### ISSUE THREAD

**Issue by superdanm2** [restic/restic#3444]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Love the enhancements in 0.12.0 regarding `--max-unused limit`. However, suppose you have some highly used (but not entirely used) packs mixed with some barely used packs. I believe with this option, when the threshold is met, even those highly used packs will still be repacked.

Would it be possible to provide a "% of unused" option that is evaluated per-pack?

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Prevent excessive/inefficient download/upload during a prune operation.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I love restic.

**Comment by aawsome** [comment]
Can you give an example where the current prune bevavior is not optiomal in you opinion?

During `prune` the packs are sorted by the per-pack unused ratio. Packs that are highly used (but not entirely used) are sorted to the end of the list of potential packs-to-repack. So those packs will be likely not repacked - except you chose `max-unused=0`
So I believe that the current prune implementation already solves the problem you are trying to solve.

**Comment by superdanm2** [comment]
On your response I've explored the code and I re-read the docs. I believe I misunderstood this feature. I think you're right.

Perhaps I was confused by the statement "Restic tries to repack as little data as possible while still ensuring this limit for unused data" (https://restic.readthedocs.io/en/latest/060_forget.html). I thought this was describing the no-op that would occur if the repo was in good standing. I now realize it means it will stop once it has restored the repo to the specified limit.

Thank you for taking the time and apologize for the superfluous request.
