### ISSUE TITLE
Disable restic maintenanceFrequency

### ISSUE THREAD

**Issue by bdietrich12** [restic/restic#3447]
Hello, 

i should like disable the restic maintenanceFrequency on a resticRespository, because it's run by multiple velero/restic on different kubernetes cluster.

I read the documentation, we can precise when run the maintenance like : 

spec:
  backupStorageLocation: restic-tests
  maintenanceFrequency: 168h0m0s

I try ro use : 

  maintenanceFrequency: Never
  maintenanceFrequency: never
  maintenanceFrequency: forget

But i can't sync with restic repository...

  maintenanceFrequency: 0h0m0s

It run the maintenance anyways.

Is it possible to disable the restic maintenance, because the maintenance (prune command) is running during the velero's backups. 

The prune commande lock the restic repositories and velero is not able to performs backups.

**Comment by rawtaz** [comment]
Sorry, but this is something completely outside of restic, there are no `maintenanceFrequency` settings in restic, I'm guessing it's a Velero thing. I noticed you asked in the forum, which is a much better place for discussing this (although it should really be done in a Velero forum instead), so I'm closing this issue :)
