### ISSUE TITLE
Support for matching untagged snapshots

### ISSUE THREAD

**Issue by systemmonkey42** [restic/restic#3456]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Support for filtering snapshots by "untagged" state when listing/forgetting.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I have a need to list and forget (apply policy) to a repository but I need all tagged snapshots to be ignored (kept).
In my environment, untagged snapshots are automated, while tagged snapshots are special cases.

I want to ensure the policy used for `restic forget` only applies to untagged snapshots.

I have provided an example pull request which accept the empty tag as a selector which matches snapshots with no tags.

For example:  The following will match "untagged" snapshots only.
```
restic snapshots --tag ''
```

This also works for 
```
restic forget --tag '' -l 1          --- Apply forget policy to untagged snapshots
restic forget --keep-tag '' -l 1     --- Apply forget policy by keep all untagged snapshots.
```

The empty snapshot name can optionally be replaced with a keyword (like `none` or `untagged`).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
always

**Comment by MichaelEischer** [comment]
#3457 was merged.
