### ISSUE TITLE
Cross platform snapshot paths

### ISSUE THREAD

**Issue by juanrgm** [restic/restic#3460]
Output of `restic version`
--------------------------

> restic 0.12.0 compiled with go1.15.8 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I would need to specify the snapshot path for it matches between Windows and Unix.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I am building a open source backup system and I am trying add a backend for restic but I have problems with the snapshot path, because it is inconsistent between operative systems.

Really, the snapshot paths only it is used as tags, and it could be any thing. They are a reference about where it were data, but also it could be a id about what data it is. It is quite likely that data location changes because any reason in the future, but the data context always will be the same.

Use a id for the snapshot path is not possible because it is always converted to absolute and it also depends of the operative system, so there is a inconsistence: https://github.com/restic/restic/blob/fdbd65485e1d8b4f56159f7120a3277979921f4e/internal/restic/snapshot.go#L38

There are some issues opened about this but all are related with to allow relative paths and not with avoid the path normalization based in the operative system.

### Possible solutions

1. Add option to overwrite snapshot paths: https://github.com/restic/restic/pull/3200.

This solution is not completely valid, read motive here: https://github.com/restic/restic/pull/3200#issuecomment-868474255

2. Add option to save raw paths (`--raw-paths`): https://github.com/juanrgm/restic/compare/backup-set-path...backup-raw-paths

If to skip completely the path normalization can be a problem, it could add a rules to avoid invalid chars.

3. Add option to save relative paths (`--relative-paths`): same proble that the first solution.
4. Add option to force the use of path conversions in Unix format (`--unix-paths`).
5. Add option to force the use of path conversions in Windows format  (`--win-paths`).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by rawtaz** [comment]
Please be more specific - what are you actually suggesting as a solution to your problem?

**Comment by juanrgm** [comment]
Thanks for your reply.

> Please be more specific - what are you actually suggesting as a solution to your problem?

I edited the issue a bit adding some details, but basically I am proposing a solution to have the control over the snapshots paths to save.

**Comment by rawtaz** [comment]
Right, so in summary, you are asking that restic is changed so that it will let you specify the complete paths that are saved for a snapshot.

**Comment by juanrgm** [comment]
Yep. 

I would like to know if core maintainers are agree with any solutions (or maybe other) to continue with the PR or not.

I know that there are pending pull requests and I would not want to increase the queue in vain.

**Comment by MichaelEischer** [comment]
I don't understand the use case. Paths on Unix/Windows are platform-specific, thus it sounds wrong to completely ignore the difference. And then `--set-path` should be sufficient?

> but also it could be a id about what data it is

This sounds to me like you're trying to "tag" a snapshot via its backup path. Wouldn't it be possible to use tags instead?

**Comment by juanrgm** [comment]
> I don't understand the use case. Paths on Unix/Windows are platform-specific, thus it sounds wrong to completely ignore the difference. And then `--set-path` should be sufficient?

`--set-path` keeps converting the path into absolute (ex: `--set-path /data` -> `D:\data`).

> This sounds to me like you're trying to "tag" a snapshot via its backup path. Wouldn't it be possible to use tags instead?

That is the only alternative, but if the path is different between snapshots, restic will re-scan all the directory again, and what happens with the deduplicy? Does it will work in snapshots with differents paths? `--parent` should to fix these problems, right?

**Comment by rawtaz** [comment]
@juanrgm Deduplication will still be 100% effective regardless of the paths and parent snapshot used, and restic will still only upload what actually changed since the last backup. Using a parent snapshot that contains the files you are backing up again only affects the scanning of local files - when restic knows a parent snapshot that contains the same files, it can determine by metadata which of them hasn't changed since the last backup, and then doesn't have to scan them again to find data blocks that has possibly changed. But neither of this affects deduplication or re-uploading. This is purely about the scanning of the source data to back up. In simple terms, without a good parent snapshot, scanning takes a bit more time, that's it.

**Comment by MichaelEischer** [comment]
> > I don't understand the use case. Paths on Unix/Windows are platform-specific, thus it sounds wrong to completely ignore the difference. And then `--set-path` should be sufficient?
> 
> `--set-path` keeps converting the path into absolute (ex: `--set-path /data` -> `D:\data`).

But when is it necessary to refer to files using the same path, when the files were backed up on different systems? I understand that file paths are converted, but I still don't know enough about your use case to understand when that could be a problem.

**Comment by juanrgm** [comment]
The main purpose was to avoid the OS dependency when an app is migrated between systems and also abstract the data path in case it was changed in the future (due to system change or simply path change).

Using tags and specifying **always** `--parent` (for speed up) I can fix that problems.

**Comment by MichaelEischer** [comment]
Restic cannot abstract away differences between operating systems. In particular, file metadata (in particular ACLs) can only be transferred in a lossy way between OSes. Judging from the description here, what's actually wanted is more like #4026.
