### ISSUE TITLE
pack size does not match calculated size from index

### ISSUE THREAD

**Issue by saberya** [restic/restic#3461]
Output of `restic version`
--------------------------
0.12.1

How did you run restic exactly?
-------------------------------
After backup failed,i execute following command

[root@autodb2 ~]#  /usr/local/bin/restic -r /mnt/backup/autodb2/smb_phab check --password-file=/root/scripts/restic-password-file --verbose
using temporary cache in /tmp/restic-check-cache-758003808
repository 6890ac2c opened successfully, password is correct
created new cache in /tmp/restic-check-cache-758003808
create exclusive lock for repository
load indexes
check all packs
pack 19d67747: unexpected file size: got 9043968, expected 4698238
check snapshots, trees and blobs
[0:00] 100.00%  10 / 10 snapshots
Fatal: repository contains errors

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
I use restic to backup mysqldump file (*.sql.gz) with the size of 20GB one file;
I mount the remote filesystem (**smb**) to local
mount command:_mount -t cifs -o "rw,username=username,password=8888888,uid=root" //backupserver01.gggg.net/backup/autodb2 /mnt/backup/autodb2_

Expected behavior
-----------------

the restic check should contain no error

Actual behavior
---------------
restic backup failed

Steps to reproduce the behavior
-------------------------------
there were always err msg causing by corrupted file like "pack 19d67747: unexpected file size: got 9043968, expected 4698238"
or "not referenced in any index"

Do you have any idea what may have caused this?
-----------------------------------------------
with same backend filesytem(smb), almost backup operations in other repos can success, but this repo was always failed.

Do you have an idea how to solve the issue?
-------------------------------------------
**_export GODEBUG=asyncpreemptoff=1_
i follow this advice, but my local restic run as a binary file without go envirnoment,I'm not sure it will work**
And the following command and msg are the progress that i resovle this problem manually:

**Firstly, i try to prune clean the err file:**
[root@autodb2 ~]# /usr/local/bin/restic -r /mnt/backup/autodb2/smb_phab prune --password-file=/root/scripts/restic-password-file --verbose
repository 6890ac2c opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 10 snapshots
[0:00] 100.00%  10 / 10 snapshots
searching used packs...
collecting packs for deletion and repacking
pack **19d67747**: calculated size 4698238 does not match real size 9043968
                           [0:00] 10.10%  2310 / 22861 packs processed
Fatal: pack size does not match calculated size from index
emmm,unsurprisingly，I had expected this result

**Secondly,**
[root@autodb2 ~]# /usr/local/bin/restic -r /mnt/backup/autodb2/smb_phab find --pack 19d67747 --password-file=/root/scripts/restic-password-file --verbose
repository 6890ac2c opened successfully, password is correct
header length is invalid
readHeader
github.com/restic/restic/internal/pack.readRecords
        /restic/internal/pack/pack.go:206
github.com/restic/restic/internal/pack.readHeader
        /restic/internal/pack/pack.go:231
github.com/restic/restic/internal/pack.List
        /restic/internal/pack/pack.go:258
github.com/restic/restic/internal/repository.(*Repository).ListPack
        /restic/internal/repository/repository.go:685
main.(*Finder).packsToBlobs.func1
        /restic/cmd/restic/cmd_find.go:431
github.com/restic/restic/internal/repository.(*Repository).List.func1
        /restic/internal/repository/repository.go:676
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1.1
        /restic/internal/backend/backend_retry.go:143
github.com/restic/restic/internal/backend/local.visitFiles
        /restic/internal/backend/local/local.go:315
github.com/restic/restic/internal/backend/local.visitDirs
        /restic/internal/backend/local/local.go:282
github.com/restic/restic/internal/backend/local.(*Local).List
        /restic/internal/backend/local/local.go:246
github.com/restic/restic/internal/backend.(*RetryBackend).List.func1
        /restic/internal/backend/backend_retry.go:137
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
        /home/build/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.0.2/retry.go:52
github.com/cenkalti/backoff/v4.RetryNotify
        /home/build/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.0.2/retry.go:31
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        /restic/internal/backend/backend_retry.go:46
github.com/restic/restic/internal/backend.(*RetryBackend).List
        /restic/internal/backend/backend_retry.go:136
github.com/restic/restic/internal/repository.(*Repository).List
        /restic/internal/repository/repository.go:670
main.(*Finder).packsToBlobs
        /restic/cmd/restic/cmd_find.go:419
main.runFind
        /restic/cmd/restic/cmd_find.go:566
main.glob..func10
        /restic/cmd/restic/cmd_find.go:39
github.com/spf13/cobra.(*Command).execute
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /restic/cmd/restic/main.go:98
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374

alright,i dont know what it is

**thirdly**
[root@autodb2 ~]# /usr/local/bin/restic -r /mnt/backup/autodb2/smb_phab rebuild-index --password-file=/root/scripts/restic-password-file --verbose
repository 6890ac2c opened successfully, password is correct
loading indexes...
getting pack files to read...
reindexing pack file 19d67747afd4c2c387bdcd6f1f85203937869ad7bf8ad7cd64905f4ffeebd837 with unexpected size 9043968 instead of 4698238
reading pack files
[0:00] 100.00%  1 / 1 packs
skipped incomplete pack file: 19d67747afd4c2c387bdcd6f1f85203937869ad7bf8ad7cd64905f4ffeebd837
rebuilding index
[0:00] 100.00%  22860 / 22861 packs processed
deleting obsolete index files
[0:00] 100.00%  5 / 5 files deleted
done

_i dont konw Why i have to execute the restic **rebuild-index** twice each time to take effect_

**Fourthly,**
[root@autodb2 ~]# /usr/local/bin/restic -r /mnt/backup/autodb2/smb_phab check --password-file=/root/scripts/restic-password-file --verbose
using temporary cache in /tmp/restic-check-cache-814521247
repository 6890ac2c opened successfully, password is correct
created new cache in /tmp/restic-check-cache-814521247
create exclusive lock for repository
load indexes
check all packs
pack 19d67747: not referenced in any index
1 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
check snapshots, trees and blobs
error for tree 1f2c2b60:apshots
  tree 1f2c2b60: file "phabricator_smb_210720_040001.sql.gz_split040" blob f3aa71300f59121a9921be90715a6ad4de6944fe62353c1e1330d5cf19b49f67 not found in index
  tree 1f2c2b60: file "phabricator_smb_210720_040001.sql.gz_split040" blob deab8e5a8dbba0d20c676a029f0d75835bd9081449507641eb2f4d03e70d9a2a not found in index
  tree 1f2c2b60: file "phabricator_smb_210720_040001.sql.gz_split040" blob 691006c1095ede647077ef39b2ef426d2d9c1d633e7af2b1de69ed1efa95d72d not found in index
  tree 1f2c2b60: file "phabricator_smb_210720_040001.sql.gz_split040" blob f134abd72f4d8759b44513f853a33e2d83b599fbba8f9e1e246e0ae29f000bc4 not found in index
[0:00] 100.00%  10 / 10 snapshots
Fatal: repository contains errors

"phabricator_smb_210720_040001.sql.gz_split040",i know this file come from which snapshot, so i'll delete this snapshot

**Fifthly,**
[root@autodb2 ~]# /usr/local/bin/restic -r /mnt/backup/autodb2/smb_phab rebuild-index --password-file=/root/scripts/restic-password-file --verbose
repository 6890ac2c opened successfully, password is correct
loading indexes...
getting pack files to read...
adding pack file to index 19d67747afd4c2c387bdcd6f1f85203937869ad7bf8ad7cd64905f4ffeebd837
reading pack files
[0:00] 100.00%  1 / 1 packs
skipped incomplete pack file: 19d67747afd4c2c387bdcd6f1f85203937869ad7bf8ad7cd64905f4ffeebd837
rebuilding index
[0:00] 100.00%  22860 / 22861 packs processed
deleting obsolete index files
[0:00] 100.00%  2 / 2 files deleted
done

[root@autodb2 ~]# /usr/local/bin/restic -r /mnt/backup/autodb2/smb_phab forget d617f594 --prune --password-file=/root/scripts/restic-password-file --verbose
repository 6890ac2c opened successfully, password is correct
[0:00] 100.00%  1 / 1 files deleted
1 snapshots have been removed, running prune
loading indexes...
loading all snapshots...
finding data that is still in use for 9 snapshots
[0:00] 100.00%  9 / 9 snapshots
searching used packs...
collecting packs for deletion and repacking
will remove pack 19d67747 as it is unused and not indexed
[0:50] 100.00%  22860 / 22860 packs processed

used:             47156 blobs / 68.040 GiB
unused:           31568 blobs / 45.355 GiB
unreferenced:                   8.625 MiB
total:            78724 blobs / 113.404 GiB
unused size: 39.99% of total size

to repack:            0 blobs / 0 B
this removes          0 blobs / 0 B
to delete:        31568 blobs / 45.364 GiB
total prune:      31568 blobs / 45.364 GiB
remaining:        47156 blobs / 68.040 GiB
unused size after prune: 0 B (0.00% of remaining size)

totally used packs:      13689
partly used packs:           0
unused packs:             9171

to keep:        13689 packs
to repack:          0 packs
to delete:       9171 packs
to delete:          1 unreferenced packs

deleting unreferenced packs
[0:00] 100.00%  1 / 1 files deleted
rebuilding index
[0:00] 100.00%  13689 / 13689 packs processed
deleting obsolete index files
[0:00] 100.00%  2 / 2 files deleted
removing 9171 old packs
[0:16] 100.00%  9171 / 9171 files deleted
done

This mistake comes up a lot. All in all, i hope that  there is some way to resolve it, manual operations take me s lot of time.
Most importantly, I wrote timed tasks, and every error was unexpected and had to spend extra time dealing with it
If anyone can help, I'd be grateful

OK,succeed;
Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

when it run normally, it help me so much, it is a good tool

**Comment by MichaelEischer** [comment]
> i dont konw Why i have to execute the restic **rebuild-index** twice each time to take effect

> **Fifthly,**
> [root@autodb2 ~]# /usr/local/bin/restic -r /mnt/backup/autodb2/smb_phab rebuild-index --password-file=/root/scripts/restic-password-file --verbose

The second `rebuild-index` call had no effect, so I'm not sure what you mean by having to run it twice? 


> pack 19d67747: unexpected file size: got 9043968, expected 4698238

I don't recall that there have been any problems with the file size calculation so far, so this indicates that something filled the file with garbage data.  That still sounds a lot like the CIFS problem. What's interesting is that `find` reported a `header length is invalid` error. This supports my point that the filesystem didn't store what it was supposed to.

> _export GODEBUG=asyncpreemptoff=1_
> i follow this advice, but my local restic run as a binary file without go envirnoment,I'm not sure it will work

Did you ensure that the environment variables also applies to your "timed tasks"? (cron jobs I suppose?). That variable must be set **every single time** you call restic. The simplest way to ensure that would be to write a small bash wrapper script.

What do you mean with "go envirnoment"? The `GODEBUG` environment variable is interpreted by the `restic` binary, there's no need to have an installed golang compiler.

>  ```
> {<data/297c3a6c> <data/2e177d71> <data/c8c0a201> <data/d50489a5>} not found in the index
> ```
You can use `find --blob 297c3a6c ...` to discover the affected snapshots and delete them. However, unless the storage problems have been fixed, this and similar errors will continue to show up. These blobs are not stored directly in the data folder, but should be located in one of the pack files.

Instead of a full `check --read-data` you could incrementally run `check --read-data-subset x/y`. Or try to use the `ionice` tool to reduce restic's io priority.


> ## Output of `restic version`
> 
> 0.12.1

That restic version hasn't been released yet, so I just assume you are using restic 0.12.0. And the full output of `restic version` should rather look like this:
```
restic 0.12.0 compiled with go1.15.0 on linux/amd64
```

**Comment by MichaelEischer** [comment]
Instead of mounting the repository via SMB/CIFS you could also use sftp to access it or use the rest-server.

**Comment by MichaelEischer** [comment]
Closing this issue as there has been no feedback in a month and the symptoms are consistent with the discussed CIFS problem.
