### ISSUE TITLE
Deprecation warning breaks json output

### ISSUE THREAD

**Issue by seqizz** [restic/restic#3462]
Output of `restic version`
--------------------------
Close to master: `restic 0.12.0 (v0.12.0-122-g58be5172-dirty) compiled with go1.16 on linux/amd64`

How did you run restic exactly?
-------------------------------

`restic snapshots -q --json --last`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

s3/minio

Expected behavior
-----------------

Deprecation warning should not be visible

Actual behavior
---------------

```
~> restic snapshots -q --json --last
Flag --last has been deprecated, use --latest 1
[{"time":"2021-07-23T04:23:20.304961144Z","parent":"58e05e061d4d47c00be3a770aac93e67ab25ee17f2aa44d84ed45945f6f3f9fb","tree":"a1fc42fad9ce71673c7311fa452137048f6c4cfcf31a1382e112a7a9a7e5b952","paths":["/mypath","/home"],"hostname":"myhostname","username":"root","tags":["mytag"],"id":"e785671781abbe9660ef5133221adcf73dcd7f300ee074de9000ec38c14b34e8","short_id":"e7856717"}]
```

Do you have an idea how to solve the issue?
-------------------------------------------

`--json` parameter should make warnings like deprecation or cache expiration hidden

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

All day, every day. But you still didn't add a "sponsor" button here! :smile_cat:

**Comment by MichaelEischer** [comment]
The deprecation message is only output on stderr. If you just parse stdout, then the json output should work as before.

**Comment by seqizz** [comment]
I should've guessed it. Thanks again :+1:
