### ISSUE TITLE
restic hangs randomly on backup, prune or check

### ISSUE THREAD

**Issue by CidTori** [restic/restic#3466]
Output of `restic version`
--------------------------

`restic 0.12.0 compiled with go1.15.8 on windows/amd64`

How did you run restic exactly?
-------------------------------

`restic backup --password-file "%USERPROFILE%\%PASSWORD_FILE_PATH%" --repo "%USERPROFILE%\%REPO_PATH%" %USERPROFILE%\%DATA_PATH% --exclude-file=%USERPROFILE%\%EXCLUDE_FILE_PATH% --verbose=3`

`restic check --password-file "%USERPROFILE%\%PASSWORD_FILE_PATH%" --repo "%USERPROFILE%\%REPO_PATH%" --verbose=3`

`restic prune --password-file "%USERPROFILE%\%PASSWORD_FILE_PATH%" --repo "%USERPROFILE%\%REPO_PATH%" --verbose=3`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

The same drive containing the backed-up data (my `%USERPROFILE%` on `C:`, on a Windows 10 laptop, with a NTFS file system).

Expected behavior
-----------------

Perform the backup/prune/check entirely.

Actual behavior
---------------

Until now, restic 0.11 worked without problem on my laptop.
But since about a week ago, it started hanging during backup.
Here is the output of a `backup` with `--verbose=3`:
```
open repository
repository 1a2b3c4d opened successfully, password is correct
lock repository
load index files
unchanged /C/Users/...
...
unchanged /C/Users/...
[0:24] 503 files 2.009 GiB, total 1827 files 9.312 GiB, 17 errors
```
But during the backup, it just stops at random: the "unchanged" files printing stops, and the "progress" line stops being updated, except for the time spent between square brackets (and the ETA when there is one), for a couple seconds, before stopping too.
It does not stop at a specific time or file, it really seems random.
Sometimes, when it stops, the "progress" line is empty.
Rarely, it even stops before that, at the "load index files" or even the "open repository" lines.
When it stops, Ctrl+C does nothing, I have to close the window.
(The errors where present before this issue, it's just some Cygwin "symlinks" that can't be accessed by restic)

I have 3 folders to backup, one with less than 100 files, one with about 7000 files, and one with about 130000 files.
It rarely stops during the small one's backup (and when it does, it's during "open repository" or "load index files"), about 50% of the time during the middle one's backup, and 100% of the time during the big one's backup.

I tried using a new repository, without improvement.
When I do, `init` works fine, and the first `backup` too (even with the big folder), but then it starts stopping randomly again.

When I try a `check` on the repo after a failed backup, of course it says:
```
unable to create lock in backend: repository is already locked by PID 12345 on MACHINE by USER (UID 0, GID 0)
```
But when I use `unlock` on the repo, even if it says that it `successfully removed locks`, some lock files are still present in the `lock` directory of the repo.
If I remove them manually and retry the `check`, it proceeds, but then stops too:
```
using temporary cache in C:\Users\...
repository 1a2b3c4d opened successfully, password is correct
created new cache in C:\Users\...
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
[0:05] 23.33%  7 / 30 snapshots
```
After a couple of seconds, the "progress" line stops updating.

Same thing with `prune`:
```
repository 1a2b3c4d opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 30 snapshots
[0:14] 23.33%  7 / 30 snapshots
```

Using an account with admin rights didn't improve anything.
Same thing with updating to 0.12.

Steps to reproduce the behavior
-------------------------------

Do a backup of a really big folder (~100000 files) locally.

Do you have any idea what may have caused this?
-----------------------------------------------

My laptop was lent to me, and is partially controlled, by my employer.
So they may have changed something on it remotely without warning me, but I don't know what.

Do you have an idea how to solve the issue?
-------------------------------------------

No 😕

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I was searching for a simple portable CLI backup application with deduplication, and restic was exactly what I needed!

**Comment by MichaelEischer** [comment]
What are the symptoms when restic hangs during these commands? Is it just sitting there doing nothing or does restic consume lots of CPU?

Could you try whether restic 0.12.1 helps in any way?

Did I understand correctly that you back up files stored locally into a repository stored locally? How do you run restic (CMD/powershell/msys/?) ? 

I'm currently not aware of any recent reports of restic hanging at points in time, especially not across multiple different commands. My first guess would be some anti-virus related issues, but that's nothing more than a hunch. Did you restart the laptop recently (I'm asking because I usually don't restart unless there are updates)?

**Comment by CidTori** [comment]
- It does nothing (no CPU use).
- Nothing changed with 0.12.1.
- Yes, I back up files stored locally into a repository stored locally. I run restic with CMD.
- I do restart my laptop regularly (once a day). I recently changed my laptop (with another one from my employer), and the problem is still there. You may be right about the antivirus, do you think restic could give more feedback about what is blocking it?

**Comment by MichaelEischer** [comment]
Hmm, I'm not too familiar with debugging such issues on Windows, maybe someone else has an idea?

Does the verbose backup progress get stuck maybe at a similar file every time?

Besides that a debug build of restic could provide some more insights, see https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs for a short summary of the necessary steps.

Other possibilities I can think of would be trying to get a stack trace using Process Explorer, unfortunately there's no easy way to access the builtin mechanism in Go on windows.

**Comment by MichaelEischer** [comment]
Closing this issue as there is not enough information to investigate.
