### ISSUE TITLE
Wikipedia article

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [restic/restic#3472]
I added restic to the [List of backup software](https://en.wikipedia.org/wiki/List_of_backup_software#Free_and_open-source_software) (english Wikipedia).

But the link will be removed there because currently there is no Wikipedia-entry for restic itself. If anyone want to... :)

The same problem goes for the german Wikipedia.

**Comment by MichaelEischer** [comment]
Closing this as duplicate of #3445 .
