### ISSUE TITLE
Support a custom download url for backblaze b2

### ISSUE THREAD

**Issue by Mossop** [restic/restic#3473]
Output of `restic version`
--------------------------

`restic 0.12.1 compiled with go1.16.6 on darwin/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Files in backblaze b2 storage can be downloaded with zero egress charges via cloudflare (https://www.backblaze.com/blog/backblaze-and-cloudflare-partner-to-provide-free-data-transfer/). Adding support for a custom download url for files would mean restoring from backups would be much cheaper. The only costs would be for file listing API requests.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I would like to be able to download my backup files for free.

**Comment by MichaelEischer** [comment]
This is a duplicated of #2300
