### ISSUE TITLE
Go traceback when running restic prune

### ISSUE THREAD

**Issue by tbm** [restic/restic#3476]
This is similar or the same as  #3126 but I'm opening a different issue just in case this is different.

Output of `restic version`
--------------------------

restic 0.12.1 compiled with go1.16.6 on linux/amd64 (Downloaded from GitHub)

How did you run restic exactly?
-------------------------------

First I ran:

```
restic forget --prune
	-g host \
	--keep-last 20 \
	--keep-hourly 48 \
	--keep-daily 14 \
	--keep-weekly 8 \
	--keep-monthly 12 \
	--keep-yearly 75
```

This was successful.

Then I ran `restic check` and this mentioned I should run `restic prune` and failed because an `id` was missing.  I then ran `prune` which gave me an error and a Go traceback.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze b2 backend.

Expected behavior
-----------------

Steps to reproduce the behavior
-------------------------------

```
65556:tbm@jirafa: ~/bin] restic check
using temporary cache in /tmp/restic-check-cache-019679264
repository 80ac4657 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-019679264
create exclusive lock for repository
load indexes
check all packs
pack 47174aa8: does not exist
pack 9e9f43b3: does not exist
pack 04b4e249: does not exist
pack 24a9e397: not referenced in any index
pack 3e4d3ebb: not referenced in any index
pack f310a72d: not referenced in any index
pack 64e15981: not referenced in any index
4 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
check snapshots, trees and blobs
error for tree e124b50d:napshots
  id e124b50dec29fbbce7c98ffb28c810d93e5d10c2af434619699fe3239fb42fa0 not found in repository
[1:55] 100.00%  77 / 77 snapshots
Fatal: repository contains errors
zsh: exit 1     restic check
65557:tbm@jirafa: ~/bin] restic prune
repository 80ac4657 opened successfully, password is correct
found 4 old cache directories in /home/tbm/.cache/restic, run `restic cache --cleanup` to remove them
loading indexes...
loading all snapshots...
finding data that is still in use for 77 snapshots
[0:00] 1.30%  1 / 77 snapshots
id e124b50dec29fbbce7c98ffb28c810d93e5d10c2af434619699fe3239fb42fa0 not found in repository
github.com/restic/restic/internal/repository.(*Repository).LoadBlob
	/restic/internal/repository/repository.go:162
github.com/restic/restic/internal/repository.(*Repository).LoadTree
	/restic/internal/repository/repository.go:728
github.com/restic/restic/internal/restic.loadTreeWorker
	/restic/internal/restic/tree_stream.go:37
github.com/restic/restic/internal/restic.StreamTrees.func1
	/restic/internal/restic/tree_stream.go:164
golang.org/x/sync/errgroup.(*Group).Go.func1
	/home/build/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```

Do you have any idea what may have caused this?
-----------------------------------------------

No.  Unfortunately I haven't run `prune check` in a long time, so I'm not sure if this is new or not.  But it's strange that `restic forget` didn't complain.

Do you have an idea how to solve the issue?
-------------------------------------------

No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm very happy with restic in general.  Maybe less so today ;)

Just to add: before `restic check` I ran `restic forget` (as mentioned above).  This was successful with no warning:

```
...
2287 snapshots

[12:07] 82.12%  1878 / 2287 files deleted
[14:52] 100.00%  2287 / 2287 files deleted
2287 snapshots have been removed, running prune
loading indexes...
loading all snapshots...
finding data that is still in use for 76 snapshots
[0:01] 100.00%  76 / 76 snapshots
searching used packs...
collecting packs for deletion and repacking
[0:15] 100.00%  6884 / 6884 packs processed

to repack:        35757 blobs / 4.769 GiB
this removes      19038 blobs / 3.972 GiB
to delete:        18296 blobs / 2.714 GiB
total prune:      37334 blobs / 6.686 GiB
remaining:        59379 blobs / 11.284 GiB
unused size after prune: 577.496 MiB (5.00% of remaining size)

repacking packs
[0:35] 1.22%  20 / 1635 packs repacked
[5:15] 8.62%  141 / 1635 packs repacked
[12:20] 20.43%  334 / 1635 packs repacked
[13:42] 22.87%  374 / 1635 packs repacked
[17:55] 28.07%  459 / 1635 packs repacked
[21:08] 32.42%  530 / 1635 packs repacked
[28:32] 45.75%  748 / 1635 packs repacked
[29:17] 46.91%  767 / 1635 packs repacked
[29:17] 46.91%  767 / 1635 packs repacked
[30:26] 48.56%  794 / 1635 packs repacked
[33:07] 52.60%  860 / 1635 packs repacked
[33:08] 52.60%  860 / 1635 packs repacked
[34:54] 54.98%  899 / 1635 packs repacked
[34:54] 54.98%  899 / 1635 packs repacked
[35:10] 55.60%  909 / 1635 packs repacked
[37:29] 59.51%  973 / 1635 packs repacked
[40:43] 64.53%  1055 / 1635 packs repacked
[42:38] 68.01%  1112 / 1635 packs repacked
[56:29] 90.21%  1475 / 1635 packs repacked
[59:33] 94.62%  1547 / 1635 packs repacked
[59:46] 94.98%  1553 / 1635 packs repacked
[1:03:03] 100.00%  1635 / 1635 packs repacked
[1:03:12] 100.00%  1635 / 1635 packs repacked
rebuilding index
[0:01] 100.00%  2607 / 2607 packs processed
[0:17] 100.00%  2607 / 2607 packs processed
[0:25] 100.00%  2607 / 2607 packs processed
deleting obsolete index files
[1:45] 12.25%  266 / 2171 files deleted
[1:45] 12.25%  266 / 2171 files deleted
[2:00] 14.00%  304 / 2171 files deleted
[2:45] 19.07%  414 / 2171 files deleted
[2:45] 19.12%  415 / 2171 files deleted
[2:57] 20.36%  442 / 2171 files deleted
[2:57] 20.41%  443 / 2171 files deleted
[3:53] 27.13%  589 / 2171 files deleted
[4:34] 31.92%  693 / 2171 files deleted
[9:08] 68.49%  1487 / 2171 files deleted
[12:53] 98.71%  2143 / 2171 files deleted
[12:54] 98.71%  2143 / 2171 files deleted
[13:04] 100.00%  2171 / 2171 files deleted
removing 4463 old packs
[0:59] 3.88%  173 / 4463 files deleted
[1:00] 3.90%  174 / 4463 files deleted
[1:14] 4.91%  219 / 4463 files deleted
[1:15] 4.91%  219 / 4463 files deleted
[1:25] 5.65%  252 / 4463 files deleted
[1:27] 5.76%  257 / 4463 files deleted
[5:33] 21.58%  963 / 4463 files deleted
[5:33] 21.58%  963 / 4463 files deleted
[14:01] 54.96%  2453 / 4463 files deleted
[20:32] 80.62%  3598 / 4463 files deleted
[20:44] 81.51%  3638 / 4463 files deleted
[25:30] 100.00%  4463 / 4463 files deleted
done
65554:tbm@jirafa: ~/bin] 
```

**Comment by tbm** [comment]
What's strange is that `restic forget` shows 2287 snapshots and it removes *all* of them: `2287 snapshots have been removed, running prune`

but just after there are still 76 snapshots: `finding data that is still in use for 76 snapshots`

If 76 snapshots are remaining, shouldn't it have removed 2287-76 snapshots?                                                                                   

Anyway, when I run `restic snapshots` now it also shows 76 snapshots.

**Comment by tbm** [comment]
I forgot to mention that I had to run `restic unlock` before I could run `restic forget`.

I normally do backups hourly but the last snapshot was from yesterday, so I guess a backup failed.

However, that doesn't explain why `restic forget` completed without any errors at all, but running `check` afterwards gave me an error.

**Comment by MichaelEischer** [comment]
@tbm The `forget` output is split into kept and removed snapshots. So I guess the 2287 snapshots are really just the number of deleted snapshots.

Please run `restic find --tree e124b50dec29fbbce7c98ffb28c810d93e5d10c2af434619699fe3239fb42fa0` to find out which snapshot is affected by the missing tree blob. It would be interesting to know whether the damaged snapshot(s) is/are for example the latest snapshot or maybe some random older one(s).

Could it be the case that `restic backup` tried to run while `forget` was cleaning up the repository? I assume you called the `unlock` command manually and that it is not called automatically from your backup scripts?
Did a backup run (before/after the `forget` run) print errors? Is the repository used by multiple hosts or just a single host?

**Comment by tbm** [comment]
> The forget output is split into kept and removed snapshots. So I guess the 2287 snapshots are really just the number of deleted snapshots

Oh right, yes that makes sense.  Because there were so many snapshots, I couldn't scroll to the beginning of the output.

> Please run restic find --tree e124b50dec29fbbce7c98ffb28c810d93e5d10c2af434619699fe3239fb42fa0

65561:tbm@jirafa: ~/bin] restic find --tree e124b50dec29fbbce7c98ffb28c810d93e5d10c2af434619699fe3239fb42fa0
repository 80ac4657 opened successfully, password is correct
found 3 old cache directories in /home/tbm/.cache/restic, run `restic cache --cleanup` to remove them
Unable to load tree e124b50dec29fbbce7c98ffb28c810d93e5d10c2af434619699fe3239fb42fa0
 ... which belongs to snapshot b0f62d37ca4964cc4cfc08bcfc416068f6f3256c9864718cc181ce80a84e727b.

And `restic snapshots` says:

```
b0f62d37  2021-05-20 14:12:06
```

> Could it be the case that restic backup tried to run while forget was cleaning up the repository?

I don't think so because I use a lock file when running restic from my backup (and backup forget script): `flock --nonblock --conflict-exit-code 0 /run/user/$UID/restic-cloud-$LOCATION.lock restic`
 
> I assume you called the unlock command manually and that it is not called automatically from your backup scripts?

Yes, I ran it manually.

> Did a backup run (before/after the forget run) print errors?

Unfortunately I don't have logs for that.

When I do a backup now, it succeeds without errors.

> Is the repository used by multiple hosts or just a single host?

Just a single host.

So I guess the solution is to drop snapshot b0f62d37 and run check/prune again.  You probably can't determine if this is a restic bug or something that went wrong on my end because I don't have full logs.

It's strange though that `forget` worked without errors and `check` immediately afterwards complained.

**Comment by MichaelEischer** [comment]
Dropping the damaged snapshot could be a possible way forward (make sure to run `rebuild-index` before, as described below). However, I'd prefer to try something else first:

I've noticed in the check log that restic complains about a few missing pack files and also about a few not referenced pack files. This makes me wonder whether the missing blob is contained in some of these pack files. Please create a backup of the `index/` folder of the repository (copying the index-folder within the cache directory should also work). Then run `rebuild-index` and afterwards run `check` again. With a bit of luck that could resolve the problem.

Do you know which restic version you were using when the now damaged snapshot was created?

> It's strange though that `forget` worked without errors and `check` immediately afterwards complained.

That's indeed a bit worrying.

**Comment by tbm** [comment]
> Please create a backup of the index/ folder of the repository (copying the index-folder within the cache directory should also work). Then run rebuild-index and afterwards run check again. With a bit of luck that could resolve the problem.

It solved some problems but not the main one:

65544:tbm@jirafa: ~/restic] restic rebuild-index
repository 80ac4657 opened successfully, password is correct
found 3 old cache directories in /home/tbm/.cache/restic, run `restic cache --cleanup` to remove them
loading indexes...
getting pack files to read...
adding pack file to index 24a9e397d2e805a57def16872ec5a79b77421c5934a5f2c4c9e570ce3e95df51
adding pack file to index 3e4d3ebb0f4173ec8e89aaac36362ade41a3fead765267a43e96c83435b29603
adding pack file to index 64e159819dbe35985dea0c857900751942b72321c05367e48c1c5031b878466f
adding pack file to index f310a72db07a36c70397fca426a741df751e8d7fe487522916d859b75c515ccb
removing not found pack file 9e9f43b32b3a3d654c7f1399d14f137017c7b8b4ff204ba8618a359bbee5fa38
removing not found pack file 47174aa8fe8a3fee467dd4e8cb2a115e439f0e25a066a59770da32a30eacb53a
removing not found pack file 04b4e24972a074868abb6b4835c50d9d47a7699304dbea523a21a46ab560416a
reading pack files
[0:02] 100.00%  4 / 4 packs
rebuilding index
[0:21] 100.00%  2659 / 2659 packs processed
deleting obsolete index files
[0:15] 100.00%  29 / 29 files deleted
done
65545:tbm@jirafa: ~/restic] restic check
using temporary cache in /tmp/restic-check-cache-870517046
repository 80ac4657 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-870517046
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree e124b50d:snapshots
  id e124b50dec29fbbce7c98ffb28c810d93e5d10c2af434619699fe3239fb42fa0 not found in repository
[1:28] 100.00%  103 / 103 snapshots
Fatal: repository contains errors

> Do you know which restic version you were using when the now damaged snapshot was created?

Most probably restic 0.11.0 from Debian.

I have restic 0.11.0 in /usr/bin/.  I have newer versions from GitHub in $HOME/bin, but I noticed the script run by systemd doesn't seem to have that in its $PATH, so the binary in /usr/bin/ is called.

I was using restic 0.12.1 to do the forget, check, prune.

**Comment by MichaelEischer** [comment]
> And `restic snapshots` says:
> 
> ```
> b0f62d37  2021-05-20 14:12:06
> ```

I've just noticed something odd. I'm going to assume that the backup ran at least once in every week between now and then. Please correct me if that is wrong.

That snapshot is already 12 weeks old (and would require `--keep-weekly 13` to be kept) and is also not from the last week in may. So I'm wondering why that snapshot still exists. Please check using `restic forget --dry-run [...]` whether that snapshot should already have been removed.

**Comment by tbm** [comment]
The backup runs hourly when my laptop is on, so yes, there would be at least one backup per week.

`restic forget --dry-run` would remove the `b0f62d37` snapshot:

```
remove 30 snapshots:
ID        Time                 Host        Tags        Paths
--------------------------------------------------------------------------------------
b0f62d37  2021-05-20 14:12:06  jirafa                  /home/tbm/.git
...
```
It's too bad I don't have the complete log of the original `restic foget` call.

**Comment by MichaelEischer** [comment]
Just to be sure, there's another snapshot from a few days later in May in the repository?

This issue starts to look a lot like #3161 to me. There my working theory is that multiple versions of a file existed (due to retries during the upload) and restic only managed to delete one, but not all versions of the file.

**Comment by tbm** [comment]
> Just to be sure, there's another snapshot from a few days later in May in the repository?

Yes:

```
68ddf9e7  2021-05-31 22:12:13
```
> This issue starts to look a lot like #3161 to me. There my working theory is that multiple versions of a file existed (due to retries during the upload) and restic only managed to delete one, but not all versions of the file.

Should I run `restic forget` again now?  Should I backup any restic files just in case? (to investigate this issue)

**Comment by MichaelEischer** [comment]
> Should I run `restic forget` again now? Should I backup any restic files just in case? (to investigate this issue)

As `check` has only reported the one missing tree blob, the repository should be ok besides that. So you can just let restic `forget` snapshot `b0f62d37` and run `prune` afterwards.

You could backup the repository index (the `index/` folder) to help with investigating if another error occurs and of course keep a copy of the output generated by restic. But besides that I don't think that there's much that could be useful. And the data that would help with investigating the initial problem was probably already deleted by prune.

**Comment by tbm** [comment]
I did `restic forget b0f62d37`, `restic prune` and `restic forget` and everything is good now.

Thanks for your help!

**Comment by MichaelEischer** [comment]
Nice to hear that you could repair your repository. I'm closing this issue in favor of #3161, which seems to be the underlying issue.
