### ISSUE TITLE
Log message in stdout when running restic dump

### ISSUE THREAD

**Issue by ahshabbir** [restic/restic#3477]
Output of `restic version`
--------------------------
`restic 0.12.0 compiled with go1.15.5 on linux/amd64`

How did you run restic exactly?
-------------------------------
`restic dump -r [repo] [snapshot id] [filename]`
This was the first command I executed on the repo.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
sftp

Expected behavior
-----------------
Restic dump should only output the file's contents to stdout, all of the log messages should go only to stderr.

Actual behavior
---------------
The 'created new cache at...' log message makes it into the stdout of restic dump.

Steps to reproduce the behavior
-------------------------------
1. Find/Create a repository that your computer has never connected to before.
2. If nothing is on the repository, backup a file in the repository (but from a separate computer)
3. Execute restic dump on the file, and pipe it into a file locally. For example: `restic dump -r [repo] [snapshot id] [filename] > outfile`
4. Look at the first few lines of the file, for example, `head -n 5 outfile`
5. Notice that the 'created new cache at...' lies at the beginning of the file.

Do you have any idea what may have caused this?
-----------------------------------------------
I think the log message might be mistakenly be written to stdout rather than stderr.

Do you have an idea how to solve the issue?
-------------------------------------------
If you execute any other restic command on the repository, for example, `restic -r [repo] snapshots`, then the problem goes way, presumably because the cache has already been created.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic has remarkable client-side deduplication, making for a fast backup utility!

**Comment by MichaelEischer** [comment]
Since restic 0.12.1 the message is no longer printed when the output is not a terminal, see #3334. Does that solve the issue for you?

**Comment by MichaelEischer** [comment]
Closing as the issue has been solved.
