### ISSUE TITLE
File Created time seens incorrect on Windows repository files

### ISSUE THREAD

**Issue by mikef57** [restic/restic#3478]
Hello,
I use restic on windows - with great success - thanks.
I am writing a Windows GUI to view the repo snapshots, folders and files and found that the Created and Modified date-time values are 'always' the same. The Modifed date is correct, the Created date is incorrect (different to what Windows shows).
At first I thought it was my program but then I dumped some blobs out using restic and found that the Created date is incorrect.
I can provide more info if you need it.

Thanks again for doing restic - great work.
Mike Fletcher

**Comment by Xyrio** [comment]
what gui tool are you using? (im looking for one too)
what language are you using in windows and wich windows version? (might be a date format related problem)

**Comment by MichaelEischer** [comment]
restic only saves the change, modification and access times. The creation time (windows) or birth time (unix) is not saved. And only the access and modification times are restored. Currently `syscall.UtimesNano` is used to restore the timestamps and it only supports the two previously mentioned timestamps.

**Comment by mikef57** [comment]
Ok, my mistake in not understanding ctime. 
Thanks for the response.
Mike
