### ISSUE TITLE
Optimize blob repacking algorithm

### ISSUE THREAD

**Issue by fd0** [restic/restic#348]
The current blob repacking code basically works like this:
- find all unused blobs
- find the pack files for these blobs
- copy all blobs in those pack files into new pack files
- update the index
- remove the (now unused) pack files and the old index files

This is not the most efficient way to do it: If just one single small blob in a large pack file is unused, the whole pack file is rewritten. Optimize the algorithm so that packs are only repacked when e.g. at least 10 or 20% of the pack's size is occupied by unused blobs.

**Comment by viric** [comment]
That percent could be a parameter with default value in the optimize operation.

I arrived to this issue because I'm running "optimize" with "2468 unused blobs found", and repacking is already 12 minutes long. Maybe writing a progress line in stdout is also interesting for this operation.

**Comment by fd0** [comment]
Indeed, the user interface for most operations need to get better :)

**Comment by fd0** [comment]
This will be resolved by #1994

**Comment by fd0** [comment]
Closing as a duplicate of #1985, please subscribe over there. Thanks!
