### ISSUE TITLE
verbose output improvement

### ISSUE THREAD

**Issue by Xyrio** [restic/restic#3483]
using different words makes filtering easier. which is what seems to be intended here but it is incomplete.

windows 7
restic 0.12.1 compiled with go1.16.6 on windows/amd64
`restic --verbose=3 backup /whatever`

the files listing uses words: new, modified, unchanged
the total at the end uses words: new, changed, unmodified

one "new" should be changed to "added"

**Comment by MichaelEischer** [comment]
What is your use case here exactly? To distinguish between the file listing part and the summary output, it should be sufficient to first filter by the line prefix `new`/`modified`/`unchanged` or `Files:`/`Dirs:`.

To have a basis for further discussion, here's a snippet of the current output of `backup --verbose=3 restic`:
```
new       /restic/internal/ui/signals/, saved in 0.001s (0 B added, 1.489 KiB metadata)
modified  /restic/internal/ui/stdio_wrapper.go, saved in 0.001s (0 B added)
modified  /restic/internal/ui/stdio_wrapper_test.go, saved in 0.000s (0 B added)
unchanged /restic/internal/ui/table/table.go
modified  /restic/internal/, saved in 0.087s (0 B added, 9.486 KiB metadata)
modified  /restic/restic, saved in 0.318s (26.535 MiB added)
modified  /restic/, saved in 1.677s (0 B added, 10.813 KiB metadata)

Files:        1152 new,   510 changed,   429 unmodified
Dirs:           24 new,   329 changed,    33 unmodified
Data Blobs:    171 new
Tree Blobs:    174 new
Added to the repo: 27.555 MiB
```

As `added` is already used all over the place, I don't see what would be the point to switch from `new` to `added` in the total output.

**Comment by Xyrio** [comment]
if you filter for "new" you also get the ones in the summary. under windows with find command you cannot use regex magic. since it is such a minor change that can simplify scripts, might just as well do it.

**Comment by khmarbaise** [comment]
It would be great to have an output like this:
```
A /restic/internal/ui/signals/
M /restic/internal/ui/stdio_wrapper.go
M /restic/internal/ui/stdio_wrapper_test.go
M /restic/internal/
M /restic/restic
M /restic/
```
I explicitly removed the entry `unchanged /restic/internal/ui/table/table.go` because if something is not modified TBH I'm not interested in.

This would result in a more easily to understand output and would reduce the output size...dramatically. 

Maybe if someone is interested in those tiny details there could be a different output mode(?) and add the full fledged output information...

**Comment by MichaelEischer** [comment]
> if you filter for "new" you also get the ones in the summary. under windows with find command you cannot use regex magic. since it is such a minor change that can simplify scripts, might just as well do it.

I suppose you could filter for `new       `. Filtering for just `new` won't be reliable in any way as it will still include unchanged/modified files. Parsing the text output format is notoriously brittle, just use the json output format and process it using `jq`.

> It would be great to have an output like this:
> 
> ```
> A /restic/internal/ui/signals/
> M /restic/internal/ui/stdio_wrapper.go
> M /restic/internal/ui/stdio_wrapper_test.go
> M /restic/internal/
> M /restic/restic
> M /restic/
> ```
> 
> I explicitly removed the entry `unchanged /restic/internal/ui/table/table.go` because if something is not modified TBH I'm not interested in.

You can get a similar output using the `diff` command already. For the `backup` command just use`jq` to reformat it the way you need.

**Comment by Xyrio** [comment]
jq does not exist on windows, and new with space afterwards does not exclude the blobs lines.

it is better to keep unmodified to see what is affected.

event better for file list would be to use a character that is not supported in filenames for event better filtering/excluding
example:
<pre>
added:    /restic/internal/ui/signals/, saved in 0.001s (0 B added, 1.489 KiB metadata)
modified:  /restic/internal/ui/stdio_wrapper.go, saved in 0.001s (0 B added)
modified:  /restic/internal/ui/stdio_wrapper_test.go, saved in 0.000s (0 B added)
unchanged: /restic/internal/ui/table/table.go
modified:  /restic/internal/, saved in 0.087s (0 B added, 9.486 KiB metadata)
modified:  /restic/restic, saved in 0.318s (26.535 MiB added)
modified:  /restic/, saved in 1.677s (0 B added, 10.813 KiB metadata)

Files:        1152 new,   510 changed,   429 unmodified
Dirs:           24 new,   329 changed,    33 unmodified
Data Blobs:    171 new
Tree Blobs:    174 new
Added to the repo: 27.555 MiB
</pre>

**Comment by MichaelEischer** [comment]
> jq does not exist on windows

That is not true. Please have a look at https://stedolan.github.io/jq/download/

> and new with space afterwards does not exclude the blobs lines.

The `Data Blobs:` and `Tree Blobs:` lines end after `new`. So I don't see why `new ` or
```
'new      '
```
would match those.

> event better for file list would be to use a character that is not supported in filenames for even easier filtering/excluding
> like a colon. example:

That limitation only applies to Windows. For example on Linux a filename `2021-08-19 12:34:56` is perfectly valid. And to repeat myself, the only format which can be reliably parsed is the JSON output.

**Comment by smlx** [comment]
https://github.com/itchyny/gojq also releases windows builds.

**Comment by Xyrio** [comment]
it simpler without learning jq. well the time spent talking about this you could have already changed it... do whatever.

**Comment by MichaelEischer** [comment]
> it is simpler without learning jq syntax. well the time spent talking about this you could have already changed it... do whatever.

We could have changed it, and possibly break the scripts of someone else. Filtering the text output of `backup` for `new` or `added` or whatever cannot work reliably in any way unless it is bound to the line start like e.g. `^new ` or `^Files:`. Or at least add spaces after `"new    "` (which works perfectly fine with `find` on Windows 10 for me). And even then there's no guarantee that it will work correctly. 

Changing `new` in the file list to `added` will only complicated parsing, as `modified` lines also include the word `added`. And making the change in the backup summary will lead to a similar problem. Unless I've completely misunderstood how you've planed to parse the backup output, the suggested solution won't work.

I have to admit that we could change the output format as we only try to guarantee a stable JSON output format. But I don't see the point in doing so to make a brittle solution (parsing output not intended for scripting using the wrong filter patterns) a little bit less brittle. Thus, I'm closing this issue.
