### ISSUE TITLE
Is restic a good starting point to implement a sync solution for  a small group?

### ISSUE THREAD

**Issue by cocodrino** [restic/restic#349]
Hi, I'm interested in build a small cloud for friends where we can share files and sync folders, something similar to dropbox but much more simple, could be restic be a good starting point?...I'm a bit more afraid in the sync aspects, the users need keep sync some folders and files what could be the best approach for this situation, I'd appreciate if you can give me a small guideline about what can I take advantage of restic and what I may need build/implment...thanks so much..

**Comment by fd0** [comment]
I don't think that restic is the right choice here, it's a backup program and not made to sync files across different computers. You might be better of by looking into syncthing. Thats a program specifically made to enable (live) syncing of files across several machine, and it's also written in Go: https://syncthing.net/
