### ISSUE TITLE
`read-data-subset` with amount of data (`1GB`), instead of %

### ISSUE THREAD

**Issue by ShadowJonathan** [restic/restic#3490]
What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

The documentation says right now that `restic check --read-data-subset=` can accept a chunk indicator (`1/5`) or a percentage (`25%`)

However, in my use-case, i'd like to check a random subset of X bytes of data every evening, due to bandwidth constraints. Could this be possible to implement as `--read-data-subset=20GB`, which then is functionally the same as `--read-data-subset=25%` (given that the total repository size is 80GB then)?

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Bandwidth constraints, and more predictable times for checking after an backup or likewise.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic looks absolutely amazing for my usecase, i'm currently thinking about buying a 6TB WD Red drive on an ODroid HC2 to keep all of my "archive data" (stored in 1TB drives across my devices) in one central place, and then use restic to sync it with S3 and the likes. Compression looks to be also interesting to use, but it's not a requirement. Restic has encryption, which to me is enough, and so i'll be using it.

This above thing irked me a bit, as it could lengthen checking times the bigger the repository gets, and so this'd keep it somewhat predictable.

**Comment by ShadowJonathan** [comment]
I should mention that this is in the context of `--read-files`, a predictable chunk of blobs being downloaded and compared

**Comment by MichaelEischer** [comment]
It should be fairly simple to implement a selection of a random set of packs up to a given size limit. We'd just have to add a variant of `selectRandomPacksByPercentage`.

**Comment by gum3ng** [comment]
Hi, I am interested in working on this issue. I am working on adding the file size case in the file cmd_check.go
