### ISSUE TITLE
Restic forget fails with B2 and object locks despite --no-lock (and a crash in forget when remote lock fails)

### ISSUE THREAD

**Issue by vsuontam** [restic/restic#3491]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/amd64

How did you run restic exactly?
-------------------------------
 restic --no-lock -r b2:restic-backup-2:/ forget e2f7d85

I have set these environment variables (with real values of course):
export B2_ACCOUNT_ID=00000000000000000000000
export B2_ACCOUNT_KEY=K001abcdabdbabcdabcdabcd
export RESTIC_PASSWORD_FILE=/home/user/restic-pw

This is the output of the command:

repository 35b4e101 opened successfully, password is correct
unable to create lock in backend: repository is already locked exclusively by PID 32487 on HOST by user (UID 1002, GID 1003)
lock was created at 2021-08-23 10:53:33 (42m34.573443863s ago)
storage ID 52256a07
the `unlock` command can be used to remove stale locks

The strange thing is that I have specified --no-lock on all commands, but a lock was made regardless. 

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze with object locks enabled (with time set to two days as I was testing the feature) 

Maybe this is relevant. I did CTRL-C my first backup proces at one point, after which restic has been complaining about "Access denied" (because of object lock I suppose).

Expected behavior
-----------------

Expected restic being able to forget a snapshot (and also delete the stale files created by interrupted backup after few days as object lock period for the files created on the interrupted backup has expired). I tried to forget a backup created a week ago or so.

Also expected no locks being created on the backend due to "--no-lock" specified to restic.  

Also didn't expect restic unlock to crash. 

Actual behavior
---------------

Restic forget fails. This is the output of the  
# restic --no-lock -r b2:restic-backup-2:/ forget e2f7d85
repository 35b4e101 opened successfully, password is correct
unable to create lock in backend: repository is already locked exclusively by PID 32487 on HOST by user (UID 1002, GID 1003)
lock was created at 2021-08-23 10:53:33 (42m34.573443863s ago)
storage ID 52256a07
the `unlock` command can be used to remove stale locks 

The restic unlock does not work either now (because the lock cannot be cleared due to the object locks). 

This is the output of the 
# restic --no-lock -r b2:restic-backup-2:/ unlock

repository 35b4e101 opened successfully, password is correct
Remove(<lock/52256a0740>) returned error, retrying after 552.330144ms: Delete: b2_delete_file_version: 401: Access Denied
Remove(<lock/52256a0740>) returned error, retrying after 1.080381816s: Delete: b2_delete_file_version: 401: Access Denied
Remove(<lock/52256a0740>) returned error, retrying after 1.31013006s: Delete: b2_delete_file_version: 401: Access Denied
Remove(<lock/52256a0740>) returned error, retrying after 1.582392691s: Delete: b2_delete_file_version: 401: Access Denied
Remove(<lock/52256a0740>) returned error, retrying after 2.340488664s: Delete: b2_delete_file_version: 401: Access Denied
Remove(<lock/52256a0740>) returned error, retrying after 4.506218855s: Delete: b2_delete_file_version: 401: Access Denied
Remove(<lock/52256a0740>) returned error, retrying after 3.221479586s: Delete: b2_delete_file_version: 401: Access Denied
Remove(<lock/52256a0740>) returned error, retrying after 5.608623477s: Delete: b2_delete_file_version: 401: Access Denied
Remove(<lock/52256a0740>) returned error, retrying after 7.649837917s: Delete: b2_delete_file_version: 401: Access Denied
Remove(<lock/52256a0740>) returned error, retrying after 15.394871241s: Delete: b2_delete_file_version: 401: Access Denied
b2_delete_file_version: 401: Access Denied
Delete
github.com/restic/restic/internal/backend/b2.(*b2Backend).Remove
        /restic/internal/backend/b2/b2.go:261
github.com/restic/restic/internal/backend.(*RetryBackend).Remove.func1
        /restic/internal/backend/backend_retry.go:108
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
        /home/build/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.1/retry.go:55
github.com/cenkalti/backoff/v4.RetryNotify
        /home/build/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.1/retry.go:34
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        /restic/internal/backend/backend_retry.go:46
github.com/restic/restic/internal/backend.(*RetryBackend).Remove
        /restic/internal/backend/backend_retry.go:107
github.com/restic/restic/internal/cache.(*Backend).Remove
        /restic/internal/cache/backend.go:38
github.com/restic/restic/internal/restic.RemoveStaleLocks.func1
        /restic/internal/restic/lock.go:282
github.com/restic/restic/internal/restic.ForAllLocks.func2
        /restic/internal/restic/lock.go:336
golang.org/x/sync/errgroup.(*Group).Go.func1
        /home/build/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1371

Steps to reproduce the behavior
-------------------------------

I can retry and update the reproduction instructions tomorrow, as the old bucket is now unusable for two days do to the object locks. 

I now created a new bucket with 1 day of object locks, so I can test things sooner, but will have to wait until tomorrow until I can try delete a snapshot.

But even creating the backup with --no-lock gave the error about not being able to delete the lock file.

Do you have any idea what may have caused this?
-----------------------------------------------

restic trying to use locks even if specified it should not. Not sure how working with object locks (or immutability in the backend) should be handled). 

Do you have an idea how to solve the issue?
-------------------------------------------
Not atm. Just wait until the object lock time runs out, but before that can't do much as back-end is strict. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I like the docs generally, and am just getting into restic, it looks like a well-maintained tool. Just think the operation on object-locked storage is not that well-specified/used.

**Comment by MichaelEischer** [comment]
> The strange thing is that I have specified --no-lock on all commands, but a lock was made regardless.

Several commands like `forget`, `prune`, `check` and `backup` ignore the `--no-lock` option.

> Backblaze with object locks enabled (with time set to two days as I was testing the feature)

restic assumes that it can delete lock files at any time (after 5 minutes to be precise). And to prune data restic must be able to delete any files it wants to. Or to be a bit more precise the files must be marked as deleted and don't show up again when listing files. With AWS S3 and the Object Lock feature buckets must be versioned which allows doing exactly what I've just mentioned. I wonder whether there's a similar feature for B2?

**Comment by MichaelEischer** [comment]
You could also try whether the S3 compatible API of B2 works with a beta release of restic (see https://beta.restic.net/?sort=time&order=desc ). restic 0.12.1 probably won't work as #3246 in not included in any released version so far.

**Comment by MichaelEischer** [comment]
Or you could try whether #2398 works for you.

**Comment by vsuontam** [comment]
Thanks. So I gather that working in read-only (or temporarily read-only due to object locked) repositories only works for taking snapshots, but not forgetting them at the moment?

AFAIK the above #2398 just hides the error if the deletion fails, so wont improve the actual behavior, right?. Atm I have also no easy way of building custom binaries based on PRs unfortunately.

**Comment by MichaelEischer** [comment]
#2398 tells B2 to hide a file, when it can't be deleted. That is enough that other restic operations won't process that file again and then `forget` and `prune` should work as normal. The only downside is that the hidden files still consume storage space. The hidden files still have to be deleted by e.g. lifecycle rules. And something also has to extend the file lock duration of files that should be kept.

If you check out the code from a PR, then you only need a go compiler and then call `go build ./cmd/restic` and you're done.

**Comment by vsuontam** [comment]
Thanks Michael. That something that could extend the file lock duration I suppose is not in place yet? Can't ask Restic to "touch" the files in B2 (that are still part of the latest snapshot), which I suppose would extend their life?

**Comment by MichaelEischer** [comment]
restic doesn't know anything about file / object locks so far. For now, it should work to (manually) extend the lock duration for all files that haven't been hidden. And to actually make sure that the repository is in a working state you have to run `check` from time to time.

**Comment by vsuontam** [comment]
@MichaelEischer Finally got the restic compiled from the #2398. Was a bit harder as I had an older golang-go version (1.6) which didn't work out of the box. Build failed for missing deps (fuse etc). After realising I do need to update the go instead of trying to manually fulfill the deps, it was an easy build. Maybe a version check of the golang-go to the build command to help future builders in this situation?

I tested the #2398 and it does indeed work better, by hiding files instead of deleting which works for me. 

I also actually tried restoring an initially hidden snashots file in the repository side (after forgetting it first with restic), and then restoring the snapshots file manually in the b2 server side.

So, I could achieve nice ransomware safe backups with this using efficient snapshots to go back in time if needed. If the attacker manages to get hold hold of the backup side where restic is run, my backups would be still safe (thanks to object locks), and file versions on the server side (and life cycle rules).

I could actually live with these limitations with the PR, as they do give me truly ransomware safe backups albeit with manual work required in the case attacker has maliciously tried deleting all. The manual work is today required to restore the older versions on server side (especially for older data files, that object locks do not protect anymore). The restore in this case would involve some scripting to get the repo to an earlier state. 

I guess the only few remaining optimizations that could be great features
- Make #2398 an option in the main restic. Having to maintain an own build is not great.
- Add some knowledge on object locks on restic. This would also be helpful with "cold backups" as well so that restic would be "forbidden" to modify files within some time period (to save money/costs). The object lock information could for example be given in the init, or be an backup option. Then in regular use case, user could just be running backup/prune without any scripting required or server side tricks.   If the super motivated attacker tried altering the object lock information, and deleting backups (that are object locked), the operation would just fail but on normal cases the operations would be seamless. 
- Some way of extending the object locks would be required (as you also point out earlier).

There are few other folks trying also achieve what I am trying:
https://github.com/restic/restic/issues/3195

**Comment by MichaelEischer** [comment]
Thanks for testing and nice to hear that it worked.

The manual and readme already mention that at least Go version 1.14 is required. There's also the possibility to build restic via `go run build.go` which includes a go version check, although I'm not sure whether that would have worked with Go 1.6. Sorry for not mentioning that a recent go version is required; it's just that nobody had complained so far ;-) .

I agree that object lock support would simplify usage with restic, but that feature request belongs into #3195.

**Comment by MichaelEischer** [comment]
@gabrielwhite Your problem is unrelated to this issue. Please have a look at #3541 instead.

**Comment by MichaelEischer** [comment]
Closing as #2398 has been merged a long time ago.
