### ISSUE TITLE
Archive unreadable empty directories

### ISSUE THREAD

**Issue by rillian** [restic/restic#3492]
Output of `restic version`
--------------------------
`restic 0.12.0 compiled with go1.16rc1 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Restic could archive empty directories even if they are not readable. Since there's no data, a record could be created without read access, resulting in a more accurate snapshot of the filesystem.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

On my Fedora 34 system, unprivileged [podman](https://podman.io/) container images often end up containing a directory which is only readable by the subuid, not the owning group, resulting in incomplete backup warnings from restic when run as the user rather than root:
```
$ restic -r $repo backup $HOME
[...]
error: Open: open $HOME/.local/share/containers/storage/overlay/$container/diff/var/cache/apt/archives/partial: permission denied
[...]
$ ls -lh $HOME/.local/share/containers/storage/overlay/$container/diff/var/cache/apt/archives/
total 0
-rw-r-----. 1 user   user  0 Jun 22 17:52 lock
drwx------. 1 100099 user  0 Jun 22 17:53 partial

```
These directories always seem to be zero-length, so it seems like restic could work around the issue by archiving a similarly-unreadable zero-length record after encountering the permission error, instead of leaving the directory entirely out of the backup. That would work around the issue and avoid filling the backup reports with long sequences of errors, possibly hiding more serious issues.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

It's lovely! Thanks for supporting it.

**Comment by MichaelEischer** [comment]
On my system, which uses ext4, an empty folder shows up with size 4096. I'm afraid that the directory size is completely implementation defined. In particular, there's probably no guarantee that 0-size folders are actually empty. So it sounds too risky to silently ignore such folders.
