### ISSUE TITLE
document supported/unsupported file metadata

### ISSUE THREAD

**Issue by rsticmf** [restic/restic#3497]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on windows/amd64
restic 0.11.0 compiled with go1.15.9 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Ideally, though perhaps unrealistic, restic should support all file metadata on all supported platforms.
(ACLs, extended attributes, inode flags, hidden/indexing/... flags etc.)

Some metadata types seem to be left out currently, e.g.
  - hidden flag on windows (https://github.com/restic/restic/issues/2075)
  - inode flags (lsattr/chattr) on linux

Borg did a good job documenting their metadata support: https://borgbackup.readthedocs.io/en/stable/usage/general.html#platforms

Would be nice to have a similar overview in restic's documentation.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Knowing in advance what file metadata support to expect could save a lot of time spent with test setups.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Of course it does :-) restic does an amazing job and is really fast (dumps to stdout being a notable exception)

**Comment by mathstuf** [comment]
I added mentions in #3565; more docs can be added to this area in the future as more missing metadata is found.

**Comment by MichaelEischer** [comment]
Closed via https://github.com/restic/restic/pull/3565
