### ISSUE TITLE
"new" (0 B added) on 2nd backup vs. "unchanged"

### ISSUE THREAD

**Issue by datajerk** [restic/restic#3503]
Output of `restic version`
--------------------------
`restic 0.12.1 (v0.12.1-41-g10b39d75) compiled with go1.15.9 on linux/amd64`

How did you run restic exactly?
-------------------------------
```
export B2....
export RESTIC_PASSWORD...
export RESTIC_REPO....
export RESTIC_CACHE_DIR=/a/path # same prob with or without this 
restic -vvv backup --tag "$BASE" --tag "$restic_version" --tag "$go_version" --one-file-system --exclude "*/#recycle/*" dir1 dir2 dir3
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
B2

Expected behavior
-----------------

On 2nd backup of the exact same data:

```
unchanged /dir1/file1
```

Actual behavior
---------------

```
new /dir1/file1 ..... (0 B added)
```

Steps to reproduce the behavior
-------------------------------

Only seems to occur with a very large number of files, could not reproduce with a small number of files.

Do you have any idea what may have caused this?
-----------------------------------------------

Size of backup?  Checking mtime, ctime, and inode with stat returns the same values, as expected

Do you have an idea how to solve the issue?
-------------------------------------------

Not at this time

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Sure.

**Comment by MichaelEischer** [comment]
Does restic print `using parent snapshot`or `no parent snapshot found, will read all files`?

**Comment by datajerk** [comment]
No, the previous snapshot does not contain the files.  I have intermixed snapshots.  If only the previous snapshot is used vs. any with same paths, that would explain what I'm seeing.  I'll restructure my backups and test again.

**Comment by datajerk** [comment]
Just tested.  Large repo, only one snapshot, yes, has most of the files there, same path, etc... still getting "new ... 0B added".  I'm going to let this compete and test again.  this backup will take 4.5 days.

**Comment by MichaelEischer** [comment]
restic selects the latest snapshot as parent that has the same hostname and identical paths. If new paths are added then the previous snapshots won't match. In that case you'd have to use `backup --parent snapshotID`.

There are also several other issues which already ask for a more flexible parent snapshot detection, see  #2246, #3198 and #3118.

**Comment by datajerk** [comment]
thanks.  using --parent with the last snapshot solves this issue.
