### ISSUE TITLE
TestArchiverAbortEarlyOnError fails on armhf

### ISSUE THREAD

**Issue by maxice8** [restic/restic#3505]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.5 on linux/amd64

How did you run restic exactly?
-------------------------------
`RESTIC_TEST_FUSE=0 make test`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Whatever the testsuite uses

Expected behavior
-----------------
The test passes

Actual behavior
---------------
```
go test ./cmd/... ./internal/...
go: downloading github.com/google/go-cmp v0.5.6
ok  	github.com/restic/restic/cmd/restic	12.482s
--- FAIL: TestArchiverAbortEarlyOnError (0.08s)
    --- FAIL: TestArchiverAbortEarlyOnError/#01 (0.02s)
        testing.go:30: using low-security KDF parameters for test
        config.go:65: disabling check of the chunker polynomial
        archiver_test.go:2020: chdir to /tmp/restic-test-3497978820
        archiver_test.go:2048: Snapshot return error: test error
        archiver_test.go:2050: track fs: map[.:1 dir:1 dir/file1:1 dir/file2:1 dir/file3:1 dir/file4:1 dir/file5:1 dir/file6:1 dir/file7:1]
        archiver_test.go:2054: opened dir/file7 1 times, want 0
        archiver_test.go:2057: chdir back to /home/buildozer/aports/community/restic/src/restic-0.12.1/internal/archiver
FAIL
FAIL	github.com/restic/restic/internal/archiver	5.981s
```

Steps to reproduce the behavior
-------------------------------
Try to run restic tests on armhf

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
I can provide more in-depth logs from the failed builder if the test provides

**Comment by greatroar** [comment]
Confirmed with QEMU on a Linux/amd64 host, Go 1.17, bf9c8771a469f1ee0d4b6fab78791d36426371b2:

```
$ GOARCH=arm go test -run=TestArchiverAbortEarlyOnError/#01 -count=100
--- FAIL: TestArchiverAbortEarlyOnError (0.27s)
    --- FAIL: TestArchiverAbortEarlyOnError/#01 (0.27s)
        testing.go:30: using low-security KDF parameters for test
        config.go:65: disabling check of the chunker polynomial
        archiver_test.go:2020: chdir to /tmp/restic-test-1422233881
        archiver_test.go:2048: Snapshot return error: test error
        archiver_test.go:2050: track fs: map[.:1 dir:1 dir/file1:1 dir/file2:1 dir/file3:1 dir/file4:1 dir/file5:1 dir/file6:1 dir/file7:1]
        archiver_test.go:2054: opened dir/file7 1 times, want 0
        archiver_test.go:2057: chdir back to /home/me/src/restic/restic/internal/archiver
FAIL
exit status 1
FAIL	github.com/restic/restic/internal/archiver	10.697s
```

I couldn't trigger this without GOARCH=arm, but neither can I trigger it consistently with that GOARCH. May still be a concurrency bug rather than anything architecture-specific.

**Comment by MichaelEischer** [comment]
I guess the race condition happens here:
https://github.com/restic/restic/blob/ef5672a902a3ccf9187fee7e4ac38a8d0e8b9cbd/internal/archiver/archiver.go#L250

The test could save 4 blobs, then queue 2 further blobs for saving (which will fail later on) and in the meantime open a seventh file. So the fix would probably be to just remove this line: https://github.com/restic/restic/blob/master/internal/archiver/archiver_test.go#L2001 .
