### ISSUE TITLE
The forget command always keeps all snapshots, regardless of the keep arguments given.

### ISSUE THREAD

**Issue by diademiemi** [restic/restic#3515]
Output of `restic version`
--------------------------
`restic 0.12.0 compiled with go1.15.5 on linux/amd64`

How did you run restic exactly?
-------------------------------

I run `restic -o rclone.connections=1 -r rclone:ftp:Repository backup $(ls -t /storage/backups/*.zip | head -n 1)` daily at 5AM with the password in an environment variable.  
No forget command works,  even when running `restic -o rclone.connections=1 -r rclone:ftp:Repository forget --keep-daily 1 --dry-run` it keeps all snapshots.  

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
FTP over Rclone.  

Expected behavior
-----------------

Running any forget command will forget snapshots according to the wiki page here https://restic.readthedocs.io/en/latest/060_forget.html. 
Running `--keep-daily 1` should only keep one snapshot.

Actual behavior
---------------

No matter what policy I apply, it always keeps all snapshots.  
Running it with `--keep-daily 1` keeps all 18 snapshots, listing the reason "daily snapshot" under all of them.  
```
keep 1 snapshots:
ID        Time                 Host        Tags        Reasons         Paths
--------------------------------------------------------------------------------------------------------------------------------------------
76588899  2021-09-12 05:00:01  redacted              daily snapshot  /storage/backups/20210912-040000-c7817cf210544272baddf334b47082fb.zip
--------------------------------------------------------------------------------------------------------------------------------------------
1 snapshots
```
This times 18 for all the snapshots. All the messages are separate, this is probably part of the issue.  

The output of `snapshots` is this:  
```
repository redacted opened successfully, password is correct
ID        Time                 Host        Tags        Paths
----------------------------------------------------------------------------------------------------------------------------
11d07f19  2021-08-28 05:41:19  redacted              /storage/backups/20210828-040000-b5cf0d96ab5642709baab77a89898150.zip
a30984d6  2021-08-29 07:54:19  redacted              /storage/backups/20210829-040000-675d32e680034edf865a99b0cbd17fa5.zip
01c4f51a  2021-08-31 05:00:01  redacted              /storage/backups/20210831-040000-ac26eed3a52b4d68b2f2e6fd991f9ff4.zip
8aaa4957  2021-09-01 05:00:01  redacted              /storage/backups/20210901-040000-7342dc43ebc64c989686bac1a45d640e.zip
ea78843d  2021-09-02 05:00:01  redacted              /storage/backups/20210902-040000-6cc22602292b487797ad0660b3ccece9.zip
5779914a  2021-09-03 05:00:01  redacted              /storage/backups/20210903-040000-2ffa0070c9b34a1b8abac555e922289f.zip
c09876c0  2021-09-04 05:00:01  redacted              /storage/backups/20210904-040000-d20b44e1222044d593efd2859372763f.zip
79bcc9b8  2021-09-05 05:00:01  redacted              /storage/backups/20210905-040000-3ce5e9b81905424596874d429c71d0b9.zip
71592058  2021-09-06 05:00:01  redacted              /storage/backups/20210906-040000-56ebbf3755674fa1ad499cb06e3a9fb8.zip
fb2085c1  2021-09-07 05:00:01  redacted              /storage/backups/20210907-040000-04c496cdcedd49448d6ba027d9dae293.zip
24e7d59d  2021-09-08 05:00:01  redacted              /storage/backups/20210908-040000-787923c2886b4e379f8b60d65406457d.zip
7a72d4e4  2021-09-09 05:00:01  redacted              /storage/backups/20210909-040000-2f08f5c300824990b7dc20522c960634.zip
4d4f3a34  2021-09-10 05:00:01  redacted              /storage/backups/20210910-040000-9b6aef45712443e0a26b9f351298e690.zip
3fafe960  2021-09-11 05:00:01  redacted              /storage/backups/20210911-040000-943975e36ad84dfb9ca6880fddf738cd.zip
76588899  2021-09-12 05:00:01  redacted              /storage/backups/20210912-040000-c7817cf210544272baddf334b47082fb.zip
363216be  2021-09-13 05:00:01  redacted              /storage/backups/20210913-040000-a847d87a3c6d43b79624783738cb5226.zip
633955f2  2021-09-14 05:00:01  redacted              /storage/backups/20210914-040000-894147e5ab3f4b5eaaf4aaa40f0b0f96.zip
a889b972  2021-09-15 05:00:01  redacted              /storage/backups/20210915-040000-5882e55390164a76ae99d5d7a3ce6aaf.zip
----------------------------------------------------------------------------------------------------------------------------
18 snapshots

```

Running `forget latest` does forget the correct backup.  

Steps to reproduce the behavior
-------------------------------

I'm not sure, these backups seem the same as in the example on the Wiki.  

Do you have any idea what may have caused this?
-----------------------------------------------

The wiki page shows the backups which were kept/forgotten are shown together in the result of `forget`, while here they're all separate.  

```
Applying Policy: keep 1 monthly snapshots
keep 1 snapshots:
ID        Time                 Host        Tags        Reasons           Paths
----------------------------------------------------------------------------------------------------------------------------------------------
3fafe960  2021-09-11 05:00:01  redacted              monthly snapshot  /storage/backups/20210911-040000-943975e36ad84dfb9ca6880fddf738cd.zip
----------------------------------------------------------------------------------------------------------------------------------------------
1 snapshots

keep 1 snapshots:
ID        Time                 Host        Tags        Reasons           Paths
----------------------------------------------------------------------------------------------------------------------------------------------
11d07f19  2021-08-28 05:41:19  redacted              monthly snapshot  /storage/backups/20210828-040000-b5cf0d96ab5642709baab77a89898150.zip
----------------------------------------------------------------------------------------------------------------------------------------------
1 snapshots

keep 1 snapshots:
ID        Time                 Host        Tags        Reasons           Paths
----------------------------------------------------------------------------------------------------------------------------------------------
363216be  2021-09-13 05:00:01  redacted              monthly snapshot  /storage/backups/20210913-040000-a847d87a3c6d43b79624783738cb5226.zip
----------------------------------------------------------------------------------------------------------------------------------------------
1 snapshots

keep 1 snapshots:
ID        Time                 Host        Tags        Reasons           Paths
----------------------------------------------------------------------------------------------------------------------------------------------
71592058  2021-09-06 05:00:01  redacted              monthly snapshot  /storage/backups/20210906-040000-56ebbf3755674fa1ad499cb06e3a9fb8.zip
----------------------------------------------------------------------------------------------------------------------------------------------
1 snapshots
...
```

Do you have an idea how to solve the issue?
-------------------------------------------

I do not, the examples on the wiki seem the same

**Comment by rawtaz** [comment]
Thanks for being so specific in the information you provide, that's always helpful!

What you're seeing is simply due to each of your snapshots having different directories/paths, see the second paragraph in https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy .

Restic groups snapshots by default on host and path, and in your case since each snapshot's path is different than the others, each snapshot gets its own group. Since restic also as a safety measure keeps the latest snapshot in each group, all your snapshots are kept.

Simply use the `--group-by` option to control how restic groups the snapshots when forgetting them. The possible values in this option are `host`, `tags` and `paths`.

**Comment by diademiemi** [comment]
I see, that makes sense! I tried it with `--group-by host` and that works, thanks!

**Comment by Crest** [comment]
By storing compressed archives in restic you're making it impossible for restic to deduplicate your backups. To deduplicate backups restic requires access to the uncompressed and unencrypted files. Restic doesn't compress your data because combining compression and encryption is a good way to introduce oracle attacks to your protocol/file format and the original author(s) decided against attempting to tackle this problem.

**Comment by diademiemi** [comment]
Actually it's doing a great job at that. I wasn't expecting it to be able to do this but it takes up about 175GB of real disk (Checked with `stats` with Restic) space while checking it with `du -sh` in a mount says it's 1.1TB. The drive doesn't even have that much, so it's definitely working.
