### ISSUE TITLE
Dry-run support for the copy command

### ISSUE THREAD

**Issue by djmattyg007** [restic/restic#3517]
Output of `restic version`
--------------------------

restic 0.12.1 (v0.12.1-10-gbc97a3d1) compiled with go1.17.1 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Similarly to how `--dry-run` is useful for determining what will and won't be included in backups, it can also be useful for copying snapshots between repositories. This is important to ensure things are working properly before committing to downloading and uploading potentially terabytes worth of data.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I'm trying to mirror a repository stored on a NAS in my house to a Backblaze B2 bucket. My upload speeds aren't amazing, so this process will take a while. Ideally I'd only need to do it once.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, I think restic is an amazing piece of software :) Thank you for making this available to the world.

**Comment by MichaelEischer** [comment]
It should be possible to pass the exact same set of snapshot selectors used for `copy` to the `snapshots` command to see which snapshots will potentially be copied. The `copy` command is intelligent enough to copy each snapshot only once even if run multiple times.

Judging from your remark on not downloading and uploading data this would limit `copy --dry-run` to only reporting which snapshots haven't been copied yet. To provide a more accurate estimate on how much data must be copied, restic would have to process the directory metadata for each snapshot which would at least require downloading parts of the repository.

**Comment by djmattyg007** [comment]
Downloading data is usually just fine. My download speed is 5 times my upload speed.

**Comment by MichaelEischer** [comment]
I still don't understand the problem which should be solved here. I'll close the issue for now, feel free to reopen it if you're still interested in it.

**Comment by anton-ryzhov** [comment]
I was researching an idea for my use case and found this issue.

I have one repository with many sources writing data with their own "forget" policies. And another repository, that copies snapshots from the 1st.

To avoid replicating, hardcoding or guessing cleanup rules on the second site, I wanted to do something like:
```bash
restic copy --from-repo DEST --repo SRC --json --dry-run | jq " extract non-existing snapshots on the SRC side" | xargs restic forget --repo DEST
```

I'm using similar trick to do the opposite — only copy snapshots that won't be removed soon from the SRC:
```bash
restic forget --dry-run --repo SRC --keep-*** --json | jq --raw-output '.[].keep[].short_id' | xargs restic copy --from-repo SRC --repo DST
```

It seems I can workaround that by listing snapshots in both repos and then match then using `snapshot.original` or `snapshot.tree`
