### ISSUE TITLE
Copy command silently ignores --no-lock flag

### ISSUE THREAD

**Issue by djmattyg007** [restic/restic#3518]
Output of `restic version`
--------------------------

restic 0.12.1 (v0.12.1-10-gbc97a3d1) compiled with go1.17.1 on linux/amd64

How did you run restic exactly?
-------------------------------

```
export RESTIC_PASSWORD='hunter2' AWS_ACCESS_KEY_ID='hunter3' AWS_SECRET_ACCESS_KEY='hunter4' AWS_DEFAULT_REGION='my-house-1' RESTIC_PASSWORD2='hunter5' B2_ACCOUNT_ID='hunter6' B2_ACCOUNT_KEY='hunter7'

restic -r s3:https://minio.example.com:9000/backups/restic --key-hint abcd1234 copy --no-lock --verbose --repo2 b2:example-b2-bucket:restic/backups
```

The AWS-style credentials for MinIO authenticate for a service user with read-only permissions.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

The source repository is a MinIO storage bucket. The destination repository is a B2 storage bucket.

Expected behavior
-----------------

I'm using read-only credentials to read from the source repository, and I'm passing the `--no-lock` flag. I would expect there to be no need to write to the source repository. If there is a need, the command should fail immediately instead of pretending it can work (before even attempting to open repositories). Ideally, it would even link to some documentation explaining why it is necessary.

Actual behavior
---------------

The output of the above command is as follows:

```
repository wxyz1234 opened successfully, password is correct
repository mnop5678 opened successfully, password is correct
Save(<lock/1522722bf2>) returned error, retrying after 552.330144ms: client.PutObject: Access Denied.
Save(<lock/1522722bf2>) returned error, retrying after 1.080381816s: client.PutObject: Access Denied.
Save(<lock/1522722bf2>) returned error, retrying after 1.31013006s: client.PutObject: Access Denied.
Save(<lock/1522722bf2>) returned error, retrying after 1.582392691s: client.PutObject: Access Denied.
Save(<lock/1522722bf2>) returned error, retrying after 2.340488664s: client.PutObject: Access Denied.
Save(<lock/1522722bf2>) returned error, retrying after 4.506218855s: client.PutObject: Access Denied.
Save(<lock/1522722bf2>) returned error, retrying after 3.221479586s: client.PutObject: Access Denied.
Save(<lock/1522722bf2>) returned error, retrying after 5.608623477s: client.PutObject: Access Denied.
Save(<lock/1522722bf2>) returned error, retrying after 7.649837917s: client.PutObject: Access Denied.
  signal interrupt received, cleaning up
```

The program terminated because I pressed Ctrl+C.

Steps to reproduce the behavior
-------------------------------

The source repository should be in a read-only state. I achieved that with MinIO by creating a service user with a read-only policy.

Do you have any idea what may have caused this?
-----------------------------------------------

No, I'm not sure why restic decided to proceed with an invalid configuration (user passed `--no-lock` flag, command *needs* to write a lock file) without even warning the user.

I suppose it's possible that there's some issue on the B2 side (the destination), but the "Access Denied" error messages don't indicate which repository is causing the issue. I used the exact same B2 credentials to initialise the repository on B2, so I think this is highly unlikely.

Do you have an idea how to solve the issue?
-------------------------------------------

Ideally restic would error out immediately in cases where the `--no-lock` flag has been supplied but the command needs to write a lock file. If for some reason this isn't feasible (I guess it might be a backwards-compatibility concern, though it's clearly broken behaviour), at the very least a warning message should be displayed.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, restic is still a great piece of software :)

**Comment by MichaelEischer** [comment]
You're right that the `--no-lock` handling is rather confusing for several commands and you're not the first one confused by that, see for example #3464. I agree that restic should return an error if the command cannot work without locking, even though that's a backwards incompatible change.

Regarding the `copy` command the situation is rather complex. It is always necessary to lock the destination repository as a concurrent `prune` run could break the repository otherwise. However, for the source repository it would be possible to avoid locking similar as it works for the `restore` command. If a concurrent `prune` operation removes data from the source repository, then copying will fail but it won't damage the destination repository.

**Comment by djmattyg007** [comment]
I think making it possible to `copy` from a read-only source repository would be very valuable. For example, if the source repository was burned to a read-only medium (eg. a DVD).
