### ISSUE TITLE
google storage: customer-supplied encryption keys

### ISSUE THREAD

**Issue by browcio** [restic/restic#3530]
Output of `restic version`
--------------------------
restic 0.12.1 (v0.12.1-101-g78dac2fd-dirty) compiled with go1.16.8 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
I would like to implement customer-supplied encryption keys in google storage backend. 

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I believe that this would add another layer of security to cloud backups. GCP do not allow to download encrypted files without providing key even if user authenticate correctly.

It should be noted that customer-supplied keys are not zero-knowledge encryption because user sends encryption key with request and data are encrypted or decrypted in the cloud. Encryption key is stored in memory and removed after operation.

I made simple implementation based on https://cloud.google.com/storage/docs/encryption/using-customer-supplied-keys and it works. There are still some problems unsolved such as: how user should provide encryption key or whether to check if repo uses customer-supplied encryption or just return error to user.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is a very handy tool.

**Comment by MichaelEischer** [comment]
Closing based on https://github.com/restic/restic/pull/3612#issuecomment-1146869395
