### ISSUE TITLE
Automatic publishing of Docker Image

### ISSUE THREAD

**Issue by cimnine** [restic/restic#3547]
Output of `restic version`
--------------------------

n/a

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I suggest to add a GitHub Action workflow that automatically builds and publishes a Docker image of restic when a new release of restic is published.

This is a follow-up of https://github.com/restic/restic/pull/3520#issuecomment-939367267.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

It does not solve a problem per se, it just makes the release process easier. IMO it also makes the Docker image more trustworthy, since if it's built & published by an individual upon release it could contain arbitrary information.

(This can not be completely prevented though, since all individuals with push access to the relevant Docker registries can push and overwrite tags anyway. But that push access could be revoked for most/all human maintainers.)

This would also make it trivial to publish restic to other container registries, such as GitHub's own GitHub Container Registry or quay.io. The benefits would be redundancy when one goes down temporarily (or permanently) or should the terms and conditions of the Docker Hub change for the worse once more.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

:-)

**Comment by MichaelEischer** [comment]
Release builds and beta releases are available https://github.com/restic/restic/pkgs/container/restic .

**Comment by MichaelEischer** [comment]
The restic release binaries are fully reproducible, there's even a script to automatically verify them: https://restic.readthedocs.io/en/latest/developer_information.html#verifying-the-official-binaries
