### ISSUE TITLE
Bash completions file issue "line 128: syntax error near unexpected token `<"

### ISSUE THREAD

**Issue by nateify** [restic/restic#3549]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/amd64

How did you run restic exactly?
-------------------------------
restic generate --bash-completion ~/.bash_completion.d/restic

Expected behavior
-----------------
The shell should start without an error

Actual behavior
---------------
My shell starts with the following:
```
-sh: /home/user/.bash_completion.d/restic: line 128: syntax error near unexpected token `<'
-sh: /home/user/.bash_completion.d/restic: line 128: `        done < <(compgen -W "${out[*]}" -- "$cur")'
```

For reference, that location under home is added to my `.bashrc` via this method which also describes using it for restic explicitly: https://www.axllent.org/docs/user-defined-bash_completion-d/

Potentially helpful info:

Output of `uname -a`
`Linux hostname 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Output of `$SHELL --version`
`GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)`

Output of `echo $SHELL`
`/bin/sh`

The package version for bash-completion is **2.8**

Steps to reproduce the behavior
-------------------------------
Running the generate command for bash and then logging out and back in

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

**Comment by MichaelEischer** [comment]
Closing as this does not look like a problem of restic.
