### ISSUE TITLE
restic mount is broken on recent FreeBSD

### ISSUE THREAD

**Issue by shalottnet** [restic/restic#3550]
Output of `restic version`
--------------------------

`restic 0.12.1 compiled with go1.17 on freebsd/amd64`

How did you run restic exactly?
-------------------------------

```
% env |egrep 'REST|B2'
B2_ACCOUNT_KEY=XXX
B2_ACCOUNT_ID=XXX
RESTIC_PASSWORD_FILE=/mnt/cfs/restic-password-file
RESTIC_REPOSITORY=b2:my-backups

% restic mount /mnt/restic
repository XXXXXXXX opened successfully, password is correct
Now serving the repository at /mnt/restic
When finished, quit with Ctrl-c or umount the mountpoint.
resource temporarily unavailable
```

The FUSE filesystem never becomes mounted: the `mount` command never displays `/mnt/restic`, and attempts to access that directory hang.

After a few seconds (~10s - ~60s), `restic mount` spontaneously exits, and any hung commands complete.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

`B2`

Expected behavior
-----------------

The restic backups should become mounted.  `mount` should display `/mnt/restic` in its output, and it should be possible to list and navigate any snapshots in the repository.

Actual behavior
---------------

The restic backups do not become mounted.  `mount` does not display `/mnt/restic` in its output, and any attempts to access the mount point (`cd`, `ls`, etc) hang until the `restic mount` command successfully exits.

Steps to reproduce the behavior
-------------------------------

On FreeBSD -CURRENT after 2021-06-16 or -STABLE after 2021-07-03, run the following:

In one terminal:
```
export RESTIC_PASSWORD=12345 ;
export RESTIC_REPOSITORY=/tmp/rest_test_repo ;
mkdir -p /tmp/rest_test_testdir /tmp/rest_test_mt_pt ;
echo asdf > /tmp/rest_test_testdir/data.txt ;
restic init ; restic backup /tmp/rest_test_testdir ;
restic snapshots ;
restic mount /tmp/rest_test_mt_pt ;
```

In another terminal:
```
mount | grep restic
cat /tmp/rest_test_mt_pt/snapshots/latest/tmp/rest_test_testdir/data.txt
```

When `restic mount` exits, clean up with:
```
rm -rvf /tmp/rest_test_*
```

Do you have any idea what may have caused this?
-----------------------------------------------

The following commit to the FreeBSD FUSE driver:

CURRENT: https://cgit.freebsd.org/src/commit/?id=7b8622fa220b9c08041102f638f848c48e022644
STABLE: https://cgit.freebsd.org/src/commit/?id=7b096a997fad199eddccfb6784e4b85184d9af17

ktrace shows that restic invokes mount_fusefs as expected.

When running restic with debugging enabled, it appears that restic attempts to mount and then immediately attempts to unmount the FUSE filesystem; the unmount hangs for ~10s to ~60s, and eventually completes, at which point restic exits.  Snippet of the debug log;

```
2021/10/09 06:28:47 fuse/root.go:53     fuse.NewRoot    1       NewRoot(), config {false [] [] [] 2006-01-02T15:04:05Z07:00}
2021/10/09 06:28:47 fuse/snapshots_dir.go:113   fuse.NewSnapshotsDir    1       create snapshots dir, inode 255262462188919481
2021/10/09 06:28:47 fuse/snapshots_dir.go:153   fuse.NewTagsDir 1       create tags dir, inode 11966682851649564941
2021/10/09 06:28:47 fuse/snapshots_dir.go:141   fuse.NewHostsDir        1       create hosts dir, inode 9551839091146849951
2021/10/09 06:28:47 fuse/snapshots_dir.go:129   fuse.NewSnapshotsIDSDir 1       create snapshots ids dir, inode 18047884018718799214
2021/10/09 06:28:47 fuse/meta_dir.go:28 fuse.NewMetaDir 1       new meta dir with 4 entries, inode 1
2021/10/09 06:28:47 restic/cmd_mount.go:167     main.runMount   1       serving mount at /tmp/qresttestmtpt
2021/10/09 06:28:47 fuse/root.go:81     fuse.(*Root).Root       1       Root()
2021/10/09 06:28:47 restic/lock.go:99   main.unlockRepo 1       unlocking repository with lock PID 20534 on backuphost by root (UID 0, GID 0)
lock was created at 2021-10-09 06:28:47 (330.259221ms ago)
storage ID 422bea50
2021/10/09 06:28:47 cache/backend.go:37 cache.(*Backend).Remove 1       cache Remove(<lock/422bea50c8>)
2021/10/09 06:28:47 local/local.go:253  local.(*Local).Remove   1       Remove <lock/422bea50c8>
2021/10/09 06:28:47 restic/cmd_mount.go:170     main.runMount   1       finish mount
2021/10/09 06:28:47 restic/lock.go:119  main.unlockAll  1       unlocking 0 locks
2021/10/09 06:28:47 restic/cmd_mount.go:138     main.runMount.func1     1       running umount cleanup handler for mount at /tmp/qresttestmtpt
```

Do you have an idea how to solve the issue?
-------------------------------------------

Backing out the above FreeBSD commit restores the previous, correct behaviour.

However, I note that none of the other FUSE-based filesystems that I use (exfat, mtpfs, sshfs, etc) are misbehaving -- all work exactly as expected -- after that commit, so it does seem like restic must be doing something different.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic is one of my favorite pieces of software.  It solves what I once thought must be an impossible set of functional constraints (security: no non-encrypted bits ever leave the local system; efficiency: after the initial backup, only changes are sent over the wire).  I talk about it with my wife on our bicycle rides.  (True story...)

And (at least until it broke :P) I loved FUSE as an interface to the repository.

**Comment by greatroar** [comment]
Restic mount uses the bazil.org/fuse lib. I don't see any recent FreeBSD issues over at https://github.com/bazil/fuse/issues, but could you check that its examples still work with current FreeBSD?

```
$ go install bazil.org/fuse/examples/hellofs@v0.0.0-20200407214033-5883e5a4b512
$ hellofs -fuse.debug mountpoint
```

And the same for bazil.org/fuse/examples/hellofs@latest?

**Comment by shalottnet** [comment]
Thanks.

I see the same behaviour with the bazil.org/fuse hellofs (both your snapshot and `latest`): on FreeBSD prior to the above change, hellofs mounts as expected; after that change, the mount fails and prints `resource temporarily unavailable`.

hellofs looks like a much easier place to begin digging into the issue, so thanks for that pointer.  I'll try to take a look myself, but please let me know if there are any particular experiments that you'd like me to try.

**Comment by MichaelEischer** [comment]
See also https://github.com/restic/restic/issues/4043

**Comment by saj** [comment]
I see this bug is still open, so I would like to post a clarifying remark.

> broken on recent FreeBSD

This problem is resolved as of FreeBSD 14.0-RELEASE.  If you are still experiencing this problem, please update and try again.

```
# freebsd-version -k
14.0-RELEASE-p3
# restic version
restic 0.16.2 compiled with go1.20.12 on freebsd/amd64
```

restic as distributed in FreeBSD packages should work fine.

Following the links, the relevant FreeBSD PR appears to be [265736](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265736).  The patch was backported to `stable/13`, so I suppose this should work on FreeBSD 13.0-STABLE as well.

FreeBSD 13.2-RELEASE will not work.  I was still running 13.2-RELEASE until yesterday.  This bug is what finally motivated me to move.

A duplicate bug was filed in #4043

> restic mount fails on FreeBSD 13.1

https://www.freebsd.org/releases/13.3R/schedule/
if you must remain on FreeBSD 13

**Comment by MichaelEischer** [comment]
Does this still affect the latest restic version 0.16.5 which is now built with Go 1.22.4?

**Comment by MichaelEischer** [comment]
Ah, I should read the issue. The bugfix is apparently release in FreeBSD by now. So there's nothing left to do here. Please protest if that assessment in incorrect.
