### ISSUE TITLE
Restic hangs if SSL certificate chain is invalid

### ISSUE THREAD

**Issue by akharlamov** [restic/restic#3556]
Output of `restic version`
--------------------------
0.12.1

How did you run restic exactly?
-------------------------------
export RESTIC_REPOSITORY=b2:xxxx
export RESTIC_PASSWORD_FILE=/root/.restic/password
export B2_ACCOUNT_ID=yyyy
export B2_ACCOUNT_KEY=zzz

/usr/bin/restic --verbose=2 list snapshots

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
Restic displays list of snapshots in the repository or displays an error

Actual behavior
---------------
Restic hangs in an infinite loop trying to set up an HTTPS connection with api.backblazeb2.com
No messages printed. 

Steps to reproduce the behavior
-------------------------------
1. Remove Let's Encrypt ISRG Root X2 certificate from /usr/share/ca-certificates and run `update-ca-certificates`
2. Try to connect to B2
3. Profit

Do you have any idea what may have caused this?
-----------------------------------------------
If TLS connection setup fails restic goes into an infinite loop.

**Comment by acsfer** [comment]
@MichaelEischer should be fixed now at https://github.com/kurin/blazer/pull/80?
