### ISSUE TITLE
Strange error when trying to back up seemingly normal file on Windows 10

### ISSUE THREAD

**Issue by Gaibhne** [restic/restic#3558]
Output of `restic version`
--------------------------
`restic 0.12.1 compiled with go1.16.6 on windows/amd64`

How did you run restic exactly?
-------------------------------
`restic -r rest:http://joerg:password@restic.myserver.com/joerg/ --verbose backup --use-fs-snapshot C:\ --exclude-file c:\dev\sync\backups\desktop-ryzen.exclude.txt`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
`restic-rest`, running on a Raspberry Pi 4 (`arm`) running Fedora 34

Expected behavior
-----------------
I would expect the file to get backed up with no complaints (or an error indicating what prevents a backup).

Actual behavior
---------------
I get the following error:
`scan: CreateFile \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\Users\Joerg\AppData\Roaming\Adobe\CameraRaw\ImportedSettings\OPEN - Portrait Film Profile: The system cannot find the file specified.`

And later during the process again:
`error: CreateFile \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy6\Users\Joerg\AppData\Roaming\Adobe\CameraRaw\ImportedSettings\OPEN - Portrait Film Profile: The system cannot find the file specified.`

Steps to reproduce the behavior
-------------------------------
The problem seems deterministic; repeated runs trigger the same error on the same file.

Do you have any idea what may have caused this?
-----------------------------------------------
Nada.

Do you have an idea how to solve the issue?
-------------------------------------------
None. But as additional info: the folder `C:\Users\Joerg\AppData\Roaming\Adobe\CameraRaw\ImportedSettings` contains multiple subfolders alongside `OPEN - Portrait Film Profile`, with similar name patterns, such as `OPEN - Warm Haze Profile`, which all seem to back up with no complaints.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I have started running backups on all my machines, and the combined repo for the four I'm backup up right now (with ~220, 190, 200 and 430 GB of data, respectively) is 284G. That's a ton of deduplication!

**Comment by MichaelEischer** [comment]
I've no real idea what's going on here. Are you able to backup that problematic file (folder?) when not using `--use-fs-snapshot`?

**Comment by Gaibhne** [comment]
No:

`scan: CreateFile \\?\C:\Users\Joerg\AppData\Roaming\Adobe\CameraRaw\ImportedSettings\OPEN - Portrait Film Profile: The system cannot find the file specified.`

**Comment by rawtaz** [comment]
Can you make sure there's no funky chars in the filename? One way to do that could be to use the Rename function in Explorer, Ctrl+a to mark all of it, cut that, enter a new name like "foo" or whatever, press enter to save that name, and see if that works to back up. If so, it was something with the filename. Otherwise it's wasn't. You still have the old name in your clipboard if you want to rename it back after that.

**Comment by Gaibhne** [comment]
There was indeed a funky char in the file name - tab autocomplete presented it as `"OPEN - Portrait Film Profile "` (note the space before the closing `"`), but with or without the space (or alt+255), I could not do much with the name. Couldn't even rename it in Windows Explorer, had to use `dir /X` and then `ren` the short name. So it sounds like it probably isn't a restic specific issue, though obviously it would be good if restic could either handle the weird char or indicate in the error what the problem is, so the next person has to spend a little less time with support channels ;)

Since this seems only remotely restic-related, and I'm not even sure restic can deal with it, feel free to close the issue if you don't want to keep it open as a reminder to maybe improve the error message or something of the sort.

**Comment by rawtaz** [comment]
One simple thing could be to enclose file names reported in e.g. error messages in some kind of quote, so that one can actually identify e.g. a trailing space in the filename.

**Comment by Dobatymo** [comment]
I am not exactly sure why there is an error in the first place. `CreateFile` should be able to handle UNC paths (starting with `\\?\`) which have a trailing space.
I just tested `open(r"\\?\D:\tmp\asd.txt ", "rb")` (in Python, but same CreateFile win32 api call I think) and it works fine. It might have todo with the shadow copy though...

**Comment by Gaibhne** [comment]
It isn't a regular trailing space, it has to be some special character that is rendered as a space, I'm sorry if I didn't make that clear. I know nothing about file systems, but with it being at the end of the name, could it be something like a null terminator that somehow became part of the file name ? With the file renamed, I unfortunately can't reproduce the issue anymore, as Windows' `ren` command won't let me recreate the funky file name.

**Comment by Dobatymo** [comment]
@Gaibhne zero bytes (and other ascii control characters) are indeed not allow in windows filenames (not only as trailing bytes, but anywhere).
It's pretty difficult to create these files though, as even low level windows apis won't allow you to create them...

**Comment by MichaelEischer** [comment]
As the error reported by restic doesn't seem to contain any character between `Profile:` and the colon, this looks indeed like a terminating null byte or similar. Most more normal windows path problems should be handled by #2745 . Besides just adding quotes around the filenames I don't think there's much we can do here.

**Comment by gum3ng** [comment]
I would like to help with this issue. I am working on formatting the error message in the file 'internal/ui/backup/text.go'

**Comment by rawtaz** [comment]
Not sure how feasible it is to quote the filename. Currently we're printing an error coming from `os.Lstat()` that already contains the error message including the filename. So either we have to replace the usage of that already complete error message with our own, or find a way to quote the filename part of it (which would be very ugly).

Perhaps a better approach, considering how very rare these errors/issues are, is to simply add a little section about it in the FAQ at https://restic.readthedocs.io/en/stable/faq.html (this will probably be split into a troubleshooting section in the future)?
