### ISSUE TITLE
Restic Init fails for S3 SSE enabled buckets

### ISSUE THREAD

**Issue by jmeza-xyz** [restic/restic#3564]
Output of `restic version`
--------------------------
```
docker run -it velero/velero:v1.7.0 restic version
restic 0.12.0 compiled with go1.15.8 on linux/amd64
```
How did you run restic exactly?
-------------------------------
Ran restic through the latest version of Velero 1.7.0 in a K8s cluster v1.19. Command being run to initialize the repository:
```
restic init --repo=s3:<s3-repo> --password-file=/path/to/credentials --cache-dir=/scratch/.cache/restic
```
Ran the same restic binary version 0.12.0 locally to init the S3 repo and get access denied
```
restic init --repo=s3:<s3-repo>
enter password for new repository: 
enter password again: 
Fatal: create key in repository at s3:<s3-repo> failed: client.PutObject: Access Denied
```
Verified that IAM policies are correct based off of this [documentation](https://github.com/vmware-tanzu/velero-plugin-for-aws#option-1-set-permissions-with-an-iam-user)

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SSE AES256 encrypted S3 bucket

Expected behavior
-----------------
Not expected, but a request to have a `--sse` flag or `-o s3.sse="AES256"` flag to enable this feature in the Minio SDK being used by Restic.

Actual behavior
---------------
Connection denied if S3 bucket has SSE enabled. If S3 bucket has SSE disabled, repo initializes.
`Fatal: create key in repository at s3:<s3-repo> failed: client.PutObject: Access Denied`

Steps to reproduce the behavior
-------------------------------
Initialize restic repo to an S3 bucket that has AES265 encryption enabled
```
restic init --repo=s3:<s3-repo>
enter password for new repository: 
enter password again: 
Fatal: create key in repository at s3:<s3-repo> failed: client.PutObject: Access Denied
```

Do you have any idea what may have caused this?
-----------------------------------------------
Restic doesn't provide an option for SSE encryption. The Minio SDK does have the putObjectOption for ServerSideEncryption [here](https://pkg.go.dev/github.com/minio/minio-go/v7#PutObjectOptions.Header)

Do you have an idea how to solve the issue?
-------------------------------------------
Please add a command flag to restic init or -o option to enable SSE for S3 buckets that are required to have SSE enabled.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic provided me some decent hours of frustration, but that doesn't take away my view that this project is awesome. I appreciate the work being done.

**Comment by MichaelEischer** [comment]
Passing the encryption key via a command line option isn't particularly secure. It would probably be better to use environment variables, although that is also not optimal. As the key is also necessary to read any data, I suppose it has to be passed to restic on each invocation?

The more complex problem here is to keep the complexity low enough to not create a maintenance burden for us, as already mentioned in #2008. SSE seems to be available in several variants, which makes things rather messy.

**Comment by MichaelEischer** [comment]
Closing based on https://github.com/restic/restic/pull/3612#issuecomment-1146869395

Please use S3 via rclone if you really need this feature.
