### ISSUE TITLE
backing up via another restic fuse mount: read input/output error 

### ISSUE THREAD

**Issue by Kriechi** [restic/restic#3567]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/arm64

uname: `Linux myhostname 5.10.63-rockchip64 #21.08.2 SMP PREEMPT Wed Sep 8 10:57:23 UTC 2021 aarch64 GNU/Linux` on a Debian Buster-based system.

How did you run restic exactly?
-------------------------------
First terminal:
```
export RESTIC_REPOSITORY=/source_backup
export RESTIC_PASSWORD_FILE=/source.pw
mkdir /tmp/source-mount
restic mount /tmp/source-mount
```
Second terminal:
```
export RESTIC_REPOSITORY=/destination_backup
export RESTIC_PASSWORD_FILE=/destination.pw
restic backup --exclude-file /exclude-file.txt --tag some-tag --time "2019-11-09 17:00:03" /tmp/source-mount/latest
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
All local on the same Linux system on the same SSD.

Expected behavior
-----------------

Back up all the files from the fuse mount point without errors.

Actual behavior
---------------

Multiple error messages, such as:

```
error: read some/file/that/is/being/backed/up.txt: input/output error
```

I do not see any retry messages, so I have to assume each file that caused an error message was successfully not backed up.

Steps to reproduce the behavior
-------------------------------

Happens every time when I try to back up with the above commands.

Do you have any idea what may have caused this?
-----------------------------------------------

The restic fuse mount seems to fail or cause read errors.

I've already run a `restic check` which `--read-data` on the source and the destination repo. No errors reported.
I can `restic restore --include the/files/that/caused/read/errors.txt`  without issues and I get the correct file and file content. The read errors do not happen on the same files between consecutive runs with the same parameters.

Do you have an idea how to solve the issue?
-------------------------------------------

No.

I've already tried compiling restic from a fresh master, and even bumped the fuse go module in the hope there might be a recent bugfix, but my read errors are still there.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm trying to migrate restic snapshots into a new repository with new chunker params while also excluding some files from the original snapshot. Happy to hear if there is a simpler method than mounting the old snapshot, and then backing it up into a new repo.

**Comment by MichaelEischer** [comment]
Can you try whether setting the environment variable `GODEBUG` to `asyncpreemptoff=1` helps?

**Comment by Kriechi** [comment]
Yes, adding `GODEBUG=asyncpreemptoff=1` to both restic processes (mount & backup) looks promising.
I did not see errors so far - I will give it a longer test over the next days.

I've also run the `restic mount` with `--verbose=3` and it didn't print anything. So only the "reader" (== restic backup process) is reporting the input/output error.
