### ISSUE TITLE
Volume in container image is backed up as empty folder

### ISSUE THREAD

**Issue by TomHutter** [restic/restic#3577]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/amd64

How did you run restic exactly?
-------------------------------
As plugin of velero on a K8s cluster. 

velero version                              
Client:
        Version: v1.6.0
        Git commit: 5bd70fd8eef316d220317245e46dc6016c348dce
Server:
        Version: v1.6.0

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Rados Object Gateway (octopus)

Expected behavior
-----------------

All data will be backed up.

Actual behavior
---------------

When the container image has a volume defined and this volume is a sub folder in the PVC to back up, the sub folder backup contains no data. In my case I created a pod with the image `postgres:bullseye`. This image contains a volume: `/var/lib/postgres/data`. The pod has a PVC mounted on `/var/lib/postgres`. When running a backup, data in `/var/lib/postgres/data` will not be backed up - `/var/lib/postgres/data` is empty.

Steps to reproduce the behavior
-------------------------------

Create a pod with the sts definition below:

~~~
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  serviceName: postgresql-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: database
      labels:
        app: db
      name: postgresql
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 999
      terminationGracePeriodSeconds: 30
      containers:
      - name: db
        image: postgres:bullseye
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
            name: postgresql
            protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: database
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: test
          - name: POSTGRES_PASSWORD
            value: password
        securityContext:
          runAsUser: 999
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: database
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      volumeMode: Filesystem
~~~
Once the pod is up and running. 
* Enter the pod: `kc exec -it postgresql-0 -- bash`
* Create some extra data in /var/lib/postgres: `cd /var/lib/postgresql/ && tar czvf data.tar.gz data`
* Run a backup: `velero backup create postgres-test --snapshot-volumes --selector app=db`
* Restore the snapshot: `restic restore -t /tmp/restore --cache-dir=/scratch/.cache/restic <snapshot>`

Compare pod and restored data:

**pod:**

listing:

~~~
postgres@postgresql-0:~$ ls -l
total 6228
drwx------ 19 postgres postgres    4096 Nov 15 09:16 data
-rw-r--r--  1 postgres postgres 6353678 Nov 15 09:19 data.tar.gz
drwxrws---  2 root     postgres   16384 Nov 15 09:16 lost+found
~~~

files in data:

~~~
postgres@postgresql-0:~$ find data | wc -l
1278
~~~

**restore:**

listing:

~~~
/tmp/restore$ ls -l 
total 6216
drwxr-sr-x 2 nobody nogroup    4096 Nov 15 09:16 data
-rw-r--r-- 1 nobody nogroup 6353678 Nov 15 09:19 data.tar.gz
drwxrws--- 2 nobody nogroup    4096 Nov 15 09:16 lost+found
~~~

files in data:

~~~
/tmp/restore$ find data | wc -l
1
~~~

Do you have any idea what may have caused this?
-----------------------------------------------

I created a pod with the image `postgres:bullseye`. This image contains a volume: 

inspect image:
~~~
        "Volumes": {
          "/var/lib/postgresql/data": {}
~~~

postgres want's to change the ownership and file mode bits during startup and runs on error, when the PVC is mounted on `/var/lib/postgres/data`. So I mounted the PVC on `/var/lib/postgres`.  

Running a backup on this pod the data in `/var/lib/postgres/data` will not be backed up. 

I did a `restic restore snapshot` on the created snapshot and the folder data is there, but no content. Files I put in `/var/lib/postgres` show up in the backup. Files in  `/var/lib/postgres/data` not.

It seems that for an unknown reason restic get's confused by the volume defined in the image and backs up the empty volume.

Do you have an idea how to solve the issue?
-------------------------------------------
No. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Not really. The data I expected to have in my backups wasn't there. Imagining how I feel ;-)

**Comment by rawtaz** [comment]
I think this is something that you should debug on the Velero side. We don't know what Velero does when you run the `velero backup ...` command. In the end it boils down to which exact restic command is run, with what environment, and so on. In general restic will back up the files that it was asked to back up, as long as it can read them successfully and the files aren't [excluded](https://restic.readthedocs.io/en/stable/040_backup.html#excluding-files) for some reason, and things like  `--one-file-system` isn't affecting things. Can you please start there? Perhaps open an issue with the Velero project if you feel everything is configured properly?

**Comment by TomHutter** [comment]
Sure thing. During my debugging I read a similar issue on the velero site and they pointed the issuer towards you. So I tried my luck here first :-) Thanks for the fast response.
