### ISSUE TITLE
restic as a git extension - an alternative to `git lfs`

### ISSUE THREAD

**Issue by haneef95** [restic/restic#3579]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/amd64 (docker)

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Make a git extension as an alternative to `git lfs`! restic <-> git integration!

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Lots of repos have binaries, and there are two options for them (neither are good):
1.  Make a full copy of the binary upon every modification. (no chunking or deduplication)
2.  Ignore those specific binary files. (untracked)

There isn't a 'magic' way of identifying the binary files and keep them in an orderly snapshot. It would really help if restic could fill that gap!

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
At first use... restic looks very promising, a well thought-out product. Would really help if this feature request is done! 😄

**Comment by haneef95** [comment]
## Potential way to implement (1 - Simple)
1. Restic is integrated within the usuals of git functions, example below:
2. Restic is executed as a [pre-commit hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#:~:text=The%20pre-commit%20hook%20is%20run%20first) for git. Which does a `restic backup --tag 'gitbranch:master'`
3. Restic replaces the `currentsnapshotid.env` file with the latest snapshot id
4. git completes a commit
5. Restic is executed as a post-commit hook, `restic tag --add 'gitcommitid:sha256'

Similar appropriate process for checking out a branch, revert commit and etc...

### Folder structure

> 
> - gitresticrepo
> 	- .git
> 	- .restic
> 		- config.env _(holds [restic env variables](https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables))_
> 		- currentsnapshotid.env _(holds the snapshotid as an env variable.)_
> 		- repo* _(default local repo/backend)_
> 		- mount* _(mount point which has the active snapshot mounted)_
> 	- appcode
> 	- appassets
> 		- images
> 			- img1.jpg
> 		- videos
> 			- vid1.mp4
> 
> 
> _* these files/folders are on `.gitignore`_
>

**Comment by MichaelEischer** [comment]
The steps you've described so far sound like a git integration is possible without making changes to restic. Providing the necessary wrappers for git as part of restic seems out of scope to me.

You might want to take a look at https://forum.restic.net/t/rfc-creating-git-remote-restic/3496 .

**Comment by MichaelEischer** [comment]
Closing as this seems out of scope and we don't have the capacity to implement and maintain such a feature anyways.
