### ISSUE TITLE
prune ends with "Integrity check failed:"

### ISSUE THREAD

**Issue by keycized** [restic/restic#3581]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/amd64

How did you run restic exactly?
-------------------------------
restic -r b2:storage01backup -p /xxxx/repopassword_file.txt forget --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 10 --prune

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
End "prune" without error

Actual behavior
---------------
[0:01] 100.00%  1 / 1 files deleted
1 snapshots have been removed, running prune
loading indexes...
loading all snapshots...
finding data that is still in use for 49 snapshots
[0:28] 100.00%  49 / 49 snapshots
searching used packs...
{<data/25e4dc93>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
Fatal: index is not complete

Steps to reproduce the behavior
-------------------------------
Don't know. 
Restic runs since long time without error. But suddenly this error came up.
I already tried to run a rebuild-index. The rebuild run without error, but the prune still runs into the same error.

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
Did you notice any errors reported in prior restic runs or did something unexpected happen? Maybe an interrupted network connection or did the host go into standby while restic was running?
Do you have logs of the `backup` and `prune` run before the prune error? Did restic report any errors there?
How often do you run `backup`, `check` and/or `prune`? Do you use the `unlock` command or is it called automatically from your backup scripts?

Please run `restic check` to analyze the damage to the repository. Did `rebuild-index` print any output?

It would be helpful to know which snapshots are missing blobs: Please run `restic find --blob 25e4dc93` to find the affected snapshots.

It would be interesting to know whether the damaged snapshot(s) is/are for example the latest snapshot or maybe some random older one(s). Is there any correlation between prune runs and the creation time of the damaged snapshots? Did you run prune since these snapshots were created?
If you still have the log files: Did any of these backup runs report errors?

**Comment by keycized** [comment]
I should have all the logs for the previous runs of Restic. But for which keywords should I search.

restic runs on a daily basis with the following sequence:

restic backup --files-from xxx --exclude-file xxx
restic snapshots
restic forget --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 10 --prune
restic snapshots


As suggested I run the following commands:

restic -r b2:storage01backup -p /xxx/repopassword.txt check
using temporary cache in /tmp/restic-check-cache-043190168
repository 7679efc4 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-043190168
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree 6d71bd06:napshots
  tree 6d71bd06: file "Documentxx.docx" blob 25e4dc93223f16a774efb5698802831834adc328eb72a23948f8ff2850d97650 not found in index
error for tree 2cdb6d67:napshots
  tree 2cdb6d67: file "Documentxx.docx" blob 25e4dc93223f16a774efb5698802831834adc328eb72a23948f8ff2850d97650 not found in index
[3:09] 100.00%  49 / 49 snapshots
Fatal: repository contains errors



restic -r b2:storage01backup -p /xxx/repopassword.txt rebuild-index
repository 7679efc4 opened successfully, password is correct
loading indexes...
getting pack files to read...
rebuilding index
[0:19] 100.00%  12588 / 12588 packs processed
deleting obsolete index files
[0:04] 100.00%  10 / 10 files deleted
done


restic -r b2:storage01backup -p /xxx/repopassword.txt find --blob 25e4dc93
repository 7679efc4 opened successfully, password is correct
Found blob 25e4dc93223f16a774efb5698802831834adc328eb72a23948f8ff2850d97650
 ... in file /Folder1/Documentxx.docx
     (tree 2cdb6d67aa7ef792eed5c5e720ef502d47be9422be63523b25f9a1db122d630b)
 ... in snapshot b13f28a1 (2018-12-31 22:32:01)
Found blob 25e4dc93223f16a774efb5698802831834adc328eb72a23948f8ff2850d97650
 ... in file /Folder2/Documentxx.docx
     (tree 6d71bd06ed692cbc1a77f12c6f8ebcd904d9ee0636ea670114fe739d82df05aa)
 ... in snapshot e686fc47 (2019-12-31 01:30:01)

**Comment by MichaelEischer** [comment]
Have you been using restic 0.12.1 for some time now or have you upgraded recently?

Did the last `prune` run before the prune errors started, report anything unusual? As the damaged snapshots are rather old ones, it is likely that one of the recent prune runs somehow lost one data blob. Do you run `check` from time to time?

To repair the repository you can follow these steps: https://github.com/restic/restic/issues/828#issuecomment-706186047 . Unfortunately, it looks like that particular file is lost (unless you still have a copy of the file lying around somewhere else).

**Comment by keycized** [comment]
I've deleted the corrupted snapshots with `restic forget`. I still have the file in the corrupted snapshot on my local drive. So no worries about that.
I probably have to run `restic check`  more often.
Man thanks for your help!
