### ISSUE TITLE
Can we specify files to be restored from stdin or some file ? else can it be add ?

### ISSUE THREAD

**Issue by akharrou** [restic/restic#3587]
> `restic 0.12.1 compiled with go1.17.2 on darwin/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Is it possible to specify which files we would want to restore from standard input, or from a file ? If not, could that be added ?

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I'm trying to do one of the following:

```zsh
# from file
$> restic ls latest | fzf --header-lines=1 | tee /tmp/restic.ls.out 
$> restic restore latest --files-from /tmp/restic.ls.out

# from stdin
$> restic ls latest | fzf --header-lines=1 | tee /tmp/restic.ls.out | restic restore latest

# or instead of `fzf`, using `find` or other tools
```

solves problem of inconvenience, user-interface usability/ease-of-use, not having to write out entire list of files I want to include/exclude, being able to do things more programmatically.

---

A currently working work around:

```zsh
$> restic restore latest --verify --repo /srv/restic-repo --target /tmp/restic-restore-repo/ \
    $( restic ls latest \
       | fzf --header-lines=1 \
       | tee /tmp/restic.ls.out \
       | xargs -I{} printf " --include {}" )
```

---

`borg` offers `--pattern-from FILE`, `--exclude-from FILE`.

**Comment by MichaelEischer** [comment]
I guess we can add "--exclude-file", "--iexclude-file" and "--files-from{,-raw,-verbatim}" options similar to the backup command. We could probably discuss whether we need all three variants of `--files-from` but then again it's probably better to just stick closely to the backup command.

Any up for a PR?
