### ISSUE TITLE
Quiet `removing $n old cache dirs from $repo`.

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#3595]
`restic backup -q --cleanup-cache` outputs `removing $n old cache dirs from $repo`.

In my opinion, `-q` should suppress the message.

Is that ok? If yes, /assign self

**Comment by MichaelEischer** [comment]
Changing the message to not print if `--quiet` is set sounds reasonable. I'd also hide the output if the json output is enabled. Currently, the other cache related output is only displayed if `!opts.JSON && stdoutIsTerminal()`, although restricting that output to only display on a terminal might be a bit too strict.
