### ISSUE TITLE
unable to save snapshot: NodeFromFileInfo: Listxattr: xattr.list /home : permission denied

### ISSUE THREAD

**Issue by gdmn** [restic/restic#3600]
Output of `restic version`
--------------------------

    restic 0.12.1 compiled with go1.16.6 on freebsd/amd64

How did you run restic exactly?
-------------------------------
      restic -vvv backup \
        --repository-file "repository2" \
        --password-file "password2" \
        --files-from "include.txt" \
        --iexclude-file "exclude.txt" \
        --exclude-if-present .exclude_from_restic_bkp \
        --one-file-system

Content of include.txt

    /home/dmn/bin

Result:

    Fatal: unable to save snapshot: NodeFromFileInfo: Listxattr: xattr.list /home : permission denied

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
    rest-server 0.10.0 compiled with go1.17.3 on linux/amd64

Expected behavior
-----------------

Snapshot is created and missing attributes are ignored.

Actual behavior
---------------

Snapshot is not created.

Steps to reproduce the behavior
-------------------------------

I tried to run restic on shared shell account. The permissions are restrictive there.

    $ ls -al /home
    lrwxr-xr-x  1 root  0  8  6 aug  2015 /home -> usr/home
    $ ls -al /usr/home
    total 0
    ls: /usr/home: Permission denied

Do you have any idea what may have caused this?
-----------------------------------------------

My user does not have permission to read attributes from directories above.

Do you have an idea how to solve the issue?
-------------------------------------------

Ignore the permission read error.

**Comment by MichaelEischer** [comment]
Does `cd /home/dmn && restic backup bin` work?

For absolute paths restic includes the permissions of all directories starting from the root directory. I guess we could ignore permission errors in the specific case here, though. https://github.com/restic/restic/blob/c5c3dfe10fff4e6e18b8f6eaefcbbac856674f7f/internal/archiver/archiver.go#L626

**Comment by gdmn** [comment]
> Does `cd /home/dmn && restic backup bin` work?

yes, it works :)

**Comment by MichaelEischer** [comment]
I've opened #3853 can you test whether that fixes the issue for you?
