### ISSUE TITLE
Unable to backup, repository locked?

### ISSUE THREAD

**Issue by clement850** [restic/restic#3609]
(I think the issue is similar with https://github.com/restic/restic/issues/1450, but not resolved for me)

Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/amd64

How did you run restic exactly?
-------------------------------
```
source .env 
/usr/sbin/restic backup --files-from include.txt --exclude-file exclude.txt
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
- OVH Object Storage (doesn't work)
- Scaleway Public Cloud S3 (doesn't work)

We have 150 servers with the same configuration, 149 works, only this one blocks

Expected behavior
-----------------

Successfully backups

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

I already launch : 
```
restic unlock

>>> repository d19aa123 opened successfully, password is correct
>>> successfully removed locks
```
```
restic check       (no errors)

>>> no errors were found
``` 
```
restic rebuild-index

>>> [0:55] 100.00%  494 / 494 packs
rebuilding index
[0:03] 100.00%  6818 / 6818 packs processed
deleting obsolete index files
[0:01] 100.00%  12 / 12 files deleted
done
```
```
restic check       (still no errors)

>>> no errors were found
``` 
```
source .env 
/usr/sbin/restic backup --files-from include.txt --exclude-file exclude.txt


>>> 29352 Processus arrêté
>>> unable to create lock in backend: repository is already locked by PID 29352 on debian by root (UID 0, GID 0)
>>> lock was created at 2021-12-29 09:01:41 (4m15.650342157s ago)
>>> storage ID 312aaaa1
>>> the `unlock` command can be used to remove stale locks

```
Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
> ```
> >>> 29352 Processus arrêté
> >>> unable to create lock in backend: repository is already locked by PID 29352 on debian by root (UID 0, GID 0)
> ```

That looks like the restic process with pid 29352 (I've no idea about the command-line, likely check/prune/rebuild-index) was paused (?) and still has locked the repository exclusively. The commands check/prune/rebuild-index lock the repository exclusively which prevents other processes from accessing the repository. 

Did all earlier restic processes exit cleanly? Does `restic list locks` show more than one lock file?

Is there a reason why you've run `restic rebuild-index`? That command should only be used when restic reports some repository damage. It won't help at all with locking problems.

**Comment by clement850** [comment]
> Did all earlier restic processes exit cleanly? Does restic list locks show more than one lock file?

Yes, I think that I have 2 lock files, because there are two lines...

> Is there a reason why you've run restic rebuild-index?

Nope I tested all the possibilities 😬

**Comment by MichaelEischer** [comment]
> Yes, I think that I have 2 lock files, because there are two lines...

Once a lock file has become stale, `restic unlock` should be able to delete it. Afterwards there should only be one lockfile left. Did you run all commands using the same user?
You can also try whether `restic unlock --remove-all` helps. Note that the latter command should only be run if there are no other restic processes running.

> 29352 Processus arrêté

As mentioned before, this is probably the cause of the locking problems. So you'll have to search for whatever triggers that message. Did you check whether restic maybe ran out of memory or something else?

**Comment by clement850** [comment]
Yes, launched using the same user. 

Not out of memory, maybe the swap is full... I will deactivate it

**Comment by clement850** [comment]
Resolved! It was a directory with too many files, and what causes the saturation of server. Thanks
