### ISSUE TITLE
Missing colon in prune output

### ISSUE THREAD

**Issue by mattxtaz** [restic/restic#3617]
Output of `restic version`
--------------------------

restic 0.12.1 compiled with go1.16.6 on freebsd/amd64

How did you run restic exactly?
-------------------------------

restic prune

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

sftp

Expected behavior
-----------------

to repack:          907 blobs / 3.743 MiB  
this removes:        191 blobs / 1002.958 KiB
to delete:          212 blobs / 90.811 MiB                                                                                                             
total prune:        403 blobs / 91.791 MiB
remaining:        32232 blobs / 6.252 GiB
unused size after prune: 271.040 MiB (4.23% of remaining size)

Actual behavior
---------------

to repack:          907 blobs / 3.743 MiB  
this removes        191 blobs / 1002.958 KiB
to delete:          212 blobs / 90.811 MiB                                                                                                             
total prune:        403 blobs / 91.791 MiB
remaining:        32232 blobs / 6.252 GiB
unused size after prune: 271.040 MiB (4.23% of remaining size)

Steps to reproduce the behavior
-------------------------------

Run restic prune and view the output. It looks like "this removes" should have a colon after it so that it matches the other lines.

Do you have any idea what may have caused this?
-----------------------------------------------

Accidently left off

Do you have an idea how to solve the issue?
-------------------------------------------

Add the colon into line 465 of cmd/restic/cmd_prune.go

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is an excellent tool. I use it for multiple backups to B2, AWS-S3, and SFTP and it has never let me down. Thank you very much for it!

**Comment by rawtaz** [comment]
Can you open a PR? :+1:

**Comment by mattxtaz** [comment]
I've just realised this is probably because all of the lines use %10d with appropriate spacing and the "this removes" line doesn't fit with that unless the spacing of every other line is changed to push them out by one more. I assume that's not actually wanted?

**Comment by rawtaz** [comment]
Not really (unless I misunderstand you). If you count the characters before `%10d` you'll see that it's 13 characters in each of those related lines. It's just a matter of the colon not fitting within these 13 characters (assuming a space after the colon). So if you could just make those 13 characters be 14 characters instead, and include the missing colon, it should be fine. The `%10d` only has to do with the following numbers. It's lines 461-469 you need to change, the rest aren't relevant.
