### ISSUE TITLE
Possible new info regarding `pack not referenced in any index`

### ISSUE THREAD

**Issue by fkusche** [restic/restic#3620]
Output of `restic version`
--------------------------
`restic 0.12.1 compiled with go1.16.6 on linux/amd64`

How did you run restic exactly?
-------------------------------
```bash
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...
export RESTIC_PASSWORD=...
/opt/restic/restic backup -r s3:https://s3.eu-central-1.wasabisys.com/... --json --quiet --one-file-system --limit-upload=20000 --exclude-caches --iexclude=tmp --iexclude=.cache --iexclude=./var/cache /

Save(<data/afa85e951d>) returned error, retrying after 552.330144ms: client.PutObject: Maximum number of server active requests exceeded
```

For checking:
```
/opt/restic/restic check -r s3:https://s3.eu-central-1.wasabisys.com/... --read-data-subset 1%

using temporary cache in /tmp/restic-check-cache-499500195
create exclusive lock for repository
load indexes
check all packs
pack cd223624: not referenced in any index
pack 57ed8770: not referenced in any index
pack 6d0233b2: not referenced in any index
...
367 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.check snapshots, trees and blobs
[13:04] 100.00%  121 / 121 snapshots
read 1.0% of data packs
[5:40] 100.00%  510 / 510 packs
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Wasabi S3

Expected behavior
-----------------

No messages regarding unreferenced packs.

Actual behavior
---------------

Messages regarding unreferenced packs shown.

Steps to reproduce the behavior
-------------------------------

See above and my additional informations below.

Do you have any idea what may have caused this?
-----------------------------------------------

The unsuccessful `PutObject` call.

Do you have an idea how to solve the issue?
-------------------------------------------

No.

Additional background info
-------------------------------

I have possibly some new info regading the "not referenced in any index" messages. The FAQ states, that the reason for them is yet unknown.

Since a few weeks, I am backing up 3 computers every night to Wasabi S3 storage. Also, every morning, I run `restic check --read-data-subset 1%`.
Every now and then, I got a bunch of errors during backup regarding `PutObject`, but they where non-fatal as they always said "retrying after ...". (I'm not 100% sure, because I did not use `--quiet` except for the last few days, so maybe I missed a fatal error.) The checks in the morning always ran without any error or warning.
All Backup jobs run in sequence not in parallel.

Last night I had two new errors during backup which I did not experience before:
- On my linux machine, I got a fatal error from `PutObject`: `Save(<data/afa85e951d>) returned error, retrying after 552.330144ms: client.PutObject: Maximum number of server active requests exceeded`
- On a windows machine, I got a few of those:
  ```json
  {"during": "archival",
   "error": {
       "Err": 21,
       "Op": "read",
       "Path": "\\\\?\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy12\\data\\info\\abc"},
   "item": "c:\\data\\info\\abc",
   "message_type": "error"
  ```
  Maybe those are because of a Veeam Agent Backup running in parallel, which also creates a Volume Shadow Copy. I now have changed the time of the Veeam Backup, so this should not happen again. However, those backups have been running in parallel for weeks now and this is the first time I got those errors.
  
Then, in the morning, the daily `restic check` gave me 367 messages like `pack 8d6f0843: not referenced in any index`. This is the first time I see those messages. I think it is very likely that those messages a caused by either the fatal `PutObject` call or the read errors. (I suspect the former.)

Just for testing if it relates to the local cache, I ran `restic check` on the third box (another linux machine). It also outputs the warnings. I checked a few random IDs and it seems that the list is the same.

For now, I did not run `restic prune`. If any dev wants to try something out, I will gladly assist.

I guess, the fatal upload error should be healed with another backup run? Is this correct?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic still makes me sleep much better...

**Comment by MichaelEischer** [comment]
> I have possibly some new info regading the "not referenced in any index" messages. The FAQ states, that the reason for them is yet unknown.

I guess we should remove that last sentence from the FAQ. The usual cause of "not referenced in any index" warnings are interrupted backup runs. Just cancel a backup and you are left with not-referenced pack files. Just run `prune`, its first action after verifying the repository integrity is to just remove the not-referenced pack files.
