### ISSUE TITLE
Can not use an S3 bucket in the non-default region

### ISSUE THREAD

**Issue by liljenstolpe** [restic/restic#363]
Greetings,

I have a bucket in us-west-2.  When I try and init that bucket, I get the following error:

creating key in backend at s3://us-west-2/restic-test failed: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

I've tried with us-west-2 and with the entire endpoint.  When I use the endpoint (s3.us-west-2.amazonaws.com instead of us-west-2) I get a protocol error instead.

**Comment by fd0** [comment]
That seems to be a bug, thanks for reporting it!

**Comment by liljenstolpe** [comment]
On 1 Dec 2015, at 15:31, Alexander Neumann wrote:

> That seems to be a bug, thanks for reporting it!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/restic/restic/issues/363#issuecomment-161086931

Thx

	Christopher


-- 
李柯睿
Avt tace, avt loqvere meliora silentio
Check my PGP key here: http://www.asgaard.org/cdl/cdl.asc
Current vCard here: http://www.asgaard.org/cdl/cdl.vcf
keybase: https://keybase.io/liljenstolpe

**Comment by liljenstolpe** [comment]
You're welcome.

**Comment by aut0** [comment]
I had the same issue. Try s3://us-west-2.amazonaws.com/restic-test. Worked for me.

**Comment by fd0** [comment]
@liljenstolpe could you please try again with the current master branch? Since reporting the bug, we've exchanged the library used to access s3, and I've verified it to work with a bucket in the eu-central region.

**Comment by cdrx** [comment]
Regions other than the default do now work, but the docs have the wrong URL scheme. s3://region/bucket doesn't work, but s3://s3.amazonaws.com/bucket does.

I created a PR against the docs to update them.

**Comment by fd0** [comment]
@cdrx Thanks a lot for investigating, I'll close this issue then.

**Comment by edpichler** [comment]
I can't use other regions that the default. Version (0.8.3+ds-1).
