### ISSUE TITLE
Fatal: number of used blobs is larger than number of available blobs

### ISSUE THREAD

**Issue by steph2016** [restic/restic#3631]
hello,
It seems I have a problem:
$ restic prune -r $RESTIC_REPOSITORY
gives:

> repository d923f435 opened successfully, password is correct
> counting files in repo
> building new index for repo
> [12:53] 100.00%  54603 / 54603 packs
> repository contains 54603 packs (731631 blobs) with 249.787 GiB
> processed 731631 blobs: 0 duplicate blobs, 0 B duplicate
> load all snapshots
> find data that is still in use for 20 snapshots
> [0:18] 100.00%  20 / 20 snapshots
> Fatal: number of used blobs is larger than number of available blobs!
> Please report this error (along with the output of the 'prune' run) at
> https://github.com/restic/restic/issues/new

so what ?
cheers

**Comment by steph2016** [comment]
possible precision: I'm not sure but this problem may have come after a bad 'restic forget...', during which the network was suddenly cut.

**Comment by MichaelEischer** [comment]
Please fill in the details asked for in the Bug template: https://github.com/restic/restic/issues/new?assignees=&labels=&template=Bug.md

Besides that, you're using a rather old restic version, please run `restic check` using restic 0.12.1 to provide more details on the current state of the repository.

`restic forget ...` cannot cause that problem at all unless you're using the `--prune` option. And even the latter case shouldn't be a problem. Please provide the full commands which you think could have been a problem.

**Comment by steph2016** [comment]
sorry for the delay, it took me 3 days to gather the info...

-->
Output of `restic version`
--------------------------
ANSWER
$ restic version
restic 0.12.1 compiled with go1.16.6 on linux/amd64


How did you run restic exactly?
-------------------------------
ANSWER
the problem appeared after the following cmd, during which the wifi was cut before the end:
$ restic forget -r $RESTIC_REPOSITORY --keep-hourly 12 --keep-daily 8 --keep-weekly 4 --keep-monthly 12 --keep-yearly 3 --prune

 



What backend/server/service did you use to store the repository?
----------------------------------------------------------------
ANSWER
* I'm not sure I fully understand the question... I will try and give all the needed info, but please ask if anything is missing.

* the problem appears at several levels, but may be summarised by a 'check':
$ restic check -r $RESTIC_REPOSITORY --read-data-subset="1/100"
using temporary cache in /tmp/restic-check-cache-208101817
repository d923f435 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-208101817
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree 86f54bad:pshots
  tree 86f54bad: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
error for tree 89f68a0a:apshots
  tree 89f68a0a: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
error for tree 93065d78:apshots
  tree 93065d78: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
error for tree e79be157:apshots
  tree e79be157: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
error for tree 3fe9e47b:
  tree 3fe9e47b: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
error for tree 93c10d5b:apshots
  tree 93c10d5b: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
error for tree 5e7fb310:napshots
  tree 5e7fb310: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
error for tree d09b54bb:napshots
  tree d09b54bb: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
error for tree 6206fce0:napshots
  tree 6206fce0: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
[0:57] 100.00%  18 / 18 snapshots
error for tree 31492cd6:
  tree 31492cd6: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index
read group #1 of 653 data packs (out of total 51768 packs in 100 groups)
[0:57] 16.23%  106 / 653 packs
[0:58] 16.69%  109 / 653 packs
[5:03] 100.00%  653 / 653 packs
Fatal: repository contains errors

* the environment variable RESTIC_REPOSITORY is
$ echo $RESTIC_REPOSITORY
rest:https://<login, pw, address & port>


Expected behavior
-----------------
ANSWER
check without error nor error message

..................................................

Do you have any idea what may have caused this?
-----------------------------------------------
ANSWER
I was using restic for months without any problems, until this time where the wifi was cut during the cmd 'retic forget ... --prune'. That's why I suspect this could be due to this wifi cut


Do you have an idea how to solve the issue?
-------------------------------------------
ANSWER
actually I already had a similar problem a time ago and I think it can be solved by re-init the repository but then all the backups are lost... I was looking for something more "friendly". 


Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
ANSWER
wonderful tool...
 happy new year

**Comment by JsBergbau** [comment]
> tree 3fe9e47b: file "index" blob b6417b6b8781ea4144ef23f83ded09b5c2f98faf71bf68ff14f77560c245119d not found in index

I would try `restic rebuild-index` or if that doesn't help wird --read-all-packs, so `restic rebuild-index --read-all-packs`. If you have a copy of the repository I'd try that, otherwise I'd wait for @MichaelEischer to answer.

**Comment by MichaelEischer** [comment]
> I would try `restic rebuild-index` or if that doesn't help wird --read-all-packs, so `restic rebuild-index --read-all-packs`.

I'm somewhat sure that won't help here, as restic does not complain about files that are not contained in the index. And check did not complain about a mismatch between the pack files and the index. On the other hand, that makes no sense at all, when `prune` was interrupted halfways. Which commands did you run after the failed `forget --prune`?

As the prune implementation has been completely rewritten since restic 0.9.6, and that or an older version was used for the interrupted `forget --prune`  command, there's not much use in investigating what went wrong in detail as it's quite likely already been fixed. If you still have to output of the interrupted `forget --prune` run, then it would nevertheless still be interesting to see it.

Otherwise, let's just jump to repairing the repository. Please follow the steps described in https://github.com/restic/restic/issues/828#issuecomment-706186047 as "Route 2".

**Comment by steph2016** [comment]
sorry, I completely lost the logs. I followed route 2 of the link, 'restic finding' all the bad trees and 'restic forgetting'  the corresponding snapshots. Seems it works... but it remains only 4 snapshots... better than 0...
thank you for all

**Comment by MichaelEischer** [comment]
Closing as the problem has been resolved.
