### ISSUE TITLE
unknown flag: --dry-run

### ISSUE THREAD

**Issue by jgogstad** [restic/restic#3635]
Output of `restic version`
--------------------------

```
❯ restic version
restic 0.12.1 compiled with go1.17.2 on darwin/amd64
```

How did you run restic exactly?
-------------------------------

```
❯ mkdir foo
❯ restic -r $(pwd)/foo init
enter password for new repository:
enter password again:
created restic repository bc9f283d57 at /Users/jgogstad/tmp/restic/foo

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
❯ restic -r $(pwd)/foo backup ~/tmp --dry-run -vv
unknown flag: --dry-run
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

local

Expected behavior
-----------------

Command copied from https://restic.readthedocs.io/en/latest/040_backup.html#dry-runs, is this a flag that is not released yet, or is it a regression?

`--dry-run` is not mentioned in the man pages, so might just be a documentation issue.

**Comment by rawtaz** [comment]
> is this a flag that is not released yet

This is correct. If you look at the `stable` version in the documentation site (instead of `latest`) you won't find it.

You can download the latest master build from beta.restic.net to be able to use the flag :)
