### ISSUE TITLE
restic hangs forever on any operation involving b2

### ISSUE THREAD

**Issue by nohn** [restic/restic#3640]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/amd64

How did you run restic exactly?
-------------------------------

export B2_ACCOUNT_ID="xxx"
export B2_ACCOUNT_KEY="yyy"
export RESTIC_REPOSITORY="b2:xxxx
export RESTIC_PASSWORD=yyyy
export XDG_CACHE_HOME=/aaa/bbb/ccc

restic -v -r b2:xxx backup /xxx/yyy/zzz/ --host xxxx

restic -v forget --host xxxx --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --keep-yearly 10

even a

restic --verbose=3 unlock

prints nothing.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

b2

Expected behavior
-----------------

operation is performed

Actual behavior
---------------

restic just hangs

Steps to reproduce the behavior
-------------------------------

see above

Do you have any idea what may have caused this?
-----------------------------------------------

no. worked like a charm until a few days ago

Do you have an idea how to solve the issue?
-------------------------------------------

no

[strace.log](https://github.com/restic/restic/files/7965312/strace.log)

**Comment by papanito** [comment]
Seems the same as #3636

**Comment by MichaelEischer** [comment]
Closing this issue as it seems to be resolved by the solution in #3636.
