### ISSUE TITLE
Usage ls vs restore

### ISSUE THREAD

**Issue by adrium** [restic/restic#3651]
## Output of `restic version`

    restic 0.12.1 compiled with go1.16.6 on linux/amd64

## What should restic do differently? Which functionality do you think we should add?

The command line usage of `ls` and `restore` could be aligned.
Adding `[dir...]` to `restore` (instead of, or in addition to `-i`) would simplify restore operations:

    restic restore [flags] snapshotID [dir...]

## What are you trying to do? What problem would this solve?

Some exploration of the snapshots with `ls` may be required before restoring partial data.
Command line arguments have to be amended and rearranged for the restore operation.

Example:

    restic-repo ls latest /data/cloud/sync/workstation/Documents/letter.odt
    restic-repo restore -t / -i /data/cloud/sync/workstation/Documents/letter.odt latest

Could be easier with:

    restic-repo ls latest /data/cloud/sync/workstation/Documents/letter.odt
    restic-repo restore -t / latest /data/cloud/sync/workstation/Documents/letter.odt

Just replace `ls` with `restore -t /path/to/destination`

## Did restic help you today? Did it make you happy in any way?

Just restored a document that I would have lost. I opened it to use it as a template and pressed Ctrl+S instead of "Save as".

Restic keeps my personal data safe every day, every hour, all the time! :raised_hands:

:heart:

**Comment by adrium** [comment]
Potentially solved by #3871

**Comment by MichaelEischer** [comment]
Let's close this for now, the <snapshot>:<path> syntax should be good enough and also has the benefit of being consistently available across commands.
