### ISSUE TITLE
Restic won't find/restore files using --include containing square brackets in name (Windows)

### ISSUE THREAD

**Issue by JsBergbau** [restic/restic#3658]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on windows/amd64

How did you run restic exactly?
-------------------------------
`restic restore -t C:\temp --include "/G/Restictest/Folder 2 [square brackets]"`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local file system

Expected behavior
-----------------
restic restores the folder `Folder 2 [square brackets]`

Actual behavior
---------------
nothing is restored

Steps to reproduce the behavior
-------------------------------
Add the files of the attachment into a repo and try to restore with the steps above.

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
It works with `restic restore -t C:\temp --include "/G/Restictest/Folder 2 *" latest`

However it took me some minutes to figure it out that the problem is obviously caused by square brackets in file name.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic makes me feel happy and save every day because for me it is the best backup program on the market right now. I trust my data is safely backuped with restic. It makes me happy to improve restic.

[Restictest.zip](https://github.com/restic/restic/files/8148761/Restictest.zip)

**Comment by MichaelEischer** [comment]
The path matching is done as described in https://pkg.go.dev/path/filepath#Match. Unfortunately, in windows there's no way to escape square brackets.

**Comment by JsBergbau** [comment]
`[[]`
Works as expected, meaning it will all find/restore all files with on opening square bracket. However for closing squarebracket `[]]` it won't work since it is not recognized as character class.

**Comment by MichaelEischer** [comment]
Shouldn't `[[]]` work? `[[]` results in an opening square bracket. And `]` on its own does not require escaping.

**Comment by JsBergbau** [comment]
`[[]]` finds only `[]`. So only files that have an opening square bracket followed by a closing one.

**Comment by MichaelEischer** [comment]
Yes, so in summary this means that you only have to escape an opening square bracket in a filename as `[[]` and that's it. Closing square brackets don't have to be changed if the opening square brackets are properly escaped.

**Comment by MichaelEischer** [comment]
Closing in favor of https://github.com/restic/restic/issues/4867 .

**Comment by pryon** [comment]
I spent quite some time experimenting and fiddling around to finally narrow it down to the square bracket characters being the issue in a long filename. Could we get a warning on Windows when using plain square brackets for `--include` so that users are made aware of this issue until a fix is available?

**Comment by MichaelEischer** [comment]
> Could we get a warning on Windows when using plain square brackets for `--include` so that users are made aware of this issue until a fix is available?

What do you mean exactly with "plain square brackets"? A pattern like `file[123].json` is perfectly valid and shouldn't cause a warning. An alternative could be adding a small note to the docs if it's not discussed there so far.
