### ISSUE TITLE
Remove trailing period from `find` output

### ISSUE THREAD

**Issue by jimt** [restic/restic#3659]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/arm64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I suggest removing the trailing period from the output of the `find` command.

https://github.com/restic/restic/blob/master/cmd/restic/cmd_find.go#L270
https://github.com/restic/restic/blob/master/cmd/restic/cmd_find.go#L354

What are you trying to do? What problem would this solve?
---------------------------------------------------------

This simplifies cutting-and-pasting the snapshot-id as I try to work through [removing corrupt snapshots from a repository](https://github.com/restic/restic/issues/1617#issuecomment-703697115).

(And seems stylisticly consistent with other restic output whch doesn't have a period.)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, it has helped backup a variety of machines on my home LAN over the past couple of years.  Just frustrated today because of a corrupt repository.

**Comment by MichaelEischer** [comment]
The suggestion sounds reasonable, can you open a PR to remove the period?

I'm curious how the repository got corrupted. Do you have an idea how that happened? Which backend are you using?
The current canonical instructions to repair a repository are at https://github.com/restic/restic/issues/828#issuecomment-706186047 .

**Comment by jimt** [comment]
> I'm curious how the repository got corrupted. Do you have an idea how that happened? Which backend are you using?

No useful information unfortunately.

It was using the S3 backend (@ Wasabi). A pair of ARM machines have backed up into this repo nightly for a couple of years.  I moved the repo to S3 @ Wasabi back in July.  Something went horribly wrong in the monthly `forget --prune` this time resulting in countless messages about `nonce is invalid` when I tried to operate on the repo. Attempting to remove the damaged pack files/rebuild the index ended up removing all snapshots of one machine and many of the other.

**Comment by MichaelEischer** [comment]
> Something went horribly wrong in the monthly `forget --prune` this time resulting in countless messages about `nonce is invalid` when I tried to operate on the repo

That sounds like the pack files were not stored completly. `nonce is invalid` is only returned if it only consists of zero bytes. Or maybe the local cache ended up with lots of incomplete data? Deleting the cache might have been worth a try.

Do you run `check`  from time to time?

**Comment by jimt** [comment]
> Do you run check from time to time?

Occasionally, but not on a regular basis.  I had restored a directory tree from the repo as recently as last month.
