### ISSUE TITLE
Publish Docker images for ARM architecture

### ISSUE THREAD

**Issue by ngosang** [restic/restic#3660]
It's easy with Docker buildx. I'm doing it in some of my projects with GitHub actions => https://github.com/ngosang/docker-amule/blob/master/.github/workflows/release-docker.yml#L49

Requested archs:
* linux/arm/v7  => arm32
* linux/arm64/v8  => arm64

**Comment by dlehammer** [comment]
Duplicate of #2359 (pt. still open)
