### ISSUE TITLE
Add an option to display the size of a snapshot

### ISSUE THREAD

**Issue by TLINDEN** [restic/restic#3662]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.17.5 on freebsd/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
`restic snapshots` shall display the size of a snapshot (i.e. disk usage), or when a special option like `--display-size` has been supplied.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I am using an external SFTP server as storage backend, which has a limited volume size. I am able to grow it but this adds cost. Currently I only see how much disk space ALL snapshots of ALL hosts are using. However, it may happen that the backup suddenly eats much more backend space than before. In such a case I want to be able to find out which snapshot it was so I can inspect the machine where it came from - AND/OR tune the backend storage size accordingly (before I get errors from restic because the disk is full).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic helps me a lot, every day! A couple of weeks ago my primary server had a boot slice error and I needed to re-install it. During the process I realized that my backups were incomplete and so I lost data from a half year. Now all my systems use restic and I am more than happy! I already accidently deleted a webserver docroot and could restore it using restic in a couple of minutes. A dream :) !

**Comment by MichaelEischer** [comment]
I'm not entirely sure what you're asking for. It sounds like the simplest solution would be to check the summary returned by `backup --verbose` for sudden increases in uploaded data size.

Another option would be to compare the non-deduplicated data size, which would be #693.

Or the question is how much data deleting a snapshot would free, and that is not easy to calculate due to deduplication. But with recent restic versions `forget --prune --dry-run <snapshot>` would do just that.

The `diff` command also prints how much data only belongs to one or both of the compared snapshots.

**Comment by TLINDEN** [comment]
Hello Michael.

I tried the `forget --prune --dry-run` command, it does the job. I also added the `--verbose` option to `backup`. So, from my point of view I am happy.

Thanks a lot!!!

**Comment by MichaelEischer** [comment]
I guess we should document this somewhere, I had the same question some time ago and didn't immediately think of using `forget --dry-run --prune`. Anyone up for a PR?

**Comment by tribor** [comment]
nevertheless, it would be helpful to have a option to `restic snapshots` (like the mentioned `--display-size`) to see metrics like  
- size of data locally 
- size of repo data
- size of data added to repo 
 
**for each snapshot**. By presenting these metrics you can easily estimate how the repo growth looks like or where deviations/irregularities have occurred.

**Comment by MichaelEischer** [comment]
@tribor The discussion for that feature belongs into #693.

**Comment by huyz** [comment]
I guess this should be closed now that #693 has been closed?

**Comment by MichaelEischer** [comment]
I think so. The snapshot now contains the size of the backed up files as well as the byte uploaded for that specific snapshot.
