### ISSUE TITLE
Restic panic("store new item in finalized index")s during backup. 

### ISSUE THREAD

**Issue by Crest** [restic/restic#367]
Restic crashes with a panic() during backups after a few gigabyte.
- OS: FreeBSD
- FS: ZFS
- Version: restic 0.1.0 (v0.1.0-168-g55d9c5f) compiled at 2015-12-07 00:21:27 with go1.5.1

[restic.txt](https://github.com/restic/restic/files/53925/restic.txt)

**Comment by fd0** [comment]
Oh wow, thanks for the report, that clearly shouldn't happen.

**Comment by paulvt** [comment]
Same here (same trace also) on Debian GNU/Linux Sid to an SFTP repository.
Version: restic 0.1.0 (v0.1.0-465-g9e81b15) compiled at 2016-03-26 11:26:22 with go1.6.

**Comment by mholt** [comment]
Dang, this happened again for me. :( Which means I'll probably have to stick with `cp` or duplicity for now.

**Comment by rawtaz** [comment]
Have faith! Once this is fixed, you'll have the greatest stand-alone backup software ever!

**Comment by fd0** [comment]
I've spent some time today thinking about what may cause this panic, and I've found a nasty bug.

@mholt you seem to be the only person able to reproduce the issue multiple times, could you please test my fix in #717 and report back?

**Comment by mholt** [comment]
Yes! Happy to test it out. I'll do a full backup again with the change you've proposed in 717 and I'll let you know how it goes.

**Comment by fd0** [comment]
Reopening, waiting for feedback from @mholt.

**Comment by mholt** [comment]
Well, ~200 GB into the backup with the fix applied and no panics. Seeing that during the first backup, restic had already panicked a few times by now, I suspect there's a good chance your fix did the trick. I'm content closing this now, (thank you!) but I'll let you know if it happens again. :+1:

**Comment by fd0** [comment]
awesome, then I'm going to close this issue for now. Please let us know if it happens again!
