### ISSUE TITLE
Problem running prune: Integrity check failed: Data seems to be missing.

### ISSUE THREAD

**Issue by maw** [restic/restic#3676]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/amd64

How did you run restic exactly?
-------------------------------
I ran this command: `Rrestic prune --dry-run`

`Rrestic` is a script I use to take care of creating and loading a password file -- otherwise it should act identically to `restic` itself.  It looks like this:

```
#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/_restic

RD=sftp:myaccount@somehost.rsync.net:backups

export RESTIC_PASSWORD_FILE=/tmp/rpf

if [[ ! -f "$RESTIC_PASSWORD_FILE" ]] ; then
   echo restic password file does not exist
   echo we will create it now
   echo
   echo enter restic password
   read -s restic_password
   rm -f "$RESTIC_PASSWORD_FILE"
   touch "$RESTIC_PASSWORD_FILE"
   chmod 600 "$RESTIC_PASSWORD_FILE"
   echo $restic_password >> $RESTIC_PASSWORD_FILE
   unset restic_password
fi

# restic --password-file "$RESTIC_PASSWORD_FILE" -r "$RD" --verbose "$@"
restic --password-file "$RESTIC_PASSWORD_FILE" -r "$RD" "$@"
```

And the file `_restic` just looks for a `restic` binary and halts execution if it can't be found. (I've been using these scripts for almost two years. I can't remember why I put this check in a different file. :stuck_out_tongue:)  It looks like this:

```
#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR

have_restic=$(hash restic)

if [[ "$have_restic" -ne "0" ]] ; then
   echo bad
   echo You need to have restic installed and available in PATH
   exit 1
fi
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

rsync.net with scp

Expected behavior
-----------------

I'm not exactly sure since I've never run it successfully.  

Actual behavior
---------------
```
mw@kurutoga:~ % Rrestic prune --dry-run
repository 2db8a190 opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 609 snapshots
[3:03] 100.00%  609 / 609 snapshots
searching used packs...
{<data/80d0b865>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
Fatal: index is not complete
```

Steps to reproduce the behavior
-------------------------------

I can reproduce it by trying to prune.  But don't know precisely what steps one should take to get into this situation, sorry.

Do you have any idea what may have caused this?
-----------------------------------------------
I am running over mosh without using tmux on the other end so I am not entirely sure what I ran previously.

But I can say I ran `Rrestic check --with-cache` earlier, I was told about a problem with tree `9ab235bc`

So I then ran
```
mw@lapicero:~ % Rrestic find --tree 9ab235bc
repository 2db8a190 opened successfully, password is correct
Unable to load tree d019e5b618bec7eb0041bf6fcd0122b660970fe26e7d343bfab85f04a2065422
 ... which belongs to snapshot 7c9d1c397cad1fff0782b28e8dee60fca0724ba782f1506d025ee824c91a02fc.
Found tree 9ab235bc0dec33fb8d981fe12bca654e6bcf3bb650ea3bb21d4dd6cd7c689813
 ... path /Users/mw/ownCloud2
 ... in snapshot 7c9d1c39 (2021-02-17 11:01:34)
  signal interrupt received, cleaning up
```

There is nothing in that snapshot that I don't mind losing (I'm reasonably sure that between previous and subsequent backups I'm well enough covered), so I then said

```
mw@kurutoga:~ % Rrestic forget 7c9d1c39
repository 2db8a190 opened successfully, password is correct
[0:00] 100.00%  1 / 1 files deleted
```

I ran with `Rrestic check --with-cache` again:

```
pack 7edba6b3: not referenced in any index
pack bccccb09: not referenced in any index
[...many other packs not referenced in any index, but if I understand correctly this isn't a cause for concern.  If you need them, I can run it again and take more care to preserve its output.]
668 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
check snapshots, trees and blobs
error for tree 9ab235bc:napshots
  tree 9ab235bc: file "._sync_2b8147ae6d3d.db-shm" blob 80d0b86573545d9fea989a3aaaa4c5a29a41524deedfa582d2
[3:01] 100.00%  609 / 609 snapshots
Fatal: repository contains errors
```

This file is in a directory managed by ownCloud:

```
mw@lapicero:~/ownCloud % file ./.sync_2b8147ae6d3d.db                                           130 ↵
./.sync_2b8147ae6d3d.db: SQLite 3.x database, last written using SQLite version 3029000
```

My hunch is that I halted a backup at just the wrong time or that that file was modified at just the wrong instant.  But I don't know this.

Do you have an idea how to solve the issue?
-------------------------------------------

None, sorry.  I thought deleting the old snapshot would do it.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Not today, but I do use it to run backups every working day and all in all I'm pretty happy with it.

**Comment by MichaelEischer** [comment]
The missing data blob probably belongs to a different snapshot. So you probably have to remove that one too to allow prune to work.

> My hunch is that I halted a backup at just the wrong time or that that file was modified at just the wrong instant.  But I don't know this.

Neither should cause this type of damage. Do you run `prune` or `check` regularly? Did check report the data blob as missing before? Just loosing a single blob is rather strange.

**Comment by maw** [comment]
[I'm sorry for taking so long to respond. It's been a busy month.]

Until recently, I haven't run `prune` or `check` recently. I decided I should start and in so doing I bumped into these problems.

I ran

```
% Rrestic find --tree 9ab235bc
repository 2db8a190 opened successfully, password is correct
Found tree 9ab235bc0dec33fb8d981fe12bca654e6bcf3bb650ea3bb21d4dd6cd7c689813
 ... path /Users/mw/ownCloud2
 ... in snapshot 7c71c166 (2021-02-17 11:20:28)
```

So if I understand things correctly, that tree existed in at least two snapshots: `7c9d1c39` from earlier, `7c71c166` from just now.

I forgot it and I'm running `prune -n` now.  It takes a while to run, but I'm afraid that I'll bump into the same problem with the same file more times.  Is there a way that I'm missing for `find` to return multiple snapshots if relevant?

**Comment by maw** [comment]
I finished a dry run:

```
% Rrestic prune -n            
repository 2db8a190 opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 648 snapshots
[2:56] 100.00%  648 / 648 snapshots
searching used packs...
collecting packs for deletion and repacking
[2:47] 100.00%  71433 / 71433 packs processed

to repack:         2482 blobs / 686.371 MiB
this removes        669 blobs / 244.896 MiB
to delete:          206 blobs / 3.385 GiB
total prune:        875 blobs / 3.624 GiB
remaining:      1381616 blobs / 334.915 GiB
unused size after prune: 4.557 MiB (0.00% of remaining size)
```

So I think I can run `prune` now -- although I'll run `check` first.

However, I think my question stands: shouldn't there be a way to find all trouble snapshots in one go?

**Comment by MichaelEischer** [comment]
> However, I think my question stands: shouldn't there be a way to find all trouble snapshots in one go?

There's currently no easy way to get rid of all damaged snapshots or to repair them. We've been focusing on various improvements in restic to make it less likely that a snapshot is ever damaged. 

After reading the `check` error again, it actually only complained about the missing data blob, so running find for that blob would probably have turned up both affected snapshots. Find will return multiple snapshots if a data or tree blob is used in multiple snapshots.

**Comment by maw** [comment]
I deleted both snapshots and was then able to run `check` and `prune` successfully.

> After reading the `check` error again, it actually only complained about the missing data blob, so running find for that blob would probably have turned up both affected snapshots. Find will return multiple snapshots if a data or tree blob is used in multiple snapshots.

Having deleted them I can't check this anymore :( but my recollection is that it only showed one problem snapshot at a time.

**Comment by MichaelEischer** [comment]
Closing as there's nothing we can still investigate and the repository has been fixed.
