### ISSUE TITLE
restic-backup documentation error in parameters

### ISSUE THREAD

**Issue by egauthier** [restic/restic#3679]
Output of `restic version`
--------------------------
`restic 0.9.6 compiled with go1.12.12 on linux/amd64`

How did you run restic exactly?
-------------------------------
Installed on Ubuntu 20.04 LTS (native not dockerized) with rclone as backend.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone attached to OneDrive Personal and Dropbox.

Expected behavior
-----------------

Actual behavior
---------------
The current documentation and man page for restic-backup show that at least 1 **FILE/DIR** parameter is required.

`restic backup [flags] FILE/DIR [FILE/DIR] ...`

It appears is not required if you are using _--files-from_ option. The following (without any **FILE/DIR** parameters) will work fine.

`restic backup --files-from=foobar.txt`

Coming from the _rsync_ world, this caused me a long time of trying to figure out what was happening (especially without a _--dry-run_ option for restic-backup).  I assumed that the **FILE/DIR** was a starting point from which any relative paths in include/exclude patterns would be resolved.

I spent hours fiddling with exclude and include files and patterns, without even thinking of removing the FILE/DIR option I was passing since it appears from the documentation that at least 1 FILE/DIR is required.

Steps to reproduce the behavior
-------------------------------

`man restic-backup`

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------
The documentation really needs clarification around include / exclude files, patterns, globbing and priorities (e.g. there seem to be no priorities or overlays....just everything is processed sequentially.....I think :) .

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
**Absolutely**.  I'm just starting with it, and although there is a learning curve, it appears to be an great, efficient solution for batch, dockerized/VM/VPS backups.

**THANK YOU**

**Comment by MichaelEischer** [comment]
> The documentation really needs clarification around include / exclude files, patterns, globbing and priorities (e.g. there seem to be no priorities or overlays....just everything is processed sequentially.....I think :) .

Restic just first collects all specified backup paths, and then starts to backup those. While performing the backup it checks every path against the excludes. AFAICT the patterns/globbing/regexp are already documented, but I haven't checked in detail whether everything is actually there. Are you missing any information in particular?

> Coming from the _rsync_ world, this caused me a long time of trying to figure out what was happening (especially without a _--dry-run_ option for restic-backup).

restic 0.13.0 has added support for dry runs. Just run `restic backup --dry-run --verbose 3` to see what would be part of the backup.
