### ISSUE TITLE
error talking HTTP to rclone

### ISSUE THREAD

**Issue by FakeDecent** [restic/restic#3681]
Output of `restic version`
--------------------------
restic 0.13.0 compiled with go1.18 on windows/amd64

How did you run restic exactly?
-------------------------------
restic -r rclone:onedrive:snapshot backup   --files-from includes.txt  --exclude-file excludes.txt 

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
onedrive

Expected behavior
-----------------
Normal operation backup function

Actual behavior
---------------
Fatal: unable to open repo at rclone:onedrive:snapshot: error talking HTTP to rclone: Get "http://localhost/file-5577006791947779410": unexpected EOF

Steps to reproduce the behavior
-------------------------------
restic self-update
（Version before update is restic 0.12.1 compiled with go1.16.6 on windows/amd64）

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by rawtaz** [comment]
To clarify; Are you saying that with restic 0.12.1 the problem does not manifest itself, and with 0.13.0 it does (when using the exact same setup and command, only changing the restic version)?

**Comment by FakeDecent** [comment]
yes,only changing the restic version

**Comment by ProactiveServices** [comment]
Works here on Windows 10. Are you using a third-party firewall that might be blocking restic as the binary is now different?

restic 0.13.0 compiled with go1.18 on windows/amd64
rclone v1.58.0
- os/version: Microsoft Windows 10 Pro 21H2 (64 bit)
- os/kernel: 10.0.19044.1586 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.8
- go/linking: dynamic
- go/tags: cmount

rclone config:
[onedrive]
type = onedrive
token = <snip>
drive_id = <snip>
drive_type = personal

**Comment by FakeDecent** [comment]
> Works here on Windows 10. Are you using a third-party firewall that might be blocking restic as the binary is now different?
> 
> restic 0.13.0 compiled with go1.18 on windows/amd64 rclone v1.58.0
> 
> * os/version: Microsoft Windows 10 Pro 21H2 (64 bit)
> * os/kernel: 10.0.19044.1586 (x86_64)
> * os/type: windows
> * os/arch: amd64
> * go/version: go1.17.8
> * go/linking: dynamic
> * go/tags: cmount
> 
> rclone config: [onedrive] type = onedrive token = drive_id = drive_type = personal

third-party firewall is not used,Computers only use Windows Defender()

**Comment by Zottelchen** [comment]
I can confirm this problem for my system too. 
Windows 10, but rclone-webdav instead of Onedrive.

**Comment by fd0** [comment]
That's odd, we haven't changed anything in the restic backend config. I know there were some changes in the way the Go runtime passes file descriptors on Windows (but I'm unable to find a reference), so the first step here would be to build restic 0.13.0 with Go 1.16 and try that. If it works, something has changed in Go and we can start digging into that.

**Comment by rawtaz** [comment]
This might be the one you're thinking of: https://github.com/restic/restic/issues/3601

**Comment by FakeDecent** [comment]
> That's odd, we haven't changed anything in the restic backend config. I know there were some changes in the way the Go runtime passes file descriptors on Windows (but I'm unable to find a reference), so the first step here would be to build restic 0.13.0 with Go 1.16 and restic 0.12.2 with Go 1.18 and try each. If it works with Go 1.16, something has changed in Go and we can start digging into that.

restic version
restic 0.13.0 (v0.13.0-15-g4d5db61b) compiled with go1.16.6 on windows/amd64

execute:
restic -r rclone:onedrive:snapshot backup  --files-from includes.txt  --exclude-file excludes.txt

Return results:
Fatal: unable to open repo at rclone:onedrive:snapshot: error talking HTTP to rclone: Get "http://localhost/file-5577006791947779410": unexpected EOF


restic version
restic 0.12.1 (v0.12.1-3-g533ac4fd) compiled with go1.18 on windows/amd64

execute:
restic -r rclone:onedrive:snapshot backup  --files-from includes.txt  --exclude-file excludes.txt

Return results:
repository 4c45359d opened successfully, password is correct
using parent snapshot ca5be316

Files:          21 new,   292 changed, 89820 unmodified
Dirs:            2 new,  1511 changed, 22081 unmodified
Added to the repo: 148.978 MiB

processed 90133 files, 36.979 GiB in 1:59
snapshot 0c3d0557 saved

**Comment by fd0** [comment]
Great, thanks! So it's not the Go version but something within restic changed. Would you be willing to to do a `git bisect` from `v0.12.1` to `v0.13.0`? That'd be really helpful because I can't reproduce it here...

**Comment by fd0** [comment]
Thanks a lot! So it was introduced by PR #3602 ... @greatroar @cqjjjzr can one of you maybe help here?

**Comment by cqjjjzr** [comment]
I'll try to give it a look..

**Comment by Zottelchen** [comment]
@cqjjjzr I am using both latest versions via scoop. I am not certain if/how that plays into it.

**Comment by FakeDecent** [comment]
The previous rclone and restic were installed using scoop,

Operation result error

I uninstall them (scoop uninstall rclone, scoop uninstall restic)

Use the following steps to test the same command rest -r rclone: onedrive: snapshottest snapshots

1. Rclone and restic downloaded from GitHub,

The operation results are normal

2. Rclone downloaded from GitHub,

Scoop installs restic,

The operation results are normal

3. Scoop installs rclone,

GitHub download restic,

Operation result error


come to conclusion:

Rclone installed using scoop caused an error

**Comment by FakeDecent** [comment]
> @cqjjjzr我通过独家新闻使用两个最新版本。我不确定这是否/如何发挥作用。

This is the scoop address:
https://github.com/ScoopInstaller/Scoop
Scoop is a tool for installing applications

**Comment by cqjjjzr** [comment]
I'll setup a VM environment to test this out. I haven't dug into how scoop install programs yet..

**Comment by FakeDecent** [comment]
I did the following tests:

1. Use scoop install rclone

2. The restic source code is updated to the latest

3. Delete foreground_ windows. Go file two lines (#3601) submitted code

cmd. SysProcAttr = &syscall. SysProcAttr{}

cmd. SysProcAttr. CreationFlags = windows. DETACHED_ PROCESS

4，go run build. go

5,restic version

restic 0.13.0 (v0.13.0-17-ga08b95c4-dirty) compiled with go1. 18 on windows/amd64

6，restic -r rclone： onedrive： snapshottest snapshots

The operation results are normal


So what do you think

**Comment by cqjjjzr** [comment]
I found that scoop will create a stub executable for all applications installed from it, called "shim". Since restic relies on pipes to communicate with rclone, I doubt the shimming has blocked that connection. However, currently I didn't why creating the process without `DETACHED_PROCESS` solves the problem..

**Comment by cqjjjzr** [comment]
Analysis:

Scoop is "shimming" apps installed via https://github.com/ScoopInstaller/Shim/blob/master/src/shim.cs . However, for unknown reason, the stdin/stdout handles which should be inherited from shim process (set by restic by redirecting) aren't passed to rclone process properly if shim process is started with `DETACHED_PROCESS`. Even when I modified shim.cs to manually pass handles, the issue persists. I observed that a blank console window flashed which may indicate a new console was allocated.

Anyway, this should be a scoop shim issue, not restic issue.

Temp workaround: use non-scoop rclone installation or use `-o rclone.program="/path/to/scoop/apps/rclone/current/rclone.exe"`

**Comment by FakeDecent** [comment]
yes,this should be a scoop issue,temp workaround is feasible

**Comment by fd0** [comment]
Can somebody create an issue for Scoop? we can keep this issue open until it is resolved, but I agree it's not a restic issue. Thanks a lot @cqjjjzr for debugging this!

**Comment by cqjjjzr** [comment]
I noticed that multiple implementations for scoop exist other than the C# one: https://github.com/71/scoop-better-shimexe and https://github.com/kiennq/scoop-better-shimexe So maybe we need to open issue in those repos..

**Comment by cqjjjzr** [comment]
I tried all 3 implementations of shim (kiennq by default, 71 and scoopcs version). None of them worked.

**Comment by FakeDecent** [comment]
@cqjjzr

1,After adding restic DETACHED_PROCESS,(scoop install rclone,scoop install restic)
I observed that a blank console window flashed，
2,I searched and found the website(https://docs.python.org/3/library/subprocess.html#subprocess.DETACHED_PROCESS)
It says:
New in version 3.7.

subprocess.CREATE_NO_WINDOW
A Popen creationflags parameter to specify that a new process will not create a window.

New in version 3.7.

subprocess.DETACHED_PROCESS
A Popen creationflags parameter to specify that a new process will not inherit its parent’s console. This value cannot be used with CREATE_NEW_CONSOLE.
3，In foreground_windows.go file
	cmd.SysProcAttr.CreationFlags = windows.DETACHED_PROCESS
Add the following line
	cmd.SysProcAttr.CreationFlags = windows.CREATE_NO_WINDOW
4，go run build.go
5，restic version
restic 0.13.0 (v0.13.0-32-gdb8a9589-dirty) compiled with go1.18 on windows/amd64
6，Complete test steps：

C:\Users\20267>restic -r rclone:onedrive:snapshottest init
enter password for new repository:
enter password again:
created restic repository 20c54f6ebc at rclone:onedrive:snapshottest

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

C:\Users\20267>restic -r rclone:onedrive:snapshottest backup C:\Users\20267\Desktop\test
enter password for repository:
repository 20c54f6e opened successfully, password is correct
created new cache in C:\Users\20267\AppData\Local\restic
no parent snapshot found, will read all files

Files:           1 new,     0 changed,     0 unmodified
Dirs:            5 new,     0 changed,     0 unmodified
Added to the repo: 1.684 KiB

processed 1 files, 0 B in 0:15
snapshot fed6622c saved

C:\Users\20267>restic -r rclone:onedrive:snapshottest backup C:\Users\20267\Desktop\test
enter password for repository:
repository 20c54f6e opened successfully, password is correct
using parent snapshot fed6622c

Files:           2 new,     0 changed,     1 unmodified
Dirs:            0 new,     5 changed,     0 unmodified
Added to the repo: 18.966 MiB

processed 3 files, 18.962 MiB in 0:29
snapshot 59a50234 saved

C:\Users\20267>restic -r rclone:onedrive:snapshottest  snapshots
enter password for repository:
repository 20c54f6e opened successfully, password is correct
ID        Time                 Host          Tags        Paths
------------------------------------------------------------------------------------
fed6622c  2022-03-30 10:17:57  Inspiron5557              C:\Users\20267\Desktop\test
59a50234  2022-03-30 10:19:53  Inspiron5557              C:\Users\20267\Desktop\test
------------------------------------------------------------------------------------
2 snapshots

C:\Users\20267>restic -r rclone:onedrive:snapshottest  diff fed6622c 59a50234
enter password for repository:
repository 20c54f6e opened successfully, password is correct
comparing snapshot fed6622c to 59a50234:

+    /C/Users/20267/Desktop/test/restic.exe
+    /C/Users/20267/Desktop/test/新建 RTF 文件.rtf

Files:           2 new,     0 removed,     0 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:     18 new,     0 removed
Tree Blobs:      6 new,     6 removed
  Added:   18.966 MiB
  Removed: 1.684 KiB

C:\Users\20267>restic -r rclone:onedrive:snapshottest  forget 59a50234
enter password for repository:
repository 20c54f6e opened successfully, password is correct
[0:00] 100.00%  1 / 1 files deleted...



The operation result is normal


I am not familiar with go language. Please verify whether there are other adverse effects

**Comment by cqjjjzr** [comment]
Well, by adding `cmd.SysProcAttr.CreationFlags = CREATE_NO_WINDOW` you're factually overwriting `DETACHED_WINDOW` flag, so you should do `cmd.SysProcAttr.CreationFlags = windows.CREATE_NO_WINDOW | windows.DETACHED_WINDOW`

I've already introduced a possible fix for shim in https://github.com/kiennq/scoop-better-shimexe/pull/3

Also, you really should properly format your markdown bro 😕

**Comment by FakeDecent** [comment]
Thank you. Here are just my personal thoughts:

The premise is that after adding ```cmd.SysProcAttr.CreationFlags = windows.CREATE_NO_WINDOW | windows.DETACHED_WINDOW```, if all functions can be used normally (rclone and restic are installed from scoop, or downloaded from GitHub, or others)
We'll use it in the next restic version, without paying attention to scoop.

1\. The restics code is under our control.

2\. The original intention of using scoop is to facilitate software installation,If need to modify some configurations in order to use restic and rclone, it is a little unreasonable (if need to modify the scope configuration).
new users also use scoop to install restic and rclone,If don't know or forget to modify the scope configuration, it will cause trouble

3\.Scoop branch Kiennq and 71 seem to know too few people and rarely update.

**Comment by cqjjjzr** [comment]
A quick test indicated that `cmd.SysProcAttr.CreationFlags = windows.CREATE_NO_WINDOW | windows.DETACHED_WINDOW` with the original kiennq shim does not work..

Considering the fact that kiennq version is the default for shimming, if the problem gets properly handled by Scoop, there shouldn't be extra configuration work.

**Comment by fd0** [comment]
We've received a report that the sftp backend is also affected, without Scoop, see #3692

**Comment by greatroar** [comment]
@fd0 I'm listed as coauthor on that commit because I suggested some cosmetic changes. I don't actually understand the Windows APIs used here.

**Comment by fd0** [comment]
@greatroar good enough, thanks!

**Comment by fd0** [comment]
Thanks a lot! @FakeDecent can you please test the latest master of restic? You can find a pre-compiled binary with the fix here: https://beta.restic.net/restic-v0.13.0-43-g192288bc/

**Comment by FakeDecent** [comment]
Thanks a lot.I did some tests and now it can be used normally.
