### ISSUE TITLE
restic 0.13.0 tests fail on 32-bit architectures

### ISSUE THREAD

**Issue by nmeum** [restic/restic#3687]
While upgrading the Alpine Linux restic package from 0.12.0 to 0.13.0 I noticed a failure of the following test case on 32-bit architectures (armv7 and x86):

https://github.com/restic/restic/blob/7080fed7ae0eb660e0ba9f352ccf3765ea2e9ed8/internal/fs/setflags_linux_test.go#L57-L67

This test case was added in commit 7080fed7ae0eb660e0ba9f352ccf3765ea2e9ed8 (CC: @greatroar).

The output for the failed test looks as follows:

```
go test ./cmd/... ./internal/...
go: downloading github.com/google/go-cmp v0.5.6
# github.com/restic/restic/internal/fs [github.com/restic/restic/internal/fs.test]
internal/fs/setflags_linux_test.go:62:24: unix.BTRFS_SUPER_MAGIC (untyped int constant 2435016766) overflows int32
ok  	github.com/restic/restic/cmd/restic	18.070s
ok  	github.com/restic/restic/internal/archiver	7.425s
ok  	github.com/restic/restic/internal/backend	3.505s
ok  	github.com/restic/restic/internal/backend/azure	0.006s
ok  	github.com/restic/restic/internal/backend/b2	0.008s
ok  	github.com/restic/restic/internal/backend/dryrun	0.005s
ok  	github.com/restic/restic/internal/backend/gs	0.008s
ok  	github.com/restic/restic/internal/backend/local	2.878s
ok  	github.com/restic/restic/internal/backend/location	0.012s
ok  	github.com/restic/restic/internal/backend/mem	2.560s
ok  	github.com/restic/restic/internal/backend/rclone	0.015s
ok  	github.com/restic/restic/internal/backend/rest	0.013s
ok  	github.com/restic/restic/internal/backend/s3	0.006s
ok  	github.com/restic/restic/internal/backend/sftp	0.007s
ok  	github.com/restic/restic/internal/backend/swift	0.007s
ok  	github.com/restic/restic/internal/backend/test	3.021s
ok  	github.com/restic/restic/internal/bloblru	0.006s
ok  	github.com/restic/restic/internal/cache	1.122s
ok  	github.com/restic/restic/internal/checker	2.603s
ok  	github.com/restic/restic/internal/crypto	0.619s
ok  	github.com/restic/restic/internal/debug	0.006s [no tests to run]
ok  	github.com/restic/restic/internal/dump	0.165s
?   	github.com/restic/restic/internal/errors	[no test files]
ok  	github.com/restic/restic/internal/filter	0.510s
FAIL	github.com/restic/restic/internal/fs [build failed]
ok  	github.com/restic/restic/internal/fuse	0.059s
ok  	github.com/restic/restic/internal/hashing	0.187s
ok  	github.com/restic/restic/internal/limiter	0.006s
?   	github.com/restic/restic/internal/migrations	[no test files]
?   	github.com/restic/restic/internal/mock	[no test files]
ok  	github.com/restic/restic/internal/options	0.025s
ok  	github.com/restic/restic/internal/pack	0.018s
ok  	github.com/restic/restic/internal/repository	6.739s
ok  	github.com/restic/restic/internal/restic	1.944s
ok  	github.com/restic/restic/internal/restorer	0.069s
?   	github.com/restic/restic/internal/selfupdate	[no test files]
?   	github.com/restic/restic/internal/test	[no test files]
ok  	github.com/restic/restic/internal/textfile	0.017s
ok  	github.com/restic/restic/internal/ui	0.014s
?   	github.com/restic/restic/internal/ui/backup	[no test files]
ok  	github.com/restic/restic/internal/ui/progress	0.143s
?   	github.com/restic/restic/internal/ui/signals	[no test files]
ok  	github.com/restic/restic/internal/ui/table	0.027s
ok  	github.com/restic/restic/internal/ui/termstatus	0.006s
ok  	github.com/restic/restic/internal/walker	0.010s
FAIL
make: *** [Makefile:12: test] Error 2
```

A change along the lines of:

```diff
diff -upr restic-0.13.0.orig/internal/fs/setflags_linux_test.go restic-0.13.0/internal/fs/setflags_linux_test.go
--- restic-0.13.0.orig/internal/fs/setflags_linux_test.go	2022-03-29 21:31:21.121497170 +0200
+++ restic-0.13.0/internal/fs/setflags_linux_test.go	2022-03-29 21:31:35.918229947 +0200
@@ -59,7 +59,7 @@ func supportsNoatime(t *testing.T, f *os
 	err := unix.Fstatfs(int(f.Fd()), &fsinfo)
 	rtest.OK(t, err)
 
-	return fsinfo.Type == unix.BTRFS_SUPER_MAGIC ||
+	return int64(fsinfo.Type) == int64(unix.BTRFS_SUPER_MAGIC) ||
 		fsinfo.Type == unix.EXT2_SUPER_MAGIC ||
 		fsinfo.Type == unix.EXT3_SUPER_MAGIC ||
 		fsinfo.Type == unix.EXT4_SUPER_MAGIC ||
```

fixes the test failure, but not sure if this is the correct way to address this issue, hence reporting it as a bug.

**Comment by MichaelEischer** [comment]
That will break detection of BTRFS on 32-bit systems. As fsinfo.Type is an int32 it will be sign-extended to an int64. However, that yields a different value than just casting the constant to a 64bit integer.

`return int64(uint(fsinfo.Type)) == int64(unix.BTRFS_SUPER_MAGIC)` might work.

**Comment by fd0** [comment]
For the record: we can run the tests on 32 bit by using `GOARCH=386 go test ./internal/fs`.

In the manpage `statfs(2)`, it is advised that the `Type` field should be of the variable type `uint` (not sure why in Go it is of type `int64` on amd64 and `int32` on 386):

> The `__fsword_t` type used for various fields in the statfs structure definition is a glibc internal  type,  not  intended  for public  use.   This  leaves the programmer in a bit of a conundrum when trying to copy or compare these fields to local variables in a program.  Using unsigned int for such variables suffices on most systems.

It think I understood what Michael is saying: If, for some reason, on a 32 bit system, `fsinfo.Type` is a value that has the highest bit set (e.g. `0x80000000`), then the value is negative. Casting it to `int64` extends the sign bit, so it becomes `0x7fffffff80000000`, which is not what we want. Instead, we need to cast it to `uint` first, and then to `int64`, so it stays at the value `0x80000000`.

Is that correct?

**Comment by greatroar** [comment]
> In the manpage statfs(2), it is advised that the Type field should be of the variable type uint (not sure why in Go it is of type int64 on amd64 and int32 on 386)

I'm guessing they autogenerate it. From browsing the Glibc header files on my machine, I get the impression that __fsword_t is actually a signed long. statfs(2) isn't very clear about this.

**Comment by greatroar** [comment]
Reported upstream.
