### ISSUE TITLE
Darwin cross compilation

### ISSUE THREAD

**Issue by dolanor** [restic/restic#369]
Hi!

Go makes it easy to cross compile just by changing a few variables.
But it doesn't work with the current makefile.
I guess it should be changed by a normal `go build`.

Are there reasons for not using go build?

**Comment by fd0** [comment]
Yes, there are very good reasons, see https://github.com/restic/restic/issues/368#issuecomment-162642530

The program `build.go` is used for end-users who compile restic for their current system, I consider cross-compilation to be a special case. You can easily setup a `GOPATH` with restic at the correct subdir and just use the normal Go tools to build it, see https://github.com/restic/restic/blob/master/CONTRIBUTING.md#development-environment

This could be described more prominently in the README. In addition, it is also possible to add cross-compilation support to `build.go`, but I don't think that's high priority right now.

**Comment by dolanor** [comment]
Thank you for the explanations. In fact it is fixed with just a :
```
go get github.com/restic/restic
cd $GOPATH/src/github.com/restic/restic/cmd/restic
GOPATH=$GOPATH:$PWD/../../Godeps/_workspace
GOOS=darwin go build cmd/restic
```

My missing was that the restic cmd is in a subdir.
