### ISSUE TITLE
sftp backend stopped working after 0.13.0 update

### ISSUE THREAD

**Issue by ohaucke** [restic/restic#3692]
Output of `restic version`
--------------------------
> restic 0.12.1 compiled with go1.16.6 on windows/amd64

> restic 0.13.0 compiled with go1.18 on windows/amd64

How did you run restic exactly?
-------------------------------
> restic --repo sftp:example.com:/backup/restic/pcname snapshots

Content of `.ssh\config`
```
Host example.com
    HostName example.com
    User username
    IdentityFile "C:\Users\username\.ssh\example.key"
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
sftp (on a FreeBSD machine)

Expected behavior
-----------------
> $ restic-v0.12.1 --repo sftp:example.com:/backup/restic/pcname snapshots
```
Enter passphrase for key 'C:\Users\username\.ssh\example.key':
enter password for repository:
...
```

Actual behavior
---------------
> $ restic-v0.13.0 --repo sftp:example.com:/backup/restic/pcname snapshots
```
subprocess ssh: username@example.com: Permission denied (publickey).
Fatal: unable to open repo at sftp:example.com:/backup/restic/pcname: unable to start the sftp session, error: EOF
```
`auth.log` entry from the server when using v0.13.0:
```
sshd[982]: Connection reset by authenticating user username 192.168.1.55 port 61832 [preauth]
```

Steps to reproduce the behavior
-------------------------------
run the commands above

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

**Comment by fd0** [comment]
Thanks for the report!

How did you install the `ssh` binary restic calls? Did you maybe use Scoop on Windows? If yes, this issue may be related to #3681.

Can you please do a `git bisect` from `v0.12.1` to `v0.13.0` so we can see when it starts failing?

**Comment by ohaucke** [comment]
I'm using the default windows ssh client and the restic binaries from the release page.

Windows 10 Pro - Version 21H1 (Build: 19043.1586)

**Comment by ohaucke** [comment]
I checked where the ssh binary resides on the disk and checked the properties.
> Product version: OpenSSH_8.1p1 for Windows

```
$ file ssh.exe
ssh.exe: PE32+ executable (console) x86-64, for MS Windows
```

**Comment by cqjjjzr** [comment]
Failed to reproduce.. Running from a PowerShell session. Are you using wsl to invoke restic?

```
./restic snapshots -r sftp:charlie@192.168.112.119:testr
enter password for repository:
repository d51b976b opened successfully, password is correct
created new cache in C:\Users\charlie\AppData\Local\restic
found 13 old cache directories in C:\Users\charlie\AppData\Local\restic, run `restic cache --cleanup` to remo
```

**Comment by ohaucke** [comment]
No but i might figured out the difference. Your private key doesn't look like to have a password.

I usually use the cmd but i also tried it in powershell:

With password on private key:
```
> restic_0.13.0_windows_amd64.exe --repo sftp:example.com:/backup/restic/pcname snapshots
subprocess ssh: username@example.com: Permission denied (publickey).
Fatal: unable to open repo at sftp:example.com:/backup/restic/pcname: unable to start the sftp session, error: EOF
```

Without password on private key:
```
> restic_0.13.0_windows_amd64.exe --repo sftp:example.com:/backup/restic/pcname snapshots
enter password for repository:
repository 09fd3dd0 opened successfully, password is correct
```

**Comment by cqjjjzr** [comment]
Well this may be expected here.. Once the process is detached from the original console, you can of course no longer input password. Maybe we need a switch or other tools.

**Comment by ohaucke** [comment]
OK so for now we would have two "workarounds":
1. create a key without password
2. use ssh-agent

I don't like both but for know i guess i can work with that.

**Comment by fd0** [comment]
As far as I remember `ssh` prompts used to work at least on Linux (for password authentication or key unlocking). I'm not sure what the status was on Windows. Apparently, it worked before the change.

**Comment by cqjjjzr** [comment]
I didn't know that :( I just read from https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp which reads: 

> Passwordless login is really important since restic fails to connect to the repository if the server prompts for credentials.

**Comment by ohaucke** [comment]
But the server doesn't prompts for credentials, the ssh client asks for the password of the key.

**Comment by jschwoer** [comment]
I am also facing this issue on Windows 10 21H1 Build 19043.1586 in normal cmd.exe (not WSL) after the update to version 0.13.0.
With version 0.12.1 I was prompted for the key passphrase and now I get the error message "subprocess ssh: Permission denied, please try again."

The ssh client shipped with Windows (C:\WINDOWS\System32\OpenSSH\ssh.exe) is used.

**Comment by cqjjjzr** [comment]
@fd0 I looked up source code of OpenSSH on Windows, and it uses `_getwch` to read from console (https://github.com/NoMoreFood/openssh-portable/blob/latestw_all/contrib/win32/win32compat/misc.c), which can't be redirected (always need an attached console). Any idea we can fix this? Maybe stop using a detached process? But if so the premature-exit problem will go back.

**Comment by mafalb** [comment]
I'm not sure if it could be useful in this case, but there is a separate binary named sshpass, which can provide interactive password

https://linux.die.net/man/1/sshpass
https://sourceforge.net/projects/sshpass/

**Comment by cqjjjzr** [comment]
@mafalb Well, things on Windows are pretty different, so it may not work :(

**Comment by fd0** [comment]
I'm not familiar with the Windows API, but I think we should evaluate if we could implement the same behavior as on Linux: start the process in the Foreground, and then move it to the background (that's what the function returned as `bg` is for):

https://github.com/restic/restic/blob/59370b6062d0ee80875c1463de6fc883630a4a2f/internal/backend/foreground_unix.go#L27-L76

**Comment by cqjjjzr** [comment]
There isn't such mechanism in Windows like the `&` in Linux. The closest equivalent may be starting a process with consoles attached, but then forcing it to detach from the active console after the passphrase is entered. However I doubt such API exists, I will look into it.

**Comment by DRON-666** [comment]
@cqjjjzr I just ran some simple tests and turns out you can just change `DETACHED_PROCESS` to `CREATE_NEW_PROCESS_GROUP` in you PR.

**Comment by cqjjjzr** [comment]
> @cqjjjzr I just ran some simple tests and turns out you can just change `DETACHED_PROCESS` to `CREATE_NEW_PROCESS_GROUP` in you PR.

seems to be true 😮‍💨 I'll test it out

**Comment by cqjjjzr** [comment]
Some quick test shows that using `CREATE_NEW_PROCESS_GROUP` is behaving correctly for both raw and shimmed rclone and ssh, and the cleaning after Ctrl+C is also handled properly. So should I create a new PR?

Huge thanks to @DRON-666

**Comment by fd0** [comment]
Yes, please open a PR! Thanks @DRON-666 and @cqjjjzr!

**Comment by fd0** [comment]
Thanks a lot! @ohaucke can you please test the latest master of restic? You can find a pre-compiled binary with the fix here: https://beta.restic.net/restic-v0.13.0-43-g192288bc/

**Comment by jschwoer** [comment]
The provided version (restic_v0.13.0-43-g192288bc_windows_amd64.exe) works for me on Windows 10.
The key passphrase is prompted.

**Comment by ohaucke** [comment]
@fd0 does work on my side as well
```
> restic_v0.13.0-43-g192288bc_windows_amd64.exe --repo sftp:example.com:/backup/restic/pcname snapshots
Enter passphrase for key 'C:\Users\username\.ssh\example.key':
enter password for repository:
...
```

**Comment by fd0** [comment]
Thanks for the feedback!
