### ISSUE TITLE
shell receives SIGTTOU and stops when SSH fails

### ISSUE THREAD

**Issue by m-varasteh** [restic/restic#3699]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/amd64

How did you run restic exactly?
-------------------------------
Using a python wrapper for Restic and making an instance of the class in the python interpreter shell.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SFTP

Expected behavior
-----------------
Expect Restic to quietly fail to make an SFTP connection and return to python shell

Actual behavior
---------------
Python shell receives a SIGTTOU and is stopped. Using strace on python shell process, it seems that it fails to get control of TTY:
```
...
ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig -icanon -echo ...}) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig -icanon -echo ...}) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig -icanon -echo ...}) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig -icanon -echo ...}) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
...
```

Steps to reproduce the behavior
-------------------------------

This my python wrapper(`temp.py`):
```
import subprocess
import os
import json

repo_addr = "/conf-backup/restic/"
class Restic:
    def execute(self,cmd,input_str=""):
        my_env = os.environ.copy()
        my_env["RESTIC_PASSWORD"] = "1234"
        my_env["RESTIC_REPOSITORY"] = self._repo
        if self._repo.startswith("sftp"):
            my_env["SSHPASS"] = self._password
            cmd.append("-o")
            cmd.append(f"sftp.command=sshpass -e ssh {self._remote_address} -s sftp")
        process = subprocess.run(cmd,
                                capture_output=True,
                                text=True,
                                env=my_env,
                                encoding="utf-8",
                                timeout=5)
        return process.stdout

    def __init__(self,includes : list, repo=repo_addr, remote_addr="", host_password="") -> None:
        self._includes = includes
        self._tags = []
        self._repo = repo
        self._password = host_password
        self._remote_address = remote_addr
        output = self.execute(['restic','--json','snapshots'])
        print(output)
```
and this is the output of running in python shell with the wrong credentials to make SSH failing

``` bash
n1:~$ python3
Python 3.8.12 (default, Jan 24 2022, 11:46:59) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import temp
>>> rst = temp.Restic(["/etc/backup.cnf"],f"sftp::backup","m1@192.168.30.50","asdasd")


[1]+  Stopped                 python3
n1:~$ fg
python3
>>> 
```

I've also tried using the restic without `sftp.command` option and nothing is changed.  

Do you have any idea what may have caused this?
-----------------------------------------------
I think it has something to do with restic's `startForeground` function.

Do you have an idea how to solve the issue?
-------------------------------------------
I'm afraid Not

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
You could tell ssh to ask for the password only once which should work by passing `-o NumberOfPasswordPrompts=1`. The underlying problem seems to be that when the timeout occurs that the ssh process is still running in the foreground. Then when python wants to print something on the terminal, it is sent to the background.

Moving the ssh process to the foreground is what's necessary to allow users to manually enter their password.

**Comment by m-varasteh** [comment]
Thanks Michael for explanation. I'm afraid setting the `NumberOfPasswordPrompts` to `1` didn't resolve the issue, so it seems that the timeout is not the problem. Anyway, right now i'm using `sshfs` to make things work. I understand that running SSH in foreground is vital to achieve the desired functionality, but the problem is that it's not correctly releasing the TTY after it's done.

**Comment by MichaelEischer** [comment]
Normally it would be restic's job to move sftp to the background after it has started. However, when the timeout specified for `subprocess.run` expires then python get's out the sledge hammer and sends SIGKILL to restic:

https://github.com/python/cpython/blob/1c8b3b5d66a629258f1db16939b996264a8b9c37/Lib/subprocess.py#L530
https://github.com/python/cpython/blob/1c8b3b5d66a629258f1db16939b996264a8b9c37/Lib/subprocess.py#L2109

That leaves restic no chance to cleanup behind itself. However, you could just prevent restic from moving sftp to the foreground by removing its controlling tty. Just run `setsid -w restic snapshots`.

**Comment by m-varasteh** [comment]
I tried the `subprocess.run` without specifying the timeout value and the result has not changed and as said before, timeout is not the cause of the problem. I'm afraid `setsid -w restic` is not a good solution for me as i need the prompt for the password. I use the `sshfs` as a workaround for this case and since it's a corner case( running restic from a script in another interactive shell other than bash or similar shells), I'm good to close the issue. But it would be appreciated if you inform me if something new came into light. Thank you for the time and effort and keep up the good work!
