### ISSUE TITLE
Add --exclude-other-filesystem support

### ISSUE THREAD

**Issue by mafgh** [restic/restic#370]
From duplicity:

> --exclude-other-filesystems
>   Exclude files on file systems (identified by device number) other than the  file  system  the  root  of  the source directory is on.

Given

> /dev/mapper/sys-root on / 
> proc on /proc
> /dev/mapper/sys-home on /home

The following would backup **/** but not **/home** nor **/proc**

> restic backup / --exclude-other-filesystem

**Comment by rfjakob** [comment]
This is pretty important when you want to back up the root filesystem and the one thing that keeps me from switching from Attic. I'll see if I can get this done.

**Comment by fd0** [comment]
Oh, that'd be excellent! If you have any questions or need guidance navigating the code base, feel free to drop by in #restic on irc.freenode.net :)

**Comment by fd0** [comment]
It was implemented and merged just now, the command-line option is `--one-file-system`.
