### ISSUE TITLE
Syntax error in exclude file causes all excludes to be ignored and back up uploads all files

### ISSUE THREAD

**Issue by quinncomendant** [restic/restic#3709]
Output of `restic version`
--------------------------

    restic 0.13.1 compiled with go1.18 on darwin/arm64

How did you run restic exactly?
-------------------------------

    export RESTIC_PASSWORD_COMMAND='(command that returns repo password)';
    export GOOGLE_PROJECT_ID='(project id)';
    export GOOGLE_APPLICATION_CREDENTIALS="(path to service account credentails)";
    export RESTIC_REPOSITORY='gs:bucket:/';
    restic -v -v backup /Users/me --exclude-file=exclude.txt --dry-run

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

GCS Coldline

Expected behavior
-----------------

When an exclude file contains syntax errors, restic should display an error _and exit_.

Actual behavior
---------------

When an exclude file contains syntax errors, restic continues to back up all files without exception. One syntax error in the exclude file causes all exclude rules to be ignored. The result is that many GB of data I didn't want in my repo is uploaded. 

Steps to reproduce the behavior
-------------------------------

1. Create a file `exclude.txt` containing any number of exclude rules, with this invalid (? not sure why, looks ok to me) exclude rule:
```
*[._]log[.-][0-9]
```
2. Do a dry-run back up like this:
```
restic -v -v backup /Users/me --exclude-file=exclude.txt --dry-run
```
The output will contain error messages: *“error for exclude pattern: Match: syntax error in pattern”*. Here's is my output:

    ❯ restic -v -v backup /Users/me --exclude-file=exclude.txt --dry-run
    open repository
    repository 8f5e121b opened successfully, password is correct
    found 7 old cache directories in /Users/me/Library/Caches/restic, run `restic cache --cleanup` to remove them
    lock repository
    load index files
    using parent snapshot 3cd63dc5
    start scan on [/Users/me]
    start backup on [/Users/me]
    error for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for 
    error for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Mat
    unchanged /Users/me/.CFUserTextEncoding
    new       /Users/me/.DS_Store, saved in 0.002s (54.004 KiB added)
    unchanged /Users/me/.bash_profile
    unchanged /Users/me/.bash_profile-local
    unchanged /Users/me/.bashrc
    unchanged /Users/me/.bashrc-local
    error for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pa
    new       /Users/me/.config/.DS_Store, saved in 0.000s (8.004 KiB added)
    unchanged /Users/me/.config/bat/config
    error for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for exclude pattern: Match: syntax error in patternerror for 
    unchanged /Users/me/.config/bat/syntaxes/PHP.sublime-syntax
    unchanged /Users/me/.config/bat/syntaxes/
    unchanged /Users/me/.config/bat/
    …etc

Do you have any idea what may have caused this?
-----------------------------------------------

I'm pretty sure restic caused this. 🙃

Do you have an idea how to solve the issue?
-------------------------------------------

Instead of just printing an error message, restic should print the error message **and then exit** (ideally with a useful exit status code).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is freaking awesome. Sometimes it just works so well I live fearlessly and forget to use --dry-run. 😁

**Comment by MichaelEischer** [comment]
Indeed, that behavior is a bit unexpected. Restic should ideally check the syntax of its exclude patterns, directly when parsing them in `filter.preparePattern`. Then it would also be a very useful to print the problematic pattern. Anyone up for a PR?

**Comment by lbausch** [comment]
@quinncomendant Your regular expression is invalid because of the missing argument to the repetition operator `*` right in the beginning.
