### ISSUE TITLE
Possible to manually specify "root directory mask" when adding files?

### ISSUE THREAD

**Issue by cathalgarvey** [restic/restic#371]
Hi folks,

I love the concept and simplicity of Restic, and that it supports a number of backends. Makes for a nice "self-hostable" alternative to Tarsnap, written in a language I'm comfortable with too. :)

However, my use-case prevents me going all-in on Restic yet, but it's possible I'm just not finding the right option in the docs:

* I've got a backup directory on my hard-drive already, which roughly mirrors my home directory and which contains the newest revision of any file I've ever had in my root dir for years. Obviously, I'd like to start with this, and start revisioning on top of it.
* I've got a laptop with a home dir full of stuff to be revisioned.
* As Restic currently appears, when given a directory to backup it will traverse back to the root directory "/", and backup that path.
* So, if I backup my HDD first, it'll use the path `/media/cathal/hdd/backups/homedir`, whereas when I then back up my homedir it'll use the path `/home/cathal/`.

I don't know if this actually *matters*. Maybe restic will recognise files by hash, and merely keep a conflicted history of file locations. But when it comes to revisioning particular files, if indeed restic does inter-file-version revisions, won't it result in one "old version" and an entirely different "new version" at this junction?

If this is an issue, I'd like if Restic allowed me to specify a root directory mask, perhaps even letting me add a root prefix, too. This would let me do this to add my old documents backup, and then to update with my current documents:

    restic -r='media/cathal/hdd/backups/newbackups.restic' --root-mask='/media/cathal/hdd/backups/homedir' '/media/cathal/hdd/backups/homedir/documents' 
    # Above command adds all files as if they came from /documents
    restic -r='media/cathal/hdd/backups/newbackups.restic' --root-mask='/home/cathal' ~/documents
    # Above command adds all files as if they came from /documents

..if I could also specify a root prefix after masking, it'd be even better, because I could omit the mask for "normal" updates thereafter:

    restic -r='media/cathal/hdd/backups/newbackups.restic' --root-mask='/media/cathal/hdd/backups/homedir' --root-prefix='/home/cathal/' '/media/cathal/hdd/backups/homedir/documents' 
    # Above command adds all files as if they came from /home/cathal/documents
    restic -r 'media/cathal/hdd/backups/newbackups.restic' ~/documents
    # Above command adds all files as if they came from /home/cathal/documents

Is something like this already possible, or how might it be implemented? I'm happy to dive in and hack on this if given some pointers on how not to screw it up; I'm proficient enough in Go but don't want to mess up the code layout through ignorance.

**Comment by fd0** [comment]
Hi, thanks for your comment. I haven't thought about this, but I will now.

Regarding the subdir structure that is created in the repository for a snapshot, I had a look at how `tar` handles this:
 * `tar c /foo/bar` gives `/foo/bar/file.txt` in the tar
 * `cd /foo; tar c bar` gives `bar/file.txt` in the tar

So in order to reduce the additional subdirs in the snapshots, just `cd` to an appropiate directory before starting restic.

For restic itself it does not really matter, it's just one or two additional meta data documents, but they are really tiny and don't disturb anything. All files are split into chunks which are then identified by the SHA256 hash, so the file name or path doesn't matter at all, restic will still only save one instance of a blob in the repository.

Does that answer your questions so far?

**Comment by cathalgarvey** [comment]
Ah! Revisiting the docs, I see you were specifying "~" prior to each `backup`'d path, which I'd missed. So, you were specifying the absolute paths all along, whereas I mistakenly thought they were relative paths and that the programme was expanding to abspaths in every case.

So, if it doesn't use abspath but goes instead by the user-provided path-to-file, then yes; this is much cleaner in real-world use. The options I suggested above would help in edgy cases or in cases where current working directory cannot be contrived, (for example, cron scripts etcetera), but are not essential in my particular case.

Thanks for the quick help!

**Comment by fd0** [comment]
You're welcome. At the moment I don't think that the extra options are necessary, so I'm tempted to close this issue for now. What do you think?

**Comment by cathalgarvey** [comment]
They're something I'd like to see in Restic for the aforementioned reasons; sometimes, CWD isn't possible to engineer prior to executing Restic. But, for my immediate uses it sounds like they won't affect storage volume much and I don't mind if the metadata gets slightly confused. I looked into the chunking algorithm, looks really clever. :)

Thanks!
