### ISSUE TITLE
v0.13 gets stuck on repack step (s3 backend)

### ISSUE THREAD

**Issue by seqizz** [restic/restic#3710]
Output of `restic version`
--------------------------

```
restic 0.13.0 (v0.13.0-17-ga08b95c4) compiled with go1.18 on linux/amd64
```

How did you run restic exactly?
-------------------------------

Command is:
```
sudo -E /usr/local/bin/restic --cache-dir /my/cache/folder --cleanup-cache prune --max-unused 20% --max-repack-size 50G
```
(It reads its configs from environment variables)

This is the way I run prune within an automated script. I realized we got a stuck prune process for one repo (~600gb). Tried to run it manually and saw it got stuck on **repacking packs** step. It stops at `1 or 2 / $whatever_pack_number` so it might be a race condition somewhere. Downgrading it to restic v0.12, I didn't see the issue and prune operation was pretty smooth. Afterwards I tried once more with version 0.13 and got stuck again.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Minio (locally hosted & single-instance)

Steps to reproduce the behavior
-------------------------------

Not sure if you can also reproduce somewhere else, skimmed through issues but couldn't find something similar.

- Have an s3 backend
- Have latest version of restic
- Run prune with given parameters above

Do you have any idea what may have caused this?
-----------------------------------------------

Sadly no, downgrading is making the issue disappear so I suspect latest changes with s3 backend maybe?

Do you have an idea how to solve the issue?
-------------------------------------------

Nope. But I am attaching a debug log which I reproduced the issue with:

- Waited few mins on "repacking packs", while it waited on `1 / 5490 packs repacked`
- Pressed Ctrl-C
- Said "signal interrupt received, cleaning up`
- Waited a bit more, since it was still stuck
- Sent `kill -3` to the process :shrug: 

Sadly I needed to remove everything until repack.go involved, since total file size was aroung 1GB otherwise. Now it's just 434 lines.

[restic-debug.log](https://github.com/restic/restic/files/8487587/restic-debug.log)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

You have no idea! You people rock :smile:

**Comment by MichaelEischer** [comment]
Do you have the goroutine dump printed after sending `kill -3` to restic? It's apparently not part of the debug log, which only show that restic is stuck...

**Comment by fd0** [comment]
If you can reproduce it, it would be best if you could run prune, wait until it gets stuck, then use `kill -3` (which is SIGQUIT) and just send us the stacktrace, which should be rather small (just a few hundred lines or so). It is printed to stderr, so you can redirect that to a file from the start with `2> stacktrace.log`. Then we can see where it got stuck. That it gets stuck again at the cleanup step is likely the same or a followup issue...

**Comment by MichaelEischer** [comment]
After taking another look at the debug.log, I'm pretty sure that this is caused by #3484, but it would still be helpful to get a stacktrace to confirm.

`Repack` now uses `StreamPack` which while streaming the contents of one pack file occupies one backend connection that counts against the connection limit. However, to upload a repacked pack file we need another connection. Now, when all backend connections are already occupied by the `StreamPack` calls, then there are no connections left to upload anything. And thus `StreamPack` gets stuck permanently.

I'm not yet sure what's the proper solution here. #3489 should fix most hangs, but probably doesn't solve the problem completely.

**Comment by fd0** [comment]
I think a real fix would be to expose the configured backend connection parallelism in the `restic.Backend()` interface, then let `StreamPacks()` query that and adjust its concurrency accordingly.

**Comment by seqizz** [comment]
Attaching stderr too. Not from a debug-enabled binary though since I am currently on the way :grimacing: 
[stderr.log](https://github.com/restic/restic/files/8495068/stderr.log)

**Comment by MichaelEischer** [comment]
Thanks for the stack trace, it confirms that the problem is indeed the deadlock involving `StreamPacks` described above. For now as a workaround you can use `-o s3.connection=10` (or higher). As there are only up to 8 repack workers, this makes sure that it is always possible to upload new packs.

**Comment by lbausch** [comment]
Just a small remark, it's actually `-o s3.connections=10`

**Comment by MichaelEischer** [comment]
@seqizz can you test whether #3717 fixes the problem?

**Comment by seqizz** [comment]
Yep, seems like repacking is processing OK with https://github.com/restic/restic/pull/3717 :+1:

**Comment by lbausch** [comment]
Also confirming #3717 makes `repacking packs` complete in reasonable time again
