### ISSUE TITLE
Performance improvement for content checksum

### ISSUE THREAD

**Issue by xor-gate** [restic/restic#372]
I think there a can be get a 300% performance gain by using the Blake2b checksum instead of SHA-256 (which is a improved version of the Blake algorithm used in SHA-3)

Benchmark from github.com/codahale/blake2:

My NAS
Intel(R) Atom(TM) CPU  C2550  @ 2.41GHz, 4 cores, 1MByte L1 cache

```
BenchmarkBlake2B-4       200       8354838 ns/op     125.51 MB/s
BenchmarkMD5-4           500       2568903 ns/op     408.18 MB/s
BenchmarkSHA1-4          300       5342146 ns/op     196.28 MB/s
BenchmarkSHA256-4        100      13622543 ns/op      76.97 MB/s
BenchmarkSHA512-4        200       8909665 ns/op     117.69 MB/s
```

KVM VPS (depends on host os scheduling)
Westmere E56xx/L56xx/X56xx (Nehalem-C) @ 2294.686 MHz, 4MByte L1 cache

```
BenchmarkBlake2B        1000       2633524 ns/op     398.16 MB/s
BenchmarkMD5        1000       2095968 ns/op     500.28 MB/s
BenchmarkSHA1       1000       2677232 ns/op     391.66 MB/s
BenchmarkSHA256      500       7270033 ns/op     144.23 MB/s
BenchmarkSHA512      500       4834102 ns/op     216.91 MB/s
```

MacBookPro11,1 2.4 GHz (i5-4258U) Intel Core i5 Haswell

```
BenchmarkBlake2B-4      1000       2130623 ns/op     492.15 MB/s
BenchmarkMD5-4          1000       1865851 ns/op     561.98 MB/s
BenchmarkSHA1-4          500       2346633 ns/op     446.84 MB/s
BenchmarkSHA256-4        200       6472990 ns/op     161.99 MB/s
BenchmarkSHA512-4        300       3949461 ns/op     265.50 MB/s
```

The specification can be read here: https://blake2.net/
Wikipedia: https://en.wikipedia.org/wiki/BLAKE_(hash_function)

On my macbook this is a performance gain of 300% :+1:

If seen bazil filesystem using Blake2 for chunking:
https://github.com/bazil/bazil/blob/master/cas/chunks/chunkutil/hash.go
Architecture: https://bazil.org/doc/architecture/#cas

Just an idea to use newer and faster technologies :-)

**Comment by fd0** [comment]
Thanks for having a look, I'll keep that in mind for a later version. At the moment it's much more important to get the code stabilized and add more important features. Changing the underlying hash is a breaking change, so we need to be really sure about it. ;)

**Comment by xor-gate** [comment]
Yeah I know, when there are more tests and it is more stable it could be developed/tested in a separated branch. Its good to know where there could be improvements done in the future. Thanks for your answer!

**Comment by aead** [comment]
Just for reference: 
The "offical" golang [x/crypto](https://godoc.org/golang.org/x/crypto) sub-repo now contains both - [BLAKE2b](https://godoc.org/golang.org/x/crypto/blake2b) and [BLAKE2s](https://godoc.org/golang.org/x/crypto/blake2s)

**Comment by xor-gate** [comment]
Thanks @aead, I must have missed your comment notification. I use BLAKE2s in a few projects myself and I'm very happy with the performance compared to SHA256. 

@fd0 if you want to leave SHA256 in for now, you could try the drop-in replacement sha256-simd which can improve the performance by a few factors.

See: https://github.com/minio/sha256-simd

**Comment by fd0** [comment]
I made a few tests with that implementation a while ago, and decided it wasn't worth including another third-party library (even if it's from the awesome people at minio). Did you test it recently?

**Comment by xor-gate** [comment]
It depends on the platform, but SIMD kan have some performance improvements. At least in the Syncthing project. I'm not using sha256 myself and have not run any benchmarks on this.

**Comment by fd0** [comment]
The last time I had a look, the syncthing people talked about this implementation crashing from time to time on some architectures. Do you maybe know if that has been solved yet?

**Comment by xor-gate** [comment]
Yes this was due to misdetection in CPU features. It has been fixed recently (here https://github.com/minio/sha256-simd/issues/6). They also implement algo-switching with best-measured on application startup:

```
[TWJVV] 10:18:53 INFO: Single thread SHA256 performance is 384 MB/s using minio/sha256-simd (379 MB/s using crypto/sha256).
```

**Comment by xor-gate** [comment]
<offtopic>@fd are you attending at FOSDEM '17?</offtopic>

**Comment by fd0** [comment]
Yeah, I'll be there on Sunday: https://restic.github.io/blog/2017-02-02/FOSDEM-2017-Brussels

**Comment by xor-gate** [comment]
Great, probably we will see each other in meatspace then :-).

**Comment by fd0** [comment]
Looking forward to it!

**Comment by aead** [comment]
@xor-gate 
On non-arm machines minio uses the /x/crypto/blake2b now - but their SHA-256 impl. for arm is very good work!

Here some benchmarks on an i7-U6500:
BLAKE2b
```
BenchmarkWrite128-4   	10000000	       166 ns/op	 770.27 MB/s
BenchmarkWrite1K-4    	 1000000	      1199 ns/op	 853.39 MB/s
BenchmarkSum128-4     	10000000	       189 ns/op	 677.14 MB/s
BenchmarkSum1K-4      	 1000000	      1216 ns/op	 841.85 MB/s
```
vs SHA-256
```
BenchmarkHash8Bytes-4   	 5000000	       282 ns/op	  28.27 MB/s
BenchmarkHash1K-4       	  500000	      3266 ns/op	 313.50 MB/s
BenchmarkHash8K-4       	  100000	     24018 ns/op	 341.07 MB/s
```
(Notice that there's a AVX(2) bug in the BLAKE2b impl., but a patch is [submitted](https://go-review.googlesource.com/#/c/34993/) )

But I would agree with you (@fd0), that there are probably more important issues (and features), than the hash-performance

**Comment by xor-gate** [comment]
Yes I agree this is low-prio but worth the discussion and testing.

**Comment by fd0** [comment]
Ah, that's not really what meant, but interesting nonetheless. I was asking for benchmarks on the stdlib SHA2 implementation versus the Minio one. :smile:

**Comment by dimejo** [comment]
> Ah, that's not really what meant, but interesting nonetheless. I was asking for benchmarks on the stdlib SHA2 implementation versus the Minio one. 😄

The [README](https://github.com/minio/sha256-simd/blob/master/README.md) lists a performance comparison with `crypto/sha256` if that's what you were looking for.

**Comment by fd0** [comment]
Interesting, thanks!

**Comment by mbarkhau** [comment]
In case anybody missed the Blake3 hype:

 - https://github.com/BLAKE3-team/BLAKE3
 - Go implementation: https://github.com/lukechampine/blake3

Maybe worth considering instead of blake2b.

**Comment by yourfate** [comment]
since the hash does not need to be cryptograhpic afaik, we should maybe think about xxhash too. That is a very fast non-cryptographic hash, which is widely used.

**Comment by MichaelEischer** [comment]
I'm pretty sure that we want a cryptographic hash, as the base assumption of restic is that there will never be two blobs which have the same hash. It is probably way to easy to violate that assumption using a non-cryptographic hash.

xxHash is also not usable for a different reason: it only creates up to 128bit hashes which has a far too high probability of hash collisions on large backups.

Restic has been using https://github.com/minio/sha256-simd for some time now which is able to make use of hardware acceleration if existing for the sha256 hash calculation.

**Comment by MichaelEischer** [comment]
As I don't us changing the content checksum sometime in the future, let's close this issue. Thanks for the input anyways!
