### ISSUE TITLE
Snapshot folder names are jumbled up in Samba

### ISSUE THREAD

**Issue by akaFTS** [restic/restic#3721]
Output of `restic version`
--------------------------
restic 0.12.1 (v0.9.6-1398-gf5474f4c) compiled with go1.15.14 on linux/amd64

How did you run restic exactly?
-------------------------------

restic -r rclone:my-database mount /bkp-nuvem/ --tag dados --allow-other --snapshot-template "BKP 2006-Jan-02 15:04:05"

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Google Drive

Expected behavior
-----------------
Mounting the repository to the `/bkp-nuvem` folder of my CentOS 7 server and adding it to my Samba configuration should make the snapshots available to Windows users in my network flawlessly. 

This is the Samba configuration file:

```
[bkp-nuvem]
    comment = BKP-NUVEM Linux Server
    browseable = yes
    path = /bkp-nuvem/snapshots
    public = no
    guest only = no
    writable = no
    valid users = @diretoria
    create mask = 0550
    force create mode = 0550
    directory mask = 0550
    force directory mode = 0550
```

Actual behavior
---------------
Most of the files and folders are, indeed, accessible from the Windows clients. However, the top-level snapshot folders (the ones under `/bkp-nuvem/snapshots`, such as `BKP 2022-Apr-17 03:10:00`) have their names jumbled up:

![image](https://user-images.githubusercontent.com/6173351/165196778-e44295f4-fac1-4abc-8889-421b53ba862e.jpeg)
Notice how only the `latest` symlink is intact.

Steps to reproduce the behavior
-------------------------------
Mount a repository using the command above, add the snapshots folder to Samba using the configuration above, and browse it from a Windows machine.

Do you have any idea what may have caused this?
-----------------------------------------------
Nope. The inner folders are okay, so it is not caused by encoding. Perhaps it has to do with how mount works under the hood.

Do you have an idea how to solve the issue?
-------------------------------------------
Not at all.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Definitely. This thing is beautiful. I've tried tons of other backup tools and restic is way above all of them.

**Comment by bjoe2k4** [comment]
A colon `:` is not allowed in file names or directories, I guess that's why you are seeing some replacement names.

**Comment by akaFTS** [comment]
Removing the colons did the trick. Thanks!

**Comment by fd0** [comment]
How did you remove the colons? did you pass `--snapshot-template` to `restic mount`? It'd be nice to leave a clue for other people looking at this issue in a year or so ;)

**Comment by akaFTS** [comment]
Yes, as you can see from the issue description I had `--snapshot-template "BKP 2006-Jan-02 15:04:05"` as the formatter for my folder names. I simply changed that to `--snapshot-template "BKP 2006-Jan-02 15h04"` and all was good.
