### ISSUE TITLE
Calculation of "Total Size" varies without changes to the repo

### ISSUE THREAD

**Issue by derBobby** [restic/restic#3736]
Output of `restic version`
--------------------------
restic 0.13.1 compiled with go1.18 on linux/386

How did you run restic exactly?
-------------------------------
Env:
`RESTIC_PASSWORD=test
`
Command 1:
`restic stats -r /tmp/restic-test
`

Output 1:
```
repository e4d4e8fe opened successfully, password is correct
scanning...
Stats in restore-size mode:
Snapshots processed:   7
   Total File Count:   798
         Total Size:   1.786 GiB
```

Command 2:
`while true; do restic stats -r /tmp/restic-test | grep "Total S" ; done
`

Output 2:
```
         Total Size:   1.943 GiB
         Total Size:   1.928 GiB
         Total Size:   1.928 GiB
         Total Size:   1.896 GiB
         Total Size:   1.928 GiB
         Total Size:   1.772 GiB
         Total Size:   1.882 GiB
         Total Size:   1.882 GiB
         Total Size:   1.786 GiB
         Total Size:   1.882 GiB
         Total Size:   1.882 GiB
         Total Size:   1.928 GiB
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local

Expected behavior
-----------------
I expect the size of the repository to remain constant if no changes are made to it.

Actual behavior
---------------
Output 2 shows that the repository size varies.

Steps to reproduce the behavior
-------------------------------
See command 1 above.

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic rocks!

**Comment by MichaelEischer** [comment]
Could you try whether PR #3740 fixes the problem?

**Comment by derBobby** [comment]
#> while true; do ./restic_linux_386 stats -r . | grep "Total S" ; done
         Total Size:   298.994 GiB
         Total Size:   300.802 GiB
         Total Size:   298.994 GiB
  signal interrupt received, cleaning up

#> ./restic_linux_386 version
restic 0.13.1-dev (compiled manually) compiled with go1.18 on linux/386

**Comment by derBobby** [comment]
the Total Size is constant now but there is a huge difference in the Total Size output of the two binaries.
Which one is correct?
Followup bug?

Output original binary
```
~/restic# while true ; do restic stats -r sftp:user@host:/repo | grep "Total S" ; done
         Total Size:   2.683 GiB
         Total Size:   2.687 GiB
         Total Size:   2.687 GiB
         Total Size:   2.683 GiB
         Total Size:   2.686 GiB
         Total Size:   2.686 GiB
         Total Size:   2.686 GiB
         Total Size:   2.685 GiB
         Total Size:   2.686 GiB
         Total Size:   2.690 GiB
         Total Size:   2.648 GiB
         Total Size:   2.686 GiB
         Total Size:   2.687 GiB
         Total Size:   2.687 GiB
         Total Size:   2.683 GiB
         Total Size:   2.683 GiB
         Total Size:   2.686 GiB
```

Output from PR branch binary
```
~/restic# while true ; do ~/bin/restic_linux_386 stats -r sftp:user@host:/repo | grep "Total S" ; done
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
         Total Size:   10.752 GiB
```

**Comment by MichaelEischer** [comment]
The output of the PR branch should be the correct one. "Total Size" should add the restore size of all snapshots together. That is running `stats` should yield the same result as running `stats snapshot-ID` for each snapshot individually and adding up the results. That is consistent with restic 0.9.6 and was accidentally changed by an old PR.

**Comment by derBobby** [comment]
I guess this issue is then closed? :-)
