### ISSUE TITLE
backup command ignores json flag

### ISSUE THREAD

**Issue by nh-matti** [restic/restic#3737]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.5 on linux/arm

How did you run restic exactly?
-------------------------------
```
export RESTIC_PASSWORD=<mypass>
export $RESTIC_REPOSITORY=sftp:<HOST>@backup.local:/home
restic backup /srv --json
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SFTP

Expected behavior
-----------------
output with flag --json should be json

Actual behavior
---------------
the json flag seems to be ignored
```
# restic backup /srv --json

Files:           0 new,     0 changed,     1 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 0 B
```

Steps to reproduce the behavior
-------------------------------
Everytime I call the `restic backup --json` command

Do you have any idea what may have caused this?
-----------------------------------------------
I have tested the same on ubuntu 20.04 Virtual Machine and the output is as expected.
I think it depends on arm version. It fails on both Arm based debian version (2x RaspberryPi 3)

Do you have an idea how to solve the issue?
-------------------------------------------
no, sorry

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Since i use restic for the family pictures, my wife is sleeping very well ;)

**Comment by MichaelEischer** [comment]
`backup --json` is only supported since restic 0.9.5 (https://github.com/restic/restic/releases/tag/v0.9.5). So just get an up-to-date restic version e.g. from the [releases](https://github.com/restic/restic/releases) section.
