### ISSUE TITLE
Support json output for forget

### ISSUE THREAD

**Issue by gmgigi96** [restic/restic#3745]
Output of `restic version`
--------------------------
restic 0.13.0 compiled with go1.18 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Support the json output when running the forget command. Currently only the "normal" output is supported.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Will make easier parse the output in json by a script.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is a fantastic tool we are using at CERN to backup every day ~40K home and project directories of our users, resulting in >300M of new files every day, for a total of 4PB of data being backed up.

**Comment by MichaelEischer** [comment]
Which part of the output from forget do you refer to? As discussed in #3117 there's no output when explicitly deleting a snapshot by ID, and `forget -n --json -d 5` returns JSON output for me. So I guess you're referring to `forget --prune`? If yes, then you're looking for #3129.

**Comment by MichaelEischer** [comment]
@gmgigi96 Ping.

**Comment by gmgigi96** [comment]
@MichaelEischer Sorry for the late reply, what I meant is exactly what is already specified in https://github.com/restic/restic/issues/3129 for the `forget --prune`
