### ISSUE TITLE
restic self-update on linux changes file permissions of restic binary

### ISSUE THREAD

**Issue by spi43984** [restic/restic#3758]
Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.16.6 on linux/amd64                                                                                                                                          
(can't test with 0.13.1 as no update is performed then)

How did you run restic exactly?
-------------------------------
restic self-update

Expected behavior
-----------------
"restic self-update" updates the binary and keeps the file permissions intact

Actual behavior
---------------
the restic binary is installed for all local users in a central directory with the following file permissions set:
-rwxr-xr-x  1 root root 18472960 May 15 14:25 restic

Running restic self-update changes these permissions to
-rwxr-x---  1 root root 18472960 May 15 14:37 restic

result: restic can't be run by users anymore until file permissions are set properly again

Steps to reproduce the behavior
-------------------------------
set file permissions properly and run restic self-update, check file permissions again

Do you have any idea what may have caused this?
-----------------------------------------------
restic doesn't check file permissions before update and doesn't set them again to the original ones

Do you have an idea how to solve the issue?
-------------------------------------------
check file permissions before update
perform update
set file permissions to the ones originally set

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It'll make me very happy soon enough...

Am currently circumventing issue by wrapper script and setting umask to 0022.

**Comment by MichaelEischer** [comment]
This has been fixed by #3675 which now explicitly calls `chmod`.
