### ISSUE TITLE
Concurrent use, running multiple backups at the same time

### ISSUE THREAD

**Issue by yatesco** [restic/restic#376]
Hi,

Can multiple instances of restic use the same repository _at the same time_?

I looked at the docs but I couldn't find an answer to this...

Thanks!

Colin

**Comment by fd0** [comment]
Yes, you can, but you won't get the optimal deduplication, so the backups will take a bit more space. A run of `restic optimize` should clear that up, though.

Please close the issue if your question was answered.

**Comment by yatesco** [comment]
Thanks fd0.
