### ISSUE TITLE
Panic when running prune on repository with empty snapshot file

### ISSUE THREAD

**Issue by sorcix** [restic/restic#3763]
restic 0.13.1 compiled with go1.18.1 on linux/amd64

Today I accidentally disconnected the USB drive containing my restic repository after backup, before the kernel was done writing. After removing a partially written index file[^1], restic now panics when pruning. I'm creating this issue as I guess it should exit with an error message, and that the panic might point to a bug somewhere. *I have another copy of my backups so I'm not looking for a solution for the corruption.*

The panic:
```
[root@laptop BACKUP]# restic -r ./repository prune
enter password for repository:
repository bbde6d6c opened successfully, password is correct
loading indexes...
loading all snapshots...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55cc97214394]

goroutine 84 [running]:
main.getUsedBlobs.func1({0xb3, 0x5b, 0x83, 0x0, 0x66, 0xa, 0xcc, 0xbf, 0xa4, 0x28, ...}, ...)
        github.com/restic/restic/cmd/restic/cmd_prune.go:558 +0x54
github.com/restic/restic/internal/restic.ForAllSnapshots.func2()
        github.com/restic/restic/internal/restic/snapshot.go:113 +0x185
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
```

<details><summary>Extra context about how I got here</summary>
<div>
After unplugging my disk, prune failed with an error:

```
[root@laptop BACKUP]# restic -r ./repository prune
enter password for repository:
repository bbde6d6c opened successfully, password is correct
loading indexes...
Fatal: load <index/7f8b7bf231>: invalid data returned
```

So I removed the index file it was referencing:

```
[root@laptop BACKUP]# rm repository/index/7f8b7bf231f0949810d347db5a15b5dde5392219bbbed329b40e15536572aa78
```

At this point I expected `restic prune` to either:

* Show an error similar to the last one.
* Prune the leftover unused files.

But it now panics as shown at the top of this issue.
</div>
</details>

[^1]: Hoping that restic would just ignore the extra data and forget about my last snapshot.

**Comment by sorcix** [comment]
Looks like the panic is caused by an empty snapshot file.

```
-rw-r--r-- 1 sorcix sorcix 280 May 16 15:19 dcfa7e1f45d5aa93b45f9f6ef1a3eac738554525d3a9756be22aa40215f03f01
-rw-r--r-- 1 sorcix sorcix   0 May 20 13:55 b35b8300660accbfa428af7ddc08fd4b3a5b4d96c1020ab122777b645deb51ea
```

Removing it allowed `restic prune` to get rid of the remaining half-written files. Great to see that I could fix it by deleting recent files, as I expected when using backup software that doesn't modify existing files. :+1: 

This also means the panic is easy to reproduce. Simply creating a new empty file in the snapshots folder triggers the panic when running prune. A different name works too, as long as it has the correct format.

```
touch repository/snapshots/b35b8300660accbfa428af7ddc08fd4b3a5b4d96c1020ab122777b645deb51ea
```

**Comment by MichaelEischer** [comment]
Thanks for the steps to reproduce, that crash is slightly embarrassing...

Which filesystem do you use on your external USB drive? Restic is explicitly asking the filesystem to store the file content before renaming the file to its final name. Or in other words: the situation your repository ended up in shouldn't be possible. It might be a good idea to run `check --read-data` to make sure there are no further damages. (although deleting the damaged index is probably enough to let any further lost files have no lasting effect).
