### ISSUE TITLE
Prune failed

### ISSUE THREAD

**Issue by notanexpert22** [restic/restic#3765]
sudo restic -r /backup/restic-repo prune
enter password for repository: 
repository 412dbbc0 opened successfully, password is correct
counting files in repo
building new index for repo
[1:06] 100.00%  28225 / 28225 packs
incomplete pack file (will be removed): 088a3150b39c3867864ae928d1684b616e288b45faa595704b8d3ffaeb9c720f
repository contains 28224 packs (279098 blobs) with 105.113 GiB
processed 279098 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 210 snapshots
[0:05] 100.00%  210 / 210 snapshots
Fatal: [<data/aaf9394b> <data/b71276d0> <data/91809706> <data/c1cfd2d9> <data/c0c5e7d2> <data/6beb9a49> <data/0ddf749b> <data/5b252320> <data/d6e498d4> <data/20f19e21> <data/cad458e0> <data/40d7c5db> <data/c08262ff> <data/ff9752a5> <data/168dee07> <data/d0877246> <data/cc40f49b> <data/ee9b9d35> <data/2917f81a> <data/f56853a3> <data/7d7d4aa5> <data/2cdfbe66> <data/94e672f5> <data/d9f6332c> <data/ce405d23> <data/c835b298> <data/e4006acf> <data/1e60da0f> <data/d6bf8090>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose

Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.9 on linux/amd64

How did you run restic exactly?
-------------------------------
sudo restic -r /backup/restic-repo prune

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Odroid HU4

Expected behavior
-----------------
Do a prune,  I executed a changed forget command before prune.  Lowered monthy snapshots from 12 mo to 6 to save space
do prune after changed forget 

Actual behavior
---------------
Error as shown above

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------
Maybe changing the forget command on an established repo.  Lowered monthly snapshots from 12 to 6.

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
> Maybe changing the forget command on an established repo. Lowered monthly snapshots from 12 to 6.

This error is unrelated to changing the `forget` command. To repair the repository it is advisable to upgrade to restic 0.13.1 first.


Did you notice any errors reported in prior restic runs or did something unexpected happen? Maybe an interrupted network connection or did the host go into standby while restic was running? Is this the first failing `prune` run? Do you have logs of the `backup` and `prune` run before the failing one? Did restic report any errors there?

How often do you run `backup`, `check` and/or `prune`?

Which backend are you using?

Please run `restic check --read-data` to analyze the damage to the repository.

Did you run any commands previously to try to repair the damage? I'm especially interested in whether you ran `rebuild—index`? If the answer is no, then please create a backup of the repository index (the `index/` folder in the repository).
Or at least do **NOT** run `rebuild index` for now.

It would be helpful to know which snapshots are missing blobs: Please run `restic find --blob aaf9394b b71276d0 91809706 c1cfd2d9 c0c5e7d2 6beb9a49 0ddf749b 5b252320 d6e498d4 20f19e21 cad458e0 40d7c5db c08262ff ff9752a5 168dee07 d0877246 cc40f49b ee9b9d35 2917f81a f56853a3 7d7d4aa5 2cdfbe66 94e672f5 d9f6332c ce405d23 c835b298 e4006acf 1e60da0f d6bf8090` to find the affected snapshots.

**Comment by MichaelEischer** [comment]
Closed as there was no feedback in a month.
