### ISSUE TITLE
Long running 'mount'

### ISSUE THREAD

**Issue by yatesco** [restic/restic#377]
Hi,

Are there any problems with having the repository mounted for a long time/permanently? The documentation doesn't mention any but it does say `Don't forget to umount after quitting!` which made me wonder...

Thanks!

Colin

**Comment by fd0** [comment]
It has not been tested as far as I know, but should work just fine. It probably won't find new snapshots, though. What's your use case for this?

If you are satisified with the answer, please close the issue. You can still add comments here and people will be able to find your question and the discussion.

**Comment by yatesco** [comment]
My use case is to expose the repository over a (read only) samba share.

**Comment by AlexDunmow** [comment]
@yatesco: did you get this working via samba?

**Comment by yatesco** [comment]
Hi @AlexDunmow, nope, I didn't in the end. I confess I moved elsewhere.
