### ISSUE TITLE
Using zstd dictionaries for new compression support to handle better deduplication

### ISSUE THREAD

**Issue by JsBergbau** [restic/restic#3775]
This is in reference to already merged pullrequest https://github.com/restic/restic/pull/3666

@fd0
sorry for writing so late, but I didn't have this in mind https://github.com/JsBergbau/Verschiedenes/issues/2 when following your work on compression support.

I've done some experiments how deduplication works together with compression. using the `--rsyncable` option.

Testfiles: Total 55 MySQL dump files with 150.8 GB from a productive moodle system. 
These were added to a repo with different treatment.

Completly uncompressed repo size was 41.1 GB
Using gzip compression data size was 26.6 GB
Using gzip with  `--rsyncable` lead to only 8.57 GB in the repo so only about 1/3 of the size, just by using `--rsyncable` option. See also https://github.com/restic/restic/issues/2886#issuecomment-894354706

How `--rsyncable` works is explained here https://beeznest.wordpress.com/2005/02/03/rsyncable-gzip/

As far as my research has shown there are dictionaries for zstd. Without using them it seems zstd uses adaptive compression like normal gzip. When using dictionaries it works, as far as I understand, like gzip with `--rsyncable` option, especially because of 

[quote] If an unsuitable dictionary is used the output may be slightly larger than using no dictionary. [/quote]

This also showed my experience with gzip. With standard adaptive gzip compression compressed file size was 26.6 GB (26.6 GB in repo), using `--rsyncable` option compressed filesize was 27.3 GB (8.57 GB in repo).

@klauspost Can you confirm my assumptions?

If so I would suggest that we use dictonary option by default. As seen with `--rsyncable` option even if compressed file size is only slightly greater than using adaptive compression with deduplication file size is only one third. 

As far as I understand https://github.com/MichaelEischer/restic/blob/5eb05a0afe9e32baad77e6ff4ea24ef7adb4c7bc/internal/repository/repository.go#L332 there is currently no dictionary option used.

Also as far as I understood data is chopped by the chunker and then compressed and not the other way round. But still as far as I understand that process it should compress better using a fixed dictionary instead of adaptive compression since chunking boundaries may change with changed input. Thus would lead to a lot of different output of the zstd compressed data with the default adaptive compression and thus leading to (almost) no deduplication. With dictionary compressed output there should be a lot of similarities and deduplication works well.

The question is on what data to train? I would suggest to first train it on text files and maybe binaries and ship these dictionaries, but not more to keep it simple. @klauspost Do you have any suggestions? Maybe there is a fixed default dictionary like `--rysncable` option used.

I volunteer to test dictionary and non dictionary compression method on productive SQL database dumps to get performance data.

**Comment by greatroar** [comment]
I think you're conflating two unrelated compression features:

* gzip's rsyncable mode makes it periodically reset its internal state, so the compressed file is essentially a series of independently compressed blocks;
* zstd's dictionary mode makes it start with a different initial state than its empty state, so that strings from the start of the input that look like strings in the dictionary can be compactly encoded.

Note that zstd still performs "adaptive" compression even when a dictionary is used: it should only make a difference at the start of each chunk, say the first few KiB.

**Comment by JsBergbau** [comment]
Thanks for the clarification. Is there something similiar in zstd to reset the internal state to help for deduplication?

**Comment by klauspost** [comment]
You would need to make independent encodes of blocks for them to yield similar output. This will hurt compression significantly.

You should deduplicate uncompressed blocks and compress the remainder.

**Comment by klauspost** [comment]
You'd need to split the input in self-synchronizing blocks and compress each separately. I seem to remember restic already has code for the splitting blocks with auto-resync.

**Comment by greatroar** [comment]
The [chunker](/restic/chunker) does that, and zstd compression runs *after* chunking and deduplication. The advice to use gzip --rsyncable was written for the old situation, where the compression had to take place *before* chunking and dedup. Not using that option would change the input so much that the self-synchronizing would stop working, which is what you're observing in your test.
