### ISSUE TITLE
Error mounting a repo

### ISSUE THREAD

**Issue by yatesco** [restic/restic#378]
Hi,

I created a repo in an Ubuntu 14.04 machine using latest go and master as of 3abff7928c614f794f00347061fe70563af7252f. `restic version` gives:
```
restic 0.1.0 (v0.1.0-171-g3abff79)
compiled at 2015-12-22 00:58:15 with go1.5.2
```

I can successfully mount this on the same box.

I then `brew install`ed it on OSX, which gives:
```
restic 0.1.0
compiled at 2015-12-22 00:35:57 with go1.5.2
```

which gives the following error:
```
➜  ~  restic mount ResticMnt
json: cannot unmarshal object into Go value of type []*repository.packJSON
```

`restic check` on the ubuntu machine works fine but fails with the same error on osx.

It might make a difference but I interrupted the first backup. The second backup of the same directory worked. `restic check` reported lots of `pack 022f240f2bbdd10e38845577f78da323a5f2dda0e8af9f23e69bd4d0f90dcdab: not referenced in any index`. I then took a guess and `restic rebuild-index`ed the repo (from ubuntu) and then `restic check` worked fine.

Thanks!

**Comment by fd0** [comment]
Thanks for reporting, this seems to be a bug, there is some JSON that could not be parsed in the repo, that should not happen. Could you please build restic with debug support and run it with a debug log, as described here: https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs

Then have a look in the debug log if you can see what's going on, maybe you can paste the relevant section. I might add some instructions based on what we can see from the log file.

**Comment by fd0** [comment]
Hey, did you maybe find the time to run restic again with a debug log?

**Comment by yatesco** [comment]
Hiya - apologies no, not yet. It is on my TODO list. One mitigating factor might be that I used a very complex key which contained all sorts of fun characters… I will try and reproduce in the next 48 hours.

**Comment by fd0** [comment]
Great, that'll help a lot I hope :)

**Comment by yatesco** [comment]
I haven't yet had chance to rebuild with debugs, but I can reproduce the error with the repo (created on Ubuntu and then copied and mounted on OSX) and the following key:

UKj@%n8wNCnJy*MBZVIZnu7$0En#pCIVeGBp84e$SXF4@CG##ouU2KEr0n4a&9zG4*3dKYw4WIhw4Q9%#odGqgulpWDMp1d0vNB3

TGZ repo is: https://www.dropbox.com/s/mqk0s7qgm6muktv/restic-repo.tgz?dl=0

Don't worry - the key is temporary so no trade secrets :-).

**Comment by fd0** [comment]
Hm, I got the repo, but it seems the password is incorrect...

**Comment by fd0** [comment]
Ah, got it. Needed to copy the key from your comment's source ;)

**Comment by yatesco** [comment]
Let me know if that is sufficient, if not I will do the rebuild with debug route.

**Comment by yatesco** [comment]
As another data point - creating the repo on OSX works (as in it can be mounted) - the problem is only if it is created on Ubuntu.

**Comment by yatesco** [comment]
Attached is the debug log from Ubuntu - I am unsure how to get the debug build on OSX as I installed it via brew.

Do you need anything else from me?

[restic-debug.log.zip](https://github.com/restic/restic/files/76590/restic-debug.log.zip)

**Comment by fd0** [comment]
Oh, I see. You created a repository with a recent version of restic, compiled from the master branch. Then you tried to mount the repo on OS X with the released version 0.1.0. In the meantime, the index format has changed, so the version on OS X is unable to read the index. This fails, and the error message is printed.

So, the solution is to also use a recent version of restic on OS X. You can build one yourself the same way as you did on Ubuntu, https://github.com/restic/restic#build-restic

That's the solution for your immediate problem, I agree that the error message is unhelpful and could be improved.

We always try to be backwards compatible (especially regarding released versions), but that does not include forwards-compatibility ;)

**Comment by yatesco** [comment]
Well `restic version` reports "0.1.0" on both Ubuntu and OSX:

ubuntu: 
```
./restic version
debug enabled
restic 0.1.0 (v0.1.0-171-g3abff79)
compiled at 2016-01-03 13:35:52 with go1.5.2```

OSX: 
```
restic version
restic 0.1.0
compiled at 2015-12-22 00:35:57 with go1.5.2
```

Git log on Ubuntu is:
```
commit 3abff7928c614f794f00347061fe70563af7252f
Merge: 55d9c5f 2976df2
Author: Alexander Neumann <alexander@bumpern.de>
Date:   Sun Dec 20 20:45:18 2015 +0100

    Merge pull request #375 from restic/fix-suid
    
    Backup and restore setuid/setgid/sticky bits
```

I don't know how to do `git log` on homebrew unfortunately.

**Comment by fd0** [comment]
Indeed, the base version is 0.1.0 in both cases, but the version on Ubuntu is 171 commits further advanced, as the string `0.1.0` is followed by `-171`. After release, development continued from that version on, so it is still included in the base version string.

**Comment by yatesco** [comment]
Ah, the yak that is versioning :-). May I gently suggest that this sort of incompatibility should be a trigger for a different version.

Happy for this to be closed?

**Comment by fd0** [comment]
I'm happy, please close. I'm still not completely happy with the versioning scheme and I'll probably release 0.2.0 soon so that it's more obvious. When restic development has settled a bit I'll change the text of the readme and the manual so that user's are instructed to compile and use the latest release instead of the master branch (which should always be stable and safe to use, but may contain bugs).

**Comment by yatesco** [comment]
Versioning with high velocity is a pain - either you don't version enough leading to this or you version too much leading to 0.3423.1 which is just silly. Good luck, and I look forward to seeing how restic progresses!

(Happy new year).

**Comment by fd0** [comment]
Thanks, you too a happy new year! Thanks for trying restic, and please keep reporting bugs, even small documentation errors or unclear error messages ;)
