### ISSUE TITLE
README add code quality badge

### ISSUE THREAD

**Issue by xor-gate** [restic/restic#379]
Go report card exposes code quality badge for sake of fancyness and maturity here:
http://goreportcard.com/report/restic/restic

With following markdown for the README.md:

```
[![ReportCard][ReportCard-Image]][ReportCard-Url]

[ReportCard-Url]: http://goreportcard.com/report/restic/restic
[ReportCard-Image]: http://goreportcard.com/badge/restic/restic
```

**Comment by fd0** [comment]
Oh wow, it gives the restic source code an A+ score. I'll add that immediately. :)

**Comment by xor-gate** [comment]
Hehe, it is certainly not bad at all :_)

**Comment by fd0** [comment]
Are you by chance attending 32c3 in Hamburg?

**Comment by xor-gate** [comment]
No to bad not :_) I went a few years ago to CCC camp.

**Comment by fd0** [comment]
Ah, bummer ;)
