### ISSUE TITLE
Merge multiple snapshots into one OR Append operation 

### ISSUE THREAD

**Issue by samuelxhu** [restic/restic#3792]
I am faced with a task using restic as a archive solution. The use case is as follows: The main disk is on SSD, fast but with limited capacity, and a second HDD on USB as an archive disk. The idea is to (from time to time or on a schedule) store (archive) data on SSD to HDD, and delete those already-archived data on SSD to leave space for new data.

Thus, is there a way to merge multiple snapshots into one (Archive)?  or is it possible for restic to support archive or append operation without breaking back compatibility?

thanks a lot in advance

**Comment by greatroar** [comment]
This would be possible in theory given restic's file formats, but the question is, why do you think you need it? If disk space is the main concern, restic's deduplication should already take care of that: the same file written to the same repository twice will only get stored once, even if it's part of two distinct snapshots.

**Comment by MichaelEischer** [comment]
That sounds similar to what #3405 is proposing.

**Comment by samuelxhu** [comment]
My use cas is to archive, therefore I would like to have all files on the
last snapshot.

**Comment by MichaelEischer** [comment]
Then why don't you just create a snapshot that includes all relevant paths, that is in your case both disks?

**Comment by greatroar** [comment]
I was assuming the restic repository was on the USB disk. Is that not correct?

**Comment by samuelxhu** [comment]
Indeed, the intended archive disk on a USB3 disk or a remote S3 bucket.

The problem with multiple snapshots as archives is as follows: user has to
search for files among tens of such snapshots, which is cumbersome.

**Comment by greatroar** [comment]
This could be solved by #3405. Alternatively, it can be solved by a view in restic mount that combines snapshots, or even a union mount on top of restic mount.

(It is stretching restic's intended purpose from backup to archiving, but I admit I would find this useful too...)

**Comment by MichaelEischer** [comment]
Closing in favor of https://github.com/restic/restic/issues/4804 .
