### ISSUE TITLE
Fails to backup when --exclude-file argument is used --> Fatal: unable to save snapshot: snapshot is empty

### ISSUE THREAD

**Issue by navilg** [restic/restic#3793]
Output of `restic version`
--------------------------
restic 0.13.1 compiled with go1.18 on linux/amd64

How did you run restic exactly?
-------------------------------
restic -r dest --tag laptop-backup --exclude-file /tmp/restic-backup/exclude-file backup source1 source2

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Local filesystem in laptop

Expected behavior
-----------------
Snapshot should have been created successfully

Actual behavior
---------------
Snapshot fails to create with below error message

```
Fatal: unable to save snapshot: snapshot is empty
```

```
navi@NavratanElementaryOS:/media/navi/Storage/MyWorkspace/projects/restic-backup$ restic -r dest --tag laptop-backup --exclude-file /tmp/restic-backup/exclude-file backup source1 source2
enter password for repository: 
repository 40213758 opened successfully, password is correct
using parent snapshot 98819434
Fatal: unable to save snapshot: snapshot is empty

navi@NavratanElementaryOS:/media/navi/Storage/MyWorkspace/projects/restic-backup$ cat /tmp/restic-backup/exclude-file
.cache
.local
lost+found/
*~
$*/
.config
.*
.*/
$RECYCLE.bin
```

Steps to reproduce the behavior
-------------------------------
1. Create a file FILENAME which contains patterns to exclude.
2. Run backup command (After repo is already initialized).
```
restic -r REPOPATH --exclude-file FILENAME backup source1
```

Content of exlude-file
```
.cache
.local
lost+found/
*~
$*/
.config
.*
.*/
$RECYCLE.bin
```

Do you have any idea what may have caused this?
-----------------------------------------------
I am not sure. It is working fine using restic 0.9.6 compiled with go1.12.12 on linux/amd64

Do you have an idea how to solve the issue?
-------------------------------------------
No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It helps me everyday :)

**Comment by MichaelEischer** [comment]
`$*/` tries to resolve the environment variable `*` and when that is not set, it expands to the pattern `/` which excludes everything. Hence, the empty snapshot. You must escape dollar signs as `$$`.

Before restic 0.11.0 the excludes check ignored `/` patterns which is no longer the case and was essentially a bug.
