### ISSUE TITLE
hash for pw

### ISSUE THREAD

**Issue by erwin66lindemann** [restic/restic#3794]
Hi, 

thanks for this great tool.

Output of `restic version`
--------------------------

restic 0.13.1 (v0.13.0-186-g1dd4b9b6) compiled with go1.15.14 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Is it possible to work with hashes for the password instead of cleartext (on console or in ENV)?
Something like that: 

echo -n password | openssl md5

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
yepp, was looking looooong time for a tool like restic. thx.

Sorry for possible short type of this feature request, my _first_ posting on github. :-)

cu
erwin66lindemann

**Comment by MichaelEischer** [comment]
If you hash your password and use the hash instead, then the hash becomes the new password which has the same problem again. So you won't gain anything.

Why not store the password in a file and use it via `--password-file` or read it from some external command using `--password-command`?
