### ISSUE TITLE
Backup fails on S3 OpenStack (client.PutObject: The XML you provided was not well-formed or did not validate)

### ISSUE THREAD

**Issue by ivomarino** [restic/restic#3797]
Running `restic 0.13.1` with OpenStack S3 I get `client.PutObject: The XML you provided was not well-formed or did not validate against our published schema` on some files like:

```
Save(<data/6fdfd1fe9d>) returned error, retrying after 4.506218855s: client.PutObject: The XML you provided was not well-formed or did not validate against our published schemata/craft-content/content/migration/main/_mg_6277_d.jpg

Fatal: unable to save snapshot
ERROR: backup failed
```
If I exclude `/craft-content/content/migration/main` everything is fine, I also backed up around 60GB of other data to this S3 bucket on OpenStack so I presume the issue comes up only with some specific files. Any suggestions on this or similar behavior on other S3 solutions like AWS or minio? Thanks for support

**Comment by MichaelEischer** [comment]
Can you provide the full log output of restic? Does the error also show up with older restic versions? Can you try whether the current master branch of restic still has the problem (prebuilt binaries are available at https://beta.restic.net/?sort=time&order=desc)?

What seems odd is that this error is showing up for a data file. These always have a size up to 12MB and a seemingly random filename, so there's no way for the backend to distinguish between the data files. Especially there shouldn't be any connection to including / excluding a specific folder in the backup. I rather suspect that this is simply related to that specific folder containing lots of data (in terms of data to be uploaded).

> Any suggestions on this or similar behavior on other S3 solutions like AWS or minio?

So far you seem to be the first to encounter that error in combination with restic. That could also mean that we're seeming a problem with the OpenStack S3 installation or your hardware here. 

Does the error show up repeatedly? As you mention "on some files", please provide the corresponding logs.

**Comment by MichaelEischer** [comment]
Closing as this is likely a problem at the storage server and the requested information was not provided in a month.
