### ISSUE TITLE
virus alert

### ISSUE THREAD

**Issue by MrPalais** [restic/restic#3807]
windows amd64 exe : 

https://www.virustotal.com/gui/file/ea9817c49566d64e79ed4986ce0742d6aecdc25ed95d11fdab29786cdaf3c0b4

**Comment by fd0** [comment]
Unfortunately this happens regularly, here's a possible explanation: https://forum.restic.net/t/restic-0-10-0-for-windows-and-jiangmin-false-positive/3135/2
