### ISSUE TITLE
Double escaped string in tree json format

### ISSUE THREAD

**Issue by aawsome** [restic/restic#3808]
Output of `restic version`
--------------------------
restic 0.13.1 (v0.13.0-147-g88a8701fb) compiled with go1.17.9 on linux/amd64
(but applies to older restic versions, too)

How did you run restic exactly?
-------------------------------
I have a dir with dirname 
`_!(!!cg"p!(}!}@"j!(k!|w"w!'''8!b!"p!''':!e@==`
 (no kidding) and run `restic backup` with a path that contains that dir.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local backend
(but should be independent from the backend)

Expected behavior
-----------------
According to the [JSON specification](https://datatracker.ietf.org/doc/html/rfc8259#section-7), I expect that the quotation marks are escaped and nothing else.
So, I would expect the tree to look like
```
"name":"_!(!!cg\"p!(}!}@\"j!(k!|w\"w!'8!b!\"p!':!e@=="
```

Actual behavior
---------------
`restic cat blob <TREE-ID>` gives:
```
{"nodes":[{"name":"_!(!!cg\\\"p!(}!}@\\\"j!(k!|w\\\"w!'8!b!\\\"p!':!e@==","type":"dir","mode":2147484141,"mtime":"2020-04-23T20:32:52.919484424+02:00","atime":"2020-04-23T20:32:52.919484424+02:00","ctime":"2020-04-23T20:32:52.919484424+02:00","uid":1000,"gid":1000,"user":"alex","group":"alex","inode":1323366,"device_id":2054,"content":null,"subtree":"7fb495dd7dab2a5d9251a19ef43aadb31b1b98c45f9614c3a9495b0c85ab42e7"}]}
```

Even worse, if you generate a tree object like 
```
{"nodes":[{"name":"_!(!!cg\"p!(}!}@\"j!(k!|w\"w!'8!b!\"p!':!e@==","type":"dir","mode":2147484141,"mtime":"2020-04-23T20:32:52.919484424+02:00","atime":"2020-04-23T20:32:52.919484424+02:00","ctime":"2020-04-23T20:32:52.919484424+02:00","uid":1000,"gid":1000,"user":"alex","group":"alex","inode":1323366,"device_id":2054,"content":null,"subtree":"7fb495dd7dab2a5d9251a19ef43aadb31b1b98c45f9614c3a9495b0c85ab42e7"}]}
```
(this is what rustic produces), and run a restic command , e.g.
`restic check`
you get the following error message:
```
check snapshots, trees and blobs
error for tree dd454271:apshots...
  Unquote: invalid syntax
[0:40] 100.00%  311 / 311 snapshots...
Fatal: repository contains errors
Command exited with non-zero status 1
```

Steps to reproduce the behavior
-------------------------------

see above

Do you have any idea what may have caused this?
-----------------------------------------------

The string seems to be escaped  two times. 
Reading JSON objects which are escaped seems to need double-escapes or the reading fails :disappointed: 

Do you have an idea how to solve the issue?
-------------------------------------------

No idea about the root cause.
However, I suggest to fix it when writing and make restic at least able to read correct json trees...

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Today restic only helped me with comparing it with my [rustic](https://github.com/rustic-rs/rustic) implementation.

**Comment by greatroar** [comment]
This is intended behavior (though not documented). On Unix/Linux/*BSD, except Mac, filenames are binary: they're byte strings with the only restriction that they may not contain / or NUL. E.g.,

```
$ touch $(echo -e "\xff")
```

produces a file with the valid name [0xFF]. But such names need to be quoted/encoded twice to become valid JSON, because JSON doesn't allow non-Unicode characters in its literal strings, even with escaping:

```
$ echo -e "\xff" | jq .
parse error: Invalid numeric literal at line 2, column 0
```

"\u00ff" is allowed, but is not the same, since that denotes "ÿ", or [0xC3,0xBF] in UTF-8.

The quoting rules are those of [strconv.Quote](https://pkg.go.dev/strconv#Quote), i.e., a subset of [Go string literals](https://go.dev/ref/spec#String_literals).

**Comment by aawsome** [comment]
You are right that the JSON escaping is not defined for non-unicode characters in a string.
So, yes, we need a solution for that problem. And escaping those character (before encoding to JSON) is actually a really good idea as the `\` character is not even allowed in a file name (at least on unix, IIRC).

But in my case this is a totally valid UTF-8 filename AND does not contain any `\`. So no need to quote, yet restic still quotes here. Instead of solving the problem it is over-solved adding unneeded complexity.
And when I read "Quote returns a double-quoted Go string literal representing s. The returned string uses Go escape sequences (\t, \n, \xFF, \u0100) for control characters and non-printable characters as defined by IsPrint. " this is another Go-specific solution, *sigh*. I know, I am biased as I'm developing rustic in Rust. But still, having language-specific things in an on-disc-format for a **backup** seems wrong to me!

Seeing #3311, I realize how weird this undocumented behavior actually is :sob:

**Comment by greatroar** [comment]
Quoting always isn't more complex than quoting sometimes and not quoting other times. You'd have to add an indicator that the string is quoted. Doable, but more complicated.

The Rust [enquote crate](https://docs.rs/enquote/latest/enquote/index.html) gets your example right:

```
extern crate enquote;

fn main() {
    let q = "_!(!!cg\\\"p!(}!}@\\\"j!(k!|w\\\"w!'8!b!\\\"p!':!e@==";
    println!("{}", enquote::unescape(q, None).unwrap());
}
```

It just doesn't know about \xff, which it treats as Unicode ÿ. If you don't have non-Unicode filenames, this looks like a good starting point.

**Comment by aawsome** [comment]
@greatroar Thanks for the link. But currently my main trouble is not unescaping, but to either implement escaping or generating a repo which causes restic to abort.

Moreover, I hope you agree that adding some escaping in order to allow non-Unicode filenames but not handling the case of non-Unicode filenames seems a bit strange :smile: 

So, If I decide to reimplement what restic is doing, I'l have to extend that or look for another suitable crate.

**Comment by aawsome** [comment]
Another issue IMO is that restic aborts when given a totally valid JSON tree - even in commands where the filename is not needed at all, like in `check` or `prune`. Maybe we should move the unescaping to the places where the filename is really needed, i.e. to commands like `restore`, `mount` or `ls` and maybe add some error handling there?

**Comment by MichaelEischer** [comment]
> Another issue IMO is that restic aborts when given a totally valid JSON tree - even in commands where the filename is not needed at all, like in `check` or `prune`. Maybe we should move the unescaping to the places where the filename is really needed, i.e. to commands like `restore`, `mount` or `ls` and maybe add some error handling there?

Most definitely not. This will just blow up in dozens of different ways and places. `check` is supposed to verify that a repository is readable, so it makes no sense to exclude filename decoding which can later on cause `restore` to fail.

`enquote::enquote` should be able to properly quote valid-utf8 filenames, although it won't be able to handle invalid utf8 (which is the whole reason for the quoting mess). Or just encode everything as `\xFF` or whatever. Btw, the quoting used by `strconv.Quote` looks an awful lot like the quoting style used in JSON, so it's not really that special.

> Moreover, I hope you agree that adding some escaping in order to allow non-Unicode filenames but not handling the case of non-Unicode filenames seems a bit strange
> 
> So, If I decide to reimplement what restic is doing, I'l have to extend that or look for another suitable crate.

Quoting everything is just much simpler, than having to implement two different cases. We're not going to change the filename quoting as this will just break tons of repositories without providing any measurable benefit (except for being different). So, if you want to stay compatible with restic, then you'll have to implement this quirk.
