### ISSUE TITLE
in webdav it doesn't work in config no_check_certificate = true

### ISSUE THREAD

**Issue by streikpc** [restic/restic#3818]
in webdav it doesn't work in config no_check_certificate = true

if it works in .BAT file like flag --no-check-certificate

also works as a variable
set RCLONE_NO_CHECK_CERTIFICATE=true

But it doesn't work, if you add a line in the conf file:
no_check_certificate = true

This as far as PC is concerned.

And of course, there is no way it will work with Android's RCX App.

**Comment by fd0** [comment]
Please fill out the [issue template](https://github.com/restic/restic/issues/new?assignees=&labels=&template=Bug.md) if you think you've found a bug, otherwise we can't help you. Thanks!
