### ISSUE TITLE
On backup, use file mtime to skip unmodified files.

### ISSUE THREAD

**Issue by viric** [restic/restic#382]
For the progress report of "restic backup" in MB/s, I understand that file mtime is not checked, to make faster decisions on whether a file changed or not. I imagine that all the files are read again from disk.

It'd be nice to be able to use the file modificaiton time (+ size + whatever stat() can provide) to skip reading the data again, and have much faster backups. Even if only with a non-default option.

**Comment by fd0** [comment]
This is already implemented. Unless you specify `--force` to the `backup` command, no files are read when the mtime hasn't changed.

I agree that the user interface is a bit misleading, as it counts the complete number of bytes to consider for backup, not the actual number that is read (or written to the repository, for that matter).

**Comment by viric** [comment]
aaah. So, if it were reading the actual data from disk, the speed would not be noticeable higher than in a backup from scratch, right?

**Comment by fd0** [comment]
That's correct.
