### ISSUE TITLE
All Backblaze-related commands simply hang with no output

### ISSUE THREAD

**Issue by noodlecollie** [restic/restic#3824]
Output of `restic version`
--------------------------
Originally:

```
restic 0.11.0 compiled with go1.15.4 on linux/amd64
```

I have since updated to:

```
restic 0.13.1 compiled with go1.18 on linux/amd64
```

The issue occurs on both versions.

How did you run restic exactly?
-------------------------------
```
export B2_ACCOUNT_ID=...
export B2_ACCOUNT_KEY=...
export RESTIC_PASSWORD=...
restic -r b2:mybucket:mypath/ snapshots
```

Alternatively, for a normal backup:

```
restic -r b2:mybucket:mypath/ backup /path/to/folder/ 2>&1
```

NB. If I haven't exported the Backblaze variables then the command simply fails with `Fatal: unable to open B2 backend: Account ID ($B2_ACCOUNT_ID) is empty`. This implies to me that the issue is to do with the Backblaze operation itself, during or after authentication.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
A list of snapshots for the repo should be displayed.

Actual behavior
---------------
No output whatsoever. The command just hangs until it is manually terminated.

Steps to reproduce the behavior
-------------------------------
Steps above.

Do you have any idea what may have caused this?
-----------------------------------------------
Not sure - everything was working fine before for a few months, but now no backup commands regarding my B2 bucket seem to work. I don't have anything set up for any services other than Backblaze.

Do you have an idea how to solve the issue?
-------------------------------------------
Nope, I'm very new to this.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Having set restic up as a daily backup script for my Linux desktop has been a great source of comfort, because (usually) I don't need to worry about it at all!

**Comment by noodlecollie** [comment]
Ah, `apt` only had `0.11` but I just learned about `restic self-update`. Unfortunately `0.13.1` exhibits the same behaviour.

**Comment by MichaelEischer** [comment]
Some common causes of that problem are outdated ca-certificates or some DNS filter which redirects some b2 urls.

If these are not the cause, then we need a debug log, as described in: https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs . The log will probably contains lots of requests from restic to B2 and the replies. The interesting parts are probably the first few requests. Make sure to remove the `Authorization` header as it contains credentials.

**Comment by noodlecollie** [comment]
I've followed the instructions for building with debug support, and the issue seems to be that getting a config file returns `EOF` repeatedly (these messages seem to just loop forever):

```
2022/07/16 19:31:50 restic/global.go:643	main.parseConfig	1	opening b2 repository at b2.Config{AccountID:"...", Key:"**redacted**", Bucket:"...", Prefix:"...", Connections:0x5}
2022/07/16 19:31:50 b2/b2.go:47	b2.Open	1	cfg b2.Config{AccountID:"...", Key:"**redacted**", Bucket:"...", Prefix:"...", Connections:0x5}
2022/07/16 19:31:50 debug/round_tripper_debug.go:108	debug.loggingRoundTripper.RoundTrip	1	------------  HTTP REQUEST -----------
GET /b2api/v1/b2_authorize_account HTTP/1.1
Host: api.backblazeb2.com
User-Agent: blazer/0.5.3
Authorization: **redacted**
X-Blazer-Method: b2_authorize_account
X-Blazer-Request-Id: 1
Accept-Encoding: gzip


2022/07/16 19:31:50 debug/round_tripper_debug.go:125	debug.loggingRoundTripper.RoundTrip	1	------------  HTTP RESPONSE ----------
HTTP/1.1 200 
Content-Length: 744
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json;charset=UTF-8
Date: Sat, 16 Jul 2022 18:31:49 GMT


2022/07/16 19:31:50 debug/round_tripper_debug.go:108	debug.loggingRoundTripper.RoundTrip	1	------------  HTTP REQUEST -----------
POST /b2api/v1/b2_list_buckets HTTP/1.1
Host: api002.backblazeb2.com
User-Agent: blazer/0.5.3
Content-Length: 91
Authorization: **redacted**
X-Blazer-Method: b2_list_buckets
X-Blazer-Request-Id: 2
Accept-Encoding: gzip


2022/07/16 19:31:51 debug/round_tripper_debug.go:125	debug.loggingRoundTripper.RoundTrip	1	------------  HTTP RESPONSE ----------
HTTP/1.1 200 
Content-Length: 715
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json;charset=UTF-8
Date: Sat, 16 Jul 2022 18:31:50 GMT


2022/07/16 19:31:51 b2/b2.go:238	b2.(*b2Backend).Stat	1	Stat <config/>
2022/07/16 19:31:51 debug/round_tripper_debug.go:108	debug.loggingRoundTripper.RoundTrip	1	------------  HTTP REQUEST -----------
HEAD /file/.../.../config HTTP/1.1
Host: f002.backblazeb2.com
User-Agent: blazer/0.5.3
Authorization: **redacted**
X-Blazer-Method: b2_download_file_by_name
X-Blazer-Request-Id: 3


2022/07/16 19:31:51 debug/round_tripper_debug.go:115	debug.loggingRoundTripper.RoundTrip	1	RoundTrip() returned error: EOF
2022/07/16 19:31:52 debug/round_tripper_debug.go:108	debug.loggingRoundTripper.RoundTrip	1	------------  HTTP REQUEST -----------
HEAD /file/.../.../config HTTP/1.1
Host: f002.backblazeb2.com
User-Agent: blazer/0.5.3
Authorization: **redacted**
X-Blazer-Method: b2_download_file_by_name
X-Blazer-Request-Id: 4


2022/07/16 19:31:52 debug/round_tripper_debug.go:115	debug.loggingRoundTripper.RoundTrip	1	RoundTrip() returned error: EOF
2022/07/16 19:31:53 debug/round_tripper_debug.go:108	debug.loggingRoundTripper.RoundTrip	1	------------  HTTP REQUEST -----------
HEAD /file/.../.../config HTTP/1.1
Host: f002.backblazeb2.com
User-Agent: blazer/0.5.3
Authorization: **redacted**
X-Blazer-Method: b2_download_file_by_name
X-Blazer-Request-Id: 5


2022/07/16 19:31:53 debug/round_tripper_debug.go:115	debug.loggingRoundTripper.RoundTrip	1	RoundTrip() returned error: EOF
```

**Comment by MichaelEischer** [comment]
Which IP does `f002.backblazeb2.com` resolve to? (e.g. check using `host f002.backblazeb2.com`). What happens if you run `curl -v https://f002.backblazeb2.com`?

**Comment by noodlecollie** [comment]
Looks like there is a valid IP:

```
$ host f002.backblazeb2.com
f002.backblazeb2.com has address 81.99.162.48
f002.backblazeb2.com has IPv6 address 2a02:8801:200:1::1
```

As for cURL, what happens isn't quite clear to me:

```
$ curl -v https://f002.backblazeb2.com
*   Trying 81.99.162.48:443...
* Connected to f002.backblazeb2.com (81.99.162.48) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, close notify (512):
* error:140943E8:SSL routines:ssl3_read_bytes:reason(1000)
* Closing connection 0
curl: (35) error:140943E8:SSL routines:ssl3_read_bytes:reason(1000)
```

**Comment by MichaelEischer** [comment]
`host 81.99.162.48` looks like something redirected the DNS lookup. Judging for the reverse hostname it looks like your ISP has hijacked the DNS lookup. Oh, and for me B2 does not return an IPv6 address.

**Comment by noodlecollie** [comment]
Does this mean that if I point my machine to a different DNS server, it could be a workaround for the problem? I have no idea why Virgin would have changed the DNS lookup...

**Comment by noodlecollie** [comment]
OK, I've confirmed that if I connect via a VPN, the `snapshot` command does go through. It seems Virgin is blocking that DNS name for some reason. I have no idea why, but it definitely shouldn't be happening, so I'll get onto their customer complaints line next week. Thanks for helping debug.

**Comment by MichaelEischer** [comment]
> It seems Virgin is blocking that DNS name for some reason

It's probably some "Web safety" feature. Although blocking a cloud storage provider for probably a few malicious files is a bit extreme. But it's unfortunately not the first issue regarding B2 where an excessive DNS block turned out to be the problem.
