### ISSUE TITLE
Rework backend interface

### ISSUE THREAD

**Issue by fd0** [restic/restic#383]
During development for switching to a new S3 library (see #366) I found several bugs in the library. These were uncovered by the tests we already have in place for backends, this shows that we have adequate tests.

Unfortunately, using libraries with advanced functions that e.g. return io.ReaderAt or similar complex interfaces (in regard to behavior) means that we need to implement extensive testing and run that on Travis for every commit and PR. For S3, this was possible due to the availability of a server implementation (minio), but this may not be the case for other services, e.g. Google Drive.

In order to reduce the complexity needed for each backend (e.g. having to build something that implements the `backend.Blob` interface for each backend), I propose radically simplifying the `Backend` interface.

Currently, it looks as follows:

```go
type Backend interface{
	// Location returns a string that specifies the location of the repository,
	// like a URL.
	Location() string

	// Delete the complete repository.
	Delete() error

	// Create creates a new Blob. The data is available only after Finalize()
	// has been called on the returned Blob.
	Create() (Blob, error)

	// Get returns an io.ReadCloser for the Blob with the given name of type t.
	Get(t Type, name string) (io.ReadCloser, error)

	// GetReader returns an io.ReadCloser for the Blob with the given name of
	// type t at offset and length.
	GetReader(t Type, name string, offset, length uint) (io.ReadCloser, error)

	// Test a boolean value whether a Blob with the name and type exists.
	Test(t Type, name string) (bool, error)

	// Remove removes a Blob with type t and name.
	Remove(t Type, name string) error

	// Close the backend
	Close() error

	// List returns a channel that yields all names of blobs of type t in
	// lexicographic order. A goroutine is started for this. If the channel
	// done is closed, sending stops.
	List(t Type, done <-chan struct{}) <-chan string
}

type Blob interface {
	io.Writer

	// Finalize moves the data blob to the final location for type and name.
	Finalize(t Type, name string) error

	// Size returns the number of bytes written to the backend so far.
	Size() uint
}
```

This leads to several implementations of the `Blob` interface for each backend, although the code looks similar.

I propose updating the interface to the following:
```go
// Handle is used to store and access data in a backend.
type Handle struct {
	Type Type
	Name string
}

type Backend interface{
	// Location returns a string that specifies the location of the repository,
	// like a URL.
	Location() string

	// Delete the complete repository.
	Delete() error

	// Put stores data in the backend.
	Put(h Handle, data []byte) error

	// Get returns the data stored in the backend at offset. At most, len(p)
	// bytes are fetched. Returned is the number of bytes read, and io.EOF
	// error when all data has been read.
	Get(h Handle, offset int, p []byte) (int, error)

	// Test value whether a Blob with the name and type exists.
	Test(h Handle) (bool, error)

	// Remove removes a Blob with type t and name.
	Remove(h Handle) error

	// Close closes open connections to servers used by the backend.
	Close() error

	// List returns a channel that yields all names of blobs of type t. A
	// goroutine may be started for this. If the channel // done is closed,
	// sending stops.
	List(t Type, done <-chan struct{}) <-chan string
}
```

This contains three changes:
 * Let `List()` return the IDs in an arbitrary order.
 * Remove the ambiguity with `Get`/`GetReader` by only providing one method.
 * Pass data between restic and the backend implementation only in byte slices managed by restic.

The last point should make sure that backends can be implemented much easier, since all the buffer handling is done in one place and for all backends.

Thoughts? @fw42

**Comment by fd0** [comment]
Having the data in a `[]byte` would allow adding retry logic independent of the backup to restic. Since we have the buffer with the data in memory, we can easily try again (without having to rewing some reader or so).

**Comment by bchapuis** [comment]
Looks like a great idea for simplifying the backend. I just wonder what would be the impact on memory consumption since blobs have an average size of 512KB.

**Comment by fd0** [comment]
At the moment, all blobs are buffered in memory somewhere anyway.. but I'll do benchmarks before/after.

**Comment by fd0** [comment]
Hm, the only bad thing about this interface is that we can't (from the perspective of restic) get any information about a transfer before it was completed. I'd like to have a user interface that displays the current transfer rate, that's hard to do with this interface. Suppose we only have small upstream bandwidth, so that saving a typical 4MiB pack file takes 10 seconds, then we only get notified once `Put()` returns, which takes 10 seconds. On the other hand, having just one operation allows backends to save the data in an efficient way (in contrast to only ever giving really small buffers of a few KiB to save).

I don't have any idea on how to improve the situation right now.

**Comment by fd0** [comment]
The new interface also leaves all buffer management to restic, so backends don't have to bother with it.

**Comment by fd0** [comment]
Oh, I just realised: Having such an interface does not allow reading only the header of a pack file, because we have no possibility to get the file size. This needs to be added, maybe by renaming `Test()` to `Stat()` with the following signature:
```go
type Backend interface {
    // Stat returns information about the Blob with the name and type. When the blob does not exist, an error is returned.
    Stat(h Handle) (os.FileInfo, error)
}
```

**Comment by fd0** [comment]
So, this is done. The final interface looks like this now:
```go
// Backend is used to store and access data.
type Backend interface {
	// Location returns a string that describes the type and location of the
	// repository.
	Location() string

	// Test a boolean value whether a Blob with the name and type exists.
	Test(t Type, name string) (bool, error)

	// Remove removes a Blob with type t and name.
	Remove(t Type, name string) error

	// Close the backend
	Close() error

	Lister

	// Load returns the data stored in the backend for h at the given offset
	// and saves it in p. Load has the same semantics as io.ReaderAt.
	Load(h Handle, p []byte, off int64) (int, error)

	// Save stores the data in the backend under the given handle.
	Save(h Handle, p []byte) error

	// Stat returns information about the blob identified by h.
	Stat(h Handle) (BlobInfo, error)
}

// Lister implements listing data items stored in a backend.
type Lister interface {
	// List returns a channel that yields all names of blobs of type t in an
	// arbitrary order. A goroutine is started for this. If the channel done is
	// closed, sending stops.
	List(t Type, done <-chan struct{}) <-chan string
}

// Deleter are backends that allow to self-delete all content stored in them.
type Deleter interface {
	// Delete the complete repository.
	Delete() error
}

// BlobInfo is returned by Stat() and contains information about a stored blob.
type BlobInfo struct {
	Size int64
}
```

**Comment by fd0** [comment]
And I took the opportunity to do a lot of cleanup. :)
