### ISSUE TITLE
forget `--keep-parent` option

### ISSUE THREAD

**Issue by kaovilai** [restic/restic#3832]
Currently forget commands proceed to delete any snapshot ID specified.
https://github.com/restic/restic/blob/dba47d29d58813c9d3f523b9e3dd5ece111f1c57/cmd/restic/cmd_forget.go#L143-L146

There should be an option to prevent snapshot ID from being deleted if it is a parent to another snapshot.

Output of `restic version`
--------------------------

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by aawsome** [comment]
Just wondering if your reason to ask for this feature is the following: You fear that if the parent is removed, then the snapshots depending on the this parent will be incomplete after pruning?

In that case, please read the documentation about deduplication and restic storing only full backups. No need to fear, `restic prune` never removes any data which is still needed for any of the present snapshots. (The `parent` snapshot is mainly an informative field and not used).

**Comment by kaovilai** [comment]
> You fear that if the parent is removed, then the snapshots depending on the this parent will be incomplete after pruning?

Correct. Thanks for the clarification.
