### ISSUE TITLE
Notification of new releases

### ISSUE THREAD

**Issue by yatesco** [restic/restic#384]
How can I be notified of new releases? I don't want to track master, rather I want to track 'released' versions. I also don't want to skip any versions (so any repository upgrades are less likely to fail).

Other than regularly checking the tags in the repo, how can I be notified that v0.2.0 is out (for example)?

Thanks!

**Comment by fd0** [comment]
If you have an RSS reader, you can subscribe the blog at https://restic.github.io/blog/

I'll add a post there when a new version is released.

**Comment by fd0** [comment]
In addition, you can subscribe the RSS feed for the releases, as described here http://stackoverflow.com/a/20840694

https://github.com/restic/restic/releases.atom

**Comment by yatesco** [comment]
Ah OK - my github-fu is lacking :-).
