### ISSUE TITLE
`sftp` backend strips leading slash (`/`) from target directory

### ISSUE THREAD

**Issue by panlinux** [restic/restic#3843]
Output of `restic version`
--------------------------
`restic 0.12.1 compiled with go1.17 on linux/amd64`

UPDATE: just tried with `restic 0.13.1 compiled with go1.18 on linux/amd64` from the Releases page, same behavior.

How did you run restic exactly?
-------------------------------
```
$ restic init -r sftp://andreas@pi4.lowtech:/storage/backups/nsnx-restic
enter password for new repository: 
enter password again: 
created restic repository 359ea679f9 at sftp://andreas@pi4.lowtech:/storage/backups/nsnx-restic

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Normal ssh server on a raspberry pi4 hardware running ubuntu 22.04.

Expected behavior
-----------------
I expected to see `/storage/backups/nsnx-restic` with restic data, like:
```
-rw-------   1 andreas andreas 155 Jul 31 20:28 config
drwxrwxr-x 258 andreas andreas 258 Jul 31 20:28 data
drwxrwxr-x   2 andreas andreas   2 Jul 31 20:28 index
drwxrwxr-x   2 andreas andreas   3 Jul 31 20:28 keys
drwxrwxr-x   2 andreas andreas   2 Jul 31 20:28 locks
drwxrwxr-x   2 andreas andreas   2 Jul 31 20:28 snapshots
```

Actual behavior
---------------
Instead of `/storage/backups/nsnx-restic` having the restic repository, it actually got created in the user's home directory:
```
andreas@pi4:~$ ls -la /home/andreas/storage/backups/nsnx-restic/
total 84
drwxrwxr-x   7 andreas andreas   8 Jul 31 20:28 .
drwxrwxr-x   3 andreas andreas   3 Jul 31 20:28 ..
-rw-------   1 andreas andreas 155 Jul 31 20:28 config
drwxrwxr-x 258 andreas andreas 258 Jul 31 20:28 data
drwxrwxr-x   2 andreas andreas   2 Jul 31 20:28 index
drwxrwxr-x   2 andreas andreas   3 Jul 31 20:28 keys
drwxrwxr-x   2 andreas andreas   2 Jul 31 20:28 locks
drwxrwxr-x   2 andreas andreas   2 Jul 31 20:28 snapshots
andreas@pi4:~$ ls -la /storage/backups/nsnx-restic/
total 18
drwx------   2 andreas andreas  2 Jul 31 20:13 .
drwxr-x---+ 13 root    root    13 Jul 31 19:52 ..
andreas@pi4:~$ 
```
sftp logs me in in the correct path:
```
andreas@nsnx:~$ sftp andreas@pi4.lowtech:/storage/backups/nsnx-restic
Connected to pi4.lowtech.
Changing to: /storage/backups/nsnx-restic
sftp> pwd
Remote working directory: /storage/backups/nsnx-restic
sftp> dir
sftp> cd /home/andreas/storage/backups/nsnx-restic/
sftp> dir
config     data       index      keys       locks      snapshots  
sftp> 
```

Steps to reproduce the behavior
-------------------------------

1. Initialize remote sftp repository in a path outside remote user's home
2. Use sftp to connect to the given path
3. Verify it's empty <-- that's the bug. Instead, the repository was created in `$HOME/<remote-path>`

Do you have any idea what may have caused this?
-----------------------------------------------
I googled, also searched the forum and existing issues about sftp, but none seem to be the above.

Do you have an idea how to solve the issue?
-------------------------------------------

Not  yet.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, local and remote backups are awesome, it's just the first time I'm using sftp and found this issue.

**Comment by panlinux** [comment]
I added debugging to the sftp server.

This is what I get when I do `restic init -r sftp://andreas@pi4.lowtech:/storage/backups/nsnx-restic`:
```
Jul 31 20:46:53 pi4 sftp-server[22198]: session opened for local user andreas from [10.10.1.118]
Jul 31 20:46:53 pi4 sftp-server[22198]: received client version 3
Jul 31 20:46:53 pi4 sftp-server[22198]: opendir "storage/backups/nsnx-restic/keys"
Jul 31 20:46:53 pi4 sftp-server[22198]: sent status No such file
Jul 31 20:46:53 pi4 sftp-server[22198]: opendir "storage/backups/nsnx-restic/key"
Jul 31 20:46:53 pi4 sftp-server[22198]: sent status No such file
Jul 31 20:46:53 pi4 sftp-server[22198]: lstat name "storage/backups/nsnx-restic/config"
Jul 31 20:46:53 pi4 sftp-server[22198]: sent status No such file
Jul 31 20:46:53 pi4 sftp-server[22198]: stat name "storage/backups/nsnx-restic/data"
Jul 31 20:46:53 pi4 sftp-server[22198]: sent status No such file
Jul 31 20:46:53 pi4 sftp-server[22198]: stat name "storage/backups/nsnx-restic"
Jul 31 20:46:53 pi4 sftp-server[22198]: sent status No such file
Jul 31 20:46:53 pi4 sftp-server[22198]: stat name "storage/backups"
Jul 31 20:46:53 pi4 sftp-server[22198]: sent status No such file
Jul 31 20:46:53 pi4 sftp-server[22198]: stat name "storage"
Jul 31 20:46:53 pi4 sftp-server[22198]: sent status No such file
Jul 31 20:46:53 pi4 sftp-server[22198]: mkdir name "storage" mode 0777
(...)
```
See how the leading `/` was removed from `/storage`.

Here I use just `sftp andreas@pi4.lowtech:/storage/backups/nsnx-restic`. The leading `/` isn't removed:
```
Jul 31 20:48:49 pi4 sftp-server[22401]: session opened for local user andreas from [10.10.1.118]
Jul 31 20:48:49 pi4 sftp-server[22401]: received client version 3
Jul 31 20:48:49 pi4 sftp-server[22401]: debug1: request 1: limits
Jul 31 20:48:49 pi4 sftp-server[22401]: realpath "."
Jul 31 20:48:49 pi4 sftp-server[22401]: debug1: request 2: sent names count 1
Jul 31 20:48:49 pi4 sftp-server[22401]: stat name "/storage/backups/nsnx-restic"
Jul 31 20:48:49 pi4 sftp-server[22401]: debug1: request 3: sent attrib have 0xf
Jul 31 20:48:49 pi4 sftp-server[22401]: realpath "/storage/backups/nsnx-restic"
Jul 31 20:48:49 pi4 sftp-server[22401]: debug1: request 4: sent names count 1
Jul 31 20:48:49 pi4 sftp-server[22401]: stat name "/storage/backups/nsnx-restic"
Jul 31 20:48:49 pi4 sftp-server[22401]: debug1: request 5: sent attrib have 0xf
(...)
```

**Comment by panlinux** [comment]
Hm, if I use two leading `/` characters, then it works. Something is stripping one.

First, showing nothing is there:
```
andreas@nsnx:~$ sftp andreas@pi4.lowtech:/storage/backups/nsnx-restic
Connected to pi4.lowtech.
Changing to: /storage/backups/nsnx-restic
sftp> dir
sftp> cd /home/andreas/storage
stat remote: No such file or directory
sftp> ^D
```

Now we init using two leading `/`:
```
andreas@nsnx:~$ restic init -r sftp://andreas@pi4.lowtech://storage/backups/nsnx-restic
enter password for new repository: 
enter password again: 
created restic repository ac2453f334 at sftp://andreas@pi4.lowtech://storage/backups/nsnx-restic

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
```
And the repository is created in the correct path under `/storage`:
```
andreas@nsnx:~$ sftp andreas@pi4.lowtech:/storage/backups/nsnx-restic
Connected to pi4.lowtech.
Changing to: /storage/backups/nsnx-restic
sftp> dir
config     data       index      keys       locks      snapshots  
sftp> cd /home/andreas/storage
stat remote: No such file or directory
sftp> ^D
```

Is this expected? I don't see the examples in https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp using two leading slashes.

**Comment by thegreatluke** [comment]
You don't have an sftp chroot setup by chance do you?

**Comment by panlinux** [comment]
I just tried with `0.13.1` and the same thing happens.

**Comment by greatroar** [comment]
This is [documented behavior](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#sftp):

> E.g., the repository /srv/restic-repo on [::1] (localhost) at port 2222 with username user can be specified as
>
>    `sftp://user@[::1]:2222//srv/restic-repo`
>
> Note the double slash: the first slash separates the connection settings from the path, while the second is the start of the path. To specify a relative path, use one slash.

For an absolute path, use two slashes. But in this simple case, you can also use the non-URL syntax: sftp:andreas@pi4.lowtech:/storage/backups/nsnx-restic. The URL syntax is really only needed to put literal IPv6 addresses in the remote specifier.

**Comment by panlinux** [comment]
Ah, thanks, I missed that in the docs..
