### ISSUE TITLE
restic 3.1 / minio 3.5Tb -> ETA 60:09:07

### ISSUE THREAD

**Issue by outbackdingo** [restic/restic#3847]
Im using restic 3.1 on local lan 1Gb ethernet agaist minio ... now i know using sftp with restic to the remote host, is actually very fast
but with minio ... it really feels like extremely super slow......

[13:39:36] 18.51%  15528568 files 671.251 GiB, total 54180535 files 3.542 TiB, 16 errors ETA 60:09:07

**Comment by MichaelEischer** [comment]
Please fill out the [issue template](https://raw.githubusercontent.com/restic/restic/master/.github/ISSUE_TEMPLATE/Bug.md). There is a typo in the restic verison, "restic 3.1" does not exist.

What storage does the minio instance use? You might want to try PR https://github.com/restic/restic/pull/3731 .

**Comment by fd0** [comment]
I'm closing this issue, we cannot do anything here but guess.
