### ISSUE TITLE
Add an option to provide a 512-bit key instead of a password and bypass key derivation

### ISSUE THREAD

**Issue by Slimevine** [restic/restic#3849]
Output of `restic version`
restic 0.13.1 compiled with go1.18.1 on linux/amd64

If I understand correctly, the way it works currently is:

1. The master (AES) key is generated randomly
2. Password is used to generate a helper key to decrypt the master key using scrypt with fixed options
3. Encrypted master key, along with scrypt options to generate the helper key  is stored in the repo

This setup is a good default but does not offer any control and requires to store the key in the repo (and even if there was an option to not store the key, you have to worry about storing it locally).

Consider this for advanced users:
1. Restic expects a 256-bit key for AES provided via command-line argument
2. You can generate the key using any KDF you want, with any config
3. You can memorize the options easily, along with the password and not store anything in the repo - and be able to recover it just by remembering the password and the options for key generator.

Would that be hard to implement? I may be way off, but on the surface it seems like it's just about adding the new argument to the commands and if statements to bypass the default mechanism to decrypt the master key and use the one provided instead. I understand that the integrity check algorithm also needs a key, in that case, if any extra keys are needed, they could be provided via command line argument too, unless they can be safely derived from the master key.

**Comment by aawsome** [comment]
See #2525 and the discussion within.

**Comment by Slimevine** [comment]
Thanks for linking it and your efforts to implement it.

I'd like to highlight here that my use is a little different than just storing the key outside the repo. I'm thinking about dynamically generating the key with Argon2 id - so all I need is to remember my password and Argon2 options, without storing anything and it being it as secure as it could be - the weakest link being either 256-bit AES key entropy or breaking Argon 2 hash with a quite strong password and heavy memory requirements (I'm not a crypto guy, please correct me if I'm wrong). So the improvement here would not be just that the master key is not stored in the repo, the master key would not have to be stored anywhere, even locally. This feature is special, because it offers great flexibility and many use cases, for the price of adding one feature.

By the way, are you aware of any simpler file encryption tools (but still implement authenticated encryption) that offer to pass the key directly? The data that I want to back up to the cloud is not huge, so I could get by without deduplication and just re-upload everything whenever it changes. Thanks.

**Comment by Slimevine** [comment]
I will admit that from security perspective it does not improve things by much. I figure that if I used a 256-bit key as the input password for Restic, being able to specify the key directly as suggested does not improve security, does it. I would guess it would be easier to break AES key directly than it would be to calculate scrypt for a 256-bit input.

Having the input password being used for encryption of the real master key in order to enable adding / removing keys without re-encrypting data is useful in the long term and I would personally not want to deprive myself from being able to use that option.

I guess that an improvement I ask for is to be able to input the 64 bytes (which is used to decrypt the master key and for Poly)  directly rather than deriving it from the password, while still having the master key encrypted in repo and being able to add / remove passwords / key.

**Comment by MichaelEischer** [comment]
> I figure that if I used a 256-bit key as the input password for Restic, being able to specify the key directly as suggested does not improve security, does it.

From what have described, just passing a 256bit key to restic would be about as secure as manually fiddling around with some key derivation function.

> **"add an option to pass a 512-bit key instead of a password and bypass key derivation"** so one could use their own key derivation or their own key, in a cleaner way.

I don't really see the use case, except for being slightly faster. On the downside it offers ample opportunity to shoot yourself in the foot. Bypassing the KDF was already rejected in #2525, so I'm closing this issue too.

**Comment by Slimevine** [comment]
I wish it existed but I agree that it's not critical. Thanks for your feedback.
