### ISSUE TITLE
Forget --keep-monthly 12 does not work? But it deleted the first young snapshot

### ISSUE THREAD

**Issue by Zesko** [restic/restic#3851]
```
$ restic version
restic 0.13.1 compiled with go1.18.1 on linux/amd64
```
--------------------------

I have two snapshots in my other disk:
1. snapshot ID: `cab37d23`, date: ` 2022-08-01 11:31:17`
2. snapshot ID: `3498ea9f`, date: ` 2022-08-05 12:10:30`

Today is August. both snapshots were created in August (each snapshot in its different day) 

I try to run ` restic forget --keep-monthly 12` 
```
$ sudo restic forget --keep-monthly 12

Applying Policy: keep 12 monthly snapshots
keep 1 snapshots:
ID        Time                 Host        Tags        Reasons           Paths
---------------------------------------------------------------------------------------
3498ea9f  2022-08-05 12:10:30  zesko       Zbackup     monthly snapshot  /btrfs/@
                                                                         /btrfs/@clouds
                                                                         /btrfs/@docker
                                                                         /btrfs/@home
---------------------------------------------------------------------------------------
1 snapshots

remove 1 snapshots:
ID        Time                 Host        Tags        Paths
---------------------------------------------------------------------
cab37d23  2022-08-01 11:31:17  zesko       Zbackup     /btrfs/@
                                                       /btrfs/@clouds
                                                       /btrfs/@docker
                                                       /btrfs/@home
---------------------------------------------------------------------
1 snapshots

[0:00] 100.00%  1 / 1 files deleted...

```
The first snapshot is not older than 1 month and was removed.

#### Expected behavior
-----------------

Both snapshots should not be removed if they are less than 12 snapshots and not older than 1 month.
That means I wanted to stay 12 snapshots in 1 month. That is my expectation.

#### Actual behavior
---------------

Oh, the first snapshot is not older than 1 month, but was removed too early by `restic forget --keep-monthly 12`

Do you have any idea what may have caused this?
-----------------------------------------------

I have no idea, maybe bug? 
Or I do not understand what does `--keep-monthly 12` mean?

**Comment by MichaelEischer** [comment]
Please have a look at https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy . `--keep-monthly 12` keeps one backup per month for the last 12 months that have snapshots. Your description rather sounds like you want to keep backups of the last 12 days?

**Comment by Zesko** [comment]
Ah, I understand now.

I want to keep any snapshots up to 1 year no matter how many snapshots.

**Comment by MichaelEischer** [comment]
Probably `--keep-within 365d` or `--keep-daily 365` or `--keep-within-daily 365d`. Please take a look at the documentation for these options.

**Comment by Zesko** [comment]
Thanks for the answer.

I have already read the document. I am a bit confused with options of `forget` because English is not my main language, sorry. 

`--keep-within 1y` is probably right choice for me
