### ISSUE TITLE
forget --keep-within(-*) Xw silently fails to parse and marks all backups for deletion

### ISSUE THREAD

**Issue by hraban** [restic/restic#3861]
Output of `restic version`
--------------------------

restic 0.13.1 compiled with go1.17.10 on darwin/amd64

How did you run restic exactly?
-------------------------------

```
$ restic forget --dry-run --keep-within-daily 2w
repository 2b048d5b opened successfully, password is correct
no policy was specified, no snapshots will be removed
```

```
$ restic forget --dry-run --keep-within 3000w
repository 2b048d5b opened successfully, password is correct
no policy was specified, no snapshots will be removed
```

Failure mode so far is OK because when it's the only policy, the result is NOP.

However, in combination with other policies, it gets worse:

```
$ restic forget --dry-run --keep-within-daily 2w --keep-within-hourly 1d
repository 2b048d5b opened successfully, password is correct
Applying Policy: keep hourly snapshots within 1d

....
```

N.B.: Only the keep hourly policy is applied! All backups >1d old are deleted.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
(irrelevant)

Expected behavior
-----------------

Parse the policy as "N weeks", or at least on failure fail the entire operation.

Actual behavior
---------------

Silently ignores the entire policy and continues with other policies, causing too many backups to be marked for deletion.

Steps to reproduce the behavior
-------------------------------

Try it on your own backup (don't forget `--dry-run`!) and look at the "applying policy" line.

Do you have any idea what may have caused this?
-----------------------------------------------

Parsing duration logic, probably somewhere in "https://github.com/restic/restic/blob/f0bb4f8708b1e09e09897463d70b5c89b20eec01/internal/restic/snapshot_policy.go"?

Do you have an idea how to solve the issue?
-------------------------------------------

1. Add unit tests
2. fix the parsing
3. optional: add a rule to fail the entire `forget` command if a policy was passed that evaluated to a NOP somehow. Ignoring policies is a pretty nasty failure mode when combined with other policies.

I tried to look at step 1 and add a new failing test, but couldn't figure out the `internal/restic/testdata/policy_keep_snapshots_*` file structure, or how to generate new fixtures for my test. :/ Sorry.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I use it a lot 👍 thanks. And thank god for `--dry-run` ;) good thing that it was mentioned in the docs, too:

> You can always use the `--dry-run` option of the `forget` command, which instructs restic to not remove anything but instead just print what actions would be performed.

- https://restic.readthedocs.io/en/latest/060_forget.html

amen, haha.

**Comment by rawtaz** [comment]
Week units are not supported in the policies, only years, months, days and hours are.

I've opened a PR #3862 that yields an error when the user specifies an unsupported unit.
