### ISSUE TITLE
Local Backend doesn't support connections option?

### ISSUE THREAD

**Issue by leadZERO** [restic/restic#3864]
Output of `restic version`
--------------------------
restic 0.13.1 compiled with go1.18.3 on darwin/arm64

How did you run restic exactly?
-------------------------------
% restic -o local.connections=16 backup /Volumes/XXXXXX
Fatal: option local.connections is not known
% env | grep RESTIC | sed -e 's/=.*//g'
RESTIC_PASSWORD
RESTIC_REPOSITORY

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local

Expected behavior
-----------------
It would be nice to use more than 2 simultaneous connections for local files going from SSD to SSD

Actual behavior
---------------
Limited to 2 connections

Steps to reproduce the behavior
-------------------------------
NA

Do you have any idea what may have caused this?
-----------------------------------------------
Not sure, I looked at the code, B2 supports the connections variable and Local looks to be registered the same way.

Do you have an idea how to solve the issue?
-------------------------------------------
Negative

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Love Restic for cloud backups! I do wish the backup gave the option to re-read the destination to confirm successful backup (dealing with some Pack ID mismatch errors). But I can fix that and submit a Feature Request separate from this.

**Comment by MichaelEischer** [comment]
This is already fixed by https://github.com/restic/restic/pull/3611 . The option is not yet available in a released version of restic (so you've essentially looked at the wrong source code version). Beta builds are available at https://beta.restic.net/?sort=time&order=desc .



> I do wish the backup gave the option to re-read the destination to confirm successful backup (dealing with some Pack ID mismatch errors).

That sounds exactly like https://github.com/restic/restic/issues/3684 .
