### ISSUE TITLE
Slow connection with HTTP/2

### ISSUE THREAD

**Issue by systemmonkey42** [restic/restic#3866]
Output of `restic version`
--------------------------
restic 0.13.1 compiled with go1.18 on linux/amd64

How did you run restic exactly?
-------------------------------
restic snapshots

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rest-server behind https proxy/ssl offloader with http/2 support

Expected behavior
-----------------
```
time restic snapshots
... lots of output ...
-----------------------------------------------------------------------------------------------------------
662 snapshots

real    0m1.331s
user    0m0.807s
sys     0m0.045s
```

Actual behavior
---------------
```
time restic snapshots
... lots of output ...
-----------------------------------------------------------------------------------------------------------
662 snapshots

real    0m31.110s
user    0m0.804s
sys     0m0.099s
```

Steps to reproduce the behavior
-------------------------------
Use RESTIC_REPOSITORY pointing to a proxy as an api-gateway for ssl-offloading with HTTP/2 support
eg `export RESTIC_REPOSITORY=rest:https://<user>:<password>:backup.domain.com/repository`

Do you have any idea what may have caused this?
-----------------------------------------------
This is an issue with GOLANG HTTP support since 1.17.3.

```
2022/08/13 17:42:24 restic/main.go:96   main.main   1   restic 0.13.1 (v0.13.0-359-gf0bb4f87) compiled with go1.18.3 on linux/amd64
2022/08/13 17:42:24 restic/global.go:690    main.open   1   parsing location rest:https://redacted/
2022/08/13 17:42:24 restic/global.go:673    main.parseConfig    1   opening rest repository at rest.Config{URL:(*url.URL)(0xc00014e900), Connections:0x5}
2022/08/13 17:42:24 debug/round_tripper.go:94   debug.loggingRoundTripper.RoundTrip 1   ------------  HTTP REQUEST -----------
HEAD /jingella/config HTTP/1.1^M
Host: archive.xippy.cf^M
User-Agent: Go-http-client/1.1^M
Accept: application/vnd.x.restic.rest.v2^M
Authorization: **redacted**^M
^M

2022/08/13 17:42:54 debug/round_tripper.go:111  debug.loggingRoundTripper.RoundTrip 1   ------------  HTTP RESPONSE ----------
HTTP/2.0 200 OK^M
Content-Length: 155^M
Content-Security-Policy: upgrade-insecure-requests^M
Date: Sat, 13 Aug 2022 07:42:24 GMT^M
X-Content-Type-Options: nosniff^M
^M

```
This shows a completely arbitrary 30 second delay between making the request, and receiving the response.

The same request using CURL completes in 200ms.   The api-gateway logs the request immediately (ie, as soon as it is made) but net/http waits 30 seconds before reporting the request complete to restic.

Do you have an idea how to solve the issue?
-------------------------------------------
Rebuilding restic with go 1.17.2 eliminates the issue completely.

```
restic version
restic 0.13.1 (v0.13.0-359-gf0bb4f87) compiled with go1.17.2 on linux/amd64
```

This issue occurs with 13.0 (built with go1.18) but not with 12.1 (built with go1.16.6)
This issue also occurs if I manually build with go1.19. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
always

**Comment by systemmonkey42** [comment]
This was resolved by upgrading the api-proxy (haproxy)

**Comment by rawtaz** [comment]
Thanks a lot for sharing the solution, that is always helpful!
