### ISSUE TITLE
Support many backups inside single s3 bucket

### ISSUE THREAD

**Issue by vshalts** [restic/restic#387]
Hi,
Can you add support of path prefix for s3 backup?

Number of buckets is limited.  At the same time it is useful to have backups with different policies/lifecycle rules/storage classes etc. For example I want some backups to go to Glacier, but other stay in Infrequent Access Storage Class. Also in Glacier it is better to not keep everything in single backup due recovery of big backup will cost a lot. So, better to split backups by topics (photos, projects, etc). It is low probability to have shared data between photos and projects, so there is no win to keep them in single backup.

I want something like:
```
$ restic -r s3://region_name/bucket_name/backup_prefix_path init
```
will create backup in bucket bucket_name under backup_prefix_path.
it should be enough to support all required functionality.

**Comment by fd0** [comment]
This is a good idea, thanks for bringing it up.

**Comment by haswalt** [comment]
I too like this idea. We've just found here that we don't have enough buckets to backup our system whilst evaluating Restic

**Comment by ckemper67** [comment]
I just wrote the code for this over the weekend while trying to improve the integration for GCS. 

Unfortunately those two changes may not be cleanly separated and I made a bunch of other changes at the same time. What is the best way to get these to you? Would a single pull request be ok or do you prefer me to tease those apart?

**Comment by fd0** [comment]
Thanks for stepping up, please create a PR just for one functionality, so we can review it properly.

**Comment by fd0** [comment]
#443 was merged a few minutes ago, it introduces custom prefixes for s3.
