### ISSUE TITLE
Restore only subtree of snapshot via <hash>:<subtree> syntax

### ISSUE THREAD

**Issue by uvulpos** [restic/restic#3871]
Output of `restic version`
--------------------------
0.9.4 (debian package + alpine image)

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
According to this [forum post](https://forum.restic.net/t/how-to-override-folder-with-backup/5336/5?u=uvulpos) I would like to have a possibility to restore just a subtree of my snapshot, in my case I have a structure like this (example)
```
| /data
| - | /changes
| - | - | /change01.txt
| - | - | /change02.txt
| - | /designs 
| - | - | /picture.png
| - | - | /logo.svg
```
The goal would be, that I can restore either everything without the data folder so I can override my folder (in case of emergency) or restore a subtree to another folder e.x. designs. I have not seen something like this in documentation. Currently I have to make a detour over `/tmp` folder which is not really good (imo) 

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Alex Weiss mentioned that a syntax like `restic restore <hash>:<subtree>` might be the solution. Seems like a good idea to me. But if you want to implement it with `--subtree=` this would be also fine for me 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic helps me to get a rather comfortable experience of implementing file backups in our project. I like the idea of the creator really much to make it repository likely and it feels familiar a little bit like git to me now. I think incremental backups is a difficult task to do but you do a great job 👍🏻

**Comment by JsBergbau** [comment]
Wouldn it be sufficient for your case to use `--exclude /data` like described here https://restic.readthedocs.io/en/latest/050_restore.html ? You can also combine with `--include` filter. Or am I getting something wrong?
