### ISSUE TITLE
local backend consistency

### ISSUE THREAD

**Issue by perillo** [restic/restic#389]
One of the primary features of a backup system is data safety, however in the documentation this aspect is not discussed.
I studied the source code and I find a possible bug in
https://github.com/restic/restic/blob/master/backend/local/local.go#L115

Close is not guaranteed to sync data to disc. I have not read the full code, however it seems that File.Sync is never called. Is this ok?

Here is an interesting reading about how hard is to ensure file consistency, with some patterns that may be useful for restic:
http://danluu.com/file-consistency/

**Comment by fd0** [comment]
Hey, thanks for raising this issue. I'll look into it, but it already smells like a bug :)

The repository design is described in [doc/Design.md](https://github.com/restic/restic/blob/master/doc/Design.md), did you already find it? There are some ideas already present, e.g. in regard to crash-resistance.

**Comment by perillo** [comment]
On Sat, Jan 16, 2016 at 11:55 AM, Alexander Neumann <
notifications@github.com> wrote:

> Hey, thanks for raising this issue. I'll look into it, but it already
> smells like a bug :)
>
> The repository design is described in doc/Design.md
> <https://github.com/restic/restic/blob/master/doc/Design.md>, did you
> already find it?
>

Yes.

> There are some ideas already present, e.g. in regard to crash-resistance.
>

The repository format is well designed, so it is robust.
However what I'm interested in is answers to these questions:

1) After I create a new snapshot, does restic guarantee that the backup is
"complete" (contains all the original data)?
2) After I restore a directory from a snapshot, does restic guarantee that
the restored data is "complete"?


Thanks

**Comment by fd0** [comment]
> 1) After I create a new snapshot, does restic guarantee that the backup is "complete" (contains all the original data)?

When the data is not modified during the course of the backup and the data is not even accessed (so that metadata like the atime is not changed), I'm confident that the data is stored in the backend. This can be checked by using `restic check --read-data`, so restic loads, checks and read all data from the repository. By computing the SHA256 hashes again it can then detect when data was stored incorrectly.

This is not perfect: Suppose the data is not correctly stored on disk (for a local backend), but the file's content is buffered in memory. In this case, the data wouldn't be read from disk and the error is not detected.

What exactly do you mean by "guarantee"? How would a program guarentee this (especially considering the hardness of the problem, as described in your link)?

> 2) After I restore a directory from a snapshot, does restic guarantee that the restored data is "complete"?

During restore, the meta data and the data is read from the repository. When an error occurs, restic is able to detect it on several layers, the storage-layer (filename is SHA256 hash) and the crypto layer (ciphertext is protected by a MAC). So as long as restic does not report an error, I'm certain that you'll end up with the same content again.

Does that count as a "guarantee"? Again, could you please elaborate?

**Comment by perillo** [comment]
On Sat, Jan 16, 2016 at 7:12 PM, Alexander Neumann <notifications@github.com
> wrote:

> 1) After I create a new snapshot, does restic guarantee that the backup is
> "complete" (contains all the original data)?
>
> When the data is not modified during the course of the backup and the data
> is not even accessed (so that metadata like the atime is not changed), I'm
> confident that the data is stored in the backend. This can be checked by
> using restic check --read-data, so restic loads, checks and read all data
> from the repository. By computing the SHA256 hashes again it can then
> detect when data was stored incorrectly.
>
> This is not perfect: Suppose the data is not correctly stored on disk (for
> a local backend), but the file's content is buffered in memory. In this
> case, the data wouldn't be read from disk and the error is not detected.
>
> What exactly do you mean by "guarantee"? How would a program guarentee
> this (especially considering the hardness of the problem, as described in
> your link)?
>

Please note that I have not read in detail the  paper
https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-pillai.pdf

Consider the case when you add a new file inside the repository.
Assuming you create a temporary file, call fsync when done (restic **does
not** do this) and then call rename.
There is a possibility that, in the event of a crash (after Close is
called, so restic can not detect it), the new file does not appear in the
directory.
It seems that fsync should be called **also** on the directory containing
the file.

If this happens, you may have a corruption that restic can not detect (?)

2) After I restore a directory from a snapshot, does restic guarantee that
> the restored data is "complete"?
>
> During restore, the meta data and the data is read from the repository.
> When an error occurs, restic is able to detect it on several layers, the
> storage-layer (filename is SHA256 hash) and the crypto layer (ciphertext is
> protected by a MAC). So as long as restic does not report an error, I'm
> certain that you'll end up with the same content again.
>
> Does that count as a "guarantee"? Again, could you please elaborate?
>

The problem, as with the repository, is that without calling fsync, close
returns without errors but at some time later you can have a disk crash.
During the restore, in addition to the directory problem, currently restic
may leave in the target directory an incomplete file, and the user **is
not** notified that the data has not been restored completely.

It would be great if there was a document describing the protocol used by
restic for writing to the backup repository **and** to filesystem during
restore.

The authors of the paper have implemented a tool called ALICE:
http://research.cs.wisc.edu/adsl/Software/alice/

**Comment by fd0** [comment]
Thanks for the interesting comments, I'll have a look. I'll leave this issue open until the TODO items are:
 * Figure out a process to create files in a local repository in a crash-safe way
 * Document it (code does not count)
 * Apply this to the restore code as well

**Comment by perillo** [comment]
On Tue, Jan 19, 2016 at 9:37 PM, Alexander Neumann <notifications@github.com
> wrote:

> Thanks for the interesting comments, I'll have a look. I'll leave this
> issue open until the TODO items are:
>
>    - Figure out a process to create files in a local repository in a
>    crash-safe way
>    - Document it (code does not count)
>    - Apply this to the restore code as well
>
>
Thanks!

I also suggest reading
https://www.usenix.org/sites/default/files/conference/protected-files/osdi14_slides_pillai.pdf
from slide #18 to #31 for a toy example.

**Comment by fd0** [comment]
In practice, our current approach (use `os.CreateFile` with `O_EXCL`) works quite well. I'm therefore closing this issue for now, please feel free to add further comments. Thanks!
