### ISSUE TITLE
Support for http proxy?

### ISSUE THREAD

**Issue by zyliu-credo** [restic/restic#3902]
Does restic support http proxy? Searched document and can't find any. It would help the following two situations:

* Any backend that uses http/https (such as S3-class backends);
* `self-update` in case the firewall requests so.

I would suggest the following interface of environment variables:
* `HTTP_PROXY_URL`
* `HTTP_PROXY_USERNAME`
* `HTTP_PROXY_PASSWORD`

For example, a squid server listening at 192.168.1.2 port 3128 with username "foo" and password "bar" would have environment:

```sh
HTTP_PROXY_URL=http://192.168.1.2:3128
HTTP_PROXY_USERNAME=foo
HTTP_PROXY_PASSWORD=bar
```

Empty USERNAME would mean no credentials needed.

**Comment by aawsome** [comment]
With the rclone backend, the standard proxy variables (`HTTP_PROXY`, `HTTPS_PROXY`) should be respected.

**Comment by zyliu-credo** [comment]
> 

Oh, I completely missed that. So that resolved the first one -- I guess we can always manually overwrite the binary file.

Thank you for the help!
