### ISSUE TITLE
restic to GCP hangs on large files

### ISSUE THREAD

**Issue by andy108369** [restic/restic#3903]
The issue is described in its full here https://github.com/vmware-tanzu/velero/issues/5251#issuecomment-1229141718

Please let me know if you need any additional data.

Restic version:

```
# /proc/<velero pid>/root/usr/bin/restic version
restic 0.13.1 compiled with go1.18 on linux/amd64
```

**Comment by MichaelEischer** [comment]
Judging from the discussion over at velero, the file in question has 4TB (yep, terabyte) and is extremely sparse. The only way to fix the performance for that file and avoid creating gigantic amounts of directory metadata would be to add support for reading sparseness information from the filesystem. This has been partially discussed in https://github.com/restic/restic/issues/79#issuecomment-115865389 and https://github.com/restic/restic/issues/79#issuecomment-216639040 . Fixing the metadata size problem would likely require a change of the repository format, which won't happen in the short-term. The same time frame applies to reading the sparseness information, unless cares enough to implement it.

**Comment by MichaelEischer** [comment]
It might be possible to improve the hashing and chunking performance for all zero chunks: these chunks always have the minimum blob length, such that we could simply check whether blobs of that length are all zero and then use the precomupted hash instead. That could improve the chunking performance for a sparse file by at least a factor 10 compared to now.

**Comment by andy108369** [comment]
Is there any quick workaround until then?
Would compressing a sparse file, say with pigz (gzip on steroids) before archiving do?

**Comment by MichaelEischer** [comment]
That might work, assuming that pigz can handle sparse files. You could also use GNU tar which has a `--sparse` option, maybe together with the `--rsyncable` option (which might help the deduplication a bit). As tar is uncompressed, that might work better in combination with restic.

**Comment by andy108369** [comment]
I haven't looked deep into it (am still a newbie in the restic world), is there a way to quickly plug `tar` command into `restic` so it'll `tar` during upload and untar during restore?

**Comment by MichaelEischer** [comment]
Hmm, we don't have hooks that can be called before and after backup or restore. It would be possible to pipe the output of `tar` directly into `restic backup --stdin`, which will create a snapshot containing only that single file.

**Comment by MichaelEischer** [comment]
I've opened #3914 to track storing  the precise location of sparse file sections. #3854 has been extended to include the optimization to speed up backing up a large sparse file.

**Comment by andy108369** [comment]
Looks like https://github.com/restic/restic/pull/3854 PR adds a support for `restore` operation only.
I think this issue should be still `open` as it is related to the `backup` part.

Ref. https://github.com/restic/restic/issues/3914

**Comment by MichaelEischer** [comment]
#3854 improves the backup speed of sparse regions to up to several GB/s. That should be enough to backup even a file with a few TB size in a reasonable timespan. Tracking the exact sparseness information is not necessary for basic sparseness support and thus is a different issue than #79.
