### ISSUE TITLE
Restic hangs on repository.(*Index).Finalize

### ISSUE THREAD

**Issue by davidrea** [restic/restic#3907]
Output of `restic version`
--------------------------

```
$ ./restic_0.14.0_windows_amd64.exe version
restic 0.14.0 compiled with go1.19 on windows/amd64
```

How did you run restic exactly?
-------------------------------
```
$ DEBUG_LOG=restic_log.txt ./restic_0.14.0_windows_amd64.exe -r  sftp://<me>@<server>:7387/home/restic-repo-tf1fs snapshots
debug log file restic_log.txt
debug enabled
<10 minutes or so>
<ctrl-c>signal interrupt received, cleaning up

$ DEBUG_LOG=restic_log.txt ./restic_0.14.0_windows_amd64.exe -r local:S:\restic-repo-tf1fs snapshots
debug log file restic_log.txt
debug enabled
<10 minutes or so>
<ctrl-c>signal interrupt received, cleaning up
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

I have tested with SFTP and local (mapped network drive) backends.

Expected behavior
-----------------

Display list of snapshots in repository.

Actual behavior
---------------

Hangs indefinitely (most of my tests have been 5-10 minutes, but I have let it run overnight with same result)

Steps to reproduce the behavior
-------------------------------

I created the repository and added backups routinely from (I believe) restic 0.8.3 under Ubuntu (Pop_os) 20.04. I'm attempting to access it under Windows 10 Pro. 

Do you have any idea what may have caused this?
-----------------------------------------------

Relevant contents of restic_log.txt:

```
<snip>
2022/08/30 08:07:08 backend/layout.go:139	backend.ParseLayout	1	parse layout string "" for backend at home/restic-repo-tf1fs
2022/08/30 08:07:08 backend/layout.go:99	backend.DetectLayout	1	detect layout at home/restic-repo-tf1fs
2022/08/30 08:07:08 backend/layout.go:117	backend.DetectLayout	1	found default layout at home/restic-repo-tf1fs
2022/08/30 08:07:08 backend/layout.go:163	backend.ParseLayout	1	layout detected: <DefaultLayout>
2022/08/30 08:07:08 sftp/sftp.go:145	sftp.Open	1	layout: <DefaultLayout>
2022/08/30 08:07:08 sftp/sftp.go:149	sftp.Open	1	using (0o600 file, 0o700 dir) permissions
2022/08/30 08:07:08 sftp/sftp.go:480	sftp.(*SFTP).Stat	1	Stat(<config/>)
2022/08/30 08:07:08 repository/index.go:404	repository.(*Index).Finalize	1	finalizing index
2022/08/30 08:17:35 restic/cleanup.go:60	main.CleanupHandler	66	signal interrupt received, cleaning up
```

Do you have an idea how to solve the issue?
-------------------------------------------

I'm happy to build/run with additional debug code in place, but I'm not a Go developer and would need to install the tools, etc. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I got some great advice in the Restic forums to upgrade to 0.14.0 and run with DEBUG_LOG enabled, thank you to MichaelEischer! Restic's snapshot listing and mounting capabilities will completely save my bacon (laptop went swimming) if I can manage to access this repository!

Edit: Spelling
Edit: Clarify hang duration

**Comment by MichaelEischer** [comment]
The debug log output `repository.(*Index).Finalize	1	finalizing index` is unlikely to be the culprit. My guess would be that restic is currently waiting for the repository to be typed in. That would at least be consistent with the debug log not containing anything related to loading the repository's key file.

Could you try to just type something and press enter to see what happens?

Based on the forum thread https://forum.restic.net/t/restic-hangs-on-finalizing-index/5381 you're calling restic from Mingw. Does it work correctly using cmd or Powershell?

**Comment by davidrea** [comment]
Thank you @MichaelEischer - running from Mingw was the culprit!

It was indeed waiting for input; the repository password. When I ran it from PowerShell, it worked perfectly. I had started out there but switched over to Mingw when working through sftp connection issues.
