### ISSUE TITLE
Piping mysqldump output to restic does not work anymore in 0.14.0

### ISSUE THREAD

**Issue by Alwaysin** [restic/restic#3916]
Output of `restic version`
--------------------------
Version not working:
```
$ /home/restic/bin/restic_0.14.0 version
restic 0.14.0 compiled with go1.19 on linux/amd64
```

Version working:
```
$ /home/restic/bin/restic_0.13.1 version
restic 0.13.1 compiled with go1.18 on linux/amd64
```

How did you run restic exactly?
-------------------------------

```
$ cat .pass
export REPO='rest:https://user:pass@server:8000/repo'
export RESTIC_PASSWORD=pass
$ source /home/restic/.pass
$ mysqldump  --opt --routines --events --triggers database | /home/restic/bin/restic_0.14.0 -r $REPO backup --tag daily_cron --tag database --stdin --stdin-filename database.sql
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
```
$ /usr/local/bin/rest-server --version
rest-server version rest-server 0.11.0 compiled with go1.17.6 on linux/amd64
```

Expected behavior
-----------------
With 0.13.1:
```
repository 155a8b46 opened successfully, password is correct

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 116.033 MiB

processed 1 files, 123.984 MiB in 0:32
snapshot 515c3633 saved
```

Actual behavior
---------------
With 0.14.0:
```
repository 155a8b46 opened (repository version 1) successfully, password is correct
mysqldump: Error 2013: Lost connection to server during query when dumping table `ADM_UTI` at row: 4932

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repository: 311 B (380 B stored)

processed 1 files, 355.115 KiB in 1:19
snapshot 2a1f5e03 saved
```

Steps to reproduce the behavior
-------------------------------

See `How did you run restic exactly?` section. I can constantly reproduce it: working with 0.13.1, not working with 0.14.0.

Do you have any idea what may have caused this?
-----------------------------------------------
No.

Do you have an idea how to solve the issue?
-------------------------------------------
No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, I use it for all our backups at work, it works very well!

**Comment by rawtaz** [comment]
Is the error message `mysqldump: Error 2013: Lost connection to server during query when dumping table `ADM_UTI` at row: 4932` always appearing with restic 0.14?

Can you try dumping the database to a file and then doing e.g. `cat thefile.sql | restic ...` to see if that works, just for isolation purposes?

**Comment by Alwaysin** [comment]
> Is the error message `mysqldump: Error 2013: Lost connection to server during query when dumping table `ADM_UTI` at row: 4932` always appearing with restic 0.14?

Yes. And never with 0.13.1.

> Can you try dumping the database to a file and then doing e.g. `cat thefile.sql | restic ...` to see if that works, just for isolation purposes?

When first dumping and doing the cat thing, the problem is not there anymore. But I find that it still takes a lot of time for a file that small (only dumping the database with mysqldump is taking less than 2sec)
With `time cat thefile.sql | restic ...`, the output is:
```
repository 155a8b46 opened (repository version 1) successfully, password is correct

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repository: 5.084 KiB (5.151 KiB stored)

processed 1 files, 123.983 MiB in 1:17
snapshot 0f5660f3 saved

real    1m18.032s
user    3m34.423s
sys     0m34.487s
```
I wonder if it is not struggling on a character or whatever, hence the timeout on the database.

When adding DEBUGLOG, I can see it seems to just hang out at some point:
```
2022/09/07 10:44:19 repository/index.go:585     repository.DecodeIndex  169     done
2022/09/07 10:45:27 repository/repository.go:680        repository.(*Repository).PrepareCache   1       prepare cache with 324 index files

```
I can provide the whole debug file if necessary.

**Comment by rawtaz** [comment]
I don't suppose you could provide the example .sql file? I tried the stdin feature locally with just a simple cat and it worked fine, so it would be great if we could reproduce it.

Perhaps if you're able to reproduce it with a minimal database dump that contains no sensitive information?

**Comment by Alwaysin** [comment]
Hmm, I've tried with a new repo and the problem does not reproduce but I don't know to what extent this can link to the problem. I noticed that the actual repo is very large (nearly 10To). After forgetting some old snapshots and pruning, trimming it down to 5To, it goes through, even with 0.14.0.

The `cat thefile.sql | restic ...`  is now way faster:
```
repository 155a8b46 opened (repository version 1) successfully, password is correct

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repository: 1.615 MiB (1.615 MiB stored)

processed 1 files, 123.955 MiB in 0:45
snapshot a2bef97d saved

real    0m46.610s
user    2m6.765s
sys     0m34.263s
```

So it seems to be a problem specific to large repos? Maybe there is some issues about it already.

**Comment by MichaelEischer** [comment]
> Hmm, I've tried with a new repo and the problem does not reproduce. I noticed that the actual repo is very large (nearly 10To). After forgetting some old snapshots and pruning, trimming it down to 5To, it now goes through with 0.14.0.

It is expected that running commands takes longer for larger repositories. restic always has to load the full repository index, which grows with the repository size and hence takes longer to load. Regarding mysqldump, it looks like there's a timeout of about one minute configured somewhere in the database.

But it looks like we have a performance regression regarding the index load time. My guess would be that this sanity check could be the culprit: https://github.com/restic/restic/blob/6c69f08a7b32747b1f8d463b20f424b369ec43fb/internal/repository/repository.go#L595

**Comment by Alwaysin** [comment]
Yes there definetly is something that makes it take longer in 0.14 and not in the previous version.

I'm willing to try any debug build if necessary.

**Comment by Alwaysin** [comment]
@MichaelEischer Thank you for your work!
I've just tested again with 0.14.0 and with the actual dev binary, and it went from 56sec down to 19sec on my ~210MB MySQL dump against my 5.6To repository.
That is a considerable improvement and I consider the issue resolved.

**Comment by MichaelEischer** [comment]
Thanks for testing, I'm happy to hear that the fix is even more effective than I've expected. There's actually potential to speed up the index iteration even further (another factor 10), but that requires more extensive changes. And it would only save a second or so for your use case.
