### ISSUE TITLE
Possibly incomplete failed lock error during backup

### ISSUE THREAD

**Issue by XLTechie** [restic/restic#3920]
### Output of `restic version`
--------------------------
`restic 0.14.0 compiled with go1.19 on linux/386`

### How did you run restic exactly?
-------------------------------
```
cd /
export B2_ACCOUNT_ID=XXX  B2_ACCOUNT_KEY=YYY
restic backup -r b2:my_repo:my_directory --verbose \
-p /root/backup.p --cleanup-cache --compression max \
--exclude var/log --exclude home/user/Private \
bin boot dev etc home initrd.img \
lib media opt root sbin selinux srv \
usr var vmlinuz
```

#### Output:

> open repository
> repository ZZZ opened (repository version 2) successfully, password is correct
> lock repository
> no parent snapshot found, will read all files
> load index files
> start scan on [bin boot dev etc home initrd.img lib media opt root sbin selinux srv usr var vmlinuz]
> start backup on [bin boot dev etc home initrd.img lib media opt root sbin selinux srv usr var vmlinuz]
> scan finished in 367.506s: 303815 files, 253.323 GiB
> Remove(<lock/cae9f1eac1>) returned error, retrying after 552.330144ms: Delete: b2_authorize_account: 401:
> [12:18:54] 19.68%  49348 files 49.852 GiB, total 303815 files 253.323 GiB, 0 errors ETA 50:15:55

### What backend/server/service did you use to store the repository?
----------------------------------------------------------------
B2 (Backblaze)

### Expected behavior
-----------------
An error with more helpful information about what's going wrong.

Also, some notice that the retry was successful, and the rest of the backup isn't just blithely tossing bits into a black hole.

### Actual behavior
---------------
Between four and 12 hours into the first backup, the following line appeared in the middle of the status output to the console:

```
Remove(<lock/cae9f1eac1>) returned error, retrying after 552.330144ms: Delete: b2_authorize_account: 401:
```

I can guess that "b2_authorize_account" is a file or lock generated from an API call (else why is it being "delete"d), but what should be after the final colon? It appears that some information is missing.

Presumably the retry was successful, because the backup continued...

Had I expected such an inconclusive error, I would have started with debug logging.

### Steps to reproduce the behavior
-------------------------------
Unknown. Will update if recurs.

### Do you have any idea what may have caused this?
-----------------------------------------------
Guesses: either a failure to capture a description or sufficient information about the error, a failure to display it to the user, or a generalized error reporting routine that wasn't setup for HTTP status codes only to be returned.

### Do you have an idea how to solve the issue?
-------------------------------------------
I do not know Go.

### Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is incredibly easy to use and start working with to do rather large scale cloud storage backups of servers and the like. I've been using it less than 48 hours, and am already quite fond of it. Thanks!

I was happy to see an open source project on Backblaze's list of available backup integrations.

**Comment by MichaelEischer** [comment]
> Also, some notice that the retry was successful, and the rest of the backup isn't just blithely tossing bits into a black hole.

The next restic release will print `operation successful after %d retries` (#2661). Restic retries requests up to 10 times and aborts the backup if an upload fails permanently.

> ```
> Remove(<lock/cae9f1eac1>) returned error, retrying after 552.330144ms: Delete: b2_authorize_account: 401:
> ```
> 
> I can guess that "b2_authorize_account" is a file or lock generated from an API call (else why is it being "delete"d), but what should be after the final colon? It appears that some information is missing.

`b2_authorize_account` is the B2 API call that failed, the filename is something starting with `cae9f1eac1`. The remaining information was either never returned by the B2 servers due to a temporary error or the library we use to access B2 lost it. Either way, failing to delete a lock file might require calling `unlock` manually, but is harmless otherwise.

In total, I don't think there's something here that requires changing on restic's side. Feel free to reopen the issue if the problem reappears.
