### ISSUE TITLE
rclone cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by JahmesJoyce** [restic/restic#3922]
I have updated today restic to version 0.14 from 0.13.1. Now I get an error with my backup script:

restic.exe : Fatal: unable to open repository at rclone:OneDrive_XXXXXXX:ServerBackup: 
cmd.Start: exec: "rclone": cannot run executable found relative to current directory

**Comment by MichaelEischer** [comment]
Please fill out the complete issue template at https://github.com/restic/restic/issues/new?assignees=&labels=&template=Bug.md . We can't help you otherwise.
