### ISSUE TITLE
`-v` / `--verbose` does not behave as specified in `--help`

### ISSUE THREAD

**Issue by petervaro** [restic/restic#3926]
## Output of `restic version`

```none
restic 0.14.0 compiled with go1.19 on linux/amd64
```

## How did you run restic exactly?

```bash
$ restic backup --help
$ restic backup <source> --repo <target> --verbose 3
```

## What backend/server/service did you use to store the repository?

Local.

## Expected behavior

I expect `-v` / `--verbose` to be able to handle `--verbose n` form without the need for `=` symbol.  The reason for this is not only the help text suggests its usage this way (on the left, it says `-v, --verbose n`, on the right it illustrates as `--verbose=n`) but virtually all other flags are able to handle their arguments this way.

## Actual behavior

Only `--verbose=n` form is accepted at the moment.  Using it in the form of `--verbose 3` results in ignoring the flag and its argument:

```text
3 does not exist, skipping
open repository
enter password for repository:
```

## Steps to reproduce the behavior

As described above, just pass down a level after the `--verbose` flag with at least 1 whitespace character between the flag and its argument.

## Do you have any idea what may have caused this?

Without looking at the source, I  imagine this is caused by the fact the `-v` / `--verbose` can be defined multiple times, as well as it can take an explicit argument.

## Do you have an idea how to solve the issue?

The simplest solution would be to set expectations right - if `-v` / `--verbose` should use the `=` then that's how it should be presented in the `--help`.

The more complex solution would be to support the above form described in the 'Expected behaviour' chapter which would very likely mean removing the support to specify `-v` / `--verbose` multiple times in favour of the explicit level / times form.

The most complex solution would be to support all forms, defining the flag n times, as well as, being able to specify the level explicitly in both `-v=n` and `-v n` forms.

## Did restic help you today? Did it make you happy in any way?

So far, definitely :heart:

**Comment by MichaelEischer** [comment]
> The simplest solution would be to set expectations right - if `-v` / `--verbose` should use the `=` then that's how it should be presented in the `--help`.

I guess you're referring to `  -v, --verbose n                     be verbose (specify multiple times or a level using --verbose=n, max level/times is 3)`? As mentioned in https://github.com/restic/restic/pull/2805 the initial `--verbose n` help text is generated by the library we use to build the CLI and cannot be changed (https://github.com/spf13/pflag/issues/267).

Breaking the CLI backwards compatibility of the `verbose` flag is not really an option. This rules out the alternatives to fixing the help text. So essentially, we're stuck here until the formatting for the flag is fixed in cobra (the CLI library).

**Comment by petervaro** [comment]
If `Cobra` is unable to generate proper help text nor is able to handle the two (or three) different forms then I believe you are right, there's not much you could at this point -- other than migrate to another library if there's any (I'm only slightly familiar with the Go ecosystem).  But that might be too much of a hassle for this flag alone (unless there are others which suffer a similar fate).

On the subject of backwards compatibility -- not sure what your attitude to deprecation warnings and a given time period is, but that might be a solution to slowly remove the repetition pattern and use the explicit form only.  (After all the issue you linked is more than 2 years old and who knows when that bug will be fixed.)

If neither migration nor deprecation is viable, perhaps it's worth explaining in the help text that due to a current limitation in the argument handler the explicit value must be passed down with the `=` symbol.  Demonstrating it alone is not enough because many, many CLI tools out there are able to handle both `--flag value` and `--flag=value` interchangeably, which could easily lead to confusion, like in my case, when one expects based on the generated left hand side and the handwritten right hand side that this might be the case.

**Comment by MichaelEischer** [comment]
> On the subject of backwards compatibility -- not sure what your attitude to deprecation warnings and a given time period is, but that might be a solution to slowly remove the repetition pattern and use the explicit form only. (After all the issue you linked is more than 2 years old and who knows when that bug will be fixed.)

I don't see how we could detect this pattern without manually parsing the command line parameters, which is a horribly idea. And requiring everyone to adjust their scripts to work around a single misleading character in the help output seems to be absolutely excessive.

> If neither migration nor deprecation is viable, perhaps it's worth explaining in the help text that due to a current limitation in the argument handler the explicit value must be passed down with the `=` symbol.

Do you have a specific suggestion on how to change the help text?

> Demonstrating it alone is not enough because many, many CLI tools out there are able to handle both `--flag value` and `--flag=value` interchangeably,

This interchangeability is a result of `--flag` being configured to require a parameter. If that were the case for the verbose flag, then we'd already have the same behavior.

**Comment by petervaro** [comment]
> Do you have a specific suggestion on how to change the help text?

Along the lines of what I said above, something like this could work:

> ```none
> -v, --verbose n    Sets the verbosity level of restic's output.  The maximum
>                    level is 3.  This flag can be used in two forms: it can be
>                    specified multiple times (without a value) to increase the
>                    level, or it can be supplied with an explicit level using
>                    the `--verbose=n` form.  (Mind the `=` symbol without the
>                    surrounding whitespace - due to a current implementation
>                    constraint in the argument handling, the generated example
>                    on the left which uses whitespace as delimiter between the
>                    flag and the value (`--verbose n`), is in fact invalid.)
> ```

But I'm no technical writer, perhaps this could be explained shorter :man_shrugging:

**Comment by MichaelEischer** [comment]
Hmm, that's far too long as help text. 

A different idea: would it help to change the left hand side of the option description to the following? Or would that be worse than the current state? I've also included an alternate suggestion for the description, although I'm not particularly keen on nesting brackets.
```
  -v, --verbose =n                     be verbose (specify multiple times or a level using --verbose=n (including the `=` symbol), max level/times is 3)
```
