### ISSUE TITLE
TLS: Oversized record received

### ISSUE THREAD

**Issue by arvdsn** [restic/restic#393]
Hey,

I've been following the discussions between you an minio and was excited to try it out. Looks like I'm running into a tls issue. 

Backend (minio) is started with `./minio server /mnt/backup/minio/`
Frontend (compiled source) is started with `./restic -r s3://10.0.0.120:9000/mbp13 init`

Result is: `creating backend at s3://10.0.0.120:9000/mbp13 failed: Put https://10.0.0.120:9000/mbp13?location=: tls: oversized record received with length 20527`

I also tried to use an existing nginx-proxy routed to /restic/ but then I get this `creating backend at s3://10.0.0.66/restic failed: Put https://10.0.0.66/restic?location=: x509: cannot validate certificate for 10.0.0.66 because it doesn't contain any IP SANs` even with valid self-signed cert.

I'm probably simply missing something, but I can't figure out what. The bucket is supposed to be created with init, right?

**Comment by fd0** [comment]
Hi, thanks for trying the new minio s3 library support!

The repository specification (that what you give restic with `-r`) has changed for s3, the old `s3://host/bucket` is still supported, but will try to connect via HTTPS, hence the TLS error.

Please try the new (not yet documented *cough*) format like this:
```
$ restic -r s3:http://10.0.0.120:9000/mbp13 init
```

**Comment by fd0** [comment]
Did you have the chance to try this again? Can you please close this issue if it is resolved?

**Comment by arvdsn** [comment]
Hi again! Yes, it works perfectly. Sorry for not getting back to you sooner :)

**Comment by fd0** [comment]
Awesome, thanks!
