### ISSUE TITLE
Restic 0.14.0 on Windows with rclone to OneDrive don't work

### ISSUE THREAD

**Issue by JahmesJoyce** [restic/restic#3932]
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on windows/amd64

How did you run restic exactly?
-------------------------------
restic_0.14.0_windows_amd64.exe backup \\server03\d$\ -r rclone:OneDrive_XXXXXX:Backup --exclude-file=C:\AdminScripte\Restic\exclude.txt -p=C:\AdminScripte\Restic\password.txt

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Microsoft-OneDrive with rclone. rclone version info:
rclone v1.58.1
- os/version: Microsoft Windows 10 Pro 21H2 (64 bit)
- os/kernel: 10.0.19044.2006 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.9
- go/linking: dynamic
- go/tags: cmount

Both executable (restic/rclone) are in the same directory.

Expected behavior
-----------------
Doing a backup like with restic_0.13.1_windows_amd64

Actual behavior
---------------
Error-Message:
Fatal: unable to open repository at rclone:OneDrive_XXXXXX:Backup: cmd.Start: exec: "rclone": cannot run executable found relative to current directory

Steps to reproduce the behavior
-------------------------------
Use commandline above

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes, I make my backup daily with restic-0.13.1 and would like to use restic-0.14.0 with compression.

**Comment by rawtaz** [comment]
Thanks for the report! Can you please try setting the environment variable `GODEBUG=execerrdot=0` in the context/shell where you run restic, to see if that then makes restic successfully run rclone? I believe the cause of this issue is: https://pkg.go.dev/os/exec#hdr-Executables_in_the_current_directory

**Comment by JahmesJoyce** [comment]
Thats it. No Restic/Rclone is doing the job. What should I do now? Moving Rclone to a different directory?

**Comment by rawtaz** [comment]
I take it you meant to write "Now restic/rclone is doing the job"?

Well, the workarounds at this point are to either run it with that environment variable (`GODEBUG=execerrdot=0`) or move the rclone binary to another directory that is in your `%PATH%`, as long as it's not in the same directory as restic.

**Comment by JahmesJoyce** [comment]
You are right. Now is restic/rclone doing the job! I will try to get it run and now I have a hint and thank you for this. Currently I call Restic from Powerscript - I will have to look to set envirentvariabels from Powerscript or to manipulate the Path-Resource from the script. I will find a way. 
Thank for this Tip!

**Comment by rawtaz** [comment]
Actually, there is one other way to deal with it: In your restic command, simply add `-o rclone.program='./rclone'` (add `.exe` or similar if your rclone binary isn't named just `rclone`).

**Comment by JahmesJoyce** [comment]
Ok, thank you. I will try it tomorrow. It seems for me it will we be a short way.

**Comment by JahmesJoyce** [comment]
Don't know why you reopen this issue? Restic is working with your hint -o rclone.program='./rclone.exe'.

**Comment by rawtaz** [comment]
Because the error message (which comes from Go, not restic) is pretty darn unclear and confusing to users, to the extent that they/you had to open an issue asking about the problem. We need to fix that, so the user is better informed when this happens.

**Comment by JahmesJoyce** [comment]
Ok, I understand. Thank you for help to solve this issue.
