### ISSUE TITLE
Ownership of Restic on Chocolatey

### ISSUE THREAD

**Issue by TheChiefMeat** [restic/restic#3933]
I'm looking for some support in regards to the ownership of the Chocolatey package that is available at:

https://community.chocolatey.org/packages/restic

I no longer have the availability to maintain this package, and would prefer that it reach loving hands so the user-base that does use Chocolatey as their Windows package manager continues to get support and frequent updates instead of it become too stale and a deprecated method of installing Restic. The package has seen nearly 7000 downloads, hence my reaching out.

Please feel free to reach out to me here; I can add a trusted member of the team to the chocolatey package to oversee future releases. If it would be preferential to mark the Chocolatey as deprecated or (if possible) delete it, that can be arranged, but I'd prefer the latter.

**Comment by maxxer** [comment]
Out of curiosity, is the package built out of a repo?

What does it take to *maintain* updates?
I am a user of Chocolatey, and of restic of course (tough not much on Win).

**Comment by TheChiefMeat** [comment]
Thanks for the reply. 

Maintenance is fairly simple; There's only two files that require changes each time there is a new release; One that describes the program and it's current version and various details, and the other file points to the download links and a hash that has to be generated and applied for each download link you wish to include as part of the Chocolatey release.

Obviously I've been doing the above for some time, but I haven't been using Windows for several years now and I'm trying to reduce and eventually remove any Windows stuff I have left.

**Comment by maxxer** [comment]
I'm not using Windows myself either... Sorry

**Comment by rawtaz** [comment]
Made a forum post here: https://forum.restic.net/t/chocolatey-package-looking-for-new-maintainer/5598

**Comment by thoscut** [comment]
I think I can maintain the package as I already have some experience in building (non-community) packages.

**Comment by moosemanf** [comment]
would also be interested, is it better just one guy doing that or can there be multiple people?

**Comment by rawtaz** [comment]
@TheChiefMeat We have two people here who advertised interest in taking over the maintenance of the package, can you please coordinate with them so we reach a conclusion and the package can keep living on? :)

**Comment by TheChiefMeat** [comment]
Thank you both for your interest in helping maintain this package; Could you please make accounts at https://community.chocolatey.org/account/Register and then I can add your usernames as maintainers of the project.

**Comment by moosemanf** [comment]
FloS is my new username over at Chocolatey

**Comment by thoscut** [comment]
Mine is TSSOS

**Comment by thoscut** [comment]
@TheChiefMeat Do you need anything else from @moosemanf and me for further processing?

**Comment by TheChiefMeat** [comment]
Apologises again for the lack of replies; I've added both TSSOS and FloS as maintainers to the package.

**Comment by moosemanf** [comment]
hey rawtaz,

thx, and yes, it worked, starting to get my hands dirty...

cheers,
Flo


>ving this because you were mentioned.Message ID: 
>***@***.***>
>

**Comment by rawtaz** [comment]
Sweet, then let's close this!
