### ISSUE TITLE
Fatal: unable to save snapshot: nodes are not ordered

### ISSUE THREAD

**Issue by JohannesRudolph** [restic/restic#3937]
What backend/server/service did you use to store the repository?
----------------------------------------------------------------
repository is stored locally on an external HDD (FAT) locally mounted at `/Volumes/b42_01/`
the source of the backup is an SMB share locally mounted at `/Volumes/vaults/`

Expected behavior
-----------------
restic backup completes without error

Actual behavior
---------------

This is the output of running my backup

``` text
$ restic version
restic 0.14.0 compiled with go1.18.5 on darwin/amd64

$  restic -r /Volumes/b42_01/restic-unifi/ --verbose backup /Volumes/vaults/
open repository
enter password for repository: 
repository 323387e9 opened (repository version 2) successfully, password is correct
lock repository
no parent snapshot found, will read all files
load index files
start scan on [/Volumes/vaults/]
start backup on [/Volumes/vaults/]
scan: lstat /Volumes/vaults/b42/photos/X/2016/Südtirol 2016_2.jpg: no such file or directoryumes/vaults/b42/inbox/2020/02-Februar/DSC06018.JPG
scan: lstat /Volumes/vaults/b42/photos/X/2017/Südtirol 2017 464.jpeg: no such file or directorys/vaults/b42/inbox/2020/02-Februar/DSC06018.JPG
scan finished in 797.849s: 76610 files, 252.015 GiB
Fatal: unable to save snapshot: nodes are not ordered got "Armdrücken 1.MPG", last "Armdrücken 1.MPG"
```

There's two issues I can observe

- the `scan: lstat` log line look fishy - the first file mentioned does not match the second (no such file or directory) and the message is garbled see e.g. `directoryumes` which should probably mean `directory /Volumes/vaults...` 
- the crash at `Fatal: unable to save snapshot: nodes are not ordered` seems to come deep from this tree implementation and violating an invariant/assert? https://github.com/restic/restic/blob/4ffd479ba490494eecd1d5b720e505b9c0c19567/internal/restic/tree.go#L161

Steps to reproduce the behavior
-------------------------------

~unfortunately it seems to be flaky and I cannot reliably reproduce it~
I can reproduce it re-running the same backup command again

```
scan finished in 1479.448s: 76610 files, 252.015 GiB
Fatal: unable to save snapshot: nodes are not ordered got "Armdrücken 1.MPG", last "Armdrücken 1.MPG"
```

Do you have any idea what may have caused this?
-----------------------------------------------

I suspect a concurrency issue / heisenbug 

Do you have an idea how to solve the issue?
-------------------------------------------

The first issue seems to be a problem of concurrent logging and not properly locking writing to stdout/stderr.

I assume tree ordering is an invariant that the tree implementation should always protect. I assume the second issue could be a concurrency issue in the tree implementation that can lead  to violation of that invariant.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I'm trying it as an alternative to backing up with rclone... so far those issues don't inspire confidence

**Comment by samvdst** [comment]
I get the same error message on macOS 12.5.1, backing up `/volumes/GoogleDrive/My Drive` to S3.
Errors on the same PDF file every time.

Copying said PDF to the Desktop and backing up from there works.

`restic 0.14.0 compiled with go1.19 on darwin/arm64`

**Comment by MichaelEischer** [comment]
This is #1866 it's just that the error message has changed in the meantime. Could you run `ls -lai@b .` (i = print inode, @ = print extended attributes, b = encoded non-printable characters) for the problematic folder and provide the output for the filename in question?

**Comment by samvdst** [comment]
In my case, the file appears twice. But not in finder.
I assume this is an issue with Google Drive FS.

```bash
ls -lai@b | grep 2022-08-27\ Vertrag
 3252382203961022964 -rwx------@ 1 sam  staff   2879158 Aug 27 17:26 2022-08-27 Vertrag Mastercard.pdf
 3252382203961022964 -rwx------@ 1 sam  staff   2879158 Aug 27 17:26 2022-08-27 Vertrag Mastercard.pdf
```

**Comment by JohannesRudolph** [comment]
Here's my output

```
17:17 $ ls -lai@b /Volumes/vaults/b42/photos/X
total 2832
           111673578 drwxrwx---  1 jrudolph  staff   16384 Sep 19 11:31 .
           111673512 drwxrwx---  1 jrudolph  staff   16384 Jun 19 23:03 ..
           111673579 -rwxrwx---  1 jrudolph  staff  351797 Apr  9  2004 Armdrücken 1.MPG
11009627365744611272 -rw-r--r--  1 jrudolph  staff  351797 Apr  9  2004 Armdrücken 1.MPG
```

**Comment by MichaelEischer** [comment]
@samvdst #3880 will change the error to a warning in you case. But its still a filesystem problem.

@JohannesRudolph Please run fsck/chkdsk for that volume, it looks like something is seriously wrong there. Does the file also show up twice on the SMB server?
