### ISSUE TITLE
--group_by for backup parent selection

### ISSUE THREAD

**Issue by chastings667** [restic/restic#3941]
Output of `restic version`
--------------------------

restic 0.14.0 compiled with go1.19 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Allow different snapshot groupings to find the best backup parent.

For the "backup" command, if an explicit parent is not specified with --parent, restic will choose the newest snapshot with the same paths and host as the current job.

This does not always find the best parent. For my (common?) use case, I have two backup sets on the same host:

full: path /a /b, no excludes
warm: path /a /b, exclude /a/archive/* /a/huge_files/* etc.

The full backup is run once a week, and warm backups on the other six days. Current parent selection will always pick the newest snapshot (since the host and paths always match), which for the full backup will be a warm snapshot, which is suboptimal since many files in full are not in warm, and will have to be rehashed.

I currently run a separate `snapshots --tag full` cmd to find the most recent snapshot by tag and then specify with --parent for backup, but this seems like it would be better integrated into the program itself.

see:

https://forum.restic.net/t/parent-selection-using-tags/5443

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Add --group_by (or a better name?) to the backup command for configurable parent selection. It would have the same semantics as forget's --group_by argument.

In my use case described above, I would use --group_by host,tag to backup just as I do for my forget invocations.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Good backups help me sleep better every night! Better sleep does result in happiness, so yes, in a way.

Although it wasn't today, a few weeks back I deleted an old photo directory thinking I had copied everything elsewhere, without verifying that I had actually done the copy. An hour later, I began to doubt myself, so I mounted the latest snapshot and made sure each file from the deleted directory existed elsewhere.

**Comment by AlBundy33** [comment]
Or maybe add an optional "reference-id" as cli argument to be independent from the used path(s)?

But maybe also group by host, user and some tag is enough. 🤔

**Comment by MichaelEischer** [comment]
> Or maybe add an optional "reference-id" as cli argument to be independent from the used path(s)?

That sounds like the "label" discussed in #4026? We can add a "label" option to the group-by option later on.
