### ISSUE TITLE
Prune repack: Failed to refresh lock 

### ISSUE THREAD

**Issue by jussihuotari** [restic/restic#3954]
Output of `restic version`
--------------------------

`restic 0.14.0 (v0.14.0-117-g7112a132c) compiled with go1.19.2 on darwin/amd64`

How did you run restic exactly?
-------------------------------

```
./restic -r sftp:backup:backup/foobar -p repo_pwd.txt prune --repack-uncompressed --compression max
repository a7513e38 opened (repository version 2) successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 24 snapshots
[0:09] 100.00%  24 / 24 snapshots
searching used packs...
collecting packs for deletion and repacking
[1:43] 100.00%  117952 / 117952 packs processed

to repack:        712588 blobs / 566.320 GiB
this removes:        429 blobs / 183.161 MiB
to delete:             0 blobs / 184.361 MiB
total prune:         429 blobs / 367.522 MiB
remaining:        712159 blobs / 566.113 GiB
unused size after prune: 0 B (0.00% of remaining size)

deleting unreferenced packs
[0:00] 100.00%  11 / 11 files deleted
repacking packs
Fatal: failed to refresh lock in timeked
[3:24] 0.03%  38 / 117952 packs repacked
Fatal: context canceled
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Sftp to a local network disk.

Expected behavior
-----------------

I'd expect Restic to run the prune without failing.

Actual behavior
---------------

At 3 minutes in `repacking packs` restic puts out an error message `Fatal: failed to refresh lock in time` and ends the process a few seconds afterwards.

Steps to reproduce the behavior
-------------------------------

I tried a few times with the same result every time. 

Do you have any idea what may have caused this?
-----------------------------------------------

I was using the latest from `master`. After a few tries I downgraded to v0.14.0, recompiled, and the process seems to run without problems (the process is not finished yet though - I thought I'd report the possible bug now from fresh memory instead of waiting for the potentially very long time repacking). 

So, could be related to #2715 ? IIRC the pull request landed to master a few days ago.

Other issue that I thought might be relevant is https://github.com/restic/restic/issues/3908#issuecomment-1231739981. However,  the memory usage by restic seems to be quite stable at around 550M, so no problems there.

Do you have an idea how to solve the issue?
-------------------------------------------

A workaround for me was to use v0.14.0.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is a delightful secure backup solution that works well in multiple environments (incl. RaspberryPi). 🙂👍

**Comment by MichaelEischer** [comment]
That is fallout from merging #3569. Actually the bug is quite embarrassing, see #3956.
