### ISSUE TITLE
Invalid values of environment variable RESTIC_COMPRESSION are silently ignored

### ISSUE THREAD

**Issue by deajan** [restic/restic#3962]
Output of `restic version`
--------------------------
```
restic 0.14.0 compiled with go1.19 on linux/amd64
```

How did you run restic exactly?
-------------------------------

```
export RESTIC_PASSWORD=SuperSecretPassword
export RESTIC_REPOSITORY='rest:https://someuser:somepassword@someserver.tld/someuser'
export RESTIC_COMPRESSION=bullshido
restic init --repository-version 2
restic backup --verbose --exclude-caches --tag="test" -o rest.connections=25 /somedir
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
```
rest-server version rest-server 0.11.0 compiled with go1.17.6 on linux/amd64
REST server is behind haproxy 2.4 which offloads TLS security.
```
Expected behavior
-----------------

using `RESTIC_COMPRESSION=<some invalid string>` should trigger the same as when run with `--compression=<some invalid string>`, eg:
```
invalid argument "bullshido" for "--compression" flag: invalid compression mode "bullshido", must be one of (auto|off|max)
```

Actual behavior
---------------

restic backups without complaining.
So there's no way to know whether compression was used, since it would just continue to run without a proper compression argument.

Steps to reproduce the behavior
-------------------------------
I hope you have everything required above ;)

Do you have any idea what may have caused this?
-----------------------------------------------
?

Do you have an idea how to solve the issue?
-------------------------------------------
Make `RESTIC_COMPRESSION` env variable tested the same way `--compression` argument is.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm the author of [backup-bench](https://github.com/deajan/backup-bench)
After a lot of benchmarking between all the solutions, I wanted to give restic a deeper test dive for it fills quite well my usecase.

**Comment by MichaelEischer** [comment]
Ah, you've found this place in the code:

https://github.com/restic/restic/blob/1a6160d15233fb2dd8f4655d9f46beb39378fdf5/cmd/restic/global.go#L136-L140

If someone has a not too horrible idea on how to handle that properly, I'm all ears.

**Comment by deajan** [comment]
IMO setting a wrong `RESTIC_COMPRESSION` env variable should stop restic execution with an error message ie "Unknown compression format", since continuing without knowing what has been done is probably the worst scenario for every user.

I'm aware that this is hard coding the possible values. But at least it's consistent.

**Comment by MichaelEischer** [comment]
I've opened a PR to return an error if the value is invalid. The problem I mentioned previously was more about getting the error to the right place nicely, not about how restic should behave.

**Comment by deajan** [comment]
Thanks ;)
