### ISSUE TITLE
Restic backup from AWS EC2 instance using IMDSv2 to S3 bucket fails

### ISSUE THREAD

**Issue by mededus** [restic/restic#3965]
Restic backup was working fine until we switch instance metadata version from IMDSv1 to IMDSv2. Backup is executed from AWS EC2 instance to S3 bucket. No credentials are exported since EC2 instance has IAM role with assigned that allows full access (all policies) to S3 bucket. Switching back to IMDSv1 solved the issue.

Output of `restic version`
--------------------------
restic 0.12.1 compiled with go1.15.14 on linux/amd64

How did you run restic exactly?
-------------------------------
Executed on AWS EC2 instance running CentOS 7.9 (restic installed via YUM using yum-plugin-copr:
```
export RESTIC_REPOSITORY="s3:s3.amazonaws.com/<s3 bucket name>"
export RESTIC_PASSWORD_FILE="<encryption password>"
restic backup /home/user --tag ec2
```

**stderr:**
`Fatal: create key in repository at s3:s3.amazonaws.com/restic-backup-tn541-st failed: client.PutObject: Access Denied`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
AWS S3 bucket 

Expected behavior
-----------------
Restic shall be able to work with S3 backup repository while executed on AWS EC2 instance that is setup with IMDSv2

Actual behavior
---------------
Restic does not work with S3 backup repository while executed on AWS EC2 instance that is setup with IMDSv2. It works when IMDSv1 is set.

Steps to reproduce the behavior
-------------------------------
Case 1:
Create S3 bucket and create policy with full access to it
Create EC2 instance and set IMDSv2. IMDSv2 enforces to use token for accessing EC2 instance metadata
Assign role that has full access S3 bucket policy to the EC2 instance
Make sure that you can access S3 bucket via AWS CLI for example, while logged to the instance via SSH terminal
Initialize restic repository
`restic -r s3:s3.amazonaws.com/<s3 bucket> -o s3.region=eu-central-1 init
`

Case 2:
Create EC2 instance with IMDSv1 in the same way like in case 1
Initialize restic repository
`restic -r s3:s3.amazonaws.com/<s3 bucket> -o s3.region=eu-central-1 init
`
Run `restic backup <your directory>`
Restic shall work. Change the IMDSv1 to IMDSv2 or go back to case 1 and try to run restic backup to initialized repository
It shall fail.

Do you have any idea what may have caused this?
-----------------------------------------------
Restic seems to use IMDS service to work with AWS resources. 

Do you have an idea how to solve the issue?
-------------------------------------------
IMDSv2 requires token to be generated and this could be the solution. Generate token. It should be backwards compatible with IMDSv1. This means that if you generate token for request against IMDSv1 it will not harm it and it shall work.

At the end I might be completely wrong and there is a solution that would solve the issue. In such case, please advice me, how to solve the issue. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I like restic a lot and the way how it works.  We use it on a daily basis. I believe this can be easily fixed by enhancing code to work with IMDSv2, if this is the root cause.

**Comment by MichaelEischer** [comment]
This has already been fixed by https://github.com/restic/restic/pull/3539 . You'll have to upgrade at least to restic version 0.13.0

**Comment by mededus** [comment]
Great, restic updated and it works. Thanks
