### ISSUE TITLE
Single command to forget all tagless snapshots?

### ISSUE THREAD

**Issue by Mrodent** [restic/restic#3976]
Output of `restic version`
--------------------------
0.14.0.  (OS: W10)

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
This is just a minor thing. As I understand it, the "forget policy" requires you always to leave at least 1 snapshot (the newest I think) meeting the criteria you have set. I read a post on the forum which suggests that this is done for "safety" reasons, and it was said that the aim is to balance safety and usability, which I understand.

This also seems to apply to when you are forgetting tagless snapshots (i.e. `restic ... forget tag ""`).

At the moment the way I organise my snapshots is to run a in a Python script as a scheduled task (every 10 minutes) which adds or removes tags for given frequencies based on analysed differences (i.e. "10-minute", "hour", "day", etc.) allowing a maximum number of each frequency to persist ... My script means that a new tag of a given category will only be added to the new snapshot only if differences have been detected relative to the most recent snapshot of that frequency category, so it's not "every hour unconditionally", which is less desirable: as I understand it, you might end up with 5 identical "hour" snapshots.

At the end of the scheduled task the final job is to delete any snapshots which now have no tags. This/these will be snapshots which are the "oldest in frequency category" (or the new snapshot if it has been found to be superfluous in all frequency categories).

But at the moment I can't do this in one operation: I have to go (using `subprocess.run(...)`)

`cmd = ['restic_14', '-r', repo_dir_path, '--verbose', '--json', '-p', pwd_file_path, 'forget', '--tag', '', '-l', '1']`
and then 
`cmd = ['restic_14', '-r', repo_dir_path, '--verbose', '--json', '-p', pwd_file_path, 'snapshots', '--tag', '']`
and then (assuming there is one tagless snapshot left)
`cmd = ['restic_14', '-r', repo_dir_path, '--verbose', '--json', '-p', pwd_file_path, 'forget', snapshots[0]['id']]`

I understand the reasoning about "safety"... but isn't it likely that *tagless* snapshots should be a special case? I.e. one "forget" flag to say "delete all tagless"... indeed it could be just that: "--forget-all-tagless". Only people who knew what they were doing would choose to use that flag. Plus it would sort of encourage people to use the tag mechanism more systematically.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
As above: I just think the wish to delete ALL tagless snapshots is a desirable feature, for the reasons described.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
YES! restic continues to be brilliant!

**Comment by MichaelEischer** [comment]
`--forget-all-tagless` sounds a lot like it is only safe for certain special use cases. Many users probably don't use tags at all, such that we'd end up providing a "wipe the whole repository" option. As you're already using a script, I don't really see the use case for that option.

**Comment by Mrodent** [comment]
Fair enough
