### ISSUE TITLE
Failed to refresh lock during prune

### ISSUE THREAD

**Issue by greatroar** [restic/restic#3984]
Output of `restic version`
--------------------------

    restic 0.14.0-dev (compiled manually) compiled with go1.19 on linux/amd64

I was working from my own branch for #3983, but that doesn't touch the locking code.

How did you run restic exactly?
-------------------------------

I did a restic forget on some old snapshots, then

    ./restic prune --compression max --pack-size 32 --repack-small

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Local USB disk.

Expected behavior
-----------------

Prune succeeds.

Actual behavior
---------------

```
collecting packs for deletion and repacking
Fatal: failed to refresh lock in timerocessed
[3:09] 11.29%  17609 / 155932 packs processed
context canceled
```

Second run shows missing data:

```
 <data/ffff0d20> <data/ffff16ca> <tree/ffff2434> <data/ffff24f5> <data/ffff2bdc> <data/ffff2dad> <data/ffff34bc> <data/ffff35ae> <data/ffff3ed1> <tree/ffff423b> <data/ffff487e> <data/ffff5525> <data/ffff5638> <data/ffff5e8b> <data/ffff620c> <data/ffff687b> <data/ffff7139> <data/ffff7741> <data/ffff7866> <data/ffff7b5b> <data/ffff805a> <tree/ffff85a2> <data/ffff8c26> <tree/ffff903e> <data/ffff9933> <data/ffff9b28> <tree/ffff9fd0> <data/ffffa481> <data/ffffac28> <data/ffffad4c> <data/ffffb29d> <data/ffffb4d7> <tree/ffffb8c4> <tree/ffffbb05> <data/ffffc14b> <data/ffffc7f1> <tree/ffffd96f> <data/ffffdf8c> <tree/ffffe33f> <data/ffffe87a> <data/fffff205> <data/fffff65d> <data/fffff991> <data/fffffd74>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
Fatal: index is not complete
```

There was a lot more output before that. In fact, the terminal emulator's buffer was full and I couldn't see the start of it.

restic check shows no errors.

Do you have any idea what may have caused this?
-----------------------------------------------

I'm suspecting #3972.

Do you have an idea how to solve the issue?
-------------------------------------------

Not yet.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

It's good to see in the mountpoint that the backups are still there.

**Comment by MichaelEischer** [comment]
Can you test whether https://github.com/restic/restic/pull/3985 fixes the issue?

**Comment by greatroar** [comment]
The prune has run to completion without #3985 and I've been unable to reproduce the issue. The five minute figure mentioned in #3985 seems on the mark, though, so I'm guessing that was it.
