### ISSUE TITLE
--latest flag for restic snapshots doesn't work

### ISSUE THREAD

**Issue by dabljues** [restic/restic#3987]
Output of `restic version`
--------------------------

```sh
$ restic version
restic 0.14.0 compiled with go1.19 on linux/amd64
```

How did you run restic exactly?
-------------------------------

```sh
$ restic snapshots --latest 10
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

S3. All the env variables (secret/access keys, repository url, password) are defined

Expected behavior
-----------------

I'd expect the output of the command to include 10 latest snapshots.

Actual behavior
---------------

```
[...]
aaa  2022-10-26 12:00:20 foo-redis-backup-12345678-aaaaa  foo-redis-backup  /foo-backup/redis
bbb  2022-10-26 13:00:21  foo-redis-backup-87654321-bbbbb  foo-redis-backup  /foo-backup/redis
---------------------------------------------------------------------------------------------------------------------------
340 snapshots
```

And it's not like it's "340 snapshots", but it actually displayed 10. It's 340 lines. I care about this because this runs as a cronjob on my cluster and it clutters the pod logs. I know I can do `| tail -n X`, but then I lose the the beginning of the command logs, which is not ideal.

Steps to reproduce the behavior
-------------------------------

I guess one has to have a restic repo with N snapshots backed up and try run `restic snapshots --latest X`, where `X<N`.

**Comment by rawtaz** [comment]
I just tested it on the latest master build of restic and it works fine AFAICT. Please note that it applies to combinations of host and path, it doesn't work across all your snapshots in one big pile so to speak. I see that you have different hostnames, is it possible that what you are seeing is ten snapshots per unique hostname and path combination?

I suggest you try it with a lower number, e.g. 2 and perhaps also with `--group-by path` or `--group-by host` to see if you can make sense of it all. I think it works.

**Comment by dabljues** [comment]
Oh yeah, the host is different, because it will be a name of a k8s pod. Hmm, I tried:

```sh
$ restic snapshots --group-by tags --latest 2
```

and unfortunately it's still displaying all of them. The same for `path`. However, when I group by host, I also get a list of all of them, but each host has it's own "row heading" so to speak, like:

```
snapshots for (host [foo-redis-backup-27768960-5fztv], tags [foo-redis-backup]):
ID        Time                 Host                                     Tags                      Paths
---------------------------------------------------------------------------------------------------------------------------
a3bfa4d2  2022-10-19 02:00:20  foo-redis-backup-27768960-5fztv  foo-redis-backup  /redis-backup/redis
---------------------------------------------------------------------------------------------------------------------------
1 snapshots
```

**Comment by rawtaz** [comment]
If all you want is to get only the 10 latest snapshots from the `snapshots` command, can't you just `snapshots | tail -10`?

**Comment by dabljues** [comment]
As I mentioned in the question, I know I can 😺 I just wanted to know if there's a better option. This also doesn't take into consideration the fact that the command output may change (I guess?) in the future and the beginning may be important or the end would be longer. For example now `tail -n 10` gives me 8 latest snapshots, because there's a `---` line and the line with the number of snapshots found. So I can go for 12 here, but it's not future proof :D

If there's no pre-defined option to do this (I though I was doing something silly), then it's fine, I can go for `tail` or use `jq` as you mentioned, we already use it to parse many many things, so it won't be anything new. I consider the issue resolved, thanks for your help!

**Comment by rawtaz** [comment]
> This also doesn't take into consideration the fact that the command output may change (I guess?) in the future and the beginning may be important or the end would be longer.

Yeah, this is a good reason to work with structured data instead (that is, the JSON output). Then you are in full control :) Thanks!
