### ISSUE TITLE
doc: Remove reference to lobaro/restic-backup-docker ?

### ISSUE THREAD

**Issue by rawtaz** [restic/restic#4002]
The documentation [references](https://restic.readthedocs.io/en/stable/020_installation.html#docker-container) the Docker image at https://github.com/lobaro/restic-backup-docker , but this one is quite outdated and doesn't seem to be getting any attention by the owner of the repository, despite questions from people.

While it indeed seems like a nice image, I think we should remove the reference from the documentation if it's outdated. What do others think?

**Comment by MichaelEischer** [comment]
restic 0.12.0 is pretty outdated by now. I agree that we should remove the reference for now, steering users towards old restic versions isn't particularly helpful.
