### ISSUE TITLE
Not able to list folders with special characters in the name

### ISSUE THREAD

**Issue by samardzicneo** [restic/restic#4009]
Output of `restic version`
--------------------------

`restic 0.14.0 compiled with go1.19 on linux/amd64`

How did you run restic exactly?
-------------------------------

```
export B2_ACCOUNT_ID="account_id"
export B2_ACCOUNT_KEY="account_key"
export RESTIC_REPOSITORY="b2:bucket_name"
export RESTIC_PASSWORD="repo_password"

restic ls --long snapshot-id "/media/Folder with spaces and (Parentheses) or &s in the name"
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze B2

Expected behavior
-----------------

Restic should list the contents of the specified folder.

Actual behavior
---------------

Restic fails, logging only this:
```
Fatal: All path filters must be absolute, starting with a forward slash '/'
```

Steps to reproduce the behavior
-------------------------------

Back up a folder with special characters like above in the name and try to list it inside the repository.

Do you have any idea what may have caused this?
-----------------------------------------------

🤷🏼‍♂️ 

Do you have an idea how to solve the issue?
-------------------------------------------

🤷🏼‍♂️ 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Not today but a few months ago, it helped me get back my data when my drive failed.

**Comment by MichaelEischer** [comment]
That looks like somehow the directory path is passed to restic in multiple parts, the check in the code just checks that the string starts with a `/`. It looks a bit like the shell is interpolating the path in an unintended way. You could call `set -x` in your shell (use `set +x` to disable that mode again), then it should show the exact command used to call restic.

**Comment by samardzicneo** [comment]
@MichaelEischer I do believe it might've been an issue with zsh, because when using bash, this doesn't happen. Anyways, in the `-x` mode, the path is shown to be in quotes.

**Comment by MichaelEischer** [comment]
Please try whether using single quotes solves the problem `'`. However, as this appears to be a problem with shell quoting/behavior, there's nothing that can be done in restic about it.

**Comment by samardzicneo** [comment]
@MichaelEischer Using single quotes does indeed fix the problem. And yes, that's understandable. I should've tried different shells before reporting the issue.
