### ISSUE TITLE
Archiver: Use directio to avoid caching data

### ISSUE THREAD

**Issue by fd0** [restic/restic#401]
Currently, the archiver pipeline reads data twice: For finding new blobs and afterwards for reading the data for storage. This is bad and should be changed, so that data is only read once and we can implement things like #255, and maybe use https://github.com/ncw/directio to bypass the file system cache. This improves responsiveness for other applications on Linux a lot.

**Comment by fd0** [comment]
Since #472 has been merged, files are read only once. This issue remains open for implementing directio.

**Comment by cfcs** [comment]
Can we change the issue title then?

**Comment by fd0** [comment]
Yes We Can!

**Comment by fd0** [comment]
Before implementing this, evaluate whether `posix_fadvise` is maybe already enough.

**Comment by cfcs** [comment]
Then we should reference this issue! -  https://github.com/restic/restic/issues/117
