### ISSUE TITLE
repacking can corrupt a repo when the storage provider is being a jerkface

### ISSUE THREAD

**Issue by benchub** [restic/restic#4012]
Output of `restic version`
--------------------------
`restic 0.14.0 compiled with go1.19.2 on freebsd/amd64`

How did you run restic exactly?
-------------------------------

`restic -r rclone:pCloudMedia:pictures prune --repack-uncompressed --compression max --max-repack-size 100G`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

rclone, which in this case is backed by pCloud.

Expected behavior
-----------------

If restic detects an error, retry harder, or somehow abort the repack so that the repo isn't left broken. 

Actual behavior
---------------

Part of the output for the `prune --repack-uncompressed` command was:

```
repacking packs
rclone: 2022/11/08 03:12:49 ERROR : data/ba/bae3aff059fec386c089ee2b977b4b6847e49d81aa24467037a6ffddb9b8aa77: Post request put error: Put "https://api.pcloud.com/uploadfile?filename=bae3aff059fec386c089ee2b977b4b6847e49d81aa24467037a6ffddb9b8aa77&folderid=3861063254&mtime=1667905865&nopartial=1": write tcp 10.2.3.12:13590->74.120.9.89:443: use of closed network connection
rclone: 2022/11/08 03:12:49 ERROR : data/ba/bae3aff059fec386c089ee2b977b4b6847e49d81aa24467037a6ffddb9b8aa77: Post request rcat error: Put "https://api.pcloud.com/uploadfile?filename=bae3aff059fec386c089ee2b977b4b6847e49d81aa24467037a6ffddb9b8aa77&folderid=3861063254&mtime=1667905865&nopartial=1": write tcp 10.2.3.12:13590->74.120.9.89:443: use of closed network connection
Save(<data/bae3aff059>) returned error, retrying after 720.254544ms: server response unexpected: 500 Internal Server Error (500)
[22:33:07] 100.00%  20425 / 20425 packs repacked
```

That's clearly the backend provider failing to do what was asked of it. However, restic seems to have noticed there was an error saving that file, and moved on.

Afterwards, I ran a check of the repo (`restic -r rclone:pCloudMedia:pictures check`) and not-so-shockingly was told:

```
check all packs
pack bae3aff059fec386c089ee2b977b4b6847e49d81aa24467037a6ffddb9b8aa77: unexpected file size: got 2834432, expected 16783656
check snapshots, trees and blobs
[0:19] 100.00%  8 / 8 snapshots
Fatal: repository contains errors
```

Steps to reproduce the behavior
-------------------------------

Given that this depends upon a storage internal error I'm not sure how to repro.

Do you have any idea what may have caused this?
-----------------------------------------------

Optimism.

Do you have an idea how to solve the issue?
-------------------------------------------

Be more eager to retry and/or give up if things aren't working out.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic is amazing. Please keep it coming.

**Comment by MichaelEischer** [comment]
> That's clearly the backend provider failing to do what was asked of it. However, restic seems to have noticed there was an error saving that file, and moved on.

restic always retries failed uploads or aborts the whole command if that fails. That is on the second try pCloud confirmed that the data was stored properly. Thus, from the perspective of restic everything is fine.

It is not a problem for uploads to fail on the first try, as long as the storage provider correctly handles the retries.

> pack bae3aff059fec386c089ee2b977b4b6847e49d81aa24467037a6ffddb9b8aa77: unexpected file size: got 2834432, expected 16783656

That looks a lot like pCloud returns the data from the initial failed upload. As far as i remember, pCloud stores multiple versions if a file is overwritten. Please check whether the damaged file has a second version. That one is likely intact.

**Comment by benchub** [comment]
It appeared to me when I checked the file only had one version (and it was the 16MB size, not the 28MB size), but this does sound like a problem with pCloud. I'll talk to them next time first. Thanks again for such a great bit of software!

**Comment by benchub** [comment]
I don't know that I'd say they "resolved" it, other than saying "partial uploads happen; try again." Maybe it was a problem with with rclone? Regardless, if memory serves I simply re-uploaded again and it was great.

pCloud's once-per-lifetime pricing is great if your data volume doesn't grow much. I also appreciate they do *not* have a local mirror near me - the whole point of offsite backups is to survive natural disasters. I've been generally happy with them.
