### ISSUE TITLE
inappropriate ioctl for device - macOS with External hard disc

### ISSUE THREAD

**Issue by yeudakn** [restic/restic#4016]
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on darwin/arm64

How did you run restic exactly?
-------------------------------
export RESTIC_REPOSITORY=/Volumes/cal/restic/Images
export RESTIC_PASSWORD_FILE=.....
restic list snapshots
repository 964e458a opened (repository version 1) successfully, password is correct
Save(<lock/03bc0c08ac>) returned error, retrying after 552.330144ms: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-2714016895: inappropriate ioctl for device
Save(<lock/03bc0c08ac>) returned error, retrying after 1.080381816s: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-639727358: inappropriate ioctl for device
Save(<lock/03bc0c08ac>) returned error, retrying after 1.31013006s: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-3346973808: inappropriate ioctl for device
Save(<lock/03bc0c08ac>) returned error, retrying after 1.582392691s: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-4211375207: inappropriate ioctl for device
Save(<lock/03bc0c08ac>) returned error, retrying after 2.340488664s: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-4275222578: inappropriate ioctl for device
Save(<lock/03bc0c08ac>) returned error, retrying after 4.506218855s: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-2116746456: inappropriate ioctl for device
Save(<lock/03bc0c08ac>) returned error, retrying after 3.221479586s: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-3716238416: inappropriate ioctl for device
Save(<lock/03bc0c08ac>) returned error, retrying after 5.608623477s: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-2689860203: inappropriate ioctl for device
Save(<lock/03bc0c08ac>) returned error, retrying after 7.649837917s: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-2110309644: inappropriate ioctl for device
Save(<lock/03bc0c08ac>) returned error, retrying after 15.394871241s: sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-2186649457: inappropriate ioctl for device
sync /Volumes/cal/restic/Images/locks/03bc0c08ac696177540512e259823eb557198b87bf70a5ff519c3a064b5a4d79-tmp-3122613838: inappropriate ioctl for device
github.com/restic/restic/internal/backend/local.(*Local).Save
	/restic/internal/backend/local/local.go:181
github.com/restic/restic/internal/backend/limiter.rateLimitedBackend.Save
	/restic/internal/backend/limiter/limiter_backend.go:30
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
	/restic/internal/backend/backend_retry.go:66
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer
	/home/build/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.3/retry.go:55
github.com/cenkalti/backoff/v4.RetryNotify
	/home/build/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.3/retry.go:34
github.com/restic/restic/internal/backend.(*RetryBackend).retry
	/restic/internal/backend/backend_retry.go:46
github.com/restic/restic/internal/backend.(*RetryBackend).Save
	/restic/internal/backend/backend_retry.go:60
github.com/restic/restic/internal/cache.(*Backend).Save
	/restic/internal/cache/backend.go:59
github.com/restic/restic/internal/repository.(*Repository).SaveUnpacked
	/restic/internal/repository/repository.go:488
github.com/restic/restic/internal/restic.SaveJSONUnpacked
	/restic/internal/restic/json.go:31
github.com/restic/restic/internal/restic.(*Lock).createLock
	/restic/internal/restic/lock.go:161
github.com/restic/restic/internal/restic.newLock
	/restic/internal/restic/lock.go:105
github.com/restic/restic/internal/restic.NewLock
	/restic/internal/restic/lock.go:66
main.lockRepository
	/restic/cmd/restic/lock.go:42
main.lockRepo
	/restic/cmd/restic/lock.go:23
main.runList
	/restic/cmd/restic/cmd_list.go:43
main.glob..func14
	/restic/cmd/restic/cmd_list.go:24
github.com/spf13/cobra.(*Command).execute
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main
	/restic/cmd/restic/main.go:98
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1165
unable to create lock in backend

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
External hard disc connected with USB 3

Expected behavior
-----------------
list of snapshot ID's

Actual behavior
---------------
Error messages and then exits, see above.

Steps to reproduce the behavior
-------------------------------
restic backup
   OR
restic list snapshots

causes the error

Do you have any idea what may have caused this?
-----------------------------------------------
No.  I suspect a macOS issue (macOS Ventura Version 13.0.0; also tried Version 13.0.1).  
restic worked fine on the pre-Ventura macOS.

Everything else I've tried on the disc works ok.  Disc Utility first aid reports no errors.

Do you have an idea how to solve the issue?
-------------------------------------------
I tried the disc on another mac:
  macOS Monterey Version 12.6
  MacBook Pro (Retina, 13-inch, Early 2015

Worked fine with restic 0.12.1 compiled with go1.16.6 on darwin/amd64

Also tried installing
restic 0.12.1 compiled with go1.16.6 on darwin/arm64
on my mac and got the same errors 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It hasn't helped me today but it does make me happy every time
I restore a file.  I really like the mount command and it would be
nice if it worked on macOS.

**Comment by greatroar** [comment]
"inappropriate ioctl for device" is ENOTTY. That's a very surprising errno from fsync. What does

    /Volumes/cal/restic/Images/locks

say? What filesystem does the disk use?

**Comment by greatroar** [comment]
Oh, hold on. I though it was the directory sync that failed, but the filename got broken off in the post. If you have a Go compiler on that box, could you run the following script on it?

```go
// synctest.go
package main

import (
	"io/ioutil"
	"log"
	"os"
	"syscall"
)

func main() {
	f, err := ioutil.TempFile(os.Args[1], "synctest")
	if err != nil {
		log.Fatal(err)
	}
	log.Println("created", f.Name())

	err = f.Sync()
	if perr, ok := err.(*os.PathError); ok {
		if errno, ok := perr.Err.(syscall.Errno); ok {
			log.Fatalf("%v (errno=%d)", err, errno)
		}
	}

	log.Fatal(err)
}
```

Run with

    go run synctest.go /Volumes/cal/restic/Images/locks

This leaves a tempfile in that directory. If the script reports "inappropriate ioctl for device", then stat output for that tempfile would be interesting. You can remove it afterward.

**Comment by greatroar** [comment]
A web search led me to realm/realm-core#5789, where an fsync on an ExFAT mount gives the same error. macOS manpages don't list ENOTTY for either fsync or fcntl.

**Comment by yeudakn** [comment]
$ go run synctest.go /Volumes/cal/restic/Images/locks
2022/11/11 17:23:08 created /Volumes/cal/restic/Images/locks/synctest827244834
2022/11/11 17:23:08 sync /Volumes/cal/restic/Images/locks/synctest827244834: inappropriate ioctl for device (errno=25)
exit status 1

**Comment by greatroar** [comment]
Okay, that was the expected result. #4021 should fix this issue.

**Comment by yeudakn** [comment]
[https://github.com/restic/restic/pull/4021] works.

Thanks

**Comment by bdillahu** [comment]
Just as another confirmation that this fixed the error for me - thanks!
