### ISSUE TITLE
restic gives up to fast on rate-limited S3 backends that use HTTP 503 to slow clients down

### ISSUE THREAD

**Issue by pille** [restic/restic#4018]
Output of `restic version`
--------------------------
restic 0.12.1 (EL7)
(but same behavior with current release)

How did you run restic exactly?
-------------------------------

irrelevant

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

S3

Expected behavior
-----------------

backups or repo operations should not break, when the backend reports HTTP 503 "slow down", see https://aws.amazon.com/premiumsupport/knowledge-center/s3-503-within-request-rate-prefix/
(maybe it's not a good idea to repurpose the status code :thinking:)

Actual behavior
---------------

```
Save(<data/b2f6a26146>) returned error, retrying after 15.394871241s: client.PutObject: The server is temporarily unavailable. Please try again later.
100.00%  1 / 1 packs repacked
Fatal: client.PutObject: The server is temporarily unavailable. Please try again later.
```

restic does some exponential backoff and eventually stops retrying. (which is sane for the original meaning of 503)

Steps to reproduce the behavior
-------------------------------

have a backup running against a rate-limited S3 backend

Do you have any idea what may have caused this?
-----------------------------------------------

see above

Do you have an idea how to solve the issue?
-------------------------------------------

make the retry parameters configurable, so one ca tweak around the problem.
i guess we just need to retry more often, so exponential backoff is still a good idea.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

not today, but it did yesterday :grinning:

**Comment by greatroar** [comment]
Did you try the --limit-upload option?

**Comment by pille** [comment]
no, as this is not a deterministic workaround. it may (unreliable) "fix" the problem, but at the expense of slowing down all operations.

**Comment by greatroar** [comment]
True. But a longer retry would also apply to errors other than HTTP 503. If Amazon limits requests at 3500/s, a rate limiter in the S3 backend would be the cleanest solution. That might interact with the general rate limiter, though.

Would remembering the 503 and blocking the next request for a second work?

**Comment by MichaelEischer** [comment]
Related to https://github.com/restic/restic/pull/2515 .

I'm not particularly eager to mess around with the retries as this will also result in longer delays, if e.g. restic tries to unsuccessfully delete a lock file.

> Would remembering the 503 and blocking the next request for a second work?

The current retries already take about 30 seconds. Are you suggesting another mechanism to add delays between request repetitions?

**Comment by greatroar** [comment]
More "thinking out loud" than "suggesting". And if I may do some more of that...

The problem with applying the retrying logic to this issue is, I think, that it's unstable in the face of concurrency. If a goroutine manages to proceed while others are in a retrying loop, it may starve them and force them to stay in that loop. Due to exponential backoff, the last goroutine to go into a retrying loop is likely the first to come out again.

**Comment by MichaelEischer** [comment]
I've reworked the retry logic in https://github.com/restic/restic/pull/4784 . That will hopefully fix this issue. Feel free to reopen it if the issue persists.
