### ISSUE TITLE
Canceling password prompt in linux console keeps further input hidden

### ISSUE THREAD

**Issue by wasamasa** [restic/restic#402]
Repro:

- `restic -r /path/to/repo init`
- `Ctrl-c`

Expected result: After cancelling the password prompt I can type shell commands normally

Actual result: My input is hidden and requires executing `reset` blindly to restore

Version: Built yesterday from Git, running on Arch Linux.

**Comment by fd0** [comment]
That's strange, this works for me. What terminal emulator are you using? How did you built restic?

**Comment by wasamasa** [comment]
This happens in the linux console, aka the black thing you see when pressing `Ctrl-Alt-F2`.

I've built it with [the restic-git PKGBUILD](https://aur.archlinux.org/packages/restic-git/) from the AUR.

**Comment by fd0** [comment]
could you be a bit more specific? there are different implementations, could you start a few terminals and then use `ps aux` to find out which process is running?

**Comment by barsanuphe** [comment]
I can confirm this happens for me as well, in Archlinux, in a yakuake/konsole terminal.

**Comment by wasamasa** [comment]
The console was started by `/sbin/agetty --noclear tty2 linux` and runs bash as shell.

**Comment by fd0** [comment]
thanks for investigating

**Comment by viric** [comment]
The same happens to me, in xterm.

**Comment by viric** [comment]
It's not about a process being alive. It's about letting the terminal with echo disabled. I guess that on SIGINT restic does not reprogram the echo on the terminal.
