### ISSUE TITLE
beta.restic.net: Use Go 1.19 to build binaries

### ISSUE THREAD

**Issue by lbausch** [restic/restic#4023]
This came up in #3999 - right now the binaries available under beta.restic.net are built using Go 1.18, e.g:

```bash
$ ./restic_v0.14.0-255-g7b4fe7bad_linux_amd64 version
restic 0.14.0-dev (compiled manually) compiled with go1.18 on linux/amd64
```
Would it be possible to use Go 1.19?

**Comment by fd0** [comment]
Done, thanks for the reminder!

**Comment by lbausch** [comment]
Thanks!
