### ISSUE TITLE
Mount fails

### ISSUE THREAD

**Issue by Mebus** [restic/restic#403]
Hallo,

I tried to mount a repo and got this error on a CentOS 7 machine. When its mounted and I try an ls inside a snapshot I get an error:

<code>
root@bluebackup ~/restic (git)-[master] # ./restic -r /var/backup/restic-backups/kiste mount /mnt/resticbackup
enter password for repository: 
Now serving /var/backup/restic-backups/kiste at /mnt/resticbackup
Don't forget to umount after quitting!
</code>

<code>
root@bluebackup ..up/snapshots/2016-01-31T01:27:08+01:00 # ls
ls: reading directory .: Input/output error
2 root@bluebackup ..up/snapshots/2016-01-31T01:27:08+01:00 #          
</code>

What's wrong here?

Mebus

**Comment by fd0** [comment]
This looks like a bug, could you please build restic with debug support via `go run build.go -tags debug` and then run:
```
DEBUG_LOG=/tmp/log ./restic mount /mnt/resticbackup
```

Afterwards have a look at the debug log, if you can spot something unusual. Please be aware that the debug log may contain sensitive things such as directory and file names. If you like, you can share it privately with me.

**Comment by Mebus** [comment]
Hey fd0,

I got this in my log:

https://gist.github.com/anonymous/241001db367805cbf40b

But I cannot see any errors. Except for "repository.go:93 need to expand buffer: want 296 bytes, got 0".

(Hope there are no sensitive things in the log.)

Mebus

**Comment by fd0** [comment]
I've found the error, fix is underway.
