### ISSUE TITLE
Crash: unexpected signal (SIGBUS)

### ISSUE THREAD

**Issue by C-Otto** [restic/restic#4031]
I ran `restic prune --max-unused 5% --max-repack-size 500M` on my Raspberry Pi 3 Model B+ (1 GByte RAM, 4 CPU cores) with the restic data on an external USB drive. During this, I encountered the following crash. Based on previous crashes I think the same thing happened before, but this is the first time I was able to capture the output shown below.

This might be related to hardware issues, but it could also be a software bug. Please close this if you think it's hardware related, I know that a RPi isn't the most reliable platform :)

```
[...]
deleting unreferenced packs
[0:00] 100.00%  7 / 7 files deleted
repacking packs
[36:58] 100.00%  25 / 25 packs repacked
rebuilding index
fatal error: unexpected signal during runtime execution
unexpected fault address 0x40426a4000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x40519dac20 pc=0x2f5c0]

runtime stack:
unexpected fault address 0x403d08d000
fatal error: fault
runtime.throw(
```

That's all the output I got via SSH. The machine stopped responding to SSH and I had to do a cold reset.

Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on linux/arm64

How did you run restic exactly?
-------------------------------
```
export RESTIC_PASSWORD=x
export RESTIC_REPOSITORY=sftp:restic@hostname:/mnt/backup/restic
export RESTIC_COMPRESSION=max
restic prune --max-unused 5% --max-repack-size 500M
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SFTP (locally), data on an external USB drive.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm happy! I've never even thought about replacing restic by anything else, which was a very common thought with all (!) previous backup solutions I tried.

**Comment by C-Otto** [comment]
It happened again, also in the "rebuilding index" phase.
```
fatal error: unexpected signal during runtime execution
unexpected fault address 0x4016eeb000
fatal error: fault
unexpected fault address 0x4016f33000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x4016277000 pc=0x76744]

goroutine 863 [running]:
```

**Comment by C-Otto** [comment]
Doing the same thing on my "big" box (amd64, directly, i.e. without SFTP) worked without any issue.

**Comment by greatroar** [comment]
There isn't a lot to go on here, but...

* is the OOM killer on? If so, turning it off might give a proper out of memory error;
* does the machine still respond to ping, or did you get a kernel crash?

Really though, I wouldn't expect restic prune to run to completion on such a small device. Run it on the bigger machine, maybe over SFTP or rest-server to the smaller one.

**Comment by C-Otto** [comment]
I didn't configure OOM explicitly, so I think it is on. However, the machine has 5 GByte of swap, and it wasn't full when the machine crashed. The machine stopped responding to pings. I'll move the prune work to other another machine if this issue persists. Feel free to close this issue, if you don't think it's something wrong with restic itself.

**Comment by greatroar** [comment]
I'm suspecting a hardware fault, but again, I can't be sure. Restic is a garbaged collected application, so it's not going to be kind on your storage hardware if you run it in the swap file.

**Comment by MichaelEischer** [comment]
> I ran `restic prune --max-unused 5% --max-repack-size 500M` on my Raspberry Pi (1 GByte RAM, 4 CPU cores)

> restic 0.14.0 compiled with go1.19 on linux/arm64

That looks like it is a Raspberry Pi 4?

> repacking packs
> [36:58] 100.00%  25 / 25 packs repacked

Even though a Raspberry Pi isn't the fastest hardware in existence, that is far slower than I'd expect. It looks like restic is much more busy with swapping that actually doing useful work.

Could you provide the full stack trace? Are there warnings printed in `dmesg`?

**Comment by C-Otto** [comment]
It's a RPi 3 Model B+. I posted all the output I got, I don't know how to get a larger stack trace. As the machine crashed, I wasn't able to check `dmesg`. For the future, I'll have a closer look at RAM/swap usage. It is very slow, but so far that didn't bother me.

**Comment by MichaelEischer** [comment]
> export RESTIC_COMPRESSION=max

You might want to just use the default compression level. That should be a lot less demanding on the hardware.

> As the machine crashed, I wasn't able to check `dmesg`.

That doesn't sound like something which restic should be able to cause.

FWIW prune does work without crashing on my raspberry pi 4.

**Comment by MichaelEischer** [comment]
The memory usage of prune will be significantly lower in the next restic version, that hopefully avoids the issue here. If the problem persists, feel free to reopen the issue.
