### ISSUE TITLE
New AWS regions

### ISSUE THREAD

**Issue by Ufoton** [restic/restic#4034]
Hello,

There are few new regions added by AWS. When try to use this regions - responce is Fatal: create repository at s3:https://s3.amazonaws.com/restic-reimage failed: client.BucketExists: 400 Bad Request

with new github.com/minio/minio-go/v7 v7.0.44 everything is ok.

**Comment by sedlund** [comment]
did you try a different name?

**Comment by MichaelEischer** [comment]
I've amended #4025 to update to the latest minio version.
