### ISSUE TITLE
Separate into librestic / restic packages for easier integration

### ISSUE THREAD

**Issue by mappu** [restic/restic#404]
Hi,

I really like this project, and want to use it as an internal component within a larger GUI system. Right now, i will shell out to an external restic binary. But it'd be easier if restic was an embeddable library. Thanks

**Comment by fd0** [comment]
Internally, restic is already mostly a library, but I doubt it's directly usable. I had that same discussion a few days ago with @tobix, and I like the idea to be able to start restic in a "server" mode that allows RPC with a standard protocol, e.g. via stdin/stdout or on a local HTTP server. What do you think?

What GUI system are you using (language, toolkit, operating system)?

**Comment by mappu** [comment]
The "server mode" is interesting, but, i don't think it solves anything. Right now, restic can be controlled by stdin / env parameters / command-line arguments (for input) and watching the stdout/stderr (for output). They're well documented IPC systems. So what advantage would be brought by such a long-running process with a custom RPC protocol?

About my system. The relevant part it's {WPF, Swift, Android Java, HTML} => {distinct golang binary} => {restic binary} currently. But i want to eliminate having a separate binary for restic at all, since it's only used by a specific internal procedure. So a library interface would be helpful for me, instead of parsing the restic stdout currently.

Thanks again for your hard work on restic.

**Comment by fd0** [comment]
Thanks for the explanation. Internally, restic mostly already is a library, have a look at the source files for the different commands (`cmd_*.go`) in `cmd/restic`.

My thoughts regarding your idea:

To be honest, at the moment I don't like the idea of exposing too much of restic as a library, because I think it is not nearly ready for that (too much still changes regularly). Having an RPC mode to control restic from a program via stdin/stdout however would work for me, although I will not focus on implementing such a mode for quite some time.

Whenever you directly interface with the restic code, expect many breaking changes. We do not consider the use case "restic as a library" right now and will not have a sane and stable API for the internal functions. The most important part of development, at least at the moment, is to have a stable repository format and fix all the basic bugs that still hide in the code.

I hope that this does not discourage you from building something that uses restic internally, but I like to avoid the wrong expectations from restic at this point :)

**Comment by fd0** [comment]
I've decided to close this issue for now. It can still be found easily.

**Comment by bclermont** [comment]
Can `internal/*` be moved ... outside?

I want to write an open-source cross platform UI using https://github.com/therecipe/qt/, I want to use restic to backup/restore files on my linux desktop, osx wife box and android devices.

If I can't `import` and call straight `archiver.Reader.Archive` and must embed `restic` binary in my app a use `exec.Command.Run`, I won't even start this project

Restic API is clean enough to be exportable outside `github.com/restic/restic`

**Comment by fd0** [comment]
I'm sorry but I disagree, there are critical things (at least for now) that happen in the `main` package. This has also recently come up as https://github.com/restic/restic/issues/1089. So, for now the answer is no. Sorry.

**Comment by bclermont** [comment]
moving out of `internal` don't mean it's somekind of social contract that github.com/restic must keep some kind of compatibility in it's API.

It just mean I can use `import` go statement. it's my responsibility to fix my own stuff if restic/lib changes.

`internal` is something I almost never see in other projects. import and use don't violate anything, it don't impose anything, it just allow innovation/experimentation. `cmd.Command.Exec`, with a JSON stream decoder, make a terrible API on **Android**

One of the first thing community ask from a  FOSS project whenever attraction happens is an API. in restic case, a golang API is free.

**Comment by bclermont** [comment]
> If I understood you correctly you mainly would like to use the commands available in the CLI binary, but without having to run the binary and unserializing JSON. Is that correct?

yes exactly, and probably what every possible API consumers wish to.

> If so, let me think about what we can do.

the logic of all commands can be exposed as a safe to use public API that call `internal/*`.
those viper commands can call that public API to avoid any duplicate logic.

**Comment by fd0** [comment]
> the logic of all commands can be exposed as a safe to use public API that call internal/*.
those viper commands can call that public API to avoid any duplicate logic.

Yes, that was my line of thought. It's a bit more code from our side to get the options across and all that.

**Comment by bclermont** [comment]
Maybe I can draft something while I design my own backup app?

**Comment by fd0** [comment]
Okay, but don't make yourself too much work before we agree on how (and if) we do this :)

**Comment by bclermont** [comment]
I tried to refactor code structure and it need to export things such as `internal/backend/*`, and it requires too much changes. I'm afraid that it's going to be too much internal changes and it will be rejected.

I will put my project on hold until less stuff is kept in `internal`, which I'm pretty sure it will happens eventually.
