### ISSUE TITLE
backup stall after a few minutes

### ISSUE THREAD

**Issue by sjoerd-ccu** [restic/restic#405]
Given restic a try to backup from my laptop to my NAS server (using sftp) in the local network.  Things start of nicely (~350mbit/s on the network once restic starts pushing), but after a few minutes the transfer stalls and the backup seems to grind to a halt.

NAS is running plain Debian jessie. Laptop run debian unstable with restic build from git:
restic 0.1.0 (v0.1.0-317-gcf88b33)
compiled at 2016-02-01 08:17:04 with go1.5.3

Unlike #353 i don't see any errors regarding the sftp connection failing, hence opening a fresh issue.

**Comment by sjoerd-ccu** [comment]
Tested with the v0.1.0 tag as well, that nicely completed the backup. So this may well be a regression in more recent versions

**Comment by fd0** [comment]
Thanks for reporting this. I've seen this happen to myself and already did a git bisect, I have a rough idea what might cause the problem and will have a look in the evening today.

This is indeed a bug.

**Comment by fd0** [comment]
Just a quick heads-up: I've built a test that triggers the issue.
