### ISSUE TITLE
ignoring par2 files in the restic repository folder

### ISSUE THREAD

**Issue by slam39** [restic/restic#4080]
Output of `restic version`
--------------------------

restic version
restic 0.14.0 compiled with go1.19 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Maybe there is a possiblity to allow/fully support presence of par2 files (or any other similar files - par3 in the future etc) presence in the repository folder.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I recentrly tried to create par2 archive files for my repo. Created a wrapper script for it to work. However the issue with diff command occured when there are such files alongside snapshots files:
https://forum.restic.net/t/multiple-ids-with-prefix-problem/5699

The solution, of course, is to create another folder tree separately for the par2 files and don't create mess with restic files (as mentioned here https://forum.restic.net/t/how-to-create-par2-parity-files-for-a-restic-repository/5149)

However, as I thought there may be other users interested in using data anticorruption solution Par2 with restic maybe there is a chance in the future for restic to support this combination of tools used in the same folder? 

Maybe at least for now, until there is no futher development of this feature: https://github.com/restic/restic/issues/256

The solution from the restic part should be quite simple I think: simply ignore (with awareness of their possible presence) par2 files while doing restic operations. With some testing of course.

1 repo folder is easier to deal with than 2.

**Comment by MichaelEischer** [comment]
Judging from the restic output in the forum, this is already fixed by #3936. Please try whether a beta build of restic https://beta.restic.net/?sort=time&order=desc (or build the master branch yourself) works.

**Comment by slam39** [comment]
thanks, with beta version it works
