### ISSUE TITLE
[SOLVED] Hours of restic scan time for Btrfs-snapshots of an unmodified 894 GB Btrfs subvolume

### ISSUE THREAD

**Issue by rfkat** [restic/restic#4092]
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on linux/amd64

How did you run restic exactly?
-------------------------------
`/pictures/restic` is created as a read-only Btrfs snapshot before restic backup is started. It comprises ca. 894 GB of data that hasn't been modified after the last run of restic backup.

Command is:
`/usr/bin/restic --password-file /resticcloudkey --repo sftp::/backup --cache-dir /resticcache -o sftp.command="ssh root@123.456.789.123 -o IdentityFile=/key_rsa -s sftp" backup /pictures/restic`

Output is:
```
using parent snapshot 3e1209fb

Files:           0 new, 114299 changed,     0 unmodified
Dirs:            0 new,  1432 changed,     0 unmodified
Added to the repository: 77.874 MiB (26.727 MiB stored)

processed 114299 files, 892.913 GiB in 7:28:03
snapshot 8091c654 saved
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backup to a remote server, via SFTP (see command).

Expected behavior
-----------------
Maybe a few minutes of scanning & restic snapshot creation. All files shown as "unchanged", since they are.

Actual behavior
---------------
The restic scan takes about 8 hours, every time, even with no source files whatsoever changed. Despite this, all files are show as "changed".

Steps to reproduce the behavior
-------------------------------
1. Create a Btrfs subvolume and fill it with around 894 GB of files.
2. Create a Btrfs read-only snapshot of it (`/pictures/restic`, in this case)
3. Let restic back up that Btrfs snapshot via SFTP to a remote server (command see above)
4. Remove Btrfs snapshot, immediately create it anew (without modifying any of the 894 GB of files in between).
5. Let restic back up that Btrfs snapshot again

Do you have any idea what may have caused this?
-----------------------------------------------
No. Source files aren't changed, cache dir has about 190 MB and doesn't grow much, on each run.

Do you have an idea how to solve the issue?
-------------------------------------------
No. Running out of ideas to try. Added `--quiet` to see whether that changes scanning behavior, but it doesn't.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I want to like it (and use it). It's just that 8 hours of constant HDD scratching after no file changes whatsoever make me want to give up.

**Comment by greatroar** [comment]
Maybe try the flag --ignore-inode. If the inodes in the snaphots are not consistent, restic will think all your files have been replaced.

**Comment by rfkat** [comment]
That seems to work, at least for files:
```
using parent snapshot 88e6c46f

Files:           0 new,     0 changed, 114299 unmodified
Dirs:            0 new,  1432 changed,     0 unmodified
Added to the repository: 77.874 MiB (26.721 MiB stored)

processed 114299 files, 892.913 GiB in 0:56
snapshot 55b90d8e saved
```
Thanks!
