### ISSUE TITLE
Add an option for incremental restore snapshot by leveraging difference comparasion of two snapshots

### ISSUE THREAD

**Issue by rainbow-ce** [restic/restic#4093]
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.17.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Currently, restic can only restore the full snapshot content. But in some cases, there are already existing previous snapshot content in the restore target location, it's time consuming to make a full restore in this case.
In https://github.com/restic/restic/issues/2348#issuecomment-553436818, one way to do this is to compare the target file modify date and size with snapshot meta data. In this way, restic need to scan the target location first.
In https://github.com/restic/restic/issues/2348#issuecomment-740527540, it uses `restic mount` and `rclone` together to accomplish incremental restore.  In this way, restic incremental restore is dependent on external command. And `restic mount` would constantly sync remote status in the background which consume network resources in case there are lots of backups.

So I'm proposing a more direct way to accomplish this, which is to add an option in command `restic restore` for user to choose if they want to leverage the result of `restic diff <snapshot1> <snapshot2>`. 
I see in the implementation of diff command, the `Comparer` can get a list of new/delete/modified file list. I think this information can be used to restore file on the target snapshot if user make sure the data consistency on the target restore location.
In this way, restic can generate a serial of restore operation such as creating/updating/deleting files on target destination without extra scanning effort, as well as preventing full restore every time.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Use new `restic restore` option to accomplish incremental restore restic snapshot content leveraging previous snapshot information.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
> if user make sure the data consistency on the target restore location.

As discussed in https://github.com/restic/restic/pull/3425#issuecomment-1336908260 that is a rather risky assumption to make. I'd rather prefer to provide a `restore --sync snapshot-ID` command, which would restore/remove files as necessary and could skip already up-to-date files.

That will be a bit slower than the suggestion here, but will be far easier to use correctly. With a bit of scripting it should already be possible to create the include patterns to just let the `restore` command restore only the modified files.

**Comment by JsBergbau** [comment]
Any update about the a `restore --sync` command since the pull request making `restore` directly resumable has been closed? Since mounting a snapshot and using `rsync` is a lot slower it would be great to have a `restore --sync` option. https://github.com/restic/restic/issues/3828

**Comment by MichaelEischer** [comment]
Closing in favor of https://github.com/restic/restic/issues/4817
