### ISSUE TITLE
Archiver file change detection triggered by filesystem mtime epsilon

### ISSUE THREAD

**Issue by seth-hunter** [restic/restic#4097]
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on linux/amd64

How did you run restic exactly?
-------------------------------
restic -r /tmp/repo backup -nvv --ignore-inode /foo
...
modified  /foo/bar.txt saved in 0.419s (0 B added, 0 B stored)
...

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local file system

Expected behavior
-----------------
File was unchanged, but underlying file system changed. File should not have been read.

Actual behavior
---------------
File is unchanged, so file should not be read.

Steps to reproduce the behavior
-------------------------------
See diagnosis below.

Do you have any idea what may have caused this?
-----------------------------------------------
File was originally backed up from one underlying filesystem (e.g. xfs), then backed up again from a different underlying filesystem (e.g. JuiceFS w/ SQL metadata) that natively stores mtime with a different precision (copied between filesystems with rsync -axHAX). In this example, the new filesystem truncated mtime to 1 microsecond, resulting in a detected mtime change. 

Do you have an idea how to solve the issue?
-------------------------------------------
internal/archiver/archiver.go:fileChanged() can implement a .Round() or an epsilon comparison of mtime values, using a non-default user-configured timestamp epsilon value. Is this a (small) bit of complexity restic is willing to take on, or is it an explicit expectation / intended requirement that underlying filesystem must implement full nanosecond-level precision for mtime?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Love restic!!

**Comment by greatroar** [comment]
The assumption in restic is that the mtime simply does not change. Do you regularly switch back and forth between filesystems, or is this a one-time migration? For the latter use case, IMHO the suggested solution is too much complexity. Adding an option means the docs get longer and harder to read/search for everyone.

**Comment by MichaelEischer** [comment]
Closing since there was no feedback and this special case is likely not worth the additional complexity.
