### ISSUE TITLE
signed config-files to avoid plain text passwords?

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4098]
Output of `restic version`
--------------------------
always latest?

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
It would be nice to have signed config-files for backup and maintenance tasks.

Config files should contain the folders to backup, excludes and so on but of course NOT the repository password.
-> maybe just a list of command line args.

Because the file is signed (with something from the repo so it can be validated against it) there should be no need to expose the password in environment variables and files.
Also there would be no issue if everyone can read the config file because if someone changes it the signature does not match the content and therefore the file is invalid.

What are you trying to do? What problem would this solve?
-------------------------------------------------------
I'm thinking about using restic to backup my files (currently only using robocopy without versioning, deduplication, ...)
But I don't like to expose the plain password somewhere.

Config files would also make wrapper scripts obsolte (hopefully).

With the mentioned idea (if it's possible) we could have a backup_host1.restic, backup_host2-user_foo.restic, forget_and_prune.restic and so on but no one would be able to restore data without the password (but would be possible with a restore.restic)

And if a file is not signed restic can simply ask for the password.

[edit]
After watching an older ccc video it serms that the password is needed to en-/decrypt the data.

But adding the plain password to the environment or a file "feels" wrong. ;-)

To be clear: I'm not talking about asymetric encryption.
My "problem" is just the plain-text password that allows the access to the whole repo.
[/edit]

**Comment by MichaelEischer** [comment]
> And if a file is not signed restic can simply ask for the password.

I don't understand what you're proposing. A signature does **not** encrypt data, it merely prevents unauthorized modifications of data. Thus, this cannot work.

It sounds like you suggest that restic could use a signed config file and then extract enough information from it such that it can access the repository. However, this would make that config file the equivalent of a plain text password. In fact, if you use a modified restic binary, then that would be able to just extract all encryption keys from it. In other word, that config file would just be another case of security by obscurity.

The usual solution is to have a password file only readable by the user running the backup. Or to request the password from a password manager using the password-command. The ideal solution would be #187, but that is more of a long term goal.

**Comment by AlBundy33** [comment]
@MichaelEischer the idea was to have a config file with fixed parameters that can be executed without password
e.g. `-r /mnt/backup backup --one-file-system /`
-> or some other fomat (xml, yaml, json, ...)

with this only the configured command can be executed and the password is not exposed.

In my opinion a plain text password is a security risk in case your system is compromised because it gives you full access to the repository.

but you are right - with a modified restic executable an attacker could workaround al restrictions.

But as an attacker I would do something like `grep -Ri password /` on a compromised system.

**Comment by MichaelEischer** [comment]
> But as an attacker I would do something like `grep -Ri password /` on a compromised system.

Please have a look at the `--password-command ` option, that would allow you to e.g. retrieve the password from a password manager. However, as restic requires access to the password, this means that an attacker on a compromised host will also be able to access it. You can add some obfuscation layers on top of that, which is already possible using the `--password-command` option. But as I've said that is only security by obscurity and won't prevent any determined attacker from retrieving the password.

**Comment by deajan** [comment]
Maybe this answer is a longshot, but I've built a restic wrapper that uses config files, and stores the repository URI and password in the config file via AES-256 encryption.
The AES-256 key is still readable in the wrapper source, but the wrapper itself can be compiled into an executable, making the process more complicated.

An attacker would require read access to the config file, access to the executable, and alot of coffee in order to debug that executable, which also uses compile time and execution time obfuscation to make it more difficult to gather the key.

See https://github.com/netinvent/npbackup for more details

**Comment by MichaelEischer** [comment]
> An attacker would require read access to the config file, access to the executable, and alot of coffee in order to debug that executable, which also uses compile time and execution time obfuscation to make it more difficult to gather the key.

Did I miss something, or is the wrapper actually calling an external restic binary? In that case, you use strace or whatever debugging tool is available on the platform and then you just watch the wrapper pass the repository URL and password to restic.

**Comment by deajan** [comment]
> Did I miss something, or is the wrapper actually calling an external restic binary? In that case, you use strace or whatever debugging tool is available on the platform and then you just watch the wrapper pass the repository URL and password to restic.

No you did not. Indeed my wrapper launches the restic binary in a subprocess, to which it passes the url & password via env variables, which only reside in said subprocess, and are wiped from memory as soon as restic used them.

The added security here comes from the fact that the repo URL and password aren't stored in clear text at rest, and will only be decrypted when needed.
So yes, an attacker with full access to the machine will end up finding the environment variables that are used, but an attacker that can read and steal copy files / scripts won't.
