### ISSUE TITLE
integrated (s)ftp-server as alternative for mount

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4099]
Output of `restic version`
--------------------------
latest?

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
As an addition to the mount-command an integrated (s)ftp-server would be nice.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Windows does not support the mount command and maybe not all own linux-installations have fuse installed.
With an integrated (s)ftp-server we could use different ftp clients and therefore have simple gui to access backups on all platforms.

**Comment by MichaelEischer** [comment]
There are plans to add FUSE support for windows #2862 . There's also an issue to add support for WebDAV #485 which is likely more useful.

On Linux installations I don't see any benefit from (s)ftp support, just install fuse and use the regular sftp support there.

**Comment by MichaelEischer** [comment]
I'll keep this issue open for now to see whether there's interest in the feature. But we'll likely rather add WebDAV support.

**Comment by AlBundy33** [comment]
This would also help on linux if you are not the owner of the system and cannot install fuse.
e.g. if you backup to a server at work or school.

webdav may also be an option.

**Comment by AlBundy33** [comment]
btw. kopia mounts the snapshots as network-drive on windows

**Comment by AlBundy33** [comment]
closed in favor of #485
