### ISSUE TITLE
tar dump of Windows stdin snapshot with 32-bit binary cannot be read by gnu tar

### ISSUE THREAD

**Issue by philaris** [restic/restic#4101]
Output of `restic version`
--------------------------
Windows latest stable binary for creating a snapshot from stdin:
```
restic 0.14.0 compiled with go1.19 on windows/amd64
restic 0.14.0 compiled with go1.19 on windows/386
```

When creating the tar dump of a Windows stdin snapshot, the issue appears with 32-bit versions in different architectures:
```
restic 0.14.0 compiled with go1.19 on linux/arm
restic 0.14.0 compiled with go1.19 on windows/386
```

The version of gnu tar is 1.34:
```
$ tar --version
tar (GNU tar) 1.34
```

How did you run restic exactly?
-------------------------------

In a Windows machine, create a repository and a snapshot from stdin. For example, open a cmd prompt:
```
mkdir testrestic
cd testrestic
```
Download a Windows version of restic in the new folder and unzip it there. In this example, I downloaded the 32-bit version [restic_0.14.0_windows_386.zip](https://github.com/restic/restic/releases/download/v0.14.0/restic_0.14.0_windows_386.zip). Then:
```
echo testpass > testpassfile.txt
restic_0.14.0_windows_386 --password-file=testpassfile.txt --repo=repo init
echo from_stdin | restic_0.14.0_windows_386 --password-file=testpassfile.txt --repo=repo backup --stdin
```

Then dump a tar file of the snapshot **from any 32-bit binary version** of restic. I use the same binary that I downloaded before.
```
restic_0.14.0_windows_386 --password-file=testpassfile.txt --repo=repo dump latest / > t32bit.tar
```

Then try to list the contents of the created tar file with gnu tar:
```
$ tar tvf t32bit.tar
tar: Extended header gid=-1 is out of range 0..4294967295
tar: Extended header uid=-1 is out of range 0..4294967295
-rw-r--r-- 0/0              13 2022-12-26 09:30 stdin
tar: Exiting with failure status due to previous errors
```
(Do not use bsdtar of Windows; the problem only manifests with gnu tar.)

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
I used the filesystem backend for the repository, but the issue would appear in any backend.

Expected behavior
-----------------

I would expect that the tar file is read by gnu tar without gnu tar exiting with failure status.

Actual behavior
---------------

Gnu tar exits with failure status.

Steps to reproduce the behavior
-------------------------------

See above.

Do you have any idea what may have caused this?
-----------------------------------------------
For a stdin snapshot, the uid and the gid of the file are set in <https://github.com/restic/restic/blob/90fb6f70b441132d65648de7b7045e2678ae1b48/internal/restic/node.go#L567-L575>

In a Windows system <https://pkg.go.dev/os#Getuid> and <https://pkg.go.dev/os#Getgid> return -1. This is converted to a `uint32` value of  4294967295. This value also appears with:
```
> restic_0.14.0_windows_386 --password-file=testpassfile.txt --repo=repo ls -l latest
repository 5c042ca5 opened (repository version 2) successfully, password is correct
snapshot 658d61b5 of [C:\stdin] filtered by [] at 2022-12-26 15:10:17.3563627 +0100 CET):
-rw-r--r-- 4294967295 4294967295     13 2022-12-26 15:10:17 /stdin
``` 

Then, when the snapshot is dumped to a tar file, the uid and gid are converted to `int` 
https://github.com/restic/restic/blob/78c7dd53efa035251d6b65dc4be106f45526f139/internal/dump/tar.go#L41-L52

In a 32-bit binary, the `uint32` value 4294967295 is converted to an `int` value of -1. 
See also <https://pkg.go.dev/archive/tar#Header>.

Do you have an idea how to solve the issue?
-------------------------------------------

I would put a smaller value in the `uint32` uid and gid variables of the node.  I will implement a fix.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is fine! Thanks for this great software!

**Comment by greatroar** [comment]
Has this been solved by #4103?

**Comment by philaris** [comment]
Yes, I thought I had closed this. See https://github.com/restic/restic/issues/4103#issuecomment-1365968619. Please close it if you agree.

**Comment by greatroar** [comment]
I can't close this, since I'm not a repo owner.
