### ISSUE TITLE
32-bit binary tar dump of repository with high uid, gid entries cannot be read by gnu tar

### ISSUE THREAD

**Issue by philaris** [restic/restic#4103]
This issue is related to #4101 and the discussion in #4102 with @greatroar.

Output of `restic version`
--------------------------
When creating the tar dump, the issue appears with 32-bit versions in different architectures:
```
restic 0.14.0 compiled with go1.19 on linux/arm
restic 0.14.0 compiled with go1.19 on windows/386
```

The version of gnu tar is 1.34:
```
$ tar --version
tar (GNU tar) 1.34
```

How did you run restic exactly?
-------------------------------
This is from #4101.

Create a repository with a single snapshot and a single file entry in the snapshot with a high uid and/or gid. Here is an example with uid and gid 4294967295 in the node of the snapshot of the repository, accomplished with a backup of stdin in Windows (more details in #4101).
```
> restic --password-file=testpassfile.txt --repo=repo ls -l c7afaf40
repository 1a634ddc opened (repository version 2) successfully, password is correct
snapshot c7afaf40 of [D:\stdin] filtered by [] at 2022-12-26 09:30:25.2227589 +0100 CET):
-rw-r--r-- 4294967295 4294967295     13 2022-12-26 09:30:25 /stdin
```

Then dump a tar file of the snapshot **from any 32-bit binary version** of restic. I use the same binary that I downloaded before.
```
restic_0.14.0_windows_386 --password-file=testpassfile.txt --repo=repo dump latest / > t32bit.tar
```

Then try to list the contents of the created tar file with gnu tar:
```
$ tar tvf t32bit.tar
tar: Extended header gid=-1 is out of range 0..4294967295
tar: Extended header uid=-1 is out of range 0..4294967295
-rw-r--r-- 0/0              13 2022-12-26 09:30 stdin
tar: Exiting with failure status due to previous errors
```
(Do not use bsdtar of Windows; the problem only manifests with gnu tar.)

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Filesystem, but the backend is not relevant.

Expected behavior
-----------------
I would expect that the tar file is read by gnu tar without gnu tar exiting with failure status.

Actual behavior
---------------
Gnu tar exits with failure status.

Steps to reproduce the behavior
-------------------------------
See above.

Do you have any idea what may have caused this?
-----------------------------------------------
The value of uid and gid in a restic node are stored as `uint32`. In our example we have a value of 4294967295.
```
> restic_0.14.0_windows_386 --password-file=testpassfile.txt --repo=repo ls -l c7afaf40
repository 1a634ddc opened (repository version 2) successfully, password is correct
snapshot c7afaf40 of [D:\stdin] filtered by [] at 2022-12-26 09:30:25.2227589 +0100 CET):
-rw-r--r-- 4294967295 4294967295     13 2022-12-26 09:30:25 /stdin
``` 

Then, when the snapshot is dumped to a tar file, the uid and gid are converted to `int` 
https://github.com/restic/restic/blob/78c7dd53efa035251d6b65dc4be106f45526f139/internal/dump/tar.go#L41-L52

In a 32-bit binary, the `uint32` value 4294967295 is converted to an `int` (`int32`) value of -1. 
See also <https://pkg.go.dev/archive/tar#Header>.

The problem appears with every value from 2147483648 to 4294967295 (including) which is mapped to a negative value of type `int32`.

Do you have an idea how to solve the issue?
-------------------------------------------
We should adapt the tar dump to not create negative values for uid and gid in the case of 32-bit binaries. We could substitute values in the range [2147483648, 4294967295] with the zero or the maximum value of `int32`. Should we do this transformation just for 32-bit binaries?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Absolutely!

**Comment by MichaelEischer** [comment]
This is mostly a limitation of the tar package in the go standard library (https://github.com/golang/go/blob/master/src/archive/tar/common.go#L26). It internally converts the uid/gid to int64 which would be sufficient for our usages.

As uids between 2^30 and 2^31 - 2 are valid, I don't think we should touch them. But as mentioned in https://github.com/restic/restic/pull/4102#issuecomment-1365940739, it should be fine to convert a uid/gid of `-1` to `0`. That special case should only apply on 32-bit systems, that is if `header.Uid == -1`. The latter is never true on 64-bit systems.

**Comment by philaris** [comment]
OK, I am writing something along these lines @MichaelEischer.
