### ISSUE TITLE
forget: is --prune executed with --dry-run?

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4112]
Output of `restic version`
--------------------------
```
restic 0.14.0 compiled with go1.19 on linux/amd64
```

How did you run restic exactly?
-------------------------------
```
$HOME/bin/restic --repository-file $HOME/bin/.restic_repository --password-file $HOME/bin/.restic_password forget --keep-within-hourly 24h --keep-within-daily 7d --keep-within-weekly 1m --keep-within-monthly 12m --keep-within-yearly 3y --tag "" --host $HOSTNAME --prune --dry-run
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
sftp

Expected behavior
-----------------
prune not executed because of --dry-run 

Actual behavior
---------------
not sure if prune is executed or not - output is not really clear.

```
Would have removed the following snapshots:
{55803c2c fdb6bcc0}

2 snapshots have been removed, running prune
loading indexes...
loading all snapshots...
finding data that is still in use for 4 snapshots
[0:09] 100.00%  4 / 4 snapshots
searching used packs...
collecting packs for deletion and repacking
[0:02] 100.00%  1407 / 1407 packs processed

to repack:         30606 blobs / 17.197 MiB
this removes:         39 blobs / 105.196 KiB
to delete:             0 blobs / 0 B
total prune:          39 blobs / 105.196 KiB
remaining:        254628 blobs / 22.621 GiB
unused size after prune: 122.595 MiB (0.53% of remaining size)
```
forget says "Would have removed the following snapshots" but prune sounds like it was executed.

Of course this is not a major issue but still a little bit inconsistent. 🙂 

Steps to reproduce the behavior
-------------------------------
see above

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------
better text 🙂 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
What do you think about #4117? Would that have helped or do you have some other message in mind?

**Comment by AlBundy33** [comment]
Is think this makes it clear enough.

I know it's a little bit pedantic but maybe the output "2 snapshots have been removed, running prune" should also be changed. 🙂

**Comment by MichaelEischer** [comment]
Here you go: https://github.com/restic/restic/pull/4117/commits/6bbb9ef52e6917b5fa97c001ed14716857d92c4a

**Comment by AlBundy33** [comment]
looks fine for me in 0.15.0 👍
