### ISSUE TITLE
more information in stats

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4113]
Output of `restic version`
--------------------------
latest

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
it would be nice if stats would show the real size of the backuped files, the size in repository (after deduplication) and maybe the space that is still available to store new snapshots.
especially the last one would be nice but not sure if you can get this information from all storages.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
more information about the used/available space

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
> it would be nice if stats would show the real size of the backuped files, the size in repository (after deduplication)

That information is already available.

> maybe the space that is still available to store new snapshots.

For most backends there's currently no way to retrieve that information. In particular, for cloud storages that information might not be available or relatively meaningless.

**Comment by AlBundy33** [comment]
didn't know the --mode parameter
is there a reason why not all values a shown by default?
Or what about an additional mode "all"?

it's a pity that the free space cannot be determined 😞

**Comment by MichaelEischer** [comment]
> didn't know the --mode parameter
> is there a reason why not all values a shown by default?
> Or what about an additional mode "all"?

Each mode has to be calculated separately. That is, unless you need every single value (which probably isn't the case) it will just be slower than just using the one or two modes which you're actually interested in.

> it's a pity that the free space cannot be determined disappointed

It would be possible for local / sftp backups. However, that information in itself is not particularly help. e.g. 10GB free space can often be sufficient to backup a 500 GB data set, if not much has changed. Conversely, it is rather complex to estimate before hand how much new data would be added by a backup (unless you run `backup --dry-run`).

What might be more useful in the long run would be a way for restic to automatically ensure that a repository stays below a certain size, although I'm not sure whether that's possible to implement in a reliable way.

**Comment by AlBundy33** [comment]
The idea about the free space was not to check if there is enough space for the next backup.
I thought this more as an additional information for the user to have the available size directly in the output of restic instead of checking it separately.

I think this can be helpful if the output is send by mail or other notifications.

**Comment by fd0** [comment]
We're trying to limit the scope of what restic can do in order to keep a lid on its complexity.

If you want the free space of some volume sent via email, you can do that yourself by running `df ` (or a similar tool) after restic is run.

I'm therefore closing this issue. Please feel free to add further comments. Thanks!

**Comment by AlBundy33** [comment]
The problem is, that `df` doen't work on windows. :-)
--> I know that `dir c:\` shows the free space in the last line ;-)

II totaly understand the goal to limit the scope of restic but having this information in the stats-output would give the user more informations about the storage without the need to script something around restic.
But this makes only sense if you can get informations from different storages and not only for local and sftp.
