### ISSUE TITLE
Integrity check failed: Data seems to be missing.

### ISSUE THREAD

**Issue by tbm** [restic/restic#4115]
restic 0.14.0 compiled with go1.19 on linux/amd64

I get:

```
restic prune
repository e5a75abd opened (repository version 1) successfully, password is correct
found 11 old cache directories in /home/tbm/.cache/restic, run `restic cache --cleanup` to remove them
loading indexes...
loading all snapshots...
finding data that is still in use for 29 snapshots
[0:11] 100.00%  29 / 29 snapshots
searching used packs...
{<data/08c4b2df> <data/0a142100> <data/144bd403> <data/19436b24> <data/1fbcff8c> <data/201b86a0> <data/29310640> <data/30132750> <data/482c1b13> <data/53242557> <data/5380db8d> <data/62bb1094> <data/7a6f923b> <data/89e931d6> <data/92370782> <data/92be94f2> <data/93c37ea7> <data/968042f7> <data/9b79f842> <data/a8785d59> <data/ab3453d0> <data/bbd41c7c> <data/e306aaea> <data/ee0b789e>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
Fatal: index is not complete
```

I wasn't going to report this because I know the repo is damaged (I had data loss on my backup drive due to the drive breaking), but since it's telling me to file a bug, maybe it's useful to you?

I have the whole log which I can share in private.

Basically I did `check` which told me there are problems (`not referenced in any index`, run prune to fix this; also `ciphertext verification failed`).  I then ran `prune` which told me `The index references 9 needed pack files which are missing from the repository`; I then ran `rebuild-index`; and now `prune` is telling me the above.

I know the repo is broken, so it's probably best to just close this, but if you think restic did something wrong, I can send the whole log (email me at tbm@cyrius.com).

**Comment by MichaelEischer** [comment]
> I wasn't going to report this because I know the repo is damaged (I had data loss on my backup drive due to the drive breaking), but since it's telling me to file a bug, maybe it's useful to you?

Thanks for the bug report. We're interested in learning how/why repositories get damaged, as that way we get an idea which problems are frequent enough to eventually warrant additional measures to protect the repository integrity (e.g. #256 in your case).

Based on the commands you've run, the error reported by `prune` is to be expected. As the reason for the repository damage is also clear, there's not much left to investigate here.

> also `ciphertext verification failed`)

If you want to repair the repository, take a look at https://github.com/restic/restic/issues/828#issuecomment-706186047 . We'll also eventually add a `repair snapshots` command, but that will likely still take a few months.

**Comment by tbm** [comment]
> As the reason for the repository damage is also clear, there's not much left to investigate here.

Yeah, I'd agree.  You tagged this issue with "need feedback" rather than closing it.  Do you need any additional input from me?

> If you want to repair the repository, take a look at https://github.com/restic/restic/issues/828#issuecomment-706186047 

Thanks that's a very detailed write-up!

**Comment by MichaelEischer** [comment]
> Do you need any additional input from me?

I just wanted to wait for whether you plan to repair the repository or not. So let's just close the issue now, if you have problems with repairing it, then feel free to ask. Sorry, for the confusion.
