### ISSUE TITLE
Restic restore fails with `killed` message

### ISSUE THREAD

**Issue by ccaneke** [restic/restic#4118]
Restoring a root backup snapshot to `/` fails with the message `killed`.

I've run `restic stat` to confirm that the snapshot is not larger than the available hard disk space.

Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19.2 on linux/amd64

How did you run restic exactly?
-------------------------------

```sudo restic -vv -r /repo restore 826622 --target /```

**Comment by AlBundy33** [comment]
is it possible that you're trying to override some system-files that may cause the error?
youd could try to restore one path after another with the --path parameter
https://restic.readthedocs.io/en/latest/050_restore.html

**Comment by ccaneke** [comment]
@AlBundy33 Thanks, that may be it. It would be very helpful to have an error message, even with `-vv` there's none.

I'll have to checkout the - - path flag.

After mounting can I use `rsync` instead of `cp`?

**Comment by ccaneke** [comment]
> is it possible that you're trying to override some system-files that may cause the error? you could try to restore one path after another with the --path parameter https://restic.readthedocs.io/en/latest/050_restore.html
> 
> or use the mount command and restore with `cp` - I would assume that you'll also get some kind of error.

I just read the doc you linked. Do you mean to say `--include` instead of `--path`? The former restores the specified path only where as I don't think the latter does.

**Comment by AlBundy33** [comment]
you're right: --include instead of --path 

I think the easiest way is to use mount with cp, rsync or any copy-tool you want

**Comment by greatroar** [comment]
"Killed" usually means the process took too much RAM and the kernel's OOM killer stepped in (check /proc/sys/vm/overcommit_memory, if that's not 2 then the OOM killer is on). Restic mount should take less memory than restic restore and you can use rsync or any other tool to copy out of the mount point.

**Comment by MichaelEischer** [comment]
Closing as there's not enough information to debug.
