### ISSUE TITLE
backup -v should output the changed files like diff

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4120]
Output of `restic version`
--------------------------
latest...

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
to create a good exclude list it would be nice if `backup -v --dry-run /` would display the changed files like diff would do if you compare snapshots.
I know that -vv displayes a lot of files but most of them beginning with "unchanged".

What are you trying to do? What problem would this solve?
---------------------------------------------------------
easy way to build an exclude-list

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by AlBundy33** [comment]
it hink it's sufficient to change
https://github.com/restic/restic/blob/59a90943bb0c780fa69fafe752b2be4a98014397/internal/ui/backup/text.go#L90
and change b.VV to b.V for all lines that output new or modified content.

**Comment by MichaelEischer** [comment]
Duplicate of #1805.

> and change b.VV to b.V for all lines that output new or modified content.

That will help with this specific use case, but is far too noisy for others.

**Comment by AlBundy33** [comment]
and moving the "unchanged-outputs" to -vvv?

**Comment by MichaelEischer** [comment]
> and moving the "unchanged-outputs" to -vvv?

Why not use `grep` or `jq` to filter out these lines? We likely won't change them until we get around to rework the logging.

**Comment by AlBundy33** [comment]
Because we wouldn't have to deal with extra (platform depending) scripts/commands.
In my opinion, the "real" changes (add, remove, change) and unchanged files have different importance and should be logged at different levels of verbosity.

**Comment by w-hc** [comment]
second this. a dedicated log level for modifications is very helpful.
