### ISSUE TITLE
tasks/profiles stored in repository

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4121]
Output of `restic version`
--------------------------
latest

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
What would you think about saved profiles or tasks in the repository?
for example instead of running
```
$HOME/bin/restic --repository-file $HOME/bin/.restic_repository --password-file $HOME/bin/.restic_password backup --one-file-system --exclude-caches --exclude-if-present .nobackup --exclude-file $HOME/bin/.restic_excludes /etc/ /home/ /opt/
```
you could define a task backup_server_xy with
```
backup --one-file-system --exclude-caches --exclude-if-present .nobackup --exclude-file $HOME/bin/.restic_excludes /etc/ /home/ /opt/
```
and execute it with
```
$HOME/bin/restic --repository-file $HOME/bin/.restic_repository --password-file $HOME/bin/.restic_password task backup_server_xy
```
maybe also with additional args (more folders, --dry-run, ...)

I know that there are a lot of wrappers for restic but in my opinion it would be nice to have an all-in-one-solution.
it would also allow to reuse tasks on different machines and is also a safe place for your configuration because in case you have to reinstall your system you don't have to think about what you have to backup because it's defined in the repo.

Same applies for a forget task. 🙂 

What are you trying to do? What problem would this solve?
---------------------------------------------------------
more (centralized) configuration than scripting or using restic-wrappers.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
What about the suggested config file support #16 ?

**Comment by rawtaz** [comment]
@AlBundy33 Wrappers exist for a reason. Take a look at https://github.com/creativeprojects/resticprofile for your needs.

**Comment by AlBundy33** [comment]
The idea was to have the profiles inside the repository - because configuration-files or seperate scripts you have to backup and restore seperately.

Defining them inside the repo has the advantage to have them always available (on existing or new machines, on each operating system, ...)

And as mentioned before I know that there are a lot of wrapper scripts but in my opinion an all-in-one-solution would be better (especially for such basic features).

Another advantage would be that we don't have to trust additional applications/scripts/developers.

**Comment by MichaelEischer** [comment]
The suggestion essentially amounts to adding a backup scheduler to restic. But that is out of scope for now.

**Comment by rawtaz** [comment]
@AlBundy33 I do see some use cases for this, but going into detail with them it does come down to pretty limited ones, for various reasons. I think config file support is a much better path in the long run.
