### ISSUE TITLE
Data blobs seem to be missing, aborting prune to prevent further data loss!

### ISSUE THREAD

**Issue by swarfer** [restic/restic#4123]
Output of `restic version`
--------------------------
on the server
   restic version
   restic 0.8.3
  compiled with go1.10 on linux/386
on the desktop
   restic version
   restic 0.10.0 compiled with go1.15.2 on windows/amd64

How did you run restic exactly?
-------------------------------
restic -r sftp:david@192.168.1.85:/mnt/hump/backups/david/restic prune
target server is Ubuntu Linux on my local lan
only the password was set in environment

output:
repository 4cdcd60e opened successfully, password is correct
counting files in repo
building new index for repo
[10:50] 100.00%  41897 / 41897 packs
incomplete pack file (will be removed): d90da62033924b13950f969c155eb88840e049e0f9f48ec15eaff8e137d4c4f6
incomplete pack file (will be removed): 96caebf7f63ada2c34000292f1cec80e2bafdd9b735afd0d4cb4d617621832f6
incomplete pack file (will be removed): e2de0ed6ca427786ad142916f7b5ca1b0f8940d5c0266a9e31b99ae1b6e7e77f
incomplete pack file (will be removed): b226a61f3ecbd1cef9966b2944affd30874898a6d8bfdd2c33d1e8f3b971fe80
incomplete pack file (will be removed): 64dccc21c85c50b973d3b881079e27c28c475b88fc26ac49d5548948bec4faef
incomplete pack file (will be removed): a047166e2fa56d12d66ceaebf32ffb3821b9354469798bb8ecad03af51fc33ec
incomplete pack file (will be removed): 0c5d8e5b2c5c1efec3aa40913eef902839d5888aa38b651aa15e5e35ce501190
incomplete pack file (will be removed): d565292103edde1248877110249d6d4ac65f6aae63338027d8f35a3c26a439dc
incomplete pack file (will be removed): f102ca24ca1832fa59e61323eec768f7252a3ef307d0161345c270e370c0811b
incomplete pack file (will be removed): 745ce1f3bf96cabe599997667f11769ee5c0d40fae667dc3a46105b867e10bda
incomplete pack file (will be removed): 4b906dc0c62d2002e16bc4e91443f32ac072316082aefef72e143ec44f245fd4
incomplete pack file (will be removed): 08b90ae2c2733e85ab209603e0d9612f3435e008b8ca6c384faddbe32c20539f
repository contains 41885 packs (157587 blobs) with 203.956 GiB
processed 157587 blobs: 20731 duplicate blobs, 27.126 GiB duplicate
load all snapshots
find data that is still in use for 18 snapshots
[0:00] 100.00%  18 / 18 snapshots
Fatal: [<data/dc1b3460> <data/882c0103> <data/94b661cc> <data/e6dee12e> <data/5177a5af> <data/200f6b00> <data/b863a701>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
my local linux server, Ubuntu server 
uname -a
Linux vidiot.local 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:15:44 UTC 2022 i686 i686 i686 GNU/Linux
**cat /etc/os-release**
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Expected behavior
-----------------

fix the errors it found, or at least provide instructions on how to fix them..

Actual behavior
---------------

aborted prune and told me to tell you about it

Steps to reproduce the behavior
-------------------------------

I ran it twice with the same result.   the server side error might be due to a power out during 

Do you have any idea what may have caused this?
-----------------------------------------------

possibly the version difference, I will upgrade the windows end and run the prune on the linux end to confirm

Do you have an idea how to solve the issue?
-------------------------------------------

no

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

normally it does, but not today

**Comment by swarfer** [comment]
upgraded to 0.14.0
first it said run rebuild-index, claimed success
but prune still fails:
repository 4cdcd60e opened (repository version 1) successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 18 snapshots
[0:01] 100.00%  18 / 18 snapshots
searching used packs...
{<data/200f6b00> <data/5177a5af> <data/882c0103> <data/94b661cc> <data/b863a701> <data/dc1b3460> <data/e6dee12e>} not found in

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
Fatal: index is not complete

**Comment by MichaelEischer** [comment]
As the repository was created using a very old restic version, it's probably not worth investigating further how the repository was damaged. Or did you notice anything suspicious before `prune` failed, which could explain the damage?

The simplest way to repair the repository is probably to use `restic find --blob 200f6b00 5177a5af 882c0103 94b661cc b863a701 dc1b3460 e6dee12e` to find all snapshots using the missing data and the use the `forget` command to delete them. For more detailed steps have a look at "Route 2" in https://github.com/restic/restic/issues/828#issuecomment-706186047 .

**Comment by swarfer** [comment]
Thankyou
I did upgrade both ends to 0.14.0 and then reran the backup which copied 1 or two files and that appeared to fix it to where
I could run the prune, then I removed backups older than 6 months and re-pruned and all is reported as good.
