### ISSUE TITLE
How to get regex exclude patterns to work with restic ?

### ISSUE THREAD

**Issue by deajan** [restic/restic#4126]
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Support for exclude regexes.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I have various files with excludes like https://github.com/deajan/linuxscripts/blob/master/burp/incexc/generic_exclusions or https://github.com/deajan/linuxscripts/blob/master/burp/incexc/windows_settings which I use to slim down full drive backups of user computers.

So far, I'm trying to use the restic exclude glob patterns, but I am stuck when it comes to more complete exclusions, like:
```
# Generic cache dir
exclude_regex = .*/([Ff]ont|[Ff]ile|[Dd]ist|[Nn]ative|[Pp]lay|[Pp]lugin|[Aa]sset|[Aa]ctivities|[Ss]cript|[Gg]pu|[Cc]ode|[Ll]ocal|[Ss]ession|[Ww]eb|JS|CRL)? ?[Cc]ache
exclude_regex = .*/[Cc]ache[Ss]torage
```

Here I try to exclude all "Font cache", "File cache", "Session Cache", etc... folders, which depending on browsers / applications will have mixed or only lowercase characters.
Of course I could write a long list of exclude patterns, but isn't there a more elegant way of achieving this ?

Best regards.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I am currently writing a restic wrapper tool for windows with CLI and minimalistic GUI that allows end user to view and restore data himself. Getting to really love restic.

**Comment by MichaelEischer** [comment]
> Of course I could write a long list of exclude patterns, but isn't there a more elegant way of achieving this ?

You'll have to unroll the patterns somewhat. Exclude patterns are matched using globbing, see https://restic.readthedocs.io/en/stable/040_backup.html#excluding-files . There's also the option for case insensitive matching.

**Comment by deajan** [comment]
Well, I've already read the docs, and I must admit that the doc link to https://pkg.go.dev/path/filepath#Match is far clear.
Anyway, thanks for your answer ;)
