### ISSUE TITLE
restic 0.15.0: prune -q shows output

### ISSUE THREAD

**Issue by C-Otto** [restic/restic#4147]
Output of `restic version`
--------------------------
`restic 0.15.0 compiled with go1.19.5 on linux/amd64`

How did you run restic exactly?
-------------------------------
`RESTIC_PASSWORD=x RESTIC_REPOSITORY=/some/path TMPDIR=/some/other/path RESTIC_COMPRESSION=max restic -q prune --max-unused 0%`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local file system

Expected behavior
-----------------

No output.

Actual behavior
---------------

`[0:00] 100.00%  616 / 616 packs processed` (Output provided via cron's mail)

Do you have any idea what may have caused this?
-----------------------------------------------

Regression from 0.14.0

**Comment by MichaelEischer** [comment]
Thanks for the bug report. That progress bar was actually only shown while running in quiet mode...
