### ISSUE TITLE
backend: server disconnect leads to panic

### ISSUE THREAD

**Issue by fd0** [restic/restic#415]
@benmur described an undesired behavior in #409: When the s3 server disconnects a client, restic panics and aborts the backup process. For the solution it was proposed to introduce re-trying at the s3 backend level. It looks like the minio library will add this functionality sooner or later.

We agreed that it is a good idea to have retry-functionality at the backend level, so all backends can benefit.

**Comment by fd0** [comment]
@benmur I've drafted up a small patch that allows writing all communication between restic and s3 to a file, could you please apply that patch and try to reproduce the dropped connections again?

Please find the patch here: https://gist.github.com/3f5172b9037f3819d160, then run restic with the environment variable `RESTIC_S3_TRACE=/tmp/s3trace.log`.

**Comment by benmur** [comment]
Thanks @fd0 that's great! I'll try that tomorrow. Do you prefer any kind of operation or is backup best?

**Comment by fd0** [comment]
Whatever produced the errors most reliably ;)

**Comment by benmur** [comment]
I have to let a rebuild-index finish first (opened #423 about that) but will definitely run with tracing on later.

**Comment by Bregor** [comment]
It seems, I crashed in this issue too.
Restic built just now from commit `3d27751b6923bd7513439725195f5478edf55b24`
Doing first full backup.

Full output here: https://gist.github.com/4589159dc1df8ab8749d

**Comment by cdrx** [comment]
minio/minio-go#330 has added support for retrying failed requests upstream

**Comment by harshavardhana** [comment]
> minio/minio-go#330 has added support for retrying failed requests upstream

Currently the retry retries s3 specific errors i.e which come about in the s3 error response. Will be adding more network related errors to the list as well.

**Comment by dominikschulz** [comment]
Is there anyone working on this? It's really annoying and I'd be willing to look into it.

The S3 backend probably should fall back to resumeable multipart uploads even if the file is smaller the 5MB for very slow connections and retry several times.

**Comment by fd0** [comment]
@dominikschulz you can try fetching the latest version of minio-go (with `gb vendor`) and submit this as a PR, maybe they've already fixed it.

**Comment by harshavardhana** [comment]
> @dominikschulz you can try fetching the latest version of minio-go (with gb vendor) and submit this as a PR, maybe they've already fixed it.
> 
> You can also try to implement retries in restic itself.
> 
> As far as I know, nobody is currently working on this.

retry is already fixed in minio-go - hopefully we have also fixed other issues reported by @fd0 :-) . In any case ping us https://github.com/minio/minio-go/issues

**Comment by fd0** [comment]
@harshavardhana we will, thank you :)

**Comment by fd0** [comment]
Please test the current master and let us know if the panic occurs again.

**Comment by dominikschulz** [comment]
Thanks for your patience. I finally got around to test it again.

I had to completly remove the previous bucket since `restic check` always failed with "too many open files". I may open another issue if I can reproduce that issue.

The aforementioned panic seems to be gone but unfortunately another one popped up:
```
restic backup /home
scan [/home]
scanned 3094 directories, 20247 files in 0:03
panic: Put https://mybucket.s3-eu-west-1.amazonaws.com/restic/data/2e5bd2f798550ddf461a335b9ee18670d9c53ed159155b660b64152a12182e83?partNumber=1&uploadId=Ys81nCmUqGhump72w22J4h2ZgFAR86L1_A47YjM5qX2Naqrk4Z6H1fUMJzcO0BbUcjVb1n6IV_WeQxcmPpNw95teTMGITVaiXCMj5tj5EO3Wl.C2vfF_xybu7AQeQCPT: http: ContentLength=5242880 with Body length 0

goroutine 26053 [running]:
panic(0x9ccac0, 0xc8202763c0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
restic.(*Archiver).saveChunk(0xc8203fcd70, 0x1b9e7b3c, 0x1381f4, 0x1bc1a9db800000, 0xc83320e000, 0x1381f4, 0x26a000, 0xc820408000, 0x7ff207558120, 0xc820290ae0, ...)
        /tmp/restic-build-269599465/src/restic/archiver.go:165 +0x12b
created by restic.(*Archiver).SaveFile
        /tmp/restic-build-269599465/src/restic/archiver.go:237 +0x556
```

**Comment by JohnnyLeone** [comment]
I'm expecting an error while restoring my snapshot on my minio storage. I try to restore a ~4.5GB file but every time at 669MB it breaks wit following error. Backing up the file went perfectly fine.
```
http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
obj.ReadAt
restic/backend/s3.(*s3).Load
	/tmp/restic-build-559492747/src/restic/backend/s3/s3.go:179
restic.ReadAt
	/tmp/restic-build-559492747/src/restic/readerat.go:25
restic/repository.(*Repository).loadBlob
	/tmp/restic-build-559492747/src/restic/repository/repository.go:106
restic/repository.(*Repository).LoadBlob
	/tmp/restic-build-559492747/src/restic/repository/repository.go:538
restic.Node.createFileAt
	/tmp/restic-build-559492747/src/restic/node.go:214
restic.(*Node).CreateAt
	/tmp/restic-build-559492747/src/restic/node.go:109
restic.(*Restorer).restoreNodeTo
	/tmp/restic-build-559492747/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
	/tmp/restic-build-559492747/src/restic/restorer.go:53
restic.(*Restorer).RestoreTo
	/tmp/restic-build-559492747/src/restic/restorer.go:122
main.runRestore
	/tmp/restic-build-559492747/src/cmds/restic/cmd_restore.go:135
main.glob..func13
	/tmp/restic-build-559492747/src/cmds/restic/cmd_restore.go:23
github.com/spf13/cobra.(*Command).execute
	/tmp/restic-build-559492747/src/github.com/spf13/cobra/command.go:599
github.com/spf13/cobra.(*Command).ExecuteC
	/tmp/restic-build-559492747/src/github.com/spf13/cobra/command.go:689
github.com/spf13/cobra.(*Command).Execute
	/tmp/restic-build-559492747/src/github.com/spf13/cobra/command.go:648
main.main
	/tmp/restic-build-559492747/src/cmds/restic/main.go:37
runtime.main
	/usr/lib/go/src/runtime/proc.go:185
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:2197
```
Is my problem related to this thread?

**Comment by harshavardhana** [comment]
@JohnnyLeone IMHO -  it would be easier to not mix your issue here perhaps a new issue is better?

Also do please open a github issue on minio end as well if you see any errors on the Minio side.

**Comment by fd0** [comment]
@JohnnyLeone Yes, please open a new issue and answer the questions in the issue template, then we can have a look. If it's reproducible that's even better :)

**Comment by fd0** [comment]
In the meantime, we've introduced backend retry. I'm going to close this issue for now. Thanks!
