### ISSUE TITLE
Support `-h` argument to `ls -l`

### ISSUE THREAD

**Issue by silverwind** [restic/restic#4159]
Output of `restic version`
--------------------------

restic 0.14.0 compiled with go1.19 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Support a `-h` flag on `restic -l <snapshot>` to print human-readable byte counts like `ls` does. From `ls` manpage:

```
-h, --human-readable       with -l and -s, print sizes like 1K 234M 2G etc.
```

`-h` in restic is already occupied by help, but combining `-h` and `-l` does not make sense so if that combination is encountered, take `-h` argument as `--human-readable`. Alternatively, remove the `-h` argument for help only via `--help` is more common.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Large file sizes are hard to read with `restic ls -l`:

```
$ restic ls -l b64a60a1
repository 9cbe0bce opened (repository version 2) successfully, password is correct
snapshot b64a60a1 of [/hugefile] filtered by [] at 2023-01-17 04:55:21.228268714 +0100 CET):
-rw-r--r--     0     0 345945001259 2023-01-17 04:55:21 /hugefile
```

Ideally, it should print `345G` in this case.

**Comment by MichaelEischer** [comment]
An `--human-readable` flag might be an option. But I don't think that redefining `-h` is a good idea, especially not in a way that depends on the presence of other options.

**Comment by rawtaz** [comment]
An option like that would be rather ugly in the CLI IMO. What about introducing a more versatile option such as e.g. `-u --unit` to which one can specify single-letter units such as `k`, `m`, `g` and so on for the usual units, but also `h` for "human readable"?

**Comment by kenny-y-dev** [comment]
This could probably be added with a call to the existing internal/format.go. I can work on a PR getting that rigged up with a new `--human-readable` option, then the functionality can get integrated and possibly be shortened to a single letter flag in the future
