### ISSUE TITLE
Allow reading exclude patterns from a file

### ISSUE THREAD

**Issue by fd0** [restic/restic#416]
It was proposed on IRC that it is easier to have restic read the exclude patterns for backup from a file, so that the command line does not get so messy. This issue is about implementing an `--exclude-file` parameter that reads the patterns from a file, one per line.

**Comment by jojomi** [comment]
Perhaps this is an idea worth generalizing even more?

[ack](https://github.com/petdance/ack2) is parsing command line options from a file called `.ackrc` in current directory. The syntax is exactly the same as on the command line, but it feels less cluttered indeed. In the case of restic I think we would need an option like `--settings=restic-project.conf` to reference different **project definitions**. On the other hand this raises the question if complex command definitions isn't rather a thing to be solved using a shell script or similar?

**Comment by fd0** [comment]
Issue #16 is about defining a configuration file, this will be handled once #16 is resolved. I need to invest some more thoughts into the config file design before this will be implemented, though. If you have any specific ideas, please add a comment there. thanks!

**Comment by jojomi** [comment]
Oh thank you for pointing me to that other Issue, I felt I read something about this project configuration feature already, and you proved me right. So I guess the main points are on the table, but I agree finding an appropriate format is not trivial. I myself felt quite good with making the configuration file *just* a replacement for the cli parameters, no special logic or format added.

**Comment by schorsch3000** [comment]
Thats exactly what i need right now.
 :+1:

**Comment by fd0** [comment]
This was added in #490
