### ISSUE TITLE
Replacing rsync

### ISSUE THREAD

**Issue by aldrinmartoq** [restic/restic#4160]
Output of `restic version`
--------------------------
```
restic 0.14.0 compiled with go1.19.3 on darwin/amd64
restic 0.14.0 compiled with go1.19 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Is there any chance to make a `rsync` replacement with restic? The use case is just to simply copy/sync files between remote hosts, the algorithm (Content Defined Chunking) saves a lot of bandwidth already, which is really impressive.

Both binary should be present, the channel could be a ssh session or maybe a netcat created pair of sockets. Ideally if it is supported between different computer architectures (arm64, x86_86, etc).

What are you trying to do? What problem would this solve?
---------------------------------------------------------

A tool for transferring files between servers, that reduces the **time** and **bandwidth** required.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm really thankfully for this program.

**Comment by rawtaz** [comment]
What in restic is it you are missing in rsync? You mentioned CDC, but rsync already does pretty much the same, see https://rsync.samba.org/tech_report/ .

Restic is a backup software, not a synchronization software. While it would be possible to turn it into what you expect from rsync, it's no small task to do so and certainly moves focus from what it currently is and does arguably well.

**Comment by greatroar** [comment]
The CDC is available as a [Go module](https://github.com/restic/chunker), so you can roll your own rsync replacement using it.

**Comment by MichaelEischer** [comment]
restic and rsync just have two completely different use cases. You probably could sync hosts using `backup` and `restore` (after it's beefed up with #2662 #2348). But that will always include the indirection of uploading the snapshot to the repository and downloading the changes later on.
