### ISSUE TITLE
"ciphertext verification failed" using rest server

### ISSUE THREAD

**Issue by miguelarios** [restic/restic#4168]
Output of `restic version`
--------------------------
`restic 0.15.0 compiled with go1.19.5 on linux/amd64`

How did you run restic exactly?
-------------------------------
`restic -r rest:http://172.25.10.3:8000/restic --verbose check` then pwd

```
using temporary cache in /tmp/restic-check-cache-316400046
enter password for repository: 
repository 956a56a8 opened (version 2, compression level auto)
created new cache in /tmp/restic-check-cache-316400046
create exclusive lock for repository
unable to create lock in backend: Fatal: ciphertext verification failed
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

rest-server

Expected behavior
-----------------

run a check or view snapshots or do a backup

Actual behavior
---------------

consistently getting the same error of `unable to create lock in backend: Fatal: ciphertext verification failed`

However the same backups are working to b2

Steps to reproduce the behavior
-------------------------------

I just ran my backup using autorestic the config file but it is using the rest-server backup. I am running the rest-server backend in docker 

Do you have any idea what may have caused this?
-----------------------------------------------

perhaps updating to version 0.15.0

Do you have an idea how to solve the issue?
-------------------------------------------

No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I am loving restic so far! Just want to figure out this issue 😄

**Comment by MichaelEischer** [comment]
Please run `ls -la path/to/repo/locks` and `shasum -a256 path/to/repo/locks/*` and provide the output.

It looks like one of the lock files got corrupted due to a bitflip on the host which runs restic. Removing all lock files using `restic unlock --remove-all` should fix the problem, but please first create a backup of all files in the `locks` folder of the repository. Afterwards, I'd strongly advise you to run `check --read-data` for the backup stored at the rest-server to make sure that there are no other bitflips in it.

**Comment by miguelarios** [comment]
@MichaelEischer 
Thank you!

```
ls -la path/to/repo/locks

drwx------ 1 root root 162 Jan 20 00:46 ./
drwxrwxrwx 1 root root 115 Dec 21 12:38 ../
-rw------- 1 root root 144 Dec 21 14:13 1725afd49aa860b55d1b792068795ed1d8ac6f34960ff9a114e6e2f5990f30ee
-rw------- 1 root root 142 Dec 21 14:14 b60b9af5a575a962bcb2705a5b1db44f4eb829f748cd92d6a9c193bd9f2568ce
```

```
shasum -a256 *

1725afd49aa860b55d1b792068795ed1d8ac6f34960ff9a114e6e2f5990f30ee  1725afd49aa860b55d1b792068795ed1d8ac6f34960ff9a114e6e2f5990f30ee
b60b9af5a575a962bcb2705a5b1db44f4eb829f748cd92d6a9c193bd9f2568ce  b60b9af5a575a962bcb2705a5b1db44f4eb829f748cd92d6a9c193bd9f2568ce
```

when you say the bitflip happened `on the host which runs restic` you mean it is the host that performs the backup not where the rest-server lives?

OK i will do those steps now and create a copy of those files prior to remove the locks

**Comment by MichaelEischer** [comment]
> when you say the bitflip happened `on the host which runs restic` you mean it is the host that performs the backup not where the rest-server lives?

Yes, I mean the host performing the backup. If a bitflip is caused by the rest-server, then the sha256 checksum wouldn't match the filename anymore.

**Comment by MichaelEischer** [comment]
> So bitflips, is this something I should test using Memtest or something? Is it super unusual for them to happen for no particular reason?

As there was apparently only a single damaged lock file, it might be a one time event. Running memtest and/or prime95 might be a good idea though. However, the big problem is that a bitflip might only occur in some very specific circumstances which are pretty hard to predict. So you might want to run `check --read-data` or `check --read-data-subset m/n` from time to time to be sure that your repo is intact.
