### ISSUE TITLE
Allow reading backup items from file

### ISSUE THREAD

**Issue by fd0** [restic/restic#417]
Add a function that reads to-be-backed-up files and directories from a file, instead of from the command line. When a shell is available, restic can be called as `restic backup $(cat dirlist)` and will backup all files/dirs contained in the file `dirlist`. I still like to have such an option, it's easy to implemented and also works e.g. on Windows.

We still need a good name for the command-line option, candidate: `--backup-file`

**Comment by damekr** [comment]
Hi, 
What do you mean by "cat dirlist"? it would be a file with e.g. 
/etc/hosts
/etc/passwd
etc?
And these files or even dirs to be backed up?

**Comment by fd0** [comment]
Exactly, the file `dirlist` in my example would contain a list of files and directories to be saved so that you don't need to specify these on the command-line, e.g.:
```
$ cat dirlist
/home
/usr
/boot
/srv
/var/log/syslog
```

So this should be equivalent to running
```
$ restic backup /home /usr /boot /srv /var/log/syslog
```

This already works on Unix like this: `$ restic backup $(cat dirlist)`. This issue describes adding a parameter (e.g. `--backup-file`) to read the list directly, e.g.:
```
$ restic backup --backup-file dirlist
```

**Comment by cfcs** [comment]
Maybe `--backup-filelist` or `--backup-file-list` would be clearer - `--backup-file` sounds a bit like it would save the backup to a specific file -?

**Comment by fd0** [comment]
This has been implemented, `backup` now has the option `--files-from` to read the list of files/dirs to backup from a file.
