### ISSUE TITLE
a cp command would be nice

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4174]
Output of `restic version`
--------------------------
...

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
restic already supports ls to list files but "only" restore to restore a complete path or dump to output a file.
an additional command cp would be nice (like linux or docker)
```
cp latest:/home/foo/bar.txt /tmp/
cp latest:/home/foo/bar.txt /tmp/foobar.txt
cp -r latest:/home/foo/ /foo/
cp -r latest:/etc/* /tmp/
...
```
latest could also be a snapshot-id of course

What are you trying to do? What problem would this solve?
---------------------------------------------------------
copy files/folders from snapshots to a given folder/file.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
makes me always happy because commads are easily to remember 🙂

**Comment by rawtaz** [comment]
I don't get it. Using `restore` you can restore individual/specific files. So what is this suggested command needed for?

**Comment by AlBundy33** [comment]
1. better to remember
2. posibility to restore a single/file to a specific folder (without to create the absolute path insode the target dir)
3. workaround to issue with unc-paths (#2807)

current
```
$ /opt/restic/restic --repository-file /opt/restic/.restic_repository --password-file /opt/restic/.restic_password restore latest --target test --include /etc/passwd
repository 66fd5f9c opened (version 2, compression level auto)
restoring <Snapshot 26936de4 of [/etc /home /opt /var/spool] at 2023-01-25 01:00:01.379619277 +0100 CET by root@nuc> to test
$ find test/
test/
test/etc
test/etc/passwd
```
expected
```
$ /opt/restic/restic --repository-file /opt/restic/.restic_repository --password-file /opt/restic/.restic_password cp latest:/etc/passwd test/
repository 66fd5f9c opened (version 2, compression level auto)
$ find test/
test/
test/passwd
```

**Comment by rawtaz** [comment]
It would probably be better to improve existing commands instead of starting to spread similar functionality out over several commands..

**Comment by AlBundy33** [comment]
imho adding new arguments like
`restore latest --target test --include /etc/passwd --strip-path /etc/ --recursive`
would add the functionality but is not easy to remember

maybe something like this?
`restore latest:/etc/passwd /tmp/test/`
`restore --recursive latest:/etc/ /tmp/test/`
it's the same as above only with restore as command instead of cp


maybe cp ans restore havee different usecases
restore with target-dir and includes to "restore" the complete tree (with absolute path) according to the includes

and cp to copy files/subtrees to a target dir (as the cp command on unix)

**Comment by rawtaz** [comment]
What is your `--recursive` supposed to do? Restoring a directory will restore it and whatever is in/under it as well.

**Comment by AlBundy33** [comment]
I was thinking about the -r of the cp command
```
$ cp /etc/* /tmp/test/
cp: -r wurde nicht angegeben, daher wird das Verzeichnis '/etc/alternatives' ausgelassen
cp: -r wurde nicht angegeben, daher wird das Verzeichnis '/etc/audit' ausgelassen
...
```
this copies all files from /etc/ to /tmp/test/

one could argue that the copy of a directory should always be recursive but on th other hand having the same syntax as known commands would be nice.
but on the other other hand 🙂 -r may not work because it's already used for the repo. 🤔 

to be honest I always copy files with `cp x y` and directories with `cp -r x y` because cp needs it - I've never needed to copy directories wihout -r. 🤔 
so omitting -r it may be ok

**Comment by MichaelEischer** [comment]
This has already been discussed in https://github.com/restic/restic/issues/4027#issuecomment-1374652405 . The way forward is to add the <hash>:<subtree> syntax from https://github.com/restic/restic/issues/3871 to the `restore` command. There is absolutely no need to introduce yet another nearly identical command.
