### ISSUE TITLE
enhancement for --verbose description

### ISSUE THREAD

**Issue by GuitarBilly** [restic/restic#4190]
Output of `restic version`
--------------------------
v0.15.1 on windows and v0.14.0 on linux (not yet upgraded to latest)

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
nothing today; restic and rest-server are great!

What are you trying to do? What problem would this solve?
---------------------------------------------------------
This is a minor item. Current description of --verbose is confusing. from the commandline:

`-v, --verbose n                  be verbose (specify multiple times or a level using --verbose=n, max level/times is 2)`

if you use `--verbose 2` to a command this is the response:

```
PS C:\LocalData\tools\RestServer> restic.exe --verbose 2 --repo "C:\Users\nlv08564\OneDrive - Nexperia\MPD\Nexperia" --tag "C_H" backup --files-from c:\_RESTIC\scripts_windows\W10.restic.include.C_H.txt
unknown command "2" for "restic"

Did you mean this?
        ls
```

I would propose to change the description of verbosity to:
`-v, --verbose                  be verbose (specify multiple times or a level using --verbose=n, max level/times is 2)`

as the verbose=n is already in the details and --verbose by itself is also a valid option.
If you want I can attempt a pull request as it seems defined only in /doc/manual_rest.rst. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic was my saviour after a rocky start with Duplicati. Restic had a steeper learning curve for me but step by step i have continued to sasfely automate, monitor, and restore my backups. Thank you!

**Comment by MichaelEischer** [comment]
The documentation in `/doc/manual_rest.rst` is just a sample of the output of `restic --help`. I've made the change in the proper place in #4198. Thanks for the suggestion!

**Comment by GuitarBilly** [comment]
thanks @MichaelEischer, 
next time i try to improve my search as https://github.com/restic/restic/issues/3926 is essentially the same issue.
