### ISSUE TITLE
Set timeouts for backend connections

### ISSUE THREAD

**Issue by MichaelEischer** [restic/restic#4193]
Output of `restic version`
--------------------------
0.15.1

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Set proper timeouts for requests. A broken network connection currently causes restic to stall waiting for 15 minutes. This delay is longer than the maximum timespan during which requests are retried. Consequently, the whole operation fails.

In addition, it is bad for performance.

Ideally, the timeouts interrupted connections which make no progress for e.g. a minute. That way the timeouts would be independent of the connection speed.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
See https://forum.restic.net/t/403-authentication-errors-with-large-data-cross-region-backup-and-restore-in-azure/5916

**Comment by MichaelEischer** [comment]
Apparently the TCP_USER_TIMEOUT socket option does what we want (see https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/ for an explanation). That is we should add some code similar to https://code.googlesource.com/google-api-go-client/+/master/transport/grpc/dial_socketopt.go

**Comment by seqizz** [comment]
Another case (s3), just wanted to link in case of consistency: https://forum.restic.net/t/restic-gets-stuck-rarely/6139/3

**Comment by kousu** [comment]
I hit this last night against OVH's object storage at `RESTIC_REPOSITORY=s3:storage.de.cloud.ovh.net/mybackups`. I have no idea why but my backups took over two hours last night, and were interrupted by my other cronjob that reboots my server. I ran my backup script again and was able to reproduce it.

I assume this is something temporary and flakey with OVH's service, but it would be good if restic could error-out in this case. Perhaps a default TCP timeout of 5 minutes or so?

With 

```
$ restic version
restic 0.11.0 compiled with go1.15.9 on linux/amd64
```

from [Debian bullseye](https://packages.debian.org/bullseye/restic):

```
$ apt-cache policy restic
restic:
  Installed: 0.11.0-1+b5
  Candidate: 0.11.0-1+b5
  Version table:
 *** 0.11.0-1+b5 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by MichaelEischer** [comment]
`TCP_USER_TIMEOUT` is only available on Linux and thus not suitable as a general solution.

For a generic solution, we can either use a custom RoundTripper that injects timeouts into requests or use a custom net.Conn that monitors the underlying connection.
The RoundTripper applies to individual requests (multiple requests can be multiplexed onto a single HTTP2 connection), whereas the net.Conn targets the underlying connection.

restic sends both very small requests, but also uploads/downloads of hundreds of MB. These have wildly different timeout requirements. Thus instead of using a fixed timeout, we can ensure that these requests make progress at a fixed rate. Or even simpler ensure that they make progress at all. This can be checked by enforing that read or write have handled some data in the last x minutes, as a broken connection will neither send nor receive data.

This also interacts nicely with idle connections if the IdleConnTimeout is smaller that the timeout used to detect broken connections.

Unlike a web server, there is no particular need for restic to defend agianst servers that intentionally send data with the lowest rate possible. Servers must at least be somewhat trusted.

## RoundTripper

See https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts
 for details on available timeouts.
The http client supports an overall fixed timeout for requests, which is not suitable for us. So we'll have to assemble something out of the individual timeouts:

- Dialer.Timeout
- TLSHandshakeTimeout
- send request body (no existing timeout)
- ResponseHeaderTimeout
- read response body (no existing timeout)

All steps except send/read only involve a small amount of data and thus can be handled with a fixed timeout.

`http2.Transport` additionally offers the following timeouts (which apply at the connection level):
- WriteByteTimeout: ensures minimum progress for sending the request body
- ReadIdleTimeout + PingTimeout: send pings if no data was received within the read idle timeout

These additional timeouts would be sufficient to enforce progress for send/read requests using HTTP2. However, for HTTP/1 pings are not supported by the protocol and WriteByteTimeout is currently not available.

Thus, we'd still need to build a custom solution for HTTP/1. That would involve wrapping the request/response body to monitor progress. If no progress happens, then the overall request must by canceled (indirectly via a context, as a Body cannot cancel the interaction with the underlying net.Conn).

It's not clear whether a canceled request would also break the underlying - likely broken - HTTP2 connection or not.


## net.Conn

Can inject deadlines for read/write from the underlying TCP connection. This is relatively straightforward to implement. writes have to complete within a given timeout. And reads either have to receive data before the timeout, or a successfull write must happen in the meantime.

The read timeout will not interfere with idle connections, as long as these are closed before the read timeout expires.

The write timeout is actually very similar to the implementation of WriteByteTimeout in the `http2.Transport`. The suggested read timeout behavior is somewhat different from ReadIdleTimeout, as it does not perform active health checks.

If an upper layer sets a deadline on the connection, then our wrapper net.Conn must honor that deadline. A connection must also be considered alive if it remains within those deadline.

WriteByteTimeout & ReadIdleTimeout work on the connection level, thus there should be no need to use them in addition to a custom net.Conn wrapper.

## Summary

The net.Conn approach appears to be simpler to implement. Thus, let's start with it. It is also cleanly able to get rid of broken HTTP2 connections.


## Related: Repository.StreamPack

For a reliable solution, we have to redesign StreamPacks that it no longer uses requests that can
idle for a long time. This has already proven problematic in a different context, see
https://github.com/restic/restic/issues/4627 .

**Comment by MichaelEischer** [comment]
> I assume this is something temporary and flakey with OVH's service, but it would be good if restic could error-out in this case. Perhaps a default TCP timeout of 5 minutes or so?

The description rather sounds like a stuck operation. Restic already uses TCP connection timeouts and keepalives, which will eventually detect idle broken connections. If a requests is pending on a TCP connection, then a longer system-defined timeout applies. But a 2 hour delay is likely a slightly different problem.

Either way, the approach to force each connection to (slowly) make progress, should also be able to handle that case.

**Comment by MichaelEischer** [comment]
Canceling an http.Request would be possible with something similar to https://github.com/ncw/swift/blob/b37a86bc3491c732a2b5ea198bc7cb307e239992/timeout_reader.go plus https://github.com/ncw/swift/blob/b37a86bc3491c732a2b5ea198bc7cb307e239992/watchdog_reader.go along with canceling the associated context.

**Comment by MichaelEischer** [comment]
I've found a simple way to implement requests timeouts in https://github.com/restic/restic/pull/4792 . This turned out way simpler than https://github.com/restic/restic/pull/4778 , thus let's follow that approach.
