### ISSUE TITLE
\restic_0.15.0_windows version unable to take root windows folder backup

### ISSUE THREAD

**Issue by Pakundu** [restic/restic#4197]
Output of `restic version`
--------------------------

How did you run restic exactly?
-------------------------------

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
Please completely fill out the issue template. We can't help you otherwise.

**Comment by Pakundu** [comment]
There are multiple errors related to reading the file when I tried to take OS drive snapshots. same things restore time as well. So, it’s Difficult to sync system file.

**Comment by MichaelEischer** [comment]
You have to be a lot more specific. Which commands did you run exactly? What is the output generated by restic?
