### ISSUE TITLE
Add documentation to explain terminology

### ISSUE THREAD

**Issue by fd0** [restic/restic#42]
Add documentation that explains the terminology used in khepri, at least:
 * backend
 * repository
 * blob, data, tree, snapshot, key

**Comment by MatthewVance** [comment]
I noticed quite a bit of the terminology (i.e., repository, blob, pack, snapshot, and storage ID) is now defined in the [Design](https://github.com/restic/restic/blob/master/doc/Design.md) document. While this doesn't cover everything (e.g., tree), it covers most things. Do you still want to add some more documentation for terms or is the info in the Design document sufficient to close this issue?

**Comment by fd0** [comment]
Oh, good point. I think we can close this issue, all of the relevant terminology is explained. Thanks for pointing this out!
