### ISSUE TITLE
unknown command "self-update" for "restic"

### ISSUE THREAD

**Issue by ethereal-engineer** [restic/restic#4206]
Output of `restic version`
--------------------------
restic 0.15.1 compiled with go1.20 on linux/amd64

How did you run restic exactly?
-------------------------------
/usr/bin/restic self-update

Gave output:

unknown command "self-update" for "restic"

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

-

Expected behavior
-----------------

Have self-update??

Actual behavior
---------------

Is missing?

Steps to reproduce the behavior
-------------------------------

Run it as shown

Do you have any idea what may have caused this?
-----------------------------------------------

A mistake while fixing the output bug in self-update for windows maybe?

Do you have an idea how to solve the issue?
-------------------------------------------

Not at this time.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I am ALWAYS confident in the quality and attention to detail of the people behind restic. This is the first time I have been surprised by a possible oversight, but we're all human.

**Comment by rawtaz** [comment]
What does `restic` output?

**Comment by ethereal-engineer** [comment]
I'm not entirely sure if this copy was `self-update`-ed or whether it was updated by one of `pacman` or `yay` on Arch. Running `restic` produces the normal command summary help list, but `self-update` is missing. Hold. I'll get the output.

**Comment by ethereal-engineer** [comment]
It's definitely not an issue with the `self-update` version. I just ran `self-update` on a version I have on an Ubuntu/Debian server and it updated fine with `self-update` option visible in default run. I suspect Arch packages. I will attempt to confirm.

**Comment by ethereal-engineer** [comment]
Confirmed
```
lappy➜  gtd-tools : main ✘ :✹ ᐅ sudo pacman -Syy
:: Synchronizing package databases...
 core                                                               153.8 KiB  15.9 KiB/s 00:10 [########################################################] 100%
 extra                                                             1737.2 KiB   555 KiB/s 00:03 [########################################################] 100%
 community                                                            7.2 MiB  1253 KiB/s 00:06 [########################################################] 100%
lappy➜  gtd-tools : main ✘ :✹ ᐅ sudo pacman -S restic
resolving dependencies...
looking for conflicting packages...

Packages (1) restic-0.15.1-1

Total Installed Size:  24.05 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 restic-0.15.1-1-x86_64 is up to date
(1/1) checking keys in keyring                                                                  [########################################################] 100%
(1/1) checking package integrity                                                                [########################################################] 100%
(1/1) loading package files                                                                     [########################################################] 100%
(1/1) checking for file conflicts                                                               [########################################################] 100%
(1/1) checking available disk space                                                             [########################################################] 100%
:: Processing package changes...
(1/1) installing restic                                                                         [########################################################] 100%
Optional dependencies for restic
    fuse2: mount archive
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
lappy➜  gtd-tools : main ✘ :✹ ᐅ restic

restic is a backup program which allows saving multiple revisions of files and
directories in an encrypted repository stored on different backends.

Usage:
  restic [command]

Available Commands:
  backup        Create a new backup of files and/or directories
  cache         Operate on local cache directories
  cat           Print internal objects to stdout
  check         Check the repository for errors
  copy          Copy snapshots from one repository to another
  diff          Show differences between two snapshots
  dump          Print a backed-up file to stdout
  find          Find a file, a directory or restic IDs
  forget        Remove snapshots from the repository
  generate      Generate manual pages and auto-completion files (bash, fish, zsh, powershell)
  help          Help about any command
  init          Initialize a new repository
  key           Manage keys (passwords)
  list          List objects in the repository
  ls            List files in a snapshot
  migrate       Apply migrations
  mount         Mount the repository
  prune         Remove unneeded data from the repository
  rebuild-index Build a new index
  recover       Recover data from the repository not referenced by snapshots
  restore       Extract the data from a snapshot
  rewrite       Rewrite snapshots to exclude unwanted files
  snapshots     List all snapshots
  stats         Scan the repository and show basic statistics
  tag           Modify tags on snapshots
  unlock        Remove locks other processes created
  version       Print version information

Flags:
      --cacert file                file to load root certificates from (default: use system certificates)
      --cache-dir directory        set the cache directory. (default: use system default cache directory)
      --cleanup-cache              auto remove old cache directories
      --compression mode           compression mode (only available for repository format version 2), one of (auto|off|max) (default auto)
  -h, --help                       help for restic
      --insecure-tls               skip TLS certificate verification when connecting to the repository (insecure)
      --json                       set output mode to JSON for commands that support it
      --key-hint key               key ID of key to try decrypting first (default: $RESTIC_KEY_HINT)
      --limit-download rate        limits downloads to a maximum rate in KiB/s. (default: unlimited)
      --limit-upload rate          limits uploads to a maximum rate in KiB/s. (default: unlimited)
      --no-cache                   do not use a local cache
      --no-lock                    do not lock the repository, this allows some operations on read-only repositories
  -o, --option key=value           set extended option (key=value, can be specified multiple times)
      --pack-size size             set target pack size in MiB, created pack files may be larger (default: $RESTIC_PACK_SIZE)
      --password-command command   shell command to obtain the repository password from (default: $RESTIC_PASSWORD_COMMAND)
  -p, --password-file file         file to read the repository password from (default: $RESTIC_PASSWORD_FILE)
  -q, --quiet                      do not output comprehensive progress report
  -r, --repo repository            repository to backup to or restore from (default: $RESTIC_REPOSITORY)
      --repository-file file       file to read the repository location from (default: $RESTIC_REPOSITORY_FILE)
      --tls-client-cert file       path to a file containing PEM encoded TLS client certificate and private key
  -v, --verbose n                  be verbose (specify multiple times or a level using --verbose=n, max level/times is 2)

Use "restic [command] --help" for more information about a command.
```

**Comment by kjetilho** [comment]
Looks like the Arch maintainer has disabled self-update - after all you really don't want to stomp on your package files.  My suggestion is to install the restic binary distributed by the project in /opt or /usr/local instead if you want to use self-update.

**Comment by rawtaz** [comment]
So to summarize, the Arch maintainers are only human and have modified the restic you are running, which is the cause of the problem. Closing! :)

**Comment by LeisureLinux** [comment]
Looked like the Debian version also removed the self-update command. 

I had to recompile from this repo. and overwrite the binary in /usr/bin. And use dpkg-repack to generate my own .deb to distribute.

**Comment by rawtaz** [comment]
> I had to recompile from this repo.

You don't have to do that if you don't want to – you can just download the latest official release from here: https://github.com/restic/restic/releases

**Comment by jan-eckhoff** [comment]
stumbled upon the same problem where in the [blog post](https://restic.net/blog/2026-07-05/restic-0.19.1-released/), the "self-update" path is recommended, but self-update just isn't there. I started worrying my version would be too old or something and going down different rabbit holes, until I found this thread and explanation.
It would be much more helpful if instead of just saying "unknown command", using self-update in such a context would result in a helpful message telling me that this functionality has been disabled by the package maintainer, and what I should do instead to update.

**Comment by l-c-g** [comment]
This behaviour is intentional and described in the [changelog for version 0.9.3](https://github.com/restic/restic/blob/master/CHANGELOG.md#changelog-for-restic-093-2018-10-13), which introduced the `self-update` command:

> Enhancement #1949: Add new command `self-update`
> 
> [...]
> 
> By default, the `self-update` command is hidden behind the `selfupdate` built tag, which is only set when restic is built using `build.go` (including official releases). The reason for this is that downstream distributions will then not include the command by default, so users are encouraged to use the platform-specific distribution mechanism.

**Comment by jan-eckhoff** [comment]
Good to know it's intentional. Nevertheless, if people come across the seemingly helpful information of "just use self-update", maybe it makes sense to either qualify that in the blog post a bit more, or catch those commands with something other than "unknown command".
