### ISSUE TITLE
Prevent accidental overwriting of *rc files (.zshrc, etc)

### ISSUE THREAD

**Issue by jakehemmerle** [restic/restic#4214]
It was late at night and I executed `restic generate --zsh-completion ~/.zshrc` thinking it would add completion to my rc and it totally nuked it. Somewhat ironic since I was setting up restic for... you guessed it... backups, which I don't have of my rc file.

**Comment by Enrico204** [comment]
Uhm, do you suggest to warn only when the file name ends with `rc`?

I think that `restic` should warn the user if the file already exists. Or, even better, it should print the code to `stdout`, allowing the user to handle it.

**Comment by jakehemmerle** [comment]
i think warning the user is a reasonable solution

**Comment by MichaelEischer** [comment]
I don't think it's a good idea to complicate restic's codebase with such checks, sorry. There will always be some way to accidentally destroy some files.
