### ISSUE TITLE
Mock filesystem access for better testing

### ISSUE THREAD

**Issue by fd0** [restic/restic#422]
Just a quick idea so I don't forget: I think it's a good idea to mock the file system access and use something like https://godoc.org/golang.org/x/tools/godoc/vfs so we can better test filesystem-related things (pipe, walker, archiver, restorer etc).

**Comment by jojomi** [comment]
Steve Francia has prepared some [good stuff](https://github.com/spf13/afero) around this problem, it might be worth a look.

**Comment by cfcs** [comment]
A link to `fakedatafs`: https://github.com/restic/fakedatafs

**Comment by fd0** [comment]
We've rewritten the archiver for 0.9.0 and it contains a fully mockable filesystem abstraction, closing.
