### ISSUE TITLE
error failed to refresh lock when restoring from repo on usb ssd

### ISSUE THREAD

**Issue by clarity99** [restic/restic#4222]
I'm trying to restore a snapshot on win 10 from a repo that is on a samsung t7 500gb ssd and I keep getting the error about failing to refresh a lock. The process then seems to hang. I've tried it a number of times and seems to always happen. 
This is a fairly big repo (417gb). Error happens after a while.

restic 0.15.1 compiled with go1.19.5 on windows/amd64
Microsoft Windows [Version 10.0.18363.1500]

Is there any workaround for this so I can restore my data?

**Comment by rsnitsch** [comment]
I'm trying to restore a fairly large snapshot and encounter the exact same issue.

I'm restoring from one local harddrive (repository location) to another (`--target` for restore operation). It just says "restoring snapshot XYZ of [list of folders] to [target-folder]" and then after 20 minutes or so it prints the error

`Fatal: failed to refresh lock in time`

and then just freezes. Running with `--verbose=2` does not result in _any_ additional output, so I have no idea what causes this.

----

My `restic version`:

`restic 0.15.1 compiled with go1.19.5 on windows/amd64`

**Comment by MichaelEischer** [comment]
The `restore` command supports the `--no-lock` option which you could use. However, the underlying problem is that somehow restic seems to get stuck while reading from the repository or restoring the data. Please set the environment variable `DEBUG_LOG=logfile.txt` to get a more detailed log. That might give a hint what is going on.

**Comment by rsnitsch** [comment]
This is the tail of the generated `logfile.txt`:

```
...
2023/04/07 18:43:56 repository/repository.go:939        repository.streamPackPart.func1 27        process blob <data/af8d76ad>, skipped 0, <Blob (data) af8d76ad, offset 16772554, length 175, uncompressed length 166>
2023/04/07 18:43:56 repository/repository.go:939        repository.streamPackPart.func1 27        process blob <data/3d375817>, skipped 0, <Blob (data) 3d375817, offset 16772729, length 497, uncompressed length 1634>
2023/04/07 18:44:06 repository/repository.go:939        repository.streamPackPart.func1 27        process blob <data/f279ed65>, skipped 0, <Blob (data) f279ed65, offset 16773226, length 1388, uncompressed length 3188>
2023/04/07 18:49:39 repository/repository.go:939        repository.streamPackPart.func1 27        process blob <data/c19240eb>, skipped 0, <Blob (data) c19240eb, offset 16774614, length 695, uncompressed length 1385>
2023/04/07 18:49:39 repository/repository.go:939        repository.streamPackPart.func1 27        process blob <data/49dc4065>, skipped 0, <Blob (data) 49dc4065, offset 16775309, length 4160, uncompressed length 39214>
2023/04/07 18:49:40 repository/repository.go:507        repository.(*Repository).SaveUnpacked   16      blob <lock/4ad87ee440> saved
2023/04/07 18:49:40 restic/lock.go:270  restic.(*Lock).Refresh  16      new lock ID 4ad87ee4400af39690f102959140bd1533f5da502debddabddb68c92bbb9373a
2023/04/07 18:49:40 cache/backend.go:37 cache.(*Backend).Remove 16      cache Remove(<lock/bd9e7407bb>)
2023/04/07 18:49:40 local/local.go:274  local.(*Local).Remove   16      Remove <lock/bd9e7407bb>
2023/04/07 18:49:40 restic/lock.go:108  main.refreshLocks       16      refreshing locks
2023/04/07 18:49:40 restic/lock.go:258  restic.(*Lock).Refresh  16      refreshing lock 4ad87ee4
2023/04/07 18:49:40 restic/json.go:25   restic.SaveJSONUnpacked 16      save new blob lock
2023/04/07 18:49:40 local/local.go:117  local.(*Local).Save     16      Save <lock/ca5de32cf7>
2023/04/07 18:49:40 repository/repository.go:507        repository.(*Repository).SaveUnpacked   16      blob <lock/ca5de32cf7> saved
2023/04/07 18:49:40 restic/lock.go:270  restic.(*Lock).Refresh  16      new lock ID ca5de32cf7dc4bba78a6d0ef484fb5aa8ab51f91e0a0de1210431e676a73397c
2023/04/07 18:49:40 cache/backend.go:37 cache.(*Backend).Remove 16      cache Remove(<lock/4ad87ee440>)
2023/04/07 18:49:40 local/local.go:274  local.(*Local).Remove   16      Remove <lock/4ad87ee440>
2023/04/07 18:49:40 restic/lock.go:100  main.refreshLocks       16      terminate
2023/04/07 18:49:40 restic/lock.go:88   main.refreshLocks.func1 16      unlocking repository with lock PID 32896 on HOSTNAME by HOSTNAME\USERNAME (UID 0, GID 0)
lock was created at 2023-04-07 18:49:40 (9.5104ms ago)
storage ID ca5de32c
2023/04/07 18:49:40 cache/backend.go:37 cache.(*Backend).Remove 16      cache Remove(<lock/ca5de32cf7>)
2023/04/07 18:49:40 local/local.go:274  local.(*Local).Remove   16      Remove <lock/ca5de32cf7>
2023/04/07 18:56:49 repository/repository.go:939        repository.streamPackPart.func1 26        process blob <data/6f495ae0>, skipped 0, <Blob (data) 6f495ae0, offset 14206893, length 653554, uncompressed length 1087002>
2023/04/07 18:56:52 repository/repository.go:939        repository.streamPackPart.func1 26        process blob <data/8dcd902d>, skipped 0, <Blob (data) 8dcd902d, offset 14860447, length 445, uncompressed length 6148>
2023/04/07 18:57:14 repository/repository.go:939        repository.streamPackPart.func1 26        process blob <data/fc02ca2a>, skipped 0, <Blob (data) fc02ca2a, offset 14860892, length 90, uncompressed length 49>
2023/04/07 18:57:14 repository/repository.go:939        repository.streamPackPart.func1 26        process blob <data/899be870>, skipped 0, <Blob (data) 899be870, offset 14860982, length 264, uncompressed length 309>
2023/04/07 18:57:14 repository/repository.go:939        repository.streamPackPart.func1 26        process blob <data/2887c24d>, skipped 0, <Blob (data) 2887c24d, offset 14861246, length 749, uncompressed length 1297>
2023/04/07 18:57:14 repository/repository.go:939        repository.streamPackPart.func1 26        process blob <data/dbccfb80>, skipped 0, <Blob (data) dbccfb80, offset 14861995, length 171, uncompressed length 158>
2023/04/07 18:57:14 repository/repository.go:939        repository.streamPackPart.func1 26        process blob <data/eff13c58>, skipped 0, <Blob (data) eff13c58, offset 14862166, length 612045, uncompressed length 4722186>
2023/04/07 18:57:15 repository/repository.go:939        repository.streamPackPart.func1 26        process blob <data/e6f956ae>, skipped 0, <Blob (data) e6f956ae, offset 15474211, length 220842, uncompressed length 528426>
2023/04/07 18:58:11 repository/repository.go:939        repository.streamPackPart.func1 26        process blob <data/f2b24cc3>, skipped 0, <Blob (data) f2b24cc3, offset 15695053, length 1625627, uncompressed length 2783093>
2023/04/07 19:33:35 restic/cleanup.go:62        main.CleanupHandler     50      signal interrupt received, cleaning up
2023/04/07 19:33:35 restic/lock.go:184  main.unlockAll  50      unlocking 1 locks
```

At 18:58 restic froze. At 19:33 I pressed CTRL-C.

**Comment by MichaelEischer** [comment]
Judging from the log, restic must have reported the lock refresh error before 18:49. Do you know whether that is correct? Did restic exit after pressing Ctrl-C?

The other strange thing about this debug log is how abysmally slow the `streamPackPart` seems to be. Both blocks of the corresponding debug messages should each only require less than a second, or maybe a few seconds at most(!), but definitely not minutes. Is there a lot of CPU usage on the host? Or nearly no free RAM?

**Comment by rsnitsch** [comment]
I've done the test again while watching RAM usage. RAM was quite high (about 1.5 GB in the later stages) but not too much for my system. Still my machine slowed down considerably which is - I guess - because the filesystem cache was completely used up by restic plus the number of files on my NTFS partition grew so dramatically that it probably affects the performance as well.

By the way, this time I used my SSD again as restore target location instead of the HDD. For that I freed up lots of space beforehand. However the free space did not suffice... I had to abort prematurely after the restore grew to more than 150 GB.

This is strange because the restore-size for the snapshot is actually only about 17 GB (as you can see there are 2.6 million files though):

```
Stats in restore-size mode:
     Snapshots processed:  1
        Total File Count:  2651193
              Total Size:  16.493 GiB
```

I suppose this is because the snapshot is originally from migrating a TimeMachine backup to restic. TimeMachine uses hardlinks a lot. But I thought that restic restore can preserve hardlinks on restore. Isn't that the case? Maybe it's only supported on Linux, not on Windows?

To that end, I did another experiment, this time within WSL. I created a restic repo within WSL (copying the snapshot from my actual restic repo located at /mnt/... to /home/... within WSL). And then I tried to restore into /home/restore. But even within Linux the target folder quickly grew to almost 200 GB. Then, restic showed lots of errors like "no space left on device" and I had to abort early, again.

My restic version within WSL:
`restic 0.15.1 compiled with go1.19.5 on linux/amd64`

**Comment by MichaelEischer** [comment]
> But I thought that restic restore can preserve hardlinks on restore. Isn't that the case? Maybe it's only supported on Linux, not on Windows?

restoring hardlinks on Windows should in theory work. Although backups created on Windows won't include hardlinks.

> But even within Linux the target folder quickly grew to almost 200 GB.

That definitely shouldn't happen. You `restic mount` the repository within WSL and use for example `ncdu` to analyze the reported disk usage. Other than that the only idea I've got at the moment is to try to find out which folder(s) are causing the problem, by iteratively limiting the restore operation to different parts of the dataset.

**Comment by MichaelEischer** [comment]
Closing as there seems to be nothing left to investigate. Locking is able to tolerate longer pause since restic 0.16.0 https://github.com/restic/restic/issues/4199
