### ISSUE TITLE
TLS handshake timeout while restoring large dataset (Swift)

### ISSUE THREAD

**Issue by rafikt1992** [restic/restic#4230]
Output of `restic version`
--------------------------
```
restic version
restic 0.15.1 compiled with go1.19.5 on linux/amd64
```
How did you run restic exactly?
-------------------------------
I am backing up around 1.2 TB using repo version 2 with default compression.

I backup to a swift object store, and the backup works properly.

I set these extra variables:
```bash
export GOMAXPROCS=6
export GOGC=35
```

However, when restoring I get that the process gets killed. the following is the command output
```bash
time restic -r $RESTIC_REPOSITORY restore -v=2  latest --target .
repository fd5f00da opened (version 2, compression level auto)
restoring <Snapshot bc88681f of [/mnt/jenkins2] at 2023-03-03 08:27:34.18486803 +0000 UTC by ubuntu VM
Remove(<lock/0c8e7ab288>) returned error, retrying after 552.330144ms: conn.ObjectDelete: Delete "https://objectstore-some-url:443/v1/AUTH_db344f23e0ac4460a1ec8ab31dbc361f/jenkins/jenkins/locks/0c8e7ab288d2e4a3728b69135f9ff621472744df96200eddf6a0459d7e1dcc4e": http: server closed idle connection
Remove(<lock/0c8e7ab288>) operation successful after 1 retries
Load(<data/3e29b5847a>, 17098447, 0) returned error, retrying after 720.254544ms: ReadFull: unexpected EOF
Load(<data/6a05ac2c1f>, 19009510, 0) returned error, retrying after 582.280027ms: ReadFull: unexpected EOF
Load(<data/3e29b5847a>, 17098447, 0) operation successful after 1 retries
Load(<data/b96fac38b0>, 16777592, 0) returned error, retrying after 468.857094ms: ReadFull: unexpected EOF
Load(<data/6a05ac2c1f>, 19009510, 0) operation successful after 1 retries
Load(<data/b96fac38b0>, 16777592, 0) operation successful after 1 retries
Killed

real    49m43.627s
user    55m29.792s
sys     10m49.546s
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Swift Object Store

Expected behavior
-----------------
backup restored successfully 

Steps to reproduce the behavior
-------------------------------

Use swift as a backend and perform a large backup (1.5 TB) then restore it

Do you have an idea how to solve the issue?
-------------------------------------------

Maybe we can just increase the timeout value of the handshake

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is a great tool, it has a lot of potential.

**Comment by MichaelEischer** [comment]
`Killed` sounds like restic hit some memory limit on the system. Newer versions usually contain memory usage optimizations that might help.

Closing as there's not enough information to debug and the restore failure has nothing to do with the TLS handshake.
