### ISSUE TITLE
Add option for setting original creation time when restoring files and folders

### ISSUE THREAD

**Issue by nullinger** [restic/restic#4233]
Output of `restic version`
--------------------------

```
restic 0.15.1 compiled with go1.19.5 on windows/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When restoring files and folders there should be the possibility to restore the original creation time.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

From my point of view metadata is also important when doing a complete data restore.
It would be great if there was an option to be able to restore the original file (and folder) creation time.

E. g. Robocopy can also include this metadata like `Robocopy.exe ... /COPY:DT /DCOPY:T`

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic is great!
Thank you for this great backup software.

**Comment by rawtaz** [comment]
@nullinger Have you reproduced this on Windows only or can you reproduce it on Mac/Linux as well?

I just tried restoring a file in an old snapshot, and I get the file's old creation date set by the restore:

~~~
% restic restore --target tmp --verify 3901cdc7
repository ba330420 opened (version 1)
restoring <Snapshot 3901cdc7 ...> to tmp
verifying files in tmp
finished verifying 2 files in tmp (took 0s)

% stat -x tmp/foo2/peepdf_0.3.zip
  File: "tmp/foo2/peepdf_0.3.zip"
  Size: 170213       FileType: Regular File
  Mode: (0644/-rw-r--r--)         Uid: (  502/  rawtaz)  Gid: (   20/   staff)
Device: 1,15   Inode: 6301790    Links: 1
Access: Mon May  3 18:01:05 2021
Modify: Mon May  3 18:01:05 2021
Change: Wed Mar 22 18:23:10 2023
 Birth: Mon May  3 18:01:05 2021
~~~

So for me, the original creation date and time are restored as expected - no options needed. This was using restic 0.15.1 on macOS Monterey.

**Comment by nullinger** [comment]
@rawtaz Thank you for your reply.
Unfortunately I cannot test it on a Mac.

Test in Linux (Ubuntu 22.04):

```sh
$ stat source/test.txt
  Datei: source/test.txt
 Größe: 0               Blöcke: 0          EA Block: 4096   Normale leere Datei
Gerät: 802h/2050d       Inode: 658762      Verknüpfungen: 1
Zugriff: (0664/-rw-rw-r--)  Uid: ( 1000/     xx)   Gid: ( 1000/      xx)
Zugriff: 2023-03-23 13:38:58.730006128 +0100
Modifiziert: 2023-03-23 13:38:58.730006128 +0100
Geändert: 2023-03-23 13:38:58.730006128 +0100
Geburt: 2023-03-23 13:38:58.730006128 +0100
$ stat restore/source/test.txt
  Datei: restore/source/test.txt
 Größe: 0               Blöcke: 0          EA Block: 4096   Normale leere Datei
Gerät: 802h/2050d       Inode: 662891      Verknüpfungen: 1
Zugriff: (0664/-rw-rw-r--)  Uid: ( 1000/      xx)   Gid: ( 1000/      xx)
Zugriff: 2023-03-23 13:38:58.730006128 +0100
Modifiziert: 2023-03-23 13:38:58.730006128 +0100
Geändert: 2023-03-23 13:43:16.202311984 +0100
Geburt: 2023-03-23 13:43:16.202311984 +0100
```
It seems that the Birth times ("Geburt") are different.
But I am not sure if it is really the same problem as in Windows. I am not a Linux expert.

**Comment by MichaelEischer** [comment]
AFAIK it is not possible to set the birth time of a file on Linux. For Windows see #3622.

**Comment by nullinger** [comment]
Thanks @MichaelEischer. I did not find that PR before.
I’ll close this issue.
