### ISSUE TITLE
restic version downgraded after apt-get upgrade

### ISSUE THREAD

**Issue by shaicoleman** [restic/restic#4237]
Expected behavior
-----------------
After restic self-update, upgrading or reinstalling the DEB package shouldn't downgrade its version.

Actual behavior
---------------
Upgrading/reinstalling a package causes `/usr/bin/restic` to be overwritten.
Backups/restores fail if repo v2 is used, which isn't supported by the older versions

Steps to reproduce the behavior
-------------------------------
Run `docker run -it docker.io/ubuntu:22.04`
```
apt-get update
apt-get -yy install restic ca-certificates
restic self-update
restic version # restic 0.15.1
apt-get -yy install --reinstall restic
restic version # restic 0.12.1
```

Do you have any idea what may have caused this?
-----------------------------------------------
`restic self-update` writes files to paths that are managed by the deb package

Do you have an idea how to solve the issue?
-------------------------------------------
* Write the updated binary to `/usr/local/bin/restic` instead
* Disable self-update on the debian package

**Comment by rawtaz** [comment]
Thanks, but this is completely outside of the restic project's scope, since we are not the ones who maintain the DEB packages - that is the Debian maintainers (or similar, depending on what Linux distribution you run).

Restic's `self-update` has no awareness of DEB, APT or similar, it just updates itself. If something else then replaces the updated binary with an older version, that is something that has to be fixed there.

**Comment by hollie** [comment]
Got bitten by this too, and I agree this is not something to fix by the restic team. 

It might be interesting however to add a note in the documentation where the self-update command is explained that this update will be overwritten if you follow the standard installation instructions (for debian at least).

https://github.com/restic/restic/blob/master/doc/020_installation.rst#stable-releases

**Comment by wlkns** [comment]
I also had this happen today, it wasn't immediately clear either - `--no-scan` wasn't an option, repository was wrong version..

Thanks @hollie I was not aware of this APT feature.
