### ISSUE TITLE
Potential bug in fuse's reported block size

### ISSUE THREAD

**Issue by 0xAdk** [restic/restic#4239]
Hi, I happened to stumble across this old pr #447 with this line

https://github.com/restic/restic/blob/f646406822158e9280a97848467e71c62ca6c7d4/internal/fuse/file.go#L53 

I don't think this is doing what you expect. I see two issues:

1. The blocks field is (unintuitively) supposed to be the "Number of 512 B blocks allocated" - [stat(3type)](https://man.archlinux.org/man/stat.3type.html), not the number of `blockSize` blocks as it is currently. 
This isn't an issue at present since `blockSize` is a constant `512`, but it will be if the constant is changed in the future.

2.  `file_size / block_size + 1` isn't a good way of doing "rounded up" integer division since it breaks when `block_size` divides evenly into `file_size`. For example with this code a file that is 512 bytes or 1 block, this issue means the code would report it as 2 blocks.

**Comment by greatroar** [comment]
The blockSize constant exists to give exactly that number a name and is documented as such. It won't change.

But you're right about the computation. The right size is

    (f.node.Size + blockSize - 1) / blockSize
