### ISSUE TITLE
Progress bar for restore

### ISSUE THREAD

**Issue by vshalts** [restic/restic#426]
Backup have nice progress bar, but restore is not.
In real life I expect to do restore not that often (now I play with restic and with restore a bit too often).
But it will be useful to have progress for restore too (for big repo I would like to see some estimation about how much time it will take).

**Comment by fd0** [comment]
Thanks for raising this issue. It's not a high priority right now, because (as you already said) restoring is important, but not done so often.

**Comment by fd0** [comment]
Still relevant, will be addressed by #2003

**Comment by fortinmike** [comment]
@fd0 Has development of this feature stalled? Seems like #2003 will never see the light of day, at least in its current form.

IMHO having restore progress (especially for big restores) is important to convey the fact that restore is working (did not freeze) and to provide at least a basic idea of how much work remains to be done to restore something. At a minimum, it would be nice to display a "spinner" (indeterminate progress) indicator to at least indicate that the restore is being performed and is not stalled.

When performing time-critical restores (e.g. a last-resort restore to bring a service back online as quickly as possible), not being able to give a time estimate to whoever you report to could be quite problematic.

**Comment by peixotorms** [comment]
+1

**Comment by rawtaz** [comment]
For anyone looking for this; While you can't see how much is still left to be done during restore, you can definitely see whether or not restic is working on the restore by inspecting the CPU usage and foremost the network traffic usage that it's causing.

**Comment by peixotorms** [comment]
I am using `watch -n 10 du -sh` to roughly check the restore size, but a progress bar (or a way to pipe the data transfer through pv) would be most welcome. Thanks

**Comment by kgnfth** [comment]
> I am using `watch -n 10 du -sh` to roughly check the restore size, but a progress bar (or a way to pipe the data transfer through pv) would be most welcome. Thanks

hi can u show the full command on how you run this
i mean do i have to run it like

`watch -n 10 du -sh | restic ...`

**Comment by patrickuhlmann** [comment]
1. you run the restic restore operation in one terminal/session
2. you open another termin/session and run the command `watch -n 10 du -sh /your/restore/folder`
In the second terminal you will see the size of the resored folder and it will refresh every 10 seconds. That way you can see how much data was already restored and it should climb over the time.

**Comment by fermulator** [comment]
@fd0 , is there any particular "requirements" or maintainer "suggestions for implementation"? -- if someone from the community would like to pick it up I mean, it would be good to have a list of requirements and implementation preferences maybe?

**Comment by MichaelEischer** [comment]
As suggested in #2438, the --verbose flag could be used to select how much information should be printed, just like with the backup command.

**Comment by darth-veitcher** [comment]
Is there still no progress reporting availability on restoring from a backup? Feels like a fairly critical requirement.

**Comment by rawtaz** [comment]
> How can we tell the total that is going to be restored to calculate % and progress? 

Probably using the `stats` command on the snapshot you intend to restore, which can tell you how much data there is in the given snapshot.

> Also what's the level of effort required to achieve this inside the tool?

Looking at #2003 which was start but then closed it seems that it isn't very simple or straight forward to just add this.

> Really feels like a big missing feature to still have around after this time.

Sure, it would be nice to have a fancy %. But if you consider how many other things there are to attend, this is low priority. Pretty much every issue/PR/problem/etc is by those who it affects considered a priority, while if you look at the bigger picture it's not that simple to just implement it.

**Comment by patrickuhlmann** [comment]
I agree that it is inconvenient and I did have hanging restore processes (problems with OneDrive). I also understand that it is hard to do estimations of remaining time. On the other hand it is one area where restic is lagging behind other solutions like borg and it is an important part of the user experience.

Would it be a possibility to show the % of blocks restored vs. the total number of blocks to be read? This seems like a simple solution based on information that most likely is already available and gives a rough idea of the current state.

**Comment by darth-veitcher** [comment]
Out of interest (and without looking at the code too deeply) isn't it a case of hooking into this for each loop of nodes and then printing to stdout?

`internal/restorer/restorer.go`

Line 60 seems to build a total number of nodes and then we iterate through, write to the target and verify the resulting output.

**Comment by pabs3** [comment]
There have already been two pull requests for this feature (#671 #2003) but they never got merged. Probably the way to go is read through the discussions on them, then read through the patches, then rebase them on git master, then address the problems discussed with them.

**Comment by asm0dey** [comment]
I'm restoring a 200 GB backup right now, and even `du` is slow on it after 116 of them were restored. Please add something at least fundamental

**Comment by MichaelEischer** [comment]
Fixed by https://github.com/restic/restic/pull/3991
