### ISSUE TITLE
publish container image on other registry

### ISSUE THREAD

**Issue by ibotty** [restic/restic#4269]
I have many computers pulling the restic image behind a single NATted IP and get rate limited by dockerhub.  Can the image be published on a registry that doesn't have draconian pull limits?  I personally like quay.io, but github has its own container registry.

**Comment by chris-sanders** [comment]
I'm looking for the same thing, ghcr.io is always nice since it's hosted right along the source code but anything without pull limits would be nice.

**Comment by mamoit** [comment]
Maybe AWS would also be interested in hosting the container images free of charge :thinking:
https://gallery.ecr.aws/
