### ISSUE TITLE
Homebrew: restic depends on go, installs go a second time

### ISSUE THREAD

**Issue by christophberger** [restic/restic#427]
I have go installed from the golang.org tarball (in /usr/local/go). When I ran brew install restic, I observed that this also installs go due to a dependency in the formula, and I ended up having two go installations on my machine. Is this dependency intentional? 

(BTW: I am just starting to try out restic but the features list already sounds awesome. Great work!)

Thanks,
Christoph

**Comment by fd0** [comment]
Hey, thanks for trying out restic! Could you have a look @fw42?

**Comment by fw42** [comment]
Yeah this is [intentional](https://github.com/restic/homebrew-restic/blob/5be11f741cc9937f4dd54603df4486d720bf2c08/restic.rb#L13) since Go is required to compile restic (which is what homebrew does). I think you can use `brew install restic --ignore-dependencies go` to skip this step.

**Comment by christophberger** [comment]
Thanks! Will try this.

**Comment by fd0** [comment]
I think we can close this issue for now :)
