### ISSUE TITLE
In version 0.15.1, the --path and --host flags for the dump subcommand are switched.

### ISSUE THREAD

**Issue by dominiwe** [restic/restic#4277]
Output of `restic version`
--------------------------

`restic 0.15.1 compiled with go1.19.5 on linux/amd64`

How did you run restic exactly?
-------------------------------

### First run

```sh
restic -r backups dump --path /root/temp/files latest files/hey
```

Output:

```plain
Fatal: failed to find snapshot: snapshot filter (Paths:[] Tags:[] Hosts:[/root/temp/files]): no snapshot found
```

### Second run

```sh
restic -r backups dump --host myhost1 latest files/hey
```

Output:

```plain
Fatal: failed to find snapshot: snapshot filter (Paths:[myhost1] Tags:[] Hosts:[]): no snapshot found
```

### Third run (working)

```sh
restic -r backups dump --path myhost1 --host /root/temp/files latest files/hey
```

Output:

```plain
hi
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Just a regular directory.

Expected behavior
-----------------

To evaluate the specified flags correctly.

Actual behavior
---------------

The `--host` and `--path` are switched as can be seen in the output containing `Fatal: failed...`.

Steps to reproduce the behavior
-------------------------------

Simply test it with the `dump` subcommand.

Do you have any idea what may have caused this?
-----------------------------------------------

A bug.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, it's awesome! :)

**Comment by MichaelEischer** [comment]
For documentation: this is a duplicate of #4211
