### ISSUE TITLE
rewrite: old snapshot deleted before new one is created?

### ISSUE THREAD

**Issue by clonejo** [restic/restic#4295]
At the end of rewriting a snapshot with `--forget`, the log output looks like this:
```
removed old snapshot c682c238
saved new snapshot 0d58bbaa
```

It suggests that restic deletes the old snapshot before saving the new one, which would be prone to data loss. I have not checked the code at all, so it might just be misleading.

I would feel better if the log messages were the other way around, or the text was clear that no snapshot can be lost.

**Comment by MichaelEischer** [comment]
The code saves the new snapshot first and deletes the old one afterwards. It is just the log messages that are misleading.

**Comment by clonejo** [comment]
@MichaelEischer Thanks for confirming that! I was too lazy for checking the code myself.
