### ISSUE TITLE
Failure to init sftp repository

### ISSUE THREAD

**Issue by viric** [restic/restic#431]
I use:
```
$ restic init -r sftp://croscatbackup/restic-tmp

enter password for new backend: 
enter password again: 
creating key in backend at sftp://croscatbackup/restic-tmp failed: file does not exist
```

It definitely creates restic-tmp there, but it fails about keys.

Using master as of today.

**Comment by fd0** [comment]
Hey, thanks for raising this. Could you please try whether the following works? (remove `restic-tmp` before trying):

```
$ restic init -r sftp:croscatbackup:restic-tmp
```

Background is: I've recently reworked the repository-location parser so that it is easier to tell the hostname and directory for sftp apart. In this case, the host name is `croscatbackup` and the directory is `restic-tmp`, which is relative to the home directory of the user on that host.

**Comment by viric** [comment]
It does not work. Same outcome. It only creates directories there, no files.

**Comment by fd0** [comment]
Hm, that's really strange. I can't imagine what causes this. Could you please
 * compile restic with debug support by running `go run build.go -tags debug`, then remove the directory on the server and try again: `DEBUG_LOG=/tmp/log restic init -r sftp:croscatbackup:restic-tmp init`
 * try a different directory on the server, e.g. `DEBUG_LOG=/tmp/log restic init -r sftp:croscatbackup:/tmp/restic-repo init`

**Comment by viric** [comment]
Oh. If I build restic that way, it works.

I was just running "go build" in cmd/restic. If I do that, it fails; with and without debug. The debug then simply ends at line:
```
2016/02/11 13:09:45 0.000 [      open]   1 global.go:226 create sftp repository at sftp.Config{User:"", Host:"croscat", Dir:"prova"}
```

If I run the build line (reported by go run build.go -v):
```
go build -tags debug -ldflags '-s -X "main.compiledAt=2016-02-11 13:03:09" -X "main.version=0.1.0 (v0.1.0-350-g2461830)"' -o restic github.com/restic/restic/cmd/restic
```
my binary doesn't work either.

What can be doing a difference?

**Comment by viric** [comment]
ah! The godeps thing! I'm using upstream dependencies.

**Comment by fd0** [comment]
Oh, that explains it. The `build.go` constructs a temporary GOPATH in /tmp which only contains the restic code and the vendored dependencies, builds restic, and removes the temporary path. That way we can be sure that we can tell from the version number `restic version` outputs exactly what code was used to produce the binary.

I think you can close this issue then, do you agree?

**Comment by viric** [comment]
Agreed!

**Comment by fd0** [comment]
Just out of curiosity: Which version of the sftp library (`github.com/pkg/sftp`) did you have installed in your GOPATH?

**Comment by viric** [comment]
e84cc8c755ca39b7b64f510fe1fffc1b51f210a5

**Comment by fd0** [comment]
Interesting, I'll reopen this issue since that is a much newer commit in the sftp library. It's interesting to see whether there's a bug in the newer version of the lib...

**Comment by viric** [comment]
Just to note... if the repository is already created, it works flawlessly with sftp.

**Comment by fd0** [comment]
I found the underlying cause and created a PR to update the sftp library and the code.
