### ISSUE TITLE
Restic printing many status lines instead of truncating line during operation

### ISSUE THREAD

**Issue by akrabu** [restic/restic#4319]
Output of `restic version`
--------------------------
restic 0.15.2 compiled with go1.20.3 on darwin/arm64

How did you run restic exactly?
-------------------------------

restic backup ~

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Local

Expected behavior
-----------------

This one is just a visual issue.  It used to show the progress bar on one line, truncating if there wasn't enough room.

Actual behavior
---------------

Now it prints hundreds of updates on multiple lines when there is not enough room in the terminal

Steps to reproduce the behavior
-------------------------------

See here:
https://v.usetapes.com/JIEzx5FMnx

<img width="749" alt="Screen Shot 2023-05-03 at 10 11 24 AM" src="https://user-images.githubusercontent.com/6868732/235990342-c6bff3b4-100f-4cf6-81fd-510d6f3be15e.png">

Do you have any idea what may have caused this?
-----------------------------------------------

I'm guessing it's related to the #2260 bugfix but I don't know.

Do you have an idea how to solve the issue?
-------------------------------------------

Unfortunately not :( 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Best backup app out there!

**Comment by akrabu** [comment]
To better illustrate why I think it's related to #2260 

https://v.usetapes.com/Jit1we7owi

Seems to be the printing of filenames, not the status line.  :)

**Comment by MichaelEischer** [comment]
See https://github.com/restic/restic/pull/4318

**Comment by akrabu** [comment]
Shoot, missed that when I looked around.   Thanks!
