### ISSUE TITLE
restic backup does not lock the repo for other parallel backup commands.

### ISSUE THREAD

**Issue by mmx2004** [restic/restic#4321]
Output of `restic version`
--------------------------
0.15.2

How did you run restic exactly?
-------------------------------
Just using restic command

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone

Expected behavior
-----------------
I'm backing up my data every minute but sometimes the process of backing up takes longer than a minute so the next backup command start to execute while the previous one still going on. I expect restic to not run the second parallel command due to lock.

Actual behavior
---------------
Backup commands runs simultaneously in parallel, like the backup command does not lock the repo for other backup commands. But, backup command is locking the repo for forget command. So I can not run forget command while backup command is still running.

Steps to reproduce the behavior
-------------------------------
Just try to us to backup commands simultaneously.

Restic is great. Thank you.

**Comment by MichaelEischer** [comment]
This is expected behavior. It is safe for multiple `backup` operations to run concurrently.
