### ISSUE TITLE
Fatal: unable to create lock in backend: repository is already locked by PID 38397

### ISSUE THREAD

**Issue by james-xiexinrong** [restic/restic#4324]
i try to run 
restic forget 03015a5c --prune 
then error happen 
debug log file bug.log
debug enabled
repository d40db62f opened (version 2, compression level auto)
Fatal: unable to create lock in backend: repository is already locked by PID 38397 on vla010000191063 by root (UID 0, GID 0)
lock was created at 2023-04-28 10:30:46 (165h32m5.88133994s ago)
storage ID 8ba25ed5

**Comment by james-xiexinrong** [comment]
sorry  
run restic unlock can fix it

**Comment by MichaelEischer** [comment]
Closing as there's nothing left to do. Recent restic versions already print a hint to use the `unlock` command.
