### ISSUE TITLE
Restic confusing pattern matching in exclude file syntax with double asterisk (**)

### ISSUE THREAD

**Issue by RayZ0rr** [restic/restic#4329]
Output of `restic version`
--------------------------

`restic 0.15.2 compiled with go1.20.3 on linux/amd64`

How did you run restic exactly?
-------------------------------
1. Move to a test directory
`cd ~/tmp/restic`
2. Run the script `make_sample_repo.sh` below to create test folders and files as backup source 

`bash make_sample_repo.sh`

```bash
#!/usr/bin/env bash

# Make main backup folder
mkdir -p source

# Make multiple nested folders
mkdir -p source/level1/level2/level3/level4/level5/level6/level7

# Fill folders with easy to identify files

# Level 1 files
touch source/level1/l1_{file1,file2,file3,file4}
# Level 2 files
touch source/level1/level2/l2_{file1,file2,file3,file4}
# Level 3 files
touch source/level1/level2/level3/l3_{file1,file2,file3,file4}
# Level 4 files
touch source/level1/level2/level3/level4/l4_{file1,file2,file3,file4}
# Level 5 files
touch source/level1/level2/level3/level4/level5/l5_{file1,file2,file3,file4}
# Level 6 files
touch source/level1/level2/level3/level4/level5/level6/l6_{file1,file2,file3,file4}
# Level 7 files
touch source/level1/level2/level3/level4/level5/level6/level7/l7_{file1,file2,file3,file4}

```
4. Create an exclude file : 
`touch source/backup_excludes.txt`
6. Paste the following content : 
```
# Set 1 :- Doesn't backup folder level6, its files and other deeper level nested folders and files
**/level5/level6/**
**/level5/level6

# Set 2 :- Backups level6 but doesn't backup files in level6 and other deeper level nested folders and files
**/level5/level6/*
**/level5/level6/**/*
```
8. Comment or Uncomment the patterns in Set 1 and Set 2 shown in the exclude file above to observe the behaviour

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Local filesystem

Expected behavior
-----------------

Set 1 should have :-
`**/level5/level6`
but not :-
`**/level5/level6/**`

That should belong in Set 2.

Actual behavior
---------------

The sets are as shown in the exclude file above.

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Maybe double asterisk (**) is not handled properly?

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is one of my most essential softwares.

**Comment by MichaelEischer** [comment]
`**` expands to zero or more wildcards. That is, `abc/**` expands to `abc`, `abc/*`, `abc/*/*`, ... .


> ## Expected behavior
> 
> Set 1 should have :- `**/level5/level6` but not :- `**/level5/level6/**`
> 
> That should belong in Set 2.

I don't understand the description of the expected behavior. `**/level5/level6/**` and `**/level5/level6` are equivalent, as excluding the `level6` folder implicitly excludes all files in that folder. Same for Set 2 both `**/level5/level6/*` and `**/level5/level6/**/*` are equivalent.

A leading `**/` is also redundant. Non-absolute patterns, as in your examples, are matched against part of a path.

**Comment by RayZ0rr** [comment]
> as excluding the level6 folder implicitly excludes all files in that folder. 

This is the case for `**/level5/level6`

So, for `**/level5/level6/**` whats happening is :- 

**Excluding all the files/folders in level6 folder implicitly excludes level6 folder.**

Is this description correct and is the expected behaviour? Then I will close the issue
