### ISSUE TITLE
Permit `--no-lock` for `backup`, slow machine causes `Fatal: failed to refresh lock in time`

### ISSUE THREAD

**Issue by skius** [restic/restic#4336]
Output of `restic version`
--------------------------
`restic 0.15.2 compiled with go1.20.3 on linux/amd64`

How did you run restic exactly?
-------------------------------
```env
RESTIC_REPOSITORY="rclone:XXX:/XXX"
RESTIC_PASSWORD_FILE="XXX"
RESTIC_COMPRESSION="max"
GOGC=1
RESTIC_CACHE_DIR="XXX"

```
(Tried both with and without `--no-lock`)
`./restic backup --tag "$host-$datetime" -x --exclude-file exclusions.txt --verbose --no-lock /`

Output:
```
open repository
repository XXX opened (version 2, compression level max)
lock repository
no parent snapshot found, will read all files
load index files
...
[2:37:14] 36.52%  38728 files 14.177 GiB, total 259551 files 38.821 GiB, 0 errors ETA 4:33:18
Fatal: failed to refresh lock in time
error: no result
error: no result
error: no result
Fatal: unable to save snapshot: context canceled
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Google Drive with rclone

Expected behavior
-----------------

I expect restic's backup to succeed.

Actual behavior
---------------

restic's backup does not succeed. See output from above. Also, `--no-lock` seems to not work (confirmed from a different system using `restic cat lock`), but I'm not sure if that's documented intended behavior somewhere.

Steps to reproduce the behavior
-------------------------------

The repo is ~330GB in size, contains ~23'000 files, is made up of ~60 snapshots with each ~4M files (and ~200-300GB in size, high deduplication). 

The specific issue arises now when trying to back up ~250k files on a different system with just 8GB of RAM. The command above uses around 12GB of memory, so 4GB is constantly swapped out, with performance suffering massively as a result. This is (even if unfortunate, looking forward to future restic versions!) to be expected and not my issue. What is my issue, is that the backup just fails.

Do you have any idea what may have caused this?
-----------------------------------------------

I assume the thrashing causes restic to not be able to refresh its lock in time. So, as opposed to #4199, I'm host-performance constrained as opposed to network-performance.

Do you have an idea how to solve the issue?
-------------------------------------------

The preferred solution would be a smaller memory footprint of course, but I'm sure that would've been implemented already if it was a quick solution. Alternatively, supporting `backup --no-lock` should allow me to cautiously complete this backup, I believe.

Potentially related: #4304

**Comment by MichaelEischer** [comment]
Fixing #4274 might be able to let the backup continue even in this case.

However, the memory usage seems to be far too high. What does `restic stats --mode raw-data` report?

You could try whether `GOMAXPROCS=1` reduces the memory usage?

> The specific issue arises now when trying to back up ~250k files on a different system with just 8GB of RAM.

I'd strongly recommend to use separate repositories for different hosts.

**Comment by MichaelEischer** [comment]
Closing as there has been no feedback and the "failed to refresh lock in time" issue has been mitigated in restic 0.16.0
