### ISSUE TITLE
"pack not referenced in any index" after rebuild-index

### ISSUE THREAD

**Issue by viric** [restic/restic#435]
I cannot get rid of "pack not referenced in any index" messages in "check", even after running rebuild-index.

Running rebuild-index (no matter how many times I run it) gives something like this:
```
rebuilding index from 2 indexes
  loading index 0
  loading index 1
  saving new index
removing 2 old indexes
checking for additional packs
  saving new index
added 34 packs to the index
```
There are always some "additional packs" at every run.

**Comment by fd0** [comment]
Thanks for reporting this, I'll have look. It probably is a bug.

**Comment by viric** [comment]
Is this bug dangerous? (possible loss of data)

**Comment by fd0** [comment]
Please retry with latest master, I've rewritten the `rebuild-index` command.

**Comment by fd0** [comment]
We've debugged this on IRC, the issue was caused by duplicate data blobs in pack files. It'll be possible to solve it using the upcoming `prune` command, see #479.

**Comment by fd0** [comment]
This is fixed by now.
