### ISSUE TITLE
Can't find AuthVersion in AuthUrl

### ISSUE THREAD

**Issue by AlwaySummit** [restic/restic#4367]
Output of `restic version`
--------------------------
0.15.0

How did you run restic exactly?
-------------------------------
I'm following https://velero.io/docs/v1.11/file-system-backup/ to use restic as the file-system-backup tool. After everything is all set, /velero backup create test --default-volumes-to-fs-backup is executed.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
swift

Expected behavior
-----------------
Backup completed without any errors.

Actual behavior
---------------
Backup is partially failed with:
time="2023-06-12T15:38:45Z" level=error msg="Error backing up item" backup=velero/test612-24 error="pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=swift:test:/monitoring --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=Fatal: unable to open repository at swift:test:/monitoring: conn.Authenticate: Can't find AuthVersion in AuthUrl - set explicitly\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=logstash-0

Steps to reproduce the behavior
-------------------------------
1. Install velero
2. Install restic
3. Set OS env
4. Execute /velero backup create test --default-volumes-to-fs-backup

Do you have any idea what may have caused this?
-----------------------------------------------
Not sure but it seems a bug because all the os_env is set correctly as below:
OS_AUTH_URL=https://identity-3.xxx.cloud/v3
OS_SWIFT_REGION_NAME=xxx
OS_USER_DOMAIN_NAME=test
OS_PASSWORD=xxx
OS_PROJECT_DOMAIN_NAME=xxx
OS_USERNAME=test
OS_PROJECT_ID=111
OS_STORAGE_URL=generated via swift auth
OS_AUTH_TOKEN=generated via swift auth
Even though I set ST_AUTH_VERSION=3, still the same error.

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
restic currently does not use the `ST_AUTH_VERSION` environment variable. 

The version detection in the swift library only checks that the OS_AUTH_URL contains the string `v3`. Thus, it shouldn't be possible for this error to occur. Are you sure that `OS_AUTH_URL` is set when restic is called? I get the exact same error message if no environment variable is set.

> 3\. Set OS env

The environment variables must be passed to the pod (or wherever restic is run by velero) and not the host environment.

**Comment by AlwaySummit** [comment]
Hi @MichaelEischer 
Thanks for your response. I suppose it's indeed the OS env related issue. Since the velero is used in my situation, I'll close this ticket. More information can be tracked in https://github.com/vmware-tanzu/velero/issues/6392.
