### ISSUE TITLE
Wrong "seconds_remaining" amount on backup start | Unnecessary folders listed in verbose logs | 

### ISSUE THREAD

**Issue by Sarraksh** [restic/restic#4368]
Output of `restic version`
--------------------------
restic 0.15.2 compiled with go1.19.8 on linux/amd64

How did you run restic exactly?
-------------------------------
Inside official docker container
```shell
docker run --rm -ti --entrypoint=sh -e RESTIC_PASSWORD=qwe -e GOOGLE_APPLICATION_CREDENTIALS=/app/service-account/backup-service-account-key.json --mount type=bind,src=[some/host/folder]/scripts/local/service-account-key.json,dst=/app/service-account/backup-service-account-key.json --mount type=bind,src=[some/host/folder]/tmp/test_file,dst=/app/backup/name/data/restic/test_file restic/restic:0.15.2
```

And then this command with and without `--verbose` flag
```shell
restic backup --json --verbose --cleanup-cache --cache-dir /app/backup/name/restic-cache --repo gs:[google/cloud/bucket/path] /app/backup/name/data/restic
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Google cloud bucket

Expected behavior
-----------------
I will describe in next section.

Actual behavior
---------------
Without `--verbose` flag (full log of secondary run with cache)
```shell
/ # restic backup --json --cleanup-cache --cache-dir /app/backup/name/restic-cache --repo gs:[google/cloud/bucket/path] /app/backup/name/data/restic
{"message_type":"status","seconds_remaining":9223372036854775808,"percent_done":0,"total_files":1,"total_bytes":2024800256}
{"message_type":"status","percent_done":1,"total_files":1,"files_done":1,"total_bytes":2024800256,"bytes_done":2024800256}
... [several identical lines]
{"message_type":"status","percent_done":1,"total_files":1,"files_done":1,"total_bytes":2024800256,"bytes_done":2024800256}
{"message_type":"summary","files_new":0,"files_changed":0,"files_unmodified":1,"dirs_new":0,"dirs_changed":0,"dirs_unmodified":5,"data_blobs":0,"tree_blobs":0,"data_added":0,"total_files_processed":1,"total_bytes_processed":2024800256,"total_duration":0.8174002,"snapshot_id":"9323c5518c8bbb8ec0f856e50ec849791a55caabf0dff6ee95544c81ab160bdd"}
```

With `--verbose` flag (full log of secondary run with cache)
```shell
/ # restic backup --json --verbose --cleanup-cache --cache-dir /app/backup/name/restic-cache --repo gs:[google/cloud/bucket/path] /app/backup/name/data/restic
{"message_type":"status","action":"scan_finished","item":"","duration":0.6854036,"data_size":2024800256,"data_size_in_repo":0,"metadata_size":0,"metadata_size_in_repo":0,"total_files":1}
{"message_type":"status","seconds_remaining":9223372036854775808,"percent_done":0,"total_files":1,"total_bytes":2024800256}
... [several identical lines]
{"message_type":"status","seconds_remaining":9223372036854775808,"percent_done":0,"total_files":1,"total_bytes":2024800256}
{"message_type":"verbose_status","action":"unchanged","item":"/app/backup/name/data/restic/test_file","duration":0,"data_size":0,"data_size_in_repo":0,"metadata_size":0,"metadata_size_in_repo":0,"total_files":0}
{"message_type":"status","percent_done":1,"total_files":1,"files_done":1,"total_bytes":2024800256,"bytes_done":2024800256}
{"message_type":"verbose_status","action":"unchanged","item":"/app/backup/name/data/restic/","duration":0,"data_size":0,"data_size_in_repo":0,"metadata_size":0,"metadata_size_in_repo":0,"total_files":0}
{"message_type":"verbose_status","action":"unchanged","item":"/app/backup/name/data/","duration":0,"data_size":0,"data_size_in_repo":0,"metadata_size":0,"metadata_size_in_repo":0,"total_files":0}
{"message_type":"verbose_status","action":"unchanged","item":"/app/backup/name/","duration":0,"data_size":0,"data_size_in_repo":0,"metadata_size":0,"metadata_size_in_repo":0,"total_files":0}
{"message_type":"verbose_status","action":"unchanged","item":"/app/backup/","duration":0,"data_size":0,"data_size_in_repo":0,"metadata_size":0,"metadata_size_in_repo":0,"total_files":0}
{"message_type":"verbose_status","action":"unchanged","item":"/app/","duration":0,"data_size":0,"data_size_in_repo":0,"metadata_size":0,"metadata_size_in_repo":0,"total_files":0}
{"message_type":"status","percent_done":1,"total_files":1,"files_done":1,"total_bytes":2024800256,"bytes_done":2024800256}
... [several identical lines]
{"message_type":"status","percent_done":1,"total_files":1,"files_done":1,"total_bytes":2024800256,"bytes_done":2024800256}
{"message_type":"summary","files_new":0,"files_changed":0,"files_unmodified":1,"dirs_new":0,"dirs_changed":0,"dirs_unmodified":5,"data_blobs":0,"tree_blobs":0,"data_added":0,"total_files_processed":1,"total_bytes_processed":2024800256,"total_duration":0.9900696,"snapshot_id":"dcde12a0ae93b23c286f517fd6f34a0ee2fc1638011455f4583c1f97309a9272"}
```

With `--verbose` flag (start of log of secondary run without cache)
```shell
/ # restic backup --json --verbose --cleanup-cache --cache-dir /app/backup/name/restic-cache --repo gs:[google/cloud/bucket/path] /app/backup/name/data/restic
{"message_type":"status","action":"scan_finished","item":"","duration":1.276226,"data_size":2024800256,"data_size_in_repo":0,"metadata_size":0,"metadata_size_in_repo":0,"total_files":1}
{"message_type":"status","seconds_elapsed":1,"seconds_remaining":9223372036854775808,"percent_done":0,"total_files":1,"total_bytes":2024800256,"current_files":["/app/backup/name/data/restic/test_file"]}
{"message_type":"status","seconds_elapsed":1,"seconds_remaining":1243,"percent_done":0.0008037908900778014,"total_files":1,"total_bytes":2024800256,"bytes_done":1627516,"current_files":["/app/backup/name/data/restic/test_file"]}
{"message_type":"status","seconds_elapsed":1,"seconds_remaining":1243,"percent_done":0.0008037908900778014,"total_files":1,"total_bytes":2024800256,"bytes_done":1627516,"current_files":["/app/backup/name/data/restic/test_file"]}
{"message_type":"status","seconds_elapsed":1,"seconds_remaining":459,"percent_done":0.002169511776276662,"total_files":1,"total_bytes":2024800256,"bytes_done":4392828,"current_files":["/app/backup/name/data/restic/test_file"]}
{"message_type":"status","seconds_elapsed":1,"seconds_remaining":317,"percent_done":0.003141393814600545,"total_files":1,"total_bytes":2024800256,"bytes_done":6360695,"current_files":["/app/backup/name/data/restic/test_file"]}
```

I noticed several things that can be a bug (the first one differently is)
If needed i will create separate issues for additional mentioned problems.

1. For some reason first message contain wrong approximate time - `"seconds_remaining":9223372036854775808`
Reproduced in all 3 examples
It can be some backward overflow of variable, because this number can be represented as one and 63 zeroes

2. In verbose (only second example) mode output contain several strings with field `"item"` which contains `/app/backup/name/data/restic/test_file`, `/app/backup/name/data/restic/`, `/app/backup/name/data/` and so on.
But `restic backup` started for `/app/backup/name/data/restic/` folder.
Files from listed folders not appear in backup, so i think this can be logging system problem

3. In verbose mode appears additional lines and most of them have `"message_type":"verbose_status"`, except string with `"action":"scan_finished"`, which have `"message_type":"status"`.
I am not sure but it may be mistake in logging system.

Steps to reproduce the behavior
-------------------------------
Run in docker container and try save backup into google cloud bucket.
At least in my tests, data not have size about 2GB, contains only one file and not changed between tests

Do you have any idea what may have caused this?
-----------------------------------------------
In comments to Actual behavior

Do you have an idea how to solve the issue?
-------------------------------------------
In comments to Actual behavior

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes of course, restic helps me and i think it is a grate backup instrument.
Thanks for your work!

**Comment by MichaelEischer** [comment]
> 1. For some reason first message contain wrong approximate time - `"seconds_remaining":9223372036854775808`
>        Reproduced in all 3 examples
>        It can be some backward overflow of variable, because this number can be represented as one and 63 zeroes

This is likely fixed by https://github.com/restic/restic/pull/3563 .



> 2\. In verbose (only second example) mode output contain several strings with field `"item"` which contains `/app/backup/name/data/restic/test_file`, `/app/backup/name/data/restic/`, `/app/backup/name/data/` and so on.
>         But `restic backup` started for `/app/backup/name/data/restic/` folder.
>         Files from listed folders not appear in backup, so i think this can be logging system problem

The log output is actually correct. As restic also includes information about the parent folders in the backup, this means that those are also processed and logged.



> 3\. In verbose mode appears additional lines and most of them have `"message_type":"verbose_status"`, except string with `"action":"scan_finished"`, which have `"message_type":"status"`.
>         I am not sure but it may be mistake in logging system.

Has been fixed by https://github.com/restic/restic/pull/4176 .
