### ISSUE TITLE
All files seen as new

### ISSUE THREAD

**Issue by lachesis** [restic/restic#4369]
Output of `restic version`
--------------------------
restic 0.14.0 compiled with go1.19 on linux/amd64

How did you run restic exactly?
-------------------------------
```
$ restic --ignore-ctime --ignore-inode -r sftp:needmore:/nfs/eric/restic-tron --verbose --verbose backup --exclude torrents -x -n /data/Users/Eric

open repository
enter password for repository:
repository 2e1d7f16 opened (repository version 1) successfully, password is correct
found 8 old cache directories in /home/eswanson/.cache/restic, run `restic cache --cleanup` to remove them
lock repository
using parent snapshot 81ff9f52
load index files
start scan on [/data/Users/Eric]
start backup on [/data/Users/Eric]
new       /data/Users/Eric/123, saved in 0.009s (0 B added)
new       /data/Users/Eric/Android/6.0_recovery.img, saved in 0.009s (0 B added)
new       /data/Users/Eric/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/boot.emmc.win, saved in 0.359s (0 B added)Users/Eric/.locatedb-manilla
new       /data/Users/Eric/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/boot.emmc.win.md5, saved in 0.358s (0 B added)s/Eric/.locatedb-manilla
new       /data/Users/Eric/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/recovery.log, saved in 0.007s (0 B added)/Users/Eric/.locatedb-manilla
new       /data/Users/Eric/.locatedb-manilla, saved in 0.714s (0 B added)
new       /data/Users/Eric/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/system.ext4.win000.md5, saved in 0.327s (0 B added)c/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/system.ext4.win000
new       /data/Users/Eric/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/system.ext4.win001, saved in 2.247s (0 B added)/Eric/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/system.ext4.win000
new       /data/Users/Eric/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/system.ext4.win001.md5, saved in 2.249s (0 B added)c/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/system.ext4.win000
new       /data/Users/Eric/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/system.info, saved in 0.005s (0 B added)a/Users/Eric/Android/MotoXPure_XT1575_Clark/2015-12-09--15-00-59_MPH24.49-18/system.ext4.win000
  signal interrupt received, cleaning up
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SFTP

Expected behavior
-----------------
Restic recognizes that most of my files have not changed & only uploads the changed files.

Actual behavior
---------------
Restic claims every file is new.

Steps to reproduce the behavior
-------------------------------
Backup once, move the files to another server, NFS mount them back, then backup again?

Do you have any idea what may have caused this?
-----------------------------------------------
Not 100% sure about this, but I suspect the problem is that the files have been copied to a new device since the initial backup. At the time of the parent snapshot, the files were on a local ZFS disk. Now they are on a NAS mounted over NFS.

Do you have an idea how to solve the issue?
-------------------------------------------
Not sure

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Not today, but I have used restic restore to solve a dozen issues in the last year.

**Comment by MichaelEischer** [comment]
> Not 100% sure about this, but I suspect the problem is that the files have been copied to a new device since the initial backup. At the time of the parent snapshot, the files were on a local ZFS disk. Now they are on a NAS mounted over NFS.

If the path to a file or any of its metadata changes, then restic has to read the files again to detect possible changes. See also https://restic.readthedocs.io/en/stable/040_backup.html#file-change-detection . As indicated by ` (0 B added)` no new data is uploaded to the repository, but restic just has to read all files once again.

Judging from the description, this issue looks like it's expected behavior, or did I miss anything?
