### ISSUE TITLE
Accept backing up from tar input

### ISSUE THREAD

**Issue by viric** [restic/restic#437]
If restic were able to backup not only from files in disk, but also from a tar file (piped in through stdin), I would be able to store in my new restic repository some old backups.

Something like:
```
$ gunzip -c mybackup-2013.tar.gz | restic backup --override-timestamp 201301010000 --tar -
```

**Comment by lathspell** [comment]
For a once-only migration you could look for a FUSE based tool to mount the tar.gz files like e.g. "archivemount". Then you can start a normal restic backup from the mount point.

You'd still need to have the --override-timestamp but at least that would be more in the Unix spirit of separate tools for separate tasks.

**Comment by viric** [comment]
Fair. I didn't know it was there any fuse thing that could mount a targz.

Then, the override-timestamp would be nice to have. Or maybe I should just use a fuse mount point that included the backup date.

**Comment by fd0** [comment]
Thanks for the suggestion. To be honest, I don't think reading tar files for backup is worth the additional code complexity, so I'd like to close this issue.

Being able to specify the timestamp that is recorded in the snapshot should be easy to do, if you still need that please open a different issue so we can discuss it.

**Comment by ThomasLohner** [comment]
This would have been useful when backing up databases and not having enough space locally, like:

`time xtrabackup --backup --stream=tar | restic -r sftp:user@host:/backup/mysql backup`

**Comment by bmillemathias** [comment]
> This would have been useful when backing up databases and not having enough space locally, like:
> 
> `time xtrabackup --backup --stream=tar | restic -r sftp:user@host:/backup/mysql backup`

I concur with the comment

**Comment by MichaelEischer** [comment]
This feature request is now tracked in #2226
