### ISSUE TITLE
backup snapshot contains unspecified content

### ISSUE THREAD

**Issue by hahahaL** [restic/restic#4377]
## backup：files-from-paraments
test-file like these:
![J@_6J@MYYEV~)@5UYZXU5D1](https://github.com/restic/restic/assets/33111103/a624b0f5-6bab-4191-afe7-78017ed7c97c)
cat filelist:
```
  /home/test1/dk/*.java
  /home/test1/dk/*.sh
```
the backup command:
```
restic -r ./repo -p ./pd ./dk --files-from=./filelist --tag java-and-sh
```
then the snapshot show these:
![`LHZ(9$(W(B5)NKVGKWW{36](https://github.com/restic/restic/assets/33111103/1b1d81ef-32e1-4261-bfc9-f77a525550da)
## the recovery data like these:
![9GNJIX4)87WUZJF_`227J_8](https://github.com/restic/restic/assets/33111103/6a910d75-e601-4a14-b352-074bb89721e4)
I don't know why the dk file in thesse snapshot，I only want to backup the files from filelist

**Comment by MichaelEischer** [comment]
You've specified the following paths in you backup command (note the `./dk` in the command):
```
/home/test1/dk/*.java
/home/test1/dk/*.sh
./dk
```

That correctly matches the file structure in the snapshot. The relative path `./dk` is expanded to `/home/test1/dk` before inclusion in the snapshot metadata. That's unfortunately necessary to allow restic later on detect that this is still the same `./dk` folder.
