### ISSUE TITLE
Windows Repositories not compatible with Restic Linux

### ISSUE THREAD

**Issue by durcom2** [restic/restic#4385]
Output of `restic version`
--------------------------

How did you run restic exactly?
-------------------------------

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
 Rest Server

Expected behavior
-----------------
compatability between windows and restic repositories

I'd like it to to work
Actual behavior
---------------
Cannot access repository created with restic backup created under windows on Linux

Tried to run a restic check on linux machine with 
restic check -p /root/resticpw.txt --repo /mnt/backups/restic

Get:

Fatal: Fatal: config cannot be loaded: unsupported repository version

Both windows box and linux box running restic 0.15.2

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by durcom2** [comment]
This seems related to issue 4382 I opened the other day.

**Comment by rawtaz** [comment]
Please replace `restic check -p /root/resticpw.txt --repo /mnt/backups/restic` on your command line with `restic version` and tell us the complete output.

**Comment by durcom2** [comment]
my mistake...was an old version of restic on that linux server, forgot to update it.  seems to work fine now.  Still having the mount issue with SAMBA though.
