### ISSUE TITLE
restic ls snapshotID dir does not work as expected.

### ISSUE THREAD

**Issue by jacko-png** [restic/restic#4386]
Output of `restic version`
--------------------------
restic 0.15.1 compiled with go1.19.5 on windows/386

How did you run restic exactly?
-------------------------------
Via Powershell 5.1.19041.3031 using the restic command.

```
%RESTIC_PASSWORD_FILE% = D:\Users\Jack Harrington\Documents\restic.txt
%RESTIC_REPOSITORY% = E:\Restic
```

Good command. wrong snapshot:
`$restic ls latest "/C/Users/Jack Harrington/AppData/LocalLow/Redbeet Interactive/Raft/User"`

```
snapshot 1270319a of [C:\Users\Jack Harrington\AppData\LocalLow\Redbeet Interactive\Raft\User\User_76561198845937532\World] filtered by [/C/Users/Jack Harrington/AppData/LocalLow/Redbeet Interactive/Raft/User] at 2023-06-25 17:09:24.2043234 +1000 AEST):
/C/Users/Jack Harrington/AppData/LocalLow/Redbeet Interactive/Raft/User
/C/Users/Jack Harrington/AppData/LocalLow/Redbeet Interactive/Raft/User/User_76561198845937532
```

Bad command (prints useless info. Notice that the particular directory is backed up, just doesn't want to list the contents:

`$restic ls 50b179d3ff9b141746e75f025929b9729ca53404e3817283ecea0fa6ab8008a4 "/C/Users/Jack Harrington/AppData/LocalLow/Redbeet Interactive/Raft/User"`

`snapshot 50b179d3 of [D:\Users\Jack Harrington C:\Users\Jack Harrington\Desktop C:\Windows\ShellNew C:\Harrington C:\Users\Jack Harrington\AppData\Local\audacity\SessionData C:\Users\Jack Harrington\AppData\Local\paint.net\SessionData D:\Program Files\Steam D:\Program Files\Games\Pok??wilds D:\Users\Jack Harrington\Minecraft Bedrock C:\Users\Jack Harrington\AppData\Roaming\.minecraft C:\Users\Jack Harrington\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe D:\Users\Jack Harrington\Documents\My Games D:\Users\Jack Harrington\Documents\Local Game Backups D:\Program Files\Steam\steamapps\common\Subnautica\SNAppData D:\Program Files\Steam\steamapps\common\GarrysMod\garrysmod D:\Program Files\Steam\steamapps\common\Portal\portal\save D:\Program Files\Steam\steamapps\common\Portal 2\portal2\SAVE C:\Windows\Media C:\Users\Jack Harrington\AppData\Roaming\Microsoft\Windows\Start Menu C:\ProgramData\Microsoft\Windows\Start Menu C:\Users\Jack Harrington\AppData\Roaming\Axolot Games\Scrap Mechanic\User\User_76561198845937532 C:\Users\Jack Harrington\AppData\Roaming\Spore C:\Users\Jack Harrington\AppData\LocalLow\Empyrean\House Flipper Game C:\Users\Jack Harrington\AppData\LocalLow\Landfall West\Stick Fight_ The Game C:\Users\Jack Harrington\AppData\LocalLow\Redbeet Interactive\Raft C:\Users\Jack Harrington\AppData\Roaming\Warner Bros. Interactive Entertainment\LEGO Star Wars - The Skywalker Saga\SAVEDGAMES\STEAM\885671804] filtered by [/C/Users/Jack Harrington/AppData/LocalLow/Redbeet Interactive/Raft/User] at 2023-04-20 14:08:42.9158719 +1000 AEST):
`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
I keep the repo on a drive

Expected behavior
-----------------
I want to see the contents of a particular directory that's been backed up. According to these docs: https://www.mankier.com/1/restic-ls it should work.

Actual behavior
---------------
Restic does not show the contents of the passed directory. I want to see if my save data is in the repo without restoring.

Steps to reproduce the behavior
-------------------------------
1. Two snapshots with a dummy dir.
2. Try running ls for the dummy dir on the old snapshot, and then on the latest. Compare results.
3. Other things that may affect it:
4. Use an inclusion file for the dummy dir, rather than just putting it in the command

Do you have any idea what may have caused this?
-----------------------------------------------
No.

Do you have an idea how to solve the issue?
-------------------------------------------
Not in the slightest, unfortunately.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes. It's better than the alternative (I don't understand backups tho: my old saves keep getting overwritten with even older saves. I think that's a steam/windows thing. Modern OSes are so fucked)

You're doing great!

**Comment by jacko-png** [comment]
Also I'm fully aware my name and timezone is plastered all over. Idc.

**Comment by MichaelEischer** [comment]
Does `restic ls 50b179d3ff9b141746e75f025929b9729ca53404e3817283ecea0fa6ab8008a4 "/C/Users"` or `restic ls 50b179d3ff9b141746e75f025929b9729ca53404e3817283ecea0fa6ab8008a4` list the expected folder?

**Comment by MichaelEischer** [comment]
@jacko-png Ping

**Comment by MichaelEischer** [comment]
Closing as there has been no reply.
