### ISSUE TITLE
Restic to slice/package/group backup into DVD or Blueray sizes for optical storage?

### ISSUE THREAD

**Issue by klamanch** [restic/restic#4388]
Feature request

Output of `restic version`
--------------------------

 restic 0.11.0 compiled with go1.15.9 on linux/amd64 Linux Mint Debian Bullseye

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

 Does restic have the capability to make automatic backup slices/groups/packages for optical storage?

What are you trying to do? What problem would this solve?
---------------------------------------------------------

 People may want to backup to something like a DVD or Blueray M-disk for long term storage like DAR does. I usually backup to a server then make optical backups for long term. At present using DAR to make backups into variable sized slices.
I didn't see anything that resembled this in the forums. Please excuse/delete if already addressed.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

 Thank you for building this software. I am not a developer but it is just what I was looking for in other backup solutions. I like that it is written in memory safe GO and encrypted. I love the speed and simplicity of the command line. Many thanks for a great product!

**Comment by MichaelEischer** [comment]
I'm afraid we won't be able to support that use case. Restic by design always requires the whole repository to be accessible. Due to the repository structure, restic must be able to access arbitrary files in the repository in an arbitrary order. Having only access to a part of a repository wont work.
