### ISSUE TITLE
`restic mount` should automatically create/remove the directory, if it does not exist and it can

### ISSUE THREAD

**Issue by stdedos** [restic/restic#4396]
Output of `restic version`
--------------------------

```
restic 0.15.2 compiled with go1.20.3 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

`restic mount` should automatically create/remove the directory, if it does not exist and it can

```
$ /usr/bin/restic -r ... mount t
repository a72e6e8d opened (version 1)
Mountpoint t doesn't exist
stat t: no such file or directory
```

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
This has intentionally been changed in https://github.com/restic/restic/pull/3008 to be consistent with the behavior of the `mount` system command.

**Comment by stdedos** [comment]
🤦 

Why do I have to create a useless directory, and after remove it immediately? 😕 

`MkDirAll` **and** "Parent directory/ies don't exist" are both nice solutions.

**Comment by MichaelEischer** [comment]
Closing as automatically creating and properly cleaning up the mount directory is probably not worth the effort.
