### ISSUE TITLE
Linking of docpage is not complete

### ISSUE THREAD

**Issue by stdedos** [restic/restic#4397]
https://restic.readthedocs.io/en/stable/045_working_with_repos.html#removing-files-from-snapshots

![image](https://github.com/restic/restic/assets/133706/32b8b97a-13c5-4f74-9115-b438367bc19b)

https://github.com/restic/restic/blob/f96896a9c0fa682fcba508b0af71d0f82baff8d8/doc/045_working_with_repos.rst?plain=1#L213

**Comment by leeebaljith** [comment]
Hi @stdedos ,can i work on this issue.

**Comment by stdedos** [comment]
Yes @leeebaljith, of course. I merely reported it - as I am not proficient with `rst`, and a quick eye-check reveals everything to be okay.

**Comment by leeebaljith** [comment]
sure, am also new to this ### rst . I checked the specified "command, see :ref:`backup-excluding-files` " on line N.O 213, and the respective Custom Anchor link is placed correctly on 040_backup.rst at line N.O 218. This is the update for now. suppose if i missed some thing here. please let me know. I will further check this and try to solve this on tomorrow.

**Comment by MichaelEischer** [comment]
This has already been fixed by #4244, the fix is included in the "latest" version of the documentation and eventually in the next restic release.

**Comment by stdedos** [comment]
_Closed as duplicate of the referenced issue, but sure_

It's fun that a newline caused that issue 😅 

Thank you for noticing 😄
