### ISSUE TITLE
Create Arch Linux PKGBUILD

### ISSUE THREAD

**Issue by scoddy** [restic/restic#44]

**Comment by elts** [comment]
Hi there,
I've created Arch Linux PKGBUILD file for restic.
Just wanted to ask should I make a pull request, or it's better to submit it to AUR?
Thanks.

**Comment by fd0** [comment]
Please create a pull request. It seems, there already is a package, see: https://aur.archlinux.org/packages/restic-git/

**Comment by elts** [comment]
Huh, didn't notice that someone already submitted restic to AUR. :-)
Nevertheless, I have created pull request with PKGBUILD file.

**Comment by Gordin** [comment]
@elts Looks like our PKGBUILDs do mostly the same thing. I took some parts from yours and updated the one in the AUR (added you as contributor of course). I suggest you you update your pull request to the latest PKGBUILD in the AUR so the repository does not have a different PKGBUILD then the AUR.
