### ISSUE TITLE
"du" displays "0 bytes" for all files in FUSE mounted snapshots

### ISSUE THREAD

**Issue by lathspell** [restic/restic#442]
I tried mounting the snapshots and verify with "du" if certain directories contain plausible amounts of data and if there might be any directories with a lot of big files (like games) that I could exclude. That didn't work in the first attempt as "du" shows 0 bytes for every file:

    # du /mnt/t/snapshots/2016-02-13T09:08:18+01:00/bin
    0       /mnt/t/snapshots/2016-02-13T09:08:18+01:00/bin

The original directory:

    # du /bin
    11468   /bin

Google found me an explanation at https://github.com/MediaFire/mediafire-fuse/issues/15 and the recommended flag did work here, too:

    # du --apparent-size /mnt/t/snapshots/2016-02-13T09:08:18+01:00/bin
    11289   /mnt/t/snapshots/2016-02-13T09:08:18+01:00/bin

Maybe you can fix this by providing a faked blocksize. If not a note regarding --apparent-size in the User Manual would be nice.

**Comment by fd0** [comment]
Hey, thanks for raising this issue. This seems indeed a good idea to have.

**Comment by viric** [comment]
"apparent size" is the *file size*. The amount of bytes in the file. That's correct for du.

Du without parameters should report the *disk space used* instead of file sizes, which may be tricky to define in restic.
