### ISSUE TITLE
virustotal false positively detects malware (MaxSecure)

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4430]
I've uploaded
https://github.com/restic/restic/releases/download/v0.16.0/restic_0.16.0_windows_amd64.zip
to
https://www.virustotal.com/

where MaxSecure reported Trojan.Malware.300983.susgen
![image](https://github.com/restic/restic/assets/6294586/a0da699a-ce7f-491b-9a22-c09e88d4758a)
![image](https://github.com/restic/restic/assets/6294586/b0bba6a0-88c0-4c67-b7c8-cca1fea63b57)

I assume it's a false positive but maybe you can do "something" to prevent this. 🙂

**Comment by AlBundy33** [comment]
Maybe it's more related to go than to restic 🤔 
https://github.com/lian/msfs2020-go/issues/14

**Comment by MichaelEischer** [comment]
I don't think there's anything we can do on our side. The name "susgen" sounds like they're randomly complaining about some part of the binary without any clear suspicion. If the match here is against some part of the go runtime, then only some explicit allow listing might help. But that has to be done by the AV vendor, and would have to be repeated for every new restic version.
