### ISSUE TITLE
add support for HTTP connections to Azure Storage Backend

### ISSUE THREAD

**Issue by konidev20** [restic/restic#4438]
Output of `restic version`
--------------------------
restic 0.16.0

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Allow HTTP connections to Azure Storage Services when explicitly specified. (The default will be HTTPs which is recommended)

> The Azure storage services support HTTP and HTTPS; however, using HTTPS is highly recommended.
Reference: [Azure Storage REST API Reference | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/storageservices/)

Azure Storage Services allow HTTP communications when `Secure Transfer Required` field is disabled under the `Configuration` tab of the storage account.

Hence, restic must allow HTTP connections to Azure Storage Services.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
- Add support for HTTP connections when the user explicitly specifies a flag to do so. 
- Support for HTTP is required when users are using custom domains for Azure Storage Services or are using it in private cloud configurations.

**Comment by MichaelEischer** [comment]
> Azure Storage Services allow HTTP communications when `Secure Transfer Required` field is disabled under the `Configuration` tab of the storage account.

Depending on the type of authentication used, that sounds like a bad idea.

To quote https://learn.microsoft.com/en-us/azure/storage/common/storage-require-secure-transfer

> Microsoft recommends that you always require secure transfer for all of your storage accounts.

> * Support for HTTP is required when users are using custom domains for Azure Storage Services

It's currently not possible to specify custom domains. And as restic generally isn't a user-facing service, I don't see the actual use case for that so far.

> or are using it in private cloud configurations.

Shouldn't the Azure provided HTTPS for an Storage Account also work for Service/Private Endpoints?

**Comment by konidev20** [comment]
Hey @MichaelEischer, 

> Depending on the type of authentication used, that sounds like a bad idea.

I'm proposing it as an option that must be explicitly specified.  Take Restic's S3 storage backend for example, it provides similar handling when HTTP URLs are provided; `UseHTTP` is enabled in the config there. If it's a bad idea here, it would be a bad idea there as well, I reckon.

> Because Azure Storage doesn't support HTTPS for custom domain names, this option is not applied when you're using a custom domain name.

Refer: https://learn.microsoft.com/en-us/azure/storage/common/storage-require-secure-transfer

> It's currently not possible to specify custom domains in restic. And as restic generally isn't a user-facing service, I don't see the actual use case for that so far.

I believe restic added support for custom domains with #4387 (linked to #2468). I didn't get the part about Restic not being a user-facing service?

**Comment by MichaelEischer** [comment]
> I'm proposing it as an option that must be explicitly specified. Take Restic's S3 storage backend for example, it provides similar handling when HTTP URLs are provided; `UseHTTP` is enabled in the config there. If it's a bad idea here, it would be a bad idea there as well, I reckon.

The authentication of S3 is similar to a Storage Account's Shared Key. AFAIK doesn't provide the equivalent of SAS/OAuth tokens, which are insecure with HTTPS. The fact that S3 offers an option without HTTPS does not mean that any other backend should do so too, unless there's a good reason for it.

> I believe restic added support for custom domains with #4387 (linked to #2468).

No. The PR and issue are about the independent Azure clouds: https://learn.microsoft.com/en-us/azure/storage/common/storage-powershell-independent-clouds .

**Comment by konidev20** [comment]
Okay, will close this Issue and PR. I don't think I have a good enough reason for it. I will re-open when I feel there is sufficient need for it.

**Comment by konidev20** [comment]
@MichaelEischer do you recommend we add support for custom domains? And then pick this up?
