### ISSUE TITLE
Switch development build system to gb

### ISSUE THREAD

**Issue by fd0** [restic/restic#444]
I'd like to switch restic over to using [gb](https://getgb.io/) for development. I've worked with `gb` for other projects, and it really improved my workflow.

This gets us:
 * Reproducible builds, even for development. All code is in the repository, compiling it is completely independent of other code users/developers might have laying around in their `GOPATH`. This prevents things such as #431 which was caused by a newer (not compatible) version of the sftp library.
 * Easier start for new developers: No need to setup a `GOPATH` or git remotes.
 * The repository is self-contained, for developers and end-users.
 * Clean separation between our code (in `src/`) and other code (in `vendor/`)
 * Faster compilation for development: gb only compiles modified files, [in contrast to `go build`](http://dave.cheney.net/2014/06/04/what-does-go-build-build)
 * No support for `go get` for restic any more. This may be unpopular, but in my opinion that's a feature. For a discussion see #368.
 * Better structure for the repository, all code will live below `src/` and does not clutter the root directory.

For users, I'd modify the `build.go` program to cope with the new structure, so there's no change in the workflow.

What do you think?

**Comment by fd0** [comment]
I've ported the repo to `gb`, if you are curious see #445 and the branch `switch-to-gb`.

**Comment by mappu** [comment]
You ask for thoughts,

If it's possible, i think it would be best to use the standard go tooling. It's like https://xkcd.com/927/ comic.

But the concept of golang dependency ecosystem does not yet have obvious solution (like npm for node). It's a big argument for the whole golang community, not to be fought and won in this single repo. And restic already has nonstandard build system (`build.go`). So, if you like gb better and the convert patch is done, then, i think +1.

**Comment by fawick** [comment]
I agree that `gb` is the way to go (no pun intended). IMHO the way it handles vendored code is the only one that makes sense.
