### ISSUE TITLE
Test case in master_index: blobs with same ID have different content length

### ISSUE THREAD

**Issue by codingbaobao** [restic/restic#4448]
Output of `restic version`
--------------------------
restic 0.16.0

How did you run restic exactly?
-------------------------------
go test ./..

Expected behavior
-----------------
If two blobs having same ID(hash), their data length should be the same

Actual behavior
---------------
They have different length when setting up test case
https://github.com/restic/restic/blob/e60c5b2d7f87004b69be546ea29cd3286a57b400/internal/index/master_index_test.go#L43-L60

Although the test in below always correct, its because `blob12a` push into master_index earlier, however I don't think its a guarantee feature.
https://github.com/restic/restic/blob/e60c5b2d7f87004b69be546ea29cd3286a57b400/internal/index/master_index_test.go#L117-L119

If you change the insert order, the test on above fail.
https://github.com/restic/restic/blob/e60c5b2d7f87004b69be546ea29cd3286a57b400/internal/index/master_index_test.go#L62-L72

How to fix
---------------
simply change the `Length` to `uint(crypto.CiphertextLength(80)) `, `UncompressedLength` to `123` in `blob12b`

I can create a pr if you need

**Comment by MichaelEischer** [comment]
You're right, both `blob12a` and `blob12b` should have the same length and uncompressed length.



> simply change the `Length` to `uint(crypto.CiphertextLength(80)) `, `UncompressedLength` to `123` in `blob12b`

Just adding the uncompressed length to `blob12a` would be even simpler.
