### ISSUE TITLE
prune: `Data seems to be missing`-Error is too verbose

### ISSUE THREAD

**Issue by espindola** [restic/restic#4449]
Output of `restic version`
restic 0.15.2 compiled with go1.20.4 on linux/amd64

How did you run restic exactly?

The command was

restic -r /backup2/restic  "forget" "--prune" "--keep-daily=7" "--keep-weekly=4" "--keep-monthly=12" "--keep-yearly=10"

It is running as part of a small backup automation program I wrote.

The error is so big it overflows my log, so I can only say that it includes a lot of:

 <tree/6fb71510> <data/6fb71826> <data/6fb71f64> <data/6fb7203b> <data/6fb7281a> <data/6fb729e9> <data/6fb72f2a> <data/6fb73415> <data/6fb73a12> <data/6fb73bd9> <data/6fb740f9> <data/6fb74459> <data/6fb74780> <data/6fb75303> <data/6fb75719> <data/6fb75abb> <data/6fb76213> <tree/6fb76388> <data/6fb76400> <data/6fb7647c> <data/6fb76572> <tree/6fb76bf6> <data/6fb76d1b> <tree/6fb76ed7> <data/6fb771b2> <data/6fb77b04> <data/6fb78396> <data/6fb790c5> <tree/6fb79583> <data/6fb795cc> <data/6fb7963f> <data/6fb798e3> <tree/6fb79e9f> <data/6fb7a2fa> <data/6fb7a4c5> <tree/6fb7a75b> <data/6fb7a809> <data/6fb7b0e5> <tree/6fb7b394> ....

Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: Integrity check failed: Data seems to be missing.
Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: Will not start prune to prevent (additional) data loss!
Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: Please report this error (along with the output of the 'prune' run) at
Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: https://github.com/restic/restic/issues/new/choose
Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: Fatal: index is not complete

Running the command again produces no errors. Running

ras-mc-ctl  --summary

reports no disk or ECC errors. Just before forget the backup program also ran:

restic check --read-data -r /backup2/restic

and that reported no errors.

I suspect a bug in restic's forget command, but it is hard to say with the start of the log truncated. For this reason I am reporting this bug only on the size of the error message.

**Comment by espindola** [comment]
I just realized that the second run of forget not reproducing the error is expected, since the second run will have deleted no snapshots and not started a prune. I am doing a manual prune now.

**Comment by espindola** [comment]
The manual prune reproduces the error.  The log is

```
loading indexes...
loading all snapshots...
finding data that is still in use for 81 snapshots
Fatal: failed to refresh lock in time
[4:25] 98.77%  80 / 81 snapshots

searching used packs...
{<data/0000027e> <data/000006e3> ....
Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
Fatal: index is not complete
```
and is 73 MB long because of the super long line.

**Comment by espindola** [comment]
a rebuild-index solved the problem. I don't know how the index first got corrupted, but the only known bug then is the error message being 73 MB long :-)

**Comment by MichaelEischer** [comment]
> Is there a `restic check` command that checks the index?

`check` always checks the index. And would produce even more output.

> and is 73 MB long because of the super long line.

That looks like your repository lost about 200MB of index files. How large is the `index` folder of the repository currently?

Did you notice any errors reported in prior restic runs before the failed `forget` or did something unexpected happen? Maybe an interrupted network connection or did the host go into standby while restic was running? Do you have logs of the `backup` and `prune`/`forget` run before the failing one? Did restic report any errors there?

How often do you run `backup`, `check` and/or `prune`?

But you're right about the large error message. Limiting it to like 1000 entries and only printing that together with the total number would be enough information.

**Comment by espindola** [comment]
> > Is there a `restic check` command that checks the index?
> 
> `check` always checks the index. And would produce even more output.

That is odd, my script runs "check --read-data" fairly frequently and that never reported a problem. The script was running "forget --prune" and, I now realize, failing when forget would drop a snapshot and run prune. I have now changed the script to

* run prune without --forget
* check --read-data
* run prune
* check --read-data

So hopefully this will find something interesting if the problem happens again.

> > and is 73 MB long because of the super long line.
> 
> That looks like your repository lost about 200MB of index files. How large is the `index` folder of the repository currently?

229 MiB

> Did you notice any errors reported in prior restic runs before the failed `forget` or did something unexpected happen? Maybe an interrupted network connection or did the host go into standby while restic was running?

No, but unfortunately the error message ate all my previous log :-(

There is a good chance this was an old error, since prune was only running when forget deleted a snapshot, and only then would an error show up (but no idea why the regular check runs were reporting nothing).

> Do you have logs of the `backup` and `prune`/`forget` run before the failing one? Did restic report any errors there?

No, see the note about the error eating my logs.

> How often do you run `backup`, `check` and/or `prune`?

I have a setup with two disks on a small server. I backup my machines to disk1 about once a week.  The server runs a program that copies from disk1 to disk2 and checks/prunes each once a week.

> But you're right about the large error message. Limiting it to like 1000 entries and only printing that together with the total number would be enough information.

Sounds good to me!

Thanks.

**Comment by espindola** [comment]
BTW, reading the code I found the following comment on doPrune

// - rebuild the index while ignoring all files that will be deleted                                                                                                    
// - delete the files 

so a power failure or other sudden stop can cause the index files to be incomplete, no? Should restic handle it by rebuilding the index when needed? Or at least mention "rebuild-index" in the error?

**Comment by MichaelEischer** [comment]
> There is a good chance this was an old error, since prune was only running when forget deleted a snapshot, and only then would an error show up (but no idea why the regular check runs were reporting nothing).

Based on the number of missing data blobs reported by prune and the current index size, it looks like the complete index went missing. In that case the `backup` command would have complained and exited with a non-zero exit code (but still created a snapshot).

> // - rebuild the index while ignoring all files that will be deleted

Rebuilding the index first writes the new index files and only afterwards deletes the old index. Thus, a power failure can only leave the repository with too many index files, but cannot cause missing index files. Restic also explicitly waits until the storage claims that the index was actually written to disk. Missing index files in that scenario are only possible if the storage claims that the index was stored even though that isn't the case.

That explanation assumes that you don't use the `--unsafe-recover-no-free-space` option. 

> Should restic handle it by rebuilding the index when needed? Or at least mention "rebuild-index" in the error?

As discussed above, a damaged index by design indicates misbehavior of the repository storage. That requires an investigation of what went wrong.
