### ISSUE TITLE
Path usage for backup/restore not consistent.

### ISSUE THREAD

**Issue by lImbus** [restic/restic#446]
I promised to fd0 I would create an issue for this, although by now, I am not entirely sure of the problem anymore. What I was trying to do can be seen in #407.

The core of the issue here is that "backup" and "restore" behave slightly differently in handling paths. From the internals of the workings, this is totally understandable, for an operator it is not. Sitting in a working copy directory ("foo") and calling `restic backup .` will backup not all the contents of this directory, but this directory. Sitting in the same directory ("foo") and calling `restic restore <ID> --target .` will create a new sub-directory "foo".

**Comment by fd0** [comment]
Thanks for pointing this out. Running `restic backup .` is indeed a peculiar corner case, I'll classify this as an enhancement.

**Comment by fd0** [comment]
This will be resolved by #549, so I'm going to close this as a duplicate.
