### ISSUE TITLE
Use POSIX_FADV_DONTNEED for backing up files to don't pollute cache

### ISSUE THREAD

**Issue by JsBergbau** [restic/restic#4465]
Output of `restic version`
--------------------------

Current dev version 08.09.2023 

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When backing up, restic should use POSIX_FADV_DONTNEED flag. 

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Restic backs the files up. It is very unlikely that these files will be need to re-read again in the next time. Currently this files go to cache, pollute it, so the really needed files vanish from cache and have to be re-read from disk.

This trick does the nocache command, see https://github.com/Feh/nocache
However this won't work with restic since go doesn't use the C standardlibrary, so it has to be implemented in restic. 

Maybe also using O_DIRECT flag is a solution, however this requires benchmarking if this makes reading files slower. 

This is analog the feature request for rest-server serving the same purpose, see https://github.com/restic/rest-server/issues/253

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic makes me really happy. It is the best backup programm I've ever seen.

**Comment by MichaelEischer** [comment]
This has already been evaluated in #2595 and #666. The tl;dr of these issues is that, `POSIX_FADV_DONTNEED` removes data from the page cache, which also includes data that is in use by other programs! The end result is a massive negative performance impact.

(P.S.. the nocache command relies on the `mincore` syscall, which as of Linux 5.0 no longer indicates whether a page is in the page cache or not: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=574823bfab82d9d8fa47f422778043fbb4b4f50e . Thus, that approach no longer works.)

**Comment by JsBergbau** [comment]
Thanks for the valuable info. I didn't expect that an unpriviledged process could remove the cache content for other processes. For me this looks a bit like a security issue in the linux kernel.

Anyway, makes sense not to implement this.

**Comment by JsBergbau** [comment]
There are some interesting benchmarks when using `POSIX_FADV_DONTNEED` https://stackoverflow.com/questions/77074445/effects-of-posix-fadv-dontneed-when-calculating-sha256-sum-with-python-tldr-do
Findings: It doesn't seem to be respected except on Raspberry PI and when using it, it decreases performance.
