### ISSUE TITLE
Local restic cache gets corrupted after first backup

### ISSUE THREAD

**Issue by roughwood** [restic/restic#4466]
`Output of `restic version`
--------------------------
restic 0.16.0 compiled with go1.20.6 on linux/amd64

How did you run restic exactly?
-------------------------------
This shell script:

```
#!/bin/bash
export RESTIC_PASSWORD=my_key_goes_here
export RESTIC_REPOSITORY=sftp:root@192.168.26.21:/mnt/user/backups/restic/monorepo

restic backup /boot --tag storage1-flash -v
```

This is running on Unraid, in this case /boot is my boot drive, but this issue appears when backing up any directory on the system.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SFTP to a second unraid server.

Expected behavior
-----------------
restic should back up to the remote server without issue from my local system.

Actual behavior
---------------
Backup succeeds initially, then any further runs fail with the following error:

repository 792e6a71 opened (version 2, compression level auto)
using parent snapshot c9707c94
invalid character '\x04' in string literal
DecodeIndex
github.com/restic/restic/internal/index.DecodeIndex
        /restic/internal/index/index.go:523
github.com/restic/restic/internal/index.ForAllIndexes.func1
        /restic/internal/index/index_parallel.go:29
github.com/restic/restic/internal/restic.ParallelList.func2
        /restic/internal/restic/parallel.go:45
golang.org/x/sync/errgroup.(*Group).Go.func1
        /home/build/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598

If I delete the cache located at the directory that `restic cache` spits out, I can then run a backup again successfully.

Steps to reproduce the behavior
-------------------------------
This is entirely reproducible on my primary Unraid storage server - the first time that a restic backup is run will succeed, any further attempts will fail with some variant of 'invalid character in string literal'. Sometimes the character is '\x04', sometimes '\x00', or others. After deleting the local cache directory a backup will succeed again.

This has been occurring for months for me, on various versions of restic, including the latest.

I am able to successfully back up to this same repository from many other machines, windows, mac, and linux over SFTP.

Do you have any idea what may have caused this?
-----------------------------------------------
Unsure but I suspect it's some behavior unique to the Unraid OS.

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I love restic, I hope this issue can get solved :)

**Comment by MichaelEischer** [comment]
> This is entirely reproducible on my primary Unraid storage server - the first time that a restic backup is run will succeed, any further attempts will fail with some variant of 'invalid character in string literal'. Sometimes the character is '\x04', sometimes '\x00', or others. After deleting the local cache directory a backup will succeed again.

This is very likely a hardware problem (either CPU or RAM) or a serious bug in the OS. DecodeIndex() only runs after decrypting and verifying the integrity of the loaded index. This leaves only two possibilities how this data corruption can occur: either when writing the index during a backup (not the case as other machines can access the repository) or while decrypting / processing it. With the given information, the latter is the most likely explanation.

> After deleting the local cache directory a backup will succeed again.

That is likely just a coincidence. If the cached data on disk were corrupt, then restic would print a different error message.

**Comment by roughwood** [comment]
Thanks for the reply. I will see if I can troubleshoot the hardware to rule it out.

> > After deleting the local cache directory a backup will succeed again.
>
>That is likely just a coincidence. If the cached data on disk were corrupt, then restic would print a different error message.

It definitely is not a coincidence - after running the first backup and having the local cache created, all further backup attempts will fail 100% of the time. Deleting the local cache directory immediately resolves this problem for a single backup, which creates the cache files, and then further backups continue to fail 100% of the time.

**Comment by MichaelEischer** [comment]
could you run `shasum -a256 path/to/cache/index/*/*` with such a damaged cache? The sha256 hash should match each file's filename.

Please also use `shasum` to verify the file in the repositories index folder.

**Comment by roughwood** [comment]
I used the following commands to test the index folders as you asked:

On the local machine
`shasum -a256 /mnt/user/appdata/.restic_cache/792e6a71d1b3ba8ba5b70608f63298b3555c9bdb6d0025a2a56d739380a1286f/index/*/* | awk '{split($2, a, "/"); if ($1 != a[length(a)]) print $0}'`

On the remote repository:
`shasum -a256 /mnt/user/backups/restic/monorepo/index/* | awk '{split($2, a, "/"); if ($1 != a[length(a)]) print $0}'`

I tested the command by intentionally editing one of the file names in the cache, which it properly identified as a mismatch. Both of these commands yielded no mismatch between the file names in the index folders and their hashes.

**Comment by MichaelEischer** [comment]
Hmm, if the cache content isn't damaged, then the only difference between downloading and using the cache version is timing. In particular, with an already filled cache, restic is likely to put more stress on the hardware than when having to download the files from scratch. That suggests that the hardware becomes unstable under load or on sudden load changes.

Does setting the environment variable `GOMAXPROCS=1` change anything?

**Comment by roughwood** [comment]
`GOMAXPROCS=1` actually seems to have fixed things. I adjusted my scripts to set this and so far things look good.

**Comment by MichaelEischer** [comment]
Thanks for the reply. As that behavior neatly fits with some weird things happening in the hardware, I'll close the issue for now. Feel free to reopen it if something changes.
