### ISSUE TITLE
Add download limit of total bytes for prune

### ISSUE THREAD

**Issue by ShadowBladezx86** [restic/restic#4473]
Output of `restic version`
--------------------------

restic 0.16.0 compiled with go1.20.7 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Allow a download cap to be set on total bytes downloaded per prune operation.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

On B2, we get 1GB of free download bandwidth daily (due to plan updates this is set to become 3GB starting October 3rd). I'd like to use close to 900MB every day to prune "for free" little bits of data. Similar to `--max-repack-size 1G` I'd like Restic to download no more than 1GB of data to aid in repacking during a prune.

I hope it is able to be done, because I understand restic might not know how much is cache-aided and how much has to be re-downloaded in order to prune.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic together with B2 is perfect as all similar data gets de-duped essentially and incremental snapshots are fantastic. I love the network-mount option as well, it has saved me during a recovery of particular files to get my system going and later slowly drip the remaining files into my system and/or use my other backups once I got my initial setup online.

I currently have a set of 2 prune commands running every day after backups are forgotten:
* prune using only cache, doing some easy stuff
* prune repacking no more than 1G, so I don't go over the free limit, however cache is also used and lowers the amount of free bandwidth used.

After this, I usually check manually and run an additional prune if it barely used any bandwidth for the day.

**Comment by MichaelEischer** [comment]
> On B2, we get 1GB of free download bandwidth daily (due to plan updates this is set to become 3GB starting October 3rd)

Huh? According to https://www.backblaze.com/blog/2023-product-announcement/ the free egress per month is three times the average storage size. 

> Allow a download cap to be set on total bytes downloaded per prune operation.

This is incredibly complex to calculate. It is not enough to consider which files are already cached, as prune only downloads the relevant file parts. I really don't think this is worth the effort.

**Comment by ShadowBladezx86** [comment]
> Huh? According to https://www.backblaze.com/blog/2023-product-announcement/ the free egress per month is three times the average storage size.

In my case I have 372GB kept, of which 10GB is free, and every 60GB additional I noticed is exactly $0.01/day. I was also confused by the pricing they promise on their website, but it's not *phrased* the same way as it is calculated daily. On top of that, I get "the first 1GB is free" on the download caps. Lastly there is some set amount of free Class B and Class C transactions, but with Restic it's easy to deal with that too, since 1000s of "real" small files turn into a couple of big packed blobs anyway.
I myself predict it will go from 1¢/60GB/day to 1¢/50GB/day, and the increase of 1GB to 3GB free download is nice for prune operations.
> This is incredibly complex to calculate. It is not enough to consider which files are already cached, as prune only downloads the relevant file parts. I really don't think this is worth the effort.

I understand this is likely too complex of a feature to bother putting it in Restic, as it won't know *exactly* how much it will actually end up pulling from the repo, right?

**Comment by MichaelEischer** [comment]
> In my case I have 372GB kept, of which 10GB is free, and every 60GB additional I noticed is exactly $0.01/day.

The blog post says that the free egress will be calculated on a monthly basis.

> as it won't know _exactly_ how much it will actually end up pulling from the repo, right?

Well, assuming there are no problems while downloading from the repository, it would theoretically be possible to precisely calculate how much data will be downloaded. But I strongly doubt that it would be worth the significant complexity. The prune code is already convoluted enough. Thinking a bit more about it, I'm not even sure how it could be implemented in an efficient way that does not slow down prune or increases the memory usage.

**Comment by MichaelEischer** [comment]
Closing as I don't think this is worth the massive implementation complexity.
