### ISSUE TITLE
restic copy for new snapshots to another identical repo gets different snapshot id

### ISSUE THREAD

**Issue by andrewchen5678** [restic/restic#4475]
Output of `restic version`
--------------------------

How did you run restic exactly?
-------------------------------

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------
```
cp or rsync repo1 to repo2

restic backup -r repo1  /directory

restic copy --from-repo repo1 -r repo2

```
the newly copied snapshot for /directory on repo2 has different id than repo1

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
This is expected behavior. We cannot maintain identical snapshot ids before https://github.com/restic/restic/issues/523 is solved.
