### ISSUE TITLE
LZ4 support

### ISSUE THREAD

**Issue by rkarlsba** [restic/restic#4482]
Output of `restic version`
--------------------------
restic 0.16.0 compiled with go1.20.6 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Please add suport for the LZ4 compression algorithm and/or similar light-weight algorithms. LZ4 is *way* faster and only compresses a wee tad worse, which I can live with.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Speed up backups

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It generally works wel, but everything an be improved :)

**Comment by MichaelEischer** [comment]
Do you have any numbers that back up that claim? What performance region are we talking about? Adding another compression algorithm complicates the repository format.

**Comment by g33kphr33k** [comment]
http://compressionratings.com/ratings.html

If you want to be pedantic for compression speed vs size then you may as well use the real-world ratings table.

**Comment by MichaelEischer** [comment]
@g33kphr33k what do these compression ratings tell me? Based on a quick glance, there seem to be no results using zstd?

**Comment by greatroar** [comment]
LZ4 compression can be *much* worse than zstd, depending on the data. If a lighter-weight compression algorithm is necessary, I think it would be better to investigate an algorithm that produces the zstd format. E.g., [compress/flate](https://pkg.go.dev/compress/flate) has a HuffmanOnly setting that skips the LZ77 (backwards matching) part of compression. Something like that should be possible to implement in klauspost/compress/zstd as well.

**Comment by greatroar** [comment]
Here's an example of where LZ4 is absolutely terrible: lists of hashes. This program creates a list of "hashes", i.e., random hex strings:

```go
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"math/rand"
	"os"
)

func main() {
	r := make([]byte, sha256.Size)
	p := make([]byte, 1+2*sha256.Size)
	p[len(p)-1] = '\n'

	for i := 0; i < 50000; i++ {
		rand.Read(r)
		hex.Encode(p, r)
		os.Stdout.Write(p)
	}
}
```

The output of this is 3250000 bytes, about 3.1MiB. Let's run the reference implementations of lz4 and zstd on its output:

```
$ /usr/bin/time lz4 --fast hashes 
Compressed filename will be : hashes.lz4 
Compressed 3250000 bytes into 3250019 bytes ==> 100.00%                        
0.00user 0.00system 0:00.01elapsed 93%CPU (0avgtext+0avgdata 8016maxresident)k
0inputs+6352outputs (0major+1692minor)pagefaults 0swaps

$ /usr/bin/time zstd -1 hashes
hashes               : 50.97%   (3250000 => 1656489 bytes, hashes.zst)         
0.01user 0.00system 0:00.01elapsed 110%CPU (0avgtext+0avgdata 7796maxresident)k
0inputs+3240outputs (0major+1447minor)pagefaults 0swaps

$ /usr/bin/time lz4 --best hashes 
Compressed 3250000 bytes into 2493411 bytes ==> 76.72%                         
0.17user 0.00system 0:00.18elapsed 99%CPU (0avgtext+0avgdata 7444maxresident)k
0inputs+4872outputs (0major+1580minor)pagefaults 0swaps
```

On this data, zstd in its fastest mode compresses much better than LZ4's best mode, and runs much faster. I bet the Go implementations' performance will be very similar.

**Comment by MichaelEischer** [comment]
Closing as zstd seems to be the best general choice and support multiple compression algorithms would add complexity.
