### ISSUE TITLE
Please add annoying to the description ( "Fast, secure, efficient, annoying backup program")  

### ISSUE THREAD

**Issue by benchonaut** [restic/restic#4508]
Output of `restic version`
--------------------------
0.16.0 , but it is crippled since many versions

How did you run restic exactly?
-------------------------------
( numerous ways, scripted , manually  )

it cripples up on everything except local files and wired connections directly to the rest server 

on of many examples
```
restic --insecure-tls -r $RESTIC_REPOSITORY  -o rclone.args="serve restic --stdio   --ftp-disable-tls13 --tpslimit=10 --drive-chunk-size=256M --drive-use-trash=false  --ftp-tls-cache-size=128 --ftp-no-check-certificate --ftp-concurrency 2 --checkers 1 --transfers 1  "  -v backup --no-scan / --exclude /the/brain/of/restic/devs
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

numerous , rclone/local/sftp/rest-server/S3

Expected behavior
-----------------

Do not crap up hours of work (!!!) 
Do retries and give parameters for that , not just that noobish 1..2..BBQ thing
Do not trust rclone or read its output programattically  ( retrying on "421 too many clients" is exactly what the 421 throttles , congratulations on letting users exceed all retry limits quickly )

Do not die on:
  
 - "this does not look like a tls handshake"(rclone -> the abovementioned 421 problems )
 
-  "read: network is unreachable" ( WTF ; RESTIC NEEDS A FIXED CABLE ; THATS MORE THAN AWKWARD/EMBARASSING, "yes , you can backup , but uh-oh , no mobile users , no people with instable wi-fi ( and it even crapped up 20m next to a LTE BSC )
 
 ONCE AGAIN: MAKE IT RECONNECT-STABLE , it is completely useless like that

Actual behavior
---------------

diying on 5 retries of ~500ms on rclone ( have you ever seen a network reconnect in 500ms ? really ? )

dying on "unkown" number of retries on own rest-server backend

not being able to tell it "then wait 30s until network recovered" or even tell it "wait until you can ping the thing" , just seeing it die ( over and over )

Steps to reproduce the behavior
-------------------------------

use it with rclone or rest backend and have a network reconnect or something else , usually short interruptions are enough let restic die and waste your time ( shall i buy you a coffee ? :( )

Do you have any idea what may have caused this?
-----------------------------------------------

People who did not implement retrying and try it in their ivory tower once, then try to convince others it would be stable or even blame it on the users ( i read all the other posts/issues/PRs on the retry and rclone  issue )

Do you have an idea how to solve the issue?
-------------------------------------------

implement retry parameters , do not trust rclone , do not trust whatever code restic currently has , do not trust yourself 

CHECK IF RCLONE TELLS YOU THAT YOU HAVE "421 too many clients" and COME BACK LATER ( it says "this does not look like a tls" and dies" )  , i firstly researched real problems until i realized that the implementation ist just totally noobish 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

well on other days , 
this day it wasted ~90GByte LTE data to happily break , like a little dog with its face full of poo expecting you to play with him/her

**Comment by MichaelEischer** [comment]
I'm not going to take a look at this deeply disrespectful issue. If you're actually interested in having restic behave differently, then rewrite your rant to be less aggressive (and there's no need to yell all the time).
