### ISSUE TITLE
Restore fails with special character files made with mknod

### ISSUE THREAD

**Issue by rgrewe** [restic/restic#4510]
Output of `restic version`
--------------------------
restic 0.16.0 compiled with go1.20.7 on linux/amd64

How did you run restic exactly?
-------------------------------
```log
[admin@db9b5d655119 ~]$ restic init -r backup/
enter password for new repository: 
enter password again: 
created restic repository 394875cee0 at backup/

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
[admin@db9b5d655119 ~]$ restic -r backup/ backup /home/admin/data/
enter password for repository: 
repository 394875ce opened (version 2, compression level auto)
created new cache in /home/admin/.cache/restic
no parent snapshot found, will read all files

Files:           0 new,     0 changed,     0 unmodified
Dirs:            3 new,     0 changed,     0 unmodified
Added to the repository: 1.319 KiB (1.094 KiB stored)

processed 0 files, 0 B in 0:00
snapshot 84a05061 saved
[admin@db9b5d655119 ~]$ restic -r backup/ restore 84a05061
Fatal: please specify a directory to restore to (--target)
[admin@db9b5d655119 ~]$ restic -r backup/ restore 84a05061 --target /
enter password for repository: 
repository 394875ce opened (version 2, compression level auto)
restoring <Snapshot 84a05061 of [/home/admin/data] at 2023-10-10 09:39:56.421694104 +0000 UTC by admin@db9b5d655119> to /
ignoring error for /home/admin/data/test: file exists
Summary: Restored 3 / 4 Files (0 B / 0 B) in 0:00
Fatal: There were 1 errors
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local

Expected behavior
-----------------
I expect that restic restores the data without errors.

Actual behavior
---------------
restic fails with file types like `block (buffered) special file`, `character (unbuffered) special file` and `FIFO`.

Steps to reproduce the behavior
-------------------------------
* Create special file with mknod. (I used `mknod data/test p` above)
* Backup it
* Try to restore it

Do you have any idea what may have caused this?
-----------------------------------------------
At restoring you try to recreate the file again with mknod, but mknod does not like if the file already exists.
```
[admin@db9b5d655119 ~]$ mknod data/cool p
mknod: data/cool: File exists
```

Do you have an idea how to solve the issue?
-------------------------------------------
If I have it correct in my mind you already remove some other special files before recreating.
https://github.com/restic/restic/blob/master/internal/restic/node.go#L304
Maybe this is also a solution for it. But I am not sure. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
We use your product already since a relative long time and are very happy about it.
Good work! Keep on it. :-)

**Comment by MichaelEischer** [comment]
Fixed by https://github.com/restic/restic/pull/4864.
