### ISSUE TITLE
documentation: integrate manual into main repo

### ISSUE THREAD

**Issue by fd0** [restic/restic#452]
Find a suitable documentation framework and integrate the manual as a human-readable text file (e.g. markdown) into the main restic repository. From there on, require new features and pull requests add documentation before the code is merged. This way, a checkout of the repo automatically has the matching documentation/manual available to the user.

Possible choices:
 * [readthedocs](https://readthedocs.org), which uses [sphinx](http://www.sphinx-doc.org/en/stable/) or [mkdocs](http://www.mkdocs.org/)
 * [flatdoc](http://ricostacruz.com/flatdoc/)
 
The manual for the latest released version of restic should be deployed to the homepage.

I'm not entirely sure what the best approach here is, regarding the technical implementation. I'd like to not depend on another hosted service (GitHub as a dependency is enough I think), but something like readthedocs (which offers several versions of the docs, at the user's choice) may be nice.

Any thoughts?

**Comment by cdrx** [comment]
I like readthedocs, it is another dependency but its been around a while and the source is just ReStructuredText so can easily be moved to something else if readthedocs went away. 

GitHub wiki might be an option?

**Comment by fd0** [comment]
> GitHub wiki might be an option?

No, because it's not versioned and not in any way coupled to the code. This leads to the (rather typical) situation where the wiki contains really old documentation that nobody cares about.

**Comment by fd0** [comment]
I've settled for mkdocs for now (we can still switch to something else later if necessary). I've also setup readthedocs.org for restic and ported the documentation and manual back to version 0.1.0. The documentation is available at:
 * 0.1.0: https://restic.readthedocs.org/en/v0.1.0-doc/
 * master: https://restic.readthedocs.org/en/latest/
