### ISSUE TITLE
Microsoft Azure Blob Storage support access tier

### ISSUE THREAD

**Issue by stani0502** [restic/restic#4521]
Output of `restic version`
--------------------------

restic 0.16.0 compiled with go1.20.6 on darwin/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Hi can restic add support for access tier (hot, cool, cold and archive)
https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview

What are you trying to do? What problem would this solve?
---------------------------------------------------------

So we can implement different access tier for different kinds of backup.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Quite happy use restic 👍

**Comment by MichaelEischer** [comment]
We can add that support if someone makes the necessary changes (please have a look at the storageClass option of the S3 backend). However, the `archive` tier won't work as there's no cold storage support in restic so far.

**Comment by konidev20** [comment]
1. We can add support for [Online access tiers](https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview#online-access-tiers); Hot, Cool and Cold Tiers. 
3. There is also the premium tier for low-latency options, but I don't think it would be relevant till there is a community need for it. 
4. Support for [Archive access tier](https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview#online-access-tiers) would not be possible as restic doesn't support cold storages. A relevant thread to follow would be #3202.

I have identified the changes to be made for 1. I will create a PR for it.

**Comment by MichaelEischer** [comment]
> 5\. Cold tier: Up to 15 hours for retrieval, with higher costs than Cool

According to the docs hot/cool/cold are all online tiers. 15hours retrieval looks like the archive tier.

> Only `PackFile` will be stored using the AccessTiers, other files will be stored using the default `Hot` access tier.

Why? This differs from the implementation in the S3 backend. Most metadata files won't change all the time. By now `prune` also only rewrites `index` files if there's an actual change.
