### ISSUE TITLE
Add an option to restic to immediately exit on 403 error when rest-server is in append-only mode

### ISSUE THREAD

**Issue by aldem** [restic/restic#4522]
Output of `restic version`
--------------------------

`restic 0.16.0 compiled with go1.20.6 on linux/amd64`

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Accidentally I ran `restic forget ... --prune` on a rest-server based repository which had `--append-only` option set. This led to unexpected delay as `restic` attempted to retry operation multiple times:

```
$ restic forget -v --host client --keep-tag none --prune`
repository 6d36759e opened (version 2, compression level auto)
Applying Policy: keep all snapshots with tags [[none]]
...
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 397.619917ms: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 1.073224147s: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 909.024306ms: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 1.830712221s: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 2.23466126s: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 3.040093455s: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 4.166889518s: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 10.033057243s: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 18.993350734s: blob not removed, server response: 403 Forbidden (403)
Remove(<snapshot/fb9f8fbbb0>) returned error, retrying after 24.142679571s: blob not removed, server response: 403 Forbidden (403)
unable to remove <snapshot/fb9f8fbbb0> from the repository
[1:06] 0.00%  0 / 1 files deleted
blob not removed, server response: 403 Forbidden (403)
github.com/restic/restic/internal/backend/rest.(*Backend).Remove
        /restic/internal/backend/rest/rest.go:299
...
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598
```

When connecting to rest-server based repository and hitting any kind of "unathorized" (403) error `restic` should not retry the operation multiple times, or at least there should be an option that will allow exit on first unsuccessful attempt.

Most likely any kind of 403 error could not be resolved by itself on a rest-server, so retrying is relatively meaningless. Proper exit code would allow to handle this problem without waiting for 1 minute before it times out.

Ideally, at least for `forget` command it would be nice to have an option that would silently skip the attempt if a rest-server repository is either read-only or is in append-only mode.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

This would help to avoid unnecessary delays in backup/maintenance scripts :)

**Comment by MichaelEischer** [comment]
Fixed by https://github.com/restic/restic/pull/4803
