### ISSUE TITLE
Report progress on SIGUSR1 (when scripted)

### ISSUE THREAD

**Issue by viric** [restic/restic#453]
If I understand correctly, restic does not report progress if not run in a terminal (from a crontab script, let's say).

It'd be nice if it could be signaled to print a line to stdout with the progress, like dd.

**Comment by fd0** [comment]
Thanks for the suggestion. I don't understand your use case: Why do you need a progress report when restic is not run from a terminal? Where should the progress report be sent when there is no terminal?

**Comment by viric** [comment]
The output be a file. A file you can read, and be interested in the
progress at a given moment, instead of blindly waiting because you store
the output to a file.

**Comment by fd0** [comment]
I've thought about this and I don't see the need for it right now.
