### ISSUE TITLE
A:\> restic list locks --verbose=2 > My.Locks.Txt

### ISSUE THREAD

**Issue by Mae72DE** [restic/restic#4536]
Output of `restic version`
--------------------------
restic 0.16.1 compiled with go1.21.3 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
`-r "\\NAS\BackupDrive\BackUp-Name"`
but not working is `set RESTIC_REPOSITORY="\\NAS\BackupDrive\BackUp-Name"`
I've to type: `A:\> set "RESTIC_REPOSITORY=\\NAS\BackupDrive\BackUp-Name"`

Problem description / Steps to reproduce
----------------------------------------

I can redirect every 'list'  to a file,
[blobs|packs|index|snapshots|keys] but not [locks].

Expected behavior
-----------------

```
A:\> restic list locks
repository 6c2143f2 opened (version 2, compression level auto)
```
Actual behavior
---------------

```
A:\> restic list locks  > My.Locks.Txt
A:\> dir My.Locks.Txt
Mi, 25.10.2023  09:39                 0 My.Locks.Txt
```
So it results in an empty 0-Byte File.
So i try this:
```
A:\> restic list locks -v=2 > My.Locks.Txt 2>&1
A:\> dir My.Locks.Txt
Mi, 25.10.2023  09:39                 0 My.Locks.Txt
```
Redirect Std-Out and Err-Out to the file, with --verbose=2 even give me a 0-Byte File-Output.

Do you have any idea what may have caused this?
-----------------------------------------------

No, sorry!

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

More german help would be nice for stupid german Windows-User like me …

**Comment by MichaelEischer** [comment]
The line `repository 6c2143f2 opened (version 2, compression level auto)` is never printed when redirecting the output of restic (the other commands also behave in exactly the same way)

If no other restic instance is running in parallel, then it's expected that the output of `list locks` is empty. Since restic 0.13.0 `list locks` does not lock the repository, such that it's pretty normal to get no output.

**Comment by calebreed601-dot** [comment]
“Ran into the same—ended up just scripting restic list locks --json and
checking timestamps, then calling restic unlock if they’re clearly stale.
Not super elegant, but works for automation.”
