### ISSUE TITLE
Illegal instruction on Raspberry Pi with arm version

### ISSUE THREAD

**Issue by franzs** [restic/restic#4540]
Output of `restic version`
--------------------------

restic 0.16.1

Problem description / Steps to reproduce
----------------------------------------

Calling restic 0.16.1 for arm on a Raspberry Pi results in an `Illegal instruction`.

```
./restic_0.16.1_linux_arm version
Illegal instruction
```

More details:

```
cat /proc/cpuinfo 
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7
```

```
uname -a
Linu xxx 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux
```

```
cat /etc/debian_version 
11.7
```

Version 0.16.0 runs on the same Raspberry Pi without issues:

```
./restic_0.16.0_linux_arm version
restic 0.16.0 compiled with go1.20.6 on linux/arm
```

**Comment by JsBergbau** [comment]
Same problem with me. The official binary seems not to be build with `go run build.go --goos linux --goarch arm --goarm 6`

You can use this binary in the meantime. I've just built it from repo with commit from yesterday.

[resticARM6.zip](https://github.com/restic/restic/files/13176663/resticARM6.zip)

**Comment by MichaelEischer** [comment]
restic 0.16.0 was built using `GOARM=5`, whereas restic 0.16.1 uses `GOARM=7`. This has apparently changed in Go 1.21 https://go.dev/blog/rebuild :

> “assume HWFP unless the build is running on an ARM system without floating-point hardware”

> Calling restic 0.16.1 for arm on a Raspberry Pi results in an `Illegal instruction`.

This only affect the Raspberry Pi 1, which only supports the ARMv6 instruction set. All later models support ARMv7.

**Comment by MichaelEischer** [comment]
https://github.com/restic/restic/pull/4542 will change the build process to set GOARM=6. I'm a bit undecided whether we should already drop GOARM=5 support for a 0.16.2 release or only in 0.17.0. At least from a semver standpoint the latter would be the way to go.

**Comment by franzs** [comment]
@MichaelEischer Thanks a lot for your efforts. :smiley:

**Comment by mirabilos** [comment]
I’m in the process of setting up an RPi 1 right now, so thanks for keeping it supported ;)
