### ISSUE TITLE
HTMLZip version of the documentation is no longer generated.

### ISSUE THREAD

**Issue by DRON-666** [restic/restic#4548]
Problem description / Steps to reproduce
----------------------------------------

Old versions (<=0.16.0) of readthedocs contain a [single-page version](https://readthedocs.org/projects/restic/downloads/) of restic documentation, but after moving to version 2 of the `.readthedocs.yaml` file, `htmlzip` format is no longer generated.

Do you have any idea what may have caused this?
-----------------------------------------------

I am not entirely sure, but I think these lines should be added to `.readthedocs.yaml` to fix this:
```
# Build HTMLZip
formats:
  - htmlzip
```

**Comment by MichaelEischer** [comment]
Could you open a PR with the change? From what I can tell, it's the proper way to reenable the htmlzip format.

**Comment by DRON-666** [comment]
Done, but I think you should run something manually to create missed files for latest release.
