### ISSUE TITLE
macOS watchdog panic when backup drive has no left space

### ISSUE THREAD

**Issue by rybalkoss** [restic/restic#4551]
Output of `restic version`
--------------------------

`restic 0.16.1 compiled with go1.21.3 on darwin/arm64`

What backend/service did you use to store the repository?
---------------------------------------------------------
External exFAT WD HDD. 

Problem description / Steps to reproduce
----------------------------------------

Kernel panic on macos when no space is left on external storage during backup, reproduced twice
Commands for backup:
```
restic init --repo /Volumes/bkp-exfat/backup-repo
restic -r /Volumes/bkp-exfat/backup-repo --verbose backup /Volumes/ssd/files
```

110GB of 350GB is copied, and only 110GB is available on external hard drive.
Panic log:
[macos-panic.txt](https://github.com/restic/restic/files/13215863/macos-panic.txt)

MacOS Sonoma, air m2

Expected behavior
-----------------

Exit with error / check for left space before backup (at least crash of app, not the OS:) )

Actual behavior
---------------

macos freezes for ~2 min and then reboots.

Do you have any idea what may have caused this?
-----------------------------------------------

External drive has less space than required

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Not yet, it's my first backup but I'm looking forward to be happy user of the such a great tool! I did a lot of research for backup utility and Restic looks to me as the perfect solution!

**Comment by MichaelEischer** [comment]
Sorry to hear that restic (indirectly) caused your system to crash. However, restic is only the messenger here. If writing to a disk until there i no more free space crashes the OS, then this is a bug in the OS and not in restic. The only reliable way to fix this is in the OS.

**Comment by rybalkoss** [comment]
@MichaelEischer thank you for the answer, just reported in case it will be beneficial to add a check for free space, or someone will have the same issue.
