### ISSUE TITLE
load/lock : The specified key does not exist

### ISSUE THREAD

**Issue by Framsfex** [restic/restic#4552]
Output of `restic version`
--------------------------
0.16.2

What backend/service did you use to store the repository?
---------------------------------------------------------
Netapp S3 StorageGRID

Problem description / Steps to reproduce
----------------------------------------
I use restic on Redhat 7 with our local S3 storage for several month without problems.
But now I get the following error:

root# restic unlock
SG_TENANT=tik-sp
RESTIC_REPOSITORY=s3:s3.tik.uni-stuttgart.de/tik-sp.restic
repository 94cb371c opened (version 2, compression level auto)

root# restic check
SG_TENANT=tik-sp
RESTIC_REPOSITORY=s3:s3.tik.uni-stuttgart.de/tik-sp.restic
using temporary cache in /tmp/restic-check-cache-1003065793
repository 94cb371c opened (version 2, compression level auto)
created new cache in /tmp/restic-check-cache-1003065793
create exclusive lock for repository
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 676.288663ms: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 393.314976ms: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 556.808795ms: The specified key does not exist.
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 832.042895ms: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 1.402572295s: The specified key does not exist.
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 1.008963481s: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 2.155772504s: The specified key does not exist.
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 2.49629471s: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 3.640986543s: The specified key does not exist.
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 1.807743052s: The specified key does not exist.
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 2.360131845s: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 4.818329421s: The specified key does not exist.
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 5.946044271s: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 2.860003795s: The specified key does not exist.
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 8.608056362s: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 6.475619767s: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 7.926058347s: The specified key does not exist.
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 7.715226292s: The specified key does not exist.
Load(<lock/5fc8640f9f>, 0, 0) returned error, retrying after 16.77688308s: The specified key does not exist.
Load(<lock/76b5cfa022>, 0, 0) returned error, retrying after 27.499749415s: The specified key does not exist.
load indexes
[0:00] 100.00%  1 / 1 index files loaded
check all packs
check snapshots, trees and blobs
[0:03] 100.00%  92 / 92 snapshots
no errors were found

Is it perhaps an internal S3 error/problem?
Can I fix it with some restic commands?

**Comment by MichaelEischer** [comment]
These error look like a problem with the S3 storage. Can you manually check whether you can download the files with prefix `locks/76b5cfa022[...]` or `locks/5fc8640f9f[...]`?

**Comment by Framsfex** [comment]
On Wed 2023-11-01 (13:32), Michael Eischer wrote:

> These errors look like a problem with the S3 storage. Can you manually
> check whether you can download the files with prefix
> `locks/76b5cfa022[...]` or `locks/5fc8640f9f[...]`?

Sorry, but what is a prefix?
I have:

***@***.***:~# restic snapshots -c --host sp-i
SG_TENANT=tik-sp
RESTIC_REPOSITORY=s3:s3.tik.uni-stuttgart.de/tik-sp.restic
repository 94cb371c opened (version 2, compression level auto)
ID        Time                 Host  Tags
-------------------------------------------
8c9b2fa6  2023-10-15 03:16:01  sp-i  conf
513cb78e  2023-10-21 03:16:01  sp-i  conf
856e4c62  2023-10-27 03:16:01  sp-i  conf
e610a221  2023-10-28 03:16:02  sp-i  conf
36cca9b4  2023-10-29 03:16:02  sp-i  conf
49f8f357  2023-10-30 03:16:02  sp-i  conf
5ff68e6f  2023-10-31 14:45:44  sp-i  conf
84f67d59  2023-11-01 03:16:01  sp-i  conf
c1dfef91  2023-11-02 15:03:38  sp-i  conf
-------------------------------------------
9 snapshots

***@***.***:~# restic snapshots | grep 76b5cfa022
***@***.***:~# 


-- 
Ullrich Horlacher              Server und Virtualisierung
Rechenzentrum TIK
Universitaet Stuttgart         E-Mail: ***@***.***
Allmandring 30a                Tel:    ++49-711-68565868
70569 Stuttgart (Germany)      WWW:    https://www.tik.uni-stuttgart.de/
***@***.***>

**Comment by Framsfex** [comment]
Meanwhile I cannot reproduce the errors any more - using the same restic commands!
It seems our S3 storage is or was damaged :-(

**Comment by MichaelEischer** [comment]
> Sorry, but what is a prefix?

In the context above, "Can you manually check whether you can download the files with prefix locks/76b5cfa022[...] or locks/5fc8640f9f[...]?" is a different way of saying "Can you manually check whether you can download the files whose name starts with locks/76b5cfa022[...] or locks/5fc8640f9f[...]?".

> Meanwhile I cannot reproduce the errors any more - using the same restic commands!
> It seems our S3 storage is or was damaged :-(

That essentially confirms my suspicion. S3-like storage can at times be slightly inconsistent, however, the problem should quickly resolve itself. If it doesn't, then the S3 storage has to be fixed. I'll close this issue, as there's nothing restic can do to workaround the problem.
