### ISSUE TITLE
Cosmetic: Less frantic updating of ETA

### ISSUE THREAD

**Issue by wezm** [restic/restic#4562]
Output of `restic version`
--------------------------

restic 0.16.2 compiled with go1.21.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

The ETA value is seemingly updated multiple times a second and is distracting when a window with it present is visible. I think that updating it once a second would be more than enough.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I am performing an initial backup of my system. The ETA value is franticly updating multiple times a second as shown in the video below:

https://github.com/restic/restic/assets/21787/2b2d69ba-bb31-46c9-9c94-ed2b80ec4e3b

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I've used restic for about 4 years and it's been great. After recently setting up a new machine I surveyed the Linux backup options once more and concluded restic is still the best option (for me) out there. Thanks for your efforts.

**Comment by madroach** [comment]
Doesn't the [`RESTIC_PROGRESS_FPS`](https://restic.readthedocs.io/en/stable/040_backup.html#environment-variables) do what you are asking for?

**Comment by wezm** [comment]
Yes it looks like it does. I was not aware of this. It appears like the [default is to update 60 times per second](https://github.com/restic/restic/blob/8b08b522c9e5bdcc1daeacab895c4e3e08e392e8/cmd/restic/progress.go#L19), which seems excessive but thanks for the pointer to how to change it.

**Comment by madroach** [comment]
Indeed 60fps is excessive. I'd opt for something between 1 and 5. Personally I use 2.
