### ISSUE TITLE
macOS error UtimesNano: operation not permitted on sudo restic restore

### ISSUE THREAD

**Issue by Kay-LGLN** [restic/restic#4564]
Output of `restic version`
--------------------------
restic 0.16.2 compiled with go1.21.3 on darwin/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
An S3 bucket on Kubernetes hosted on the internet, but within the EU.

Problem description / Steps to reproduce
----------------------------------------
I'm using (Intel) macOS Sonoma patched to
```bash
$ sw_vers
ProductName:	macOS
ProductVersion:	14.0
BuildVersion:	23A344
```
with System Integrity Protection (SIP) enabled
```bash
$ csrutil status
System Integrity Protection status: enabled.
```
and [iTerm2](https://iterm2.com/) (Build 3.4.22). I found [this hint](https://github.com/restic/restic/issues/2051#issuecomment-430779549) that enabled SIP **could** cause restic problems, the suggested solution I found was to use macOS full diskaccess. That's why I configured macOS full diskaccess for
```
/System/Applications/Utilities/Terminal.app
/Applications/iTerm.app
/usr/local/bin/restic
/usr/local/Cellar/restic/0.16.2/bin/restic
```
iTerm2 runs my bash that interacts with restic.

**Initialize the repository:**
```bash
export sudoPW="secret";
export RESTIC_PASSWORD="secret";
export AWS_ACCESS_KEY_ID="secret";
export AWS_SECRET_ACCESS_KEY="secret";
export UserName="$(stat -f%Su /dev/console)";
export RealNameSpaced="$(dscl . -read /Users/$UserName RealName | cut -d: -f2 | sed -e 's/^[ \t]*//' | grep -v "^$" | awk '{print tolower($0)}')";
export RealNameDotted=${RealNameSpaced// /.};
export S3_Bucket_MyBase_URL="s3:https://s3.eu-de.cloud-object-storage.appdomain.cloud/backup-${RealNameDotted}";
export local_iPad_Backup="/Users/$USER/Library/Application Support/MobileSync/Backup/";
restic -r "$S3_Bucket_MyBase_URL/iPad_backup" init;
```

**Backup:**
```bash
echo $sudoPW | sudo -p "" -S -E bash -c 'restic --repo "$S3_Bucket_MyBase_URL/iPad_backup" backup "$local_iPad_Backup"
```

**Restore:**
```bash
echo $sudoPW | sudo -p "" -S -E bash -c 'restic -r $S3_Bucket_MyBase_URL/iPad_backup --verbose=2 restore latest --target "/"'
```
Restic executed with sudo has an error upon restoring my restic iPad backup. Restics error message doesn't help me to find the reason for the error. The options `--verbose` and `--verbose=2` doesn't change restics restore output to be more detailed.

Expected behavior
-----------------
Upon restics restore I'd expect restic to reproduce all data exactly as they were prior the backup. The options `--verbose` and `--verbose=2` should change restics output to be more detailed.

Actual behavior
---------------
```bash
$ echo $sudoPW | sudo -p "" -S -E bash -c 'restic -r $S3_Bucket_MyBase_URL/iPad_backup --verbose=2 restore latest --target "/"'
repository 535a9ac9 opened (version 2, compression level auto)
[0:00] 0.00%  0 / 1 index files loaded
restoring <Snapshot 0ea37a4c of [/Users/username/Library/Application Support/MobileSync/Backup] at 2023-11-07 13:48:49.171048 +0100 CET by root@hostname> to /
ignoring error for /Users: UtimesNano: operation not permitted
Summary: Restored 3377 / 3378 files/dirs (583.808 MiB / 583.808 MiB) in 0:33
Fatal: There were 1 errors
```
The ouput stays the same if I don't use `--verbose` or `--verbose=2`.
```bash
$ echo $sudoPW | sudo -p "" -S -E bash -c 'restic -r $S3_Bucket_MyBase_URL/iPad_backup restore latest --target "/"'
repository 535a9ac9 opened (version 2, compression level auto)
[0:00] 0.00%  0 / 1 index files loaded
restoring <Snapshot 0ea37a4c of [/Users/username/Library/Application Support/MobileSync/Backup] at 2023-11-07 13:48:49.171048 +0100 CET by root@hostname> to /
ignoring error for /Users: UtimesNano: operation not permitted
Summary: Restored 3377 / 3378 files/dirs (583.808 MiB / 583.808 MiB) in 0:33
Fatal: There were 1 errors
```

Do you have any idea what may have caused this?
-----------------------------------------------
If I backup my iPad (iOS patched to latest, not jailbreaked) with the macOS Finder function to my MacBook that I run restic from. MacOS always uses the fixed path
```bash
/Users/$USER/Library/Application Support/MobileSync/Backup/
```
I think something in this path could interfere with the enabled SIP. Disabling SIP is not a solution for me, because I have to obey a rule to leave SIP enabled.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I'm new to restic, but until now I had more problems using restic than restic solved for me. But I would love to use restic instead of rsync for backups. 🥲

**Comment by Kay-LGLN** [comment]
I'm not completely certain but **UtimesNano** from the error message could come from a go function inside restic?

**Comment by Kay-LGLN** [comment]
I found [here](https://support.apple.com/en-us/102149), that macOSs SIP does not protect /Users, then maybe the path to the iPad backup isn't the issue here?

**Comment by rawtaz** [comment]
I'd say you are generally speaking not supposed to fiddle with `/Users` on macOS.

To not do that, it'd be better to restore the data to your `~` and move the relevant directories from it into their real place.

Or you can use the `<snapshot>:<subfolder>` syntax described [here](https://restic.readthedocs.io/en/latest/050_restore.html) to restore only the relevant part of the backed up path to where you want it, e.g. (not tested) `$ echo $sudoPW | sudo -p "" -S -E bash -c 'restic -r $S3_Bucket_MyBase_URL/iPad_backup restore --target ~ latest:/Users/$USER'`. Presuming the expansion works as expected, otherwise try with `"$HOME"` instead of `~`.

The latter should restore only the `/Library/Application Support/MobileSync/Backup` part of the backed up path `/Users/username/Library/Application Support/MobileSync/Backup` into/under your `~`. Try it and see it if works!

**Comment by Kay-LGLN** [comment]
Thank you very much for your reply, @rawtaz. I will try your suggestions. Where did you get from that SIP protects /Users, I can't find that [here](https://support.apple.com/en-us/102149).

**Comment by Kay-LGLN** [comment]
I had success recovering my iPad backup without restic showing errors. Because the Target is inside me home directory I executed the restore as my user, simply without sudo.
`restic -r $S3_Bucket_MyBase_URL/iPad_backup --verbose=2 restore latest --target "/"`
But I'm still confused /Users is not a directory that is listed to be protected by SIP and in a restore command `verbose` doesn't do anything. Who can shed some light on this?

**Comment by Kay-LGLN** [comment]
Atm I'm uncertain if the following works with enabled SIP. Does anybody know? I'll continue testing this next week. 🙂
```
mkdir $TMPDIR/iPad_backup
restic -r $S3_Bucket_MyBase_URL/iPad_backup restore latest --target "$TMPDIR/iPad_backup"
echo $sudoPW | sudo -p "" -S -E bash -c 'mv -f $TMPDIR/iPad_backup/*.* /'
```

**Comment by MichaelEischer** [comment]
I don't think there's anything that can be done on restic's side about this. Ideally, don't restore to `/` which is rather dangerous anyways.
