### ISSUE TITLE
Exits with spurious error codes with --one-file-system

### ISSUE THREAD

**Issue by mumbleskates** [restic/restic#4566]
Output of `restic version`
--------------------------
restic 0.16.1 compiled with go1.21.3 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
sftp

Problem description / Steps to reproduce
----------------------------------------
Backups with `--one-file-system` can produce error codes like
```
error: lstat /proc/3239146: no such file or directory
error: lstat /proc/3239151: no such file or directory
error: lstat /proc/3239152: no such file or directory
```
even when the contents of `/proc` should be entirely skipped because it is a mount point for a different filesystem. This leads to apparently spurious error codes returned at the end of the backup, with the message `Warning: at least one source file could not be read`

Expected behavior
-----------------
If these lstat calls that leave the file system can be avoided, they should be. At minimum they shouldn't be an error, because those files weren't going to be backed up to begin with

Actual behavior
---------------
restic can exit with an error code anyway

Do you have any idea what may have caused this?
-----------------------------------------------
This isn't a situation unique to my system or situation. I'm not sure what's going amiss with the filesystem detection.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
great backup system, efficient, reliable. love a good content-addressed data structure.

**Comment by MichaelEischer** [comment]
This looks like another instance of https://github.com/restic/restic/issues/3366 . For now, you'll have to use `backup --exclude /proc`.

**Comment by mumbleskates** [comment]
yep that looks like the same bug! thanks
