### ISSUE TITLE
Backend: use AttemptGet instead of Test + Get to reduce latency impact

### ISSUE THREAD

**Issue by mappu** [restic/restic#457]
Backend abstraction offers Test and Get endpoints. From logging it seems Test (or it's Stat?) is called then followed by Get on all Get requests.

For high-latency backends (example, 200ms or greater) it could prevent efficiently using the network connection. So I think it would be better to add a backend AttemptGet that combines the two requests.

**Comment by fd0** [comment]
I agree that it could be better, but where did you see `Test()` followed by `Stat()`?

**Comment by mappu** [comment]
>where did you see `Test()` followed by `Stat()`?

nowhere
I did found ( ( Test or Stat, don't know which ) followed by Get ).

**Comment by fd0** [comment]
Since there hasn't been any activity here recently and I cannot reproduce the issue I'm going to close it for now. Please feel free to add further comments. Thanks.
