### ISSUE TITLE
Restic don't follow 308 on swift backend

### ISSUE THREAD

**Issue by qeqar** [restic/restic#4587]
Output of `restic version`
--------------------------
restic 0.16.2 compiled with go1.21.3 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
swift

Problem description / Steps to reproduce
----------------------------------------
When trying to init a repo on an swift backedn i get a FATAL when there is a 308 redirect in place

`restic init -v 
Fatal: create key in repository at swift:BUCKETNAME:/ failed: client.PutObject: HTTP Error: 308: 308 Permanent Redirect`

The reason on the Openstack site is that by default the installation gives out http api links, and then do a 308 to https.

Expected behavior
-----------------
Restic to follow redirect 308/301

Is this behavior intended? is there a risk to follow redirect? Or would it be ok to just add a follow redirects?

**Comment by MichaelEischer** [comment]
> The reason on the Openstack site is that by default the installation gives out http api links, and then do a 308 to https.

This is a serious security vulnerability as any client sending an authenticated request to the HTTP API would leak the used credentials / auth tokens. The OpenStack / Swift APIs generally use bearer tokens which **NEVER** must be sent over plaintext connections.

In addition, it is seriously inefficient if each upload request has to be retried.
