### ISSUE TITLE
Feature request: Display Key ID used for snapshots || Forget\prune log

### ISSUE THREAD

**Issue by Milamber07** [restic/restic#4588]
Output of `restic version`
--------------------------

any

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Additional column displaying key ID used for backup.

```
$ restic snapshots

ID        Date                 Key ID     Host        Tags        Directory    
------------------------------------------------------------------------------
5b969a0e  2023-12-09 16:12:52  h74hfj3f   localhost               /Users/admin/desktop       
```

"Immutable" for N month forget\prune log. Displaying key id used for forget\prune, policy used, raw-date deleted after pruning, affected directories etc.

```
$ restic log --mode forget-prune

Date                 Key ID     Host        Policy                        Affected Dirs            Pruned
------------------------------------------------------------------------------------------------------------
2023-12-05 12:13:14  j8gfh4ys   localhost   forget --tag foo --tag bar    /Users/admin/desktop     212.3MB
                                            --keep-last 9 --prune         /Users/admin/documents
2023-12-08 12:13:14  j8gfh4ys   localhost   forget --tag foo --tag bar    /Users/admin/desktop     
                                            --keep-last 9
2023-12-09 15:51:38  mkd82nf8   server-1    prune                                                  89.1MB

```

What are you trying to do? What problem would this solve?
---------------------------------------------------------

With a current version of restic (0.16.2) it is possible to set any host and tag using any restic repo key.
If a machine gets compromised with a restic key, it potentially can mimic any host\tag for a backup in a compromised repo without knowing. Basically it will be able to read all data from snapshots, download it, replace with malware\corrupted or else and upload as a backup for all hosts in a repo. It will be highly unlikely to spot for multiple backup hosts.

Forget\prune log will contribute to spotting abnormal activities especially with a long list of snapshots for multiple hosts.
It would be nice to have a key log too - for creation, deletion, command used etc.
Perhaps an immutable unified log can have all of these and more without taking much space.

P.S. by "immutable" in this context I mean the following - inability to change log data via restic commands and any direct file modification will result in log file corruption.

**Comment by MichaelEischer** [comment]
> Additional column displaying key ID used for backup.

All keys in a repository have full access to every snapshot and thus are equivalent. Thus, there's no point in adding such a column.

> If a machine gets compromised with a restic key, it potentially can mimic any host\tag for a backup in a compromised repo without knowing.

The only way to prevent that is to use separate repositories.

> Forget\prune log will contribute to spotting abnormal activities especially with a long list of snapshots for multiple hosts.

Unless we add a server side component and hand out individual keys to each restic client, this feature request is impossible to implement. This fundamentally clashes with the design decision of restic to work with nearly arbitrary storage backends.

> P.S. by "immutable" in this context I mean the following - inability to change log data via restic commands and any direct file modification will result in log file corruption.

"inability to change log data via restic commands": an attacker is not restricted to restic commands, but can do whatever is allowed by the storage backend.


What might be implementable is to hand out signature keys to each client, which are used to sign snapshots created for a specific host (plus a highly complex process to manage and authorize/revoke keys). A forget / prune log is much harder, as with restic's design we cannot force malicious clients to write such a log. The only alternative is to write protect most files (Object Locks on S3) and then require clients to store signed snapshots deletion messages if a snapshot is deleted. Then it becomes possible to detect when a snapshot is deleted unexpectedly. This would require so many changes to restic, that there's no chance that it will be implemented in the next few years.
