### ISSUE TITLE
B2 error handling warning in docs

### ISSUE THREAD

**Issue by ismell** [restic/restic#4589]
The B2 [setup docs](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#backblaze-b2) have this scary warning:

> Due to issues with error handling in the current B2 library that restic uses, the recommended way to utilize Backblaze B2 is by using its S3-compatible API.
>
> Follow the documentation to [generate S3-compatible access keys](https://help.backblaze.com/hc/en-us/articles/360047425453-Getting-Started-with-the-S3-Compatible-API) and then setup restic as described at [Amazon S3](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#amazon-s3). This is expected to work better than using the Backblaze B2 backend directly.

Is there more context? A bug or link describing the failure? Or is this warning out dated now?

Thanks,
Raul

**Comment by rawtaz** [comment]
Here is one specific post that helps clarify: https://forum.restic.net/t/error-initializing-repo-in-backblaze/5369/6

Not sure what there is to clarify though? The docs say that it's a matter of the B2 library being suboptimal.

**Comment by ismell** [comment]
Thanks for the link. It looks like the original bug that prompted this was: https://github.com/kurin/blazer/pull/84

That has since been fixed. It also looks like restic is using the officially supported blazer repo now: https://github.com/restic/restic/blob/master/go.mod#L8

So maybe it would be worthwhile to update the documentation to remove the: **Due to issues with error handling in the current B2 library that restic uses**
from the documentation?

**Comment by MichaelEischer** [comment]
The warning in the docs was prompted by https://github.com/restic/restic/issues/3859 . We've added a workaround for that particular issue, but others like https://github.com/restic/restic/issues/3796 or https://github.com/restic/restic/issues/2172 are still unresolved. These cannot be fixed without significant changes to the B2 library, which likely won't happen (at least there hasn't been any significant activity in recent years).
