### ISSUE TITLE
After restoring restic reports that all files at least changed

### ISSUE THREAD

**Issue by alet** [restic/restic#4592]
Output of `restic version`
--------------------------
restic 0.16.2 compiled with go1.21.3 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
ext4 filesystem

Problem description / Steps to reproduce
----------------------------------------
After restoring restic reports that all files at least changed
1. Make backup of home
2. Format disk/Install new OS
3. Restore home
4. Do some work
5. Backup to existing repo - during this step restic reports '0 unmodified' files and folders

Expected behavior
-----------------
Backup only new/changed files

Actual behavior
---------------
Restic reports '0 unmodified' files and folders

Do you have any idea what may have caused this?
-----------------------------------------------
Prior versions worked as expected

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes, great tool ))

**Comment by moritzdietz** [comment]
Hi! This might be better for the forum over at https://forum.restic.net than a GH issue, but regardless I'll try to help a bit 🙂
Have you read https://restic.readthedocs.io/en/stable/040_backup.html#file-change-detection and checked whether the information there is sufficient to answer your question?

**Comment by alet** [comment]
Hi! Thanks! It solves problem. I read documentation but maybe too long time ago and can't remember such option (--ignore-inode). Maybe this section wasn't present or maybe I forgot this page. Thanks again!
