### ISSUE TITLE
ls snapshot shows all files recursively

### ISSUE THREAD

**Issue by fbuetler** [restic/restic#4594]
Output of `restic version`
--------------------------
restic 0.16.2 compiled with go1.21.3 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
ext4 filesystem

Problem description / Steps to reproduce
----------------------------------------
Listing the files in a snapshot shows all files recursively. The presence of the `--recursive` flag of `ls` hints, that this should only happen if configured (same behavior without the `--path /` argument).

```bash
restic ls <snapshot id> --path /
```

Expected behavior
-----------------
The `ls` command for without `--recursive` should only list all files and directories within the given directory.

Actual behavior
---------------
The `ls` command lists all files recursively within a snapshot.

**Comment by MichaelEischer** [comment]
If `restic ls <snapshot id>` is called without a path, then it prints all files within a snapshot. To only list a specific folder, you have to specify a path, e.g. using `restic ls <snapshot id> /` (without `--path` ! that option is only relevant to filter snapshots).
