### ISSUE TITLE
falsely classifying files as new

### ISSUE THREAD

**Issue by kaktus42** [restic/restic#4597]
Output of `restic version`
--------------------------
restic 0.16.2 compiled with go1.21.3 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
sftp

Problem description / Steps to reproduce
----------------------------------------
I am backing up a mail directory with Maildir format.
Most of the files are not changing from backup to backup.

However, when running the second backup, all files are registered as new. Nothing is unmodified.
The actual backup size, however is de-duplicating correctly, as the additional storage is very small.

I am running the backup as a CronJob on Kubernetes, so a new pod
is created with every daily backup.
I already checked the inodes, but they are the same between different runs.

```
$ restic -v --no-cache -r sftp:backup_dest:vmail backup /vmail
open repository
lock repository
no parent snapshot found, will read all files
load index files
start scan on [/vmail]
start backup on [/vmail]
scan finished in 4.991s: 93189 files, 7.346 GiB

Files:       93189 new,     0 changed,     0 unmodified
Dirs:         1707 new,     0 changed,     0 unmodified
Data Blobs:     15 new
Tree Blobs:      8 new
Added to the repository: 5.995 MiB (829.066 KiB stored)

processed 93189 files, 7.346 GiB in 1:35
snapshot 6b1a2da3 saved
```

Password is stored in env.

Expected behavior
-----------------
List most of the files as unmodified.

Actual behavior
---------------
Lists all of the files as new.

Do you have any idea what may have caused this?
-----------------------------------------------
Nope. I wonder how I can check all parameters that decide if a file is new.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I love how easy it was go get started. Also that it was available in the alpine repository.

**Comment by meise** [comment]
K8s environment are known for unstable hostnames. [Parent snapshot](https://restic.readthedocs.io/en/stable/040_backup.html#file-change-detection) detection is based on path and hostname. So to get parent detection to work, you have to define a stable hostname via `-H` (`--hostname`) backup flag or set snapshot ID manually for `--parent` flag.

**Comment by kaktus42** [comment]
Perfect. That was it. Thanks! And happy holidays :)
