### ISSUE TITLE
No `--stdin-from-command` option for backup command

### ISSUE THREAD

**Issue by q-b** [restic/restic#4613]
Output of `restic version`
--------------------------
``
restic 0.16.2 compiled with go1.21.3 on linux/amd64
``

What backend/service did you use to store the repository?
---------------------------------------------------------

S3

Problem description / Steps to reproduce
----------------------------------------

It seems that #4410 got merged just before 0.16.2 release. However the `--stdin-from-command` does not seems to be working/available (while recommended in the latest documentation).

```
$ restic backup --help

The "backup" command creates a new snapshot and saves the files and directories
...
      --read-concurrency n                     read n files concurrently (default: $RESTIC_READ_CONCURRENCY or 2)
      --stdin                                  read backup from stdin
      --stdin-filename filename                filename to use when reading from stdin (default "stdin")
      --tag tags                               add tags for the new snapshot in the format `tag[,tag,...]` (can be specified multiple times) (default [])
...

$ restic backup ... --stdin-from-command mysqldump ...
unknown flag: --stdin-from-command
```

Expected behavior
-----------------

Working as expected so we could replace `mysqldump ... | restic backup --stding ...` with the improved version.

Actual behavior
---------------

```
$ restic backup ... --stdin-from-command mysqldump ...
unknown flag: --stdin-from-command
```

Do you have any idea what may have caused this?
-----------------------------------------------

None

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yup, looks great, easy to use, fast, thx :heart:

**Comment by rawtaz** [comment]
The 0.16.2 release was a patch release for version 0.16, so it didn't contain this new feature.

The next 0.17 release will contain the feature, as it is currently on the master branch.

If you grab the [latest build of restic from beta.restic.net](https://beta.restic.net/latest/) you will find the option in there :)

**Comment by meldarionqeusse** [comment]
I am running 0.16.5 and apparently it does not have the `--stdin-from-command` but the documentation make reference to this feature. It is a bit confusing also I could not find version 0.17 in the beta link that you mentioned above. 
![image](https://github.com/restic/restic/assets/21668964/34535c05-45ee-4f29-a6cc-416258909c83)

**Comment by rawtaz** [comment]
@meldarionqeusse The documentation you are reading is for the _latest_ development version of restic, which does have this feature. This latest development version is what will become restic version 0.17.0 when it's released soon.

Restic 0.16.5 indeed does not have the feature, and this matches the documentation for the _stable_ version of restic which is 0.16.5. So there's really nothing wrong with the documentation, you were just looking at the docs for a non-released version.

You can get the latest development version of restic from https://beta.restic.net/latest/ , this one does contain the feature you are looking for.
