### ISSUE TITLE
'backup --files-from' results in 'ls latest' producing header with all filenames

### ISSUE THREAD

**Issue by ogregpt** [restic/restic#4628]
Output of `restic version`
--------------------------
restic 0.16.2-dev (compiled manually) compiled with go1.20.6 on linux/amd64
it's restic_v0.16.2-128-g76f507c77_linux_amd64
same problem with restic 0.16.2

What backend/service did you use to store the repository?
---------------------------------------------------------
local filesystem (SFTP has same problem)

Problem description / Steps to reproduce
----------------------------------------
When using 'backup --files-from', the 'ls latest' of that snapshot consists of an ugly, unformatted header and the actual file list.
The header is 'snapshot xyz of [ (ALL files listed here) ]' which is true, but the listing is not easy to read.
If using 'backup path', the header contains [ path ].

To reproduce (any find command will do):

**host: find /etc/network | ~/bin/beta-restic -r ~/restic-repo/ --files-from -**
repository 94e619c2 opened (version 2, compression level auto)
no parent snapshot found, will read all files
[0:00] 100.00%  7 / 7 index files loaded
error: open /etc/network/interfaces: permission denied

Files:           7 new,     0 changed,     0 unmodified
Dirs:            7 new,     0 changed,     0 unmodified
Added to the repository: 0 B   (0 B   stored)

processed 7 files, 16.844 KiB in 0:00
snapshot 46e891a9 saved
Warning: at least one source file could not be read

**host: ~/bin/beta-restic -r ~/restic-repo/ ls latest**
repository 94e619c2 opened (version 2, compression level auto)
[0:00] 100.00%  7 / 7 index files loaded
snapshot 46e891a9 of [/etc/network /etc/network/interfaces.d /etc/network/if-pre-up.d /etc/network/if-pre-up.d/wireless-tools /etc/network/if-pre-up.d/wpasupplicant /etc/network/interfaces /
etc/network/if-post-down.d /etc/network/if-post-down.d/wireless-tools /etc/network/if-post-down.d/wpasupplicant /etc/network/if-down.d /etc/network/if-down.d/resolved /etc/network/if-down.d/
resolvconf /etc/network/if-down.d/wpasupplicant /etc/network/if-up.d /etc/network/if-up.d/resolved /etc/network/if-up.d/wpasupplicant /etc/network/if-up.d/000resolvconf /etc/network/if-up.d/
mountnfs] at 2024-01-07 12:08:08.573929019 +0100 CET by restic-test@host filtered by []:
/etc
/etc/network
/etc/network/if-down.d
/etc/network/if-down.d/resolvconf
/etc/network/if-down.d/resolved
/etc/network/if-down.d/wpasupplicant
/etc/network/if-post-down.d
/etc/network/if-post-down.d/wireless-tools
/etc/network/if-post-down.d/wpasupplicant
/etc/network/if-pre-up.d
/etc/network/if-pre-up.d/wireless-tools
/etc/network/if-pre-up.d/wpasupplicant
/etc/network/if-up.d
/etc/network/if-up.d/000resolvconf
/etc/network/if-up.d/mountnfs
/etc/network/if-up.d/resolved
/etc/network/if-up.d/wpasupplicant
/etc/network/interfaces.d

Expected behavior
-----------------
Something sensible, maybe [-] to indicate the header might be too complex to display neatly because stdin was used.

Actual behavior
---------------
The header of the ls listing contains an unformatted list of all the files in the backup.

Do you have any idea what may have caused this?
-----------------------------------------------
No.

No.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I'm still considering restic for future backups, so yes.

**Why am I doing it this way?**
The problem is reproduced on Linux, but it was identified on Windows, where my 'backup tree' contains a number of symlinks.
These are not followed by restic, so I 'find' them in the backup tree and pass the list to restic.

**Comment by ogregpt** [comment]
Just updated to 0.16.3: same problem.

I just started testing my restore-script, unfortunately restic also there produces a one-line header with all 5000+ filepaths in it - quite disturbing though it's possible to filter the messages in a pipe.
Is this a bug, or does it work as designed?

Regards

**Comment by damoclark** [comment]
The reason this happens is that the path(s) specified when taking a backup (even from `--files-from` option) 'implicitly' identify the backup snapshot (in combination with the host and the time).  If you run `restic snapshots` for instance, you will see that the list will be shown in the output against that particular snapshot ID as well.  

This and many other issues reveal an underlying design flaw in how restic operates.  There is a proposed solution (#4026) that I submitted some time ago, but based on the current [developer priorities](https://forum.restic.net/t/roadmap-for-restic-0-17-to-0-19/7197) and [project roadmap](https://github.com/orgs/restic/projects/2), it not under consideration at this time.

**Comment by ogregpt** [comment]
Thanks - I agree with the proposals described in your issue, they could bring som clarity and flexibility to my backups using paths;
The backup mentioned in this issue uses a file list produced by the find+grep programs (following symbolic links and using exclude patterns) - it cannot be easily transformed (by me) into paths and excludes in restic, so I'll live with each snapshot being isolated - and discard the list with 5000+ paths...
Maybe addition of the .gitignore feature will help me, I'll certainly try it out.

**Comment by ogregpt** [comment]
Maintaining snapshots made using a file list:
Having used restic a few months I'm starting to test the **forget** policies - I'm out of luck because the snapshots are considered different: the filelists in the snapshots are always a little bit different because they're made dynamically outside of restic.

**Comment by MichaelEischer** [comment]
@ogregpt The `--group-by` option is probably useful in your case, see https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy .

**Comment by damoclark** [comment]
> @ogregpt The `--group-by` option is probably useful in your case, see https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy .

I'm not so sure Michael.  

> the filelists in the snapshots are always a little bit different because they're made dynamically outside of restic.

Because of this, I think the path component of @ogregpt snapshots vary, so I don't think `--group-by` can't help here.  

Entertaining #4026 would resolve the two issues raised by @ogregpt, and many other issues as mentioned in issue 4026.  

While it would be a considerable undertaking, my view is that it would be worth it in the long run, especially because it would reduce the number of support requests that appear related to the flaws of the current model of using the path to identify a backup-set.  But, I do acknowledge that because I am not a core developer, I don't have the full picture.

**Comment by ogregpt** [comment]
@MichaelEischer @damoclark :
Thank you both - to my relief Michael's suggestion **does** indeed work: the --group-by option overrides the path component...

**Comment by MichaelEischer** [comment]
> Entertaining #4026 would resolve the two issues raised by @ogregpt, and many other issues as mentioned in issue 4026.

I don't have time to look into that issue before restic 0.17.0 is done.

**Comment by damoclark** [comment]
> I don't have time to look into that issue before restic 0.17.0 is done.

Perfectly understandable Michael.  I checked out the roadmap and it appears a mammoth undertaking, with some exciting new features coming.  

> Thank you both - to my relief Michael's suggestion does indeed work: the --group-by option overrides the path component...

Seems my skepticism was wrong - I'm glad that this did work for you.  :) 

I think I was misguided by my own context.  I have configured restic to backup using separate snapshots for each mounted filesystem.  So most of my hosts have more than one path defined.  I am guessing that your use case at the moment has just a single 'dynamic' backup for your host, so grouping by host alone allows you to apply your forget policy against all your snapshots.

If in the future, you need to add additional backups to the same host, you should be able to make that work by using tags to separate them from your dynamic backup, and can `--group-by host,tag`
