### ISSUE TITLE
Out of memory: pruning after repo v2 upgrade and forgetting snapshots

### ISSUE THREAD

**Issue by dsteinfeld** [restic/restic#4632]
Output of `restic version`
--------------------------

What backend/service did you use to store the repository?
---------------------------------------------------------

Problem description / Steps to reproduce
----------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Do you have any idea what may have caused this?
-----------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
duplicate of #4633
