### ISSUE TITLE
Out of memory when pruning after forgetting snapshots and upgrading repo to v2

### ISSUE THREAD

**Issue by dsteinfeld** [restic/restic#4633]
Output of `restic version`
--------------------------
restic 0.16.2 compiled with go1.21.3 on windows/386

What backend/service did you use to store the repository?
---------------------------------------------------------
Docker running on Synology NAS

Problem description / Steps to reproduce
----------------------------------------
Prune reports Out of Memory:
C:\Users\DougS.dougdesk>set RESTIC_PASSWORD=<mypwd> 
C:\Users\DougS.dougdesk>restic -r rest:http://synology:8002 prune --repack-uncompressed --compression max
repository 48e21007 opened (version 2, compression level max)
loading indexes...
[0:05] 100.00%  1737 / 1737 index files loaded
loading all snapshots...
finding data that is still in use for 25 snapshots
runtime: out of memory: cannot allocate 159383552-byte block (                                                                                                                1442217984 in use)25 snapshots
fatal error: out of memory

I did the following:
1) On the NAS I shut down the docker backend and copied the repository.  I brought up a container pointing to the new repository.  The repo is approximately 3.6TB and 700,000 files

2) Ran check --read-data on the copied repo:
C:\Users\DougS.dougdesk>restic -r rest:http://synology:8002 check --read-data
using temporary cache in C:\Users\DOUGS~1.DOU\AppData\Local\Temp\restic-check-cache-2715778951
repository 48e21007 opened (version 1)
created new cache in C:\Users\DOUGS~1.DOU\AppData\Local\Temp\restic-check-cache-2715778951
create exclusive lock for repository
load indexes
[0:18] 100.00%  1737 / 1737 index files loaded
check all packs
check snapshots, trees and blobs
[1:29] 100.00%  1401 / 1401 snapshots
read all data
[16:54:37] 100.00%  783630 / 783630 packs
no errors were found

3) Deleted snapshots with a policy:
C:\Users\DougS.dougdesk>restic -r rest:http://synology:8002 forget --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75
repository 48e21007 opened (version 1)
Applying Policy: keep 7 daily, 5 weekly, 12 monthly, 75 yearly snapshots
keep 25 snapshots:
ID        Time                 Host        Tags        Reasons           Paths
------------------------------------------------------------------------------
b9b54c3c  2019-12-10 22:43:39  dougdesk                yearly snapshot   p:\
79e52ece  2019-12-31 02:00:00  dougdesk                yearly snapshot   p:\
b2e5c6f8  2020-12-31 02:00:14  dougdesk                yearly snapshot   p:\
7e9f41d1  2021-12-31 02:00:13  dougdesk                yearly snapshot   p:\
12bd144a  2022-12-31 02:00:13  dougdesk                yearly snapshot   p:\
dbb1fde8  2023-02-28 02:00:16  dougdesk                monthly snapshot  p:\
c291bd91  2023-03-31 02:00:13  dougdesk                monthly snapshot  p:\
0ac13eb5  2023-04-30 02:00:13  dougdesk                monthly snapshot  p:\
9069e93a  2023-05-31 02:00:13  dougdesk                monthly snapshot  p:\
ce38d46a  2023-06-30 02:00:13  dougdesk                monthly snapshot  p:\
f8a4a8d6  2023-07-31 02:00:13  dougdesk                monthly snapshot  p:\
cebe88b1  2023-08-31 02:00:14  dougdesk                monthly snapshot  p:\
e2f40712  2023-09-30 02:00:13  dougdesk                monthly snapshot  p:\
0be63a3e  2023-10-31 02:00:13  dougdesk                monthly snapshot  p:\
43c06aef  2023-11-30 02:00:13  dougdesk                monthly snapshot  p:\
d18dde89  2023-12-10 02:00:15  dougdesk                weekly snapshot   p:\
e97b72ba  2023-12-17 02:00:14  dougdesk                weekly snapshot   p:\
d386e0c9  2023-12-24 02:00:13  dougdesk                weekly snapshot   p:\
3c88c2ca  2023-12-27 02:00:13  dougdesk                daily snapshot    p:\
fe5e0f3f  2023-12-28 02:00:13  dougdesk                daily snapshot    p:\
ddd43ff4  2023-12-29 02:00:13  dougdesk                daily snapshot    p:\
d6e4e276  2023-12-30 02:00:13  dougdesk                daily snapshot    p:\
35743bf0  2023-12-31 02:00:13  dougdesk                daily snapshot    p:\
                                                       weekly snapshot
                                                       monthly snapshot
                                                       yearly snapshot
4e7f6861  2024-01-01 02:00:13  dougdesk                daily snapshot    p:\
944f574a  2024-01-02 02:00:13  dougdesk                daily snapshot    p:\
                                                       weekly snapshot
                                                       monthly snapshot
                                                       yearly snapshot
------------------------------------------------------------------------------
25 snapshots

remove 1376 snapshots:
<removed unless you need these>
[0:01] 100.00%  1376 / 1376 files deleted
 
4) Upgraded the repo to v2
C:\Users\DougS.dougdesk>restic -r rest:http://synology:8002 migrate upgrade_repo_v2
repository 48e21007 opened (version 1)
checking repository integrity...
using temporary cache in C:\Users\DOUGS~1.DOU\AppData\Local\Temp\restic-check-cache-3784478896
repository 48e21007 opened (version 1)
created new cache in C:\Users\DOUGS~1.DOU\AppData\Local\Temp\restic-check-cache-3784478896
load indexes
[0:18] 100.00%  1737 / 1737 index files loaded
check all packs
check snapshots, trees and blobs
[0:30] 100.00%  25 / 25 snapshots
no errors were found
applying migration upgrade_repo_v2...
migration upgrade_repo_v2: success

5) Attempted prune/repack/compress
C:\Users\DougS.dougdesk>restic -r rest:http://synology:8002 prune --repack-uncompressed --compression max
repository 48e21007 opened (version 2, compression level max)
loading indexes...
[0:05] 100.00%  1737 / 1737 index files loaded
loading all snapshots...
finding data that is still in use for 25 snapshots
runtime: out of memory: cannot allocate 159383552-byte block (                                                                                                                1442217984 in use)25 snapshots
fatal error: out of memory

The stack trace is available but it's 2000 lines so it's attached rather than including inline.

Expected behavior
-----------------

Complete delete/compress operation.

Actual behavior
---------------

Crashed almost immediately after loading snapshots/finding data.  Also attempted a run with:

`set GOGC=20`
 
based on a suggestion in another OOM thread but no different behavior was observed.

Do you have any idea what may have caused this?
-----------------------------------------------
No, as this is a 32GB machine

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is a marvel.  It keeps on chugging, producing backups that are error free over the long haul.

[prune out of memory.txt](https://github.com/restic/restic/files/13910460/prune.out.of.memory.txt)

**Comment by MichaelEischer** [comment]
> No, as this is a 32GB machine

You're using a 32bit build of restic and thus it can only use 2GB of RAM. Please use a 64bit build instead (windows_amd64).

**Comment by dsteinfeld** [comment]
Thank you!  I should have caught that as I was running 0.9.6 64 bit.  Perhaps a warning message if 32 bit restic is run on a 64 bit OS to protect the overly confident from themselves?

Thanks again!

**Comment by MichaelEischer** [comment]
> Perhaps a warning message if 32 bit restic is run on a 64 bit OS to protect the overly confident from themselves?

While that could be useful, I don't see how we could implement that in a nice way. Restic shouldn't annoy users as long they don't run out of memory, and I'm not aware of a way to intercept the out of memory error. And anything more complex is probably not worth the trouble. So I'll close the issue for now, but feel free to reopen it if there's an easy way to implement such a warning.
