### ISSUE TITLE
IPv6 Mirror

### ISSUE THREAD

**Issue by luggesexe** [restic/restic#4634]
Hello restic-Team,

I am currently on a Ubuntu 22.04.3 LTS Server with only IPv6. The installation via apt-get works well, while using the netcologne-Ubuntu-Mirror. I tried to self-update as the apt command seems to install the 0.12.1-Version.

Fatal: unable to update restic: Get "https://api.github.com/repos/restic/restic/releases/latest": dial tcp 140.82.121.6:443: connect: network is unreachable

[As this is a well discussed issue for all of Github](https://github.com/orgs/community/discussions/10539) I would think of different approaches for this issue regarding restic and would love to hear the thoughts.

* Change the code to fallback on a IPv6-only-Service (f.e. [here](https://github.via-ipv6.com/)). Although this could be a security issue.
* Add a CLI-Tag to set a custom URL (like restic self-update --custom-mirror XXXXX), so that people can take the risks themselves.
* Build up a Mirror-Network such it is done with Ubuntu. The whole  restic version is about 20mb in size as I saw it. This could easily be done by everyone willing (including me) using a small webserver with Cron support.  As I checked restic.net is fully capable of IPv6 as it could serve as a master for other mirrors.

Is this something that could be considered?
Did restic help you today? Did it make you happy in any way?
I am very happily using restic since quite some time and the external backups already saved me from some bad things happening. Keep up the good work!

**Comment by MichaelEischer** [comment]
While I agree that it's rather unfortunate the Github still doesn't support IPv6, I don't think any of the suggested options is a viable alternative for us:
- Falling back by default to a (random) third party service doesn't sound like a good idea to me. As the binaries are signed using GPG, it wouldn't be possible to tamper with the binaries themselves, but the check for the latest version can be hijacked.
- Using a custom option is similar to the previous option, although it's a bit better. To be generally usable we'd have to document it properly, such that we once again point towards a third party service (or end up with a rather unhelpful documentation if we don't).
- Using a custom mirror network just dramatically increases the work for the project and thus is no option either.

I still have the hope that Github will add proper IPv6 support, so I'm not to eager to introduce workarounds.

The `self-update` command is relatively straightforward, it just checks the latest release, then uses the GPG signature to verify the SHA256SUMS file and uses that to verify the downloaded binary.

**Comment by luggesexe** [comment]
Hello Michael,
for the moment I just used a workaround pulling the restic-Data on to a IPv4+IPv6 able server and building from source. I hope, that Github enables IPv6 soon. Until then 🥴....
