### ISSUE TITLE
Restic Restore to Backblaze B2 requires a read/write application key

### ISSUE THREAD

**Issue by strich** [restic/restic#4653]
Output of `restic version`
--------------------------
restic 0.16.2 compiled with go1.21.3 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
Backblaze B2

Problem description / Steps to reproduce
----------------------------------------
Running command `restic_0.16.2_windows_amd64.exe restore latest --cache-dir .cache --target develop-PS5-loose -o b2.connections=8 --verbose`.
I get 401 errors when trying to use an application key that is read-only. If the key is read/write then it works.

Expected behavior
-----------------
I expect to be able to distribute the restic restore command to external trusted parties but not open my bucket to write operations.

**Comment by CommanderRoot** [comment]
I have not tried it but my guess would be that it could work if you use the `--no-lock` option as it's probably failing when it tries to create one

**Comment by MichaelEischer** [comment]
Closing, as `restore --no-lock` should be enough to solve the issue.
