### ISSUE TITLE
Document that `az login` identity also works for Azure

### ISSUE THREAD

**Issue by letmaik** [restic/restic#4658]
https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#microsoft-azure-blob-storage

For example, the following works if the user has the `Storage Blob Data Contributor` role on the storage account:

```sh
export AZURE_RESOURCE_GROUP="some-group"
export AZURE_ACCOUNT_NAME="someaccount"
az login
restic -r azure:backup:/ init
```

This can be run on any machine, not just Azure VMs.

**Comment by MichaelEischer** [comment]
Would you be interested in opening a PR to adapt the documentation?
