### ISSUE TITLE
s3 backend is broken

### ISSUE THREAD

**Issue by aplsms** [restic/restic#4660]
Hello,

I have a problem initializing the backup on S3 bucket. S3 bucket is present and accessible. Also I can't access old S3 backups with the same error

```
$ restic -r s3:s3.amazonaws.com/my-restic-backup-bucket/mbp.restic --verbose=5 init
Fatal: create a repository at s3:s3.amazonaws.com/my-restic-backup-bucket/mbp.restic failed: client.BucketExists: 301 Moved Permanently

$ restic -r s3:s3.amazonaws.com/my-restic-backup-bucket/restic --verbose=5 list snapshots
Fatal: unable to open config file: Stat: 301 Moved Permanently
Is there a repository at the following location?
s3:s3.amazonaws.com/my-restic-backup-bucket/restic
```

I've tried to change the URL by Amazon recommendation:

```
$ restic -r s3:my-restic-backup-bucket.s3.amazonaws.com/restic --verbose=5 list snapshots
Fatal: unable to open repository at s3:my-restic-backup-bucket.s3.amazonaws.com/restic: minio.New: Amazon S3 endpoint should be 's3.amazonaws.com'.
```

I can access the bucket using AWS CLI

```
aws s3 ls s3://my-restic-backup-bucket/
                           PRE ios/
                           PRE restic/
2022-06-20 15:13:51 1100459290 Centos-7.utm.zip
2022-06-20 15:16:15 1078773974 Centos-8.utm.zip
```

Restic Version:
```
$ restic version
restic 0.16.3 compiled with go1.21.6 on darwin/arm64
```

Please help me resolve this issue, our production is affected.

**Comment by MichaelEischer** [comment]
Restic currently requires that AWS S3 URLs are specified as path-style URLs; they're internally translated into virtual hosted style.

My guess is that you did not specify the region in which the bucket is hosted (https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#amazon-s3)

> If needed, you can manually specify the region to use by either setting the environment variable AWS_DEFAULT_REGION or calling restic with an option parameter like -o s3.region="us-east-1".

See also https://github.com/restic/restic/issues/3909

**Comment by aplsms** [comment]
I've specified the region, result the same:

```
$ restic -r s3:s3.amazonaws.com/my-restic-backup-bucket/restic --verbose=5 list snapshots
Fatal: unable to open config file: Stat: 301 Moved Permanently
Is there a repository at the following location?
s3:s3.amazonaws.com/my-restic-backup-bucket/restic

$ restic -r s3:s3.us-east-1.amazonaws.com/my-restic-backup-bucket/restic --verbose=5 list snapshots
Fatal: unable to open config file: Stat: 301 Moved Permanently
Is there a repository at the following location?
s3:s3.us-east-1.amazonaws.com/my-restic-backup-bucket/restic
```

**Comment by MichaelEischer** [comment]
You can create a debug log using the environment variable `DEBUG_LOG=restic.log`. That might show where that redirection is pointing to.

As your backup apparently worked previously, it might also be interesting to take a look at what has changed since then.

**Comment by aplsms** [comment]
interesting...
in case you have a bucket name like `this-string-without-dots`  everything works fine.
in case you have a bucket name like `backup-ca.companyname.com` I have a redirect.

```


2024/01/26 17:09:01 layout/layout.go:132	layout.DetectLayout	1	layout detection failed
2024/01/26 17:09:01 layout/layout.go:156	layout.ParseLayout	1	error: auto-detecting the filesystem layout failed, use default layout default
2024/01/26 17:09:01 layout/layout.go:139	layout.ParseLayout	1	parse layout string "default" for backend at mbp.restic
2024/01/26 17:09:01 debug/round_tripper.go:93	debug.loggingRoundTripper.RoundTrip	1	------------  HTTP REQUEST -----------
HEAD /ap-oregon.companyname.com/ HTTP/1.1
Host: s3.dualstack.us-east-1.amazonaws.com
User-Agent: MinIO (darwin; arm64) minio-go/v7.0.66
Authorization: **redacted**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20240127T010901Z
X-Amz-Security-Token: I1...tDg==


2024/01/26 17:09:01 debug/round_tripper.go:110	debug.loggingRoundTripper.RoundTrip	1	------------  HTTP RESPONSE ----------
HTTP/1.1 301 Moved Permanently
Connection: close
Content-Type: application/xml
Date: Sat, 27 Jan 2024 01:09:01 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-west-2
X-Amz-Id-2: 1W...Q=
X-Amz-Request-Id: 1S554V6ZHWKQHF75


2024/01/26 17:09:01 s3/s3.go:166	s3.isAccessDenied	1	isAccessDenied(minio.ErrorResponse, minio.ErrorResponse{XMLName:xml.Name{Space:"", Local:""}, Code:"301 Moved Permanently", Message:"301 Moved Permanently", BucketName:"ap-oregon.companyname.com", Key:"", Resource:"", RequestID:"1S554V6ZHWKQHF75", HostID:"1W.../Q=", Region:"us-west-2", Server:"", StatusCode:301})
2024/01/26 17:09:01 s3/s3.go:149	s3.Create	1	BucketExists(ap-oregon.companyname.com) returned err 301 Moved Permanently
2024/01/26 17:09:01 restic/cleanup.go:87	main.Exit	1	exiting with status code 1

```
I see no target for redirect.

**Comment by MichaelEischer** [comment]
The redirection target is apparently included in the body of the reply from S3...

Bucket names with dots in their name are problematic when mapped to DNS domains. Especially in combination with TLS, a cert for *.s3.amazonaws.com is not valid for sub.bucket.s3.amazonaws.com but only for bucket.s3.amazonaws.com .

This is a limitation of S3. From https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html

> If you include dots in a bucket's name, you can't use virtual-host-style addressing over HTTPS, unless you perform your own certificate validation. This is because the security certificates used for virtual hosting of buckets don't work for buckets with dots in their names.

The S3 library performs an automatic fallback to path style requests in that case. But I can't tell why that causes redirects in your case.

**Comment by aplsms** [comment]
ok, so I was able to fix the problem.
1. `AWS_DEFAULT_REGION` should point to the region with the bucket, otherwise it will point to `AWS_DEFAULT_REGION` and ignoring the endpoint.
2. Endpoint should point to `s3.dualstack.us-west-1.amazonaws.com` 

so command line will looks like: 

```
$ export AWS_DEFAULT_REGION=us-west-1
$ aws-vault exec prod -- restic -r s3://s3.dualstack.us-west-1.amazonaws.com/backupbucket.companyname.com/mbp.restic init

debug log file restic.log
debug enabled
created restic repository 726c831391 at s3://s3.dualstack.us-west-1.amazonaws.com//backupbucket.companyname.com/mbp.restic

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
```

2 years nobody going to fix the issue...
