### ISSUE TITLE
`key` help does not document subcommands

### ISSUE THREAD

**Issue by ProactiveServices** [restic/restic#4676]
Output of `restic version`
--------------------------
restic 0.16.3 compiled with go1.21.6 on linux/amd64

Problem description
----------------------------------------

`restic help key` shows the list/add/remove/passwd subcommands but does not show help for what they do. Specifically, the difference between "add" and "passwd" is not explained.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Today and every day since I first found it.

**Comment by MichaelEischer** [comment]
We should split the `key` command into multiple subcommands, similiar to the `repair` command.

"add" create a new key. "passwd" replaces the current key with a new one using the new password.
