### ISSUE TITLE
REST backend: Add basic and digest auth

### ISSUE THREAD

**Issue by fd0** [restic/restic#469]
The REST backend at the moment has no support for Authentication, add options to set username and password, and do basic and digest auth.

**Comment by fawick** [comment]
Note for later: https://github.com/abbot/go-http-auth seems to be valid choice instead of implementing everything ourselves.

**Comment by fd0** [comment]
FYI: This seems to be the server part, this issue is about the backent (=client).

**Comment by cfcs** [comment]
What does digest auth provide over basic auth?

**Comment by fd0** [comment]
It does not send the password to the server. In case of a compromised server the attackers are unable to learn the client's password.

**Comment by cfcs** [comment]
But digest is rather trivially bruteforced (salted md5), so TLS-SRP is a better alternative.
I'd suggest sticking with Basic for now (since this will usually run on the loopback interface), and implementing TLS-SRP (and HTTPS) if you are serious about the password security requirement - ?

**Comment by fd0** [comment]
Basic auth was implemented and I don't see the point in adding digest auth, closing.
