### ISSUE TITLE
restic prune ends with Fatal: index is not complete

### ISSUE THREAD

**Issue by alci63** [restic/restic#4690]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
rclone

Problem description / Steps to reproduce
----------------------------------------
1m41s ➜ restic prune
enter password for repository: 
repository f7f0ba29 opened (version 2, compression level auto)
loading indexes...
[0:02] 100.00%  42 / 42 index files loaded
loading all snapshots...
finding data that is still in use for 37 snapshots
[0:26] 100.00%  37 / 37 snapshots
searching used packs...
{<data/46f16cfd> <data/64e597b3> <data/dcfe4bbf> <data/8e9cef5e> <data/314589c3> <data/2d9e4048> <data/c3319088> <data/07cb59af> <data/8ef04398> <data/6fb50d53> (4034 more)} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
Fatal: index is not complete

**Comment by MichaelEischer** [comment]
Did you notice any errors reported in prior restic runs or did something unexpected happen? Maybe an interrupted network connection or did the host go into standby while restic was running?
Is this the first failing `prune` run? Do you have logs of the `backup` and `prune` run before the failing one?
Did restic report any errors there?

How often do you run `backup`, `check` and/or `prune`?

Is the repository used by multiple hosts or just a single host? Do you use the `unlock` command or is it called automatically from your backup scripts?

Please run `restic check` to analyze the damage to the repository. If downloading all data from the repository isn't a problem, then please run `restic check --read-data` instead to perform a full integrity check.

It would be helpful to know which snapshots are missing blobs: Please run `restic find --blob 46f16cfd 64e597b3 dcfe4bbf 8e9cef5e 314589c3 2d9e4048 c3319088 07cb59af 8ef04398 6fb50d53` (those are the ids of the blobs reported as missing) to find the affected snapshots (well, at least some of them).

**Comment by alci63** [comment]
Hi,

I started from scratch and did this:

1) init a local reposirtory (on a ext4 removable media)

restic -r /media/myuser/mydisk/backup init

2) backup to local repository 

restic -r /media/user/disk/backup backup /home/user/

3) init a distant repository using a rclone backup

restic -r rclone:pcloud:restic-backup init

4) copy local repository to distant repositroy

restic --repo rclone:pcloud:restic-backup copy --from-repo /media/myuser/mydisk/backup/

5) check local repository

restic -r /media/myuser/mydisk/backup/ check
--> 319 additional files were found in the repo, which likely contain duplicate data.

6) check distant repository : FATAL ERROR

restic --repo rclone:pcloud:restic-backup check

588 additional files were found in the repo, which likely contain duplicate data.
This is non-critical, you can run `restic prune` to correct this.
check snapshots, trees and blobs
[0:24] 100.00%  2 / 2 snapshots
Fatal: repository contains errors

7) prune distant repository : FATAL ERROR

restic --repo rclone:pcloud:restic-backup prune
enter password for repository: 
repository ca0bb18f opened (version 2, compression level auto)
loading indexes...
[0:02] 100.00%  183 / 183 index files loaded
loading all snapshots...
finding data that is still in use for 2 snapshots
[0:08] 100.00%  2 / 2 snapshots
searching used packs...
collecting packs for deletion and repacking
pack 1302d93e: calculated size 17252774 does not match real size 2834432
Run 'restic repair index'.
[0:03] 7.39%  2836 / 38393 packs processed
Fatal: pack size does not match calculated size from index

I'm leaving the repo as is for now, to try to troubleshoot this...

Regards
Franck

**Comment by MichaelEischer** [comment]
> pack 1302d93e: calculated size 17252774 does not match real size 2834432

Sorry for the late reply. If I remember correctly, then pCloud can store multiple versions of a file. Can you check whether the file in `data/13/1302d93e[...]` has multiple versions? Please download it and run `shasum -a256` on that file. The resulting hash should match its filename.

The pack file in question was likely damaged during the upload, then real size of 28MB is larger than what restic would create using the default settings. This is unfortunately not the first time we've seen such problems in conjunction with pCloud.

Did rclone report any warnings while uploading the repository copy to pCloud? Fixing the repository should be rather straightforward. Delete the broken file, then run `restic repair index` and afterwards copy the snapshots again.

**Comment by alci63** [comment]
Thanks @MichaelEischer 
Indeed, hash of ```data/13/1302d93e[...]``` does not match with file name. So I deleted the file, repaired the index and copied snapshots again.
Then check, prune, check worked:

`5m33s ➜ restic --repo rclone:pcloud:restic-backup check
using temporary cache in /tmp/restic-check-cache-1671829285
enter password for repository: 
repository ca0bb18f opened (version 2, compression level auto)
created new cache in /tmp/restic-check-cache-1671829285
create exclusive lock for repository
load indexes
[0:06] 100.00%  14 / 14 index files loaded
check all packs
check snapshots, trees and blobs
[0:26] 100.00%  9 / 9 snapshots
no errors were found
`

And yes, rclone did display some errors, that were supposedly solved after retries. Unfortunately I didn't keep the logs...

Thanks again
Franck
