### ISSUE TITLE
Backup fails with open : no such file or directory

### ISSUE THREAD

**Issue by dhopfm** [restic/restic#4695]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
Locally attached USB harddrive:
```
/dev/sdb1 on /run/media/<redacted> type ext4 (rw,nosuid,nodev,relatime,errors=remount-ro,stripe=8191,uhelper=udisks2)
```

Problem description / Steps to reproduce
----------------------------------------
When trying to `backup`, it fails with a generic error:

```
DEBUG_LOG=/tmp/restic-debug.log /usr/bin/restic --exclude-file=<redacted> backup /home/david
debug log file /tmp/restic-debug.log
debug enabled
repository 8eadd85c opened (version 2, compression level max)
found 6 old cache directories in /home/david/.cache/restic, run `restic cache --cleanup` to remove them
open : no such file or directory
```

Interestingly, even the attached [restic-debug.log](https://github.com/restic/restic/files/14233856/restic-debug.log) doesn't provide any clues (to me at least).

Expected behavior
-----------------
Backup to succeed, more helpful error + debug messages would be great. I suspect there should be a value between `open` and the `:`?

Actual behavior
---------------
Backup fails due to unknown reasons.

Do you have any idea what may have caused this?
-----------------------------------------------
This is an older repo which I just updated without any issues: password change, migration to v2, purge (no data recompression) -- no complaints or errors whatsoever. File permissions come to mind as well but are looking fine so far.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic has been serving me well through many, many years without any issues. Thank you very much for your great work and for setting the right priorities!

**Comment by MichaelEischer** [comment]
Based on the debug logfile no value was passed to "--exclude-file="

**Comment by dhopfm** [comment]
You are right, too many variables in flight on my behalf. Thanks for the quick response and the improved error message!
