### ISSUE TITLE
Find file system boundaries

### ISSUE THREAD

**Issue by fd0** [restic/restic#47]
Add option to stay on the same file system.

**Comment by fw42** [comment]
What does this mean? Don't follow symlinks that point to a different filesystem?

**Comment by fw42** [comment]
Or don't traverse into mountpoints I guess.

**Comment by fd0** [comment]
It means "do not traverse into mountpoints", symlinks aren't followed at all, they are backed up as symlinks.

**Comment by fd0** [comment]
Implemented in #626, closed.
