### ISSUE TITLE
Frequent `unsupported file type "irregular"` messages on what I think are normal files

### ISSUE THREAD

**Issue by upgrade0217** [restic/restic#4704]
Output of `restic version`
--------------------------
`restic 0.16.4 compiled with go1.21.6 on windows/amd64`

What backend/service did you use to store the repository?
---------------------------------------------------------
Local C: drive (NTFS, of course)

Problem description / Steps to reproduce
----------------------------------------

```
C:\Users\<username>\Documents\scripts>C:\Users\<username>\Documents\scripts\restic.exe --repo C:\Users\<username>\backup-<remote_drive_name> backup "P:\<directory>\<subdirectory>" -p C:\Users\<username>\key.txt
repository 9a01e5c0 opened (version 2, compression level auto)
using parent snapshot 4e1a289b
[0:00] 100.00%  1 / 1 index files loaded
error: nodeFromFileInfo P:\<directory>\<subdirectory>\<subdirectory>\<subdirectory>\<subdirectory>\<filename>.pdf: unsupported file type "irregular"
error: nodeFromFileInfo P:\<directory>\<subdirectory>\<subdirectory>\<subdirectory>\<subdirectory>\<filename>.docx: unsupported file type "irregular"

Files:           6 new,     1 changed,    46 unmodified
Dirs:            0 new,     7 changed,    55 unmodified
Added to the repository: 1.584 MiB (1.497 MiB stored)

processed 53 files, 15.556 MiB in 0:02
snapshot 1f47a98c saved
Warning: at least one source file could not be read
```

Expected behavior
-----------------

I don't expect any "irregular" file errors, these should all be plain vanilla files.

Actual behavior
---------------

I get the errors shown above. I can open the files listed in their respective programs, and the list is not consistent from run to run. (Some files appear consistently, but other ones come and go from the list.)

The drive P: is a mapped Windows network share. However, I believe I have seen this on a nearly identical backup script that backs up parts of my local C: drive to itself.

Do you have any idea what may have caused this?
-----------------------------------------------

The only change I am aware of is running a `restic self-update` command. I think my previous version was maybe 6 months to a year old. I see that issue #4560 was fixed and changed the error messages, but I only recall seeing the "invalid node type" messages a few times on one specific file, not with the volume and frequency that I'm seeing the error messages now.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is amazing, I use it everywhere, all the time. It replaced piles of bad rsync scripts, and is my absolute favorite backup solution. It was also my introduction to learning about Go.

**Comment by hello-world-dot-c** [comment]
I've just started using restic together with https://github.com/kmwoley/restic-windows-backup and am also experiencing this issue. Same restic version.

**Comment by MichaelEischer** [comment]
Just to be clear: only some files on the UNC share cause that error? Are those special in any regard, like stored in OneDrive or similar?

**Comment by hello-world-dot-c** [comment]
> Just to be clear: only some files on the UNC share cause that error? Are those special in any regard, like stored in OneDrive or similar?

Yes, indeed, in my case these files are stored in Dropbox and they seem to be online files even though I didn't enable that option. That means, these files appear in the folder but don't take up space on disk and this explains the "irregular" error. I'll now try to exclude everything in Dropbox from the backup but it would be nice if there was a way to exclude them generally without throwing an error.

**Comment by upgrade0217** [comment]
> Just to be clear: only some files on the UNC share cause that error? Are those special in any regard, like stored in OneDrive or similar?

It does appear to happen consistently on certain files, but they don't have any special characteristics that I am aware of. It happens to files on the UNC share, but has also happened with files on my local disk. I don't know if there is a good way to get file properties of the ones that do it consistently and see what might be going on in more detail?

**Comment by MichaelEischer** [comment]
From what I know about these irregular files on Windows, they are implemented using so called reparse points. According to the Windows docs you can use `fsutil reparsepoint query filename` to inspect them https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-reparsepoint .

**Comment by upgrade0217** [comment]
Thanks! It does appear that this file has become a reparse point. Output of `fsutil reparsepoint query` is below:
```
Reparse Tag Value : 0x80000007
Tag value: Microsoft
Tag value: SIS
Format version: 5
CSid:           0B0E4922-6D34-11EA-9B83-00505688148E
LinkIndex:      0x00000000.02213569
LinkFileNtfsID: 0x00010000.002e6a3c
CSFileNtfsID:   0x00060000.0003b930
CSChecksum:     0x89b8854c.9745cc10
Checksum:       0xbd4b059e.2c223963

Reparse Data Length: 0x40
Reparse Data:
0000:  05 00 00 00 10 b0 11 b1  22 49 0e 0b 34 6d ea 11  ........"I..4m..
0010:  9b 83 00 50 56 88 14 8e  69 35 21 02 00 00 00 00  ...PV...i5!.....
0020:  3c 6a 2e 00 00 00 01 00  30 b9 03 00 00 00 06 00  <j......0.......
0030:  10 cc 45 97 4c 85 b8 89  63 39 22 2c 9e 05 4b bd  ..E.L...c9",..K.
```

Looks like this is due to "Single Instance Storage" ([https://en.wikipedia.org/wiki/Single-instance_storage](https://en.wikipedia.org/wiki/Single-instance_storage)) implemented on the ancient server these files are hosted on. According to Wikipedia, SIS is "officially deprecated since Windows Server 2012."

It looks like Microsoft's new data deduplication feature for NTFS also uses reparse points ([https://learn.microsoft.com/en-us/previous-versions/windows/desktop/dedup/about-data-deduplication?redirectedfrom=MSDN](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/dedup/about-data-deduplication?redirectedfrom=MSDN)), so even when (if?) my company updates the server, restic will still not be able to handle backing up these drives.

I don't know if adding support for data-deduplication reparse points is something that would ever end up on restic's roadmap or not, but I'm at least thankful for you taking the time to help me understand what was going on, @MichaelEischer . I'll leave it to you to close this issue if you think that supporting these reparse points is off the table -- it's certainly above my ability to implement and submit a pull request. :)

**Comment by upgrade0217** [comment]
For anyone's future reference, the reparse tag value for SIS deduplication (the old one) is `0x80000007`, and the tag for the new deduplication scheme is `0x80000013`.

**Comment by DRON-666** [comment]
> so even when (if?) my company updates the server, restic will still not be able to handle backing up these drives.

@upgrade0217 This is not true: there is an [exception](https://tip.golang.org/src/os/types_windows.go#L201) for `IO_REPARSE_TAG_DEDUP` in `go` runtime.

**Comment by upgrade0217** [comment]
> there is an [exception](https://tip.golang.org/src/os/types_windows.go#L201) for `IO_REPARSE_TAG_DEDUP` in `go` runtime.

Oh, that's fantastic! Support for SIS deduplication reparse points would be nice, although only for legacy applications. It looks like the support for this belongs at the golang level, so I'll close this issue.

Thanks all!

**Comment by Framsfex** [comment]
I have similar problems with restic 0.19.1 on Windows 10:

```
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\Microsoft.OutlookForWindows_8wekyb3d8bbwe\olk.exe: unsupported file type "irregular"pData/Local/Microsoft/Windows/WebCache/WebCacheV01.dat
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\Microsoft.SkypeApp_kzf8qxf38zg5c\Skype.exe: unsupported file type "irregular"dmin/AppData/Local/Microsoft/Windows/WebCache/WebCacheV01.dat
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsStore_8wekyb3d8bbwe\microsoftstore.exe: unsupported file type "irregular"Local/Microsoft/Windows/WebCache/WebCacheV01.dat
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsStore_8wekyb3d8bbwe\store.exe: unsupported file type "irregular"/AppData/Local/Microsoft/Windows/WebCache/WebCacheV01.dat
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\GameBarElevatedFT_Alias.exe: unsupported file type "irregular"t/Windows/WebCache/WebCacheV01.dat
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\Microsoft.ZuneMusic_8wekyb3d8bbwe\MediaPlayer.exe: unsupported file type "irregular"pData/Local/Microsoft/Windows/WebCache/WebCacheV01.dat
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\Skype.exe: unsupported file type "irregular"
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\WindowsPackageManagerMCPServer.exe: unsupported file type "irregular"/Users/admin/AppData/Local/Microsoft/Windows/WebCache/WebCacheV01.dat
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\WindowsPackageManagerServer.exe: unsupported file type "irregular"
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\microsoftstore.exe: unsupported file type "irregular"
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\olk.exe: unsupported file type "irregular"
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\python.exe: unsupported file type "irregular"
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\python3.exe: unsupported file type "irregular"
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\store.exe: unsupported file type "irregular"
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\ubuntu1804.exe: unsupported file type "irregular"
error: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\winget.exe: unsupported file type "irregular"

```

this is just a short extract, I get many hundreds of these error messages.
My Windows knowhow is nearly zero, I run our central rest-server and the users ask me, how to handle these restic errors.
But I am an UNIX guy :-}
What can I tell my Windows users?
