### ISSUE TITLE
Backups fail with "unable to save snapshot" - no retries

### ISSUE THREAD

**Issue by ItalyPaleAle** [restic/restic#4706]
Output of `restic version`
--------------------------

restic 0.16.2 compiled with go1.21.3 on linux/amd64

(Installed from the Fedora repositories)

What backend/service did you use to store the repository?
---------------------------------------------------------

Restic REST server, running on a RPi and connected via Tailscale

Problem description / Steps to reproduce
----------------------------------------

The connection between the source and the target server (REST server running on a RPi) is not always stable. Backups are often failing with a network error while saving snapshots:

> Fatal: unable to save snapshot: Post "http://:***@100.xxx.xxx.xxx:4848/xxx/data/5d0094bb55e5b179bcfc04febe8dba95ae3e0ff43ed9176220c1f0432295910f": readfrom tcp 100.xxx.xxx.xxx:39242->100.xxx.xxx.xxx:4848: write tcp 100.xxx.xxx.xxx:39242->100.xxx.xxx.xxx:4848: write: connection timed out

Note that sometimes the error is different, such as a "connection timed out" on the read side. All of the errors are network-related.

Expected behavior
-----------------

In case of network failures, Restic should automatically retry the operation, with an exponential backoff.

Actual behavior
---------------

Restic shows a fatal error, aborts the backup, and exits.

Do you have any idea what may have caused this?
-----------------------------------------------

I _suspect_ the operation of saving a snapshot is not retried in case of transient network failures.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic helps me every day :) It also saved my bottom at least once. I am running it on my servers as well as my Linux dev box, and I've been recommending it to others!

**Comment by MichaelEischer** [comment]
Fixed by https://github.com/restic/restic/pull/4784. The issue here is that retries currently only happen for up to 15 minutes. However, a stuck connection may take longer than that to timeout and therefore results in no retries at all.
