### ISSUE TITLE
Post Quantum Encryption Support

### ISSUE THREAD

**Issue by JayXT** [restic/restic#4738]
It's a feature request for future restic releases.

**What should restic do differently? Which functionality do you think we should add?**
restic offers sane encryption defaults for modern state of computing. However, when general quantum computers come into existence, present encryption protocols will fall short before their processing and especially deciphering capabilities. So, it's important to ensure restic is able to use next generation encryption protocols.

**What are you trying to do? What problem would this solve?**
The main problem is that restic encryption in its current design will eventually become obsolete and not secure enough. So the solution is to redesign/upgrade it appropriately.

**Comment by MichaelEischer** [comment]
> The main problem is that restic encryption in its current design will eventually become obsolete and not secure enough.

Huh, can you elaborate on that a bit more? restic currently uses AES-256, poly1305 & scrypt but no asymmetric ciphers. Based on what I know about post quantum cryptography, neither of these algorithms is broken by quantum computers.

**Comment by JayXT** [comment]
Oh... So it doesn't rely on asymmetric encryption? If it's the case, then probably you're right and the request could be considered as resolved. Thank you for the prompt reply!

**Comment by MichaelEischer** [comment]
There has been some discussion towards using asymmetric encryption in https://github.com/restic/restic/issues/187 , but there's nothing implemented.
