### ISSUE TITLE
Feature Request: Use a non-default User-Agent for HTTP(s) connections

### ISSUE THREAD

**Issue by systemmonkey42** [restic/restic#4768]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When using a remote REST or HTTP(S) backend, the user agent provided is the default "Go-http-client/2.0"

An example user agent might be
`Restic/0.16.4; arch/x86_64`
which would be detected by the frontend, allowing it to apply correct validation checks.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Using our front-end application gateway, I would like to provide restic specific validation requirements (eg, disable forms based login, while enforcing HTTPS and BASIC auth), by detecting a "restic" specific user agent.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Always

**Comment by MichaelEischer** [comment]
I'm not a big fan of changing the user agent for every one. But it would be fine to extend the backends with an option to change the user agent. Although, someone would have to implement it, I'm too busy with other PRs.

**Comment by konidev20** [comment]
Hey @MichaelEischer, I have created a PR for this. Please check it out when you're free.

**Comment by systemmonkey42** [comment]
Hi @konidev20,

That looks great.  Would it be possible for an environment variant like `RESTIC_USER_AGENT` to be used if it exists?

Thanks

**Comment by konidev20** [comment]
> Hi @konidev20,
> 
> That looks great. Would it be possible for an environment variant like `RESTIC_USER_AGENT` to be used if it exists?
> 
> Thanks

Will check it out this weekend.

**Comment by konidev20** [comment]
Hey @systemmonkey42, 

This has been merged in the latest main branch. 

Please close this issue, once you're good with the changes

**Comment by systemmonkey42** [comment]
Thanks for that.  It works perfectly.
