### ISSUE TITLE
invalid character '¬' after object key:value pair

### ISSUE THREAD

**Issue by fliespl** [restic/restic#4771]
Output of `restic version`
--------------------------

root@bigmike:~# restic version
restic 0.16.4 compiled with go1.21.6 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------

sftp

Problem description / Steps to reproduce
----------------------------------------

Running daily backup fails with following and won't start:

```
/usr/local/bin/restic backup -x --exclude-file /root/autorestic-exclude.txt --tag ar:location:bm /
using parent snapshot 01c7dce9
invalid character '¬' after object key:value pair
DecodeIndex
github.com/restic/restic/internal/index.DecodeIndex
	/restic/internal/index/index.go:523
github.com/restic/restic/internal/index.ForAllIndexes.func1
	/restic/internal/index/index_parallel.go:29
github.com/restic/restic/internal/restic.ParallelList.func2
	/restic/internal/restic/parallel.go:45
golang.org/x/sync/errgroup.(*Group).Go.func1
	/home/build/go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:75
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650
```

```
/usr/local/bin/restic check
using temporary cache in /tmp/restic-check-cache-1616868260
create exclusive lock for repository
load indexes
error: error loading index 7a6566833ff2e44505d6495ee25b1183e2a4924a8c65e278375171a2267bc29f: DecodeIndex: invalid character '¬' after object key:value pair
Fatal: LoadIndex returned errors

exit status 1

Error: 1 errors were found
```

Expected behavior
-----------------

Correct backup

Actual behavior
---------------

Output above

Do you have any idea what may have caused this?
-----------------------------------------------

Not really.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Most days it does, not while it fails :)

**Comment by MichaelEischer** [comment]
> invalid character '¬' after object key:value pair

This specific error message means that data corruption occurred while restic was creating a backup. That usually means a bitflip in the CPU/memory of the host creating the backup. (It is NOT a problem of the repository storage, that would result in a different error).

Please run a memory / CPU stress test to check for problems with your hardware.

As only the index seems to be affected, you can repair your repository using `restic repair index`. In addition, please run `restic check --read-data` to verify the integrity of your repository. Warning: this will have to download the whole repository.

**Comment by fliespl** [comment]
Thank you - understood!
