### ISSUE TITLE
Use `fd` for `restic find` if present in `PATH`

### ISSUE THREAD

**Issue by j-lakeman** [restic/restic#4777]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Utilise `fd` https://github.com/sharkdp/fd/ for `restic find` if present in `PATH`.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
It's much faster than anything else and supports regular expressions by default as well as glob-based patterns.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Nevertheless the greatest backup application I ever came across!

**Comment by MichaelEischer** [comment]
`restic find` works with an internal virtual filesystem. There is nothing `fd` would work on.

You can already use `fd` to search a mounted restic repository.
