### ISSUE TITLE
Resuming an interrupted backup when using REST backend doesn't work until you manually repair index

### ISSUE THREAD

**Issue by Whissi** [restic/restic#4779]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
REST

Problem description / Steps to reproduce
----------------------------------------
I start a backup using the following command: `restic -r rest:https://user:pass@invalid.repo.borgbase.com backup D:\MyData`

After uploading 500+ MB I press <kbd>Ctrl</kbd> + <kbd>C</kbd> to interrupt the backup.
Restic ends with the following output:
```
signal interrupt received, cleaning up
Fatal: unable to save snapshot: context canceled
```
Now I re-run the previous command to resume backup. Instead of continuing backup where Restic stopped, Restic is re-reading from beginning and re-uploading already uploaded files.

When I check the repository before resuming the backup with the command `restic check` I'll get the following output:
```
[...]
check all packs
pack 956ded1b716dd3f09fd816028290d67b39255ca73922eb1c5aa3b1407082a04d: not referenced in any index
pack aa036d14c4b569a42a2b24f449bda4e1d6220d204146b31b4325c06add8e80b7: not referenced in any index
pack 17851792d472748bd1d160ff11878e292cf63685b99be5b6c336a26c33412adf: not referenced in any index
pack ba3dc39796ad03beac7abe39087c2c5573728b84c0a11582f070368d121aa971: not referenced in any index
pack 4c711429133f693200d940620ed2e921524b59c5946344afe4de0ccf74bc5f74: not referenced in any index
pack 925ad153f9d76d90fd047833d88337ba8d3ef83b990daca3d9243dc26c20c75b: not referenced in any index
pack 62f8d52c6fb5d7f8462ca085c92af930ed53a1c651a9253f64fea7e7e3a40181: not referenced in any index
pack a290f232d88ee3833423b9972d380fb6d2249834dceaf117d23ffa30b0731ba2: not referenced in any index
8 additional files were found in the repo, which likely contain duplicate data.
This is non-critical, you can run `restic prune` to correct this.
check snapshots, trees and blobs
[0:00] 100.00%  1 / 1 snapshots
no errors were found
```
If I will now run the command `restic repair index` which will generate the following output
```
repository f5e95b89 opened (version 2, compression level auto)
loading indexes...
getting pack files to read...
adding pack file to index 17851792d472748bd1d160ff11878e292cf63685b99be5b6c336a26c33412adf
adding pack file to index 4c711429133f693200d940620ed2e921524b59c5946344afe4de0ccf74bc5f74
adding pack file to index 62f8d52c6fb5d7f8462ca085c92af930ed53a1c651a9253f64fea7e7e3a40181
adding pack file to index 925ad153f9d76d90fd047833d88337ba8d3ef83b990daca3d9243dc26c20c75b
adding pack file to index 956ded1b716dd3f09fd816028290d67b39255ca73922eb1c5aa3b1407082a04d
adding pack file to index a290f232d88ee3833423b9972d380fb6d2249834dceaf117d23ffa30b0731ba2
adding pack file to index aa036d14c4b569a42a2b24f449bda4e1d6220d204146b31b4325c06add8e80b7
adding pack file to index ba3dc39796ad03beac7abe39087c2c5573728b84c0a11582f070368d121aa971
reading pack files
[0:00] 100.00%  8 / 8 packs
rebuilding index
[0:00] 100.00%  225 / 225 packs processed
deleting obsolete index files
[0:00] 100.00%  1 / 1 files deleted
done
```
The next time I resume backup will continue backup where I previously interrupted as expected.

I am unable to reproduce this behavior using local or sftp backend.

Expected behavior
-----------------
There shouldn't be an error when the backup was interrupted.

The backup should resume from where the previous run was interrupted (i.e., already uploaded files should not be re-uploaded) — without the need to repair the index.

Actual behavior
---------------
When a backup using REST backend got canceled, there's an error message (`Fatal: unable to save snapshot: context canceled`) that doesn't occur when using other backends.

When the backup is re-run (resumed), Restic starts from scratch (re-uploading files that were already uploaded).

Do you have any idea what may have caused this?
-----------------------------------------------
No, except that using REST backend seems to trigger this.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I am new to Restic and still evaluating. But it was really pleasing to see that the built-in support for volume shadow copies seems to work flawlessly.

**Comment by MichaelEischer** [comment]
This is expected behavior, see https://restic.readthedocs.io/en/stable/faq.html#will-restic-resume-an-interrupted-backup

> This effectively makes it continue from where it saved the last index, which should be up to a few minutes ago.

Index files are currently uploaded every 10 minutes, that is your test case is apparently shorter than that.

> I am unable to reproduce this behavior using local or sftp backend.

The index upload behaves exactly the same for all backends. The different behavior must be caused by your test setup, maybe your upload to those backends is much faster?


At some point in the future it might be possible that restic updates the index when the backup gets interrupted, but for now index updates only happen periodically.

**Comment by Whissi** [comment]
Are you really sure there's no issue? What about the fact that when canceling a backup with a REST backend, we encounter that error message, whereas it doesn't happen with a local or SFTP backend?

However, I can confirm the following: I repeated the test with a new repository. After running for 20 minutes, I canceled the backup with <kbd>CTRL</kbd>+<kbd>C</kbd>. Once again, I received the error message, which I hadn't seen with other backends so far.

Now, I waited for 60 minutes. During this time, I regularly invoked `restic check`, which consistently showed that 160 packs were not yet assigned (`pack e75...: not referenced in any index`) — even after 60 minutes. I was quite convinced that you must be mistaken. But when I restarted (resumed) the backup after these 60 minutes, it indeed skipped the previously backed-up files as expected and continued from where I had interrupted the first backup run.

**Comment by MichaelEischer** [comment]
> Are you really sure there's no issue? What about the fact that when canceling a backup with a REST backend, we encounter that error message, whereas it doesn't happen with a local or SFTP backend?

Whether that error message is shown or not depends on how fast restic can remove the lock that's held during a backup. Either way, it doesn't matter; what's happening behind the scenes is the same in both cases.

> Now, I waited for 60 minutes. During this time, I regularly invoked `restic check`, which consistently showed that 160 packs were not yet assigned (`pack e75...: not referenced in any index`) — even after 60 minutes.

The rest-server has no clue about the internals of the repository format, just like storing the repository locally or via sftp. Thus, nothing will change while no backup or similar runs.
