### ISSUE TITLE
Repository layout differs between sftp/local and s3 compatible repositories

### ISSUE THREAD

**Issue by ckemper67** [restic/restic#478]
I was considering syncing an sftp generated restic backup repository into an s3 compatible repository for long term storage, but it turns out the directory layout differs between those.

## Output of `restic version`
restic compiled manually

## Expected behavior
Repository layout compatible between sftp and s3

## Actual behavior
sftp/local toplevel directories:
config     data/      index/     keys/      locks/   snapshots/ tmp/

s3 toplevel directories:
config     data/      index/     key/   snapshot/ 

Notice that "keys" and "snapshots" differ between these two

## Steps to reproduce the behavior
restic -r sftp:user@server:restic backup ~

sync server directory to s3/gcs

restic -r s3:mybucket list snapshots

**Comment by ckemper67** [comment]
I forgot to add: The layout below the "data" directory differs as well: The sftp/local use the first two characters of the content hash as a directory prefix to avoid too many directory entries.

**Comment by fd0** [comment]
I'm sorry, but I don't think we can support this directly. When more backends are implemented, depending on the actual storage we cannot guarantee that directly copying data over to a different backend will work, so I will close this issue. You can however subscribe to issue #323, which tracks implementing a `copy` command to transfer data from one backend to another, thereby converting the format.
