### ISSUE TITLE
Restic restore include-file/exclude-file switches

### ISSUE THREAD

**Issue by akrabu** [restic/restic#4781]
Output of `restic version`
--------------------------

restic 0.16.4 compiled with go1.21.6 on darwin/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

It would be helpful if the include-file, --iinclude-file, --exclude-file, and --iexclude-file switches existed for the "restore" function.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I recently needed to restore a bunch of different files that got deleted.  About 1600 of them, in random places.  When I did "restic diff" I could easily get a list of all the files that were deleted - but I don't have an easy way to feed that into Restic to restore just those files.

My options are to restore a large swath of files to get a few, or to run restic restore on each file individually - which seems impractical with that many files.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic rules!  ✌️

**Comment by MichaelEischer** [comment]
Thanks for the suggestion. I agree that `restore` should offer those options in a way similar to the backup command. Anyone up for a PR?

**Comment by konidev20** [comment]
@akrabu the changes have been merged. You can test :)

**Comment by ahmed658** [comment]
@konidev20 paths of files with brackets don't work
file.txt:
/E/data/Design development/3d maps/Elgabaly 3d max library/1-Exterior/2-Elevations/3-Materials/3-MARBLE CLADDING & STONE/marble/marbel/waterget/WR-7200o[.jpg

restic restore --include-file "/share/file.txt"
Fatal: --include-file: invalid pattern(s) provided

I had to edit the file and add a \ before the [

so now it's
/E/data/Design development/3d maps/Elgabaly 3d max library/1-Exterior/2-Elevations/3-Materials/3-MARBLE CLADDING & STONE/marble/marbel/waterget/WR-7200o\[.jpg

and restore worked fine after editing:
Summary: Restored 13 / 1 files/dirs (146.035 KiB / 146.035 KiB) in 0:01

but it's not very practical to edit files to manually skip characters in paths listed and saved by restic ls command itself

**Comment by ahmed658** [comment]
@MichaelEischer Is there a way to give restic a list of plain file names instead of patterns?

**Comment by konidev20** [comment]
> @MichaelEischer Is there a way to give restic a list of plain file names to restore instead of patterns?

You can try something like an awk script or a sed expression to escape the special characters. 

```
restic ls | sed 's/[]\/$*.^[]/\\&/g' > includePatterns.txt

```

**Comment by MichaelEischer** [comment]
> Is there a way to give restic a list of plain file names to restore instead of patterns?

Not at the moment, feel free to open a feature request.
