### ISSUE TITLE
Add 'prune' command

### ISSUE THREAD

**Issue by fd0** [restic/restic#479]
In #459, the `optimize` command was removed due to a bug. This issue is about adding a new command called `prune` which basically does the same as `optimize`, just with a better name (and hopefully without the bug).

**Comment by squarism** [comment]
Is this similar to deleting snapshots?  I'd like to subscribe/watch an issue that represents when deletes are implemented if I understand restic correctly (which may not be the case).  As of right now, are repositories append only?

**Comment by fd0** [comment]
This issue is about adding the `prune` command, which is one part of regularly removing old snapshots. I'd suggest subscribing to #51 or #18.

And you're right: At the moment, repositories are append-only. We had a command similar to `prune` for a while, but it turned out that there was a grave bug in the code so I removed it for now. Better safe than sorry.

**Comment by fd0** [comment]
I've nearly finished the implementation of a `prune` command and need some feedback on how to specify which snapshots to remove/keep, please add your comments to #572. Thanks!
