### ISSUE TITLE
command self-update not available on 0.16.4 on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by Anita219** [restic/restic#4798]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
-

Problem description / Steps to reproduce
----------------------------------------
At work, we have a script to setup our machines for development. I just switched to Ubuntu 24.04 LTS, so had to setup everything. Part of the script is to install the needed packages using apt and then setting up some stuff.  When running the script, I discovered the following error:

> unknown command "self-update" for "restic"

After some debugging, I determined, that this happens when I install restic by hand, too. So it seems to be a problem in either restic or apt - as you can see in the following screenshot. Unfortunately, the version 0.16.4 is the only one available with apt, so I cannot check other versions.

![image](https://github.com/restic/restic/assets/9081375/ae178b45-554a-4ca3-9d7d-963bb19d74fb)

If I use the newest version from here https://github.com/restic/restic/releases/tag/v0.16.4 and run it, it has the self-update feature. 

Expected behavior
-----------------
restic self-update should be available or the documentation should be updated

Actual behavior
---------------
the command restic self-update is included in the documentation but does not work

Do you have any idea what may have caused this?
-----------------------------------------------
Nope. Maybe the package maintainer decided to exclude this feature for future releases? It's still part of the official documentation though. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Despite this problem, I find the documentation very easy to follow. So thank you for being so detail-oriented. It really helps. :)

**Comment by mafalb** [comment]
The debian/ubuntu package doesn't have self-update. There is a patch applied that removes it.
https://salsa.debian.org/go-team/packages/restic/-/blob/master/debian/patches/remove-self-update.patch

This makes sense IMO, modifying stuff by hand that are managed by the package manager cries for trouble. I would say it's not a bug, it's a feature.

**Comment by Anita219** [comment]
Thank you very much for linking it! I googled a lot to find any notice that it is intentional but found anything. I agree that it can be considered a feature - it is definitely a change though. Thank you :)

**Comment by sneakyx** [comment]
Sorry to ask on this old and closed issue, but how can I update now to version 0.18.x on Ubuntu 24.04?

**Comment by rawtaz** [comment]
@sneakyx It is up to the Ubuntu package maintainers to provide the different versions of restic in the API package repositories.

However, you can always download the latest release of restic from the official download page here: https://github.com/restic/restic/releases

**Comment by calebreed601-dot** [comment]
What version r u using exactly

**Comment by sneakyx** [comment]
At the moment on the old server with Ubuntu 22.04 version 18.1. On the newer server (Ubuntu 24.04) 16.x (the newest package version).
We had an issue during the restore process (some files were not in the expected folder) and I thought it might have to do something with the different versions of restic. But I can't tell exactly, because my workmates did the restore process. I was only surprised that the newer server has an older package version.

**Comment by calebreed601-dot** [comment]
Ok, I'll check it out.
