### ISSUE TITLE
Memory leak in fuse mount

### ISSUE THREAD

**Issue by viric** [restic/restic#480]
If I do a "ls -lRa" through multiple snapshots, the amount of memory used by the restic process increases. I stopped it when it took 7GB of RAM.
## Output of `restic version`

restic 0.1.0 (v0.1.0-451-g4dac6d4)
compiled at 2016-03-02 17:56:59 with go1.5.3
## Expected behavior

Keep the amount of memory used low, for an ls.
## Actual behavior

Too much memory used

**Comment by fd0** [comment]
That's a bug, thanks for reporting!
