### ISSUE TITLE
TMPDIR not work as expected on Windows

### ISSUE THREAD

**Issue by delhi2050** [restic/restic#4813]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
local

Problem description / Steps to reproduce
----------------------------------------
```shell
set TMPDIR=D:/TMP/restic
set RESTIC_REPOSITORY=D:/BAK/proj
restic backup --no-cache C:/Projects
```

Expected behavior
-----------------
Writing restic-temp-pack-000000000 to D:/TMP/restic/restic-temp-pack-000000000

Actual behavior
---------------
Writing restic-temp-pack-000000000 on C:\Users\<user>\AppData\Local\Temp\restic-temp-pack-000000000

**Comment by MichaelEischer** [comment]
The correct environment variable on Windows is `TMP` or `TEMP`. I've opened a PR to fix the documentation.
