### ISSUE TITLE
restic dump fails on filenames with blanks

### ISSUE THREAD

**Issue by pille** [restic/restic#4827]
Output of `restic version`
--------------------------
`restic 0.16.4 compiled with go1.21.6 on linux/amd64`

What backend/service did you use to store the repository?
---------------------------------------------------------
sftp (but should not matter. also skipping backend-related config, see reasoning below.)

Problem description / Steps to reproduce
----------------------------------------
restic dump command fails on filenames including blanks.

regular behavior:
```
restic --tag homes dump latest "/home/user/file.txt"
repository 1e9427f6 opened (version 2, compression level max)
test file data
```

failing behavior:
```
restic --tag homes dump latest "/home/user/file with blanks.txt"
Fatal: no file and no snapshot ID specified
```
failing behavior (including escaping the blanks):
```
restic --tag homes dump latest "/home/user/file\ with\ blanks.txt"
Fatal: no file and no snapshot ID specified
```

Expected behavior
-----------------

dump any file given, that is included in snapshot

Actual behavior
---------------

file(name)s including blanks cause error message

Do you have any idea what may have caused this?
-----------------------------------------------

error message seems to be coming from parameter parsing code, as it errors out before touching the repository.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
my motivation of submitting this "minor inconvenience bug" increased, when i got notifications that two of my other reports (3806 and 4018) got fixed/implemented/closed. [not hash-tagging those issues, since they are not really related]
since i switched to restic 2/3 years ago, my established use-cases usually just worked and created confidence.

**Comment by MichaelEischer** [comment]
> restic --tag homes dump latest "/home/user/file with blanks.txt"
> Fatal: no file and no snapshot ID specified

I can't reproduce that error. For my test snapshot `dump` works just as expected.

That error message is only returned by the dump command if it does not receive exactly two arguments. On Linux, the CLI arguments are already passed argument by argument by the calling process, such there's not much the called program can mess up. Which poses the question how exactly are you calling restic? Manually from a shell, from a script or something else?

**Comment by pille** [comment]
thanks for clarifying and pointing to my broken wrapper.
