### ISSUE TITLE
improving system's responsiveness

### ISSUE THREAD

**Issue by gour** [restic/restic#483]
## Output of `restic version`

```
restic 0.1.0 (v0.1.0-460-gafd0eb7)
```

I was evaluating restic some months ago, but the cpu% usage and average load was so high making my 16GB i7 2.8G system totally unresponsive while performing full backup (~600G) although I tried with re-nice to reduce the load and improve system's responsiveness.

Yesterday, after reading about some similar backup applications I could see that restic is still the leader in terms of ui-friendliness, ease-of-use, engineering design etc. so I've visited #restic where I received some hint which could make the system usable while doing backup for the first time.

Now I've tried with:

```
$ sudo ionice -c 3 nice ./restic -r /media/gour/backup/ backup /home
```

and despite of seemingly very high average lo load (31/28/26) and cpu% usage of >200%, the temperature of the system does not go above 70 C, and the backup rate is over 39MiB/s while restic is performing backup of my /home (~700GiB).

However, the most important change is that now my system is quite responsive which was not the case in the past when I was practically uselessly slow for any practical work. :-)

Hoping to help someone who might encounter problem with Restic and system responsiveness as well as place to share experience and/or further tips how to improve performance.

Finally, let me say that I'm using Sid with:

```
4.4.0-1-amd64 #1 SMP Debian 4.4.2-3 (2016-02-21) x86_64 GNU/Linux
```

kernel.

**Comment by fd0** [comment]
Thanks for leaving this here, I think it's valuable to add this to the user documentation.

**Comment by jniggemann** [comment]
I do not experience high system load and unresponsiveness, plus this issue is quite old. 
Is it possible this issue is no longer current with restic 0.7.x?

**Comment by fd0** [comment]
I'm inclined to just close the issue for now and add an entry to the FAQ, not in terms of "what to do when the system is unresponsive" but rather "how to prioritize restic's IO" or so.

**Comment by jniggemann** [comment]
I'll add that to the FAQ.

**Comment by fd0** [comment]
That'd be much appreciated. Thanks a lot for your work on the documentation!
