### ISSUE TITLE
Restic stuck at end of backup

### ISSUE THREAD

**Issue by pfrankw** [restic/restic#4830]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
b2:bucketname as repository

Problem description / Steps to reproduce
----------------------------------------
Restic is stuck at the end of a backup of around 1.6TB of data.
It is showing the timer and have been 25 hours so far.
It isn't doing anything apparently.

Expected behavior
-----------------
It should have finished by hours.

Actual behavior
---------------
It's stuck at end of the backup.

![image](https://github.com/restic/restic/assets/6452799/cba35117-1bee-4e63-b477-c104dddcafcb)

If you see that there are multiple lines it's because I have pressed enter.

Do you have any idea what may have caused this?
-----------------------------------------------
The filesystem restic is reading data from is BTRFS, I don't know if there is any correlation.
On top of that this 1.6TB backup failed multiple times due to electrical issues that stopped the server. Maybe is it trying to remove older "attempts" ? It doesn't seem but may be.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It always does, that's why I'm here. Thank you.

**Comment by pfrankw** [comment]
Also, restic is currently running inside screen.

**Comment by pfrankw** [comment]
Update: It is now running for 37 hours. If i issue "restic snapshots" I can't see new snapshots.

**Comment by pfrankw** [comment]
Solved: It seems that the repository was locked from the previous failures, but there was no message, the restic process was just stuck because it needed to acquire lock.

In order to solve it I had to Ctrl+C, issue restic unlock, and then redo the backup.

**Comment by MichaelEischer** [comment]
> Solved: It seems that the repository was locked from the previous failures, but there was no message, the restic process was just stuck because it needed to acquire lock.

The `backup` command acquires the necessary lock on startup and would exit with an error if it is unable to extend the lock. It much rather looks like the B2 backend somehow got stuck. But that's no longer possible to verify after the fact, so I'll close this issue for now.

If you continue to have problem, please reopen this issue or try accessing B2 via S3, see https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#backblaze-b2 .
