### ISSUE TITLE
Slight cosmetic snapshot listing bug 

### ISSUE THREAD

**Issue by akrabu** [restic/restic#4834]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on darwin/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
SharePoint

Problem description / Steps to reproduce
----------------------------------------

If a snapshot's host (possibly other fields) contains an `’` it will throw off column alignment.  Or at least I think that's what's happening.  It could be that having that character in tags or pathnames would also throw off alignment, but I did not test that.

Expected behavior
-----------------

Tags should be lined up in one column

Actual behavior
---------------

Tags do not line up, possibly because of the `’` in the host name?  This does not happen on standard `'` apostrophes.

![Screenshot 2024-05-29 at 11 21 47 AM](https://github.com/restic/restic/assets/6868732/b601aad7-be93-435f-9fa2-e23cd88e34ac)

![Screenshot 2024-05-29 at 11 23 37 AM](https://github.com/restic/restic/assets/6868732/722eb8db-5430-4886-8960-7dcf47131e51)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

🫶

**Comment by MichaelEischer** [comment]
This is related to unicode characters. The table code currently uses `len(...)` to determine the length of a string, which is wrong for all characters except ASCII.

To complicate things further, characters can be narrow or wide (width of 1 or 2), see https://github.com/restic/restic/blob/2280fbfd2e8e3b6eeba8ebaa95d06b9e4519ced9/internal/ui/termstatus/status.go#L262 for more details. The go standard library provides a rune count function https://pkg.go.dev/unicode/utf8@go1.22.3#RuneCountInString , however, what we need is the terminal display width.

Anyone up for a PR?

**Comment by fthoma** [comment]
_First of all: Thanks  for restic, it saved me more than once from my own stupidity_ :wink:

I looked into it a bit and have two suggestions for a PR replacing the relevant `len(...)` calls in the table code.

1. Use [go-runewidth](https://github.com/mattn/go-runewidth) package which has [StringWidth()](https://github.com/mattn/go-runewidth/blob/master/runewidth.go#L177)
2. Implement a helper function similar to the POSIX [wcwidth](https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c)

I tried option 1) locally and it worked for narrow and wide characters alike. At least with my terminal font.

Any thoughts or preferences?
