### ISSUE TITLE
System crash on MacOS

### ISSUE THREAD

**Issue by CAP-ONE** [restic/restic#4836]
Output of `restic version`
--------------------------

restic 0.16.4 compiled with go1.21.6 on darwin/arm64

What backend/service did you use to store the repository?
---------------------------------------------------------

Local, NTFS HDD to APFS (encrypted) nvme SDD

Problem description / Steps to reproduce
----------------------------------------

Using Restic on a Macbook M1 Max 2021 with 32 Go of RAM, running Sonoma 14.5

During the backup, the system freeze then reboot itself, likely after a kernel panic. Panic Log after booting below:

[panic_log.txt](https://github.com/user-attachments/files/15506612/panic_log.txt)

Commands executed for the local backup 

```
restic init --repo "/Volumes/Medias SSD/storage-backup"
restic -r "/Volumes/Medias SSD/storage-backup" --verbose backup /Volumes/Storage --exclude-file=/Users/[username]/Documents/excludes.txt
```
tested with `--compression max` before going back to default compression when I thought this was causing the issue

Last line the terminal displayed was `[1:18:55] 17.84%  568368 files 155.847 GiB, total 883977 files 873.807 GiB, 1 errors ETA 356:06:49` with at least 1.2 To of space left on the SSD before initializing the backup, so unlikely caused due to a lack of space 

Expected behavior
-----------------

Exit properly with an error  without causing the system to crash.

Actual behavior
---------------

The system freeze then reboot. All backup progress is then lost.

Do you have any idea what may have caused this?
-----------------------------------------------

Maybe CPU or memory related

**Comment by MichaelEischer** [comment]
A whole system crash is a problem of the underlying operating system and/or drivers. It is not a bug in restic.

From the panic log:
>       Kernel Extensions in backtrace:
>          com.paragon-software.filesystems.ntfs(160.1.16)[F7D5D6FD-A571-3352-AC45-B7BB18CDF667]@0xfffffe0015868000->0xfffffe00158a8b6b

It looks like your ntfs driver crashed. This must be fixed there.
