### ISSUE TITLE
`restic prune --forget` stuck with `futex(0x633e04e81548, FUTEX_WAIT_PRIVATE, 0, NULL`

### ISSUE THREAD

**Issue by fdw** [restic/restic#4846]
Output of `restic version`
--------------------------
`restic 0.16.4 compiled with go1.21.6 on linux/amd64`

What backend/service did you use to store the repository?
---------------------------------------------------------
b2

Problem description / Steps to reproduce
----------------------------------------
I'm running `restic prune --repo=b2:<something>`. The same command has worked before, but now it has been stuck (see below).

Expected behavior
-----------------
It deletes unused data, repacks other and finally ends.

Actual behavior
---------------
It runs smoothly until `98.48%  65 / 66 packs repacked`. Then, it seems to get stuck. I've waited now for two hours with no change visible.
Running it with `DEBUG_FILES=*`  leaves a very large output right before it hangs: `repository/packer_manager.go:198	repository.(*Repository).savePacker	156	 updating blobs [<Blob (data) e386718f, offset 0, length 698, uncompressed length 5624> <Blob (data) 93459dd0, offset 698, length 166, uncompressed length 244> <Blob (data) de0ea222, offset 864, length 1624, uncompressed length 3908> <Blob (data) fd21a2a2, offset 2488, length 1097, uncompressed length 3426> <Blob (data) f076bdc9, offset 3585, [...] failed reading stderr from command: /usr/bin/bash ; Cause: bufio.Scanner: token too long`.
`strace` (without `-f`) gives:
```
futex(0x633e04e81548, FUTEX_WAIT_PRIVATE, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = 202
futex(0x633e04e81548, FUTEX_WAIT_PRIVATE, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = 202
futex(0x633e04e81548, FUTEX_WAIT_PRIVATE, 0, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = 202
```

`strace -f` seems very busy, but ultimately has also no interesting lines (if you need a log, please tell me).
Maybe significant is `lsof`:
```
[...]
restic  <snip>   7u      REG   0,36  3264440      51 /tmp/restic-temp-pack-1761677866 (deleted)
restic  <snip>  14u      REG   0,36  9844155      63 /tmp/restic-temp-pack-1201850915 (deleted)
restic  <snip> 15u     sock    0,9      0t0   34169 protocol: TCP
restic  <snip> 16u      REG   0,36 19937926      62 /tmp/restic-temp-pack-4101877415 (deleted)
```

Do you have any idea what may have caused this?
-----------------------------------------------
Absolutely no idea. Worked before, and I haven't changed anything about the repo.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Today not so much, because I've been trying to fix this for some hours now ;)
However, I've been running it without major problems for some years now, and it's an essential part of my backup process. I feel quite safe (and also secure) that my data cannot disappear!
Thank you! ❤️

**Comment by fdw** [comment]
I've made it work in two steps using `--max-repack-size`, first doing about half of the repacks, and then the second half. Either his has changed something, or there was some hiccup in the backend.

**Comment by MichaelEischer** [comment]
Closing for now as it looks like this was a backend hickup and I don't think there's something we can do here. Feel free to reopen the issue if the problem reappears.
