### ISSUE TITLE
Restic repository corrupted with error: ciphertext verification failed 

### ISSUE THREAD

**Issue by hibohra1398** [restic/restic#4848]
Output of `restic version`
--------------------------
restic 0.16.4

What backend/service did you use to store the repository?
---------------------------------------------------------
We are using GCP bucket as backend to create backup for below services:
Mongodb, postgresql, zookeeper and Schema Registry dump

Problem description / Steps to reproduce
----------------------------------------
We are facing issue with restic backup wherein 2 of our repositories have been corrupted leading us to not access  backup snapshots and also we are not able to access existing snapshots.

This is not reproducible and we ourselves are facing this issue with 2 of our backup jobs mongodb backup and schema registry backup.

We are using gcs bucket as our repository and running restic as a kubernetes cronjobs.

Exception:
```
open repository
lock repository
load index files
ciphertext verification failed
github.com/restic/restic/internal/crypto.init
	/restic/internal/crypto/crypto.go:30
runtime.doInit1
	/usr/local/go/src/runtime/proc.go:6740
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6707
runtime.main
	/usr/local/go/src/runtime/proc.go:249
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650
```

Steps tried to recover:
```

restic snapshots ls -r 
Ignoring "<id>": failed to load snapshot <id>: ciphertext verification failed
Ignoring "<id>": failed to load snapshot <id>: ciphertext verification failed
Ignoring "<id>": failed to load snapshot <id>: ciphertext verification failed
Ignoring "<id>": failed to load snapshot <id>: ciphertext verification failed
Ignoring "<id>": failed to load snapshot <id>: ciphertext verification failed
Ignoring "<id>": failed to load snapshot <id>: ciphertext verification failed
Ignoring "<id>": failed to load snapshot <id>: ciphertext verification failed



restic unlock --remove-all -r gs:<gcs-bucket-name>:/<foldername>/schema-registry 
enter password for repository:
repository 7400edb4 opened (version 2, compression level auto)

╰─ restic check --read-data -r gs:<gcs-bucket-name>:/<foldername>/schema-registry  
using temporary cache in /var/folders/l2/<id>/T/restic-check-cache-<>
enter password for repository:
repository <repo> opened (version 2, compression level auto)
created new cache in /var/folders/l2/<indexId>/T/restic-check-cach<id>
create exclusive lock for repository
load indexes
[0:44] 100.00%  463 / 463 index files loaded
error: error loading index <indexId>: ciphertext verification failed
error: error loading index <indexId>: ciphertext verification failed
error: error loading index <indexId>: ciphertext verification failed
....
....
Fatal: LoadIndex returned errors


Tried:
restic repair index --read-all-packs -r gs:<gcs-bucket-name>:/<foldername>/schema-registry 

Command worked but still was not able to get restic snapshots list or push a new snapshot
```

Documentation and Issues Checked:
https://restic.readthedocs.io/en/latest/077_troubleshooting.html#find-out-what-is-damaged
https://forum.restic.net/t/help-with-fatal-load-index-invalid-data-returned/4147/2
https://github.com/restic/restic/issues/4168

Expected behavior
-----------------
Restic should not get corrupted and we should be able to access existing snapshots and take new snapshots

Actual behavior
---------------
Currently restic is blocked and we are not able to take backup

Do you have any idea what may have caused this?
-----------------------------------------------
Went through docs and older issues not able to investigate the issue as the same thing work for other backups

Please help and we are not able to build confidence into using this in production

**Comment by MichaelEischer** [comment]
When were the `config` file and any file in the `keys` folder of the repository last modified? Were there any errors right before the errors started to show up? Did the automation for some reason call the `init` command of restic?

The errors look like the used key file does not match the key used to encrypt the repository content. That is somewhat similar to https://github.com/restic/restic/issues/4832 , but you're using the GCS backend so there could be a separate problem.

**Comment by hibohra1398** [comment]
We had initialized the repo on 27th May 2024 for rest of our backups out of postgresql, zookeeper, schema-registry, mongodb i see that the key was changed for mongodb and schema-registry back up on  Jun 3, 2024


We use below code to check if we want to initialize the backup or not
```
                  # Init the backup Dir
                  {{- if .Values.restic.enabled}}
                  if restic snapshots >/dev/null 2>&1; then
                  echo "restic repo exists"
                  else
                  restic init
                  fi
                  {{- else }}
                  mkdir -p {{.Values.defaultBackupDir}}
                  {{- end}}
```

We have one job calling one gcs bucket path so there is no way any other job would initialise the repo or use it.

I also tried to restore by using repair index and unlock option but no luck

**Comment by MichaelEischer** [comment]
> if restic snapshots >/dev/null 2>&1; then

That logic is unreliable as it cannot distinguish between a non-existent repository and problems with the backend communication. But even in the latter case, `restic init` wouldn't reinitialize a repository, unless the backend claimed that it does not contain a `config` file. Do you have the output generated by the `init` command runs on Jun 3, 2024?

> i see that the key was changed

What exactly do you mean with that? Initializing a repository a second time generates a second key in the `keys` folder, but does not modify the old one. 

> I also tried to restore by using repair index and unlock option but no luck

This cannot work as the used key no longer matches the key used to encrypt the older data.

Does the old key files still exist and are you able to retrieve an old copy of the `config` file? If yes, then you can repair the repository by reverting the `config` file and removing the new key file.

If you only have the old key file, then it would be possible to create a new fake config file that allows accessing the data in the backup again. However, deduplication would likely suffer in future snapshots. Creating a fake config file require some experimental code, so I'd only recommend going down that road if really necessary.

If you do not have the old key file, then the repository is permanently inaccessible.

**Comment by hibohra1398** [comment]
Thanks for your reply!

Unfortunately i didn't had log for the job I mentioned above but there was same job in another env which started failing today. I saw that new key was generated. 



```
+ set -e
+ cd /tmp
+ suffix=<>
+ postgresDir=postgresql-backup
+ restic snapshots
+ restic init
created restic repository <> at gs:<bucket>:/<folder>

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
+ echo ''
+ echo 'running postgresql dump'

running postgresql dump
+ pg_dump -h postgresql -U postgres -F c -b -v -f  <>  <>
<pg_dump details.........removed these lines.......>
+ rm -rf postgresql-backup.tgz
+ doBackup postgresql-backup.tgz
+ bkpFile=postgresql-backup.tgz
+ cat postgresql-backup.tgz
+ restic --verbose backup --stdin --stdin-filename postgresql-backup.tgz -g paths
open repository
lock repository
load index files
ciphertext verification failed
github.com/restic/restic/internal/crypto.init
	/restic/internal/crypto/crypto.go:30
runtime.doInit1
	/usr/local/go/src/runtime/proc.go:6740
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6707
runtime.main
	/usr/local/go/src/runtime/proc.go:249
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1650
+ finish
```

No we don't have older config/key. Also one of the reason i see this being a issue is below:
![image](https://github.com/restic/restic/assets/113414131/5f537fe3-c552-4226-ae26-30ed36f02ba9)

But not quite sure as I see that restic key is replaced and a new key is added so if I am not wrong it reinitialised it but then in the end not sure why we ended up with ciphertext verification failed error


Can you recommend another command to verify existence of the repository instead of listing snapshots ?

**Comment by MichaelEischer** [comment]
> No we don't have older config/key. Also one of the reason i see this being a issue is below:

That lifecycle rule is the reason for the broken repositories. The config and keys files are only created when initializing a repository and do not change over the lifetime of a repository (unless you explicitly tell restic to modify the keys / upgrade the repo format).

You must remove the lifecycle rule; it's effectively deleting random files from the repository, no wonder that it is broken. After that you'll have to create new repositories.

> a new key is added so if I am not wrong it reinitialised it but then in the end not sure why we ended up with ciphertext verification failed error

The password that you pass to restic is used to decrypt the key file, which contains the actual master password used to encrypt data. Initializing a repository a second time will result in a new master password, which cannot decrypt already existing data.

> Can you recommend another command to verify existence of the repository instead of listing snapshots ?

There's currently no perfectly well suited command, but take a look at https://restic.readthedocs.io/en/stable/075_scripting.html#check-if-a-repository-is-already-initialized .

The `init` command already includes a check that there's not yet a repository, which makes that above construction safe enough.
