### ISSUE TITLE
restic prune failure: Data seems to be missing

### ISSUE THREAD

**Issue by systemdlete** [restic/restic#4857]
Output of `restic version`
--------------------------
repository 63297c70 opened (version 1)
loading indexes...
[0:05] 100.00%  15 / 15 index files loaded
loading all snapshots...
finding data that is still in use for 1547 snapshots
[6:35] 100.00%  1547 / 1547 snapshots
searching used packs...
{<data/96d53402> <data/c8828bff> <data/a5f6b1a0> <data/e032b91b> <data/43fbbd6f> <data/85c23477> <data/3b4d1ef9> <data/20beeec3> <data/c65fd535> <data/c446b584> (222 more)} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
Fatal: index is not complete

What backend/service did you use to store the repository?
---------------------------------------------------------
Repo is stored on mega.nz cloud storage, using mega-sync.   The repo is currently sync'd to the mega cloud servers.

Problem description / Steps to reproduce
----------------------------------------
Experienced a failure with backup (first time ever since using restic).
Ran restic check, which reported an unreferenced pack, followed by numerous unreferenced files.
Ran restic repair index, which ran to successful end
Ran restic snapshots, and got a ton of errors.
So I thought the thing to do is run that prune, as suggested, to get rid of the offending item.
But prune struggled to get through the entire process, ultimately failing with an out of disk space error.

(The /tmp space runs out pretty quickly; few programs I use exhaust tmp space, even after many weeks of uptime.  It might be a good idea to detect this and suggest an alternative way to do this, such as setting an envar to an alternate location where there is more space, and maybe an estimate of needed space, though I am sure that is not an easy thing to do.   Alternatively, maybe there is a means by which the pruning or repairing could perform their work incrementally somehow)

Expected behavior
-----------------
Continued successful backups, as I have enjoyed for several months since replacing my old backup tool with restic.  I had not experienced any serious issues until now.

Actual behavior
---------------
Suddenly failure to backup after months of success with restic.

Do you have any idea what may have caused this?
-----------------------------------------------
I have not taken good care of my restic repo, such as running regular checks and repairs in a timely manner.
There was a hard disk failure a couple of months back, but the system is RAID'd and the drive has since been replaced.
System has been rebooted several times, which includes a mandatory fsck upon every boot (tune2fs -c 1).
In addition, my PCs are on UPS, to avoid power spikes and drops, which can damage data.

There could have been some network connectivity outages, periodically, due to my own network configuration changes. I mention this only to point out that perhaps mega.nz missed a beat somehow during these outages.  OTOH, I am not observing errors from mega, which I am pretty sure is reliable--the last time mega.nz failed me was many years ago.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I LOVE restic.  It is simple, clean, very fast, extremely scriptable and easily configurable, and easy to use.   I admit I don't get into the weeds of restic, but from my POV, it is easy to understand as an API.

**Comment by systemdlete** [comment]
So I've tried repairing and pruning and checking a few times now, but the repo still seems to be corrupted.

Not sure what to do at this point.   For now, I will probably just start a new repo, and run regular maintenance on it this time to avoid another messed up repo.  Please advise.

**Comment by MichaelEischer** [comment]
> Ran restic check, which reported an unreferenced pack, followed by numerous unreferenced files.

Please provide a few samples of those error messages if you still have them. `unreferenced packs` probably correspond to the `not referenced in any index` error messages. However, `unreferenced files` doesn't exist. The most similar error message is related to missing blobs for certain files. That would mean that the repository was already damaged at that point and that `prune` is only the bearer of bad news.

> So I thought the thing to do is run that prune, as suggested, to get rid of the offending item.
> But prune struggled to get through the entire process, ultimately failing with an out of disk space error.

`prune` refuses to work if a repository is damaged in order to not make things worse. `prune` and the other commands are also designed to allow interruptions at arbitrary points in time without damaging the repository. That also includes cases where restic fails to write its temp files as that causes the current command to just fail and exit.

Do you still have the error message? How much free space does exist in /tmp ? 

> Repo is stored on mega.nz cloud storage, using mega-sync. The repo is currently sync'd to the mega cloud servers.

Does that mean that there's a local copy of the repository and a copy in the cloud? If yes, then I'd expect mega-sync to eventually upload all files even if it missed some at first. Judging from the information provided, my guess would be that the repository damaged is caused by some missing pack files. Restic requests that a filesystem writes data in the repository to disk before continuing, such that a power loss shouldn't have any negative consequences.

On which filesystem is the repository stored? Did hard disk failure cause any further damage except having to rebuild the raid?

> There could have been some network connectivity outages, periodically, due to my own network configuration changes. I mention this only to point out that perhaps mega.nz missed a beat somehow during these outages.

You could use the rclone backend of restic to directly upload files to mega.

> repository 63297c70 opened (version 1)

That is not the output for `restic version`. All that message tells me is that you're using restic >= 0.14.0.

> Not sure what to do at this point. For now, I will probably just start a new repo, and run regular maintenance on it this time to avoid another messed up repo. Please advise.

Please give us a bit of time to reply, this is a spare time project. To repair the repository follow the steps at https://restic.readthedocs.io/en/stable/077_troubleshooting.html .

**Comment by systemdlete** [comment]
Here, I will save you LOTS of time, Michael.  Thank you for your prompt reply.  

I think this might be on my side after all.   It seems that my mega account overflowed--I went over my limit.  Which, in turn, put the brakes on additional uploads, which means that anything trying to write to the mounted mega.nz drive will likely fail, and then... well, I think you can picture the rest of this scenario.

It turns out that I hadn't REALLY overrun my limit; it was simply that I need to clean up a LOT of trash; mega.nz leaves a lot of artifacts of its work behind and needs to be cleaned out periodically.  I have cleaned out those files and now my mega.nz account is active again and syncing.

With regard to running out of space with the repair functions, I have discovered that running restic repair --no-cache seems to address that problem.  It warns me that it will take longer, but I don't mind; these types of operations can be performed at off-times when the restic repo server is not busy.   I stumbled across it while browsing the options in restic manpage.

I ran check with no errors.  Then I ran repairs again, and waiting for check to finish.  If check finishes cleanly again, I'll try the prune again.   I am still seeing the unreferenced objects in the index at this point.

**Comment by systemdlete** [comment]
Unfortunately, check did not exit cleanly.

Sorry for the mess-up which I might have avoided if I had just kept up with mega.nz maintenance.  If there is no hope for the old repo, then I'll just move on with the new one.   The old repo still seems to be able to list and browse its snapshots, so I can still use it for restores.

Thank you for providing this great little backup tool and support.

**Comment by MichaelEischer** [comment]
> Which, in turn, put the brakes on additional uploads, which means that anything trying to write to the mounted mega.nz drive will likely fail, and then... well, I think you can picture the rest of this scenario.

When using the rclone backend to directly upload to mega, then restic would learn about the failed upload and just abort the whole backup. That would then leave the repository in a working state.

> restic repair --no-cache

I think you mean `restic prune --no-cache`? No other command warns about not using a cache. `--no-cache` normally doesn't change how much data is written to `/tmp`, unless you've changed the cache directory used by restic. `prune` by default only writes a few temporary files to `/tmp` (a few hundred MBs at most).

**Comment by MichaelEischer** [comment]
Is there anything left to do here?
