### ISSUE TITLE
Backing up C:\mydir\mydata, unable to create \\?\C\Users\...\mydir (Windows)

### ISSUE THREAD

**Issue by mchvs** [restic/restic#4865]
Output of `restic version`
--------------------------
restic 0.16.4-dev (compiled manually) compiled with go1.22.4 on windows/amd64
(commit 5cff6e084e28c5d8fcff65cf344977df36575db3)

What backend/service did you use to store the repository?
---------------------------------------------------------
Local NTFS filesystem under Windows 10 version 22H2 19045.4529.

Problem description / Steps to reproduce
----------------------------------------
Run `git bisect` and found commit 5cff6e084e28c5d8fcff65cf344977df36575db3 to be the first to give the error.

Compile this commit for Windows and run:

```
C:\>mkdir \mydir\mydata

C:\>restic --repo \mydir\myrepo init
...
created restic repository 19264c58 at \mydir\myrepo

C:\>restic --repo \mydir\myrepo backup \mydir\mydata
...
repository  opened (version 2, compression level auto)
no parent snapshot found, will read all files
[0:00] 0 index files loaded
Fatal: unable to save snapshot: CreateFile \\?\C:\Users\<myname>\mydir: The system cannot find the file specified.
```

Expected behavior
-----------------
Restic should locate the repository under C:\mydir\ .

Actual behavior
---------------
Restic tries to locate the repository under C:\Users\ instead of C:\mydir\ .

Do you have any idea what may have caused this?
-----------------------------------------------
No, unfortunately.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes! Every single day! :) Restic is the best. If this report helps to make it even better, I'm happy to help!

**Comment by MichaelEischer** [comment]
> Fatal: unable to save snapshot: CreateFile \\?\C:\Users\<myname>\mydir: The system cannot find the file specified.

That _exact_ error already occurs in resitc 0.16.4 and older. You've sort of rediscovered https://github.com/restic/restic/issues/2076 .

While trying to reproduce the issue, I found an different issue caused by the xattr change that caused `restic --repo \mydir\myrepo backup c:\mydir\mydata` (notice the `c:`) to fail. See https://github.com/restic/restic/pull/4866

**Comment by mchvs** [comment]
Interesting. Most likely I mixed both problems when trying to figure out what was wrong.

**Comment by mchvs** [comment]
I can not reproduce the error, either using \mydir\mydata or c:\mydir\mydata after https://github.com/restic/restic/pull/4866 was merged.

Great work, as always!
