### ISSUE TITLE
A new patch tag in 0.16 series with dependencies update

### ISSUE THREAD

**Issue by hairyhum** [restic/restic#4873]
Output of `restic version`
--------------------------

0.16.4

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

We currently detect a bunch of upstream vulnerabilities in the released restic version: 
GHSA-m5vv-6r4h-3vj9
GHSA-4v7x-pqxf-cx7m
GHSA-8r3f-844c-mc37

These should be addressed by updating the upstream dependencies, but there was no release tag since `0.16.4` and we don't know if current `master` is stable and compatible enough to build from it instead.

Would it be possible to tag a new patch version for `0.16` series?

What are you trying to do? What problem would this solve?
---------------------------------------------------------

We're packaging restic as a part of kanister release and trying to keep it clean from vulnerabilities as much as possible.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
Let's go for a patch release. There are too many changes queued on `master` to rush them out. The code can be considered stable, but will still require a few more changes before we can release it as restic 0.17.0.

**Comment by MichaelEischer** [comment]
Restic 0.16.5 has been released with updated dependencies: https://github.com/restic/restic/releases/tag/v0.16.5
