### ISSUE TITLE
failed to create snapshot for [c:\]: VSS error: async operation failed: VSS_E_INSUFFICIENT_STORAGE (0x8004231f)

### ISSUE THREAD

**Issue by mkatsevVR** [restic/restic#4875]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
sftp

Problem description / Steps to reproduce
----------------------------------------

Using restic on Windows 10 with --use-fs-snapshot worked fine for years but suddenly started failing with the error in the title. There's plenty of space on the drive (less than 50% used) and as a test, creating a shadow copy with `wmic shadowcopy call create Volume='C:\'` worked fine.
The issue went away after a reboot, but then started again a couple of days later. Once it started happening, nothing worked other than a reboot (tried deleting existing shadows with `vssadmin`, cleaning up more disk space, etc.

Expected behavior
-----------------
Backup works

Actual behavior
---------------
VSS snadshot fails, resulting in a number of "The process cannot access the file because it is being used by another process" errors.

Do you have any idea what may have caused this?
-----------------------------------------------
No, it just started on its own last week.

**Comment by MichaelEischer** [comment]
Judging from a quick search the error code indicates that creating the snapshot would require more storage than VSS is allowed to use. If I remember correctly, that is a parameter different from the amount of free space on disk.

I don't know particularly much about VSS, maybe someone else can help?

**Comment by deajan** [comment]
Sorry to respond really late.
What does `wmic shadowcopy` say ? If it does list already present VSS snapshots, you could delete them with `wmic shadowcopy delete`.

Also, you can have a look at `sysdm.cpl` where in `system protection` you can set the maximum size VSS is allowed to use on disk:
![image](https://github.com/user-attachments/assets/e57b8287-1386-4570-b5d9-8966a3b7d54f)

**Comment by mkatsevVR** [comment]
After a few reboots the problem went away and hasn't happened since

**Comment by MichaelEischer** [comment]
The let's close this issue for now. Feel free to reopen it if the problem shows up again.
