### ISSUE TITLE
Meta backup/restoration.

### ISSUE THREAD

**Issue by 443eb9** [restic/restic#4877]
Output of `restic version`
--------------------------

0.16.4

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Backup/Restore meta, like date modified, and date created, etc.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

None

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, it allows me to backup files much more easier and faster. But it's a pity that restic can't store meta.

**Comment by MichaelEischer** [comment]
Please properly fill out the issue template and reopen the issue afterwards. There's no information at all what operating system you're using and what commands you've run, so it's not possible to investigate this issue. Restic already supports restoring file modification times.
