### ISSUE TITLE
unable to create cache directory , disabling cache: mkdir : no such file or directory

### ISSUE THREAD

**Issue by mchvs** [restic/restic#4880]
Output of `restic version`
--------------------------
restic 0.16.4-dev (compiled manually) compiled with go1.22.4 on linux/arm64
(compiled after checking out https://github.com/restic/restic/pull/4805/commits/0271bb97f8dcab28eff41153d6c80093c9316582)

What backend/service did you use to store the repository?
---------------------------------------------------------
Local ext4 filesystem.

Problem description / Steps to reproduce
----------------------------------------
Using the default restic cache dir:
```
$ ./restic -r backup/ check
unable to create cache directory , disabling cache: mkdir : no such file or directory
create exclusive lock for repository
repository c76ce5ae opened (version 2, compression level auto)
load indexes
[0:00] 100.00%  1 / 1 index files loaded
check all packs
check snapshots, trees and blobs
[0:00] 100.00%  11 / 11 snapshots
no errors were found
```

- I get this error in the master branch after checking out https://github.com/restic/restic/pull/4805/commits/0271bb97f8dcab28eff41153d6c80093c9316582
- I can not reproduce the error if I force a `--cache-dir`
- It seems to be irrelevant if the default cache dir exists or not.
- I don't see any permission issue with my default cache dir at `~/.cache/restic/`

Expected behavior
-----------------
The default cache dir must be used as usual.

Actual behavior
---------------
I'm getting the `unable to create cache directory , disabling cache: mkdir : no such file or directory` error message.

Do you have any idea what may have caused this?
-----------------------------------------------
- It seems to be related to the fix for https://github.com/restic/restic/issues/4437
- Maybe `cachedir` is empty when `os.MkdirAll()` [is called](https://github.com/restic/restic/commit/0271bb97f8dcab28eff41153d6c80093c9316582?diff=split&w=0#diff-efd94e38c190ad55029b381d903f2758124d8ccec01a8f3892d439afd835eec3R176)?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes! I've been using restic for maybe 2.5 years now and I'm very happy with it. I hope that this report helps the next release to be even better than the current one.

**Comment by MichaelEischer** [comment]
Thanks for the bug report. This will be fixed by https://github.com/restic/restic/pull/4883 .
