### ISSUE TITLE
Decide license

### ISSUE THREAD

**Issue by fd0** [restic/restic#49]
khepri is currently licensed as 2-clause-BSD, stay with it or change to GPL?

**Comment by fw42** [comment]
Why are you considering GPL? What's wrong with BSD?

**Comment by fd0** [comment]
Just some thoughts for now: Up to now I've released all code as GPL, I have to admit that I like the viral aspect of it. However, most code in the Go universe is BSD, so in order to avoid having to figure out ugly licensing clashes, I've decided to use BSD for restic. I'm just a bit worried that somebody else might take restic, make a product and raise a ton of money for it. But that's probably unjustified.

I like that the BSD license is more free in terms of code-reuse.

**Comment by fd0** [comment]
We'll stick with BSD.
