### ISSUE TITLE
rewrite copies "Size" metadata instead of recalculating it if files have been excluded

### ISSUE THREAD

**Issue by CommanderRoot** [restic/restic#4902]
Output of `restic version`
--------------------------
restic 0.16.5-dev (compiled manually) compiled with go1.22.0 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
local

Problem description / Steps to reproduce
----------------------------------------
I used `restic rewrite` to exclude some folders / files from a few existing snapshots

Expected behavior
-----------------
If files / folders get excluded in a rewrite then restic should recalculate the "Size" value which it displays when using `restic snapshots`

Actual behavior
---------------
Restic just copies the "Size" metadata which results in both the original and the rewritten snapshot displayed with the same size

Do you have any idea what may have caused this?
-----------------------------------------------
I haven't looked at the code but my guess would be that this "step" was simply forgotton as no other metadata is changed (except if you ask it to)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
restic is great and I use it for server backups as well as dekstop pc backups

**Comment by alex-kattathra-johnson** [comment]
I can take a look at this.

**Comment by alex-kattathra-johnson** [comment]
@CommanderRoot: I think the `prune` command is where the data from the snapshots are cleaned up. Try this workflow, `backup` -> `rewrite` with `--forget` flag -> prune.

**Comment by CommanderRoot** [comment]
I'm not talking about the used disk storage but rather the reported snapshot size when using `restic snapshots`. I'm aware that the forgotten files are only removed on `prune` if there is no snapshot left which contains them.

**Comment by alex-kattathra-johnson** [comment]
Sorry, I'm a noob here looking to get my hands dirty with contributing to the project. I've created a preliminary PR to make the change. Updated outputs after the change:
```
 ~/Projects/restic  issue-4902  0m  ./restic --insecure-no-password --repo /tmp/backup backup ~/Projects/sampledata                                        
repository d489fcd0 opened (version 2, compression level auto)
created new cache in /home/ajohnson/.cache/restic
no parent snapshot found, will read all files
[0:00]          0 index files loaded

Files:           2 new,     0 changed,     0 unmodified
Dirs:            4 new,     0 changed,     0 unmodified
Added to the repository: 6.000 GiB (6.001 GiB stored)

processed 2 files, 6.000 GiB in 1:00
snapshot e6a08c5d saved
 ~/Projects/restic  issue-4902  0m  ./restic snapshots --insecure-no-password --repo /tmp/backup                                                           
repository d489fcd0 opened (version 2, compression level auto)
ID        Time                 Host         Tags        Paths                               Size
-----------------------------------------------------------------------------------------------------
e6a08c5d  2024-07-06 08:51:21  alex-laptop              /home/ajohnson/Projects/sampledata  6.000 GiB
-----------------------------------------------------------------------------------------------------
1 snapshots
 ~/Projects/restic  issue-4902  0m  ./restic rewrite --exclude "5G*" --insecure-no-password --repo /tmp/backup --forget                                    
create exclusive lock for repository
repository d489fcd0 opened (version 2, compression level auto)
[0:00] 100.00%  1 / 1 index files loaded

snapshot e6a08c5d of [/home/ajohnson/Projects/sampledata] at 2024-07-06 08:51:21.834438527 -0500 CDT by ajohnson@alex-laptop
excluding /home/ajohnson/Projects/sampledata/5G_sample.txt
saved new snapshot 83d54eb9
removed old snapshot e6a08c5d

modified 1 snapshots
 ~/Projects/restic  issue-4902  0m  ./restic snapshots --insecure-no-password --repo /tmp/backup                                                           
repository d489fcd0 opened (version 2, compression level auto)
ID        Time                 Host         Tags        Paths                               Size
-----------------------------------------------------------------------------------------------------
83d54eb9  2024-07-06 08:51:21  alex-laptop              /home/ajohnson/Projects/sampledata  1.000 GiB
-----------------------------------------------------------------------------------------------------
1 snapshots
```

**Comment by akrabu** [comment]
I had actually come here to post an issue / feature request to see if the snapshot size could be computed when running rewrite, as a way to "upgrade" old snapshots - but I saw this issue and realized if the size was recomputed for rewritten new snapshots, there's no reason why it wouldn't be recomputed for old rewritten snapshots as well, I would think.  So yes, computation of snapshot size during a `rewrite` would be a great feature.  Thanks!
