### ISSUE TITLE
--copy-chunker-params in documentation but no longer available

### ISSUE THREAD

**Issue by rmmonster** [restic/restic#4915]
Output of `restic version`
--------------------------

restic 0.16.5 (v0.16.5-0-gfe9f142b5) compiled with go1.22.4 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------

n/a

Problem description / Steps to reproduce
----------------------------------------

[the documentation suggests to use --copy-chunker-params during copy, which isn't available in 0.16.5](https://restic.readthedocs.io/en/stable/045_working_with_repos.html#ensuring-deduplication-for-copied-snapshots)

`restic -r /srv/restic-repo-copy init --from-repo /srv/restic-repo --copy-chunker-params`

Expected behavior
-----------------

either
`restic -r /srv/restic-repo-copy init --from-repo /srv/restic-repo --copy-chunker-params`
works or it should be removed from the documentation

Actual behavior
---------------

unknown flag: --copy-chunker-params

`--copy-chunker-params` is not listed in `restic help copy`

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes 💓

**Comment by MichaelEischer** [comment]
I've just tested 0.16.5 and the latest master version and the following command works perfectly fine: `./restic -r newrepo init --from-repo testrepo --copy-chunker-params`. We haven't changed anything about `--copy-chunker-params` since 0.16.5.

It looks like you're running an old version of restic.

> `--copy-chunker-params` is not listed in `restic help copy`

I assume you meant `restic help init`?

**Comment by rmmonster** [comment]
It was indeed a misunderstanding on my part. I apparently read about half the doc and assumed the rest.
