### ISSUE TITLE
ls --ncdu broken for relative paths

### ISSUE THREAD

**Issue by mchvs** [restic/restic#4919]
Output of `restic version`
--------------------------
restic 0.16.5-dev (v0.16.5-841-g1328cdd00) compiled with go1.22.4 on linux/arm64

What backend/service did you use to store the repository?
---------------------------------------------------------
local filesystem

Problem description / Steps to reproduce
----------------------------------------
Can't run `restic ls --ncdu` on some backups of relative paths.

Starting at one directory above the restic source code:
```
$ restic --repo /tmp/myrepo --insecure-no-password init
...
$ restic --repo /tmp/myrepo --insecure-no-password backup restic/
...
$ restic --repo /tmp/myrepo --insecure-no-password ls latest --ncdu | ncdu -f -
```

The `ncdu` output is shown as expected, but...
```
$ cd restic
...
$ restic --repo /tmp/myrepo --insecure-no-password backup .
...
$ restic --repo /tmp/myrepo --insecure-no-password ls latest --ncdu | ncdu -f -
```

Results in:
```
Error: could not open .git
  Line 412 byte 3: Expected ']'
```

Expected behavior
-----------------
`restic ls --ncdu` creating the correct input for `ncdu`.

Actual behavior
---------------
Unfortunatelly, the input to `ncdu` sometimes is broken.

Do you have any idea what may have caused this?
-----------------------------------------------
No, unfortunately.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes! Always!

**Comment by MichaelEischer** [comment]
Thanks for the bug report. I think I've found the problem, can you give #4920 a try? Apparently, every snapshot with more than one element in the snapshot's root tree was printed incorrectly. That is, a snapshot created using `restic backup /` was also be printed incorrectly by `ls --ncdu`.

**Comment by mchvs** [comment]
Unfortunately I'm getting a different error now, both for `restic backup restic/` and `restic backup .`. The output of the first one is:

```
Error: could not open -
   Line 1 byte 682: No name field present in item information object
```

Line 682 of `restic ls --ncdu` reads:

`{"name":"issue-4549","asize":499,"dsize":512,"dev":2049,"ino":563929,"nlink":1,"notreg":false,"uid":1001,"gid":1001,"mode":436,"mtime":1720818389},`

The output of `restic version` is:

`restic 0.16.5-dev (v0.9.5-4005-g9f6606523) compiled with go1.22.4 on linux/arm64`

**Comment by MichaelEischer** [comment]
> Error: could not open -
>    Line 1 byte 682: No name field present in item information object

I guess I know, what's the problem. There's now a new tiny commit that use "/" as name for the toplevel directory.

Btw, which ncdu version are you using? I have ncdu 2.4 on my system and it seems to be much more forgiving than what you're using. With the latest commit, now also ncdu 1.15 seems to accept the input data.

**Comment by mchvs** [comment]
Good catch! I tested with all my repositories and it worked fine for all of them now.

```
$ ./restic version
restic 0.16.5-dev (v0.9.5-4006-gff9238ebf) compiled with go1.22.4 on linux/arm64

$ ncdu --version
ncdu 1.15.1
```

Thank you!
