### ISSUE TITLE
syncany could be a good inspiration software: plugins!!!

### ISSUE THREAD

**Issue by cocodrino** [restic/restic#492]
Hi guys, It's not a criticized and neither I'm saying than syncany is better than restic, I prefer restic because it doesn't depend of java and it is simple tfor install and use, but syncany has a really cool plugins system which can be used for extend the software and provide other transference protocols or storage service, like ftp, webdav,amazon,dropbox,samba...it's really great...even they've a web interface plugin

http://syncany.readthedocs.org/en/latest/plugins.html#web-interface-plugins

would be nice see something similar for restic..what do you think???...thanks guys and keep the good job..

**Comment by fd0** [comment]
Thanks for the hint, at least I did not know the software before. Since restic is a very new project (syncany has been worked on for several years), we haven't yet planned any plugin system. We'll keep it in mind.
