### ISSUE TITLE
Verification error after in-place restore with restic_v0.16.5-869-g4f4598a1e_linux_amd64

### ISSUE THREAD

**Issue by damoclark** [restic/restic#4923]
Output of `restic version`
--------------------------
restic 0.16.5-dev (compiled manually) compiled with go1.22.0 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
Local filesystem

Problem description / Steps to reproduce
----------------------------------------
Verify after restore is generating size mismatch errors:

```bash
xxx@xxx:/tmp$ sudo ./restic_v0.16.5-869-g4f4598a1e_linux_amd64 restore --key-hint=xxx --password-file=xxx --repo=/path/to/local/repo -t /mnt/temp/rootfs/ --delete --sparse --verify --overwrite if-changed --host xxx --path / latest
```

Output:

```bash

repository xxx opened (version 2, compression level auto)
[0:21] 100.00%  95 / 95 index files loaded
restoring snapshot xxx of [/] at 2024-07-17 02:00:44.976448849 +1000 AEST by xxx@xxx to /mnt/temp/rootfs/
Summary: Restored 125299 files/dirs (12.362 GiB) in 6:45, skipped 165521 files/dirs 6.086 GiB
verifying files in /mnt/temp/rootfs/
ignoring error for /mnt/temp/rootfs/etc/passwd: Invalid file size for /mnt/temp/rootfs/etc/passwd: expected 2835, got 2938
ignoring error for /mnt/temp/rootfs/usr/share/distro-info/ubuntu.csv: Invalid file size for /mnt/temp/rootfs/usr/share/distro-info/ubuntu.csv: expected 2667, got 2731
Fatal: There were 2 errors

xxx@xxx:/tmp$ echo $?
1
```

Steps taken
------------
1. I initially restored a root filesystem for host A to `/mnt/temp/rootfs`
2. Then I performed the above restore but for a root filesystem for a different host, host B, but same distribution into the same path
3. I expected restic to update `/mnt/temp/rootfs` so that it exactly matches the restic snapshot for host B

I checked the size of `/mnt/temp/rootfs/etc/passwd` on disk and it reports 2938.  

```
ls -l /mnt/temp/rootfs/etc/passwd
-rw-r--r-- 1 root root 2938 Mar 30 12:54 /mnt/temp/rootfs/etc/passwd
```

While checking the restic snapshot using restic `ls` command gives 2835:

```
./restic_v0.16.5-869-g4f4598a1e_linux_amd64 ls --key-hint=xxx --password-file=xxx --repo=xxx -l --path / --host xxx latest /etc/passwd
repository xxx opened (version 2, compression level auto)
[0:22] 100.00%  95 / 95 index files loaded
snapshot xxx of [/] filtered by [/etc/passwd] at 2024-07-17 02:00:44.976448849 +1000 AEST):
-rw-r--r--     0     0   2835 2024-03-30 12:54:11 /etc/passwd
```

Note, restic v0.16.5 gives same output.

When performing the same  checks for file /mnt/temp/rootfs/usr/share/distro-info/ubuntu.csv, the differences are consistent with the above. 

I re-ran the restore and replaced `--verify` with `--dry-run -vv` to see what it says is out of date.

It of course lists many unchanged files.  But the `ubuntu.csv` and `passwd` both show as `updated`.  

Thus, the verify output is correct, but the restore failed to correctly restore the files.

Furthermore, from the dry-run, there are many directories showing as `restored`, along with symlinks (shown 'with size 0 B').   Perhaps metadata? The handful I've checked exist.  Here is a snippet:

```
restored  /etc/dnsmasq.d
restored  /etc/dpkg/dpkg.cfg.d
restored  /etc/dpkg/origins/default with size 0 B
restored  /etc/dpkg/origins
restored  /etc/dpkg
restored  /etc/emacs/site-start.d
restored  /etc/emacs
restored  /etc/environment.d
restored  /etc/firefox/policies
restored  /etc/firefox/pref
restored  /etc/firefox
restored  /etc/fonts/conf.avail
restored  /etc/fonts/conf.d/10-antialias.conf with size 0 B
restored  /etc/fonts/conf.d/10-hinting-slight.conf with size 0 B
restored  /etc/fonts/conf.d/10-scale-bitmap-fonts.conf with size 0 B
restored  /etc/fonts/conf.d/11-lcdfilter-default.conf with size 0 B
```

Expected behavior
-----------------
The files on /mnt/temp/rootfs should exactly match what was stored in its restore snapshot

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I like to contribute where I can to help this project.  It's great software.

**Comment by MichaelEischer** [comment]
> ```shell
> ignoring error for /mnt/temp/rootfs/etc/passwd: Invalid file size for /mnt/temp/rootfs/etc/passwd: expected 2835, got 2938
> ignoring error for /mnt/temp/rootfs/usr/share/distro-info/ubuntu.csv: Invalid file size for /mnt/temp/rootfs/usr/share/distro-info/ubuntu.csv: expected 2667, got 2731
> ```

Is the content of those files garbled? In particular the last 50-100 bytes are relevant.

Just to be sure there's no weird problem in the repository: Please restore just those two files into an empty folder and check whether their file content is correct.

> Furthermore, from the dry-run, there are many directories showing as `restored`, along with symlinks (shown 'with size 0 B'). Perhaps metadata? The handful I've checked exist. Here is a snippet:

restore currently only verifies the content of files. All other file types are always considered as changed and are simply replaced. `with size 0 B` for symlinks is indeed a bit weird. I'll look into improving the dry-run output for those files.

**Comment by MichaelEischer** [comment]
I think I've found the problem: if all parts of the file that should be kept are already up to date, then currently the file is not truncated. That is the first 2835 bytes of `etc/passwd` are apparently already up to date. The only thing that's missing is truncating the file to that size.

I won't have time to fix that before saturday.

**Comment by damoclark** [comment]
> Is the content of those files garbled? In particular the last 50-100 bytes are relevant.

Nope, nothing garbled.

> I think I've found the problem: if all parts of the file that should be kept are already up to date, then currently the file is not truncated. That is the first 2835 bytes of `etc/passwd` are apparently already up to date. The only thing that's missing is truncating the file to that size.

Yes, this makes sense.  It is also likely much less common that a file reduces size, thus not revealing this issue previously.  

> 
> I won't have time to fix that before saturday.

No problem at all.  Just helping out with testing ahead of release.  

D.
