### ISSUE TITLE
Add backup from remote source

### ISSUE THREAD

**Issue by hdhog** [restic/restic#493]
HI, I would like to be able to make backups from remote servers.
example
```bash
restic -r ./myrepo backup sftp://root@123.123.123.123/folder
restic -r ./myrepo backup smb://root@123.123.123.123/folder
restic -r ./myrepo backup ftp://root@123.123.123.123/folder
```

**Comment by fd0** [comment]
Thanks for the suggestion. We've already discussed this use case in #299 and I'll close this issue as a duplicate. You can subscribe to #299 in order to get notified when this feature eventually gets implemented.
