### ISSUE TITLE
Cleanup removed snapshots from cache

### ISSUE THREAD

**Issue by MichaelEischer** [restic/restic#4934]
Output of `restic version`
--------------------------
0.16.5

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
When using a restic repository from multiple host, then after running `forget` on one of the hosts, the removed snapshots still exist in the cache of the other hosts. Restic should remove those snapshots from the cache of all hosts.

It would be sufficient, if for example the commands that list all snapshots, also automatically clean up the cache.
For that it might be possible to hook into the `List` function of a `Repository` to remove stale snapshots from the cache.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Keep the cache size small.

**Comment by konidev20** [comment]
Hey @MichaelEischer, 

There is a function in `repository.go` called `prepareCache()` which is used to clean up old index and pack files from the local cache. This method is called during `LoadIndex`.

I have made a draft change for this. We can discuss the relevant code change there.
