### ISSUE TITLE
Allow excluding files based on file attributes

### ISSUE THREAD

**Issue by m-wild** [restic/restic#4935]
Output of `restic version`
--------------------------

restic 0.16.4 compiled with go1.21.6 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

It should be possible to exclude files based on their attributes (e.g. `FILE_ATTRIBUTE_UNPINNED`).

This could be achieved with command line options using the Windows Explorer single-letter code or bitmask for example:

```
restic backup C:\Users\Example\OneDrive --exclude-attrs="U"

restic backup C:\Users\Example\OneDrive --exclude-attrs="0x100000"
```

Then implemented as a new function in exclude.go, something like (with appropriate handling for non-Windows):

```go
// assuming attrs are first converted into the uin32 representation somehow...
func rejectByAttrs(attrs uint32) (RejectFunc, error) {
    return func(item string, fi os.FileInfo) bool {
        fa := fi.Sys().(*syscall.Win32FileAttributeData).FileAttributes
        return attrs & fa != 0
    }
}
```

Not sure if this is applicable to non-Windows OS

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Backing up a local OneDrive folder using while OneDrive Files On-Demand feature (https://support.microsoft.com/en-us/office/save-disk-space-with-onedrive-files-on-demand-for-windows-0e6860d3-d9f3-4971-b321-7092438fb38e).

I would like to exclude files which are marked as "online-only files" in OneDrive as these can be incredibly slow to download, and could be too large for the disk (e.g. 1TB of OneDrive online files being downloaded to a 500GB disk).

**Comment by MichaelEischer** [comment]
Let's consolidate this into https://github.com/restic/restic/issues/3697 . I'm not sure it is useful to allow users to exclude files based on arbitrary attributes. Some way to exclude cloud files feels like it would be more suitable.
