### ISSUE TITLE
Error: lstat file name too long

### ISSUE THREAD

**Issue by starptr** [restic/restic#4940]
Output of `restic version`
--------------------------
```
restic 0.16.4 compiled with go1.22.1 on linux/amd64
```

What backend/service did you use to store the repository?
---------------------------------------------------------
Rclone with Storj using the S3 backend

Problem description / Steps to reproduce
----------------------------------------

```
GOMAXPROCS=1 RESTIC_COMPRESSION=off restic -r rclone:storjrepo:mybucket/foobackups -o rclone.args="serve restic --stdio --bwlimit 300M --tpslimit=10 --checkers=1" -o rclone.connections=2 --pack-size=128 backup ~/foo
```
This runs as expected for the most part. However, some files fail and prints out:
```
error: lstat /home/username/foo/bar/aFileNameSuchThatTheTotalLengthOfThisPathIs278CharsLong.mp4: file name too long
```

Expected behavior
-----------------

I expect the error message to not appear.

Actual behavior
---------------

The error message is produced.

Do you have any idea what may have caused this?
-----------------------------------------------

Probably some combination of a low PATH_MAX and restic, rclone, and/or storj not handling long filenames correctly.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yeah it mostly does the job, but this problem might be hard to fix especially because the path can't be any more flat than it currently is.

**Comment by MichaelEischer** [comment]
That's very odd. The error is entirely unrelated to rclone and storj as it occurs while restic simply tries to read the file.

Are you able to run `stat /home/username/foo/bar/aFileNameSuchThatTheTotalLengthOfThisPathIs278CharsLong.mp4` or `ls -ld /home/username/foo/bar/aFileNameSuchThatTheTotalLengthOfThisPathIs278CharsLong.mp4`? This looks very much like a limitation of your system. I don't see what restic could do about it.

**Comment by starptr** [comment]
Running `stat` results in a similar error about filename being too long. You are right, the system is in a strange state where it was somehow able to create this file even though I cannot even `touch` a file of similar filename length. I solved my situation by tweaking the tool that is generating these files with these filenames to truncate long filenames.
