### ISSUE TITLE
Fatal errors should be JSON formatted with --json

### ISSUE THREAD

**Issue by mikix** [restic/restic#4948]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.22.2 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Currently, fatal errors aren't JSON formatted if `--json` is provided. It would be nice if it did surface that in a more programmatically-detectable way.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Fatal errors can be detected by scanning for lines that start with `Fatal:` but still... it'd make me feel safer if I could instead scan for a JSON blob with `"message_type": "fatal_error"` though.

This would be especially handy if Restic ever wants to add more metadata to the error (like requested in #4947)

Open Questions
------------------------
- What should the `message_type` be? I could see an argument for `fatal_error` but I could also see an argument for just `error` (also used for per-file errors in backup/restore commands) with either a null path or a flag like "is_fatal: true`.
- Should we keep printing the `Fatal:` freeform string to the console, to ease the transition for folks like me that are already looking for and parsing such lines?

I'm happy to work on a PR for this, if I could get some pre-guidance on the open questions. Thanks!

**Comment by MichaelEischer** [comment]
Related to https://github.com/restic/restic/issues/1804 .

> * Should we keep printing the `Fatal:` freeform string to the console, to ease the transition for folks like me that are already looking for and parsing such lines?

In which context exactly? Are you only referring to the output when using the `--json` option? Ideally we'd stop printing non-JSON messages to stderr altogether. At some point, we have to remove all non-JSON messages from stderr so I'm not sure how useful it would be to have both message types (a program would have to first check for JSON output and only afterwards fall back to the free form string parsing). We could also use feature flags to make the (partial) stderr JSON output an opt-in feature while we're working on it.

A word of warning: not every error that causes restic to exit with a non-zero exit code is a fatal error. The error types can be quite inconsistent depending on the command.

> * What should the `message_type` be? I could see an argument for `fatal_error` but I could also see an argument for just `error` (also used for per-file errors in backup/restore commands) with either a null path or a flag like "is_fatal: true`.

I'd prefer to use a separate message type for fatal errors. Those errors are printed in `cmd/restic/main.go` and thus are independent of the command specific errors reported by for example `backup`. I'm not entirely convinced with naming it `fatal_error` as we also have the `"at least one source file could not be read"` error, which isn't really a fatal error. Maybe something like `exit_error` would be a better fit.

**Comment by mikix** [comment]
> In which context exactly? Are you only referring to the output when using the --json option? Ideally we'd stop printing non-JSON messages to stderr altogether.

That’s a fair desire and I can work with it.

My use case is my backup program which scans output as it comes from restic. It current looks for certain kinds of fatal errors to respond with a policy action (no space left, no repository- though that now has a “10” exit code) or just generic error message to show the user by looking for lines that start with “Fatal:”.

So if restic suddenly stopped printing that, current releases of my app combined with new releases of Restic wouldn’t work well together because errors would happen and my app wouldn’t notice. That’s the kind of transition ease I was talking about.

But it’s not a big deal. I can just try to make sure that my app releases a version that parses JSON exit errors before Restic does its next release.

> Maybe something like exit_error would be a better fit.

Makes sense - I can work on a PR. 👍
