### ISSUE TITLE
repair index --read-all-packs creates empty index record - feature or bug?

### ISSUE THREAD

**Issue by wplapper** [restic/restic#4949]
Output of `restic version`
--------------------------
restic 0.17.0 compiled with go1.22.5 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
local file and Microsoft Onedrive

Problem description / Steps to reproduce
----------------------------------------
when running restic -r <repo> repair index --read-all-packs on relatively small repositories, the above command creates a new index file and an empty index file with the contents '{"packs":[]}\n' (length 
55 bytes)

Expected behavior
-----------------
I expect one index file, particularly when the second file is logically empty.

Actual behavior
---------------
I see tho files listed.

Do you have any idea what may have caused this?
-----------------------------------------------
restic repair index rebuild process

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by wplapper** [comment]
I see tho files listed. - spelling mistake: 'tho' should be 'two'

**Comment by MichaelEischer** [comment]
This is just a minor cosmetic issue that also only shows up for very specific pack file counts. Empty indexes are ignored while loading them.

If someone wants to take a stab at this, the relevant code section is at https://github.com/restic/restic/blob/76d56e24d615b2460247bf184ed4c0906d8e39eb/internal/repository/index/master_index.go#L448 where the index should only be sent towards saveIndex if it is not empty.

**Comment by wplapper** [comment]
I had a look at the relevant code; I added a few log records. This is the log output:
See attached file log_extract.log.

The section in repository/index/master_index.go, function Rewrite, regarding the building of the new Index is in my opinion unnecessary, since repo.Flush() has already done that successfully. Only the task of removing the old indices needs to be done.
[log_extract.log](https://github.com/user-attachments/files/16405234/log_extract.log)

**Comment by wplapper** [comment]
here is the fix: git diff internal/repository/index/master_index.go
--- a/internal/repository/index/master_index.go
+++ b/internal/repository/index/master_index.go
@@ -456,6 +456,9 @@ func (mi *MasterIndex) Rewrite(ctx context.Context, repo restic.Unpacked, exclud
        worker := func() error {
                for idx := range saveCh {
                        idx.Finalize()
+                       if len(idx.packs) == 0 {
+                               return nil
+                       }
                        if _, err := idx.SaveIndex(wgCtx, repo); err != nil {
                                return err
                        }
I attach modified file internal/repository/index/master_index.go as 'internal/repository/index/master_index.txt'.
[master_index.txt](https://github.com/user-attachments/files/16430494/master_index.txt) - I called it ...txt

**Comment by MichaelEischer** [comment]
Please open a PR with the changes. Issues aren't well suited to discuss code changes.

Instead of returning, please just call `continue`. That way there's less risk of unexpected behavior if for some reason an empty index is sent to saving and  the index is not the last one (not sure what we'd have to break for that to happen  though)
