### ISSUE TITLE
Backup time increased significantly on version 0.17.0 (Windows)

### ISSUE THREAD

**Issue by jvandenbroek** [restic/restic#4950]
Output of `restic version`
--------------------------
restic 0.17.0 compiled with go1.22.5 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
Rclone SFTP

Problem description / Steps to reproduce
----------------------------------------
Backing up a remote Samba share from a relatively slow NAS results in backup duration of ~2 hours instead of ~15 minutes it takes on version 0.16.x. This probably has to do with the new Extended Attributes support, which is a really nice feature to have, however it should not have such an impact.

An option to revert to the old scan behavior would probably solve this, no need to check for changed attributes every backup, especially if it is this expensive.

Expected behavior
-----------------
Same or slight increase of backup times compared to previous version.

Actual behavior
---------------
Backup time takes ~8 times longer when source is on  (slow) network share.

Do you have any idea what may have caused this?
-----------------------------------------------
Probably the new Extended Attributes support.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic makes my life easier, can't think of any better / more reliable backup solution.

**Comment by MichaelEischer** [comment]
This is probably related to https://github.com/restic/restic/issues/4955 . Although, there extended attributes just result in weird errors. Apparently, samba manages to at least no break entirely.

**Comment by aneesh-n** [comment]
I have created a PR https://github.com/restic/restic/pull/4980 to ignore EA processing for paths that do not support EA. Hopefully this should help in this case where the Samba share is the source.

It would be great if you could test this PR on your end as well.

**Comment by MichaelEischer** [comment]
Fixed via #4980
