### ISSUE TITLE
Restic v0.17.0 file listings (ls, find, etc) not responding to SIGINT/TERM

### ISSUE THREAD

**Issue by akrabu** [restic/restic#4957]
Output of `restic version`
--------------------------
restic 0.17.0 compiled with go1.22.5 on darwin/arm64

What backend/service did you use to store the repository?
---------------------------------------------------------
Local

Problem description / Steps to reproduce
----------------------------------------
CTRL+C (SIGTERM) doesn't cancel file listings (`ls`/`find`/`diff`), but CTRL+\ (SIGQUIT) does.

Expected behavior
-----------------
SIGTERM should stop the file listing and quit, instead of waiting 'til the end of the file listing.

Actual behavior
---------------
See here:
https://v.usetapes.com/3HZ2EHgHS4

TL;DW: if you CTRL+C a file listing with `ls`, `find`, or `diff` it won't quit, but if you use ctrl+\ it will (possibly `snapshots` too, if it was long enough?  maybe others??  `list` seems to work as expected though)  

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Saved my bacon many times :)

**Comment by MichaelEischer** [comment]
https://github.com/restic/restic/pull/4960 should fix this. I found a few more somewhat problematic commands, but the listed ones (and `stats`) were probably the worst offenders.
