### ISSUE TITLE
Timestamps randomly not restored

### ISSUE THREAD

**Issue by akrabu** [restic/restic#4969]
Output of `restic version`
--------------------------
restic 0.17.0 compiled with go1.22.5 on darwin/arm64
(also occurs on v0.16.5)

What backend/service did you use to store the repository?
---------------------------------------------------------
Local

Problem description / Steps to reproduce
----------------------------------------
Restored a large snapshot, random files had the date modified set to the date of the restore.  Restored that specific folder only - it still did not restore the timestamps on the same files.

Expected behavior
-----------------
Restore metadata accurately

Actual behavior
---------------
Files are restored intact, but randomly missing metadata, including timestamps.  Timestamps will have the current restore date. 

Do you have any idea what may have caused this?
-----------------------------------------------
Uncertain.  Here's the debug log filtered for an affected file:

```
8108:2024/08/01 12:47:05 restorer/restorer.go:209	restorer.(*Restorer).traverseTreeInner	1	SelectFilter returned true true for "/zicam letter.doc"
8109:2024/08/01 12:47:05 restorer/restorer.go:373	restorer.(*Restorer).RestoreTo.func2	1	first pass, visitNode: mkdir "/zicam letter.doc", leaveDir on second pass should restore metadata
32757:2024/08/01 12:47:12 restorer/restorer.go:209	restorer.(*Restorer).traverseTreeInner	1	SelectFilter returned true true for "/zicam letter.doc"
32758:2024/08/01 12:47:12 restorer/restorer.go:430	restorer.(*Restorer).RestoreTo.func3	1	second pass, visitNode: restore node "/zicam letter.doc"
32759:2024/08/01 12:47:12 restorer/restorer.go:289	restorer.(*Restorer).restoreNodeMetadataTo	1	restoreNodeMetadata zicam letter.doc /Users/copenhav/_RESTORED/test/zicam letter.doc /zicam letter.doc
37768:2024/08/01 12:47:13 restorer/restorer.go:209	restorer.(*Restorer).traverseTreeInner	88	SelectFilter returned true true for "/zicam letter.doc"
```

There is a good chance this is due to special characters in the filename.  There are many special symbols, such as "fancy" dashes and apostrophes that seem to choke 'tar' and 'ditto' both, while testing.

After some experimentation, I found that any folder having a locked file (uchg flag) seems to have dates restored incorrectly, including within subfolders - but not the subfolder itself.  So that would be a good place to check first!

![Screenshot 2024-08-01 at 5 39 49 PM](https://github.com/user-attachments/assets/98e54e88-5934-48a5-a4ae-5d60694b1398)
![Screenshot 2024-08-01 at 5 41 22 PM](https://github.com/user-attachments/assets/30dc5c05-fab9-4e2f-9b2b-8863a6b52dce)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

🫶

**Comment by MichaelEischer** [comment]
Restic so far does not support BSD-flags, see https://github.com/restic/restic/issues/1622 . There should have been errors when restoring the timestamps, but those were likely swallowed due to https://github.com/restic/restic/pull/4958/files .

**Comment by akrabu** [comment]
> Restic so far does not support BSD-flags, see https://github.com/restic/restic/issues/1622 . There should have been errors when restoring the timestamps, but those were likely swallowed due to https://github.com/restic/restic/pull/4958/files .

Would it be possible to skip the unsupported flags, while still restoring the supported ones and timestamps??

**Comment by MichaelEischer** [comment]
> Would it be possible to skip the unsupported flags, while still restoring the supported ones plus timestamps??

restic doesn't know about that flag at all. So it just acts like that flag doesn't exist. Metadata is restored on a per-file basis, so there's no reason why individual file errors should affect the other files in the folder.

**Comment by MichaelEischer** [comment]
Hmm, I've reread the issue and now I'm completely unsure what's going on. The debug log snippet above does not complain about `error restoring timestamps for`, so apparently that step was successful, which means that #4958 isn't relevant here.

What does does `stat -x some/affected/file` return?

**Comment by akrabu** [comment]
> restic doesn't know about that flag at all. So it just acts like that flag doesn't exist. Metadata is restored on a per-file basis, so there's no reason why individual file errors should affect the other files in the folder.

Yeah, that's how I would expect it to work.  But not only does it not restore the "locked" flag (uchg), it also appears to stop processing further metadata within that folder.  I'm not 100% sure that's what happens, but if you look closely for the tiny lock symbol in the screenshots, "Fig 1.eps" was never locked to begin with - and is still affected.

In larger folders, you'll have a ton of files with the correct date, then a file that was locked and is no longer locked, and then a ton of files with today's date as the modified date instead.  I *think* it's tripping on that, but that be correlation not causation.

> Hmm, I've reread the issue and now I'm completely unsure what's going on. The debug log snippet above does not complain about error restoring timestamps for, so apparently that step was successful, which means that https://github.com/restic/restic/pull/4958 isn't relevant here.

Yeah that's the even weirder part... inside the debug log, it isn't throwing any errors, and for all intents and purposes seems to be OK.  Except, it's not lol

> What does does stat -x some/affected/file return?

File: "Fig 1.eps"
  Size: 1205623      FileType: Regular File
  Mode: (0755/-rwxr-xr-x)         Uid: (977179194/smitmark)  Gid: (1971611142/OHSUM01\Domain Users)
Device: 1,14   Inode: 439465782    Links: 1
Access: Thu Aug  1 17:37:21 2024
Modify: Thu Aug  1 17:37:21 2024
Change: Thu Aug  1 17:37:21 2024
 Birth: Fri Feb 12 14:01:11 1999

**Comment by akrabu** [comment]
@MichaelEischer Anything else I can do to troubleshoot for you??

**Comment by MichaelEischer** [comment]
> Access: Thu Aug 1 17:37:21 2024
> Modify: Thu Aug 1 17:37:21 2024
> Change: Thu Aug 1 17:37:21 2024
> Birth: Fri Feb 12 14:01:11 1999

I'm a bit puzzled by these timestamps. Is that the source or the restored file? The access/modify/change times seems sort of reasonable for the restored file. But the birth time apparently matches that of the original file. To complicate things further, restic does not restore the birth time (unless macOS is somehow keeping it as xattr).

Please run another restore with enabled DEBUG_LOG and try to match the timestamps of that file with when restic restored the metadata for some affected files.

Other than that we could try comparing the metadata captured by restic for a problematic file before and after restore:
```
cd source/folder/with/problematic/file
restic backup ./filename
restic cat <snapshotID>:/

# somewhere else
restic restore <snapshotID> -t out
cd out
restic backup ./filename
restic cat <newSnapshotID>:/
```
Depending on what is stored in the `extended_attributes` (base64 encoded), you might want to remove those from the output. (or send it to me in private)

**Comment by akrabu** [comment]
### Here's the `stat -x` of "Fig 1.eps" when mounted from the repository:

```
  File: "Fig 1.eps"
  Size: 1205623      FileType: Regular File
  Mode: (0755/-rwxr-xr-x)         Uid: (1661798422/copenhav)  Gid: (1971611142/OHSUM01\Domain Users)
Device: 26,8   Inode: 14783135626878503563    Links: 1
Access: Fri Feb 12 14:01:11 1999
Modify: Fri Feb 12 14:01:11 1999
Change: Thu Jul  6 18:04:47 2023
 Birth: Tue Aug 13 09:53:35 2024
```

### Here's the file restored:

```
  File: "Fig 1.eps"
  Size: 1205623      FileType: Regular File
  Mode: (0755/-rwxr-xr-x)         Uid: (977179194/smitmark)  Gid: (1971611142/OHSUM01\Domain Users)
Device: 1,13   Inode: 440918519    Links: 1
Access: Tue Aug 13 10:15:40 2024
Modify: Tue Aug 13 10:15:40 2024
Change: Tue Aug 13 10:15:40 2024
 Birth: Fri Feb 12 14:01:11 1999
```

### Here's every mention of "Fig 1.eps" in the debug log:

```
32508:2024/08/13 10:15:31 restorer/restorer.go:209	restorer.(*Restorer).traverseTreeInner	1	SelectFilter returned true true for "/Fig 1.eps"
32509:2024/08/13 10:15:31 restorer/restorer.go:373	restorer.(*Restorer).RestoreTo.func2	1	first pass, visitNode: mkdir "/Fig 1.eps", leaveDir on second pass should restore metadata
33511:2024/08/13 10:15:40 restorer/restorer.go:209	restorer.(*Restorer).traverseTreeInner	1	SelectFilter returned true true for "/Fig 1.eps"
33512:2024/08/13 10:15:40 restorer/restorer.go:430	restorer.(*Restorer).RestoreTo.func3	1	second pass, visitNode: restore node "/Fig 1.eps"
33513:2024/08/13 10:15:40 restorer/restorer.go:289	restorer.(*Restorer).restoreNodeMetadataTo	1	restoreNodeMetadata Fig 1.eps /Users/smitmark/Desktop/test5/Fig 1.eps /Fig 1.eps
33514:2024/08/13 10:15:40 restic/node.go:245	restic.Node.restoreMetadata	1	not running as root, ignoring lchown permission error for /Users/smitmark/Desktop/test5/Fig 1.eps: lchown /Users/smitmark/Desktop/test5/Fig 1.eps: operation not permitted
33713:2024/08/13 10:15:40 restorer/restorer.go:209	restorer.(*Restorer).traverseTreeInner	5568	SelectFilter returned true true for "/Fig 1.eps"
```

An interesting thing to note, if I try to run `xattr` to view the extended attributes on the mounted repository, it freezes.  Stat works fine, though.

If you want more of the debug log I can send it to you somewhere?

I'll have to work with the user's schedule to try backing up the original file again and doing the metadata comparison.

**Comment by MichaelEischer** [comment]
Thanks for the additional information. Unfortunately, I still don't have the slightest clue what is going on. So the following comments are just there to have things written down.

> Access: Tue Aug 13 10:15:40 2024
> Modify: Tue Aug 13 10:15:40 2024
> Change: Tue Aug 13 10:15:40 2024
>  Birth: Fri Feb 12 14:01:11 1999

It's slightly weird that the timestamps match the `restoreNodeMetadataTo` time and not that of the first pass. I don't have the slightest clue how the birth time ends up being set to 1999. Restic internally uses the [utimes](https://man.freebsd.org/cgi/man.cgi?query=utimes&apropos=0&sektion=2&manpath=macOS+14.3.1&arch=default&format=html) syscall which can only set the access and modification times. So there must be some other way how the birth time is restored. However, I couldn't find anything on that topic. It might be some macOS magic.

> I generally don't run as root, as I don't always have root permissions depending on the machine I'm on. Is that the issue?

The "Not running as root" error has no influence on restoring the file timestamps. If the `utimes` syscall failed, then there would be a `error restoring timestamps for ...` error.

> This might be because of the `mount` bugs on Sonoma, though. I do get some "nfs server fuse-t:/restic: not responding" errors as well, but not while running `xattr`.

That quite likely the case. I unfortunately don't know any details what's causing those hangs.

**Comment by MichaelEischer** [comment]
Can you run `xattr -l filepath` for the old and restored file? xattrs are the only things that is set after the file timestamps.

The man page for [setxattr](https://man.freebsd.org/cgi/man.cgi?query=setxattr&apropos=0&sektion=2&manpath=macOS+14.3.1&arch=default&format=html) also contains the following remark:

> On some filesystems, such  as  HFS+,  setting  the  extended  attribute  com.apple.ResourceFork will update the modification time	(``mtime'') of        the file.

That might explain a part of what's happening. I've changed the order of restore steps in https://github.com/restic/restic/pull/5006 . Can you give that a try?

**Comment by akrabu** [comment]
@MichaelEischer Sorry I didn't get a chance to try that - ended up catching COVID two weeks ago, and the end of last week was me scrambling to catch up at work haha

But I will happy report that #5006 does seem to fix the problem!  Thanks!

**Comment by MichaelEischer** [comment]
Nice, thanks for testing!
