### ISSUE TITLE
Cloud key vault integration (alternative to passwords)

### ISSUE THREAD

**Issue by udf2457** [restic/restic#4984]
It would be nice if restic could be integrated with key vault type services, e.g. [AWS KMS](https://aws.amazon.com/kms) or [Azure Key Vault](https://azure.microsoft.com/en-us/products/key-vault/).

So a per-repo password could be automatically generated and protected by keys held in the vault.

**Comment by alex-kattathra-johnson** [comment]
If we decide to implement this, I'd be interested in giving it a shot.

**Comment by MichaelEischer** [comment]
There's already `restic --password-command` which should be sufficient to implement your use case.
