### ISSUE TITLE
building restic on raspbian jessie with golang 1.3.3 fails

### ISSUE THREAD

**Issue by Echsecutor** [restic/restic#501]
I have some trouble building restic on my raspberrypi running raspbian jessie with golang. There seems to be some header file missing. Maybe the "at least go 1.3" statement from the docs is no longer up to date?

$ go version
go version go1.3.3 linux/arm

$ git clone https://github.com/restic/restic
Cloning into 'restic'...
...

$ git show
commit 5b33a7a903fc0c6d834be20c7399fe3f5ba1f210
Merge: 75dd9e0 1fe0e30
Author: Alexander Neumann <fd0@users.noreply.github.com>
Date:   Thu Apr 14 08:58:12 2016 +0200
...

$ go run build.go 
\# golang.org/x/crypto/poly1305
golang.org/x/crypto/poly1305/poly1305_arm.s:11 5a: No such file or directory: textflag.h
build failed: exit status 2
exit status 1

**Comment by jzacsh** [comment]
does `gb build` work? [slightly different step, per CONTRIBUTING.md](https://github.com/restic/restic/blob/5b33a7a903fc0c6d834be20c7399fe3f5ba1f210/CONTRIBUTING.md#development-environment)

**Comment by fd0** [comment]
Hi, thanks for bringing this up. Go 1.3 was released in 2014 and is rather old already. Nowadays, many libraries including the `crypto/poly1305` lib require this header file, which was added in Go 1.4.

In order to fix this issue I've submitted https://github.com/golang/go/issues/11448 and https://go-review.googlesource.com/12033, but apparently forgot to update the lib in the restic repository.

I'll have a look later today and update the vendored dependency, then you should be able to compile restic on linux/arm with Go 1.3

**Comment by Echsecutor** [comment]
Many thanks for looking into this! With the latest version, the error msg has changed. ;)

$ git show
commit 4531456be5f0034dbbda05303c5bcdfe68a1b371
Merge: 59ec393 4fb6669
Author: Alexander Neumann <alexander@bumpern.de>
Date:   Mon Apr 18 21:40:30 2016 +0200
...

$go run build.go 
\# golang.org/x/crypto/poly1305
golang.org/x/crypto/poly1305/poly1305_arm.s:26 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:29 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:34 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:61 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:74 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:111 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:123 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:124 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:139 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:140 syntax error, last name: R9
golang.org/x/crypto/poly1305/poly1305_arm.s:149 syntax error, last name: R9
too many errors
build failed: exit status 2
exit status 1

**Comment by Echsecutor** [comment]
@jzacsh thanks for the hint, but I can not even get gb to work.

$ go get github.com/constabulary/gb/...
\# github.com/constabulary/gb/vendor
gocode/src/github.com/constabulary/gb/vendor/depset.go:87: undefined: build.ImportComment

**Comment by fd0** [comment]
`gb` requires at least Go 1.4, so that error is expected. The other is not. So I suspect that your initial assessment was correct: On ARM, restic cannot be compiled with Go 1.3. Sorry.

**Comment by fd0** [comment]
By the way: Did you know that at least for Debian there is Go 1.5 available in the stable-backports?

**Comment by Echsecutor** [comment]
Cheers! 
The usual hassle with update cycles. ;) I ended up just downloading the arm binaries for go1.6 from golang.org Now compilation went smoothly.

**Comment by fd0** [comment]
Heh, glad it worked for you :)
