### ISSUE TITLE
Recommend a specific Backblaze B2 lifecycle rule in the documentation

### ISSUE THREAD

**Issue by moenodedev** [restic/restic#5027]
Update the documentation to say the "Keep only the last version of the file" Backblaze B2 lifecycle is recommended. The documentation is confusing and doesn't provide a specific recommendation.

https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#backblaze-b2
> Different from the B2 backend, restic’s S3 backend will only hide no longer necessary files. Thus, make sure to setup lifecycle rules to eventually delete hidden files. The lifecycle setting “Keep only the last version of the file” will keep only the most current version of a file. Read the [Backblaze documentation](https://www.backblaze.com/docs/cloud-storage-lifecycle-rules).

https://forum.restic.net/t/safe-to-change-b2-lifecycle-settings/59
> I think it is reasonable (and safe) to set this to “Keep only last version”. The background is that restic will by default never write the same file twice: Due to the way the repo is structured combined with the encryption the file name will always be different. The only exception is the file config, but that will also not change in the current version of restic.

**Comment by MichaelEischer** [comment]
Fine with me. Anyone up for a PR?
