### ISSUE TITLE
Restic crashes on IBM i PASE

### ISSUE THREAD

**Issue by vmlemon** [restic/restic#5049]
Output of `restic version`
--------------------------
````
bash-5.2$ ./restic_0.17.1_aix_ppc64 version
runtime: memory allocated by OS [0x700000048000000, 0x70000004c000000) not in usable address space: base outside usable address space
fatal error: memory reservation exceeds address space limit

runtime stack:
runtime.throw({0x100f10140?, 0x4000000?})
        /usr/local/go/src/runtime/panic.go:1067 +0x34 fp=0xffffffffffff588 sp=0xffffffffffff548 pc=0x10007c8c4
runtime.(*mheap).sysAlloc(0x1800fbce0, 0x10002df38?, 0x18010bf28, 0x1)
        /usr/local/go/src/runtime/malloc.go:734 +0x75c fp=0xffffffffffff640 sp=0xffffffffffff588 pc=0x10000fb0c
runtime.(*mheap).grow(0x1800fbce0, 0x9001000a01a15a0?)
        /usr/local/go/src/runtime/mheap.go:1489 +0xb4 fp=0xffffffffffff6d0 sp=0xffffffffffff640 pc=0x10002e914
runtime.(*mheap).allocSpan(0x1800fbce0, 0x1, 0x0, 0x10)
        /usr/local/go/src/runtime/mheap.go:1244 +0x1e4 fp=0xffffffffffff780 sp=0xffffffffffff6d0 pc=0x10002df84
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:962 +0x88 fp=0xffffffffffff7d8 sp=0xffffffffffff780 pc=0x10002d938
runtime.systemstack(0xffffffffffff828)
        /usr/local/go/src/runtime/asm_ppc64x.s:282 +0xa4 fp=0xffffffffffff7f8 sp=0xffffffffffff7d8 pc=0x100082e74
````

What backend/service did you use to store the repository?
---------------------------------------------------------
Local file system

Problem description / Steps to reproduce
----------------------------------------

Whilst I realise that "IBM i" is not an offically supported platform, for Restic, I observed that its PASE UNIX compatibility environment implements the AIX ABI, and much of its userland API.

Since I have an account on PUB400.com (a freely-accessible public system), and noticed that Restic builds for AIX/PowerPC are available, I decided to test one, out of morbid curiosity. 

I downloaded the latest AIX binary, from GitHub, using wget, to my home directory, unpacked it, and after setting the executable permission, attempted to run it:

````
bash-5.2$ ./restic_0.17.1_aix_ppc64                           runtime: memory allocated by OS [0x700000048000000, 0x70000004c000000) not in usable address space: base outside usable address space                                                     fatal error: memory reservation exceeds address space limit                                                                 runtime stack:
runtime.throw({0x100f10140?, 0x4000000?})                             /usr/local/go/src/runtime/panic.go:1067 +0x34 fp=0xffffffffffff598 sp=0xffffffffffff558 pc=0x10007c8c4              runtime.(*mheap).sysAlloc(0x1800fbce0, 0x10002df38?, 0x18010bf28, 0x1)
        /usr/local/go/src/runtime/malloc.go:734 +0x75c fp=0xffffffffffff650 sp=0xffffffffffff598 pc=0x10000fb0c
runtime.(*mheap).grow(0x1800fbce0, 0x9001000a01a15a0?)
        /usr/local/go/src/runtime/mheap.go:1489 +0xb4 fp=0xffffffffffff6e0 sp=0xffffffffffff650 pc=0x10002e914
runtime.(*mheap).allocSpan(0x1800fbce0, 0x1, 0x0, 0x10)
        /usr/local/go/src/runtime/mheap.go:1244 +0x1e4 fp=0xffffffffffff790 sp=0xffffffffffff6e0 pc=0x10002df84
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:962 +0x88 fp=0xffffffffffff7e8 sp=0xffffffffffff790 pc=0x10002d938
runtime.systemstack(0xffffffffffff838)
        /usr/local/go/src/runtime/asm_ppc64x.s:282 +0xa4 fp=0xffffffffffff808 sp=0xffffffffffff7e8 pc=0x100082e74

````
It appears that IBM i 7.5 (corresponding to AIX 7.2 TL5) is running:

````
bash-5.2$ uname -a
OS400 WWW 5 7 007800001B91
````

I haven't tried to build it from source, yet.

Expected behavior
-----------------

I'd expect that Restic wouldn't crash, and would print the help text.

Actual behavior
---------------

As mentioned, Restic crashes, attempting memory allocation.

Do you have any idea what may have caused this?
-----------------------------------------------

Unsure if the system is low on RAM, or if PASE handles memory in a way that contradicts the usual behaviour of AIX. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic is impressing me, with its portability, and extreme speed, so far!

**Comment by MichaelEischer** [comment]
> fatal error: memory reservation exceeds address space limit

That is an error in the golang runtime and would have to be fixed there. There's *nothing* we can do about that in restic.
There is an old unresolved issue https://github.com/golang/go/issues/45017 . I'm afraid we can't do anything as long as that isn't solved

**Comment by stormalf** [comment]
Hello,  based on the https://github.com/JasonTashtego the issue with memory can be solved easily by updating tagptr_64bit.go and replace 0xa by 0x7. I think that in few days, I'll try to fork a go repo and put all steps together to help the community to go forward based on the wonderful work done by all people involved in https://github.com/golang/go/issues/45017. Stay tuned!
