### ISSUE TITLE
restic diff between two snapshots small change but very large size defference

### ISSUE THREAD

**Issue by khodekhadem** [restic/restic#5055]
Output of `restic version`
--------------------------
restic 0.17.1 compiled with go1.23.1 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
s3

Problem description / Steps to reproduce
----------------------------------------
I'm using restic to backup a large test file (more than 200 G) and each time I make small changes in the file but when I check output of restic diff between two snapshots in a row I get 
```
root@server:/# restic --insecure-tls diff 68440d97   dad06131
repository d9c87bb9 opened (version 2, compression level auto)
comparing snapshot 68440d97 to dad06131:

[0:06] 100.00%  115 / 115 index files loaded
M    /streamtest

Files:           0 new,     0 removed,     1 changed
Dirs:            0 new,     0 removed
Others:          0 new,     0 removed
Data Blobs:  65547 new, 65725 removed
Tree Blobs:      1 new,     1 removed
  Added:   32.250 GiB
  Removed: 32.339 GiB
```
difference is more than 30 gig but I only changed a few lines 

this file is actually a stream file from MySQL database files, which has shut down I face this problem even if I backup the directory with multiple files   

Expected behavior
-----------------
I expected a few megabytes of difference 

Actual behavior
---------------
the difference is about 15 percent of the whole file

Do you have any idea what may have caused this?
-----------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by MichaelEischer** [comment]
> this file is actually a stream file from MySQL database files, which has shut down I face this problem even if I backup the directory with multiple files

Judging from the large amount of changes, the stream file has changes all over the place. Restic splits input data into chunks of about 1MB size, which can be a problem if the database changes a few bytes in lots of different places. See also https://github.com/restic/restic/issues/1071 .

> each time I make small changes in the file

Please be more specific.
