### ISSUE TITLE
My zpaq use case, one file by increment

### ISSUE THREAD

**Issue by flibustenet** [restic/restic#506]
I'd like to show my (recent) use case of zpaq http://mattmahoney.net/dc/zpaq.html

When I give a name like "mybackup???" it will create a new file each time I make a new backup "mybackup001.zpaq, mybackup002.zpaq..."
The usage of theses files is automatic when I need to restore.

Zpaq has nothing to send the backup to an other backend. Then when I want to send my backup online I just need to send the new generated file with scp or whatever.

Also, the files are compressed, it's difficult to understand how to use restic without compression.

**Comment by fd0** [comment]
Hey, thanks for reaching out. I've trouble understanding what your question or issue with restic is, could you elaborate?

In order to clarify a potential misunderstanding: At the moment, restic does not use compression at all, just deduplication.

**Comment by flibustenet** [comment]
Sorry, I mixed two things... (two things I like with zpaq)

My first question is to suggest a backend like zpaq:
- One file for all the backup, which can grow at each increment  (like a zip or tgz file)

or better

- One file for the first backup, and one file for each increment. Like that it's easy to mirror a backup to an other machine, we just need to copy the last file.
```
$ zpaq add "r???" myprojects
will create r001.zpaq
$ scp r001.zpaq backup_server:/...
work work work
$ zpaq add "r???" myprojects
$ scp r002.zpaq backup_server:/...
```

I thought about compression in the same time because of this give me the idea:
https://github.com/golang/proposal/blob/master/design/14386-zip-package-archives.md
I see that there is an issue here #21 

_Thanks to take time to read my poor english !_

**Comment by fd0** [comment]
Thanks for the explanation. I don't see much value in adding such a backend. A repository in a directory (using the `local` backend) can easily be mirrored to another server with e.g. `rsync`. When files in the repo that have been deleted locally aren't removed in the remote directory, the same effect can be achieved.

Implementing compression (on a per-blob level) is tracked in #21.
