### ISSUE TITLE
Last version for Windows 7

### ISSUE THREAD

**Issue by KamikazeePL** [restic/restic#5065]
Latest version which works on **Windows 7** is 
**[0.16.2](https://github.com/restic/restic/releases/tag/v0.16.2)**

**Comment by MichaelEischer** [comment]
I've added the remark to https://github.com/restic/restic/issues/4636

**Comment by sergeevabc** [comment]
Party is not over, download restic 0.18.0 for Windows 7 x64 [here](https://github.com/restic/restic/issues/4636#issuecomment-2759457029).
