### ISSUE TITLE
Add an option to backup Linux servers via SFTP

### ISSUE THREAD

**Issue by insinfo** [restic/restic#5070]
Add an option to backup Linux servers via SFTP, I currently need a tool that can backup several Debian Linux servers via SFTP without having to install anything on the server, I currently do this via several scripts which is not a very good solution.

**Comment by damoclark** [comment]
I suspect what you propose is beyond the design philosophy of Restic as a client-centric backup technology. 

Have you considered a fuse mount of your remote Debian servers locally and backing that up using Restic?  It will be slow, but sftp isn’t a terribly efficient protocol for transferring many files anyway. 

It’s something you can experiment with now and see how it goes.

**Comment by greatroar** [comment]
Duplicate of #299.
