### ISSUE TITLE
Adding a new simple encryption enabled nearly mimicking version control system into restic.

### ISSUE THREAD

**Issue by dheerajshyampvsofficial** [restic/restic#5072]
Output of `restic version`
--------------------------

0.17.1-dev

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

This is out of existing functionality. I am adding a new **Java** developed tool which nearly mimics a version controls system with enabled encryption. The tool name is **ReVCS**. I have provided an md file named **ReVCS.md** which can help you understand far more better.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Integration of this simple nearly mimicking vcs with restic can make restic a backup tool as well as version controlling system even. This can make developers or users utilize restic to have timely backups with added another layer of encryption and compression. Version control helps accelerate the development cycle, and backups protect you from the consequences of data loss or corruption

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes for all.

**Comment by MichaelEischer** [comment]
Closing as part of https://github.com/restic/restic/pull/5073
