### ISSUE TITLE
Feature Request: Storage Backend "Amazon Cloud Drive"

### ISSUE THREAD

**Issue by MirkoDziadzka** [restic/restic#508]
I would be great of restic would support "[Amazon Cloud Drive](https://www.amazon.com/clouddrive/home)" as a storage backend.

It seems that you can get "unlimited" file storage for around 60 USD/year - which makes it a great target for encrypted backup.

An API is available: https://developer.amazon.com/public/apis/experience/cloud-drive/content/restful-api

**Comment by fd0** [comment]
Thanks for the suggestion.

**Comment by fd0** [comment]
Ah, this issue is a duplicate of #212, closing.
