### ISSUE TITLE
Not retrying to load config

### ISSUE THREAD

**Issue by Mika56** [restic/restic#5081]
Output of `restic version`
--------------------------
restic 0.17.1 compiled with go1.23.1 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
S3 on Scaleway

Problem description / Steps to reproduce
----------------------------------------
Scaleway recently introduced rate limits on their object storage service.
Running multiple `restic backup` in a row will result in:

```
Fatal: unable to open config file: Stat: Reduce your request rate.
Is there a repository at the following location?
s3:https://s3.fr-par.scw.cloud/<redacted>
```

Expected behavior
-----------------
While Restic does retry network calls when reading and writing on network, it does not seem to be the case when opening configuration.

Actual behavior
---------------
Restic does not retry reading config, and fails immediately

Do you have any idea what may have caused this?
-----------------------------------------------

https://github.com/restic/restic/blob/efec1a5e96bec82a423ba01aeead48260c861471/cmd/restic/global.go#L648-L650

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Thank you for building an awesome, robust and free backup software! ❤️

**Comment by michaelbeaumont** [comment]
Isn't this change breaking for scripting purposes? [The restic docs suggest using `cat config` to check for repo existence, for example](https://restic.readthedocs.io/en/stable/075_scripting.html#check-if-a-repository-is-already-initialized). Apparently the new retry can't be disabled so this is just broken now.

**Comment by MichaelEischer** [comment]
@michaelbeaumont Open a new issue and describe why this is a problem. So far it it's only a complaint but no explanation _why_ the changed behavior is problematic.
