### ISSUE TITLE
Command chaining

### ISSUE THREAD

**Issue by KaJakKrzysztof** [restic/restic#5085]
restic 0.16.2 compiled with go1.22rc2 on linux/amd64

There is a need to execute restic check RIGHT AFTER making a snapshot and BEFORE any other command may take place.
Reasons:
1. damaged/failed snapshot can be a base for next one which can lock repo being done right before check
2. pruning can prune previous snapshots while the last one may be bad

This is real-life example why I even noticed the problem:

...
Added to the repository: 3.110 TiB (2.841 TiB stored)

processed 4064822 files, 5.106 TiB in 35:08:04
snapshot 81f7cfde saved
+ restic check --read-data
using temporary cache in /tmp/restic-check-cache-223678389
repository 06ad3847 opened (version 2, compression level auto)
created new cache in /tmp/restic-check-cache-223678389
create exclusive lock for repository
repo already locked, waiting up to 0s for the lock
unable to create lock in backend: repository is already locked by PID 557818 on beast by root (UID 0, GID 0)
lock was created at 2024-10-07 08:47:01 (1m21.119924663s ago)
storage ID 821532af
the `unlock` command can be used to remove stale locks

I do really not know how to make it possible, so, feel free and throw ideas

Restic is GREAT. I rarely contribute any ideas to any software, this will surely be exception :)

**Comment by MichaelEischer** [comment]
> There is a need to execute restic check RIGHT AFTER making a snapshot and BEFORE any other command may take place.

Restic will move towards non-exclusive locks in the future: https://github.com/restic/restic/issues/1141, see also https://forum.restic.net/t/roadmap-for-restic-0-17-to-0-19/7197. This will allow running `prune` concurrently to other commands and probably also `check`.

So for now the solution is to schedule your backups such that they don't overlap with `check`. In the future, this particular situation should just work without locking conflicts.

> 2\. pruning can prune previous snapshots while the last one may be bad

If you're worried about that then use `forget --keep-latest 5` to always keep the last few snapshots.

**Comment by KaJakKrzysztof** [comment]
This is not the same - you will have to do chain-locking outside the restic which is much harder than inside it with the backup repo - why? because NOONE can predict how long the write can last if the backup size is large enough - I have 4TB data to be backed up - mostly it takes half an hour, but if drive is busy, it can take as long as the whole day! Adding another concurrent operation while doing something that exceeded expected time is couter-productive. Chaining is really important in any cyclic operation.

Please reconsider.

**Comment by MichaelEischer** [comment]
I don't see how this would remain relevant once two-phase pruning is implemented. And that feature isn't that far out that it's worth the trouble to massively complicate the locking approach of restic.

**Comment by KaJakKrzysztof** [comment]
Ok, I'll pass this topic then. A pity. But still, keep up the good work :)
