### ISSUE TITLE
unable to save snapshot: Detected data corruption while saving blob, hash mismatch

### ISSUE THREAD

**Issue by evanraalte** [restic/restic#5086]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.22.2 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
local repo, on two different disks (in my case a repo inside a folder on mounted /dev/sdd and later on /dev/sdb)

Problem description / Steps to reproduce
----------------------------------------

I wanted to create a restic backup of my nextcloud files at:
`/mnt/sdc/nextcloud-aio/ncdata/user/files` 
to an external drive. 

I used the steps listed in the documentation to create the repo. I also shutdown the Nextcloud containers. Then I started the backup to my external usb hdd (/dev/sdd):
`restic -r /mnt/sdd/data/restic/nextcloud/ --verbose backup /mnt/sdc/nextcloud-aio/ncdata/user/files`

It all went pretty smooth until I got: 

```
start scan on [/mnt/sdc/nextcloud-aio/ncdata/user/files]
start backup on [/mnt/sdc/nextcloud-aio/ncdata/user/files]
scan finished in 19.034s: X files, X GiB
error: no result
error: no result
Fatal: unable to save snapshot: Detected data corruption while saving blob 27f6244cd9e0950cf2852273d8e704d0b66f68b5e298ce8849ba8a01846c8df9: hash mismatch
Corrupted blobs are either caused by hardware issues or software bugs. Please open an issue at https://github.com/restic/restic/issues/new/choose for further troubleshooting.
```

After this I ran a long SMART scan on all my drives (SDB, SDC and SDD), but no errors were found.

Then I tried the backup again, but this time to a restic repo on /dev/sdb (which is internal), to rule out usb mounted storage issues. However, I still get the "hash mismatch" error.

I suppose I haven't ruled out that my drive containing the data has no issues, that'd be not ideal.. 
Expected behavior
-----------------

My backup is done, and I am ready to move it to an S3 bucket :) 

Actual behavior
---------------

I get the hash mismatch error, and get the suggestion to post an issue on github (which I am doing right now).

Do you have any idea what may have caused this?
-----------------------------------------------

It starts to look like a defect source drive (SDC), but I hope there is a way to get more diagnostics on this issue somehow.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Awesome user interface, very clear!  It also might have helped me diagnose a problem with my drive, good that I am (better late than never) looking for a more stable backup solution off site! :)

**Comment by greatroar** [comment]
The prime suspect is zstd compression, which had a data corruption problem in the recent past. I suggest you retry with restic 0.17.1 and report which compression setting (--compression, $RESTIC_COMPRESSION) you're using.

**Comment by evanraalte** [comment]
Thank you for your response @greatroar! I tried it after my initial post with 0.17.1 already (via a docker container this time, `apt` sources did not offer me a quick way to install `0.17.1`), here I got the same issues. I have not used the `--compression` flag nor `$RESTIC_COMPRESSION` env var, so I suppose I used the default compression  settings, which is `auto`.  Are you suggesting that I should try setting it to `off`?

I am running on a server with limited ram, and I did observe SWAP usage. I ran a full memtestx86 suite without any errors, so a (farfetched) hypothesis of mine is that using the SWAP partition might cause issues?

**Comment by greatroar** [comment]
Yes, trying to backup with --compression=off (or try --compression=max) may give you a working backup. But that wouldn't solve any underlying corruption issue in zstd. If you're able, would you try to compile and run a restic binary with the following patch applied?

```diff
diff --git a/internal/repository/repository.go b/internal/repository/repository.go
index d408e3105..a74c10c7e 100644
--- a/internal/repository/repository.go
+++ b/internal/repository/repository.go
@@ -346,6 +346,7 @@ func (r *Repository) saveAndEncrypt(ctx context.Context, t restic.BlobType, data
        debug.Log("save id %v (%v, %d bytes)", id, t, len(data))
 
        uncompressedLength := 0
+       uncompressed := data
        if r.cfg.Version > 1 {
 
                // we have a repo v2, so compression is available. if the user opts to
@@ -366,6 +367,7 @@ func (r *Repository) saveAndEncrypt(ctx context.Context, t restic.BlobType, data
        ciphertext = r.key.Seal(ciphertext, nonce, data, nil)
 
        if err := r.verifyCiphertext(ciphertext, uncompressedLength, id); err != nil {
+               os.WriteFile("/tmp/restic-error-"+id.String(), uncompressed)
                //nolint:revive // ignore linter warnings about error message spelling
                return 0, fmt.Errorf("Detected data corruption while saving blob %v: %w\nCorrupted blobs are either caused by hardware issues or software bugs. Please open an issue at https://github.com/restic/restic/issues/new/choose for further troubleshooting.", id, err)
        }
@@ -404,6 +406,7 @@ func (r *Repository) verifyCiphertext(buf []byte, uncompressedLength int, id res
                }
        }
        if !restic.Hash(plaintext).Equal(id) {
+               os.WriteFile("/tmp/restic-error-"+id.String(), plaintext)
                return errors.New("hash mismatch")
        }
 
```

This should produce a file /tmp/restic-error-27f6244cd9e0950cf2852273d8e704d0b66f68b5e298ce8849ba8a01846c8df9 with your failing data. Please check it to see if it's safe for uploading here (it's plaintext!). If not, or you don't recognize the file's contents, we'll need to devise some way of remotely debugging this.

**Comment by evanraalte** [comment]
Thank you for the suggestion! Currently I am not able to test this, but I might have some spare time in the weekend. Will update this thread once I do.

**Comment by evanraalte** [comment]
Okay I got to run some tests, changed to code as follows (added `0644` compared to yours):
```go
diff --git a/internal/repository/repository.go b/internal/repository/repository.go
index d408e3105..2b8b6286e 100644
--- a/internal/repository/repository.go
+++ b/internal/repository/repository.go
@@ -346,6 +346,7 @@ func (r *Repository) saveAndEncrypt(ctx context.Context, t restic.BlobType, data
        debug.Log("save id %v (%v, %d bytes)", id, t, len(data))
 
        uncompressedLength := 0
+       uncompressed := data
        if r.cfg.Version > 1 {
 
                // we have a repo v2, so compression is available. if the user opts to
@@ -364,8 +365,8 @@ func (r *Repository) saveAndEncrypt(ctx context.Context, t restic.BlobType, data
 
        // encrypt blob
        ciphertext = r.key.Seal(ciphertext, nonce, data, nil)
-
        if err := r.verifyCiphertext(ciphertext, uncompressedLength, id); err != nil {
+               os.WriteFile("/tmp/restic-error-"+id.String(), uncompressed, 0644)
                //nolint:revive // ignore linter warnings about error message spelling
                return 0, fmt.Errorf("Detected data corruption while saving blob %v: %w\nCorrupted blobs are either caused by hardware issues or software bugs. Please open an issue at https://github.com/restic/restic/issues/new/choose for further troubleshooting.", id, err)
        }
@@ -404,6 +405,7 @@ func (r *Repository) verifyCiphertext(buf []byte, uncompressedLength int, id res
                }
        }
        if !restic.Hash(plaintext).Equal(id) {
+               os.WriteFile("/tmp/restic-error-"+id.String(), plaintext, 0644)
                return errors.New("hash mismatch")
        }
```

`./restic version` yields:
```
restic 0.17.1-dev (v0.17.1-170-g60cba5564-dirty) compiled with go1.22.2 on linux/amd64

**Comment by andreymal** [comment]
> I ran a long SMART scan on all my drives

"hardware issues" is not limited to drives, it may also be something like too overclocked/undervolted cpu/ram

Try to run mprime torture test (https://wiki.archlinux.org/title/Stress_testing#MPrime), when I undervolted my cpu too much, mprime crashed almost instantly (even though memtestx86 did not show any errors)

**Comment by MichaelEischer** [comment]
> Update: I am trying to increase my Vcore now with small steps. Increasing it has as affect that mprime fails less often

One the one system on which I've seen a similar error, the solution was to completely disable turbo boost. Maybe that also helps in your case. 

I'll close this issue for now as this looks like a hardware issue.

**Comment by gdtv** [comment]
I had the same problem. In my case, it was a memory hardware issue. I used memtest86 to test the memory, and it showed errors. Replacing the memory solved the problem. I'm writing this down here in the hope that it will be helpful to others who encounter the same problem.
