### ISSUE TITLE
"forget --prune" and repository locks - introduce tiered locks for automatic recovery?

### ISSUE THREAD

**Issue by jjYBdx4IL** [restic/restic#5090]
Somewhat related to: Restic tries to create lock file on forget even with --no-lock and --dry-run #3464

I'm running 'forget --prune' automatically in the background every 7 days against a Google Drive repo. For that to work, I can't use repository locks on the remote side because if the computer gets shut down, the lock remains in place and backups refuse to work.

Question: what happens if a prune gets interrupted? Can the repository remain in a bad state? For regular backups I assume I just end up with some redundant data that's not getting used.

Feature request: to avoid all of that and allow me to use locking properly, maybe there could be a tiered lock implementation? Ie let the remote lock file point to a local lock so restic is able to automatically recover after aborted runs by acquiring the local lock and thereby making sure nothing else is currently operating on the repository.

BTW: is the remote lock safe anyway? Does Google Drive make any assurances as to synchronicity of file visibility? I doubt it. The entire solution seems to be based on a broken assumption - at least regarding to Google Drive. So a local lock or central lock server (cmp NFS) would be necessary anyway.

p.s. maybe also use system-wide lock implementations instead of lock files? Semaphores?

**Comment by MichaelEischer** [comment]
Prune requires a lock to ensure that no other processes concurrently modify the repository. This will only change once https://github.com/restic/restic/issues/1141 is implemented. After that we can also automatically start cleaning up stale locks: https://github.com/restic/restic/issues/2736 .
