### ISSUE TITLE
Document `restore --target / --delete` safety check

### ISSUE THREAD

**Issue by durcom2** [restic/restic#5091]
Output of `restic version`
--------------------------

017.1

What backend/service did you use to store the repository?
---------------------------------------------------------
restic server

Problem description / Steps to reproduce
----------------------------------------

restore --delete to root ( / )on ubuntu 24 throws an error
I have a restic backup of my /home folder and need to restore

command:  /restic restore --delete --overwrite if-newer --repo rest:http://xxxx  -t /home latest
works but restores to /home/home

command: restic restore --delete --overwrite if-newer --repo rest:http://xxx -t / latest
throws error:  Fatal --target / --delete must be combined with an include or exclude filter

Expected behavior
-----------------

It should do the restore to the proper folder
Actual behavior
---------------
Errors out

Do you have any idea what may have caused this?
-----------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by durcom2** [comment]
Figured it out...did as the error message suggested... just did an include on /home
that worked.
Makes sense from a safety standpoint when restoring to /  However, this behaviour should be documented...

**Comment by MichaelEischer** [comment]
> Makes sense from a safety standpoint when restoring to /

As your backup apparently only includes `/home`, `restic restore --delete --target / [...]` would have wiped everything else in the root folder without the safety check.

**Comment by durcom2** [comment]
I understand how it works now, but not really the "default" behaviour I would expect.
I just want to back up /home, and then restore to /home
so on restic backup I back up folder /home as source
however, when I restore the snapshot and specify /home as target I get restored to /home/home
Is there a way to do a restore to /home so I don't get the double level of folders?

I know on rsync if you specify a trailing / (/home/) on the backup source it just backs up the backup folder contents, and if you don't specify the trailing / then it backs up the folder and contents
Not sure if restic does the same?
If not, maybe that should be added to restic to be consistent with how rsync works
Also, should be documented either way...(I couldn't find anything in the docs about this)

**Comment by MichaelEischer** [comment]
> however, when I restore the snapshot and specify /home as target I get restored to /home/home
> Is there a way to do a restore to /home so I don't get the double level of folders?

Yes from the `restore` [docs](https://restic.readthedocs.io/en/stable/050_restore.html)

> To only restore a specific subfolder, you can use the <snapshot>:<subfolder> syntax, where snapshot is the ID of a snapshot (or the string latest) and subfolder is a path within the snapshot.

> I know on rsync if you specify a trailing / (/home/) on the backup source it just backs up the backup folder contents, and if you don't specify the trailing / then it backs up the folder and contents

You could create your backup using `cd /home && restic backup .`. https://github.com/restic/restic/issues/4026 will probably also introduce some new way to do so.
