### ISSUE TITLE
Implement function to delete old snapshots according to a retention policy.

### ISSUE THREAD

**Issue by fd0** [restic/restic#51]
Idea: Use snapshot selectors from #1, remove snapshots, then run fsck with prune #50

Have a config like "keep hourly snapshots for the last two days, daily backups for the last four weeks, and weekly backups for everything that's older".

**Comment by fw42** [comment]
How is this issue different than https://github.com/restic/restic/issues/18?

**Comment by fd0** [comment]
Thanks for pointing out that this needs more explanation. #18 is about deleting a specific snapshot, e.g.: `restic remove 01020304`, this issue should track automatic deletion of old snapshots. I'd like to instruct restic to delete snapshots older that 60 days by calling e.g. `restic remove --older-than 60d`.

**Comment by eripa** [comment]
I would like to see this feature. It would help convincing some naysayers in terms of long-lasting backup-sets with data that changes frequently. :+1:

**Comment by eripa** [comment]
Maybe the title or description should contains something in the likes of "retention policy" or similar?

**Comment by fd0** [comment]
Good idea, thanks

**Comment by zbindenren** [comment]
+1

Hi 

I like restic, cool tool.

Is this still planed? Any estimations?

Or how I can delete old snapshots?

**Comment by fd0** [comment]
You can't, not yet. It's being worked on, but there's no timeline yet.

**Comment by roesel** [comment]
Restic looks great and it seems to be exactly what I need. Deleting old snapshots according to a retention policy is the only feature that I'm missing, since this way I cannot use it on dynamically evolving folders. I can't wait for this feature to be implemented.

Keep up the good work! :)

**Comment by domsl** [comment]
I have to agree - Restic is awesome and very easy to use, which is what I am looking for.

> Have a config like "keep hourly snapshots for the last two days, daily backups for the last four weeks, and weekly backups for everything that's older".

> 

This feature would be perfect and would make it so easy to have an ongoing backup for a synced folder, which you would set up and then could forget about it, knowing it will get backed up and will not bloat up unnecessarily. 

Thanks for the great work!

**Comment by zcalusic** [comment]
I'd say that this feature is an absolute necessity and long overdue.

I have restic repo that's been running for a while, and now the disk it uses is filling up. I can't enlarge it or get a bigger one. I'm now days away from disk full error. :(

Just to doublecheck, is there any option right now to remedy the situation, beside deleting everything and starting over fresh?

I've seen somewhere, but I can't find it now, that I could manually delete some older snapshot and run optimize to clean up the space. But I don't see optimize command in my restic installation, is it hidden or renamed in the meantime?

**Comment by fd0** [comment]
There was a command called `optimize`, but it turned out that in some situations too much data was deleted, so we removed the command.

I'm currently working on a command called `prune` in #479, which will serve as the basis for removing data from the repo according to a policy.

**Comment by fd0** [comment]
This is implemented and was merged just now, see https://restic.readthedocs.io/en/latest/Manual/#removing-snapshots-according-to-a-policy

**Comment by zcalusic** [comment]
Oh, it's a great news!

I eventually had to nuke my previous restic setup due to disk full condition, but let's hope it was the last time I need to undertake such drastic measures, thanks to your hard work @fd0!

**Comment by eripa** [comment]
Awesome work!! Will check this out soon!

**Comment by zbindenren** [comment]
Thx

**Comment by roesel** [comment]
Will look into this soon as well. Thank you for implementing this!
