### ISSUE TITLE
Allow dumping files to stdout

### ISSUE THREAD

**Issue by fd0** [restic/restic#510]
This is a followup issue to #255: Find a place and implement a command or option that allows dumping a file from a snapshot to stdout.

This allows the following use case:
- Backup an SQL dump with restic: `mysqldump | restic backup --stdin --stdin-filename production.sql`
- Restore it directly: `restic cat-file-to-stdout $SNAPSHOTID production.sql | mysql`

**Comment by cfcs** [comment]
Also somewhat useful for workarounds like the one suggested in https://github.com/restic/restic/issues/949

**Comment by fd0** [comment]
This is done in #1346, there's the new `dump` command. I'm closing this issue.

**Comment by rawtaz** [comment]
Should have been `restore --stdout` instead of `dump`, to be coherent with `backup --stdin`.
