### ISSUE TITLE
Since 0.17.2 "error: incomplete metadata for C:: multiple errors occurred: [get named security info failed with:"

### ISSUE THREAD

**Issue by andydld** [restic/restic#5107]
Output of `restic version`
--------------------------

0.17.2

What backend/service did you use to store the repository?
---------------------------------------------------------

Windows
Backup to another local drive and S3-compatible like MinIO and Wasabi

Problem description / Steps to reproduce
----------------------------------------

It seems that the error depands von VSS (Volume Shadow Copy Service).

command line:

`restic --limit-upload 1220 --verbose --use-fs-snapshot --compression=max backup C:\Hyper-V\SRV02`

Expected behavior
-----------------

No error.

Actual behavior
---------------

The output/llog shows this:

Log (the Windows-error is in german):

```
open repository
using parent snapshot 2c9cacd3
load index files
start scan on [C:\Hyper-V\SRV02]
start backup on [C:\Hyper-V\SRV02]
creating VSS snapshot for [c:]
successfully created snapshot for [c:]
error: incomplete metadata for C:: multiple errors occurred: [get named security info failed with: Zugriff verweigert; get EA failed while opening file handle for path \?\GLOBALROOT\Device\HarddiskVolumeShadowCopy52, with: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
scan finished in 6.700s: 13 files, 145.731 GiB

Files: 0 new, 4 changed, 9 unmodified
Dirs: 0 new, 6 changed, 9 unmodified
Data Blobs: 19809 new
Tree Blobs: 6 new
Added to the repository: 14.071 GiB (6.083 GiB stored)

processed 13 files, 145.731 GiB in 1:27:37
snapshot 1ee4fc7e saved
Warning: at least one source file could not be read
```

Do you have any idea what may have caused this?
-----------------------------------------------

I had no problems with 0.17.1.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm using restic since 2021. It works great and stable.
Great job, Keep it up!

**Comment by MichaelEischer** [comment]
This is a result of https://github.com/restic/restic/pull/5097 , which fixed how metadata is read for VSS snapshots. We'll probably need some additional exception to skip metadata retrieval for `HarddiskVolumeShadowCopyXX` paths.

**Comment by stephan0307** [comment]
I get the same error when using restic on windows in a virtual disk (virtual disk as file and mounted as device)

command for backup: restic.exe -r repository backup src
the following error is shown for every file to backup:
error: incomplete metadata for src: get named security info failed with: Access is denied.

This error happens since version 1.17.0 (i made tests with versions 1.17.0, 1.17.1 and 117.2)
Version 1.16.5 is working without any problem

**Comment by ilium007** [comment]
These backups have been running fine for months on a Proxmox virtual disk within Windows Server 2019. The past few days:

```
restic.exe : error: incomplete metadata for D:\: multiple errors occurred: [get named security info failed with: Access is denied.; get EA failed for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy165\, with: get file EA failed with: The parameter is incorrect.]
At C:\restic\backup_us.ps1:288 char:13
+             & $ResticExe backup $ResticBackupFlags $folder_list $vss_ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error: incomple... is incorrect.]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Even though the VSS copy is being created by the script:

```
PS C:\Windows\system32> vssadmin list shadows
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Contents of shadow copy set ID: {bdb8d598-e74b-4f07-ad16-37ea06eb6cd3}
   Contained 1 shadow copies at creation time: 30/10/2024 10:37:37 AM
      Shadow Copy ID: {e13962ba-7ca4-41d7-9106-b2d8f168da9d}
         Original Volume: (D:)\\?\Volume{1b7ce77d-5771-451d-8ac9-e75236cde72e}\
         Shadow Copy Volume: \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy165
         Originating Machine: xxxx.local
         Service Machine: xxxx.local
         Provider: 'Microsoft Software Shadow Copy provider 1.0'
         Type: Backup
         Attributes: Differential

PS C:\Windows\system32>
```

Any ideas on why this has only just started this week?

**Comment by ilium007** [comment]
Reverted to 0.17.1 this has come from 0.17.2 released 2 days ago that made changes to the was VSS metadata is read:

https://github.com/restic/restic/pull/5097

**Comment by globi84** [comment]
I have the same problem with the command

`restic --verbose backup C:\Users\USERNAME\ --exclude-file=c:\restic\windows.exclude --exclude-file=c:\restic\local.exclude --use-fs-snapshot`

```
creating VSS snapshot for [c:\]
successfully created snapshot for [c:\]
error: incomplete metadata for C:\: get EA failed while opening file handle for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy22\, with: The process cannot access the file because it is being used by another process.
scan finished in 10.325s: 37227 files, 7.381 GiB
```

**Comment by ilium007** [comment]
> I have the same problem with the command
> 
> 
> 
> `restic --verbose backup C:\Users\USERNAME\ --exclude-file=c:\restic\windows.exclude --exclude-file=c:\restic\local.exclude --use-fs-snapshot`
> 
> 
> 
> ```
> 
> creating VSS snapshot for [c:\]
> 
> successfully created snapshot for [c:\]
> 
> error: incomplete metadata for C:\: get EA failed while opening file handle for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy22\, with: The process cannot access the file because it is being used by another process.
> 
> scan finished in 10.325s: 37227 files, 7.381 GiB
> 
> ```

Revert to 0.17.1 and turn off maintenance or it will self update again

**Comment by globi84** [comment]
> Revert to 0.17.1 and turn off maintenance or it will self update again

If you could fix it in the next few days, that would be great. I have over 50 clients who need it fixed.

**Comment by MichaelEischer** [comment]
> If you could fix it in the next few days, that would be great. I have over 50 clients who need it fixed.

I'll try to fix the bug in the next days.

**Comment by MichaelEischer** [comment]
The error should be fixed by https://github.com/restic/restic/pull/5110 .

Please give it a try to make sure I didn't miss anything. To build the PR, download the go compiler from https://go.dev/dl/, download the code from the PR and build restic using `go build ./cmd/restic`.

Different Windows versions apparently return different sets of errors. The initial message in this issue contains both security descriptor and extended attribute errors (likely Windows 10 as I'm seeing the exact same errors). Whereas the second error sample, only reports extended attribute errors.

There will be a separate fix for the master branch. That branch is apparently affected by an additional bug that completely breaks the VSS feature.

**Comment by MichaelEischer** [comment]
I've reworked the implementation of #5110 such that it works the same way as #5112. Apparently it makes a difference whether \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopyXX or \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopyXX\ (note the trailing backslash) is used. Only the latter can be properly used for file operations.

**Comment by mchvs** [comment]
I just cross compiled [this branch](https://github.com/MichaelEischer/restic/tree/fix-vss-root-volume-patch). If I got it right, then:
```
> restic version
restic 0.17.2-dev (v0.9.5-4394-g1f0f6ad63) compiled with go1.22.4 on windows/amd64

restic backup . --use-fs-snapshot
repository (...) opened (version 2, compression level max)
using parent snapshot (...)
[0:00] 100.00%  2 / 2 index files loaded
creating VSS snapshot for [c:\]
successfully created snapshot for [c:\]
Fatal: unable to save snapshot: GetFileInformationByHandle \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy26: Incorrect function.
```

I can run other tests and provide more information if necessary. Just let me know.

**Comment by MichaelEischer** [comment]
Thanks for testing.

> restic 0.17.2-dev (v0.9.5-4394-g1f0f6ad63)

@mchvs Based on the version number that commit is from the `patch-release` branch but not the `fix-vss-root-volume-patch` branch.

> Fatal: unable to save snapshot: GetFileInformationByHandle \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy26: Incorrect function.

The above commit won't trigger that error. In fact, that exact error can **only** be triggered by the `master` branch. It cannot be triggered by `fix-vss-root-volume-patch`. The `fix-vss-root-volume-patch` branch temporarily had a state that could trigger a related error, but that is fixed now.

Please double check that you're at the right commit.

**Comment by mchvs** [comment]
Oh, sure!

```
>restic version
restic 0.17.2-dev (v0.9.5-4185-g962279479) compiled with go1.22.4 on windows/amd64

>restic backup . --use-fs-snapshot
repository ... opened (version 2, compression level max)
using parent snapshot ...
[0:00] 100.00%  2 / 2 index files loaded
creating VSS snapshot for [c:\]
successfully created snapshot for [c:\]

Files:           3 new,     2 changed,  5126 unmodified
Dirs:            0 new,    53 changed,  1123 unmodified
Added to the repository: 51.091 MiB (17.631 MiB stored)

processed 5131 files, 8.022 GiB in 0:32
snapshot ... saved
```

Worked fine for me. The new snapshot passes `check --read-data` and `restore --verify`.
