### ISSUE TITLE
No Alias `restic` When Installed With `winget`

### ISSUE THREAD

**Issue by jbdyn** [restic/restic#5108]
Hi! 👋

First of all, thank you very, very much for `restic` and the hard work you put into it. ❤️

I wanted to setup my backup solution on Windows (not my preferred choice, but it is what it is for now) and ran `winget install restic.restic`. Although the command stated it added the alias `restic`, it is not available as such, but only as `restic_0.17.1_windows_amd64`, the binary found in `$env:PATH`.

I am using PowerShell 7.4.6 (the cross-platform one, not the Windows PowerShell) on Windows 10 Pro 22H2.

Output of `restic version`
--------------------------
```
restic: The term 'restic' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Problem description / Steps to reproduce
----------------------------------------
- Install via `winget`.

  ```
  winget install restic.restic
  ```
  ```
  Gefunden restic [restic.restic] Version 0.17.1
  Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
  Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
  Der Installer-Hash wurde erfolgreich überprüft
  Archiv wird extrahiert...
  Archiv erfolgreich extrahiert
  Paketinstallation wird gestartet...
  Befehlszeilenalias hinzugefügt: "restic"    <-- claims to add the alias "restic"
  Erfolgreich installiert
  ```
- Start a new shell.
- Test the alias. Fails.

  ```
  restic version
  ```
  ```
  restic: The term 'restic' is not recognized as a name of a cmdlet, function, script file, or executable program.
  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  ```
- Search for the alias. Fails.

  ```
  Get-Alias restic
  ```
  ```
  Get-Alias: This command cannot find a matching alias because an alias with the name 'restic' does not exist.
  ```
- Test the binary found in `$env:PATH`. Works.

  ```
  restic_0.17.1_windows_amd64 version
  ```
  ```
  restic 0.17.1 compiled with go1.23.1 on windows/amd64
  ```
- Install `scoop`.
- Install `restic` via `scoop` (as also stated in the docs).

  ```
  scoop install restic
  ```
- Test the command (not an alias). Works.

  ```
  restic version
  ```
  ```
  restic 0.17.2 compiled with go1.23.2 on windows/amd64
  ```

Expected behavior
-----------------
`restic` is available as an alias when installed via `winget`.

Actual behavior
---------------
`restic` is not available as an alias when installed via `winget`.

Do you have any idea what may have caused this?
-----------------------------------------------
Maybe the winget manifest for `restic.restic` is not defined correctly?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It indeed made my day as I *finally* get a proper home-made backup solution. `restic` helped me a lot on following the 3-2-1 backup strategy (two local copies, one offsite), as it was not a thing I need to bother with at all. It just works. And that is always a huge relief for me in a complex setup, which - in my case - involves different devices and many moving parts.
So, much love to you for this awesome software. ❤️

**Comment by MichaelEischer** [comment]
> Maybe the winget manifest for `restic.restic` is not defined correctly?

We don't maintain the winget manifest for restic. From what I could find, the correct place to report the issue is likely https://github.com/microsoft/winget-pkgs

**Comment by jbdyn** [comment]
Thank you @MichaelEischer for your fast reply! My findings turn this issue into an enhancement request.

Your suggestion lead my finally to [this issue](https://github.com/microsoft/winget-cli/issues/4043) in [microsoft/winget-cli](https://github.com/microsoft/winget-cli):

- https://github.com/microsoft/winget-cli/issues/4043

Apparently, I ran `winget install restic.restic` _without_ admin rights and the process is thereby not allowed to create symlinks in the `%localappdata%\Microsoft\WinGet\Links`.
The `winget` logs also say that the symlink creation failed (but not why).
Manual symlink creation failed then with a useful error message about missing admin privileges.
However, as the linked issue states, `winget` does not report this correctly in its output to the user.

But, when symlink creation fails, `winget` adds the path to the package itself to `PATH`. That is why `restic_0.17.1_windows_amd64.exe` works.

So, there are two ways to circumvent this:
1. Run `winget install restic.restic` with admin privileges (and remember to do so in the future).
2. Rename the portable executable from `restic_<version>_windows_<arch>.exe` to `restic.exe`.

   This is also what [syncthing](https://github.com/syncthing/syncthing), [fzf](https://github.com/junegunn/fzf), [chezmoi](https://github.com/twpayne/chezmoi), [fastfetch](https://github.com/fastfetch-cli/fastfetch) and [zoxide](https://github.com/ajeetdsouza/zoxide) have, which has the consequence that it does not matter anymore if `winget install restic.restic` is installed with or without admin privileges.
    In either case, `restic` (as recognized abbreviation for `restic.exe`) is available as command and ready to go.

@MichaelEischer what do you think about the second option?

**Comment by MichaelEischer** [comment]
> 2\. Rename the portable executable from `restic_<version>_windows_<arch>.exe` to `restic.exe`.

While restic's self-update mechanism would be able to handle such a rename, I'm pretty sure that we'd break some tool.

Ideally winget would just fall back to rename or copy the binary if it cannot create a symlink.

**Comment by jbdyn** [comment]
> While restic's self-update mechanism would be able to handle such a rename, I'm pretty sure that we'd break some tool.

Yeah, probably.

> Ideally winget would just fall back to rename or copy the binary if it cannot create a symlink.

I will watch the corresponding issue microsoft/winget-cli#4043. The solution might solve this.

**Comment by mgrottenthaler** [comment]
I stumbled upon your issue when I had a similar problem. In case somebody else find this:

1. I don't want to install restic as admin. Even if I wanted, my account doesn't have admin privileges directly (separate local admin). This would break upgrading and other problems...
2. I just need a version independent way to call restic from my script.

I came up with a workaround for my PowerShell script:

``` powershell
# find restic exe
# Base folder where winget puts restic
$base = "$env:LOCALAPPDATA\Microsoft\WinGet\Packages\restic.restic_Microsoft.Winget.Source_8wekyb3d8bbwe"

# Find all restic executables
$resticBins = Get-ChildItem -Path $base -Filter "restic*.exe" | Sort-Object Name -Descending

if ($resticBins.Count -eq 0) {
    Write-Error "No restic executable found in $base"
    # optional: keep window open for user to see error message
    Read-Host -Prompt "Press Enter to exit"
    exit 1
}

# Pick the newest one (highest name after sorting)
$resticExe = $resticBins[0].FullName

Write-Host "Using restic: $resticExe"
# run restic version
& $resticExe version
```

hope this helps somebody else out there. It would be great, if winget would not add the version to the filenames...
