### ISSUE TITLE
Ciphertext verification failed error

### ISSUE THREAD

**Issue by jutuahol** [restic/restic#5118]
Output of `restic version`
--------------------------
source server: restic 0.17.1 compiled with go1.23.1 on linux/amd64
repo server restic 0.17.2 compiled with go1.23.2 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
With Backrest docker from Ubuntu Server. Repo server is old laptop running Ubuntu Server as well. Both Ubuntu Servers are  24.04.1 LTS. First Ubuntu has Ethernet connection, second Ubuntu uses WLAN. Repositories are stored in external USB hard drive.

Problem description / Steps to reproduce
----------------------------------------
I'm making backups from Ubuntu's local disks and storing them to another Ubuntu Server in same network. 

Have tried to use Samba share, SFTP repo and restic-server to transfer backup. Backup process finishes without errors but running check --read-data gives always ciphertext verification failed errors. Backup size is about 500GB.

Expected behavior
-----------------
Check would finish without errors.

Actual behavior
---------------
Lot of ciphertext verification failed errors.

Snippet of error message
```
sudo restic -r ubuntu-images-repo/ check --read-data

using temporary cache in /tmp/restic-check-cache-331727604
create exclusive lock for repository
enter password for repository:
repository e2a38464 opened (version 2, compression level auto)
created new cache in /tmp/restic-check-cache-331727604
load indexes
[0:01] 100.00%  38 / 38 index files loaded
check all packs
check snapshots, trees and blobs
[0:01] 100.00%  1 / 1 snapshots
read all data
pack 70be998dcceedac0ba8981c49d107d05ffc06fc75848dd1696603c7fabb3b6f8 contains 7 errors: [blob e8c97793d901f2ea702bc3dac59129b761335933b2a463e3173ffd5ac4422a2a: decrypting blob <data/e8c97793> from 70be998d failed: ciphertext verification failed blob d3ac936127c85ac744a5ef357edf4e8dc3b3ac85247b872f9bcbe5d7a67d7a48: decrypting blob <data/d3ac9361> from 70be998d failed: ciphertext verification failed blob d493e714a87a8d92cfaea07e95ac82d7332f381d95207404bbf91a12c970aa01: decrypting blob <data/d493e714> from 70be998d failed: ciphertext verification failed blob ef11af4da6a4c16ae8ce86784cfcb611ca5ba8df4ec5074f85501f1847b077a6: decrypting blob <data/ef11af4d> from 70be998d failed: ciphertext verification failed blob 3a5a9001efd167d0c02c2deb42f98614ed1a2dc29311ea7d43edc072c5b2a051: decrypting blob <data/3a5a9001> from 70be998d failed: ciphertext verification failed blob 92951ebe0e36a61cffff04f5a14ea04eab51223d4de6e103bd80d0865a49a1dc: decrypting blob <data/92951ebe> from 70be998d failed: ciphertext verification failed unexpected pack id a9a075013087a00de6a20f1102eca91a27d42f39e66d1250ec19ac543170a9db]
pack f0ba960df62f8d7d4f13eb3ee46d4944a3d2fdbd9f1216dd673484b0b2d0b363 contains 2 errors: [blob 32e3be3ee3c0792d74cc00c0551833db70a11e3a03b0d7d1973a09ba1242f14f: decrypting blob <data/32e3be3e> from f0ba960d failed: ciphertext verification failed unexpected pack id 45b8ef7abf8668e3128d025214addef4f9dc4ff676a44696a0f839624207e4c6]
pack 605cb9229074d6adcaec9b55957d2e67d4eab24328efba30b12af7c129bfb81b contains 2 errors: [blob a2d8b392ec52ba6e3ec3d0a8bd85d8984a9929c495c7690546f190f7b6b43245: decrypting blob <data/a2d8b392> from 605cb922 failed: ciphertext verification failed unexpected pack id ee709f38e5e4e26a40e5f2d52fc3c0167ea8cd1de7848a75d5e2dfdb84f68295]
signal interrupt received, cleaning up
download error: context canceled
download error: context canceled
[0:11] 0.07%  23 / 30898 packs
```

Do you have any idea what may have caused this?
-----------------------------------------------
Could it be related to hardware or network? I executed memtest86 and smartctl -t long for repo server and both finished without errors. However not sure if hardware setup is optimal or good enough with WLAN and USB-hard disk.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Thanks for the tool, its fantastic!

**Comment by MichaelEischer** [comment]
> Have tried to use Samba share, SFTP repo and restic-server to transfer backup. Backup process finishes without errors but running check --read-data gives always ciphertext verification failed errors

Which rest-server version did you use? Did you start with a fresh repository or back up to the already broken repository?

Starting from restic 0.16.4, restic verifies the pack file content before uploading, that should make it nearly impossible to see `ciphertext verification failed` error unless the pack file is damage on the repo server side.

> Could it be related to hardware or network? I executed memtest86 and smartctl -t long for repo server and both finished without errors. However not sure if hardware setup is optimal or good enough with WLAN and USB-hard disk.

rest-server verifies pack files during upload to prevent `unexpected pack id [...]` errors. If that damaged pack file was uploaded via rest-server, then the repo server is definitely to blame. Samba and SFTP also include integrity checks of uploaded data, but less strict than rest-server.

The data corruption is usually either triggered by CPU or RAM issues. For the former, `prime95` has proven pretty effective to stress the CPI as it can also self-verify its calculations.

**Comment by jutuahol** [comment]
> Which rest-server version did you use? Did you start with a fresh repository or back up to the already broken repository?

rest-server version rest-server 0.13.0 compiled with go1.22.5 on linux/amd64

Used fresh repository with new name. Ran also prime95 for around 1 hours - no errors occurred. 

I tried to plug USB drive directly to source server, ran backup (data amount 500GB) and check with --read-data -> no errors. Then plugged USB back to repo server, created new repo and backed up 200GB of same data -> errors came back.

If I run check from source server I get errors almost immediately:

```
$ sudo restic -r rest:http://user:password@192.168.3.5:8000/repo check --read-data

using temporary cache in /tmp/restic-check-cache-4036432995
enter password for repository:
repository 244a31eb opened (version 2, compression level auto)
created new cache in /tmp/restic-check-cache-4036432995
create exclusive lock for repository
load indexes
[0:00] 100.00%  14 / 14 index files loaded
check all packs
check snapshots, trees and blobs
[0:00] 100.00%  1 / 1 snapshots
read all data
Pack ID does not match, want 008e6fe197329e857c0cc5489dd8f107073b75d502ff501d674c241ee846cd8d, got 4cd24170bd6ea8052ee7780db3e34ca508ccffbb0351f24ea9c71e4cb709b791
Pack ID does not match, want 108eb4648023219b48942d00c5a09ca1164f820abbaf9fd643b8bda16e80a677, got 8f507061e7597c71f071790452989bd8a63081525b2e1c89a788e147e0f9fe84
Pack ID does not match, want c0f64c8995c983e29696d7adaa4fbaf0cacb189b870d5489a625350f4a664781, got 7f6917ca1440344965ead251e741f36c264f50be2f50dc2908bf7552e3024c94
Pack ID does not match, want 8039085306ff9d72feccfa667cca79e02d58ed69e1518ebc7c655b3d8fb0001f, got 94a1a0300a0116c50048950d13c7bf19ef98faf28bcaedd6cc6ebf909de2b350
Pack ID does not match, want c0b3006866c9f0c53715a393f27629005cf026235e07cde67a043c5de30f3b2f, got 22dea98b8f7273a2d91c0a8c56cc9a933c57cc80f7f9d2d9d572316f040d0965
Pack ID does not match, want 905ea3a41ed4c5ba97c7efcd8a62f5cb6a43a2825bf31e98aaa2ff922be95da3, got 30b3555172fca3fd45c3dcd9940505a3a5dd6da67e890df230f330048f3cbb40
Pack ID does not match, want 20b133613a4fd566e28d4f894c48daa170b08a8c6c26fb421c4ab18365b1a0a5, got e822fcaaed69d232eb444b6f5559cbb9248f209955e02a6920fba0956064056f
Pack ID does not match, want 60f9593730284c4c4b9575209cda5d8d05dd961799469a0c2d0eb9227fc72ffc, got 7ba3400c0385915fe992334cab36132c6fd97d4db0ce73cace0f2c1aed25d024
Pack ID does not match, want c0a8729e71ba72a5f42664160baa332104f8ce8f60c5eb2984e41b564e6b8bd1, got 17e30983423e6a71d2dd3a19ee31befe3fe6af187a059366d4645240f9057a0f
  signal interrupt received, cleaning up
pack 80350c9e77716c3656b904dc57a980b8c9697daa6bc34ee8c826ed98ec5466b0 failed to download: StreamPack: context canceled
[0:16] 0.45%  44 / 9883 packs
Fatal: repository contains errors
````

When running check command from repo server, I get ciphertext errors almost immediately:

```
$ sudo restic -r /mnt/usb/backups/repo check --read-data

using temporary cache in /tmp/restic-check-cache-3770075819
create exclusive lock for repository
enter password for repository:
repository 244a31eb opened (version 2, compression level auto)
created new cache in /tmp/restic-check-cache-3770075819
load indexes
[0:00] 100.00%  14 / 14 index files loaded
check all packs
check snapshots, trees and blobs
[0:00] 100.00%  1 / 1 snapshots
read all data
pack 905ea3a41ed4c5ba97c7efcd8a62f5cb6a43a2825bf31e98aaa2ff922be95da3 contains 16 errors: [blob efab0c215de830e9aa44c32e924d858d5a714316cfff0c865ced598df5412d56: decrypting blob <data/efab0c21> from 905ea3a4 failed: ciphertext verification failed blob 98f2c21eb0dc1baf6ba19a183d91704bab723a987d1d091ca229bb6d305b9adf: decrypting blob <data/98f2c21e> from 905ea3a4 failed: ciphertext verification failed blob 6b94cc4bcd1bd357a24d568c4f8d561ef8342be09f3bc6ab3188d628181be1e7: decrypting blob <data/6b94cc4b> from 905ea3a4 failed: ciphertext verification failed blob faad5e1e5d9f9a11cc884b7351f2de03d7ae3d9df3defddbfb16faadbbb7dc42: decrypting blob <data/faad5e1e> from 905ea3a4 failed: ciphertext verification failed blob 62bab2309b37a7b9bfa314fe21a0e8db8b25354df213192cd6232e2fec9120c7: decrypting blob <data/62bab230> from 905ea3a4 failed: ciphertext verification failed blob 8fa1487d9b0a7e31da161ca78afdb17626fab78504cf44aa9d64445b8fd561b6: decrypting blob <data/8fa1487d> from 905ea3a4 failed: ciphertext verification failed blob 69f624d6c1d6ec3597834ade173006d83cbdb372892661e00076fca840f3ee85: decrypting blob <data/69f624d6> from 905ea3a4 failed: ciphertext verification failed blob 247d85ee1c22857cd4c1dc6e40cc4cfbef3c7c0e3ca2c7a717a299d3eef9f74f: decrypting blob <data/247d85ee> from 905ea3a4 failed: ciphertext verification failed blob 3351d9a78e494d4b89dcb988558aac355e56bc73bdc4f93ebbc372d45b19fc9d: decrypting blob <data/3351d9a7> from 905ea3a4 failed: ciphertext verification failed blob 86989b7ec0b1a4e7dccccb61acc7169bdc90d0783785cbf1003e0d5a8caac452: decrypting blob <data/86989b7e> from 905ea3a4 failed: ciphertext verification failed blob fcd42d107b5068dd195eefd988947963a491cb18f2c160dcc5861073e86e6299: decrypting blob <data/fcd42d10> from 905ea3a4 failed: ciphertext verification failed blob 12fcd28bfa7451ec915faf761c48ffafd2c09cc65a7398c6ae1ab5d20a751317: decrypting blob <data/12fcd28b> from 905ea3a4 failed: ciphertext verification failed blob b3c47a00b7710a8dcaa7b4c60309afa17cef61153bb3da29e1f76337ce1a08f3: decrypting blob <data/b3c47a00> from 905ea3a4 failed: ciphertext verification failed blob c184caf0b3f5b7ab08db0505ff0508b9268c58fd4e25a88d1b46170e475293dd: decrypting blob <data/c184caf0> from 905ea3a4 failed: ciphertext verification failed blob f7aa9ede846aa19c0bf06938759ff892b937e557e822997a460f20975f4b1fda: decrypting blob <data/f7aa9ede> from 905ea3a4 failed: ciphertext verification failed unexpected pack id 30b3555172fca3fd45c3dcd9940505a3a5dd6da67e890df230f330048f3cbb40]
```

There is difference between SFTP and restic-server. When backup is done via SFTP, there are few ciphertext errors. When done via restic-server, there are much more ciphertext errors.

**Comment by MichaelEischer** [comment]
Both servers complain about `905ea3a41ed4c5ba97c7efcd8a62f5cb6a43a2825bf31e98aaa2ff922be95da3` so it looks like the data stored in the repository is broken. Please run `shasum -a256 path/to/repo/data/90/905ea3a41ed4c5ba97c7efcd8a62f5cb6a43a2825bf31e98aaa2ff922be95da3`. Based on the above output I'd expect that command to print
```
30b3555172fca3fd45c3dcd9940505a3a5dd6da67e890df230f330048f3cbb40 905ea3a41ed4c5ba97c7efcd8a62f5cb6a43a2825bf31e98aaa2ff922be95da3
```

> When done via restic-server, there are much more ciphertext errors starting coming as soon as check command is executed.

rest-server verifies the data before writing it to disk. The disk usage patterns are different than that of SFTP to different corruption patterns aren't entirely unexpected.

> Then plugged USB back to repo server, created new repo and backed up 200GB of same data -> errors came back.

That suggests that the repo server breaks the files while writing the to the USB disk. Based on my remark above, this feels like the most likely cause of the problem. Please run a `fsck` on the USB disk. Given the massive amount of corrupted repository files, it's not unlikely that the filesystem itself is damaged as well.

Do you have to possibility to store the repository somewhere else on the repo server? 

Does `dmesg` report any USB related errors on the repo server? Can you try a different USB port / cable?

**Comment by jutuahol** [comment]
I had already deleted the original repository but created new one via restic-server to run shasum:

```
sudo restic -r repotest2 check --read-data
using temporary cache in /tmp/restic-check-cache-3302744728
create exclusive lock for repository
enter password for repository:
repository 7e1a2149 opened (version 2, compression level auto)
created new cache in /tmp/restic-check-cache-3302744728
load indexes
[0:00] 100.00%  6 / 6 index files loaded
check all packs
check snapshots, trees and blobs
[0:00] 100.00%  1 / 1 snapshots
read all data
pack b06ec3d98631d8bd567e6dd729f19506bfc11e1dd2ca0cc6c37e9fa3107ec7b2 contains 7 errors: [blob e1f7123fffb0efa3868d36b4a22a8cfa656a66dc66f6ebaa7f645d96df1bb84d: decrypting blob <data/e1f7123f> from b06ec3d9 failed: ciphertext verification failed blob 04a7e97a0ae9d95c0a23c13aec36fa2718584164d99afcc64abf80aa67e95ac4: decrypting blob <data/04a7e97a> from b06ec3d9 failed: ciphertext verification failed blob 70e6d9185df0609b681acfe31e5ee92ac20dafc5f5bbac25d4c5b0da7bbf252e: decrypting blob <data/70e6d918> from b06ec3d9 failed: ciphertext verification failed blob f470082339d99e9160314f020df76662d87cb74828688a572ecb770115f94b7e: decrypting blob <data/f4700823> from b06ec3d9 failed: ciphertext verification failed blob 080c8d354fd6b30b5dbf26ce5bab20dd172a7ff87e6cdbb5a9e71c44f89087c8: decrypting blob <data/080c8d35> from b06ec3d9 failed: ciphertext verification failed blob 41d24a11ff8cccbc56ed346f402b5556b07892d3e48c05a8a38ce31b3da147a5: decrypting blob <data/41d24a11> from b06ec3d9 failed: ciphertext verification failed unexpected pack id 97c90b73f82f134146d143527fa72a4da339a32a1420779e41d9bb8d2aa84dcf]
```
```
sudo shasum -a256 repotest2/data/b0/b06ec3d98631d8bd567e6dd729f19506bfc11e1dd2ca0cc6c37e9fa3107ec7b2
97c90b73f82f134146d143527fa72a4da339a32a1420779e41d9bb8d2aa84dcf  repotest2/data/b0/b06ec3d98631d8bd567e6dd729f19506bfc11e1dd2ca0cc6c37e9fa3107ec7b2
```

This was the only USB related line I found from dmesg. 
`[  123.442672] /dev/sdb: Can't open blockdev`

Fsck gave lot of "Inode seems to contain garbage" errors and I let if to fix them.

> Do you have to possibility to store the repository somewhere else on the repo server?

Repo server has 100GB SSD disk. When I created repository there with around 70GB backup, it works fine. When trying to backup same 70GB data (after running fsck) to external USB disk with another cable and with different USB port, getting again same errors as seen above.

Based on this I would guess for some reason my repo server (Dell XPS 13 laptop from 2016) seems not to work properly with external USB disk (old SAMSUNG HD204UI disk).

**Comment by MichaelEischer** [comment]
> Based on this I would guess for some reason my repo server (Dell XPS 13 laptop from 2016) seems not to work properly with external USB disk (old SAMSUNG HD204UI disk in Lacie USB case).

Based on the amount of errors the only option is to find some other storage device. I'll close this issue for now as it clear by now that this is a hardware issue.
