### ISSUE TITLE
"get named security info failed with: Access is denied." with WinFSP volume on Windows

### ISSUE THREAD

**Issue by fabiantreu** [restic/restic#5127]
Output of `restic version`
--------------------------
`restic 0.17.2 compiled with go1.23.2 on windows/amd64`

What backend/service did you use to store the repository?
---------------------------------------------------------
Local NTFS drive

Problem description / Steps to reproduce
----------------------------------------
Running a backup gives this error for all files:
`error: incomplete metadata for <path-to-file>: get named security info failed with: Access is denied.`

Expected behavior
-----------------
no error

Do you have any idea what may have caused this?
-----------------------------------------------
Maybe a bug in 0.17.X versions? The backup works fine with restic 0.16.5. Versions 0.17.1 and 0.17.2 give the access error. The source location which I am trying to backup is a WinFSP Volume (mounted Cryptomator vault).

**Comment by MichaelEischer** [comment]
Duplicate of https://github.com/restic/restic/issues/5103 . Please reopen the issue if it is not fixed by restic 0.17.3 which will be released in the next few days.
