### ISSUE TITLE
"incomplete metadata / get named security info failed" error

### ISSUE THREAD

**Issue by tszynalski** [restic/restic#5128]
Output of `restic version`
--------------------------

`restic 0.17.2 compiled with go1.23.2 on windows/amd64`

Problem description / Steps to reproduce
----------------------------------------

After upgrading to 0.17.2, my backup job now prints the following error:
`error: incomplete metadata for C:\: multiple errors occurred: [get named security info failed with: Access is denied.; get EA failed while opening file handle for path \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy34\, with: The process cannot access the file because it is being used by another process.]`

The error is repeated for every drive that contains files to be backed up.
The job seems to complete regardless, but restic returns a nonzero exit code, so my script thinks the backup has failed.

I use restic with the following params: `--files-from --iexclude-file --use-fs-snapshot --verbose`

This did not happen on 0.17.1.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm happy that the VSS metadata bug was fixed so quickly!

**Comment by MichaelEischer** [comment]
Duplicate of https://github.com/restic/restic/issues/5107 . Please reopen the issue if it is not fixed by restic 0.17.3 which will be released in the next few days.
