### ISSUE TITLE
Build Restic on DragonFlyBSD

### ISSUE THREAD

**Issue by vmlemon** [restic/restic#5131]
Output of `restic version`
--------------------------

```
root@:~/restic # ./restic version
restic 0.17.2-dev (v0.17.2-257-g408ec41a1) compiled with go1.23.2 on dragonfly/amd64
```

`uname -a` reports:

```
root@:~/restic # uname -a
DragonFly  6.4-RELEASE DragonFly v6.4.0-RELEASE #54: Fri Dec 30 09:06:50 PST 2022     root@pkgbox64.dragonflybsd.org:/usr/obj/usr/src/sys/X86_64_GENERIC  x86_64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Whilst I realise that DragonFlyBSD is an incredibly niche platform, it was fairly easy, to add very generic support for it, as a derivative of FreeBSD, with official GoLang support, so it could help Restic become accessible, to an additional user base, if we also supported it.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Out of curiosity, I decided to try building the latest checkout of Restic, on DragonFlyBSD, after noticing that the GoLang toolchain supports it, and seeing that no-one else has mentioned it, in the issue tracker.

On the first attempt, I received the following error:

```
root@:~/restic # ./buildr.sh ^M^M
go run build.go^M
warning: GOPATH set to GOROOT (/root/go) has no effect^M
warning: GOPATH set to GOROOT (/root/go) has no effect^M
# github.com/restic/restic/internal/fs^M
internal/fs/node.go:25:24: undefined: nodeFillGenericAttributes^M
internal/fs/node.go:28:26: undefined: nodeFillExtendedAttributes^M
internal/fs/node.go:259:12: undefined: nodeRestoreExtendedAttributes^M
internal/fs/node.go:266:12: undefined: nodeRestoreGenericAttributes^M
build failed: exit status 1^M
exit status 1^M
*** Error code 1^M
^M
Stop.^M
make: stopped in /root/restic^M  
```
After copying internal/fs/node_aix.go, to internal/fs/node_dragonfly.go, and tweaking it, I was able to produce a working binary, that runs on DragonFlyBSD/x86-64, albeit without support for extended attributes.

If there's any interest, I can supply this change, as a pull request?

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I'm surprised by how easy to work with, the Restic codebase is, despite having very limited knowledge of GoLang.

**Comment by MichaelEischer** [comment]
> After copying internal/fs/node_aix.go, to internal/fs/node_dragonfly.go, and tweaking it, I was able to produce a working binary, that runs on DragonFlyBSD/x86-64, albeit without support for extended attributes.

That sounds simple enough that we can risk adding yet another platform. Support for the platform will be limited though, if something platform-specific is broken then it will likely stay that way until someone contributes a fix. In particular, our CI tests only cover Linux/macOS/Windows, that is the other platforms may break without us noticing. All other platforms are just built but not tested by the CI: https://github.com/restic/restic/blob/408ec41a1d1d9f94e9eca78f34a9f86aed84e18f/.github/workflows/tests.yml#L210-L240 .

**Comment by vmlemon** [comment]
After setting up a new DragonFlyBSD VM, installing the latest release of Go (involves ```curl https://dl.google.com/go/go1.23.3.dragonfly-amd64.tar.gz --output - | tar xvf -```, moving the "go" directory to /usr/local, and adding "/usr/local/go/bin", to the PATH, in the "set path()" stanza of ~/.cshrc, on DragonFlyBSD), it looks like I can build the latest master branch version of Restic:
<img width="487" alt="image" src="https://github.com/user-attachments/assets/1f8b3f5b-662c-4f65-8ff5-3f599d9e54b4">

Creating a new repository, with an empty password seems to work properly:
<img width="487" alt="image" src="https://github.com/user-attachments/assets/8b00aed9-bec5-470c-95c0-22120a2b6ae0">

I'm also able to backup /root, without any surprises:
<img width="487" alt="image" src="https://github.com/user-attachments/assets/157d9f17-4227-4c58-8982-d67e966bd93d">

Running a backup of / seems mostly uneventful:
<img width="487" alt="image" src="https://github.com/user-attachments/assets/e8873461-5af1-4b8b-9d43-ee687019fe90">

It looks like /proc/PID/dbregs, and /proc/PID/fpregs files are larger than their advertised 0-byte, or 512-byte sizes, being system-generated, but I'm able to stop a backup, and start a new backup, excluding /proc, and everything finishes, without errors.

I also needed to exclude /root/TestRepository, since Restic tries to archive its own active repository, and I haven't tried to do anything, involving BSD flags (DragonFlyBSD has "chflags", but there doesn't seem to be many objects, other than /tmp (has the "noscache" flag, according to ```ls -lo /```), that use them).

I'm unsure of what'd be necessary, to plumb in FUSE mounting support, if it's possible, and DragonFlyBSD 6.4.0 doesn't seem to ship any obvious way of manipulating extended attributes, out-of-the-box (but, the manual pages, for TAR, and CURL at least mention flags exercising them), so I guess we can call this the basics of support, for the time being...

**Comment by MichaelEischer** [comment]
Thanks a lot for testing!

> involving BSD flags (DragonFlyBSD has "chflags", but there doesn't seem to be many objects, other than /tmp (has the "noscache" flag, according to `ls -lo /`), that use them).

There's no BSD flags support so far. But that's already sort of tracked via https://github.com/restic/restic/issues/4076 .

> I'm unsure of what'd be necessary, to plumb in FUSE mounting support, if it's possible

There is already fuse support for freebsd, so maybe dragonflybsd could just work.

> DragonFlyBSD 6.4.0 doesn't seem to ship any obvious way of manipulating extended attributes, out-of-the-box (but, the manual pages, for TAR, and CURL at least mention flags exercising them)

[pkg/xattr doesn't have DragonFlyBSD support](https://github.com/pkg/xattr/blob/master/xattr_bsd.go), so maybe the xattr syscall just don't exist there?

> so I guess we can call this the basics of support, for the time being...

Yes that is definitely good enough for now. I'll close this issue for now. We can figure out additional details later on if someone (or you) takes care of it.
