### ISSUE TITLE
https://github.com/restic/restic/blob/master/VERSION needs updating

### ISSUE THREAD

**Issue by ilyagr** [restic/restic#5132]
After installing `brew install --HEAD restic`, I get:

```console
$ restic version
restic 0.17.2-dev (v0.17.2-257-g408ec41a1) compiled with go1.23.3 on darwin/arm64
```

It should use 0.17.3, not 0.17.2. I think you forgot to update https://github.com/restic/restic/blob/master/VERSION.

**Comment by rawtaz** [comment]
It's all in the patch-release branch and will be merged to master shortly. Thanks for keeping track on things :)
