### ISSUE TITLE
Restic times out when using Rclone and forced SSH commands

### ISSUE THREAD

**Issue by colans** [restic/restic#5139]
Output of `restic version`
--------------------------

* `restic 0.17.3 compiled with go1.23.3 on linux/amd64`

And Rclone:

```
rclone v1.68.1
- os/version: ubuntu 24.04 (64 bit)
- os/kernel: 6.1.87-0-virt (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.1
- go/linking: static
- go/tags: none
```

What backend/service did you use to store the repository?
---------------------------------------------------------

* [BackUpScale](https://backupscale.com/) (new Production system)

Problem description / Steps to reproduce
----------------------------------------

With this invocation:

* `sudo restic --verbose=2 --option rclone.program="ssh jdoe@10.42.2.135 rclone -vvv" --repo rclone:location1:bucketname/username/repo2 --password-file /etc/restic/password snapshots`

...and this in `authorized_keys`:

* `command="/usr/local/bin/rclone-wrapper",no-port-forwarding,no-X11-forwarding,no-pty ssh-ed25519 AAAA...`

This is what's actually getting run from the wrapper:

* `/usr/bin/rclone serve restic --stdio --b2-hard-delete --drive-use-trash=false --verbose --append-only location1:bucketname/username/repo2`

I get this result, after taking a minute to timeout:

> Fatal: unable to open repository at rclone:location1:bucketname/username/repo2: error talking HTTP to rclone: Get "http://localhost/file-11924593322512373101": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Expected behavior
-----------------

Now, if I take out the forced command (and only have `no-port-forwarding,no-X11-forwarding,no-pty ssh-ed25519 AAAA...`) everything works fine:

```
repository 721e53fe opened (version 2, compression level auto)
created new cache in /root/.cache/restic
```

This works pretty much right away, so it's not that the timeout needs to be extended in the other scenario.

However, I have this working on an older system with a VM.  Both systems are running the latest Rclone & Restic releases.  I'm trying this on a Kubernetes pod, but bypassing the load balancer and `go-mmproxy`, and connecting directly to one of the pods on the VPN.

Do you have any idea what may have caused this?
-----------------------------------------------

Seems to be caused by the forced command, but it works elsewhere, and should work theoretically.  Unfortunately, I can't get much more when running both commands with debugging turned on.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

If it weren't for Restic, I wouldn't be able to work on BackUpScale!  So thank you all!!

**Comment by MichaelEischer** [comment]
Hmm, there isn't anything obviously wrong with the setup on first glance. There are a few minor differences compared to the description at https://ruderich.org/simon/notes/append-only-backups-with-restic-and-rclone though. I'm a bit worried that the wrapper script somehow corrupts either stdin or stdout.

What happens if you manually open an ssh connection to the server using the restricted ssh key? Is there _any_ human readable output  there?

**Comment by MichaelEischer** [comment]
You could also set the environment variable `DEBUG_LOG=restic.log` and check whether there's anything useful in there.

**Comment by colans** [comment]
> I'm a bit worried that the wrapper script somehow corrupts either stdin or stdout.

Thanks for the tip!  That was it.  I have some log entries that get sent from there, but as I haven't set up the endpoint yet, I just turned them into `echo` statements, which were corrupting the stream.  Taking them out fixed it.

**Comment by colans** [comment]
Sorry for what turned out to be a non-bug report.
