### ISSUE TITLE
can't build from source: github.com/Backblaze/blazer@v0.6.1: checksum mismatch

### ISSUE THREAD

**Issue by catgirlconspiracy** [restic/restic#5154]
Building restic from source with an empty `~/go` fails.

Problem description / Steps to reproduce
----------------------------------------

```shell_session
$ rm -rf ~/go
$ git clone https://github.com/restic/restic.git
Cloning into 'restic'...
remote: Enumerating objects: 79292, done.
remote: Counting objects: 100% (471/471), done.
remote: Compressing objects: 100% (212/212), done.
remote: Total 79292 (delta 271), reused 418 (delta 234), pack-reused 78821 (from 1)
Receiving objects: 100% (79292/79292), 67.02 MiB | 5.39 MiB/s, done.
Resolving deltas: 100% (51195/51195), done.
$ cd restic
$ git rev-parse HEAD
1133498ef80762608f959df41d303f7246fff04f
$ go run build.go
go: downloading github.com/anacrolix/fuse v0.3.1
go: downloading github.com/restic/chunker v0.4.0
go: downloading github.com/spf13/cobra v1.8.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading go.uber.org/automaxprocs v1.6.0
go: downloading golang.org/x/sync v0.8.0
go: downloading golang.org/x/term v0.25.0
go: downloading github.com/Backblaze/blazer v0.6.1
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azcore v1.16.0
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.8.0
go: downloading github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.4.0
verifying github.com/Backblaze/blazer@v0.6.1: checksum mismatch
	downloaded: h1:8EIXx5tQJt7vZWPxlYJv987dDwINuQiAr0hg8PsOGZs=
	go.sum:     h1:xC9HyC7OcxRzzmtfRiikIEvq4HZYWjU6caFwX2EXw1s=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
build failed: exit status 1
exit status 1
$
```

It works on another computer that had the dependency downloaded, but apparently something caused the checksum on that repository to change. :woman_shrugging: 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I've been using restic for several years and it's always gotten me the files back that I needed. I love being able to have confidence in my backups :heart:

**Comment by wplapper** [comment]
in file go.mod find the line "github.com/Backblaze/blazer" (for version 0.17.3-dev it is line 8). Replace the version string "v0.6.1" with "v0.7.1". Run "go mod tidy". Done!

**Comment by MichaelEischer** [comment]
The go module proxy still contains the original repository version. However, it appears like the tag was moved one commit earlier: https://github.com/Backblaze/blazer/issues/20

**Comment by MichaelEischer** [comment]
The upstream issue has been fixed. restic 0.17.3 can again be built without the go module proxy
