### ISSUE TITLE
minio update broke compatibility with Google Cloud Storage

### ISSUE THREAD

**Issue by ckemper67** [restic/restic#520]
I updated to the latest source version of restic and I cannot access my restic repository on Google Cloud Storage anymore. I started to investigate and it seems the problem started with the upgrade of the minio version in change. If I checkout the tree just prior to the commit 1b50d55 everything works fine. If I checkout at a0ab9f2 (after the merge) I get errors.

Another weirdness that may help with the investigation: It seems that some operations still work when using http instead of https

I will try to play with the vendoring to see if rolling back to an earlier version of minio helps us to pinpoint the issue.

## Output of `restic version`
restic compiled manually
compiled at unknown time with go1.6.2

restic is checked out at a0ab9f2. It might be interesting to somehow incorporate that into the restic version output. 

## Expected behavior
bin/restic snapshots -r s3:https://storage.googleapis.com/<bucket>/<prefix>

Getting a listing of the snapshots in my restic repository
## Actual behavior
bin/restic snapshots -r s3:https://storage.googleapis.com/<bucket>/<prefix>

Error message:
A header or query you provided requested a function that is not implemented.

## Steps to reproduce the behavior
(checkout after the merge of the latest minio update)
git checkout a0ab9f2 -f 
gb build
bin/restic snapshots -r s3:https://storage.googleapis.com/<bucket>/<prefix>
(fails: A header or query you provided requested a function that is not implemented.)
(without https this works for some reason)
bin/restic snapshots -r s3:http://storage.googleapis.com/<bucket>/<prefix>
(succeeds)

(checkout prior to the latest minio update)
git checkout 60f1fbe -f
gb build
bin/restic snapshots -r s3:https://storage.googleapis.com/<bucket>/<prefix>
(succeeds)
bin/restic snapshots -r s3:http://storage.googleapis.com/<bucket>/<prefix>
(succeeds)

**Comment by fd0** [comment]
Thanks for reporting this. Maybe someone from minio can have a look? ping @harshavardhana

**Comment by ckemper67** [comment]
I traced it to https://github.com/minio/minio-go/commit/7fbac252ae617eb72091c37d16eed901ca1d6475 and specifically setting the `Expect` header. If I take out that change at restic's HEAD I can still connect to GCS.

**Comment by fd0** [comment]
That's weird, thanks for investigating. I've pinged @harshavardhana, maybe he can take a look.

**Comment by harshavardhana** [comment]
> A header or query you provided requested a function that is not implemented.

This error indicates that 100-continue is not implemented by GCS, may be as part of signature calculation as well. Will validate.

**Comment by ckemper67** [comment]
As far as I can tell it is only implemented for POST. I tried to limit it
to POST and PUT and I got an error from the PUT as well.

**Comment by moho1** [comment]
I had the same problem and updated the minio source in my local repo. With the current minio-go master everything seems to work fine.
