### ISSUE TITLE
Question - How many requests does Restic make to S3 when using the S3 backend?

### ISSUE THREAD

**Issue by jerrac** [restic/restic#524]
## How many requests does Restic make to S3 when using the S3 backend?

I've been trying to calculate how much it would cost to backup to S3. Space used isn't hard, but how do I figure out how many PUT, COPY, POST, GET, etc. requests restic will make?

The backup I did today to my external hard drive had about 1.4 million items.

    [2:38:17] 100.00%  31.932 MiB/s  296.147 GiB / 296.146 GiB  1405642 / 1405271 items  2 errors  ETA 0:00 
    duration: 2:38:17, 31.93MiB/s

But does restic make a request per item? Or does it do something else?

What about browsing the repo, or restoring it?

http://aws.amazon.com/s3/pricing/ has the pricing I've been checking with. Infrequent Access Storage is a lot cheaper for storage, but requests are a lot more expensive. So, if restic makes a lot of requests, it might be better to use normal storage. But if it doesn't, then IA would be good...

## Output of `restic version`
restic 0.1.0 (v0.1.0-548-g795e3d5)
compiled at 2016-05-14 07:41:18 with go1.6.1

**Comment by fd0** [comment]
Hi, thanks for bringing this up. At the moment, it's hard to say how many requests restic really sends to the server. Files are split into blobs (if they are large enough), these blobs are then pooled together in pack files and uploaded to the server. The number of blobs in a pack depends mostly on the individual blob size, there are upper limits for the pack size (16MiB) and number of blobs (2000 I think).

For accessing s3 we're using the [minio-go](https://github.com/minio/minio-go), which abstracts the access even more. It may happen that for larger uploads multiple requests are carried out. How that counts towards the number of request I don't have any idea.

At the moment this is not a use case restic is optimized for. For example the index (which blobs are stored where) is not cached locally, but downloaded from the backend before each backup.

If this answers your question, please close the issue.

**Comment by jerrac** [comment]
Hmm... Ok. Thanks for answering.

**Comment by mdwhatcott** [comment]
You could use aws cloudtrail to track the requests made to a test aws account:

https://aws.amazon.com/cloudtrail/

**Comment by tomwaldnz** [comment]
I'm curious if the index files are still downloaded from S3 for every backup. That could be a lot of data for large backups, and AWS bandwidth is expensive.

It would probably reduce bandwidth to run a backup to a local disk, then use "aws s3 sync" to push the changed files up to S3. That way only changed files are pushed. I don't know how smart the sync is, if it sends the whole changed file or a diff.

**Comment by fd0** [comment]
Since 0.8.0 (current version is 0.9.1) we have a local metadata cache, so the number of requests during backup was reduced *a lot* since 2016 :)
