### ISSUE TITLE
restic -r check / error for tree

### ISSUE THREAD

**Issue by K-Quadrat** [restic/restic#528]
Today i compiled actual restic version and made a new snapshots, after that restic -r check and i got some errors for tree

I tried to solve that problem but i could't, so i removed repository and Initialize a new one, but error message is still the same when i do restic -r check.

## Output of `restic version`
restic 0.1.0 (v0.1.0-550-ge1b5593)
compiled at 2016-06-05 11:30:54 with go1.6

## Actual behavior
Create exclusive lock for repository
Load indexes
Check all packs
Check snapshots, trees and blobs
error for tree 4dc35584:
  tree 4dc35584: node "command_socket" with invalid type "socket"
  tree 4dc35584: node "iface_socket" with invalid type "socket"
repository contains errors

## Steps to reproduce the behavior
restic -r check

**Comment by fd0** [comment]
Hey, thanks for the report, you found a bug in the checker code!

**Comment by aut0** [comment]
I have a similar problem. restic -r check yields:

Create exclusive lock for repository
Load indexes
Check all packs
pack ebb2b680921d23a9f26d66ecf5ec0542bb9e8628c2ba6bbf560e8f3bd1fd208d: not referenced in any index
pack 578dd5d96780823cfb6ce1dd8f9fb710dc1f0e158c270d925ae5c79e3a9f3849: not referenced in any index
pack 4a949e84ebef1f6027c6b991e5310cf666ae175aa5bdef09a2a05a097a2a3f9f: not referenced in any index
pack b0c50f0a483ae0117c8bd5c5ffd913d3e87f69d7fa0929708b2a8752349f2d0c: not referenced in any index
pack 1d09fcfeabdc052d158d880ed11ae3e8c9169638f899b24ee696b49ccf7bd7ac: not referenced in any index
Check snapshots, trees and blobs
error for tree 738c45c1:
  tree 738c45c1: node "daemon.sock" with invalid type "socket"
error for tree 475cc30f:
  tree 475cc30f: node "daemon.sock" with invalid type "socket"
repository contains errors
