### ISSUE TITLE
Feature-request: Snapshot summary

### ISSUE THREAD

**Issue by hmsdao** [restic/restic#530]
Something I would love to have is some sort of snapshot summary.
An example is Robocopy for windows outputs a summary after a job has finished.

example:

```
               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :     35514         1     35513         0         0         0
   Files :    353825        49    353775         0         1         0
   Bytes : 357.875 g  101.35 m 357.776 g         0   125.5 k         0
   Times :  43:31:28   0:02:28                       0:00:00  43:28:59


   Speed :              713367 Bytes/sec.
   Speed :              40.819 MegaBytes/min.

   Ended : Wed Jun 08 05:32:27 2016
```

This would be nice if that was saved together with the snapshot also, so you could ask for the summary of a snapshot.

An example could be something like this:

```
restic -r <REPO> snapshots --summary <SNAPSHOT-ID>
```

**Comment by fd0** [comment]
Good idea, thanks for the suggestion.

**Comment by fd0** [comment]
We've added a summary at the end of the backup run, so I'm closing this issue for now. Feel free to add further comments, thanks!
