### ISSUE TITLE
backend/s3: Unnecessary copy on member access

### ISSUE THREAD

**Issue by mappu** [restic/restic#532]
Hi,

In `restic/backend/s3/s3.go` the `Load`, `Save`, `Stat` methods operate with value receiver instead of with pointer receiver. So the struct `s3` is copied on every method access.

Is this safe to convert to pointer receiver?

Or was it intentional? The main item in the struct is `*minio.Client` which, as a pointer member, won't have its data copied anyway.

**Comment by fd0** [comment]
Hi, thanks for pointing this out. I think that this will not impact performance at all, neither will the memory usage rise or fall when changing this. But you have a point, it's at least inconsistent. If you like, please create a pull request.

**Comment by fd0** [comment]
I'll close this PR for now, I don't think it's relevant.
