### ISSUE TITLE
Building fails: import cycle not allowed

### ISSUE THREAD

**Issue by noqqe** [restic/restic#534]
I tried to build restic on ubuntu 12.04 with go version go1.6.2 linux/amd64

## Output of `restic version`

none...

## Expected behavior

It builds :)

## Actual behavior

```
# go run build.go
import cycle not allowed
package main
        imports fmt
        imports errors
        imports runtime
        imports runtime/internal/atomic
        imports unsafe
        imports runtime
```

## Steps to reproduce the behavior

Try to build it. 

Not entirely sure why this happens.

**Comment by fd0** [comment]
Hi, thanks for raising this issue. I'm unable to reproduce it in the environment you described, and to be honest I'm quite puzzled why this error happens. The error tells us that `main` (from restic) imports `fmt` (go stdlib), which imports a bunch of other libs from the stdlib. And this leads to an import cycle. Which should not happen, because it's the most widely tested library for Go in existence.

I've got a few things for you that may help debugging this:
 * Paste the output of: `echo $GOROOT; echo $GOPATH; go env`
 * How did you install Go?
 * Into which folder did you check out the restic repo?

**Comment by noqqe** [comment]
Hi,

I installed go by downloading the prebuild packages. The Go version delivered by the OS was very old - so i preferred this option.

```
 wget https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz
 tar xfvz go1.6.2*
 mv go /usr/local/go
```

Go env output> 

```
# echo $GOROOT; echo $GOPATH; go env
/root/goroot/
/usr/local/go/
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/go/"
GORACE=""
GOROOT="/root/goroot"
GOTOOLDIR="/root/goroot/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

The folder i checked out restic was just my home dir .. in this case /home/ubuntu/restic. Does this matter?

**Comment by fd0** [comment]
Something on your system is messing with the variable `$GOROOT`... try the following:

    unset GOROOT
    go run build.go

I can't see why `GOROOT` needs to be set at all in your situation. Does that help?

**Comment by noqqe** [comment]
Oh wow that solved it. I'm quite new to go. 

Im not sure why I set that - Something during the installation / usage of the system go version told me to do so. At least in my memory.

Anyways, sorry for opening a bug created by my own misconfiguration and thanks for the quick help!

**Comment by fd0** [comment]
I'm glad to help. If you stumble upon the page which instructed you to set `GOROOT`, it'd be good to fix that.

At least now people who have the same error can find a solution...

**Comment by Thouheed** [comment]
I'm getting the above error while building go as

import cycle not allowed
package main
        imports fmt
        imports errors
        imports internal/reflectlite
        imports runtime
        imports internal/bytealg
        imports internal/cpu
        imports runtime
Kindly help me with this error
