### ISSUE TITLE
hubiC backend integration

### ISSUE THREAD

**Issue by acidsploit** [restic/restic#536]
Feature request: Any chance we will see hubiC integration in the future as a storage backend?

I'm happy to help in testing code if needed.

**Comment by fd0** [comment]
Thanks, for the suggestion, I'll have a look.

**Comment by smeinecke** [comment]
Hi! I'd like to use restic with hubic but it seems as if the difference between the public swift/openstack API and hubic is not as small as espected. SVFS (https://github.com/ovh/svfs) which is also go based has an extra tool to generate additional login credentials for hubic.

Did someone already successfully use restic with hubic?

**Comment by vovcacik** [comment]
@smeinecke As far as I read the difference is only in authentication. [Rclone][] got it working with Hubic so you can take a look at the whole process.

[Rclone]: https://rclone.org/

**Comment by n0npax** [comment]
seems hubiC just works with the swift endpoint. I was able to create and restore a backup from the hubiC using authentication based on tokens.
I exported `OS_STORAGE_URL` and `OS_AUTH_TOKEN` and set `--repo` like:
``` -r swift:https://lb1.hubic.ovh.net/v1/AUTH_<SOME_NUMBERS> ```

**Comment by fd0** [comment]
Oh, that's nice, thanks for the feedback!

**Comment by ifedorenko** [comment]
FYI, I started to work on hubiC backend (https://github.com/ifedorenko/restic/tree/hubic). Mostly copy&paste authentication logic from [SVFS hubic.go](https://github.com/ovh/svfs/blob/v0.9.1/svfs/hubic.go), then let existing Swift backend do the rest. Appears to work in my limited testing on Linux and OSX.

If somebody wants to try
1. sign up for hubiC free account
2. register hubiC application and run [hubic-application.rb](https://github.com/ovh/svfs/blob/v0.9.1/scripts/hubic-application.rb) as explained in  [SVFS hubic documentation](https://github.com/ovh/svfs/blob/v0.9.1/docs/HubiC.md)
3. export "mount options" returned by hubic-application.rb as `HUBIC_AUTH` and `HUBIC_TOKEN` environment variables
4. use `hubic:container-name:/[prefix]` repository url formal, e.g. `hubic:default:/restic`

I'll appreciate feedback about the code and general functionality. Beware this is the first time I used go, so expect dump mistakes ;-)

**Comment by fd0** [comment]
@ifedorenko Is this needed? @n0npax reported that restic works with hubiC with the Swift endpoint, didn't that work for you?

**Comment by ifedorenko** [comment]
Swift tokens generated by hubiC expire in 24 hours. While it is possible to tell the users to script token request&renewal themselves, I think it is better to have restic do it automatically. (Note that the proposed change implements hubiC authentication only, everything else is delegated to existing swift backend implementation).

**Comment by ifedorenko** [comment]
Actually, for operations that run longer than 24 hours, like `restic check --read-data` I mentioned in the other issue, restic will have to implement token renewal.

**Comment by vovcacik** [comment]
@ifedorenko the token renewal is must have, at least for automated backups. I've already mentioned this, but Rclone got has this sorted out, including token renewal.

**Comment by ifedorenko** [comment]
My proposed change does handle token renewal.

**Comment by breml** [comment]
I just tested successfully the extended version from @ifedorenko (https://github.com/ifedorenko/restic/commit/3e1a766d9afc6d7933dddf8230b978a7fec183b0). Thank you for the good work, I would like to see this change merged into restic.

**Comment by fd0** [comment]
As always with a new backend, we need to figure some stuff out first:
 * Is there a free (or sponsored) test account we can use to run the integration tests on Travis and do development/debugging? Without a way to test and debug stuff, we won't merge a new backend.
 * Is hubic a protocol, or a service? Is it offered by someone else besides OVH?
 * What's the additional value besides using `rclone mount` and using the local backend with restic?

Did I forget anything?

**Comment by rawtaz** [comment]
I think "who will maintain the code" and not less importantly "who will maintain the test account and other stuff needed to support code maintenance", both in the long run, are important questions too.

Even if someone were to pay for that other chinese backend you commented on in another issue, what happens if that person stops doing so at some point? We'd sit here with a backend to maintain but without support for it.

**Comment by tamalsaha** [comment]
At the risk of sounding crazy, have you considered adding a plugin support for restic backend? Kubernetes project uses gRPC based plugin system. Also https://github.com/hashicorp/go-plugin exists. This way user's can maintain plugin for backends outside the main repo.

**Comment by breml** [comment]
@fd0 I am not an expert in regards to hubic, but still here my 2cts:

* Yes, there is a free test account with 25GB space (https://hubic.com/de/offers/)
* As far as I understand hubic it has a special authentication mechanism, but other than that it is compatible to OpenStack Swift. I guess, in this combination it is only provided by OVH.
* Additional value: The only thing I could think of is, there is only one tool needed for the backup and in my experience it is more stable to have a tool directly talk to the API than have a fuse mount (especially small network hickups are quite problematic with mount points).
* Setup is easy. You only need to set two ENV vars (works more or less the same way as Backblaze B2 for example).
* Can't say something about the maintenance, because I have not written the code.

**Comment by fd0** [comment]
> At the risk of sounding crazy, have you considered adding a plugin support for restic backend?

No, you don't sound crazy and I have indeed thought about it. I'm just not finished yet ;)

I had a discussion with @ncw (author of rclone) to maybe use rclone as a backend for restic, but that's also still at the "idea" phase.

**Comment by jbruggem** [comment]
Probably :). I just tried it a few days ago and it worked fine.

**Comment by fd0** [comment]
Nice, I'll close this issue for now. Thanks for the hint!
