### ISSUE TITLE
Unknown CI environment

### ISSUE THREAD

**Issue by coocheenin** [restic/restic#539]
I will wonder if someone has similar bug.
After installing (via go get) I try to see the version.

`restic version `

and got _unknown CI environment_ warning. Also other commands like backup, init etc generates this message.

## Output of `restic version`
unknown CI environment

golang1.6.2 on linux 386

**Comment by fd0** [comment]
Hi, thanks for raising this issue. restic cannot be installed using `go get`, please follow the instructions in [the README](https://github.com/restic/restic#build-restic). The reasons for this are outlined in issue https://github.com/restic/restic/issues/368#issuecomment-163735737

**Comment by coocheenin** [comment]
Ah, ok! Understand. And i have to say thank you for so useful software you have created.

**Comment by fd0** [comment]
Heh, thanks! I'm glad you took the time to report this ;)
