### ISSUE TITLE
Add tags to snapshots

### ISSUE THREAD

**Issue by fd0** [restic/restic#55]

**Comment by mappu** [comment]
[snapshot-comments-v1.diff.txt](https://github.com/restic/restic/files/133561/snapshot-comments-v1.diff.txt) here's patch.

Use optional `-c` when performing backup to set comment on snapshot. Comment is optional (default emptystring). Comment is displayed in `restic snapshots` output.

**Comment by fd0** [comment]
Could you please create a PR, so we can do a proper code review? If you need assistance, please let me know :)

**Comment by fd0** [comment]
Hey, any news here? If you need any assistance creating a PR, please let me know! You can also drop by `#restic` on `irc.freenode.net` if you like :grinning:

**Comment by fawick** [comment]
#463 is the relevant PR.

**Comment by fd0** [comment]
Thanks for your help!

This is not exactly the same, the code by @mappu (#463) adds a `comment` field, which is slightly different from the way I imagined the feature: Tags (or labels) can be specified multiple times, whereas the comment field is just one string. So we'll keep this issue open for now.

**Comment by mappu** [comment]
Thank you @fawick .

This patch has some downsides (hidden paths in snapshots output during there's no control over output format, ...). It should be very easy to take idea from this patch and make a tags system instead, but, display of tag on `snapshots` output should be discussed.
