### ISSUE TITLE
Release strategy

### ISSUE THREAD

**Issue by fd0** [restic/restic#556]
I've just released 0.2.0 since the last release happened almost a year ago in August 2015. I'm thinking about switching to a time-based release schedule, e.g. at least one release every six months. What do you think?

ping @fw42

**Comment by rawtaz** [comment]
What's the purpose of a release in your opinion? Is it more about getting work-done-so-far out or is it more about releasing a new version when you feel it truly is a new version?

I think maintenance, i.e. minor releases, could be done regularly, but major releases that's less about maintenance and more about new features should perhaps be done when 


30 jul 2016 kl. 11:51 skrev Alexander Neumann <notifications@github.com>:

**Comment by fd0** [comment]
In my opinion, releases have the following purposes:
 * Create stable code points that everybody can refer to without having to hunt for the commit ID
 * Add new features and communicate (via semantic versioning) the compatibility of these features (major vs. minor version)
 * Have some kind of a heartbeat, show people who do not follow the master branch that the project is still alive

**Comment by fd0** [comment]
So, no more comments, I'm going to close this issue. I'll try to regularly release new versions of restic.
