### ISSUE TITLE
Question about restore behavior in Linux

### ISSUE THREAD

**Issue by Animedium** [restic/restic#561]
Hi,

I was testing backup and restore with different permission options to file and I found restore option not consistent with Linux behavior.

So case is that 'User B' is owner of the file and 'User A' is making backup and restore with restic.
File have permissions set to 666 so 'User A' can backup this file with no problem.

Problems start with restore. As Linux user 'User A' can do various operations on that file and he can even remove it.
But during restore file cannot be replaced as long as user that make restore is not owner of the file.

Here is table with tests results

```
- -w- --- ---   User A : User A     will be restored
- --- -w- ---   User A : User A     will not be restored
- --- --- -w-   User A : User A     will not be restored
- -w- --- ---   User A : User B     will be restored
- -w- -w- -w-   User B : User A     will not be restored ?
- -w- -w- -w-   User B : User B     will not be restored ?
```

I would like to ask if this was designed that way or it should not work like that?

**Comment by fd0** [comment]
Hi, thanks for opening an issue. I'm not sure I understood you correctly: You're testing restoring of file modes when the owner of the file is a different user than the  one executing the backup, is that correct?

Could you please write up a few commands that show this behavior?

**Comment by Animedium** [comment]
As I wanted to show you example problem became more complex.
So we have file file "test01.txt" on which we perform tests. File is owned by "testuser".

Few commands to get file with required properties:
```
sudo chown testuser:testuser test01.txt
sudo chmod 666 test01.txt
ls -al | grep test01.txt
-rw-rw-rw- 1 testuser testuser   69 sie  3 13:22 test01.txt
```

Then different user, lets call it "ansible" come and wan't to do backup and restore.
First backup, no error here.
```
restic -r /temp/Restic/Repo backup /temp/Restic/Data/Files01/Dir01/test01.txt
enter password for repository: 
using parent snapshot ab2c7788
scan [/temp/Restic/Data/Files01/Dir01/test01.txt]
scanned 0 directories, 1 files in 0:00
[0:00] 100.00%  0B/s  69B / 69B  0 / 1 items  0 errors  ETA 0:00 
duration: 0:00, 0.00MiB/s
snapshot e1a1c87c saved
```

Then restore. Here is error. Operation not permitted. File was not changed at all operation.
```
restic -r /temp/Restic/Repo restore latest -t /temp/Restic/Data/Files01/Dir01 --path /temp/Restic/Data/Files01/Dir01/test01.txt
enter password for repository: 
restoring <Snapshot e1a1c87c of [/temp/Restic/Data/Files01/Dir01/test01.txt] at 2016-08-03 13:17:39.230116178 +0200 CEST> to /temp/Restic/Data/Files01/Dir01
error for /temp/Restic/Data/Files01/Dir01/test01.txt: create node: Lchown: lchown /temp/Restic/Data/Files01/Dir01/test01.txt: operation not permitted
```

Still as a user "ansible" I can remove file "test01.txt" and then restore it. During restore the information as above is writted but file did not return to original, backuped version.
```
ls -al | grep test01.txt
-rw------- 1 ansible ansible   69 sie  3 13:22 test01.txt
```

**Comment by Animedium** [comment]
So we have file file "test01.txt" that is owned by "ansible" user on which we perform tests.
```
ll | grep test01.txt

-rw-rw-rw- 1 ansible ansible   69 sie  3 13:27 test01.txt
```

First backup, no error here.
```
restic -r /temp/Restic/Repo backup /temp/Restic/Data/Files01/Dir01/test01.txt

enter password for repository: 
using parent snapshot ab2c7788
scan [/temp/Restic/Data/Files01/Dir01/test01.txt]
scanned 0 directories, 1 files in 0:00
[0:00] 100.00%  0B/s  69B / 69B  0 / 1 items  0 errors  ETA 0:00 
duration: 0:00, 0.00MiB/s
snapshot e1a1c87c saved
```

Then few commands to get file with required properties. Change owner and permissions.
```
sudo chown testuser:testuser test01.txt
ls -al | grep test01.txt

-rw-rw-rw- 1 testuser testuser   69 sie  3 13:22 test01.txt
```

Then restore. Here is error. Operation not permitted. File was not changed at all during operation.
```
restic -r /temp/Restic/Repo restore latest -t /temp/Restic/Data/Files01/Dir01 --path /temp/Restic/Data/Files01/Dir01/test01.txt

enter password for repository: 
restoring <Snapshot e1a1c87c of [/temp/Restic/Data/Files01/Dir01/test01.txt] at 2016-08-03 13:17:39.230116178 +0200 CEST> to /temp/Restic/Data/Files01/Dir01
error for /temp/Restic/Data/Files01/Dir01/test01.txt: create node: Lchown: lchown /temp/Restic/Data/Files01/Dir01/test01.txt: operation not permitted
```

Still as a "ansible" user I can remove file "test01.txt" and then restore it. 
```
ls -al | grep test01.txt

-rw-rw-rw- 1 ansible ansible   69 sie  3 13:22 test01.txt
```

**Comment by fd0** [comment]
The restore command at the moment does not alter existing files, especially it does not delete existing files. This is a safety feature. I'm going to close this issue for now, feel free to add further comments. Thanks!
