### ISSUE TITLE
Memory leak when backing up over http2 to minio behind Nginx

### ISSUE THREAD

**Issue by markuslindenberg** [restic/restic#565]
## Output of `restic version`

restic 0.2.0
compiled at 2016-08-07 23:53:44 with go1.7rc5

## Expected behavior

Backing up to an existing repository is quick, memory usage doesn't grow while backup is running.

## Actual behavior

Backing up to an existing repository is very slow while memory usage grows until the process is killed (either by the OOM killer or manually).

## Steps to reproduce the behavior

A verifiable TLS certificate is needed for the server to reproduce as http2 requires TLS and verification currently cannot be switched off.

### Setup minio Server

* Debian 8 on amd64
* `nginx-full` 1.9.10-1~bpo8+3 from [Debian Backports](https://backports.debian.org/)
* `openssl` and `libssl1.0.0` 1.0.2h-1~bpo8+1 from Backports
* Minio (Version 2016-07-13T21:46:05Z)
* Let' s Encrypt ECDSA certificate acquired using [acmetool](https://github.com/hlandau/acme)

Replace `HOSTNAME` with the host's FQDN. 

#### Acquire certificate

```
acmetool quickstart --expert
acmetool want HOSTNAME
```

#### Configure Nginx

/etc/nginx/sites-available/HOSTNAME
```
server {
	listen [::]:443 ssl http2;
    listen 443 ssl http2;
    server_name HOSTNAME;

	ssl_certificate /var/lib/acme/live/HOSTNAME/fullchain;
	ssl_certificate_key /var/lib/acme/live/HOSTNAME/privkey;

	ssl_session_timeout 5m;
    ssl_session_cache shared:SSL:10m;
    # ssl_dhparam /etc/ssl/private/dhparam.pem;
    ssl_protocols TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
    ssl_ecdh_curve prime256v1;
    ssl_prefer_server_ciphers on;
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

	gzip off;
	server_tokens off;
	
	location / {
		include proxy_params;
		proxy_buffering off;
		proxy_request_buffering off;
		proxy_http_version 1.1;
		client_max_body_size 0;

		proxy_pass http://[::1]:9000;
	}
}
```

```
ln -s /etc/nginx/sites-available/HOSTNAME /etc/nginx/sites-enabled/HOSTNAME
systemctl reload nginx
```

#### Start minio

```
mkdir /tmp/minio
minio server --address [::1]:9000 /tmp/minio
```

### Setup backup client

The backup client is a Debian 8 amd64 with about 5.8GB of data in it's filesystem. 

```
export RESTIC_REPOSITORY=s3://HOSTNAME/test
export RESTIC_PASSWORD=secret
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...

restic init

# first backup runs fine
restic backup -e /proc/ -e /dev/ -e /sys/ -e /run/ -e /tmp/ /

# second backup is slow and has memory leak 
restic backup -e /proc/ -e /dev/ -e /sys/ -e /run/ -e /tmp/ /
```

The problem can be mitigated by disabling http2 in Nginx. Without http2, backup is fast (i/o bound).

**Comment by fd0** [comment]
Thanks for your comprehensive report!

**Comment by fd0** [comment]
I can reproduce this. The behavior only occurs when data is read from the repo, e.g. in an incremental backup or when running `check`. For a backup of about 1.7GiB, running `restic check --read-data` uses 1.4GiB RAM.

**Comment by fd0** [comment]
I've found a connection leak which may have another cause for this behavior, can you please test the current master branch again? Thanks!

**Comment by moho1** [comment]
I can reproduce this issue in the wild when accessing Google Cloud Storage.
> restic 0.2.0 (v0.2.0-179-g6f5bf45)
compiled at 2016-08-29 16:27:41 with go1.7

Setting the enviroment variable GODEBUG=http2client=0 avoids the issue.

A crashdump just before the OOM killer can be found at https://gist.github.com/moho1/77bb2e8ae83f4ba7954310162e43e582 maybe it helps in any way.

**Comment by fd0** [comment]
@moho1 could you give the code in #598 (branch `update-minio-go`) a try and report back?

**Comment by fd0** [comment]
@moho1 reported yesterday that with the changes in #598 (merged to master now) the memory consumption is much better. Could you try again @markuslindenberg?

**Comment by markuslindenberg** [comment]
Yes, will try asap. Sorry for being unresponsive.

**Comment by markuslindenberg** [comment]
Problem seems gone. I can backup over http2 and memory consuption basically doesn't grow while the backup is running. 

Thanks for the awesome handling of this issue. :+1:

**Comment by fd0** [comment]
Great, then I'll close this issue as "resolved".
