### ISSUE TITLE
sftp backend fails in path, if used from Windows

### ISSUE THREAD

**Issue by viric** [restic/restic#568]
## Output of `restic version`
current master

## Expected behavior
restic backup -r sftp://remote//path/to/go
(back up normally)

## Actual behavior
\path\to\go\data does not exist

The same command, if run from linux, works fine.

**Comment by viric** [comment]
The backslashes are introduced by "filepath.Clean" in https://github.com/restic/restic/blob/master/src/restic/backend/sftp/sftp.go#L255

**Comment by fd0** [comment]
Oh, good catch, thanks!

**Comment by fd0** [comment]
can you please give the code in the branch `fix-568` a try and report back?
