### ISSUE TITLE
User Interface: Snapshot Expire Options?

### ISSUE THREAD

**Issue by fd0** [restic/restic#572]
Hi,

I'd like to collect some opinions on the user interface for removing snapshots from the repo. The `prune` command is nearly done (see #518), the last remaining part is a good user interface.

What the command does is listing all snapshots, then going through all the data blobs stored in the repo and removing (by repacking) those that aren't referenced any more. It's not as efficient as it could be (and it's rather slow), but it works and is correct (as far as I can see).

So I just need to add a function that lists the snapshots and removes those that are to be deleted. All options described below are applied to snapshots grouped by host and list of directories separately. If you have snapshots from two different hosts in the repo, the snapshots for each host will be processed separately, e.g. if only the last 10 snapshots should be kept, this means 10 backups per host. The same is applied for list of dirs, if you have snapshots for `/foo` and `/bar, /baz`, you'll end up with the last 10 backups of `/foo` and the last 10 backups of `/bar, /baz`.

I've come up with the following options for `prune`:
 * `--host=X` only remove snapshots that were created for host `X` (to be specified in combination with the other options)
 * `--keep-last=n` by using this option restic will only remove snapshots if there are more than `n` for each host/dirs.
 * `--keep-all=DUR` keep all backups made during `DUR`, e.g. `24h`, this will not touch any backups made in the last 24 hours.
 * `--keep-hourly=DUR` keep hourly backups for `DUR`, which can for example be `2d`. This instructs restic to go through the snapshots in reverse chronological order (newest to oldest) from the current time two days back (48 hours). For each hour, it removes all but the last backup. If we have three backups at 23:12, 23:30 and 23:55 restic will remove all but the last.
 * `--keep-daily=DUR` keep daily backups for `DUR`, e.g. `2w`. This will keep at most one backup per day for the last two weeks.
 * `--keep-monthly` and `--keep-yearly` are treated the same.
 * @Thor77 on IRC suggested another setting `--max-repo-size`, which is harder to implement (because it requires traversing all snapshots) and will maybe implemented later.

Is this enough/sufficient?

Is it a good idea to have defaults for the values (e.g. 24h hourly snapshots, 4w daily, 1y monthly, 10y yearly) so the user doesn't have to bother specifying the command-line options every time? Or is that too invasive, because just running `prune` without any options will probably remove some snapshots/data?

I'm looking forward to your comments! :smiley:

**Comment by Thor77** [comment]
I wouldn't go for defaults, it's too invasive imho and can lead to unexpected data-loss.
Additionally I would realy like to see a `--dry-run` option that just lists snapshots which would get deleted.

**Comment by fd0** [comment]
Oh, good point, that's a really good idea. Thanks!

**Comment by paulvt** [comment]
I actually like obnam's way where you can prune with a "keep policy" either on the command line or in a configuration file... I used to use something like:
```
keep = 7d,13w,24m,60y
```
which keeps the most recent 7 daily, 13 weekly, 24 monthly, and 60 yearly snapshots.
See also: http://code.liw.fi/obnam/manual/obnam-manual.en.html#forgetting-old-backup-generations

**Comment by fd0** [comment]
I like the idea to split this into the `forget` command, which deletes snapshots, and the `prune` command, which frees data in the repo.

**Comment by paulvt** [comment]
That makes sense. I believe that also --keep=2 deletes the most two recent snapshots. Ideal for redoing an backup (so you can remove that VM image file that really shouldn't have gone into the backup ;)).

**Comment by fd0** [comment]
Hm, I don't understand the semantics here: For `keep=2` I'd expect that everything else is deleted but the last two snapshots.

I'd also like to accept snapshot IDs as parameters, so you can run `restic forget 123456` and only remove the snapshot with that ID.

This also nicely fits with the policy of "don't remove anything by default when run without any parameters" (either you have to specify a policy, or a snapshot ID to remove), and I really like the name `forget`, because it makes clear what happens when run.

**Comment by paulvt** [comment]
Yes, sorry, haha. That would be counter-intuitive indeed. It's indeed forget <uid> or forget with policy.
I forgot snapshot UIDs in obnam are just integers.

**Comment by fd0** [comment]
So, now I've implemented the code to forget snapshots according to a policy. I really like the idea how obnam handles forgetting. restic now allows specifying how many e.g. daily snapshots to keep, where days without a backup are ignore. This way, `forget` won't remove any snapshots when no new snapshots are created.

**Comment by paulvt** [comment]
I think the note about ignoring days without backups for "keep daily" should be added to the docs! :)
I do weekly backups and it took me some time to figure out why --keep-daily=14 was trying to keep 3 months worth of snapshots, until I reread your comment her.

Btw, from daily to monthly is quite a step (factor 30).  I am wondering why you didn't add that one too?

**Comment by fd0** [comment]
Hm, I think the documentation is clear enough:
```
--keep-daily n for the last n days which have one or more snapshots, only keep the last one for that day.
```

But we can add a section which explains it.

Your last sentence is missing something, I think you meant something like: "From daily to monthly backups is a big step, why didn't you add weekly snapshots to keep?". This is a great question, because I've actually implemented that. It's in the code, but missing in the documentation. I'll fix that.

**Comment by paulvt** [comment]
You are right, I just overlooked it. The weird interaction of --keep-daily with weekly backups just surprised me, but it is understandable with regards to safety.

Ok, great! I just went by the docs, I see it now in `restic forget --help`.

**Comment by fd0** [comment]
I've added PR #576 which adds more documentation.

**Comment by paulvt** [comment]
Thanks! Gonna test/use it now.

**Comment by fd0** [comment]
Great, let me know if anything comes up. Btw, I'm also available in #restic on irc.freenode.net, if you like IRC.
