### ISSUE TITLE
Optimize repository layout

### ISSUE THREAD

**Issue by fd0** [restic/restic#58]
At the moment, all blobs of a type (data, snapshot, tree) are stored within one directory. Change that and create prefix-subdirs, e.g. store the blob `aec070645fe53ee3b3763059376134f058cc337247c978add178b6ccdfb0019f` at
```
ae/c0/aec070645fe53ee3b3763059376134f058cc337247c978add178b6ccdfb0019f
```

**Comment by scoddy** [comment]
tested, closing issue.
