### ISSUE TITLE
Display amount of data deleted after prune

### ISSUE THREAD

**Issue by mafgh** [restic/restic#581]
When pruning, restic logs the amount of data in use and amount of blobs still in use but not the amount of data deleted:

```
...
repository contains 1160 packs (166518 blobs) with 5.134 GiB bytes
...
found 166260 of 166518 data blobs still in use
```

A couple of ideas on how to log it:

1. found 166260 of 166518 data blobs still in use, deleting NNN blobs (J.JJJ GiB)
1. done, deleted NNN blobs, J.JJ GiB

**Comment by fd0** [comment]
Thanks for the suggestion, that sounds like a good idea.
