### ISSUE TITLE
Failure to remove broken packs < 2048 bytes

### ISSUE THREAD

**Issue by viric** [restic/restic#586]
## Output of `restic version`
restic 0.2.0 (v0.2.0-150-g9fd941f)
compiled at 2016-08-25 14:15:31 with go1.6

## Actual behavior

$ restic prune
enter password for repository: 
counting files in repo
building new index for repo
unable to list pack 265caccc: Load at -2048 failed: sftp: "Bad message" (SSH_FX_BAD_MESSAGE)
[0:12] 100.00%  2779 / 2779 files
repository contains 2778 packs (25624 blobs) with 13.957 GiB bytes
...

$ restic check --read-data
enter password for repository: 
Create exclusive lock for repository
Load indexes
Check all packs
pack 265caccc23f871267ae31ed69407857a6f44e06fc9f90f4b89c71640af1fbc00: not referenced in any index

The pack file should be removed, but it is not due to the sftp seek failure.

## Steps to reproduce the behavior
The 265caccc file is 453 bytes long (less than 2048, so it cannot be seeked 2048 ahead from the end).

**Comment by fd0** [comment]
Ah, this should be fixed by 9f752b8306b95c57bd267bae47f2c8462551331b
