### ISSUE TITLE
Resume interrupted backups

### ISSUE THREAD

**Issue by fd0** [restic/restic#59]
When a backup is interrupted and restarted later, restic writes all data again, newly encrypted, because the index is written at the end so restic doesn't know about what blobs have already been stored.

This can be fixed for example by regularly (e.g. every X minutes or every Y files or so) uploading a preliminary index that is removed after the next preliminary index (which is a superset of the first one) has been uploaded. Once the final index was successfully uploaded, all preliminary indexes from this session are removed.

Connects #243

**Comment by cocodrino** [comment]
hi...it's possible right ow resume a backup???...I'm interested on this feature...thank you

**Comment by fd0** [comment]
Yes, restic will automatically resume a backup roughly where it left of.
