### ISSUE TITLE
Panic during prune command to minio S3 repo

### ISSUE THREAD

**Issue by zcalusic** [restic/restic#603]
restic 0.2.0 (v0.2.0-202-gfae65eb)
compiled at 2016-09-04 10:30:20 with go1.7

I expected prune command to finish, instead it panicked. The remote repository is minio server, the latest version as of this morning.

Running restic prune command, I got:
```
counting files in repo
building new index for repo
[1:41] 100.00%  7660 / 7660 packs
repository contains 7660 packs (211352 blobs) with 33.663 GiB bytes
processed 211352 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 7 snapshots
[23:02] 100.00%  7 / 7 snapshots
found 154108 of 211352 data blobs still in use
will delete 2615 packs and rewrite 1080 packs
500 Internal Server Error
client.PutObject
restic/backend/s3.s3.Save
	/tmp/restic-build-958875747/src/restic/backend/s3/s3.go:182
restic/backend/s3.(*s3).Save
	<autogenerated>:2
restic/repository.(*Repository).savePacker
	/tmp/restic-build-958875747/src/restic/repository/packer_manager.go:120
restic/repository.(*Repository).SaveAndEncrypt
	/tmp/restic-build-958875747/src/restic/repository/repository.go:232
restic/repository.Repack
	/tmp/restic-build-958875747/src/restic/repository/repack.go:62
main.CmdPrune.Execute
	/tmp/restic-build-958875747/src/cmds/restic/cmd_prune.go:202
main.(*CmdPrune).Execute
	<autogenerated>:45
github.com/jessevdk/go-flags.(*Parser).ParseArgs
	/tmp/restic-build-958875747/src/github.com/jessevdk/go-flags/parser.go:278
github.com/jessevdk/go-flags.(*Parser).Parse
	/tmp/restic-build-958875747/src/github.com/jessevdk/go-flags/parser.go:154
main.main
	/tmp/restic-build-958875747/src/cmds/restic/main.go:34
runtime.main
	/home/zcalusic/src/go.googlesource.com/go/src/runtime/proc.go:183
runtime.goexit
	/home/zcalusic/src/go.googlesource.com/go/src/runtime/asm_amd64.s:2086
```

**Comment by fd0** [comment]
Hey, thanks for opening an issue about it. This seems to be a server issue, restic tries to save data to the server, and the server returned `500 Internal Server Error`. Could you please have a look at the server side and see if there's an error in the log file there?

Your data is safe by the way: restic will first rewrite still needed data, and only afterwards remove unneeded data. So you can just start the prune process again.

Is it maybe possible that the storage location for the minio server is full?

**Comment by zcalusic** [comment]
Yeah, I noticed that Internal Server Error and checked logs on the minio side immediately, but there are no errors reported there, I'm afraid. I'm already running the the second prune in the hope the next run will finish successfully. And I'm also monitoring remote disk usage, because it is really quite low on disk space, the reason I'm doing the prune. I see that now I have more packs/blobs and some duplicates also:
```
repository contains 7743 packs (211352 blobs) with 34.018 GiB bytes
processed 220271 blobs: 8919 duplicate blobs, 363.395 MiB duplicate
```

**Comment by fd0** [comment]
Ok, let's look at the server side what's happening there. The duplicate data is expected since restic will (due to safety reasons) FIRST create copies of still needed data and only THEN remove data :)

I'm also planning to retry requests to the backend that failed, this is tracked in #353 for all backends.

**Comment by zcalusic** [comment]
Yeah, makes sense to be extra careful, very good design! 

I'll see if I can debug this further and provide more useful data.

And tnx for the help!

**Comment by fd0** [comment]
You can also drop by on https://gitter.im/minio/minio, the people there are very helpful.

**Comment by zcalusic** [comment]
Oh, well. As soon as I found out how to enable debug logging from minio, the very next prune command was successful. I guess I'll just leave the debug settings on, in case it happens again in the future. But, no additional information to report at this time.

**Comment by fd0** [comment]
So I'll close this issue for now. Retrying a failed backend operation will be tracked in #353, and this smells like it's a potential problem in the minio server. Please add any new information you find, thanks!

**Comment by zcalusic** [comment]
IMHO, I think that end users should never be exposed to stack traces. It looks like the application crashed, and actually it is. :)

So, even if this is 100% minio fault, restic could be more user friendly, so you might keep the issue open just to remember to properly handle errors in this part of code. Just my 2¢.

**Comment by fd0** [comment]
You're right, and I'm working on that. All errors that are not yet handled by restic will be returned as a stack trace, so that we can notice and handle them. For this case, it'll be done in #353. :)

**Comment by zcalusic** [comment]
Ah, yes, I could've figured it myself that #353 will also fix this issue.

Keep up the good work! :+1:
