### ISSUE TITLE
panic: close of closed channel in restic/repository test

### ISSUE THREAD

**Issue by ckemper67** [restic/restic#605]
I have seen this test fail, but it does not seem reproducible.

## Output of `restic version`
restic compiled manually
compiled at unknown time with go1.6.2 on darwin/amd64

commit e443454c4bc7323a3e5a402af6abb78e1f133e7f
Author: Alexander Neumann <alexander@bumpern.de>
Date:   Sun Sep 4 15:46:50 2016 +0200

    Add OS and Arch to 'version' output

## Expected behavior
Tests pass

## Actual behavior

```
# restic/repository
panic: close of closed channel

goroutine 1501 [running]:
panic(0x2080c0, 0xc820b88040)
       	/usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
restic/repository.closeIfOpen(0xc820dd6540)
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/repository/parallel.go:16 +0x53
restic/repository.FilesInParallel.func1(0xc82000a240, 0xc820dd65a0, 0x32c0a0, 0xc820dd6540, 0xc820dd6600)
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/repository/parallel.go:55 +0x144
created by restic/repository.FilesInParallel
       	/Users/ckemper/work/src/github.com/restic/restic/src/restic/repository/parallel.go:63 +0x17c
restic/list
```

## Steps to reproduce the behavior
gb test

**Comment by fd0** [comment]
Hu, this is strange! I'm not seeing this bug locally, nor has Travis?

**Comment by fd0** [comment]
I've reworked this test and it hasn't occurred on Travis for some time, so I'm closing this issue.
