### ISSUE TITLE
kernel is oom-ing on first backup

### ISSUE THREAD

**Issue by supermarin** [restic/restic#612]
## Output of `restic version`
```
restic 0.2.0 (v0.2.0-246-g791f73e)
compiled at 2016-09-10 21:34:06 with go1.7.1 on linux/amd64
```
## Expected behavior
Backup completed

## Actual behavior
Killed by oom

## Steps to reproduce the behavior
clone, build, init, backup

**Comment by fd0** [comment]
Hey, thanks for reporting this. I acknowledge the issue, restic uses too much RAM. It was already reported as #526, so I'm closing this issue as a duplicate.

**Comment by fd0** [comment]
Could you tell me a bit about your setup? How much data was there to be saved? Which backend did you use?

**Comment by supermarin** [comment]
VPS,  pretty small one (512 mb ram). Around 35GB of data

**Comment by fd0** [comment]
Local backend? or s3?

**Comment by supermarin** [comment]
all locally on a hard drive
