### ISSUE TITLE
Invalid -r value causes explosion

### ISSUE THREAD

**Issue by codekoala** [restic/restic#622]
## Output of `restic version`

    restic 0.2.0 (v0.2.0-285-g98b012a)
    compiled at 2016-09-17 23:05:39 with go1.7.1 on linux/amd64

## Expected behavior
Warn the user that the specified repository is invalid.

## Actual behavior

    Open
    restic/errors.Wrap
    	/tmp/restic-build-415280905/src/restic/errors/wrap.go:22
    restic/backend/local.Open
    	/tmp/restic-build-415280905/src/restic/backend/local/local.go:41
    main.open
    	/tmp/restic-build-415280905/src/cmds/restic/global.go:305
    main.GlobalOptions.OpenRepository
    	/tmp/restic-build-415280905/src/cmds/restic/global.go:272
    main.CmdSnapshots.Execute
    	/tmp/restic-build-415280905/src/cmds/restic/cmd_snapshots.go:75
    main.(*CmdSnapshots).Execute
    	<autogenerated>:50
    github.com/jessevdk/go-flags.(*Parser).ParseArgs
    	/tmp/restic-build-415280905/src/github.com/jessevdk/go-flags/parser.go:315
    github.com/jessevdk/go-flags.(*Parser).Parse
    	/tmp/restic-build-415280905/src/github.com/jessevdk/go-flags/parser.go:185
    main.main
    	/tmp/restic-build-415280905/src/cmds/restic/main.go:34
    runtime.main
    	/usr/lib/go/src/runtime/proc.go:183
    runtime.goexit
    	/usr/lib/go/src/runtime/asm_amd64.s:2086

## Steps to reproduce the behavior
    restic -r /asdfasdfasdf snapshots

**Comment by fd0** [comment]
Hey, thanks for reporting this. restic obviously shouldn't print a stack trace but a nicer error.

**Comment by codekoala** [comment]
Works great! Thanks!!
