### ISSUE TITLE
panic: shorthand redefinition on restic restore

### ISSUE THREAD

**Issue by schorsch3000** [restic/restic#633]
I'm running `restic restore <snapshotsId from restic snapshots>`

## Output of `restic version`
restic version
restic 0.2.0
compiled at 2016-09-29 09:50:51 with go1.6.3 on linux/amd64
build from 3114d41cb757

## Expected behavior

I expect restic to restore my backup 

## Actual behavior
````
# restic restore aa1b779d --target /tmp
panic: shorthand redefinition

goroutine 1 [running]:
panic(0x91d0c0, 0xc82000faa0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc82009cbd0, 0xc8201600a0)
	/tmp/restic-build-672564917/src/github.com/spf13/pflag/flag.go:673 +0xcae
github.com/spf13/cobra.(*Command).mergePersistentFlags.func2.2(0xc8201600a0)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:1247 +0x7d
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc82009cd80, 0xc82015d538)
	/tmp/restic-build-672564917/src/github.com/spf13/pflag/flag.go:236 +0x85
github.com/spf13/cobra.(*Command).mergePersistentFlags.func2(0xe10de0)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:1249 +0xbd
github.com/spf13/cobra.(*Command).mergePersistentFlags.func2(0xe10560)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:1252 +0xed
github.com/spf13/cobra.(*Command).mergePersistentFlags(0xe10560)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:1256 +0x297
github.com/spf13/cobra.stripFlags(0xc820019e90, 0x3, 0x3, 0xe10560, 0x0, 0x0, 0x0)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:367 +0x8b
github.com/spf13/cobra.(*Command).Find.func1(0xe10560, 0xc820019e90, 0x3, 0x3, 0x7, 0x0, 0x0, 0x0)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:427 +0x7d
github.com/spf13/cobra.(*Command).Find.func1(0xe10de0, 0xc82000a060, 0x4, 0x4, 0x20, 0x0, 0x0, 0x0)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:435 +0x2b5
github.com/spf13/cobra.(*Command).Find(0xe10de0, 0xc82000a060, 0x4, 0x4, 0xc82000fa20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:457 +0x183
github.com/spf13/cobra.(*Command).ExecuteC(0xe10de0, 0xc82015def0, 0x0, 0x0)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:677 +0x1e6
github.com/spf13/cobra.(*Command).Execute(0xe10de0, 0x0, 0x0)
	/tmp/restic-build-672564917/src/github.com/spf13/cobra/command.go:648 +0x2d
main.main()
	/tmp/restic-build-672564917/src/cmds/restic/main.go:41 +0x147
````
btw: i'm able to restore bachups via mount.

**Comment by schorsch3000** [comment]
this also happens with a build from the v.0.2.0 tag
`# restic version
restic 0.2.0
compiled at 2016-09-29 09:50:51 with go1.6.3 on linux/amd64
`
with the same repository

**Comment by fd0** [comment]
Thanks for reporting this, it is a bug and was introduced with #631. I'm sure that it does not happen with version 0.2.0, since the `pflag` library (which caused the panic) was only introduced in #631. Could you check again?

**Comment by schorsch3000** [comment]
Seems like i got confused with calling `./restic` which was the tagged 0.2.0 and `restic` which was the one build from  3114d41.

Sorry.


The one build from the 0.2.0 tag is able to restore, that part of the report was wrong.

i don't need to live bleeding edge on my backup-system, but i really like to have the 
`restic forget --keep-*` parameters working, which aren't availible in 0.2.0.

Thanks, Dirk

seeing that the #631 is quite young, i'll should be fine to use a build from eeec0d63c2c6afb61fc8acf0e03b3387d51e5b09 until this is fixed, right?

**Comment by fd0** [comment]
You can either use an older commit, or just wait a few minutes until #635 is merged :)

I'll probably release 0.3.0 in a couple of days so you'll get the `forget` and `prune` commands in a released version.

**Comment by schorsch3000** [comment]
Perfect, i'll upgrade once 0.3.0 is released then, i plan to not restore the next few days :)

**Comment by schorsch3000** [comment]
I've just tested a build from  eb94395: i'm able to restore again.
