### ISSUE TITLE
No bug, just feedback

### ISSUE THREAD

**Issue by schorsch3000** [restic/restic#634]
Hi,
beside that bug #633 i've reported earlier today i'm quite happy using restic now.
We manage about 25 servers that actually need a backup, most of our server don't have application-data that needed to be backed up, and they can bei re-bootstraped within minutes.
We used to use the backup-gem, which seems to be quite popular in the chef-world.
It does full-backups every time.

We managed, in the same infrastructure, to get our first backup done 25 times faster with restic than with the backup gem.
Followup-backups, depending on the amount of changed date again 10 to 20 times faster.

Thank you.

**Comment by fw42** [comment]
you should consider open sourcing your chef integration code for restic, might be useful for others too

**Comment by schorsch3000** [comment]
I've thought about that today.
At the Moment the integration takes some shortcuts, matching our environment, and some dirty-ones too.
The dirty-ones will be fixed soon for sure.
I'm not sure about the company-open-source-policy, but i will investigate.

**Comment by fd0** [comment]
Great, thanks for the feedback! The restore process at the moment is single-threaded and therefore quite slow, although it seems that this is already fast enough for you ;)

"Incremental" backups will be much faster once there's a client-side metadata cache...

**Comment by schorsch3000** [comment]
The measured timings are for backup, not restore.
we had only one accident that needed restore in the last 3 years, so restore-performance only really affects the restore-tests which are also automatically.
Also, restoring the backup-gem way is faster than backup, since you can pipe things together, but its far from fast. So, everything is fine :)

**Comment by fd0** [comment]
Yeah, for smaller restores (just a few files or dirs) you can also use the fuse mount, I don't know if you've discovered that already, but it's really handy!

**Comment by schorsch3000** [comment]
Yes, that's what i've checked first after i've discovered #633 to prove the repository is integer.
That's really sweet, a fast way to see what that file looked like last week.

**Comment by schorsch3000** [comment]
While speaking of fuse-mount, is there a way to get the folder-name somewhere near the output of `restic snapshots`? having multiple directories with different schedules in one repository and to have only timestamps as identifier is hard :)

**Comment by fd0** [comment]
If you have a good idea on how to improve the structure of the fuse mounted directories, please feel free to open an issue! At the moment I don't have a good idea ;) It's just a matter of implementing it.

**Comment by schorsch3000** [comment]
i'm not sure either, maybe something like 
`$host/$directory/timestamp`,
but that would imply replacing `/` with something else or getting confused if there are backups that are subfolders of another.

like 
`/var`
and `/var/www`

that would result in 

`/myhost/var/timestamp`
and
`/myhost/var/www/timestamp`

so having $timestamp AND www in `/var/`

Having a format-string for fusemount on the other hand seems like a overkill.

That's why i've asked, maybe someone else had a brilliant idea beforehand.

**Comment by fd0** [comment]
Thanks for the suggestions. It also bugs me that the fuse mount is a rather ugly list of timestamps, so I'm looking for ideas to improve thaht.

**Comment by pvgoran** [comment]
At the very least, tags (as lexicographically-sorted list) could be added to the name structure, like this: `tag1,tag2,tag3:timestamp` (possibly replace the semicolon with something for better compatibility).

**Comment by fd0** [comment]
Let's continue this in #636, please add your ideas there.
