### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by fd0** [restic/restic#64]
Like `virsh`

```
restic> help
backup
restore
list
```

**Comment by fw42** [comment]
Is this really useful? What does this give you that you are missing right now?

**Comment by fd0** [comment]
Executing mutliple actions without having to reenter the password.

**Comment by andrewchambers** [comment]
tab completion within the shell might be useful too. especally for completing id's.

**Comment by fw42** [comment]
> Executing mutliple actions without having to reenter the password.

On a day-to-day basis, what use case do you have where you need to run multiple commands in a row often? And can't you just use the RESTIC_PASSWORD environment variable for that?

> tab completion within the shell

That can be implemented as a bash/zsh script as well, seems more useful to me

**Comment by fd0** [comment]
* Florian Weingarten <notifications@github.com> wrote:
> > Executing mutliple actions without having to reenter the password.
> On a day-to-day basis, what use case do you have where you need to run multiple commands in a row often? And can't you just use the RESTIC_PASSWORD environment variable for that?

I can use the environment variable, but this would end up in my shell
history, I dislike that. A common workflow is: Listing a snapshot,
searching for a file and afterwards restoring it. This would be much
easier without having to type the password three times.

> > tab completion within the shell
> 
> That can be implemented as a bash/zsh script as well, seems more useful to me

Good idea.

**Comment by fd0** [comment]
I'll close this for now.
