### ISSUE TITLE
no ID found / type not specified

### ISSUE THREAD

**Issue by stuertz** [restic/restic#640]
## Output of `restic version`
restic 0.3.0 (v0.3.0-6-g6f72164)
compiled at 2016-10-10 15:48:02 with go1.6.3 on windows/amd64

## Expected behavior
[15:50:55,65] g:\restic>g:\restic\restic -r g:\restic\ forget /d 7 /w 4 /m 12 
forget some backups

## Actual behavior
[15:50:55,65] g:\restic>g:\restic\restic -r g:\restic\ forget /d 7 /w 4 /m 12 
no ID found
restic.init
	c:/Temp/restic-build-193909127/src/restic/backend_find.go:7
main.init
	c:/Temp/restic-build-193909127/src/cmds/restic/table.go:46
runtime.main
	C:/Go/src/runtime/proc.go:177
runtime.goexit
	C:/Go/src/runtime/asm_amd64.s:1998

Also interesting: 
  restic.exe  -r g:\restic list
leads to 
  type not specified

But doing backups still works :-)

Did I oversee any incompatible changes to the repository?

## Steps to reproduce the behavior
Run restic 0.3 on a restic 0.2 repository on windows

**Comment by fd0** [comment]
Thanks for reporting this, the error message is not so great. You're using the wrong calling convention, please use:
```
$ restic forget -d 7 -w 4 -m 12
```

In your case, restic tries to find a snapshot with the ID `/d`, which obviously fails.

**Comment by fd0** [comment]
I've improved the error message in #641 to:
```
$ bin/restic forget /d 7 /w 4 /m 12
argument "/d" is not a snapshot ID, ignoring
argument "7" is not a snapshot ID, ignoring
argument "/w" is not a snapshot ID, ignoring
argument "4" is not a snapshot ID, ignoring
argument "/m" is not a snapshot ID, ignoring
cound not find a snapshot for ID "12", ignoring
```

**Comment by stuertz** [comment]
Thx for pointing this out. Works fine.
