### ISSUE TITLE
No documentation of which metadata is backed up

### ISSUE THREAD

**Issue by chneukirchen** [restic/restic#647]
Currently one has to look into the source to find out which metadata is backed up:

```
    Name       string      `json:"name"`
    Type       string      `json:"type"`
    Mode       os.FileMode `json:"mode,omitempty"`
    ModTime    time.Time   `json:"mtime,omitempty"`
    AccessTime time.Time   `json:"atime,omitempty"`
    ChangeTime time.Time   `json:"ctime,omitempty"`
    UID        uint32      `json:"uid"`
    GID        uint32      `json:"gid"`
    User       string      `json:"user,omitempty"`
    Group      string      `json:"group,omitempty"`
    Inode      uint64      `json:"inode,omitempty"`
    Size       uint64      `json:"size,omitempty"`
    Links      uint64      `json:"links,omitempty"`
    LinkTarget string      `json:"linktarget,omitempty"`
    Device     uint64      `json:"device,omitempty"`
```

times seem to have nanosecond resolution. I don't know if ctime is restored.

In particular, xattrs (incl. POSIX acl and Linux capabilities), and ext[234] special flags are not backed up or restored as far as I can see.

I see no mention of efficient extraction of sparse files (this is quite easy to do when chunking).

**Comment by fd0** [comment]
You're right, that's not documented yet. Most default attributes are saved and restored, ctime is not restored, and no extended attributes like ACL or capabilities are saved. Sparse files are not handled in a special way yet, and aren't restored. I hope that answers the questions until we have documented this properly.

**Comment by mgumz** [comment]
@fd0 do you see the documentation somewhat around https://github.com/restic/restic/blob/master/doc/design.rst#trees-and-data ?

**Comment by fd0** [comment]
Ah, hm. That doesn't sound like the right place, because it is already outdated. For example, the ACL/extended attributes are not included in the Design document. Maybe a list in the manual would be good as a reference. We can amend that when new data is saved.

**Comment by mgumz** [comment]
https://github.com/restic/restic/blob/master/doc/manual.rst#under-the-hood-browse-repository-objects ?

**Comment by nicolas17** [comment]
According to #25 it seems like xattrs are saved now. Is this documented anywhere?

**Comment by fd0** [comment]
No, not yet. Somebody needs to step up and add a section to the manual :)
