### ISSUE TITLE
restore fails to restore files in a read-only directory

### ISSUE THREAD

**Issue by fold0** [restic/restic#656]
Version: restic 0.3.0 (v0.3.0-19-g6b88d3b)

When a snapshotted directory originally had no write permission (e.g. mode 0555), restic fails to restore any files in that directory: restore first creates the directory and restores its original permissions, and later fails to create any files in it because of missing write permission.

Stack trace:

error for <censored>: open <censored>: permission denied
OpenFile
restic.Node.createFileAt
	/tmp/restic-build-502800658/src/restic/node.go:199
restic.(*Node).CreateAt
	/tmp/restic-build-502800658/src/restic/node.go:109
restic.(*Restorer).restoreNodeTo
	/tmp/restic-build-502800658/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
	/tmp/restic-build-502800658/src/restic/restorer.go:53
restic.(*Restorer).restoreTo
	/tmp/restic-build-502800658/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
	/tmp/restic-build-502800658/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
	/tmp/restic-build-502800658/src/restic/restorer.go:65
restic.(*Restorer).RestoreTo
	/tmp/restic-build-502800658/src/restic/restorer.go:122
main.runRestore
	/tmp/restic-build-502800658/src/cmds/restic/cmd_restore.go:135
main.glob.func13
	/tmp/restic-build-502800658/src/cmds/restic/cmd_restore.go:23
github.com/spf13/cobra.(*Command).execute
	/tmp/restic-build-502800658/src/github.com/spf13/cobra/command.go:599
github.com/spf13/cobra.(*Command).ExecuteC
	/tmp/restic-build-502800658/src/github.com/spf13/cobra/command.go:689
github.com/spf13/cobra.(*Command).Execute
	/tmp/restic-build-502800658/src/github.com/spf13/cobra/command.go:648
main.main
	/tmp/restic-build-502800658/src/cmds/restic/main.go:41
runtime.main
	/usr/local/go/src/runtime/proc.go:111
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1721

**Comment by fd0** [comment]
Oh, interesting corner case, thanks for bringing this up! It's indeed a bug, the order needs to be changed (create, save files, then restore original permissions at the end).

**Comment by wscott** [comment]
Not sure if Go lets you talk to syscalls directly, but in C you can
open(O_CREAT) a file with read-only permissions directly and then write the
contents.  Saves some extra syscalls.

**Comment by fd0** [comment]
This case is a bit different: A files is to be restored in a directory that has already been set to read only.

**Comment by cfcs** [comment]
@fd0 just a note: if you're running `restic` as root on a machine with unprivileged users, you'd probably want to make sure the "default permissions" (before restoration of permissions) are sane and do not allow interfering with the backup (perhaps mask out `group+others` with the initial umask?).

**Comment by dimejo** [comment]
I think #1536 fixed this. Did you try this with the new restic release (v0.8.2)?

**Comment by gerardbosch** [comment]
No, I'm using 0.7.3, the one that comes with Ubuntu 17.10, but thanks to notice it. As I saw the issue "Open" I thought it was not fixed yet. Thanks.

**Comment by rawtaz** [comment]
*A lot* has happened since 0.7.3. If I were you I would either make whoever managed those Ubuntu packages update them, or use my own binaries for restic (sometimes one can't use only packages). Restic is actively developed, it deserves more up to date versions than that :-)

**Comment by fd0** [comment]
Oh, thanks for the hint, this is indeed solved by #1536. @gerardbosch just in case you didn't know: restic is a single, statically linked binary that you can easily build yourself (or even use the binary releases).

I'm going to close this issue, please feel free to add a comment if it does not work as expected with 0.8.2, thanks!
