### ISSUE TITLE
Keeping snapshots without a tag

### ISSUE THREAD

**Issue by teknico** [restic/restic#661]
I'd like to keep some old snapshots that have no tag. Would it be possible to allow the "forget" command to exclude snapshots, rather than just tags? Thanks.

**Comment by Niondir** [comment]
What if you just add a tag to that old snapshot? And if that's not possible, having a feature to change tags might be a good solution :) That you could have a tag like `keep-forever`

**Comment by teknico** [comment]
@Niondir, I hinted at that on IRC, but @fd0 seemed to prefer excluding snapshots directly.

**Comment by fd0** [comment]
I'm not against adding tags to snapshots per se, but it will require some thought on how to design the user interface. The snapshot IDs will also change, which shouldn't be a problem.

The easiest solution here is to implement keeping specified snapshot IDs, that's very little code, so it's the obvious solution.

**Comment by fd0** [comment]
We've just merged #855 which adds the `tag` command, it can be used to add tags to snapshots :)

**Comment by rawtaz** [comment]
I suggest we close this issue. One can easily add and edit tags on snapshots, including old ones like @teknico had a use case to keep. I also think the forget command is fine as it is - it can work with policies and indirectly also tags, there's no need for it to also be able to identify snapshots.

**Comment by fd0** [comment]
I agree, please feel free to add further comments. Thanks!
