### ISSUE TITLE
Restic docker container

### ISSUE THREAD

**Issue by Niondir** [restic/restic#664]
Not a bug, just something nice I like to contribute. I really like restic and start using it for some of my projects. Since I'm setting up a lot of infrastructure using Docker, I created a Docker container to simplify docker based backups.

It helps a lot to setup regular backups, especially when Docker is already in place. Just specify your repo location, credentials and a cron expression.

You can find the project here:
https://github.com/Lobaro/restic-backup-docker

Maybe you can link it somewhere in the projects documentation. Else I'm happy about any feedback.

**Comment by fd0** [comment]
Thanks for your contribution! I'd like to create some sort of "contributions" section, either in the manual or in the README, as a place for linking projects. I just need time to do that ;)

**Comment by jniggemann** [comment]
I'd go forward with that, but IMHO we need to establish a common vision first.
Right now, the README and the manual share a lot of information that we have to keep in sync manually.  

The README is what people see first when they go to the github project page. Ideally, it would contain only information relevant to the project itself:
* Introduction (as is)
* Changelog (ideally, a link to the changelog)
* License (as is)
* News (as is)
* Authors (could be a link, too)

Contributions could be a chapter in the manual.

Ideas?

**Comment by jniggemann** [comment]
IMHO it would be good to add this to the "Installation" section (with a clear emphasis on being a contribution). I'm working on this.
