### ISSUE TITLE
`backup` ignores hostname when choosing parent snapshot

### ISSUE THREAD

**Issue by clonejo** [restic/restic#674]
## Output of `restic version`
    restic 0.3.0
    compiled at 2016-11-15 01:26:59 with go1.7.3 on linux/amd64

## Expected behavior
Restic chooses a snapshot with the same hostname and folder selection as parent snapshot.

## Actual behavior
Restic only considers the folders, not the hostname when choosing a parent snapshot.

## Steps to reproduce the behavior
Create snapshots of the same folders from two different computers in the restic repository. Create another snapshot for the first computer. It shows it's using the other computer's snapshot as parent.

**Comment by fd0** [comment]
Thanks for reporting this bug, it'll be fixed in #675.
