### ISSUE TITLE
Can't compile with go1.8beta1

### ISSUE THREAD

**Issue by zcalusic** [restic/restic#680]
## Output of `restic version`

restic 0.3.0 (v0.3.0-37-g0738087)
compiled at 2016-12-01 12:20:33 with go1.7.3 on linux/amd64

## Expected behavior

Compiles.

## Actual behavior

```
old version of Go detected (devel +41908a5 Thu Dec 1 02:54:21 2016 +0000), I'll try but no guarantees
# cmds/restic
.../go/pkg/tool/linux_amd64/link: -X flag requires argument of the form importpath.name=value
build failed: exit status 2
exit status 1
```

## Steps to reproduce the behavior

```go run build.go```

**Comment by fd0** [comment]
It works very well with Go 1.8beta1:
```
$ ~/Downloads/go1.8/bin/go run build.go 
$ ./restic version 
restic 0.3.0 (v0.3.0-38-g505a209)
compiled at 2016-12-01 20:48:59 with go1.8beta1 on linux/amd64
```

The detection does not work with development versions, but it's not meant to: It's meant for end-users.

But I second your proposal to remove the version check. Since we're requiring Go 1.6 at minimum we can just use the new ldflags syntax.

**Comment by fd0** [comment]
For the record: The reason to support Go 1.6 is that the current Debian stable is currently at this version (via backports).
