### ISSUE TITLE
add a manpage

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#697]
Would you consider adding a manpage? I've seen https://github.com/restic/restic/issues/31 and `doc/Manual.md`, but I mean a manpage as in `man restic` :-). I would help packaging.

**Comment by legrostdg** [comment]
Something like the output of "./restic --help" would be OK.

**Comment by fd0** [comment]
Yeah, good idea.

**Comment by daviddahlberg** [comment]
Here is a suggestion. I'd appreciate some general feedback, before I proof-read and clean it up.

As I seem not to be able to upload a ".1" file here, please get it 
[https://cloud.dahlberg.cologne/index.php/s/VHeiASfAMcVBCsB](from my ownCloud).

Written in mdoc; View using:
$ mandoc ./restic.1 | $PAGER
$ nroff -mdoc ./restic.1 | $PAGER

**Comment by fd0** [comment]
Huh, thanks a lot for your work! Are you aware of any generated that can be used to generated the manpage from a readable format? I don't speak nroff/troff and I'd really like to avoid learning another language...

**Comment by rumpelsepp** [comment]
asciidoctor works fine for manpages.

**Comment by daviddahlberg** [comment]
Some features only work native workflow. Such as semantic markup of flags, arguments, environment variables etc. in a way that they may be searched by man/whatis/apropos. Also man pages usually follow a certain style (eg. standard section names and sequences), which the other tools do not support. 

But if you do not want a "real" full featured man page, but just something that may be started with "man restic" and looks close enough, pod2mdoc seems to be somewhat popular. Here on github, some people seem to have workflows for markdown to man and of course there is pandoc, which converts almost every type of formatted text into every other.

Here's the ultimate resource:
http://mdocml.bsd.lv/

Especially:
http://manpages.bsd.lv/history.html
http://manpages.bsd.lv/
http://mdocml.bsd.lv/man/mdoc.7.html

**Comment by kisst** [comment]
since Sphinx is already used to build the readthedocs html, why not just use the same tool with `-b man` and generate ( a bit to verbose ) man page as well ?

**Comment by fwilhe** [comment]
[Cobra](https://github.com/spf13/cobra) can generate [man pages](https://github.com/spf13/cobra/blob/master/doc/man_docs.md). I did not look closer into this, but since restic already uses cobra this might be a easy way to get man pages. What do you think?

**Comment by fd0** [comment]
That's possible, and would be nice because we can have inline documentation for the commands. It would need some automation to generate a man page for restic and all the sub commands, which is updated regularly (especially for releases).

**Comment by fd0** [comment]
I think having the man pages generate by cobra is the way to go, so we have the same documentation inline and in the man pages and don't need to write (and update) another document.

**Comment by middelink** [comment]
Is someone working on this?

**Comment by fd0** [comment]
I've started
