### ISSUE TITLE
Show progess status when using  "restore" command

### ISSUE THREAD

**Issue by yhafri** [restic/restic#701]
## Output of `restic version`

Any

## Expected behavior

When we run "restic restore ...", we would like to see the same progress information as with "restic backup ...".

It's always useful to know when the restore will last: in few minutes, or couple or hours. How much data we're downloading, at what speed ...

## Actual behavior

There's no progress information. Only one line that confirm the restore operation is done at the very end.

**Comment by fd0** [comment]
Thanks for your suggestion, this is tracked in #426. I'm going to close this issue as a duplicate.
