### ISSUE TITLE
backup --one-file-system and 'nested' mount points.

### ISSUE THREAD

**Issue by bket** [restic/restic#702]
## Output of `restic version`
debug enabled
restic 0.3.1 (a507374b121)
compiled at 2016-12-16 06:57:37 with go1.7.4 on openbsd/amd64

## Expected behavior
Example disk layout:

	/			(Mountpoint_1)
	/storage
		/disk1		(Mountpoint_2)
			/home
			/yyy
			/zzz
	/usr
	/whatever

Expected behaviour of 'restic backup -x / /storage/disk1/home' is that:

- Only data on Mountpoint_1 in / is backed up;
- Only data on Mountpoint_2 in /storage/disk1/home is backed up.

## Actual behavior
- Data on Mountpoint_1 in / is backed up;
- All data on Mountpoint_2 is backed up.

## Steps to reproduce the behavior
Repeat the above on nested mount points...

## Workaround
restic backup -x / && restic backup -x /storage/disk1/home

## Additional
cmd_backup.gatherDevices returns a map of allowed devices. cmd_backup.runBackup uses this map to exclude files. Items on this map are not related to the original files/dirs which have been selected for backup.

**Comment by fd0** [comment]
Thanks for your report! I've suspected that the current handling is not complete, we've had a brief discussion in the comments for the PR (#626) and concluded that the current function also does not handle filesystems mounted several times. This is tracked in #645.

**Comment by fd0** [comment]
There's a fix in the works over at #908, could you maybe give it a try?

**Comment by fd0** [comment]
Works, merged :)
