### ISSUE TITLE
Invalid Meta-Data seem to crash the backup process

### ISSUE THREAD

**Issue by 0xBE7A** [restic/restic#705]
I was about to backup some old photos and everything went smoothly until restic wanted to backup a single JPG. The file seem to have a invalid creation date, which seem to confuse restic.

ls -lisan of the JPG:
`2149591549 1024 -rwxrwxrwx 1 502 500 159603 Sep 14  30828 'mnt/$My Pictures/Saab-Fotos/Saab Aero rot Nähe Barcelona/DSC00551.JPG'`

## Output of `restic version`
```
restic 0.3.2
compiled at 2016-12-20 18:16:58 with go1.7.4 on linux/amd64
```

## Expected behavior
Just ignore it, i guess

## Actual behavior

```
scanned 1677 directories, 37155 files in 0:14
panic: Marshal: json: error calling MarshalJSON for type *restic.Node: node /home/bela/mnt/$My Pictures/Saab-Fotos/Saab Aero rot Nähe Barcelona/DSC00551.JPG has invalid ModTime year 30828: 30828-09-14 03:48:05.4775807 +0100 CET

goroutine 88 [running]:
panic(0x8805e0, 0xc42224a6a0)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
restic/archiver.(*Archiver).dirWorker(0xc42020f040, 0xc4221b9d70, 0xc4200c62c0, 0xc420142840, 0xc420142b40)
        /tmp/restic-build-770806789/src/restic/archiver/archiver.go:403 +0xd72
created by restic/archiver.(*Archiver).Snapshot
        /tmp/restic-build-770806789/src/restic/archiver/archiver.go:712 +0x7a7e
```

The bug could be reproduced by placing the file in a different directory and using a different repo. I think that a debug run of restic cant help here, because the error happens because of 
`id, err := arch.SaveTreeJSON(tree)
			if err != nil {
				panic(err)
			}`

I could also give you a live presentation of the bug at the c4. just tell me.

**Comment by fd0** [comment]
Huh, wow, that is odd. Thanks for the report! Could you please run `stat` on the file?

**Comment by 0xBE7A** [comment]
Here you go:
`File: mnt/$My Pictures/Saab-Fotos/Saab Aero rot Nähe Barcelona/DSC00551.JPG
  Size: 159603          Blocks: 2048       IO Block: 16384  regular file
Device: 28h/40d Inode: 2149591549  Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (  502/ UNKNOWN)   Gid: (  500/ UNKNOWN)
Access: 2012-02-17 10:28:17.809189700 +0100
Modify: 30828-09-14 04:48:05.477580700 +0200
Change: 2012-02-17 10:28:05.059191000 +0100
 Birth: -
` 

I tried it first on a samba mount, but also tried it on ext4.

**Comment by 0xBE7A** [comment]
Update: After a bit of testing, it turned out that i wasn't actually using ext4 in the second test. So i tried to copy the directory, which caused the issue, alone. It worked with no errors to my surprise. I am currently doing a second test of backing up the mounted smb share. Results will follow tomorrow. The issue was might caused by some other things than restic.

**Comment by fd0** [comment]
For the cases which did not lead to a panic: Please post the output of `stat`. The underlying issue here is that the Go stdlib encodes a timestamp as JSON in a format defined in RFC 3339, which only permits 4-digit year. The code is here: https://github.com/golang/go/blob/master/src/time/time.go#L950-L954

**Comment by 0xBE7A** [comment]
OK, copying the file to my ext4 HDD fixed the access and modify date to the correct 4 digit one. That's the reason why it worked out and you was right with your guess. Thanks for pointing that out.
