### ISSUE TITLE
client.BucketExists: The access key ID you provided does not exist in our records

### ISSUE THREAD

**Issue by yhafri** [restic/restic#712]
## Output of `restic version`

Any OS
```
$ restic version
restic 0.3.2 (v0.3.2-6-g5132f5b)
compiled with go1.7.3 on darwin/amd64
```

## Expected behavior
I would like to reset a bucket from scratch and wipe out everything stored before.
`restic init` should be able to reinitialize the bucket.

Or at least we would like to have an option for that:
`restic init --force`

## Actual behavior

```
$ restic init
create backend at s3:http://somewhere.com:8080/myshare failed: client.BucketExists: The access key ID you provided does not exist in our records
```

## Steps to reproduce the behavior

This is with Minio from master.

```
$ export RESTIC_REPOSITORY=s3:http://somewhere.com:8080/myshare
$ restic init
created restic backend 613c6a8534 at s3:http://somewhere.com:8080/myshare

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

Then, on the server side:
- stop Minio
- delete the corresponding restic directory created above
- start Minio

Back to the client:
$ restic init
create backend at s3:http://somewhere.com:8080/myshare failed: client.BucketExists: The access key ID you provided does not exist in our records
```

**Comment by fd0** [comment]
Hm, interesting, thanks for reporting this. I'm not sure that this is a bug in restic, I'll have a look.

**Comment by yhafri** [comment]
Thanks @fd0
I tried with restic-debug, but no luck. Nothing  displayed on the console.

**Comment by zcalusic** [comment]
It could be that Minio somehow remembers that the bucket is still there, cause it was deleted beneath it, maybe some kind of cache? I played a lot with Minio some weeks ago, didn't have this problem. But, I also always deleted the top folder and everything beneath, when I wanted a clean start.

OTOH, it might be restic S3 backend having some ideas of its own.

I'll install Minio again after the New Year, so can help decipher this. Unless @fd0 is faster...

**Comment by yhafri** [comment]
Thx @zcalusic 
Even by deleting the top folder, I'm able to reproduce the problem at will.

**Comment by yhafri** [comment]
Happy new year guys!!!
I'm more and more confident that this issue isn't related to *restic*.
Please @fd0 un-tag it as a bug for now. I'll keep you informed.

**Comment by fd0** [comment]
Will do, thanks for keeping us updated!

**Comment by yhafri** [comment]
This is definitely related to Minio's behaviour (confirmed with their team) and not our beloved restic.
Sorry for the noise guys :-)

**Comment by fd0** [comment]
Did you create an issue with Minio? Can you please link the issue here? :)

**Comment by yhafri** [comment]
Not yet. I've just exchanged with them on Gitter

**Comment by rawtaz** [comment]
What about now? :D

**Comment by yhafri** [comment]
This is definitely unrelated to *restic* as i've explained before.

Our _Chaos Monkey_ test tool created such a mess in the backend that an important config file have been deleted (the one that match ACCESS_KEY, SECRET_KEY) ... which led to this strange error.

By avoid deleting this file in our test strategy, the situation is back to normal.

@fd0, you can please safely close this issue?

**Comment by fd0** [comment]
I'm closing this issue as per @yhafri's request. Thanks for letting us know the resolution! (you also could've closed the issue yourself, but I'm also happy to do it)
