### ISSUE TITLE
 Make restic wait when locked

### ISSUE THREAD

**Issue by ckeen** [restic/restic#719]
## Output of `restic version`
restic 0.3.0 (v0.3.0-19-g6b88d3b)
compiled at 2016-11-03 13:39:00 with go1.7.3 on linux/amd64

## Expected behavior
When running restic prune and another backup job is already running, restic should wait for a configured amount of time for the lock to become available.

## Actual behavior
Instead restic aborts and complains about the active lock.

## Steps to reproduce the behavior
Run a restic backup task, then run a restic prune in parallel

**Comment by rawtaz** [comment]
The suggested behavior sounds good to me. It seems natural to have restic wait for a configurable amount of time (via command line argument and perhaps also environment variable). During that time (which can also be 0 to disable it entirely) restic should inform the user it's waiting and that the user can press a key combo to cancel the wait and job altogether.

**Comment by bwmarrin** [comment]
Hey! Here's another good reason for the --timeout :)

**Comment by fd0** [comment]
@bwmarrin I'm sorry, I don't understand your comment...

**Comment by fd0** [comment]
Ah, @bwmarrin is referring to https://github.com/restic/restic/issues/519#issuecomment-270137855

**Comment by sanmai** [comment]
This can have a use here:

https://github.com/fsnotify/fsnotify/blob/master/example_test.go

**Comment by pschichtel** [comment]
If it is possible to reliably detect that an existing lock was the cause of the command failure, the script calling restic could easily implement some retry mechanism.

Is it possible to detect this (preferably without parsing the command output) ?

**Comment by MichaelEischer** [comment]
@pschichtel That sounds like you're looking for #956 . Currently, the only way to determine that the command failed due to a lock, is to parse the command output.
