### ISSUE TITLE
Support Google Cloud Storage as Backend

### ISSUE THREAD

**Issue by gebi** [restic/restic#721]
Hi,

thx for restic, awesome tool! (especially the forget --keep* parameters!)

It would be really nice to support google cloud storage natively too, beside s3.
There are native go client libraries
https://github.com/GoogleCloudPlatform/google-cloud-go#cloud-storage-

A nice sample program is eg:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/storage/objects/main.go

**Comment by fd0** [comment]
Hi, thanks for your report. This was already requested in #211, and it is in the works (although with not much progress lately, sorry). I'm going to close this as a duplicate.

**Comment by gebi** [comment]
Hi,

sorry for making a dublicated report, i thought i've searched for it before, sorry!

it seems #211 and #449 both try to implement google cloud storage through the s3 compatibility API, this is IMHO a fruitless endevour, as it means one has to configure a default project, one needs a developer key and the solution does not support Service Accounts.
Means using the IAM (identity and access management is also not possible).

There is a way to use the S3 APIs with google style ACLs but then you are already far away from what normal s3 libraries can do out of the box.

Would you be interested in a native GCS backend using the official google cloud go client libs?

**Comment by fd0** [comment]
Yes, I'm interested. But before that can happen, we (as a project) need to find answers to the questions raised in this thread: https://github.com/restic/restic/issues/212#issuecomment-230400007

Does GCS require a clientID or a client secret that needs to be kept secret? Is there a test service?

**Comment by fd0** [comment]
Hey @gebi, are you maybe interested in helping out? Can you answer my questions? :)

**Comment by gebi** [comment]
Hi @fd0, yes sure, i would gladly help out!

No, GCS does not require a clientID or embedded client secret.
One normally creates a service account where you get back a .json file including the private key, and just write filename in some environment variable and the google go libraries will use it (those env variables are standardised between all tools and most most libs), but you can also implement your own config scheme if you want (support for the upstream config vars would be nice though).

There is no test-service sofar as publicly writable GCS buckets AFAIK, most tests i've seen are done on your own buckets. Maybe there is some support for open source software devs in this regard?

A few notes about gcs implementation which might be of help:
https://cloud.google.com/storage/docs/consistency

As for getting your own config scheme running (because it might not be obvious) it's:
```go
cfg, err := google.JWTConfigFromJSON(key) // key is the credentials JSON as []byte
if err != nil {
    log.Fatal(err)
}
client, err := storage.NewClient(ctx, option.WithTokenSource(cfg.TokenSource(ctx)))
```

**Comment by gebi** [comment]
Any ways how i can help you out :)?

**Comment by fd0** [comment]
Yeah, let's move over to #212 and get people motivated to resume the work, e.g. @kurin and @ckemper67 :)

We had some internal changes the last couple of weeks, including a change in the backend API, so there is some work still to be done.

**Comment by gebi** [comment]
hm... that's about amazon cloud drive, some hacky consumer foo that's unreliable and mostly used to get some free riding for storage with their unlimited plan.
I also can't find neither kurin nor ckemper67 in your mentioned report, did you really meant 212?

**Comment by fd0** [comment]
Hmpf, you're right, I meant #211 ;)
