### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [restic/restic#724]
Dear team behind Restic,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by fd0** [comment]
I've updated the latest release and attached compiled versions of restic: https://github.com/restic/restic/releases/tag/v0.3.3

Does that work for you?

I think this issue is solved :)

**Comment by sergeevabc** [comment]
Vielen Dank für Ihre Teilnahme, Herr Neumann. Gott segne Sie.

P.S.
```restic_windows_amd64``` should be renamed to ```restic_windows_amd64.exe```, or it won’t launch.
