### ISSUE TITLE
Pack is unneeded, but not contained in rewritePacks

### ISSUE THREAD

**Issue by zcalusic** [restic/restic#734]
## Output of `restic version`

restic 0.3.3 (v0.3.3-32-g164ba82)
compiled with go1.8rc2 on linux/amd64

## Expected behavior

Running prune completes.

## Actual behavior

counting files in repo
building new index for repo
[0:36] 100.00%  11055 / 11055 packs
repository contains 11055 packs (2182938 blobs) with 49.525 GiB bytes
processed 2182938 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 20 snapshots
[12:04] 100.00%  20 / 20 snapshots
found 1938162 of 2182938 data blobs still in use, removing 244776 blobs
**pack bafffef9 is unneeded, but not contained in rewritePacks**

## Steps to reproduce the behavior

restic prune

I'll now try with version from Jan 15, to see if prune completes then.

**Comment by fd0** [comment]
Oh, thanks for the report!

**Comment by zcalusic** [comment]
With v0.3.3-21-g36276c4 all went ok:
```
will delete 296 packs and rewrite 747 packs, this frees 2.962 GiB
creating new index
[0:01] 100.00%  10370 / 10370 packs
saved new index as 05b7ab69
done
```

So this bug has been introduced with the latest commits.

**Comment by fd0** [comment]
Ok, I'll debug this.

**Comment by zcalusic** [comment]
Tested on 3 relatively smaller repos, prune working again! 👍

**Comment by zcalusic** [comment]
And on another not so small repo with 34202 packs (309232 blobs) with 172.295 GiB bytes, prune passes without an error!

Thanks for quick fix @fd0!
