### ISSUE TITLE
Init error on windows when repo path begins with drive letter

### ISSUE THREAD

**Issue by jva6438** [restic/restic#735]
## Output of `restic version`
restic 0.3.3 (v0.3.3-4-g9f1f174-dirty)
compiled with go1.7.4 on windows/amd64
## Expected behavior
Creation of repo

## Actual behavior
Error 
```Batchfile
C:\Dev\restic>.\restic.exe init --repo D:\backup-photos
debug log file \temp\restic-debug.log
debug enabled
create backend at D:\backup-photos failed: MkdirAll: mkdir \\?: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.
```
Message in french is "The syntax of the file name, directory, or volume is incorrect"
## Steps to reproduce the behavior
See Error. Tested on Windows 7 home
Content of log file
```
2017/01/22 18:57:50 restic/main.go:39	main.main	1	main []string{".\\restic.exe", "init", "--repo", "D:\\backup-photos"}
2017/01/22 18:57:50 restic/global.go:338	main.create	1	parsing location D:\backup-photos
2017/01/22 18:57:50 restic/global.go:346	main.create	1	create local repository at "D:\\backup-photos"
2017/01/22 18:57:50 restic/lock.go:112	main.unlockAll	1	unlocking 0 locks
```

Workaround : creation of empty repo directory before calling restic init :
```
C:\Dev\restic>set DEBUG_LOG=\temp\restic-debug.log
C:\Dev\restic>set RESTIC_PASSWORD=test

C:\Dev\restic>mkdir D:\backup-photos

C:\Dev\restic>.\restic.exe init --repo D:\backup-photos
debug log file restic-debug.log
debug enabled
created restic backend fbc002ea9f at D:\backup-photos

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

C:\Dev\restic>.\restic.exe  --repo D:\backup-photos backup P:\G4
debug log file restic-debug.log
debug enabled
scan [P:\G4]
scanned 6 directories, 768 files in 0:00
```

**Comment by fd0** [comment]
Thanks for reporting this issue. I'd appreciate any help from Windows developers to tackle this :)

**Comment by ibib** [comment]
os.MkdirAll fails because it cant use the UNC prefix from [here](https://github.com/restic/restic/blob/master/src/restic/fs/file.go#L43).
There is already a ticket at [golang/go](https://github.com/golang/go/issues/10900)

**Comment by fd0** [comment]
Thanks for investigating. It seems we need to reimplement `MkdirAll` for Windows, maybe we can use the code from syncthing: https://github.com/syncthing/syncthing/commit/f12b8c19be459433de5f6b1507b3b176556ea071
