### ISSUE TITLE
Restore is failing with input/output error due to regression after 0.3.3 release

### ISSUE THREAD

**Issue by fawick** [restic/restic#742]
## Output of `restic version`
Made backup with:
```
restic 0.2.0 (v0.2.0-0-gc7f5ac2)
compiled at 2016-07-30 18:27:58 with go1.6
```
Tried to restore with:
```
restic 0.3.3 (v0.3.3-37-g30ff741)
compiled with go1.7.4 on linux/amd64
```
## Expected behavior
Expected restore to work with v0.3.3-37-g30ff741.

## Actual behavior
Restoring (or FUSE-mounting and simply calling cp) with v0.3.3-37-g30ff741 fails with an input/output error, for example 
```
$ cd mnt/snapshots/2017-01-21T16\:07\:36+01\:00/foo/bar
$ cp -rv baz\snafu.dat ~
cp: error reading 'baz/snafu.dat': Input/output error
```
Restoring the same data with restic 0.2.0 works fine, though.

## Steps to reproduce the behavior

1. Make a backup with restic 0.2.0. 
2. Restore the backup with restic 0.3.3-g30ff741

Running in debug mode produced the following line in the debug.log:
```
2017/01/24 02:14:35 fuse/file.go:114    fuse.(*file).getBlobAt  13      LoadBlob(snafu.dat, cde42322eb81315fdcbe53ce6bd5e1a5c28435b2d9d66440a44ee81cc9e0d5f3) failed: buffer is too small for data blob (2458446 < 2458478)
```

I have not yet tested whether the official 0.3.x releases exhibit the same snag, but might be able to do so tomorrow night, if it is deemed necessary.

**Comment by fawick** [comment]
Ah, well, sleep is overrated, anyway. I just tested and found that none of the released versions 0.3.0, 0.3.1. 0.3.2, and 0.3.3 raise the input/output error.

**Comment by fawick** [comment]
The HEAD of master at the time I write this (v0.3.3-59-g0d12572) still gives the error, so I guess it's `git bisect` time.

And we have a winner: https://github.com/restic/restic/commit/9a5b9253c4bce73a68b08e9f6bd6ac205d8ebc8f

```$ git bisect log
git bisect start
# good: [d1ecdf74411a03bd85c1e4520c388fec23016519] Add VERSION file for 0.3.0
git bisect good d1ecdf74411a03bd85c1e4520c388fec23016519
# bad: [30ff7413be6d1af606c828f137c35d6460522522] Merge pull request #737 from restic/fix-734
git bisect bad 30ff7413be6d1af606c828f137c35d6460522522
# good: [75f21f23ff10474e0ef5e445f1f21d8480c9eb4f] Merge pull request #700 from restic/debug-panic
git bisect good 75f21f23ff10474e0ef5e445f1f21d8480c9eb4f
# good: [38ba5fbceb01898382a16426c1d7aec4f7af1b37] Merge pull request #727 from MirkoDziadzka/fix-typo
git bisect good 38ba5fbceb01898382a16426c1d7aec4f7af1b37
# bad: [36276c41b25ec5cba9e8b0f1f761e3a67e541ced] Add Benchmark for IndexSave
git bisect bad 36276c41b25ec5cba9e8b0f1f761e3a67e541ced
# bad: [710499cf468727cb4475f707bf2dbb65f73ed661] Add benchmark for LoadAndDecrypt
git bisect bad 710499cf468727cb4475f707bf2dbb65f73ed661
# good: [215af5c60acb6247dc15de45973ecc7f94fb92fc] Add LoadBlob benchmark
git bisect good 215af5c60acb6247dc15de45973ecc7f94fb92fc
# bad: [91dcb958e079fa064aca4475dbba6aef90fe00c6] Fix tests
git bisect bad 91dcb958e079fa064aca4475dbba6aef90fe00c6
# bad: [9a5b9253c4bce73a68b08e9f6bd6ac205d8ebc8f] LoadBlob: use buffer as scratch space
git bisect bad 9a5b9253c4bce73a68b08e9f6bd6ac205d8ebc8f
# first bad commit: [9a5b9253c4bce73a68b08e9f6bd6ac205d8ebc8f] LoadBlob: use buffer as scratch space
```

**Comment by fd0** [comment]
Huh, thanks a lot for your report and the extensive debugging! I'll investigate now :)

**Comment by fawick** [comment]
Thanks a lot for addressing and fixing this quickly!

**Comment by truongdo** [comment]
still seeing this in v0.4.0 when restoring mysql,

2/14/2017 7:33:01 PMerror for /var/lib/mysql/ibdata1: buffer is too small for data blob (524408 < 524426)
2/14/2017 7:33:01 PMrestic/repository.(*Repository).LoadBlob
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/restic/repository/repository.go:535
2/14/2017 7:33:01 PMrestic.Node.createFileAt
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/restic/node.go:214
2/14/2017 7:33:01 PMrestic.(*Node).CreateAt
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/restic/node.go:109
2/14/2017 7:33:01 PMrestic.(*Restorer).restoreNodeTo
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/restic/restorer.go:90
2/14/2017 7:33:01 PMrestic.(*Restorer).restoreTo
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/restic/restorer.go:53
2/14/2017 7:33:01 PMrestic.(*Restorer).restoreTo
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/restic/restorer.go:65
2/14/2017 7:33:01 PMrestic.(*Restorer).RestoreTo
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/restic/restorer.go:122
2/14/2017 7:33:01 PMmain.runRestore
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/cmds/restic/cmd_restore.go:135
2/14/2017 7:33:01 PMmain.glob..func13
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/cmds/restic/cmd_restore.go:23
2/14/2017 7:33:01 PMgithub.com/spf13/cobra.(*Command).execute
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/github.com/spf13/cobra/command.go:599
2/14/2017 7:33:01 PMgithub.com/spf13/cobra.(*Command).ExecuteC
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/github.com/spf13/cobra/command.go:689
2/14/2017 7:33:01 PMgithub.com/spf13/cobra.(*Command).Execute
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/github.com/spf13/cobra/command.go:648
2/14/2017 7:33:01 PMmain.main
2/14/2017 7:33:01 PM	/tmp/restic-build-849847342/src/cmds/restic/main.go:37
2/14/2017 7:33:01 PMruntime.main
2/14/2017 7:33:01 PM	/home/truong-d/go/src/runtime/proc.go:183
2/14/2017 7:33:01 PMruntime.goexit
2/14/2017 7:33:01 PM	/home/truong-d/go/src/runtime/asm_amd64.s:2086
2/14/2017 7:33:50 PMRestore completed

**Comment by fd0** [comment]
Thanks for leaving a comment, this seems to be a separate issue.
