### ISSUE TITLE
Restic expects renames across directories to be atomic

### ISSUE THREAD

**Issue by andrewchambers** [restic/restic#744]
I tried to run restic on a 9p based filesystem, however renames are only atomic within a directory so the atomic renames from $RESTIC_REPOSITORY/tmp/ to other directories are not working.

## Output of `restic version`

restic 0.3.3 (v0.3.3-59-g0d12572)
compiled with devel +92ecd78 Mon Jan 16 18:27:48 2017 +0000 on linux/amd64

## Expected behavior

init successful

## Actual behavior

enter password for new backend: 
enter password again: 
create key in backend at /home/ac/Desktop/mnt/backup failed: Rename: rename /home/ac/Desktop/mnt/backup/tmp/temp-084643386 /home/ac/Desktop/mnt/backup/keys/879268901c9ab478c1fe49b09bcebb70240e4d52aa1f60a4e45f2b836e026934: invalid cross-device link

## Steps to reproduce the behavior

- launch a 9p file system such as https://github.com/joushou/qptools/tree/master/cmd/ramfs
- Try and mount it using 9pfuse from https://github.com/9fans/plan9port
- try and run restic init on that directory.

**Comment by fd0** [comment]
Hey, thanks for your report. I'm not sure what we should do here. We're using `os.Rename` to move a file from the `tmp` directory to the `keys` directory (in this case), and it returns a weird error `invalid cross-device link`. The [documentation](https://godoc.org/os#Rename) talks about restrictions when the old an new file are not in the same directory:
```
func Rename(oldpath, newpath string) error
Rename renames (moves) oldpath to newpath. If newpath already exists, Rename replaces it. OS-specific restrictions may apply when oldpath and newpath are in different directories. If there is an error, it will be of type *LinkError.
```

So, what would be the correct strategy to move a file from one to another directory for a "9p based filesystem"?

**Comment by andrewchambers** [comment]
Maybe the change is too invasive, but I would suggest creating temp files in the same directory as where the final version will reside.  e.g. key.tmp-4534213424 etc.

It might be a rare enough use case where this doesn't matter, but perhaps there are other filesystems that can't do such renames.

**Comment by fd0** [comment]
That would be the obvious solution, but it would need additional code in the function to list all files in the repo (so that tempfiles are not returned). At the moment I'm inclined to tag this as `wontfix`.

I'm curious though, what's the benefit of using such a filesystem?

**Comment by andrewchambers** [comment]
I prefer the 9P protocol over fuse (it is simpler), I am personally using it for an private file storage project. The value to most people is probably limited, the only benefit would be restic could potentially run on the plan9 OS which has a go compiler, though the user base will be very small, and there would probably be other issues.

Also, I wonder if you run some risk of platforms silently turning a Rename into a non atomic copy + delete across devices. I haven't seen any guarantee from Go at least that os.Rename is always atomic, though maybe in practice it is.

**Comment by fd0** [comment]
Thanks for the explanation. For the record: restic does not depend on the rename being atomic, the `tmp` directory is rather used to separate non-completed files from the rest of the repo.

I'm going to close this issue as `wontfix`. If you would like to work on it though, I'd be happy to collaborate.
