### ISSUE TITLE
Repository mountpoint shows only one folder of two folders contained in backup

### ISSUE THREAD

**Issue by meinz255** [restic/restic#753]
## Output of `restic version`
restic 0.3.3
compiled with go1.7.4 on linux/amd64

## Expected behavior
I run restic two times to backup two different folders and then mount the restic repository. What I expect is to see both folders in the mountpoint with the latest date (backup of folders foo and bar):
mnt/snapshots/2017-01-28T17\:03\:52+01\:00/ contains foo (new repository assumed, folder foo was the first backuped folder)
mnt/snapshots/2017-01-28T17\:03\:58+01\:00/ contains foo and bar

## Actual behavior
mnt/snapshots/2017-01-28T17\:03\:52+01\:00/ contains only foo
mnt/snapshots/2017-01-28T17\:03\:58+01\:00/ contains only bar

## Steps to reproduce the behavior
restic -r resticRepo/ init
restic -r resticRepo/ backup foo
restic -r resticRepo/ backup bar
restic -r resticRepo/ mount mnt/

ls mnt/snapshots/2017-01-28T17\:03\:52+01\:00/
foo
ls mnt/snapshots/2017-01-28T17\:03\:58+01\:00/
bar

**Comment by zcalusic** [comment]
Without much investigation, I'd say that this is completely expected. When you do backup foo, you can't expect that it contains any bars, under no circumstances.

If you want both folders to be contained in the same snapshot, why not backup them both at the same time, like this: `restic backup foo bar`?

**Comment by meinz255** [comment]
Thanks for your fast reply! You are completely right I got my fallacy.
