### ISSUE TITLE
golang is a dev requirement not a user one

### ISSUE THREAD

**Issue by brikou** [restic/restic#755]
README.md and Manual.md explains that golang is required to use restic, it may look a bit scary to add this dependency if you just want to try out restic.

A simpler way to install restic is just to download it...

```sh
curl --location https://github.com/restic/restic/releases/download/v0.3.3/restic_linux_amd64.bz2 | bunzip2 > /usr/local/bin/restic
chmod +x /usr/local/bin/restic
```

I think this download explanation should be part of README.md to have more people using it.

**Comment by fd0** [comment]
Great idea, are you willing to write a section and contribute it in a pull request? Maybe without the `curl` command and the hardcoded version number, just guide people into downloading a pre-compiled binary. Bonus points for verifying the SHA-256 hash and my GPG signature!
