### ISSUE TITLE
Listing blobs not possible

### ISSUE THREAD

**Issue by oysols** [restic/restic#756]
## Output of `restic version`
restic 0.3.3 (v0.3.3-0-g4d93da9)
compiled with go1.7.4 on linux/386

## Expected behavior
`restic -r repo list --help`
Usage:
  restic list [blobs|packs|index|snapshots|keys|locks] [flags]
Should be able to list blobs.

## Actual behavior
`restic -r repo list blobs`
Fatal: invalid type

## Steps to reproduce the behavior
init repo
run backup
`restic -r repo list blobs`

**Comment by fd0** [comment]
Thanks for raising this issue, it is indeed a bug.
