### ISSUE TITLE
Inconsistent use of blob, data and tree

### ISSUE THREAD

**Issue by oysols** [restic/restic#758]
## Output of `restic version`
restic 0.3.3 (v0.3.3-0-g4d93da9)
compiled with go1.7.4 on linux/386

## Expected behavior
According to the design document blobs are either data or trees.
`restic cat blob` should work for both data and trees.
`restic cat data` should work for data.
`restic cat tree` should work for trees.

## Actual behavior
`restic cat blob` works for data only.
`restic cat data` does not exist.
`restic cat tree` works for trees.

## Additional info
The design document already refers to `restic cat data` even though the example right below it uses `restic cat blob`.

## Proposed fix
I don't see the need for all three. It should be enough to include `restic cat blob`, and make it work for both data and trees.

**Comment by fd0** [comment]
Thanks for your suggestion and for finding the inconsistencies in the documentation!
