### ISSUE TITLE
Undocumented feature `restic cat index`

### ISSUE THREAD

**Issue by oysols** [restic/restic#759]
## Output of `restic version`
restic 0.3.3 (v0.3.3-0-g4d93da9)
compiled with go1.7.4 on linux/386

## Expected behavior
`restic cat index` works as expected, but is not included in documentation.

## Actual behavior
```
# restic -r repo cat --help
The "cat" command is used to print internal objects to stdout.

Usage:
  restic cat [flags] [pack|blob|tree|snapshot|key|masterkey|config|lock] ID
```

**Comment by fd0** [comment]
Thanks for pointing this out!
