### ISSUE TITLE
Fuse mount should have option "allow_others"

### ISSUE THREAD

**Issue by AlexDunmow** [restic/restic#767]
## Output of `restic version`
restic 0.3.3 (v0.3.3-7-g094e80f)
compiled with go1.7.4 on linux/amd64

## Expected behavior
Fuse mount should be accessible by other users and presentable over CIFS by using "allow_others" fuse option. Or have a flag to enable such behaviour.

## Actual behavior
Fuse mount has no options and is only accessible by mounting user and not presentable over CIFS at all.

## Steps to reproduce the behavior
Mount a backup repository

**Comment by fd0** [comment]
Thanks for raising this as an issue. It briefly came up in a discussion with @Thamster in https://github.com/restic/restic/pull/754#issuecomment-276023059. I'll repeat my comment here:

> It's a security feature that, by default, only the user running the process which implements the fuse filesystem can read it. So I'm not going to merge a PR that will always allow root to read the filesystem mounted provided by restic, therefore I'm closing this PR (as for now).
>
> I'm however willing to merge a PR which adds the options --allow-others and --allow-root to the mount command (including proper documentation in the manual), so that you can enable this behavior (similar to sshfs options -o allow_other and -o allow_root).

**Comment by fd0** [comment]
Please leave a comment here should you begin working on this, so duplicate work is prevented.

**Comment by fd0** [comment]
When this is implemented, just add both options (`allow_others` and `allow_root`). Let me know if you need assistance.
