### ISSUE TITLE
Allow --files-from to take a dash (-) for stdin

### ISSUE THREAD

**Issue by opennota** [restic/restic#769]
The `backup` command currently does not recognize `-` as a synonym for stdin:

```
$ find -name '*.go' | restic backup --files-from -
open -: no such file or directory
```

Whereas one can use `/dev/stdin` for that, I would like restic to recognize the dash, because `-` as a filename to mean stdin is a convention used by a great many programs.

If both `--files-from -` and `--stdin` are used, restic should of course print a warning.

**Comment by fd0** [comment]
Thanks for raising this as a different issue. If someone starts working on this, please leave a comment. Also if you need guidance on what to do.

**Comment by barthr** [comment]
I would like to start work on this tomorrow. I think I already know what needs to be done. Will PR tomorrow

**Comment by opennota** [comment]
@barthr OK. I'll stop working on it, then.

**Comment by barthr** [comment]
See PR: https://github.com/restic/restic/pull/772

**Comment by barthr** [comment]
See PR: #772

**Comment by barthr** [comment]
See PR: #772 for discussion

**Comment by opennota** [comment]
Also PR #773
