### ISSUE TITLE
Disable password reading when backup is used with `--stdin`

### ISSUE THREAD

**Issue by opennota** [restic/restic#770]
## Output of `restic version`

restic 0.4.0 (v0.4.0-4-gf5faff9)
compiled with go1.8rc2 on linux/amd64

## Expected behavior

restic shows password prompt and upon entering the password backups the contents of the standard input.

## Actual behavior

No password prompt; instead restic  prints an error:

`unable to open repo: wrong password or no key found`

## Steps to reproduce the behavior

```
$ restic init -r /tmp/test
$ echo hello | restic backup --stdin -r /tmp/test
unable to open repo: wrong password or no key found
```
It seems that restic tries to use `hello` as a password. It can be verified by using the correct password for the repository in the `echo` command.

**Comment by rumpelsepp** [comment]
What happens if you set the password via environment variable?

**Comment by fd0** [comment]
Oh, indeed, you need to supply the password either contained in a file (with `--password-file`) or via the environment variable `RESTIC_PASSWORD`.

I consider this a bug, restic should warn that it has no password and exit instead of trying to read the password from stdin.
