### ISSUE TITLE
SFTP PORT problem

### ISSUE THREAD

**Issue by zxl777** [restic/restic#785]
restic -r sftp:root@host:2222/root/iBackup init

subprocess ssh: ssh_exchange_identification: Connection closed by remote host
create backend at sftp:root@xxx:2222 failed: unable to start the sftp session, error: EOF

i try ssh and sftp cli to this host ,is OK.

## Output of `restic version`
restic 0.4.0

**Comment by fd0** [comment]
Hey, thanks for raising this issue. Setting the SSH server port via the repository string is not possible, please use an entry in the SSH client config file to set the port for a server, like this:
```
Host servername.tld
     Port 2222
```

**Comment by wendell77** [comment]
I had the same problem, but it was with the user-defined rbash.
user:x:1003:1004:,,,:/home/user:/bin/rbash
I change to /bin/bash and it worked.
