### ISSUE TITLE
Add --host flag for backup command

### ISSUE THREAD

**Issue by sanmai** [restic/restic#788]
Please add `--host` flag to `backup` command to be used with `--stdin` flag. 

This is useful when pulling/pushing files for backup from other hosts. See workarounds mentioned in #784. If a backup from another host was made without this flag, then `forget` command can't be used reliably.

~~~[There's only one place where host is set](https://github.com/restic/restic/blob/master/src/cmds/restic/cmd_backup.go#L379), so this shouldn't take too much effort.~~~

And no, unfortunately one couldn't set a hostname with an envvar. [Go gets it directly from the kernel at least in Linux.](https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/src/os/sys_linux.go#L9)

**Comment by fd0** [comment]
Good idea, we can certainly add such a parameter. Thanks for raising this issue!

**Comment by dizlexik** [comment]
Is there any reason why you wouldn't want the parameter name to be consistent with other commands, i.e. "--host"? I know it would help to clean up my scripts a little.
