### ISSUE TITLE
S3: TCP connections are not reused

### ISSUE THREAD

**Issue by LouisChrist** [restic/restic#791]
## Output of `restic version`
```
restic 0.4.0 (v0.4.0-21-g073edd9)
compiled with go1.7.3 on windows/amd64
```

## Expected behavior
Run `restic check` or `restic prune` with minio backend.

## Actual behavior
After a few runs restic starts throwing hundreds/thousands of the following errors: 
```
obj.Stat: Head http://10.5.5.200:9000/restic/restic/data/d7f3e34db62b5bf971bbd305b5ae1464dccb6f0ed6d4a8a9e16d94bc54ae85d6: dial tcp 10.5.5.200:9000: connectex
Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden.
```
English version should be:
```
http://10.5.5.200:9000/restic/restic/data/d7f3e34db62b5bf971bbd305b5ae1464dccb6f0ed6d4a8a9e16d94bc54ae85d6: dial tcp 10.5.5.200:9000: connectex
Only one usage of each socket address (protocol/network address/port) is normally permitted.
```
`restic check` also throws the following errors:
```
pack 5f3aa2b1e264101cb9a0709d0d160bd4baff9be7f6dd334287d36504504e6d23: does not exist
pack 18ae2846f2889cdd91517d172ae7ce74b842e2a951a1df0fffdebfe9dfefeb7a: does not exist
pack f1a747801453ee1a567799a5aff6ae59de2abc726afcd14885a13efb32d07cb1: does not exist
pack 121d132ac1e70542f8eba7ddffabc5e60ea7112e3a2263db7db4960713d7b0fe: does not exist
pack 602f23335528a29a7a1519a9b7af5c194664a2772f6eeae1f31fda17641eadc0: does not exist
pack 4da0bcb3d99a313cf5761272acfa01667c5457ab8bbca59aea7767f83c0e14c7: does not exist
pack 3bb077f13145cb2db7f65c7293b7a15d6f92e576cf8b7a603de6b9c411d74428: does not exist
pack 294741f8f0de730dca74ca77b04da29ce0fee06b844fc882d6af1420aec6cd7c: does not exist
pack 4a37f6692c90ee0cbc32541a03cfa26091ad9ab97715b0c8aa5040d1ad95c325: does not exist
pack 7a7856588a9bbc7bc1e65b68886dde2d9cc9c34dda0ae052c022c4351abc705b: does not exist
pack 7f897b4ad2dc1b40b3b41239fdbe0253cb5e678c69071842c9235480703c8a17: does not exist
pack 5f15e96b361fbbf6a5a1b9f8f83717408757bf942efcdf8751e3d9a296ad872f: does not exist
pack 66ea80136330063f97f069dd1342e697f12b439c2c5910a29647cebb925fa00b: does not exist
pack b73cb1b2a959704d442d345543f85cf10e7a9871857c7bdcb5f3c8ac5f8e70bf: does not exist
pack 66a9f9b3fdcf23b421a3af458034f6b09acde63e2933ff66441fd121c0ddd25e: does not exist
```

## Steps to reproduce the behavior
Run `restic check` or `restic prune` a few times. 

- A bigger repository needs fewer runs.
- `restic prune` needs fewer runs

Running `restic prune` on Windows 10 Education with 8.5GB repositiory results in erros during the third run. The Minio instance is running on a diffrent machine in the same local network.

## Problem
Restic creates new TCP connections until all ports are in use. `netstat -an |find /c "TIME_WAIT"` shows a maximum of about 16000 connections in TIME_WAIT state.

**Comment by fd0** [comment]
Huh, that's odd. Thanks for your report!

**Comment by fd0** [comment]
Could you please test the code in #792 in the branch `fix-791` and report back if it fixes the behavior you see?

**Comment by LouisChrist** [comment]
First of all: Thanks for the fast fix.

I tested everything again. This time on a 25GB repository:
- `restic prune`: works well, no connections in TIME_WAIT state
- `restic check`: works better, about 100-120 new connections in TIME_WAIT state per run

With `MaxIdleConnsPerHost:` increased to 40, `restic check` will not create any new connections in TIME_WAIT state too.

**Comment by zcalusic** [comment]
Yeah, it needs to be at least as big as this constant: https://github.com/zcalusic/restic/blob/master/src/restic/checker/checker.go#L56 Otherwise, the connections are constantly built up and teared down, resulting in the socket mayhem on the machine.

This issue is basically #669, just for S3 backend.

**Comment by fd0** [comment]
Thanks for testing it, I'll set `MaxIdleConnsPerHost` to 40.
