### ISSUE TITLE
destination buffer too small, slice bounds out of range

### ISSUE THREAD

**Issue by moho1** [restic/restic#80]
During my first full-backup of my homedir, restic throws the following error. The error is reproducible. According to strace, it happens while proceeding a mail-archive with *many* small files.

	% restic -r /backup/restic backup .
	[15:59] 26.33%  17.990 MiB/s  16.848 GiB / 63.979 GiB  171188 / 539947 items  ETA 44:42
	duration: 15:59, 68.31MiB/s
	error: destination buffer too small
	panic: runtime error: slice bounds out of range

	goroutine 1 [running]:
	main.CmdBackup.Execute(0xc20804e100, 0x1, 0x4, 0x0, 0x0)
		/home/moho1/usr/go/src/github.com/restic/restic/cmd/restic/cmd_backup.go:196 +0x11f9
	main.(*CmdBackup).Execute(0x7d19e8, 0xc20804e100, 0x1, 0x4, 0x0, 0x0)
		<autogenerated>:2 +0xc7
	github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc20800a500, 0xc20800a010, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
		/home/moho1/usr/go/src/github.com/jessevdk/go-flags/parser.go:278 +0x8c1
	github.com/jessevdk/go-flags.(*Parser).Parse(0xc20800a500, 0x0, 0x0, 0x0, 0x0, 0x0)
		/home/moho1/usr/go/src/github.com/jessevdk/go-flags/parser.go:154 +0xb1
	main.main()
		/home/moho1/usr/go/src/github.com/restic/restic/cmd/restic/main.go:172 +0x15c

	goroutine 17 [syscall, 16 minutes, locked to thread]:
	runtime.goexit()
		/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

If you need more Information, just jet me know.

**Comment by fd0** [comment]
Thank you for your report. I think I have an idea what's going on here. Do you maybe have a directory with a huge amount of files and/or subdirectories? If so, could you test creating a backup of just this directory?

In addition, you can try to create a full debug log:

    $ cd cmd/restic
    $ go build -a -tags debug -o restic.debug
    $ DEBUG_LOG=/tmp/log DEBUG_TAGS=all ./restic backup ~/hugedir

Please be aware that the debug log file contains the names of all files and directories that are touched, so this is potentially sensitive (especially for your homedir).
Just have a look if you can spot what's going on.

Thanks!

**Comment by fd0** [comment]
According to @moho1, this is reproducable with a directory containing about 86k files, with a size of 2.4GiB. A directory triggering this bug can be created as follows:

    $ for i in $(seq -w 0 90000); do dd if=/dev/urandom of=file-$i bs=1024 count=58; done
