### ISSUE TITLE
Restic 0.4.0: buffer is too small for data blob

### ISSUE THREAD

**Issue by truongdo** [restic/restic#807]
## Output of `restic version`
restic 0.4.0 (v0.4.0-0-ga7c2f28-dirty)
compiled with go1.7.5 on linux/amd64

## Expected behavior
Restoring should work without error

## Actual behavior
error for data/mysql/ibdata1: buffer is too small for data blob (524408 < 524426)
restic/repository.(*Repository).LoadBlob
	/tmp/restic-build-119647226/src/restic/repository/repository.go:535
restic.Node.createFileAt
	/tmp/restic-build-119647226/src/restic/node.go:214
restic.(*Node).CreateAt
	/tmp/restic-build-119647226/src/restic/node.go:109
restic.(*Restorer).restoreNodeTo
	/tmp/restic-build-119647226/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
	/tmp/restic-build-119647226/src/restic/restorer.go:53
restic.(*Restorer).restoreTo
	/tmp/restic-build-119647226/src/restic/restorer.go:65
restic.(*Restorer).RestoreTo
	/tmp/restic-build-119647226/src/restic/restorer.go:122
main.runRestore
	/tmp/restic-build-119647226/src/cmds/restic/cmd_restore.go:135
main.glob..func13
	/tmp/restic-build-119647226/src/cmds/restic/cmd_restore.go:23
github.com/spf13/cobra.(*Command).execute
	/tmp/restic-build-119647226/src/github.com/spf13/cobra/command.go:599
github.com/spf13/cobra.(*Command).ExecuteC
	/tmp/restic-build-119647226/src/github.com/spf13/cobra/command.go:689
github.com/spf13/cobra.(*Command).Execute
	/tmp/restic-build-119647226/src/github.com/spf13/cobra/command.go:648
main.main
	/tmp/restic-build-119647226/src/cmds/restic/main.go:37
runtime.main
	/usr/lib/go/src/runtime/proc.go:183
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:2086

## Steps to reproduce the behavior
Might be related to #743 #742 

I'm not sure how to reproduce this issue.
Interestingly, restic 0.3.3 downloaded from the released page worked without any problem.

Do you think this issue has anything to do with a high-speed bandwidth (5-8MB/s) connection?

**Comment by fbkopp** [comment]
Same error:
C:\Users\Fabio\Desktop\backup>restic.exe version
restic 0.4.0 (v0.4.0-46-gc83e608)
compiled with go1.7.1 on windows/amd64

restoring <Snapshot 78486253 of [C:\Users\Fabio\Desktop D:\DriveP D:\Java C:\xampp\htdocs] at 2017-02-15 11:03:45.185552 -0200 BRST by FABIO-VM\Fabio@fabio-vm> to x:\temp
error for x:\temp\Desktop\Programas\cmder\vendor\git-for-windows\usr\share\misc\magic.mgc: buffer is too small for data blob (524377 < 524385)
restic/repository.(*Repository).LoadBlob
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/repository/repository.go:535
restic.Node.createFileAt
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/node.go:222
restic.(*Node).CreateAt
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/node.go:109
restic.(*Restorer).restoreNodeTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:53
restic.(*Restorer).restoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:65
restic.(*Restorer).restoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:65
restic.(*Restorer).RestoreTo
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/restic/restorer.go:123
main.runRestore
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/cmds/restic/cmd_restore.go:135
main.glob..func12
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/cmds/restic/cmd_restore.go:23
github.com/spf13/cobra.(*Command).execute
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/github.com/spf13/cobra/command.go:599
github.com/spf13/cobra.(*Command).ExecuteC
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/github.com/spf13/cobra/command.go:689
github.com/spf13/cobra.(*Command).Execute
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/github.com/spf13/cobra/command.go:648
main.main
        C:/Users/Fabio/AppData/Local/Temp/restic-build-998844079/src/cmds/restic/main.go:37
runtime.main
        C:/Go/src/runtime/proc.go:183
runtime.goexit
        C:/Go/src/runtime/asm_amd64.s:2086

**Comment by fd0** [comment]
Thanks a lot for raising this issue, you've found a bug!

**Comment by fd0** [comment]
Could you please have a look if the code in #808 fixes the issue?

**Comment by fbkopp** [comment]
For me #808 resolved the issue.
Thanks for rapid response.
