### ISSUE TITLE
Additional files in the `keys` directory causes all operations to fail

### ISSUE THREAD

**Issue by oysols** [restic/restic#810]
## Output of `restic version`
restic 0.4.0 (v0.4.0-0-ga7c2f28-dirty)
compiled with go1.7.5 on linux/386

## Expected behavior
Additional files in the `keys` directory should either be ok or produce an informative error message.

## Actual behavior

Additional files in the `keys` folder will cause all restic operations to fail.
```
# restic -r testrepo/ -p .pwd check
unable to open repo: Unmarshal: invalid character 'P' looking for beginning of value
```

## Steps to reproduce the behavior
```
echo "jsdfjksfdjiosfd" >> testrepo/keys/28174164e678a0f33aea4fb38b7b43dee317662f3bc5c0bfaafacf7ef772e608.extra
```

To correct the problem, just delete the file.

**Comment by fd0** [comment]
Good point, thanks for reporting this issue!

**Comment by fd0** [comment]
It has been resolved in the meantime, so I'm closing this issue.
