### ISSUE TITLE
node.Subtree.IsNull() panic

### ISSUE THREAD

**Issue by zcalusic** [restic/restic#811]
## Output of `restic version`

restic 0.4.0 (v0.4.0-58-g0674f32)
compiled with go1.8 on linux/amd64

## Actual behavior

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ff902]

goroutine 59 [running]:
restic/archiver.(*Archiver).dirWorker(0xc4228a55e0, 0xc42289c420, 0xc42ec3f130, 0xc4228898c0, 0xc422889ce0)
        /tmp/restic-build-891831329/src/restic/archiver/archiver.go:379 +0xf12
created by restic/archiver.(*Archiver).Snapshot
        /tmp/restic-build-891831329/src/restic/archiver/archiver.go:712 +0x67d

## Steps to reproduce the behavior

Regular nightly backup, failed at 93.11% :(

This is to celebrate go1.8 release with a bang. :)

Will run again in debug mode if it helps...

**Comment by zcalusic** [comment]
Funny, it fails on MooseFS mount point. But, only on this particular machine (I have such mounts on others, no panic there). Its contents also excluded from backup like this /mfs/*.
```
2017/02/17 11:03:34 archiver/archiver.go:377	archiver.(*Archiver).dirWorker	72	got tree node for /mfs: <nil>
```
If you can help explain what it is looking for, and what &lt;nil&gt; represents in this case, I can check what is different with this mount point on this machine. Though, it worked well for months before this night, weird...

**Comment by fd0** [comment]
I'm working on it, I saw this myself, #809 is my WIP PR.

**Comment by fd0** [comment]
It can also be reproduced by trying to backup some special files in `/sys`, e.g.:
```
$ restic backup /sys/bus/acpi/                         
using parent snapshot 5ccce252
scan [/sys/bus/acpi]
scanned 15 directories, 182 files in 0:00
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x607a22]

goroutine 101 [running]:
restic/archiver.(*Archiver).dirWorker(0xc420162280, 0xc4221f2e40, 0xc4221fe370, 0xc420016d80, 0xc420017140)
	/home/fd0/shared/work/restic/restic/src/restic/archiver/archiver.go:379 +0xf12
created by restic/archiver.(*Archiver).Snapshot
	/home/fd0/shared/work/restic/restic/src/restic/archiver/archiver.go:712 +0x6a8
[1]    2491 exit 2     bin/restic backup /sys/bus/acpi/
```

**Comment by zcalusic** [comment]
Ah, that explains it. I have mfs mounted with noxattrs option explicitely.
