### ISSUE TITLE
[RFE] - Run some CPU/disk/net intense jobs directly on the remote host

### ISSUE THREAD

**Issue by dsommers** [restic/restic#813]
Output of `restic version`
```
restic 0.4.0 (v0.4.0-46-gc83e608)
compiled with go1.6.3 on linux/amd64
```

This is an enhancement suggestion.

Some operations could probably be run directly on the remote host when using sftp, in particular `forget` and `prune` operations, but probably also "search" functions as well.

The idea is that `restic` could accept a `--remote-run` argument to operational modes which can make use if this feature if the remote is using the sftp (and possibly the restic-rest server).  In this case, `restic` would request the repository password locally and transfer it securely to the remote host, run the `restic` command on the the remote and just report back the result (including progress as it runs).

The advantage here is that some operations requires lots of disk reads to do the job, especially over slower links, can be much more efficient if run locally where the data set is stored.  In some cases the data may even be stored on high performance storage solutions which again would not have much effect over a slower link.  Plus it would make some operations more useful over mobile networks as well without killing the data quota many mobile subscriptions has, as only the result of the operation is transferred over the net - which normally would not need to be many megabytes.

**Comment by fd0** [comment]
Thanks for your suggestion! Unfortunately, in my opinion this violates the (current) [threat model](https://github.com/restic/restic/blob/master/doc/Design.md#threat-model): The storage location is not trusted completely, so any code running there is not to be trusted with the repository password (or key). 

So at least for now this will not be implemented, I'm going to close this issue.

I think most of what you're describing will be sped up by the metadata cache (see #29), so that filenames/directories in the backup are not fetched at all from the repo, but read from the local cache.

**Comment by dsommers** [comment]
Fair enough, I understand the threat model argument.  I certainly do hope #29 will improve the performance dramatically.

On the other hand, I will argue that the storage location _might_ be trusted more completely.  In my case, the storage device is only accessible from a local LAN or via VPN (with several layers of authentication and access control) and the physical location of the hardware is also under full control.  So even though the threat model have good arguments for many scenarios, it doesn't cover all use cases.

Another thought ... What if the repository uses different encryption keys for the data and the meta data?  Where (if the user accepts the risks) the meta data can be made accessible on the server side while the user data itself is still encrypted during these operations.

I am looking at different backup solutions for a highly disk intense dataset (total storage is 2-4TB, where each project being backed up will be between 150-200GB; there will be several projects running in parallel as well) ... so in these cases, even a local cache might not perform as well as a server with a high speed storage (with its own high speed, battery backed-up hardware cache).  I love the simplicity of restic, but currently it is far from ideal due to these performance challenges on such large data sets.

**Comment by cfcs** [comment]
You can't run commands using sftp.

If you have SSH access, which I guess you have if you're able to run commands, and if you trust the server, you can just run the restic client on the remote server?

**Comment by fd0** [comment]
This is a different case for the threat model that you're describing, I think we may address this later.

**Comment by dsommers** [comment]
Even though SFTP is a protocol without a "shell", it is a sub-protocol of SSH.  So unless the server side restricts anything but the SFTP protocol ([Solution 1](http://serverfault.com/questions/354615/allow-sftp-but-disallow-ssh#354618), [Solution 2](https://github.com/scponly/scponly/wiki); there are even more), you do have access to ordinary SSH.  And the SFTP-only restriction may be applied on the server side, outside the control of restic.

So with that in mind, `restic` could just as well use ssh:// as sftp:// as the protocol identification of the backup repository.  The `restic` front-end could then provide a few additional features if ssh:// was used instead of sftp://

In regards to running `restic` on the client or the server.  Yes, it may very well work to run `restic` directly on the server.  And you provide a fairly good argument on one of the issues with the thread model, @cfcs.  Hence my suggestion to have separate encryption keys for user data and meta data.  But ideally, those should be derived from the same user password to not make things too difficult for the end-user.


### Thoughts on the threat models and some ideas
This is getting a bit off-topic, but still somewhat related.  As I have some more ideas how to resolve this.  Without knowing anything about the storage container format used by restic, my thoughts here may or may not be completely incompatible with the current situation.  Some of what I write here may already be fully or partially implemented already.

In the restic repository, two keys should be stored encrypted with different passphrases; one for the user data and one for the meta-data.  When the client starts a job, it retrieves both these keys encrypted.  Locally on the client there is are two additional master keys, which are coupled to these repository keys.  The master keys keeps and protects the passphrases for the repository keys.  The master key is encrypted using the end-users password.  So when an operation which only needs meta-data access, `restic` only retrieves and decrypts that key, first by getting the repository passphrase from the master key and then by decrypting the meta-data key using the repository passphrase.

On a remote host execution of `restic`, this model can allow only the meta-data key to be decrypted while the user-data is fully protected.  This is solved by the local client retrieves the meta-data passphrase and sends only that to the remote `restic` process.  The remote process can then only retrieve the encryption key for the meta-data.  This way a server will only have a limited access to the lesser sensitive backup data.  (I say "lesser sensitive" as meta-data may contain some sensitive data, but not as critically sensitive as the real user data).

Why separate repository keys and a master key?  This model allows the encryption key protecting the repository data to be cryptographically strong enough, regardless of the strength of the users password.  And when a user decides to change its password, only the master key password needs to change.  For all I know, this might already be the case in the current implementation.  And a similar model is also what is used in [LUKS](https://gitlab.com/cryptsetup/cryptsetup/blob/master/README.md) too.

Key rotation on the repository data (user + meta) by rotating the encryption key protected by the repository keys will also be possible without changing the users password with this model.

This model could also enable an even stronger access control if a repository is shared among more clients, where each client will have their own local set of of a sub-master key, where an ACL list (which operations will be allowed by this sub-master key) can be signed by the master key and a separate set of sub-repository keys (which essentially derives the same repository encryption keys).  To decrypt the sub-repository code, the defined ACL and the signature must be added in the process.  So if a rouge client tries to elevate its privileges by modifying the `restic`client, the signature will not be correct and the sub-repository keys cannot be decrypted.  Likewise, if a client access is revoked by a client with the appropriate ACL, the sub-repository keys will just be removed in the repository.

Why is this an important feature?  It can allow backup-only clients, who cannot do anything than to send data to a repository.  While restore must happen through a different client.  This can also restrict the use of fuse-mounts as well.  The ACL itself can go much broader than "this client can run these `restic` commands.  It can limit how far back in the repository history it may look, limit at which days or hours it can use `restic`, etc, etc.

There are several traps here as well.  As these master and repository keys (including sub keys) must be distributed too, so if an attacker tries to make life difficult by deleting these keys from a remote repository nothing is fully lost.  Think of scenarios like a disgruntled client which doesn't the get access it wants (or even a crypto-malware type of attack) , but have full ssh/sftp access to the repository; that user can delete (or even encrypt) the keys stored in the repository - which removes access to some or all others as well.

This scribbling is purely just food for the mind ... not saying this is a perfect solution (it is way far from that), just planting some seeds.  Who knows what can come out of it in the future? :)

**Comment by sanmai** [comment]
There's closely related proposal #784. Would it work for you?

**Comment by fd0** [comment]
Thanks for writing up your ideas @dsommers. This sounds like a combination of a remote mode (#784) and asymmetric backups (#187), which we may add later. For that I need to be done with more pressing issues (like the metadata cache, the new repo format etc), and for each of the (many) features and ideas you have we'll need to define a use case, a threat model and an attacker model, then talk through the crypto stuff. I know from my own experience that the last part gets very tricky very fast, and it always helps having properly defined the former parts for the discussion.

**Comment by dsommers** [comment]
Fully agree, @fd0!  Please let me know if I can be of some help.  I am working full time on OpenVPN, so I won't have much coding time available (and I still haven't had time to dig into Go).  But on threat/attacker models and the higher levels of the crypto stuff I believe I can be of some help.

**Comment by dsommers** [comment]
@sanmai My proposal here is somewhat related to #784, but it goes further.  In #784 much of the security aspects to  is handled on the server side, and strictly speaking it may be tampered with by non-restic clients/users.  The ACL model I propose here will tries to make it impossible to tamper with the privileges, and if detected you cannot get the needed keying material to do operations against the repository; regardless of what SSH allows you to do or not.  My goal is to reduce the attack vector to be as close to `restic` alone.

With that said, a server side component of restic with a "server mode" is a reasonable concept.

**Comment by cfcs** [comment]
@dsommers re: SSH/SFTP: Perhaps a bit pedantic, but you specifically said `using sftp`, which is not possible:
> Some operations could probably be run directly on the remote host when using sftp, in particular forget and prune operations, but probably also "search" functions as well.

It's quite common to limit SSH users to only be allowed to use SFTP, to hinder them from fucking with the server. In fact it sounds like most of what you want in terms of access control can be implemented with SFTP and Linux DAC, Linux ACLs, and extended attributes like immutability (`chattr +i`) and append-only (`chattr +a`) on files and/or folders.

I don't understand your idea about splitting up the keys used. Why would the metadata about the structure of your repository be any less sensitive than the contents? What if I want to search the actual data and not just metadata? It seems to me like you could just decide to upload the repo key directly and run `restic` on the server if you have SSH access + trust it to be secure.

**Comment by dsommers** [comment]
Last question first ... why is the meta-data less sensitive than the data itself?  If you have something "top secret" stored in a file named "meeting-20170203.odt" with a file size of 390kb with some uid/gid references, the file information, file size, etc are arguably less sensitive than the contents of that file.

So if you want to search for contents *inside* files, then this remote option is not secure enough in my point of view.  In that case, you need to do this search over the network where the client itself unlocks the user data and does the search locally.  But purge, forget or searching for file names (which basically depends on the meta-data) can be quite faster when the operation is running on the same system the data is stored on vs pulling that data over the wire as needed.   With that said, I haven't yet seen or tested any backup solution which allows searching inside the user-data.  All I solutions I have used or considered have only supported meta-data lookup; in the more enterprise version this is most commonly stored in an SQL database.

Yes, you are probably right that a similar approach may be implementedthrough DAC and POSIX extended attributes.  But that does still not protect the data if the a rouge clients finds ways to circumvent this (f.ex. like [bugs](https://bugzilla.redhat.com/show_bug.cgi?id=1161164) like this).  A sysadmin may reset the ACLs by [mistake](https://www.cyberciti.biz/tips/my-10-unix-command-line-mistakes.html) (search for `chmod`).  And `chattr`, `chmod`, `setfacl` and their variants are not necessarily restricted to only the creator of a directory or file.

The split-key approach actually accounts for these issues.  A `restic` client with access to a shared repository will not be able to do anything (but damage through deleting/rename files) if the user tries to elevate its privileges.  If that happens, the sub-key that client have access to cannot be decrypted, thus give access to the passphrase unlocking the meta- or user-data on disk.  And even a rogue sys-admin where the data is stored cannot also not change this easily.  In essence, the split-key approach allows to differentiate privileges by a non-sys-admin using the same unix account.  Plus the sub-key model would even work on systems (including file systems) not even supporting user/group ACL controls at all.

**Comment by cfcs** [comment]
1) Filenames can be less sensitive. They can arguably reveal exactly what you're trying to keep hidden. "Why we are merging with Acme Inc.docx"; "steaming-hot-heterosexual-sex-in-a-country-where-thats-illegal.mov"; and so on. If you're running Linux with NetworkManager the filenames expose the SSIDs of all the wifi networks you've been connected to, for example. This is very much a "I have a specific use-case where this is kind of OK"-type change you're asking for.

2) See 1), the same argument remains valid.

3) Few points:
  - See 1) again
  - That specific bug does not bypass extended attributes in the underlying filesystem. `immutable` or `append-only` are not magically ignored by the NFS server - why would you expose your restic files over NFS? Would you really run NFS on a supposedly secure server?
    - Sure, if you have rogue clients with local access. In that case you probably shouldn't be using this server for backups, and sending it encryption keys sounds dangerous.
- If a sysadmin resets ACLs by mistake, and doesn't rectify it, perhaps you should fire them or move them to a junior position with less responsibility.
  - `chmod` is not used to modify ACLs on Linux; you use `setfacl` for that. It's hardly something you type by accident, inside the restic storage folder.
  - `chattr` is restricted to the uid 0 user (plus/minus namespaces - probably also anyone with `CAP_DAC_OVERRIDE` which is hopefully no-one), so not even the owner can fuck this up. You literally have to hire Jar Jar Binks and give them root access to fuck this up.
  - At this point you could start arguing that remote storage is not safe anymore because the BOFH at the remote site might be deleting the backups out of sheer malice.

4) The split-key approach is IMHO not a conceptually bad idea, but it enables users to use restic in an unsafe way, and it adds more "moving parts" that can go wrong.
The split-key approach, when used to give the metadata key away, effectively is equivalent to not encrypting the metadata; It allows anyone you share the machine with to read your metadata.

**Comment by dsommers** [comment]
> Would you really run NFS on a supposedly secure server? 

Why not?  NFSv4 with Kerberos authentication is considered safe and deployed at large organisations.  This also enables the NFSv4 setting sec=krb5p, where all the RPC calls goes encrypted.

> chmod is not used to modify ACLs on Linux; you use setfacl for that. It's hardly something you type by accident, inside the restic storage folder.

Well, `setfacl` have the `-R` option ... so having an error in the path or being in the wrong directory when using `setfacl -R` can implicit hit a restic data directory.  Anyone claiming that they have never done such a mistake is either lying or haven't had long enough experience with sys-admin tasks.

> chattr is restricted to the uid 0 user (plus/minus namespaces - probably also anyone with CAP_DAC_OVERRIDE which is hopefully no-one)

Well, there are sysadmins with root access.  And again `-R` is also supported by `chattr`.  And "hopefully no-one" is a typical FLW.  Somebody is definitely doing stupid things.

> The split-key approach, when used to give the metadata key away, effectively is equivalent to not encrypting the metadata

How come?  The only one who will have access to these data are clients who have been provided with these sub-keys.  The only time the subkeys decrypted and present on the server side is inside the restic process memory when a client have started a remote server operation.  Otherwise, all keys are encrypted on-disk everywhere.  So to be able to read the meta-data, you need access to the meta-data encryption key and be able to decrypt it first.  That gives the information needed to decrypt the meta-data stored on-disk.

**Comment by cfcs** [comment]
Let's agree to disagree, on all points. :-)
