### ISSUE TITLE
restore of sockets

### ISSUE THREAD

**Issue by moho1** [restic/restic#82]
I tried to restore a backup of my home directory, but the restore fails when trying to restore a socket, created by gnupg. The creation of the socket seems to fail silently and causes the following chmod to fail (yes, the socket does not exists afterwards).

	% sudo restic -r /backup/restic restore 541eed2a home
	Enter Password for Repository: 
	restoring <Snapshot "/mnt/backup/btrfs/home/current" at 2015-02-01 01:24:58.352747129 +0100 CET> to home
	error for home/moho1/.PlayOnLinux/gpg/S.gpg-agent: create node, Chmod: chmod home/moho1/.PlayOnLinux/gpg/S.gpg-agent: no such file or directory
	error for moho1/.PlayOnLinux/gpg: restore subtree, create node, Chmod: chmod home/moho1/.PlayOnLinux/gpg/S.gpg-agent: no such file or directory
	error for moho1/.PlayOnLinux: restore subtree, restore subtree, create node, Chmod: chmod home/moho1/.PlayOnLinux/gpg/S.gpg-agent: no such file or directory
	error for moho1: restore subtree, restore subtree, restore subtree, create node, Chmod: chmod home/moho1/.PlayOnLinux/gpg/S.gpg-agent: no such file or directory
	error for .: restore subtree, restore subtree, restore subtree, restore subtree, create node, Chmod: chmod home/moho1/.PlayOnLinux/gpg/S.gpg-agent: no such file or directory
	restore subtree, restore subtree, restore subtree, restore subtree, create node, Chmod: chmod home/moho1/.PlayOnLinux/gpg/S.gpg-agent: no such file or directory

A debug log only shows the following:

    2015/02/01 18:24:04 [restic] main []string{"/home/moho1/usr/go/src/github.com/restic/restic/cmd/restic/restic.debug", "-r", "/backup/restic", "restore", "541eed2a99917daf22f14b988c71a4c019765520894079b3d59be26a4ee5df21", "home"}
    2015/02/01 18:24:11 [restic] main []string{"/home/moho1/usr/go/src/github.com/restic/restic/cmd/restic/restic.debug", "-r", "/backup/restic", "restore", "541eed2a99917daf22f14b988c71a4c019765520894079b3d59be26a4ee5df21", "home"}

The node-entry for the socket is:

		{
		"name": "S.gpg-agent",
		"type": "socket",
		"mode": 493,
		"mtime": "2014-12-05T16:20:23.61970057+01:00",
		"atime": "2014-12-08T10:13:37.189999886+01:00",
		"ctime": "2014-12-26T00:47:43.860350493+01:00",
		"uid": 1000,
		"gid": 1000,
		"user": "moho1",
		"inode": 168029,
		"content": null
		},

**Comment by fd0** [comment]
Thanks for the report! This is indeed a bug: Sockets cannot be restored, they are created the moment a program starts to listen. Therefore, restic shouldn't try to restore the socket.

The debug log capabilities have been introduced only recently and the restore functionality does not yet use it.
