### ISSUE TITLE
fuse: speed up listing very large files

### ISSUE THREAD

**Issue by fbkopp** [restic/restic#820]
## Output of `restic version`
root@user-linux:~# restic version
restic 0.4.0 (v0.4.0-70-g3d1dc63-dirty)
compiled with go1.7.4 on linux/amd64

## Expected behavior
no delay to list directory contents

## Actual behavior
it take more than 12 minutes

## Steps to reproduce the behavior

```
root@user-linux:~# restic mount -r /data/teste2/ /mnt/ --allow-other --owner-root
enter password for repository:
Now serving the repository at /mnt/
Don't forget to umount after quitting!
```

****in another terminal
```
root@user-linux:~# cd /mnt/

root@user-linux:/mnt# ls
snapshots

root@user-linux:/mnt# cd snapshots/2017-02-22T08\:30\:31-03\:00/

root@user-linux:/mnt/snapshots/2017-02-22T08:30:31-03:00# ls
Backup

root@user-linux:/mnt/snapshots/2017-02-22T08:30:31-03:00# time ls
Backup

real    0m0.001s
user    0m0.000s
sys     0m0.000s

root@user-linux:/mnt/snapshots/2017-02-22T08:30:31-03:00# cd Backup/SERVER/WindowsImageBackup/SERVER/Backup\ 2017-02-21\ 213024/

root@user-linux:/mnt/snapshots/2017-02-22T08:30:31-03:00/Backup/SERVER/WindowsImageBackup/SERVER/Backup 2017-02-21 213024# time ls -la                                                      total 857713444
-rwxr-xr-x 1 root root          776 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_AdditionalFilesc3b9f3c7-5e52-4d5e-8b20-19adc95a34c7.xml
-rwxr-xr-x 1 root root        37498 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Components.xml
-rwxr-xr-x 1 root root         5520 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_RegistryExcludes.xml
-rwxr-xr-x 1 root root         3138 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writer0bada1de-01a9-4625-8278-69e735f39dd2.xml
-rwxr-xr-x 1 root root         2168 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writer4dc3bdd4-ab48-4d07-adb0-3bee2926fd7f.xml
-rwxr-xr-x 1 root root         1488 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writer542da469-d3e1-473c-9f4f-7847f01fc64f.xml
-rwxr-xr-x 1 root root         7712 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writer66841cd4-6ded-4f4b-8f17-fd23f8ddc3de.xml
-rwxr-xr-x 1 root root         1628 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writer75dfb225-e2e4-4d39-9ac9-ffaff65ddf06.xml
-rwxr-xr-x 1 root root         1484 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writera6ad56c2-b509-4e6c-bb19-49d8f43532f0.xml
-rwxr-xr-x 1 root root         3828 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writerafbab4a2-367d-4d15-a586-71dbb18f8485.xml
-rwxr-xr-x 1 root root         8578 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writerbe000cbe-11fe-4426-9c58-531aa6355fc4.xml
-rwxr-xr-x 1 root root         1746 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writerd61d61c8-d73a-4eee-8cdd-f6f9786b7124.xml
-rwxr-xr-x 1 root root      3883510 Fev 21 21:22 4a66920e-938b-49ab-8ebd-ece661f14c23_Writere8132975-6f93-4464-a53e-1050253ae220.xml
-rwxr-xr-x 1 root root         4180 Fev 21 21:22 BackupSpecs.xml
-rwxr-xr-x 1 root root    312475648 Fev 21 21:22 d59a8009-4aa9-11e6-80b4-806e6f6e6963.vhdx
-rwxr-xr-x 1 root root  29628563456 Fev 21 21:22 d59a800a-4aa9-11e6-80b4-806e6f6e6963.vhdx
-rwxr-xr-x 1 root root 667455324160 Fev 21 21:22 fbeabc3c-4aa9-11e6-80b5-74867af88755.vhdx
-rwxr-xr-x 1 root root 180898234368 Fev 21 21:22 fbeabe4d-4aa9-11e6-80b5-74867af88755.vhdx

real    12m46.908s
user    0m0.001s
sys     0m0.003s
root@user-linux:/mnt/snapshots/2017-02-22T08:30:31-03:00/Backup/SERVER/WindowsImageBackup/SERVER/Backup 2017-02-21 213024#

```

**Comment by fd0** [comment]
Huh, that's odd indeed. Thanks for the report!

What backend are you using? Do you maybe have a high latency to a remote storage location?

Could you please create a [debug log](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs) of the fuse mount and the `ls` that takes so long?

**Comment by fbkopp** [comment]
What back end are you using?
R: local file system with btrfs raid1

 Do you maybe have a high latency to a remote storage location?
R: No, its local drives

Could you please create a debug log of the fuse mount and the ls that takes so long?
R: the log is 5,2gb, compressed is here https://transfer.sh/MD4VX/restic-debug.gz

i think problem is huge files in backup
in log: 2017/02/28 08:55:56 fuse/file.go:43     fuse.newFile    155     create new file for fbeabc3c-4aa9-11e6-80b5-74867af88755.vhdx with 831130 blobs
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 526df4f9 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 526df4f9 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 526df4f9 not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 526df4f9 found in pack 62a865c1 at 591153, length 524320
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 526df4f9 found in pack 62a865c1 at 591153, length 524320
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 07854d2f not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 07854d2f not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 07854d2f not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 07854d2f found in pack 342c96e1 at 14600, length 524320
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 07854d2f found in pack 342c96e1 at 14600, length 524320
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id d86ea3e6 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id d86ea3e6 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id d86ea3e6 not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id d86ea3e6 found in pack 62a865c1 at 2249628, length 524320
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id d86ea3e6 found in pack 62a865c1 at 2249628, length 524320
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id a7e42294 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id a7e42294 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id a7e42294 not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id a7e42294 found in pack 342c96e1 at 3248852, length 524601
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id a7e42294 found in pack 342c96e1 at 3248852, length 524601
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id fb339e06 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id fb339e06 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id fb339e06 not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id fb339e06 found in pack 342c96e1 at 3773453, length 524320
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id fb339e06 found in pack 342c96e1 at 3773453, length 524320
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 38f28a53 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 38f28a53 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 38f28a53 not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 38f28a53 found in pack 36ab4604 at 0, length 524320
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 38f28a53 found in pack 36ab4604 at 0, length 524320
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id d5f3509f not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id d5f3509f not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id d5f3509f not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id d5f3509f found in pack 36ab4604 at 1573241, length 794891
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id d5f3509f found in pack 36ab4604 at 1573241, length 794891
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 67282298 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 67282298 not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 67282298 not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 67282298 found in pack 36ab4604 at 3515088, length 1336449
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 67282298 found in pack 36ab4604 at 3515088, length 1336449
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id a7dd000f not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id a7dd000f not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id a7dd000f not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id a7dd000f found in pack 667c25aa at 1048640, length 524320
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id a7dd000f found in pack 667c25aa at 1048640, length 524320
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 07854d2f not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 07854d2f not found
2017/02/28 08:55:56 repository/index.go:140     repository.(*Index).Lookup      155     id 07854d2f not found
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 07854d2f found in pack 342c96e1 at 14600, length 524320
2017/02/28 08:55:56 repository/index.go:122     repository.(*Index).Lookup      155     id 07854d2f found in pack 342c96e1 at 14600, length 524320

in ls -la: -rwxr-xr-x 1 root root 667430158336 Fev 24 21:22 fbeabc3c-4aa9-11e6-80b5-74867af88755.vhdx
the file has 667,43gb in size.

and there is no optimization to search repository
root@fabio-linux:/data# wc -l restic-debug.log
56616223 restic-debug.log
root@fabio-linux:/data# cat restic-debug.log | grep "repository/index.go:140" | wc -l
54486092

**Comment by fd0** [comment]
Oh, yeah, that explains it! Thanks for helping to debug this!

**Comment by fd0** [comment]
Could you please check if the code in #998 resolves your issue?

**Comment by fbkopp** [comment]
This code addresses the problem of listing directories with large files,
Thank you,

**Comment by fd0** [comment]
Thanks for the feedback!
