### ISSUE TITLE
Add `--host` switch to `mount` command

### ISSUE THREAD

**Issue by paulvt** [restic/restic#821]
It would allow the user to access/browse snapshots of other hosts than the current one.
This is for example useful for hosts that are no longer alive or available.

The switch is possible useful for other commands too?

**Comment by sanmai** [comment]
Related: #793

**Comment by fd0** [comment]
Hey, thanks for opening this issue. I do not yet understand what an option `--host` to the `mount` command should do. Could you elaborate a bit please?

At the moment restic allows browsing all snapshots from all hosts in the repository via fuse.

The parameter to the backup command was only added to manually specify a different hostname than the one restic automatically detects when a backup is made.

**Comment by paulvt** [comment]
It would be just to filter, I guess. Currently, you have to mount, then list the snapshots, grep for the hostname, and then use the list in a second terminal to browse through the matching dates under the mount.

**Comment by middelink** [comment]
This was fixed in PR #866

**Comment by fd0** [comment]
Indeed, thanks for the reminder!
