### ISSUE TITLE
empty line in files-from adds all

### ISSUE THREAD

**Issue by skojin** [restic/restic#822]
## Output of `restic version`

restic 0.4.0 (v0.4.0-0-ga7c2f28-dirty)
compiled with go1.7.5 on linux/amd64

## Expected behavior

Empty line in -files-from file will be ignored

## Actual behavior

Empty line in -files-from file treat as current directory, 
for file

    file1.txt
    
    file2.txt

backup command try to backup current directory completely

scan [/home/me/file1.yml /home/me /home/me/file1.yml]

## Steps to reproduce the behavior

add empty line in -files-from file and start backup from non empty directory

**Comment by fd0** [comment]
Ah, that's not the intended behavior, thanks for reporting it!
