### ISSUE TITLE
restore file to restore root owned file

### ISSUE THREAD

**Issue by skojin** [restic/restic#825]
## Output of `restic version`
restic 0.4.0 (v0.4.0-0-ga7c2f28-dirty)
compiled with go1.7.5 on linux/amd64

## Steps to reproduce the behavior

I backup by ngnix config that owned by root, restore fail with

error for b-rest/config-name: lchown b-rest/config-name: operation not permitted
Lchown
restic.Node.restoreMetadata
        /tmp/restic-build-119647226/src/restic/node.go:147

I think we need option to ignore permissions when restore, since I primary backup file content not permissions.

**Comment by fd0** [comment]
Agreed, I'm already working on this: Split errors for restore into two categories: Fatal and non-fatal (e.g. permission errors), and add an option to ignore non-fatal errors for restore.

**Comment by JusticeForMikeBrown** [comment]
Any idea on how to address? 

Followed the guide and created a service account called restic then set these permissions on binary at '/usr/bin/restic'

> 0750
> 
> setcap cap_dac_read_search=+ep

`-rwxr-x---. 1 root restic 12M Jun 14 11:08 /usr/bin/restic`

**Comment by JusticeForMikeBrown** [comment]
Please see my solution in #1766.

**Comment by fd0** [comment]
This issue has already been solved in the latest version, restic will print the errors but continue anyway. I'm closing it here. Thanks!
