### ISSUE TITLE
Manually select key ID

### ISSUE THREAD

**Issue by robbat2** [restic/restic#826]
## Output of `restic version`
restic 0.4.0
compiled with go1.6.2 on linux/amd64

## Expected behavior
Restic should allow manual selection of key by ID for ALL actions (eg specific key-id & password during backup)

## Actual behavior
Key is selected by trying all keys to find one that works with the provided password.

If there are many keys on a remote repo, this can take a long time, and on a local repo, restic can be seen with `strace` opening the keys one at a time.

## Steps to reproduce the behavior
Add many keys to a repo, with different passphrases, and then try to use one that comes late in the list.

**Comment by fd0** [comment]
Good point, thanks for reporting this!

**Comment by MichaelEischer** [comment]
This has been implemented in restic 0.9.4, see #2097.
