### ISSUE TITLE
key add, key passwd: Allow new password via scripting

### ISSUE THREAD

**Issue by robbat2** [restic/restic#827]
## Output of `restic version`
restic 0.4.0
compiled with go1.6.2 on linux/amd64

## Expected behavior
Restic should be fully scriptable to add a new key or rotate the password of a key:
* `restic -p $OLD_PASS_FILE key add --new-password-file $NEW_PASS_FILE`
* `restic -p $OLD_PASS_FILE key passwd $ID --new-password-file $NEW_PASS_FILE`

## Actual behavior
`restic -p` argument uses the same password for the new key as the existing key.

See also #826 that wants to add consistent manual selection of keys

**Comment by fd0** [comment]
Hey, thanks for suggesting this. Could you please describe your use case?

**Comment by robbat2** [comment]
Use case: Using an S3 repo, I'd like an administrative host to be able (scriptable) to create a number of keys with unique passphrases, one for each host being backed up.

Better yet  would be to say that the later keys are permitted to do backups, but not change any settings (or restore, but that's into the realm of asymmetric keys).

**Comment by fd0** [comment]
Thanks for the explanation, that makes sense.

**Comment by HLeithner** [comment]
+1

**Comment by skriss** [comment]
an easy way to add this would be to allow the new password to be passed via stdin, similarly to how it's allowed for other commands. So at https://github.com/restic/restic/blob/master/cmd/restic/cmd_key.go#L72, change to something like:

```
if stdinIsTerminal() {
	return ReadPasswordTwice(newopts,
		"enter password for new key: ",
		"enter password again: ")
} else {
	return readPassword(os.Stdin)
}
```

Which would be very similar to how it's done for other commands, i.e. https://github.com/restic/restic/blob/master/cmd/restic/global.go#L284

Is that reasonable? Happy to submit a PR if so.
