### ISSUE TITLE
Recover from broken pack file

### ISSUE THREAD

**Issue by fd0** [restic/restic#828]
This is a followup issue for #816: Add code to allow recovering from a broken/modified pack file.

**Comment by vrusinov** [comment]
My repo got corrupt by a bad hardware (non-ECC ram crapped out), so I had to do something.

I came up with a very naive solution which still helped in my case: https://github.com/vrusinov/restic/commit/114162a7f47501956cc2d45f18380b54032ea232 simply skips over the broken packs.

Here are logs from my run (sorry - I did not redirect them to file and they got corrupt via multiple screen resizes):

```
$ ./restic -r <...> prune
repository 835063d2 opened successfully, password is correct
counting files in repo
building new index for repo
[45:51:51] 100.00%  432804 / 432804 packs
repository contains 432804 packs (2663948 blobs) with 2.023 TiB
processed 2663948 blobs: 1313002 duplicate blobs, 922.721 GiB duplicate
load all snapshots
find data that is still in use for 90 snapshots
[0:20] 100.00%  90 / 90 snapshots
found 882714 of 2663948 data blobs still in use, removing 1781234 blobs
will remove 0 invalid files
will delete 40687 packs and rewrite 230464 packs, this frees 1.138 TiB
                                                                                                                                          [7hash does not match id: want 0ef6e1bdb59dc4e8163c2c992908976044cb676206c216c007a672b9070f0640, got 7943171a72b60cccbcf1ff24f9ff17c3687777e8ehash does not match id: want 439033a843e2bae9086dcdd6bd18ec2eb36613f46c806a3814b2adb5116a9da6, got 04b44f28d3ccb224bba6be86afeb6407aa347c8dahash does not match id: want bc436381b40346bb72c4317d073091f3781bd489eeac266f184cc4803e3be5ca, got 84955fhash does not match id: want 74802e2af1c8bbbb22af9a4421cfa7b01e7cfbb3d925604c85c3d10f147b42c3, got 711986                                                          [1                                             [126:44:28] 82.95%  1911hash does not match id: want 0147da880e3dc750856e723e03dcf92092defeb30352d1388e4eddea1483bfe5, got acb1d7789329cba8d7f58677f45b57252598949                         [140:05:15] 98.64%  227336 / 230464 packs re[141:12:02] 100.00%  230457 / 230464 packs rewritten
counting files in repo
[6:45:31] 100.00%  198187 / 198187 packs
finding old index files
saved new indexes as [939ea75c 958bb9fc 493847d1 fec9d699 46587741 d976bd69 e4aa6b10 2a40e95d f2bd7833 fd6ae06f 5b998eef 91abaa44 743b30c9 bbcb74b8 945cea7c 1385d4b6 cf14a0ba 602f3bdf 2362c449 49f7c33c 37bf8057 80397d49 c019d3da d0d029ab 8c6321fd 2e9fab47 4dab459b 256f44e2 ad325830 922f8c0e efe5454e 586eddda dd824156 e2c89304 3597a4ce 5173f03c 5dee0eb3 8d4a562f c7c0320b 2ac34992 9cbdf625 af9b1b0e 4d69c195 9eef2abf 03f6512b c9e29d26 d6761cbd 5943e5e6 5112cfa2 9e133a60 6acf5d39 5ca49088 bf13f5b6 60582ed7 d615119b 8eb4fcd8 516c342e 02920c6c 4a54d4df 4ce566e1 e5fb2bf2 84286cf0 936a40a8 9a750234 8666f490 21e5d0ba 8c8f65e9]
remove 1442 old index files
[61:29:21] 100.00%  271151 / 271151 packs deleted
done
```

This also shows the impact of not collecting garbage for ~3 months. :)

Pros of this solution:
- it works :)
- it is super easy to implement and understand
- there's little chance that it will introduce more corruption by trying to do some clever recovery

The cons are:

- this may drop some potentially recoverable data
- logging needs to be more visible. It should *shout* about data loss.
- maybe we should make it flag-controlled - I don't think it's ok to drop stuff by default as it may destroy too many things, especially if run on the same hardware which introduced corruption in the first place

Now, @fd0 - what do do you think about this? If we agree on simply dropping broken packs, I'll be happy to make it flag-protected, improve logging and maybe to write some tests (although proper tests would be tricky - not sure how much patience will I have).

**Comment by MichaelEischer** [comment]
I've extended @fd0's [debug-1999](https://github.com/restic/restic/tree/debug-1999) branch as a stop-gap solution to help with recovery by extracting all intact parts of the damaged pack file. You can use it as follows:
- Build the debug-1999 branch using `go build -tags debug ./cmd/debug`
- Run `restic debug examine --extract-pack <id-of-broken-pack-file>` to extract all blobs in the damaged pack file into the current folder (-> it's best to use a temporary folder to reduce the chaos). The packfile must still be located in the proper place inside the repository, but it is not necessary for it to be contained in the repository index (i.e., there's no need to run `rebuild-index`, please **do not** run that command right now) The option `--try-repair` can be used to try to repair a single bit flip, and `--repair-byte` tries to repair a full byte at once (but is also much slower)
- Move the damaged pack file out of the repository, create a backup of the index and run `restic rebuild-index`
- Then run `restic backup .` in the folder which contains the extracted blobs
- Now with a bit of luck `restic check --read-data` should no longer report errors or only a few ones
- If the missing blobs are part of a file of which you still have the original, then run `restic backup <original-file>`, which will recover the missing blobs.
- Afterwards you can delete the snapshots created while recovering the error.

To repair the remaining errors you can either remove affected snapshots (use the `find` command to find snapshots which use a certain blob or pack). Or try the `repair` command from PR #2876.

**Comment by steph2016** [comment]
I had the 'Fatal: number of used blobs is larger than number of available blobs #3631' issue. I finally followed Route 2: for each error, I made a 'find tree' then 'restic forget' the corresponding snapshot. The 'restic check' finally worked, but it remains only 4 snapshots over the 18.

**Comment by hvhaugwitz** [comment]
I recently recovered my repo after partial disk failure (mostly using route 2).

Why is this not part of the restic documentation and would it be possible to add a `repair` command that simplifies/automates the mentioned steps?

**Comment by MichaelEischer** [comment]
The repair steps still require a lot of manual effort (likely too much for many users), so we'd like to offer a much more automated way, probably using a derivative of #2876. That would automate all steps of route 2 starting after `rebuild-index`.

**Comment by ctonsing** [comment]
> _Updated on 30.04.2022_
> 
> # **Please add a reaction to this post if you used it to repair a damaged repository.**

Just a quick question: which approach should be used when attempting to repair a damaged repository with an error like ```The index references 2 needed pack files which are missing from the repository``` ?

**Comment by MichaelEischer** [comment]
> with an error like `The index references 2 needed pack files which are missing from the repository` ?

For that error either Route 2 or Route 3 should work. But please make sure to first fix the issue that caused the missing pack files.

**Comment by ctonsing** [comment]
Thank you @MichaelEischer, much appreciated. I followed route 2 and it worked as expected. The missing blobs could be re-uploaded from disk and restic check returns no errors anymore. Unfortunately it's not really possible anymore to determine what caused the issue in the first place. I suspect it was the storage provider (Ceph cluster) which ran into some problems during a restic operation sometime in the past.

**Comment by darrinsmart** [comment]
Appreciate the tips here. I have a corrupt repo, which passes `restic check` but failes `restic check --read-data`:
```
Pack ID does not match, want a2fd8ddf0f5cc12328ad8b84d439f43ed59d33ab63bb7fb5411a404d20d51030, got 41442f67ab5ebedf513d3813222fdff6db0714a4b7499929fe8d7dc88b6a9223
Pack ID does not match, want a903774dc0c438d65f9bcf3d6523e5c50b2162b4d6fc815de524a7f209d32171, got 5250debabe1ce648075a2c046995011b7075e7bc5f1fb7d4c27b9ef6acf0a237
```
So I'm going route 1. Unfortunately I get a crash when running `restic debug examine --reupload-blobs --try-repair 41442f67ab5e6db0714a4b7499929fe8d7dc88b6a9223 5250debabe1cb7075e7bc5f1fb7d4c27b9ef6acf0a237`:

```
examine a2fd8ddf0f5cc12328ad8b84d439f43ed59d33ab63bb7fb5411a404d20d51030
  file size is 5454034
Load(<data/a2fd8ddf0f>, 0, 0) returned error, retrying after 552.330144ms: loadAll(<data/a2fd8ddf0f>): invalid data returned
Load(<data/a2fd8ddf0f>, 0, 0) operation successful after 1 retries
  wanted hash a2fd8ddf0f5cc12328ad8b84d439f43ed59d33ab63bb7fb5411a404d20d51030, got 41442f67ab5ebedf513d3813222fdff6db0714a4b7499929fe8d7dc88b6a9223
  ========================================
  looking for info in the indexes
      data blob 9ecbbdcc35046151b087429a9df9a025700756964b5a4f0ae55d1fdf6d32c5b0, offset 0     , raw length 624551
      data blob fb3543722c582da96639fa14f4b32b848408d9c05c658884354248ea3bebede7, offset 624551, raw length 4829373
      file sizes match
      loading blob 9ecbbdcc35046151b087429a9df9a025700756964b5a4f0ae55d1fdf6d32c5b0 at 0 (length 624551)
         successfully decrypted blob (length 624519), hash is 9ecbbdcc35046151b087429a9df9a025700756964b5a4f0ae55d1fdf6d32c5b0, ID matches
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8c9065]

goroutine 1 [running]:
github.com/restic/restic/internal/repository.(*packerManager).SaveBlob(0x0, 0x1457c20, 0xc000814000, 0x610435ccbdcb9e01, 0xa0f99d9a4287b051, 0x4f5a4b9656077025, 0xc5326ddf1f5de50a, 0xc001d920b0, 0xc002200000, 0x91a0c, ...)
	/nfs/kona-home/users/darrin/src/restic/internal/repository/packer_manager.go:69 +0x65
github.com/restic/restic/internal/repository.(*Repository).saveAndEncrypt(0xc00080cb60, 0x1457c20, 0xc000814000, 0xa4f5a4b96560701, 0xc001d92000, 0x919ec, 0x98787, 0x51610435ccbdcb9e, 0x25a0f99d9a4287b0, 0xa4f5a4b96560770, ...)
	/nfs/kona-home/users/darrin/src/restic/internal/repository/repository.go:432 +0x3a7
github.com/restic/restic/internal/repository.(*Repository).SaveBlob(0xc00080cb60, 0x1457c20, 0xc000814000, 0x1, 0xc001c44010, 0x98787, 0x98797, 0x51610435ccbdcb9e, 0x25a0f99d9a4287b0, 0xa4f5a4b96560770, ...)
	/nfs/kona-home/users/darrin/src/restic/internal/repository/repository.go:843 +0x295
main.loadBlobs(0x1457c20, 0xc000814000, 0x146afc0, 0xc00080cb60, 0x23c15c0fdf8dfda2, 0x3ef439d4848bad28, 0xb57fbb63ab339dd5, 0x3010d5204d401a41, 0xc0062b8080, 0x2, ...)
	/nfs/kona-home/users/darrin/src/restic/cmd/restic/cmd_debug.go:393 +0x9dd
main.examinePack(0x1457c20, 0xc000814000, 0x146afc0, 0xc00080cb60, 0x23c15c0fdf8dfda2, 0x3ef439d4848bad28, 0xb57fbb63ab339dd5, 0x3010d5204d401a41, 0x0, 0x0)
	/nfs/kona-home/users/darrin/src/restic/cmd/restic/cmd_debug.go:519 +0x6b6
main.runDebugExamine(0x1457c20, 0xc000814000, 0xc0000460a2, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/nfs/kona-home/users/darrin/src/restic/cmd/restic/cmd_debug.go:471 +0x335
main.glob..func9(0x1b597a0, 0xc000814200, 0x2, 0x4, 0x0, 0x0)
	/nfs/kona-home/users/darrin/src/restic/cmd/restic/cmd_debug.go:199 +0xb1
github.com/spf13/cobra.(*Command).execute(0x1b597a0, 0xc0008141c0, 0x4, 0x4, 0x1b597a0, 0xc0008141c0)
	/nfs/kona-home/users/darrin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x49f
github.com/spf13/cobra.(*Command).ExecuteC(0x1b5bfa0, 0x23, 0xc0006c7eb8, 0x4)
	/nfs/kona-home/users/darrin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/nfs/kona-home/users/darrin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/nfs/kona-home/users/darrin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
main.main()
	/nfs/kona-home/users/darrin/src/restic/cmd/restic/main.go:98 +0x1d7
```

I was able to extract & repair blobs with `restic debug examine --extract-pack --try-repair a2fd8ddf0f5cc12328ad8b84d439f43ed59d33ab63bb7fb5411a404d20d51030 a903774dc0c438d65f9bcf3d6523e5c50b2162b4d6fc815de524a7f209d32171`. It found 2 blobs with bit-flip errors.

Is there a way to re-insert the extracted blobs?

(I'm using the master branch of restic, at commit 5f9ac2b1)

**Comment by MichaelEischer** [comment]
@darrinsmart Let's discuss that in a new issue. I'd prefer not to clutter this one too much.
