### ISSUE TITLE
Kubernetes integration

### ISSUE THREAD

**Issue by tamalsaha** [restic/restic#831]
Hi,
I wanted to let you know that we are planning on integrating restic with Kubernetes. Here is our proposal: https://github.com/appscode/restik/issues/1

If you guys have comments, I would love to hear that in the proposal issue.

**Comment by fd0** [comment]
Interesting, I'll have a look.

**Comment by bzub** [comment]
It's not much, but I wanted to share my restic and rest-server container repos/images.  They are working well for me in Kubernetes so far.  Hope it helps.

https://gitlab.com/bzub/restic
https://gitlab.com/bzub/rest-server
https://quay.io/repository/bzub/restic
https://quay.io/repository/bzub/rest-server

**Comment by tamalsaha** [comment]
Thanks @bzub . We are close to releasing this. https://github.com/appscode/stash . If you have any questions, let us know in our project repo.
