### ISSUE TITLE
Why not import as Traditional "github.com/restic/restic"

### ISSUE THREAD

**Issue by sadlil** [restic/restic#833]
Checking the codebase of restic it occurred to me **Why not the import statement uses the traditional format like** `github.com/restic/restic`? 
I have checked that `build.go` handles the complexities required to build the project. 
But it is hard to use the `src/restic` package as a dependency to build something based on this lib. Also importing as `github.com/restic/restic` could help use `go install` and other options too.

Is there any specific reason to use the import as it is?

BTW Thanks for a this great tool.

**Comment by fd0** [comment]
We've discussed this a few times already, see #444 and #660.

There are two (independent) views to this. The user's view is: It should be easy to compile restic from a checkout of the repo. Do `git clone`, then run `go run build.go` and there's your binary. Especially I think it's important not to burden users with setting up a proper `GOPATH`. Please note that this can also be achieved when the "traditional" directory structure is used, just with different code in `build.go`.

The second view is the one of a developer: We've chosen to use the `gb` build tool a while back (in #444), so this repository is basically its own `GOPATH`. The reasons are described in the issue, one of the most important ones is that you (as a developer) do not need to fiddle around with checking out the repository at the right place in your `GOPATH` and then adding your own fork to it.

As for the "import as library" thing: Although the project is structured as a library and an executable, the library part is not suitable for importing in a different project. There are no guarantees at all concerning API stability. If this were a traditionally structured repository, I'd probably use an `/internal/` path component which prevents importing in third-party projects.

I'll close this issue as your question is answered, but please feel free to add a comment.

**Comment by sadlil** [comment]
Thanks for the clarification. I had an scenario where i need to run the backups and restore process from another process, instead of running `exec` restic, i wanted to use the same API restic cli uses to do the tasks. Looks like i need to find some work around.

**Comment by fd0** [comment]
We're in the process of adding JSON as an output option (`--json`) to some commands, maybe that's helpful for you in order to parse the results of a command...

**Comment by fd0** [comment]
I'm curious: Can you describe your use case in a bit more detail?

**Comment by sadlil** [comment]
Suppose i am running an Statefull application containerized and running within `kubernetes`. In my prod deployment i am thinking to run another sidecar container that will periodically backup my application's data via restic. So in that case restic needs to run time to time. Instead of running the cli via `exec`, its better to have control over the process using the library the cli uses.  That was my intention to do.

**Comment by TamalSaha** [comment]
@fd0 , @sadlil  and I are working on integrating restic with Kubernetes https://github.com/appscode/restik/issues/1
