### ISSUE TITLE
Use protobufs instead of JSON

### ISSUE THREAD

**Issue by middelink** [restic/restic#838]
Since we are in Go and aiming for not wasting cycles, would it not be a better idea to use protobufs, which are binary on the wire/disk, instead of the ascii(ok, utf8) based json? where each timestamp, integer essentially non-string value needs to be translated thousands of times.

Since protobufs are also extendable and backwards compatible, like json, you will not loose any functionality. (as that seems to be one of the concerns in repov2)

Just saying :)

**Comment by fd0** [comment]
Thanks for raising this again. I'm well aware of alternatives to JSON, for the sake of simplicity we'll stay with JSON for now. Maybe in a later version of the repository. But then we'll also evaluate other alternatives.

**Comment by middelink** [comment]
To further spur the discussion along, profiling restic on my Intel machine and doing just a "find" on a 43G repo (run took 0m50.729s), results in:

(pprof) top25   
31840ms of 53200ms total (59.85%)
Dropped 384 nodes (cum <= 266ms)
Showing top 25 nodes out of 194 (cum >= 420ms)
      flat  flat%   sum%        cum   cum%
    3360ms  6.32%  6.32%     3360ms  6.32%  encoding/json.stateInString
    3080ms  5.79% 12.11%     5420ms 10.19%  encoding/json.checkValid
    2720ms  5.11% 17.22%     3240ms  6.09%  syscall.Syscall
    2590ms  4.87% 22.09%     2590ms  4.87%  crypto/sha256.block
    2050ms  3.85% 25.94%     2050ms  3.85%  runtime.futex
    1800ms  3.38% 29.32%     1800ms  3.38%  runtime.usleep
    1630ms  3.06% 32.39%     2680ms  5.04%  runtime.mallocgc
    1550ms  2.91% 35.30%     3230ms  6.07%  encoding/json.(*decodeState).scanWhile
    1550ms  2.91% 38.21%     2990ms  5.62%  runtime.scanobject
    1230ms  2.31% 40.53%     2670ms  5.02%  encoding/json.nextValue
    1170ms  2.20% 42.73%    21760ms 40.90%  encoding/json.(*decodeState).object
     980ms  1.84% 44.57%      980ms  1.84%  crypto/aes.encryptBlockAsm
     930ms  1.75% 46.32%     2120ms  3.98%  runtime.pcvalue
     860ms  1.62% 47.93%      860ms  1.62%  runtime.greyobject
     790ms  1.48% 49.42%     1920ms  3.61%  time.parse
     770ms  1.45% 50.86%      780ms  1.47%  encoding/json.stateEndValue
     720ms  1.35% 52.22%     3330ms  6.26%  runtime.gentraceback
     600ms  1.13% 53.35%      600ms  1.13%  encoding/json.unquoteBytes
     580ms  1.09% 54.44%      580ms  1.09%  runtime.heapBitsForObject
     550ms  1.03% 55.47%      550ms  1.03%  golang.org/x/crypto/scrypt.salsaXOR
     510ms  0.96% 56.43%      510ms  0.96%  encoding/hex.Decode
     490ms  0.92% 57.35%      490ms  0.92%  runtime.readvarint
     460ms  0.86% 58.21%      460ms  0.86%  runtime.memmove
     450ms  0.85% 59.06%      940ms  1.77%  runtime.step
     420ms  0.79% 59.85%      420ms  0.79%  runtime.epollwait

so json is definitely a place we spend a lot of cycles.

**Comment by middelink** [comment]
Did the same for a 731481 file, 94597 directory backup of my workstation, took 12m7.183s -- although the progressbar reported 3m26.. threads?

(pprof) top25
11.19mins of 12.84mins total (87.21%)
Dropped 855 nodes (cum <= 0.06mins)
Showing top 25 nodes out of 151 (cum >= 0.13mins)
      flat  flat%   sum%        cum   cum%
  4.81mins 37.45% 37.45%   4.81mins 37.45%  crypto/sha256.block
  1.28mins 10.01% 47.46%   1.75mins 13.65%  github.com/restic/chunker.(*Chunker).Next
  1.28mins  9.99% 57.45%   2.61mins 20.32%  runtime.scanobject
  0.83mins  6.45% 63.90%   0.83mins  6.45%  runtime.memclrNoHeapPointers
  0.80mins  6.25% 70.15%   0.80mins  6.25%  runtime.greyobject
  0.57mins  4.43% 74.57%   0.59mins  4.58%  syscall.Syscall
  0.56mins  4.36% 78.93%   0.56mins  4.36%  runtime.heapBitsForObject
  0.14mins  1.07% 80.01%   0.14mins  1.07%  runtime.memmove
  0.12mins  0.96% 80.97%   1.63mins 12.68%  runtime.mallocgc
  0.11mins  0.82% 81.79%   0.11mins  0.86%  syscall.Syscall6
  0.09mins  0.69% 82.48%   0.09mins  0.69%  runtime.usleep
  0.07mins  0.57% 83.06%   0.07mins  0.57%  runtime.futex
  0.06mins   0.5% 83.55%   0.07mins  0.51%  encoding/json.stateInString
  0.06mins  0.47% 84.02%   0.13mins  0.98%  encoding/json.compact
  0.06mins  0.45% 84.47%   0.07mins  0.53%  path/filepath.Clean
  0.06mins  0.43% 84.90%   0.13mins  1.04%  runtime.pcvalue
  0.05mins  0.41% 85.31%   0.23mins  1.79%  runtime.gentraceback
  0.05mins  0.36% 85.67%   0.12mins  0.92%  strings.genSplit
  0.04mins  0.31% 85.98%   0.07mins  0.58%  encoding/json.checkValid
  0.03mins  0.27% 86.26%   4.03mins 31.37%  runtime.systemstack
  0.03mins  0.25% 86.50%   0.08mins  0.59%  runtime.sweepone
  0.03mins  0.23% 86.73%   0.08mins   0.6%  runtime.gcmarkwb_m
  0.02mins  0.18% 86.91%   0.09mins  0.68%  runtime.selectgoImpl
  0.02mins  0.17% 87.08%   0.10mins  0.79%  runtime.writebarrierptr_prewrite1
  0.02mins  0.13% 87.21%   0.13mins  1.02%  runtime.findrunnable

Much less json, much more crypto and Chunker.

**Comment by fd0** [comment]
Thanks for looking at this. I think there are more pressing issues that limit restic in terms of performance, especially the local metadata cache will improve this a lot. Afterwards we may talk about changing the repository format.

I know that I'm slowing you down a bit, you seem to be very eager to improve this :smile:, but I'm very very conservative in regards to changing the repository format. The stability of the repo format is much more important than efficiency improvements :)

**Comment by fd0** [comment]
Besides, there are more efficient JSON parser implementations for Go, e.g.:
 * https://github.com/pquerna/ffjson
 * https://github.com/mailru/easyjson
 * http://jsoniter.com/

We could switch to one of those without having to change the repository format. ffjson for example does not use reflection but employs code generation to generate a parser for a struct.

**Comment by middelink** [comment]
I just added the data to make my point backed up by numbers ^^

No worries, it's just a new project which scratched an itch of mine and it has tons of features I always wanted in a backup tool :) I definitely agree that stability goes before efficiency!

Thanks for the links though, they look interesting.

**Comment by mgumz** [comment]
in general i agree with @fd0 about the stability of the repo-format.

if it comes to "use protobuf"-aspect itself: creating the jsons seems to be the rare case in comparison to "decoding data" -> https://capnproto.org/

i suggest to retag this issue here "RFC".

**Comment by MichaelEischer** [comment]
It's probably too late now to make such a fundamental change of the repository format. Unless we plan to completely revise the repository format, it's not worth the added complexity.
