### ISSUE TITLE
Limit forget to specific path

### ISSUE THREAD

**Issue by robbat2** [restic/restic#841]
## Output of `restic version`
restic 0.4.0
compiled with go1.6.2 on linux/amd64

## Expected behavior
On a given host, it should be possible to keep differing numbers of snapshots for different paths. Eg retain all `/etc`, but only keep a few of `/home`

## Actual behavior
`restic forget` only offers match by hostname and tag

**Comment by fd0** [comment]
Indeed, that may be a good thing to add. Thanks for reporting!

**Comment by middelink** [comment]
Hmm, I can read this two ways, either as a way to filter snapshots on their paths, or as a question to break up an existing snapshot with both /etc and /home in it. The first is doable, the second much much harder. (It would require "surgery" on the snapshot tree, which forget is not about.)

If it's the first, I can have a stab at it.

**Comment by fd0** [comment]
I think it's the former: Adding a "path" filter to the `forget` command, in terms of "if present, do not touch any snapshots that do not include the given path(s)".

**Comment by robbat2** [comment]
Yes, I mean the former. This should NOT poke into a single snapshot at all.

In a forget wrapper, I'd do something like:
```
restic forget --hostname $FOO --path /etc --keep...
restic forget --hostname $FOO --path /home --keep...
```
with different `--keep` parameters for `/etc` vs `/home`

**Comment by robbat2** [comment]
There's a first prototype of it.

Open question: if a snapshot contains multiple root paths, what should the matching behavior be?
Eg, in the `snapshot_filter_test.go` , there are backups with `[]string{"/usr", "/bin"}`

**Comment by robbat2** [comment]
Changed now to require that the paths match exactly, just like the tags.

**Comment by fd0** [comment]
Hm, there are two commits which reference this issue, but no PR yet?

**Comment by middelink** [comment]
Yeah, both of us have it "fixed" in our own trees. For you to look at :)
Mine addresses the bigger issue with all commands, and therefor includes this one.

**Comment by fd0** [comment]
Hm, that's a nice idea but doesn't work so well in practice: The comments are attached to the commit, which is lost when the branch is rebased or otherwise modified. In addition, there's no notification that this issue has been mentioned in a commit (or that a new comment was added), so I don't see your activity.

Please create a PR and comment on the lines there (the comments are then attached to the line in the file, which is preserved for branch rebases and so on), then we can have a proper discussion.

@robbat2 @middelink can we merge your work in a single PR?

**Comment by middelink** [comment]
I think my current PR #856 covers his exactly. Except for the documentation part, which I think is clear enough, but yeah, I read the `SamePaths()` code so I'm not exactly objective there. ^^

**Comment by robbat2** [comment]
My commit was mostly to prototype & discuss it. e9a2982 looks good to promote to a PR.
