### ISSUE TITLE
GOAWAY from minio remote behind a HTTPS nginx reverse proxy.

### ISSUE THREAD

**Issue by JohnnyLeone** [restic/restic#849]
## Output of `restic version`
restic 0.4.0 (v0.4.0-0-ga7c2f28)
compiled with go1.8 on linux/amd64

## Expected behavior
restore my file completely without a GOAWAY result.

## Actual behavior
The minio io instance is behind a HTTPS nginx reverse proxy. After some more testing today i was able to restore my data from minio without the reverse proxy and HTTP only successfully. 
I'm running in an error while restoring my snapshot on my minio storage. I try to restore a ~4.5GB file but every time at 669MB it breaks wit following error. Backing up the file went perfectly fine.
```
http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
obj.ReadAt
restic/backend/s3.(*s3).Load
	/tmp/restic-build-559492747/src/restic/backend/s3/s3.go:179
restic.ReadAt
	/tmp/restic-build-559492747/src/restic/readerat.go:25
restic/repository.(*Repository).loadBlob
	/tmp/restic-build-559492747/src/restic/repository/repository.go:106
restic/repository.(*Repository).LoadBlob
	/tmp/restic-build-559492747/src/restic/repository/repository.go:538
restic.Node.createFileAt
	/tmp/restic-build-559492747/src/restic/node.go:214
restic.(*Node).CreateAt
	/tmp/restic-build-559492747/src/restic/node.go:109
restic.(*Restorer).restoreNodeTo
	/tmp/restic-build-559492747/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
	/tmp/restic-build-559492747/src/restic/restorer.go:53
restic.(*Restorer).RestoreTo
	/tmp/restic-build-559492747/src/restic/restorer.go:122
main.runRestore
	/tmp/restic-build-559492747/src/cmds/restic/cmd_restore.go:135
main.glob..func13
	/tmp/restic-build-559492747/src/cmds/restic/cmd_restore.go:23
github.com/spf13/cobra.(*Command).execute
	/tmp/restic-build-559492747/src/github.com/spf13/cobra/command.go:599
github.com/spf13/cobra.(*Command).ExecuteC
	/tmp/restic-build-559492747/src/github.com/spf13/cobra/command.go:689
github.com/spf13/cobra.(*Command).Execute
	/tmp/restic-build-559492747/src/github.com/spf13/cobra/command.go:648
main.main
	/tmp/restic-build-559492747/src/cmds/restic/main.go:37
runtime.main
	/usr/lib/go/src/runtime/proc.go:185
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:2197
```

What does the GOAWAY actually mean? Does it kill my connection and restic doesn't try to reconnect to the server how can i prevent that?

## Steps to reproduce the behavior
Nginx HTTPS reverse proxy in front from minio.
Restore you're backup in a long session.

**Comment by fd0** [comment]
Thanks for reporting this interesting case. Could you please apply the patch [here](https://gist.github.com/fd0/2c3b6afe814d664706e2bd207ed14cd5) and then attempt a restore again? Please enable logging on the nginx server and post the logs here, together with the last entries of the created `s3-backend.log` (created by the patch).

**Comment by fd0** [comment]
As far as I understand it GOAWAY means that the nginx server respectfully informs the client that it closes the connection. It may be that there is some idle timeout and restic made too many connections (which aren't in use any more), but the s3 client library does not handle this case so well. With the backend debug log we can contact the library authors and see what they think.

Next step after that is trying with the most recent version of the s3 client library, but let's try the first step first.

**Comment by JohnnyLeone** [comment]
Thanks for assistance!
I've patched the restic sources accordingly and attached here the relevant part of the last few packages. If you need more content of the logs i can post them.

nginx access log: 

```
HOST CLIENT - - [05/Mar/2017:12:25:52 +0000] "HEAD /public/restic/data/87d0cfa89970c081d84087459e44ed87bc8fce0ba04c1158a8668536505e0553 HTTP/2.0" 200 218 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:53 +0000] "GET /public/restic/data/87d0cfa89970c081d84087459e44ed87bc8fce0ba04c1158a8668536505e0553 HTTP/2.0" 206 2951224 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:54 +0000] "HEAD /public/restic/data/87d0cfa89970c081d84087459e44ed87bc8fce0ba04c1158a8668536505e0553 HTTP/2.0" 200 217 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:56 +0000] "GET /public/restic/data/87d0cfa89970c081d84087459e44ed87bc8fce0ba04c1158a8668536505e0553 HTTP/2.0" 206 4726552 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:56 +0000] "HEAD /public/restic/data/1329d84cd1f41463caaae7b419e9877dbb2bfa585200c6c71654d5169b4a23e1 HTTP/2.0" 200 216 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:56 +0000] "GET /public/restic/data/1329d84cd1f41463caaae7b419e9877dbb2bfa585200c6c71654d5169b4a23e1 HTTP/2.0" 206 1508856 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:57 +0000] "HEAD /public/restic/data/1329d84cd1f41463caaae7b419e9877dbb2bfa585200c6c71654d5169b4a23e1 HTTP/2.0" 200 216 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:58 +0000] "GET /public/restic/data/1329d84cd1f41463caaae7b419e9877dbb2bfa585200c6c71654d5169b4a23e1 HTTP/2.0" 206 2088089 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:59 +0000] "HEAD /public/restic/data/1329d84cd1f41463caaae7b419e9877dbb2bfa585200c6c71654d5169b4a23e1 HTTP/2.0" 200 216 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:59 +0000] "GET /public/restic/data/1329d84cd1f41463caaae7b419e9877dbb2bfa585200c6c71654d5169b4a23e1 HTTP/2.0" 206 1346732 "-" "Minio (linux; amd64) minio-go/2.0.1"
HOST CLIENT - - [05/Mar/2017:12:25:59 +0000] "DELETE /public/restic/lock/adeef7ac3777a108d9be6cdd6b153f9269a321452cd3e0a098632c05d02b7f1a HTTP/2.0" 204 128 "-" "Minio (linux; amd64) minio-go/2.0.1"
```

I've uploaded the s3-backend.log here http://pastebin.com/raw/zpt8uNVT because it is pretty long for the same chunk of data.

**Comment by fd0** [comment]
ping @harshavardhana, could you please have a look? Anything we can do here?

**Comment by JohnnyLeone** [comment]
After some more testing with the latest s3 library and latest restic version doesn't helped but sometimes the restore end with a total of 2.2gb of the file. Some tuning the reverse proxy e.g increase "ssl_session_timeout" doesn't help.
Also i've tried to mount the volume and copy the file from the mount dir to my host, i can verify that this method works perfectly and the file transfers completely.

**Comment by harshavardhana** [comment]
> ping @harshavardhana, could you please have a look? Anything we can do here?

go 1.8 has revealed some bugs in http client usage for us and how one needs to handle http content body.  Including other transport layer issues. 

Would it be possible to try this with go1.7.5 instead @JohnnyLeone and let us know?

**Comment by JohnnyLeone** [comment]
Unfortunately same error, i've used this time the official release which is build with go1.7.5, also i compiled the latest version of restic with the latest s3 backend with go1.7.5.

**Comment by harshavardhana** [comment]
> Unfortunately same error, i've used this time the official release which is build with go1.7.5, also i compiled the latest version of restic with the latest s3 backend with go1.7.5.

I haven't been able to reproduce this problem at my end so i am not sure what might be problem here - i used similar types of datasets upto 10GB including using nginx with or without the proxy.  Even Minio configured with TLS all of them seem to be working fine. 

Is there anything else in the environment like your nginx configuration etc. let us know which might help. Thanks

**Comment by fd0** [comment]
You can also try to disable HTTP2: set `GODEBUG=http2client=0` and run the program with that environment variable set.

**Comment by JohnnyLeone** [comment]
I've tested some more. If i set the `GODEBUG=http2client=0` environment variable i'm able so sucessfully restore the download. Is it related to my nginx config because it sets `proxy_http_version 1.1;`? Are there any implications with this solution to disable HTTP2?

Here is my current nginx config for my minio installation. http://pastebin.com/raw/NBFkYhgs

**Comment by fd0** [comment]
It just work just fine without http2, no worries. :)

**Comment by harshavardhana** [comment]
> Here is my current nginx config for my minio installation. http://pastebin.com/raw/NBFkYhgs

We are not really sure but can you open a github issue on minio we will figure this out. Perhaps it is a bug on our server muxer end. Thanks for testing.

Thanks once again @fd0 :-)

**Comment by fd0** [comment]
This issue should be resolved for recent versions of Go (>= 1.8), so I'm going to close the issue for now. Please feel free to add further comments should this still be an issue. Thanks!

**Comment by perhov** [comment]
The symptoms seem to have reappeared in restic 0.12.0.

restic 0.11.0 works fine, and restic 0.12.0 with GODEBUG=http2client=0 also works fine.

restic 0.12.0 without GODEBUG=http2client=0 emits warnings `Load([...]) returned error: [...] http2: server sent GOAWAY and closed the connection`.

Version information:

```
$ restic-0.12.0 version
restic 0.12.0 compiled with go1.15.8 on linux/amd64
```

```
$ restic-0.11.0 version
restic 0.11.0 compiled with go1.15.3 on linux/amd64
```

Command output:

```
$ restic-0.12.0 check --read-data
using temporary cache in /tmp/restic-check-cache-271166605
repository bdc4f584 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-271166605
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
[0:00] 100.00%  36 / 36 snapshots
read all data
Load(<data/d58edce2b6>, 0, 0) returned error, retrying after 462.318748ms: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
Load(<data/f7a67916fe>, 0, 0) returned error, retrying after 440.328595ms: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
Load(<data/6044ca064c>, 0, 0) returned error, retrying after 351.593438ms: unexpected EOF
Load(<data/ec54c171a8>, 0, 0) returned error, retrying after 353.291331ms: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
Load(<data/71565e93a4>, 0, 0) returned error, retrying after 596.012294ms: unexpected EOF
Load(<data/34ed725971>, 0, 0) returned error, retrying after 430.90274ms: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
Load(<data/714be3c2b4>, 0, 0) returned error, retrying after 738.458435ms: unexpected EOF
Load(<data/a6d374a18d>, 0, 0) returned error, retrying after 620.92448ms: http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
[10:15] 100.00%  14412 / 14412 packs
no errors were found
```

```
$ restic-0.11.0 check --read-data
using temporary cache in /tmp/restic-check-cache-853655209
repository bdc4f584 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-853655209
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
read all data
[11:02] 100.00%  14412 / 14412 packs
no errors were found
```

```
$ GODEBUG=http2client=0 restic-0.12.0 check --read-data
using temporary cache in /tmp/restic-check-cache-417061802
repository bdc4f584 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-417061802
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
[0:00] 100.00%  36 / 36 snapshots
read all data
[11:17] 100.00%  14412 / 14412 packs
no errors were found
```

The backend in this case is a minio server behind an nginx reverse HTTPS proxy, and the repository is around 70 GB.

**Comment by jreiners** [comment]
I'm also seeing very similar results on the newest version with about 800GB being backed up, I see it during writes mainly, I'm running nginx proxy manager with http2 enabled, I might try to disable upstream and see if it goes away.

I haven't tried the GODEBUG fix yet, but I'm sure it'll work.
