### ISSUE TITLE
Darwin support

### ISSUE THREAD

**Issue by rubenv** [restic/restic#85]
Currently restic relies on the Linux stat structure, which means that OSX (Darwin) isn't supported (nor is Windows):

```
# github.com/restic/restic
./tree.go:318: stat.Ctim undefined (type *syscall.Stat_t has no field or method Ctim)
./tree.go:318: not enough arguments in call to time.Unix
./tree.go:319: stat.Atim undefined (type *syscall.Stat_t has no field or method Atim)
./tree.go:319: not enough arguments in call to time.Unix
./tree.go:338: cannot use stat.Nlink (type uint16) as type uint64 in assignment
./tree.go:344: cannot use stat.Rdev (type int32) as type uint64 in assignment
./tree.go:346: cannot use stat.Rdev (type int32) as type uint64 in assignment
./tree.go:458: undefined: O_PATH
```

I'll happily help with porting (we'll need to move some things into platform specific pieces), but it's probably best to talk about the further implications first.

Some things that come to mind:
* Are there any caveats I should be aware of in the backup format with regards to cross-platform support?
* Have you considered what should be the desired behavior when doing cross-platform restores? (e.g. backup a Linux server, restore some of it on a Mac)

Biggest use case for me are Linux servers and Mac laptops, but if we can tackle Windows as well while we're at it, all the better.

It's probably a good idea to add cross-compile tests to the CI setup (tests would be even better, but that's hard, so let's ignore that for now).

Here's the full output of cross-compiles to windows/mac:

```
Number of parallel builds: 8

-->   windows/amd64: github.com/restic/restic/cmd/restic
-->    darwin/amd64: github.com/restic/restic/cmd/restic
-->     linux/amd64: github.com/restic/restic/cmd/restic

2 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/restic/restic
./tree.go:318: stat.Ctim undefined (type *syscall.Stat_t has no field or method Ctim)
./tree.go:318: not enough arguments in call to time.Unix
./tree.go:319: stat.Atim undefined (type *syscall.Stat_t has no field or method Atim)
./tree.go:319: not enough arguments in call to time.Unix
./tree.go:338: cannot use stat.Nlink (type uint16) as type uint64 in assignment
./tree.go:344: cannot use stat.Rdev (type int32) as type uint64 in assignment
./tree.go:346: cannot use stat.Rdev (type int32) as type uint64 in assignment
./tree.go:458: undefined: O_PATH

--> windows/amd64 error: exit status 2
Stderr: # github.com/restic/restic
./tree.go:313: undefined: syscall.Stat_t
./tree.go:318: not enough arguments in call to time.Unix
./tree.go:319: not enough arguments in call to time.Unix
./tree.go:458: undefined: O_PATH
./tree.go:458: undefined: syscall.O_NOFOLLOW
./tree.go:476: undefined: syscall.Mknod
./tree.go:481: undefined: syscall.Mknod
./tree.go:486: undefined: syscall.Mkfifo
```

As you can see, some things are easy (missing fields), others are hard (type differences).

**Comment by fw42** [comment]
One possible catch could be the default filesystem case insensitivity of HFS.

But generally :+1: to Darwin support.

**Comment by rubenv** [comment]
@fw42 oh yes, that too. Such a ridiculous thing.

**Comment by fd0** [comment]
Thanks for getting this started, I'll definitely need help with cross-platform support. The rough plan was to refactor/abstract Node.fill_extra() and Node.CreateNodeAt into platform-specific files using build tags. Also, the Linux syscall interface needs to be refactored, because the stdlib syscall package is insufficient and frozen, so we need to implement calling the relevant syscalls on our own.

Since JSON documents are quite flexible, it is easy to store different/additional information that isn't used for restore on the target platform. For example, storing the link counter for hard linked files could just be ignored when restoring under windows.

Are there any platform-specific file/directory attributes you are aware of? I think we can begin supporting the basic attributes on all platforms, and add more later (e.g. #25  describes saving and restoring extended attributes under Linux like ACL).

I think the most important question at the moment is: Are there any things we need to consider that coud in the future break compatibility, e.g. by requiring incompatible changes to the JSON documents?

**Comment by fd0** [comment]
I just pushed b7b9c7750df11f9174d0c18f460b0f3ec3aeec4f which splits out the platform specific code to different files. Could one of you test restic under darwin? What extra attributes should be saved on darwin?

**Comment by rubenv** [comment]
Gave it some testing. Long story short, it seems to work!

---

Here's the gory details:

My test set: 393547 files (71Gb)

Machine used:
```
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2,6 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
```

Backup was from `~/Projects` to `/tmp/restic` (so same disk). This is a 1TB SSD and as far as I can tell wasn't I/O constrained (I saw peaks of 150-200Mb read + write, but it can handle up to 600).

# First run
```
scan /Users/ruben/Projects/
[0:26] 78804 directories, 312779 files, 70.492 GiB
Done in 0:26
[12:11] 100.00%  98.693 MiB/s  70.492 GiB / 70.492 GiB  391583 / 391583 items  ETA 0:00
duration: 12:11, 98.75MiB/s
snapshot 941e71d2 saved
```

So almost 99MiB/s, which is pretty awesome (especially considering the fact that network backups should be the main use case). It means we can almost saturate Gigabit. Absolutely brilliant.

Much less stellar: the memory usage:
![restic](https://cloud.githubusercontent.com/assets/42904/6038203/76561d5a-ac5b-11e4-996b-71812b37c8ed.png)

Ouch, almost a gigabyte for 300k files. I have servers with millions of files, that will be a problem.

# Second run (no changes)
```
found parent snapshot 941e71d24f7ebe4e04cdf19369cc7c9e6f944aa6ab5239e1b85d9a1213b2a594
scan /Users/ruben/Projects/
[0:35] 78804 directories, 312779 files, 70.492 GiB
Done in 0:35
load old snapshot
[2:27] NaN%  0B/s  0B / 0B  80943 / 77123 items  ETA 0:00
duration: 2:27, 0.00MiB/s
snapshot 86e69d46 saved
```

Same thing here with the memory usage:
![screen shot 2015-02-04 at 10 43 11](https://cloud.githubusercontent.com/assets/42904/6038243/abd76fe2-ac5b-11e4-830c-d717404569af.png)

There's another more interesting fact though:
```
[2:27] NaN%  0B/s  0B / 0B  80943 / 77123 items  ETA 0:00
```
Very strange to see `80943 / 77123` items.

# The backup folder
The final backup folder has some interesting numbers as well:
```
osaka:restic $ du -hs
 61G	.
osaka:restic $ find . | wc -l
  314453
```
Deduplication at work!

---

I like what I'm seeing here! Now, I have some ideas to get that memory usage back down. It all depends on how much you care about that progress bar. I think you should get rid of it and perform everything with bounded channels, that'll get the memory usage to pretty much zero.

The basic idea:
* Current state and previous state are sorted streams (channels) of file records
* You can compare those similarly to how mergesort works

Anyway, that's a different discussion. As for this issue: I think we're there (didn't expect it to happen so fast!). Other points can be tackled elsewhere.

Thanks a lot for looking into this (I was going to do it, but you beat me to it).

![706514](https://cloud.githubusercontent.com/assets/42904/6038379/c212a5a0-ac5c-11e4-81ea-39c42cbd0484.jpg)

**Comment by fd0** [comment]
Wow, not bad. Thanks for the detailed report!

Could you try restoring something? Does that also work?

**Comment by rubenv** [comment]
Did a large(ish) backup + restore (99087 files, 2.9G).

Then took sha256 sums of everything and verified them in the restore.

```bash
find . -type f -exec shasum -a 256 {} \; > hashes.txt
shasum -a 256 -c hashes.txt | grep -v ": OK"
```

Which had a perfect result.

I then did a very unscientific snapshot test, comparing the output of `ls -al`:

```diff
--- a.txt       2015-02-05 12:12:18.000000000 +0100
+++ b.txt       2015-02-05 12:12:18.000000000 +0100
@@ -1,6 +1,6 @@
 total 400
-drwxr-xr-x+ 54 ruben  staff  1836 Jan 26 15:39 ./
-drwxr-xr-x+ 15 ruben  staff   510 Jan 26 15:39 ../
--rw-r--r--+  1 ruben  staff   237 Dec  8 10:47 bind-once.html
--rw-r--r--+  1 ruben  staff   206 Mar 21  2014 catalog.js
-drwxr-xr-x+  4 ruben  staff   136 Jun 10  2014 complete/
+drwxr-xr-x  54 ruben  staff  1836 Feb  5 12:02 ./
+drwxr-xr-x  15 ruben  staff   510 Feb  5 12:02 ../
+-rw-r--r--   1 ruben  staff   237 Dec  8 10:47 bind-once.html
+-rw-r--r--   1 ruben  staff   206 Mar 21  2014 catalog.js
+drwxr-xr-x   4 ruben  staff   136 Feb  5 12:02 complete/
```

It's a bit hard to see, but the results are very good: basic POSIX metadata is retained correctly for files. It's not for directories.

There's also the `+` bit. According to `man ls`:
```
Otherwise, if the file or directory has extended security information (such as an access control list), the permissions field printed by the -l option is followed by a '+' character.
```

So we're missing some metadata somewhere (don't care too much).

All in all: working Darwin support (alpha)!

As for the memory thing, we can discuss this in a different issue. Let me just add the final note that it's probably a good idea, when you're designing a new system, to take peak memory usage into account. Ideally this would be a fix (O(1)) amount, regardless of the number of files / size of the backup. This'll help things both on the big end (huge servers) and the small end (mobile) of things.

**Comment by fd0** [comment]
Sounds good. So I'd like to add tests for backup and restore of meta data for all platforms. When this is done I think we can close this issue. Do you agree?

**Comment by rubenv** [comment]
Sounds good.

Oh yes, I forgot to mention, I tried running the test suite but it doesn't work: `mktemp` on OSX is not the GNU Coreutils one (massive frustration).

I'll have some patches for the tests soon.

**Comment by fd0** [comment]
I already thought about replacing the test suite's shell scripts a Go program, what do you think?

**Comment by rubenv** [comment]
All for it, shell glue = pain. Will help on Windows as well.

**Comment by fd0** [comment]
I changed my mind. This issue is closed as basic Darwin support is done. The followup issues are #87 and #88.

**Comment by rubenv** [comment]
:+1: Thanks already, didn't expect Darwin support so quickly.
