### ISSUE TITLE
Backup a file owned by root

### ISSUE THREAD

**Issue by mnesrine** [restic/restic#862]
## Output of `restic version`
restic 0.3.3 (v0.3.3-9-g38ba5fb-dirty)
compiled with go1.6.2 on linux/amd64

##
When I backup a file that owned by root, this backup fail with error permission.
Although a backup failed, restic replay by "snapshot ID saved" and we found a file in the snapshots list.

```
$./restic backup hello.html
         scan [hello.html]
         scanned 0 directories, 1 files in 0:00
         error for /home/foo/hello.html: Open: open /home/foo/hello.html: permission denied
         [0:00] 0.00%  0B/s  0B / 1.642 KiB  0 / 1 items  1 errors  ETA 0:00
         duration: 0:00, 0.01MiB/s
         snapshot d9e117ae saved
```

## Steps to reproduce the behavior

1- change owner of the file_to_backup.
2- restic backup file_to_backup

**Comment by fd0** [comment]
Thanks for taking the time to report this issue. I agree, restic should return an error instead of creating an empty snapshots.
