### ISSUE TITLE
Make cli filtering more consistent

### ISSUE THREAD

**Issue by middelink** [restic/restic#863]
Currently few commands accept all 3 filters (`--host`, `--path` and `--tag`) and a lot of other commands accept just one or two. Can we try and make things more consistent? For a casual user consistency rules. They don't want to look at the help each time they need to run a command.

My first attempt at solving this. Not a PR yet (expecting loads of comments ^^ and will have merge conflicts with the 2 other PRs I have inflight):
  https://github.com/middelink/restic/compare/master...middelink:widespread-tags

**Comment by fd0** [comment]
Good idea, consistency is important!

**Comment by fd0** [comment]
Will you add a PR for this so we can discuss the code?
