### ISSUE TITLE
Add JSON ouput to find command

### ISSUE THREAD

**Issue by yhafri** [restic/restic#869]
## Output of `restic version`

`Any`

## Expected behavior

This is exactly the same idea behind the new option *--json* for [snapshots](https://github.com/restic/restic/pull/751) command.
We would like to get the output as *JSON* instead of raw/not-formatted text:

```
$ restic find --json -s 82a6e9de 554*
[ 
 {"snapshot": "82a6e9dec437fd736f6a59cdd1eb11f68ab2fde01a7976050d80a6a5109aad27"}:
   [ 
     {"hits": 1},
     {"matches": [
        {"match": [ 
          {"path":"test\554a2d0ab44d5.pdf"},
          {"permissions": "-rw-rw-rw-"},
          {"size": 3171662},
          {"date": "2015-05-06 11:02:36 -0400 EDT"} 
        ]}
      ]}
    ]
]
```

or even simpler if the above isn't possible (or hard to achieve):

```
$ restic find --json -s 82a6e9de 554*
[ 
 {"snapshot": "82a6e9dec437fd736f6a59cdd1eb11f68ab2fde01a7976050d80a6a5109aad27"}:
   [ 
     {"hits": 1},
     {"matches": [ 
          {"match": "-rw-rw-rw-     0     0 3171662 2015-05-06 11:02:36 -0400 EDT test\554a2d0ab44d5.pdf"} 
       ]}
    ]
]
```

## Actual behavior

```
$ restic find -s 82a6e9de 554*
found 1 matching entries in snapshot 82a6e9dec437fd736f6a59cdd1eb11f68ab2fde01a7976050d80a6a5109aad27
  -rw-rw-rw-     0     0 3171662 2015-05-06 11:02:36 -0400 EDT test\554a2d0ab44d5.pdf
```

I'm willing to _sponsor_ this feature. Please reach me out if interested.

**Comment by middelink** [comment]
Would this work? It has a slightly different output format though.
```console
$ restic -r rest:http://qnap.**.********.**:8000 find -s f5a13c51 bin --json
[{"matches":[{"path":"/usr/bin","permissions":"dr-xr-xr-x","date":"2017-03-04T15:48:13.172+01:00"},{"path":"/usr/lib/debug/usr/bin","permissions":"drwxr-xr-x","date":"2017-03-04T05:16:08.407+01:00"},{"path":"/usr/local/bin","permissions":"drwxr-xr-x","date":"2016-11-05T16:38:36+01:00"},{"path":"/usr/share/locale/bin","permissions":"drwxr-xr-x","date":"2017-03-04T05:16:20.794+01:00"}],"hits":4,"snapshot":"f5a13c51c10d7bb1bea25c3bacfd69898491ddfdbd7ebe309bea6e46bc3572f6"}]
```

**Comment by yhafri** [comment]
Simply awesome +1

**Comment by fd0** [comment]
Do we really need the count? at the time the JSON is parsed, it's already apparent how many hits are there (`=len(matches)`)...

**Comment by yhafri** [comment]
It depends @fd0. My intent is to use the number of matches for a reporting purpose. Thus, it's a real plus.
Think of "find" as a mini search engine. You see the number of hits first, then the data.

**Comment by yhafri** [comment]
Hi @fd0 

It seems that the `find --json` is not working anymore (both 32/64-bit) :-(

Today, we tried to build restic from `trunk` (_go v1.7.3_) and the feature seems to be broken (panic crash).

Same result with the prebuilt binaries [v0.5.0](https://github.com/restic/restic/releases/tag/v0.5.0). No crash, but the result is wrong.

Try for example:
```
$ restic find find --json "*"
```

The version we're currently using and which works perfectly on Windows, Linux and MacOS is: `a5728398747f2a11cdf24c1d98636a5b46c`.

Thank you!

**Comment by ibib** [comment]
I thin a own Ticket would be better.

Error: https://gist.github.com/ibib/b802eae2110cc4c5e44197c337b07e75
Error appears before password prompt.

`git bisect start

...

git bisect bad 946b4f4b86319b802d2c4f68df88400253a6fa59
first bad commit: [946b4f4b86319b802d2c4f68df88400253a6fa59] Add extended options via -o/--option
`

**Comment by fd0** [comment]
Oh, I'm sorry to hear that. It's always better to create a new issue so we can track it.

@ibib thanks for bisecting

**Comment by fd0** [comment]
#905 will fix this.
