### ISSUE TITLE
Implement external test suite in Go

### ISSUE THREAD

**Issue by fd0** [restic/restic#87]
At the moment, the external test suite is implemented in shell an only runs under Linux. This issue tracks the progress of implementing a test suite in Go that runs on Linux, darwin and Windows.

**Comment by fw42** [comment]
What's the problem with implementing it as shell scripts (or anything else other than Go)? Is this mostly about cross-platform compatibility?

**Comment by andrewchambers** [comment]
Go tests give code coverage, profiling, race detection and is cross platform.

**Comment by fd0** [comment]
Writing tests in shell is really tedious and error-prone. Even writing the few tests that are there was a pain. The other arguments @andrewchambers pointed out.

I can also live with having the test suite in another language, e.g. Ruby, but not shell.

**Comment by fd0** [comment]
This was fixed with #179.
