### ISSUE TITLE
restore does not truncate files it restores [CRITICAL]

### ISSUE THREAD

**Issue by middelink** [restic/restic#875]
## Output of `restic version`
restic compiled manually (HEAD actually)
compiled with go1.8 on linux/amd64

## Expected behavior
When restoring a file, the restore cmd will place a file of exact length, permissions, ownership and contents back in the location specified.

## Actual behavior
It only open (or creates) the file but does NOT truncate an existing file.

## Steps to reproduce the behavior
```console
$ mkdir /tmp/etc
$ cp /bin/unzip /tmp/etc/fstab
$ ls -l /tmp/etc/fstab
-rw-------. 1 middelin middelin 185488 Mar 10 22:34 /tmp/etc/fstab
$ restic -r rest:http://qnap.**.********.**:8000 restore -t /tmp f5a13c51 -i /etc/fstab
(ignoring chown failure; #244, #625 #855; although it should have done the other chxxx's)
$ ls -l /tmp/etc/fstab
-rw-------. 1 middelin middelin 185488 Mar 10 22:34 /tmp/etc/fstab
```

(bug marked critical as this will completely undermine confidence in restoring files.)

**Comment by middelink** [comment]
And since I discovered it, dibs!

**Comment by fd0** [comment]
Thanks a lot!
