### ISSUE TITLE
Rework tests (especially integration) to be "panic safe"

### ISSUE THREAD

**Issue by fd0** [restic/restic#879]
This is a followup issue for #873, I'm copying @middelink's text here:

> btw, I like this way of setting up:

```
func testBla() {
env, teardown := withEnvironment(t...)
defer teardown(t, env)

... testcode ...
}

```
> defer makes sure the teardown code gets run, even in light of a panic attack.

Rework all tests to use this pattern so that cleanup is run even when the test panics.

**Comment by yhafri** [comment]
@fd0: does this also solve #873 ?

**Comment by middelink** [comment]
Partially. #873 asked for a flag to set tmpdir, and that did not happen. But #879 would stop tests from  leaving behind leftovers. Note however that crashes during non-tests, like making a backup and OOMing, will still leave files behind.

**Comment by yhafri** [comment]
@middelink thanks for the clarification

**Comment by fd0** [comment]
Thanks for responding @middelink :)

From my point of view, #873 is resolved: There is a way to use a custom directory, and it is documented in the manual. This issue is just about not leaving temp files behind when tests panic.
