### ISSUE TITLE
Darwin: Save/Restore extended metadata

### ISSUE THREAD

**Issue by fd0** [restic/restic#88]
At the moment, restic only saves the most basic meta data under darwin. This issue tracks the progress on saving and restoring extended meta data.

**Comment by rawtaz** [comment]
What's missing in this issue - is there more metadata that's not being backed up? Or is it just tests that are missing?

I took a peek at https://github.com/restic/restic/blob/master/internal/restic/node_xattr.go and it seems that this file and its code will be active on Darwin, making me think that restic *is* backing up extended attributes on macOS, hence not sure what's missing.

**Comment by fd0** [comment]
Hm. Interesting question. I'm not sure any more what was meant with this issue, maybe there are file systems specific attributes on Darwin that aren't saved with the extended attributes...

I'm closing this issue for now. If you are a user reading this issue and want to save metadata on Darwin that isn't saved yet, please leave a comment. Thanks!
