### ISSUE TITLE
Compilation on Android and termux not possible

### ISSUE THREAD

**Issue by Mebus** [restic/restic#886]
Hallo! 

I tried to compile restic on Android using termux, but I get this error:

```
localhost% go run build.go
# os/user
../../../lib/go/src/os/user/lookup.go:9: undefined: current
../../../lib/go/src/os/user/lookup.go:15: undefined: lookupUser
../../../lib/go/src/os/user/lookup.go:21: undefined: lookupUserId
../../../lib/go/src/os/user/lookup.go:27: undefined: lookupGroup
../../../lib/go/src/os/user/lookup.go:33: undefined: lookupGroupId
../../../lib/go/src/os/user/lookup.go:38: undefined: listGroups
build failed: exit status 2
exit status 1
localhost% go version
go version go1.8 android/arm
localhost% 

```

How can this be fixed?

Mebus

**Comment by fd0** [comment]
Do not use the version of Go supplied by termux, it looks like they patched the Go source code and broke `os/user`: https://github.com/termux/termux-packages/blob/master/packages/golang/src-os-user.patch

**Comment by fd0** [comment]
You can also try removing `CGO_ENABLED=0` [here](https://github.com/restic/restic/blob/master/build.go#L208).

**Comment by Mebus** [comment]
I added a bug in termux:

https://github.com/termux/termux-packages/issues/849

Mebus

**Comment by fd0** [comment]
Uh, I've also submitted a bug: https://github.com/termux/termux-packages/issues/848

**Comment by Mebus** [comment]
It compiled without CGO_ENABLED=0 :-)

Mebus

**Comment by fd0** [comment]
So I'm going to close this, it's not an issue with restic. Thanks for reporting it!
