### ISSUE TITLE
Document architectural design decisions in short texts

### ISSUE THREAD

**Issue by fd0** [restic/restic#890]
@middelink had the idea to document design decisions in short texts, so that people can easily digest them one after another and we can direct people to the texts. This article explains something similar:
http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions

I have the following topics/decisions that I think need elaborating:
 * [ ] Why there is a `build.go` for compiling restic
 
Please add other suggestions to this issue

**Comment by j6s** [comment]
Bump - I am currently wondering about the role of `build.go`.

**Comment by fd0** [comment]
It's there to make it very easy for end-users to compile restic: check out the repo (or extract the release tar) and run `go run build.go`, it'll take care of everything needed. It order to compile restic with Go before 1.11, you'll need to do the following:
 * put the code into a directory tree `src/github.com/restic/restic`
 * set the environment variable `GOPATH` to the directory containing the tree above
 * then run `go build ./cmd/restic` within `$GOPATH/src/github.com/restic/restic`

The thing with `GOPATH` should be treated a technical detail end-users should not need to care about when building restic, in contrast: building restic should be very easy.

Internally, `build.go` (which has its own repository at https://github.com/fd0/build-go) will either use Go modules for Go >= 1.11 or construct the path mentioned above in a temporary directory on the fly.

**Comment by fd0** [comment]
Since we apparently haven't gotten around to actually documenting anything, I'll close this issue for now. Please feel free to add further comments. Thanks!
