### ISSUE TITLE
Cannot specify port for sftp backend

### ISSUE THREAD

**Issue by andrewchambers** [restic/restic#895]
## Output of `restic version`
restic 0.5.0 (v0.5.0-24-gc85055b)
compiled with go1.8 on linux/amd64

## Expected behavior
either
restic -r sftp:ac@localhost:2022/Ahhhhggg init
or
restic -r sftp:ac@localhost:2022:/Ahhhhggg init

should dial port 2022

## Actual behavior

Dials port 22 with a directory containing the port.

2017/03/25 13:31:20 restic/global.go:367	main.create	1	create sftp repository at sftp.Config{User:"ac", Host:"localhost", Dir:"2022/Ahhhhggg"}

2017/03/25 13:31:29 restic/global.go:367	main.create	1	create sftp repository at sftp.Config{User:"ac", Host:"localhost", Dir:"2022:/Ahhhhggg"}

## Steps to reproduce the behavior

See above

**Comment by andrewchambers** [comment]
Good point. It is inconsistent with the rest back end however which Is
where I took the syntax.

**Comment by fd0** [comment]
Hm, I can see the inconsistency. The REST backend config format is `rest:` plus a URL, whereas the sftp config format is `sftp:user@host:/path`, so adding another `:` for the port is not so easy because it would create an ambiguity: `sftp:x@s:2222:foobar` may be parsed as:
 * user `x` on the host `s`  on port 2222, repo is in the path `foobar` relative to the user's starting directory
 * user `x` on the host `s`, repo is in the path `2222:foobar` relative to the user's starting directory.

Hm. How unsatisfying ;)

**Comment by andrewchambers** [comment]
That being said, I'm totally happy with your advice, thank you.

On 25/03/2017 9:01 PM, "Alexander Neumann" <notifications@github.com> wrote:

Hm, I can see the inconsistency. The REST backend config format is rest:
plus a URL, whereas the sftp config format is sftp:user@host:/path, so
adding another : for the port is not so easy because it would create an
ambiguity: sftp:x@s:2222:foobar may be parsed as:

   - user x on the host s on port 2222, repo is in the path foobar relative
   to the user's starting directory
   - user x on the host s, repo is in the path 2222:foobar relative to the
   user's starting directory.

Hm. How unsatisfying ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/restic/restic/issues/895#issuecomment-289196717>, or mute
the thread

**Comment by fd0** [comment]
PR #896 will address this issue in the manual.

**Comment by rfjakob** [comment]
Hmm, I'm confused, setting a port does seem to be supported using the

    sftp://host:10022//dir/subdir

URL format. It even has a testcase: [sftp/config_test.go#L23](https://github.com/restic/restic/blob/master/src/restic/backend/sftp/config_test.go#L23). Is this deprecated functionality?

**Comment by fd0** [comment]
You're right, it is supported via the old url-style syntax, which is deprecated and will be removed eventually.

**Comment by darioseidl** [comment]
The [docs](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html) for the stable version (v0.11.0) still mentions the URL syntax. It didn't seem to work for me (hostname with different port).

Has it been removed (and should it be removed from the docs)?

**Comment by MichaelEischer** [comment]
The URL syntax should still work:  `sftp://blabla@[2001:aaaa:aaaa::1]:1234/testrepo` did work for me. Did you quote the URL on the command line?

**Comment by darioseidl** [comment]
OK, thanks. Maybe I did forget to quote (the URL was in a variable in a bash script) or made some other mistake, but I have it working now with the ssh/config.

**Comment by silicontrip** [comment]
Please don't remove the `sftp://` notation too soon, I have a use case where I'm not able to change `ssh_config`
I'm not sure if something like the `rsync -e` might be suitable.
