### ISSUE TITLE
restic init doesn't work anymore with REST backend

### ISSUE THREAD

**Issue by zcalusic** [restic/restic#899]
## Output of `restic version`

restic 0.5.0 (v0.5.0-36-g6935f82)
compiled with go1.8 on linux/amd64

## Expected behavior

It seems that transition to "POST /repo/?create=true" way of creating repos isn't complete. restic init should be able to create repo from scratch, not exit with an error.

## Actual behavior

Restic client stops with an error:

create backend at rest:https://rest-server:port/repo/ failed: server response unexpected: 404 Not Found (404)

Turning debugging on, on the rest-server, reveals this sequence:

GET /repo/keys/
ListBlobs()
open /ext/restic/repo/keys: no such file or directory
HEAD /repo/config
CheckConfig()
stat /ext/restic/repo/config: no such file or directory
POST /repo/?create=true

Either restic shouldn't try to access repository parts that are yet to be created (keys/config), or if it's some kind of failsafe, it shouldn't choke on 404 Not Found, as 404 is perfectly normal and expected. We just requested to initialize that repo, of course it doesn't exist yet!

## Steps to reproduce the behavior

restic init, with repo pointed to REST backend.

**Comment by fd0** [comment]
Huh, that's indeed odd, thanks for reporting it! I need to investigate why this wasn't catched in the CI tests...

**Comment by fd0** [comment]
I'm unable to reproduce this, works just fine with the same revision of restic and the latest rest server, my debug output for `restic init` is:
```
rest-server 0.9.0 (84cabc7) compiled with go1.8 on linux/amd64
Data directory: /tmp/restic
Authentication disabled
Starting server on :8000
HEAD /config
CheckConfig()
stat /tmp/restic/config: no such file or directory
POST /?create=true
CreateRepo()
Creating repository directories in /tmp/restic
HEAD /config
CheckConfig()
stat /tmp/restic/config: no such file or directory
POST /keys/f729e1422d290c83b662db783a91c9e0cb68c753e4cfa0968125f1ce21d1d0ef
SaveBlob()
Creating repository directories in /tmp/restic
POST /config
SaveConfig()
```

**Comment by fd0** [comment]
Oh, interesting: Using the URL `http://localhost:9000/repo` works, but `http://localhost:9000/repo/` (note the trailing slash) doesn't. Is this a bug in the server or the backend?

**Comment by fd0** [comment]
And the 404 is returned by the `POST` to create the repo. btw: I think we need to improve logging for the REST server...

**Comment by zcalusic** [comment]
Funny thing is that I tried without ending slash, but got the same result. Unless I did something wrong.

The other mystery is that in my debug log there's GET /repo/keys/ where in yours it doesn't happen?

Yeah, i have plans for better logging in REST server, just didn't have time to architecture that and work on it.

**Comment by fd0** [comment]
I have no idea. Can you maybe have a look if it's in the server or the backend?

**Comment by zcalusic** [comment]
Ah, you're right, without the trailing slash, it works. I must've messed up my test, because I was in a hurry to have that backup done.

I'll check what is going on here in the rest-server, it might be a bug in there, after all.

**Comment by fd0** [comment]
Thanks!

**Comment by zcalusic** [comment]
OK, this is definitely a rest-server bug. Three mux rules are needed to cover all possible valid cases. restic client running HEAD /test/config getting 404 and reporting 404 error back when creating repo mislead me to think that some earlier restic call to rest-server was the culprit.

NB: I tried to run restic integration tests with go run run_integration_tests.go, but all I get back is unknown CI environment, exit status 1. Also I can't seem to find anything about that in the documentation. Please don't tell docker is required to run tests. :(

**Comment by fd0** [comment]
This is a safety feature: The `run_integration_tests.go` program is not meant to be run locally, it expects the directory layout Travis provides and will also silently install/overwrite things, e.g. the minio server binary. You can use it by setting the environment variable `TRAVIS_BUILD_DIR` to some non-empty string, but I recommend not doing that.

In order to run the REST backend tests, expose the URL for the server to be used in the variable `RESTIC_TEST_REST_SERVER`, e.g. like this:
```
$ RESTIC_TEST_REST_SERVER=http://localhost:8000 go test -v restic/backend/rest
```

**Comment by fd0** [comment]
And we could also move calling the restic server into the backend tests, so that the tests are run automatically if the `rest-server` binary is available, similar to the sftp backend tests. What do you think?
