### ISSUE TITLE
Statistics in prune cmd do not add up.

### ISSUE THREAD

**Issue by middelink** [restic/restic#900]
## Output of `restic version`
0.5

## Expected behavior
for the statistics to add up :)

## Actual behavior
```console
# restic -r rest:http://qnap.********.**:8000 prune
counting files in repo
building new index for repo
[13:17] 100.00%  15586 / 15586 packs
repository contains 15586 packs (1697307 blobs) with 71.899 GiB bytes
processed 1697307 blobs: 17196 duplicate blobs, 165.663 MiB duplicate
load all snapshots
find data that is still in use for 209 snapshots
[1:06:58] 100.00%  209 / 209 snapshots
found 1548104 of 1697307 data blobs still in use, removing 149203 blobs
will delete 318 packs and rewrite 113 packs, this frees 2.339 GiB
[0:35] 100.00%  113 / 113 packs rewritten
[0:03] 100.00%  318 / 318 packs deleted
counting files in repo
[3:02] 100.00%  15180 / 15180 packs
finding old index files
saved new index as 8117b867
remove 181 old index files
done
```
please note we start out with 15586 packs, it deletes 318 packs and ends up with 15180 packs. (unexplained difference of 88 packs)
Investigation of the `data` directory in the repo shows there are indeed only 15180 packs.

## Steps to reproduce the behavior
run prune on a repo you haven't pruned in a while (3-4 wks)

**Comment by fd0** [comment]
Thanks for reporting, those stats need to be looked at again.

**Comment by fd0** [comment]
I think this is resolved by now, please add a comment should that not be the case. I'm closing the issue for now, thanks!
