### ISSUE TITLE
Restore all available versions of a file

### ISSUE THREAD

**Issue by sgeisbacher** [restic/restic#906]
i would like to restore all available versions (one per snapshot) of a file to easier find the version i'm looking for. i'm thinking of writing a bachelor-thesis where you snapshot your word-document every hour. and then you recognise you accidentally deleted a part sometime in the past. so i want to restore the word-doc from each snapshot to one target-directory with <filename>-<snapshotid/snapshottimestamp>.<ext>

i can implement that and make a pull-request, if you like

**Comment by ibib** [comment]
i really like the idea
some additional features for this (which can be added later):
    -restore no duplicates (different modification time).
    -target directory naming after `snapshotid/snapshottimestamp/mtime/atime/ctime` for easier search.
    -this might be a bit overkill but maybe something like `git bisect` to find the relevant version of a file.

**Comment by fd0** [comment]
You can already do that by mounting the repo to a directory.

**Comment by sgeisbacher** [comment]
yeah, but if you have 5 versions/snapshots of a file you have to mount 5 different snapshots or have i missed something? i think in such a case it would be easier for users to be able to export all to one target-directory

**Comment by fd0** [comment]
Uhm, did you try this at all? You mount a repository, then all snapshots in that repository are available as subdirs below the mount point. You can then easily inspect or copy all revisions of the file you're searching for. That's even easier that restoring and then inspecting the files. In addition, the fuse mount will only load data on demand, so there's no overhead.

At the moment I think this use case is covered very well by the fuse mount, so I'm going to close this issue for now.

**Comment by sgeisbacher** [comment]
oh sorry, my mistake. i had in mind that you are only able to mount a single snapshot. so closing is totally ok!

**Comment by popovn** [comment]
> You mount a repository

Not on Windows
how to easily view all version of file (get all snapshots when file was changed)?
