### ISSUE TITLE
Empty Mountpoints Are Not Backed Up

### ISSUE THREAD

**Issue by zx2c4** [restic/restic#909]
When backing up a system with, say, `restic backup -x /`, I expect for `/dev/*` or `/proc/*` to not be backed up, since it's a different filesystem. However, I _do_ expect the base directory, `/dev`, to be backed up as an empty directory, since it resides on the parent filesystem. I realize you can't descend into covered mounts, in case an unmounted `/dev` isn't empty, somehow, but at the very least you can back it up as empty?

**Comment by fd0** [comment]
Huh, you're right, these directories are not saved. This behavior is caused by the fact that calling `lstat()` on a mount point returns the stat for the root node of the fs mounted there, so it is excluded. This needs to be handled as a special case, unfortunately. Thanks for the report!

**Comment by fd0** [comment]
FYI, there's a PR which will fix this issue: #3119
