### ISSUE TITLE
Empty lines in exclude-file result in empty snapshot

### ISSUE THREAD

**Issue by Gjum** [restic/restic#915]
## Output of `restic version`

    restic 0.5.0 (356099d)
    compiled with go1.8.1 on linux/amd64

## Expected behavior

`my-exclude`:
```
first-line

third-line
```

command:

    restic -r /repo backup /data --exclude-file my-exclude

I expect this to back up all of `/data` except `first-line` and `third-line`.

This is of course a simplified example, my real exclude files are much bigger and their readability benefits from empty lines.

## Actual behavior

Because the file contains a newline, no files in `/data` get scanned:
```
enter password for repository: 
scan [/data]
scanned 0 directories, 0 files in 0:00
[0:00]   0B/s  0B / 0B  0 / 0 items  0 errors  ETA 0:00 
duration: 0:00, 0.00MiB/s
Fatal: no files/dirs saved, refusing to create empty snapshot
```

A quick search revealed [this (possibly) relevant part of the code](https://github.com/restic/restic/blob/f5a55a81f751e8c821879c6769e375d3b961739d/src/cmds/restic/cmd_backup.go#L419), where only comment lines are discarded, but empty lines get added as exclude patterns.

Removing the newline or replacing it with a comment results in the expected behavior.

## Steps to reproduce the behavior

See `Expected behavior`.

**Comment by Gjum** [comment]
Also somewhat related, as far as I can tell multiple usages of `--exclue-file` are not supported for `backup`, instead the second usage overrides the first.

I couldn't find a Github issue for that but that probably is already tracked somewhere. Just thought I'd mention that because it's also somewhat unexpected behavior relating to exclude files, if you think it's reasonable I can open another issue for this specific problem.

A quick workaround would be to use `--exclude-file <(cat first.exc second.exc)`, but that still leaves the unexpected overriding behavior.

**Comment by fd0** [comment]
Hey, thanks a lot for the report and taking the time to debug this! I'll have a look.

**Comment by fd0** [comment]
Could you please check if the code in #916 (branch `fix-915`) solves the bug you reported.

**Comment by Gjum** [comment]
Everything works perfectly now, both using empty lines and specifying multiple exclude files. Thanks for the quick response, that means a lot.

Keeping this open until the PR is merged.

**Comment by fd0** [comment]
yep, I'll close it when I merge the PR
