### ISSUE TITLE
use newer xattr

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#921]
It would be great if restic could use a newer version of xattr (latest release: `v0.2.0`). According to `vendor/manifest` it uses revision `b867675798fa7708a444945602b452ca493f2272`.

It would help the Debian packaging of the latest restic.

**Comment by fd0** [comment]
No problem, are you interested in doing a PR?

**Comment by legrostdg** [comment]
Sorry, I don't have much time to check if this release changed the api and still is compatible with restic or not. I just have enough time to do the packaging for xattr and the newer restic...

I will probably be an easy check for the person who added xattr support to restic.

**Comment by fd0** [comment]
No problem at all :)
