### ISSUE TITLE
getting repository is already locked message when running prune

### ISSUE THREAD

**Issue by nbommu1** [restic/restic#926]
## Output of `restic version`

restic 0.5.0 (v0.5.0-24-gc85055b)
compiled with go1.8 on linux/amd64

## How did you start restic exactly? 
restic -r s3:s3.amazonaws.com/bucketname  -p <passwordfile> forget <snapshots-id>

## What backend/server/service did you use?

s3
## Expected behavior
actually we are taking backups of each server in a single s3 repo, schedule jobs are running fine, when we run weekly snapshots cleanup we are getting into this issue, if we run clean up snapshots job with different timing it works fine, do have an option to check for lock where I can control prune snapshots wait for lock to be vanish and run?

## Actual behavior
repository is already locked by PID 4152 on server1 by root (UID 0, GID 0)
lock was created at 2017-04-19 12:20:55 (1.504682657s ago)
storage ID ffb93e0a

snapshot clean up fails due to the lock.

## Steps to reproduce the behavior
run multiple snapshot prune on single repo.

## Do you have any idea what may have caused this?
running another snapshot cleanup job on different server on the same repo.

**Comment by fd0** [comment]
Which command do you run as the "cleanup job"? Do you run `prune` and/or `forget` on each server? Please note that this is not necessary, you can do that from one single server.

There are two operations, `forget` and `prune`. Both require an exclusive lock on the repo, so no other jobs may be run in parallel. This is important because both commands remove data from the repository, and all other instances of restic are not aware of that. So we make sure that no other instance of restic may be running.

**Comment by nbommu1** [comment]
Hi, thanks for your reply,

in my case I have many servers where backup are running daily to a single repo in s3, each server has two cron jobs, one is daily back up and another one is weekly snapshots clean with tag(hostname)

here is the command where I run weekly cleanup and getting into lock  since rest of the servers running clean up at the same time.
restic --no-lock -r s3:s3.amazonaws.com/bucket -p passwordfile forget --keep-last 7 --prune --tag hostname

if I run with option "forget --keep-last 7" on a single server, will it delete all the snapshosts and keep last 7 for each server?
can you please suggest on  this?

thanks
Niranja

**Comment by nbommu1** [comment]
looks like it does that waht I want.

restic -r s3:s3.amazonaws.com/bucket-p restic_pass forget --keep-last 7 --prune

keeping 7 snapshots for each server and deleting rest of them, 

thanks for you help, I'm all set.

**Comment by fd0** [comment]
When you run `restic forget --keep-last 7` on one server, it will keep the last 7 snasphots per server, which means you end up with `n * 7` snapshots in the repo (where `n` is the number of servers). For a detailed explanation see here: https://restic.github.io/blog/2016-08-22/removing-snapshots

You can easily experiment with it by using the `--dry-run` option to `forget`.

**Comment by fd0** [comment]
Then I'm going to close this issue.
