### ISSUE TITLE
option to check repo lock

### ISSUE THREAD

**Issue by nbommu1** [restic/restic#929]
## Output of `restic version`
restic 0.5.0 (v0.5.0-24-gc85055b)
compiled with go1.8 on linux/amd64

## How did you start restic exactly? (Include the complete command line)
I'm running into a an issue while running prune job with different retention policies at the same time, it works great with global retention policy(ref#926). if I want to run prune job with different retention policies lock is preventing run prune job,  It would be great if we have an option to check the lock before kick off prune job or sub command to check the repo lock along with other commands. 

can you please help us out this?

thanks
Niranjan

**Comment by fd0** [comment]
I don't think we need additional code. Please be aware that `forget` (which removes snapshots according to a policy) and `prune` (which removes content that is not referenced any more) are different operations and can be run on different machines and hosts.

The way I imagined using these two commands with a set of servers was:
 * run `restic backup` on a machine, daily
 * regularly (e.g. weekly) remove old snapshots for that machine with `restic forget --hostname foo --keep-last[...]`
 * regularly (e.g. also weekly) have one host run `restic prune`.

That should be enough.

Please let me know if you disagree.
