### ISSUE TITLE
Backup data from sftp.

### ISSUE THREAD

**Issue by painhardcore** [restic/restic#932]
Wanted to automate backups with restic, but didn't found option that can make snapshot from sftp directory.
It's missing?

**Comment by fd0** [comment]
Thanks for creating an issue. Creating backups over sftp is not implemented, and probably never will be. The protocol is not suited for that, at least not in my opinion. I have ideas for running a remote restic instance on a server and pulling the backups from there, for a discussion see #299. I'm going to close this issue for now, feel free to add further comments.

**Comment by zcalusic** [comment]
@painhardcore, you could probably use sshfs to mount remote sftp location as local mount, then proceed with restic backup as usual. Give it a try.
