### ISSUE TITLE
tell me how backups on different hosts on one backup repository works

### ISSUE THREAD

**Issue by rupat** [restic/restic#933]
Note: This is more a question than an error report or issue

So my first question is, are the backups really separated by hosts ?
how restic detects host ?
is there a possibility to set the hostname used for a backup (maybe i mount a filesystem of a virtual machine and want to backup this. than i do not want to use the actual hostname of my system) ?

files backed up separate per host or being referenced as the same "file to backup" on different snapshots ?

Maybe i add a file /etc/issue from Host A to repository xyz.
After this i add the same file from Host B to the same repository xyz.

**Comment by fd0** [comment]
I'm not sure what you mean with hosts that are "separated": restic creates a snapshot of files/dirs at one point in time. Among others, the hostname of the machine running restic is recorded. It can be overridden by using `restic backup --hostname foo`, then the string `foo` is set for that snapshot as the host name.

A snapshot is identified by a unique ID (a hexadecimal string). A snapshot is independent of all other snapshots: This means that a file `/etc/issue` of one host can contain completely different things than the same file of a different host. If they contain the same data, this is only saved once in the repo (that's the deduplication at work). I'd suggest running a few backups and then using the fuse mount (did you already discovered that yet?) to browse around.

If you want to know more about the design of restic (and the repo structures) please have a look at the docs: https://restic.readthedocs.io/en/latest/references.html#design

I'm going to close this issue for now as your questions have been answered, please feel free to add further comments.
