### ISSUE TITLE
SFTP Upload Stops and does not recover

### ISSUE THREAD

**Issue by nob13** [restic/restic#937]
## Output of `restic version`
```
restic 0.5.0 (v0.5.0-0-gf678c97)
compiled with go1.8 on linux/amd64
```

## How did you start restic exactly? (Include the complete command line)
```
./restic_0.5.0_linux_amd64 -r sftp:root@[myserver]:/backups/test backup /media/[longpath] -p restic_password_test.txt 
```

## What backend/server/service did you use?

Ubuntu 14.04.2 Root Server
```
openssh-server                      1:6.6p1-2ubuntu2.8
```

## Expected behavior
Uploads a lot of data (145 GB at 10MBit upload) until the End.

## Actual behavior
Connection breaks at some point, transfer sped is going down, no reaction on Ctrl+C. Have to kill and restart.

Output:
```
root@nas:~/restic# ./restic_0.5.0_linux_amd64 -r sftp:[myserver]:/backups/test backup /media/[longpath] -p restic_password_test.txt 
scan [/media/[longpath]]
scanned 207 directories, 30055 files in 0:01
subprocess ssh: Write failed: Broken pipe / 145.489 GiB  8346 / 30262 items  0 errors  ETA 17:39:47 
unable to refresh lock: cmd.Wait: exit status 25589 GiB  8346 / 30262 items  0 errors  ETA 17:44:42 
  Interrupt received, cleaning up # This is at Ctrl C, but nothing happens, have to kill it.
[11:40:19] 24.73%  898.026 KiB/s  35.986 GiB / 145.489 GiB  8346 / 30262 items  0 errors  ETA 35:30:59 
```

## Steps to reproduce the behavior
Step above.

## Do you have any idea what may have caused this?
It's possible that my ISP cuts the connection each 24h, but I am not sure whether it still does.

**Comment by fd0** [comment]
Hey, thanks for the report. This is actually a known problem (tracked in #353). The sftp process dies (no idea why), the error message is: `subprocess ssh: Write failed: Broken pipe`.

restic should restart the ssh process and resume operations. But this needs to be handled in the architecture, so it's not so easy.

I'm going to close this as a duplicate. Please subscribe to #353 in order to be notified when it's corrected.

**Comment by fd0** [comment]
Ah, please be aware that you can just restart your backup process, and restic will resume uploading data at approximately the point where the connection died the last time. All redundant data is being cleaned up by the next `prune` run.

**Comment by nob13** [comment]
Ok, thanks for the fast reply!
