### ISSUE TITLE
Is there a way to pass the passphrase in a script

### ISSUE THREAD

**Issue by gregf** [restic/restic#939]
Is there any way for me to automate passing the passphrase to my backup script?

I'm migrating from borg and with borg I could do

```
export BORG_PASSPHRASE="my secret"
```

and then borg wouldn't prompt me for it when it ran.

**Comment by fd0** [comment]
Have a look at the manual, there are several ways (one via the environment variable `RESTIC_PASSWORD`, as you've done it for borg): https://restic.readthedocs.io/en/latest/manual.html#initialize-a-repository
