### ISSUE TITLE
Document Use Cases

### ISSUE THREAD

**Issue by fd0** [restic/restic#94]
Create documentation that describes the use cases considered for restic, e.g.:
 * backup directory /foo/bar
 * restore backup to /foo/bar
 * backup file /foo
 * restore file /foo
 * backup stdin (for `mysqldump [...] | restic backup -` or so)
 * output contents of file from backup
...

**Comment by tsenart** [comment]
Hey there! I originally saw your talk at FOSDEM last year. You def. got my attention :-)
I'm currently considering using http://www.haystacksoftware.com/arq/ with something like AWS Glacier or the newer Google Nearline for personal offsite backups. I would, however, love to use a solid open source backup tool for such and I immediately thought of restic. I know things can still be unstable but I'd be willing to contribute over time to get to a better place. Now... I'd like to hear from your own words how does restic compare to Arq in terms of functionality and vision. I think that's a pretty useful write-up to do overall, for everyone else in similar positions as me. Thanks!

**Comment by fd0** [comment]
Hey, thanks for leaving a comment! This issue is mainly meant to track the progress in creating a document that describes the use cases addressed by restic, it hasn't just been written yet. Maybe the example list above is too low level.

I hadn't heard of arq before (there are SO MANY backup systems out there), but had a quick look. It seems, restic and arq share a lot of common ideas, e.g. content addressable storage.

The vision I have for restic is very similar to arq. At the moment, restic lacks many features (which is expected for such an early development version), but also implements deduplication with content defined chunking (CDC), which arq is missing (as far as I can see). Additionally, I haven't seen any checks for authenticity, which restic checks via an HMAC signature.

So, what is your use-case? Backup a bunch of directories from your laptopo to an offsite server every hour?

**Comment by tsenart** [comment]
Yeah that's pretty much my use case. I also want to keep versions over time. Pluggable storage backends is a must too. So far, so good!

**Comment by fd0** [comment]
Then I think restic fits your use case really good, once all the needed features are implemented. The `README.md` also lists the most important design goals.

**Comment by tsenart** [comment]
How can I help?

**Comment by fd0** [comment]
Compile restic (under Linux and darwin), backup some data, report all the bugs, annoyances and suprising things you find. For example, have a look at #90 and backup some really huge directory while running restic through the `xtime` (script linked in #90), in order to determine the maximum memory usage.

**Comment by tsenart** [comment]
:+1:

**Comment by fd0** [comment]
Since it came up in the IRC channel today: Reading backup data from stdin isn't supported yet, neither will workarounds like backing up device files or fifos (restic will backup them as the special files they are, rather than reading from them). I've added #255 to track the implementation.

**Comment by fd0** [comment]
Since we have a manual (written by @bchapuis) this issue is already resolved.
