### ISSUE TITLE
Temporary files not cleaned up

### ISSUE THREAD

**Issue by zcalusic** [restic/restic#948]
## Output of `restic version`

restic 0.5.0 (v0.5.0-152-g0f057bd)
compiled with go1.8.1 on linux/amd64

## How did you start restic exactly? (Include the complete command line)

backup restic /ext/folder

## What backend/server/service did you use?

Local

## Expected behavior

After pressing ctrl-C, and seeing "Interrupt received, cleaning up" message, all temporary files cleaned up.

## Actual behavior

ls -al /tmp/restic*
-rw-------  1 root     root  4282188 May  7 14:51 restic-temp-pack-039388186
-rw-------  1 root     root  4362550 May  7 14:51 restic-temp-pack-062900235
-rw-------  1 root     root  4341030 May  7 14:51 restic-temp-pack-289160167
-rw-------  1 root     root  1984480 May  7 14:51 restic-temp-pack-324310133
-rw-------  1 root     root  4268231 May  7 14:51 restic-temp-pack-357860846
-rw-------  1 root     root  4236711 May  7 14:51 restic-temp-pack-463911725
-rw-------  1 root     root  4730190 May  7 14:51 restic-temp-pack-522590086
-rw-------  1 root     root  4604023 May  7 14:51 restic-temp-pack-792933041
-rw-------  1 root     root  4335230 May  7 14:51 restic-temp-pack-881845928
-rw-------  1 root     root  4723215 May  7 14:51 restic-temp-pack-914300980
-rw-------  1 root     root  4389711 May  7 14:51 restic-temp-pack-923045980

## Steps to reproduce the behavior

Start backup, then interrupt it.

## Do you have any idea what may have caused this?

Not really. Seems like a minor bug.

**Comment by middelink** [comment]
/tmp is normally cleaned by some awesome cronjob running on your linux machine.

That said, (and taken into account the number of people complaining about it), perhaps it is time to investigate if we can pass the pack filehandle around and delete the file right after opening once?

**Comment by fd0** [comment]
Good point, I think we can already do that!

**Comment by fd0** [comment]
Ah, that doesn't work cross-platform, meh.

**Comment by fd0** [comment]
Let's see what the CI tests think about this change.

**Comment by fd0** [comment]
Yeah, Windows doesn't like it: https://ci.appveyor.com/project/fd0/restic/build/1601-master
