### ISSUE TITLE
Allow backup of block devices

### ISSUE THREAD

**Issue by zcalusic** [restic/restic#949]
@fd0, how do you feel about adding a feature to restic to allow backing up block devices? Not unlike what rsync provides with --copy-devices argument (https://lists.samba.org/archive/rsync/2010-June/025164.html).

The relevant case: virtualized Windows OS setup on physical partitions. Tried mounting partitions as NTFS, backed up content with restic, then restored on freshly created NTFS filesystems. While the whole process went well, there's no ntfsfixboot or similar in the world that can make such recovered partition bootable again. Unfortunately, when it comes to Windows, the only way that ever worked for me is to backup the whole partition.

N.B. Until this feature is available, there's a slick workaround using https://github.com/jimparis/diskfile which allows mounting block devices as regular files (that's exactly the opposite of what loop driver does!). Of course, it would be nicer to have this feature built right into restic, so there's no need to do FUSE magic/translation just to backup block devices. And it would be more efficient.

**Comment by fd0** [comment]
Hm, can't you do that easily by chaining restic and dd together like this:
```shell
$ dd if=/dev/sda1 | restic backup --stdin --stdin-filename sda1
```

**Comment by zcalusic** [comment]
Huh, so simple?!  :+1: Somehow I forgot about --stdin, or at least that it would be really helpful for this case. Yeah, it definitely works and is plenty fast. Thanks for the hint.

Now, I wonder how to restore such a file, I suppose restore --stdout would come handy eventually (and be nicely symmetrical with backup --stdin). Until that time, I guess fuse mount could be used...

**Comment by fd0** [comment]
So, we just need a way to write files from a snapshot to stdout. I feel that this doesn't really belong to the `restore` command, maybe add a `cat` command?

**Comment by zcalusic** [comment]
Sure. Whatever can help the case.

**Comment by zcalusic** [comment]
In the meantime, I did a test restore via FUSE mount, and it worked flawlessly! Every single bit was restored properly from this quite large 80GB file (took exactly 6 hours). Which is really great, because that is my only backup of that data. I'm trusting restic more and more every day. :)

I still remember when such large files were impossible to restore via FUSE mount, due to OOM-ing machine and so, nowadays that works very well.

If you ask me, additional method to 'cat' file from repo would still be handy, but you can set the lowest of low priorities to this feature, as long as FUSE mount continues to cover this case nicely. :)

**Comment by fd0** [comment]
Yeah, this is caused by #746.

**Comment by zcalusic** [comment]
Thanks to @fawick work in #1346 this can be closed, now.
