### ISSUE TITLE
sftp backends timeouts quietly

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#954]
Using version 0.5.0, with the SFTP backend, a very clunky wifi connection and very slow dsl, I get frequent timeouts. Sometimes (after a "short" timeout) restic gets back to work, sometimes (after a "long" timeout) it continues to run, but does not backup anything anymore... Would it be possible to resume to backup without restarting restic, or at least fail with an error message mentioning a timeout issue?

**Comment by fd0** [comment]
Thanks for opening this issue. I see that you haven't filled out the issue template, is there a reason for that? If not, please fill out the issue template now, you can find the text [here](https://github.com/restic/restic/blob/master/.github/ISSUE_TEMPLATE.md).

It sounds like your ssh connection died, you should've seen the error message from the ssh client. Adding generic reconnection logic is tracked in #415.

I'm going to close this issue for now, it may be reopened when we have enough information to debug the problem.

**Comment by legrostdg** [comment]
Sorry about this, there was no error message from the ssh client, so it seemed like I had nothing interesting to provide. restic just seemed to run like before, but without backing up anything anymore.

## Output of `restic version`

    $ restic version
    restic 0.5.0
    compiled with go1.7.4 on linux/amd64

## How did you start restic exactly? (Include the complete command line)

    $ restic -r sftp:user@myserver:/backup/laptop.restic --password-file password.txt --one-file-system --exclude=/var/cache --exclude=/var/tmp --exclude=/home/user/tmp --exclude=/home/user/.cache backup / /var /usr /home /boot /boot/efi

## What backend/server/service did you use?

sftp

## Expected behavior

complete backup

## Actual behavior

restic runs like before (without any errors) but does not backup anything anymore

## Steps to reproduce the behavior

not sure

## Do you have any idea what may have caused this?

ssh timeout?

**Comment by fd0** [comment]
Could you please create a debug log (instructions [here](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs), and see if you can reproduce the problem? Then have a look at the debug log, maybe post the last ~100 lines or so. Please be aware that the debug log may contain sensitive things, so be sure to remove them before posting.
