### ISSUE TITLE
[FEATURE] print state of repo

### ISSUE THREAD

**Issue by unclesamwk** [restic/restic#955]
Hey Alex,

very nice restic.

I've a feature request.

restic -r path state now ...

... prints informations like:
-> Backup now in progress,finished, error, failed,...
-> Size of repos, deplucation sizes
-> count of files,dir per repo
-> start time of backup und finished timestamp for repos

all output in json

:-)

greetings
Sam

**Comment by fd0** [comment]
Hey, thanks for opening an issue. The hypothetical `state` command you're imagining seems to print out a lot of different information, and I have the feeling that this is too diffuse.

Could you describe your use case? What is it that you'd like to know about your repo? Most of the information you've mentioned we either don't have readily available (e.g. the duplication ratio), or are simply not aware of (e.g. running backups, failed backups).

So I'm going to close this issue for now, as the description is too vague. Please feel free to add comments and answer my questions, I'd like to find out what data you're after. Thanks!
