### ISSUE TITLE
Go version requirement

### ISSUE THREAD

**Issue by sellibitze** [restic/restic#96]
The README says, I need go version 1.2.x to build it. I just installed "go version go1.2.1 linux/amd64" and I get the following error:

```
src/github.com/restic/restic/backend/id.go:17: undefined: sync.Pool
```

I'm guessing Pool has been added to a more recent go version?

Anyhow, I saw your CCCAC talk via media.ccc.de today: Well done!

**Comment by fd0** [comment]
Thanks for opening this issue. `sync.Pool` has indeed been added in Go 1.3, so that's the minimum requirement.

**Comment by fd0** [comment]
The `README.md` file has been updated in 1516cb5996ed37a1b304d1ecbbc2535509cfd356.
