### ISSUE TITLE
PKGBUILD broken

### ISSUE THREAD

**Issue by messju** [restic/restic#963]
The doc/PKGBUILD wants to install  "$pkgname/README.md", but the README is named "README.rst".

The causes makepgk to errror:
install: cannot stat 'restic-git/README.md': No such file or directory

The fix is trivial: Just change "$pkgname/README.md" to "$pkgname/README.rst".

**Comment by fd0** [comment]
Thank you very much for raising this issue. There's the `restic-git` package in AUR which is independently maintained... so I'd suggest removing `doc/PKGBUILD`, and I've already contacted the AUR maintainer. What do you think? Is it valuable to have a copy of the `PKGBUILD` here?

**Comment by messju** [comment]
I first reported this at https://aur.archlinux.org/packages/restic-git/ , but then i found the doc/PKGBUILD fixed it there and made pkgbuild happy. So I thought here would be a more appropiate place to report this. But on second thought I think it's less confusing to have only one PKGBUILD and that should be in the aur git repo.

(For example the yaourt tool asked me to edit PKGBUILD to fix the build, but after doing this, yaourt ignored my changes and took the PKGBUILD from the restic git repo instead. I'm pretty sure this confusion comes from the doc/PKGBUILD from restic, so I'd vote for removing it, but I am no export on aur or yaourt.)

**Comment by fd0** [comment]
Agreed, I'll remove it. Thanks!
