### ISSUE TITLE
panic: store new item in finalized index

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#969]
## Output of `restic version`

    $ restic version
    restic 0.5.0
    compiled with go1.7.4 on linux/amd64

## How did you start restic exactly? (Include the complete command line)

    $ restic -r sftp:user@myserver:/backup/laptop.restic --password-file password.txt --one-file-system --exclude=/var/cache --exclude=/var/tmp --exclude=/home/user/tmp --exclude=/home/user/.cache backup / /var /usr /home /boot /boot/efi

## What backend/server/service did you use?

sftp

## Expected behavior

success

## Actual behavior

    scan [/ /var /usr /home /boot /boot/efi]
    [2:45] 375041 directories, 4248360 files, 202.878 GiB     <- side note: there should only be around 100GiB there, 202.878 GiB is the side including excluded dirs.
    scanned 375041 directories, 4248360 files in 2:45
    [41:55:30] 29.55%  416.470 KiB/s error for
    /home/user/mail/.INBOX.debian/cur/1494922886.M787921P6408.capeo,S=6890,W=7016:2,: lstat
    /home/user/mail/.INBOX.debian/cur/1494922886.M787921P6408.capeo,S=6890,W=7016:2,: no such file or directory
    error for home/user/mail/.INBOX.debian/cur/1494925411.M427233P6408.capeo,S=5451,W=5562:2,: Lstat:
    lstat /home/user/mail/.INBOX.debian/cur/1494925411.M427233P6408.capeo,S=5451,W=5562:2,: no such file or directory
    ^[[2K^Mwarning for /tmp/restic-temp-pack-932020790: file has changed
    warning for /tmp/restic-temp-pack-932020790: expected 3125275 bytes, saved 3126386 bytes
    panic: store new item in finalized index
    goroutine 1832138 [running]:
    panic(0x856540, 0xc42f8bb9d0)
            /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
    restic/repository.(*Index).Store(0xc43461ea80, 0x2, 0x379, 0x48bd354a59a24ddc, 0xb1f62d03f2e8b75c, 0xc06fc2c419b30175, 0x382d2ef85d14ff10, 0x0, 0x9d34d89fbb123036, 0xfc3a75bd72bd7429, ...)
            /build/restic-8CTil3/restic-0.5.0/src/restic/repository/index.go:102 +0x459
    restic/repository.(*MasterIndex).Store(0xc42016e450, 0x2, 0x379, 0x48bd354a59a24ddc, 0xb1f62d03f2e8b75c, 0xc06fc2c419b30175, 0x382d2ef85d14ff10, 0x0, 0x9d34d89fbb123036, 0xfc3a75bd72bd7429, ...)
            /build/restic-8CTil3/restic-0.5.0/src/restic/repository/master_index.go:126 +0x2ab
    restic/repository.(*Repository).savePacker(0xc42006ede0, 0xc431965920, 0x2da36cd10c44d545, 0x8e80fa9321ae71f6)
            /build/restic-8CTil3/restic-0.5.0/src/restic/repository/packer_manager.go:151 +0x6d4
    restic/repository.(*Repository).SaveAndEncrypt(0xc42006ede0, 0xc436d4bc01, 0xc45d3e4000, 0x80921, 0x13a000, 0xc436d4bcf0, 0x0, 0x0, 0x0, 0x0, ...)
            /build/restic-8CTil3/restic-0.5.0/src/restic/repository/repository.go:202 +0x421
    restic/repository.(*Repository).SaveBlob(0xc42006ede0, 0x45eb7259d8ba8801, 0xc45d3e4000, 0x80921, 0x13a000, 0x45eb7259d8ba889e, 0xf62da36cd10c44d5, 0xac8e80fa9321ae71, 0x1a63809266adab6a, 0x0, ...)
            /build/restic-8CTil3/restic-0.5.0/src/restic/repository/repository.go:528 +0x16b
    restic/archiver.(*Archiver).Save(0xc436ca0230, 0x80901, 0xc45d3e4000, 0x80921, 0x13a000, 0x45eb7259d8ba889e, 0xf62da36cd10c44d5, 0xac8e80fa9321ae71, 0x1a63809266adab6a, 0x8c71acbb4ab47dc9, ...)
            /build/restic-8CTil3/restic-0.5.0/src/restic/archiver/archiver.go:103 +0x222
    restic/archiver.(*Archiver).saveChunk(0xc436ca0230, 0x538d75fe, 0x80921, 0x0, 0xc45d3e4000, 0x80921, 0x13a000, 0xc440a9c2c0, 0xb08d00, 0xc45e510010, ...)
            /build/restic-8CTil3/restic-0.5.0/src/restic/archiver/archiver.go:160 +0x118
    created by restic/archiver.(*Archiver).SaveFile
            /build/restic-8CTil3/restic-0.5.0/src/restic/archiver/archiver.go:237 +0x39c
     59.946 GiB / 202.878 GiB  2006383 / 4623401 items  1 errors  ETA 99:57:49
    [41:55:40] 29.55%  416.441 KiB/s  59.946 GiB / 202.878 GiB  2006383 / 4623401 items  1 errors  ETA 99:58:14

## Steps to reproduce the behavior

not sure

## Do you have any idea what may have caused this?

seems to be a change in a file

**Comment by fd0** [comment]
Huh, this is odd, thanks for the report! I thought I had resolved all issues with finalized indexes...

**Comment by fd0** [comment]
So preliminary analysis: `/tmp/` is included in the backup, that's where restic leaves temporary files. It then happened that a temp file it was currently writing was to be saved, and that caused the whole mess. Interesting :)

**Comment by fd0** [comment]
This is mitigated in the master branch, tempfiles are removed directly after creation. So I'm going to close this issue for now. Please feel free to add further comments.
