### ISSUE TITLE
Add type to map

### ISSUE THREAD

**Issue by fd0** [restic/restic#97]
At the moment, each Tree object holds a Map for all blobs used within the tree. This Map doesn't distinguish between subtree blobs and data blobs. Change the Map code to track what type of object is meant (e.g. "tree", "data", ...).

**Comment by fw42** [comment]
Why? What problem would this solve?

**Comment by fd0** [comment]
This is changed right now (not yet ready for pushing it to the repo) for #56, this issue is obsolete afterwards I guess.

Then underlying problem is that I'd like to distinguish data and meta information about this data on the repository level, so that commands like fsck can easily find all the blobs that are trees, for example. At the moment, this isn't really represented in the map in a tree, but I think that's not strictly necessary.

We'll see if this is needed at all once #56 is done.

**Comment by fd0** [comment]
This is solved in #56, packs contain a type field for each blob. Closed.
