### ISSUE TITLE
ListDir is lacking information to differ original directory

### ISSUE THREAD

**Issue by dirk777** [restic/restic#972]
## Output of `restic version`
restic 0.5.0
compiled with go1.8 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)
restic -r sftp:id......aP8 ls fee5d774 --long

## What backend/server/service did you use?
sftp

## Expected behavior
snapshot fee5d774 of [/tmp/myDocuments/Backup /tmp/yourDocuments/Backup] at 2017-05-04 19:40:08.173763197 +0200 CEST):
drwxr-xr-x   501    20      0 2017-04-26 14:39:43 /tmp/myDocuments/Backup
....
drwxr-xr-x   501    20      0 2017-05-02 11:32:27 /tmp/yourDocuments/Backup
....

## Actual behavior
snapshot fee5d774 of [/tmp/myDocuments/Backup /tmp/yourDocuments/Backup] at 2017-05-04 19:40:08.173763197 +0200 CEST):
drwxr-xr-x   501    20      0 2017-04-26 14:39:43 /Backup
....
drwxr-xr-x   501    20      0 2017-05-02 11:32:27 /Backup
....

## Steps to reproduce the behavior
just take two directories where the last path component is equal

## Do you have any idea what may have caused this?

Please provide full information of original path when using listdir. 

Another small improvement could be to replace whitespace as delimiter of pathes within the square brackets in output line. It is not possible to determine the right path if a a directory has a whitespace
 
Last but not least, it seems that the output is also lacking of a beginning bracket before timezone will stated. The closing one is printed after timezone.

**Comment by fd0** [comment]
Hey, thanks for the report. This is caused by the archiving code, which only uses the last path component for storing things within the repo. It is already known and tracked as #549.
