### ISSUE TITLE
restic_0.6.0-rc.1_linux_amd64 is not bz2'd

### ISSUE THREAD

**Issue by lloeki** [restic/restic#980]
## Output of `restic version`

N/A

## How did you start restic exactly? (Include the complete command line)

N/A

## What backend/server/service did you use?

N/A

## Expected behavior

`restic_0.6.0-rc.1_linux_amd64.bz2` should be available.

## Actual behavior

`restic_0.6.0-rc.1_linux_amd64` is available instead, which required special casing adjustments in provisioning scripts.

## Steps to reproduce the behavior

- go to [release v0.6.0-rc.1](https://github.com/restic/restic/releases/tag/v0.6.0-rc.1#Downloads)
- look for `restic_0.6.0-rc.1_linux_amd64.bz2`

## Do you have any idea what may have caused this?

 Manual release process?

**Comment by fd0** [comment]
Heh, you're right, nice catch! I've uploaded the missing binary.

**Comment by lloeki** [comment]
Hmm @fd0 you just uploaded `restic_0.5.0_linux_amd64.bz2` :D

**Comment by fd0** [comment]
Crap.

**Comment by fd0** [comment]
Fixed now.

**Comment by lloeki** [comment]
Thanks!
