### ISSUE TITLE
"restic check" with rest-backend is using up too many fd's on rest-server.

### ISSUE THREAD

**Issue by middelink** [restic/restic#985]
## Output of `restic version`
```console
$ restic version
restic 0.6.0-rc.1 (v0.6.0-rc.1-13-ge7f031c)
compiled with go1.8.3 on linux/amd64
```

## How did you start restic exactly? (Include the complete command line)
```console
/usr/local/sbin/restic -r rest:http://qnap.ch.polyware.nl:8000 check
```

## What backend/server/service did you use?
rest
version 0.9.1

## Expected behavior
no complaints about using too many file descriptors.

## Actual behavior
Among other output:
```console
  client.Do: Get 
http://qnap.ch.polyware.nl:8000/data/0f05fa962f1afb155afece9fe16f46661f3286d1b93edf6ee511fd10c1621ddc: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: connect: cannot assign requested address
error for tree 97c78ddd:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/26173a38e51153726034605a690f0d8aab2892600ca478f92c3240d9e5f6df86: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: connect: cannot assign requested address
```

Looking at the open fd's at the time:
And checking ls /proc/$(pgrep restic)/fd | wc -l I see spikes in the 1000's of fd's... (coming and going btw)
```console
[middelin@bigbox ~]$ ls -l /proc/$(pgrep restic)/fd | wc -l
976
[middelin@bigbox ~]$ ls -l /proc/$(pgrep restic)/fd | wc -l
1018
[middelin@bigbox ~]$ ls -l /proc/$(pgrep restic)/fd | wc -l
ls: cannot access /proc/16692/fd/992: No such file or directory
ls: cannot access /proc/16692/fd/993: No such file or directory
ls: cannot access /proc/16692/fd/995: No such file or directory
ls: cannot access /proc/16692/fd/1017: No such file or directory
1024
```

## Steps to reproduce the behavior
Run `restic check` over a rest backend?

## Do you have any idea what may have caused this?
Guess it's time for an http/2 implementation of rest-server's front and backend, so we can mux all requests over a single tcp socket... :(

**Comment by fd0** [comment]
Huh, that's odd, I'll have a look. The rest-server and the rest backend already use http2 if available, no need to change anything. Just give the server a TLS certificate and use a HTTPS URL for restic and it'll work.

**Comment by middelink** [comment]
To clarify, I do not have a cert on my rest server, so indeed it won't promote the connection up to HTTP/2.

**Comment by fd0** [comment]
Hm, but isn't that a requirement for HTTP2? As far as I know there is a way to speak HTTTP2 via plain TCP without TLS, but it isn't implemented in either Browsers nor servers...

**Comment by zcalusic** [comment]
I tried to reproduce this weird bug, but I couldn't. Restic check on a pretty heavy repo through REST backend worked just fine, using only 5 fd's at all times.

Admiteddly, I do have certs in place, so it's not exactly the same, but there's nothing preventing regular keepalive HTTP/1.1 connections even if you're using plain HTTP. At least I think I nailed all the bugs last time I spent hours debugging issues like this.

Please double/triple check that you're really using the recent versions of both restic client and rest-server. 'Cause the errors you see remind me of some ancient versions behaviour...

Also you can turn on debugging in both apps and check if anything suspicious is going on. It might be a strange corner case where you have some trivial problem on one side (say rest-server) which then propagates to the other side (restic client out of fd).

**Comment by middelink** [comment]
Pretty sure:

```console
[local box]$ restic version
restic 0.6.0 (v0.6.0-19-g4dbbc24-dirty)
compiled with go1.8.3 on linux/amd64
```
```console
[storage box]$ ./rest-server 
rest-server 0.9.1 (954686c) compiled with go1.8.3 on linux/amd64
Data directory: /tmp/restic
Authentication disabled
Starting server on :8000
^C
```
And, whilst running `restic check` on the a newly rebuild-index'ed repo:
```console
$ ls -l /proc/$(pgrep restic)/fd | grep socket: | wc -l
547
$ ls -l /proc/$(pgrep restic)/fd | grep socket: | wc -l
180
$ ls -l /proc/$(pgrep restic)/fd | grep socket: | wc -l
105
$ ls -l /proc/$(pgrep restic)/fd | grep socket: | wc -l
172
$ ls -l /proc/$(pgrep restic)/fd | grep socket: | wc -l
1011
```

So, definitely more than 5 sockets.

**Comment by middelink** [comment]
Just noticed something else, there are 2 error msgs, first cannot assign, then running out of sockets.

```console
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/cd40fcee5db5b42cb4c49a98708b611bc2a714e09cf90c7e58ea4742958ea440: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: connect: cannot assign requested address
error for tree f359722b:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/cd40fcee5db5b42cb4c49a98708b611bc2a714e09cf90c7e58ea4742958ea440: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: connect: cannot assign requested address
error for tree 22583211:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/05d28966f0ac21eabffeaeae4b0a11ff9bab290278f4d484352e621cba97c5f3: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: connect: cannot assign requested address
error for tree c4d77e3d:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/cd40fcee5db5b42cb4c49a98708b611bc2a714e09cf90c7e58ea4742958ea440: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: connect: cannot assign requested address
error for tree 478ee3dd:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/ff8e9c22e4fc332a5de1478dcb90630602ee5f875990ea7fd4bda16395dd766e: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: connect: cannot assign requested address
error for tree 2e3429b3:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/cd40fcee5db5b42cb4c49a98708b611bc2a714e09cf90c7e58ea4742958ea440: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: connect: cannot assign requested address
error for tree 15a49fe1:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/8a2ac4b953f28024bae7c199727daf2a74836a99b8c1da929c82d85f798baf31: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: socket: too many open files
error for tree f65d6422:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/609c046fc49c9ffbae001aa49401db05ba63919d41f34cf5195992f0df9bac73: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: socket: too many open files
error for tree e4f59878:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/609c046fc49c9ffbae001aa49401db05ba63919d41f34cf5195992f0df9bac73: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: socket: too many open files
error for tree f4fb9e1f:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/8a2ac4b953f28024bae7c199727daf2a74836a99b8c1da929c82d85f798baf31: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: socket: too many open files
error for tree dde46561:
  client.Do: Get http://qnap.ch.polyware.nl:8000/data/8a2ac4b953f28024bae7c199727daf2a74836a99b8c1da929c82d85f798baf31: dial tcp [2a02:168:5204:0:265e:beff:fe0f:5327]:8000: socket: too many open files
```

**Comment by zcalusic** [comment]
Do netstat -tn | grep TIME_WAIT on the restic client side and see what comes out. If you have loads of connections to rest-server host in TIME_WAIT state, it means restic is not using keepalive connections and Linux kernel can't recycle previously closed sockets fast enough, so it soon runs out of available sockets to use.

**Comment by fd0** [comment]
@zcalusic can you please try again with `GODEBUG=h2client=0` (which disables http2)?

**Comment by middelink** [comment]
In a few seconds after "Check all packs", I see
```console
$ netstat -nt | grep TIME | wc -l
9928
$ netstat -nt | grep TIME | wc -l
12876
```

And by the time it goes into fail mode, it's up to 40k sockets lingering. I think you're making my poor qnap cry ^^

**Comment by zcalusic** [comment]
Tested with GODEBUG=h2client=0 and it also went fine. There was only one TCP connection open to the rest-server the whole time, and all requests went through it. As I already said, HTTP/1.1 is enough to have proper keepalive connections.

@middelink, could it be that qnap is doing something weird, has some kind of firewall which blocks keepalive connections?

**Comment by middelink** [comment]
@zcalusic, No firewall whatsoever. And I'm just running the native x86_64 binary compiled on the desktop, nothing fancy. Granted, it's just a 4 core Celeron N3160 @1.6Ghz, but that should be enough, right?

**Comment by middelink** [comment]
Ok, weirder. There is still a large queue of lingering sockets, 53K as we speak, but I do not get errors on the `restic check`. I seems like the debugging slows it down just enough for whatever is being obnoxious to cope with the influx.

Is there anything in the restic-debug.log to indicate it creates new connections? The only http related things I see are:
```console
2017/05/31 15:56:23 restic/main.go:59   main.main       1       main []string{"./restic", "-r", "rest:http://qnap.ch.polyware.nl
:8000", "check"}
2017/05/31 15:56:23 restic/global.go:374        main.open       1       parsing location rest:http://qnap.ch.polyware.nl:8000
2017/05/31 15:56:23 restic/global.go:365        main.parseConfig        1       opening rest repository at rest.Config{URL:(*url
.URL)(0xc4201ea600)}
2017/05/31 15:56:23 debug/round_tripper_debug.go:74     debug.loggingRoundTripper.RoundTrip     1       ------------  HTTP REQUE
ST -----------
HEAD /config HTTP/1.1
Host: qnap.ch.polyware.nl:8000
User-Agent: Go-http-client/1.1


2017/05/31 15:56:23 debug/round_tripper_debug.go:87     debug.loggingRoundTripper.RoundTrip     1       ------------  HTTP RESPO
NSE ----------
HTTP/1.1 200 OK
Content-Length: 155
Content-Type: text/plain; charset=utf-8
Date: Wed, 31 May 2017 13:56:25 GMT


...
2017/05/31 16:00:27 rest/rest.go:141    rest.(*restBackend).Load        147997  Load <data/f14d7b8027>, length 1300, offset 2896057
2017/05/31 16:00:27 rest/rest.go:164    rest.(*restBackend).Load        147997  Load(<data/f14d7b8027>) send range bytes=2896057-2897356
2017/05/31 16:00:27 debug/round_tripper_debug.go:74     debug.loggingRoundTripper.RoundTrip     147997  ------------  HTTP REQUEST -----------
GET /data/f14d7b8027b391c998dd13b9e6bc6d962cbce92cf17e81e2641ecc64282d4b3d HTTP/1.1
Host: qnap.ch.polyware.nl:8000
User-Agent: Go-http-client/1.1
Range: bytes=2896057-2897356


2017/05/31 16:00:27 debug/round_tripper_debug.go:74     debug.loggingRoundTripper.RoundTrip     148027  ------------  HTTP REQUEST -----------
GET /data/f14d7b8027b391c998dd13b9e6bc6d962cbce92cf17e81e2641ecc64282d4b3d HTTP/1.1
Host: qnap.ch.polyware.nl:8000
User-Agent: Go-http-client/1.1
Range: bytes=2884902-2885362


2017/05/31 16:00:27 checker/checker.go:361      checker.loadTreeWorker.func1    147975  exiting
...
```

**Comment by middelink** [comment]
I gave in and installed a certificate on the qnap rest-server (don't like it, it's on my own LAN and carries already encrypted data!) however, that seem to have cured the issue. I do have multiple open connections with the rest-server ~90, but they are slowly growing, ~1 connection per second.

However, given the fact that running under debug mode also seemed to slow things down enough to keep running, I wonder if tls is just enough of a performance to do the same.

**Comment by zcalusic** [comment]
The only other difference I see is that you're using IPv6. Could it be that Go HTTP library has issues with keepalives when using IPv6?

**Comment by fd0** [comment]
@middelink can you try again with HTTP2 disabled?

**Comment by fd0** [comment]
I can reproduce the problem locally, at least partly: REST server via IPv4 without TLS.

**Comment by fd0** [comment]
It's my fault, I accidentally remove MaxIdleConnsPerHost in a963052d64c953e15bea42671d366a3eadd5b91c. See #986 for a fix.

**Comment by middelink** [comment]
@zcalusic, I'm completely puzzled as to why it was working for you then...

I can confirm IPv6, IPv4 now work without TLS and IPv6 works with TLS (unable to test IPv4 with TLS as rest:https://192.168.x.y:8000 fails on missing IP SAN in cert)

**Comment by fd0** [comment]
@middelink I suspect that with HTTP2 (via TLS), there's only one or two connections because of the stream multiplexing and there's no need for restic to open more. I don't know why you saw more than one connection with TLS though.

**Comment by zcalusic** [comment]
@middelink, I'm a bit puzzled, too. There are still some pecularities about Go HTTP library that we're yet to discover, I guess. :)

@fd0, you forgot that I tested with HTTP2 turned off, and it still worked well.

**Comment by fd0** [comment]
Ah, you're right. That's obscure indeed.
