### ISSUE TITLE
The find command hangs on backups > 5GB

### ISSUE THREAD

**Issue by yhafri** [restic/restic#989]
## Output of `restic version`

`any`

## How did you start restic exactly? (Include the complete command line)

`$ restic find  901705242.zip  --json`

## What backend/server/service did you use?

`Minio`

## Actual behavior

*restic* hangs forever.

## Do you have any idea what may have caused this?

Is the search feature dependent on the size of the backups?
And how one can debug what's going on?

**Comment by fd0** [comment]
Please fill out the issue template when opening issues, this includes the version number.

`find` probably doesn't hang forever, it's just busy traversing all the tree structures of all snapshots. You can  create a [debug logfile](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs) to see what's going on. Please be aware that it may contain sensitive data such as file and directory names.

**Comment by yhafri** [comment]
Here's the debug-log with restic version `0.6.1` (sensitive data were altered).

[restic-debug.log.gz](https://github.com/restic/restic/files/1049559/restic-debug.log.gz)

**Comment by fd0** [comment]
Hm, it keeps loading the same tree over and over again:

```
$ zgrep 'load tree ac08ce34' restic-debug.log.gz | wc -l
16535
```

Could you dump this tree please, so we can have a look at what it is? First, find the complete tree ID:
```
$ restic list blobs | grep 'tree ac08ce34'
```

Then dump the tree with: `restic cat blob <ID>`. Let's see what that is all about.

I have a hunch: Do you maybe have many empty directories?

**Comment by yhafri** [comment]
@fd0 here you're:

```
./restic-debug list blobs | grep 'tree ac08ce34'

debug enabled
tree ac08ce34ba4f8123618661bef2425f7028ffb9ac740578a3ee88684d2523fee8
```

Then:
```
./restic-debug cat blob ac08ce34ba4f8123618661bef2425f7028ffb9ac740578a3ee88684d2523fee8

debug enabled
{"nodes":[]}
```

And the directory isn't empty as you can see:
```
$ du -hs 1132motionsrv
5,4G   1132motionsrv
```

**Comment by yhafri** [comment]
I've the feeling that the `search feature` is broken.

**Comment by fd0** [comment]
It is not broken, just very slow in your case.

I didn't mean to imply that the directory itself is empty (it clearly is not), but rather that it contains many directories that are empty (about 16k). Is that possible? You can check with: `find 1132motionsrv -type d -empty | wc -l`.

**Comment by yhafri** [comment]
```
$ find 1132motionsrv -type d -empty | wc -l
0
```

**Comment by fd0** [comment]
Huh, that's very odd. I think this is a bug.

**Comment by yhafri** [comment]
Just tried with `restic 0.5.0`, same result :-(
Hope this helps.

**Comment by fd0** [comment]
Hm, I had a second look at the debug log you supplied, the directory `ADDADATA` was recorded as being empty, could you maybe have a look what's in there? Do they contain files that have been excluded in the backup?

**Comment by fd0** [comment]
Could you please try the code in the branch `improve-search-performance` (see #993)? It will reduce the number of backend requests in your case A LOT!

**Comment by yhafri** [comment]
Awesome @fd0 it works :-)
Can you please merge this fix with `0.6.1` ?

**Comment by fd0** [comment]
I will merge it into master so it will be included in the next release. It should be safe to use the master branch.

**Comment by fd0** [comment]
If you want you can download the 0.6.1 release, and apply the PR as a patch, https://github.com/restic/restic/pull/993.diff
