### ISSUE TITLE
Add seed to chunker

### ISSUE THREAD

**Issue by fd0** [restic/restic#99]
If attackers are able to observe the repository, they are able to recognize blobs based on the size. For example, an attacker could build a list of chunks for files and search for these chunks (based on their size) in the repository. This leaks information.

Add a repository-specific seed to the chunker so that split-points are unique per repository. Eventually combine this with #56.

**Comment by scoddy** [comment]
Seed should be crypted in the key object store

**Comment by fd0** [comment]
At the moment the chunker uses a hardcoded polynomial for the rabin fingerprints. This will be changed and a new polynomial of degree 53 will be generated for each repository.  There are (2^53-2/53) = 169947155749830 different irreducible polinomials of degree 53. The polynomial will be stored within the encrypted datat in the key files.

**Comment by fd0** [comment]
This has been added in b2307cafa2a1fda8e77f361fa2a5b2a0148ca833.
