### ISSUE TITLE
unused github.com/minio/go-homedir dep?

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#995]
You seem to have added github.com/minio/go-homedir to vendor/, but it does not seem to be used. Is there a reason for this that I missed?

**Comment by ibib** [comment]
It is used in [mini-go](https://github.com/restic/restic/blob/22a6cd3a268819d00f6fa9886e40d0330631afc6/vendor/src/github.com/minio/minio-go/pkg/credentials/file_minio_client.go#L27) which is used as S3-Client.

**Comment by legrostdg** [comment]
Woops! OK, thanks!
